UI/window-basic-auto-config-test.cpp, libobs/CMakeLists.txt, libobs/audio-monitoring/win32/wasapi-output.c, libobs/media-io/audio-io.c, libobs/media-io/audio-io.h, libobs/media-io/video-io.c, libobs/obs-audio.c, libobs/obs-encoder.c, libobs/obs-output.c, libobs/obs-scene.c, libobs/obs-source-transition.c, libobs/obs-source.c, libobs/util/util_uint64.h, plugins/decklink/decklink-device-instance.cpp, plugins/decklink/decklink-output.cpp, plugins/linux-alsa/alsa-input.c, plugins/linux-pulseaudio/pulse-input.c, plugins/obs-filters/async-delay-filter.c, plugins/obs-filters/gpu-delay.c, plugins/win-capture/game-capture.c, plugins/win-wasapi/win-wasapi.cpp, test/test-input/sync-pair-aud.c
obs-studio use the monotonic clock in nanoseconds internally.
When scaling this value using a 32-bit fraction, the code in obs-studio will cast the values to uint64_t which can lead to numerical overflow and sometimes uint128_t which works, but can be optimised. For example in audio_frames_to_ns():
```
util_uint128_t val;
val = util_mul64_64(frames, 1000000000ULL);
val = util_div128_32(val, (uint32_t)sample_rate);
return val.low;
```
The code above uses a bunch of multiplications and divisions, which it doesn't have to do, because the fraction we are scaling with fits into 32-bits. Instead use:
`     return util_mul_div64(frames, 1000000000ULL, sample_rate);`
The way this function works is by first computing the floor value, and then adding the remaining error. Because the divisor fits …
=> libobs: Implement and use better scaling function for 64-bit integers

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss
The files on disk are lowercase whereas the qss was refrencing them in upper case. This is hidden on Windows due to the platform's case insensitivity, But would cause error messages and the icons not to render on case sensitive file systems like Linux's ext4 and Mac's HFS, and APFS*. It would be preferable if we could format check the theme files to ensure that they match the case on disk.
\* Depending on how the user has configured it
Error messages and missing icons
Launching it on an archlinux running machine
uname -a
```
Linux 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux
```
=> UI: Theme case fix

UI/window-basic-main.cpp, UI/window-basic-settings.cpp
Sets the minimum selectable resolution via the UI to 8 x 8.
Resolutions lower than 8 x 8 can get rounded down to 0 by libobs, causing video initialization failure with easy no way for the user to fix it ([example](https://obsproject.com/forum/threads/failed-to-initialize-video-invalid-parameters.123019/)).
Tried entering lower resolutions via UI and .ini. Ensured OBS continued to enforce sensible values.
=> UI: Set 8 x 8 as minimum selectable resolution

formatcode.sh
Batch files into clang-format to prevent needless processes. Now its
twice as fast in real time and uses 4x less resources. The old
implementation is also slower (but pretty close to) running a single
invocation of clang-format on all files.
before
time ./formatcode.sh
real	0m3.860s
user	0m20.975s
sys	0m6.694s
after
time ./formatcode.sh
real	0m1.486s
user	0m5.426s
sys	0m0.203s
(single threaded performance, all files on commandline)
real	0m3.511s
user	0m3.420s
sys	0m0.036s
The old code was probably significantly slower on less beefy machines. This brings resource usage inline with running single threaded but actually runs faster with more cores. 100 was chosen arbitrarily but since we have about 800 files to format it should make good use of up to 8 cores. Going as low as 15 is also pretty …
=> CI: Improve formatcode.sh efficiency

libobs/obs-hotkey.c
Use correct data pointer for hotkey pair
When registering a hotkey pair 2 different data pointers can be set, but only the first one is used for the pressed function call
On windows 64 bit by having different data pointers for data0 and data1
=> libobs: Use correct data pointer for hotkey pair

libobs/util/platform-nix.c
Fix os_get_executable_path_ptr on Linux.
Terminate a non-terminated string generated by readlink() to pass to dirname() that needs terminated string as a parameter.
Fixes #2973 
I think this fix prevents a possibility of buffer overflow.
I tested this fix on Ubuntu 19.10.
I can start and stop recording while streaming with no error.
=> libobs: Fix os_get_executable_path_ptr on Linux

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adding Mixcloud as a Streaming Service
Enables users to stream to Mixcloud with minimum configuration changes.
Followed convention, these are also known endpoints provided by Mixcloud (I work there and lead that team)
New Streaming Service
=> rtmp-services: Add Mixcloud service

libobs-winrt/winrt-capture.cpp
Remove hack compilation guards that allowed older Windows SDK versions to be used.
This will prevent compiling without WGC cursor toggle support.
WGC cursor capture behaves as expected whether on or off.
=> libobs-winrt: Require Windows 10 SDK 19041

CMakeLists.txt
Update cmake to check for the latest (now required) Windows SDK 19041 to build against.
We now require this version
Attempted to build against older SDK, watched cmake generate error.
Updated SDK to 19041, error no longer present.
TODO: Update build directions with this new requirement.
- Fixup (non-breaking minor change or update)
=> cmake: Update Windows SDK check to 19041

libobs/obs-cocoa.m, libobs/obs-internal.h, libobs/obs-video.c, libobs/obs.c
Use autoreleasepool for graphics thread.
Apparently necessary to clean up macOS leaks.
Fixes #2293
OBS still works on Mac and Windows. Used _CFAutoreleasePoolPrintPools() in debugger to verify leaky behavior before change, and good behavior after change. Not quite guaranteed to fix original issue, but hopefully it does.
=> libobs: Use autoreleasepool for graphics thread

libobs/media-io/audio-io.c
Remove unused code.
Compiler warning about ts_to_frames() returning uint64_t instead of double, but the function isn't even used anyway.
OBS still compiles and runs.
=> libobs/media-io: Remove unused code

libobs-winrt/CMakeLists.txt
This module houses more WinRT functionality than just window capture.
Better project organization.
OBS still builds and runs. WGC still works.
=> libobs-winrt: Move project to core VS filter

libobs/obs.c
Various libobs functions check for a null obs_core. Several of the checks dereference the pointer before checking it which would result in a crash if null were ever passed, and the null checks are not done consistently across all functions. Assuming obs_startup and obs_shutdown are called properly, there should never be a null obs_core in libobs. This PR removes the null checks.
This requires a slight re-ordering of the shutdown code, as modules which call into libobs during unload might have been accessing one of the functions protected with a null check, and obs_core is actually null at that point. The modules now unload while obs_core is still valid.
Performance and code cleanup.
Ran OBS through my usual testing, no issues encountered. Small risk that some 3rd party plugins may be …
=> libobs: Remove excessive null checks

UI/window-basic-main.cpp
Fixes issue when opening a fullscreen projector, the existing projector on the same monitor wouldn't be deleted.
Found it annoying when extra projectors would be open.
Opening fullscreen projectors on the same screen multiple times.
=> UI: Delete existing fullscreen projector

plugins/win-capture/graphics-hook/vulkan-capture.c
Use general layout and 0 access masks for external synchronization as
specified in the spec.
Also set pipeline stages for maximum synchronization just in case
because it doesn't seem like the pipeline stages are specified.
"Vulkan-incompatible APIs will require the image to be in the GENERAL
layout whenever they are accessing them."
"Whilst it is not invalid to provide destination or source access masks
for memory barriers used for release or acquire operations,
respectively, they have no practical effect. Access after a release
operation has undefined results, and so visibility for those accesses
has no practical effect. Similarly, write access before an acquire
operation will produce undefined results for future access, so
availability of those writes has no practical use. In an earlier …
=> win-capture: Improve Vulkan synchronization

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-settings.cpp, UI/window-projector.cpp, UI/window-projector.hpp
Automatically change projector settings.
Before, the user would have to close and reopen projector when settings changed.
Changed projector settings and see if they were changed.
- UI tweak
=> UI: Auto update projector settings

plugins/oss-audio/CMakeLists.txt, plugins/oss-audio/data/locale/en-US.ini, plugins/oss-audio/oss-input.c
This PR adds corresponding module text, and en-US translation file for oss-audio plugin.
To prepare for support of languages other than English (US).
Run it with 
```
export LANG=en_US.UTF-8; obs
```
=> oss-audio: Add en-US translation data file

UI/window-projector.cpp
Fixes projector always on top setting with Linux.
Fixes #2514
Made projector on top.
=> UI: Fix projector always on top not working on Linux

plugins/image-source/color-source.c, plugins/image-source/image-source.c
Changes the default color for color source to #d1d1d1.
The default color can trigger photosensitivity in users suffering from it; the new color should reduce or avoid the trigger.
Flashed the new color in my own face, it not nearly as painful as flashing a full #ffffff white without precautions. I haven't actually compiled obs-studio with this change.
=> image-source: change color source default color to d1d1d1

UI/platform-x11.cpp
When running obs on FreeBSD (and possibly on other *nix platforms), there might be a chance languages with the same family were prematurely picked over the desired one.
One can reproduce the issue by the following shell commands:
```
export LANG=zh_TW.UTF-8
obs
```
And we could observe that zh_CN was picked over zh_TW despite the existence of zh_TW locale files.
To fix a bug when detecting preferred languages.
Re-run with
```
export LANG=zh_TW.UTF-8
obs
```
=> UI: Fix GetPreferredLocales locale detection

UI/window-basic-adv-audio.cpp, UI/window-basic-adv-audio.hpp
Add percent checkbox to advanced audio dialog.
Before, the user would have to right click in the dialog to change the audio volume type, and this was hard to find.
Toggled percent.
- UI tweak
=> UI: Add percent checkbox to advanced audio dialog

UI/window-basic-main-scene-collections.cpp
GetUnusedSceneCollectionFile tries to create a safe, unused filename for a new scene collection JSON file based on the user-specified scene collection name. It would check the length of the safe version of the user-specified name, but then it doesn't consider that the length may have changed when GetClosestUnusedFileName was called to alter the filename to prevent filename collisions by adding an incremented integer to the end of the filename. This could result in OBS thinking a filename was safe and available, but the resulting filename could be one that already exists. OBS could then overwrite a scene collection JSON file with this new file without any indication that the file previously existed.
Instead of trying to calculate a length based off of the returned filename, let's just use …
=> UI: Fix GetUnusedSceneCollectionFile filename creation

plugins/win-capture/window-capture.c
This change adds the window capture method information to the log file.  With this change, the log file will include whether a user selected "Automatic" or directly selected a window capture method.  It will also include which method was ultimately used, whether the user select "Automatic" or not.
I moved the `blog` call to the end of the `update_settings` function so that I had access to both `method` and `wc->method`.
People providing support requested this change.
I compiled and ran OBS git master on Windows 10 1903 64-bit using VS2017.
- Logging change (non-breaking change which does not change functionality)
=> win-capture: Log window capture method

CI/full-build-macos.sh, CI/scripts/macos/Brewfile, CI/scripts/macos/app/entitlements.plist
This PR adds a single build-script for macOS that allows building, bundling, packaging, code-signing and notarization in one file.
It handles necessary dependencies (Homebrew, VLC, CEF, pre-built deps) with default versions extracted from the Github Action workflow files, stores previous local artifacts on recompiles and acts lazily:
* By default the script only invokes `cmake` and `make`
* Compilation can be skipped to then bundle and/or package only
* Code signing will try to sign an available bundle or package, if found
* Notarization prefers an existing package over an existing bundle as the app bundle inside the `.dmg` will be notarized as well
The script will ask for code-sign/notarization credentials if necessary.
Combines changes made for Github Actions into a single build script …
=> CI: Add all-in-one macOS build script

plugins/win-capture/graphics-hook/vulkan-capture.c, plugins/win-capture/graphics-hook/vulkan-capture.h
Reorganize data to avoid best practices layer warning. Sort of a false
positive in our case because we only have one buffer per pool now.
Implicit layers should be clean citizens.
Opened and closed vkcube several times with OBS open. Opened and closed OBS several times with vkcube open. Best practices warning about VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT usage is gone now.
=> win-capture: Reset command pool rather than buffer

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
* cybergame.tv - Servers and website gone (defunct)
* castr AU - DNS resolution fails
* stream.live - Defunct by the looks of it (dns fail, website broken)
Offline services should be removed to keep the list clean.
JSON has been checked for validity.
- Services update
- [N/A] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [N/A] The code has been tested.
- [N/A] I have included updates to all appropriate documentation.
=> rtmp-services: Remove offline servers/services

UI/volume-control.cpp
Update volume meters at 60Hz (technically 62.5Hz). Reimplementation of #3068.
EDIT: **[Here is a demo](https://streamable.com/ypd6uo)** (30Hz on top, 60Hz on bottom)
The volmeter update rate essentially determines the volmeters' "frame rate". Volmeters that update more frequently are more responsive and more accurate, and also give the program a much-improved feeling of snappy performance.
Performance increase of this change appears to be less than 1% CPU usage increase on average.
Built on Windows 10 and visually inspected. Monitored CPU usage with OBS's built-in CPU usage monitor.
=> UI: Update volmeters at 60hz

UI/forms/OBSBasic.ui, UI/window-basic-main.cpp
Fixes an issue where the pause button or the button text would change the minimum width of the window.
Fixes https://github.com/obsproject/obs-studio/issues/2157
Started recording, the pause button didn't change size of window.
=> UI: Fix buttons changing minimum window width

UI/data/locale/en-US.ini, UI/forms/OBSLogReply.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-log-reply.cpp, UI/window-log-reply.hpp
* Removes the ? button in the Log Reply window (not sure how I missed it last time)
* Adds a basic description to the dialog. Improved wording suggestions welcome.
* Added a button to get basic troubleshooting via the Log Analyzer
**Before:**
**After:**
**To Do:**
Previously, the log dialog contained no context about what it was for.
As we now have an officially-hosted log analyzer, providing access to it from this dialog made sense. At the same time, such a button doesn't make sense for the crash dialog.
* Help -> Log Files -> Upload Last Log File
* Help -> Crash Reports -> Upload Last Crash Report
=> Enhance Log dialog with description and Analyze button

UI/item-widget-helpers.hpp
Sort audio source by name locale aware
The old sorting is based exclusively on the numeric Unicode values of the characters.
https://ideas.obsproject.com/posts/810/
On windows 64 bit see if sources in the advanced audio window are showing in the right order
- Enhancement (non-breaking change which improves efficiency)
=> UI: sort audio sources by name locale aware

UI/window-basic-settings.cpp
Highlights combobox label if audio device is unknown.
Makes it easier for users find the unknown device.
Checked to see if labels were highlighted.
- UI tweak
=> UI: Highlight unknown audio device label in settings

libobs/obs-source.c
If a source is not loaded do not check filter compatibility for filters on that source.
Fixes #2509
On windows 64 bit replicating the steps in #2509
=> libobs: Don't check filter compatibility on not loaded sources

UI/data/locale/en-US.ini, UI/window-basic-main.cpp
Remove prompts that are before the auto-config when OBS is first run.
Makes the auto-config front and center to new users. New users might click no, not knowing what the auto-config is.
Ran OBS as normal.
=> UI: Remove first run auto-config prompts

CI/install-dependencies-osx.sh
This PR adds checks around each Homebrew dependency to only install if necessary and upgrade otherwise. Due to CI providers changing their default Homebrew setups, one cannot assume some packages to not exist already.
Running `brew install` within a script that is set to abort on errors via `set -e` will break as Homebrew quits with a non-zero return value if one tries to install a formula already present. The proper fix is to use Homebrew bundle (see the GitHub Actions workflows), but this quick fix should be future proof as well.
Tested locally with pre-installed formulas
=> CI: Quick fix to cover pre-installed Homebrew dependencies for macOS

deps/media-playback/media-playback/media.c, libobs/graphics/graphics-ffmpeg.c, libobs/media-io/video-scaler-ffmpeg.c
FFmpeg YUV to RGB conversions require extra destination padding for all pixels to be processed.
Fixes https://obsproject.com/mantis/view.php?id=1032
Fixes https://obsproject.com/mantis/view.php?id=1177
JPEG images and some movie files were loading with corrupt right edges.
Fixes #3062.
Provided sample image is now fully processed. Hacked up a test to verify the movie fix. Also tested DeckLink rescale.
=> Fix FFmpeg YUV to RGB conversion by adding extra destination padding to line sizes

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-projector.cpp, UI/window-projector.hpp
Add a simple checkbox to the context menu of a projector or the multiview window.
The projector windows (especially the multiview projector) are very useful. Having them always on top is useful and this checkbox provides a way to toggle this feature without opening the settings dialog.
Also reported on the idea page [here](https://ideas.obsproject.com/posts/848/always-on-top-option-for-multiview-window)
Tested it with multiple projectors (fullscreen and windowed) on Windows 10. This won't likely affect other areas of code or break other functionality.
=> UI: Add always on top checkbox to projector context menu

deps/media-playback/media-playback/media.c, deps/media-playback/media-playback/media.h, plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/obs-ffmpeg-source.c
- deps\media-playback\media-playback\media.c
add av_dict_set(&opts, "stimeout", "30000000", 0);
when connect ffmpeg source fail it will be closed
- deps\media-playback\media-playback\media.c.h
add kill_cb in mp_media_info, when ffmpeg thread is killed it will be called
- plugins\obs-ffmpeg\obs-ffmpeg-source.c
add ffpmeg_source_reconnect, when ffmpeg_source_tick found media thread has been destory it will start reconnect thread after 10000 ms
ffmepg source does not reconnect when source disconnect
obs add a rtmp source or rtsp source test close the network and after a moment reconnect。
After 10000  ms it will be reconnect。
New feature (non-breaking change which adds functionality) 
Fixes #2878
=> obs-ffmpeg: Add auto reconnect to remote media sources

UI/frontend-plugins/frontend-tools/forms/scripts.ui, UI/frontend-plugins/frontend-tools/scripts.cpp, UI/frontend-plugins/frontend-tools/scripts.hpp
Add defaults button to script dialog.
Makes it easier for users to reset script settings.
Changed script settings, then clicked defaults button, and then everything was reset as expected.
=> frontend-tools: Add defaults button to script dialog

UI/window-basic-main.cpp
Fix a bug where the stats dock steals the focus of the main window at startup.
This fix focuses the main window after it has completely loaded.
Fixes bug #2209 
Tested on Windows 10. 
The steps to reproduce lead to the correct behavior: 
1. Enable the Stats dock in View > Docks.
2. Quit and restart obs-studio.
3. Press Alt+F4
-> Closes the main window and not the stats dock
=> UI: Fix bug where stats dock steals focus of main windows

UI/frontend-plugins/frontend-tools/scripts.cpp
When script is added, automatically select script. Also when the dialog is opened,
select previous used script.
Before users would have to click on script when they added it or opened the script window.
Added scripts and closed scripts dialog and the scripts were selected as expected.
=> frontend-tools: Automatically select scripts

UI/window-basic-interaction.hpp, UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
Allow the use of the ESC key to close the settings window.
When there are unsaved changes it prompts to save your settings (Same behavior like clicking on the [x] button in the upper right).
This improves the workflow when the settings window is opened by accident by providing a fast way to close it. Moreover it implements the expected action when the esc key is pressed on a dialog or settings window (Visual Studio, Word, Discord, ... have the same behavior). 
It addresses this issue: #2166
1. Open the settings window
2. Change nothing
3. Hit escape
-> closes the settings window
1. Open the settings window
2. Change something
3. Hit escape
-> shows a confirmation dialog to close the settings window  
1. Open the settings window
2. Hit some configured hotkeys (like …
=> UI: Allow the use of Esc key to quit settings window

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main-transitions.cpp
Adds `obs_frontend_set_tbar_position` and `obs_frontend_release_tbar`, which allow plugins and scripts to control the tbar in OBS. This specific change is required for the `SetTBarPosition` request to be added to obs-websocket.
There is a draft PR for obs-websocket to add a TBar control request to the plugin, and adding that request is impossible without modifying OBS.
- Opened studio mode and played with software slider, works just as expected.
- Loaded an obs-websocket test script with the modified obs-websocket plugin and used it to set the TBar position
- The transition should start and the on-screen TBar should move according to the values sent to obs-websocket
=> UI: Add TBar controls to obs-frontend-api

UI/properties-view.cpp, UI/properties-view.hpp
Allow drag & drop reordering of property lists.
Motivation is to easily reorder items in VLC source playlist.
Reordered items in VLC source playlist.
=> UI: Allow drag & drop reorder of property lists

UI/obs-app.cpp
Displays a native Windows dialog with help text when OBS is launched with `-h` or `--help`, similar to other applications (for example, Microsoft's own [Windows Terminal](https://github.com/microsoft/terminal)).
Once launched, the user can press Ctrl+C on the dialog to copy the contents for easy usage.
While other operating systems allow GUI apps to print to the command line, Windows does not, so the `-h` parameter would not perform as intended.
This change also hides `--allow-opengl` on non-Windows platforms, and hides `-V` on Windows because it doesn't do anything.
On Windows:
* Launch OBS with the `-h` or `--help` flag
* See a help dialog
* Press OK to close the dialog and cancel the OBS launch
Also tested on Ubuntu to ensure the existing `-h` behaviour didn't break.
- New feature …
=> UI: Show help text for launch parameters on Windows

plugins/obs-ffmpeg/obs-ffmpeg-source.c
This change breaks the tying of the 'close' option to the media source being a local file vs. network source. In doing so, it is possible to keep network sources streaming continuously, which fixes a few things when using network cameras as sources:
* The preview pane works in studio mode.
* There is no delay in switching scenes before video appears.
* The multiview works properly/normally.
This does introduce one bit of weirdness which could be easily fixed with sufficient knowledge of OBS to do it quickly: if a networked media source fails with both `Restart playback when source becomes active` and `Close file when inactive` disabled, it is slightly tricky to get it to restart the video stream. (It can be done by enabling those options and hiding the scene, though.) It would be nice to …
=> obs-ffmpeg: Allow continuous network streaming

UI/window-projector.cpp, UI/window-projector.hpp
This deletes the fullscreen projector when the monitor it is on is disconnected.
Before, the projector would move to a different screen.
Created fullscreen projector and disconnected monitor.
=> UI: Delete projector when monitor is disconnected

plugins/obs-qsv11/QSV_Encoder.cpp, plugins/obs-qsv11/QSV_Encoder.h, plugins/obs-qsv11/obs-qsv11.c
This change sets the preference for encoding to the integrated GPU over the discrete GPU on Intel systems with both iGPU and dGPU.
The motivation is to give streaming customers the best hardware encoding experience when there are both iGPU and dGPU options on Intel systems.
This patch has been tested with 3 different versions of graphics drivers (both internal and external) on 3 different platforms to verify HW encoding on the iGPU over the dGPU.
=> obs-qsv11: Set preference for encode to iGPU in case of i+i

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp
Old URL is being phased out for the cleaner interface. Changed in both
the settings pane and the wizard.
Old URL is being phased out for the cleaner interface. Changed in both
the settings pane and the wizard. Old URL doesn't work is user is in Dark Mode on facebook. 
Allows people to get the stream key correctly and faster. The old URL will be removed later as well. 
- Open URL from button in Settings
- Open URL from button in Wizard
MacOS Catalina. Chrome. 
=> UI: Update Facebook get stream key URL

UI/forms/OBSBasic.ui, UI/properties-view.cpp, UI/qt-display.hpp, UI/qt-wrappers.cpp, UI/source-label.hpp, UI/window-basic-auto-config.cpp, UI/window-basic-interaction.cpp, UI/window-basic-main.cpp, UI/window-basic-preview.cpp, UI/window-basic-preview.hpp
AllDockWidgetFeatures is now deprecated. Use underlying values instead.
Use default QFlags constructor instead of nullptr/0.
Use QWheelEvent::angleDelta() in place of orientation() and delta(), and
position() in place of x() and y().
Breakpoint inspected every except two spots that I can't figure out how to reach, but I feel confident in the pattern change:
https://github.com/obsproject/obs-studio/blob/5687c5157c38a7b895fdd52a3f546816b168658d/UI/qt-wrappers.cpp#L267
https://github.com/obsproject/obs-studio/blob/5687c5157c38a7b895fdd52a3f546816b168658d/UI/window-basic-main.cpp#L7655
=> UI: Fix warnings for Qt 5.15

plugins/obs-outputs/librtmp/rtmp.c
While streaming from OBS on an unstable connection, I have found instances where OBS will hang until it is force quit. During some testing with [arut/nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module) proxying connections I found that when the OBS that was streaming to nginx-rtmp-module had network issues it would cause the OBS to hang and never recover.
I eventually identified that the server was sending a `NetStream.Publish.BadName` status message that was never handled.
More information from Adobe about that error can be found [on their site](https://helpx.adobe.com/adobe-media-server/kb/prevent-netstream-publish-badname-errors.html).
I would like OBS to not hang when there are network glitches.
I tested this on macOS by making a build on my MacBook Pro and did the …
=> obs-outputs: Handle NetStream.Publish.BadName from rtmp server

libobs/obs-source.c
To prevent issues in audio mixing make sure the audio data is also cleared
when audio timing is reset.
Ensure the audio data is cleared when a timestamp jump has been detected.
While streaming to twitch with a Media Source that is rtmp I have experienced issues where, after the Media Source has disconnected and reconnected, the audio for that source would no longer be passed along to twitch and any other audio channels would stutter for as long as the "problem" source was enabled.
When debug logging was enabled, I noticed this log message that pointed me towards the timestamp issues:
```
debug: Timestamp for source 'Remote Video' jumped by '49580127663', expected value 678824875200, input value 728405002863
```
This lead me to check out the `handle_ts_jump()` function and I looked for …
=> libobs: Reset audio data on timestamp jump

UI/window-basic-main.cpp
Resolves an issue on macOS where the default action is not set for prompts when the user is removing one or multiple sources or scenes.
On macOS when a user is asked to confirm if they wanted to remove one or multiple scenes and sources they can use the mouse to press Yes or No, on the keyboard they can press escape to cancel or enter, but the enter key does nothing because there is no default action set.
Bizarly this issue doesn't happen on Windows 10.
Tested only on macOS Catalina 10.15.5 on a MacBook Pro 15" 2019
=> UI: Set remove prompt default action

plugins/mac-capture/audio-device-enum.c
This allows the following virtual audio devices to be listed as Desktop Audio devices:
- loopback;
- iShowU;
- BlackHole.
These devices were not listed while they should be.
Tested on macOs 15 (Catalina)
=> mac-capture: Add several virtual audio drivers to Desktop audio

UI/data/locale/en-US.ini, UI/forms/AutoConfigStartPage.ui
Add messages to describe what the wizard is for and how it can be run at any time.
Since #2744 removed the prompts, this adds those messages to the auto-config dialog itself.
Opened auto-config dialog.
=> UI: Add informative messages to auto-config dialog

UI/window-basic-main.cpp
Fixes an issue where the Start Streaming button would still be checked while in a disabled state during `STREAMING_STARTING`, causing the text to be the same colour as the button.
Before:
After:
This doesn't change behaviour when a stream fails due to:
https://github.com/obsproject/obs-studio/blob/0fff23d8e1cb715d0b2b117938c68b072419e22e/UI/window-basic-main.cpp#L5274-L5276
And will correctly go back to a checked state once the stream starts due to:
https://github.com/obsproject/obs-studio/blob/0fff23d8e1cb715d0b2b117938c68b072419e22e/UI/window-basic-main.cpp#L5496-L5500
I also checked relevant delay and stop functions, all correctly set the checked state when they run.
1. Put in an invalid stream key (tested with Twitch)
2. Click "Start Streaming" …
=> UI: Fix unreadable Connecting Stream button

UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp
The automatic scene switcher in linux is not picking up some windows during the running proccess, even when the getting the list works fine. 
Using for recording notice that was not working for me for some windows and since was no issue start investigating and found a solution.
This has been tested manually, OS: Linux, Distribution: Manjaro.
I configure automatic scene switch for windows that was not being able to trigger the change, and confirm that with the fix they are working now.
=> UI: Fix scene switcher not detecting some windows

UI/properties-view.cpp
UI: Make color display, don't show alpha value in color label
The color picker loads the label not showing alpha hex value but on
color change then shows the alpha level in the hex value (which is
hardcoded to 255).
This changes so the label always shows only RGB value.
Of course, can be easily changed back to ::Arbg later if an alpha 
picker is added.
On first load and open palette:
Wrong behavior removed by this diff; saving new color would show the FF alpha value in the hex value: 
UI consistency, fixes. 
MacbookPro 2019. MacOS Catalina. 
=> UI: Make color display, don't show alpha value in color label

plugins/win-capture/graphics-hook/vulkan-capture.c
Vulkan loader needs pure name, which needs manual fix-up on 32-bit.
Just noticed Vulkan game capture doesn't work for 32-bit applications.
vkcube 32-bit works and 64-bit didn't regress.
=> win-capture Fix 32-bit Vulkan capture

.github/workflows/clang-format.yml, .github/workflows/main.yml
The changes in this PR enable maintainers to add the `Seeking Testers` label to existing pull-requests and trigger artifact creation by just re-running previous jobs.
Additionally minor fixes to workflows have been added:
* Additional conditions for main workflow `push` events was added to avoid duplicate workflow runs for pushes inside pull requests
* Mismatches between CEF build path and cache path for Windows builds have been fixed
Github event data is "fixed" to a commit and as such additional data such as labels are not updated on re-runs. To fix this, label data needs to be fetched for a GitHub pull request (or issue) on-demand during the workflow run. The changes contained in this PR do just that and allow maintainers to add the necessary label (`Seeking Testers`) after a …
=> CI: Add label change detection for Github Action re-runs

libobs/obs-windows.c
Adds translation strings & a check on Windows to ensure F13 and above are correctly translated.
Fixes #2377.
Map a key to F13 on a Stream Deck or using Logitech G HUB and press the key in Settings -> Hotkeys. Tested on Windows 10.
=> libobs: Translate F13-F24 hotkeys on Windows

libobs/util/dstr.c
(edited by Jim)
Fixes a crash.
The depad functions haven't been tested with cases where the padding is at the front of the string, thus when padding at the front of the string, it could read more memory than it was supposed to, causing a possible crash.
Tested with a string that had spaces in the front.
=> libobs: Fix reading memory past size of string

plugins/obs-outputs/flv-mux.c
modify "audiocodecid" and "videocodecid" data types: string->number
reference: https://github.com/obsproject/obs-studio/issues/3131
The spec says the metadata for codecid are double. 
I have problems writing rtmpclient and parsing metada. It's just a suggestion.
push and pull video stream.
=> obs-outputs: Use FLV codec IDs for videocodecid/audiocodecid

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Fix play pause crash
obs_source_media_play_pause called on a invalid ffmpeg source crashes OBS.
tested with obs media controls plugin: https://github.com/exeldro/obs-media-controls
=> obs-ffmpeg: Fix play pause crash

plugins/linux-v4l2/v4l2-input.c
The PR #2978 which was merged a few days ago added the two struct members resolutionUnchanged and framerateUnchanged which are use in the newly added code which keeps track if the device must be restarted after a configuration change.
These two keys are using CamelCase despite all of the other code using snake_case. This PR fixes that.
Code consistency
It compiled fine and I checked that the stream restart logic still works.
Best match of list: Code cleanup
=> linux-v4l2: Fix case of variables

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Replaced ingest server and added recommended settings for the Uscreen service.
It's a more stable ingest server.
=> rtmp-services: Update Uscreen service

CI/before-deploy-osx.sh
A switch was added to the deployment script used in Azure Pipelines CI that checks whether the updated mbedtls variant is installed via Homebrew. As each `dylib`'s version string has been incremented, the necessary commands to fix up dynamic library paths/identities adapt to this change as well.
Homebrew always keeps up with updated versions of its Formulas, so when `mbedtls` was updated, the old filenames didn't match anymore and thus builds generating artifacts would fail. By checking for the specific version present in the filesystem the new script should be able to adapt to this change (until the next new version comes along of course).
Will be tested via successful Azure Pipelines runs.
=> CI: Add fix for macOS builds failing on push for Azure CI

plugins/win-capture/duplicator-monitor-capture.c
```
22:34:58.340: [duplicator-monitor-capture: 'Display Capture'] update settings:
22:34:58.340:     monitor: 1 (3440x1440)
22:34:58.340:     cursor: false
```
Logs the monitor number & its resolution when properties are changed (as the index can be different compared to the top of the log).
Other sources log when properties are changed. Display Capture should too, as it's invaluable when debugging (especially dual-GPU).
Add a Display Capture source on Windows 8+. Change its properties. Hit OK.
=> win-capture: Log duplicator display when updating properties

.github/workflows/main.yml, CI/full-build-macos.sh
Disables Python scripting support for macOS builds on CI as well as in default builds using the macOS build script.
Python scripting support is not in a working state on macOS and with Homebrew updating default Python to v3.8.3 there will be build issues if an updated Python is installed and prioritised over macOS' system Python (as OBS doesn't build successfully with newer Python versions present). Disabling Python scripting support for macOS builds for the time being avoids this issue.
OBS built and run with updated build script successfully on macOS 10.15 and Python 3.8.3 installed.
=> CI: Disable building OBS with Python scripting support on macOS

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Remove Restream FTL endpoints from the services list.
Restream FTL has been built to support Mixer interactive steaming, with Mixer being shut down on July 22 we will be dropping FTL support and encourage users to switch to RTMP. More info on Mixer shutting down: https://blog.mixer.com/2020/06/22/the-next-step-for-mixer/
=> rtmp-services: drop Restream.io FTL support

plugins/coreaudio-encoder/encoder.cpp, plugins/coreaudio-encoder/windows-imports.h
For four channels, CoreAudio aac encoder wrongly defaults to quad
(FL FR, BL BR) instead of 4.0 (FL FC FR, BC).
This goes against  the aac spec
(ISO/IEC 14496-3:2009.Amd.4:2013).
So 4.0 needs to be explicitly set for the CoreAudio encoder.
This fixes an issue raised by @BtbN in PR 3174 where Twitch would 
silence channels when CoreAudio encoder is used.
The reason is because a quad channel layout is produced instead of 4.0.
The PR fixes the channel layout issue.
I've checked that recordings with CoreAudio encoder with 4.0 selected in audio settings
are indeed decoded as 4.0 (by FFmpeg native aac decoder).
I haven't checked directly with Twitch but @BtbN  reports this fixes the issue he reported. 
=> coreaudio-encoder: Fix encoding of 4.0 speaker layout

UI/obs-app.cpp, UI/obs-app.hpp, UI/window-basic-main.cpp
When distributing OBS via third party platforms that have their own update systems we want to be able to disable the OBS updater without having to resort to having a separate build entirely.
This is a PR for one of the changes proposed in RFC #⁠30: https://github.com/obsproject/rfcs/pull/30
This change adds a new `--disable-updater` command line options and `/disable_updater(.txt)` sentinel file to disable the built-in OBS updater.
As per https://github.com/obsproject/rfcs/pull/30, when distributing OBS via third party platforms the built-in updater should be disabled to avoid conflicts with the platform's updater system.
To keep the maintenance effort to a minimum we'd like to re-use the existing build and simply include the sentinel file or start parameter in the platform configuration …
=> UI: Add flag/file to disable built-in updater

libobs/graphics/graphics-ffmpeg.c, libobs/media-io/media-remux.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Fix various FFmpeg deprecation warnings using with patterns from updated FFmpeg examples.
Debugger breakpoint inspection. Mux and remux of 1/3 video/audio stream combination, and loaded PNG image. Binary file output match when remuxing before and after changes. Also verified fallback paths by flipping compilation guards locally.
=> FFmpeg deprecation warnings

deps/libff/libff/ff-util.c, deps/media-playback/media-playback/decode.h, libobs/media-io/media-remux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.h
More FFmpeg cleanup, including bug fix for PR #3185, and race fix for FFmpeg output recording.
Don't like dead code or bugs.
Debugger breakpoint inspection for codec_tag change, both sides.
=> More FFmpeg cleanup

UI/frontend-plugins/decklink-output-ui/CMakeLists.txt, UI/frontend-plugins/frontend-tools/CMakeLists.txt, UI/frontend-plugins/frontend-tools/scripts.cpp, UI/properties-view.cpp, UI/qt-wrappers.cpp, UI/qt-wrappers.hpp, UI/window-basic-main-profiles.cpp, UI/window-basic-main-scene-collections.cpp, UI/window-basic-settings.cpp, UI/window-importer.cpp, UI/window-remux.cpp
Fixes crash when using Linux browser when opening file dialog.
Workaround for https://github.com/obsproject/obs-browser/issues/219 until the actual issue is solved.
Opened file dialog to make they still work.
=> UI: Use non-native file dialog w/ Linux

deps/media-playback/media-playback/media.c
Preload video when seeking paused
When a video is paused and you seek to an other position in the video, the source will display the frame from the moment it is paused. With this fix it will show the frame of the new position.
Pausing and seeking a local video using the Media Controls plugin
=> deps/media-playback: Preload video when seeking paused

CI/before-deploy-osx.sh, CI/before-script-osx.sh
Attempt to disable Python to fix Mac PR automation. See #3172 for details.
Mac PR automation is failing.
Azure will let us know...
=> CI: Disable Python for Mac PR automation

plugins/win-capture/graphics-hook/vulkan-capture.c, plugins/win-capture/graphics-hook/vulkan-capture.h
Make fixes mostly to stabilize CTS. Tested on Windows with RTX 2080 Ti.
Use separate linked-list maps for devices and queues.
Process queues upfront in OBS_CreateDevice, and not lazily in
OBS_GetDeviceQueue.
Handle failed node allocation for OBS_CreateInstance, OBS_CreateDevice,
and OBS_CreateSwapchainKHR.
Handle VK_NULL_HANDLE for OBS_DestroySurfaceKHR and
OBS_DestroySwapchainKHR.
Add temporary code path CTS_WORKAROUND to deal with CTS sharing surfaces
between instances.
Fix return value for OBS_DestroyInstance.
Add missing _freea calls, required for _malloca.
Make sure the queue passed to OBS_QueuePresentKHR supports transfer to
safely call vkCmdCopyImage.
Update GetInstanceProcAddr/GetDeviceProcAddr to conform closer to spec.
Remove extra macros because I dislike indirection more than …
=> win-capture: Improve Vulkan hook stability

plugins/win-capture/graphics-hook/vulkan-capture.c
Prevents multiple queues in the same family from racing on frame data.
Removal of vk_family_data also fixes broken capacity calculation. Two
queue families can share the same index if one is "protected-capable"
and the other isn't.
Recently learned about the possibility of queue family index sharing.
vkcube 32/64, Doom (2016), CTS
=> win-capture: Make Vulkan frame data local to queue

libobs/CMakeLists.txt
Add util/sse2neon.h to libobs_util_HEADERS in libobs/CMakeLists.txt
Plugins fail to compile on arm/rpi due to missing header install
The previous patch #3180 for arm/rpi missed this addition to CMakeLists
Fresh build on Raspberry Pi 4B 4Gb without changes:
* obs-studio will compile and install
* obs-websocket & obs-ndi will fail due to missing sse3neon.h
Fresh build on Raspberry Pi 4B 4Gb with changes: 
* obs-studio, obs-websocket & obs-ndi compile and install
Operating System: Raspbian GNU/Linux 10 (buster)  
Kernel: Linux 5.4.51-v7l+  
Architecture: arm  
*  Bug fix (non-breaking change which fixes an issue)
=> libobs: Add util/sse2neon.h to CMakeLists.txt

UI/properties-view.cpp
I moved the text for the checkbox properties with tooltips into the QCheckBox, and made the label only contain the help.svg image. This allows the text to be a part of the checkbox, so when you click the text it fires the checkbox event. 
This change just makes the text of boolean properties with tooltips on the properties page clickable.
I was trying to fix this issue: https://github.com/obsproject/obs-studio/issues/2698
Tested on Windows 10 with RTX 2060
Tested changes by checking properties UI functions properly
=> UI: Fix clickable text on boolean properties with tooltips

UI/platform-osx.mm
This change forces windows on Mac OS that have been set as 'always on top' to be more aggressively 'on top' by manipulating the underlying NSWindow's `level` attribute.
I've been using OBS in conjunction with Apple Keynote. In full screen mode, Keynote covers OBS's windows even when 'always on top' has been set in preferences.
This change allows me to use a Windowed Projector to see previewed source even when Keynote is running in full screen mode.
I'm entirely new to Objective C and this type of projects, so I'm fully ready to hear that there was a much better way to do this.
Tested on Mac OS Catalina 10.15.6 on MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Built locally, run from (unsigned, un-notorized) app bundle.
Set 'Make projectors always on top' in the preferences, opened …
=> UI: Make macOS 'always on top' more aggressive

.github/workflows/main.yml, CI/full-build-macos.sh
Fixes Brew Bundler breaking on CI due to missing prior Homebrew update: https://github.com/Homebrew/homebrew-bundle/issues/751
Issue prohibits macOS CI workflows from completing and could also lead to issues when using the macOS build script.
* Tested locally
* Successful fix will let macOS workflow finish
=> CI: Fix Brew Bundler breaking without prior brew update

libobs/obs-source.c, plugins/obs-ffmpeg/obs-ffmpeg-source.c
This PR changes the preloading / async texture behavior in libobs.  `obs_source_show_preloaded_video` now updates the texture when called instead of when `obs_source_preload_video` is called. As the only user of `obs_source_preload_video`, obs-ffmpeg was changed to only call `obs_source_show_preloaded_video` if video was actually preloaded.
Fixes broken(?) API behavior - the current behavior of `obs_source_preload_video` / `obs_source_show_preloaded_video` can fail if something else writes to the async texture in between the preload / show calls. This code is hopefully closer to what the functions were intended to do.
Fixes https://github.com/obsproject/obs-studio/issues/2906
Tested with a Media Source using a 1 FPS video with "show nothing when playback ends" and "restart playback when …
=> Fix preloaded video behavior

UI/CMakeLists.txt, UI/api-interface.cpp, UI/data/locale/en-US.ini, UI/obs-app.cpp, UI/obs-app.hpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/screenshot-obj.hpp, UI/window-basic-main-outputs.cpp, UI/window-basic-main-screenshot.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-frontend-api.rst
This adds the ability to take screenshots of the preview with a hotkey. It currently only saves to png and doesn't have any settings, so it saves to where the recordings are saved.
https://ideas.obsproject.com/posts/4/add-a-screenshot-button
This is simpler than #1269 because it uses QImage to save the screenshot.
The code is based off of @Palakis screenshot code in the websockets plugin.
Took screenshots and made sure they saved correctly.
=> UI: Add ability to make screenshots

plugins/oss-audio/oss-input.c
util_mul_div64() is a new helper to do scaling introduced in https://github.com/obsproject/obs-studio/pull/2657. This commit sweeps the
oss-audio plugin code to generalize the way of doing scaling.
This commit serves as an optimization to oss-audio's arithmetic operations.
It's tested on FreeBSD by sending SIGSTOP and SIGCONT to the obs process during audio recording.
=> oss-audio: Use util_mul_div64() to do time scaling

UI/forms/OBSBasic.ui, UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp
Remove the plus and minus icons and move the selection of adding configurable transitions to the combo box. The remove ability has been moved to the config button menu.
Before users might not have known the extra transitions existed because they would have to click the plus button to find them.
Added transitions via the combo box and clicked different transitions and everything worked as expected.
- UI tweak
=> UI: Redesign transitions dock

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/forms/OBSBasic.ui, UI/log-viewer.cpp, UI/log-viewer.hpp, UI/obs-app.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
When the user clicks 'Show current log' in menu, show log window.  This replaces the current action of opening the log in an external program.
When the message is an error or warning the text is highlighted.
Also added checkbox to show log viewer on startup.
Currently when showing the log, the log is static. With this, users can see what is happening as the log is updating.
Did things in OBS to make sure it was updating properly, and created errors/warnings to make sure they were highlighted as expected.
=> UI: Add log viewer window

UI/forms/OBSBasicSettings.ui, UI/window-basic-main.cpp, deps/media-playback/media-playback/media.c, libobs/media-io/video-io.h, libobs/media-io/video-matrices.c, libobs/media-io/video-scaler-ffmpeg.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.h, plugins/obs-x264/obs-x264.c
Several changes:
- Solidify support for sRGB video format.
- Add color metadata to file containers for playback libraries that ignore the metadata in the video stream.
- Base 601 support around SMPTE 170M, which is the expected definition of 601 for applications such as Chromium.
- Switch default video format from 601 to sRGB.
Based on this RFC: https://github.com/obsproject/rfcs/pull/7
709/1886 is a weird pair, and most PC applications are sRGB, so make sRGB the default video color space for simplicity.
Chrome on Mac using sRGB is straightforward, whereas midtones are raised for 709, which may not have been desired.
Android ExoPlayer library is known to look at container metadata and not stream metadata for playback.
Inspected all diffs with debugger breakpoints. Various 601/709/sRGB …
=> Color space refinements

.github/workflows/main.yml
Update macOS deps for build script and Github CI to include updated Qt build. 
Github Action runners contain `libtiff` and `webp` preinstalled via Homebrew. Building Qt on CI for re-distribution will lead to Qt's `imageformats` plugins to be linked against those Homebrew-provided libraries (instead of third-party code contained in Qt's repos).
This leads to a situation where the Qt distributed as part of `obs-deps` can not be bundled on a system without these libraries installed via Homebrew as well.
Fixes https://github.com/obsproject/obs-studio/issues/3242
* OBS built and bundled successfully with `libtiff` and `webp` not linked/available on build system
* OBS built and bundled successfully with `libtiff` and `webp` linked/available on build system
* Qt plugins checked for Homebrew …
=> CI: Update macOS deps version to fix unmet Qt plugin dependencies

UI/source-tree.cpp, UI/source-tree.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Previously the item select and deselect signals wouldn't work with groups.
Fixes #2794
Selecting and deselecting scene/group items to make sure the signals are fired.
=> UI: Make select/deselect signals work w/ group items

README.rst
This removes the Mantis link in the readme and replaces it with the GitHub Issues one.
Mantis isn't used anymore by the project.
Made sure the link showed up correctly when looking at the readme on the branch.
=> README.rst: Remove Mantis

plugins/decklink/DecklinkBase.cpp, plugins/decklink/DecklinkBase.h, plugins/decklink/DecklinkInput.hpp
Created another virtual function to override and moves stubbed function to the header to remove three file warnings: `...hidden overloaded virtual function 'DecklinkBase::Activate' declared here...`
Reduce warnings, more-correct code on mac. 
MacOS Mojave 10.14.16
- Builds on mac
- No longer flags errors: 
```
Scanning dependencies of target mac-decklink
[ 37%] Building CXX object plugins/decklink/mac/CMakeFiles/mac-decklink.dir/__/plugin-main.cpp.o
[ 38%] Building CXX object plugins/decklink/mac/CMakeFiles/mac-decklink.dir/__/decklink-devices.cpp.o
[ 38%] Building CXX object plugins/decklink/mac/CMakeFiles/mac-decklink.dir/__/decklink-output.cpp.o
[ 38%] Building CXX object plugins/decklink/mac/CMakeFiles/mac-decklink.dir/__/decklink-source.cpp.o
[ 38%] Building CXX object …
```
=> mac-decklink: Fix C++ virtual function warnings

.github/workflows/main.yml, CI/full-build-macos.sh
Adds `QtNetwork` from obs-deps to application bundle to restore support for plugins that expect it to be shipped as part of OBS' own bundle.
Currently the Streamdeck OBS plugin requires `QtNetwork` and is linked against the Framework inside OBS' application bundle (using the `@executable_path` dylib variable). OBS and its included plugins do not require `QtNetwork` and hence it wasn't bundled automatically.
This fix adds the framework manually and fixes up identity and `QtCore` references to restore this support.
* OBS compiled locally with fixes to build script
* OBS bundled locally
* QtNetwork framework found inside bundle with correct identity/paths
=> CI: Add QtNetwork to bundle to restore Streamdeck support

UI/window-basic-auto-config-test.cpp, plugins/rtmp-services/CMakeLists.txt, plugins/rtmp-services/nimotv.c, plugins/rtmp-services/nimotv.h, plugins/rtmp-services/rtmp-common.c
- Add support for Nimo TV "Auto" server
- The ability to select a server based on user location.
Tested on Windows 10 and Mac OS X 10.15.3.
=> rtmp-services: Add Nimo TV auto server

UI/data/locale/en-US.ini, UI/obs-app.cpp
This adds a check when compiling for linux to check for a ChromeOS
container specific directory. If this directory exists OBS will fail to
start with an error that ChromeOS is unsupported. Its still unclear how
much this will help since these users are typically on debian stable so
this change wont reach them for another 4 years.
I also dont have a chromeos device to test this on. But it looks promising...
If anyone with a chromeos device could confirm id appreciate it.
Telling people on ChromeOS that OBS doesnt work is annoying. Now they will know as soon as they start up the program.
Manually creating the target folder works as intended. Removing it OBS works as intended. I find it highly unlikely people running on linuxes outside of chromeos or chromeos developers will have an …
=> UI: Check and fail when launched under ChromeOS

plugins/image-source/obs-slideshow.c
This replaces the proc handler calls with the existing media controls api.
This removes duplicate code that could also be handled with existing code.
The media controls plugin, https://obsproject.com/forum/threads/media-controls.125774/, doesn't have to change much code to accommodate the slideshow source.
Once the context bar is merged, another PR will be made to hide unneeded controls from the context bar for the slideshow, such as the timers and the slider.
Used slideshow source and made sure everything still worked.
=> image-source: Use media control api for slideshow

plugins/obs-x264/CMakeLists.txt, plugins/obs-x264/obs-x264-options.c, plugins/obs-x264/obs-x264-options.h, plugins/obs-x264/obs-x264-test.c, plugins/obs-x264/obs-x264.c
OBS' x264 plugin has a text field for entering x264 options. The error reporting for this text field is bad. These patches improve the error reporting by printing more useful messages to the log file.
Before:
15:25:30.435: [x264 encoder: 'streaming_h264'] preset: veryslow
15:25:30.435: [x264 encoder: 'streaming_h264'] tune: zerolatency
15:25:30.435: [x264 encoder: 'streaming_h264'] x264 param: --bad=stuff failed
15:25:30.435: [x264 encoder: 'streaming_h264'] settings:
15:25:30.435:       rate_control: CBR
15:25:30.435:       bitrate:      1050
15:25:30.435:       buffer size:  1050
15:25:30.435:       crf:          0
15:25:30.435:       fps_num:      15
15:25:30.435:       fps_den:      1
15:25:30.435:       width:        1920
15:25:30.435:       height:       1080
15:25:30.435: …
=> obs-x264: Log when options are ignored

libobs/obs-internal.h, libobs/obs-source.c
Currently we use a bool flag to signal the video thread that it should
call obs_source_deferred_update. This does not work correctly when the
update callback is slow and the update is triggered faster than the
callback can complete.
For example:
* the settings are set to state A
* defer_update is set
* obs_source_deferred_update is called and enters into the callback
* the callback starts making use of the settings in state A
* the settings are set to state B
* defer_update stays set
* the callback finishes
* defer_update is set to false
Now defer_update is false but the callback has only observed settings in
state A but not B.
This commit fixes this bug by keeping an update counter. If the counter
has changed while we were in the callback we know that we need to update
again.
The counter …
=> libobs: Fix deferred update sometimes using stale data

UI/window-basic-auto-config.cpp
If style is not set it default's to Mac's style on Mac which adds
padding for a background. Looks like wasted space on Mac because there
is no background. Matches windows. Does not affect Linux.
https://doc.qt.io/qt-5/qwizard.html#elements-of-a-wizard-page
BEFORE:
AFTER: 
Fixes outstanding mac issue with wizard layout. 
MacOS Mojave v10.14.
=> UI: Mac fix — remove wizard background padding

libobs/util/utf8.c
It is undefined behavior to apply an offset to a null pointer. I would
have liked to reference cppreference but best I found was the PR that
added this check to clang's undefined behavior sanitizer:
https://reviews.llvm.org/D67122 .
We should not have undefined behavior.
We can observe the undefined behavior by compiling with `-fsanitize=undefined`. I do this with clang-10 on Linux. Create a text source. When typing the first character for the source we see the following message. Note that there is earlier undefined behavior already which this PR does not fix.
```
obs-studio/libobs/util/utf8.c:147:13: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/e/programming/obs/obs-studio/libobs/util/utf8.c:146
```
With this PR we no …
=> libobs: Fix undefined behavior

UI/window-basic-main.cpp
Change the default sample rate from 41 kHz to 48 kHz.
In a discussion on Discord the consensus was that 48 kHz is a better
default. This was prompted by the merge of the rnnoise library which can
only handle 48 kHz natively. 48 kHz is also more commonly used as a
default on personal computers.
Potential problem:
If the user has never changed the sample rate and saved the config file then the setting will silently change. I think that's fine because most users probably do not care and those that do have likely changed it manually in the past.
I deleted the config directory and started obs. The default showed as 48 kHz.
N/A
=> UI: Change default sample rate to 48 kHz

UI/log-viewer.cpp
Ensures tabs and spaces are rendered correctly by wrapping each line in a `<pre>` tag.
**Before:**
**After:**
Logs are harder to read without the included tabs and spaces, plus this makes it consistent with Notepad and other tools.
Open the log viewer. Notice tabs and spaces are rendered.
=> UI: Render tabs and spaces in Log Viewer

UI/data/locale/en-US.ini, UI/log-viewer.cpp, UI/log-viewer.hpp
This restores the ability to open the log file itself from the OBS UI.
I wasn't sure whether "Open" or "Open file" was more suitable.
The new log viewer is awesome, but there are use cases to open the log file itself, such as viewing profiler information without launching OBS a second time. This provides a way to do that.
Launched on Windows 10, clicked the button which opened the file in Notepad.
=> UI: Provide Open button in the Log Viewer

UI/api-interface.cpp, UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp
Fixes issue where sometimes the transition loop would return null transition.
Tested with transition override menu.
=> UI: Fix transition enumeration

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-settings.cpp
Fixes an issue on Linux where updating the projector always on top setting wouldn't work.
Apparently, on Linux, you cannot update the window flags while it is still open, so just close the projectors and reopen them again when the setting changes.
Created projector and changed the always on top setting.
=> UI: Fix always on top w/ projectors on Linux

libobs/CMakeLists.txt
Add explicit linkage to X11 
fixing #3305
Tested in #3305 
=> libobs: Fix underlinking X11

UI/window-projector.cpp
This fixes a bug where the projector wouldn't work on secondary
monitors on Windows.
Will need confirmation by others that the bug is fixed, as I only tested this on Linux.
=> UI: Fix projector not working on secondary monitors

plugins/obs-ffmpeg/obs-ffmpeg-source.c
This fixes a crash when seeking when there is no valid
media.
Created media source without media and then moved the seek slider.
=> obs-ffmpeg: Fix crash when seeking with no media

UI/window-basic-main.cpp
Ensures that only one instance of each Interact / Filters / Properties dialog is opened at the same time.
No other situation allows opening two Properties dialogs at the same time. This seems like an edge case that wasn't covered.
The reason why this is a bad idea is because each dialog will be out of sync (different selected settings).
* Double click on a Display Capture source to open the Properties window
* Change the selected Display in the Properties window
* In the Sources list, double click on the same Display Capture source to try opening Properties
* In the "Settings Changed" confirmation dialog, click Cancel. The new dialog should no longer open.
=> UI: Don't open second dialog if close event is ignored

.github/workflows/docs.yml
Performs a checkout of the OBS repo, updates the sphinx config with the latest libobs version & copyright year, generates the HTML documentation, and provides a zip with artifacts that can be uploaded to `obsproject.com/docs`.
Example run can be found here: https://github.com/WizardCM/obs-studio/runs/1024678780?check_suite_focus=true
For pull requests, this is only run for direct edits to the documentation, and skips the version bump.
There's no need for generating documentation to be a manual process.
Additionally, this includes warnings about formatting.
* Push to a branch and see it build
* Submit a PR with changes to the docs folder.
=> CI: Add Sphinx Docs generator Github Action

UI/log-viewer.cpp, UI/window-basic-main.cpp
Rather than closing the Log Viewer when "View Current Log" is clicked, bring it to the front rather than closing it.
Also add minimize/maximize buttons for better UX.
It is not common for a menu item to toggle a window. Instead, bring it to the front and focus it.
Additionally, a log can be quite verbose. Providing a maximize button allows for faster viewing of a larger log, and being able to minimize means less visual clutter when not focusing on the log.
This also makes the Log Viewer match the Script Log in behaviour.
Click Help -> View Current Log
Place the Log Viewer elsewhere on the screen
Click Help -> View Current Log again
See the log viewer
=> UI / Log Viewer: Bring to front rather than close, add minimize/maximize buttons

UI/window-basic-adv-audio.cpp
Due to the placement of addStretch(), the checkbox was being attached to the Mono label when resizing the dialog.
This ensures it's aligned to the left, with some spacing.
**Before:**
**After:**
It makes no sense to show the toggle away from the volume column and may confuse users.
Resize the AAP dialog.
=> UI: Align Advanced Audio Percent toggle to Volume text

UI/window-basic-main.cpp
Fixes a bug where the system tray icon still shows while disabled.
[It fixes this issues](https://github.com/obsproject/obs-studio/issues/3205)
I simply tested this on my local Windows 10 machine.
=> UI: Fix tray icon appearing when disabled in settings

UI/window-basic-main.cpp, UI/window-basic-main.hpp
While editing a scene name, the Qt shortcut key for the renameScene action remained active. If the user pressed the shortcut key while actively editing a scene name, the widget would retrigger the action, causing the name edit to fail and discard the current changes to the scene name. The scene name would be reset to its previous saved value and reselected as if the user had pressed the shortcut key for the first time. 
This commit removes the QAction associated with the shortcut key from the scenes dock widget when editing starts and adds the action back to the widget once editing is done.
Fixes #3044.
Compiled on Windows 10 1909 Home 64-bit with VS2019.
1. Pressed F2 to rename a scene.
2. Typed some letters for new scene name.
3. Pressed F2 before completing rename.
4. Pressed Enter key …
=> UI: Disable scene rename shortcut key while renaming

UI/window-basic-main.cpp
Output channel 6 was not being deleted, so use for loop
to delete all possible channels.
Bug fix and code cleanup.
Ran OBS to make sure nothing broke.
=> UI: Fix output channels not being deleted

libobs/obs-windows.c
This adds logging for the "Hardware-accelerated GPU Scheduler" (HAGS)
introduced with Windows 10 2004 which is known to cause issues with OBS
and game performance.
Adds a new line in the OBS log below Windows 10 Gaming Features named "Hardware GPU Scheduler" to indicate status of the Hardware-accelerated GPU Scheduler introduced with Windows 10 2004.
HAGS is known to cause performance issues with OBS as well as game capture. Also some games do not work properly with it. Adding a log entry for it helps troubleshooting for users with latest Windows 10 as the option seems to be enabled by default for some users despite it being an experimental/early access feature.
- Visual Studio 2019 on Windows 10 Pro 20H2 (slow ring) with compatible RTX2080S and latest Nvidia driver.
- HAGS enabled and …
=> libobs: Log Windows 10 Hardware GPU Scheduler

UI/forms/source-toolbar/device-select-toolbar.ui, UI/forms/source-toolbar/game-capture-toolbar.ui, plugins/obs-outputs/flv-mux.c, plugins/obs-outputs/librtmp/rtmp.c, plugins/obs-outputs/rtmp-stream.c, plugins/obs-x264/obs-x264.c
Clears GCC warnings on unused and deprecated vars
Warnings are annoying.
Makes it easier to find more important warnings in logs.
It still compiles and obs Open
=> Fix compiling warnings

UI/forms/OBSBasicSettings.ui
Ensures that pressing Tab in the Settings window focuses fields in the correct order.
Basic UX and accessibility improvement.
* Open Settings
* Tab through each screen
=> UI: Add missing tab stop fields in Settings

plugins/win-capture/graphics-hook/vulkan-capture.c
CTS has been fixed, so the workaround is no longer necessary.
(TODO: This isn't actually true yet.)
Issue: https://github.com/KhronosGroup/VK-GL-CTS/issues/218
PR: https://github.com/KhronosGroup/VK-GL-CTS/pull/223
Don't want to leave hacks around.
CTS, vkcube 32/64, Doom (2016)
=> win-capture: Remove Vulkan CTS workaround

.github/workflows/main.yml
https://github.com/obsproject/obs-deps/commit/e3cf394948352d8db49d830b3b0ee8cf2390efd7
Crashes are bad, and up-to-date deps are good.
Built & ran OBS on macOS
=> CI: Update macOS deps to fix crash from invalid linking

plugins/win-capture/graphics-hook/vulkan-capture.c
Two changes: one to support 1.0 API applications/drivers, and another to set uninitialized members that can lead to a crash.
Be robust when creating instances. Crashes are bad.
Fallback path faked with debugger. Crash when restoring vkCube from minimize is gone. Lots of debugger inspection. Also tested Doom (2016) capture.
=> Vulkan instance fallback, and uninitialized member fix

UI/window-basic-main.cpp
Simply gets rid of a warning about needing parenthesis around bitwise operator
It was the only thing between me and a perfect clean compile.
I tested it on my machine.
=> UI: Fix compiler warning about needing parenthesis

UI/window-basic-main-dropfiles.cpp
This fixes a memory leak when dropping files when the name
is the same as other sources.
Inspired by #3393, I went to look in other places where the source is not getting released after calling obs_get_source_by_name.
Dropped same file multiple times and noticed leaks didn't happen like before.
=> UI: Fix memory leak when dropping files

UI/window-basic-stats.cpp
If a user would start recording, then open the stats dialog,
the recording time left would be blank
Fixes bug.
Made sure the recording time left displayed correctly when opening the stats dialog.
=> UI: Fix rec time left not showing in stats

UI/context-bar-controls.cpp
This fixes an issue in the Freetype 2 Source where color changes were not applied at all.
It's nice when buttons do what they say they do.
Add a Freetype 2 Text Source and try changing the Color via the Toolbar.
=> UI: Don't save invalid colors via Source Toolbar (Freetype 2 Source)

UI/forms/OBSBasic.ui, UI/forms/source-toolbar/browser-source-toolbar.ui, UI/forms/source-toolbar/color-source-toolbar.ui, UI/forms/source-toolbar/device-select-toolbar.ui, UI/forms/source-toolbar/game-capture-toolbar.ui, UI/forms/source-toolbar/image-source-toolbar.ui, UI/forms/source-toolbar/media-controls.ui, UI/forms/source-toolbar/text-source-toolbar.ui
This adds spacing between the timer and duration labels in
the media controls. The vertical alignment of the labels
have been fixed as well. And the width of the source label
has also been widened.
Before:
After:
Makes the context bar visually look better.
Fixes #3374 
Looked at the labels to made sure it looked better.
- UI tweak
=> UI: Refine context bar

plugins/win-dshow/CMakeLists.txt, plugins/win-dshow/virtualcam-install.bat.in, plugins/win-dshow/virtualcam-uninstall.bat.in
This adds two batch scripts to install and uninstall the virtual cam
devices for installations where the installer could not be useed.
Most commonly, this is for portable installations or those who prefer
the .zip file.
We had several people ask how to register virtual camera on portable
installations with the RC for v26.
Tested the script logic for all scenarios on the installer:
- No cam registered
- Only 32bit registered
- Only 64bit registered
- Both already registered
- All the above in the root of the obs-studio folder
- All the above in the win-dshow plugin folder
Script functioned as expected. Tested uninstaller, devices were unregistered.
=> win-dshow: Add installer scripts for manual Virtual Cam registration

UI/media-controls.cpp, UI/media-controls.hpp, UI/media-slider.cpp, UI/media-slider.hpp
This allows the user to adjust the media slider with the left
and right keyboard arrows. It is currently set to adjust
by 5 second increments.
User mentioned on Discord they wanted this feature.
Used keyboard arrows to change media time.
=> UI: Allow adjusting media slider with arrow buttons

UI/media-controls.cpp
When there is no media, set the media to the restart state.
Currently, this only affects the VLC source, as the media
source doesn't use the OBS_MEDIA_STATE_NONE, at this time.
When VLC source is first loaded with no media, the media controls are enabled.
When creating the VLC source, I made sure the controls were in the correct state.
=> UI: Set restart state when there is no media

UI/window-basic-main.cpp
Update code to use an icon theme every time the tray icon is updated.
This is a follow up to #1736, which fixed only some instances of the tray being updated.
I like my icons neat and tidy so I just added the ones that remained.
Manually by running the app and checking the icon shows up and it's from the theme, basically
Bug fix, I'd say
=> UI: Ensure tray icon is themed in all cases

UI/window-basic-main.cpp
This fixes a bug where studio mode where it would transition
to the preview scene when loaded instead of using previous
program scene.
Fixes #2576
Set program scene in studio mode and restarted OBS. I then made sure the previous program scene was still the program scene.
=> UI: Fix studio mode load bug

UI/window-basic-main.cpp, deps/media-playback/media-playback/media.c, docs/sphinx/reference-libobs-media-io.rst, docs/sphinx/reference-outputs.rst, libobs/media-io/video-io.h, libobs/media-io/video-matrices.c, libobs/media-io/video-scaler-ffmpeg.c, plugins/decklink/decklink-device-instance.cpp, plugins/mac-avcapture/av-capture.mm, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c, plugins/obs-x264/obs-x264.c, plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/win-dshow.cpp
Change the default color setting in the UI from sRGB to 709, and VIDEO_CS_DEFAULT from 601 to 709.
Submodule PR: https://github.com/obsproject/obs-amd-encoder/pull/405
It seems like YouTube applies nonlinear-to-linear sRGB, and
linear-to nonlinear-709 transformations to uploaded videos now. This
makes sRGB too dark on their platform for video players that alias 709
as sRGB, which is almost everyone. Make 709 the default to keep peace.
Update VIDEO_CS_DEFAULT to 709 for consistency.
Debugger inspection of all changes.
=> Unify color space settings as 709

UI/media-controls.cpp
This removes duplicate code that is already in the
start/stop timer functions.
Code cleanup.
Played and paused media to make sure it still worked.
=> UI: Remove duplicate media timer code

UI/data/themes/Rachni.qss
This fixes a bug with the Rachni theme in which the virtual
camera button wouldn't change colors when active.
Enabled virtual camera button to made sure it changed colors.
=> UI: Fix vcam button not changing colors when checked

UI/scene-tree.cpp
This fixes a bug where the same scene would show up in
the multiview more than once when reordering scenes.
Bug fixing.
Reordered scenes by drag & drop and made sure the multiview looked normal.
=> UI: Fix scene tree event handling

deps/media-playback/media-playback/media.c
Fixes #3341 by ensuring timestamps are reset after pausing.
Adds a reset_ts call after waiting for semaphore if the media source was paused to ensure the timestamp is properly reset.
fixes the fast-forward component of #3341. The other component is agreed by the issue opener to be by design, so this issue can be considered resolved with this PR.
Verified that other state changes still function as expected.
- Bug fix (non-breaking change which fixes an issue
=> deps/media-playback: Fix fast-forward after reset

.github/workflows/main.yml
Updates macOS deps version to include most recent version, enabling `rnnoise` support on macOS.
Enable this enhanced noise reduction method on macOS.
* Build created on macOS
* `rnnoise` availability checked in filter options
=> CI: Bump macOS-deps version to include rnnoise

CI/full-build-macos.sh, azure-pipelines.yml
Fixes macOS builds failing on Azure by using new all-in-one script.
Homebrew deprecated installations from remote URLs a while back. This was fixed for Github CI and the new all-in-one script a while ago, but not for Azure CI which still uses the old scripts. This fix utilises the new script which is actively maintained and was rewritten from scratch (and is kept in lockstep with Github CI).
* Azure CI steps executed locally
=> CI: Fix Azure macOS pipeline to use new build script

plugins/obs-ffmpeg/obs-ffmpeg-output.c
Some codecs have no recommended pix_fmts so we must check that pix_fmts
is not null before trying to find a good match. This just prays whatever
OBS is configure for is a valid format when users choose these oddball
codecs. When its not you should get a normal recording fail instead of a
crash now.
fixes #3031
No longer crashes
Ran the replication steps from the bug after fix and it no longer crashes. Recording to mkv still seems fine.
=> obs-ffmpeg: fix crash with rawvideo

UI/window-basic-main.cpp
Previously this check would prevent you from using URL output if your
file output target was invalid.
Lets you record with valid settings.
Tested with missing recording directory and recording worked, switching modes back to file mode failed with the expected error.
=> UI: Fix recording check when using url output

.github/workflows/clang-format.yml
It is kind of pointless to have the Mac clang format check
when there is already one on Linux.
Remove unnecessary check.
No testing needed.
=> CI: Remove clang format Mac check

UI/window-basic-main.cpp
Earlier code calls enable on platform specific UI elements resulting in
crash since these elements are deleted on Linux.
I want to be able to debug linux users issues.
Uploading logs works again.
=> UI:Fix crash on log upload

deps/obs-scripting/obs-scripting-python.c
Returning PyObject with borrowed reference will result in double free
and/or use after free issue.
Issue seen as crash when running Python script calling script_path().
Fixes a memory bug that happens to Python script using the function script_path()
Fixes crashes and potentially nastier problems that are difficult for script developers to find.
Python script that previously would crash at reload and closing of OBS runs fine after change.
=> obs-scripting: Fix script_path() python memory corruption

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
This PR adds [Mux](https://mux.com) to OBS's list of preset streaming services. (I work at Mux on the developer experience team.)
The `services.json` file doesn't seem to actually adhere to the configuration in `/.editorconfig`, so I tried to make it consistent with the other services in that JSON file.
We at Mux have a lot of users who are using OBS; it'd be nice to make their lives a little easier.
Not having a C++ compiler handy on this machine, I loaded the changed `services.json` into the `plugin_config` directory on my local machine and tested streaming under both RTMPS and RTMP using the packaged version of OBS 25.0.8.
I've tested it on Fedora Linux 32, but it's only a JSON change so I can't see it acting any differently on Windows or a Mac.
- New feature (non-breaking change which …
=> rtmp-services: Added Mux to services.json

plugins/win-dshow/virtualcam-install.bat.in, plugins/win-dshow/virtualcam-uninstall.bat.in
Ensures the current working directory is set when running the VirtualCam install scripts to ensure they don't fail. Previously they'd silently fail, but removing the silent flag would return "Module not found".
Thanks to @ElectronicWar and @Gol-D-Ace on Discord for coming up with & verifying the fix.
The scripts would fail if run by admin, as the default path was system32. Failing scripts are no good.
Build OBS. Right click "Run as admin" one of these scripts from within the win-dshow folder.
=> win-dshow: Set current working directory in VirtualCam scripts

plugins/mac-capture/window-utils.h, plugins/mac-capture/window-utils.m
This pull request addresses the issue found [here](https://github.com/obsproject/obs-studio/issues/3146) where sources inside Windows Capture show system/icon windows as well. Upon investigating the issue, it appears that the problem is inside `plugins/mac-capture/window-utils.m`:
```
NSArray *enumerate_windows(void)
{
NSArray *arr = (NSArray *)CGWindowListCopyWindowInfo(
kCGWindowListOptionOnScreenOnly, kCGNullWindowID);
[arr autorelease];
return [arr sortedArrayUsingComparator:win_info_cmp];
}
```
The `CGWindowListCopyWindowInfo(option, relativeToWindow)` returns every single window that is onscreen. It just so happens that the icons such as those in the menu bar
are also considered windows, which have different `kCGWindowLayer` levels. The ones we're concerned with are found at the …
=> mac-capture: show actual windows in Window Capture sources

UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp, UI/frontend-plugins/frontend-tools/auto-scene-switcher-osx.mm, UI/frontend-plugins/frontend-tools/auto-scene-switcher-win.cpp, UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp, UI/frontend-plugins/frontend-tools/auto-scene-switcher.hpp
The xdisplay in the Linux scene switcher was never closed
when OBS exits.
Noticed the cleanup function was never being called.
Ran the auto scene switcher to make sure it still worked properly.
=> frontend-tools: Free xdisplay on Linux auto scene switcher

deps/media-playback/media-playback/media.c
Fix current time at not standard speed
obs_source_media_get_time would give 0 for every speed lower than 100%
On windows 10 64 bit with time showing in the media controls
=> deps/media-playback: Fix current time at not standard speed

plugins/linux-v4l2/v4l2-input.c
unlike other YUV based formats nv12 chroma plane has the same padding as
the luma plane.
ref: https://01.org/linuxgraphics/gfx-docs/drm/media/uapi/v4l/pixfmt-nv12.html
Fixes nv12 capture
fixes #3506
Tested using ffmpeg and v4l2loopback for capture.
`ffmpeg -re -loop 1 -i ~/SMPTE_Color_Bars.png -vf 'format=nv12' -f v4l2 /dev/video2`
=> v4l2-linux: Fix nv12 linesize

UI/log-viewer.cpp
Ensure log text (in non-English languages especially) in the Log Viewer is always treated as UTF-8 so that characters are always printed correctly.
Source names in Japanese weren't rendering correctly. On English systems, it'd print incorrectly from the get-go. On Japanese systems, it'd print correctly on first log, but on reboot would show incorrectly.
* Name a source `デスクトップ音声`
* View the log
* Restart
* View the log again
=> UI: Always parse log contents for Log Viewer as UTF-8

UI/platform-osx.mm, UI/platform.hpp, UI/window-basic-main.cpp
This patch reduces OBS' idle CPU usage by about 40-50% by removing the need to do expensive colourspace conversions for drawing the UI.
Profiling on macOS showed a high amount of calls made to colour conversion methods by Qt. The underlying issue (according to comments made in a Qt ticket I found https://bugreports.qt.io/browse/QTBUG-47660) seems to be that each time "the Qt backingstore is pushed to macOS, each pixel is color-rescaled by macOS" and also "macOS converts the 32 bit/pixel pixmap supplied by the Qt backingstore to a 64 bit pixmap, each time the backingstore is flushed to the screen".
Due to retina screen resolutions being default on macOS (and 10-bit colour on 5k iMacs), the size and bit-depth of these bitmaps is effectively "damn big", hence high CPU usage for these …
=> UI: Improve macOS performance by disabling Qt colourspace conversion

plugins/rtmp-services/rtmp-common.c
Currently in services.json, setting `bframes=(any integer)` disables b-frames. This PR sets b-frames to the integer value specified.
The current behavior is counter-intuitive. There will be no adverse/breaking changes since no service has b-frames set to a non-zero integer.
=> rtmp-services: Set actual integer value of bframes in services

UI/obs-app.cpp
As with Windows and macOS there's no need to check for ChromeOS on
FreeBSD.
Minor improvement to avoid unnecessary code on FreeBSD.
Built with change on FreeBSD and started OBS.
=> UI: Skip ChromeOS test on FreeBSD

.github/workflows/main.yml
Fixes current issue on CI where commit hash is added to `Info.plist` for macOS builds. When CI is triggered by a tag event, only the tag name/version is used instead.
* Ensures that Sparkle update checks work with version numbers and don't require the exact hash
* Tested on my own fork with a fresh tag
=> CI: Use tag number only for macOS plist when triggered by version tag

UI/window-basic-main.cpp
The tab order for the Virtual Camera and Replay buffer were incorrect. While appearing in the middle of the list, they functioned as the last items in the tab order
It was discovered during replication of bug #3524
An amendment of this pull request added in scope of fixing the tab order for the recording buffer buttons
This was tested by just tabbing through the control elements.
Enabling and Disabling the replay buffer has also been tested and tab order continues to work as intended
=> UI: Fix tab order for controls dock

plugins/rtmp-services/data/services.json
I've been reviewing and integrating new services to my project https://streamon.app and it seems like weabook.live is now a recipe app - no longer a live streaming provider.
If you try to use this service it will no longer work with OBS.
No changes to executable code
=> Remove weabook.live from services.json

.cirrus.yml
#3103 # Description
Track FreeBSD package rename.
FreeBSD removed the swig30 package and replaced it with just swig, currently version 4.0.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246613
Cirrus-CI build test run: https://cirrus-ci.com/task/5811192847400960
=> Update FreeBSD CI for package name change

plugins/obs-ffmpeg/obs-ffmpeg-mux.c
If using ffmpeg-mux to send a network stream, signal a disconnect error code
on error to allow reconnections to take place.
`srt://` custom destinations do not reconnect like `rtmp://` streams do, and as I added #3460 to report errors I found that the error that was returned wasn't the right one to cause reconnections to happen.
I streamed to an `srt://` custom destination, killed the remote destination, restart it, and OBS reconnected.
=> obs-ffmpeg: Signal a remote disconnect for network streams from ffmpeg-mux

plugins/coreaudio-encoder/windows-imports.h
Fixes issue https://github.com/obsproject/obs-studio/issues/3503
The path of coreaudio dll has changed in current versions of iTunes on windows.
The patch fixes the issue while keeping compatibility with previous path.
Fixes an issue.
Tbf I haven't sought to factor as much code as possible so the code could probably be more elegant.
Note that this fixes path issues for the desktop iTunes app; not for UWP iTunes.
Tested on windows 10, visual studio 2019.
The new path from iTunes is found in obs-studio.
=> coreaudio-encoder: Fix path on windows

UI/source-tree.cpp
Fixes #3465
#3465
Manual tested on desktop PC Windows 10 and added asserts to test (removed before check-in but I can add them back if requested). Test steps in issue.
No expected impact on other areas of code, one-line change.
Bug fix
Adds a setFocus() command when we re-insert the label after the QLineEdit editor has been removed. setFocusPolicy is only for editors so changing NoFocus to StrongFocus didn't work.
=> UI: After source rename, set focus back to label

docs/sphinx/reference-frontend-api.rst
Fixed a minor error in the documentation, the term lacked the EVENT keyword
A required change to improve documentation
Testing should not be neccessary
=> Docs: Fix Frontend Finish Loading event

.github/workflows/main.yml
Changes usage of `set-env` in GitHub Actions with the new syntax to set environment variables for later steps.
Github deprecates the `set-env` command: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
* Needs to be tested on CI
=> CI: Remove deprecated use of `set-env` in Github Actions

UI/window-basic-settings.cpp
Alters the settings window to prevent the user from disabling the Replay Buffer when it's currently active
I noticed that I could alter this, and it would not be reflected in the UI at all. This added some confusion to whether the application would still function as normal. While the replay buffer was still functioning, it was weird to see granted I had disabled it in settings.
By disabling the checkbox from being altered when it's active, it removes a source of confusion to the end-user
I have tested this in both Simple and Advanced recording mode. The checkbox remained locked when the replaybuffer was active, and returned to a modifiable state when it had been disabled
=> UI: Prevent disabling replay buffer if it's active

plugins/win-capture/get-graphics-offsets/dxgi-offsets.cpp, plugins/win-capture/get-graphics-offsets/get-graphics-offsets.c, plugins/win-capture/get-graphics-offsets/get-graphics-offsets.h, plugins/win-capture/graphics-hook-info.h, plugins/win-capture/graphics-hook/dxgi-capture.cpp, plugins/win-capture/load-graphics-offsets.c
Hook DXGI release function to release D3D objects if the related swap
chain is also being destroyed.
An added bonus is that the game capture hook will handle swap chain
recreation for applications that don't use ResizeBuffers.
User reported that swap chain recreation was not being handled properly.
In the process of reproducing the issue, decided to clean leaks.
When leaks were cleaned up, swap chain recreation was also fixed as a side effect.
- D3D10: Mega Man X Legacy Collection, windowed/fullscreen toggle
- D3D11: SimpleSample11, 32-bit and 64-bit, windowed/fullscreen toggle (swap chain recreate).
- D3D11: Mesen emulator, windowed/fullscreen toggle (ResizeBuffer and swap chain recreate paths).
- Verified ABI compatibility between old/new hook vs. new/old OBS using SimpleSample11.
- Bug …
=> win-capture: Fix D3D leaks on swap chain release

UI/adv-audio-control.cpp
Fixes: #3514
#3514
Manual tested on MacOS in all languages. No expected impact on other areas of code, one-line change. Test steps in issue.
=> UI: Fix text clipping on non-English locales in certain locations

UI/window-basic-status-bar.cpp
This shows the time with PAUSED label when recording is paused. Example: `00:05:21 (PAUSED)`.
With there being a pause icon now, I believe that it is more useful to just show the record time.
Paused recording and made sure that the label was shown properly.
- UI tweak
=> UI: Keep showing time label when paused

UI/window-basic-filters.cpp, UI/window-basic-filters.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, libobs/obs-source.c, libobs/obs.h
This adds the ability to copy and paste a single filter.
Users might want to copy a single filter, instead of all filters.
Copy and pasted filters.
=> UI, libobs: Add ability to copy/paste single filter

UI/window-basic-filters.cpp, UI/window-basic-filters.hpp
Add option to duplicate a filter
If you want multiple filters with almost the same settings you have to copy all properties of the filter 1 by 1, now you can duplicate the filter and only set the properties that are different in the new filter.
On windows 64 bit by duplicating multiple filters and testing you can not create 2 filters with the same name.
=> UI: Add duplicate filter

UI/obs-app.cpp, UI/platform-osx.mm, UI/platform.hpp
Added logic that checks on MacOS if there any other applications running with same [BundleID](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids).
fixes: https://github.com/obsproject/obs-studio/issues/3053
One instance of the app was started by clicking on the application icon from Finder, second instance was started from the terminal. As a result "dialog" appear which stated that another instance is already running.
Also tested that flag "--multi" works as expected.
=> UI: Detect other instances of OBS on MacOS

UI/window-basic-main-outputs.cpp
`AdvancedOutput::AdvancedOutput(OBSBasic *main_)` lacked a proper event handler connection which caused a bug where `OBS_FRONTEND_EVENT_REPLAY_BUFFER_SAVED` wasn't emitted in the advanced output mode.
A very simple bug-fix in the front-end API.
On Arch Linux VM with a plugin listening to the event.
=> UI: Fix replay buffer saved event in advanced mode

UI/window-basic-main-outputs.cpp
Same changes as 0c0ffb341cfb521473479cdcd391c3507b05cf46
**Before:**
**After:**
Consistency & usefulness. The Replay Buffer message remained generic while Recording and Streaming displayed informative errors.
* Switch to Advanced output mode
* Switch to NVENC and set GPU to 1
* Try starting the Replay Buffer
=> UI: Report detailed output errors for Replay Buffer

libobs/obs-data.c
Makes the return function's second parameter provide the `default` data. Ensured consistency with other \_get\_default\_ functions.
Fixes #3357
Call the API. Ensure returned data matches the default values.
=> libobs: Return default obj and array rather than current

.github/workflows/main.yml, CI/full-build-macos.sh
When generating a build environment that supports multiple build configurations (e.g. Xcode) the directory structure assumed by the build script for bundling might not exist.
This change introduces an additional environment parameter `BUILD_CONFIG` that allows to specify the build dir and falls back to `RelWithDebInfo` if not supplied.
Additionally the `brew update` command before `brew bundle` is now in sync with GitHub Actions and _might_ also fix current Azure CI issues with macOS.
When building/debugging OBS with Xcode, this change allows quick and easy bundling of the project e.g. by specifying the `Debug` build directory.
* Tested with an Xcode project and multiple build configs as well as no specific build config
- Code …
=> CI: Update macOS build script to support alternative build configs

plugins/obs-ffmpeg/obs-ffmpeg.c
Add MX350 to blacklist
This GPU does not have NVENC support
Confirmed device ID from NVIDIA. Compiled and ran OBS, but I do not have an MX350 device to validate against. No reason this should not work.
=> obs-ffmpeg: Add MX350 to NVENC blacklist

.github/workflows/main.yml, CI/install-dependencies-linux.sh, plugins/linux-v4l2/CMakeLists.txt, plugins/linux-v4l2/linux-v4l2.c, plugins/linux-v4l2/v4l2-output.c
Adds virtual camera output for Linux.
Based on plugin by @CatxFish with a refactoring of the code.
Windows already has a virtual camera built-in, so this adds Linux support.
Dependencies:
```
sudo apt install linux-generic
sudo apt install v4l2loopback-dkms
```
To run:
```
sudo modprobe v4l2loopback exclusive_caps=1
```
Ran OBS, started virtual cam and tested the camera in different programs.
=> linux-v4l2: Add virtual camera output

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add YouTube - RTMPS (Beta) to the service drop down.
YouTube Live is going to migrate to RTMPS. In order to do this in a safe manner, we are adding RTMPS as a beta option first to get some initial traffic. After verifying with the initial traffic, we will change the default URL for YouTube - RTMP to use RTMPS as well, and remove YouTube - RTMPS (Beta) option.
* Tested on macOS Catalina 10.15.7 against the YouTube RTMPS service.
* Verified that the stream health is good.
=> rtmp-services: Add YouTube RTMPS beta service

libobs/obs-nix.c
Add the content of the XDG_SESSION_TYPE environment variable to
the output log if it is set. This is usually set on modern Linux
distributions and typically carry either "x11" or "wayland" when
run from a desktop environment.
This is independent from the QT_QPA_PLATFORM environment variable
which would allow OBS Studio to run inside a wayland session. The
session type it runs on does have an implication on the behavior of
some plugins like screen and window capture. So having this
information exposed here is extremely helpful for diagnosing
issues.
Build and run on Linux with x11 and wayland sessions as well as a negative, from inside docker.
=> libobs: Add desktop session type to Linux log

UI/window-basic-main-outputs.cpp, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-x264/obs-x264.c, plugins/rtmp-services/rtmp-custom.c
Also changes obs-x264, obs-ffmpeg, rtmp-services.
Repetition of sps/pps and AUDs are mandatory for mpegts live streams per spec.
This PR enables that for srt streams with mpegts container. In addition it enables AUDs (x264/nvenc) and annex B option (x264).
For obs-x264, the repeat-headers option had previously been hard-coded to false; we set it to false on default to keep previous behaviour. But we now allow it to be settable in x264 options.
For obs-ffmpeg/jim-nvenc, we add a setting for video headers repetition.
Since srt is dealt with rtmp-custom service, when x264 or jim-nvenc is used with mpegts, we automatically enable the repeat-headers option.
**This fixes some connection issues for srt streams.** (i should have opened an issue to document the bug but I confess I've been a bit …
=> UI: Enable sps/pps (video headers) repetition (for srt/mpegts)

UI/forms/OBSBasicSettings.ui, UI/window-basic-settings.cpp
Disable stream encoder setting in Simple Output Mode if there is an active output.
We disable the stream encoder setting in Advanced Output Mode when an output is active, so let's also disable the stream encoder setting in Simple Output Mode when an output is active.
Without this change, a user can change the stream encoder setting in Simple Output Mode if there's an active stream, which can cause the encoder selection to not actually change when restarting a stream.
Compiled and ran on Windows 10 64-bit to verify that the stream encoder setting is disabled in Simple Output Mode when streaming is active.
=> UI: Disable stream simple output encoder when output active

plugins/vlc-video/vlc-video-source.c
The list of valid file extensions in the VLC Source was stored lowercase, and this check was being done with the assumption that filenames were too. This PR switches the check from case sensitive to case insensitive.
Fixes #3562
It's possible for files to have some/all characters uppercase. Such files were being ignored by the "Add Directory" option.
Create a folder with a .MP4 file. In the VLC Source, add the directory and see the file doesn't play (even after saving the Properties). After applying this change, try again - this time the file will play.
=> vlc-video: Use case insensitive compare for valid extension check

UI/window-basic-main.cpp, UI/window-basic-main.hpp
If the source toolbar is hidden, there doesn't seem to be any point in fetching and updating properties every time the source selection changes.
A user [ran into an issue](https://github.com/obsproject/obs-studio/issues/3673#issuecomment-719996332) caused by a source toolbar interaction with display capture. Even after hiding the source toolbar, the issue persisted which is somewhat unexpected behavior.
Toggled source toolbar on and off at various times with various sources selected and deselected, toolbar remained accurate.
=> Don't update the source context bar when it is hidden

plugins/linux-v4l2/v4l2-output.c
v4l2_outputparm includes unused fields, defined as
```
__u32		reserved[4]
```
Accesses to reserved[4] was out of bounds.  Fix this and simplify by
just zeroing the entire struct v4l2_streamparm instead.
Issue was reported as a Clang warning compiling on FreeBSD
So far, compile-tested on FreeBSD -CURRENT
=> linux-v4l2: avoid OOB write

UI/frontend-plugins/CMakeLists.txt, UI/frontend-plugins/decklink-captions/CMakeLists.txt, UI/frontend-plugins/decklink-captions/decklink-captions.cpp, UI/frontend-plugins/decklink-captions/decklink-captions.h, UI/frontend-plugins/decklink-captions/forms/captions.ui, libobs/CMakeLists.txt, libobs/obs-internal.h, libobs/obs-output.c, libobs/obs-source.c, libobs/obs-source.h, libobs/obs.h, libobs/util/bitstream.c, libobs/util/bitstream.h, plugins/decklink/OBSVideoFrame.cpp, plugins/decklink/OBSVideoFrame.h, plugins/decklink/decklink-device-instance.cpp, plugins/decklink/decklink-device-instance.hpp, plugins/decklink/decklink-source.cpp, plugins/decklink/linux/CMakeLists.txt, plugins/decklink/mac/CMakeLists.txt, plugins/decklink/platform.hpp, plugins/decklink/win/CMakeLists.txt, plugins/decklink/win/platform.cpp, test/cmocka/CMakeLists.txt, test/cmocka/test_bitstream.c
This is a WIP so it needs more cleanup and the windows STT -> caption stuff to be fixed.
Opening this as a draft to get feedback on the implementation.
Decklink sources now parse ancillary data that comes in over SDI. If there is caption data, we extract the cea708 caption data and forward that to obs using the newly added obs_source_output_cea708()
This data is then used in obs-output.c to stick the cea708 caption data to be interlaced into the encoder.
Here's some rudimentary UI.
Some productions that use OBS to stream have closed caption data on the SDI feed that they are already streaming. This allows them to send that to twitch directly without another service.
Used a hyperdeck mini with cea708 data to send sdi data to a decklink duo 2. This was then added as a decklink source. I …
=> decklink: Add ability to ingest/embed cea 708 captions

.github/workflows/main.yml
Removes caching/cache-restoration of prebuilt OBS-Deps and Qt. Apparently using `/tmp/obsdeps` as path for caching isn't entirely robust on CI, so extracting the cache failed in recent CI runs.
As both dependencies are available and downloaded from Github anyway, the caching for Github Action runs is unnecessary.
* Removes possible incompatibility/issues with building on Github CI
* Needs to be tested on CI
=> CI: Remove caching of obs-deps for Github CI

plugins/decklink/linux/CMakeLists.txt
Typo left headers as source files so required functions were never
compiled in.
fixes #3699
Makes decklink plugin loadable again.
Compiles on my machine. I dont have the decklink sdk so it fails to load due to that but I assume this fixes it.
=> decklink: Fix compiling on linux

plugins/win-capture/window-capture.c
Noticed a couple of unused variables, and removed them.
Don't like compiler warnings.
Compiler warnings are gone.
=> win-capture: Fix unused variables

libobs-winrt/winrt-capture.h, plugins/win-capture/game-capture.c, plugins/win-capture/window-capture.c
Fix various issues around warnings that I've noticed in win-capture.
Debugger inspection through modified areas. WGC and DX11 game capture both verified to still work.
=> More win-capture warnings

UI/obs-app.cpp, libobs/obs-nix.c, libobs/util/platform-nix.c, libobs/util/profiler.c, plugins/obs-outputs/librtmp/rtmp.c
This makes OBS compile and run on OpenBSD.
Note that audio&webcam input are available only via FFmpeg, since both JACK and PulseAudio do not work well, and V4L2 plugin contains a lot of Linux-specific code. This is subject to separate PRs.
OBS is great, and OpenBSD is great. They must work together.
Compiles and runs on OpenBSD/amd64, both 6.8 and CURRENT. Regression tests pass.
New-feature: OpenBSD support
=> Add OpenBSD support

UI/CMakeLists.txt, UI/obs-app.cpp, UI/platform-x11.cpp, UI/platform.hpp
This change is an attempt to fix 3053 on FreeBSD. This change detects other instances of the obs by creating a dummy thread named `OBS runonce`. This should be usable on FreeBSD and possibly compile on DragonFly.
Since the td_name detection happens before thread spawning. To account for the case that multiple OBS instances started simultaneously and they fetched the thread list at the same time, an exclusive file advisory lock would be acquired in open(), so that only one instance is allowed to scan the threads list of the current user.
To fix #3053 
Running OBS in the same user more than one time.
=> UI: Detect other instances of obs on FreeBSD

plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini, plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
The plugin only uses one of the locales defined, the other ones can be removed.
This also makes the plugin actually use the one remaining string.
A discussion on Discord revealed that most of the locales aren't used and the one that should be used isn't actually called. 
This addresses these issues.
Built successfully on my computer
macOS 11.0.1 Beta (20B5012d)
I'm honest, I didn't, cause I don't know how (I don't see how anything should have changed though). Edit: Since the Clang Format Check says its ok I'm ticking this field as well.
=> mac-virtualcam: Update locales

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
ffmpeg-mux does not notice if ffmpeg returns an error from
av_interleaved_write_frame() which means that OBS never knows if there is a
problem in ffmpeg.
This is the biggest issue for cases like srt:// or tcp:// streams that can
regularly fail. Without this change OBS never knows that something went wrong.
Only network streams are checked to prevent impacting potential transient
errors in recordings.
Also ignores the error "Invalid data found when processing input" (AVERROR_INVALIDDATA) to prevent transient errors.
This is a re-implementation of #3460 with more limited impact to only report errors for network streams.
I noticed that when using an `srt://` custom stream endpoint OBS, if there is an issue with the SRT connection, a message is printed in the logs saying the SRT connection …
=> obs-ffmpeg: Add error detection to ffmpeg-mux network streams

plugins/win-capture/app-helpers.c, plugins/win-capture/inject-library.c, plugins/win-capture/load-graphics-offsets.c, plugins/win-capture/plugin-main.c, plugins/win-capture/window-helpers.c
Fix rest of warnings when win-capture is /W4.
Exercised game capture code paths: inject/direct, 32/64, anticheat on/off.
=> win-capture: Clean up remaining /W4 warnings

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Allow the `EINVAL` error from ffmpeg to be treated as non-fatal and also enable error checking for non-network streams. This is a follow-up to #3737 and #3460.
After reviewing submitted log messages containing `av_interleaved_write_frame failed:` a pattern emerged of a few kinds of errors:
Invalid data coming from OBS:
```
08:49:14.392: [ffmpeg muxer: 'simple_file_output'] ffmpeg-mux: av_interleaved_write_frame failed: Invalid argument
08:49:14.392: [matroska @ 007a7840] Application provided invalid, non monotonically increasing dts to muxer in stream 0: -100 >= -300
```
```
14:46:51.550: [ffmpeg muxer: 'simple_file_output'] ffmpeg-mux: av_interleaved_write_frame failed: Invalid data found when processing input
14:46:51.550: [mpegts @ 00000230992b48c0] H.264 bitstream malformed, no …
```
=> ffmpeg-mux: Treat EINVAL as non-fatal and enable error checking for non-network streams

UI/platform-x11.cpp
Include pthread_np.h header and use pthread_set_name_np to fix build
on FreeBSD 12.1.  The Linux-compatible pthread_setname_np alias was
added later.
Fix build on older FreeBSD releases that are still supported by the FreeBSD project.
Build tested on FreeBSD 13 locally and on FreeBSD 12.1 in Cirrus-CI.
=> UI: fix build on older FreeBSD versions

libobs-opengl/CMakeLists.txt, libobs/CMakeLists.txt, plugins/mac-capture/CMakeLists.txt, plugins/mac-syphon/CMakeLists.txt, plugins/text-freetype2/CMakeLists.txt
Removes the Cmake directives to explicitly set the language of some plugins to `C` on macOS which breaks most recent `cmake` versions.
`Cmake` merged and released a change with version 3.19 that breaks building on macOS with our current `cmake` rules.
The change as explained in https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4780 now sets the language flag explicitly when `LANGUAGE` is set in `cmake` rules. This leads to the switch `-x c` being added to calls to `cc` or `clang` which then fails when the compiler meets an ObjectiveC file (as is the case in `libobs` and some other plugins.
According to one of `cmake`'s maintainers, the flag is supposed to _explicitly_ set the source code language, not which compiler is preferred. This PR removes all instances of setting the …
=> CI: Remove explicit LANGUAGE flags for cmake 3.19+

plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt, plugins/mac-virtualcam/src/dal-plugin/Info.plist, plugins/mac-virtualcam/src/dal-plugin/OBSDALDevice.h, plugins/mac-virtualcam/src/dal-plugin/OBSDALDevice.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.h, plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALObjectStore.h, plugins/mac-virtualcam/src/dal-plugin/OBSDALObjectStore.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.h, plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugin.h, plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugin.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALPluginMain.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.h, plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Fixes global namespaces issues in the DAL plugin that will arise when another DAL plugin based on the same example code is installed on the system.
ObjectiveC does symbol lookups at runtime, which means that two plugins can be loaded with identical symbol names. This leads to undefined behaviour as it is not defined which class/method will be used.
The issue was mentioned in https://github.com/johnboiles/obs-mac-virtualcam/issues/215 before and has been shown to interfere with the EOS Webcam Utility for macOS (which also didn't namespace its functions uniquely) https://github.com/johnboiles/obs-mac-virtualcam/issues/232#issuecomment-732318227.
Virtualcam tested locally with the plugin-version installed to check if there are still ambiguous symbols. …
=> mac-virtualcam: Fix global namespace issues in DAL plugin

plugins/obs-outputs/librtmp/rtmp.c
Log unhandled status description as debug level.
Certain RTMP status descriptions can contain stream keys. We don't want to log those normally, so log the description for unhandled status codes as RTMP_LOGDEBUG. If someone needs to debug an RTMP server's return messages, they can compile OBS with the RTMP Log Level set to RTMP_LOGDEBUG.
We don't want to log stream keys.
Compiled on Windows 10 2004 (Build 19041.630) 64-bit.  I ran a few test streams, but did not trigger this specific log line in this specific branch of the `if-else`.  I did some manual testing by doing some test logging before the `if-else`, and this syntax seemed fine.
=> obs-outputs: Log unhandled status description as debug level

UI/obs-app.cpp, UI/window-basic-main.cpp
This significantly simplifies the configuration setting's initial load.
This also fixes as issue where the source toolbar would initialise as "TextLabel" with enabled buttons if the user had not yet toggled the setting.
Fixes #3722
UX improvement.
The old `else` clause was not triggering an `UpdateContextBar()` if the user had never toggled the context bar's display. The new code makes it much clearer what will happen, and is more consistent with other settings.
On Windows 10.
* Delete the `ShowContextToolbars` entry in global.ini (or load a fresh OBS)
* Launch OBS
=> UI: Set default source toolbar visibility to true & simplify its setting initialisation

UI/window-basic-filters.cpp, UI/window-basic-filters.hpp
Instead of giving each filter that is loaded in the OBSBasicFilters window focus, only focus a single row on loading and still focus a new row on adding a filter.
Speeds up loading of the filter window with large number of filters
Prevents deadlock by not getting the properties of filters during OBSBasicFilters::UpdateFilters() which uses the source->filter_mutex
On Windows 64 bit by having a source with multiple filters with properties that load other scenes, scene items, sources and filters.
=> frontend-tools: Don't give every loaded filter focus

UI/window-basic-main.cpp
Save replay button stays at checked state on each click
Fixes #3116
Tested on macOS v10.15.7 multiple times with the steps to reproduce provided by the user
=> UI: Fix Save Replay button staying highlighted

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-d3d11/d3d11-texture2d.cpp, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h
This can be useful for reading from textures provided by middleware.
I'm working on game capture library, and this will allow cleaner integration.
See:
Library: https://github.com/LagFreeGames/LfgGameCapture
Plugin: https://github.com/jpark37/obs-studio/tree/lfg-game-capture
Textures are successfully wrapped and display correctly as part of game capture plugin.
=> libobs: Allow wrapping D3D11 object with gs_texture_t

UI/window-importer.cpp
Fix a few issues with importing scene collections
* Prevent name collision during scene collection import
* Prevent import failure for collections with slash in name
* Log success/failure for scene collection importer
The Scene Collection Importer for importing scene collections from other applications would attempt to set the new filename using the name of the scene collection. However, it would determine an unused filename, and then replace spaces with underscores, which could cause a name collision. This changes the importer to replace spaces with underscores first for the base filename, and then determine an unused filename.
Ultimately, I think that refactoring to use something like `GetUnusedSceneCollectionFile` from `UI\window-basic-main-scene-collections.cpp` for the filename …
=> Improve scene collection importer

.github/workflows/main.yml, CI/full-build-macos.sh
Adds `decklink-captions` to the fixups done by dylibbbundler.
Without the fixup decklink captions will still be linked against the dynamic libraries in `/tmp/obsdeps` in the build environment, which will crash the app in normal circumstances.
* OBS built and tested locally, then compared against version without the fix
=> CI: Add decklink-captions to dylibbundler fixups

UI/hotkey-edit.cpp, UI/obs-app.cpp, UI/slider-absoluteset-style.cpp
UI: Use Qt::MiddleButton instead of deprecated Qt::MidButton
Qt::MidButton has been deprecated since Qt4 and removed in Qt6.  It was replaced by Qt::MiddleButton, which is available in all versions of Qt5.  Building against Qt 5.15+ will produce compiler warnings when using Qt::MidButton, and warnings are bad.
https://github.com/qt/qtbase/commit/880cbf602701b0116ca1143d6d07ee8e7eb3f03f
https://github.com/qt/qtbase/commit/16e546e32fec393bc3b126f280114bcbfa7151ff
I compiled and ran OBS on Windows 10 Home 64-bit 2004 (Build 19041.630).  I bound "Start Recording" to my mouse's middle button, and tested the hotkey, and it worked fine.
=> UI: Use Qt::MiddleButton instead of deprecated Qt::MidButton

UI/properties-view.cpp
Previously sliders would not be disabled when the the obs_property was
disabled.
Fixes display of disabled sliders for plugins.
Tested on a branch of v4l2 which enables/disables properties.
=> UI: Fix disabled sliders

plugins/mac-virtualcam/src/obs-plugin/CMakeLists.txt, plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.h, plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm, plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Gives the MachServer of the mac-virtualcam a unique name which was forgotten in a previous commit (#3758)
@PatTheMav noticed he forgot to change this in his PR (https://github.com/johnboiles/obs-mac-virtualcam/pull/242#issuecomment-734944476), I hope this is what he meant.
He described all other details in his PR #3758, which is probably a way better explanation than what I could give.
Built locally on my machine (macOS 11.0.1, Intel), and tested that the virtual camera still works.
=> mac-virtualcam: Fix remaining global namespaces

plugins/vlc-video/vlc-video-source.c
Should fix #3695, which resulted in OBS crashing on exit if metadata was retrieved on a stopped VLC source. Why it only happened on stopped sources, I don't really know.
Not leaking memory and preventing crashes I guess.
It's been a bit tricky, because the crash didn't happen for me when I ran obs in Visual Studio, but after building the patched vlc-video source and adding it to a release build of obs the crashes stopped.
=> vlc-video: Free media struct

plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
This patch updates the DAL part of the macOS Virtualcam plugin to be a fat binary that includes both x86_64 and arm64 binaries.
This enables universal apps running on Apple Silicon to use the plugin (even while OBS is running as x86_64 under Rosetta).
This patch can probably be removed once all of OBS supports Apple Silicon (since I assume something like this will be the default for the entire build).
```
> file build/plugins/mac-virtualcam/src/dal-plugin/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam
build/plugins/mac-virtualcam/src/dal-plugin/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64] …
```
=> mac-virtualcam: Build a universal x86_64+arm64 binary for M1 Macs

UI/window-basic-interaction.cpp
Interact passes the Qt cursor position to sources without scaling it, causing the cursor position to be incorrect.
Fixes https://github.com/obsproject/obs-browser/issues/99
Interact is unusable when the cursor is in the wrong position.
Use a display on Windows or macOS with DPI scaling. Tested with 200% on Windows.
Load http://txt.wzd.li/cursor.html and move your cursor in the Interact window.
Attempt to select text or press buttons in any webpage using Interact.
=> UI: Scale Interact cursor position based on display DPI

deps/obs-scripting/obs-scripting-lua.c
This was implemented in python in #3286, but was not implemented into the lua scripting. Currently lua scripters can not disconnect from handlers
This will close #3841 
This direct solution has not been tested, but with how this is the same fix from python scripting, I do not believe there will be any discrepancies between implementations as the previous fix had been tested and implemented into a existing version of OBS
=> obs-scripting: Fix removing signal handlers in lua

plugins/linux-v4l2/linux-v4l2.c
The output functionality in the linux-v4l2 plugin assumes that /bin/sh is bash when checking whether the v4l2loopback module is installed, giving incorrect results and undesired console output when this assumption is violated. This patch fixes that.
When /bin/sh isn't bash, the existing system() call used to check for installation of the v4l2loopback module always returns success, whether or not it really is installed. This causes the "Start Virtual Camera" button to appear even when it can't work. The modinfo console output that also appears either way is a distraction from more important information in OBS's output.
I'm running Debian testing with dash as /bin/sh and have v4l2loopback-dkms installed. When I rename v4l2loopback.ko to something else to simulate it not being installed, …
=> linux-v4l2: Fix bashism in v4l2loopback detection

plugins/sndio/sndio-input.c
Replace it with the typical strerror for platforms that dont have full
posix support (freebsd/clang).
fixes #3835 
Fixes compilation on some platforms.
It still compiles on gcc and clang 11
=> sndio: remove strerror_l

libobs/obs-audio.c
Regression introduced by dc4e20500: while the stop detection is pending,
it should still return false so the rest of the discard code can run.
Otherwise, the source audio will remain in the buffer, lagging the
source and triggering audio buffering increases until max audio
buffering is reached.
This is at least one of the possible root causes of the catastrophic audio death that multiple streamers have experienced since at least 2018. It was reproduced by repeatedly toggling monitor mode for multiple sources.
[This script](https://gist.github.com/marcan/ac89490843389ee0919f2a56c9f5ff3a) using obs-websocket will repeatedly toggle monitor mode for certain sources (adjust `source_patterns` to taste). Running it with a couple RTMP media sources active will reproduce the original problem - you …
=> libobs: fix the pending stop trick

.github/workflows/main.yml
Updates CI build configuration for macOS to use Qt 5.15.2 and obs-deps 2020-12-11.
Update dependencies for OBS 26.1 release. Fixes several Qt-related issues in the app and ensures HLS streaming compatibility.
Qt 5.15.2 and the deps were tested with multiple local builds.
=> CI: Update macOS to Qt 5.15.2 and deps 2020-12-11

UI/source-tree.cpp
The (de)select signal can come from a obs_scene_enum_items which locks the scene. The Qt::QueuedConnection makes sure the (de)select is handled outside of that lock.
Fixes #3673
On windows 64 bit by replicating the bug in #3673
=> UI: Handle (de)select scene items queued

plugins/linux-jack/jack-wrapper.c
Bug fixes for linux-jack:
* Mark input ports as terminal type. This means latency compensation does not expect to find other output ports that the data flows out of.
* Fix a deadlock when shutting down the source. See the commit message for a detailed description.
* Fix the timestamp calculation, which was completely broken.
The deadlock bug was found at stack depth three trying to reproduce/fix a different OBS bug.
The port type fix is at the suggestion of the Ardour developers. It doesn't quite fix the latency compensation issues when capturing Ardour sessions with OBS for other reasons, but it's correct.
The timestamp calculation also was found due to its poor interaction with the OBS mixing code prior to #3863.
Switching scene collections from one with a couple JACK clients used to …
=> linux-jack: fix timestamps, deadlock on shutdown, and port type

UI/source-tree.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
As a result of d68484e7, the "Deselect" signal is never fired for sources that are being deleted, as by the time the queued invokeMethod comes around, the object has already been deleted. This already has visible side effects, as the context bar is not updated when deleting a scene item.
While we could fix this by putting context bar updates directly in the "Remove" signal handler, this is a bit of a hacky workaround as we risk running into the same issue that made d68484e7 necessary in the first place, and we may as well remove the queued connection from the deselect signal to get the same behavior.
Fixing the underlying issue that prevents synchronous calls to the context bar and other things seems very difficult due to the mutex locking order issues. So this PR is a compromise, adding …
=> UI: Add deferred function to update context bar

.github/workflows/main.yml, CI/full-build-macos.sh, CI/scripts/macos/helpers/helper-gpu-entitlements.plist, CI/scripts/macos/helpers/helper-plugin-entitlements.plist, CI/scripts/macos/helpers/helper-renderer-entitlements.plist
Adds necessary changes to package OBS with the planned updated CEF version 4183.
Chromium requires a multi-process setup on macOS which adds 4 new app bundles in the main app bundle's framework directory. These app bundles need to be signed with appropriate entitlements for notarisation.
*Note:* This PR will break until our build of CEF 4183 is made available on our CDN (might require another force-push if we move from S3 to our own CDN) and the obs-browser submodule has been updated with the appropriate commit for CEF 4183.
* OBS built, signed and notarised successfully
=> CI: Add necessary changes for CEF 4183

.github/workflows/main.yml, cmake/Modules/FindLibcurl.cmake
Coerces `cmake` to not find and use Homebrew `curl`.
Fixes https://github.com/obsproject/obs-studio/issues/3887.
Github Action runners seem to have Homebrew `curl` installed by default which is picked up by OBS' `cmake` run. This will link OBS against that `curl` installation which has a lot more further dependencies (among them OpenSSL) since Homebrew merged their `curl` and `curl-openssl` packages.
Even though `cmake` is supposed to prefer the library stubs provided by the platform SDKs, without this change it still prefers the version installed by Homebrew.
Needs to be tested via CI runs.
=> CI: Fix macOS 10.13 crashes and dependency incompatibilities

UI/window-basic-auto-config.cpp, UI/window-basic-auto-config.hpp, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Remove Smashcast from the services list.
Website dead, social media dead, ingest servers dead.
Submitted as draft to give them 7 days to return or respond before removal.
JSON is valid. OBS doesn't complain.
Service removal
=> UI/rtmp-services: Remove Smashcast

.github/workflows/main.yml, CI/full-build-macos.sh, CI/scripts/macos/Brewfile
Removes `libjack` and `fdk-aac` from default macOS builds to ensure compatibility with macOS 10.13.
With Homebrew deprecating macOS 10.13 but OBS still supporting it we need to build external dependencies ourselves. SpeexDSP is added to macOS-deps via https://github.com/obsproject/obs-deps/pull/44, `libjack` is removed (because it has too many dependencies we'd need to manually fix up) as well as `fdk-aac` as macOS' CoreAudio encoder has better quality.
OBS built created locally and tested, some more tests are pending with users of 10.13.
=> CI: Remove jack, speex and fdk-aac from default builds for macOS

plugins/image-source/image-source.c, plugins/image-source/obs-slideshow.c
Simply adds .webp files to the file browser's file filter.
OBS already supports WebP images, but they do not display in the file browser due to the filter excluding them.
Presently, users have to explicitly set the filter to `All Files (*.*)` or manually write in the path of their .webp image. There is also advice on the internet to use Browser Source to load .webp files, which is a subpar experience.
Used macOS Catalina (10.15.7) to build and run. Tested image slideshow and Image sources, loading a .webp image, using both the specific WebP file filter and the "All formats" filter.
=> image-source: Add webp to file filter

plugins/mac-virtualcam/src/dal-plugin/CMSampleBufferUtils.mm, plugins/mac-virtualcam/src/dal-plugin/Logging.h, plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALPluginMain.mm, plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Marks function parameters as unused, removing compiler warnings
These warnings bothered me in Xcode as they made real problems less clear.
Also less warnings = better, I suppose.
Successfully compiled (Xcode 12.2, macOS 11.1), warnings are gone.
=> mac-virtualcam: Mark parameters as unused

UI/window-basic-main.cpp
UI: Support fractional scaling for Canvas/Base size
Without this change, new profiles created on systems using a fractional scaling factor (e.g., 125%, 150%, 175%) will get an incorrect (X, Y) pair for the new canvas size. For a display with 125% scaling, OBS would set (1536, 864) instead of (1920, 1080). With this change, it will set (1920, 1080).
I noticed that new profiles created on my system, which has a 125% scaling factor, were being given a canvas size of 1536x864.  This seems to be an uncaught issue with fractional scaling and high DPI, and we should fix those.
I compiled and ran the current OBS git master on Windows 10 64-bit (Build 19041.685).  I verified that new profiles on my system are now created with a base/canvas size of 1920x1080 instead of 1536x864 as before.
- Bug fix …
=> UI: Support fractional scaling for Canvas/Base size

plugins/coreaudio-encoder/CMakeLists.txt
coreaudio-encoder: Set compiler flag for mingw before adding resource file. 
Before this change, the resource file is added to source list and compiler flag is added after it. While compiling with mingw toolchain `windres` resource compiler catches up the `-Wno-multichar' as an option which is unknow to it. This change fixes it. This flag was added in commit aa0e64b7c9c331f69a73f56c9b7fcc4d27bd72df
I have used msys2/mingw-w64 toolchain to test it.
=> coreaudio-encoder: Set compiler flag for mingw before adding resource file

libobs/obs-scene.c
Fixes bug where the lock state wouldn't be copied when duplicating
a scene.
Duplicated a scene to make sure scene items were still locked or unlocked.
=> libobs: Set lock state when duplicating scene item

docs/sphinx/reference-frontend-api.rst
I found that there where no docs added for #1910 and with some digging found the doc strings from the obs-websocket in https://github.com/Palakis/obs-websocket/pull/338 This simply puts the docs together so that others don't have to scry for them.
The docs where not added with the original commit, I've pulled together what appears to be documentation @Rosuav used in obs-websocket
On 26.1.0 Linux, I've confirmed that API treats the arguments as expected via a lua script. The only exception is `geometry` (other than it does fine with an empty string) as I cant find examples of the data to encode to pass it)
Documentation
=> docs/sphinx: Add missing obs_frontend_open_projector

plugins/image-source/obs-slideshow.c
This fixes a bug where the transition wouldn't work when playback
is randomized and restart on activate is used.
Fixes #3993
Created slideshow with randomize playback and restart on activation enabled. Switch to another scene and back and made sure the transitions were working as expected.
=> image-source: Fix slideshow transition not working when randomized

UI/data/themes/Acri.qss
Fixes text getting clipped by the padding applied to all Acri theme buttons by default by removing it from context bar buttons
Before:
After:
Currently the text on context bar buttons gets clipped on Acri due to the vertical padding applied to buttons, and the context bar being a fixed height that does not have room for it
Checked various source types on Acri
=> UI: Fix padding on Acri context bar buttons

plugins/rtmp-services/data/services.json
This adds the main ingest servers used by CamSoda to the list of available services
Some of our streamers said that having to enter the stream key and server is cumbersome, so we decided that it would be better if they are able to pick up part of that info from within OBS.
We tested this by replacing services.json in a couple of machines (and on my box with a fresh build of master at time of creating the PR)
=> rtmp-services: Add CamSoda service

.github/workflows/main.yml, CI/full-build-macos.sh, libobs-opengl/gl-cocoa.m, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h
Adds the necessary changes to make texture sharing available for `obs-browser` with compatible CEF versions (4183+).
Reduces CPU load for browser sources by using shared off-screen rendered texture from CEF.
Do note that with the new renderer and new patch the texture handle will change with every `AcceleratedPaint` call, which will regress performance on Windows a bit. macOS never had this feature before, so it's not an issue there.
Also note that for the time being `SendBeginFrame` crashes the GPU process on macOS, so CEF will render at its own frame rate with the plugin defaulting to the canvas frame rate on browser source initialisation. 
**Notes:**
* This PR is necessary to build OBS once https://github.com/obsproject/obs-browser/pull/252 is merged and the submodule updated to …
=> libobs: Add texture sharing support for macOS/OpenGL

UI/obs-app.cpp, UI/window-basic-settings.cpp
This enables in Settings the checkbox for hardware acceleration for Browser Sources in macOS.
This requires cef 4183 and the following PRs:
https://github.com/obsproject/obs-studio/pull/3933
https://github.com/obsproject/obs-browser/pull/252
Adds setting for hardware acceleration on macOS for browser sources.
Bring feature parity to macOS with windows.
Checked that hw acceleration is toggled on and off by checking/unchecking the newly available checkbox in Settings > Advanced.
-
=> UI: Enable HW acceleration switch for browser sources on Mac

libobs/graphics/graphics.c
fix crash
fix crash
yes
Bug fix
=> libobs: Fix gs_duplicator_get_texture function check

UI/properties-view.cpp, UI/properties-view.hpp, docs/sphinx/reference-properties.rst, libobs/obs-properties.c, libobs/obs-properties.h, plugins/obs-filters/color-correction-filter.c
Restore alpha support to color picker as a separate property type. This is one of several fixes for the color overlay feature in the color correction filter, which had some questionable math in it.
This is technically a breaking change since I'm tweaking the math, but I don't think many noticed the total regression in the first place, so I doubt this feature is widely used.
Doing a pass to redo the filters in linear space, and noticed this feature must have regressed when alpha was removed from the main color picker.
Color overlay works again. Verified chroma key did not regress.
=> Fix color overlay in correction filter, add color picker with alpha

libobs/CMakeLists.txt
not all symbols were satisified in libobs. This was noticable when building with '-DCMAKE_SHARED_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now'
This fixes #3924
Package build got fixed after applying this patch
=> libobs: Fix missing Linux libraries with certain flags

UI/obs-app.cpp, UI/obs-app.hpp, UI/window-basic-main-scene-collections.cpp, UI/window-importer.cpp
Refactor the scene collection importer to use `GetUnusedSceneCollectionFile` to maintain consistency with other scene collection filenames and also to handle all special characters.
To do this, I moved `GetUnusedSceneCollectionFile` to `UI/obs-app.cpp` where `GetClosestUnusedFileName` and `GetFileSafeName` are also located.  I am not sure if this is the best solution.  Perhaps we should create something more agnostic in obs-app like `GetUnusedFileAtPath` and leave `GetUnusedSceneCollectionFile` in-place, but have it call the new function.
Fixes #2566.
I compiled on Windows 10 64-bit 2004 (Build 19041.685).  To test:
1. Open OBS.
2. Create a scene collection with a name that has special characters.
3. Make a backup of the scene collection JSON file.
4. Delete the scene collection in OBS. …
=> Refactor importer to escape special characters in scene collection names

plugins/linux-v4l2/v4l2-helpers.c, plugins/linux-v4l2/v4l2-helpers.h, plugins/linux-v4l2/v4l2-input.c
This pull request adds the following debug output improvements:
* Timeout errors are now LOG_ERROR instead of LOG_DEBUG. This made it hard to track down video device timeout issues.
* Additional diagnostic debug output, showing frame buffer states.
* All video data stream outputs are now prefixed with the name of the device for easier readability.
* Added DEBUG output that prints all buffer states when a timeout occurs.
This pull request is the result of many days of work trying to debug issues with my USB, HDMI video capture devices. 
It improves the error output. Without the patch OBS was completely silent when the HDMI capture devices were freezing. Now it will indicate that the video capture devices are timing out and print which device it is. The added debug output is even more …
=> linux-v4l2: Improve error and debug logging

UI/context-bar-controls.cpp
I guess I might as well push this out here, at least as a draft, for a bit of review and suggestions for improvement.
This adds a check for 'null' in 'mod' and simply 'return' if it's there, to prevent a segmentation fault.
This prevents a segmentation fault when, for example, an ALSA source is selected, and adds ALSA devices to the Source Toolbar (this could most likely be done better).
This also fixes the following issue: https://github.com/obsproject/obs-studio/issues/3485
Tested building and running OBS Studio with all sound backends disabled, as well as with both, or only one of ALSA and PulseAudio enabled on Gentoo Linux.
I don't actually ever use PulseAudio, so more testing with that would be nice.  I can only say that I saw more sources available with it installed.
- Bug fix …
=> UI: Fix crash in Source Toolbar

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add Glimesh to the list of supported stream services, using its FTL ingestion endpoints. Also includes the Get Stream Key button shown to users when the Glimesh service is selected.
Glimesh is a new live streaming platform launching soon, due to the ongoing deprecation of the FTL protocol from OBS we want to ensure we can get Glimesh support landed without hassle. We've solidified all of our ingest server regions and have confirmed they all have connectivity. This services addition should serve us through our launch.
Tested changes on Mac OSX and Windows.
I also noticed some service updates include a change to the `plugins/rtmp-services/data/package.json` and some do not, if that is required for this pull request please let me …
=> rtmp-services: Add Glimesh service

plugins/obs-outputs/ftl-stream.c
When connection to FTL ingest is lost, ftl_event() calls
obs_output_signal_stop() to trigger a reconnect. However, during the
reconnect delay, send_thread is still waiting on send_sem semaphore.
After the delay, ftl_stream_start() is called, which in turn resets
the semaphore and creates a new send_thread. Old send_thread now exits
the loop and triggers another reconnect and the whole process repeats
again. The fix resets the semaphore in ftl_event() so the old
send_thread exits immediately.
Please let me know if there is a better way to fix the issue, as my
understanding of the reconnect process might still be lacking.
Reconnecting to YouNow FTL ingest would keep retrying and disconnecting 
every few seconds (as set by retry delay) without ever succeeding.
Tested with YouNow FTL ingest …
=> ftl-stream: Fix reconnect loop on FTL ingest disconnect

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Reconnect live input stream (e.g. RTMP) after it was disconnected.
Live input stream can't reconnect even there is a reconnection feature was implemented, the reason is we are setting `close_when_inactive = false` for continueous living stream, but we still need the reconnection.
Testing in my local machine, with connect and disconnect RTMP streams.
- Bug fix
=> obs-ffmpeg: Fix media sources not reconnecting properly

UI/window-basic-main-outputs.cpp, plugins/obs-outputs/ftl-stream.c
This change allows users to use the FTL protocol when choosing a custom streaming service. By providing a URL starting with `ftl://` in the custom server field, the `ftl_output` plugin is chosen to handle transmitting stream data instead of `rtmp_output`.
Thank you for your time in reviewing this change!
In order to stream via the FTL protocol to a host that is not included in the curated list of streaming services, a user must [manually update](https://github.com/Glimesh/janus-ftl-plugin#streaming-from-obs) `services.json` with a service listing that specifies the `ftl_output` output.
Along with some folks at Glimesh.tv, I have been building an [open-source FTL ingest server](https://github.com/Glimesh/janus-ftl-plugin), and this change greatly simplifies the process for streamers to …
=> UI: Support FTL URLs for custom streaming service

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main.cpp, docs/sphinx/reference-frontend-api.rst
This adds functions to the frontend api to start/stop the virtual
camera, to check if it is active and adds function to get the output
reference. It also adds api events for when the virtual camera is
started or stopped.
The other outputs have frontend api functions, so the virtual camera should as well.
Tested by creating a script to call the functions and using the api events.
=> obs-frontend-api: Add frontend api functions for the virtual camera

plugins/rtmp-services/twitch.c
Updates the Twitch inject endpoint for the "Auto" server option to use the officially documented API.
Fixes #3943
Verified the code path was hit and returned the correct result, and that the stored list was updated.
=> rtmp-services: Use official Twitch endpoint to fetch ingests

UI/window-basic-main-screenshot.cpp
This uses the existing config bool SimpleOutput/FileNameWithoutSpace when saving screenshots.
Screenshot filenames contained spaces even when the checkbox for "Generate File Name without Space" was checked. This was surprising.
Built and tested by saving a screenshot and checking the filename.
=> UI: Use FileNameWithoutSpace for screenshot output

libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-dispatch.cpp
Functionality is coming in a future Windows update to disable the yellow
border when using WGC. Add code now to opt in. Will require SDK upgrade
later for OBS build.
winrt::apartment_type::multi_threaded is necessary to dodge assert for
calling get() on RequestAccessAsync result. Don't think I will ever
fully understand COM apartments.
Also fix a race crash discovered during testing.
Everyone hates the yellow border.
Tried capturing an application that used to show a yellow border, and it doesn't anymore.
=> libobs-winrt: Disable WGC border on insider SDK

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Adds ability to start and stop the virtual camera from the
system tray.
https://ideas.obsproject.com/posts/1297/add-start-virtual-camera-option-to-tray-menu
Tested by clicking the system tray action to make sure the virtual camera started and stopped properly.
=> UI: Add virtual camera to system tray

UI/window-basic-main.cpp
Allow to load obs plugins from custom directory, specified by
OBS_PLUGINS_PATH and OBS_PLUGINS_DATA_PATH environment variables.
Example usage:
`OBS_PLUGINS_PATH=/opt/lib/obs-plugins OBS_PLUGINS_DATA_PATH=/opt/share/obs/obs-plugins obs`
It's required to make it possible to package obs plugins using guix and nix package managers. Because in those package managers every package has it's own directory with the result of the build, it's not possible to relocate plugin's binaries to obs directory.
It will help to solve: https://github.com/NixOS/nixpkgs/issues/77627
Tested on Guix GNU/Linux, kernel 5.10.3, x1 yoga 4th laptop
- Built a patched obs package for Guix GNU/Linux
- Built wlrobs and specrtralizer plugins
- Set enviroment variables, checked with strace that plugins are loaded and work as …
=> Load plugins from path specified by OBS_PLUGINS_PATH

CI/before-script-linux.sh, CI/full-build-macos.sh, CI/install-dependencies-linux.sh, azure-pipelines.yml
I've manually gone through and fixed stray mentions of `CEF_BUILD_VERSION` and replaced them with `LINUX_CEF_BUILD_VERSION` and `MACOS_CEF_BUILD_VERSION` respectively. This should, theoretically, fix a number of build conditionals.
Seems @DDRBoxman missed a few.
Parent commits: 30569777378c713e153845ae80bd8022c4d02666 and 410c60e799f76aa413305e3cce10347d8f0a00f5
I'm marking this as "Seeking Testers" to check that the CI build succeeds, and then will ask @dori4n to test.
=> CI: Fix CEF version for both Linux & macOS

plugins/obs-outputs/CMakeLists.txt
Related #3834
Fixes #3881 
To support FTL, it needed to be present in-tree to be compiled. This PR adds support for system-wide installations of libftl. 
It uses pkg-config to find the system-wide installation. 
If pkg-config can't provide `libftl` we just fall back to using the in-tree submodule. 
If that's also not available it won't be included at all like before.
The OBS Studio package on Arch Linux does not come with FTL support, as both FTL-SDK and OBS Studio lacked the capabilities to use system libraries. (See [[1]] [[2]])
The former was solved by a [fork][3] as development stopped (The company behind it, Mixer, is not operating anymore). This PR should fix the latter problem upstream, instead of having to maintain patchsets in Arch Linux.
I tested this on my Arch Linux machine. I …
=> obs-outputs: Use system-wide FTL-SDK if present

deps/jansson/CMakeLists.txt, deps/libcaption/CMakeLists.txt, deps/libff/CMakeLists.txt, deps/obs-scripting/CMakeLists.txt, deps/obs-scripting/obslua/CMakeLists.txt, deps/obs-scripting/obspython/CMakeLists.txt
Bump CMake minimum version required to 2.8.12 for all subprojects.
CMake 3.19 has begun emitting a deprecation warning that support for CMake 2.8.12 will be dropped in a future CMake release.
> CMake Deprecation Warning at deps/obs-scripting/obslua/CMakeLists.txt:1 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
Warnings are bad.
The lowest minimum any subproject supported before this was 2.8, so bumping a patch version number shouldn't cause issues.  Also, the OBS root CMakeLists.txt requires CMake 3.10, and 3.16 on Windows, so having the lower 2.x versions on the …
=> deps: Update cmake_minimum_required to 2.8.12

UI/window-basic-main.cpp
As macOS will not logging crash internally, crash related action in menu shall removed temporarily until macOS support internal logging
#3019 stated macOS doesn't have internal crash report. Instead, macOS are using system crash log 
Tested by clicking menu in macOS
=> UI: Fix mac can't use crash report in menu tab

.github/workflows/flatpak.yml, CI/flatpak/com.obsproject.Studio.json, CI/flatpak/ffmpeg-libsrt.patch
This pull requests adds a new workflow to generate a Flatpak manifest. The workflow is limited to the master branch, and pull requests with the "Seeking Testers" label. Only in-tree plugins are included.
This is only the very minimal setup that's able to produce such bundles. The workflow is explicitly named "experimental" for now, because ALSA is disabled in the Flatpak bundle, and JACK depends on PipeWire 0.3.
(Side note: I made this while preparing to investigate various CEF-on-Linux problems. The bundle contain CEF and the Browser plugin is enabled.)
The Flatpak bundle improves testing compared to the current setup that generates a Debian package, mostly because it is not limited to Debian-based systems.
The new CI workflow generates a Flatpak bundle file that can be downloaded via …
=> Initial Flatpak CI support

docs/sphinx/reference-libobs-util-platform.rst, libobs/obs-module.c, libobs/util/platform-nix.c, libobs/util/platform-windows.c, libobs/util/platform.h
This PR implements a new platform function, `os_is_obs_plugin` that returns true if passed a path to a DLL that exports `obs_module_load`. 
Many OBS plugins (and OBS itself) ship dependent DLLs alongside the plugin DLL. On startup, OBS would load the dependent DLLs only to realize they aren't a valid plugin file and free them. This has an impact on the startup time, potentially confuses users with "obs_module_load not found" messages in the log, and may cause side-effects in the OBS process if the loaded DLL performs initialization in DllMain.
I ran OBS with a bunch of plugins installed, code correctly identified them as plugins and loaded them.
Plugins compiled with non-standard compilers / PE packers / etc may have a risk of being misidentified. I couldn't find any such plugins during …
=> libobs: Add os_is_obs_plugin function

UI/hotkey-edit.hpp, UI/window-importer.cpp, UI/window-remux.cpp
UI: Replace deprecated QLayout->setMargin with setContentsMargin
QLayout->setMargin has been deprecated since Qt 5.13 (though marked obsolete since at least Qt 4.8) and removed in Qt6. It was replaced by QLayout->setContentsMargins, which is available in all versions of Qt5. Building against Qt 5.13+ can produce compiler warnings when using QLayout->setMargin, and warnings are bad.
https://doc.qt.io/archives/qt-4.8/qlayout-obsolete.html
https://doc.qt.io/qt-5/qlayout-obsolete.html
https://github.com/qt/qtbase/commit/d6d33f0b80dd85043c71f71a3ed5485d6014e6c4
https://github.com/qt/qtbase/blame/5.15.2/src/widgets/kernel/qlayout.h
I compiled and ran OBS using Qt 5.15.2 on Windows 10 Home 64-bit 2004 (Build 19041.630) with and without these changes and compared UI elements that had used the old …
=> UI: Replace deprecated QLayout->setMargin with setContentsMargin

UI/window-basic-settings.cpp
The "fullName" property was filled only in case of exceeding TRUNCATE_TEXT_LENGTH. The length now is 80 chars. Also search function had worked only with item->text() what was the reason of maximum search length in Hotkeys Filter(Setting->Hotkeys).
The following changes allow to search in filter without the length limit of string along with the current functionality.
The issue is well described here https://github.com/obsproject/obs-studio/issues/3902
The bug has been reproduced and changes have been tested on 5.4.0-58-generic #64~18.04.1-Ubuntu  
=> UI: fix the maximum search length of Hotkeys Filter

plugins/mac-avcapture/av-capture.mm
This adds additional capture presets, including 3840x2160 and 1920x1080, in addition to the preset "High." There's no reason these can't be supported, they just haven't been added.
Newer capture hardware is capable of supporting these capture modes, so there's no reason that I can see to not include them.
Verified the capture is successful on a MacBook Pro running macOS Big Sur Public Beta (11.2 - 20D5029f) when paired with an Elgato HD60 S+ interface over USB.  This interface could only capture 4K at 30fps, which I verified using a 4K/30Hz source. 1080p@60Hz capture was also verified.
=> mac-avcapture: Add additional capture presets

libobs/util/platform-windows.c
Fix recently added leak.
Leaks are bad.
OBS now reports 0 leaks.
=> libobs: Fix dstr leak

plugins/obs-filters/data/chroma_key_filter_v2.effect, plugins/obs-filters/data/color_correction_filter.effect, plugins/obs-filters/data/color_key_filter_v2.effect
GLSL does not auto-promote float to vector where HLSL does.
Filters broken on Linux.
Filters not broken anymore on Linux.
=> obs-filters: Fix pow arguments

libobs/obs-hotkey.c, plugins/linux-v4l2/v4l2-input.c
Sets the thread name for the hotkey thread. Name chosen to match the graphics thread naming.
Sets thread name for the v4l2 capture thread.
Currently these threads are either unnamed or inherits the main libobs name which can be marginally confusing.
It compiles and gdb shows the right thread names.
=> libobs, linux-v4l2: Set thread names

UI/window-basic-main.cpp, plugins/linux-v4l2/linux-v4l2.c, plugins/linux-v4l2/v4l2-output.c
Expand PATH for Debian-like systems.
Moves v4l2 module checks together.
Improve detection when the module is already loaded.
Fix crash when systray is not enabled
Improve life for everyone.
Tested on dkms systems with and without modprobe on path. Systray check looks other similar checks for systray elements.
=> UI, linux-v4l2: Assorted fixes

UI/volume-control.cpp, UI/volume-control.hpp, UI/window-basic-main.cpp
Close context menu on destroy of VolControl
Fix crash of OBS
Steps to reproduce:
- open context menu of a volume control
- use hotkey to switch to a scene without the source you have the context menu open for
- click properties or filters option in the context menu
On windows 64bit by replicating the steps above.
=> UI: Close context menu on destroy of VolControl

docs/sphinx/reference-modules.rst, libobs/obs-module.c, libobs/obs.h
This adds a function to find module library.
Co-authored-by: @Palakis
In order to easily find the library file needed to load the browser panels on Linux, these functions were added. This should work on Mac and Windows as well.
Used code made by @Palakis, as they were trying to make Linux browser panels work as well.
Tested with https://github.com/obsproject/obs-browser/pull/254
=> libobs: Add function to get module lib

.github/workflows/flatpak.yml
Use the KDE image for Flatpak CI
The KDE images comes with the SDK needed pre-installed and should avoid re-downloading/installing it everytime. This should hopefully reduce the build time by a few minutes 
Details at https://github.com/bilelmoussaoui/flatpak-github-actions#docker-image
It needs the Seeking Testers label to be tested, since the Flatpak workflow skips pull requests without it
=> CI: use a KDE image for Flatpak

UI/forms/AutoConfigStreamPage.ui, UI/forms/OBSAbout.ui, UI/forms/OBSBasic.ui, UI/forms/OBSBasicFilters.ui, UI/forms/OBSBasicInteraction.ui, UI/forms/OBSBasicSettings.ui, UI/forms/OBSBasicTransform.ui, UI/forms/source-toolbar/game-capture-toolbar.ui, UI/forms/source-toolbar/media-controls.ui, UI/forms/source-toolbar/text-source-toolbar.ui, UI/obs-app.cpp, UI/window-dock-browser.hpp
When marking a widget as native, Qt makes part of the widget hierarchy native as well. This is for historical reasons, at least on Linux, mostly to match how X deals with frame and input windows.
However, this doesn't play well with QtWayland. As a preparation for Wayland, let's disable this behavior.
All credits go to @davidedmundson.
This way of creating native widgets makes OBS Studio behave poorly on Wayland.
Run OBS Studio and make sure everything looks correct, specially with the previews.
=> Cleanup native widgets

libobs/obs-scene.c
Duplicate source name for private sources in scene
Allows for identification of sources in studio mode.
Makes it like scenes and filters that keep there name when duplicated
On windows x64 with the move transition plugin
=> libobs: Duplicate source name for private sources

deps/libcaption/CMakeLists.txt
libobs headers depend on libcaption headers. So ensure they are
installed with obs' headers.
fixes #3925
Installing it lands in <caption/caption.h> as expected.
=> libcaption: Fix header missing in install

plugins/linux-capture/xcompcap-main.cpp
In case no-one else initializes X11 locks do this as part of loading the
module.
Fixes #3479
Tested on master with a handful of sources and on top of some other PRs and everything continues working as expected.
=> linux-capture: Ensure locks are initialized

UI/obs-app.cpp, UI/qt-wrappers.cpp
Re-enable native file pickers in Linux when the browser plugin is enabled.
After the recent CEF upgrade, it seems Chromium doesn't conflict with GMainLoop anymore, so the reason to disable platform native file choosers, and the GLib mainloop integration, is gone.
Build with the browser plugin, add a Browser source, and open any file using OBS Studio.
=> Re-enable native filepicker

deps/libcaption/CMakeLists.txt, libobs/obs-scene.c, libobs/obs-scene.h
Removes prior attempt to expose libcaption headers which really shouldnt
have public. This instead moves the obs-internal include out of the
public obs-scene.h and into it's implementation.
Lets people build plugins with the public headers again.
Built OBS.
=> libobs: Fix leaking obs-internal.h

plugins/linux-v4l2/v4l2-output.c
While the current code only ever calls try_connect() with the input
argument 'device' in the range of 0 and MAX_DEVICES, this adds a check
to ensure that future code does not break the following sprintf.
In addition, use snprintf instead of sprintf to ensure that if anything
breaks, the sprintf does not lead to memory corruption. Again, the new
check should already make sure of that, but the additional effort of
using snprintf instead of sprintf is so low that it is worth to have a
little more security in the future.
Device detection still worked with this change.
This used current-git-master on a Debian 10 system,
even with a self-compiled v4l2loopback module outside
of the main kernel tree.
- Code cleanup (non-breaking change which makes code more secure)
=> linux-v4l2: added range check for try_connect()

plugins/obs-outputs/librtmp/rtmp.c, plugins/obs-outputs/librtmp/rtmp.h, plugins/obs-outputs/rtmp-stream.c
This commit splits RTMP_Init off into a new RTMP_Reset function, which resets the internal connection state variables without re-initing the rest of the library.
The original RTMP_Init calls the new function, perfectly preserving the old behaviour while adding a new reset function to address the issue with.
Fixes #2865 (RTMP reconnects fail).
Bug is caused by the internal connection variables not being reset on reconnect, leading OBS to both be unable to parse valid packets from and send valid packets to the remote end.
Tested using portable mode install against an unpatched media server (specifically: MistServer), by streaming to localhost on a Linux machine. Bug can no longer be reproduced by me with this commit applied. Since the only changes to the RTMP connection are local variables …
=> obs-outputs: fix RTMP reconnect (fixes #2865)

UI/obs-app.cpp, UI/obs-app.hpp
This PR adds a new launch parameter, `--disable-high-dpi-scaling`, that, when present, will disable Qt's high DPI scaling functionality.
As outlined in #4058 I, and a few people I've talked with, were impacted by the fix that came in a newer version of Qt causing our scaling to be "broken" (rather, it was fixed, but broken for our use case) and our workflow to be impacted by it.
With this new launch parameter we can stay up-to-date on OBS again and continue with our usual streaming procedures.
I've tested and compared the scaling against 26.0.2 and 26.1.1 both with and without the new launch parameter and the results are as expected.
=> UI: Add launch parameter to disable high-DPI scaling

plugins/linux-capture/xcompcap-helper.cpp, plugins/linux-capture/xcompcap-helper.hpp, plugins/linux-capture/xcompcap-main.cpp
This PR fixes the **three Problems** reported in #3040 that have been found in the Window-Source (XComposite) of the linux-capture Plugin:
TL;DR Video: https://mazdermind.de/dl/github/obs/3040/2.mp4
When a selected Window is closed, OBS randomly chooses another Window of the same Application (for example any other Browser-Window) if the initial window is closed. Because of that restoring the, maybe accidentally closed Window, will not restore it in the Scene.
The reason for this is, that if no Window of the selected ID can be found, a search based on the Window-Title or the Window-Class is started (See [Lines 242-244 of xcompcap-main.cpp](https://github.com/obsproject/obs-studio/blob/fd66869/plugins/linux-capture/xcompcap-main.cpp#L242-L244) for the quite convoluted comparison). If no …
=> linux-capture: Fix Problems with the Window-Selection of the XComposite Source

libobs/obs-audio.c, libobs/obs-source-transition.c
This change makes the OBS mixing tree robust against sources with lagging audio. When a source lags beyond the ability to be synced by the audio buffering, only that source will be affected, not the entire mix. df4eb82 fixed a pathological bug that made this happen persistently for a given source and caused OBS audio output to completely fall over; this change addresses the underlying issue that a single misbehaving source breaks global audio output, transiently or not.
Historically, `warning: Max audio buffering reached!` has been treated as some kind of inherent deeply-seated problem; once you get that message all bets are off and restarting OBS is the only solution. This is despite the fact that there are many situations where getting that message does *not* result in persistent …
=> Make audio mixing robust against lagging sources

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, docs/sphinx/reference-frontend-api.rst
Adds a new api function `obs_frontend_reset_video()` which calls the internal `ResetVideo()` UI function to reload the video with any new settings. Useful when changing video settings via plugins.
This is required in order to implement a new request `SetVideoSettings` into obs-websocket. When profile settings are changed, we must be able to reset the video in order to apply them. `obs_reset_video()` only resets the libobs side and as such is not useful.
Been using this in combination with a private obs-websocket branch for almost 6 months now to adjust video settings over websocket. OBS running on Ubuntu 20.04 Desktop
=> UI: Add obs_frontend_reset_video() function

plugins/rtmp-services/data/services.json
Updated recommended settings for Piczel.tv service, added aq-strength=0 to x264opts
Setting aq-strength=0 allows Firefox to play WebRTC Streams
JSON is valid, settings appear to work with OBS
=>  rtmp-services: update Piczel.tv recommended

plugins/win-dshow/data/locale/en-US.ini, plugins/win-dshow/win-dshow.cpp
A new toggle has been added to DirectShow's plugin video capture settings to allow enabling/disabling autorotation of the video source.
I'm trying to use a Logitech StreamCam to record my desk. This camera sends rotation information that is then used by OBS's DirectShow plugin to rotate the video (think it's currently [the only camera that does this](https://github.com/obsproject/libdshowcapture/blob/afca513c7ad555e273a55eaa9ab9bc9447218d49/source/device.cpp#L264) 😅).
Because of the camera position (top view of my desk, with the lens in parallel to it), the rotation sensor goes crazy, being triggered by the lightest touch to the desk (or even on its own). You can check the issue on [this video](http://www.youtube.com/watch?v=042OG-OEot0).
[![Autorotation …
=> win-dshow: Add autorotation toggle

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
This leads to a crash when the output is stopped, either by clicking the
stop button or when exiting OBS studio.
Example with clear trace: https://obsproject.com/logs/UokqjcvadJ9pEesu
This crash is:
- rare in release builds
- reliable for me (100% so far) in debug builds
It is held by an `OBSData`, which, if not null, will automatically
call `obs_data_release()` on scope exit.
Fixes a crash.
1. Tools -> Decklink Output
2. Enable autostart of main output
3. restart obs
4. Tools -> Decklink Output
5. click 'stop' by main output
output reliably stops without a crash
- release builds: intermittent crash (say 10% of the time)
- debug builds: reliable crash (appears to be 100% of the time)
Windows 10 Pro x64 10.0.19042
DeckLink Mini Monitor 4k
Visual Studio 2019 16.8.4
Qt 5.15.2
- Bug fix …
=> decklink-ui: fix double free of settings

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp, plugins/rtmp-services/data/services.json
add streaming service "OPENREC.tv" into "plugins/rtmp-services/data/services.json".
add stream key link for "OPENREC.tv"
This change allows users to stream without complicated operations.
- JSON is valid
- I confirmed that it works after build. I checked on Mac and Windows.
=> rtmp-services: Add OPENREC.tv service

UI/window-basic-main-transitions.cpp
This adds a menu item in the transitions config menu to access
filters for stinger transitions.
Users have requested filters for stingers.
Applied filters to stinger transitions to made sure it worked.
=> UI: Add ability for stingers to use filters

CI/flatpak/com.obsproject.Studio.json
Disable the obs-browser plugin from the Flatpak (experimental) workflow.
The Chromium sandbox is conflicting with the Flatpak sandbox in a non-trivial,
non-workaroundable way. Until Chromium / CEF provides a way to unconditionally
disable the entire sandbox, let's not degrade the Flatpak experience.
TBD
=> flatpak: Disable browser for now

UI/window-basic-settings.cpp
In #3988, @RytoEx mentioned that the recent Qt upgrade to 5.15.2 introduced a regression in which Qt begins returning DPI/scaling aware resolutions for each screen. While this was fixed for new profiles, this was not reflected in the choice for the Canvas (Base) Resolution in the Settings screen yet.
This commits fixes this issue, and calculates the correct physical screen size again, respecting per-screen DPI scaling.
NOTE: The previous commits related to HiDPI scaling usually use the following ifdef block:
```cpp
#ifdef SUPPORTS_FRACTIONAL_SCALING
cx *= devicePixelRatioF();
cy *= devicePixelRatioF();
#elif
cx *= devicePixelRatio();
cy *= devicePixelRatio();
#endif
```
For this commit, I used the `devicePixelRatio()` which is supplied by `QScreen`, which returns a `qreal` value (and …
=> UI: Fix screen resolution calculation for Canvas (Base) Resolution

CI/flatpak/com.obsproject.Studio.json
Expose the Wayland socket to the sandbox, and enable Wayland at build time using the new ENABLE_WAYLAND define for CMake.
Enabling the newly introduced Wayland support on the "Flatpak (experimental)" workflow allows easily testing it.
Install the artifact generated by the "Flatpak (experimental)" workflow. In a Linux / Wayland session, run OBS Studio and notice the following lines:
```
info: Initializing OpenGL...
info: Using EGL/Wayland
info: Initialized EGL 1.4
```
=> flatpak: Enable Wayland

plugins/win-capture/graphics-hook/dxgi-capture.cpp
Just need to forward declare D3D12 type.
Keep toggle working.
Build works fine now.
=> graphics-hook: Fix build without COMPILE_D3D12_HOOK

libobs-winrt/winrt-capture.cpp
Catch WinRT exceptions instead of letting OBS die.
Attempt to fix #4230. If nothing else, we'll have more log info.
WGC still works. I haven't reproduced the Close() exception myself.
=> libobs-winrt: Make Close() failures non-fatal

.github/workflows/clang-format.yml, .github/workflows/main.yml, formatcode.sh
1. Rather than using clang-format-8 from a secondary repo, use clang-format-10 directly. Compatible with both 18.04 and 20.04 CI.
2. Lock Ubuntu CI builds to building on Ubuntu 18.04 LTS for now. v4l2loopback-dkms fails to install/build on the GH CI on Ubuntu 20.04 as iti's a stripped down kernel for Azure which is missing the videodev headers. Attempting to manually install required extras does not work. Attempted with both 0.12.3 and 0.12.5 v4l2loopback versions. I didn't feel comfortable removing virtual camera for CI builds, so I went with downgrading for now.
```
Building v4l2-loopback driver...
make -C /lib/modules/5.4.0-1039-azure/build M=/var/lib/dkms/v4l2loopback/0.12.5/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-1039-azure'
CC [M] …
```
=> CI: Build on Ubuntu 18.04, use newer clang-format

plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Potentially fixes crash issues with updated OBS virtualcam versions on macOS by removing an old version of the DAL plugin before copying over the new version.
After updating the DAL plugin (e.g. by updating OBS itself), OBS will work fine at first, but crash on consecutive launches. Fixes #4079.
This is mainly due to macOS considering the DAL plugin to be "tainted" after the update:
```
21:58:15.404192 com.apple.cmio CMIO_DAL_System.cpp:349:CheckOutInstance The System is starting 
21:58:15.404220  Loading Preferences From User CFPrefsD 
21:58:15.411899 com.apple.cmio CMIO_DAL_PlugInManagement.cpp:829:LoadPlugInNow Load plugin now (true) <private> 
21:58:15.421729  CODE SIGNING: process 57860[obs]: rejecting invalid page at address 0x333ef000 from offset 0x4000 in file …
```
=> mac-virtualcam: Fix codesign error after updating OBS

UI/CMakeLists.txt, libobs/util/platform-cocoa.m, plugins/mac-capture/mac-audio.c, plugins/mac-vth264/encoder.c
Updates for compatibility with Apple Silicon Macs, as documented in "[Addressing Architectural Differences in your macOS Code](https://developer.apple.com/documentation/apple_silicon/addressing_architectural_differences_in_your_macos_code)" 
The largest difference is the behavior of the timebase on Apple Silicon machines when running natively; this does not appear to impact OBS when running under Rosetta. The `mHostTime` returned by CoreAudio's `AudioTimeStamp` also appears to be scaled to the host's time base, so in order to ensure proper synchronization, it must be scaled to nanoseconds for OBS as well. OBS's `os_gettime_ns()` can be greatly simplified by simply using `clock_gettime_nsec_np()` as well -- this seems to have been added in macOS Sierra 10.12, so it shouldn't cause any …
=> Bug fixes for Apple Silicon

plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Previous pull request closed accidenally ... sorry ...
mac-virtualcam: DAL PlugIn check $HOME/Documents/obs-studio for a placeholder.png
file and use if instead fo the default placeholder.png file. This will
prevent the user's custom file from being replaced every time OBS is updated.
The only modification is to OBSDALStream.mm in the source for the dal-plugin module for mac-virtualcam. This change get's the user's home directory, then looks for Documents/obs-studio/placeholder.png relative to the user's home directory. If this custom file is found, the DAL plugin will us it instead of the default placeholder.png file.
The virtual camera a is a very useful addition to OBS, but it is frustrating to have to replace the default placeholder.png file every time OBS Studio is upgraded. It would …
=> mac-virtualcam: DAL PlugIn check for custom png file

.github/workflows/main.yml, CI/full-build-macos.sh, CI/scripts/macos/helpers/helper-entitlements.plist
Adds additional and missing entitlements to CEF components used for obs-browser.
Fixes https://github.com/obsproject/obs-studio/issues/4059
To ensure full compliance with hardened runtime and notarisation requirements all components of CEF need to be codesigned with correct entitlements.
* OBS built and entitlements checked locally
* Additional checks need to be made on versions built on CI
=> CI: Fix missing entitlements on CEF components for obs-browser

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Add `obs_source_media_started(s->source);` to function `ffmpeg_source_play_pause` in `obs-ffmpeg-source.c`
Fixes #4252 obs_source_media_play_pause does not play a stopped or ended media_source
This does not happen with the vlc_media_source 
Tested play/pause functionality 
- Windows 10 X64
=> obs-ffmpeg: Fix bug with obs_source_media_play_pause

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
The UpdateSceneSelection function was doing the same thing as the
code in the SetCurrentScene function.
Don't like duplicate code.
Changed scenes to make sure everything still worked.
=> UI: Remove redundant code

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
fixed warning regarding connect signal/slot automatically by QMetaObject::connectSlotsByName when run obs at the beginning
Reference: https://stackoverflow.com/questions/24355023/qmetaobjectconnectslotsbyname-no-matching-signal
#4264
build and run obs
=> UI: fixed warning for auto connect signal

UI/hotkey-edit.cpp, UI/hotkey-edit.hpp, UI/log-viewer.cpp, UI/qt-wrappers.cpp, UI/qt-wrappers.hpp, UI/source-tree.cpp, UI/source-tree.hpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, UI/window-basic-stats.cpp, UI/window-missing-files.cpp
This changes cleans up some deprecated functions that were removed in
Qt6. Some are placed behind version ifdefs and others are replaced for
their non-deprecated Qt5 version.
There wont be any more Qt5 releases, and the differences to make things compile arnt too different. QtX11Extras and QtMacExtras were removed which complicates making this actually work, but with some creative definitions it compiles enough to test this PR.
Compiles against Qt6 and Qt5.
=> UI: Cleanup Qt for Qt6

UI/log-viewer.cpp, UI/obs-app.cpp, UI/qt-wrappers.hpp, UI/window-basic-main.cpp
Fix some issues with Qt6 compatibility.  Strictly speaking, only the first and fourth commits are necessary.  I consider the others to be cleanups as they either simplify `#if` checks or prevent warnings.  Descriptions are included in the individual commits, but they are also provided here for convenience.
1. UI: Force plugins to use version appropriate Qt Network
Make building against either Qt5 or Qt6 easier by checking the Qt version used and loading the appropriate Qt Network DLL.
2. UI: Set default string size arg for QT_UTF8 / QString::fromUtf8
Our QT_UTF8(str) macro uses QString::fromUtf8(str) with no size argument. In Qt5, QString::fromUtf8 uses a default value of -1 for the size arg. If size is -1, it is taken to be strlen(str). In Qt6, QString::fromUtf8 doesn't use a default …
=> UI: Fix Qt6 build issues

UI/window-basic-preview.cpp, UI/window-basic-preview.hpp
If a group only contains one source, and the source is resized, the group often doesn't resize/move to reflect the new size of the source. This bug was introduced by the cursor code which meant GetStretchHandleData() is run twice, on move & click.
Bug originally found by @Warchamp7 
There might be a cleaner way to do this, but I can't think of a good way to get the handle data in move & click without rewriting the event handling altogether.
Bugs are bad, especially for groups.
Place an image source in a group on its own. Resize the source using the mouse.
=> UI: Don't attempt to resize parent group when changing cursor

CMakeLists.txt
In CMakeLists.txt, FIND_MODE is not defined here. This was moved from UI/CMakeLists.txt in commit cb4d2ff7faa8b52cf219ae85fe6caf1d2fc3f906. In UI/CMakeLists.txt, FIND_MODE is REQUIRED if DISABLE_UI is false or undefined and ENABLE_UI is true. Since the same booleans are required for the if-else branch in CMakeLists.txt where we try to find Qt, we can set find_package to REQUIRED here as well.
Currently, CMake will only warn that Qt is missing, and it will continue trying to configure, but ultimately fail in obs-vst or UI.  With this change, CMake will abort early if ENABLE_UI is enabled by requiring Qt Widgets.
I ran CMake before and after these changes to observe the change in the timing of the CMake failure.  I also compiled and ran OBS on Windows 10 64-bit and did a short recording.
- …
=> cmake: Require Qt if UI is enabled

libobs/obs-nix-x11.c
If obs was shutting down in very early in initialization like when the X11 display
is missing this context parameter might still be NULL. Return early to allow
shutdown to complete without crashing.
We dont need to crash here, so lets not.
Tested by setting display to garbage.
=> libobs: Fix crash when no context

UI/window-basic-main-dropfiles.cpp
Fixes #4236.
Makes OBS support drag and drop of files with capitalized file names. This one-liner was suggested by @WizardCM in [this comment](https://github.com/obsproject/obs-studio/issues/4236#issuecomment-778775619).
When people drag and drop into OBS files with capitalized extensions in the names, these files do not show up in OBS (and no explanation is provided). People with systems set to hide file extensions might get confused. (Other programs typically can handle capitalized file names.)
I verified existence of the bug prior to this change:
1. Dropped file called Untitled.png in OBS - it appeared in the scene
2. Dropped file called Untitled.PNG in OBS - *nothing happened* - bug
Then I created the patch and verified that it works as expected:
1. Dropped file called Untitled.png in …
=> Make drag and drop insensitive to file extension case

UI/window-basic-main-dropfiles.cpp
Adds parsing for the "layer-css" query param of URLs dragged into the main window, similarly to the other layer-* parameters already used.
OBS allows developers to effectively design overlays through browser sources and implement a lot of logic in javascript and style it through CSS, even dynmically changing it within the overlay itself. This all happens client-side, without the need to save further configuration data on a backend.
However, aside from the name, url and sizing of the Browser Source Element, no further data can currently be set/defined for such dragged elements. End Users are often not as knowledgable in CSS styling, thus requiring further tools to customize the looks of their overlays and widgets externally and then being required to copy such styling information into the …
=> UI: Add css on Drag and Drop

UI/window-basic-main.cpp
After selecting "Resize output (source size)", save the new Video settings.
Reused the code from Auto Config.
Fixes #4207
* Right click a source
* Select "Resize output (source size)
* Restart OBS
=> UI: Save video settings after 'Resize output (source size)'

libobs-d3d11/d3d11-subsystem.cpp, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h, plugins/win-capture/duplicator-monitor-capture.c
We want WGC for laptops and DXGI for everything else (except desktops with multiple GPUs where the monitor is attached to the opposite GPU). Assume laptop if multiple GPUs and battery exists.
Builds on PR #4140.
Current test still selects DXGI for laptops.
Verified DXGI is selected on desktop, and that one adapter is returned on PC with one GPU.
Ryto says this works on laptop..
=> Improve laptop check for Desktop Capture method auto-selection

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Remove beta label for YouTube - RTMPS service and make it the default. Remove
YouTube - RTMP service and move the legacy RTMP URLs to the Server
dropdown list.
We have verified YouTube - RTMPS as a beta option. Ready to make it as default.
- Tested on macOS Big Sur 11.2.1 against the YouTube RTMPS service.
- Verified that the stream health is good.
=> rtmp-services: Make YouTube - RTMPS service the default

UI/obs-app.cpp
It seems this flag introduced various regressions on X11 (and, potentially, on other platforms too, but needs confirmation). Let's preserve the old ways on current platforms, and only use this flag on the new Wayland platform.
This is a potential fix for the broken previews on X11 issue that @cg2121 reported.
- Open OBS Studio on Linux / X11
- Switch to Studio Mode
- Observe no issues
Alternatively:
- Add a screen capture on X11
- Go to the properties dialog
- Observe no issues
=> Only set AA_DontCreateNativeWidgetSiblings on Wayland

UI/CMakeLists.txt, UI/obs-app.cpp
This moves X11 platform to the qt private functions, as x11info was
removed from Qt6 so this is required for a clean Qt5/6 transition.
This is the implementation of x11info::getdisplay so it should still
work on older platforms. This "API" doesnt really guarantee anything
though.
Also clean up wayland only bits as we use them for all windowing systems
now, and the name of the native pointer we want is the same on both
platforms for now.
x11info was removed from Qt6 so this is required for a clean Qt5/6 transition.
X11 still runs with this change on Qt 5.15.2.
=> UI: Remove x11info dependency

UI/window-basic-main.cpp, docs/sphinx/reference-sources.rst, libobs/obs-source.c, libobs/obs.h
Make "Copy Filters" context menu item active only when there is at least one filter that can be copied.
This adds a helper function for inferring number of filters a source has, documents this helper and uses it to create context menu.
Note: I broke up the PR into two commits, one for helper with its docs and one for actual change. If needed, I can squash them.
This change upholds OBS consistency of making context menus active only when they can be used.
1. Create a scene with at least three sources, add one filter to at least one source, add multiple sources to another
2. Check that source with no filters has "Copy Filters" inactive
2. Check that source with one filter has "Copy Filters" active
3. Check that source with multiple filters has "Copy Filters" active
4. Copy filters to the …
=> UI: Copy Filters context menu is active only when needed

plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Set aspect ratio after av_reduce, e.g. 1920:1080 becomes 16:9.
Modify dts computation to offset by number of bframes to match FFmpeg.
Hard-code various H264 config values as they appear in FFmpeg.
Don't set maxEncodeWidth/maxEncodeHeight since FFmpeg doesn't, and we
don't support resolution changes.
Force-enable lookahead if nvEncGetEncodePresetConfig says to.
If Psycho Visual Tuning is on, switch aqStrength to from 0 to 8 to match
FFmpeg default.
Set vbvBufferSize to match FFmpeg behavior.
Compute buffer count according to FFmpeg logic.
Fix various static analysis warnings about variable size.
Plumb Psycho Visual Tuning setting into fallback encoder.
Cleaning things up before a future NVENC upgrade.
Various experiments with modified FFmpeg to simulate OBS encodes against lossless Sintel …
=> obs-ffmpeg: Align both NVENC implementations

UI/frontend-plugins/decklink-output-ui/CMakeLists.txt, UI/frontend-plugins/frontend-tools/CMakeLists.txt
Qt5X11Extras (QX11Info) was added in 762983b5d853ba8444c4efee450ea872b294060e, but it doesn't seem to actually be used. Qt6 doesn't yet ship X11Extras, so let's remove it.
#3177 added Qt5X11Extras as a dependency, though doesn't actually seem to use classes or functions from it.  This was to work around obsproject/obs-browser#219, but that appears to have been resolved by updating to CEF 4280+.  Native dialogs were reinstated in https://github.com/obsproject/obs-studio/commit/58497e59d9054b538f4cd65b93d11b210ac26618 (#4155), but we still have Qt5X11Extras as a dependency.  Since X11Extras is not currently part of Qt6, and it has no expected ship date, and we aren't using it, let's remove it.
Pinging @cg2121 and @GeorgesStavracas since they authored the PRs linked above. …
=> Remove X11Extras

libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp
This update is for Intel systems with integrated and discrete graphics only. Windows 10 20H1 runs OBS on the dGPU by default due to Windows D-list setting. It would be better to run on the iGPU by default.  
Better performance on systems with both Intel iGPU and dGPU
Tested on CFL system with non-Intel discrete graphics and CFL system with Intel discrete graphics. Works as expected. Only sets default to integrated graphics on systems with both iGPU and dGPU.
Adds a check for Intel systems with both integrated and discrete graphics. If so, sets adapter to Intel integrated graphics.
=> libobs-d3d11: Default to Intel IGPU on IGPU+DGPU systems

plugins/win-dshow/ffmpeg-decode.c
This fixed #4367. While freeing decode->hw_frame and decode->frame, we should use av_frame_free() instead of av_free(). Otherwise, memory leak happen.
Memory leak will happen while switching video format for camera between MJPG and H264.
Tested on windows 10 works fine
=> win-dshow: Fix memory leak caused by using incorrect API

CI/flatpak/com.obsproject.Studio.json
luajit developers ask people to use branches instead of tarballs, however, Flatpak interprets having both 'commit' and 'branch' fields as 'use this branch, and this commit should be at the top of the branch', which is not really what we want.
Remove the specified commit from the Flatpak manifest.
The Flatpak workflow is broken because this particular commit simply doesn't exist anymore.
* Let the Flatpak workflow run
=> flatpak: Don't specify luajit commit

UI/window-basic-auto-config.cpp
With the same approach as in #4225, fix the canvas resolution calculation in the auto-config utility. This fixes #4298.
The current release version of OBS has several issues when determining the canvas resolution. This initially occurred due to the Qt update to 5.15.2. While this was fixed for a new profile in a previous commit, I fixed it in the settings screen in #4225. However, now I noticed that thanks to #4298 that I did not adjust this in the auto-config utility. 
This PR adds this.
_Note: In the filed issue, @energizerfellow mentioned that OBS calculates a weird output resolution for screens >4096 pixels in either dimension. Maybe that's worth looking into? I haven't checked this issue and this PR won't change anything to it, but given that this fix will usually cause an increase …
=> UI: Fix canvas resolution in auto-config

plugins/obs-x264/obs-x264.c
Adjusted some x264 settings to make it behave more like FFmpeg. Didn't touch b_filler and b_vfr_input because those seem scary, and didn't want to cause regressions.
More confidence that FFmpeg tests match OBS behavior.
VLC playback was fine. Inspected video recording frame-by-frame in Avidemux.
=> x264 minor alignment with FFmpeg

libobs/obs-properties.c
Fix property group check
Fix bug introduced by #4360
With the move transition plugin adding a move source filter the "General" group.
=> libobs: fix property group check

UI/window-basic-main.cpp
Remove ifdefs checking for Qt Version >= 5.6 or 5.9.  This does not include removals in #4394 or obsproject/obs-browser#273.
Among the systems we officially support, the oldest Qt version is Qt 5.9 on Ubuntu 18.04, so Qt 5.9 is the oldest Qt we officially support, even though Qt 5.9 is EOL. We should be able to safely remove these ifdefs.  Less ifdefs, cleaner code.
Compiled and ran OBS and obs-browser on Windows 10 64-bit with these changes. I verified that display names in projector menus and "Reset UI" behave the same in OBS Studio 26.1.1 and after this patch.
Additional testing on other operating systems appreciated.
=> UI: Remove ifdefs for Qt 5.9 and older

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
When not configuring global_stream_key and starting a recording, obs-ffmpeg-mux.exe will hang. Applied same check as seen in init_params() to prevent this.
I think VS applied the formatting properly.
This issue will be a problem for anyone who initially compiles and debugs OBS.
Started recording in OBS. Should always happen if global_stream_key is empty.
=> obs-ffmpeg: Hangs when global_stream_key is not configured

cmake/Modules/ObsCpack.cmake
If someone tries to build without git they need to set
OBS_VERSION_OVERRIDE, this makes the error message occur before things
like string parsing on the OBS_VERSION which look like missing
parameters.
Better configure errors for people on odd environments.
Still builds with the right obs_version using override and git. Errors with the new message when making the git describe command fail.
=> cmake: Better failure message for no OBS_VERSION

UI/window-basic-main.cpp
The horizontal center to screen redo/undo works, but uses the vertical center string. Likely a copy and paste mistake.
Discovered while adding context information for translators, that I'm not able to see the text "Undo Horizontal Center to Screen in ...", despite the undo correctly working.
It hasn't been tested.
=> UI: Fix Horizontal Center Text

UI/source-tree.cpp
UI: fix UI block after dragging source #2609
drag source as special steps, UI will block. Fixes #2609.
win10 works fine
=> UI: fix UI block after dragging source #2609

plugins/win-capture/window-capture.c
This fixed #2321 , clear last frame if settings of window source is empty.
Preview of window source should match to settings.
WIN10 works fine
=> win-capture: clear last video frame if settings of window source is empty #2321

UI/CMakeLists.txt
QtMacExtras is currently not in Qt6 and there's no word on if/when it will be reintroduced. We don't appear to be using it, so let's remove it.
See also https://github.com/obsproject/obs-vst/pull/81.
Less dependencies. Makes a future transition to Qt6 easier.
CI has built this successfully, but I'm awaiting testing from macOS users on this change.
=> UI: Remove Qt5MacExtras

docs/sphinx/reference-libobs-graphics-graphics.rst
Add some documentation about this new Linux-only function, and its characteristics.
It's good to have this new function documented, since it can be tricky to understand it simply by staring it.
(Nothing needs to be tested)
=> Document gs_texture_create_from_dmabuf

UI/installer/mp-installer.nsi
Adds exit codes to the installer when running in silent mode. The following codes are defined:
Code 3 = Unsupported OS (64bit on 32bit or below Windows 7)
Code 4 = Missing a dependency (VS 2019 or DirectX redistributables)
Code 5 = OBS is already running
Code 6 = OBS files are in use by another app (eg virtual camera)
Third party packaging systems might invoke the OBS installer in silent mode. This gives them useful exit status information so that they can report an appropriate error to the user instead of a generic "Installation failed".
Ran the installer with OBS open, verified proper exit status was set. Ran the installer without OBS open, verified it installed silently.
=> Add exit codes for silent installer

UI/window-basic-main.cpp, UI/window-basic-status-bar.cpp
If the encoder is hung and you try to exit these two values will still
be null when obs shutting down.
Im not entirely sure this is the right way to solve this crash but it works on my machine
and we are shutting down while the encoder process is (in my case hung or crashed)
so it seems fine to just give up and continue with shutdown without crashing.
Testing changes to the obs-ffmpeg-mux that resulted in a crash or hung process (with debugger attached) caused obs to crash on shutdown.
OBS closes without crashing when the obs-ffmpeg-mux process is hung or crashed.
=> UI: Fix crash on exit with stuck encoder

plugins/win-dshow/virtualcam-module/placeholder.cpp, plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp, plugins/win-dshow/virtualcam-module/virtualcam-filter.hpp
The virtual camera assumed a statically-sized image and would crash if the user modified it. This PR allows a different sized image which will be scaled to fit the resolution of the camera.
Hopefully fixes one of the crash reports we've seen with the virtual camera in #4243.
Tested in multiple apps at multiple resolutions, verified no crashing or corruption appeared. @RytoEX performed additional extensive testing on Discord (thanks!)
=> Fix crashing when using a custom vcam placeholder

UI/source-tree.cpp
This PR is for #2602. While getting source list, we should ignore scene source which has been removed. If we don't ignore it,  a deleted scene source will be added later. Besides, signals of that scene have been sent before, such as "remove" of scene.  So we can't remove this scene source by "auto removeItem" defined in SourceTreeItem::ReconnectSignals().
ignore deleted scene source
steps as #2602, the ways to delete scene include hotkey and menu.
=> UI: Ignore scene source which has been removed

libobs/obs-data.c, libobs/obs-scene.c, libobs/util/bmem.c, libobs/util/darray.h, libobs/util/dstr.h, plugins/obs-transitions/transition-stinger.c
Fix warnings seen in Visual Studio.
Warning spam is annoying. Also fix accidental integer usage of floating-point value.
Debugger inspection of changes.
=> Warnings pass (2021-03-31)

plugins/rtmp-services/rtmp-services-main.c
Include the current format version in the path of the RTMP services URL.
The format has been updated in a backwards-incompatible way, resulting in older OBS versions not being able to receive the latest services updates. Solving this problem requires server-side parsing of the User-Agent to deliver the correct format. In the future, this can be avoided by having OBS insert the required format version in the URI.
Compiled, verified that the correct URL is being downloaded (`https://obsproject.com/obs2_update/rtmp-services/v3/package.json`).
=> rtmp-services: Include format version in update URL

UI/data/locale/en-US.ini, UI/window-basic-main-outputs.cpp, UI/window-basic-main-outputs.hpp, UI/window-basic-main-screenshot.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-remux.cpp
This shows a message in the status bar with the following events:
- Recording is saved
- Recording is auto remuxed
- Replay buffer is saved
- Screenshot is taken
OBS has no feedback when files are saved.
Saved different types of files to make sure it showed the message correctly.
=> UI: Add save notifications to status bar

.github/workflows/flatpak.yml, CI/flatpak/com.obsproject.Studio.json
Make the Flatpak workflow cache the build objects between runs, and use this cache to speed up the workflow execution time.
Build cache reduces CI load.
One can observe the last CI run of the `master` branch of my repository for an example of the build cache being used: https://github.com/GeorgesStavracas/obs-studio/runs/2248155034
The build hit the cache of all dependencies, and most of OBS Studio's code also hit ccache, speeding up the build time quite substantially.
- Performance enhancement (non-breaking change which improves efficiency... of CI)
=> Build cache for the Flatpak workflow

docs/sphinx/reference-sources.rst, libobs/obs-source.c, libobs/obs.h, plugins/obs-filters/chroma-key-filter.c, plugins/obs-filters/color-correction-filter.c, plugins/obs-filters/color-grade-filter.c, plugins/obs-filters/color-key-filter.c, plugins/obs-filters/data/chroma_key_filter_v2.effect, plugins/obs-filters/scale-filter.c
Need to expand filter API to ensure existing filters don't render incorrectly.
Also restore chroma key matching algorithm to nonlinear space because I don't want to deal with regressions by trying to improve the algorithm.
Fix regressions.
Legacy filter no longer renders incorrectly, and chroma key behavior is restored on user-provided sample image.
=> Fix filter regressions from SRGB changes

plugins/obs-filters/noise-suppress-filter.c
This fixes #4441 (first commit).
The second commit is a minor code cleanup:
- sets defaults intensity of RTX denoiser to max.
- adds an initialization check of nvafx.
- splits nvafx initialization from channel allocation for better
readability of the code.
- moves the intensity update from the filter_audio process function
to the plugin update function.
- logs the error code in case nvafx returns an error when running.
(useful for devs; I haven't translated the error codes which are
available in the sdk).
- Fixes an issue.
- Code cleanup will make maintainance easier.
Tested that the issue is fixed and that the plugin works fien after the code cleanup.
=> obs-filters: RTX denoiser initialization fix and code cleanup

UI/forms/OBSBasic.ui
The behavior of Duration input in Scene Transitions dock is now conformed to the one of Studio Mode transitions UI.
Prior to this commit, the Studio Mode transitions menu allowed for 50 ms minimum, 50 ms step, and 20000 ms maximum, yet the Scene Transitions dock allowed for 2 ms minimum, 50 step, and 10000 ms maximum. 2 ms duration is basically a cut transition, therefore both minimums and maximums have been conformed to the ones of the Studio Mode menu.
I knew that it was possible to do 20 second fades (as witnessed on LGIO livestreams), yet my OBS only allowed 10 seconds. I investigated the code and found discrepancies in how the UI elements are specified. Since either elements are controlling the same property, I believe both should enforce the same constraints.
Purely cosmetic and …
=> UI: Conform transition duration in Scene Transition dock

UI/undo-stack-obs.cpp
Adds a limit to the undo stack. Simply pops off the last element when it reaches maximum capacity.
To prevent an unlimited number of items in the 
=> UI: Add maximum number of items in undo/redo stack

UI/undo-stack-obs.cpp, UI/undo-stack-obs.hpp, UI/window-basic-main-scene-collections.cpp
Wipes the stack on scene collection change
We discussed this in discord.
I tested it on my linux machine.
=> UI: Wipe undo/redo stack when switching scene collections

UI/context-bar-controls.cpp, UI/source-tree.cpp, UI/window-basic-filters.cpp, UI/window-basic-main.cpp, UI/window-basic-preview.cpp, UI/window-basic-properties.cpp, UI/window-basic-source-select.cpp, UI/window-basic-transform.cpp
The undo/redo functions are setting the current scene. Every time
it would do this, it would actually transition to the scene.
This forces the current scene, so it fixes a bug where the
transition would be grayed out when undoing/redoing.
Fixes bug that I found
Used undo/redo and made sure everything worked as expected.
=> UI: Force current scene when using undo/redo

UI/window-basic-main-transitions.cpp
The context bar wouldn't update when using undo and redo.
Fixing bug that I noticed.
Used undo and redo and made sure the context bar was updating.
=> UI: Update context bar when using undo/redo

UI/window-basic-main.cpp
If the user were reordering scenes, the preview scene would change
to a different one, than the one they were currently on.
Reordered scenes and made sure the current scene stayed the same.
=> UI: Fix reordering scenes not working properly

UI/window-basic-main-transitions.cpp
When setting the current scene and if it was the same as the previous,
the log would be spammed with switching scene messages.
This issue particularly happened when using undo/redo, as their
functions were setting the current scene.
Users reported the log was being spammed when using undo and redo.
Used undo/redo and switch scenes to make sure everything worked as expected.
=> UI: Fix spamming of log when setting current scene

UI/data/locale/en-US.ini, UI/window-basic-main-transitions.cpp, libobs/obs-scene.c, libobs/obs.h
Undo/Redo source visibility transitions
allow undo changing source visibility transition
On windows 64
- [] I have included updates to all appropriate documentation.
=> Add Undo/Redo source visibility transitions

plugins/vlc-video/vlc-video-source.c
Excludes URL entries from being marked as "missing" by the missing file dialog
URLs should not be considered missing files, and generally should not be checked for validity anyway. Previously, if an entry in the playlist was a URL, it would be marked as a missing file and pop up on load.
Made a playlist full of url and file entries, urls did not show up in missing files dialog, but missing files did.
=> vlc-video: Ignore URLs when checking for missing files

UI/properties-view.cpp, plugins/obs-filters/chroma-key-filter.c, plugins/obs-filters/color-correction-filter.c, plugins/obs-filters/color-key-filter.c
Now that color math is done in linear space, we need more precise values to adjust brightness for color channels near zero.
User reported the step size is too large.
Setting still works for modified filters.
=> Increase brightness precision for filters

UI/auth-twitch.cpp
When Twitch introduced the new Dashboard, it included some updated popouts. We decided against replacing the in-app docks until we were confident that nothing would break.
This also fixes an issue where the submit button on the Stream Information dock would be cut off at certain resolutions.
Two notes:
1. I have not updated the Chat URL because FFZ's Settings button does not appear in the Dashboard Chat popout (but BTTV's does)
2. Twitch have yet to make an updated popout for Stats, so it uses the old URL
I also purposefully chose to continue using `/u/<user>/` URLs instead of removing the user part as this ensures that the logged in Twitch session/user cookies match the authenticated user in Settings -> Stream.
Using outdated URLs is never recommended. While Twitch haven't mentioned …
=> UI: Use newer Twitch Dashboard docks for integration

libobs/graphics/math-extra.c
If v1 vector is within EPSILON, it would previously return v1, when logically v2 (the target) should be returned instead.
Noted by @jpark37 in #2930. No parts of OBS use this util, however it follows the same issue as was fixed in #2930, so it deserves to be fixed too.
To summarize how the current behavior can be an issue, if there is a transition which uses torque for gradual translation to a target (v2), and the current position(v1) is within the EPSILON, v2 will never be reached, which would make a check like
```c
struct vec3 dst;
calc_torque(&dst, current, target, ...);
if (dst == target) {
transitionCompleted();
}
```
have undefined behavior.
**This fix could not be tested, as no examples of this util function's usage could be found.** …
=> libobs: Return target vec not current when within EPSILON

plugins/mac-capture/audio-device-enum.c
macOS 11.2
No response
27.0.0-rc1
Both RC1 as well as newest nightly
https://obsproject.com/logs/o3_DktbhzZo_B8yL
No response
Add another virtual audio device to mac OS desktop.
The following virtual audio devices are missing on Mac OS desktop setting: "GroundControl 2ch", "GroundControl 16ch", "GroundControl 64ch".
1. Open OBS preferences->audio->global audio devices->desktop audio
2. Check the drop down menu.
3. See that the following virtual audio devices are missing even though they are installed on my machine:  "GroundControl 2ch", "GroundControl 16ch", "GroundControl 64ch".
Repository
obsproject/obs-studio
=> mac-capture: Add another virtual audio device to the list

plugins/mac-virtualcam/src/dal-plugin/Logging.h
Hides the DLog and DLogFunc macros behind the -DDEBUG flag, causing the logs to only appear in testing environments.
On production build, calls to these macros will result in nothing happening.
Console logs in this amount:
are hilarious.
On production, there will be no more unnecessary debug logs, leaving the console like this:
macOS 11.2.3, Intel
Building in Xcode keeps the logs, outside of it with the `-DCMAKE_BUILD_TYPE=RelWithDebInfo` flag, the logs are gone.
=> mac-virtualcam: Hide logging behind debug flag

plugins/obs-filters/luma-key-filter.c
Increase precision of luma key settings.
Previous step size was reported ineffective, even moreso now with linear color math for luma near zero.
All settings still work as intended.
=> obs-filters: Increase luma key precision

CI/flatpak/com.obsproject.Studio.json
It seems that the browser source works inside a Flatpak sandbox and/or Wayland with CEF 4280, so let's try and reenable it.
This reverts commit e64c61710fb064ca87341f091ac55cb5861fc202.
The browser source is pretty important! :slightly_smiling_face: 
In addition to that, this is another step towards feature parity of the Flatpak build and regular builds.
- Install the Flatpak bundle generated by the "Flatpak (experimental)" workflow
- Run this version OBS Studio
- Add a browser source
I'm actually not sure? It could either be
or
=> Reenable browser source in Flatpak

UI/window-missing-files.cpp
Fix missing files dialog crash loading source icon
Other solution as #4528 to same crash
obs.dll!get_source_info+0x33
obs.dll!obs_source_get_icon_type+0x9
obs64.exe!OBSBasic::GetSourceIcon+0x18
obs64.exe!MissingFilesModel::data+0x41a
On windows 64 bit loading a corrupt scene collection.
=> UI: Fix missing files dialog crash loading source icon

UI/window-basic-main.cpp
When Undo/Redo was added, this comparison was accidentally removed. The resulting conditional would always return true, causing sources to be deleted unintentionally.
Fixes #4546
Click "No" when deleting multiple sources
=> UI: Fix invalid check for Remove Multiple Sources dialog result

UI/window-basic-main.cpp, UI/window-basic-main.hpp
A crash would occur when clicking the 'x' button in the missing files
dialog. This seemed to only happen in debug mode and using QT 5.15.0.
Closes #4363
Fixes #4359
Fixes crash that I found.
Closed the dialog and made sure it didn't crash.
=> UI: Fix crash when closing missing files window

CI/flatpak/com.obsproject.Studio.json, plugins/linux-v4l2/v4l2-output.c
It is not possible to run host system executables like modinfo, pkexec, and modprobe inside a Flatpak sandbox. However, Flatpak provides a way to run command on the host system: the flatpak-spawn executable.
flatpak-spawn is a tiny helper that, when executed with the '--host' parameter, talks to the org.freedesktop.Flatpak D-Bus interface to run and retrieve the return value of the executable. This provides OBS Studio a way to escape this sandbox limitation without opening large holes in the sandbox.
Make v4l2's implementation of VirtualCam run system commands using flatpak-spawn when inside a Flatpak sandbox. The detection of the sandbox is done by checking the existence of the /.flatpak-info file, which is created by Flatpak itself, and only exists inside the sandbox. If OBS Studio is …
=> Make VirtualCam work with Flatpak

CI/scripts/macos/app/Info.plist, cmake/osxbundle/Info.plist
Fixes an issue where on macOS the app’s Info window in Finder would say
"Version: OBS - Free and Open Source Streaming/Recording Software"
instead of the version set in CFBundleShortVersionString.
Since CFBundleGetInfoString is deprecated anyways, it can safely be
removed.
Apparently, [NSHumanReadableCopyright](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-112854-TPXREF117) is supposed to be a replacement, but that looks like it serves a different purpose than what we had in CFBundleGetInfoString
This was something that was kind of bothering, also *I'm sure* there was an open issue regarding this on this GitHub, but I can't seem to find it. Maybe someone remembers
Bundled the package …
=> CI,cmake: Fix macOS version information

.github/workflows/flatpak.yml
Use the right subaction (flatpak-builder) for the Flatpak workflow.
The Flatpak action now contains two subactions:
- flatpak-builder: for building and uploading a bundle
- flat-manager: for deploying the bundle to a remote repository
We're only interested in the `flatpak-builder` subaction for now. In the future, we can use `flat-manager` to automatically send OBS Studio releases to e.g. Flathub.
This won't affect existing pull requests, except the ones that have the "Seeking Testers" label applied - in which case, they may simply need to rebase against the master branch.
- Run the "Flatpak (experimental)" workflow, both with and without the "Seeking Testers" label
- Code cleanup (non-breaking change which makes code smaller or …
=> CI: Use flatpak-builder subaction

plugins/obs-transitions/transition-stinger.c
- When resolutions on the source and stinger don't match, the Matte texture is rescaled before being provided to the Matte shader. This results in a Matte smaller than the textures it is supposed to cover
- When using a Track Matte Stinger as a visibility transition, side-by-side and stacked file modes will render the full texture (both the stinger side and the matte side) instead of cropping it to only show the stinger side.
Fixes this: https://obsproject.com/forum/threads/obs-studio-27-release-candidate.141857/page-2#post-522508
Tested on Windows 10 20H2, with a 1920x1080 Track Matte Stinger running as the visibility transition of a 1024x768 source (either an image or a video).
=> obs-transitions: Track Matte fixes for Source Visibility transitions

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adds Luzento.com to RTMP Services
This provides a simple way for users to configure OBS to stream to Luzento.com with preferred settings. It includes 2 "servers" Primary and Primary (Test). Primary (Test) is a server that users can use to test their live stream settings internally without streaming to their audience. 
Mac Mini M1 OBS 27.0.0-rc2
=> rtmp-service: Add Luzento.com

plugins/obs-filters/noise-suppress-filter.c
Loads NVAFX in a thread to avoid impact to startup time. Care was taken to avoid reentrancy across threads as NVAFX doesn't appear to like that. Also includes a change from @pkviet to only initialize the channels that are required instead of all eight.
OBS would take a significantly longer time to start up if NVAFX filters were used. Without a splash screen, users may think it has failed to launch.
I was unable to test locally as I don't have an RTX GPU, however pkv tested multiple filters and observed correct behavior. More testing would be good before merging.
**If testing, please build from source - CI seems to have built a copy of obsproject/master instead of this PR.**
=> obs-filters: Reduce NVIDIA AFX loading delays

libobs/obs-source.c
Checks that a source's context data is valid before attempting to run the actual missing files check.
Crash bad!
I found this when building OBS on one machine and installing the deb package on another.
Tested on Ubuntu 20.04
Without fix: Crash in vlcs_missingfiles during OBS load
With fix: Issue is logged with a warning and OBS loads fully without crashing.
=> libobs: Fix crash when calling missing files functions on a source with invalid context data

plugins/obs-transitions/data/fade_to_color_transition.effect, plugins/obs-transitions/transition-fade-to-color.c, plugins/obs-transitions/transition-fade.c, plugins/obs-transitions/transition-luma-wipe.c, plugins/obs-transitions/transition-slide.c, plugins/obs-transitions/transition-swipe.c
Transitions were updated to be color linear, but that's not always what we want.
Nonlinear and linear both have issues, but people are used to nonlinear, so switch back. Maybe we'll switch to CIELUV if we stop caring about performance on bad GPUs.
Checked that the transitions still work.
=> Switch transition interpolation back to nonlinear SRGB

plugins/text-freetype2/text-freetype2.c
Colors not working properly. Don't want to alter gradients (yet).
Colors should work. Also don't want linear vs. nonlinear gradient discussion.
Colors work now.
=> text-freetype2: Render in nonlinear space

libobs/data/default.effect, libobs/obs-source.c, plugins/image-source/image-source.c
Apply alpha in nonlinear space for compatibility with bad applications.
The image source now needs to be a custom draw, which prevents the direct filter rendering optimization.
We may want to provide a toggle in the future, but just try to match previous behavior for now. v27 has enough new features for support to deal with.
Alpha should be applied in linear space, but most applications do not, including Chromium and Visual Studio.
Used 255/255/255/64 texture in various scenarios.
The shader involved in more complicated, but the performance hit seems manageable:
NVIDIA RTX 2080 Ti: 34 us -> 41 us for 1080p image
Intel UHD Graphics 750: 448 us -> 576 us for 1080p image
=> Apply alpha in nonlinear space for images and async video

UI/window-basic-main.cpp
Removed unnecessary lines from the function. Also if the source happened to be
null, the SetCurrentScene function would be called anyway. Finally, the
UpdateContextBar and api lines were removed, as they are also being called with
SetCurrentScene.
Cleaning up messy code.
Switched scenes to make sure nothing changed.
=> UI: Cleanup on_scenes_currentItemChanged function

libobs/obs-source.c, plugins/obs-filters/crop-filter.c, plugins/obs-filters/data/blend_add_filter.effect, plugins/obs-filters/data/blend_mul_filter.effect, plugins/obs-filters/data/blend_sub_filter.effect, plugins/obs-filters/data/chroma_key_filter.effect, plugins/obs-filters/data/chroma_key_filter_v2.effect, plugins/obs-filters/data/color_correction_filter.effect, plugins/obs-filters/data/color_grade_filter.effect, plugins/obs-filters/data/color_key_filter.effect, plugins/obs-filters/data/color_key_filter_v2.effect, plugins/obs-filters/data/luma_key_filter.effect, plugins/obs-filters/data/luma_key_filter_v2.effect, plugins/obs-filters/data/mask_alpha_filter.effect, plugins/obs-filters/data/mask_color_filter.effect, plugins/obs-filters/luma-key-filter.c, plugins/obs-filters/mask-filter.c, plugins/obs-filters/scroll-filter.c, plugins/obs-filters/sharpness-filter.c
Build on earlier change to blend filter inputs to output premultiplied alpha. The filters themselves need to handle premultiplied alpha input.
Fixes #4606.
Chroma key regressed, and we may as well just fix everything.
All modified filters have been tested on Windows, D3D11 and GL.
=> Fix premultiplied alpha handling for filters

UI/properties-view.hpp, UI/undo-stack-obs.cpp, UI/window-basic-filters.cpp, UI/window-basic-filters.hpp
This PR includes 3 commits that fix 3 distinct issues coming from the audio filters. First, if audio filters were changed (and probably filters in general, but I did not check), it would enable the redo option, even though there was no redo action available. Secondly, audio filters were not being added to the undo stack once they were deleted. Third, the changes to audio filters (at least dropdown selections) were not being added to the undo stack.
Fixes audio filters issues.
Tested this on my machine.
=> UI: Fix issues with audio filters and undo/redo

plugins/obs-filters/data/color_key_filter.effect
Do not treat incoming color uniform as premultiplied.
Incorrect color expansion was causing hue shifts.
Hue shift no longer occurs.
=> obs-filters: Fix bad math in Color Key v1

plugins/obs-filters/chroma-key-filter.c, plugins/obs-filters/color-correction-filter.c, plugins/obs-filters/color-key-filter.c, plugins/obs-filters/data/blend_add_filter.effect, plugins/obs-filters/data/blend_mul_filter.effect, plugins/obs-filters/data/blend_sub_filter.effect, plugins/obs-filters/data/chroma_key_filter_v2.effect, plugins/obs-filters/data/color_correction_filter.effect, plugins/obs-filters/data/color_key_filter_v2.effect, plugins/obs-filters/data/mask_alpha_filter.effect, plugins/obs-filters/data/mask_color_filter.effect, plugins/obs-filters/mask-filter.c
For v2 filters, switch Opacity settings from integer [0, 100] to
floating-point [0.0, 1.0] with four decimal places for granular blacks.
Also multiply alpha in shader to maintain precision.
Could not access small black values even with Opacity of 1.
Small black values have been tested to be available in v1/v2 of modified filters.
=> obs-filters: Increase opacity precision

UI/window-basic-main.cpp
Fixes bug introduced in commit d7e4945eab31983fbe33e7a6b40f4866018c3227
Previously `CreateFilterPasteUndoRedoAction` would get the source which was copied from (source), not the source that was receiving filters (destination). So Undo-Redo would restore the destination's filter state on the source.
Related to #4562, #4616.
1. Create empty scene
2. Crate image sources 1 and 2
3. Add "Color correction" filter to 1 and "Scroll" to 2.
4. Right-click source 1 and click "Copy filters"
5. Right-click source 2 and click "Paste filters" (source 2 has color correction and scroll now)
6. Press CTRL+Z and make sure source 2 has only color correction
7. Press CTRL+Y and make sure source 2 has both color correction and scroll
Previously step 6 would be messed up (source 1 would be modified).
- Bug fix …
=> UI: Fix Undo/Redo for pasting multiple filters

plugins/obs-transitions/transition-stinger.c
Remove dead code after #4549.
Was causing warnings when I noticed the variables weren't being used.
Code compiles without warnings.
=> obs-transitions: Remove dead code

UI/properties-view.cpp
Set decimal places before value on QDoubleSpinBox to preserve precision.
Large precision filter values (Brightness/Opacity) were being truncated.
Values are no longer truncated after filter switches and OBS restarts.
=> UI: Fix rounding truncation

docs/sphinx/reference-sources.rst, libobs/obs-scene.c, libobs/obs-source.c, libobs/obs-source.h, libobs/obs.h, plugins/image-source/color-source.c, plugins/image-source/image-source.c, plugins/linux-capture/xshm-input.c, plugins/mac-capture/mac-display-capture.m, plugins/obs-filters/chroma-key-filter.c, plugins/obs-filters/color-correction-filter.c, plugins/obs-filters/color-grade-filter.c, plugins/obs-filters/color-key-filter.c, plugins/obs-filters/crop-filter.c, plugins/obs-filters/luma-key-filter.c, plugins/obs-filters/mask-filter.c, plugins/obs-filters/scale-filter.c, plugins/obs-filters/scroll-filter.c, plugins/obs-filters/sharpness-filter.c, plugins/obs-text/gdiplus/obs-text.cpp, plugins/text-freetype2/text-freetype2.c, plugins/win-capture/duplicator-monitor-capture.c, plugins/win-capture/game-capture.c, plugins/win-capture/monitor-capture.c, plugins/win-capture/window-capture.c
Add new flag OBS_SOURCE_SRGB to indicate SRGB awareness. SRGB usage will be forced off if this flag is not present.
Also requires obsproject/obs-browser#292 to be submitted afterward.
Too many third-party plugins are displaying wrong colors.
scene
group
srgb_aware
!srgb_aware
OBS_SOURCE_SRGB
!OBS_SOURCE_SRGB
v1 no srgb
v2 srgb
Color
Image
text (gdi)
text (freetype)
duplicator monitor (DXGI)
game capture
window capture (bitblt)
window capture (wgc)
monitor capture (win7, hack code)
browser
XSHM (Linux)
Display Capture (Mac)
apply lut
chroma key
color correction
color key
crop
luma key
mask
scale
scroll
sharpness
transitions
async video
Off-World-Live/obs-spout2-source-plugin
OBS.Live
- New feature (non-breaking change which adds …
=> Backwards compatibility for sources without SRGB awareness

plugins/image-source/data/locale/en-US.ini, plugins/image-source/image-source.c
Add support for applying alpha in linear space to match Photoshop
behavior in linear mode, and for just overall correctness. The default
setting is still nonlinear to match common user expectation though.
Want to provide some ability for OBS to match Photoshop authoring flow.
Half white texture (255/255/255/127) against black is (127/127/127) by default, and (187/187/187) in linear mode.
=> image-source: Allow linear space alpha

plugins/obs-filters/data/color_grade_filter.effect
Shader regressed for Apply LUT on OpenGL. Trivial fix.
Apply LUT should work on OpenGL.
Apply LUT works on OpenGL.
=> obs-filters: Fix shader for LUT on OpenGL

libobs/data/default.effect, libobs/graphics/graphics-ffmpeg.c, plugins/image-source/image-source.c
Add support for 16-bit images.
Helps preserve alpha precision for 16-bit linear textures.
Banding fixed on Windows. Image loads on Linux.
=> Add support for 16-bit images

plugins/win-capture/duplicator-monitor-capture.c
Previously disabled DXGI because the index is wrong.
Should disable WGC instead.
Hacked wgc_supported to be false, and now the correct entry is disabled.
=> win-capture: Fix WGC disable index for display

libobs/obs-scene.c
Fix deadlock removing scene item
moved the clearing of the show and hide transition outside the full scene lock
Techjar on discord #beta-testing:
> the UI thread acquires the lock on scene->video_mutex in obs_sceneitem_remove
> at the same time the graphics thread acquires the lock on scene->sources_mutex in tick_sources
> the graphics thread then tries to acquire scene->video_mutex in scene_video_tick, but blocks because the UI thread has it locked already
> finally the UI thread goes to actually remove the show/hide transition from the scene, but first tries to acquire the lock on context->mutex (there's a few functions where this occurs), which in this case is actually the same pointer as scene->sources_mutex, which is already locked by the graphics thread, so it blocks
> we are now …
=> libobs: Fix deadlock removing scene item

libobs/obs-source.c, libobs/util/platform.c, plugins/obs-filters/noise-suppress-filter.c
Fix a couple warnings seen in GCC.
Warnings are gone.
=> Warnings 2021-05-04

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add Brime to RTMP stream services, using its RTMP ingestion endpoints. 
Brime Live is a new live streaming platform. We've solidified all of our ingest server regions and have confirmed they all have connectivity. This services addition should serve us through our public launch later this summer.
- Support for 120fps (experimental, but tests have shown really solid results)
- Support for (3840 x 2160)
- Support for 20k bitrate
Tested changes on Windows 10 x64.
=> rtmp-services: Add Brime Live service

UI/window-basic-main-transitions.cpp
When transitioning, the transitions properties menu would still be
enabled.
Since the transition drop down is disabled, this should be as well.
Transitioned using a configurable transition and made sure the menu was disabled when transitioning and enabled when not.
Also made sure with non-configurable transitions the menu was always disabled.
=> UI: Disable transition props menu when transitioning

CI/flatpak/com.obsproject.Studio.json
Actually really enable the browser source in the Flatpak manifest.
Due to an unfortunate series of events, we ended up with both `-DBUILD_BROWSER=ON` **and** `-DBUILD_BROWSER=OFF` in the Flatpak manifest, which was effectively disabling the browser source even after https://github.com/obsproject/obs-studio/pull/4431 landed.
- Download the Flatpak bundle generated by the "Flatpak (experimental)" workflow
- Try and add the browser source - it must be at least available
=> Enable browser source for real in Flatpak

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp
Commit 1: Removes unnecessary function call.
Commit 2: If the fade to black was active and the user switched scene collections,
or exited studio mode, the source wouldn't be cleared, causing the
transition not to work properly when used again.
Fixes bug that I've noticed.
Used fade to black and made sure it would work properly when switching scene collections or exiting and entering studio mode.
- Bug fix
=> UI: Fade to black fixes

plugins/obs-transitions/data/fade_to_color_transition.effect, plugins/obs-transitions/data/fade_transition.effect, plugins/obs-transitions/data/luma_wipe_transition.effect, plugins/obs-transitions/data/slide_transition.effect, plugins/obs-transitions/data/stinger_matte_transition.effect, plugins/obs-transitions/data/swipe_transition.effect, plugins/obs-transitions/transition-fade-to-color.c, plugins/obs-transitions/transition-fade.c, plugins/obs-transitions/transition-luma-wipe.c, plugins/obs-transitions/transition-slide.c, plugins/obs-transitions/transition-stinger.c, plugins/obs-transitions/transition-swipe.c
Color mismatch is apparent when using source transitions, which lerps
against transparent black and blends into the canvas nonlinearly. When
the transition is done, the blend switches to linear, leading to a pop.
Fix the issue by blending into the canvas in linear space. The lerp is
still nonlinear by design.
Don't want color pop at the end of transition.
Checked all modified transitions against both scene and source.
=> obs-transitions: Blend in linear space

plugins/obs-filters/data/color_key_filter_v2.effect
Was incorrectly computing distance between linear color and nonlinear
key. Make color nonlinear to match previous behavior.
Make color key behave the same.
Verified broken test case now behaves as before. Chroma key shader looks similar.
=> obs-filters: Fix color key distance

libobs/data/default.effect, libobs/graphics/graphics-ffmpeg.c, libobs/graphics/graphics.h, libobs/graphics/image-file.c, libobs/graphics/image-file.h, libobs/graphics/srgb.h, libobs/graphics/vec4.h, libobs/obs-source.c, plugins/image-source/image-source.c
Image sources are now premultiplied on load, allowing properly filtered samples. We can also trivialize the render function and remove the custom draw attribute to restore the direct rendering filter optimization.
Correctly filtered samples are nice. Speed is good.
Exercised all modified code paths, even if it meant temporarily modifying code or copying snippets to a testbed to run them.
Tests included 8-bit and 16-bit images with transparency, animated gifs, verifying the direct rendering optimization is restored, and toggling the linear checkbox for all images.
=> Premultiply image sources on load

plugins/decklink/decklink-output.cpp
Fixes a segfault in decklink_output_stop() while also removing unused code.
OBS kept crashing while im testing Decklink stuff.
The actual crash is caused because obs_module_unload() is called before the decklink outputs are stopped. In obs_module_unload(), the deviceEnum pointer is freed. During decklink_output_stop(), the removed code tries to retrieve a reference of the decklink device from the deviceEnum and crashes because it has already been freed. This code appears to serve no purpose anyway, so we remove it.
Ubuntu 20.04, using master HEAD: No crashes after removing the extra code.
=> decklink: Fix crash during shutdown when output is on

libobs/CMakeLists.txt
Add missing header.
File shows up in VS solution explorer. Also helps unbreak plugin builds somehow.
File shows up in VS solution explorer.
=> libobs: Add srgb.h to CMakeLists.txt

plugins/obs-filters/color-grade-filter.c, plugins/obs-filters/data/color_grade_filter.effect, plugins/obs-filters/data/luma_key_filter_v2.effect, plugins/obs-filters/luma-key-filter.c, plugins/obs-filters/scale-filter.c
Fix scale filter using the wrong blend setup, which altered colors for semi-transparent inputs.
Also update blend setups to have extra precision for Apply LUT and Luma Key.
Better color handling.
Tested colors using opaque and semi-transparent textures are stable and expected.
=> More filter color fixes

plugins/obs-transitions/transition-stinger.c
This would cause a memory leak when toggling the track matte
transition.
Don't like memory leaks.
Toggled track matte to make sure memory leak was gone.
=> obs-transitions: Make sure gs calls are in graphics context

UI/importers/studio.cpp
Two changes.
UI: Fix scene collection importer OS translation 
The OS translation in the Scene Collection Importer seems to have been broken since the feature was added because the translated sources were not added back to the output JSON object. Add the translated sources to the output JSON object to get the feature to work. 
----
UI: Add versioned sources to scene collection importer 
Versioned sources were added in commit b2302902a3b3e1cce140a6417f4c5e490869a3f2 after the scene collection importer was added in commit 191165c7210f2b8adf8756cf121341075bf16b3d. When a versioned source gets converted in TranslateOSStudio, it can end up with a translated "id" but an untranslated "versioned_id". When OBS loads the resulting JSON, it will rely on the versioned_id, and rewrite the id to the …
=> Fix scene collection importer OS translation

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
Commit 1: To prevent rendering the texrender more than necessary, only
render it once per frame in a tick callback.
Commit 2: When closing OBS, sometimes it would crash if the Decklink outputs
were active.
Commit 1: Inspired by https://github.com/obsproject/obs-studio/commit/4636413334a9f0418fdb320677939fcc4c73642a, I went looking for other places where this might be happening.
Commit 2: When testing the texrender code, it would sometimes crash on shut down.
Used the Decklink output to make sure everything worked as expected.
=> decklink-output-ui: Decklink fixes

.github/workflows/main.yml, cmake/Modules/FindDetours.cmake, plugins/win-capture/graphics-hook-ver.h, plugins/win-capture/graphics-hook/CMakeLists.txt, plugins/win-capture/graphics-hook/d3d12-capture.cpp, plugins/win-capture/graphics-hook/dxgi-capture.cpp, plugins/win-capture/graphics-hook/graphics-hook.c, plugins/win-capture/graphics-hook/graphics-hook.h
Make a number of changes to try to stabilize D3D12 game capture.
- Integrate Detours to hook D3D12 ExecuteCommandLists rather than using our own ad-hoc hooking code. I would like to replace everything with Detours, but this seems to be the only hook function that somehow gets undone, and we're trying to get 27 shipped. Will do more extensive Detours integration later.
- Fix potential D3D12 device leak.
- Prevent potential recursive free.
- Add "timeout" for the expected DXGI swap chain if 16 Present() calls happen on a different swap chain.
- Add more logging to help debug issues, which we used to find the ExecuteCommandLists hook failure.
D3D12 game capture has some stability issues.
Tested against very basic D3D12 sample, both 32-bit and 64-bit builds.
Matt has verified D3D12 hook …
=> D3D12 hook improvements

.github/workflows/main.yml
Adds a check for macOS code signing credentials configured in the repository and skips notarization if necessary secrets are not configured.
Fixes CI runs breaking on forks without code signing credentials set when a run is triggered by a version tag.
* Needs to be tested on CI
* 
=> CI: Add check for code signing credentials used by notarization

plugins/win-capture/graphics-hook/CMakeLists.txt
Need to include Detours include dir. Build currently only works if Vulkan SDK is not installed.
Want to be able to build with Vulkan SDK installed.
Can now build with Vulkan SDK installed.
=> graphics-hook: Add Detours include dir

cmake/Modules/FindDetours.cmake
Since CMake 3.17, find_package_handle_standard_args (FPHSA) will emit a warning if the package name in the caller and in FPHSA do not match. This normalizes the name "Detours" in CMake calls to prevent this warning.
Prevent warnings.  See #2972.
I configured OBS via cmake-gui before and after this change.  Before, I received the warning pictured below.  After, I did not receive the warning.  OBS built successfully with this change.  I don't have any DX12 games to test game capture on.
=> cmake: Fix Detours package name CMake warning

UI/adv-audio-control.cpp
String format with null is bad.
GCC warning.
GCC warning is fixed. Log output still looks good.
=> UI: Fix null string being passed to blog()

libobs/obs-source.c
This is necessary if the source contains overlapping draws.
Fixes #4711.
Wayland cursor capture was not rendering correctly.
Cursor looks fine now.
=> libobs: Straight alpha blend for filtered inputs

UI/window-basic-filters.cpp
FreeBSD build fix.  repeatable is a bool, so pass false instead of NULL.
Correct type to fix build on FreeSD.
Build failed with
```
../../UI/window-basic-filters.cpp:1232:31: error: cannot initialize a parameter of type 'bool' with an rvalue of type 'nullptr_t'
redo, undo_data, redo_data, NULL);
^~~~
/usr/include/sys/_null.h:37:14: note: expanded from macro 'NULL'
#define NULL    nullptr
^~~~~~~
../../UI/undo-stack-obs.hpp:58:32: note: passing argument to parameter 'repeatable' here
std::string redo_data, bool repeatable = false);
^
1 error generated.
```
Build-tested on FreeBSD 13 with Clang 11.
=> UI: Correct add_action repeatable arg type

.github/workflows/main.yml
Pins `dmgbuild` version on GitHub Actions to avoid breakage introduced with its 1.5 update.
Restore macOS builds on GitHub Actions.
Tests require CI runs (pending).
=> CI: Fix dmgbuild breaking CI by pinning its version number

libobs/obs-source.c
Fixes issue where color-correction filter v1 changes from v26 to v27.
Don't want v1 filter behavior to change.
Screenshots match now.
=> libobs: Restrict direct filtering to SRGB match

plugins/obs-filters/data/chroma_key_filter_v2.effect
Not easy to tell with green where Cb and Cr are close to each other (0.16, 0.10), but obvious when using a bluish hue (0.84, 0.50).
Some reported problem with blue chrome key.
Blue case works now.
=> obs-filters: Fix swapped chroma distance values

UI/window-basic-main.cpp
When you right-click on a source in the Sources list that does not have any filters, the "Copy Filters" item is disabled. When you right-click on an audio source in the Audio Mixer that does not have any filters, the "Copy Filters" item is enabled. This fixes the Audio Mixer context menu to behave like the Sources context menu.
When you right-click on a source in the Sources list that does not have any filters, the "Copy Filters" item is disabled. When you right-click on a scene in the Scenes list that does not have any filters, the "Copy Filters" item is enabled. This fixes the Scenes context menu to behave like the Sources context menu.
Consistency is good.  Fixes #4790.
Compiled and ran OBS on Windows 10 after these changes and checked context menus for the Audio Mixer and the Scenes …
=> Disable Copy Filter menu items when source/scene has no filters

.github/workflows/main.yml
This bumps dmgbuild to the latest version in CI.
This is a stopgap until #4560 is reviewed & merged (after 27 is considered stable).
Follow up from #4780. 
Once again, a CI build today failed due to the detach error. We don't want that.
Yes, CI passed with Seeking Testers flag.
=> CI: Bump dmgbuild to 1.5.2 to fix detach error

UI/window-basic-main.cpp
Cancels/ignores a Scene Item move event if there is no source associated with it.
Avoids filling the undo stack with unnecessary noise/data. Also probably avoids some (currently unknown) side effects.
This would appear as `"Undo Move '' in 'Scene Name'"` in the undo stack.
* Deselect all sources in the Sources list
* Click the up or down arrows in the Sources list
* Watch the Edit -> Undo menu & the log
=> UI: Don't execute or track empty SceneItem move actions

UI/window-basic-main.cpp
Replaces the untranslated "Delete Scene" text for the undo action of deleting a scene with the existing "Delete 'x'" string.
Before:
After:
It's not clear which scene would be restored. Additionally, everything should always be translated.
* Delete a scene
* Look in the Edit menu
=> UI: Translate Undo action "Delete Scene" and include scene name

UI/window-basic-filters.cpp
After changes to enable/disable filters stopped working. This was because undo/redo would be disabled 
Fixes bug.
I tested this on my machine.
=> UI: Fix filters changes not properly being added to undo stack

plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
nvenc_create needs to return a value.
Noticed compiler warning. Was very (un)lucky that leftover rax value is the proper value.
Breakpoint inspection. Played back recorded video in VLC.
=> obs-ffmpeg: Add missing return statement

UI/source-tree.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Optimize backup scene for undo/redo
when reordering the sources in a scene all sources that are part of that scene used to be stored as json twice in the stack.
Now sources are only stored and loaded once. For reordering only the scene with its groups are stored.
On windows 64 bit by dragging and dropping sources in the sources list, also tested moving items from and to a group.
=> UI: Optimize backup scene for undo/redo

UI/window-basic-main-outputs.cpp
This PR contains two commits which are separate approaches to solving #4799.  There was some debate about which approach was better, so I'm presenting both as options here for review.
The first commit adds a permanent translation to the active profile config file in `UI/obs-app.cpp` with other upgrade functions.  This approach means that if a user downgraded OBS after this, they would experience #4799, except it wouldn't find the new encoder IDs.
The second commit adds an in-place translation in `UI/window-basic-main-outputs.cpp` before an AdvancedOutput creates a video encoder.  This approach means that the translation happens every time an encoder is created, but it doesn't create new issues if the user chooses to downgrade OBS.
If this PR produces artifacts, or you build with both …
=> Handle mac-vth264 encoder ID changes

deps/media-playback/media-playback/media.c, libobs/obs-source.c, libobs/obs.h
Use unused padding of obs_source_frame/obs_source_frame2 instead.
Bitfields are tough to use portably.
Linear alpha checkbox for media source still works.
=> libobs,deps/media-playback: Avoid bitfields

UI/window-basic-main.cpp
Warp unused parameter with UNUSED_PARAMETER.
Don't like compiler warnings.
OBS compiles and runs.
=> UI: Fix unused parameter warning

plugins/linux-capture/pipewire.c
Properly account for the hotspot by subtracting it from the cursor position.
The cursor bitmap is centered on the hotspot, so not accounting for it means PipeWire captures were positioning the cursor sprite slightly off.
Notice that this is effectively untestable on GNOME without this PR's sibling request: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1901
- Add a PipeWire capture (window or monitor)
- Notice that the cursor is positioned *exactly* where it should be
=> pipewire: Properly account for cursor hotspot

plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Don't purge packets when there are none
The replay buffer sometimes tries to purge packets while there are no packets to purge
With my source record plugin on windows 64 bit
=> obs-ffmpeg: Don't purge packets when there are none

libobs-winrt/winrt-capture.cpp
Latest Windows SDK has a macro for borderless window capture support.
Prepare OBS to WGC capture without border.
Compiles. The property is not present on 21H1, and it correctly returns false. I assume borderless will work on an Insider build as before, but I don't to destabilize my PC by installing that again.
=> libobs-winrt: Use better Windows SDK version check

UI/window-basic-main.cpp
Follow up to PR #3988 and commit 5cdd084c7f946e385748e96306223cd1f1d05b3e. Without this change, displays listed as projector targets on systems using a fractional scaling factor (e.g., 125%, 150%, 175%) will show an incorrect width and height for their size. For a display with 125% scaling, OBS would show 1536x864 instead of 1920x1080. With this change, it will show 1920x1080.
This behavior is new to OBS Studio 26.1, and it does not occur in OBS Studio 26.0.2, so it's a regression. This is because we upgraded Qt from 5.10.1 to 5.15.2, so functions involving screen size or geometry (e.g., QScreen's geometry and width() and height() calls on returned geometry) began returning DPI/scaling aware values for the screen's size, resulting in this changed behavior.
Compiled OBS on Windows 10 …
=> UI: Make projector display resolutions DPI-aware

UI/display-helpers.hpp, UI/window-basic-interaction.cpp, UI/window-basic-main.cpp, UI/window-basic-preview.cpp
Remove ifdefs for fractional scaling support (Qt 5.6+).
This is a companion PR to obsproject/obs-browser#273.
Among the systems we officially support, the oldest Qt version is Qt 5.9 on Ubuntu 18.04. Fractional scaling is supported in Qt 5.6 and newer. We should be able to safely remove these ifdefs and simplify the code.
@WizardCM Wanted me to check what Qt versions FreeBSD and Arch currently offer, and they both offer Qt 5.15.2. Xenial (Ubuntu 16.04) still has Qt 5.5, but we no longer officially support that platform, and its End of Standard Support is April 2021, so I don't think we need to worry about it.
Compiled and ran OBS and obs-browser on Windows 10 64-bit with these changes. I verified that browser interaction and the preview pane behave the same in OBS Studio 26.1.1 and after …
=> UI: Remove fractional scaling ifdefs

plugins/win-capture/duplicator-monitor-capture.c, plugins/win-capture/plugin-main.c, plugins/win-capture/window-capture.c
Check for the device type (OBS renderer) and Windows features when the plugin loads instead of every time a source is created.  The device type (OBS renderer) can only be changed with an application restart, so there's no need to check this whenever a source is created.  Windows Graphics Capture is either supported on the system or it isn't, so we shouldn't have to check whenever a source is created.
Return early in property modified callbacks for `duplicator-monitor-capture.c` and `window-capture.c` if the returned param is null.
Many thanks to @jpark37 for helping me with this.
Fixes #4832.  Less calls to `obs_enter_graphics()`.
I used the code sample from #4832 and compiled on Windows 10 and tested before and after these changes.  After these changes, OBS doesn't crash.
- Bug fix …
=> Fix win-capture null pointer

UI/remote-text.cpp
Rather than silently succeeding, terminate early if a HTTP error (4xx clientside or 500x serverside) is detected. The new messages are from curl directly.
New log uploader error dialog:
Log upload failures are now also logged too.
New Twitch OAuth error dialog:
In most cases, if a HTTP server responds with a 4xx or 5xx error, the data included may not be in the expected format, and would have to be specially handled. 
Currently, if the log uploader fails, it shows an empty box:
If `GetRemoteFile` fails, the user is more likely to see an unhelpful error dialog, such as when Fastly went down & the Twitch OAuth API responded with HTML instead of JSON:
Change this URL:
https://github.com/obsproject/obs-studio/blob/e0edd753ad88230275441d60b3c1832acf1da0e7/UI/window-basic-main.cpp#L5772
To a …
=> Handle HTTP errors in log uploader & file downloader

plugins/linux-capture/CMakeLists.txt, plugins/linux-capture/pipewire-capture.c, plugins/linux-capture/pipewire.c, plugins/linux-capture/portal.c, plugins/linux-capture/portal.h
Don't register captures (window, desktop) that are not supported by the portal implementation. Also, don't create new D-Bus connections and proxies for each capture - do it only once, globally, and reuse these objects.
This was originally noticed at https://github.com/obsproject/obs-studio/issues/4815 - we shouldn't show captures that are not supported by the portal implementation. The fix for this issue made realize we could add an extra optimization on top of it.
- Open OBS Studio on any wlroots-based compositor (e.g. Sway)
- Observe that "Window capture (PipeWire)" is not shown
=> Only register available PipeWire captures

UI/window-basic-main.cpp
Adds a safety check to the pause-functions, double-checking that they
won't be called whether it is already in the desired state.
When calling the PauseRecording and UnpauseRecording functions from for example the frontend-api, the function would still run.
Calling it multiple times can cause this behaviour, visible to the user:
Other functions, like StartRecording also have similar checks in place.
macOS 12, Xcode 12.2
Calling via the frontend api will no longer cause the functions to run if it's already as intended.
=> UI: Check if recording is paused when trying to pause

libobs/callback/signal.c
signal_handler_disconnect_global was not disconnecting, because the struct used to compare was not initialized correctly
I use this function in my plugins, but it was not working, causing OBS to crash when signals where handled on deleted objects.
Using my audio monitor plugin on windows 64 bits
=> libobs/callback: Fix signal_handler_disconnect_global

UI/window-basic-main.cpp
Fixes the Advanced Audio Properties UI panel not visually updating when a source's audio mixers
or sync offset are changed (obs_source_set_audio_mixers or obs_source_set_sync_offset) 
from a non UI thread like from a script timer or hotkey callback.
I made a Lua script to mute/unmute a source on a specific track via a hotkey and it worked
but the Advanced audio properties UI window didn't reflect the update if it was already open 
until closed and reopened which is really confusing to the user. 
When fixing that noticed that setting sync offset has the same issue.
Tested locally on MacOS 11 (x64) with a Lua script:
https://gist.github.com/ratwithacompiler/29faad3348ba52bb8aaa9407a9d5eb4d
=> UI: Fix audio mixer UI not updating from threads

UI/window-basic-main.cpp
Logs visibility transitions alongside scenes, sources, filters & monitoring.
```
15:21:20.195: - scene 'Scene 3':
15:21:20.195:     - source: 'Color Source 3' (color_source_v3)
15:21:20.195:         - filter: 'Color Correction' (color_filter)
15:21:20.195:         - filter: 'Color Correction 2' (color_filter)
15:21:20.196:         - show: 'Color Source 3 Show Transition' (fade_to_color_transition)
15:21:20.196:     - source: 'Window Capture' (window_capture)
15:21:20.196:         - show: 'Window Capture Show Transition' (swipe_transition)
15:21:20.196:         - hide: 'Window Capture Hide Transition' (swipe_transition)
15:21:20.196:     - source: 'Test Nesting' (group)
15:21:20.196:         - source: 'Browser' (browser_source)
15:21:20.196:             - show: 'Browser Pokaż efekt …
```
=> UI: Log Show/Hide transitions on scene collection load

libobs/obs-module.c
-  Size check of obs_source_info is moved before copying in `obs_register_source_s` so that it won't access out of the bounds.
- A macro `HANDLE_ERROR` is fixed to use `data.type_data` and `data.free_type_data` instead of directly accessing `info` to avoid potential out of bounds access if the given `obs_register_source_s` is so small that `type_data` or `free_type_data` is not available.
To avoid memory access out of bounds if a module is compiled with newer libobs version.
I applied this change to OBS 26.0 and intentionally put a module compiled with OBS 27.0.
I added extra `blog` just before `memcpy` and confirmed [memcpy](https://github.com/obsproject/obs-studio/blob/3cc4feb8dd0b57137272157836002c350f7a2d54/libobs/obs-module.c#L634) is not called.
OS: CentOS 8, hardware: i7-7700.
- …
=> libobs: Fix memory overrun if libobs version mismatches

libobs/data/default_rect.effect, plugins/mac-syphon/syphon.m
Fix issue where Syphon Client image was disappearing when outputting RGBA.
Skipping alpha writes is not the same as writing 1.0 to alpha. We want to draw as opaque if transparency is disallowed. This matches the behavior of Game Capture on Windows.
Fixes #4873.
Syphon Client sources were invisible in some contexts.
Verified DrawOpaque is now being called if "Allow Transparency" is false, and checked recorded videos both ways.
=> Syphon Client opaque draws

plugins/text-freetype2/text-freetype2.c
Use `obs_properties_add_color_alpha` instead of `obs_properties_add_color` to set alpha channel for text colors.
Alpha channel is added to the color picker for each color.
Text (GDI+) has alpha property but Text (Freetype 2) does not.
I checked several color and alpha combinations.
Tested on CentOS 8, Intel Core i7700, and its built-in GPU.
Since the defaults for `color1` and `color2` are set to 0xFFFFFFFF, I don't think it broke existing behavior. Since the old color picker returns with alpha channel as 255, existing instances of the source should work without touching.
I reviewed the implementation and checked `gs_reset_blend_state` is called from the `video_render` call back. It expects non premultiplied alpha hence I don't need to touch R, G, and B channels.
I reviewed other plugins …
=> text-freetype2: Add alpha channel property

plugins/linux-capture/pipewire.c
Pass only width and height to `gs_draw_sprite_subregion()`, instead of adding x and y to them. 
The `gs_draw_sprite_subregion()` function is used when a cropping rectangle is received from PipeWire. It is usually used by compositors to implement window screencast - where a large and mostly empty frame is sent, the window contents are only a small part of it, and the crop rectangle tells us that.
Recently the wlroots implementation of portals started to use it to implement cropping, and it exposed a bug in the PipeWire code in OBS Studio. The gs_draw_sprite_subregion() function takes a pair of integers representing position (x, y) and a pair of integers representing size (width, height). The PipeWire code, however, passes a second pair of positions (x2, y2) instead of sizes, and it causes …
=> pipewire: Properly pass sizes to gs_draw_sprite_subregion

UI/window-basic-settings-stream.cpp, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add [Bilibili Live](https://live.bilibili.com/) to rtmp services list.
A live streaming platform in China mainland.
Add support for "Bilibili Live" in rtmp services.
=> rtmp-services: Add "Bilibili Live"

libobs/obs-nix.c
The proposed way to handle plugin distribution through Flatpak depends on these directories to be read. It goes as follows:
1. Flatpak's extension point merges the 'lib' and 'share' directories at /app/plugin
2. Plugins prefix their install paths in the Flatpak manifest to /app/plugins/\<plugin name\>
3. OBS Studio lists /app/plugin as one of the search paths in OBS Studio code
This commit implements the third step of this process, which is the only one that actually involves OBS Studio itself.
Related: https://github.com/flathub/com.obsproject.Studio/issues/135
This change is one of the necessary steps to formalize plugin distribution through Flatpak. With it, it is possible to distribute plugins as Flatpak extensions, which in turn allows them to be listed at app stores such as GNOME …
=> List Flatpak search paths

UI/data/locale/en-US.ini, UI/properties-view.cpp, docs/sphinx/reference-properties.rst, libobs/obs-properties.c, libobs/obs-properties.h
Buttons are very useful. They're even more useful if they can take you somewhere, such as to download a dependency or to open a troubleshooting/FAQ page.
This introduces two button attributes, a `type` & a `url`. If a type is not defined, the button behaves as before.
When @pkviet started working on #3603 it gave me the idea to provide a way for plugins to link to external webpages.
Append this to `duplicator_capture_properties`:
```c
obs_property_t *btn = obs_properties_add_button(
props, "help", "Troubleshooting", NULL);
obs_property_button_set_type(btn, OBS_BUTTON_URL);
obs_property_button_set_url(
btn,
"https://obsproject.com/help");
```
Click the button.
=> libobs, UI: Add support for button properties as links

libobs/obs.c, libobs/obs.h
Adds `obs_enum_all_sources()` which enumerates all sources in OBS, not just scenes or inputs.
There is currently no way to enumerate *all* sources in OBS. Only inputs and scenes have a way to be enumerated. Some applications like obs-websocket's upcoming v5.0.0 release have features that need to take advantage of enumerating all sources in order to function properly.
All sources were enumerated when using `obs_enum_all_sources()` to print the name of each source.
=> libobs: Add `obs_enum_all_sources()` to enumerate all source types

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, docs/sphinx/reference-frontend-api.rst
Returns the path of the current profile's location on the filesystem.
Plugins may need access to the location of the current profile's directory, and currently there is no way to do so without reimplementing lots of code. Some example usages:
- The plugin needs to store/access data files within the current profile's directory (Palakis/obs-websocket#355)
- The plugin needs to have access to files within the profile directory which cannot be accessed via existing methods. Eg. `streamEncoder.json` (Palakis/obs-websocket#676)
- OS: Ubuntu Desktop 20.04
```cpp
char *profilePath = obs_frontend_get_current_profile_path();
if (!profilePath) {
blog(LOG_INFO, "Profile path not found!");
} else {
blog(LOG_INFO, "Profile path is %s", profilePath);
}
bfree(profilePath);
```
Operation returned profile …
=> UI: Add obs_frontend_get_current_profile_path() to frontend-api

UI/obs-app.cpp, UI/obs-app.hpp, UI/window-basic-main.cpp
Adds `--disable-missing-files-check` as a startup flag. Prevents the missing files popup from being spawned if missing files are found.
Just like there is a flag for `--disable-updater`, users may be using OBS in an environment where they do not want any popups when OBS launches. This would be helpful for both power users and anyone who uses OBS in an automated fashion.
Using `--disable-missing-files-check` when launching OBS via the command line successfully prevents the popup from appearing.
=> obs-app: Add startup flag to disable missing files window

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main-profiles.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-frontend-api.rst
Adds front-end API functions: 
+ `obs_frontend_create_profile(const char *name)`
+ `obs_frontend_duplicate_profile(const char *name)`
+ `obs_frontend_delete_profile(const char *profile)`
Tested on Win 10 & macOS 11.2:
* Create new profile with unique name - success
* Create new profile using an existing profile's name - no profile created, warning logged
* Create duplicate profile with unique name - success
* Create new profile using an existing profile's name - no profile created, warning logged
* Delete currently selected profile - success, current profile switches to a valid existing profile
* Delete profile not currently selected - success
* Delete profile that doesn't exist - warning logged
* Delete sole profile - silent fail
- New feature (non-breaking change which adds …
=> UI: Add obs-frontend-api functions to create/delete profiles

UI/window-remux.cpp
When a recording is automatically remuxed, the text on the status bar would wrongly show the name of the file being remuxed, not the file being remuxed to.
Fixes this bug, now the name/path of the new file is being shown:
Got noticed on the Discord server
macOS 12, compiled and issue was fixed.
For those worried, a quick project-level search shows that `autoRemuxFile`, which is being changed by this fix, is only intended for and used by the statusbar, and not by anything else, so nothing else should break.
=> UI: Fix displayed autoremux file name

libobs/data/default.effect, libobs/data/default_rect.effect
Necessary for an upcoming fix to browser source, obsproject/obs-browser#300.
Need browser source alpha to behave like the rest of OBS.
Windows and Mac return the correct colors.
=> libobs: Add DrawSrgbDecompressPremultiplied technique to default effects

docs/sphinx/reference-sources.rst, libobs-d3d11/d3d11-duplicator.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs-opengl/gl-subsystem.h, libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-capture.h, libobs/data/default.effect, libobs/graphics/graphics.h, libobs/obs-internal.h, libobs/obs-scene.c, libobs/obs-source.c, libobs/obs.h, plugins/win-capture/dc-capture.c, plugins/win-capture/dc-capture.h, plugins/win-capture/duplicator-monitor-capture.c, plugins/win-capture/game-capture.c, plugins/win-capture/monitor-capture.c, plugins/win-capture/window-capture.c
There are situations where rescaling sources with scale filtering disabled can lead to divergent behavior. These series of commits attempt to make these situations consistent by computing bilinear filtering in linear space with shader instructions if the sampled texture is not able to do the conversion automatically.
Consistency is good.
Manual bilinear sampling adds extra cost.
- NVIDIA RTX 3090, 1080p Draw, before: 28 µs
- NVIDIA RTX 3090, 1080p Draw, after, skip copy: 29 µs
- NVIDIA RTX 3090, 1080p Draw, after, extra copy: 60 µs
- Intel UHD Graphics 750, 1080p Draw, before: 497 µs
- Intel UHD Graphics 750, 1080p Draw, after, skip copy: 709 µs
- Intel UHD Graphics 750, 1080p Draw, after, extra copy: 728 µs
=> Manual SRGB filtering

plugins/decklink/decklink-device-mode.cpp, plugins/decklink/decklink-device-mode.hpp, plugins/decklink/decklink-output.cpp
- Changes the formats dropdown for Decklink output to only show formats using the same framerate as OBS does.
- Prevents the output from starting if the configured Decklink output FPS differs from the current OBS FPS.
OBS cannot perform framerate conversions, meaning that if OBS's framerate is set to 45fps, and decklink output is set to 60fps, the output will either lag heavily or simply not function.
Changed OBS's framerate, opened the Decklink output dialog. It only shows compatible rates.
=> decklink: Don't show incompatible formats in Decklink output window

CI/flatpak/com.obsproject.Studio.json, libobs/CMakeLists.txt, libobs/util/platform-nix-portal.c, libobs/util/platform-nix.c
Add a new portal-based inhibitor. This inhibitor is only used when the Desktop portal is available and running; the previous D-Bus implementation is used in the absence of the portal.
XDG Portals provide a plethora of features meant to be used inside and outside sandboxed environments. OBS Studio currently uses portals to implement Wayland-compatible monitor and window captures.
However, OBS Studio performs another action that can be done through portals: inhibit the screensaver. Under the Desktop portal (the same used by the captures mentioned above), there is an "Inhibit" portal that provides session inhibition.
Using portals is desired because they allow tightening the sandbox, and are well-defined integration points to modern platforms.
- Perform any regular action that inhibits the …
=> Portal-based Inhibitor

libobs/obs-scene.c
There is a bug in function 'build_current_order_info' (obs-scene.c): the obs_sceneitem_t* items are pushed into DARRY of 'struct obs_sceneitem_order_info'.
Most of the time it won't crash, but if we enable the 'AddressSanitizer' tool in VS 2019, the da_push_back will always triggered the Exception "Stack buffer overflow", because we do memcpy 2*sizeof(obs_sceneitem_t*) bytes from a sizeof(obs_sceneitem_t*) bytes buffer.
(1)Enable 'AddressSanitizer' tool in VS 2019
(2)Drag and drop source in source list to change the order
=> libobs: Fix stack buffer overflow in build_current_order_info

libobs/media-io/video-frame.c, libobs/obs-source.c
When playing video, OBS can overflow and crash, or render video edges
incorrectly if the video resolution does not divide into 2 for trivial
chroma subsampling. This is fixed by rounding chroma plane sizes up
instead of down, and maintaining that through the video pipeline.
Crashing is bad. Green edges are bad.
Tested odd/even resolutions for UYVY, NV12, I420, I40A, I422, and I42A.
=> libobs: Round up chroma sizes for odd resolutions

plugins/decklink/decklink-device-mode.cpp, plugins/decklink/decklink-device-mode.hpp
Also simplify DeckLinkDeviceMode::IsEqualFrameRate using cross-multiply.
Don't like compiler warnings.
Breakpoint inspection, Filtered mode list is the same before and after change.
=> decklink: Fix truncation warnings

UI/source-tree.cpp, UI/window-basic-main.cpp
This reverts commit 457adcedd319ca2317d7cd5300694d486e88af90. Requires https://github.com/obsproject/obs-browser/pull/304
Drag n' Drop was temporarily reverted due to https://github.com/obsproject/obs-studio/issues/4488, but https://github.com/obsproject/obs-browser/pull/304 supposedly fixes it.
- Try and reproduce https://github.com/obsproject/obs-studio/issues/4488 - it shouldn't be reproducible anymore with this PR, and https://github.com/obsproject/obs-browser/pull/304
=> Reenable drag/drop on Linux scenes/sources

plugins/obs-filters/mask-filter.c
Makes behavior of blend addition more reasonable.
Fixes #5048
0 + x should equal x.
Tested 16/16/16 on 0/0/0 is now 16/16/16 instead of 71/71/71.
=> obs-filters: Use linear value of secondary texture

plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
VAAPI properties were not all being run through translation, which was incredibly obvious in non-English. This ensures they are.
I do wonder if some of the dropdown options should also have translation keys - I'm open to feedback here.
Before:
After:
(notice "Profile" is now correctly translated)
User-facing strings should always be translated.
Loaded a FFMPEG VAAPI encoder on Ubuntu & verified strings were translated.
=> obs-ffmpeg: Translate VAAPI property names

UI/window-basic-main.cpp
Fix undo delete scene that is used as source
When deleting a scene that is used in other scenes it was not restored correctly in the other scenes.
On windows 64 bit by deleting scenes and using the undo and redo.
=> UI: Fix undo delete scene that is used as source

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adds [Lovecast](https://www.lovecastapp.com/) to rtmp services list.
A live wedding/event streaming platform.
Add support for "Lovecast" in rtmp services.
=> rtmp-services: Add "Lovecast"

UI/api-interface.cpp, libobs/util/cf-lexer.h
Inspired by the issue #5009, I checked all the argument types for `da_find`, `da_push_back`, `da_push_back_da`, `da_insert`, `da_insert_array`, `da_insert_da`, and `da_erase_item` by using [this test](https://github.com/norihiro/obs-studio/tree/test-darray-type) on Linux. The idea was inspired by [this article](https://stackoverflow.com/questions/4712720/typechecking-macro-arguments-in-c) and modified a little to make the message more readable.
Two similar issues are found and this PR fix them.
If these two changes are put in one commit, please let me know so that I will modify the commit.
Currently the test mentioned in above shows some false warning regarding `char**` and `const char**` so that I think it is not worth to merge into master branch.
The macro `da_push_back` has to receive …
=> Fix argument type mismatches on the macro da_push_back

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Replays from the replay buffer will be automatically remuxed to MP4 like
recordings are, if autoremux is enabled.
Fixes #4998 
macOS 12.0, compiled and run.
When the Replay Buffer is saved, the replay is being remuxed. Works both by saving from UI as well as frontend-api.
Recording autoremux is unaffected. When stopping recoding and saving buffer at the same time, both files will get remuxed properly.
=> UI: Autoremux Replay Buffer

UI/window-remux.cpp
Fixes a bug where the progress bar for autoremuxes wouldn't be made
visible when it started, and only a blank popup window appeared.
Turns out that the progress bar wasn't made visible when autoremuxing, only for normal remux:
https://github.com/obsproject/obs-studio/blob/725fce78bafda3834767d75be04a961eed8967f0/UI/window-remux.cpp#L856
When stopping a recording and autoremux is enabled, this blank window appeared:
The moment the remux is finished, the progress bar appears in the window:
This is obviously not how the progress bar is supposed to work :D.
On smaller recordings most people probably don't notice, but bigger files (>200MB in my case) that take longer definitely made this issue obvious.
macOS 12, compiled and run.
Progress bar is properly shown during the remux:
- Bug fix …
=> UI: Show autoremux progress bar

UI/data/locale/en-US.ini
Fix one locale text for the YT integration by replacing '&&' with 'and'.
Consistency with the other two texts "Create and Go Live" and "Choose and Go Live".
/
/
=> UI: Replace '&&' with 'and' in YT integration

libobs/util/platform-nix.c
The unit of `/proc/<pid>/statm` is the page size of the system. The value retrieved from `statm` should be multiplied by `sysconf(_SC_PAGESIZE)`.
Memory usage displayed on Stats was too small due to a misaligned unit of `resident_size` read from `statm` file and libobs's `os_proc_memory_usage.resident_size`.
This is the Stats window before fixing the issue. Memory usage is 0.1 MB, which is obviously too small.
This article shows a screenshot with `Memory Usage 0.0 MB` on OBS Studio 25.0.8 from PPA. I checked changes from 25.0.8 in stats window and util but cannot found any fix of the memory usage.
https://www.linuxandubuntu.com/home/obs-studio-stream-from-linux
This is the Stats window after fixing the issue.
I tested as screenshots above on CentOS 8.
I have not tested on Ubuntu. Someone …
=> libobs/util: Fix reading memory usage on Linux

UI/api-interface.cpp
Send OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP
OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP was never send.
The only place triggering it is in [ClearSceneData()](https://github.com/obsproject/obs-studio/blob/bab21888f389cf16c2966d9c7a099682dd6f4974/UI/window-basic-main.cpp#L4388)
but disableSaving is always set there by the function itself and by the calling functions so the line in this PR blocks it
other events like OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGED still need to be blocked while loading
On windows 64 bit receiving OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP in a plugin. 
=> obs-frontend-api: Send OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP event

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-frontend-api.rst
Add functions to open properties and filters
Allow plugins to open the properties and filters windows of a source
With changes to my source dock plugin on windows 64 bit
=> UI: Add functions to open properties and filters

deps/media-playback/media-playback/media.c, libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-d3d11/d3d11-vertexbuffer.cpp, libobs/graphics/effect.c, libobs/obs-source.c
Fix a couple issues, one is heavy lock contention on allocations, and the other issue is CPU usage from busy-waiting for accurate times when we don't care about accuracy all that much.
OBS uses a lot of CPU when there are many media sources, and can even lock up entirely.
OBS no longer freezes because of allocation locks with many sources on my machine, and saw CPU usage drop from 1.1% to 0.8% when one video is playing for the sleep change. No new leaks for the darray usage change.
=> Various optimizations for media playback

plugins/linux-capture/linux-capture.c
Load the XSHM capture on EGL/X11 too, in addition to the PipeWire captures.  Rework the obs_module_load() function of linux-capture to use a switch statement, and load XSHM both on EGL/X11 and GLX/X11.
Fixes https://github.com/obsproject/obs-studio/issues/5122
Unlike Xcomposite, the XSHM plugin does not use GLX code, and thus can be used on when EGL renderer is used. It still is X11-specific though, and shouldn't be used on Wayland.
* On Linux, run OBS Studio on X11 with `OBS_USE_EGL=1`
* The XSHM window capture must be enabled (but *not* the Xcomposite screen capture)
* The PipeWire captures must be enabled
=> linux-capture: Load XSHM capture on EGL/X11

plugins/obs-outputs/net-if.c
Fix inet_ntop()/inet_pton() being called with an incorrect argument for
IPv6 addresses.
On Linux, the offset of the sin_addr and sin6_addr fields differ and
the confusion on the inet_ntop() call produces an erroneous IPv6 string
representation such as "0:0:2001:db8::". This is visible on the UI,
Settings -> Advanced -> Network -> Bind to IP.
The same goes for the inet_pton() call.
Tested on my Linux machine that OBS Studio can bind to the specified IPv6 address and connect to an RTMP server.
=> obs-outputs: Fix binding to IPv6 addresses on *nix

UI/obs-app.cpp
Since Qt doesn't use Wayland by default only under session with `XDG_CURRENT_DESKTOP=GNOME` like Gnome Shell or Phosh.
**We now force Qt with OBS to use Wayland under Wayland sessions directly in the code, the user still can choose an other platform if he needs to.**
~~- I made the original entry invisible in a session with `XDG_CURRENT_DESKTOP=GNOME` and also change his action name from "New Window" to "New Instance". (I can undo the name change, if  needed)
Why "Instance" ? Because it makes more sense since OBS asked if you really want to run an another instance of OBS when already launched~~
~~- I added a new entry which only show under GNOME with a second action to launch it with `-platform wayland`~~
~~**Once this Qt issue is resolved and any Qt LTS with this behavior is unsupported, …
=> UI: Force Wayland usage under Wayland session

UI/youtube-api-wrappers.cpp
This change makes `LiveStream` object created by OBS non-reusable, meaning the stream key is deleted once the broadcast ends and does not show up in the YouTube Web UI or API.
As observed by @Gol-D-Ace during testing the current implementation would create a new stream key every time a broadcast is started, resulting in the list of stream keys on the YouTube websites containing duplicates for every time a stream was started in OBS.
Using this method the YouTube website will show "Auto-generated key" instead and the key will not be exposed through the Web UI. It will be automatically disposed of when the broadcast ends.
1. Started stream
2. Stopped stream
3. Observed that no stream key was left visible on the YouTube API or website
=> UI: Create YouTube LiveStream objects as non-reusable

UI/frontend-plugins/frontend-tools/scripts.cpp
Fix crash on shutdown
crash on shutdown introduced by #4504
On windows 64 bit
=> frontend-tools: Fix crash on shutdown

deps/media-playback/media-playback/decode.c, deps/media-playback/media-playback/media.c
For media file whose _best_effort_timestamp_ of audio frame is AV_NOPTS_VALUE, when "loop" is choosen, its audio can't be played after first EOF. 
[test file.zip](https://github.com/obsproject/obs-studio/files/6838898/test.file.zip)
For this kind of file, make sure the audio can be played normally when loop is choosen.
1. add media source for the attached file, choose "loop", enable audio monitor;
2. wait for playing to end, then it will be played from 0 again;
3. check the audio monitor.
=> deps/media-playback: Fix bug about audio without best_effort_timestamp

plugins/win-capture/graphics-hook/d3d12-capture.cpp
Use D3D12_RESOURCE_STATE_PRESENT for CreateWrappedResource arguments. We
should assume the application will set the backbuffer to PRESENT, and
expect that to be preserved across the Present() call.
Remove unnecessary calls to ReleaseWrappedResources.
Clean up (void**) casts with modern patterns.
Noticed some bad usages from code inspection.
Debugger breakpoint inspection of MS DX12 sample using game capture hook.
=> graphics-hook: Fix D3D11On12 usages

plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt, plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Moves the DAL plugin to the data directory of the mac-virtualcam. 
Until now, the DAL plugin was just lying in the top-level data directory next to the libobs, obs-plugins,
and obs-studio directory, which was kind of bothering.
macOS 11.2.3, Xcode 12.2
Virtual cam is still installed, both when running OBS within and outside of the app bundle.
=> mac-virtualcam: Move DAL plugin to plugin data directory

plugins/rtmp-services/data/services.json
Adds BoxCast to rtmp services
Adds Boxcast to the list of available streaming service providers 
Allows Boxcast customers a readily available way to stream to the Boxcast client services using OBS Studio
Tested locally on Garuda Linux
=>  rtmp-services: Add BoxCast

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, plugins/obs-transitions/transition-stinger.c
Adds transitions to the missing files check, allowing for stinger
transitions to be shown in the dialog
With my transition named "Stinger", this is how it looks.
Also works with the separate matte file (even though that isn't yet enabled in OBS anyways).
When a stinger file got removed/renamed/whatever, the transition would silently not show up. 
This should help fix this.
macOS 12.0 beta 5, Compiled and run
When moving or renaming the file, the dialog would pop up as intended, and
setting a new file will change the setting in the properties window
=> UI,obs-transitions: Enable missing files dialog for stinger transition

UI/window-basic-settings.cpp
Fixes an issue where in the hotkey settings, some header labels wouldn't
be styled as intended, specifically not bold.
See the screenshots, before:
After:
QSS-wise, the style from the source specific label function has been taken over.
From:
https://github.com/obsproject/obs-studio/blob/a9352985c797a3a0fe75ae8ba89013f30dc4b5ab/UI/window-basic-settings.cpp#L2628-L2633
Doesn't fit the rest of the labels style wise
macOS 12, compiled and run.
See screenshot above.
=> UI: Apply QSS to generic hotkey settings label

UI/data/locale/en-US.ini, UI/window-basic-transform.cpp
This updates the Edit Transform window title to include the name of the scene item being edited.
Consistency with the Properties and Filters windows.
This is also a helpful stopgap until someone can make other UX improvements to the Edit Transform window with how it handles multiple selected sources.
Ensured the window title updates correctly when switching sources, deselecting sources, and selecting multiple sources.
=> UI: Show name of scene item in Transform window title

UI/obs-app.cpp, UI/platform-osx.mm, UI/platform.hpp
macOS looks if the NSUserDefault NSFullScreenMenuItemEverywhere is set
to true, and if it is, it adds its own full screen menu item.
Sets this NSUserDefault to false since it defaults to true.
Before: 
After:
One drawback is that the call to save the setting is made every time OBS is opened.
Now, while NSUserDefaults is thread safe and doesn't interrupt anything else, it isn't the most pretty thing to do.
The problem is that, to my knowledge, there is no macOS onboarding process or something that runs on install-time, and creating something like that is out of scope. If someone ever creates one, this should get moved there.
There currently are two menu items that let the user switch to full screen, one added by OBS and one by macOS.
Removes the one macOS adds by default, while leaving the …
=> UI: Remove macOS-Default Full Screen Menu Item

UI/source-tree.cpp, UI/source-tree.hpp
Dims the items of hidden sources in the sources dock to make it more
obvious that they are not visible. Both the icon and the sources name
are affected.
Before: 
After: 
I also wanted to change the lock to always be dimmed, but the colour seems to be baked into the .svg files of the icons. The solution would probably be to create a third icon (which shows the closed lock in dimmed) and switch to that when the source is hidden, unfortunately how the icons get into the program with QT is magic to me. I'll leave that either for someone else to do or would need further advice from someone knowledgeable in that department.
`QLabel *iconLabel` has been moved to the header to give other functions access to it.
Saw this on the ideas page and thought it was a good idea. …
=> UI: Dim hidden source items in source tree

plugins/win-capture/graphics-hook/d3d10-capture.cpp, plugins/win-capture/graphics-hook/d3d11-capture.cpp, plugins/win-capture/graphics-hook/d3d12-capture.cpp, plugins/win-capture/graphics-hook/dxgi-capture.cpp, plugins/win-capture/graphics-hook/graphics-hook.h
Doesn't make sense to grab the oldest frame when not capturing overlays, because the overlay was already rendered in it.
This will grab the latest frame.
The "Capture third-party overlays (such as steam)" option in Game Capture wasn't working properly, it would capture overlays at all times if the game uses DirectX 12, regardless of this setting.
Fixes #3946
Tested in Modern Warfare (2019) and Civilization 6 in DX12 mode (with discord and steam overlays).
Bug fix.
=> graphics-hook: Fix D3D12 third party overlay capture setting

UI/data/locale/en-US.ini, UI/remote-text.cpp, UI/remote-text.hpp, UI/window-basic-settings-stream.cpp, UI/window-youtube-actions.cpp, UI/window-youtube-actions.hpp, UI/youtube-api-wrappers.cpp, UI/youtube-api-wrappers.hpp
These changes are intended to improve how YouTube API errors are exposed to the user and fix a few issues found during debugging/testing.
Several issues such as live streaming not being enabled on a channel or a Google account without YouTube channel being used during the OAuth process are currently not properly explained to the user.
The API to retrieve existing broadcasts was used poorly, leading to potentially hundreds of requests made only to throw their results away since *every single broadcast* on a channel was fetched, rather than only those we care about (live, scheduled). This PR also adds an indicator to the list informing the user that data is still being fetched from the API.
Additionally resuming a stream that was interrupted (e.g. due to OBS crashing) was not possible, and …
=> Various YouTube Integration improvements and fixes

UI/data/locale/en-US.ini, UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Adds an entry to the "Scene Collection" tab of the menu bar that makes
the missing files dialog come back in case it got dismissed of files got
removed while OBS was open.
This is the UI change (edited):
If files are missing, the regular missing files dialog shows up.
If no files are missing, this popup will show:
Currently, the only way to get the missing files dialog back is by either switching scene collections or by restarting OBS.
Sometimes it would be good to get it back more easily, for example if you dismissed it when it came up originally only to notice that you in fact do need it. This should simplify that process.
macOS 12.0 beta 5, compiled and run.
Popups show as intended (described above).
=> UI: Add menu bar item to show missing files dialog

UI/forms/OBSBasic.ui, UI/window-basic-main.cpp
This shows the source icon next to the source label in the
context bar.
Makes it easier for users to tell what the current source is.
Switched between sources to make sure icon updated properly.
=> UI: Show source icon in context bar

UI/forms/AutoConfigStreamPage.ui, UI/forms/OBSAbout.ui, UI/forms/OBSBasicFilters.ui, UI/forms/OBSBasicInteraction.ui, UI/forms/OBSBasicSettings.ui, UI/forms/OBSBasicTransform.ui, UI/forms/OBSExtraBrowsers.ui, UI/forms/OBSImporter.ui, UI/forms/OBSMissingFiles.ui, UI/forms/OBSRemux.ui, UI/forms/OBSUpdate.ui, UI/forms/source-toolbar/game-capture-toolbar.ui, UI/forms/source-toolbar/text-source-toolbar.ui
This applies similar fixes to those in #5133 to the rest of the UI forms
After #5133 and this PR are merged, all UI forms in the project should now open in Qt Creator/Designer and resave without any entries being shuffled around or clobbered
Before this change, the changed QWidgets in the form files are not properly shown in Qt Creator, only their associated layouts are displayed and their QWidget properties are not accessible or shown. These widgets will also get completely removed upon saving.
After these changes, the items are properly listed in the Qt Creator hierarchy.
Qt Creator/Designer is the primary method for building UI forms and all our form files should open and save without creating unnecessary history changes
All forms have been compared against v27.0.1 to ensure they still …
=> UI: Clean up other UI form file markup

UI/window-basic-source-select.cpp
Fixes an issue where if creating a new source was re-done from a
different scene, the source would be created first in that scene and
then OBS would switch to the scene where the source originally was
created.
Changes the order of these two operations, which makes OBS create the
source in the correct scene.
Noticed this bug while doing another PR.
To reproduce (100% reproducible on every try):
- Have any scene collection with at least 2 scenes
- Create a new source - when prompted with the properties dialog, either press cancel, or change properties and press OK, but keep in mind you'll create 2 undo/redo actions
- Undo
- If you previously pressed "OK" instead of "Cancel", Undo again
- Switch to a different scene
- Redo
You will get thrown back into the scene where you created the source, …
=> UI: Fix redo recreating sources in the wrong scene

libobs-winrt/winrt-capture.cpp
Replace casts that trigger implicit conversion with simple data access.
I dislike magic. I also dislike the MS employee who thought it was a good idea to replace `HRESULT` with `winrt::hresult`, especially in an API that was already public.
Compile still works, WGC still works. Breakpoint inspected a couple catch blocks, but not all of them.
=> libobs-winrt: Replace casts with data access

UI/display-helpers.hpp, UI/forms/OBSBasicSettings.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-settings.cpp, UI/window-projector.cpp, UI/window-projector.hpp
The adds an option in the settings to show safe areas in the preview.
https://ideas.obsproject.com/posts/843/draw-safe-areas-ebu-r95-on-preview-window
Made sure it rendered properly in preview.
=> UI: Add option to draw safe areas in preview

UI/log-viewer.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Commit 1 - Removes redundant code when using log viewer on startup.
Commit 2 - Deletes the log viewer when closing it, instead of hiding it.
Cleanup of code.
Open and closed log viewer to make sure everything was deleted properly.
- Bug fix
=> UI: Log viewer fixes

UI/auth-youtube.hpp
Avoiding duplicating the vector in every file that includes this header. Mostly making this as a PR to check `inline const` is available in all our CI builds (C++17).
Sharing constants is better.
OBS still compiles.
=> UI: Use inline const for shared vector

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Dark/left.svg, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/forms/OBSYoutubeActions.ui, UI/window-basic-main.cpp, UI/window-youtube-actions.cpp
Removes some hardcoded styles, removes the minimum size on the YouTube actions window (Which would let you shrink it smaller than it needs to be), and adds styling to the new widgets used for the integration on all themes.
There were places where styling was hardcoded or just non-existent due to the use of widgets we haven't used yet.
Tested all themes with these changes and ensured all widgets appeared correctly.
=> UI: Add styling for YouTube integration

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/obs-app.cpp
QPalette is useful for removing duplicate styling definitions. Unfortunately, due to the incorrect order of operations when loading stylesheets into OBS, the default palette would also be loaded when parsing the stylesheet, resulting in unusable macros.
Based on the above change, I've modified all built in themes to use the palette where possible, making colour definitions clearer. Documentation on this capability can be found [here](https://doc.qt.io/qt-5/stylesheet-reference.html#paletterole).
Additionally, while consolidating variables in the themes, I noticed that `highlightedText` was defined incorrectly in theme files, so it was being ignored:
https://github.com/obsproject/obs-studio/blob/5d54cc36a7b4d4fa384de015e55c3249b5b7eaca/UI/obs-app.cpp#L910-L911
I've also gone through and …
=> UI: Fix support for QPalette in Qt Stylesheets

plugins/decklink/decklink-source.cpp
If the option to deactivate when not showing was on, the Decklink
input device wouldn't deactivate/activate when hiding/showing.
Noticed when testing with Decklink devices.
Toggled the visibility of the Decklink source, to make sure it deactivated/activated properly.
=> decklink: Fix deactivate when not showing

plugins/win-capture/game-capture.c
Fixes shmem crashes when using Alt+Tab.
Fixes #5208
No longer crashes. Game feed comes back.
=> win-capture: Clear stale pointers for game capture

UI/window-basic-main-transitions.cpp
Fix crash when output source 0 is null
When trying to switch scenes while output source 0 is null obs will crash on obs_transition_get_time
On windows 64 bit by starting OBS with loads of plugins multiple times. ±1 out of 5 times obs will start without setting output source 0 on startup
=> UI: Fix crash when output source 0 is null

UI/youtube-api-wrappers.cpp
Ensures description and other options are carried over when `ResetBroadcast` is called.
A better way to fix this problem (and avoid calling `ResetBroadcast` alltogether) would be to transition a broadcast that has monitoring enabled to `testing` before going `live`, but that would require waiting for several seconds and should probably have UI feedback as well.
Users complained about description being reset when starting scheduled broadcast.
Scheduled broadcast, ensured description isn't lost when starting.
=> UI: Add missing properties to ResetBroadcast

UI/forms/OBSYoutubeActions.ui, UI/window-youtube-actions.cpp
Changes description from `QLineEdit` to `QPlainTextEdit` to allow for multi-line descriptions
Result:
Descriptions can have newlines.
Created broadcast with multi-line description.
=> UI: Change YouTube description input to QPlainTextEdit

UI/window-basic-main.cpp
Fixes #5199 and an additional bug where the UI and internal state of the broadcast configuration isn't reset when force-stopping (e.g. when discarding remaining delayed stream data).
Bugs are bad.
- Tested delayed stream without autostart to make sure the check thread still works
- Tested stopping a delayed stream (forced/unforced)
- Tested force-stopping a delayed stream before it starts (to verify thread gets cleaned up)
=> Fixes for YouTube integration when delay is enabled

UI/window-youtube-actions.cpp, UI/youtube-api-wrappers.cpp, UI/youtube-api-wrappers.hpp
If a language or country is not set in the YouTube channel data, we should fall back to the OBS locale rather than `en-US`.
YouTube Category names were not locallised unless the channel had a default language assigned (apparently automatically by YouTube). Furthermore the country or region requires manual configuration by the user otherwise it will also be unset.
Set OBS language to something other than `en-XX` and verified that the categories now are in that locale's langauge.
=> UI: Use OBS locale for YouTube categories API

UI/forms/OBSBasicSettings.ui
The fixes in #5143 caused the audio pane in settings to stretch out to fit the available space.
Add a spacer so the pane only uses the space it needs.
These group boxes shouldn't stretch
Checked the audio pane of Settings
=> UI: Fix vertical stretching in audio settings pane

UI/window-basic-settings-stream.cpp, UI/window-youtube-actions.cpp, UI/youtube-api-wrappers.cpp, UI/youtube-api-wrappers.hpp
- Cleanup
+ Remove unused `BindDescription` struct from `youtube-api-wrappers.hpp `
+ Remove unused members of `ChannelDescription` and `StreamDescription` structs as well as related code
- Fixes
+ Restore `auth.reset()` on service switch (Fixes #5236)
Obsolete code makes us unhappy. So do bugs.
Compiled on Windows, verified that #5236 is no longer happening.
=> More YouTube cleanup and fixes

UI/source-tree.cpp, UI/window-basic-filters.cpp, UI/window-basic-interaction.cpp, UI/window-basic-main.cpp, UI/window-basic-properties.cpp, UI/window-basic-source-select.cpp, UI/window-namedialog.cpp
Disable hotkeys when a user starts an interaction with the UI where they are expected to type text and re-enable hotkeys when the interaction is completed.
This PR disables OBS hotkeys during the following user interactions:
* renaming sources
* renaming scenes
* renaming audio sources in the mixer
* while in the source/scene deletion confirmation dialog
* adding a source (the add source dialog)
* the filters window
* the properties window
* source interact mode
OBS resumes listening for hotkeys after those user interactions end.
Not covered by this PR:
* typing in browser source docks (e.g., Twitch/Mixer Chat or Stream Information docks)
Extended discussion on [Idea 144: Better media source playback control](https://ideas.obsproject.com/posts/144/better-media-source-playback-control) …
=> UI: Disable hotkeys when a user is expected to type text

libobs/graphics/graphics.h, libobs/util/windows/ComPtr.hpp
Fix minor static analysis warnings.
Don't like warning spam.
Breakpoint inspection.
=> libobs: Fix minor static analysis warnings

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adds [Disciple Media](https://www.disicplemedia.com) to the rtmp services list.
Disciple is a community platform with live streaming capabilities.
Add support for Disciple Media for OBS users
Local / CI build
=> rtmp-services: Add "Disciple Media"

UI/volume-control.cpp, UI/volume-control.hpp
Get rid of the time-critical timeSetEvent thread on Windows.
Trying to reduce CPU usage/contention. Doesn't solve the stalls on Windows 11, but it shouldn't hurt.
Volume meters still appear to update.
CPU% in status bar looks the same, but getting rid of a thread should be a positive.
Verified updates still amortize to 60 FPS with temporary timing code. Audio updates were actually firing at 100 Hz on my PC.
=> UI: Update volume controls by callback

UI/obs-app.cpp, UI/window-basic-main.cpp
There are two commits in this PR.  One commit fixes a Qt6-incompatible call to QLocale::setDefault.  The other commit fixes a Qt6-incompatible operator usage with two Qt::Modifier instances.
----
UI: Fix Qt6-incompatible call to QLocale::setDefault 
The YouTube integration changes introduced code that does not build on Qt6. The errors were:
* void QLocale::setDefault(const QLocale &)': cannot convert argument 1 from 'QString' to 'const QLocale &'
* no suitable user-defined conversion from "QString" to "const QLocale" exists
This commit creates a new QLocale in place from a QString using the `QLocale(const QString &name)` constructor, and passing that QLocale to QLocale::setDefault.
----
UI: Fix Qt6-incompatible operator usage
Commit 60d95cb5 introduced some code that used the + operator …
=> Fix Qt6 compatibility issues

UI/window-basic-auto-config-test.cpp, UI/window-basic-auto-config.cpp, UI/window-basic-auto-config.hpp
Enables bandwdith testing for YouTube if service integration is used. Also sets target bandwidth to YouTube maximum of 51 Mbps rather than using default of 10.
Bandwidth testing for YouTube was originally disabled due to the created video resulting in temporary strikes due to YouTube's content filters determining the content to be spam.
With the YouTube integration we can instead simply create a throwaway stream key without any attached broadcast, meaning that no video will be created, and nothing we send will be saved. That way we can safely test the bandwidth to the YouTube servers.
- Ran bandwidth test
- Made sure UI properly resets and locks out bandwidth test if account is disconnected
=> UI: Enable AutoConfig bandwidth test for YT integration

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs/util/windows/win-version.h
Windows 11 support for DISCARD swap effect seems to be buggy and slow.
Use FLIP_DISCARD instead. Staying with DISCARD on Windows 10 because of
reports of flickering that hopefully won't happen on Windows 11.
We're also not using ALLOW_TEARING because it seems to break after an
OBS cycle of minimize/restore on both Windows 10 and 11. The swap chain
displays a stale image. Not sure if ALLOW_TEARING would be beneficial
even if it was working.
Fixes #4807.
Fixes #5097.
Don't want OBS to run terrible on Windows 11.
Verified responsiveness fixed on Windows 11 insider build by moving mouse back and forth to check button hover response in bottom-right of OBS. Windows 10 21H1 continues to work fine.
=> Fix Windows 11 responsiveness using FLIP_DISCARD

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp
ALLOW_TEARING is supposed to be better.
Seems like MS wants us to use this.
Swap chain continues to work through resize and minimize/restore. Checked WIndows 10 and Windows 11.
=> libobs-d3d11: Use ALLOW_TEARING if supported

CMakeLists.txt, libobs-winrt/winrt-capture.cpp
Update minimum Windows SDK version to 10.0.20348.0.
Necessary for borderless WGC support to be compiled in. Also for future support of per-process audio capture.
Borderless WGC works on Windows 11 preview build.
Verified build does not compile on 19041, and reports error message.
=> Windows SDK 10.0.20348.0

libobs/obs-encoder.c
This makes it a bit more clear when muxing takes longer than expected
instead of attributing the time to the do_encode.
Should help to inform us when muxing and not encoding is resulting in their encoder overload, such as on recording on slow devices.
I recorded a video and had the resulting profile.
```
info: video_thread(video): min=4.93 ms, median=7.688 ms, max=1003.55 ms, 99th percentile=11.924 ms
info:  ┗receive_video: min=1.014 ms, median=1.385 ms, max=999.418 ms, 99th percentile=4.454 ms
info:    ┗do_encode: min=1.013 ms, median=1.384 ms, max=999.417 ms, 99th percentile=4.453 ms
info:      ┣encode(streaming_h264): min=1.003 ms, median=1.342 ms, max=23.443 ms, 99th percentile=2.824 ms
info:      ┗send_packet: min=0.003 ms, median=0.027 ms, max=997.62 ms, 99th percentile=1.728 ms
``` …
=> libobs: Add profiler section for send_packet

libobs/obs-scene.c
Fixes #3166.
We can't request graphics lock after full_lock(scene) as the lock order has been defined in render thread.
Here, I think it is unnecessary to invoke obs_enter_graphics() because new sceneitem has not been inserted, and it will be accessed only in current thread.
Make sure gs lock should be requested before full_lock(scene) as logic in video render thread.
Steps as 3166
=> libobs: Fix a deadlock caused by obs_enter_graphics

UI/CMakeLists.txt, UI/frontend-plugins/decklink-output-ui/CMakeLists.txt, UI/frontend-plugins/frontend-tools/CMakeLists.txt, libobs/graphics/graphics.c, libobs/obs-hotkey-name-map.c, plugins/obs-outputs/flv-mux.c, plugins/obs-outputs/ftl-stream.c, plugins/obs-outputs/obs-outputs.c, plugins/obs-outputs/rtmp-stream.c, plugins/obs-outputs/rtmp-windows.c
Windows headers are giving numerous compile-time errors when trying to do a manual build using Visual Studio targeting ARM64. Most of them are symbol redefinition caused by rouge Windows headers.
Notable clashes are `timeval`, `connect()` (`winsock.h`), `near`, `far` (`minwindef.h`), `min()` (against `std::min()`) and `max()` (against `std::max()`).
Windows headers are legit messes due to its legacy. You think you included `Windows.h`, actually it is MUCH more than that. 
`WIN32_LEAN_AND_MEAN` is designed to speed up build when computers are not as powerful as today by tell the headers do their own job and don't invite others into compilation. Now it has a new job, that is to stop others messing around with symbol table. 
There's more. `winsock.h` and `WinSock2.h` are never meant to be …
=> Resolve potential symbol clash on MSVC

libobs/util/sse-intrin.h
Restrict the use of `emmintrin.h` to Intel MSVC platforms only.
`emmintrin.h` will cause havoc on non-Intel MSVC platforms. 
I tried to rebuild it and it was successful.
=> libobs: Restrict emmintrin.h to x86(_64) MSVC platform

deps/media-playback/media-playback/media.c
If there is a PTS discontinuity in the playback stream that causes the PTS to
reset, it is likely that new audio frames will come in while there are still
video frames waiting to be dequeued. This will cause the audio frames to be
played while the video frames wait for the PTS to get back up to where they
were before the discontinuity.
This change checks to see if the PTS is more than `MAX_TS_VAR` higher than the `next_pts_ns` and if it is, just assumes that it is time to render it.
Fixes #4887
The issue is that [`deps/media-playback/media-playback/media.c`](https://github.com/obsproject/obs-studio/blob/master/deps/media-playback/media-playback/media.c) does not understand PTS discontinuities.
In the calculation of the next PTS that should be handled, it assumes that the audio and video …
=> deps/media-playback: Handle discontinuities to fix video stalls

UI/win-update/updater/CMakeLists.txt, libobs/CMakeLists.txt, libobs/util/platform-windows.c, plugins/win-capture/CMakeLists.txt, plugins/win-capture/graphics-hook/CMakeLists.txt, plugins/win-capture/window-helpers.c
Only need psapi.lib for XP/Vista, which we aren't compiling for anymore.
Get rid of PSAPI_VERSION macro fragility.
Debugger inspection for GetProcessMemoryInfo and GetProcessImageFileNameW.
=> Remove dependency on psapi.lib

libobs/obs-scene.c
Prevents scene items from being created from removed sources.
There are some cases where an item may attempt to be created for a removed (but not destroyed) source.
Previously, items created from removed sources would lead to the item itself being saved, but the underlying source not being saved. While this does not break OBS immediately, it means that the source along with all associated items will disappear on OBS reload.
This prevents the item from being created in the first place, reducing the chances of user work being lost.
1. Create an input in OBS
2. Using a plugin, fetch the input
3. Increment the reference for the input
4. Call `obs_source_remove()` on the input
5. Attempt to add the input as a scene item to a scene in the UI
6. The scene item will not appear and a warning will …
=> libobs: Block sceneitem creation if item source is removed

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Removes unused `OBSBasic::RemoveSelectedSceneItem` slot.
Appears to be a remnant left by the undo/redo system changes, not used at all by any parts of the UI. This slot does not have undo/redo system functionality, so it is not useful in its current form.
Built fine on Ubuntu 20.04
=> UI: Remove unused RemoveSelectedSceneItem slot

UI/window-basic-properties.cpp
Use the correct source when setting the current scene during undo callback execution.
Bugs are bad. It was doing this:
- Create an input (source)
- Click OK on the properties dialog
- Press CTRL + Z
=> UI: Fix used source for SetCurrentScene during undo

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss
Reorder styling on Dark so that checked buttons can still get hover styling. Also adds a distinct background color for disabled buttons. Fixes the text being the same color as the button when disabled.
Before
After
Before
After
Before
After
Before
After
Before
After
These changes are all general improvements to the themes but they're mainly targeted at elements and states that are more prevalent now with the YouTube integration.
Checked both themes
=> UI: Theme fixes for Dark and Acri

libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs/util/windows/ComPtr.hpp
Use DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT to determine if the swap chain is full, and skip Present if it is to avoid stalling the graphics thread.
This is the flip model swap chain version of #2259, which for OBS will only apply to Windows 11.
Don't want to stall the graphics thread.
Debugger inspection of diffs on Windows 11, Windows 10, and with modifications to test waitable object on Windows 10.
=> Incorporate DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT

libobs-d3d11/d3d11-subsystem.cpp
It's about the CPU being ahead of the GPU, not flip queue being full.
EDIT: Also fixed variable typo.
Don't want to mislead people.
It's a comment. I compiled it.
EDIT: Debugger inspection for variable typo fix.
=> libobs-d3d11: Fix present skip comment

UI/forms/OBSBasicSettings.ui, UI/window-basic-main.cpp
Sets the minimum reconnect delay to 1 second and migrate existing configs with 0 seconds.
Fixes OBS breaking when using a 0 second reconnect delay due to various components not expecting zero values. Example user issue: https://obsproject.com/forum/threads/cant-reconnect-after-internet-going-down-then-coming-back-online.148269/
Ran OBS, ensured UI capped the value and configs with 0 seconds were migrated.
=> UI: Force minimum reconnect delay of 1 second

.github/workflows/main.yml
Upload build artifacts so a double zip isn't created.
Left a do-nothing 7z command behind to mask the error code from robocopy, which reports 1 for success, confusing GitHub Actions.
Double zip is annoying for downloader.
ZIP files downloaded with the proper names, archive contents were as expected, extracted OBS ran fine for both 32-bit and 64-bit.
N/A?
=> CI: Fix double zip by uploading build folders

plugins/linux-capture/pipewire.c
Retrieve the session handle for the PipeWire screencast without performing strict type checks.
g_variant_lookup() obligatorily receives the type of the variant to lookup. This function is used when retrieving the session handle from the portal's response, and the variant type passed is "s" (a string).
However, xdg-desktop-portal had a bug: the documentation explicitly mentions that the session handle is an object path (of variant type "o"), but it passed a string (of variant type "s"). This mismatch [was fixed](https://github.com/flatpak/xdg-desktop-portal/pull/609) in the xdg-desktop-portal release 1.10, but that broke the PipeWire capture code, which was passing specifically the "s" value to the variant lookup.
Fix this by not checking the variant type at all. Object paths ("o") are …
=> linux-capture: Lookup session handle without typechecks

plugins/win-dshow/win-dshow.cpp
win-dshow: Buffering should be disabled for Elgato Facecam in "Auto-detect" mode to prevent latency changes over time
When "Buffering" is set to "Auto-detect" it was always enabled for all Elgato devices. I added "Facecam" as an exception to that rule.
We found that buffering causes latency changes over time for Facecam in OBS and audio from other devices does not stay in sync with the webcam video.
Tested with Elgato Facecam on Windows 10.
=> win-dshow: Don't buffer Elgato Facecam by default

libobs-opengl/gl-wayland-egl.c, plugins/linux-capture/pipewire.c
Check if the required EGL extensions to import DMA-BUFs are available before importing buffers.
The two required extensions are EGL_EXT_image_dma_buf_import and
EGL_EXT_image_dma_buf_import_modifiers.
We need those extensions to be present  to import DMA-BUFs.
*  EGL_EXT_image_dma_buf_import: This extension is required to import
DMA-BUFs with the modifier-less path. It is limited to buffers with 3
planes. [1]
* EGL_EXT_image_dma_buf_import_modifiers: This extension is required to
import DMA-BUFs with an explicit modifier. It raises the limit of buffer
planes to 4, which is the maximum planecount for DMA-BUFs. [2]
[1] https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_image_dma_buf_import.txt
[2] https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_image_dma_buf_import_modif …
=> libobs-opengl: Load required EGL extensions

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp
Fix the service check for services where its name in the UI does not match its Auth::Def service string.
In Restream's case, the service name in the UI and rtmp-services is "Restream.io" while the service name in its Auth::Def is "Restream".  This mismatch causes the `service_check` bool to be false, whereas the previous condition (`!!main->auth && service.find(main->auth->service()) != std::string::npos`) would have evaluated to true.
This was broken in commit e6f1daab8c64aa4cd57c7615647ad80362d72d72.
Fixes #5290.
We want service integrations to work.
Compiled and tested on Windows 10.  Connected to accounts for Twitch, YouTube, and Restream and checked against the STR in #5290.
=> UI: Prevent Restream OAuth disconnection

libobs/util/util_uint64.h
Use intrinsics to perform 128-bit math directly.
Noticed the function was doing extra math that x86-64 processors can handle without shenanigans.
Disassembly inspection in RelWithDebInfo. New instruction sequence is trivial (mul, div).
=> libobs: Simplify util_mul_div64 for x64 on Windows

UI/window-basic-auto-config.cpp
Removes thread from auto configuration code that was accessing UI objects and causing crashing. Given we immediately start and wait on the thread, it seemed largely pointless anyway.
Fixes illegal Qt behavior that caused a crash. Fixes https://github.com/obsproject/obs-studio/issues/5364.
Ran OBS, auto config loaded when it crashed before.
=> UI: Remove thread from YouTube auto config

CMakeLists.txt, libobs/graphics/effect-parser.c, libobs/graphics/effect-parser.h, libobs/graphics/shader-parser.c, libobs/obs-output.c, libobs/util/array-serializer.c, libobs/util/darray.h
This PR adds a test of argument types for darray macros. If type mismatch is found, an error or an warning will be raised. The test is enabled in the flow `CI Multiplatform Build` / `Linux/Ubuntu 64-bit`.
This test was requested by R1CH. https://discord.com/channels/348973006581923840/374636084883095554/867388478194581545
Some mismatches are found such as #5009, #5016. We want to avoid similar mistakes.
Some implementations are falsely detected by the test, type casts are added.
These commits are checked on my local machine (Fedora 34).
| commit | message | result |
|---|---|---|
| d6c77964 | libobs: Fix stack buffer overflow in build_current_order_info | Error | 
| 7b4ae861 | libobs: Fix da_push_back taking a wrong type of item | Error |
| 04b0d632 | UI: Fix da_push_back taking a wrong …
=> Test darray type during CI

UI/window-basic-settings-stream.cpp
One line was erroneously moved outside of an `else` when the YouTube integration was merged in e6f1daab8c64aa4cd57c7615647ad80362d72d72.
Users complained, I listened with an open ear.
Confirmed that box is no longer getting unchecked when opening settings.
=> UI: Fix Twitch bandwidth test checkbox

libobs/data/default.effect, libobs/data/default_rect.effect
Technique is no longer referenced, and doesn't seem useful.
Don't want people to use this technique.
OBS still load default and default_rect effects without errors.
=> libobs: Remove DrawSrgbDecompressPremultiplied

UI/forms/OBSBasicSettings.ui
This commit fixes a tab stop order for `Draw safe areas` in the settings dialog. The tabstop definition was missing on the commit afd58a78e.
The tab stop order was incorrect.
Tested on Fedora 34. Hit Tab key several times and checked the order is correct in the `General` tab.
=> UI: Fix tab stop order for Draw safe areas

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
This adds RIST to the list of protocols supported by the obs ffmpeg_mpegts_muxer.
RIST is container and codec agnostic. But this implementation relies on ffmpeg avformat integration and uses mpeg-ts container.
Obs-studio supports srt & ftl among the new protocols.
Rist is gaining traction. It relies on rtp frames rather than udt.
But it's quite similar to srt in terms of capabilities : 
- ARQ (Automatic Repeat reQuests, or packet resend if there's packet loss),
- low latency,
- FEC correction,
- bonding.   
The advanced profile (in development) will have dynamic bitrate capability.
According to rist users/devs, a rist stream can be recovered with up to 50% packet loss
against 10% with srt. (I haven't checked the claim.)
It's standards based and there's an open source implementation …
=> obs-ffmpeg-mux: Add support for rist protocol

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
This PR updates the CamSoda servers in the rtmp-services plugin list  to match the ones that we currently are using.
We changed changed the dns names of our ingest points and while the old  still work for the foreseeable future we  would like to have the new ones in OBS.
=> rtmp-services: update CamSoda domains

plugins/linux-v4l2/CMakeLists.txt, plugins/linux-v4l2/v4l2-helpers.h, plugins/linux-v4l2/v4l2-input.c, plugins/linux-v4l2/v4l2-mjpeg.c, plugins/linux-v4l2/v4l2-mjpeg.h
Added support for format "MJPG" to capture from the linux-v4l2 plugin.
Added code to use avcodec to unpack jpegs from the camera.
I would like to run 1920x1080@30 from my Logitech C290.
I've selected "Moition-JPEG" from the "Video Format" drop down
I've selected "1920x1080" from the "Resoution" drop down
I've selected "30.00" from the4 "Frame Rate" drop down
This produces log output like this:
```
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 1920x1080
info: v4l2-input: Pixelformat: GPJM
info: v4l2-input: Linesize: 0 Bytes
info: v4l2-input: Framerate: 30.00 fps
```
And a smooth FullHD output
=> linux-v4l2: Support for Motion-JPEG codec

.github/workflows/flatpak.yml, CI/flatpak/com.obsproject.Studio.json
Pass Twitch, Restream, and YouTube client ids and hashes to the Flatpak build, and enable services integration.
The flatpak-builder tool now supports passing secrets options to the build system. These options are not printed during the build, nor added to the resolved manifest after build, so they don't leak env vars from CI.
Pass the various services hashes and clientids to the build system using the new "secret-opts" key.
Related: https://github.com/flathub/com.obsproject.Studio/issues/139
- Let this CI workflow run on a commit of the master branch
- Download the Flatpak artifact and observe that services are enabled
=> Integrate services on Flatpak builds

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Removes the `bool OBSBasic::StreamingActive() const` since `bool OBSBasic::StreamingActive()` exists further down (exactly the same code), along with `RecordingActive` etc.
No need for it to exist twice.
macOS 12.0.1
Still compiles and runs
=> UI: Remove duplicated StreamingActive() function

UI/window-basic-main.cpp, UI/window-basic-main.hpp
The system tray assumed all outputs are inactive when it's initiated,
however outputs can be active if started via command line options. This
caused the wrong (only) text to be set if the output was in fact active.
Fixes #5484
macOS 12.0.1, compiled and run
When using launch parameters, the system try will now show the correct texts for "Start/Stop Streaming/Recording/Replay Buffer/Virtual Camera" and also have the active icon (with the little dot).
=> UI: Set correct text in system tray on startup

UI/window-basic-main.cpp, UI/window-basic-settings.cpp, UI/window-youtube-actions.hpp, UI/youtube-api-wrappers.cpp, libobs/obs-audio-controls.c, plugins/obs-ffmpeg/obs-ffmpeg-av1.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Found warnings when compiling OBS.
Warnings are annoying.
Compiled to see if warnings went away.
=> UI, libobs, obs-plugins: Fix compiler warnings

libobs/audio-monitoring/pulse/pulseaudio-output.c
Previously we would wait for pulse to attempt to read from the monitor
source and obs buffered at least 5ms of audio data before we tried to
fill the buffer. In some cases this resulted in consistently triggering
underruns in pulse.
Instead we try to fill the buffer immediately as obs outputs audio data
and while the pa buffer is not full. We also stop trying to grow the
buffer to prevent underruns after we reach 1s of latency.
Attempting to fix #3525
Adding a media source with an mp3 gave consistent underrun's with the old code. After these changes there are no more under runs reported from the pulse log or obs.
=> pulse: fill audio monitor buffer more aggressively

UI/context-bar-controls.cpp, UI/context-bar-controls.hpp
Adds undo/redo for when users change the text of a text source in the context bar.
Makes use of the `repeatable` undo/redo function (I really love that function!); making
sure that there aren't 10 new entries in the undo stack after typing 10 letters.
(Delay needed to create a new action should be three seconds according to `ae5ac8fa8`)
This doesn't have undo/redo as of right now, but it should.
macOS 12.0.1, compiled and run
Undo and redo correctly get added. If multiple letters are typed/removed, those changes will get undone/redone all at once unless a lot of time has passed between typing those letters.
=> UI: Add undo/redo for context bar text changes

UI/window-basic-main.cpp
When undoing a scene removal, `obs_source_load` would get called on all sources, not just those had to get recreated since they no longer existed.
If I understand [the docs](https://obsproject.com/docs/reference-sources.html?highlight=.load#c.obs_source_info.load), that method should only be called when a source has been freshly created, and not at any random point in its lifetime (which it would be for existing sources. This could be potentially dangerous for source types other than `scene` as well if they didn't "expect" the call). This change makes only the sources get `.load`ed that were recreated.
In case I misunderstood the docs in that regard and the call to `.load` was intentional for all sources, this PR would be the wrong solution. In that case, `.load` for scenes would need to …
=> UI: Don't load existing sources for scene removal undo

docs/sphinx/reference-core.rst, libobs/obs.c, libobs/obs.h
Adds a function that gets a transition by its name. Like `obs_get_source_by_name`, but for transitions.
`obs_get_source_by_name` has the limitation that it doesn't get private sources.
This new method makes obsproject/obs-browser#312 much cleaner.
Tested with obsproject/obs-browser#312.
If a transition exists, it will get returned, otherwise it will return null (like `obs_get_source_by_name`).
=> libobs: Add obs_get_transition_by_name

plugins/rtmp-services/data/services.json
Add [Autistici.org](https://live.autistici.org) to rtmp services list.
Autistici/Inventati is a no-profit association from Italy which provides various services. Starting in 2020, it is running a free streaming service at https://live.autistici.org.
Adding Autistici.org to the list of rtmp services was [suggested by one user](https://ideas.obsproject.com/posts/1497/add-autistici-live-preset-in-streaming-services-list), as per OBS policy we are now submitting the request first-hand. 
Local Build
=> rtmp-services: Add Autistici.org

UI/window-basic-filters.cpp
Adds an undo/redo action when you click "Defaults" in the filters properties window.
The callback (or whatever you'd call that) `filter_change` was moved into a function so that it could be called from outside without code being duplicated for no reason (this is the majority of the lines added/removed).
Pressing "Defaults" on the filter properties would previously not create an undo action, resulting in bad UX and unpredictable behaviour when you first changed a filter, then pressed "Defaults" and did an undo.
macOS 12.0 beta 6, compiled and run
Pressing "Defaults" will add an `Undo Filter Changes on 'FILTER_NAME'` undo action.
Undo/Redo for normal changes to filters still works as before.
=> UI: Add undo/redo for resetting filters properties

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add PhoneLiveStreaming to rtmp services list.
Allows live streaming to toll-free telephone systems using OBS Studio.
Local build
Thank you for your help @derrod with the link to a correct example.
=> rtmp-services: add PhoneLivestreaming

plugins/obs-transitions/transition-stinger.c
Fix showing the first part of the stinger again at the end of the transition
sometimes a stinger transition flashes the first frames at the end of the track matte stinger transition
On windows 64bit by breaking the process during the track matte stinger transition
=> obs-transitions: Fix stinger transition looping

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-source-select.cpp, UI/window-basic-source-select.hpp
Fixes #3632
Applies transformations correctly to copy/pasted sources when copy and pasting multiple. 
Previous behavior was unintuitive and not how users would expect copy + paste to function.
Verified functionality running on Windows 10 with latest code from master + this commit
Also verified undo/redo still function as expected
- Bug fix (non-breaking change which fixes an issue)  
=> UI: Apply transforms/crops correctly to sources on paste

plugins/obs-qsv11/QSV_Encoder.cpp, plugins/obs-qsv11/obs-qsv11.c
This commit removes the old checking of Intel discrete device IDs and sets the default to integrated when Intel discrete and integrated graphics (i+I) are co-existing on the platform. 
As Intel continues to add discrete graphics cards, maintaining a long list of discrete device IDs to check against isn't wise. When i+I platforms are detected, default to integrated graphics. 
Tested with the following scenarios:
- i+I: RKL+DG2, TGL+DG2, ADL+DG2
- DG2 only: TGL
- Monitor connected to iGPU in i+I cases and user selection of OBS on iGPU/dGPU (Low Power/High Performance Graphics Settings)
- Monitor connected to dGPU in i+I cases and user selection of OBS on iGPU/dGPU (Low Power/High Performance Graphics Settings)
- DG2 A0 128 EU, DG2 A0 512 EU and DG2 B0 512 EU cards
Tweak (non-breaking change …
=> obs-qsv11: Remove Intel discrete device ID checking

UI/CMakeLists.txt
Move the python linkage after the obs target is defined so that we can
also add linker flags to preserve the unused python linkage. This is
required before GCC 11.
Pat suggested `target_link_options` but this is only available on cmake 3.13 which is not available in ubuntu 18.04 so I switched it to the deprecated LINKER_FLAGS property.  I left this in a comment in case.
Previous fix would not work on our PPAs.
Tested on ubuntu 18/20 and this works there as well now.
=> UI: Update python linkage for older compilers

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, docs/sphinx/reference-frontend-api.rst
Returns the current path of the record output.
obs-websocket currently reimplements the `GetCurrentOutputPath()` function. To avoid future breakages (we have already had to update our side once), this allows us to fetch it directly from OBS.
Same tests as #4525 
=> UI: Add obs_frontend_get_current_record_output_path()

UI/obs-frontend-api/obs-frontend-api.h, UI/window-basic-main.cpp, docs/sphinx/reference-frontend-api.rst
For example: this event is for when scripts need to know when
OBS is exiting. Currently scripts are destroyed before the current
exit event.
Since https://github.com/obsproject/obs-studio/commit/228ca556611e77d9be6926dbdad59acf37321813, scripts don't know when OBS is exiting.
Tested with a script.
=> obs-frontend-api: Add scripting shutdown event

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-d3d11/d3d11-texture2d.cpp, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h
Adds support for using shared textures that were made with the
D3D11_RESOURCE_MISC_SHARED_NTHANDLE flag.
This increases the minimum required Windows version to Windows 8 or the
Platform Update for Windows 7. As official support is only for Win 8+
this does not change official support.
The new shared texture method required by our CEF branch uses shared textures made with the D3D11_RESOURCE_MISC_SHARED_NTHANDLE and D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX flags, so we need support for NT Handles.
This has been tested against an implementation of the new shared texture method used in our CEF branch.
=> libobs/graphics: Add support for NT Handle shared textures

UI/source-tree.cpp, UI/window-basic-main.cpp, UI/window-basic-source-select.cpp
- Makes the UI react properly to the `source_remove` signal and only when relevant
- Removes calls to `RefreshSources()` that are no longer necessary with this PR
Calling `obs_source_remove()` on an input from obs-websocket was not updating the UI if there was a scene item of the input in the current scene. This is because the source tree was not being refreshed, leaving one last reference to the source.
- Tested removing inputs via unreleased `RemoveScene` request in obs-websocket: Works great
- Tested all functions where `RefreshSources()` was removed by the second commit: Works exactly as before, with `RefreshSources()` still being called when necessary.
=> UI: React to `source_remove` correctly and update UI accordingly

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, UI/window-basic-adv-audio.cpp, UI/window-basic-main-profiles.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, docs/sphinx/reference-core.rst, libobs/CMakeLists.txt, libobs/audio-monitoring/null/null-audio-monitoring.c, libobs/audio-monitoring/osx/coreaudio-monitoring-supported.c, libobs/audio-monitoring/pulse/pulseaudio-monitoring-supported.c, libobs/audio-monitoring/win32/wasapi-monitoring-supported.c, libobs/obs-source.c, libobs/obs.c, libobs/obs.h
- Adds `obs_audio_monitoring_supported()`
- Adds `audio_monitoring` source signal for monitoring type changes
- Updates the Advanced Audio Properties dialog when an input's audio monitoring type changes
We allow users to change the monitoring type through obs-websocket, and it wasn't updating the UI when someone would perform a request. I also hate incomplete functionality.
OS: Ubuntu 20.04
Build: Latest git commit as of posting
- `obs_audio_monitoring_supported()` related changes were only tested on Ubuntu, but *should* work the same on all platforms.
- `audio_monitoring` signal was tested via obs-websocket
- Advanced Audio Properties update when `SetInputAudioMonitorType` obs-websocket request is performed
- New feature (non-breaking …
=> libobs/UI: Signal when monitoring type is changed and update UI accordingly

plugins/text-freetype2/text-freetype2.c, plugins/text-freetype2/text-freetype2.h
This moves the default settings to the `.get_defaults` callback so that our request does not return an empty object.
obs-websocket's `GetInputDefaultSettings` request uses obs_get_source_defaults() in order to fetch a source id's default settings. Currently, calling the request returns an empty object for `text_ft2_source_v2`, since the default settings are configured inside of `.create` and not `.get_defaults`
Ubuntu 20.04: Tested existing ft2 sources and creating new sources. Functionality unchanged.
=> text-freetype2: Move default settings to .get_defaults

plugins/win-capture/inject-helper/inject-helper.c
Potential definition clash with c99defs.h. Not needed anyway.
Seeing warning in a branch where the symbols clash.
Verified injection still works for game capture.
=> inject-helper: Remove UNUSED_PARAMETER macro

UI/qt-display.cpp
Deletes the underlying `obs_display_t` object when the window draw surface is destroyed (X11 and Wayland), preventing OBS from attempting to switch to invalid GLX context on draw.
Closes #4185
Currently: This issue is mainly caused by the behavior of Qt's `DeleteLater`. When a window using OBSQTDisplay is closed, there is an indeterminate delay until the Qt object for it is deleted, allowing for a race.
With this: The `OBSQTDisplay` object is deleted before the draw surface is, preventing the race condition. No longer reports *any* X errors, let alone crashes.
This issue can be most easily reproduced by doing:
- Open OBS
- Open the filters dialog of a playing source
- Close the dialog via the x in the top right corner (Not the `Close` button)
Expect X errors to be logged, and if lucky …
=> UI: Fix crash on *nix caused by OBSQTDisplay destruction after draw surface invalidation

deps/ipc-util/ipc-util/pipe-windows.c, deps/ipc-util/ipc-util/pipe-windows.h
There is an expectation that ready_event will signal/wake 1:1, so the
stray teardown signal may get lost. Add new stop_event for safety.
OBS hang is bad.
This may not be common in practice because I can only repro the hang by altering timing using a debugger. Still better to be safe.
Manipulated timing to repro hang, and hang no longer occurs with new setup.
=> ipc-util: Fix potential ready_event hang

libobs-d3d11/d3d11-texture2d.cpp
Cubemaps weren't even working properly before this. The gs_texture_2d::data vector did not take cubemaps into account. This code fixes that issue. -Jim
Would be nice to have cubemaps working I suppose. -Jim
Tested by Jim -Jim
=> libobs: Fix gs_texture_2d::BackupTexture with GS_TEXTURE_CUBE

UI/window-basic-settings.cpp
This removes our own code for gcd, as it is already built into cpp.
Code cleanup.
Open settings to see if the aspect ratio still worked.
=> UI: Use std::gcd for aspect ratio

UI/window-basic-main.cpp, docs/sphinx/reference-scenes.rst, libobs/obs-scene.c, libobs/obs.h
This PR consists of three commits, hopefully fixing all undo shenanigans when deleting sources:
Commit 1 makes scenes listen to the removed signal of their source. When that signal is called, all
other scenes will check if they have removed sources, thus removing nested instances of the
scene that got deleted. This makes them release their references to that scene, letting it get destroyed
properly.
Previously, scenes would check for removed sources when they were rendered (and still do, that doesn't
change). However, this would mean that they had to be selected once in the scene list or get rendered 
otherwise to release their references. Without undo/redo, this wasn't a big problem (it only showed in
for example the name of the source still being in use), however undo/redo expects to …
=> UI,libobs: Fix delete scene undo problems

UI/context-bar-controls.cpp
Fixes a crash that occurred since `main->GetCurrentSceneSource()` returns null during shutdown and the OBSSource wasn't null-checked.
Crash = Bad
macOS 12.0.1, compiled and run
The crash, which occurred when having a text source selected while shutting down, doesn't occur anymore.
=> UI: Fix context bar shutdown crash

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, docs/sphinx/reference-sources.rst, libobs/obs-source.c
In the advanced audio properties, the balance slider does not update after undo/redo actions. To fix this bug, I adding a source_signal and a value change listener for the audio balance widget. 
Fixes #4763 
Testing environment (Arch Linux, i3 Desktop)
Test steps:
1) Open advanced audio properties
2) Move balance slider
3) Undo/redo the action
=> UI: Fix bug with audio balance slider not updating

libobs/obs-source.c
This PR fixes an issue where old frames, potentially hours old, can be redisplayed for a short period of time when an inactive async source begins outputting video again. The two sources that are known to have this bug are the ffmpeg source and VLC source.
When sources output NULL frames, it is generally used to disable the source and prevent the last frame from being left on screen. However, when the source begins outputting video again, the last frame is still in the async cache.
Depending on the stability of the source's frame output, this still frame can end up being shown for 5+ output frames.
By freeing the async cache when a NULL frame is submitted, we avoid the issue of old frames being re-displayed.
OS: Ubuntu 20.04
This was especially apparent in a custom source I was …
=> libobs: Free async cache when sources output NULL frames

plugins/linux-capture/pipewire-capture.c, plugins/linux-capture/pipewire.c, plugins/linux-capture/pipewire.h, plugins/linux-capture/portal.c, plugins/linux-capture/portal.h
Implement restoring screencast sessions using portals. Do so by storing the restore token received by the portal in the source data, and using it next time the source is loaded. This feature is only available in the v4 version of the ScreenCast portal [1] - if an older version is running in the host system, the current behavior is preserved.
Currently OBS Studio has to recreate screencast sessions from scratch each time a PipeWire source is loaded. This can be annoying,
Use the new screencast restore options provided by xdg-desktop-portal to restore previous sessions.
- Have xdg-desktop-portal and xdg-desktop-portal-gnome  installed from the master/main branches [2]
- Run this branch of OBS Studio on Wayland, or X11 with `OBS_USE_EGL=1`
- Add a PipeWire source, and select a window or a …
=> Screencast session restore for Wayland / PipeWire

.github/workflows/clang-format.yml, .github/workflows/qt-xml.yml
Give XML and clang-format validator more descriptive job names.
When setting up restrictions for PR merges to require checks to have passed GitHub only allows to specify individual jobs rather than an entire check suite. The clang-format and Qt XML actions previously had identical generic job names which breaks that specific UI.
Made sure jobs still run
=> CI: Update XML/clang-format validation job names

UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This change removes the minimum total size from the context bar, instead
removing certain elements when the size is too small. This means that
users will still be able to make OBS smaller in width while keeping the
context bar enabled.
First, the properties, filter and interact buttons will get reduced to
just the symbols, if it gets even smaller the source specific menus are
hidden.
This is how it looks:
https://user-images.githubusercontent.com/59806498/137125517-df9f4abc-b267-49ae-bea4-33ab8b782d7b.mp4
This is a draft for two (three/four) reasons:
- ~~It doesn't yet refresh when docks are popped out.~~
- The first threshold (740) is the current minimum size of the toolbar. However, the second threshold (600) was chosen arbitrarily. I'm not a UX expert, feedback or suggestions on that …
=> UI: Minimize context bar when too small

UI/remote-text.cpp
Rather than returning an empty error alongside a `false` success response, this populates the error field with the string version of the cURL error.
**Before:**
> ```
> 19:41:22.314: AutoUpdateThread::run: Failed to fetch manifest file: 
> 16:02:22.238: TwitchAuth::GetChannelInfo: Failed to get text from remote: 
> ```
**After:**
> ```
> 19:41:22.314: AutoUpdateThread::run: Failed to fetch manifest file: Couldn't connect to server
> 16:27:57.040: TwitchAuth::GetChannelInfo: Failed to get text from remote: Couldn't connect to server
> ```
Empty errors tell the user or support volunteer nothing about what went wrong. Providing at least the cURL error provides some context.
Enable Twitch integration and restart OBS. Sometimes, an error dialog with zero error information appears. (In this …
=> UI: Expose cURL error if Remote Text error text is empty

.gitattributes, .github/workflows/crowdin-sync-download.yml, .github/workflows/crowdin-sync-upload.yml
This adds 2 GitHub Actions that streamline the synchronization and localization process between this repository and the Crowdin project.
Features of the 'Download Action':
- Updates all translations in the main repository and all 3 submodules that include translateable content (obs-browser, obs-vst & enc-amf).
- Updates the `AUTHORS` file with both Git contributors and translators.
- Updates the translations of the `UI/xdg-data/com.obsproject.Studio.desktop`.
- Updates the `UI/data/locale.ini`: New languages need 60% to be added, languages with less than 30% will be removed.
Note: The GitHub Action only pushes submodule changes to the main repository if it is even with the main repository to prevent other commits from being implemented without knowing. The translation updates would still …
=> CI: Crowdin Synchronization

CI/flatpak/com.obsproject.Studio.json
Basically, synchronize this Flatpak manifest with what's in Flathub. This includes a couple of dependency updates, and extension points.
We've been using a simplified version of the Flatpak manifest because it's main purpose was CI support. Now that this manifest is what will be used to publish Flathub updates, we need to bring in all the features it had.
- Download the Flatpak generated from the CI
- Open the bundle with an app store (e.g. GNOME Software, or KDE's Discover)
- Observe that plugins are listed there
=> Unassorted Flatpak updates and extensions

UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Add the "hi-dpi icon" and "modern toolkit" kudos to the AppData file, and let app centers tell the world how awesome OBS Studio is :slightly_smiling_face: 
Kudos are read by app centers such as GNOME Software and Discover to calculate the "awesomeness" level of the application. OBS Studio qualifies for two of these kudos: the "hi-dpi icon" kudo, since we have 128x128 and bigger icons; and the "modern toolkit" icon, since we use Qt5.
- Build this branch, and observe that app centers add these kudos to OBS Studio
=> Add kudos to AppData file

UI/importers/sl.cpp
Enables the FindFiles function for the Streamlabs importer on macOS, which previously was
windows-only.
This is not needed for OBS Classic or XSplit, since neither exist(ed) on Mac.
`Search known locations for scene collections when importing` would do nothing on macOS (so this is something in between a tweak and a bug fix).
Installed Streamlabs (a big pain, no idea why they would make the process so damn annoying) and created a collection.
It shows up in the importer window and is correctly identified as Streamlabs.
=> UI/importers: Automatically detect SL Collections on macOS

UI/auth-restream.cpp, UI/auth-twitch.cpp, UI/auth-youtube.cpp, UI/window-extra-browsers.cpp
The `create_widget()` function supports QWidget as the first parameter, this makes use of that.
This provides browser docks with the ability to receive additional information from their parent QWidget. For example, acquiring the title of the dock using `widget->parentWidget()->windowTitle()`, or in future being able to get/set information about a dock via the context menu.
Tested in both Custom Browser Docks and the Twitch Chat dock using BTTV "Font size"
=> UI: Pass parent QWidget to Browser Docks

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-extra-browsers.cpp, UI/window-extra-browsers.hpp
Adds a persistent `uuid` property to Custom Browser Docks in the Docks menu and internally. This allows for the ability to uniquely identify custom browser docks.
This UUID is accessible from the `global.ini` configuration, the dock widget itself, and the menu item representing the dock.
```ini
[BasicWindow]
ExtraBrowserDocks=[{"title": "Google", "url": "https://google.com", "uuid": "f081624cc81f49b0848470e8d16d8e46"}]
```
There are certain future enhancements that would be entirely impossible without a way to uniquely identify docks.
* Create a custom browser dock (or already have one configured)
* Close OBS
* Check `global.ini`
=> UI: Generate unique identifiers for Custom Browser Docks

UI/window-basic-main-transitions.cpp, plugins/obs-filters/noise-suppress-filter.c, plugins/text-freetype2/text-freetype2.c
Fixes some unused parameter warnings.
XCode (`Apple clang version 13.0.0 (clang-1300.0.29.3)`) yelled at me.
macOS 12.0.1, still compiles and warnings are gone.
Also still compiles on Windows and Linux CI.
=> Fix some unused parameter warnings

.github/workflows/flatpak.yml
Don't publish beta releases to Flathub stable.
Beta releases are being considered, in which case the tag name will contain '-beta' instead of '-rc'. Adapt the CI workflow to take '-beta' into account too.
Observe that this [fake beta release](https://github.com/GeorgesStavracas/obs-studio/runs/4419285226?check_suite_focus=true) skips the `Publish to Flathub` step.
- Enhancement (non-breaking change which adds functionality)
=> CI: Don't publish betas to Flathub stable

.github/workflows/crowdin-sync-download.yml, .github/workflows/crowdin-sync-upload.yml
This fixes an issue with the Crowdin Sync Upload action when more than 1 commit gets pushed where one of the commits contains an updated language file. By increasing the fetch depth I make sure all pushed commits get covered by the checkout.
This also updates the job names for both actions to clarify what they are in the global scope.
A failing action is bad.
In a fork and a private Crowdin project.
=> CI: Increase Crowdin Sync Checkout Fetch Depth

UI/frontend-plugins/aja-output-ui/CMakeLists.txt, UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp, plugins/aja/main.cpp
When the AJA plugin loads we check if any devices are present, if they are not we tell OBS to not load the AJA plugin.
This should cut down on user confusion and reduce clutter.
Ran locally with no devices and the plugin doesn't load.
=> aja: Disable plugin if no devices are found

plugins/aja/aja-common.cpp, plugins/aja/aja-output.cpp, plugins/aja/aja-source.cpp
This PR adds the current property value in the Aja output properties if it doesn't exist. This stops the properties callback from calling an infinite number of time and eventually crashing.
AJA output ui would crash
=> aja: Fix crash in output settings when no card present

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add Fantasy.Club to rtmp services list.
Simplify life for streamers using the Fantasy.Club platform
Dev team updates to local services.json instances
=> rtmp-services: Add Fantasy.Club

UI/auth-twitch.cpp, UI/auth-twitch.hpp
Some Twitch dashboard panels now require a UUID, it is not used for
anything but local storage right now, and according to Twitch we can
generate it ourselves (or even use a static string). To be safe we can
just use QUuid to generate a "real" UUID and then store it locally until
the user disconnects the account.
Twitch break, I fix.
Logged into panel on new profile, verified it works and UUID is saved/loaded.
=> UI: Add UUID to Twitch panel URLs

plugins/linux-capture/pipewire-capture.c
If you don't have a xdg-desktop-portal backend then pipewire wont init,
however on exit we unconditionally deinit which can crash in pipewire
which does not handle this gracefully.
Its not the most graceful solution, but I didn't think we should be querying dbus
again just to figure out if pipewire can be safely deinit'ed.
Crashing on exit is bad.
Running obs in a wayland session without a portal backend crashes on exit, with this it doesnt.
=> pipewire: only deinit if we init'ed

plugins/vlc-video/vlc-video-source.c
Emits `obs_source_media_ended` regardless of whether the playlist is in loop mode. Makes the signal's behavior on-par with `obs_source_media_started`.
An affected use case would be:
A VLC source plays a video stream 24/7. Sometimes the stream playback ends unexpectedly and requires manual intervention.
A script listens for the `obs_source_media_ended` signal and resets the source automatically, allowing continued playback. Currently, this script would not receive the event unless `loop` is disabled.
`obs_source_media_started` is emitted every time an entry in the playlist is played, and so therefore `obs_source_media_ended` should be emitted every time playback of a playlist entry ends.
Currently, the signal is only emitted when the loop setting is disabled, however the parent handler …
=> vlc-video: Emit media ended signal regardless of loop setting

.github/workflows/main.yml, cmake/Modules/FindLibpci.cmake, plugins/obs-ffmpeg/CMakeLists.txt, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
As discussed in the issue, I retrieve the DRI devices from `/dev/dri/by-path/` instead of `/dev/dri/renderDXXX` (e.g. `/dev/dri/by-path/pci-0000:00:02.0-render`). This enable us to use [`lspci`](https://github.com/pciutils/pciutils/) to get the device name as well.
If `/dev/dri/by-path/` does not exist, I fall back to the old implementation
This is the first time contributing here: I am not sure it is correct to add the `-lpci` flag where I did in `CMakeLists.txt`. Additionally I don't work often in C, but I hope this works out as intended since it's a small contribution.
Fixes #2936
I tested it in a clean environment on my desktop with two vaapi devices. It appears to work as intended
specs:
```
OS: Manjaro Linux x86_64 
Kernel: 5.14.7-2-MANJARO 
Resolution: 1920x1080, 1920x1080 
DE: …
```
=> obs-ffmpeg: Set DRI devices and their name persistently

.github/workflows/flatpak.yml
Adapt the Flatpak workflow to also run on `release/**` branches.
We'll soon be moving to branching before releases, which is a case that the current Flatpak worflow did not account for.
I've created a [fake `release/27.999.0` branch in my personal repository](https://github.com/GeorgesStavracas/obs-studio/tree/release/27.999.0), and the Flatpak actions now run there too.
=> CI: Run Flatpak jobs on release branches too

CI/install-dependencies-linux.sh, cmake/Modules/FindXkbcommon.cmake, libobs/CMakeLists.txt, libobs/obs-nix-wayland.c, libobs/obs-nix-x11.c
Users on wayland are displeased that they cannot see their hotkey
bindings. This enables keys reported like X11, and has the infrastructure
in place in case wayland ever decides to allow for capturing input.
Also fix numpad subtract missing on X11.
Users cannot even see or set hotkeys which might be usable while OBS is in focus. Hotkeys now work while OBS is in focus and display properly on the UI.
Tested in kde that keymapping tables work correctly on US layouts and the keys on my keyboard that work in X11 work in Wayland.
More testing on non-US layouts would be appreciated.
=> libobs: Add wayland hotkey infrastructure

UI/window-basic-transform.cpp
Fix a stack overflow caused by using OBSScene in OBSBasicTransform::OBSSceneItemRemoved, which is callback of signal.
OBSSceneItemRemoved is called as this callstack (dead cycle):
I think it is really quite dangerous to use OBSSource/OBSScene/OBSSceneItem in callback of signal, especilly using these variable type to params of invokeMethod.
Because in callback of signal, we can't ensure source's refs. If refs has been -1, that means any thread is being destroying it. 
If we use OBSSource for param, after running function passed to invokeMehtod, refs will be -1 again. Then obs_source_destroy will be called for this deleted object, crash happen!
I have meet this kind of crash many times. Such as https://github.com/obsproject/obs-studio/pull/5605
@jp9000  It's perfect if this can be …
=> UI: Fix a stack overlow caused by using OBSScene

plugins/win-capture/window-capture.c
When HWND is invisible, WGC can't be initialized, which makes wc->previously_failed to be true. 
Then WGC will no longer be reset when window is visible.
make sure WGC should be inited at right moment
steps to reproduce bug:
1. open a window, add window source in OBS based on WGC
2. call ::ShowWindow(SW_HIDE) for window
3. call ::ShowWindow(SW_SHOW)
4. OBS can't capture its view any more
=> win-capture: Fix bug that WGC capture is stopped

deps/media-playback/media-playback/media.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-formats.h, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.h, plugins/obs-ffmpeg/obs-ffmpeg.c, plugins/win-dshow/ffmpeg-decode.c
These commits address various FFmpeg changes, and deprecations.  They also address removals of deprecated code post FFmpeg 4.x.
Details about the changes and why they are needed are in each commit message.  As far as I can tell, these changes are compatible for the entire FFmpeg 4.x series, and _should_ be fine for FFmpeg 3.2+ releases.
Big thanks to @pkviet who helped me with this!
These changes allow us to use FFmpeg 4.4+ up to FFmpeg to FFmpeg/FFmpeg@9d4989f2e17c11d4ee9daa489b6e4f5195d80b99.
On Windows 10 with FFmpeg 4.2.4, FFmpeg 4.4.1, and FFmpeg git (ffmpeg-N-104473-g9d4989f2e1, FFmpeg/FFmpeg@9d4989f2e17c11d4ee9daa489b6e4f5195d80b99), I successfully tested:
* streaming to Twitch with NVENC and x264
* recording to MKV and MP4 with NVENC, x264, and QSV
* Color Source with Color …
=> Fix FFmpeg deprecations up to FFmpeg 4.4 and current FFmpeg git

UI/CMakeLists.txt, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Remove Qt Windows Extra for Qt 6 and later
Qt 6 and later removed platform-specific extra modules from the code base. 
It compiles.
Tested on Windows 10 x64 and 11 ARM64 without crash.
=> Remove Qt Windows Extra for Qt 6 and later

plugins/obs-outputs/rtmp-stream.c
Change the place where _dbr_set_bitrate_ is called in RTMP send_thread, make sure it's done before obs_output_end_data_capture.
_dbr_set_bitrate_ in rtmp-stream.c is called (if triggered) after _obs_output_end_data_capture_ in current logic.
While the _obs_output_end_data_capture_ will start another thread _end_data_capture_thread_ to stop (and may destroy) the video encoder. So it's not thread safe for dbr_set_bitrate to update video encoder, because the encoder may be destroyed at any time during _end_data_capture_thread_ .
Enable dbr
start streaming
limit network to trigger dbr
stop streaming
=> obs-outputs: Reset dbr bitrate before end_data_capture_thread start

UI/window-basic-main-outputs.cpp, UI/window-basic-main-outputs.hpp, UI/window-basic-main.cpp
"Overwrite if file exists" setting not respected for replay buffer
Refer to issue #4227
The reason behind this is there are no file overwritten checkings when saving replay buffer.
Even there is a file name checking when starting replay buffer, the variable is unused actually
> https://github.com/obsproject/obs-studio/blob/2787e63d8ecd0f4578ab47c6ca5cf73c0bce1844/UI/window-basic-main-outputs.cpp#L1946-L1947
1. Open OBS
2. Set local recording and replay buffer filename to something static
3. Save replay buffer multiple times
4. Observe that the file is overwritten
=> UI: Add checks for overwrite setting to replay buffer

UI/forms/OBSBasicFilters.ui, UI/window-basic-filters.cpp, UI/window-basic-filters.hpp
Updates the filters window to use a QSplitter layout for the properties area.
The handle is disabled for audio filter windows. The handle and property area are hidden when there are no filters.
The current filters window has hardcoded size limits on the properties view that requires scrolling for filters with a large number of settings.
This PR removes that arbitrary limit and also lets users resize the area if they still need to.
Tested adding and removing filters on a media source (Async + Effects filters), a text source (Effects filters only), and an audio source (Audio filters only)
Ensured that the resize handle was only available when appropriate. Ensured resizing worked as expected. Ensured properties window is shown/hidden when appropriate.
- New feature (non-breaking change which …
=> UI: Update the filters window to be resizeable

libobs/obs.hpp
Adds the `OBS_AUTORELEASE` #define to obs.hpp.
Since these helpers come from obs-websocket, obs-websocket needs a way to disable its own helpers if OBS is new enough to include them already. We need this in order to fix building for new and older OBS.
Built obs-websocket successfully
=> libobs: Add preprocessor directive for AutoRelease types

plugins/win-dshow/virtualcam.c
Modify Windows virtualcam output to make sure it's thread safe. 
The virtualcam output for Windows is not thread safe.
=> win-virtualcam: Make sure virtualcam output thread safe

libobs/obs-source.c
Holds an active reference to a source during signaling of the `source_remove` signal, to prevent receivers from being given an already-destroyed source.
All receivers of the `source_remove` signal should receive a valid source to operate on.
- Call obs_source_remove(source)
- Receiver 1 gets signal, calls `obs_source_release(source)`
- Receiver 2 gets signal, calls `obs_source_release(source)`, refs == -1, source destroyed
- Receiver 3 gets signal, source already destroyed, is forced to ignore signal due to invalid source
This is a theoretical situation which is currently possible in obs-websocket. While I can believe I've seen crashes related to this, I cannot prove it.
=> libobs: Hold source ref during `source_remove` signal

plugins/mac-capture/mac-display-capture.m, plugins/mac-capture/mac-window-capture.m, plugins/mac-capture/window-utils.h, plugins/mac-capture/window-utils.m
Reduce CPU utilization on macOS when using Window Capture.
The current implementation of Window Capture on macOS uses Core Graphics to render a bitmap raster which is then handed off to OBS.
This PR replaces that with an implementation that accesses the window's CGImage bitmap directly and blits it and hands that off as a frame to OBS, instead.
Tested on a 2020 iMac 27" w/ 3.6 GHz 10-Core Intel Core i9, AMD Radeon Pro 5700 XT 16 GB, macOS Catalina 10.15.7.
Tested with OBS 26.1.2 and Riot Games League of Legends, with an empty scene with only the Window Capture input source, OBS was consuming 55%-70% CPU.
Tested with the changes in this PR, OBS only consumed 30-35% CPU.
- Code cleanup (non-breaking change which makes …
=> mac-capture: Improve window capture performance

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-libobs-graphics-graphics.rst, docs/sphinx/reference-scenes.rst, libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-opengl/gl-subsystem.c, libobs-opengl/gl-subsystem.h, libobs/graphics/device-exports.h, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h, libobs/obs-scene.c, libobs/obs-scene.h, libobs/obs.h
Implements non-default blending modes for sources, allowing for compositing functionality similar to Photoshop/Nuke etc.
The implemented blending modes are:
- Normal
- Additive
- Subtractive
- Screen
- Multiply
- Lighten
- Darken 
Screenshots of each mode's behaviour are available [here](https://obsproject.com/forum/threads/source-blending-modes.148443/).
Blending modes have been implemented to leverage the existing blend state functionality, so changes to allow the blending equation's operation type to be modified have been added. Each blending mode is a preset combination of the blending equation's source/destination factors and operation, so the number of modes implemented is somewhat limited. Non-default blending modes require scene items to be rendered to a texture (using the same …
=> Implement non-default blending modes

libobs-d3d11/d3d11-duplicator.cpp
Despite DuplicateOutput deing documented to always return BGRA8, it is
seen fluctuating between BGRA8 and RGBA16F when HDR is enabled.
DuplicateOutput1 seems to provide a stable format whether SDR or HDR.
Also update the texture recreation logic to check for format changes.
Want to make valid CopyResource calls.
Format doesn't fluctuate. HDR/SDR transitions are handled fine. HDR always displays image even though we don't tonemap for SDR yet.
=> libobs-d3d11: DuplicateOutput1 for DXGI capture

UI/adv-audio-control.cpp, UI/window-basic-adv-audio.cpp, UI/window-basic-main-profiles.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, docs/sphinx/reference-core.rst, libobs/CMakeLists.txt, libobs/audio-monitoring/null/null-audio-monitoring.c, libobs/audio-monitoring/osx/coreaudio-monitoring-available.c, libobs/audio-monitoring/pulse/pulseaudio-monitoring-available.c, libobs/audio-monitoring/win32/wasapi-monitoring-available.c, libobs/obs.c, libobs/obs.h
A nitpick to my own PR #5225
With the reasonable possibility of monitoring support becoming a runtime check, the phrase `available` is more fitting.
\> Built OBS
\> Ran OBS
=> libobs: Rename obs_audio_monitoring_supported to _available

CI/flatpak/com.obsproject.Studio.json, docs/sphinx/reference-libobs-graphics-graphics.rst, libobs-opengl/gl-egl-common.c, libobs-opengl/gl-egl-common.h, libobs-opengl/gl-nix.c, libobs-opengl/gl-nix.h, libobs-opengl/gl-wayland-egl.c, libobs-opengl/gl-x11-egl.c, libobs-opengl/gl-x11-glx.c, libobs/graphics/device-exports.h, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h, plugins/linux-capture/CMakeLists.txt, plugins/linux-capture/pipewire.c
This MR implements the negotiation for sharing of DMA-BUFs via PipeWire as described in https://docs.pipewire.org/page_dma_buf.html.
This MR follows up on #5221 by adding capabilities to query all modifiers supported by the renderer.
This query was implemented for EGL based renderers. 
For proper DMA-BUF capability negotiation it is important, that both clients announce there capabilities by the means of a list of supported modifiers for a given format. Since PipeWire 0.3.33 we have the possibility to announce such a list per format and assure that it will not be mixed up with the capabilities of SHM buffer transport, which is distinguished by not announcing the modifier key.
This MR is required for obs to be able to use DMA-BUF transport via PipeWire with Wayland compositors after the …
=> linux-capture: proper DMA-BUF capability negotiation via PipeWire

CI/flatpak/com.obsproject.Studio.json
Add AJA NTV2 library to the Flatpak to enable AJA plugins compilations.
The commit `abf17cc1e7aadd9f3e4972774a3aba2812c51b75` was chosen to get all CMake changes that were added.
Those lines :
``` json
"type": "shell",
"commands": [
"sed -i 's/Clang|GNU/GNU/g' cmake/CommonFlags.cmake",
"sed -i 's/Linux|Darwin/Linux/g' cmake/CommonFlags.cmake"
]
```
Were added because some common flags are not correctly added.
- https://github.com/aja-video/ntv2/pull/4
Cleanup CEF installation from the bundle since it's no longer needed after OBS copied the needed files elsewhere.
- Feature parity
- Reduce bundle size
- Built it with flatpak-builder and check if AJA plugins had an loading attempt.
- Check if browser sources were working.
- CI changes
=> Flatpak: Add AJA NTV2 and deduplicate CEF

UI/window-basic-filters.cpp
This hides audio filters if a source supports async video but not filters.
**Note:** I am unsure if this is better suited in the first check that returns `false`, or the more programmatic one directly after it. Feedback welcome.
**Before:**
**After:**
* UI shouldn't display items that are unsupported/incompatible/do nothing.
* Fixes #5136
1. On Windows, enable `BUILD_TESTS` in CMake and add a "20x20 Random Pixel Texture Source (Test)" source
2. On macOS, add a Window Capture source.
3. Open the Filters window
4. Under "Audio/Video Filters" click the + (Add) button
5. Notice the list provided, and try clicking an audio filter then adding it
=> UI: Filter out incompatible audio filters in A/V list

UI/volume-control.cpp, UI/volume-control.hpp, libobs/obs-audio-controls.c
Currently, the volume meters don't show volume levels when
muted. This shows the levels and makes it grayscale when
the source is muted.
Muted:
Not muted:
Give indication to users of volume levels, even if muted.
Muted/unmuted audio sources, to make sure volume meters updated properly.
=> UI: Display grayscale volume meter if muted

docs/sphinx/reference-encoders.rst, libobs/obs-encoder.c, libobs/obs.h, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Set frame size (number of samples for each encoded packet) to audio stream parameter for the ffmpeg mux.
Sometimes the last audio packet is missing in MP4 file.
This issue is found when debugging the audio glitch in #5371.
Environment: Fedora 34, ffmpeg 4.4.1
1. Add debug information of PTS and DTS of packets written by ffmpeg-mux. See 232a94a06.
2. Set output mode `Advanced`, encoder `x264`, recording format `mp4`, audio bitrate `160` kbps.
3. Start and stop recording
4. Run `ffprobe -hide_banner -loglevel error -show_entries packet=codec_type,pts,dts -of compact` and compare the output made by step 1.
5. Continue steps 3 and 4 several times.
=> Fix missing last audio packet

UI/window-basic-main.cpp
Fixes an issue where sources could get released and destroyed when
undoing the removal of a nested scene.
Introduced as a side effect of 3d544653, this bug could make sources disappear forever (not good!).
Problem no longer appears.
Steps to reproduce:
Have two scenes, `Scene 1` with `Scene 2` nested in it, `Scene 2` with any source (text in my case).
Remove `Scene 2` from `Scene 1`.
Undo.
Notice the text source gets destroyed on master, but not with this PR.
=> UI: Hold refs to old sources during remove source undo

UI/window-basic-main.cpp
Similar fix to #5693 (but for scene removal instead of source removal), due to changes in 3d54465 sources could get lost.
I would've combined the two had I noticed this one as well when I did #5693.
Steps to reproduce:
- Have two scenes
- Scene `1` has scene `2` nested, as well as another source. Scene `2` can be empty.
- Delete `2`. Undo.
- Notice the other source that used to be in `1` is gone and destroyed.
Sources no longer get destroyed.
=> UI: Hold refs to existing sources during remove scene undo

docs/sphinx/reference-frontend-api.rst
Fixes the function names of `obs_frontend_open_source_properties()` and `obs_frontend_open_source_filters()`
Accurate docs are a nice thing to have
n/a
=> docs: Fix names of filter/properties functions

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-frontend-api.rst
Adds a frontend api call to open the interact dialog of a source, just like the `_properties` and `_filters` functions.
Wanted to have complete functionality for obs-websocket's `OpenInputPropertiesDialog` and `OpenInputFiltersDialog` requests.
Tested using unmerged `OpenInputInteractDialog` request.
=> UI: Add `obs_frontend_open_source_interaction()`
