.mailmap
Adding some authors to a .mailmap file to coalesce together commits made
by same authors, but not matching names.
=> Adding .mailmap

plugins/rtmp-services/data/services.json
https://api.twitch.tv/kraken/ingests
=> Add Asia/Australia Twitch ingests

plugins/rtmp-services/data/services.json
(Updated from Hitbox API's list)
All cities/countries written
Changed: EU-North
Added: Russia, US-Central, South Korea, China & Oceania
=> Update hitbox.tv ingest servers list

obs/window-basic-adv-audio.cpp, obs/window-basic-adv-audio.hpp, obs/window-basic-main.cpp, obs/window-basic-main.hpp
Delete source controls when the settings window is deleted.
=> UI: Small fixes to advanced audio settings

plugins/linux-v4l2/v4l2-input.c
Some minor changes that should make the plugin behave more predictable.
=> linux-v4l2: Minor improvements

plugins/rtmp-services/data/services.json
https://github.com/jp9000/OBS/commit/2bb4025
=> rtmp-services: Update GoodGame.ru ingests

COPYING
Address for FSF was wrong, corrected
=> FSF address

plugins/linux-capture/xhelpers.h, plugins/linux-v4l2/v4l2-helpers.h
This branch will fix some warnings reported by doxygen.
=> Documentation fixes

plugins/win-wasapi/win-wasapi.cpp
Fixes audio looping and playback issues with some chipsets (VIA and Realtek) during capture.
=> win-wasapi: Fix capture during silence

plugins/rtmp-services/data/services.json
=> rtmp-services: update Hitbox ingest servers list

plugins/win-capture/game-capture.c
Finally got around to fix my repo so I can issue a PR now.
I did not actually test the function that converts the B5G5R5A1 format, just adjusted the values from the B5G6R5 function.
=> Modified 16bit to 32bit color conversion to use SSE.

plugins/rtmp-services/data/services.json
Twitch.tv recently added additional ingest servers.
https://api.twitch.tv/kraken/ingests
=> rtmp-services: Update twitch.tv ingests

obs/forms/OBSBasicSettings.ui
CoreAudio AAC encoder is now available for both AAC-LC and HE-AAC.
Added some Audio bitrate settings for lower bitrate region.
=> UI: Add Audio bitrate

plugins/rtmp-services/data/services.json
These changes reflect the broadcast settings that we currently recommend.
=> Update Beam's recommended broadcast settings

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added DJlive.pl - polish platform for DJ`s
=> Please add DJlive.pl - polish platform for DJ`s to services.json

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
sorry i derped the url's
i tested all servers 
:blush:
=> rtmp-services: fix url

obs/window-basic-main.cpp
This changes the color of the buttons when streaming and recording to red when they are active.
=> UI: Add recording and streaming indicator

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Hey!
We at @WatchBeam recently added a good amount of new ingests to our platform. So here's a PR to add those to OBS Studio!
\- JamyDev
=> Add new Beam.pro ingests

UI/window-basic-main.cpp
Fixes https://obsproject.com/mantis/view.php?id=588
=> Don't nudge sources if preview is locked

plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
Affected both FFmpeg and nvenc encoders.
Fixes issue 667.
I'm not sure this is the most correct fix, but it did work for me.
=> obs-ffmpeg: Fix assumption about plane height with i444

.travis.yml, CI/install-dependencies-osx.sh
This reverts commit d160cedbc327dfa8dfc0b751a8c83079f4f1b37c.
=> Revert "CI: Build on OSX 10.10 on travis"

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Update to match changes from Restream.io ingests API: https://restream.io/ingests
=> rtmp-services: Update ingests list for Restream.io

UI/window-basic-main.cpp
Added missing frontend-api event call for AddScene and removed thus
obsolete event call in DuplicateSelectedScene.
=> UI: Fix frontend-api event call for adding scenes

CI/util/build-package-deps-osx.sh, CI/util/win32.sh, CI/util/win64.sh
I also added @jp9000's deps scripts for reference
=> CI: Build more features into FFMPEG deps

CI/before-script-osx.sh, CI/install-dependencies-osx.sh
Hopefully this will fix a crash from CEF on 10.9
=> CI: Update browser plugin ref and build scripts.

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
* Kamcord no longer does live streaming apparenlty
* The other doesn't exist anymore
=> rtmp-services: remove shut down services

UI/obs-app.cpp, UI/obs-app.hpp, UI/window-basic-main.cpp
This adds a few more commands:
--help, -h: get available commands
--version, -V: get current version
--studio-mode: enable studio mode
--minimize-to-tray: minimize to system tray
--startreplaybuffer: start replay buffer
=> UI: Add more command line options

UI/window-basic-status-bar.cpp, UI/window-basic-status-bar.hpp
This adds separate timers for streaming and recording to the status bar.
=> UI: Add separate timers to status bar

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
=> rtmp-services: Update twitch ingests

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/window-basic-main-outputs.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, plugins/obs-outputs/CMakeLists.txt, plugins/obs-outputs/rtmp-stream.c, plugins/obs-outputs/rtmp-stream.h
* Adds UI code/Qt stuff for checkboxes in advanced settings under "Networking"
* Adds rtmp-windows.c and rtmp-stream.h to cmake
* Adds log message to indicate that the user has enabled new socker loop/low latency mode
=> Add UI for networking changes in win-rtmp

UI/window-basic-settings.cpp
=> Hide new network stuff on non-Win32 systems

.travis.yml, CI/before-script-linux.sh, CI/install-dependencies-linux.sh
Just a simple build, skips deployment.
=> CI: Build on Linux

UI/window-basic-main-outputs.cpp
=> UI, enc-amf: Update AMD Encoder

CI/before-deploy-osx.sh
http://stackoverflow.com/a/36194213/136408
=> CI: Fix true / false on stable builds

CI/install-dependencies-osx.sh
This will enable the noise suppress filter on mac.
=> CI: OSX - Brew install speexdsp

CI/install-dependencies-linux.sh
Fixes Travis build error for the new libff2 stuff.
=> CI: Linux - Install FFmpeg from source

UI/data/locale/en-US.ini, UI/window-basic-main.cpp
This is a workaround for:
https://obsproject.com/mantis/view.php?id=598
=> UI: Add workaround to fix deleting final scene bug

UI/frontend-plugins/frontend-tools/CMakeLists.txt, UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp, UI/frontend-plugins/frontend-tools/frontend-tools.c
This adds the automatic scene switcher to Linux. The Windows and Mac versions already have this feature.
=> frontend-tools: Add automatic scene switcher for Linux

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Chaturbate is an adult live cam streaming website: https://chaturbate.com (NSFW)
We currently have around 5000 simultaneous streams running to hundreds of thousands of viewers.
Thanks
=> rtmp-services: Add Chaturbate Streaming Service

appveyor.yml
Old script checks only if file(cache) exists never updates it.
=> CI: Download deps if they are outdated

.editorconfig
…irements
For more details: http://editorconfig.org/
VS2017 supports this natively.
VS2015 and earlier can use a plug-in.
Most other popular IDEs support this natively or via a plug-in.
=> .editorconfig: Add file to speed up editor configuration

libobs/obs-output.c
I believe the issue with the next to impossible frame count to be an integer underflow, as in order to achieve those you'd have to have recorded for at least 345 days with 144 fps. So this commit fixes them by using a normal integer first and then deciding on the result if it should be used or be replaced with a 0.
=> libobs: Fix an int underflow in log_frame_info

plugins/obs-qsv11/QSV_Encoder.cpp
Change re-enter lock from mutex to atomic variable.
Since encoder_open and encoder_close is called in different thread,
it will cause the mutex acquired in one thread and release in another thread.
It doesn't fit the concept of mutex and mutex.unlock will trigger assert when
debugging in Visual Studio.
I replace it with interlocked compare-and-exchange mechanism.
=> obs-qsv11: change re-enter lock implementation

appveyor.yml
#1040 
If someone forks this repo, he will get error when using appveyor. It was my miss, didn't consider this case.
=> CI: fix curl download if file doesn't exist

.travis.yml, CI/before-deploy-osx.sh, CI/install/osx/build_app.py
I want to see where this fails.  Verbosity up everywhere, and build across multiple Xcode images.
=> CI: Crank up output verbosity for debugging

CI/before-deploy-osx.sh
Trying this in a different order.  Here's hoping!
=> CI: Do set-key-partition-list after import

.travis.yml, CI/before-deploy-osx.sh, CI/install/osx/build_app.py
Removing verbosity flags and extra OSX builds.
Reverted a change to the logging in `build_app.py` to see if the logging returns to normal or if it produces log spam.
=> CI: Cleanup

UI/data/locale/en-US.ini, UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This should help people find guides/resources.
=> UI: Add help portal link to help menu

appveyor.yml
This PR adds the Python path for the AppVeyor build service for scripting support.
=> CI: Add Python path for AppVeyor

cmake/Modules/FindLuajit.cmake
Makes building on Windows easier.
=> cmake: Add more LuaJIT lib names

UI/window-basic-main.cpp
Potential fix for https://obsproject.com/mantis/view.php?id=1170
While hastebin might not be the best to go for, it was the easiest to make the change to on short notice. Put this here for discussion, and to provide a working alternative if it's needed.
=> UI: Replace gist for log uploads

UI/frontend-plugins/frontend-tools/scripts.cpp
Some headers are no longer unconditionally included, leading to build failures like so:
```
FAILED: UI/frontend-plugins/frontend-tools/CMakeFiles/frontend-tools.dir/scripts.cpp.o 
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++ -DHAVE_OBSCONFIG_H -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DUSE_XDG -Dfrontend_tools_EXPORTS -IUI/frontend-plugins/frontend-tools -I/mnt/rokikaru/portage-stuff/builds/portage/media-video/obs-studio-9999/work/obs-studio-9999/UI/frontend-plugins/frontend-tools -IUI/frontend-plugins/frontend-tools/frontend-tools_autogen/include -isystem /mnt/rokikaru/portage-stuff/builds/portage/media-video/obs-studio-9999/work/obs-studio-9999/UI/obs-frontend-api -isystem /mnt/rokikaru/portage-stuff/builds/portage/media-video/obs-studio-9999/work/obs-studio-9999/libobs …
```
=> [Qt 5.11] Include 'QAction' in 'scripts.cpp' to fix a build failure.

appveyor.yml
18.5.21
change to dependencies2017.zip
=> CI: Upgrade to VS2017 on Appveyor

plugins/vlc-video/vlc-video-plugin.c
As of version 3, libvlc on mac OS is linked against libvlccore
differently. Previously libvlccore was referred to via the @loader_path
macro, now @rpath is used. As such, dlopen is no longer able to find
libvlccore. Explicitly dlopen libvlccore so that the symbols that
libvlc needs can be found.
Tested against VLC versions 2.2.8 and 3.0.3.
=> vlc-video: Dlopen libvlccore.dylib on mac OS

libobs/obs-scene.c, libobs/obs.c
This is just a simple fix of some warnings that appear when using GCC 9.
I tried my best to follow your contribution guidelines, but let me know if you need some adjustments! I'll be glad to make them.
=> Fix GCC 9 Warnings

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added KakaoTV live rtmp server to service list
=> rtmp-services: Add KakaoTV

CI/before-script-osx.sh, CI/install-dependencies-osx.sh
This should be okay to merge once @RytoEX gives the ok.
=> CI: Update OSX Deps package

UI/forms/OBSBasicFilters.ui, UI/window-basic-filters.cpp, UI/window-basic-filters.hpp
Delete key now should prompt to remove filters
=> UI: Add various shortcuts for filters window

UI/forms/OBSBasicSettings.ui
=> UI: Use themeID for red message in settings view

README.rst
Change README hyperlinks from Markdown style to RST style. Make URLs HTTPS. Correct some grammar.
Follow-up to PR #1444.
=> Fix README RST

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Default.qss, UI/data/themes/Rachni.qss, UI/qt-display.cpp, UI/qt-display.hpp, libobs/obs-display.c, libobs/obs.h
=> UI: Add ability to style preview background color

UI/data/themes/Default.qss
This changes the bottom area color for the about dialog
for the light theme. This color makes it more consistent
for the theme.
=> UI: Change about dialog bottom color (light theme)

plugins/coreaudio-encoder/encoder.cpp, plugins/decklink/plugin-main.cpp, plugins/image-source/image-source.c, plugins/linux-alsa/linux-alsa.c, plugins/linux-capture/linux-capture.c, plugins/linux-jack/linux-jack.c, plugins/linux-pulseaudio/linux-pulseaudio.c, plugins/linux-v4l2/linux-v4l2.c, plugins/mac-avcapture/av-capture.mm, plugins/mac-capture/plugin-main.c, plugins/mac-syphon/plugin-main.c, plugins/obs-ffmpeg/obs-ffmpeg.c, plugins/obs-filters/obs-filters.c, plugins/obs-outputs/obs-outputs.c, plugins/obs-qsv11/obs-qsv11-plugin-main.c, plugins/obs-text/gdiplus/obs-text.cpp, plugins/obs-transitions/obs-transitions.c, plugins/obs-x264/obs-x264-plugin-main.c, plugins/rtmp-services/rtmp-services-main.c, plugins/text-freetype2/text-freetype2.c, plugins/vlc-video/vlc-video-plugin.c, plugins/win-capture/plugin-main.c, plugins/win-dshow/dshow-plugin.cpp, plugins/win-mf/mf-plugin.cpp, plugins/win-wasapi/plugin-main.cpp
=> Plugins: Add descriptions to modules

plugins/image-source/obs-slideshow.c
Now the slideshow source will only load 5 images at a time. Images are
loaded and deleted when necessary. Each image has a two image buffer.
=> image-source: Decrease slideshow source memory usage

plugins/obs-filters/data/chroma_key_filter.effect
Reduces number of samples taken for same effect.
=> obs-filters: Optimize chroma key's box filter

CI/install-dependencies-linux-ubuntu16.sh, CI/install-script-linux.sh, CI/install-script-win.cmd, appveyor.yml
This PR enables building on Linux (Ubuntu 16.04) with AppVeyor.  This mostly allows us to test builds on a newer Ubuntu LTS than Travis CI's current Linux build environment (Ubuntu 14.04), and it gives us a backup Linux CI build in case Travis fails a build.  This also lets us test building with RTMPS/mbedTLS, though it _might_ be possible to do that on Travis as well.
Ubuntu 16.04's dependencies are different from the existing Ubuntu 14.04 dependencies, so a separate script for installing those dependencies has been added.  This PR also builds mbedTLS from source so that CI can build with RTMPS support to make sure that it can be compiled.  The reason that mbedTLS must be built from source is that on Ubuntu 16.04 (Xenial), the version available from apt, mbedTLS 2.2.1, does not work with …
=> CI: Build on Linux with AppVeyor

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
=> rtmp-services: Add Vimm.TV

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/obs-app.cpp, UI/obs-app.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-settings.cpp, UI/window-remux.cpp, UI/window-remux.hpp
=> UI: Add option to auto remux

UI/window-remux.cpp, UI/window-remux.hpp
This fixes the QAbstractItemModel invalid index warning.
=> UI: Fix auto remux warning

README.rst
=> Add Discord badge to README

plugins/linux-capture/xcompcap-main.cpp
Rather than inheriting the exact visuals from the window,
find whether the color buffer has alpha, find a config with
the necessary attributes for capture, and match its depth to
the depth of the window instead of the color buffer. Also,
cleanup glxpixmap texture binding before destroying the texture.
=> linux-capture: XCompCap now chooses glXFBConfigs based on window depth

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Updating the server list for Chaturbate.
Thanks
=> rtmp-services: Update Chaturbate POPs

CMakeLists.txt
seeing how much faster this compiles on appveyor
=> cmake: Use multiprocessor compilation on Windows

UI/window-basic-main.cpp
=> UI: Start projector user-facing monitor count at 1

CI/before-deploy-osx.sh, CI/install-dependencies-osx.sh, README.rst, azure-pipelines.yml
This requires an azure pipelines free plan to be added to the obsproject account.
https://github.com/marketplace/azure-pipelines
=> CI: macOS builds on Azure Pipelines

UI/data/locale/en-US.ini, UI/window-basic-settings.cpp
Fixes mantis issue https://obsproject.com/mantis/view.php?id=1366
=> UI: Fix locale for 'disabled' devices in audio settings

plugins/obs-filters/expander-filter.c
This improves the expander especially in the ballistics phase.
- Make envelope per channel.
- Move ballistics (attack/release) to log domain and after gain stage.
(some code clean up too)
cf Josh Reiss, Uni. London, [pdf](http://c4dm.eecs.qmul.ac.uk/audioengineering/compressors/documents/Reiss-Tutorialondynamicrangecompression.pdf)
Thanks to Dedrick for very useful feedback.
=> obs-filters/expander: Various improvements

azure-pipelines.yml
This is mainly for reducing build time.
=> CI: Build 32/64 bit Windows parallel on Azure

UI/data/locale/en-US.ini, UI/window-basic-main.cpp
Fixes:
https://obsproject.com/mantis/view.php?id=1395
https://obsproject.com/mantis/view.php?id=1396
=> UI: Fix a couple of locale issues

UI/forms/OBSBasicSettings.ui, UI/window-basic-main.cpp
https://ideas.obsproject.com/posts/429/add-25-and-50-fps-pal-to-common-fps-values
=> UI: Add PAL 25 & 50 FPS as common FPS values

UI/auth-oauth.cpp, UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/window-basic-main.cpp, UI/window-basic-settings-stream.cpp, UI/window-basic-settings.cpp
=> UI: Add checkbox for Twitch bandwidth test mode

UI/obs-app.cpp, UI/window-basic-main.cpp, UI/window-basic-stats.cpp, UI/window-projector.cpp
Fixes:
https://obsproject.com/mantis/view.php?id=937
=> UI: Use icons from theme on Linux

UI/window-basic-source-select.cpp
Fixes https://obsproject.com/mantis/view.php?id=1394
=> UI: Remove help icon from source select dialog

UI/properties-view.cpp
Fixes: https://obsproject.com/mantis/view.php?id=1418
=> UI: Fix file browser showing up when dir selected

UI/window-basic-main.cpp
Fixes https://obsproject.com/mantis/view.php?id=1411
```
21:54:06.516: ------------------------------------------------
21:54:06.516: Loaded scenes:
21:54:06.516: - scene 'Scene':
21:54:06.517:     - source: 'Text 5' (text_gdiplus)
21:54:06.517:     - source: 'Group B' (group)
21:54:06.517:         - source: 'Text 4' (text_gdiplus)
21:54:06.517:         - source: 'Text 3' (text_gdiplus)
21:54:06.517:     - source: 'Group A' (group)
21:54:06.517:         - filter: 'Filter 1' (scroll_filter)
21:54:06.517:         - source: 'Audio Input Capture' (wasapi_input_capture)
21:54:06.517:             - monitoring: monitor only
21:54:06.517:         - source: 'Text 2' (text_gdiplus)
21:54:06.517:         - source: 'Text 1' (text_gdiplus)
21:54:06.517:             - filter: 'Filter 2' …
```
=> UI: Log group items on startup

UI/source-tree.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Addresses 0000915:
https://obsproject.com/mantis/view.php?id=915&nbn=2#bugnotes
=> UI: Autoselect text on scene/source rename

UI/window-remux.cpp, UI/window-remux.hpp
Addresses: https://obsproject.com/mantis/view.php?id=1426
=> UI: Fix remux dialog ignoring filename changes

CONTRIBUTING.rst
Few words about the commit's titles were added (capital letter).
=> CONTRIBUTING.rst: Improve commit guidelines

UI/window-basic-main-outputs.cpp, UI/window-basic-main-outputs.hpp, UI/window-basic-main.cpp, libobs/obs-output.c
This PR includes a few general improvements from our Caffeine branch:
- Massively speeds up builds within Visual Studio on multi-core CPUs
- Fixes certain failures related to non-encoded output types
- Shows the output's last_error in the stream failure dialog
=> Minor improvements

UI/qt-display.hpp, libobs-opengl/gl-subsystem.h, libobs/graphics/image-file.c, libobs/obs-video-gpu-encode.c, libobs/obs-video.c, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c, plugins/obs-ffmpeg/obs-ffmpeg.c, plugins/obs-filters/expander-filter.c, plugins/obs-filters/limiter-filter.c
- Unused and unitialized Variables
- Formatings and Sizes
- Uncaught Switch cases
=> Clear linux compiling warnings

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-main.hpp
https://ideas.obsproject.com/posts/288/add-enable-disable-preview-shortcut
=> UI: Add hotkey to toggle preview

libobs/data/bilinear_lowres_scale.effect
=> libobs: Fix shader for GLSL

UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp, UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.h, UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp, UI/frontend-plugins/decklink-output-ui/decklink-ui-main.h, UI/frontend-plugins/decklink-output-ui/forms/output.ui
Putting this here for anyone who wants to play around with it. Once again probably another throw away UI PR.
=> Decklink: preview out support

UI/window-basic-settings.cpp
Commit 31d36691 missed updating a couple of lines while moving settings around.
- https://github.com/obsproject/obs-studio/commit/31d36691
=> UI: Fix Linux build without PulseAudio

UI/data/locale/en-US.ini, UI/window-basic-stats.cpp, UI/window-basic-stats.hpp
https://ideas.obsproject.com/posts/366/show-remaining-record-time-based-on-disk-space-and-current-settings
=> UI: Estimate recording time left until disk is full

UI/window-basic-main.cpp, UI/window-basic-main.hpp
This adds the ability to copy and paste filters from scenes.
=> UI: Add ability to copy/paste scene filters

UI/obs-app.cpp
Fixes: https://obsproject.com/mantis/view.php?id=1446
=> UI: Fix theme bug when updating from older versions

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss
=> UI: Fix theme issues with vis/lock checkboxes

UI/window-basic-settings.cpp, plugins/mac-vth264/encoder.c, plugins/obs-qsv11/obs-qsv11.c, plugins/obs-x264/obs-x264.c
This also modifies obs-ffmpeg, mac-vth264, obs-qsv11 and obs-x264.
=> UI: Increment bitrates by 50

CI/install-dependencies-osx.sh
This might fix broken builds. Lets let CI finish and see.
=> CI: Use swig 3.04 on OSX

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
=> rtmp-services: Update GameTips.TV

UI/window-basic-main.cpp
Observed when fixing https://github.com/obsproject/obs-studio/pull/1866
=> UI: fix crash due to NULL dereference

libobs/graphics/effect-parser.c
Adds more log information for effects, such as the reformatted effect code, parameters, techniques and passes. This is useful for tracking down issues and what actually ends up being compiled in the end, without having to guess where the error is actually at, as what is compiled and what was originally there usually differ by a lot.
This information is only logged if libobs is compiled in debug and _DEBUG_SHADERS is defined and not compiled if either of those are not the case.
=> libobs: Add additional effect debugging information

UI/window-projector.cpp, libobs/data/default.effect, plugins/obs-filters/chroma-key-filter.c, plugins/obs-filters/data/chroma_key_filter.effect, plugins/obs-filters/data/color_key_filter.effect
Clean up a handful of minor issues that I've run into while working on other PRs. Mostly dead code removal, and a small RGB -> YUV optimization.
=> Minor cleanup

.github/FUNDING.yml
**First:** Go to Settings -> Sponsorships -> Set up sponsor button in GitHub
Full instructions: https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository
=> GitHub: Add funding buttons

UI/data/themes/Dark.qss
This fixes a pixelated font on high-DPI, especially on Windows.
Seems the Qt documentation lied to me.
=> UI: Revert Dark theme Scenes font change

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Dark/settings/output.svg, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/forms/images/settings/output.svg
=> UI: Fix output icon size. Add padding to settings list items

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
The "common" value can be argued about.
=> rtmp-services: Add Steam

libobs/obs-source-deinterlace.c
There are devices like the GV-USB2 that produce frames with smooth
timestamps at an uneven pace, which causes OBS to stutter because the
unbuffered path is designed to aggressively operate on the latest frame.
We can make the unbuffered path work by making two adjustments:
- Don't discard the current frame until it has elapsed.
- Don't skip frames in the queue until they have elapsed.
The buffered path still has problems with deinterlacing GV-USB2 output,
but the unbuffered path is better anyway.
People use Amarec as an intermediary, and that's just too sad.
All testing has been performed on Windows.
GV-USB2, Unbuffered: Stuttering is gone! Spot-checked 10 hour recording; A/V is in sync, and 240p video output is smooth throughout.
GV-USB2, Buffered: No regression (still broken). …
=> libobs: Improve timing of unbuffered deinterlacing

CMakeLists.txt
Fix typo in master CMakeLists.txt: 'Interal' to 'Internal'
self-explanatory
n/a
=> cmake: Fix typo

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add Stripchat Streaming Service
Add new streaming service
Update rtmp-sevices version of services.json
=> rtmp-services: Add Stripchat streaming service

UI/auth-restream.cpp, UI/auth-restream.hpp, UI/data/locale/en-US.ini, UI/window-basic-auto-config-test.cpp, UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp
New "channels" widget for Restream service, if account is used for authorization
Obs has been built from sources with changes, result has been checked visually
It is new feature which adds functionality
=> UI: Add Restream integration: stream info widget, channels widget

plugins/win-wasapi/plugin-main.cpp
Fixes typos in description of wasapi module.
The code looks better.
Everything still works.
=> win-wasapi: Fix typo with description

libobs/obs-properties.c
When commit 6b6ea575ffaa61fb240f22c96cac7326bedc0a23 was merged, it did not modify obs_properties_apply_settings and obs_properties_remove_by_name. Which means that even though they are visually there, they don't work correctly - the callback for modifying properties doesn't work right, and the removal of properties doesn't work if they are in a group.
This change is required to make property groups work correctly.
This has been tested against obs-ffmpeg-encoder which uses Property Groups a lot. After applying the fix, the modified callbacks worked correctly.
=> libobs: Fix modified callback and remove by name for groups

UI/window-basic-main.cpp, UI/window-basic-properties.cpp, libobs-opengl/gl-shaderparser.c
Remove unnecessary (char *) casts
OCD, remove bad practice.
Compile clean in VS. Application still runs.
=> Remove casts

UI/win-update/updater/hash.cpp, plugins/win-capture/graphics-hook/graphics-hook.c
Variable type and format specifier should be consistent.
Fix warning found by cppcheck.
Compilation pass.
=> Fix Variable type and format specifier

.travis.yml, CI/before-deploy-osx.sh, CI/install-dependencies-osx.sh, azure-pipelines.yml
Just a few minor tweaks to switch over to cef 3770 on CI for OSX
=> CI: Update CEF on osx to 3770

UI/record-button.cpp
Let's try a build using Qt::WA_LayoutUsesWidgetRect suggested by @cg2121
=> wip try Qt::WA_LayoutUsesWidgetRect

UI/record-button.cpp
=> blank lines suck

UI/record-button.cpp, UI/window-basic-main.cpp
=> Try this, maybe it will work somehow

libobs/obs-cocoa.c
Something changed (or will change depending on POV) that makes strict the default. Fixed up the code.
Can't compile on my Mac setup.
Breakpoint inspection every place code has changed.
=> libobs: Strict objc_msgSend support

UI/window-basic-main.cpp, UI/window-basic-main.hpp
This simplifies the fullscreen toggle code
Removes unneeded variables. Simpler code is always better.
Toggled fullscreen.
=> UI: Simplify fullscreen toggle code

UI/data/locale/en-US.ini, libobs/util/platform.c
a few of the requested filename formattings from: https://ideas.obsproject.com/posts/501/add-additional-recording-filename-strings
=> libobs: Add video info to filename formatting

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
I added Stars.AVN.com streaming service.
Please merge it into the master.
Best regards,
Dmytro
=> rtmp-services: Add Stars.AVN.com streaming service

plugins/obs-filters/mask-filter.c
I am using the "Image Mask/Blend" filter with type alpha mask (color channel) to dynamically crop out part of a source. I have an external application running that updates the mask file when needed, so I needed those changes to be reflected in real time.
I used code from `image-source.c` to make this happen. I hope I didnt introduce any memory leaks or whatever. Also I am not 100% sure which functions require a `obs_enter_graphics();`. But when tested locally it appears to work exactly how I imagined it would.
=> obs-filters: Reload the mask image when file change is detected

UI/window-extra-browsers.cpp
**October Edit:** This PR will likely be unnecessary with the new dashboard being rolled out.
The Twitch docks that are enabled via Service Integration are based on panels which come from Twitch's streamer Dashboard. This PR enables the ability for users to add their own Custom Browser Docks (introduced in a previous commit) that point to Twitch Dashboard panels that aren't provided natively in OBS, or to add Twitch panels without specifically using the Service Integration capabilities.
Implementation details:
* This code is exclusively designed to run on Twitch dashboard popouts. I considered making the check more aggressive, and would happily accept feedback in this area. (this could be done with a regular expression, for example)
* As these docks can be added regardless of service …
=> UI: Add support for Custom (Legacy) Twitch Dashboard Docks

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
=> rtmp-services: Add Konduit.live

CI/before-deploy-osx.sh
Change install_name id from `/usr/local/opt/mbedtls/lib/libmbed*.dylib` to `@executable_path/../Frameworks/libmbed*.dylib`
Verified libmbedtls dylibs loaded by exporting `DYLD_PRINT_LIBRARIES=1` prior to launching OBS in Terminal.
=> CI: Fix mbedtls id in mac deploy script

CI/install/osx/packageApp.sh
Fix install name for QtNetwork in macOS packaging script.
=> CI: Fix QtNetwork in Mac packaging script

libobs-d3d11/d3d11-subsystem.cpp
Sometimes Present stalls are seen when multiple swap chains are active, e.g. fullscreen preview or fullscreen multiview. The repro rate is not 100%, but I haven't seen it since adding the fix.
User reported long graphics frame time when using fullscreen multiview, and I was able to reproduce sometimes.
Toggled on and off fullscreen multiview and fullscreen preview several times. Given previous frequency, maybe half the time, it's likely the issue is fixed.
=> libobs-d3d11: Increase the frame queue capacity

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
I add one more service to "plugins/rtmp-services/data/services.json"
It's called show-it.tv (https://show-it.tv/), it provides cam streaming services.
=> rtmp-services: Add show-it.tv

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
We have a new back-end to the SermonAudio webcasting system which required a new URL and now allows for increased bitrates.
=> rtmp-services: Update to the SermonAudio entry

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added Uscreen to streaming services drop down.
=> rtmp-services: Add Uscreen

libobs/obs-source.c, libobs/obs-source.h, libobs/obs.h
This adds libobs functions to control media.
Since #1803 was such a large PR, it was hard to review. Plus it was impossible to keep up with master since merge conflicts would happen all of the time. I'm now submitting the feature one piece at a time. With this, the UI portion can be discussed as a separate item on how to best implement it.
Compiled OBS.
=> libobs: Add media control support to backend

libobs/obs-scene.c
`obs_sceneitem_group_add_item` and `obs_Sceneitem_group_remove_item`
were leaving the affected scene in an inconsistent state.
To resolve, simplify and make the code more readable, we replace the
manual linked lists mutation with existing `detach_sceneitem` and
`attach_sceneitem` calls.
Tested by invoking the methods above and observing results.
=> libobs: fix obs_sceneitem_group_XXX_item API

plugins/decklink/platform.hpp, plugins/decklink/plugin-main.cpp, plugins/decklink/win/platform.cpp
Logs out the compiled and installed version of the decklink API on plugin load
Might help debugging issues in the future.
=> decklink: Log decklink API version on plugin load

deps/media-playback/media-playback/media.c
This removes duplicate seeking code. The get current time function was also simplified.
Code cleanup.
Tested with #2380 
=> deps/media-playback: Simplify seek/time code

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
> ### Description
> Added Uncanny.gg to services drop down .
> 
> ### Types of changes
> New feature (non-breaking change which adds functionality)
> 
> ### Checklist:
> * [x]  My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
> * [x]  I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
> * [x]  My code is not on the master branch.
> * [x]  The code has been tested.
> * [x]  All commit messages are properly formatted and commits squashed where appropriate.
=> rtmp-services: Uncanny.gg

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added Madcat to streaming services drop down.
=> rtmp-services: Add Madcat

UI/importers/sl.cpp
Streamlabs' fork of OBS allows the same name to be used by multiple scenes and sources. When importing a collection which contains repeated names, the resulting collection can crash OBS if a source and scene share a name. This change makes it so all names of imported sources and scenes are unique, like the OBS Classic and XSplit importers do.
Preventing a crash with collections imported from Streamlabs.
I have tested this change against a Streamlabs collection that caused a crash in RC1 when you tried to import it and then load the collection.
=> UI: Fix importing SL collections with repeated names

UI/importers/sl.cpp
The previous fix for repeated names accidentally meant that if a scene
item in a scene was meant to show another scene that was lower in the
list, it would fail to create the item, and wouldn't make it into the
imported collection.
This fix makes sure that scenes as sources still works properly in that
situation.
Preventing missing scene items from an imported SL collection.
With a collection that exhibited the bug being fixed, I tested that the change meant that all items got correctly imported.
=> UI: Fix scenes as sources for SL import

plugins/win-capture/game-capture.c, plugins/win-capture/graphics-hook/graphics-hook.c, plugins/win-capture/graphics-hook/vulkan-capture.c
Clean up VC++ warnings, and remove unnecessary code.
Code health, maintainability.
Breakpoint inspection for most lines. Vulkan capture continues to work.
=> win-capture clean-up

azure-pipelines.yml
CI: Update Linux CI from Ubuntu 16.04 to 18.04
This PR/commit only changes the Ubuntu image from Ubuntu 16.04 to 18.04 for the Prebuild and Build_Linux jobs on Azure.
PR #2497 seemed to successfully build on CI in the PR build, but its code subsequently failed to build in the Build_Linux CI job after being merged to master.  The build failure seems to be due to CI using Ubuntu 16.04 LTS rather than the newer 18.04 LTS.  Discussion on Discord concluded that we should update CI to Ubuntu 18.04.
I built the latest master on 16.04 and the PR branch with 18.04.  Then I PR'd the updated branch onto my own master and let the PR build.  Once that was successful, I merged the PR onto my master branch and let that build.  Here's a screenshot and a build result table from [my Azure CI …
=> CI: Update Linux CI from Ubuntu 16.04 to 18.04

plugins/win-capture/graphics-hook/vulkan-capture.c
Fix paths to not do Vulkan capture things if the driver doesn't support it.
Fixes #2590.
Intel doesn't seem to support Vulkan capture, and we were sending it down a crash path.
Vulkan capture gracefully fails on Intel HD 530. Still works on RTX 2080 Ti.
=> win-capture: Fix crash if GPU can't Vulkan capture

UI/properties-view.moc.hpp, UI/source-tree.hpp, UI/window-basic-stats.hpp
These files appeared to be dependent on their include order and were
missing definitions when files were compiled in a different order.
e.g. 
`source-tree` depends on `enum obs_fontend_event` and `OBSSceneItem`
`window-basic-stats` depend on `enum obs_frontend_event`
`properties-view.moc` depends on `obs_data_t`
Fixes compilation for non-standard builds.
Builds and runs.
Trivial
=> UI: Fix missing includes

.github/workflows/clang-format.yml, CI/before-script-linux.sh, CI/before-script-osx.sh, CI/install-dependencies-linux.sh, CI/install-dependencies-osx.sh
Set up a new github action to run clang format on linux and osx
Previously we ran the clang format checks as part of the regular build tasks. I ran into an issue where this was formatting a submodule and causing the build number to get marked "modified" This should avoid that in the future and have a better separation of concerns
=> CI: Move clang format check into a seperate github workflow

CI/before-deploy-osx.sh, azure-pipelines.yml
=> CI: Rewrite new deps paths in obs-ouputs.so

plugins/mac-syphon/CMakeLists.txt, plugins/mac-syphon/syphon.m
Use ARC on the syphon plugin
Syphon plugin was crashing on release, so lets give up and modernize it to use ARC
Ran it on my machine, needs more testing
ARC has been a thing since like 2011 :|
=> mac-syphon: Move the syphon plugin over to ARC

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Update ChathostessModels service
Need change to the name and add a backup server as well as change max video bitrate
Server tested and working properly.
=> rtmp-services: Update ChathostessModels service

libobs-opengl/gl-subsystem.c
Flip viewport in coordination with update_viewproj_matrix.
Fix Multiview on Mac.
Tested regular preview with and without Studio Mode, Multiview window, and video recording on Windows (GL), Mac, and Linux.
=> libobs-opengl: Fix viewport flip

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Change Stripchat Streaming Service
Change streaming service
Update rtmp-sevices version of services.json
=> rtmp-services: Change Stripchat streaming service

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added VirtWish to streaming services drop down.
=> rtmp-services: Add VirtWish service

libobs/util/threading-windows.c
It's the better way to declare thread names, but you need Windows 10, version 1607 to use it.
Use the `SetThreadDescription` function to register the thread name.
Using the `SetThreadDescription` function lets the entire system know about the thread name, not just a currently attached debugger.
Built my own version of obs and ran it. Checked that the new code runs. Verified that the function has the intended effect by manually skipping the legacy code and watching the thread list in the debugger.
=> libobs: Additionally use SetThreadDescription if possible

cmake/Modules/FindOSS.cmake, plugins/CMakeLists.txt, plugins/oss-audio/CMakeLists.txt, plugins/oss-audio/oss-audio.c, plugins/oss-audio/oss-input.c, plugins/oss-audio/oss-platform.h.in
This PR introduces oss-audio as a audio source plugin.
This plugin enables audio capturing support on platforms which uses OSS as sound interface such as FreeBSD, without the use of any kind of ALSA or PA shims.
I tested the changes on my desktop with a jack cable connected to a laptop.
=> plugins: Add oss-audio input support

libobs/util/threading-posix.c
Handle spurious wakeups, and ensure mutex unlock.
Nasty behavior can occur if event wait is not respected, or mutex is never unlocked.
Debugger breakpoint inspection.
=> libobs/util: Fix POSIX event bugs

UI/data/locale/en-US.ini
This removes the unused language region string.
There was a guy on Crowdin who had the problem that there were 4 countries that are using his language and he wanted to know what he has to do in this case. Then I've seen this string is unused and came to the idea of just removing it entirely.
/
Clean-up of an unused string.
This language string is also unused, but it helps a lot to identify corrections on Crowdin with the language names (like it happened here: https://github.com/obsproject/obs-studio/commit/add59d52538aaf084474841754d1ea5881a1e063) and to get new language names for upcoming languages that are not already present in the locale.ini (https://github.com/obsproject/obs-studio/blob/master/UI/data/locale.ini).
=> UI: Remove language region

UI/obs-app.cpp
Closes obsproject/obs-studio#2290
The crash dialog displayed the following message even when OBS-Studio runs in portable mode:
> Woops, OBS has crashed!
> Would you like to copy the crash log to the clipboard?  (Crash logs will still be saved to the %appdata%\obs-studio\crashes directory)
Now the message contains the actual path of the crash dump:
> Woops, OBS has crashed!
> Would you like to copy the crash log to the clipboard?  (The crash log will still be saved to [path to crash directoy]\Crash 2020-03-16 22-43-23.txt)
This closes issue #2290 
Under some circumstances the displayed path of the crash directory is wrong. Then it is hard to find the crash dump.
It was tested on a Windows machine. 
I forced OBS-Studio to crash by executing code which throws an exception.
Tested in the …
=> Show accurate path in Crash dialog

UI/obs-frontend-api/CMakeLists.txt
Previously the api header was not targeted for installation and may have
been missing for third party users (read out of tree).
previously out of tree builds could not include frontend api, now they can.
installed locally to confirm the placement of the header into the obs prefix.
build fix. fixes #2625
=> UI: Install public headers for frontend-api

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add list of rtmp servers for the AngelThump service
Ease of streaming to the service for users
Started and successfully connected with new build
New streaming service
As per conversation between @TimIsOverpowered / @iAxx / @jp9000 
https://angelthump.com/help/stream
https://angelthump.com/help/ingests
=> rtmp-services: add angelthump

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Server Update
Server url update and order change.
Update the name of the platform. From Afreeca.TV and 아프리카TV to AfreecaTV.
Updated server url.
Change order according to number of users per each server. 
Locally tested and is working properly.
=> rtmp-services: AfreecaTV Update

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Bitrates have been updated
For 1080p support increase max-bitrates
JSON has been checked for validity.
- Services update
- [N/A] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [N/A] The code has been tested.
- [N/A] I have included updates to all appropriate documentation.
=> rtmp-services: Update Lahzenegar RTMP

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add weabook.live stream service to OBS dropdown options.
Weabook.moe is an moe social, and weabook.live is live streaming service for .moe, so add to OBS dropdown options will improve user experience.
Just changed 2 files of services.json. do not effect to other. 
Add a stream service.
=> rtmp-services: Add weabook.live

plugins/linux-capture/xshm-input.c
Adds support and relevant properties for cropping screen capture input on Linux platforms.
Adds fields allowing users to crop screen capture input.
In my case, this change is motivated by the performance impact. I use a 4K monitor and OBS video output at 1080p. The overhead incurred by doing copies on an entire 4K image is un-necessary in cases where the effective video output resolution is much lower than the display resolution. Cropping the capture to 1080p eliminates that overhead.
I tested this on the following display setup and it seems to behave: 
```
DisplayPort-0 connected 3440x1440+3840+0
DisplayPort-1 connected primary 3840x2160+0+0
```
Just watching the preview run for a minute or so makes the impact of the overhead obvious:
```
FPS: 33.44
Average time to render frame: 30.0ms …
```
=> linux-capture: Add support for cropping the input source

.github/workflows/main.yml, CI/install-dependencies-osx.sh, CI/scripts/macos/Brewfile, CMakeLists.txt, test/CMakeLists.txt, test/cmocka/CMakeLists.txt, test/cmocka/test_darray.c, test/cmocka/test_serializer.c, test/osx/test.mm
Adds cmocka a C unit testing framework to use with libobs.
We should be able to add unit tests for relevant changes to libobs, this enables that
Ran the unit tests locally and on CI
=> libobs: Add sample unit tests leveraging cmocka

UI/window-basic-main.cpp
Log monitoring status of global audio devices.
Request from support (Flaeri).
Run the code.
=> UI: Log monitoring type for global audio devices

plugins/win-capture/graphics-hook/vulkan-capture.c
The swap image index may not be a rotating value, so manage a separate
index to avoid reusing frame data early and stalling.
Heard about the swap image index behavior in some Vulkan chat.
vkcube of course.
=> win-capture: Decouple swap and frame indices

plugins/win-capture/window-helpers.c
Don't use Chrome classes for priority
Avoids accidental fallback to Discord for example.
Tested fallback behavior of Electron game (TETR.IO), UWP application (Calculator), and Win32 application (Notepad). TETR.IO no longer falls back to Discord.
=> win-capture: Don't use Chrome classes for priority

libobs/media-io/video-scaler-ffmpeg.c
Use plane height instead of overall height for copying planes to fix
memory stomp introduced by #2836.
Debugger breakpoint inspection.
=> libobs: Fix video scalar copy heights

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
A request for add our streaming service with "Taryana - Apachat | تاریانا - آپاچت" title name.
=> Add "Taryana - Apachat" streaming service.

libobs/util/simde/simde-math.h, libobs/util/sse-intrin.h, libobs/util/sse2neon.h
Adding support for arm compilation in order to run on raspberry pi by adding [sse2neon](https://github.com/DLTcollab/sse2neon)
It would be nice if the project could compile for arm devices, starting with raspberry pi
I compiled the build on raspberry pi using this [script](https://github.com/venepe/install-obs-raspberry-pi) to install obs with the ndi and websocket plugins.  I was able to run ndi and the websocket plugins.
I ran the build on a Raspberry Pi 3B+ running Raspberry Pi OS 2015-05-05.  I also ran the code on a macbook running macOS Catalina.  I did **not** test the changes on a windows machine.
The code compiles and runs on raspberry pi.
_I did not compile the changes through a windows machine as I do not have one …
=> libobs: Add arm support

plugins/win-capture/graphics-hook/vulkan-capture.c
Use linked lists in place of fixed-size arrays in an attempt to fix
behavior when programs generate lots of non-resource objects.
Possibly fixes #3145.
~~TODO: Rebase after prerequisite pull requests have been merged: #3074, #3113, and #3149. The commits have been cherry-picked into this branch in the meantime.~~
There is at least one program out there that dies because we didn't have flexible handling for lots of Vulkan objects that there usually aren't lots of.
Checked vkcube, and Doom 2016. Open and close vkcube several times with OBS open. Open and close OBS several times with vkcube open.
=> win-capture: Remove fixed-size Vulkan arrays

UI/window-basic-settings.hpp
Tag overridden virtual function with override.
Clang warning.
Compiles.
=> UI: Fix warning about missing override

CI/install/osx/packageApp.sh, CI/scripts/macos/packageApp.sh
Disable Python when building on CI for macOS.  Follow-up to 63373a8fd713b94d63940e7f131beee5d4963d3a and 2c60aa2abe27d3fdb01d01edde508f57ca26a82f (PR #3203).
Prevent CI build failures.
I let CI run a full build on my fork and waited for the CI to successfully build for macOS.  I have not tested the resulting build.
=> CI: Disable Python on macOS

plugins/obs-qsv11/obs-qsv11.c
An issue found where new "Latency" and "Subjective Video Enhancement" options where always using default settings even after being changed in UI. This issue was introduced when mapping old QSV settings to new ones in #3035 
1. Removed legacy options from default setting list
2. In update_latency function, update “latency” only when “async_depth” or “la_depth” is in setting list
3. In function update_enhancements function, update “enhancements” only when “mbbrc” or “CQM” is in setting list
=> obs-qsv11: Fix bug mapping old qsv settings to new

UI/window-basic-main-screenshot.cpp
Remove unused variable from screenshot function.
Cleans up a compiler warning
Compiles, looks sane, and I was able to take screenshots still.
Code cleanup (non-breaking change which makes code smaller or more readable)
=> UI: Remove unused variable

plugins/win-capture/graphics-hook/vulkan-capture.c
Not all surfaces support VK_IMAGE_USAGE_TRANSFER_SRC_BIT. Only
VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT is required by spec. Add fall back.
Apparently very old AMD drivers failed to support this usage bit. I don't think we've seen any crashes in the wild currently, but better to be safe before such a driver shows up.
Breakpoint inspection for vkCube 32/64. Doom (2016) also works. Debugger shenanigans to force fall back path.
=> win-capture: Robust Vulkan swap chain handling

plugins/obs-filters/noise-suppress-filter.c, plugins/obs-outputs/librtmp/dh.h, plugins/obs-outputs/librtmp/handshake.h
Fix unused variables when compiling without rnnoise
Fix unused variable warnings in GCC when using assert() in release (This is really dumb)
Easier to find more important warnings in logs.
It still compiles
=> obs-filters/obs-outputs: Cleanup unused var warns

CI/full-build-macos.sh
Fixes bugs and remedies usability issues discovered by @WizardCM:
* Adds support for `BUILD_DIR` env variable to change the build directory used by the script (which is a new `build` directory under the checkout directory by default)
* Adds support for the `-d` switch to skip dependency checks and downloads (use at your own peril)
* Adds check for macOS versions earlier than 10.15 (with support for v11.0 coming up) to install and use `curl` via Homebrew
* Adds progress bar to `curl` downloads for increased transparency for when the script might seem otherwise to be "stuck"
* Remove step to install `packagesbuild` which is not needed for OBS builds
* Fixes capitalisation error in bundling step that could occur on case-sensitive file systems
* Adds additional step output for fetching OBS …
=> CI: Update macOS CLI build script

docs/sphinx/reference-properties.rst, docs/sphinx/scripting.rst
This corrects an incorrect statement about callbacks in the scripting docs, and corrects the properties documentation defining the wrong typedef for the obs_properties_add_modified_callback function.
To have correct and up to date documentation.
N/a
=> docs/sphinx: Fix errors with scripting and properties.

UI/qt-wrappers.cpp
Fixes bug that would cause a crash on exit when drag and dropping scenes.
Fixes #3310 
Tested it on my machine, as well as others.
=> UI: Fix source ref bug causing crash on exit

plugins/win-capture/graphics-hook/graphics-hook.c
Tag debug output in the game process with "[OBS]" and mention that
graphics-hook.dll is ours.
Developers have mentioned they didn't realize the HL scientist message was coming from OBS. This will allow them to track down OBS-related issues more quickly. Unfortunately renaming the DLL itself is problematic.
Inspected log output from vbcube. Breakpoint inspection.
=> win-capture: Improve game capture messages

plugins/rtmp-services/CMakeLists.txt, plugins/rtmp-services/data/services.json, plugins/rtmp-services/rtmp-common.c, plugins/rtmp-services/rtmp-services-main.c, plugins/rtmp-services/showroom.c, plugins/rtmp-services/showroom.h
Add SHOWROOM streaming service to OBS dropdown options.
Add plugin to get mutable rtmp url from API.
SHOWROOM is a live streaming service. This change allow user to stream without complicated operations.
I confirmed that it works with Live server.I checked on Mac and Windows.
Details are shown below.
1. sign into https://www.showroom-live.com/
1. Register as a distributor.
1. Get obs_key from https://www.showroom-live.com/api/obs/obs_key
1. Open OBS streaming setting
1. Select SHOWROOM service from dropdown list
1. Paste obs_key to AccessKey field
1. Start streaming.
(screenshot)
=> rtmp-services: Add SHOWROOM

plugins/linux-v4l2/v4l2-controls.c
Previously, changing boolean or menu settings in the "camera controls" portion of v4l2 video sources would send incorrect values to the ioctl. This made configuring some camera properties impossible.
This change fixes the support.
Cameras on Linux look bad since they can't be configured properly.
To check if settings are updated I used `v4l2-ctl -d /dev/video0 --all`
Before this change, boolean and menu values would not update.
I'm on `Linux manjaro 5.4.58-1-MANJARO #1 SMP PREEMPT Tue Aug 11 15:46:30 UTC 2020 x86_64 GNU/Linux`
Code fixes for `v4l2_control_changed`
=> linux-v4l2: Fix boolean and menu control types

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Updated the RTMP servers list for Vaughn Live / iNSTAGIB & Breakers
Gives access to newly added ingest points to those platforms
It's JSON, not much to test.
Updated RTMP servers list for the aforementioned platforms
=> rtmp-services: Update Vaughn Live / iNSTAGIB & Breakers

plugins/linux-v4l2/v4l2-input.c
v4l2 pixfmt fourcc's are always stored little-endian.
ref: https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-enum-fmt.html?highlight=vidioc_enum_fmt
Makes the logs more readable.
It logs the correct format.
=> v4l2-linux: Fix fourcc order

UI/window-basic-main.cpp
Adds the ability to close the application through CTRL + Q
QOL and requested in #3106
Tested on my linux machine
=> UI: Implement exit on CTRL + Q for linux

plugins/win-capture/cursor-capture.c
This fixes the handling of padding on cursor masks for color cursors. This was affecting the capture of cursors in the game RuneScape, see #3472.
There were a couple issues. get_bitmap_data wasn't allocating enough memory for the cursor mask in some cases. apply_mask wasn't taking into account the possibility for the mask pixel rows to be padded(to bmWidthBytes).
I'm not really a programmer, so I may have missed a better way to implement this.
OBS now correctly captures the cursor in the game RuneScape. I have not observed any regressions when capturing graphical cursors elsewhere.
=> win-capture: Fix mask handling on some color cursors

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
ffmpeg-mux does not notice if ffmpeg returns an error from
av_interleaved_write_frame() which means that OBS never knows if there is a
problem in ffmpeg.
This is the biggest issue for cases like srt:// or tcp:// streams that can
regularly fail. Without this change OBS never knows that something went wrong.
I noticed that when using an `srt://` custom stream endpoint OBS, if there is an issue with the SRT connection, a message is printed in the logs saying the SRT connection has failed but OBS never notices it. OBS noticing when the stream has failed is the first step in being able to do the auto-reconnection of SRT streams.
I created recordings and `srt://` streams and found that they worked successfully and that an error was displayed when I forcefully stopped the remote SRT receiver.
- …
=> obs-ffmpeg: Add error detection to ffmpeg-mux

plugins/win-capture/graphics-hook/vulkan-capture.c
Rivatuner Statistics Server calls vkGetInstanceProcAddr for
vkCreateDevice with a NULL instance. According to spec, this should
return NULL, but RTSS will dereference this and crash.
This change returns function pointers for every intercepted function
regardless of instance, which is enough to keep RTSS alive.
People use RTSS. Other layers may have the same bad behavior.
- vkcube no longer crashes with RTSS installed.
- vkcube and Doom (2016) run with and without OBS game capture attached.
=> win-capture: Violate Vulkan spec for compatibility

libobs-winrt/winrt-capture.cpp
We were performing a custom cursor draw for WGC, which we attempted
because we thought we could bring back hardware cursor responsiveness,
but MS says that it won't. Since the custom draw was bugged to cause
black screens anyway, just use the native cursor draw for now.
Black screens when OBS and target window were driven by separate GPUs.
- Repro'd black screen issue with Intel and AMD GPUs. Black screen no longer happens now.
- WGC cursor capture on and off behave as expected on Windows 10 20H1.
=> libobs-winrt: Use native cursor draw for WGC

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
UK Server added
Added server for users in the Europe region
Locally tested and is working properly.
=> rtmp-services: Update AfreecaTV

UI/window-basic-stats.cpp
Helps prevent Stats dock from resizing OBS when long text is set.
Fixes #3583.
OBS resizing unexpectedly is unpleasant.
Verified minimum width is acknowledged, and that the Stats dock does not resize OBS in previous situations.
=> UI: Apply minimum width to Stats fields

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp
Update Twitch Get Stream Key link
Old url redirect to incorrect url
New link redirect to correct user's stream key url in Firefox and Edge
=> UI: Update Twitch Get Stream Key link

plugins/linux-alsa/alsa-input.c
OBS already handles a couple of different audio formats, this expands
alsa input to try these additional formats for devices with weird format
support.
Im pretty sure this (~~but its untested as I dont have any devices with non-s16 support~~ User reports its working on their device)
fixes #3547
Testing with a webcam it appears to still work when the devices support S16, removing S16 from the list to check it gives the helpful error that the device doesnt support any of OBSs formats.
=> linux-alsa: Support more device formats

docs/sphinx/reference-scenes.rst
Correct docs according to warnings from GitHub Actions/Checks.
Fix these issues so that we can focus on meaningful warnings.
I created a PR against my own fork to verify that the warnings went away.  I downloaded and viewed the resulting documentation HTML to verify that the documentation still looked correct.
=> docs: Fix GitHub Actions doc check warnings

plugins/rtmp-services/data/services.json
Viloud is an online video platform for creating and streaming live, linear and on-demand TV channels.
=> rtmp-services: Add Viloud service

CONTRIBUTING.rst
In the CONTRIBUTING.rst document, update link to compiling and building instructions to point to the GitHub repo at the "obsproject" org URL. Replace link to Mantis with link to GitHub Issues for our bug tracker to mirror the contents in README.rst.
Updated links are good.  We use GitHub Issues now instead of Mantis.
This is a simple text/documentation change that is not related to the application, so I just checked if the updated text was correct and that the links worked.
=> CONTRIBUTING.rst: Update CONTRIBUTING doc

plugins/linux-v4l2/linux-v4l2.c
Using modinfo dumps all the output into the terminal instead redirect
all output to dev/null.
Spamming the terminal with subshell output usually isnt good.
Works on my machine
=> linux-v4l2: Hide modinfo from terminal

plugins/decklink/decklink-device-instance.cpp
Ignore color space change in format detection to fix endless loop.
Fix #3511
Fix #3277
No longer restart video stream on colorspace change.
When video format auto detection is activated, the VideoInputFormatChanged method iis called on format and color space changes.
If the stream is restarted, a bmdVideoInputColorspaceChanged event is fired.
Restarting a stream on color space change creates an endless stream restart loop, causing high load, video and audio issues.
=> decklink: Fix format detection loop

UI/frontend-plugins/decklink-captions/decklink-captions.cpp, libobs/obs-output.c, plugins/decklink/OBSVideoFrame.cpp, plugins/decklink/OBSVideoFrame.h, plugins/decklink/decklink-device-instance.cpp, test/cmocka/test_serializer.c
There were a bunch of unused variable warnings, clean those up
Warnings are noisy
=> decklink: Clean up warnings introduced by caption code

libobs-winrt/winrt-capture.cpp, libobs/obs-output.c, plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c, plugins/obs-filters/rnnoise/src/denoise.c, plugins/obs-filters/rnnoise/src/pitch.c, plugins/obs-filters/rnnoise/src/rnn.c, plugins/rtmp-services/rtmp-common.c
Clean up various warnings seen with MSVC.
I hate warning spam.
OBS still runs. I did not test every feature.
=> Fix MSVC warnings

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Increase the maximum allowed audio bitrate for streaming to twitch to 320 kbps.
According to https://help.twitch.tv/s/article/broadcast-guidelines?language=en_US twitch increased the maximum allowed audio bitrate to 320 kbps.
This change will let people use more audio bitrate when the streaming service recommendations get enforced which is the default in OBS.
Streaming to twitch still works and setting the audio bitrate to 320 kbps will no longer get reduced to 160 kbps.
Doesn't apply here IMHO.
=> rtmp-services: Increase twitch audio bitrate

plugins/win-capture/graphics-hook/vulkan-capture.c
Pass valid instance when looking up VkCreateDevice.
This fixes a crash that can happen if the next actor in the chain correctly returns NULL for our bad function parameters. Fortunately for us, most ignore the spec and return a valid function pointer.
vkcube 32/64 breakpoint inspections for valid instance. Capture works for both.
=> win-capture: Fix our own Vulkan spec violation

UI/window-basic-main.cpp
fix typo:  base.ini -> basic.ini
None
None
Code cleanup
- [x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x ] My code is not on the master branch.
- [x ] The code has been tested.
- [x ] All commit messages are properly formatted and commits squashed where appropriate.
- [x ] I have included updates to all appropriate documentation.
=> UI: fix typo

libobs/audio-monitoring/pulse/pulseaudio-output.c
PulseAudio code needs to be called with the PA lock held. This chielfly
fixes multiple races during stream shutdown:
* If the functions are called without the lock held, deferred event
handling races end up with PA infinite looping on the mainloop, or
asserting, or other badness, as the reentrant calls cause data
structure corruption on the PA side.
* If we don't reset our callbacks, PA might call us even after we
request stream disconnection (since the stream actually getting fully
shut down is asynchronous), and then we dereference NULL pointers from
our userdata etc. PA will keep its data structures alive until necessary
via reference counting, but not ours.
The lock around pa_stream_begin_write doesn't result from any issues I
experienced, but it looks correct; PA doesn't say anywhere …
=> linux-pulseaudio: fix race conditions

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Steam now automatically selects the closest available server
Also refer to: https://steamcommunity.com/broadcast/upload
Steam now automatically selects the closest available server. There is no more need for the region selection
Ran a couple successful test broadcasts on Windows 10
=> rtmp-services: Update Steam

CI/full-build-macos.sh
make -j$(nproc)
Moar threads for moar cores
I ran the script once
=> CI: Run make with -j$(nproc)

plugins/mac-virtualcam/src/dal-plugin/OBSDALDevice.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
As suggested by @PatTheMav in #3970, this removes some logging from the DAL plugin that is not really necessary but spams Console.app
The DAL plugin has been logging quite a lot, which was mainly for debugging purposes. This is probably not needed anymore.
Successfully compiled (macOS 11.1, Xcode 12.2)
=> mac-virtualcam: Remove unnecessary logging

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add RTMP ingests for MyFreeCams.com to the list of streaming services.
Broadcasting to MyFreeCams via RTMP is now fully supported.
Each ingest was tested using OBS 26.1.0 on macOS 11 and Windows 10.
=> rtmp-services: Add MyFreeCams

.github/workflows/main.yml
Update the CI to use CEF 4183 on macOS
This lets us use hardware acceleration and texture sharing. It also fixes a crash on Big Sur
fishgl has been run on 10.13, 10.15 11.1 11.2
=> CI: Update macOS to CEF 4183

.gitattributes
This normalizes the line ending of all en-US.ini files.
While developing a new feature for my tool [OBSCrowdinHelper](https://github.com/Vainock/OBSCrowdinHelper), I discovered inconsistencies with the line endings of different files on Crowdin. Some have the endings LF, some CRLF. This was likely the result of using different operating systems for cloning the OBS Studio repository and uploading the source files to Crowdin.
Normally this wouldn't matter, except when reading and parsing the translations and source texts.
If this gets merged, cloning the repository and uploading the en-US.ini files to Crowdin in the future will fix the current inconsistencies on this platform.
/
=> .gitattributes: Normalize en-US.ini

.mailmap, AUTHORS
Updates the git authors to the state of 8ce58b0 (also updates the .mailmap file, see the conversation).
Will show on the about page.
Created with
```
git shortlog -sn --no-merges
```
and removed the commit numbers.
The git authors list hasn't been updated since January 2019, just the translators.
When I asked about this on the discord, Fenrir agreed it might be due to an update.
He noted that last time this was done, some people didn't want to be on there but we concluded that since this information is publicly available, that probably shouldn't be a problem.
I see that this could be debatable though.
Compiled on my machine (macOS Big Sur 11.0.1, Intel) and it showed on the authors list in the about tab.
- …
=> AUTHORS: Update authors from git

libobs/obs-cocoa.m
- Use objective-c message syntax instead of calls to objc_msgSend. The resulting code is much shorter.
- Remove use of deprecated [NSProcessInfo operatingSystem]. It always returns NSMACHOperatingSystem.
- Stop parsing [NSProcessInfo operatingSystemVersionString]. The documentation explicitly says "not for parsing".
It reduces the number of lines of code in the project
Build and run on macOS 10.15
=> libobs: Cleanup uses of objc_msgSend in Objective-C code

plugins/rtmp-services/data/services.json
Updated recommended settings for Piczel.tv service
We now encourage streamers to tune their streams for lower latency
JSON is valid, settings appear to work with OBS
=> rtmp-services: update Piczel.tv recommended

.gitignore
Removes `.DS_Store` from .gitignore once since it's in there twice
`.DS_Store` was in there twice, which is unnecessary.
I know it's not a big thing, but removing it makes the file look better.
macOS 11.1 (20C69), .DS_Store file still exists but isn't shown.
=> .gitignore: Remove duplicated .DS_Store

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
* Temporarily removing the 'supported resolutions' constraint due to #4124.
* Increasing 'max video bitrate' to 10000 kbps.
Tested using a variety of bitrates/framerates/resolutions in macOS & windows.
=> rtmp-services: Update MyFreeCams

plugins/linux-capture/xcompcap-main.cpp
xcompcap was taking locks in the wrong order resulting in deadlocks on
close. If you had an xcompcap properties window open on close it was
nearly 100% deadlock. This ensures locks are taken in the same order as
libobs takes when shutting down.
no one wants obs to hang on shutdown.
Exiting obs with an xcomposite capture properties window open no longer hangs. Capture works normally.
=> linux-capture: Fix lock ordering

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added the new [polystreamer.com](https://polystreamer.com) multi-streaming service to the **services.json** file, and incremented the version number in the accompanying **package.json** file.
PolyStreamer is an new multi-streaming service (like restream or castr), and it'd be awesome if it was a built-in selection in OBS. :+1: 
I validated the JSON, and built OBS and tested streming to the service from the UI dropdown:
=> rtmp-services: Add PolyStreamer service

UI/platform-x11.cpp, UI/window-basic-main.cpp, deps/libcaption/caption/caption.h, deps/libcaption/caption/cea708.h, libobs-opengl/gl-subsystem.c, libobs/obs-audio.c, libobs/util/platform-nix.c, plugins/linux-v4l2/v4l2-output.c, plugins/obs-filters/luma-key-filter.c, plugins/rtmp-services/rtmp-custom.c
Fix various warnings.
Warnings are bad.
Inspected non-trivial changes with debugger in CLion.
=> Another warning clean-up pass

docs/sphinx/reference-libobs-util-threading.rst, libobs/obs-internal.h, libobs/obs-scene.c, libobs/util/threading-posix.h, libobs/util/threading-windows.h
Augmented atomic API with non-returning store functions, and made various implementation improvements.
Mostly OCD, but OBS code is public, so let's set a good example.
Debugger inspection within OBS for most function changes, copy/paste to external project for testing uncalled functions.
=> Various atomic improvements

libobs/obs-win-crash-handler.c
Makes the crashlog a little nicer to read
Adds the thread name to the crashlog.
This makes use of the data stored since PR #2831
=> libobs: Include thread names in thread traces

libobs/util/threading-windows.h
Use native instructions on ARM64 (dmb is slow).
Use magic number for 32-bit ARM since _ARM64_BARRIER_ISH is for ARM64.
Faster is better.
Inspected disassembly using DUMPBIN /DISASM.
=> libobs/util: ARM atomic fixes

libobs/util/threading-windows.h
Use _ARM_BARRIER_ISH for ARM path.
Remove useless conversion in os_atomic_load_bool.
I'm pretty sure these are the last changes I will make to this file.
Debugger inspection.
=> libobs/util: More atomic fixes

plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Previously the save callback would be called when the replay buffer
hotkey was pressed and not when the saving of the replay was finished.
When the 'get_last_replay' procedure was called after the saved callback
function, it would return the incorrect path, as the path would still
be the previous path.
Found bug with https://github.com/obsproject/obs-studio/pull/3953
When saving the replay buffer, the path would be blank and next time it is saved, the path would be the previous path.
Made sure it worked properly with #3953.
=> obs-ffmpeg: Fix replay save callback not working properly

plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
This is a small overhaul of the DAL plugin installation routine in OBS:
* Destination paths turned out to be "stable" so strings are set in code instead of interpolated
* Overzealous users might have deleted the DAL plugin directory itself which lead to unexpected results when DAL plugin is then installed optimistically
* Made logic checks more obvious (Target directory exists? Plugin already installed? Update needed?)
Fixes https://github.com/obsproject/obs-studio/issues/4095.
DAL plugin Installation needs to be handled by an OSAScript code block generated by string composition and benefits from more explicit code and less interpolations.
* Tested locally with missing destination directory, outdated plugin and missing plugin.
=> mac-virtualcam: Handle missing DAL plugin destination directory

libobs/util/threading-windows.h
Unsure if the intrinsics imply ordering. Safer to assume they don't.
Want stable ARM64 builds.
Compiled functions in a separate VS project for ARM64. Not sure what it takes to build OBS for Windows/ARM64, much less actually run.
Verified x64 still compiles and runs though.
=> libobs/util: Compiler barriers for ARM64 atomics

UI/window-basic-main.hpp
This function wasn't removed in #4308.
Forgot to remove function.
No testing needed.
=> UI: Remove UpdateSceneCollection function from header

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-frontend-api.rst
This adds a function and a frontend event
function: `obs_frontend_get_tbar_position()`
returns: `int position`
event `OBS_FRONTEND_EVENT_TBAR_VALUE_CHANGED`
When Trying to code for using the tBar it makes more sense to be able to get the position and be notified when it changes, rather then make assumptions
Linux Ubuntu x64 20.10 
=> UI: Add Frontend API function to get value of T-bar

plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Add missing bounds check, and remove unnecessary cast.
Bug, clean-up.
Debugger inspection, record videos for all paths, Avidemux frame-by-frame, VLC playback.
=> More NVENC alignment

libobs/obs-properties.c
Looking at the code might be easier than reading its description.
Fixes internal `libobs` function `check_property_group_recursion()` used by externally-exposed `obs_properties_add_group()`. This helper recursively checks for occurrences property group recursion. Unfortunately, before this change the return of recursive calls was ignored allowing for recursion on child "nodes".
Bugs are bad. This one is pretty isosteric since `obs_properties_add_group()` is used only by two plugins in ways that (as far as I see) never attempt to create problematic setups.
I **have not** tested this change because I'm not sure how I would go about it. I'm tempted to write a test OBS plugin which just triggers this bug. But I think a proper unit test in `test/` directory would be more useful long-term. …
=> libobs: fix property group check

plugins/rtmp-services/CMakeLists.txt, plugins/rtmp-services/data/services.json, plugins/rtmp-services/rtmp-common.c, plugins/rtmp-services/rtmp-services-main.c, plugins/rtmp-services/service-specific/dacast.c, plugins/rtmp-services/service-specific/dacast.h
Add Dacast streaming service to OBS dropdown options.
Add plugin to get mutable RTMP URL, stream key, username, password, and encoder options from API.
Dacast is a live streaming platform. This change allows users to stream without complicated operations.
I confirmed that it works with the Live server. I checked on Mac and Windows.
Details are shown below.
1. Log in to https://www.dacast.com/
2. Select Live Streams
3. Create Live Stream
4. Add title and select your region
5. Select Encoder Setup
6. Select Generate
7. Copy Encoder Key
8. Open OBS streaming setting
9. Select Dacast service from the dropdown list
10. Paste Encoder Key in the Encoder Key field
11. Start streaming.
=> rtmp-services: Add Dacast

CI/full-build-macos.sh
Quote all bash variables containing paths
The current script will fail if the checkout path contains spaces.
Tested the `ensure_dir` function with arguments containing spaces. `full-build-macos.sh` has not been tested.
=> CI: Quote all bash variables containing paths

UI/window-basic-main.cpp
There is no related issue.
On my vs2019 & WIN10(19041.867), there is a compile error caused by this special character.
But as @RytoEX 's test result in https://github.com/obsproject/obs-studio/pull/4373, this compile error may not reproduce on every one's vs2019.
https://user-images.githubusercontent.com/18413354/111929179-95815f80-8af0-11eb-83f2-6e3f322f8593.png
(Jim note: This is likely due to non-english systems having various different character encodings.)
Remove special character to make sure no compile error.
Compile solution with vs2019 on window10
Code cleanup (non-breaking change which makes code smaller or more readable)
=> UI: Remove special character ('…') to prevent vs2019 compiler error

plugins/win-capture/graphics-hook/gl-capture.c
Previous fix attempted to place swap_recurse count in gl_data struct,
where it could be unexpectedly memset to 0. Separate member from struct,
and make thread-local for additional safety.
The revert commit mentioned Quake Live was broken, but I don't see any new issues. The issues even without the change were:
- Game capture image stuck on front-end after entering game.
- Game flipping vertically on alternating frames when returning to frontend.
- Game becoming completely white if attempted to force hide -> show game capture in OBS to try to reset connection in frontend.
Don't want to copy same game image multiple times.
Debugger inspection in Counter-Strike. Quake Live was buggy, but this PR doesn't seem to add additional regressions. …
=> win-capture: Restore GL capture deduplication

plugins/linux-capture/pipewire.c
De-escalate an assertion in the PipeWire-based capture to a warning, and an attempt to find the correct stream to use.
The assertion did found a bug in the KDE implementation of the Desktop portal. However, it comes with the side effect of exiting OBS Studio in this case, where we can actually make it work (even if buggy).
- Open OBS Studio in KDE
- Add at least two PipeWire captures (can be either monitor or window streams)
- Either everything works, or everything works AND a warning is in the console output
=> linux-capture: De-escalate assertion to a warning

CI/flatpak/com.obsproject.Studio.json
Make the Flatpak CI disable obs-browser, because BUILD_BROWSER if ON by default thanks to #4483 
=> flatpak: Disable obs-browser build

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Updating Mixcloud Service settings to be more compatible
We're seeing a number of users repeatedly using settings which cause problems, so this addresses those and provides better defaults
Followed convention, these are also known best configurations on Mixcloud (I work there and lead that team)
Amending Mixcloud services configuration to be more compatible with our infrastructure
=> rtmp-services: Update Mixcloud

UI/window-basic-transform.cpp, libobs/obs-scene.c
Groups are currently broken with undo/redo. This PR is to resolve those issues. Some issues include transformations done in a group cannot be undone and can cause weird behavior. Another is the edit transforms does not work.
Fix to proper functionality. 
Resolves [this card](https://github.com/orgs/obsproject/projects/4#card-58282723)
I tested it on my linux machine.
=> UI: Fix wrong behavior with undo/redo and groups

plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
This was changed to default on but is not exposed for ffmpeg nvenc.
Where cards without temporal AQ support will fail to initialize and we
cannot do checks beforehand. This exposes the parameter to allow users
to disable this feature when using the ffmpeg implementation.
Someone with a GTX770 couldn't use nvenc on the RC.
I see the setting and can disable it.
=> obs-ffmpeg: Expose psycho-aq setting

.github/workflows/main.yml, CI/full-build-macos.sh
=> CI: Specify arch for prebuilt deps

plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Fixes some memory leaks Xcode has detected
I was chatting with PatTheMav about these a few days ago on discord, hopefully they are fixed now.
Built and run on macOS 11.2.3, everything still works.
I can't confirm whether there was indeed memory leaking since I don't have the tools (or don't know how to use them), but it can't hurt.
=> mac-virtualcam: Fix memory leaks

UI/window-basic-main.hpp
Removes `LoadProfile()` declaration from window-basic-main.hpp.
`LoadProfile()` has no definition and is not referenced in this codebase:
```bash
grep ./obs-studio/ -rniI -e "LoadProfile"
./obs-studio/UI/window-basic-main.hpp:379:	void LoadProfile();
```
Tested in Win 10 & macOS 11.2
=> UI: Delete unimplemented declaration, LoadProfile()

.github/workflows/flatpak.yml
Switch from using the `master` branch of the flatpak-github-actions to the latest tagged release `v3`
To avoid any future breakages as all futures needed such as caching are now part of the latest stable release
It needs the `Seeking Testers` label. Although, nothing changed between the `master` & `v3`. So no breakage is expected.
Code cleanup (non-breaking change which makes code smaller or more readable)
=> CI: use a stable version of the flatpak action

.github/workflows/main.yml, CI/install-dependencies-linux.sh
Removes kernel headers and dkms packages from the CI pipeline. These are
only needed when running obs and not when building. This avoids crashing
and burning in CI when secureboot is enabled. see: https://github.com/obsproject/obs-studio/pull/4560/checks?check_run_id=2403303957
It would be nice for CI to work.
CI.
=> CI: Remove unneeded runtime deps

UI/window-basic-main.cpp
It makes more sense for these to be in the ClearSceneData function.
Clearing of sources in a single function.
Compiled and ran to make sure nothing broke.
=> UI: Move clearing of copy/paste variables

README.rst
Replaces the official Discord Badge with one from shields.io, which is higher DIP compared to the official one.
The current badge looks kind of out of place:
I think this looks way better: 
Looked at the README on GitHub
- Documentation (a change to documentation pages) (I guess?)
=> README.rst: Use High DPI Discord Badge

CONTRIBUTING.rst, README.rst
Removes the indents that cause the text to be interpreted as block quotes.
The block quotes looked like they are unintentional.
Imho this looks better.
Committed and checked that the quotes are gone
=> docs: Remove block quotes

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp, plugins/rtmp-services/data/services.json
This RMTP update is to add Odysee on the rmtp services list.
Some Odyseenauts are not fixing the 2500kpbs bitrate issue, so I've added the recommended settings on this code.
This is tested using Manjaro on my Lenovo Laptop. And it is flawless.
Added RMTP services
=> rtmp-services: add Odysee.com

cmake/Modules/FindJack.cmake
Fix the `FindJack.cmake` file to support finding PipeWire's libjack implementation.
With Linux distributions that have all audio go through PipeWire, we want to be able to use the PipeWire version of libjack, even though the library is installed to a non-standard path.
In particular, this impacts Fedora Linux, which is the first distribution to have made this change.
Reference: https://fedoraproject.org/wiki/Changes/DefaultPipeWire
Added this change and built the package for Fedora 33 (with `jack-audio-connection-kit-devel`) and Fedora 34 (with `pipewire-jack-audio-connection-kit-devel`). OBS Studio worked as expected in either case.
=> cmake: Fix FindJack to support finding PipeWire's libjack

plugins/obs-filters/noise-suppress-filter.c
If the NVAFX SDK is installed, test at obs-filters load time to see if the NVAFX denoiser is actually supported by the GPU.
Prevents user confusion when they install the SDK on an unsupported GPU and the NVIDIA Noise Reduction becomes available but is non-functional (with no UI feedback that this is the case).
Tested on both supported and unsupported GPUs. Adds about 10-20ms to startup time.
=> Test if NVAFX denoiser is supported when loading obs-filters

libobs/graphics/graphics-ffmpeg.c
Should fix regression for 16-bit PNGs.
Fixes #4787.
Regressions are bad.
Test image is back to normal. All three branches debugger inspected to behave as intended.
=> libobs: Assume sRGB instead of linear for 64 bpp

plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
For new NVENC, warn if PVT is requested, but unsupported by the GPU.
For old NVENC, if PVT is enabled when FFmpeg failure occurs, retry
without PVT.
NVENC failure is a bad user experience.
Breakpoint inspection. I don't actually have a failing card, so it would be good to have someone else verify that.
EDIT: Flaeri says it works.
=> obs-ffmpeg: Support lack of Psycho Visual Tuning

plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Only use lossless encode if the capability is supported.
Set qpPrimeYZeroTransformBypassFlag to 1 for lossless.
Do not set profileGUID for lossless.
For both NVENC implementations, retry with a heavier reset because both
are unable to recover from failure lightly.
Earlier attempt to retry on failure result in bad encoding settings.
Breakpoint inspection of PVT toggled on/off, and debugger inspection of NVENC initialization parameters for both implementations.
=> obs-ffmpeg: NVENC usage fixes

UI/installer/mp-installer.nsi
During the installation process, silently installs the Visual C++ redistributables if they are not already installed.
Requires redistributables in the install build directory.
**Important note:** this implementation would require the installer itself ship with the Visual C++ redistributable EXE. If it's decided that we'd rather not ship these and instead download them from the web behind the scenes (or with user confirmation), this can be achieved using the [Inetc plugin](https://nsis.sourceforge.io/Inetc_plug-in) for NSIS and the following change:
```diff
vs2019Missing_64:
-		File VC_redist.x64.exe
+		inetc::get /SILENT https://cdn-fastly.obsproject.com/downloads/VC_redist.x64.exe "$PLUGINSDIR\VC_redist.x64.exe" /END
ExecWait '"$PLUGINSDIR\VC_redist.x64.exe" /quiet /norestart'
```
The …
=> UI/installer: Silently install Visual C++ Redistributables

plugins/mac-capture/mac-display-capture.m
- Display names for captured displays should render human readable when selecting the source
- This works on other platforms already 
- Tested on M1 MBP and x86 MBP, macOS 11.3
=> mac-capture: Update display names to be human readable

libobs/obs-audio.c, libobs/obs-internal.h, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-filters/noise-suppress-filter.c
Fix various minor warnings.
Debugger inspection of all changes.
=> Warnings 2021-07-06

UI/window-basic-auto-config.cpp, UI/window-basic-settings-stream.cpp, plugins/rtmp-services/data/services.json, plugins/rtmp-services/rtmp-common.c
Move service stream key link strings from UI code to `plugins/rtmp-services/data/services.json`.  Add a mechanism to fetch this value from services.json.  Replace service specific code in UI for a service's stream key link with generic code.
Note:  I do not know if the additions to services.json require changing the format_version or if this is considered a breaking change.  Please let me know if format_version needs changed.
Having these service-specific strings hard-coded in the UI code means that if one of the URLs needs to be changed, we need to release a full OBS release to deliver that change.  Moving them into services.json means we can push an update to services.json, which can happen independently of an OBS release.  This makes updating these URLs easier.
This also allows us to …
=> Move stream key link to services.json

UI/auth-youtube.cpp, UI/auth-youtube.hpp, UI/window-youtube-actions.cpp
Adds a chat dock for YouTube, since the youtube chat URL is not static it is added as a placeholder until a broadcast is started.
As we cannot login in CEF (Google *sometimes* blocks that) the chat input is hidden via custom CSS.
Pre-broadcast placeholder:
Chat after starting broadcast:
People want chat.
Started streams, ended streams, had streams locked to private by youtube claiming their team looked at it when in reality some third-rate machine learning algorithm just doesn't like black screens with no sound.
=> UI: Add YouTube Chat Dock

deps/obs-scripting/obs-scripting-lua-source.c, deps/obs-scripting/obs-scripting-lua.c, deps/obs-scripting/obs-scripting-python.c, libobs/CMakeLists.txt, libobs/callback/signal.c, libobs/media-io/audio-io.c, libobs/media-io/video-io.c, libobs/obs-encoder.c, libobs/obs-scene.c, libobs/obs-source.c, libobs/obs.c, libobs/util/config-file.c, libobs/util/profiler.c, libobs/util/threading.h, plugins/obs-filters/noise-suppress-filter.c, plugins/obs-filters/obs-filters.c
Fix leaks identified with Visual Studio.
Leaks are bad.
Debugger inspection for all diffs.
=> Fix a bunch of pthread leaks

libobs/util/threading-windows.c
Fix warning about potential passing of NULL to FreeLibrary, and switch
from Kernel32.dll to KernelBase.dll based on MS documentation.
Don't like warnings and I noticed the DLL issue from browsing the doc.
Verified KernelBase.dll works on 21H1. Code snippet changes thread name in VS debugger (when the preceding legacy name setter is commented out.)
=> libobs/util: Improve SetThreadDescription usage

UI/data/locale/en-US.ini, UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/forms/OBSYoutubeActions.ui, UI/remote-text.cpp, UI/remote-text.hpp, UI/window-youtube-actions.cpp, UI/window-youtube-actions.hpp, UI/youtube-api-wrappers.cpp, UI/youtube-api-wrappers.hpp, cmake/Modules/CopyMSVCBins.cmake
Adds ability to upload thumbnails directly from within OBS.
Requested feature.
Uploaded thumbnails.
=> UI: Add Thumbnail uploading to YouTube integration

docs/sphinx/reference-frontend-api.rst
PR https://github.com/obsproject/obs-studio/pull/2053 didn't update the OBS Studio Frontend API `obs_frontend_event` list to mention the `OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED` event that was added, which made it a bit difficult to find. So I've added it 😉 
What types of changes does your PR introduce? Uncomment all that apply
=> docs: Add transition duration changed event

libobs/util/platform-nix-portal.c
Make the portal inhibitor asynchronous, by using g_dbus_connection_call() instead of g_dbus_connection_call_sync(). If an uninhibit call is made before the previous inhibit call finishes, cancel the inhibit call instead.
Currently, libobs contains two inhibitors: the portal-based one, and the regular one based on each desktop environment's session manager. The portal inhibitor takes precedence over the session manager one, when available.
Like the session manager inhibitor, the portal inhibitor performs all D-Bus calls synchronously in the calling thread, which can lead to stalls. This is not a good practice.
Fixes obsproject/obs-studio#5314
- Run `dbus-monitor` in a separate terminal
- Open OBS and start and stop recording / streaming
- Notice that the screen is inhibited and uninhibited …
=> libobs: Make portal inhibitor asynchronous

cmake/Modules/FindLibdrm.cmake, plugins/linux-capture/CMakeLists.txt
We require libdrm for its header so add the cmake module and header path
to the build. We don't need to link libdrm though so we dont add it to
libraries.
Some users might fail to build due to missing deps if they dont have this library installed. See #5325
Compiles and checks the module on my machine.
=> linux-capture: Add libdrm dependency check

plugins/linux-capture/CMakeLists.txt
I forgot to extend the FATAL_ERROR messages to include libdrm.
The build should fail like it does with the other required components. Also take the time to re-add the quiet that I failed to commit in my last commit.
Ruining my filesystem worked to fail the build.
=> linux-capture: Fail when libdrm missing

UI/window-basic-auto-config.cpp
This change removes the disabling of auto-config bandiwdth testing for youtube, as the test pattern does no longer get your account flagged (previously it would result in a community guidelines strike).
It also removed the recursive call that would cause YouTube API request to be executed twice once the bandwidth testing was enabled again.
Makes code a little cleaner, avoid unnecessary API requests.
Made sure stuff still works.
=> UI: Do not disable AutoConf bandwidth test for YouTube

libobs-opengl/gl-stagesurf.c
Previously glReadPixels was used to stage surface because Mac had annoying problem.
However, recent MacOS can stage surface as same as Linux code.
This commit removes a switch by __APPLE__ to use glReadPixels.
The motivation of the PR is to improve a plugin [OBS Color Monitor](https://github.com/norihiro/obs-color-monitor), which uses the API `gs_stage_texture`. It is reported the plugin is slower in macOS on [a forum post](https://obsproject.com/forum/threads/obs-color-monitor.143375/#post-527166). The plugin needs to bring textures from GPU to process in CPU to monitor the color information after color correct filters are applied.
The PR should be beneficial for the other plugin [Source Record](https://github.com/exeldro/obs-source-record), which calls the API `gs_stage_texture` as …
=> libobs-opengl: Use PBO for macOS device_stage_texture as same as Linux

UI/window-basic-filters.cpp
Small fixes to the filters window, making sure the correct lists are focused. 
First commit fixes #4764, second commit a bug I discovered while working on the first commit (not introduced by it), see commit message for details.
macOS 12.0 beta 5, compiled and run.
Issues described in the bug report are fixed.
=> UI: Filter Menu fixes

.github/workflows/main.yml
This PR removes `composer` in macOS build host. [Composer](https://getcomposer.org/) is a dependency manager for PHP, which is not necessary for OBS Studio's build flow.
macOS 64-bit build fails when removing curl and php by brew.
Error message is as below.
```
Error: Refusing to uninstall /usr/local/Cellar/curl/7.79.1_1 and /usr/local/Cellar/php/8.0.12
because they are required by composer, which is currently installed.
You can override this and force removal with:
brew uninstall --ignore-dependencies curl php
Error: Process completed with exit code 1.
```
Checked the build flow passed.
=> CI: Fix error when uninstalling curl and php

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add [Kuaishou Live](https://live.kuaishou.com/) to rtmp services list.
A live streaming platform in China mainland.
Add support for "Kuaishou Live" in rtmp services.
* New feature (non-breaking change which adds functionality)
=> rtmp-services: Add Kuaishou live

plugins/obs-ffmpeg/obs-ffmpeg-mux.c
The commit 4a5ac3974 fixed the bug the first PTS is not zero. This commit fixed the same issue in replay-buffer.
A variable `video_dts_offset` is renamed to `video_pts_offset` and the variable is initialized by `pts` instead of `dts`.
Fix #5475
Though FFmpeg has further different implementation, the change of this PR follows the implementation of the commit 4a5ac3974, which fixed the same issue on normal recording. FFmpeg `libavformat/segment.c` uses just one offset calculated from the first PTS of video. Accuiring `start_pts` at the key-frame of the video.
```
seg->cur_entry.start_pts = av_rescale_q(pkt->pts, st->time_base, AV_TIME_BASE_Q);
```
Then, rescale the offset for each stream and subtract it from PTS and DTS.
```
offset = av_rescale_q(seg->initial_offset - (seg->reset_timestamps …
```
=> obs-ffmpeg: Fix starting video packet offset in replay-buffer

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add rtmp-service for Utreon
Add rtmp-service for Utreon ;-)
Manually applied the json entry to my local installation.
=> rtmp-services: add Utreon

plugins/linux-v4l2/v4l2-output.c
For Linux virtual camera output.
Don't blindly try all `/dev/video<0-63>` devices if they exist and can be opened, but instead scan
`/dev/` directory and try to open all `/dev/videoX` devices that are present in the tree.
Sorting of the tree is done with GLIBC's `versionsort` extension. So that `/dev/video9` is tried
before `/dev/video10`.
Trying to fix #4347.
```shell
$ rmmod v4l2loopback
$ modprobe v4l2loopback video_nr=100
$ obs
```
Starting OBS virtual camera then correctly opens `/dev/video100`
=> linux-v4l2: Change search strategy for v4l2loopback devices

UI/CMakeLists.txt
This fixes #2222 by ensuring python symbols are in the global symbol
table through a direct linkage to the executable. When python is
normally linked via frontend-tools.so its symbols are not global since
we dlopen frontend-tools.so. This causes issues for native python
modules which stopped directly linking python around 3.8 as the symbols
will not resolve.
This is pretty much a hack, but it minimizes the number of extra symbols
we add and hopefully isnt too terrible to maintain.
Making python users happy is a good thing.
Running python 3.9 the url-text.py script no longer works with the same issues as #2222. With this fix it works again. The 2222 script with a plain import also works.
Hopefully it doesnt explode on windows/mac if someone could test there that would be great.
- Bug fix …
=> UI: Link python when obs-scripting python is enabled

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add Manyvids to rtmp services list
Manyvids.com starts to provide static rtmp URL. To facilitate our users, we want to add Manyvids to the rtmp service list. 
Local build
=> rtmp-services: Add Manyvids.com

docs/sphinx/reference-scenes.rst
Adds documentation for `obs_group_or_scene_from_source`
Function was added in 6b2c3f4, but documentation is missing.
Docs generated with CI.
=> docs: Document obs_group_or_scene_from_source

UI/importers/sl.cpp
Add support for importing the Screen Capture source type from Streamlabs scene collections. Since the Screen Capture source type is essentially an abstraction layer for Display Capture, Game Capture, and Window Capture, this adds some translation logic to translate Screen Capture sources into one of those source types.
Caveat:  since the target of the game capture subtype does not seem to be exposed, this does not specify a target process for that source.
That said, this should still be an improvement over failing to create a suitable source at all.
We should support imports for as many source types as possible.
I've tested this with all three subtypes (Display, Game, Window) on my Windows 10 machine.  Could use additional testing for machines with multiple displays.
- Bug fix …
=> UI: Import Streamlabs Screen Capture source type

CONTRIBUTING.rst
Adds link to service submission guidelines to the contributing document.
We want the requirements and options available to service operators that wish to submit their service for inclusion in OBS to be more clear and more easily findable.
Made sure formatting is correct
- [N/A] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [N/A] The code has been tested.
=> CONTRIBUTING.rst: Add service submission guidelines

docs/sphinx/reference-frontend-api.rst, docs/sphinx/reference-libobs-util-config-file.rst, docs/sphinx/reference-scenes.rst, docs/sphinx/reference-sources.rst
Modifies various docs pages to add missing functions and improve the readability.
I've been collecting a list of docs issues as I've been working on obs-websocket, decided to put the time into applying fixes.
Not tested
=> Docs: Many improvements

UI/auth-twitch.cpp, UI/obs-app.cpp, UI/obs-app.hpp
Check if the current OBS theme is "Dark Mode"-esque and use that to determine if the Twitch browser panel docks should use Twitch's Dark Mode or not.
Making Twitch-based docks respect whether the current OBS theme is dark makes a more consistent UI/UX.  Requested here:  https://ideas.obsproject.com/posts/1616/
I've tested this locally.  Currently, you need to restart OBS if you change the theme.  You then need to refresh the docks, either by using the context menu (right-click menu), or by closing and reopening the docks to get the change to take effect.  We're looking into a way to fix those issues.
=> UI: Set Twitch Panel Dark Mode using OBS theme

docs/sphinx/reference-core.rst, libobs/obs.c, libobs/obs.h
This complements the already existing raw video callback function.
Parity with the video callback.
Created audio callback when testing some custom code.
=> libobs: Add raw audio callback function

.github/workflows/flatpak.yml, .gitignore
Publish GitHub releases of OBS Studio directly into Flathub and Flathub Beta. All releases are published to Flathub Beta, and only stable releases are published to Flathub.
Currently the only Linux distribution officially supported by the OBS Studio community is Ubuntu, through the community PPA. We've been slowly growing support for Flatpaks, which covers support for a lot more distros beyond Ubuntu. Since https://github.com/obsproject/obs-studio/pull/4994 the Flatpak builds achieved complete feature parity with regular builds.
This is the last big step in the Flatpak front: publish GitHub releases directly into Flathub.
[Flathub already has a separate repository for OBS Studio](github.com/flathub/com.obsproject.Studio/), and I've been manually publishing releases there, but it doesn't …
=> Publish to Flathub

plugins/linux-capture/pipewire.c
Add version checks for PipeWire components to en- and disable features on specific combinations.
This solves compatibility issues with different PipeWire versions between host and flatpak.
Build flatpak and run it on Debian. OBS should fallback to SHM transport.
=> linux-capture: Fallback to SHM on older PipeWire versions

plugins/obs-ffmpeg/obs-ffmpeg-mux.c
This PR adds two changes for the case if an internal failure occurs during saving the replay buffer.
- Release contents of array `mux_packets` before releasing the array itself.
- Set `muxing` = false if `pthread_create` failed.
When releasing a darray mux_packets at error, contents of mux_packets are not released. It causes memory leaks if error occurs during saving the replay buffer to a file.
I think the failure will rarely occur but noticed it when reviewing the code for the implementation of #5371.
1. Modify `replay_buffer_save` to simulate failure of `pthread_create`.
2. Configure to use replay buffer.
3. Click `Start Replay Buffer`.
4. Click `Save Replay`.
5. Check number of memory leaks in the log file.
To simulate the failure of `pthread_create`, I modify the code like below. …
=> obs-ffmpeg: Fix memory leaks if replay buffer failed

plugins/aja/CMakeLists.txt
Add .rc files for metadata on the AJA plugin DLLs
Windows DLL files should have metadata
Compiled on CI
=> aja: .rc file for the aja plugin

UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Set donation, bugtracker, and translate AppData fields.
These are more fields that app stores such as GNOME Software and Discover show. Nothing fancy, but the more information we provide, the better it looks!
- Install this branch
- Open OBS Studio's details page in any Linux app center like GNOME Software or KDE's Discover
- Observe that the app center shows these fields
=> Set donation, bugtracker, and translate AppData fields

docs/sphinx/reference-sources.rst
Add missing source output flags to the documentation
missing
-
=> docs: add missing source output flags

plugins/linux-capture/xcompcap-main.cpp
The GLX_EXT_texture_from_pixmap spec says:
> The contents of the texture after the drawable has been bound are defined
> as the result of all rendering that has completed before the call to
> glXBindTexImageEXT.  In other words, the results of any operation which
> has caused damage on the drawable prior to the glXBindTexImageEXT call
> will be represented in the texture.
> 
> Rendering to the drawable while it is bound to a texture will leave the
> contents of the texture in an undefined state.  However, no
> synchronization between rendering and texturing is done by GLX.  It is
> the application's responsibility to implement any synchronization
> required.
In practice, on most systems with a GPU this kept a directly binding to
the framebuffer, which made it work with the previous code. …
=> XComposite: Fix capturing on software rasterization setups

UI/window-basic-source-select.cpp
Adds an undo/redo action for the "Add existing source", which previously
was missing.
Overall mimics the behaviour of the undo/redo, including the scene-switching to the scene that is affected when undo/redo-ing).
Fixes #5091 
macOS 12 beta 5, compiled and run
Undo/Redo works, on redo the source reappears on the correct scene.
=> UI: Add undo/redo for "Add existing source"

CI/full-build-macos.sh
The missing Pull Request to adapt the fixes made by @DDRBoxman on CI to get OBS building again with the updated dependencies.
Fix creation of application bundle on macOS via the provided build script.
* OBS build successfully on macOS 12 with provided script.
=> CI: Fix build issues introduced by updated obs-deps

.github/workflows/main.yml
Use the Windows obs-deps release on CI instead of the current dependencies2019.zip.
Let's us distribute test builds via CI and eventually use obs-deps for all CI builds.
While I have been testing these locally, we'd like to make testing more easily available to a wider audience.
=> CI: Use Windows obs-deps release

docs/sphinx/reference-core.rst
Adds documentation for obs_get_scene_by_name.
It's a helper function in obs.h (introduced in 09ffab6)  but nevertheless should get documented.
Missing documentation = bad
Generated on CI.
=> docs: Document obs_get_scene_by_name

UI/window-basic-main.cpp
Cleans up an unused statement which introduced an unneeded variable.
Less code in window-basic-main is always a good thing :p
No seriously, I just stumbled across it while working on something else.
Still compiles (macOS 12.0.1).
=> UI: Remove unneeded call when removing scene

plugins/obs-outputs/rtmp-stream.c
From Windows 7 onwards, dynamic send buffering is enabled, which automatically sets an appropriate send buffer size based on network conditions. By explicitly setting SO_SNDBUF to 64k during connection setup, we actually _disable_ dynamic send buffering which can result in reduced throughput. Thankfully I don't think this affects the majority of users since the default send buffer is usually 64k already.
This PR replaces the setting of SO_SNDBUF with log output showing the current value of SO_SNDBUF at stream start and end (assuming a clean disconnect). This will aid in debugging throughput issues caused by a buffer that isn't big enough, perhaps as a result of the user disabling dynamic send buffering system-wide.
The dynamic send buffering is essentially the same behavior as "enable …
=> Stop setting SO_SNDBUF and instead log the initial and final values

UI/CMakeLists.txt
If OBS is built with YT integration but without obs-browser, the build will fail which is an issue.
Build output with the issue from Tarulia on discord:
```
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/ccglBK1Q.ltrans2.ltrans.o: in function `YoutubeAuth::Login(QWidget*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text+0x9dd1): undefined reference to `deobfuscate_str'
/usr/bin/ld: <artificial>:(.text+0x9de7): undefined reference to `deobfuscate_str'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 194480
/tmp/ccglBK1Q.ltrans3.ltrans.o: in function `YoutubeApiWrappers::InsertCommand(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, …
```
=> UI: Fix build with YT integration without browser

docs/sphinx/reference-frontend-api.rst
Corrects the documentation for `obs_frontend_get_current_preview_scene` and
`obs_frontend_set_current_preview_scene`. While the behaviour described before
is likely the desired one, the frontend API wouldn't behave like that (and looking at
git blame, it never did).
https://github.com/obsproject/obs-studio/blob/47397ce527ab11fcab70dfc14f6e1641d93785fc/UI/api-interface.cpp#L551-L572
If we at some point decide to break everything, this behaviour should get fixed as
well. For now, changing how it behaves would be a breaking change for no real
reason, so it's better to just fix the docs.
I found out the hard way, wondering why the scene could be null.
Built docs on CI:
=> docs: Fix frontend API docs for preview_scene functions

UI/slider-ignorewheel.cpp
Removes an unneeded include in slider-ignorewheel.cpp
Makes it possible to copy-and-paste the classes in the file (for example for use in an external plugin) without modifying it or also having to copy `volume-control.hpp` which is part of (and highly integrated with) core OBS.
The include wasn't used anyways, so it can be cleaned up.
macOS 12.0.1, still compiles and runs.
=> UI: Remove unneeded include

UI/window-basic-main.cpp
Fixes an issue where the `UpdateEditMenu` wouldn't respect that sources
can't be duplicated.
Fixes a draft issue which apparently can't be referenced by a link (thanks GitHub!)
macOS 12.0.1, compiled and run
If one of the copied sources can't be duplicated, the "Paste (Duplicate)" field
is disabled, otherwise enabled.
=> UI: Correctly disable "Paste Duplicate" if required

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Fixes copy/paste transform not working anymore.
Also fixes the Edit menu having things enabled that shouldn't be enabled,
like "Edit Transform" while multiple items are selected (or like "Copy Transform"
being enabled when multiple items are selected, this is why these changes
are in one PR, the second commit depends on changes made in the first).
27.2 issue report
Copy/Paste transform works again.
"Edit Transform", "Copy Transform" and "Copy Filters" are no longer available if
multiple source are selected.
=> UI: Reenable copy/paste transform & Correctly enable edit menu items with multiple sources

CI/flatpak/com.obsproject.Studio.json
The Flatpak actually bundle the v2.1 branch of LuaJIT not a specific commit hash. And each time that a beta and stable bundle is released. It could potentially contain a different version LuaJIT.
Put LuaJIT dependency in sync between macOS and Flatpak.
Note: 2.1 was preferred when I asked on discord.
=> Flatpak: Use same commit hash for LuaJIT 2.1 as macOS

UI/window-basic-main.cpp, UI/window-basic-settings.cpp
Previously, when changing the General > System Tray > Enable toggle, even though the Apply button would be enabled, nothing would happen when it was pressed. You would need to choose OK or Cancel to actually cause the tray icon to appear/disappear in the taskbar. With this change, it now updates when you press Apply.
Demo:
I was looking at Issue #2162 and xcasxcursex noted in a comment that Apply wasn't enough to update the tray icon. I didn't see an open issue for this problem specifically.
Tested on Windows 10 (19043.1415).
1. Toggled tray on, clicked Apply, verified tray icon appeared.
2. Toggled tray off, clicked Apply, verified tray icon disappeared.
3. Toggled tray icon on, clicked OK, verified tray icon appeared.
4. Toggled tray icon off, clicked OK, verified tray icon disappeared. …
=> UI: Immediately apply tray icon change on Apply

plugins/linux-capture/xcompcap-main.cpp
NVIDIA drivers appears to have a bug where binding would be excessively
slow. Apply a workaround similar to what [KWin] does to prevent the issue.
Also performs a refactor so that the code paths with and without the
workaround can be shared.
[KWin]: https://github.com/KDE/kwin/blob/4f2c3a00c4a86c08321e80d601fecd09d0871c79/src/libkwineffects/kwinglplatform.cpp
Fixes: 316f858c6 ("linux-capture: Fix capturing on software rasterization setups")
Closes: https://github.com/obsproject/obs-studio/issues/5685
Tested-By: univrsal <uni@vrsal.xyz>
- N/A I have included updates to all appropriate documentation.
=> linux-capture: Disable strict binding for NVIDIA drivers

plugins/obs-ffmpeg/data/locale/en-US.ini
Adds a locale that was referenced in code, but not added to the locale file ("FFmpegOpts", now "FFmpeg Options").
This is not intended:
Compiled and run (macOS 12.1), see above ^
=> obs-ffmpeg: Add missing "FFmpegOpts" locale

libobs-d3d11/d3d11-subsystem.cpp
May be useful for setting display range metadata.
Also span info across multiple lines. Single line had become too long.
HDR future.
Sample:
```
output 0:
name=ROG PG259QNR
pos={0, 0}
size={1920, 1080}
attached=true
refresh=60
space=RGB_FULL_G2084_NONE_P2020
sdr_white_nits=240
nit_range=[min=0.098400, max=400.000000, max_full_frame=351.276398]
```
Nit range still exists if display is SDR.
=> libobs-d3d11: Log display nit range

libobs/obs-properties.c, libobs/obs-properties.h
`obs_property_text_monospace` return a boolean but is declared to return a `obs_text_type`.
Fix a mismatch
It builds and still works with this change.
=> libobs: Fix type mismatch on obs_property_text_monospace

plugins/aja/main.cpp
Remove some debug logs that weren't useful for Aja 
Cleaning up un-needed logs.
=> aja: Remove inter-plugin debug logging

plugins/obs-ffmpeg/obs-ffmpeg.c
Add MX450 to blacklist
Nvenc no worky.
It hasn't. But probably doesn't need to be.
=> obs-ffmpeg: Add MX450 to blacklist

CI/flatpak/com.obsproject.Studio.json
This allows Linux accessibility tools such as the Orca screen reader to be used with OBS.
Without this change, it is not possible to use the Orca screen reader to get speech and braille feedback from the OBS beta flatpak.
1. I added the flathub-beta flatpak repository to my local flatpak installation.
2. I installed com.obsproject.Studio from the flathub-beta repository using the flatpak command-line utuility.
3. I enabled the Orca screen reader using the Super + Alt + S shortcut key.
4. I searched for and ran OBS from the activities overiew in my GNOME desktop session.
5. OBS loaded and ran, but when attempting to navigate the initial configuration wizard, I did not hear anything spoken with text to speech from Orca. I exited the wizard, but still did not hear anything.
6. After making …
=> flatpak: Enable communication with org.a11y.Bus

CI/flatpak/com.obsproject.Studio.json
Like https://github.com/obsproject/obs-deps/pull/90.
Update the libaom and SVT-AV1 versions and also apply several
cherry-picked commits to FFmpeg for SVT-AV1.
Feature parity
Building it on my machine and in the CI.
- CI changes
=> flatpak: Update libaom and SVT-AV1

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
This PR updates YouNow ingest server address
Updates in YouNow infrastructure (old server address will be phased out)
Tested streaming from a local machine (macOS 12.2) with the updated package.json and services.json files
=> rtmp-services: Update YouNow ingest

UI/data/locale/en-US.ini
The operating system is called "Chrome OS" (sometimes also "chromeOS", but that
is used mostly in pictures), not "ChromeOS". OBS should correctly use that name.
When going through Crowdin to find out why the German translation of
"ChromeOS container" changed from "ChromeOS-Container" to
"Chrome-OS-Container" (the latter actually being more wrong than
the former), I looked at how it actually should be, noticing the English
locale was wrong as well.
Btw, the correct German translation for the new locale is "Chrome OS-Container"
N/A, just a locale change
// see above - [ ] The code has been tested.
=> UI: Correctly style "Chrome OS"

plugins/obs-ffmpeg/obs-ffmpeg-source.c
This fixes crashes in Media Source when :
- the user forgets to set the input format for srt or rist URLs;
- disabling / enabling / disabling etc Media source with a rist URL when the restart_on_activate setting is set to true.
The said setting is therefore set to false for rist URLs.
Tested by playing srt or rist streams in Media Source.
They play fine even if the 'input format field is empty.
Rist streams also play fine when one disables/re-enables the source.
=> obs-ffmpeg: Force mpegts & disable restart on activate for srt/rist

.github/workflows/main.yml
Commit 7a5bffc0a66980113c32dbed123b3928d38abe8b (PR #5986) applied a fix to the macOS build script. This applies the same fix to the GitHub Actions workflow that is actually currently used on CI.
Fixes #6002.
Broken CI builds are bad.
I haven't tested this.  CI is the test.
=> CI: Update workflow to copy SOVERSION symlinks

plugins/obs-ffmpeg/external/dynlink_cuda.h, plugins/obs-ffmpeg/external/nvEncodeAPI.h
Update the in-tree nv-codec-header files (nvEncodeAPI.h and dynlink_cuda.h) to n11.1.5.1, which is the version currently used in the OBS Studio dependencies, to keep the in-tree version in sync with the version in our dependencies.
Keep dependency files in sync.
Compiled OBS in VS2019 on Windows 10.  Recorded with NVENC (jim-nvenc).  Resulting file looked fine.
=> obs-ffmpeg: Update nv-codec-header files

UI/forms/OBSBasic.ui
Adds shortcuts for Copy/Paste Transform.
I propose `Ctrl + Alt + C/V` (`Cmd + Alt/Option + C/V` on Mac) which were mentioned before in (informal) internal discussions as a potential shortcut for this, and I think it make the most sense.
This has come up from time to time, more so now that with 27.2 copying a source no longer separately copies its transform (which was incorrect behaviour, but used in some people's workflows).
Closes #6035.
macOS 12.3 Beta 4, compiled and run.
They get correctly added to their menus in the Edit menu (see screenshot above), and pressing them executes their respective functions (if the menu is enabled).
=> UI: Add shortcuts for Copy/Paste Transform

UI/window-basic-main-dropfiles.cpp
Resolve .url, .lnk files on Windows when dragged onto the main window.
Suggested here: https://ideas.obsproject.com/posts/1636
Tested on Windows 10 by dragging different types of files onto the main Window.
Tweak
=> UI: resolve .url, .lnk shortcuts during drag-and-drop

plugins/obs-ffmpeg/obs-ffmpeg.c
Adds the NVENC blacklist that is present for Windows also to Linux (it filters out known GPUS without actual NVENC support).
That brings Linux on par when interpreting the `NVENC supported` message in the log (the log entry will not show up if only unsupported GPUs are in the system).
(Or this check has been missing on purpose and I feel stupid)
I'm currently using Debian with an AMD GPU. So real world test is not done! That's also why the tested tick further down is missing. This should really get the `seeking-testers` label. What I did locally for testing is to disable the FFMPEG check whether nvenc support was enabled (Debian does not enable this flag). And changed the vendor id to the AMD/ATI one to see whether code gits the relevant sections.
But yeah, please someone give this a go …
=> obs-ffmpeg: add NVENC blacklist check for Linux

libobs-d3d11/d3d11-subsystem.cpp
We'll need flip model swap chains in the future for HDR, and we don't
want to limit HDR to WIndows 11. The new test is the existence of
IDXGIFactory5, which was introduced in Windows 10 1607. This should be
enough for HDR, for which we use APIs in Windows 10 1703.
Hopefully having SetMaximumFrameLatency(40) this time will make enough
of a difference to not bring back reports of degraded performance when
using flip model on Windows 10.
Want HDR to work.
Verified expected swap chain desc, and no regression on Windows 11.
Verified expected swap chain desc, and OBS seems to work on Windows 10 20H2 in Hyper-V.
=> libobs-d3d11: Relax minimum Windows for flip model

.github/workflows/qt-xml.yml
libxml2-utils updated recently but the manifest is out-of-date. Try to fix it with the suggestion of running apt-get update first.
Broken CI is bad. Admittedly, this _shouldn't_ be required 99% of the time, but CI is failing right now and this can fix it.
The PR is the test.
=> CI: Fix Qt XML Validator workflow

.github/workflows/main.yml
Provide some clarity on the GitHub Actions artifacts list.
The current artifact name pattern doesn't make it clear what the Flatpak bundle is.
The PR is the test. Requesting a review from @GeorgesStavracas to make sure this makes sense in terms of Flatpak bundle/naming expectations.
=> CI: Add 'flatpak' to Flatpak bundle name

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
1. Changes in  services.json file :
{
"name": "Shareplay.tv",            
"more_info_link": "https://shareplay.tv",
"servers": [
{
"name": "Default",
"url": "rtmp://shareplay.tv:833/live"
}
],
"recommended": {
"keyint": 2,
"profile": "main",
"supported resolutions": [
"1920x1080",
"1280x720",
"852x480",
"640x360"
],
"bitrate matrix": [
{
"res": "640x360",
"fps": 30,
"max bitrate": 1000
},
{
"res": "640x360",
"fps": 60,
"max bitrate": 1500
},
{
"res": "852x480",
"fps": 30,
"max bitrate": 2000
},
{
"res": "852x480",
"fps": 60,
"max bitrate": 3000
},
{
"res": "1280x720",
"fps": 30,
"max bitrate": 4000
},
{
"res": "1280x720",
"fps": 60,
"max bitrate": 6000
},
{
"res": "1920x1080",
"fps": 30,
"max bitrate": 6000
},
{
"res": "1920x1080",
"fps": 60,
"max bitrate": 9000
}
],
"max fps": 60,
"max …
=> rtmp-services: Add Shareplay TV

.github/workflows/main.yml
Use the entries in the matrix.ubuntu property to differentiate the Linux CI artifacts. This allows us to have separate artifacts for each job configuration created by the matrix.
This PR only changes the name of the artifact entry in the list of artifacts. I did not change the local filename of the .deb files from the build. That could be addressed in a separate PR if it makes sense to do so.
See above.
The PR is the test.
=> CI: Differentiate Linux CI artifact names

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
I have replaced service provider name Shareplay.tv to SharePlay.
I have changed in the following file.
1.  Services.json  
2.  package.json
Request for replacing service provider name
I have test in my local system using obs-studio
Changes for service provider name
=> rtmp-services: Update SharePlay.tv recommendations

.github/workflows/main.yml, .github/workflows/qt-xml.yml, UI/data/themes/Rachni.qss, UI/properties-view.cpp, UI/properties-view.hpp, UI/window-basic-main.cpp, UI/window-basic-properties.cpp, UI/window-basic-source-select.cpp, UI/window-projector.cpp, libobs/obs-encoder.c, plugins/mac-capture/audio-device-enum.c, plugins/obs-libfdk/obs-libfdk.c, plugins/rtmp-services/rtmp-custom.c, plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/ffmpeg-decode.h, plugins/win-wasapi/win-wasapi.cpp
Various cherrypicked commits for a 27.2.4 hotfix and two commits to enable and fix CI builds on the `release/27.2` branch.
Prepare for 27.2.4 hotfix.
Builds didn't fail, I hope somebody tested those commits before merging them to `master`.
=> 27.2 release branch CI fixes + Cherrypicks for 27.2.4

UI/obs-app.cpp
Removes an unused include statement
During some "adventures", I stumbled across this lonely import. It probably doesn't matter, but I can't unsee it.
Its usages probably were removed/refactored at some point, it seems there's no need to keep it.
Compiled on my machine (macOS 12.3).
=> UI: Remove unneeded QProxyStyle include

plugins/obs-filters/scale-filter.c
Undistort checkbox should be ignored if bilinear lowres effect is used.
Filter should render something.
Clear rectangle without fix; proper draw with fix.
Undistort checkbox still works with bicubic and lanczos.
=> obs-filters: Fix invalid scale filter combination

cmake/Modules/ObsHelpers_macOS.cmake
Fix a dylibbundler path issue with case-sensitive partition.
I made a VM to test some changes on macOS with a case-sensitive partition and I found this issue.
With this fix it does use dylibbundler rather than skipping it because of not being inside a `macos` folder.
=> cmake: Fix dylibbundler path for case-sensitive partition

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Description
Change Stripchat Streaming Service
Motivation and Context
How Has This Been Tested?
Types of changes
Change streaming service
Update rtmp-sevices version of services.json
Checklist:
My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
I have read the [contributing document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
My code is not on the master branch.
The code has been tested.
All commit messages are properly formatted and commits squashed where appropriate.
=> rtmp-services: Update Stripchat streaming service

.github/workflows/crowdin-sync-download.yml, .github/workflows/crowdin-sync-upload.yml
Updates Crowdin Sync to 0.2.0 and converts the actions to proper GitHub Actions. Implements and depends on https://github.com/obsproject/crowdin-synchronization/pull/8.
Relevant changes:
- Prepare for submodule removal
- Fix multiple edge cases that would otherwise cause errors
- Fix security issues
Hardening this action improves reliability.
In a fork and private Crowdin project.
=> CI: Update Crowdin Sync to 0.2.0

libobs/graphics/image-file.c
file name like "xxx.GIF" can't be loaded as animated image.
xxx.GIF can be loaded normally
rename xxx.gif with xxx.GIF, make sure it can be loaded
=> libobs: Fix image source not loading upper case file extensions

plugins/linux-pipewire/pipewire-capture.c, plugins/linux-pipewire/pipewire.c, plugins/linux-pipewire/pipewire.h, plugins/linux-pipewire/portal.c, plugins/linux-pipewire/portal.h
Some cleanups and small tweaks for the PipeWire capture code.
The information that we currently log is not enough to give proper support, and at best allows us to know that the first few steps of negotiation worked. Improve these logs.
Also do some code shuffling to make it more sensibly organized in different files.
=> Unassorted PipeWire cleanups

plugins/obs-filters/scale-filter.c
Allows scaling filter to resize incoming HDR video.
Don't want HDR to tonemap to SDR through scale filter unnecessarily.
=> obs-filters: Add HDR support to Scaling filter

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Add .mxf extension to local file dialog extension filters.
Let choose an MXF file in Obs FFmpeg source, using the open file selector
Mac os 11.6.2
Mac intel
Xcode
Tested with trying to load mxf file with and without the patch
=> obs-ffmpeg: Add mxf extension to open file dialog filters

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Adds the ability to move a selected item 10 pixels in the preview when
holding shift while using the arrow keys, instead of going just 1 pixel
per step.
Implementing this was really simple since the system is already made with
distances other than 1 in mind, it just wasn't used anywhere.
https://user-images.githubusercontent.com/59806498/163171601-fffb4924-fe3a-4aa8-97ab-bfdba5905b1f.mov
Moving a sceneitem a medium to large distance in a straight line currently
requires opening the Edit Transform dialog, manually entering a number, closing
the dialog again and then potentially doing fine adjustments in the preview.
While this works, it's an extra step that could be avoided.
Apparently the Shift modifier is used in Photoshop as well, so I assume
it's a rather common shortcut.
macOS 12.4 …
=> UI: Add shortcut for larger movement steps in preview

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Update "Bilibili Live".
1. Add Official local name.
2. Add more info link.
3. Remove "Tencent Cloud" server because it is no longer working.
Local Build
=> rtmp-services: Update Bilibili Live

UI/forms/OBSYoutubeActions.ui
This removes the min and max size properties which lead to crashes
on wayland compositors like gnome which are strict about these
values.
I'm not sure if there is a better way to fix this via the qt gui editor or if these will be reinserted if someone uses that tool. If they will be then likely we need to find a more permanent solution. But i dont have that tool on my system (nor do i want to learn how to use it...). Enforcing sizing constraints on the top level surface seems weird anyway (the dialog gets very wide with non-english languages).
fixes #6227
Tested on fedora 35
=> UI: Fix manage broadcast crash

CI/flatpak/com.obsproject.Studio.json
This module as no cleanup stage and let many unused file so I try to remove most of them.
Remove unneeded PipeWire files from the bundle.
Add a PipeWire screen capture with the Flatpak.
- CI cleanup
=> flatpak: Cleanup PipeWire module

UI/importers/sl.cpp, UI/qt-display.cpp, UI/window-basic-filters.cpp, UI/window-basic-interaction.cpp, UI/window-basic-main.cpp, UI/window-basic-properties.cpp, libobs-opengl/gl-cocoa.m, plugins/obs-transitions/transition-cut.c, plugins/obs-transitions/transition-luma-wipe.c, plugins/obs-transitions/transition-slide.c, plugins/obs-transitions/transition-swipe.c
Fix some unused parameters warning
Fix comparison of integer with different sign warning
Reduce warning amount when compiling Obs.
Macos 11.6.2 (Intel)
Xcode 13.2.1
Compil and run.
=> Fix compiler warning

.github/workflows/main.yml
Update the macOS image used on GitHub Actions from macOS 11 to macOS 12.
Use the latest Xcode and macOS SDK. Unblock #5875 by allowing CI to produce builds using the macOS 12.3 SDK and ScreenCaptureKit.
CI is the test. CI must return all green for macOS builds before this can be merged.
=> CI: Update macOS image to macOS 12

plugins/obs-x264/obs-x264.c
Replace crash with standard recording failure dialog, and log message.
Crashing is unnecessary.
Verified dialog popup and log message for Rec. 2100 PQ & HLG. Verified 601/709/sRGB recordings with ffprobe, and debugger inspection.
=> obs-x264: Disallow HDR attempts gracefully

UI/window-basic-main-outputs.cpp
The old names were simple_h264_recording, simple_h264_stream,
recording_h264, and streaming_h264.
The new names are simple_video_recording, simple_video_stream,
advanced_video_recording, and advanced_video_stream.
Don't want to use "h264" to describe HEVC/AV1 streams.
Verified all four new names appear in the log for their code paths.
=> UI: Redo encoder names now that H.264 isn't alone

plugins/mac-capture/mac-window-capture.m
Replaces the current implementation of Window Capture, which uses Core
Graphics to render a bitmap raster, with one that accesses the window's
CGImage bitmap directly, blits it, and hands that off as a frame to OBS
instead.
Taken out of #5680.
@dossy did great work figuring this out, the entire pull request
is just rather big (also containing other changes and cleanups),
with everything being in one commit which makes it somewhat
difficult to review (It also contains changes to how the window
selection works, which is somewhat controversial and will require
more debate).
The performance enhancement itself though is pretty crucial for
anyone using window capture, it should not get held up in other
debates.
macOS 12.4 Beta
I can no longer count individual frames when using window capture :P …
=> mac-capture: Improve window capture performance

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add rtmp input configuration with recomendation
We would like to add sympla on obs with facility
Choose Sympla Input and add private key 
78f75ccb-3fa3-fc7d-7085-f060bb28fa99
=> rtmp-services: Add sympla service

UI/window-basic-main.cpp
Switches the preview and program window around in vertical studio mode so that program is on top. This is also how the vertical multiviews do it and from what I can tell it's considered the "correct" way.
This will undoubtably be a bit confusing for existing users (and a few might complain about this breaking their spacebar heating), but we have a major version coming up and those usually bring breaking changes with them, so I personally think it's okay - but consider this more of a proposal than a "I want this merged no matter what".
Before:
After:
According to the notes, there also is a "multiview that has it wrong", but to me both vertical ones seem fine to me - perhaps it got fixed in the meantime?
This was requested in https://ideas.obsproject.com/posts/406/ and then PR'd in #1695 …
=> UI: Put program on top in vertical studio mode

.github/workflows/main.yml, .github/workflows/steam.yml
CI: Update first-party GitHub Actions
Keep first-party actions up-to-date.
The PR is the CI test.
=> CI: Update first-party GitHub Actions

UI/platform-osx.mm, UI/platform-windows.cpp, UI/platform-x11.cpp, UI/platform.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Refactors the existing implementation for Windows into
platform-windows.cpp, allowing for other OS implementations in the
future.
- The Windows implementation won't survive a switch to Qt 6, so people
might want to start working on that.
See https://github.com/obsproject/obs-studio/pull/6060#issuecomment-1107444134.
Still compiles on macOS. Testing on Windows with CI builds to confirm that things still work.
=> UI: Move taskbar overlay functions into platform.hpp

libobs/obs-nix-x11.c
The context for `x11_hotkeys_vtable` has a key code map `keycodes` converting from X11's key code to OBS's key code, generated by these lines.
https://github.com/obsproject/obs-studio/blob/73e6df5d09302e76283fb79d2d960868b077aa68/libobs/obs-nix-x11.c#L765-L770
The function `key_from_base_keysym` is looking up another table mapping from OBS's key code to X11's key code.
Since the later table cannot set two or more mapping for one OBS's key code, I added the right-modifiers to this function.
However the hotkeys can be configured with right modifiers in UI, the right modifiers did not work when hitting the hot keys.
This is because `query_hotkeys` in `obs-hotkey.c` was querying states of only left modifiers.
Tested with XFCE4, Fedora 34 with these steps.
1. Set hotkey Shift + F2 to switch to …
=> libobs: Fix hotkey with right-side modifiers

CI/check-services.py
Last PR was merged a bit prematurely, so here's the final update to that change to alter the PR message to be a bit nicer to read (table), see: https://github.com/derrod/obs-studio/pull/11
Being able to read is nice.
My fork.
=> CI: Update service-removal PR description

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Updated Eventials service ingest and recommended
The previous ingest was changed and needed to be updated as well as our audio max bitrate
Tested locally by streaming on Ubuntu 20.04 in a DELL Latitude 5490
=> rtmp-services: Update Eventials ingests

UI/window-basic-main-transitions.cpp, UI/window-youtube-actions.hpp
Fixes some compiler warnings
Warnings are annoying.
Compiled, warnings gone.
=> UI: Fix warnings

UI/window-basic-main-transitions.cpp
https://github.com/obsproject/obs-studio/commit/78bdd4cb01dcf6cde5e658335f4fe29511d01094 removed it accidentally
GDB backtrace show that there was an issue in `CreateDefaultQuickTransitions` and `cutTransition` was in fact not initialised.
Ran OBS with GDB and no issue with the patch.
=> UI: Fix cut transition not being initialised

plugins/mac-vth264/encoder.c
Send PTS in second instead of multiplying `fps_den`.
Fix #5948 and #2760.
As a reference, GStreamer implements PTS (`ts`) and duration as below.
```
ts = CMTimeMake (frame->pts, GST_SECOND);
if (frame->duration != GST_CLOCK_TIME_NONE)
duration = CMTimeMake (frame->duration, GST_SECOND);
else
duration = kCMTimeInvalid;
vt_status = VTCompressionSessionEncodeFrame (self->session,
pbuf, ts, duration, frame_props,
GINT_TO_POINTER (frame->system_frame_number), NULL);
```
FFmpeg implements PTS (`time`) as below. I'm afraid `num` and `den` are opposite in FFmpeg.
```
time = CMTimeMake(frame->pts * avctx->time_base.num, avctx->time_base.den);
VTCompressionSessionEncodeFrame(vtctx->session, cv_img, time, kCMTimeInvalid, frame_dict, sei, NULL);
```
Tested on macOS 12.0.1, MacBook Air (M1, 2020). …
=> mac-vth264: Fix PTS passed to the encoder

.github/workflows/flatpak.yml, .github/workflows/main.yml
Flatpak artifacts filename have no longer a hash.
CI step:
It seems that using git inside a docker container can now trigger this issue. We actually use a container for Flatpak CI.
So this PR fix the lack of hash in the Flatpak artifact filename.
I create a PR on my fork to test the CI. And with this fix, Flatpak filename have its hash.
=> CI: Fix git usage inside Flatpak action container

UI/window-basic-settings.cpp
Stupid me didn't test #6530 with a clean config folder.
Fix an issue.
Run OBS with a clean folder and settings should not show the message unlike this picture.
=> UI: Fix network feature visibility after loading settings

cmake/Modules/ObsDefaults_macOS.cmake
CMake seems to set either `CMAKE_OSX_ARCHITECTURES` and `CMAKE_OSX_DEPLOYMENT_TARGET` implicitly to empty cache variables when not defined explicitly on the commandline or via a GUI.
Setting a default thus requires the `FORCE` flag to overwrite these empty defaults with our desired results. The branches ensure that user-provided non-empty values are not overwritten as well.
Ensure OBS is built with correct architecture-appropriate build flags on macOS.
* Tested with several CMake configuration runs locally
=> cmake: Fix build architectures and deployment target not set to defaults

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Add .m4v extension to local file dialog extension filters.
Implement ideas : 
https://ideas.obsproject.com/posts/1788/mediasource-add-m4v-to-open-dialog-all-media-and-video-file-types
https://ideas.obsproject.com/posts/1258/support-movies-stored-with-m4v-suffix
Tested by trying to choose .m4v file in media source with and without the patch
Sample file (export from keynote following both "Ideas") : 
https://www.swisstransfer.com/d/95cd9685-3836-4719-bc59-d3041ec94b62
- New feature (non-breaking change which adds functionality) -->
=> obs-ffmpeg: Add m4v extension to open file dialog

plugins/obs-qsv11/QSV_Encoder.cpp
A mismatch will lead to failure.
Citrix and Tencent virtual adapters are adding additional Intel adapters, and causing mismatches.
Citrix user says the change works.
=> obs-qsv11: Use same adapter as OBS

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
This fixes a bug where the new circular buffer code is hit by protocols such as rist or srt
although the buffer was meant for files.
As a result srt and rist were not working any more.
Fix  a bug.
Tested that srt & rist stream fine.
File recordings still work.
=> obs-ffmpeg: Fix srt/rist not working with new buffer code

plugins/aja/aja-source.cpp
This commit moves the check of the size before the DMA transfer to avoid calling DMA transfer with too large size.
When too many audio frames are captured at the same time the ring buffer on the card is wrapped, DMA transfer overrun to write audio data, which resulted in corruption of memory contents, sometimes OBS crashes.
OS: Fedora 34
OBS version: release/27.2 (d9865bdffb) + cherry-pick 1ba03d3f0a2613cf30de317a0381f683a5e946c7 to find memory corruption easily.
Hardware: AJA KONA 4
Configuration:
- Add multiple sources of `AJA I/O Device Capture` with these settings
- Video format: 1080p59.94a
- Pixel format: YUV-8
- SDI transport: 3G Level-A (3Ga)
- Connect a camera to the SDI input on AJA KONA 4
To test, do the steps below several times.
1. Start OBS Studio with option `--verbose`.
2. …
=> aja: Fix memory overrun on aja-source

plugins/mac-avcapture/av-capture.mm
Direct access to `[AVCaptureDevice devices]` is deprecated since macOS 10.15. An `AVCaptureDeviceDiscoverySession` is to be used instead, which this PR implements.
When running on older macOS versions or compiling against older platform SDKs, the deprecated method is used.
PS: The formatting is not proper ObjC style, but that's clang-format's doing with our current settings.
Prepare for lowest supported macOS version increase to 10.15 and be more up-to-date with Apple's internal APIs.
* Compiled on M1 Mac with macOS 11.0 target to check that the new API is used and expected video capture devices are visible.
=> mac-avcapture: Fix deprecation warning for AVCaptureDevice list

UI/platform-windows.cpp
Implement Taskbar Overlay for Qt6
Qt6 removed `winextras` module which was present in Qt5.
OBS Studio uses this module to manipulate Windows Taskbar Overlay. 
This is a replacement implementation of the same function using only Win32 API.
=> UI: Implement Taskbar Overlay for Qt6

UI/frontend-plugins/aja-output-ui/CMakeLists.txt, deps/obs-scripting/obspython/CMakeLists.txt, libobs/obs-internal.h, libobs/obs-output.c, plugins/aja/CMakeLists.txt, plugins/aja/aja-common.cpp, plugins/aja/aja-output.cpp, plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c, plugins/obs-filters/CMakeLists.txt, plugins/obs-outputs/CMakeLists.txt, plugins/text-freetype2/CMakeLists.txt, plugins/win-capture/graphics-hook/CMakeLists.txt
=> Warnings 2022-06-26

.github/workflows/flatpak.yml
While I tried to test #6656, I discovered that the Flatpak release CI no longer works and post this error:
```
The workflow is not valid. .github/workflows/flatpak.yml (Line: 24, Col: 9): Unrecognized named-value: 'matrix'. Located at position 37 within expression: github.event_name == 'release' && ( matrix.branch != 'stable' || (!contains(github.ref, '-beta') && !contains(github.ref, '-rc')) )
```
~~Revert Flatpak CI changes from https://github.com/obsproject/obs-studio/commit/8fba906be4f08059ac3925ef942ab6688ec4213b~~
The tag is parsed to allow the Flatpak to be built and publish on the right branch of Flathub.
This is now a fix with a tag check and a dynamic matrix.
For stable tags:
For beta/rc tags:
The job is "Publish to Flathub (beta)".
Fix the CI
Custom release on my fork.
As it is …
=> CI: Fix Flatpak releases

plugins/obs-qsv11/obs-qsv11.c
Added a function `ts_mfx_to_obs` to convert the timestamp in MFX to OBS, which rounds timestamps to the closest multiple of `fps_den`.
FFmpeg uses `av_rescale_q`, which rounds to nearest and halfway cases away from zero at the code below.
https://github.com/FFmpeg/FFmpeg/blob/804bf898dad32813c6bc05ae19d0dcfd45cd8d8a/libavcodec/qsvenc.c#L1840-L1841
Also added a function `ts_obs_to_mfx` to convert that in OBS to MFX. The behavior is not changed but it will be better to understand the code.
(I didn't put `inline` since [Linux kernel coding style](https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst#15-the-inline-disease) suggested not to. If `inline` is preferable, I will add it.)
When frame rate is set to 59.94 fps (60000/1001), MFX cannot handle the …
=> obs-qsv11: Fix timestamp for fractional frame rate

UI/data/locale/en-US.ini
Basically reverts #5931
Google changed their minds.
https://www.theverge.com/tldr/2022/7/14/23219443/google-chromeos-not-chrome-os-branding
Hasn't, is just a string change.
=> UI: Correctly spell "ChromeOS" again

plugins/mac-avcapture/av-capture.mm, plugins/mac-videotoolbox/encoder.c
Split from #6759 as @gxalpha asked to allow a faster review for those commits.
Fix warnings.
#6759 fail to build without those.
=> Fix some macOS warnings

UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp, deps/obs-scripting/obs-scripting-python-import.h, libobs-opengl/gl-egl-common.c, libobs-opengl/gl-nix.c, libobs-opengl/gl-wayland-egl.c, libobs/graphics/graphics-ffmpeg.c, libobs/obs-scene.c, libobs/obs-video.c, libobs/util/bmem.c, libobs/util/c99defs.h, plugins/aja/aja-common.cpp, plugins/aja/aja-common.hpp, plugins/aja/aja-output.cpp, plugins/aja/aja-routing.cpp, plugins/aja/aja-source.cpp, plugins/image-source/image-source.c, plugins/linux-capture/xcomposite-input.c, plugins/obs-ffmpeg/obs-ffmpeg-av1.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.h
`OBS_UNUSED` is not portable to MSVC and so will not prevent it from emitting error once we switch to /W4.
Just wanted to do it.
I build with `-Werror=unused-parameter` and suppress FTLs warning. No error because of unused parameter.
=> Remove OBS_UNUSED

UI/CMakeLists.txt
UI: Suppress LNK4098
defaultlib 'MSVCRT' conflicts with use of other libs; use
/NODEFAULTLIB:library
Don't want build failures. This is the same change applied in #6723, specifically:
* https://github.com/obsproject/obs-studio/commit/da35719f831c81c965fe1faac0fb53b25d6de340
* https://github.com/obsproject/obs-studio/commit/cb5f718d1d01a08b513630a60ea6378566132184
* https://github.com/obsproject/obs-studio/commit/f03827eb63e6f73be06a634791e1772c6e42ff31
Tested a Debug build locally on Windows in VS2019.
=> UI: Suppress LNK4098

UI/window-basic-settings.cpp
Use QComboBox item data rather than always checking for the default
theme custom string.
Wanted to clean this.
Ran OBS and switched between themes save and restarted. No issue.
=> UI: Cleanup theme combobox code

plugins/obs-outputs/librtmp/rtmp.c
Replaces the usage of SO_SNDTIMEO with TCP_USER_TIMEOUT on Linux.
- Noted as more effective than SO_SNDTIMEO by multiple sources.
- Drops TCP connection on timeout instead of returning send() errors, meaning more predictable reconnect timing and reconnect.
- Timeout period actually reflected in practice. SO_SNDTIMEO takes double the timeout time than actually requested to timeout on unix, whereas WinSock works correctly.
Depends #6651 
Timeouts should function correctly regardless of OS.
Ubuntu 20.04: Works as expected
Windows: Works as expected
=> obs-outputs: Improve librtmp timeouts on Linux

libobs/audio-monitoring/osx/coreaudio-output.c
Add judgement to check whether source is active in audio monitoring like other backends.
https://github.com/obsproject/obs-studio/blob/f6f6690ccfeb4b78eec82d4ff853cb6db7138860/libobs/audio-monitoring/pulse/pulseaudio-output.c#L230-L231
https://github.com/obsproject/obs-studio/blob/f6f6690ccfeb4b78eec82d4ff853cb6db7138860/libobs/audio-monitoring/win32/wasapi-output.c#L316-L318
Fixes #6670
Test in MacOS 11.2 M1
Reproduce those steps, audio muted when Media Source hidden.
=> libobs: Don't monitor hidden sources on macOS

libobs/obs-cocoa.m
Use [NSEvent addGlobalMonitorForEventsMatchingMask:] instead of IOKit.
This way is much cleaner. Also the other way is entirely broken on my computer.
Fixes #2292.
Relates to #6550.
1, Open OBS
2. Allow OBS under System Preferences -> Security & Privacy -> Accessibility.
3. (Potentially) restart OBS
4. Press some hotkeys while another program is focused
=> libobs: Rewrite macOS hotkeys implementation

CI/check-format.sh
If the path to clang-format has spaces, as might occur when testing locally with a version not in path or not covered in this script, it will fail. Enclose the call to clang-format in quotes to prevent this failure.
Want to more easily test new versions of clang-format locally.
Tested locally.
=> CI: Fix clang-format if path has spaces

.github/workflows/clang-format.yml, .github/workflows/main.yml, CI/check-format.sh, UI/window-basic-main-transitions.cpp
CI: Switch to Visual Studio 2022
This PR also switches CI to clang-format 13 as that is what _currently_ is shipped with Visual Studio 2022 17.2. As such, once this is merged, we would expect developers to use clang-format 13.0.1 until the next Visual Studio 2022 update reaches General Availability. If necessary, I can split these changes to a separate commit or PR.
This PR also currently contains a submodule update for obs-browser, which contains the changes made in https://github.com/obsproject/obs-browser/pull/371. That should be merged and the submodule updated before this is merged.
Visual Studio 2022 brings many updates, including much improved indexing speeds, improved search, and better CMake and git integration. Visual Studio 2022 is also now a 64-bit application, and is also …
=> CI: Switch to Visual Studio 2022

plugins/obs-ffmpeg/texture-amf.cpp
Use same pattern that the mux code uses.
Consistency.
Debugger inspection, but I'm not sure if it makes a difference in stream/recording.
=> obs-ffmpeg: Set MaxCLL/MaxFALL for AMF

UI/data/themes/Yami.qss
Adds the custom Yami icon to the missing states of QGroupBox where QCheckBox has them already.
https://user-images.githubusercontent.com/59806498/181836756-39d499bb-6141-4ac2-9f4d-29c7687f47d5.mov
This is undesirable:
https://user-images.githubusercontent.com/59806498/181836607-1fe5eb2e-90d0-4132-981e-8ba8fc670a62.mov
Compiled and run, now the icon appears properly.
=> UI/themes: Add image to QGroupBox checkbox on Yami

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added Streamvi to streaming services drop down.
=> rtmp-services: Add Streamvi service

plugins/obs-filters/nvidia-greenscreen-filter.c
This fixes a bug where an update of the parent source breaks the filter.
A signal handler is added to listen to updates of the parent.
This triggers a reset of the RTX FX.
Fix a bug.
Bug fixed.
=> obs-filters: Reset RTX Greenscreen if parent is updated

plugins/obs-filters/scroll-filter.c
Add support for scrolling of HDR frames.
No reason we shouldn't be able to support scrolling of HDR frames.
=> obs-filters: Add HDR support to Scroll

CI/flatpak/com.obsproject.Studio.json
- Update KDE Runtime to 6.3 (Qt 6.3)
* x264: Use same commit as obs-deps
* srt: Updated to 1.5.0
* mbedtls: Updated to 3.2.1
* librist: Updated to the same commit as obs-deps
* aom: Updated to 3.4.0
* svt-av1: Updated to 1.1.0
* ffmpeg: Updated to the same commit and patches as obs-deps
* luajit: Updated to the same commit as obs-deps
Also avoid cleaning up PipeWire and FFmpeg headers, plugins could happen to build against them.
Update the Flatpak
Build and run the Flatpak locally.
=> flatpak: Update deps with obs-deps, Qt and allow some headers to be kept

CI/flatpak/com.obsproject.Studio.json
2022-07-28 tag was removed.
Fix
=> flatpak: Change obs-deps tag to 2022-07-29

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/forms/OBSBasic.ui, UI/forms/OBSPermissions.ui, UI/obs-app.cpp, UI/platform-osx.mm, UI/platform.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-permissions.cpp, UI/window-permissions.hpp
Adds a window for simpler permissions management to macOS.
Pops up the first time when opening OBS, and can be invoked manually via a menu item.
The buttons should be self-explanatory.
Microphone and Camera permissions can be requested and granted directly (if not already rejected), Screen Capture and Accessibility always require a trip into System Preferences. 
Yami (with missing font issue):
Dark:
Menu entry:
Permissions are a pain, and this might make things easier for users.
macOS 13
Tested functionality of buttons and that they correctly show the status.
Tested that the window only pops up by default once. Tested that it is invokable via the menu.
=> UI: Add macOS permissions window

plugins/aja/aja-output.cpp, plugins/aja/aja-output.hpp
Removes an obsolete function that was intended to check if a video frames' worth of audio samples were present in the audio sample queue in the AJA Output plugin. This code was used in some early attempts to get the output plugin working but is no longer needed.
The code is obsolete.
Did a quick search to find any references of the code in question.
=> aja: Remove unused code from output plugin

UI/data/themes/Rachni.qss
accessibility and interact icons is missing.
Before
After
=> UI: Add missing Icon in Rachni theme

UI/data/themes/Acri.qss
accessibility and interact icons is missing.
Before
After
https://github.com/obsproject/obs-studio/pull/6912#issuecomment-1202782712
=> UI: Add missing Icon in Acri theme

plugins/linux-pipewire/CMakeLists.txt, plugins/linux-pipewire/pipewire.c
This reverts commit 0532a5c1f0296098a268dc43d889a08c932e1c48.
Ubuntu 21.10 is from OBS 28 onwards not longer supported and as such we
can raise the requirement of the PipeWire dependency to 0.3.33.
=> Revert "linux-capture: Fix Ubuntu 21.10 builds"

test/CMakeLists.txt
Fixes CMake build error on Linux:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
COCOA (ADVANCED)
linked by target "macOS_test" in directory /var/tmp/paludis/build/media-video-obs-studio-28.0.0-beta1/work/obs-studio-28.0.0-beta1/test/osx
```
=> test: Only build osx tests for OS_MACOS

UI/window-basic-preview.cpp
Addition to 76ae9cbc which was made independently of the spacing helpers
introduced in 2d6a9c9c.
100% (unchanged):
200% (old):
200% (new):
As a note: I did notice that the spacing lines are visibly misaligned, however this issue already exists in the current master, with scaling it just becomes more obvious. This is why I consider it a different issue that should be addressed separately.
Noticed when playing around with the nightly / beta.
macOS 13
See screenshot(s) above.
=> UI: Make spacing helpers DPI aware
