.github/workflows/flatpak.yml
Publish beta releases to Flathub Beta's `beta` branch, and stable releases to Flathub's `stable` branch.
The publishing jobs only account for the Flathub repository, but they do not account for the branch within these repositories. We should publish to the correct branches of the correct repositories (`beta` branch for the `beta` repo, and `stable` branch for the `stable` repo).
- I've created a fake beta release in my repo
- [With this branch, it correctly built and (tried to) publish to the `beta` branch of Flatpak Beta](https://github.com/GeorgesStavracas/obs-studio/runs/4669361217?check_suite_focus=true)
- [With this branch, the `stable` build was entirely skipped](https://github.com/GeorgesStavracas/obs-studio/runs/4669361193?check_suite_focus=true) …
=> Publish to the correct Flathub branches

libobs-opengl/gl-egl-common.c, plugins/linux-capture/pipewire.c
Various unassorted cleanups to the PipeWire code of the `linux-capture` plugin, and to `libobs-opengl`.
As the code grows in scope and complexity, we need to do some conscious effort to keep it tidy.
There shouldn't be any actual functional changes here. All (except one) commits are aesthetical cleanups.
=> Various EGL & PipeWire cleanups

UI/volume-control.cpp
Fix vertical grayscale meters when volume is muted
#5181 only works for horizontal meters
On windows 64 bit with muted vertical meters
-
=> UI: Fix vertical grayscale meters when volume is muted

libobs/obs-video.c
In graphics thread, both tick_sources() and output_frame() will invoke obs_source_release, which may cause source::destroy invoked in defer-thread or any thread.  For source::destroy of window/monitor plugin,  freeing WGC is posted into graphcis thread.
So, It is better to check remaining tasks before stopping graphics thread. 
@jpark37   It should be reviewed by you.
before stopping graphics thread, make sure stored WGC tasks can be handled
add window source and display source based on WGC mode;
exit OBS;
make sure all actual destroy can be handled from graphics thread
=> libobs: Ensure all graphics tasks can be handled before exiting graphics thread

UI/window-basic-filters.cpp
Increment the show reference of a source when the filters dialog is open, just like the properties dialog.
Keep the behavior of video displays in OBS consistent.
Subscribed to the `InputShowStateChanged` event in obs-websocket
=> UI: Increment showing in filters dialog

CI/flatpak/com.obsproject.Studio.json
Update FFmpeg to 4.4.1 with a cherry-pick of https://github.com/FFmpeg/FFmpeg/commit/d1b47f3bfcc625ca1cae210fc198dcbd54381a88 to fix issue with VAAPI.
It also apply FFmpeg patches and cherry-picks from [obs-deps](https://github.com/obsproject/obs-deps/tree/master/CI/patches).
It also add RIST support with the same commit hash as macOS and Windows for parity.
Mbed TLS module is also moved before librist to allow the latter to be built with Mbed TLS.
Add libaom and SVT-AV1 ~~(only on x86_64)~~ support.
~~Rather than creating second FFmpeg module for x86_64 to enable SVT-AV1, I use a sed command to enabled it by default on x86_64.~~
Note: I also update nv-codec-headers (surely will be squashed in FFmped update commit).
Feature parity
Set OBS Studio to stream to this URL: …
=> Flatpak: Update FFmpeg to 4.4.1 and add RIST, libaom and SVT-AV1 support

UI/obs-app.cpp, UI/platform-osx.mm, UI/platform.hpp
Adds a check that detects if OBS is running on Rosetta on macOS and logs
the result.
~~Also adds a popup window that asks the user wether OBS is intended to
run on Rosetta. This window is currently disabled, and should get
get enabled once we officially support ARM natively.~~
With OBS most likely being compilable natively with the next release, it
will be good to know which version users are using when they face
issues (for example with third party plugins not working).
macOS 12.0.1, Intel: 
- Compiled and Run
- Log correctly confirms that it's not translated.
A friends Mac mini (using a CI build of this branch), macOS 12.0.1, M1:
- Log correctly reports translation via Rosetta.
=> UI: Add Rosetta Detection

UI/obs-app.cpp
`%T` is specified for `strtime` instead of `%X` so that the time format is not localized.
Time format in the log was fluctuating in Linux. (I think its also applicable for Windows and macOS.) Sometimes `AM` or `PM` was inserted so that the milisecond was not always located just after the second.
Millisecond time in the log was added in 36ad777b8 but the millisecond was not always added just after the second digits depending on locale settings. Some locale settings add `AM` or `PM` at the end so that second and millisecond are separated.
The log is also read by support volunteers among a lot of country so that it should not be translated. Currently, some Asian language is written.
| `LANG` | Time format in log |
|--------|--------------------|
| `en_US.utf8` | `11:14:38 AM.952` |
| `C` | …
=> UI: Do not localize timestamp in log file

UI/window-basic-main-transitions.cpp
When a sceneitem is right-clicked, if a sceneitem didn't have a visibility transition
set, the debug log would throw a `debug: obs_source_get_id: Null 'source' parameter`
warning (twice, one for show and one for hide). However, the source being null there
is expected if no transition is set, so that warning/message should get silenced.
Debug log messages shouldn't warn about things that are intended.
Gets pretty annoying quickly.
Messages are gone, the visibility transition right click options still work as intended.
=> UI: Fix "Null 'source' parameter" warning

UI/forms/OBSBasicSettings.ui, UI/hotkey-edit.cpp, UI/hotkey-edit.hpp, UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
This replaces the programmatic generation of the hotkeys tab with XML, and reorganises how the list of hotkeys is generated, reusing concepts from `LoadAudioSources()`, This also ensures no invalid `QWidget::setLayout` calls occur.
Summary of changes:
* Removed previously unused `hotkeyWidget` & `hotkeyLayout` XML (this was being discarded on first Settings render)
* Moved `hotkeySearchLayout` (top bar) and its children (search label, search box, filter box, reset button) into XML
* Moved reset click signal to Qt signal `on_hotkeyFilterReset_clicked`
* Moved `hotkeyScrollArea` and its required elements into XML
* Set parent widget of `OBSHotkeyEdit`
* Added `OBSHotkeyEdit` constructor that is loaded from XML (for the filter box) without `DupeIcon` support
* Moved `searchFunction` from a …
=> UI: Don't recreate entire Hotkey Settings tab, fix memory leaks

UI/window-projector.cpp
To calculate label offset, program and preview for 18-scene have same size as 8-scene but `labelOffset` returned different value between 18-scene and 8-scene.
Fix #5718.
The labels are scaled by `ppiScaleX` and `ppiScaleY`, which is the scale factor for preview and program. Hence, the offset for the labels should be calculated based on the scale factor of preview and program.
OS: Fedora 34
OBS Version: 27.2.0-beta2-27-ge00195ad6 with this change
All 8 types are displayed and checked by eyeball.
- Horizontal, Top (8 Scenes)
- Horizontal, Bottom (8 Scenes)
- Vertical, Left (8 Scenes)
- Vertical, Right (8 Scenes)
- Horizontal, Top (18 Scenes)
- Horizontal, Top (24 Scenes)
=> UI: Fix label offset on projector view

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp
Add DXGI_COLOR_SPACE_TYPE and SDR white level when available for HDR
characteristics.
GetPathInfo/IsInternalVideoOutput functions were copied from MS docs.
Will be useful for debugging HDR issues in the future.
Verified proper logging of color space when "Use HDR" is off/on, and white level when "SDR content brightness" slider is set to 0/40/100; 80/240/480 nits respectively. The slider uses this formula: `nits=4*x+80`
Windows 7 skips past the nonexistent functionality gracefully.
=> libobs-d3d11: Log display color space info

UI/window-basic-preview.cpp
Fixes https://github.com/obsproject/obs-studio/issues/5724
Bug fix
Locked scene item and made sure it couldn't be resized.
=> UI: Ignore resizing item when it is locked

UI/window-projector.cpp
Removing this attribute fixes #3582 and allows projector windows to be resized under KDE. It's more of a workaround, so this has to be tested by others. The flag is required for the main preview, since it'll freeze otherwise when restoring obs after minimizing it, but disabling it just for projectors fixed the issue without affecting the main preview or the preview in properties/filter dialogs.
Disabled the attribute in [UI/window-projector.cpp#L33](https://github.com/univrsal/obs-studio/blob/efbfe9bf9da0fd6680934219ef16bb6771e80c22/UI/window-projector.cpp#L33) for all systems that use X11.
Might need another check to not disable the attribute if Wayland is used.
Resizing projectors is not possible under KDE otherwise without using workarounds listed in #3582.
Projectors and multiviews …
=> UI: Disable WA_PaintOnScreen for projectors

CI/flatpak/com.obsproject.Studio.json
Use official Github mirror for Freedesktop Pipewire GitLab.
Constant 504's.
Run CI
=> CI: Use GitHub mirror for PipeWire repository

UI/window-basic-properties.cpp
On current master, when clicking `OK` in the source properties dialog the context bar wouldn't update.
Fixes this issue.
(Changes update from normal to deferred to prevent the context bar "flashing" (going away and
reappearing) once when the properties dialog is closed)
Not sure when this issue was introduced (and I'm not bisecting it just for the sake of finding out; it was probably me doing the minimized context bar anyways), I just randomly noticed it.
Tested with text source and color source, the context bar correctly shows
changes made in the properties dialog (in my case text/color).
=> UI: Update context bar when exiting properties dialog

.github/workflows/main.yml
Update CI deps to 2022-01-01 packages.
Fix RIST on macOS. Patch libaom.
This aligns CI Windows builds with recently shipped beta builds to support AV1 and RIST as well as providing other updates.
* Update FFmpeg from 4.2.4 to 4.4.1
* Update nv-codec-headers from 9.0.18.2 to 11.1.5.0
* Add libaom and SVT-AV1 support (64-bit only)
* Add RIST support
* Enable multithreading for libvpx obs-deps builds
Fix CI macOS builds.  Bring CI Windows builds in line with recent beta builds.
Although this appears to be adding new features for Windows, this is really bringing CI in line with the existing OBS Studio 27.2.0 beta builds, so we aren't actually introducing new changes.  The obs-deps repo changes lagged behind the 27.2.0 beta release period a bit, so we had a bit of desync as obs-deps caught up. …
=> Update CI deps to 2022-01-01 packages

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Moves the processing to hide the window earlier in the startup process - rather than showing the main window and hiding it in the tray initialization, just _don't_ show the main window. This prevents the window from briefly flashing and taking focus from other apps.
This requires a new check for `sysTrayEnabled` - we need to know whether the tray icon will be visible. (If it's not, and the window is hidden, there would be no way to maximize the window.)
Lastly, this PR removes the Apple-specific workarounds, as they no longer appear to be necessary.
Fixes #2668 and prevents the main window flashing on startup.
_Setting_
1. Enable **System Tray** and **Minimize to system tray when started**.
2. Restart OBS.
2. Verify tray icon appears and window does not flash.
3. Disable **System Tray** …
=> Fix window flashing when starting minimized to tray

UI/window-basic-settings.cpp, libobs/obs-source.c
Fixes a couple of apparent copy/paste errors preventing that were preventing push-to-talk and push-to-mute delays saving when choosing Apply or OK in the settings menu.
Fixes #3467
Tested on Windows x64.
Verified that the push-to-talk and push-to-mute delay values were persisted across OBS reboots. (I didn't test the actual functionality of the setting - just the UI.)
=> Fix push-to-talk/mute delay not saving

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
avcodec.h stopped including channel_layout.h per FFmpeg commit
1be3d8a0cb77 [1]. Fixes compilation error on macOS against FFmpeg 
later than the mentioned commit.
[1] https://github.com/FFmpeg/FFmpeg/commit/1be3d8a0cb77f8d34c1f39b47bf5328fe10c82d7
appleclang 12 raises errors when compiling obs with FFmpeg
master.
(On visual studio 2019, we only have warnings. C99 converts these warnings
into errors though on macOS).
This fixes the issue.
Note that in agreement with commit https://github.com/obsproject/obs-studio/pull/5501/commits/abf1d609d29196921df8f09ab6e07340b7cf9660
I haven't ifdef the channel_layout.h include per avcodec version.
Edit: these issues occur also on linux (issue #5756) 
This has been tested on macOS with FFmpeg 4.4, FFmpeg master.
And also on windows.
Obs-Studio now …
=> obs-ffmpeg: Further FFmpeg deprecations fixes for FFmpeg 4.4+ (on mac)

libobs/obs-nix-x11.c
Qt will mask certain input events. In order to avoid them masking things
like mouse button events we open a new display here.
This ended up getting introduced in 506b950 but we didnt notice until later.
Fixes #4843
Mouse 4 works when pressed while another window is active. This is the same as the behavior we had for 26.
=> libobs: Open a separate X11 connection for hotkeys

UI/properties-view.cpp
Reordering the filters makes the filter mutex of the source locked while loading a new the properties of a filter which may require other locks. By loading the properties of the filter on a QueuedConnection we make sure the filter mutex is cleared when that happens.
I don't like deadlocks.
The main UI thread gets a lock on the filter mutex followed by a lock on the app sources mutex to fill the properties of the filter
while the graphics thread does a lock on the app sources mutex followed by a lock on the filter mutex
On windows 64 bit by reordering move transition override filters
=> UI: Stop locking filter mutex while loading properties

plugins/aja/aja-routing.cpp
Issue introduced by f09137a2e00aecbce634d3e46a8a809ca8cd6907.
On some Linux distributions `-Werror=format-security` is set when building package keeping OBS Studio from being built with AJA plugins.
Allow OBS Studio to be build with `-Werror=format-security` set. Which is the case on ArchLinux build system.
Build OBS Studio with `makepkg`. 
- On master it would emit an error.
- On this branch it builds.
=> aja: Fix format-security warning which lead to a build error on some Linux distributions

UI/frontend-plugins/aja-output-ui/AJAOutputUI.cpp, UI/frontend-plugins/aja-output-ui/AJAOutputUI.h, UI/frontend-plugins/aja-output-ui/CMakeLists.txt, UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp, UI/frontend-plugins/aja-output-ui/aja-ui-main.h, UI/frontend-plugins/aja-output-ui/data/locale/en-US.ini, UI/frontend-plugins/aja-output-ui/forms/output.ui, plugins/aja/aja-common.cpp, plugins/aja/aja-common.hpp
Add GUI options to the AJA Output UI window for toggling the AJA HDMI Multi View feature on the upcoming AJA ioX3 device. The UI for this feature will only appear if an ioX3 device is connected to the host system. The AJA HDMI Multi View feature in the ioX3 device allows monitoring each of the 4 SDI inputs as separate 1080p quadrants of a UHD/4K HDMI output stream. Monitoring of the HDMI Multi View stream requires a UHD/4K capable monitor. All rasterization of the Multi View frame occurs in hardware of the ioX3.
1. Added an "Additional Settings" section to the AJA Output window containing the following UI elements:
- **Device** selection drop-down menu enumerating the AJA devices connected to the host system. If an ioX3 device is selected the **Enable Multi View** checkbox and **Multi …
=> aja: Add ability to toggle AJA HDMI Multi View feature from AJA Output UI

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
Shuts down the decklink UI outputs when the OBS_FRONTEND_EVENT_EXIT is fired.
When outputting over decklink and exiting OBS there was a crash
Tested locally on my windows machine by starting an obs decklink output and then pressing the exit button on the main ui.
=> decklink-output-ui: Stop outputs on OBS_FRONTEND_EVENT_EXIT

UI/frontend-plugins/aja-output-ui/AJAOutputUI.cpp, UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp, plugins/aja/aja-common.cpp, plugins/aja/aja-common.hpp, plugins/aja/aja-output.cpp, plugins/aja/aja-source.cpp, plugins/aja/aja-ui-props.hpp
1. Fix AJA Output plugin default settings from clear preferences not working properly.
2. Check for empty cardID in addition to cardID NULL check.
The AJA Output plugin UI was showing the default settings we configure in the UI code but the output plugin itself was not passing the default settings to the plugin create callback. This change causes the output plugin to use the default settings seen in the UI when starting the output plugin.
Also, when the cardID was initially read from the device properties list before the AJA devices were enumerated the cardID string was empty. We want a valid cardID before starting the plugins so now we check for both NULL cardID and empty cardID.
Found as the result of an internal bug ticket found by AJA QA when running OBS and the AJA Plugin from a …
=> aja: Fix for invalid default settings and empty cardID string

UI/youtube-api-wrappers.cpp
Adds a log message of the error returned by cURL.
Some users are experiencing issues with the YouTube API, but not errors related to the HTTP request themselves are currently being logged. 
Intentionally timed-out requests by proxying them through Fiddler.
=> UI: Log YouTube API HTTP request errors

plugins/linux-v4l2/v4l2-input.c
The timeout_usec variable is uint64_t, but the log format was set to %ld (signed long int), so it would sometimes log a nonsensical value. Let's use $PRIu64 instead, which should be equivalent to %llu (unsigned long long int).
Fixes #5797.
Incorrect data in logs is bad.  Correct logs are helpful.
I haven't tested this.  Will require assistance from others to verify this change.
That said, it's just a logging change, so it's probably safe to merge if it passes CI.
@kkartaltepe @feaneron 
=> linux-v4l2: Fix timeout logging

deps/media-playback/media-playback/media.c
We currently pass a 'buffer_size' option to avformat in bytes.
Unfortunately, avformat/librist.c admits an option with the same name but in milliseconds.
The default values set in the UI (2 MB= 2 10^6) go beyond the range admitted in ms (0-30 000)
so avformat issues errors.
This fix disables the option when rist protocol is detected.
Bug notice given in discord #beta channel : 
- Deagan: `Was RIST support only for outputting from OBS then, not currently for an inbound Media Source? I am attempting to use Larix Streamer to receive a RIST transmission using the "rist://@192.168.x.x:PORT?cname=RECEIVER" formatting, still to no resolve.`
- leb: `while i can't seem to get it working either with the same setup, i can replicate a crash with a rist url in the media source when the network buffer …
=> media-playback: Fix bug with rist streams.

plugins/aja/aja-source.cpp
Fix for Kona1 card not auto-detecting the capture pixel format when Pixel Format is set to "Auto".
We use the video payload ID (VPID) data in the SDI stream to detect the pixel format and this was accidentally gated behind `NTV2DeviceHasBiDirectionalSDI`, which does not apply to the Kona1, and a number of other older cards. This was preventing uni-directional SDI cards (input-only) from detecting the VPID on the wire.
The Kona1 card was not auto-detecting the pixel format when the capture plugin Pixel Format setting was set to "Auto".
Tested by the developer on a Kona1 card and io4K+ to make sure it didn't break the existing newer cards auto-detection.
=> aja: Fix Kona1 not auto-detecting capture pixel format

plugins/aja/aja-common.cpp, plugins/aja/aja-common.hpp
Two things fixed in this PR per request of AJA QA:
1.  Rename HDMI Monitor In/Out selections as well as Analog In/Out to to HDMI IN/OUT and ANALOG IN/OUT respectively, to match what is shown on those devices. (io4K+, IOXT, etc.)
3. Hide HDMI1 input selection on devices with a discrete HDMI IN port. This was essentially a duplicate menu entry.
"HDMI Monitor" In and Out were not officially used terms in the AJA products. QA requested those list items be changed to HDMI IN/OUT.
Additionally, certain cards which have those discrete HDMI IN and OUT ports should not show the numbered HDMI input selections. Those are reserved for Kona HDMI, or any future cards that have multiple HDMI input or output ports.
Tested by developer on io4K+. QA will verify on all of the applicable cards/firmwares:
- …
=> aja: Fix input/output selections on devices with discrete ANALOG/HDMI ports.

plugins/aja/aja-common.cpp, plugins/aja/aja-presets.cpp
Crosspoint indices were wrong for the UHD4K_ST425_Quad_3Gb_Squares_RGB_Capture preset and VPID was not being set for the selected 3G-Level A or B transport modes passed along from the capture UI.
Fix signal routing for 4x 3G SDI UHD/4K RGB low-framerate capture. There was a typo in the crosspoint indices for the 3G Level-B preset, and the VPID values were not being set when SDI Transport was set to 3Ga or 3Gb. Thus the capture preset was not even being recalled for quad-link RGB SDI modes.
Quad-link SDI RGB low-framerate capture was broken.
Verified by sending a quad-link SDI RGB low-framerate signal from an AJA Ki Pro device into an AJA io4K+ capture device in OBS, setting the capture Video Format to UHD/4K low-framerate (23.98 to 30fps) formats, setting Pixel Format to BGR-8, setting …
=> aja: Fix signal routing for 4xSDI UHD/4K RGB

UI/obs-app.cpp
This needs to matcht the base name of the .desktop file name.
This is needed for propagating the correct app id on Wayland,
which is needed e.g. for proper window icons on Plasma Wayland
=> Set desktopFileName for QApplication

plugins/mac-vth264/encoder.c
This changes fixes DTS timestamps in videotoolbox packets being always zero (at least on ARM macs). Credit for the changes goes to rcombs <rcombs@rcombs.me>, I was just helping her to debug this stuff.
This was seemingly one of the factors causing https://github.com/obsproject/obs-studio/issues/4670 (Inability to save recordings when limiting bitrate, streams crashing). That issue isn't completely fixed however, as OBS still seems to drop frames after ~5 seconds when "Limit bitrate" is turned on (regardless of settings).
I tried streaming and recording before and after the change with "Limit bitrate" turned on, streaming would hang on a black screen and recording would save an empty file before, they both work now (albeit with frame drops). …
=> mac-vth264: Fix DTS timestamps when blank

UI/window-basic-settings.cpp
Avoids unbounded stack growth when pasting content that has many invalid characters. Fixes https://github.com/obsproject/obs-studio/issues/5815.
Fix a crash.
Pasted content containing many invalid characters. No crash.
=> UI: Use regexp to filter filename formatting

plugins/win-capture/window-helpers.c
We currently try not to list minimised windows in the Window Capture source. Apparently, `IsIconic()` and `IsWindowVisible()` aren't enough to check if a UWP window is minimised. [From what I can find](https://social.msdn.microsoft.com/Forums/windows/en-US/0d7419a7-1d25-40bc-909e-a0db33b109a8/iswindowvisible-fails-to-detect-if-store-app-is-visible?forum=vclanguage), `DwmGetWindowAttribute` looking for the `DWMWA_CLOAKED` attribute seems to be the right fix.
* #5769 exposed that minimised UWP apps appear in the window capture list, even though they cannot be captured.
* As we don't currently list minimised apps, let's avoid it with UWP apps too
* Open two UWP apps. Minimise one of them.
* Open Window Capture properties and try to capture. The visible one should appear, and the minimised …
=> win-capture: Don't list minimized UWP apps

libobs/obs-internal.h, libobs/obs-video.c
These were operated on by atomic functions but were not marked as volatile or loaded with `os_atomic_load_long`, potentially introducing subtle race conditions. Detected by ThreadSanitizer.
Race conditions are bad.
Checked disassembly to verify loads and stores were atomic.
=> libobs: Mark raw_active and gpu_encoder_active as volatile

plugins/aja/aja-common.cpp, plugins/aja/aja-common.hpp, plugins/aja/aja-widget-io.cpp
The result from `CNTV2SignalRouter::WidgetIDToChannel` was incorrect for SDI Output 5 on cards with a discrete SDI Monitor Output (io4K/io4K+/etc). This results in SDI5 output not working on certain cards with a dedicated SDI MONITOR output, such as the io4K/io4K+.
Created a wrapper function `WidgetIDToChannel` to perform the `NTV2WidgetID`-to-`NTV2Channel` lookup. Hard-code `NTV2_WgtSDIMonOut1` to `NTV2_CHANNEL5` if building against NTV2 SDK 16.2 or earlier, otherwise continue to use `CNTV2SignalRouter::WidgetIDToChannel`.
The bug in the NTV2 SDK will be fixed in 16.3.
AJA QA found that there was a regression in functionality, in that SDI5 output (SDI MONITOR) was no longer working. SDI MONITOR is a special dedicated monitor output on certain AJA external I/O devices and is technically …
=> aja: Workaround for SDI5 output not working on io4K+

plugins/aja/aja-source.cpp
Moved the call to `ResetVideoBuffer` from within the `aja_source_update` callback to the body of the `AJASource::CaptureThread`, just before the thread loop starts running.
AJA QA was finding intermittent crashes as the result of changing settings (video/pixel format, etc.) in the GUI of the AJA Source plugin. The stack traces provided by QA, and my reproduction of the issue in the debugger, indicated that the crashes were a result of calling `Deactivate` to destroy the currently running `CaptureThread` from within `aja_source_update`, followed by a call to `ResetVideoBuffer`. The call to `ResetVideoBuffer` would sometimes free the video buffer that was in-flight to OBS before the active `CaptureThread` was fully torn down and re-created with new settings.
Tested by running an automated …
=> aja: Fix crash when capture thread is reset

plugins/aja/aja-presets.cpp
Remove the flag to enable the 3G Level-B to Level-A converter from the `UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Capture` preset. The converter was enabled erroneously and caused problems with UHD/4K YCbCr 2SI 3G Level-B SDI signals on the Kona5. 
Enabling the 3Gb->3Ga converter alters the signal on the Kona5 and other newer boards that return `true` for `NTV2DeviceCanDo3GLevelConversion`. Older boards can safely enable the converter even if it is not needed, as was the case with this bug.
UHD/4K YCbCr 2SI 3G Level-B capture was broken on boards which return `true` for `NTV2DeviceCanDo3GLevelConversion` due to the enablement of the 3Gb->3Ga level conversion register in the associated capture preset.
Verified that the change fixes UHD/4K YCbCr 3G Level-B 2SI SDI signals on Kona5 but does not break …
=> aja: Fix UHD/4K YCbCr 3G Level-B 2SI preset

plugins/obs-qsv11/common_directx11.cpp
This is a simple bug fix for a memory leak in the QSV plugin module
Memory leaks (exacerbated by 4K and discrete graphics) will cause encoding failures on long recordings. These destructor checks/calls should have been in the original code but were missed and now fixed.
Re-tested on TGL and DG2 systems with QSV recording for 12+ hours to verify fix is working. 
- [ X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ X] My code is not on the master branch.
- [ X] The code has been tested.
- [ X] All commit messages are properly formatted and commits …
=> obs-qsv11: Memory leak bug fix in QSV plugin module

libobs/obs.c
Don't destroy mutex before destroying sources is done
Don't like crashes
on windows 64 bit
=> libobs: Don't destroy mutex before destroying sources is done

plugins/win-capture/window-helpers.c
Fix missing HWND argument type, and use DWORD based on MS sample.
Correctness. Warnings are annoying.
Verified DwmGetWindowAttribute is still behaving as before.
=> win-capture: Fix parameter mismatches

UI/xdg-data/com.obsproject.Studio.appdata.xml.in
It is mistakenly set to github.org, instead of github.com. Sorry :(
While the idea of leading people to report bugs to the wrong website is entertaining, we should at least make sure this wrong website exists and has an issue report form.
Meanwhile, let's just point people to our actual issue tracker.
Open the URL, and observe that it leads you to the correct website.
=> UI: Fix bugtracker URL in AppData file

UI/window-basic-main.cpp
They detection for wether the Right Click -> Transform -> Suboptions are
enabled was not checking the n selected items but the
first n items in the list, which would lead to the options being enabled
or disabled based on the whether other items were locked.
Let's fix that.
Bugs not good. See the #beta-testing channel on Discord.
(Tested on macOS 12.1)
- Lock/Unlock first (top of the list) item in the sources list.
- Right click any other item and choose go to the "Transform" menu
- Notice that in beta3/4 all but the first three options, meaning options like "Reset Transform", rotate, etc., are enabled based on whether the first item in the list was locked or unlocked?
- Well, not any more with this fix.
=> UI: Fix transform options being wrongly enabled/disabled

UI/properties-view.cpp
In `OBSPropertiesView::AddProperty`, `OBS_PROPERTY_GROUP` (line 1449) creates neither a widget nor a label, causing `AddProperty` to create a default one (line 1460). Without a widget, it does not get attached to the layout, resulting in a memory leak (line 1474). Detected by PVS Studio.
https://github.com/obsproject/obs-studio/blob/ae4797f8cc690c0c94781767b9b1de4a29d3b4aa/UI/properties-view.cpp#L1448-L1474
This commit also simplifies a bit of the code to avoid repeatedly testing the same condition.
Memory leaks are bad.
Breakpoint testing.
=> Fix QLabel leak in OBSPropertiesView::AddProperty

UI/source-tree.cpp
The group reorder signal was never disconnected when
resetting signals.
Bug fix.
Created groups to make sure nothing broke.
=> UI: Disconnect group reorder signal

plugins/mac-vth264/encoder.c
This PR consists of three commits that provide various fixes for the mac-vth264 encoder plugin.
----
mac-vth264: Remove OSX 10.8 compatibility code
OBS no longer supports building on OSX. The minimum version of macOS that we support is macOS 10.13. We can safely remove this 10.8 compatibility code.
The changes in this commit apparently make the minimum version supported macOS 10.10 due to no longer providing a custom enum for [kCMFormatDescriptionBridgeError_InvalidParameter](https://developer.apple.com/documentation/coremedia/1416276-format_description_bridge_error_/kcmformatdescriptionbridgeerror_invalidparameter?language=objc).
----
mac-vth264: Use float for expected frame rate
The encoder property kVTCompressionPropertyKey_ExpectedFrameRate is a hint to the video encoder. Since frame …
=> Various fixes for mac-vth264

UI/window-basic-main.cpp
Fixes a warning introduced with the WindowDisplayAffinity code for environments that don't support it / where it isn't implemented.
And no, I don't get the whitespace change on the comment either, ask clang-format.
Less warnings == more good
Still compiles (macOS 12.1), warning gone
=> UI: Fix unused variable warning on non-windows

libobs/obs-module.c
Currently if a module fails its load callback, it remains loaded and OBS continues to call additional exports such as `obs_module_post_load`. This goes against the [documented behavior](https://obsproject.com/docs/reference-modules.html#c.obs_module_load), which states that a module that fails its load callback is unloaded.
This commit releases locale resources and frees the module's information, preventing further callbacks from libobs. The module itself (the DLL) is not yet unloaded from memory as os_dlclose is commented out for causing unspecified issues - this should be revisited in the future.
I noticed the AJA plugin was having its `obs_module_post_load` code executed even though the module's `obs_module_load` returned false due to no AJA devices on my system. This seemed bad. …
=> libobs: Free module if obs_module_load callback returns false

plugins/aja/aja-common.cpp
This change hides the ANALOG IN/OUT list items from the AJA Capture and Output UI, respectively.
Proper support for analog video capture and display with supported AJA cards (Kona4, Kona LHI, etc.) will be added in a future version of the plugin.
Placeholder list items for ANALOG IN and OUT were accidentally left in the UI. There is not enough time left in this release cycle to add and test the rest of the code needed to support analog capture and display with supported AJA cards.
1. Spot-checked on an AJA Kona4 card to verify that the ANALOG IN/OUT list items were hidden from the AJA capture and output UI.
2. Checked a Corvid44 card to make sure the UI for a non-analog-capable card didn't break.
=> aja: Disable Analog In/Out selections in the UI

UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp
Stopping the Preview output in the AJA Output UI can lead to a crash.
**Problem**
The function `preview_output_stop` in `UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp` calls `video_output_stop`, which results in a call to `pthread_mutex_destroy`: https://github.com/obsproject/obs-studio/blob/364f102561faf565ae22e5fa0f1f4aabf3e07c48/UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp#L103
This results in the `data_mutex` field of `struct video_output` from being deleted and made `NULL` while still in use by the `render_preview_source` function in aja-ui-main.cpp.
The call to `video_output_close` a few lines after this also results in a call to `video_output_stop` on the same structure. Allowing this call to perform the `video_output` mutex cleanup seems to be the correct action. …
=> aja-output-ui: Fix crash when stopping AJA Preview output

plugins/win-dshow/win-dshow.cpp
This flag leads to a cheaper technique, "Draw" instead of
"DrawNonlinearAlpha", and all the paths are opaque anyway.
Faster is better.
Tested 4K NV12 source. Image looked fine. Verified shader swap in Intel GPA. Seems to be a few microseconds faster on average, maybe 76 -> 73 µs.
=> win-dshow: Use OBS_SOURCE_FRAME_LINEAR_ALPHA

docs/sphinx/reference-libobs-graphics-graphics.rst, libobs-d3d11/d3d11-subsystem.hpp, libobs-opengl/gl-subsystem.h, libobs/graphics/graphics.h
This format will be useful for P010 chroma in the future.
HDR
Verified D3D11 and OpenGL paths work in separate fork.
=> Add GS_RG16

plugins/win-dshow/win-dshow.cpp
Adds entry for buffering state of dshow sources to the log.
In order for this to operate successfully, and continue to do so in the future, it moves the `SetupBuffering()` above the `blog` so the buffering is set before the log prints.
Dshow issues show up fairly frequently in support context, and knowing the state of buffering can be useful when troubleshooting. Applicable for issues regarding smoothness/stutter as well as latency.
Tested on windows 10 20H2, verifying correct log output using auto and enabled/disable buffering on the following:
* virtual devices (virtualcam)
* eos Webcam utility
* basic capture card (cantlink)
=> win-dshow: Log buffered state

plugins/vlc-video/vlc-video-source.c
The vlc plugin was keeping only up to two audio channels. It was overlooked when surround sound support was added to obs-studio. This commit remedies this oversight.
Signed-off-by: pkv <pkv@obsproject.com>
Media with surround sound pass only one or two audio channels to obs through the vlc plugin.
We want parity with Media Source (ffmpeg libs).
Tested on windows 10 vs 2019. 
A video file with 5.1 audio plays correctly with 6 audio channels.
=> vlc-video: Enable surround sound support

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
This PR updates [nanoStream Cloud / bintu](https://info.nanocosmos.de) server addresses for transcoding ingests.
In addition, also updated:
- stream_key_link to direct our customers to the user dashboard
- more_info_link directs to an on-boarding article for nanoStream Cloud / bintu using OBS Studio
This is a follow up to the original submission https://github.com/obsproject/obs-studio/pull/4086,
that included incorrect settings for server addresses for nanocosmos transcoding service, forcing the
user to manually configure a Custom service.
Tests on local machine running Fedora Linux with latest OBS release.
- Copy settings to the local user configuration folder.
```sh
cp obs-studio/plugins/rtmp-services/data/services.json ~/.config/obs-studio/plugin_config/rtmp-services/services.json
``` …
=> rtmp-services: Update nanoStream Cloud / bintu ingests

UI/window-projector.cpp
Fixes a crash with projectors. Happens if the projectors source gets removed via `obs_source_remove() `
To reproduce, you can use undo/redo:
- Add a new source, in the properties click cancel (OK is fine as well, you'll just have to undo twice)
- Open a source projector
- Undo (twice if you previously clicked OK)
- Crash
Alternatively:
- Create a new scene
- Open a projector of that scene
- Delete the scene
- Create a new scene with the same name
- Crash
The projector window was closed, but not removed from the list of active projectors, leading to this crash.
Makes sure the projector gets deleted properly (using existing methods), and removed from the list of active projectors.
macOS 12.0 beta 5
Tested with both fullscreen and windowed projectors, OBS doesn't crash.
Removing a scene will …
=> UI: Properly close projector when source is removed

libobs/graphics/graphics.h
Was missing case for GS_RGBA16F.
Bug.
Verified GS_RGBA16F returns 64.
=> libobs/graphics: Fix gs_get_format_bpp

libobs/CMakeLists.txt
Makes them easily searchable from Visual Studio.
Useful for my workflow of using finding text in solution.
OBS still compiles for me on Windows without trying to compile the effect files. I guess CI will show if this works on Mac/Linux.
=> libobs: Add effect files to CMakeLists.txt

UI/data/locale/en-US.ini, UI/obs-app.cpp, UI/platform-windows.cpp, UI/platform.hpp
Screenshot from Ubuntu 20.04 running in Wine stable:
Adds a warning on startup if OBS is run in Wine and logs Wine version.
Note: this moves the creation of the log file so it's ready once the check happens. This will also fix the Rosetta status not being logged.
While running OBS in Wine works surprisingly well, you shouldn't.
This just warns people who don't realise that (they exist, we had them in #linux-support).
- Ran OBS in Wine
- Ran OBS not in Wine
=> UI: Add Wine detection/warning

.github/workflows/main.yml
Explicitly sets Windows runners to use the 2019 image.
Builds appear to fail with the 2022 image (which is now default for `windows-latest`). Until #5155 lands we probably still want to keep our builds working.
(It hasn't)
(This PR *is* the test)
=> CI: Specify Windows Server 2019

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Updates RTMP ingests for Picarto.
Picarto changed their ingest server list a while ago, and all the old servers are auto-redirecting to closest now. This new list makes it possible for users to manually override the server directly from OBS' presets again, as before.
New ingest list has been verified against list published here: https://help.picarto.tv/help/how-to-configure-open-broadcaster-software
In addition, all the servers have been checked and work.
Note: did not run `clang-format` on `services.json`, as doing so changed practically every line of the file.
=> rtmp-services: Update Picarto ingests

libobs/util/platform-windows.c
Fix VS static analysis warnings in platform-windows.c
PR 5929
Debugger inspection before/after.
=> libobs/util: Fix VS static analysis warnings

UI/window-basic-main-profiles.cpp
Make the action of renaming a profile send only one of each of those events:
- `OBS_FRONTEND_EVENT_PROFILE_CHANGING`
- `OBS_FRONTEND_EVENT_PROFILE_LIST_CHANGED`
- `OBS_FRONTEND_EVENT_PROFILE_CHANGED`
Actually `on_actionRenameProfile_triggered()` sent those events but when `CreateProfile()` is called through `AddProfile()` which is called through the first method those events are sent a second time.
The `rename` is only true when renaming a profile thanks to `on_actionRenameProfile_triggered()`, so for any other `CreateProfile()` call `rename` is false.
Depending on how future plugins that use the new `_CHANGING` event, it could provoke crashes because they were expecting a `_CHANGED` and not a second `_CHANGING` and do something that they should not have done twice.
Crashing while the …
=> UI: Avoid emiting events 2 times when renaming a profile

libobs/obs-nix-wayland.c
Fixes a bug where keymaps were mapped with MAP_SHARED.
OBS currently segfaults under weston because xkb_state is NULL if mmap fails.
OBS no longer segfaults under weston.
=> wayland: Map keymap with MAP_PRIVATE

plugins/linux-capture/pipewire.c
Enter the graphics context before calling `gs_texture_destroy()` or else the call will fail causing the texture handles to leak.
Upon Pipewire session destruction, enter the graphics context when textures are being destroyed.
I was getting leak reports from OBS on shutdown when using Pipewire capture, thought I'd investigate..
Run with and without the change.
Before on OBS Shutdown:
> info: Number of memory leaks: 2
Also in debug build:
> debug: gs_texture_destroy: called while not in a graphics context
With the patch:
> info: Number of memory leaks: 0
=> linux-capture: Fix for pipewire capture leaking texture handles

plugins/win-wasapi/win-wasapi.cpp
According to rcdrone and Microsoft's documentation, work queues are properly supported on Windows 8.1 and above. However, since 27.2's release, we've heard reports that while Mic/Aux capture works correctly (verified), Desktop Audio does not (also verified).
This locks the work queue code behind a Windows 10 check. 
I did attach a debugger to a debug build of OBS but none of the `throws` were hit, and I don't understand the code well enough to track down what could be happening.
* Fixes #5967
* Launch OBS on Windows 8.1
* Play audio
* Notice it's captured
=> win-wasapi: Only enable work queue on Windows 10+

.github/workflows/main.yml, CI/full-build-macos.sh
Ensures that SOVERSION symlinks of bundled libraries (e.g. `libavcodec.58.dylib -> libavcodec.58.134.100.dylib`) are present in the generated App Bundle.
Fixes https://github.com/obsproject/obs-deps/issues/95
Also applies necessary changes to adapt https://github.com/obsproject/obs-deps/pull/93 
When linking to a shared library, it is common to use the SOVERSION variant (e.g. `libavcodec.58.dylib`) because major versions are expected to not break the API. This allows projects to update the specific library versions without breaking link information.
`dylibbundler` only copies the _actual_ library file linked by OBS into the generated App Bundle (per its purpose), which means that e.g. plugins linking against `libavcodec` will break any time OBS updates the specific version of FFmpeg used …
=> CI: Fix missing SOVERSION libraries in macOS App Bundle

UI/source-tree.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Calls the refresh function of the "Edit" menu (which enables options like copy/paste and transform) when items get selected and deselected instead of when the menu is creted.
Warchamp found that copying and transforming with shortcuts is broken - this was because the state of the menu items, to which the shortcuts are bound, only refreshes when the menu gets called. This means that when the a source was selected, the shortcuts for copying or transforming would be disabled until either the Edit menu was selected or the source right clicked, forcing the menu to refresh (which would enable the menu entry).
Now, the state of the menu items (and with that the shortcuts) will get refreshed when items are selected or deselected.
macOS 12.3 Beta 3, compiled and run.
Shortcuts like copy and …
=> UI: Refresh edit menu on item select/deselect

libobs/obs-module.c
The current path would prevent the browser source from loading if OBS itself is in the "Application Support" folder, where it might end up when being installed via certain distribution platforms.
This adjusts the existing hack to specifically check for the obs-studio subfolder where the old browser source library would reside.
This PR should ideally be merged into master and `release/27.2` to distribute a fixed, signed, build for those platforms.
Browser source not loading is sort of inconvenient.
Verified that adjusting the path fixes loading the browser source.
=> libobs: Adjust path for legacy browser source block

plugins/linux-v4l2/v4l2-helpers.h, plugins/linux-v4l2/v4l2-input.c, plugins/linux-v4l2/v4l2-mjpeg.c
Previously we assumed mjpeg was always decoded to 422 but it seems some
cameras provide different pixel formats such as 420.
This change delays setting the obs frame pixel format until after we
have decoded the v4l2 frame.
fixes #5821
People prefer when their webcams render correctly.
My c920 with mjpeg remains unchanged. Hopefully the users from the issue can test this with their webcams.
=> linux-v4l2: fixup mjpeg pixel format computation

plugins/obs-outputs/rtmp-stream.c
Auto tuning apparently doesn't work very well on this version and af6844f5c24d77ca7b4b1bcc000504d8e693a563 reportedly caused throughput regressions. Set a fixed 512k buffer instead.
RTMP throughput regression on Windows 7.
Breakpoints.
=> Set a fixed size socket buffer on Windows 7

plugins/win-wasapi/win-wasapi.cpp
Catch `HRError` if the RTWQ functions fail so that we can fallback to the old code instead of crashing.
Crash bad.
Stopped mmcss service, ran OBS.
=> win-wasapi: Fall back to old code if RTWQ fails

plugins/linux-v4l2/v4l2-mjpeg.c, plugins/linux-v4l2/v4l2-mjpeg.h
Previously the switch did not catch all cases issuing a quite large
warning. Also there was a const-ness warning for codecs on ffmpeg 5.0
that this addresses.
A clean compile is a happy compile.
Compiled.
=> linux-v4l2: Fix warnings in mjpeg

UI/log-viewer.cpp, UI/log-viewer.hpp
This includes 3 fixes. 2 very big ones, and a smaller one to improve readability
1) Update the internal QTextDocument of the text component directly
2) Use QPlainTextEdit, which supports HTML & is designed for long text
3) Use QString's arg function for formatting strings
Fix 1 significantly improves realtime performance when adding lines individually, to the point that the UI no longer freezes if the viewer is open and the log is being spammed. It also improves initial launch speed when there's a large amount of text already in the file.
Reference: https://stackoverflow.com/a/54501760/2763321
Fix 2 completely eliminates delay when opening the viewer, regardless of how many lines are already in the log file. For a standard log after OBS launch, this cuts opening time from about 2 seconds …
=> UI: Fix performance issues with the Log Viewer

UI/source-tree.cpp
Makes sure that the edit menu gets refreshed when changing the lock state of a source, enabling/disabling options like
Reset Transform. This includes the right click menu, the Edit menu and Hotkeys.
Fix #6024
Locking and then right clicking a source now has the Reset Transform menus etc correctly disabled (and enabled for unlocking).
=> UI: Refresh edit menu on item locked signal

UI/platform-x11.cpp, libobs/graphics/graphics.h, plugins/linux-v4l2/v4l2-output.c
Fix building OBS Studio on FreeBSD:
- `libobs/graphics/graphics.h`: The `gs_texture_create_from_dmabuf` & `gs_query_dmabuf_*` functions were marked as Linux-only as of f7a55f45fdacf9c8383cafae8170294ac8997954.
- `plugins/linux-v4l2/v4l2-output.c`: `versionsort` (and by extension, `__strverscmp`) are not available on FreeBSD, as they are GNU extensions (`versionsort` is used by `virtualcam_start` to read `/dev/video*` devices in the right order), so implemented them.
- `UI/platform-x11.cpp`: Was calling `to_string` on FreeBSD when not `using namespace std;`, so calling `std::to_string` instead.
Fixes building on FreeBSD.
Tested on FreeBSD 13.0-RELEASE-p4 and FreeBSD-CURRENT, hardware is non-applicable.
Compiled with clang version 11.0.1 & 13.0.1.
- Bug fix (non-breaking change which fixes …
=> Fix building OBS Studio on FreeBSD

UI/frontend-plugins/decklink-captions/decklink-captions.cpp, UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp, plugins/decklink/plugin-main.cpp
The modules were still being loaded even if the user didn't have any Decklink devices.
Don't show Decklink tool menu items if it is not installed and less memory usage.
Checked the tools menu to see if the items were removed.
=> decklink: Don't load modules if Decklink not found

UI/window-basic-main.cpp
For apps using sparkle, it's normal for the "Check For Updates" button
to be in the app menu instead of the help menu, so let's put it there.
While `ApplicationSpecificRole` is what Qt recommends for such purposes, this would move
it between the separator and "Preferences...". However, we can hijack `AboutQtRole` which
moves it right below "About OBS" (which is where it should go, and where most other sparkle
apps put it (In particular, I checked VLC and Cyberduck)).
- [Ideas page](https://ideas.obsproject.com/posts/1545/check-for-updates-should-appear-in-the-obs-menu-in-the-main-menu-not-help)
- https://github.com/obsproject/obs-studio/issues/5338
While there is no formal documentation, there is plenty of precedent for this (see the discussion on the issue linked above). In addition to …
=> UI: Move "Check For Updates" menu to app menu on macOS

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/volume-control.cpp, UI/volume-control.hpp
My branch has two commits, as recommended by the fine folks on OBS Discord.
The first addresses issue 3915 by replacing a cached bitmap with selective repaint. This helps with legibility at scaled DPI, and also eliminates unnecessary repainting of the scale area.
V27.0.1 (using cached bitmap). Left 100%, right 125% scaling
First commit. Left 100%, right 125% scaling
The second commit allows the appearance of the meter to be adjusted via the stylesheet. This permits the appearance to be optimized by the user to deal with scaling or other needs and preferences.
Second commit. Left 100%, right 125% scaling
Second commit, vertical orientation. Left 100%, right 125% scaling
Second commit, stylesheet specifies meter bar 9 pixels wide, silly font at 150%
Minor changes
- A horizontal meter has …
=> Improve scaling of audio meter (issue 3915)

plugins/win-dshow/win-dshow.cpp
Log status of hardware decoding.
Useful to know whether or not hardware decoding is enabled for support.
Log text looks correct in both checkbox positions.
=> win-dshow: Add hardware decode status to log

plugins/win-dshow/ffmpeg-decode.c
Replace AVCodecContext cleanup with avcodec_free_context.
Comment for avcodec_alloc_context3 says to use avcodec_free_context.
Function call seems to work okay. Can see from avcodec_free_context implementation that avcodec_close is no longer needed.
=> win-dshow: Fix wrong AVCodecContext free call

UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Based on the product description from the main website
The change is directly related to the Flathub app page:
https://flathub.org/apps/details/com.obsproject.Studio
The current page is rather bare and it doesn't contain most of the information that is on the main site. By including this information from the main site, it becomes easier for users to find the app by searching for keywords.
As a package maintainer over on Flathub, I want to make sure that the page listing for OBS is up to date.
```
[kevin@kevin-at-fedora ~/Projects/obs-studio/UI/xdg-data]$ appstream-util validate ./com.obsproject.Studio.appdata.xml
./com.obsproject.Studio.appdata.xml: FAILED:
• attribute-missing     : <release> has no timestamp
Validation of files failed
```
_The missing release data is expected, as that is …
=> UI: Additional product details

libobs/obs-video.c, libobs/util/platform-windows.c
Use integer math for Windows timings, and clamp interval computation to prevent infinite stalls.
Noticed double math was unnecessary on Windows. Don't want OBS graphics thread to hang.
Debugger inspection showed math behaving as desired. OBS 60 FPS recording was verified 60 FPS.
=> Video timing improvements

UI/obs-app.cpp, UI/platform-x11.cpp
Suspicion is that floats were not being parsed correctly when a foreign locale is set.
- CUBE files now load correctly.
- HLS arguments to custom FFmpeg now parse correctly.
The Qt recommendation is to set LC_NUMERIC to "C" in the QCoreApplication doc:
https://doc.qt.io/qt-5/qcoreapplication.html
> On Unix/Linux Qt is configured to use the system locale settings by default. This can cause a conflict when using POSIX functions, for instance, when converting between data types such as floats and strings, since the notation may differ between locales. To get around this problem, call the POSIX function setlocale(LC_NUMERIC,"C") right after initializing [QApplication](https://doc.qt.io/qt-5/qapplication.html), [QGuiApplication](https://doc.qt.io/qt-5/qguiapplication.html) or QCoreApplication …
=> UI: Restore LC_NUMERIC to C locale on Mac/Linux

plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/ffmpeg-decode.h
Add av_buffer_unref call.
Leaks are bad.
Program runs fine.
=> win-dshow: Fix hwdevice_ctx leak

UI/obs-app.cpp, UI/platform-osx.mm, UI/platform-windows.cpp, UI/platform-x11.cpp, UI/platform.hpp
Changes the various multi-instance check function names into one, making
calling it much more clean, since it no longer needs to differentiate between
macOS, Linux, FreeBSD and whatever DragonFlyBSD is.
Unfortunately, Windows requires carrying the RunOnceMutex, so it's not *as*
clean as it could be, but imo better than what we currently have.
The ifdef-ladder in obs-app.cpp is ugly and mostly unneeded, since the
check works the same on all operating systems, except Windows where
the function has a return value. Having four different functions doing
the same thing is not very nice to look at.
Compiles on macOS, Windows and Ubuntu (CI).
Tested on macOS 12.3 and Windows 11 that the check still works.
Not tested on other unix-like (since I don't have them), but other than
the function names …
=> UI: Simplify multi-instance check

UI/qt-wrappers.cpp, UI/qt-wrappers.hpp, UI/window-basic-main.cpp
Since the source list is a custom list model, the
QDataStreams for OBSSceneItem are not needed.
Remove unneeded code.
Performed actions in the source list to make sure everything still works.
=> UI: Remove OBSSceneItem QDataStream

UI/window-basic-properties.cpp
When we added undo/redo in 86eb7aeb a distinction between Updates and
Visual updates was made, presumably for filters which need special
handling of the update case. These functions were also added to regular
source properties, but didnt use any special code instead calling
obs_source_update an additional time after a short time.
Instead lets remove the 2nd delayed call and only call obs_source_update
once per settings change.
some sources perform work during update or log additional information (xcomposite is both) this second
call causes graphical weirdness for the user in this case and extra logging to read through for support.
Undo/redo of xcomposite and v4l2 capture didnt break. Its unclear to me if this change was made to workaround some slow
source which might desync between their …
=> UI: Avoid calling obs_source_update multiple times

libobs/obs-encoder.c
Fix overflow subtracting unsigned numbers
When offset_size is greater than size, size would overflow.
Don't like overflowing numbers causing crashes
On windows 64 bit
=> libobs: Fix overflow subtracting unsigned numbers

UI/window-basic-main.cpp
Another indicator to the user that replays can't be saved
when recordings are paused.
Better UX
Paused and unpaused recording to make sure button is disabled.
=> UI: Disable replay save button when paused

UI/window-basic-main.cpp
When the user right clicks a dock titlebar, display a context-aware context menu rather than the generic Docks menu.
**Before**:
**After**:
**At @Warchamp7's request.**
His belief is it shouldn't matter where you're right clicking on a dock, it should show that dock's context menu.
Additionally, we moved the Docks menu to the main menu bar so accessing it from a context menu should no longer be necessary.
* Right click on a dock titlebar
=> UI: Display dock-relevant context menu on titlebar

deps/media-playback/media-playback/decode.c, deps/media-playback/media-playback/decode.h, deps/media-playback/media-playback/media.c, deps/media-playback/media-playback/media.h
FFmpeg has deprecated stack-allocated AVPacket objects, so make a pool
and use the new pattern instead.
Hate compiler warnings.
Debugger inspection of all modifications.
No crashes/leaks for these scenarios:
- Loop off, exit during playback
- Loop off, exit after playback
- Loop on, exit during first loop
- Loop on, exit during second loop
=> deps/media-playback: New AVPacket pattern

libobs/graphics/graphics.h, libobs/graphics/texture-render.c, libobs/obs-source.c
Correct oversight where obs_source_process_filter_begin may be called with a different format than filter_texrender expects.
This hasn't been an issue so far because filters historically use GS_RGBA every frame, but format changes can occur in the future when filters start supporting target switches between SDR and HDR.
Verified destroy/create logic is skipped in current branch, and that format switches are handled in an experimental HDR branch.
=> libobs: Support filter_texrender format changes

UI/window-basic-main.cpp
If the user would toggle hide in mixer in studio mode,
the source would show up in audio mixer, even if it
wasn't active.
Fixes https://github.com/obsproject/obs-studio/issues/4142
Toggled hide in mixer for audio sources in studio mode.
=> UI: Fix mixer hide toggle in studio mode

UI/window-basic-main-dropfiles.cpp
- Adds undo/redo to dropfiles, so that sources created by drag-and-drop can be removed
again via Ctrl-Z.
~~- Adds a dialog telling the user that the file is not supported if a file with an unknown
extension is drag-and-dropped into OBS. So far, this fails silently.~~
- Source actions like this should have undo/redo
~~- Having nothing happen if a user drags an unknown file into OBS can be confusing to the
user who might have no idea what's going on (and is just wondering why no new source
appears)~~
macOS 12.3 Beta 4, compiled and run
- Undo/Redo works, tested with raw text, a media file and a url
~~- Dialog appears if I try to add an unknown file type: 
*<<Removed>>*~~
- Bug fix (undo/redo)
~~- Tweak (dialog)~~
=> UI: Dropfiles Undo/Redo

libobs-d3d11/d3d11-duplicator.cpp
Remove DXGI_FORMAT_R10G10B10A2_UNORM since it can be ambiguous whether
it is Rec. 2020 PQ, or high-precision sRGB. We can revisit later.
Don't want to deal with bugs from an untested format. I'm not even sure how to convince DXGI to use the format as all my attempts have failed.
Remaining two formats still work when HDR is toggled on and off.
=> libobs-d3d11: Simplify duplicator formats

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, docs/sphinx/reference-frontend-api.rst
Developers now can easily get a translated string from the frontend
instead of using their own translations.
Makes it easier for plugin developers.
Tested with my plugin.
=> obs-frontend-api: Add function to get frontend translated string

UI/window-projector.cpp
Since the remove signal is coming from another thread,
QMetaObject::invokeMethod has to be used, or corruption
could possibly occur.
Noticed invokeMethod was not being used with the signal.
Tested by removing a scene and seeing if the scene projector was deleted.
=> UI: Fix handling of remove signal with projectors

plugins/mac-capture/audio-device-enum.c
Add vbcable to the whitelist for loopback devices. VB-Cable is now available on "Audio Output Capture" window
There's currently a manual whitelist for loopback devices, due to there being no way to programmatically detect them. User can't use VB-Cable with OBS.
Compile on MacOS 11.6. I checked if all VB-Cable (VB-Cable, vb-cable A, VB-Cable B, VB-Cable C and VB-Cable D ) are listed in Audio Output Capture.
=> mac-capture: Add vbcable to whitelist for loopback devices

UI/window-basic-main-dropfiles.cpp
webp files get recognized by the image source since #3942, but that PR didn't include drag-and-drop. This PR fixes that.
Fixes [ideas#1740](https://ideas.obsproject.com/posts/1740/)
macOS 12.3, compiled and run
Dragging and dropping now correctly adds the webp file as an image source instead of ignoring it.
=> UI: Add webp to dropfiles

plugins/win-wasapi/win-wasapi.cpp
Getting reports that it isn't working for 1607 and below.
If they continue, we should probably just pull the RTWQ path.
NOTE: Audio is currently broken because of da4d98d0e46b60b993ff222a266354e6cff06417. Need revert to test audio recording.
Fixes #6132
Want WASAPI to work.
Verified version check passes on Windows 11, and audio plays fine.
Reporter of #6132 has verified his 1607 server edition works.
=> win-waspai: Tighten version check for RTWQ

.editorconfig
Adds editorconfig entries to align with CMake-format configuration.
CMake-Format by default uses spaces with 2-character widths for formatting. This is predominantly used to align long lists of files and parameters along the same visual vertical axes (which are often dynamically defined by the length of the first token in function calls).
Forcing CMake-format to use tabs breaks this important formatting step, so the choice was made to adapt its own formatting rules for all files ending with `.cmake` or named `CMakeLists.txt`
Probably requires some testing by users with different editors/IDEs which support editorconfig files.
=> CI: Update editorconfig to match CMake-format configuration

UI/obs-app.cpp, UI/platform-osx.mm, UI/platform-windows.cpp, UI/platform-x11.cpp, UI/platform.hpp
Removes the `InitApplicationBundle()` function which is no longer in use.
The function was marked deprecated with the cmake rewrite and changed to
no-op; given that it doesn't do anything and returns true everywhere it (and the
associated check) can just been removed.
Compiled on macOS 12.3
=> UI: Remove InitApplicationBundle() function

plugins/obs-libfdk/obs-libfdk.c, plugins/rtmp-services/rtmp-custom.c
Also modifies rtmp-services.
This sets the aac bitstream to ADTS for the mpegts output.
This fixes a bug with mpegts ouput where the avformat muxer issues
an error with fdk-aac encoder.
Fixes a bug.
Streams work with mpegts output.
Both srt & rist are fine.
Tested on win 10 to nimble server.
=> obs-libfdk: Set bitstream to ADTS for mpegts output

UI/CMakeLists.txt, UI/frontend-plugins/aja-output-ui/CMakeLists.txt, UI/frontend-plugins/decklink-captions/CMakeLists.txt, UI/frontend-plugins/decklink-output-ui/CMakeLists.txt, UI/frontend-plugins/frontend-tools/CMakeLists.txt
Due to how CMake and generated project files are structured, just using
AUTOUIC to pick up Qt `.ui` files will lead to a situation where
changing such a file doesn't trigger a regeneration of the associated
header files and thus a re-build of the target.
Upstream fix still requires `.ui` files to be added as target sources.
CMake issue: https://gitlab.kitware.com/cmake/cmake/-/issues/17959
Also adds the UI files to the target file overview in Visual Studio and Xcode.
Removes necessity to change a code file just to have the build system recompile the UI header files.
Changed single UI file and checked build output.
=> UI: Fix UI file changes not being picked up by CMake

libobs-d3d11/d3d11-subsystem.cpp
This matches the behavior of glClearColor/glClear on OpenGL.
Both renderers should behave the same when possible.
Verified color difference with FRAMEBUFFER_SRGB on/off for both renderers on Windows.
Mac doesn't always seem to honor the current FRAMEBUFFER_SRGB setting at glClear time, but I'm not sure what we can do about that if anything.
=> libobs-d3d11: Make gs_clear honor FRAMEBUFFER_SRGB

libobs/CMakeLists.txt, libobs/obs-avc.c, libobs/obs-hevc.c, libobs/obs-hevc.h, libobs/obs-nal.c, libobs/obs-nal.h
Also create obs_nal_find_startcode from obs_avc_find_startcode to share
with obs_hevc_keyframe.
Needed to decode and record HEVC in the future.
Verified obs_avc_keyframe did not regress with an H264 stream, and obs_hevc_keyframe/obs_extract_hevc_headers works in another branch with an HEVC stream.
This code by itself will not add additional HEVC functionality to OBS.
=> libobs: Add HEVC parsing functions

libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-stagesurf.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-d3d11/d3d11-texture2d.cpp, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h
Add wide-channel format support for encoding HDR on GPU.
Needs more support code to actually use HDR in OBS.
Want to support HDR in the future.
Functionality works in HDR fork.
=> libobs/graphics, libobs-d3d11: Add P010 support

cmake/Modules/ObsHelpers.cmake, cmake/Modules/ObsHelpers_Windows.cmake, cmake/Modules/ObsHelpers_macOS.cmake
Windows and Linux do not require a contained application bundle to run
and debug OBS - as such targets can and should be copied independently
from the main OBS application target.
Also silences the output of the `install` step that sets up those files.
Allows updating single plugins inside the build tree without the need to build and package the main OBS project.
Checked on Linux and Windows by changing a single plugin to force a recompile, then comparing the checksums of the files copied into the `rundir` to confirm they've been updated.
=> CMake: Fix targets not being copied into rundir on Windows and Linux

libobs/obs-source-deinterlace.c
Seeing a rare assert on startup for a media source with deinterlacing
already on. Tested with Yadif 2x. Repro is maybe 10% of OBS launches?
Accessing bad memory is bad.
Verified OBS still runs if the rare case occurs using conditional breakpoint.
=> libobs: Add array check for deinterlace logic

UI/window-extra-browsers.cpp, UI/window-extra-browsers.hpp
When updated all custom browser docks lost their UUIDs because an empty string is applied to the property.
[Faulty line of code](https://github.com/obsproject/obs-studio/blob/923d427212c0c2873b83258d4704d6b203c0a84e/UI/window-extra-browsers.cpp#L182), `item.uuid` is empty here, it was not found earlier because the [action was used rather than the dock to save the UUID](https://github.com/obsproject/obs-studio/blob/923d427212c0c2873b83258d4704d6b203c0a84e/UI/window-extra-browsers.cpp#L495).
The UUID was removed from `Item` in `ExtraBrowsersModel` because it ends never used. I can revert this change if requested.
I also change the way that those docks are saved, rather than using actions properties, docks properties are used.
I was working on ADS (Advanced Docking System) when I step on …
=> UI: Fix custom browser docks UUID

CI/flatpak/com.obsproject.Studio.json
The CMake Overhaul disabled it for no reason since 27.2 Flatpak always had AJA support included.
And as for JACK, the CMake Overhaul made JACK plugin disabled per default.
Revert an unexpected change.
Built fine on my machine.
The CI will build the Flatpak with AJA and JACK plugins without any issue.
- CI changes
=> Reenable AJA and JACK plugins on Flatpak

.github/workflows/main.yml, CI/full-build-macos.sh, deps/obs-scripting/obs-scripting-python.c
Moves `obspython.py` to `Resources` on macOS.
This is a variation of #6196 but for the legacy build system in case we want to create another 27.2.x bugfix release.
Having `obspython.py` in the code directories requires it to be signed, since it's a text file this is done via extended attributes. This breaks on Steam or when using another packaging method that does not retain those.
Additionally per Apple themselves it is not recommended to store scripts there, and they should live in resources instead: https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG201
- Checked that files are in the correct folders, but was unable to test scripts on my Mac since only arm64 python was installed …
=> CI/deps: Move obspython.py to Resources (27.2 branch)

libobs/util/base.h
Macro is easier than `sizeof(x) / sizeof(x[0])`.
Don't want error-prone typing.
Verified it returned correct size under debugger.
=> libobs: Add OBS_COUNTOF for array count

UI/remote-text.cpp, deps/file-updater/file-updater/file-updater.c, plugins/rtmp-services/service-specific/nimotv.c, plugins/rtmp-services/service-specific/showroom.c, plugins/rtmp-services/service-specific/younow.c
ALPN was disabled in 2016 due to poor server support, occasionally resulting in failed negotiations. Six years later, ALPN is now widely supported, and NPN is being removed in the latest version of nginx.
NPN support is being removed from major web servers, leaving no way to negotiate protocol upgrades.
Verified connectivity still works on Windows 10. **Needs testing on Windows 7 / 8**.
=> Enable curl ALPN support

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c, plugins/win-dshow/ffmpeg-decode.c
Instead of allocating `AVPacket` on stack, allocate it by `av_packet_alloc()`.
In ffmpeg-mux, ffmpeg-vaapi, and obs-ffmpeg-nvenc, AVPacket is allocated at the initialization to avoid frequent allocation of AVPacket.
The deprecated function `av_packet_alloc` is also found in `deps` but this PR does not change `deps`.
According to FFmpeg, `av_init_packet` and `sizeof (AVPacket)` are deprecated.
> sizeof(AVPacket) being a part of the public ABI is deprecated. once av_init_packet() is removed, new packets will only be able to be allocated with av_packet_alloc().
Tested on Fedora 34 (Linux).
Note that `obs-ffmpeg/obs-ffmpeg-nvenc.c` and `win-dshow/ffmpeg-decode.c` are never tested.
=> plugins: Use av_packet_alloc instead of av_init_packet

docs/sphinx/reference-libobs-media-io.rst, docs/sphinx/reference-outputs.rst, libobs/media-io/video-io.h, libobs/media-io/video-matrices.c, libobs/obs.c
Add VIDEO_CS_2020_PQ and VIDEO_CS_2020_HLG for future Rec. 2020 support.
HDR is coming.
=> libobs: Add Rec. 2020 video_colorspace enum values

UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp, libobs/obs-scene.c
Add Copy  and Paste options to the source visibility menu.
Allows you to set the same transition on multiple sources without configuring each one.
On windows 64bit by copy and pasting source visibility transitions.
=> UI: Add Copy/Paste for source visibility transitions

libobs/obs.c
OBS can crash when recording again after resetting video after a previous record.
Crash repro no longer crashes.
=> libobs: Fix stale active_copy_surfaces entries

docs/sphinx/reference-sources.rst, libobs/CMakeLists.txt, libobs/data/area.effect, libobs/data/bicubic_scale.effect, libobs/data/bilinear_lowres_scale.effect, libobs/data/color.effect, libobs/data/default.effect, libobs/data/default_rect.effect, libobs/data/lanczos_scale.effect, libobs/obs-internal.h, libobs/obs-scene.c, libobs/obs-source-transition.c, libobs/obs-source.c, libobs/obs-source.h, libobs/obs.h
This provides the framework for automatically compositing SDR and HDR
sources together. Source will need to leverage the new
video_get_color_space to opt into HDR support.
HDR spaces are coming, not just sRGB anymore.
HDR branch
PR branch
=> libobs: Add color space management

.github/workflows/main.yml
Adds short commit hashes (as known from GitHub) to artifacts generated by the "BUILD" workflow.
Allows easier separation and identification of downloaded artifacts on local machines.
Will be tested after successful CI run.
=> CI: Add shortened commit hashes to generated workflow artifacts

deps/media-playback/media-playback/closest-format.h, deps/media-playback/media-playback/media.c
Avoid conversion to UYVY422 for 422P video input files (like dnxhd or xdcam422)
YUV422P is currently converted to UYVY before using it.
Obs have a dedicated video format for this (I422). Use it to avoid pixel conversion to UYVY
Mac os 11.6.2
Xcode
Tested with DnxHD 422 and XDcam files
=> obs-ffmpeg : use I422 for YUV422P input format

.github/workflows/main.yml, CI/build-windows.ps1, CI/windows/01_install_dependencies.ps1, CI/windows/02_build_obs.ps1, CI/windows/03_package_obs.ps1
Changes architecture identifiers for Windows build scripts to `x86` and `x64` to avoid possible localisation issues.
Current build scripts rely on comparing a architecture string provided
by the OS which will be localised in certain languages.
This change uses a boolean 64-bit flag to use script-defined identifiers
to avoid this issue.
Fixes #6229.
* Built OBS via the scripts from PowerShell using `x86` and `x64` identifiers.
=> CI: Fix Windows build scripts relying on localized architecture string

cmake/Modules/ObsHelpers_macOS.cmake
Fixes broken recording functionality on macOS when running OBS from Xcode.
When using `install`, CMake will fix up a binary's rpath entries automatically. As `install` is also used to copy all build artifacts into a common runtime directory, this will lead to independent binaries such as "obs-ffmpeg-mux" to be fixed up to run within a fully portable app bundle.
Yet during development, the app bundle is not fully portable, so rpath entries to e.g. libobs need to be retained. Using CMake's `install PROGRAMS` variant will achieve just that.
OBS built, run, and recording created straight from Xcode.
=> cmake: Fix obs-ffmpeg-mux missing rpath entries for libobs in build tree

cmake/Modules/ObsHelpers.cmake, cmake/Modules/ObsHelpers_Windows.cmake, plugins/win-capture/get-graphics-offsets/CMakeLists.txt, plugins/win-capture/graphics-hook/CMakeLists.txt, plugins/win-capture/inject-helper/CMakeLists.txt
Fixes `win-capture` support files not being copied into the runtime directory for testing. Also fixes hooks and helpers not being detected and copied into `ProgramData` by OBS in turn.
The `add_target_resource` function uses unnecessary path components when copying files to the rundir, resulting in files added that way not to end up where OBS expects them to.
The generated binaries created by sub-targets also need to be copied as part of `win-capture`'s data files, which was easy to fix as the target exists before CMake switches into the subdirectories.
Build OBS on Windows 11 in Debug config, confirmed `dll` and `pdb` files ended up in support directory of `win-capture` and library was copied to `ProgramData` upon launching OBS.
=> win-capture: Fix added resources not properly copied to rundir

cmake/Modules/ObsHelpers_macOS.cmake
Check empty OBS_MODULE_LIST and OBS_SCRIPTING_MODULE_LIST before use them, since empty list leads to add_dependencies() failure.
Don't fail when -DENABLE_SCRIPTING=OFF.
On MacOS, tested with -DENABLE_SCRIPTING=OFF and -DENABLE_SCRIPTING=ON.
* Bug fix (non-breaking change which fixes an issue)
=> cmake: check empty OBS_MODULE_LIST and OBS_SCRIPTING_MODULE_LIST on macOS 

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-source-select.cpp, docs/sphinx/reference-scenes.rst, libobs/obs-scene.c, libobs/obs-scene.h, libobs/obs.h
Nonlinear blending is useful to emulate blending behavior of other applications.
This is mainly for the browser source, since the web will probably never change to use linear color blending.
- Verified in RenderDoc that alpha blending for browser source behaves as expected when "SRGB Off" method is used, and linearly when "Default" method is used.
- Setting is preserved when source is copy/pasted.
- Setting is preserved across OBS restarts.
- Localized strings appear correctly in English.
=> libobs,UI: Add support for nonlinear SRGB blending

plugins/obs-filters/scale-filter.c
Undistort checkbox should be ignored if bilinear lowres effect is used.
Fix regression caused by #6206.
Clear rectangle without fix; proper draw with fix.
Undistort checkbox still works with bicubic and lanczos.
Checked bicubic, lanczos with and without undistort. Also checked point/bilinear/area this time.
=> obs-filters: Fix scale undistort, attempt two

plugins/aja/aja-source.cpp
- Set the colorspace to 601 for SD video and 709 for HD/UHD/4K video
- Set video range to VIDEO_RANGE_PARTIAL
The AJA source plugin had the colorspace and video range set to `VIDEO_CS_DEFAULT` and `VIDEO_RANGE_FULL` respectively. This change tells OBS to use the colorspace `VIDEO_CS_601` for SD video and `VIDEO_CS_709` for HD/UHD. Additionally, partial range should be used by default with the AJA card at this time. I need to do some digging to find out what our support for full range looks like before enabling a path for that.
The colors looked washed out when capturing video with the AJA source plugin. Setting the correct colorspace matrices for SD (601) and HD/UHD (709) fixes this.
Washed out video (current version)
Fixed colors (with this PR)
Tested with SD, HD and UHD/4K formats …
=> aja: Use correct colorspace/range for SD or HD/UHD/4K

libobs-winrt/winrt-capture.cpp
Try harder to avoid crashing when capture is in a dead state.
Not sure how normal operation would lead to `active = false` -> `RebuildDevice` without `winrt_capture_free` being called in between, but it wouldn't kill us to add these checks, so just add them. Don't want our users to crash just because I can't force it to happen.
Copied from stream-labs/obs-studio#416. Not taking the active check because it will 100% early exit since we set active to false on device loss entry.
=> libobs-winrt: Add null checks to capture

libobs/obs-video.c
Change int/size_t compare to size_t/size_t compare.
Saw a warning for it that I can't reproduce for some reason.
Debugger inspection of loop using x264.
=> libobs: Fix sign mismatch

cmake/Modules/ObsHelpers_macOS.cmake
Fixes plugins not being copied into the application bundle for macOS builds.
Makes the check for the number of plugins in the global list an explicit length check (not relying on CMake implicit functionality), also moves it in line with how the same was solved in `ObsHelpers.cmake` globally.
Built OBS with a fresh build directory on macOS and checked application bundle contents.
=> cmake: Fixes plugins not being copied into application bundle on macOS

plugins/obs-transitions/CMakeLists.txt, plugins/obs-transitions/data/fade_transition.effect, plugins/obs-transitions/transition-cut.c, plugins/obs-transitions/transition-fade.c
Both transitions are capable of passing through HDR sources now.
Also update VS solution to list transition effect files.
Need transitions to support HDR to render their HDR scene children.
HDR scenes were being tonemapped behind these transitions before, and now they aren't.
SDR scenes continue to look SDR.
Tested fade transition for scenes and sources using SDR & HDR.
=> obs-transitions: Add HDR support to cut/fade

docs/sphinx/reference-sources.rst, libobs/obs-source-transition.c, libobs/obs.h, plugins/obs-transitions/data/fade_to_color_transition.effect, plugins/obs-transitions/data/fade_transition.effect, plugins/obs-transitions/transition-fade-to-color.c, plugins/obs-transitions/transition-fade.c
Add logic to avoid unexpected deviation.
Multiple people have noticed that fading a solid color in or out with the same solid color behind creates a blend that deviates from the solid color. It should take a straight line and not change color at all.
Verified all code paths were exercised, and that the image data looked good visually and in RenderDoc.
=> libobs,obs-transitions: Smooth source transition fades

libobs/obs-source.c
Avoid redrawing potentially stale image from previous frame.
Nasty. Confusing.
Draw SDR transition against HDR scene, then hide it. Needs HDR fork to repro. Broken before; fixed after.
=> libobs: Clear image on color convert

plugins/win-capture/cursor-capture.c
Not sure what the previous setup was trying to do. I guess we'll find
out if users complain.
Need to test cursor drawing as part of HDR changes, and I don't want the code doing weird things.
Cursor renders correctly in master and HDR branches.
=> win-capture: Use normal blend equation for cursor

deps/media-playback/media-playback/decode.c, libobs/graphics/graphics-ffmpeg.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Use `avcodec_free_context()` to replace `avcodec_close`
```
* @note Do not use this function. Use avcodec_free_context() to destroy a
* codec context (either open or closed). Opening and closing a codec context
* multiple times is not supported anymore -- use multiple codec contexts
* instead.
*/
int avcodec_close(AVCodecContext *avctx);
```
test using ffmpeg-nvenc on Windows
=> obs-ffmpeg, win-dshow, deps/media-playback: Use recommended API for AVCodecContext

plugins/linux-pipewire/pipewire.c
Fixes a crash when init_obs_pipewire fails.
I was implementing a non-portal based PW backend and had something fail when it crashed here, and noticed it was a problem in the regular code also.
Made `init_obs_pipewire` return FALSE in the regular code base to simulate a failure, which would always crash.
With the fix, it no longer crashes if there is a failure.
=> linux-capture: Don't initialize format info if init_obs_pipewire fails

deps/media-playback/media-playback/media.c, docs/sphinx/reference-libobs-media-io.rst, libobs/media-io/video-io.h, libobs/media-io/video-matrices.c, libobs/obs.c, plugins/aja/aja-source.cpp, plugins/decklink/decklink-device-instance.cpp, plugins/linux-v4l2/v4l2-input.c, plugins/mac-avcapture/av-capture.mm, plugins/vlc-video/vlc-video-source.c, plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/win-dshow.cpp
Video matrix is slightly different based on the number of bits per
channel, so derive from video_format for convenience.
video_format_get_parameters_for_format provides a more accurate matrix
than video_format_get_parameters.
Formats for HDR and high-precision SDR use more bits, so the existing matrix function will be off.
Verified matrix/ranges through debugger inspection.
Checked some SDR/HDR usages, but I don't have equipment to test AJA.
=> Add video_format_get_parameters_for_format

UI/obs-app.cpp, libobs/util/base.c
This makes the behavior of `--verbose` make sense in all places.
Verbosity of stdout was previously hardcoded to INFO, while log viewer and log files had correct verbosity behavior.
- Ran with `--verbose`, got verbose stdout
- Ran without `--verbose`, got standard stdout
=> libobs, UI: Fix `--verbose` logging for stdout

deps/media-playback/media-playback/media.c
More completeness and consistency.
Want accurate video decoding.
Set breakpoints for AVCOL_SPC_BT709 and AVCOL_SPC_BT2020_NCL in get_sws_colorspace, and VIDEO_TRC_SRGB and VIDEO_TRC_PQ in mp_media_next_video, and all media source playbacks looked fine. Needed to modify the code to test get_sws_colorspace to activate the swscale path.
=> deps/media-playback: Fix AVColorSpace usages

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/window-basic-main-outputs.cpp, UI/window-basic-main-outputs.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-settings.cpp, UI/window-basic-settings.hpp, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.h, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.h
This PR allows users to choose to save recordings in split files instead of one monolithic file.
This is a feature requested by the bounty #5078, fixes #5079.
Testing environment: Fedora 34
Without split file (https://obsproject.com/logs/d3-CJPt7fPMJhurR):
With 2-second split file (https://obsproject.com/logs/HhM4wSJUTz7NOom4):
In current implementation, known issues are
- Even though the audio stiched by FFmpeg is ok, the audio read by Kdenlive 21.08.1 shows small glitch at the end of each file. The audio causes slight drift. --> Using video files from a camcorder and saw similar behavior. Minor difference is that Sony's camcorder outputs audio a little earlier than video.
=> Automatic file splitting

UI/forms/OBSBasicSettings.ui, UI/window-basic-main-outputs.cpp, UI/window-basic-main.cpp
The original PR was made with time specified in seconds because it was
useful to debug the behavior. For production, assuming most users want
to specify 10 minutes or more, the time should be specified in minutes.
This PR changes the unit for the settings time in automatic file splitting. Originally it was implemented in seconds but changes to minutes.
The PR #5371 was made with the time settings specified with the unit `second`. However it was useful for debugging, it looks not useful for production since I assume most users want to set 10 minutes or more.
1. Enable Automatic File Splitting.
2. Set Split by Time
3. Specify 1 minute.
4. Start recording for more than 1 minute and check the length of the recording file.
OS: Fedora 34.
- Breaking change (fix or feature that would cause …
=> UI: Set automatic file splitting time in minutes

libobs-opengl/gl-egl-common.c
This replaces direct opengl calls to error handling helpers. Previously
this would cause errors to be misattributed to the next opengl functions
called.
Fixes dmabuf importing returning a texture on failure on kde.
dmabuf imports fail correctly and cursor texture imports no longer report errors.
=> libobs-opengl: Use gl helpers in create_dmabuf_image

.github/workflows/flatpak.yml, .github/workflows/main.yml, CI/freebsd/03_package_obs.sh, CI/linux/03_package_obs.sh, CI/macos/03_package_obs.sh, CI/windows/03_package_obs.ps1
- Hardcode short hash length to 8, as it is not guaranteed that short hashes
are the same length. This caused problems with upload/download action names, as
the hashes sometimes didn't match.
- Fixes Windows installer job, as the download artifact name was incorrect
- Same as above but for the macOS notarize job
Found bugs when testing workflows.
Tested with fork.
=> CI: Fix Windows/macOS release jobs

plugins/win-dshow/win-dshow.cpp
Makes more sense than Rec. 709.
Easy of use.
Verified Rec. 2100 (PQ) is used by default for this setting.
=> win-dshow: Use Rec. 2100 (PQ) by default for P010

UI/window-basic-main.cpp
If the user would minimize to tray instead of taskbar, the
window would flash when clicking show in the tray menu, and
the preview would be disabled. This would only happen on Linux.
Fixes https://github.com/obsproject/obs-studio/issues/3418
- Set OBS to minimize to system tray instead of taskbar
- Clicked show in tray menu to make sure everything worked as expected
=> UI: Fix show/hide toggle with minimize to taskbar

libobs/obs-internal.h, libobs/obs-source-deinterlace.c, libobs/obs-source.c
As titled.
Redundant field/logic is bad.
Stepped through all modified logic in debugger for SDR and HDR videos.
=> libobs: Remove redundant async_color_format member

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-capture.h, plugins/win-capture/dc-capture.c, plugins/win-capture/duplicator-monitor-capture.c, plugins/win-capture/window-capture.c
HDR for DXGI/WGC display capture, and WGC window capture.
Also add fast SDR paths for BitBlt to skip color conversions.
HDR
Breakpoint inspection for all render path permutations.
=> win-capture: Add DXGI/WGC HDR support

plugins/win-dshow/virtualcam-module/CMakeLists.txt
Fixes the Windows virtual cam module not being copied into the runtime directory.
Root issue is the same as in https://github.com/obsproject/obs-studio/pull/6245, namely that the modules are build artifacts of a separate subproject, but are related to the `win-dshow` plugin and are required to be placed in that plugin's data directory.
Tested in Windows 11 VM locally.
=> virtualcam-module: Copy Windows virtual camera files to rundir

cmake/Modules/FindPipeWire.cmake, cmake/Modules/FindWayland.cmake
${WAYLAND_DEFINITIONS} is set to  "-I/usr/include/wayland" on my system
Setting it as INTERFACE_COMPILE_DEFINITIONS leads to CMake emitting "-D-I/usr/include/wayland" in the compiler flags
this breaks the compilation
Instead add WAYLAND_DEFINITIONS as compile option so it just gets appended without adding the superflours "-D"
I was trying to compile OBS for the first time using openSUSE Tumbleweed. I was able to set the dependencies and cmake up, but during compilation GCC throws an error:
> \<command-line>: error: macro names must be identifiers
This is caused by cmake emitting
`cd /home/user/Programming/OBS/obs-studio/build/libobs && /usr/bin/cc -D-I/usr/include/wayland -DENABLE_DARRAY_TYPE_TEST [...]`
-D makes gcc wait for a macro, but instead the include flag follows immediately.
To …
=> cmake: Fix compiler flags from FindWayland and FindPipeWire

deps/media-playback/media-playback/decode.c
`d->decoder` should be free by `avcodec_free_context`, instread of `av_free`
use correct API to free context
test switching files for media source on Windows
=> deps/media-playback: Use avcodec_free_context to free AVCodecContext

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.h
Necessary for video player to remap display ranges.
Want HDR to look good.
Verified max luminance metadata appears in VLC for Rec. 2100 (PQ), but not Rec. 709 for direct NVENC, and FFmpeg output.
=> obs-ffmpeg: Add max luminance metadata for PQ

UI/volume-control.cpp, libobs/obs-audio-controls.c
Audio sources that have not yet output (or whatever) any audio currently
do not know which speaker configuration and how many channels the audio
will have, so the audio mixer defaults to 1.
This changes this to 2 since the majority of sources are stereo.
Browser source that hasn't put out any audio yet:
This changes how `obs_volmeter_get_nr_channels` works (it will now default
to 0 if the number is unknown instead of 1), technically making it a breaking
change. However, that function is neither documented in the docs (like the
rest of `obs-audio-controls.h`, I'll maybe write that in the future, but don't
really have the time right now) nor used anywhere else in OBS; so I'd personally
assume plugins don't use it and find it safe enough to make this change.
From Warchamps list
macOS 12.3, …
=> libobs, UI: Default mixer volume meter to two channels

plugins/win-dshow/CMakeLists.txt, plugins/win-dshow/win-dshow.cpp
New file added to keep vendor concerns out of device.cpp.
Needs https://github.com/obsproject/libdshowcapture/pull/44 to compile.
Need hardware-specific pokes to support HDR.
Code compiles
=> win-dshow: Reference new device-vendor.cpp file

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
Want to avoid receiver gamut remapping from Rec. 2100 to P3.
Fix min luminance appearing as NaN by switching from 0/0 to 0/1.
Also set max luminance for HLG because why not.
Hopefully better-quality processing for viewer.
Verified metadata for PQ/HLG recordings in VLC and mkvtoolnix.
Not sure how to round trip test the FFmpeg output path, but I at least inspected the AVMasteringDisplayMetadata struct in debugger had the right values.
=> obs-ffmpeg: Set P3-D65 metadata for HDR

CI/check-format.sh
Objective-C files end on `.mm`, not `.m,`, so that's what the formatter should look for.
When, looking at #5449, I noticed some tabs were instead spaces and wondered
why it didn't get changed when running the formatter locally and why the check
didn't fail.
Turns out that typos are bad.
Objective-C is uncommon enough in this project that just no one has noticed yet,
but that also means that no files have been modified during the time where this was
wrong and on current master all files are still properly formatted.
=> CI: Fix clang-format to include Objective-C

deps/media-playback/media-playback/closest-format.h
Used by HDR media playback with hardware decode.
Noticed HDR video is invisible when used for stinger transition, which enables hardware decode by default. (Stinger still needs more fixing for HDR though.)
HDR video is now visible.
=> deps/media-playback: Add P010 to closest_format

libobs/obs-source.c
Need premultiplied alpha for this, not straight alpha.
Noticed modified luma wipe was glitchy during color space testing, and used RenderDoc to debug.
Same luma wipe scenario is now clean.
=> libobs: Fix color space auto-convert blending

plugins/obs-transitions/data/luma_wipe_transition.effect, plugins/obs-transitions/data/slide_transition.effect, plugins/obs-transitions/data/swipe_transition.effect, plugins/obs-transitions/transition-luma-wipe.c, plugins/obs-transitions/transition-slide.c, plugins/obs-transitions/transition-swipe.c
Updated luma wipe, slide, and swipe.
Only transition left is stinger, but that one is a bit more complicated.
Need to update transitions to support HDR, or they will clamp to SDR.
Tested various SDR/HDR permutations of output settings and sources.
=> obs-transitions: More HDR support

libobs/obs-source.c
Leave a log message when the difference between `timestamp` and `next_audio_ts_min` exceeds TS_SMOOTHING_THRESHOLD.
When a user reported audio glitch happening every several ten minutes, the user should be suggested to add `--verbose` option.
Timestamp of some of audio sources gradually desync over the time and audio glitch is suspected to be caused when the desync exceeds the threshold, leave a log message to investigate the glitch of the audio as reported in #4600.
OS: Fedora 34
Hardware: MOTU M2 (suspecting ~90ppm slower oscillator)
Log shows these entries and I saw an audio glitch at the point ~1 second later than this log.
```
17:56:10.315: Audio timestamp for 'Mic/Aux' exceeded TS_SMOOTHING_THRESHOLD, diff=70026420 ns, …
```
=> libobs: Log audio timestamp exceeding TS_SMOOTHING_THRESHOLD

.github/workflows/steam.yml, CI/steam/obs_build.vdf, CI/steam/scripts/install.bat, CI/steam/scripts/installscript.vdf, CI/steam/scripts/uninstall.bat
Adds a GitHub actions workflow as well as necessary files for Steam build to be uploaded directly from this repo.
This is version 1 of this workflow, which does not yet account for M1/Apple Silicon builds. Once we get closer to starting the beta phase of the next release and have decided on a naming scheme for builds, whether to use universal builds for Steam, etc. the action will be updated to a "v2".
OBS is now on Steam, we don't want to have to deal with manually uploading builds. As originally proposed in https://github.com/obsproject/rfcs/pull/30 this adds the necessary automation via GitHub actions.
Thanks to [OpenTTD](https://github.com/OpenTTD/OpenTTD) whose workflow has served an inspiration for this version.
A number of runs of various iterations on my own repo: …
=> CI: Add Steam build uploader

.github/workflows/steam.yml
Only runs Steam CI workflow when running on the obsproject org.
People complained about emails.
Tried running it on my repo, job was skipped.
=> CI: Do not run Steam workflow on forks

libobs-opengl/gl-x11-egl.c
Brings X11 EGL in line with Wayland. This prevents you from recording at
a higher fps than the monitor where an OBS preview is being displayed.
Noticed during testing X11 egl.
OBS renders at 144fps when the display is set to 60fps and the preview is enabled.
=> libobs-opengl: Disable vsync during present

plugins/win-dshow/ffmpeg-decode.c
Fixes colors for devices that send HDR streams.
Want correct HDR colors.
Checked Elgato 4K60 S+.
=> win-dshow: Respect TRC of encoded video

plugins/aja/aja-source.cpp
Subtract the audio packet time from the timestamp for audio.
The code is copied from `pulse-input.c`.
When calling `obs_source_output_audio`, timestamp should be the starting time of the audio packet.
OS: Fedora 34.
Hardware: AJA Video Kona 4 (connected to the top PCIe slot)
CPU: Intel Core i7-11700
MB: ASRock Z590 Extreme (no GPU card is installed)
Camera: Sony SRG-120HD (configured to send 1080p59.94)
I found the bug during implementing another PR #6351.
The implementation was tested with debug information in the change of the PR.
=> aja: Subtract packet time from audio timestamp

plugins/obs-transitions/data/luma_wipe_transition.effect, plugins/obs-transitions/data/slide_transition.effect, plugins/obs-transitions/data/swipe_transition.effect
Leftover from previous commit.
Don't like to leave a mess.
Verified all three transitions still work.
=> obs-transitions: Remove unused shader functions

CI/windows/02_build_obs.ps1
The Windows build script would respect the user-specified build directory for the configure step, but not for the build step. Fix that by applying the same logic in Configure-OBS to Build-OBS.
We don't want to clobber the default build32 or build64 directories if the user specifies a build directory.
I ran the build script locally before and after this change to confirm this works as expected.
=> CI: Respect user-specified build directory

UI/source-tree.cpp, libobs/obs-scene.c
I identified a deficiency in the API wherein using group and ungroup actions would not issue the expected `item_add` and `item_remove` signals. I've put together a basic implementation that meets my expectations for the API behavior in that regard.
The `item_add` signal is issued after all of the scene items are re-parented to the new group, and the `item_remove` signal is issued right before the group is modified. This allows the API consumer to more easily inspect the group's contents in a meaningful manner.
Unfortunately a side effect I noticed was that the UI's logic for inserting the group row in the sources list had a conflict with the newly issued signal, as the `item_add` signal was introducing a row for the new group automatically. I just went with the least intrusive option, …
=> libobs,UI: Issue appropriate signals on group / ungroup

libobs/util/c99defs.h, plugins/obs-outputs/CMakeLists.txt
Details in #6226, basically this fixes an issue where OBS links to the system-installed librtmp1, which is incompatible with our librtmp.
Closes #6226 
Spent all day trying to fix an ambiguous issue only to find that this hasn't been PR'd yet.
Without PR: OBS crashes when starting stream to RTMP server
With PR: No OBS crash any longer
=> libobs,obs-outputs: Fix librtmp1 dependency interference on some linuxes

libobs/data/color.effect
The NaNs cause green in areas of black.
We were previously using `max(0., x)` to remove NaNs, but the instruction seems to disappear when shader optimizations are enabled. MS says it sounds like an FXC bug, but they don't work on that shader compiler anymore, so hopefully this workaround for the workaround will hold up.
Want black to be black.
Verified black is now black in HLG recordings where the EETF is triggered, HDR nominal peak greater than 1000, 10000 in the test case.
=> libobs: Fix NaNs when using EETF for HLG

UI/window-basic-main-outputs.cpp, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Some format checks were causing 10-bit videos to save as 8-bit when using old NVENC, and just needed updating.
8-bit HDR is a bad look.
Verified video metadata comparison with ffprobe, and banding reduction visually.
=> Fix I010/P010 video saving as 8-bit for old NVENC

libobs/media-io/media-remux.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
Add content light levels (MaxCLL/MaxFALL) to video streams. Should note that we're not computing these; we're just assuming worst case from user setting.
Also update remux to preserve content light levels and mastering display metadata from input video stream.
YouTube wants the content light levels, and more metadata is probably useful for compatibility in general.
Verified MKV in mkvtoolnix, and mastering display metadata from remux with ffprobe. ffprobe does not appear to print the content light levels, but I verified that in a binary diff with Beyond Compare. FFmpeg output was tested a little lax, I just stepped through the code in a debugger.
=> More HDR metadata work

UI/window-basic-main.cpp, UI/youtube-api-wrappers.cpp, libobs/obs-source.c, plugins/aja/aja-presets.cpp, plugins/obs-filters/color-correction-filter.c, plugins/win-capture/get-graphics-offsets/d3d9-offsets.cpp
Fix indent of 2nd line and later for multiline comment blocks.
The most frequent comment indentation style is as below. I followed this style to update comments.
- Indent the first line of a comment with tab(s).
- Indent remaining lines with the same amount of tab(s) + one space so that the first `*` is vertically aligned.
Some comment blocks are ugly indented like below. `clang-format` did not touch the indent of comments.
https://github.com/obsproject/obs-studio/blob/a82bbb416f84461172224ac33d59d281668e17e0/libobs/obs-source.c#L1508-L1513
`git show -w` shows nothing was changed.
Ran `./CI/check-format.sh` and the updated indent is not modified on Fedora 34.
=> Fix indent on multiline comments

plugins/obs-outputs/librtmp/rtmp.c, plugins/obs-outputs/librtmp/rtmp.h
This fixes a bug where the RTMP send thread can deadlock upon the underlying TCP connection being broken. By introducing a send timeout, this allows the thread to unblock and give up, triggering a reconnect as normal. The correct solution to this problem would be to rewrite librtmp with asynchronous IO, but that seems like something unlikely to happen.
Having the TCP connection between OBS and the media server broken has been pretty common in my experience, and OBS currently doesn't handle this very well. If this happens, you usually have to either force close OBS or wait an indefinite amount of time for it to give up on the connection naturally.
**Before**:
- Start stream in OBS
- Use tool (pfSense) to invalidate connection state
- OBS bitrate drops to 0
- Output does not respond to stop …
=> obs-outputs: Implement send timeout in librtmp (Fix RTMP output deadlock)

plugins/obs-libfdk/obs-libfdk.c
Remove `#ifndef __linux__` below.
https://github.com/obsproject/obs-studio/blob/7eb36eadb13c7581dd942377945cf71912e0f552/plugins/obs-libfdk/obs-libfdk.c#L138-L142
The surround audio was introduced by bbac3280c1 but 7.1 channel audio was disabled since libfdk-aac >= 0.1.3 is required. Now the minimum Ubuntu version is 18.04, which provide libfdk-aac 0.1.5. It is not necessary to exclude Linux now.
Tested on Fedora 34.
=> obs-libfdk: Enable 7.1 channel surround for Linux

libobs-opengl/gl-egl-common.c
[xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr) just got support for explicit modifiers. The negotiation process to find a working format modifier pair requires the client to import a buffer and renegotiate if the import failed. This patch prevents obs from crashing after a failed import which helps immensely in completing the search.
------------------------ Original commit message --------------------------------------------------
This replaces direct OpenGL calls to error handling helpers. Previously
this would cause errors to be misattributed to the next OpenGL functions
called.
Fixes DMA-BUF importing returning a texture on failure on KDE+NVIDIA.
Use obs with xdg-desktop-portal-wlr from master on a Computer supporting explicit modifiers.
- Bug fix …
=> backport: libobs-opengl: Use gl helpers in create_dmabuf_image

UI/forms/OBSBasic.ui
The scrollbars were always set to be on, no matter
how many volume controls that were being used.
It was brought up before that the scrollbars were always on because of rendering problems, but after some testing, I found that everything still works as expected.
Fixes https://github.com/obsproject/obs-studio/issues/5905
Made sure scrollbars only showed up when needed.
=> UI: Only use volume scrollbars when needed

libobs-winrt/winrt-capture.cpp
WGC capture is at the compositor level, so it's less quirky than the
BitBlt path would be.
Rounded corners in Windows 11 work. LiveSplit shenanigans do not.
Want to support transparency without making the behavior too weird.
WGC window and display capture still work, and window corners respect transparency.
=> libobs-winrt: Support window transparency for WGC

.github/workflows/flatpak.yml, .github/workflows/main.yml
The action repo recommends using the checksum of the manifest as cache key. The hash of the last commit is actually used.
Note: This error `Error: Failed to save cache: ReserveCacheError: Unable to reserve cache with key flatpak-builder-7d9a9401dcf04743a57b8f438d60bc4a2e3767630734d301da849c9de8c14668, another job may be creating this cache.` will always appear because the cache with those deps already exist. **But it will not fail the job.**
- Create a cache with a better key to reduce build time on flatpak CI.
- The command to generate the hash was tested in a terminal inside an OBS repo.
- After many forced push on a test PR on my repo, I confirm that the new cache key can speed up the CI compilation time since it only compile OBS except if the manifest is changed.
- CI improvements
=> CI: Use manifest hash as Flatpak cache key

cmake/Modules/CopyMSVCBins.cmake
Fixes functionality in `CopyMSVCBins` when cURL is imported as a CMake package (instead of being discovered using a "finder" module).
Soon to be updated obs-deps built on CI will retain CMake package files created while building dependencies. When CMake uses packages, the usual triplet of variables from finders are not set. `CopyMSVCBins` relies on one such variable.
This PR sets the `CURL_INCLUDE_DIR` if the cURL target is present, but apparently imported as a CMake package, to ensure prior functionality is restored.
* Recent obs-deps from rework PR set up for building OBS
* Purged contents of "additional_install_files" directory
* Purged "rundir" inside OBS build directory
* Purged "cURL"-related cache variables in CMake cache
* Reconfigured and built OBS
* Ran OBS successfully
- Tweak …
=> cmake: Fix cURL library handling for updated dependencies

UI/auth-oauth.cpp, UI/auth-youtube.cpp, deps/media-playback/media-playback/decode.c, deps/obs-scripting/obs-scripting-python.c, deps/obs-scripting/obspython/obspython.i, libobs/obs-video.c, plugins/linux-v4l2/v4l2-output.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c, plugins/obs-outputs/net-if.c, plugins/obs-outputs/rtmp-stream.c, test/cmocka/test_bitstream.c, test/cmocka/test_darray.c
This PR is meant to fix some compilation warnings, ignoring FFmpeg deprecation, AJA NT2 and FTL related ones:
- obs-ffmpeg-vaapi emits a format-overflow warning.
- obs-outputs emits a warning because of a pointer type mismatch in conditional expression and an unused-parameter warning.
- v4l2-output emits a format-truncation warning.
-  media-playback, test/cmocka and obs-ffmpeg emits unused parameter warnings in the CI.
- obs-scripting: PyEval_InitThreads() and PyEval_ThreadsInitialized() are deprecated since Python 3.9. Fixes based on https://github.com/swig/swig/commit/9c50887daa2b44251e77be8123c63df238034cf5.
- obs-scripting (python wrap) emits a warning because of an unused parameter. A workaround to put the parameter as in a `UNUSED_PARAMETER()` was made. It really just adds …
=> Fix some compillation warnings that appear on Linux

libobs/graphics/graphics-ffmpeg.c
This change will orient images based on whether there is an Orientation flag in the EXIF metadata for an image.
Images which require the Orientation field to display correctly (such as portrait photos from most phones) can now be brought in without needing to be edited prior.
I used the following test data set and confirmed that all images show as expected: [https://github.com/recurser/exif-orientation-examples](https://github.com/recurser/exif-orientation-examples)
=> libobs: Orient images based on EXIF metadata

plugins/obs-ffmpeg/jim-nvenc.c
Fix NVENC HEVC fallback routing.
Don't want unexpected H.264.
Verified video metadata for H.264 and HEVC fallback paths forced by moving instruction pointer in debugger.
=> obs-ffmpeg: Fix NVENC HEVC fallback being H.264

plugins/vlc-video/vlc-video-source.c
This fixes issue https://github.com/obsproject/obs-studio/issues/6295 .
libvlc does some downmixing/upmixing when the number of channels
requested is less than the number of channels of the source.
We take advantage of that feature to avoid doing it with swresample
because we're missing info that libvlc is not giving (the exact channel
layout of the source).
Fixes a bug.
**Important Note**
- surprisingly libvlc does not provide any speaker layout info about a source it decodes. I checked with ePirat. This is a real bummer because this means we can't let swresample do its usual task of downmixing or upmixing to the output speaker layout.
- the libvlc audio callback has however an interesting feature which I haven't seen documented, which is if we request less channels than the original …
=> vlc-source: Fix surround sound not properly downmixed

plugins/obs-x264/obs-x264.c
Thought the encoder name was redundant when I removed it, but it's a different meaning of encoder.
Want logging to be as good as it was.
Verified warn and warn_enc macros work properly.
=> obs-x264: Restore video encoder name to log

plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
See individual commit descriptions for details.
Correctness and user-friendliness.
=> Various NVENC B-frame improvements

plugins/vlc-video/vlc-video-plugin.c, plugins/vlc-video/vlc-video-plugin.h, plugins/vlc-video/vlc-video-source.c
Fixes rotation and aspect ratio of VLC Video Source videos. Only works for local video files - video streams will still be incorrect (https://github.com/obsproject/obs-studio/issues/2933) and will need to be dealt with separately.
Cause: previously, the buffer size passed from libvlc was being used as the video size, but this was often incorrect as the buffer size could be rounded up to the next multiple of 32. This was then "fixed" by getting the pixel size of the original video file, however it didn't take into account rotation or aspect ratio attributes. This PR addresses this.
Fixes #5250 - portrait videos (e.g. from phones) being rendered with incorrect aspect ratio.
Also fixes #3843
Tested on macOS 11.5.2 on Intel and 12.3.1 on Apple silicon. Ran several videos of different …
=> vlc-video: Fix video rotation and aspect ratio

cmake/Modules/ObsHelpers.cmake, cmake/Modules/ObsHelpers_Linux.cmake, cmake/Modules/ObsHelpers_Windows.cmake, cmake/Modules/ObsHelpers_macOS.cmake, libobs/CMakeLists.txt, plugins/obs-ffmpeg/jim-nvenc.c
- Stop including `obs-hevc.{h,c}` in sources target if HEVC is disabled with a fix for `jim-nvenc`
- Headers are now installed per default on Linux
- `obs-hevc.h` is not installed if HEVC is disabled
- OS exclusive headers are no longer installed on the wrong OS
This needed to be fixed so I fixed it.
The HEVC change was made at the same time since the HEVC header is not required if disabled.
- Linux OBS Portable installation have headers without Windows or macOS headers
- OBS build with HEVC disabled or enabled
=> CMake headers installation fix with HEVC include fix

UI/obs-app.cpp
Fixed portable mode regression.
Portable mode is useful for testing.
Verified portable mode on Windows is enabled with text file, and disabled without.
=> UI: Restore portable mode on Windows

libobs/data/format_conversion.effect, libobs/obs-internal.h, libobs/obs-source-deinterlace.c, libobs/obs-source.c
Not normally a valid combination, but Xbox writes 8-bit HDR videos.
Want to view Xbox HDR videos with "proper" colors.
Verified Xbox HDR video matches VLC playback. Also checked real HDR and SDR videos for regressions.
=> libobs: Add support for reading I420 PQ

libobs/data/color.effect
Avoid redundant math. Doesn't seem to help FXC DXBC output, but maybe some shader compiler might not be smart. And less is less.
Don't like redundant logic.
Verified PQ input and output look reasonable.
=> libobs: Reduce PQ shader math

libobs/data/color.effect
Replace `common` with `c` in `color.effect`.
After the commit 0f53dc28b, OBS Studio fails to initialize. The use of the reserved name caused initialization failure on Linux with log lines as below.
```
Error compiling shader:
0:37(8): error: illegal use of reserved word `common'
0:37(8): error: syntax error, unexpected ERROR_TOK, expecting ',' or ';'
```
https://obsproject.com/logs/WU5thNosIFxNkekN
Tested on Fedora 34.
=> libobs: Fix reserved word in variable names

UI/CMakeLists.txt
WinExtras does not exist in Qt 6. Only try to find it and link against it if using Qt 5.
Maintain compatibility with Qt 5 and Qt 6.
Was able to successfully run cmake locally against Qt 5 and Qt 6.
=> UI: Find Qt WinExtras only in Qt 5

UI/window-basic-main-dropfiles.cpp, libobs/graphics/graphics-ffmpeg.c, libobs/graphics/graphics.h, libobs/graphics/image-file.c, libobs/graphics/image-file.h, libobs/obs-source-transition.c, plugins/image-source/image-source.c
Add JXR support via WIC. Just support HDR JXR images written by Xbox Game Bar for now. We can get fancier later.
We can try adding jxrlib support on Mac/Linux another day.
JXR images are written by Xbox Game Bar on Windows.
Tested image source with JXR and PNG. Verified filter bypass optimization still works for SDR. Random non-HDR JXR image from Internet fails gracefully.
=> libobs,image-source,UI: Add JXR support on Windows

deps/obs-scripting/obs-scripting-python-import.c, deps/obs-scripting/obs-scripting-python-import.h
Fixes `frontend-tools` not being loaded on macOS when Python scripting is enabled.
Issue was introduced in 4c1687901ecfc99b1fd0d810e86e9deff5497b2d in an attempt to remove compiler warnings.
* Tested with enabled Python scripting on local macOS builds.
=> obs-scripting: Fix loading of scripting libraries with runtime lookup

UI/forms/OBSBasic.ui
Changes the shortcut for Copy/Paste Transform from `Ctrl/Cmd+Alt+C/V` to `Ctrl/Cmd+Shift+C/V`.
Being introduced in #6038 this shortcut has not yet been shipped in production, so it can safely be changed.
I wasn't aware at the time of the original PR, but it appears to be general consensus that Shift should be used as a secondary modifier, with Alt being a tertiary (or not used at all). Both the UX guidelines of Apple and Microsoft agree on this, we should adhere to that principle as well.
[Apple](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/):
> - Prefer the Shift key as a secondary modifier when a shortcut complements another shortcut. [...]
> - Use the Option [Alt] key as a modifier sparingly. If a third, less-common command is related to …
=> UI: Use Shift instead of Alt for Copy/Paste Transform

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp
The names wouldn't be updated in the advanced audio dialog
when the source is renamed.
Noticed named weren't being updated.
Renamed source and made sure the name was updated in the dialog.
=> UI: Add rename signal to adv audio dialog

libobs/obs-scene.c
Fixes studio mode preview on SDR monitor for HDR canvas rendering SDR
source into SDR swap chain. Needs to render SDR source into HDR render
target, and then tonemap into SDR swap chain for preview.
Want Studio Mode preview and program views to match colors.
Checked SDR on SDR, SDR on HDR, HDR on SDR, and HDR on HDR for both sides of studio mode.
=> libobs: Lock scene to video color space

libobs/obs-source.c
Follow BT.2408 recommendation and cap HLG at 1000 nits.
Don't want uncomfortably bright HLG video on bright monitors. Parity with future Chromium implementation.
Check 400/1000/2000 nits on PQ for regressions, and they all look the same.
Check 400/1000/2000 nits on HLG, and 2000 used to be brighter, but is now the same as 1000.
=> libobs: Cap HLG video at 1000 nits

docs/sphinx/reference-libobs-util-platform.rst, libobs/media-io/audio-io.c, libobs/util/platform-nix.c, libobs/util/platform-windows.c, libobs/util/platform.h
This PR implements a new function `os_sleepto_ns_fast`, which sleeps in a low precision but won't return until reaching the specific time.
This change introduces `os_sleepto_ns_fast` to the audio thread so that the audio packets will be periodically output.
Prior to this change, the audio thread roughly waits the time of `AUDIO_OUTPUT_FRAMES`, which is hard coded `1024`, and consecutively processes twice or more if the latency is accumulated. This behavior caused fluctuation of timing to output audio packets and affects audio buffering in decklink output.
The amount of audio buffer is monitored with a temporary commit db923d1f3b5eacae79275b489e0758af09aaa451, which is one more commit ahead of #1865 for logging purpose.
The buffer size in decklink is monitored at just before sending new …
=> libobs/media-io: Sleep to next audio time accurately

plugins/linux-v4l2/CMakeLists.txt, plugins/linux-v4l2/v4l2-input.c
It is a small fix of obvious cmake typo
Unable to add device after OBS start.
Ubuntu 20.04
Tested with c920
Start OBS without any webcam plugged in.
Plug camera
Click Sources -> Video Capture Device
Preview is not available.
The reason is that device_added is never called. HAVE_UDEV is not set correctly by cmake.
HAVE_UDEV was set to ON only when ENABLE_UDEV was set to OFF
=> linux-v4l2: Fix camera reconnecting issue

deps/media-playback/media-playback/media.c, deps/media-playback/media-playback/media.h, plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/obs-ffmpeg-source.c
Added the ability to pass options to the media source to provide ffmpeg which options, such as forcing the RTSP transport protocol 
**This is a feature for the Media Source but does require code change in the obs-ffmpeg plugin.**
This adds one additional free text entry field at bottom of the media source dialogue
This was added so that obs can be configured to stream from rtsp devices using TCP, devices that often experience random video corruption when streaming over UDP.  This corruption usually presents as near the bottom of a video frame, as shown and discussed below
https://github.com/obsproject/obs-studio/issues/3684
I've tested this heavily on 64bit Windows 10, and on Ubuntu Focal x64.
Performance enhancement (non-breaking …
=> obs-ffmpeg: Add ability to set FFmpeg options

libobs/media-io/media-remux.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
The upgrade to FFmpeg master introduces
several issues:
- avcodec/version.h is no longer included in codec.h; avformat.h
doesn't carry the avcodec version any more.
- the new channel layout APIbreaks obs-ffmpeg-audio-encoders,
obs-ffmpeg-mux & obs-ffmpeg-output.
Allow for a later upgrade to FFmpeg 5.
**Note:**
- I removed the convert_ff_channel_layout which is not compatible with
the new API; it is replaced by code which has compatibility with both
old and new channel layout API.
- I added an ffmpeg-mux fix for 4.0 channel layout.
obs-studio compiles (on win 10 x64, vs2019).
The FFmpeg audio encoders work (tested with streaming and recording).
The obs-ffmpeg-output works too.
FFmpeg version tested: 
- master branch on commit https://github.com/FFmpeg/FFmpeg/commit/944b8c96c90ae050606e638f7 …
=> obs-ffmpeg: Several fixes allowing support of FFmpeg 5

UI/window-basic-main.cpp
UI: Fix memory leak with Manage Broadcast dialog
When OBS has been connected to a YouTube account, the Manage Broadcast dialog becomes available. Opening and closing this dialog leaks about 2-3 MB of memory each time. This happens because the dialog is never deleted, and a new object is created every time the dialog opens.
If we set Qt::WA_DeleteOnClose on the dialog, then the dialog->exec() call would call delete this. However, if the dialog->Valid() call returned false (this should currently be impossible), then exec is never called, so it would not clean up.
To fix this, make the dialog stack-allocated instead of using new and
delete.
Detected by clang-analyzer.
----
The Qt docs recommend using `dialog->open()` over `dialog->exec()`, but that is a broader change to investigate another …
=> UI: Fix memory leak with Manage Broadcast dialog

libobs/data/format_conversion.effect
Need to truncate 16 bits to 10 bits for accuracy.
Want accurate colors.
Inspected shader math in RenderDoc debugger for all three pixel shaders.
=> libobs: Ignore lower six bits for P010 sources

libobs/obs-internal.h, libobs/obs-source.c
Matches how VLC operates. HDR is only in effect with proper metadata.
Want to behave like other popular programs when no default is specified.
Tested 10-bit video file without video metadata now appears like VLC. PQ and HLG videos still render fine.
=> libobs: Default 10-bit video to sRGB instead of PQ

plugins/win-wasapi/win-wasapi.cpp
Adds additional context to WASAPI error log lines showing the source name that references the device.
Users sometimes have sources or settings pointing to invalid devices which spam the log with initialization errors that only mention the device GUID. Without logging the source name it becomes impossible to figure out which source is responsible.
Forced both CaptureThread and RTWQ modes and disabled my devices while running OBS.
CaptureThread:
```
02:29:38.856: Device 'Line (3- Steinberg UR22C)' invalidated.  Retrying (source: Desktop Audio 2)
02:29:38.865: Device 'Line (3- Steinberg UR22C)' invalidated.  Retrying (source: Desktop Audio 2)
02:29:41.866: [WASAPISource::TryInitialize]:[Line (3- Steinberg UR22C)] Failed to activate client context: 88890004
02:29:41.866: WASAPI: Device …
```
=> win-wasapi: Log source name when showing device errors

plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
OBS always renders HLG for 1000 nits, so reflect that in the metadata even though metadata technically isn't supposed to be needed for HLG.
Hopefully better metadata leads to more accurate playback.
For obs-ffmpeg-mux.c, checked output videos for PQ 400/1000/2000, and HLG 400/1000/2000, and got back 400/1000/2000, and 1000/1000/1000.
For obs-ffmpeg-output.c, just checked values were correct in debugger.
=> obs-ffmpeg: Set 1000 nits for HLG metadata

plugins/vlc-video/vlc-video-source.c
https://github.com/obsproject/obs-studio/commit/5e4081e5637c7b6761ce54d5aef344fa85414e29 / #6424 introduced a sign-compare warning while building OBS.
> obs-studio/plugins/vlc-video/vlc-video-source.c:515:23: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
`out_channels` has no reason to be a signed type. Making it an unsigned one fix the warning.
Less warning the better.
=> vlc-video: Fix sign-compare warning

plugins/obs-ffmpeg/jim-nvenc.c
Cherry-pick of two of #5706 commits. Which are not related to the added feature.
Textures dynamic array is not reserved because of copy-paste miss.
Note: I also renamed the commit.
And mapped_res might never be initialized and nv_texture_free might unmap
a non-existant resource.
I was trying to rebase #5706 and I found those commits.
I can't test it, I don't have a Windows machine with a Nvidia card.
=> obs-ffmpeg: Nitpick/fixes for jim-nvenc

.github/workflows/services-json.yml, CI/check-jsonschema.py, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/schema/package-schema.json, plugins/rtmp-services/data/schema/service-schema-v3.json, plugins/rtmp-services/data/services.json
This adds full JSONSchema definition files for both services.json and package.json, which can be validated using various tools, including an IDE. This includes user-friendly descriptions pulled from [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines).
Additionally, this adds a Python-based validation runner when users submit Pull Requests, informing them of any failing validations directly within the diff.
Unfortunately, I had to write a custom python script to perform complete validation, as none of the existing libraries provide line numbers by default - it's exclusively _paths_ within the JSON structure. Additionally, errors would be poorly formatted and generally hard to read. Instead I have to return a custom JSON result and …
=> Add JSONSchema definitions for services & validate using CI

UI/data/locale/en-US.ini
Changes transition settings from being called "Swap Preview/Output Scenes After Transitioning" to "Swap Preview/Program Scenes After Transitioning", as well as tooltip strings.
In the tooltips, there are instances of "output" left which I *think* are appropriate, but it would be great to have a native English speaker to chime in on this.
It's called "Preview/Program" everywhere else, so that's the terminology we should use.
N/A, string change.
=> UI: Use correct terminology for Program in Studio Mode

.github/workflows/services-json.yml, CI/check-services.py, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adds scheduled/manually triggered workflow run to check if service entries are still valid (i.e. if servers are reachable).
Also reformats the currently hand-formatte d`package.json` and `services.json` with python to get a consistent result.
(Waiting for #6354 to be reviewed/merged)
If a service dies but nobody uses it, does it make a sound?
Well, no. So we have to periodically check ourselves and purge defunct servers/services if necessary.
Ran manually on my fork:
- Workflow run: https://github.com/derrod/obs-studio/runs/6098001774?check_suite_focus=true
- Resuling PR: https://github.com/derrod/obs-studio/pull/5
=> CI: Add automatic service checks

libobs/media-io/audio-io.c
Rearrange comparison order so that NaN is caught.
Comparisons with NaN always result in false.
NaNs cause problems later in audio encoder.
When a NaN (not a number) audio sample is fed to OBS, it immediately stops both streaming and recording because ffmpeg audio encoder doesn't like it.
See #4885, which this patch should theoretically fix, if compiler obeys IEEE semantics (no `-ffast-math` or so).
I have not tested yet.
=> libobs: Clamp audio NaN to 0.0f

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
Removing the first call to `video_output_stop` prevents the `data_mutex` field in `struct video_output` from being destroyed while still in use. The `render_preview_source` function will call `video_output_lock_frame` upon that mutex and encounter a NULL pointer exception.
Co-authored-by: @paulh-aja 
Fixes #5832.
----
This change is from #5891, but for Decklink Output UI. In my experience, the problem results in a hang rather than a crash, but either is bad.
Text from #5891:
Stopping the Preview output in the AJA Output UI can lead to a crash.
**Problem**
The function `preview_output_stop` in `UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp` calls `video_output_stop`, which results in a call to `pthread_mutex_destroy`: https://github.com/obsproject/obs-studio/blob/364f102561faf565ae22e5f …
=> decklink-output-ui: Fix crash when stopping preview

deps/media-playback/media-playback/decode.c, deps/media-playback/media-playback/decode.h
Previous FFmpeg deprecation fix, and optimization attempt causes short
videos to loop badly. Keep deprecation fix, and fix the rest later.
Want video loop to look nice.
Video loop looks nice again.
=> deps/media-playback: Fix video looping

libobs/obs-source.c
Only warn when the pointer provided to obs_source_release() is non-NULL. In some custom usages of libobs, libobs may be freed before OBS* smart pointers (like OBSSource) are destructed, leading to a misleading warning if the pointers have already been cleared with nullptr.
Warnings are being misleading
Previous behavior is basically:
- Clear OBS* pointers with nullptr
- Unload libobs
- Those smart pointers that were cleared will still call obs_source_release() on destruct
- Warning appears
Test with this patch == no more warnings
=> libobs: Only warn when releasing non-NULL source

UI/window-basic-main-transitions.cpp
Fixes an issue where when "Duplicate Scenes" and "Switch Preview/Program
after Transitioning" were disabled and preview and program were the same
scene, pressing "Transition" would just disable the menus without
anything happening. This is because a transition is initiated, but never
actually starts transitioning (since both scenes are the same). The
check for this already exists, but was only triggered in swapScenesMode.
Also renames the newScene variable to lastScene to make it more obvious
what it actually is (especially since now, it's not only the new scene
anymore).
Fix #2748 
macOS 12.4
The scenario above (both "Duplicate Scenes" and "Switch Preview/Output ..."
disabled) no longer breaks the menus by disabling them.
=> UI: Don't transition in studio mode if scenes are the same

plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/obs-ffmpeg-source.c
There are two separate locales for "FFmpeg Options", now there is only one.
Also moves the tooltip up to where the other source options are.
Duplicate locales only cause extra code and work for translators.
macOS 12.4
Made sure for the source both the name and tooltip of the property are shown.
=> obs-ffmpeg: Remove duplicate "FFmpeg Options" locale

UI/forms/OBSBasicSettings.ui
Removes m3u8 (HLS) as a recording format option in simple output mode.
Many users accidentally select m3u8 and then wonder why they have hundreds of 4 second video files. Anyone who actually needs local HLS output is likely an advanced user and can set it up there.
https://obsproject.com/forum/threads/recording-in-4-second-intervals.128706/
https://obsproject.com/forum/threads/obs-only-records-a-series-of-8-second-clips-instead-of-continuous-file.111192/
https://obsproject.com/forum/threads/my-stream-got-saved-as-tons-of-small-ts-files.106669/
https://obsproject.com/forum/threads/recording-creates-multiple-files.121238/
https://obsproject.com/forum/threads/help-obs-records-many-4-second-files-instead-of-one-big-one-after-update.118353/
- Ran OBS, verified m3u8 didn't show up any more.
- …
=> UI: Remove m3u8 format from simple output mode

.github/workflows/services-json.yml, CI/check-services.py
Pings people responsible for modifying affected service entries in the `services.json` file.
Looks like this: https://github.com/derrod/obs-studio/pull/8 (The "@" was ommited for this test to avoid pinging people).
Give service owners an opportunity to fix their entry or servers.
Ran on my fork: https://github.com/derrod/obs-studio/runs/6541019315?check_suite_focus=true
- New feature (non-breaking change which adds functionality) -->
=> CI: Ping authors of failed services in removal PR

plugins/linux-capture/xcomposite-input.c
This was leftover from the cpp conversion where the delete would not
fail, but for darray we need to skip da_erase if its unneeded.
fixes #6532
=> linux-capture: Check da_erase target is valid

deps/media-playback/media-playback/decode.c, deps/media-playback/media-playback/decode.h, deps/media-playback/media-playback/media.c, docs/sphinx/reference-sources.rst, libobs/data/color.effect, libobs/data/format_conversion.effect, libobs/obs-source.c, libobs/obs-video.c, libobs/obs.h, plugins/win-dshow/win-dshow.cpp
Rendering HDR media without EETF may cause brights to get clipped. Use metadata, and reduce overall brightness with EETF where source is brighter than scene.
Only per-stream metadata is checked. Frame-level metadata is ignored.
Don't want to lose bright detail by clipping..
=> Use EETF when HDR media exceeds HDR scene

UI/forms/OBSBasicTransform.ui
This makes it easier to understand what the
values in the dialog mean.
Makes UI better.
Opened dialog to see if the suffixes were correct.
=> UI: Add suffixes to transform dialog

plugins/obs-ffmpeg/jim-nvenc-helpers.c, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/jim-nvenc.h
Add dialog messages for lack of 10-bit support, and exceeding the
hardware B-frame limit. Also move code around to test these just once.
Previous dialog messages for these failures were quite cryptic.
Verified both dialog messages appear as desired. Also verified I was able to record SDR H.264/HEVC & HDR HEVC videos successfully if the checks passed.
=> obs-ffmpeg: Improve dialog text for NVENC errors

libobs/obs-source.c
When `tex` is null in `obs_source_draw_texture`, stop rendering before rendering.
Sometimes decklink source outputs error logs below for every frame when the device does not get a valid input signal (The power of the source is off, for example.)
```
A sprite cannot be drawn without a width/height
```
Confirmed the log message does not appear on Fedora 34.
Also concifmed the video is rendered when a valid frame is available.
=> libobs: Fix rendering null sprite

deps/obs-scripting/obslua/CMakeLists.txt, deps/obs-scripting/obspython/CMakeLists.txt
Fixes `obs-frontend-api` symbols not being available to scripting environments since merging the rework.
Fixes https://github.com/obsproject/obs-studio/issues/6539
The required preprocessor definition activating support for `obs-frontend-api` within the scripting plugin needs to be set for the actual C/C++ compiler as well as the swig pre-compiler.
These commits ensure that the definition exists if UI is enabled in the project.
* Compiled locally and checked for existing symbols using the Lua file provided in [#6539](https://github.com/obsproject/obs-studio/issues/6539).
=> obs-scripting: Fix missing obs-frontend-api bindings for scripting plugins

UI/qt-display.cpp, UI/qt-display.hpp, UI/window-basic-main.cpp
This hooks the platform specific events in order to close the obs
display more accurately. Earlier attempts on hooking visiblity in Qt
, but Qt does not ensure that visibility is changed before the surface is
destroyed. So we ended up racing with the egl driver, and on some
drivers if you lose the race they hang.
Also force closure of the main preview window earlier to avoid similar
ordering issues in qt.
Finally only force display creation if the display is actually visible.
When a source type is not video/drawable (or is missing) this would
force the display to be created for the blank window and also hang.
People prefer if obs doesnt hang on their favorite proprietary drivers. Mostly resolves #6466 
Repeatedly opening and closing source and filter properties worked. Opening xcomposite …
=> UI: close display before native surfaces

libobs/obs-hotkey.c, libobs/obs.c
(This description has been revised from the original, since a proposed UI component has been removed)
Trigger hotkeys only when the key and modifiers pressed by the user exactly match the hotkey definition.
To fix #4408.
Suppose a user defines hotkey actions for "1", "Ctrl-1", "Alt-1", and "Ctrl-Alt-1." With the code in OBS 27 or earlier, if they then press "Ctrl-Alt-1", ALL FOUR actions will be triggered, in an order that may change between runs of OBS (presumably due to how the json is loaded).
While there may be some use case for this, requiring exact matches greatly expands the number of actions that can be invoked independently by hotkeys.
Bug reports
[https://github.com/obsproject/obs-studio/issues/4408](url)
[https://obsproject.com/mantis/view.php?id=925](url) …
=> Don't trigger hotkeys without modifiers if user is holding down modifiers (strict)

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, UI/qt-wrappers.cpp, UI/qt-wrappers.hpp
This limits the length of the name label in the advanced audio
dialog to 80 characters, so the dialog doesn't get too wide. If the
name is truncated, "..." are added at the end of the label, and the
label's tooltip is set to the full name of the source.
Prevents really long source names from making the dialog look bad.
Made sure long names were truncated in the dialog.
=> UI: Truncate names in advanced audio dialog

CI/flatpak/com.obsproject.Studio.json
Add a post-install command to the OBS module that installs the `obs_libraries` component, which provides CMake config files.
CMake config files are required for building OBS plugins with the Flatpak as a runtime.
Builds from the `master` branch stopped shipping the `LibObsConfig.cmake` file, and never shipped the `obs-frontend-apiConfig.cmake` file.
Fixes #6556 
Built locally, the resulting Flatpak ships the following CMake config files:
- `/app/lib/cmake/libobs/libobsConfig.cmake`
- `/app/lib/cmake/libobs/libobsConfigVersion.cmake`
- `/app/lib/cmake/libobs/libobsTargets.cmake`
- `/app/lib/cmake/libobs/libobsTargets-release.cmake`
- `/app/lib/cmake/obs-frontend-api/obs-frontend-apiConfig.cmake`
- `/app/lib/cmake/obs-frontend-api/obs-frontend-apiConfigVersion.cmake`
- …
=> flatpak: Install CMake config files

plugins/obs-ffmpeg/ffmpeg-mux/CMakeLists.txt, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
This adds a circular buffer to ffmpeg-mux when writing to a file. Output from ffmpeg is buffered so that slow disk I/O does not block ffmpeg writes, as this causes the pipe to become full and OBS stops sending frames with a misleading "Encoding overloaded!" warning. The buffer may grow to 256 MB depending on the rate of data coming in and out, if the buffer is full OBS will start waiting in ffmpeg writes.
A separate I/O thread is responsible for processing the contents of the buffer and writing them to the output file. It tries to process 1 MB at a time ~~and align writes to 4 KB for better performance on drives with caching disabled~~. Small writes are batched up to a minimum of 64 KB.
It also supports seeking in case the muxer has to go back to an earlier part of the file. This works by …
=> Add additional buffer when writing to file with obs-ffmpeg-mux

libobs/obs-video.c
Stale surfaces can cause improper downloads from GPU, and lead to video
corruption in certain cases.
Corrupt video when streaming NV12 with x264, and recording with NVENC.
Streamed NV12 with x264, and recorded with NVENC. Corruption before change; fixed after.
=> libobs: Ensure active copy surfaces are active

libobs/data/format_conversion.effect
Don't want to rely on consumer to ignore those bits.
Paranoia.
=> libobs: Clear low bits when writing P010

libobs/obs-hotkey.h
As discussed, deprecates `obs_hotkey_enable_strict_modifiers` so that we can get rid of it later.
I would probably push to master but
a) I'm too scared and
b) I don't actually know how
- Follow-up to #5095
This got changed in the UI and we don't need it for developers either.
Calling it will now warn that it's deprecated.
- Code cleanup (non-breaking change which makes code smaller or more readable) I guess? Or at least in the future it will
=> libobs: Deprecate obs_hotkey_enable_strict_modifiers

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Store current scene into a pointer variable in `OBSBasic` class.
When current scene is requested, return the saved pointer instead of querying `scenes` object, which is not multithread-safe.
`OBSBasic::GetCurrentScene()` is modified to return the stored pointer to the current scene instead of querying the `scenes` object. There can be a discussion not change the function and implement a new function for the purpose of multithread safe, then use it from the rendering routine and frontend-api.
~~New functions `os_atomic_store_ptr` and `os_atomic_load_ptr` are added to safely store the pointer to the current scene and load from any threads.~~ Reverted.
The function `OBSBasic::GetCurrentScene()` is also called from the graphics thread when rendering the preview and the multiview projectors. …
=> UI: Fix multithread-unsafe GetCurrentScene

libobs-opengl/gl-x11-egl.c
This PR removes unnecessary screen-number, not-read member variables in the struct `gl_windowinfo`, and an unused enum type.
These codes are copied from `gl-x11-glx.c` but not necessary for EGL.
https://github.com/obsproject/obs-studio/blob/fb639e303c337602316f6a11b2ad46c578be977c/libobs-opengl/gl-x11-glx.c#L74-L90
https://github.com/obsproject/obs-studio/blob/fb639e303c337602316f6a11b2ad46c578be977c/libobs-opengl/gl-x11-glx.c#L530-L535
The `screen_num` was used for `gladLoadGLX` and `glXChooseFBConfig` but not necessary for EGL.
https://github.com/obsproject/obs-studio/blob/fb639e303c337602316f6a11b2ad46c578be977c/libobs-opengl/gl-x11-glx.c#L266-L269
https://github.com/obsproject/obs-studio/blob/fb639e303c337602316f6a11b2ad46c578be977c/libobs-opengl/gl-x11-glx.c#L379-L380
Built on Fedora …
=> libobs-opengl: Remove unused code

plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Encoders have only one codec so this property is not needed.
Also rename the encoder to "FFMPEG VAAPI H.264".
Cleanup
Try to encode with VAAPI H.264 and it worked.
=> obs-ffmpeg: Remove codec property from VAAPI encoder

UI/window-basic-settings.cpp
The Settings dialog derives theme names from names of the theme files, nominally by removing the ".qss" extension. However, the current code parses the name as "everything left of the first '.'" rather than "everything left of the LAST '.'"
Thus, if there is a file with a name such as "Dark-V27.2.4.qss" in the themes directory, the Settings dialog will show it as "Dark-V27", and an attempt to select the theme will cause an error. This PR corrects the parsing.
Theme directory including theme file with "." characters
Setting dialog in 27.2.4 truncates at first "." Selecting the truncated name shows an error, since file can't be loaded.
Fix correctly shows the name up to the .qss extension.
Fixes a bug in parsing of theme filenames which prevented some valid names from being used.
Tested on …
=> UI: handle theme file names with "." characters

UI/forms/OBSBasicFilters.ui
This removes the horizontal spacer that pushed the filters
reset button to the right.
Before:
After:
Makes the dialog look better
Looked to see if the button was all the way to the left
=> UI: Fix position of reset filters button

UI/forms/OBSBasicTransform.ui
The spinboxes in the transform dialog were different sizes.
Before:
After:
Makes the dialog look better
Looked at dialog to see if it looked better.
=> UI: Make transform dialog spinboxes consistant

plugins/decklink/decklink-device-instance.cpp
When the width or height is zero, avoid calling `obs_source_output_video2`.
When opening a decklink source without plugging its input device, these error messages are shown for each frame.
```
error: glMapBuffer failed, glGetError returned GL_INVALID_OPERATION(0x502)
error: gs_texture_map (GL) failed
```
Debugging the code, I found the API sometimes send frames with 0x0 size when the mode is set to auto. Without filtering such frames, which causes libobs to output error messages.
OS: Fedora 34
Device: Decklink Quad
Settings of the decklink source is `Mode` = `Auto`.
Preparation
1. Configure decklink-source with `Mode` = `Auto`.
Run these steps several times.
1. Restart OBS.
2. Check stdout or log file.
Note that this changes minor behavior at the time the source becomes inactive. Prior to …
=> decklink: Avoid sending 0x0 frame to libobs

UI/media-slider.cpp, UI/media-slider.hpp
When pressing the up and down arrows or moving the mouse wheel
for the media slider, the slider would move.
Noticed the slider would move when using the up/down arrow keys or the mouse wheel.
In the future we could use the mouse wheel for seeking.
Made sure the slider didn't move.
=> UI: Add eventFilter to media slider

plugins/win-dshow/win-dshow.cpp
Save and restore webcam settings/ video device configuration properties
Requires https://github.com/obsproject/libdshowcapture/pull/37
Inspired by [Camooz](https://obsproject.com/forum/resources/camooz-tool-to-manage-and-save-and-restore-camera-settings.1271/)
Some webcams don't save the settings and this allows you to have different webcam settings per scene collection
On windows 64 bit
- New feature (non-breaking change which adds functionality) -->
=> win-dshow: Save and restore video device configuration properties

plugins/linux-v4l2/CMakeLists.txt, plugins/linux-v4l2/v4l2-decoder.c, plugins/linux-v4l2/v4l2-decoder.h, plugins/linux-v4l2/v4l2-input.c
Added support for format "H264" to capture from the linux-v4l2 plugin.
Build on top of kosmisk-dk PR to also support MJPEG https://github.com/obsproject/obs-studio/pull/3046
H264 tends to have less noise than MJPEG
It also can use less USB bandwidth which might be important if you're using more than 1 webcam on save USB bus.
I've selected "Moition-JPEG" from the "Video Format" drop down.
I've switch to "H264" from the "Video Format" drop down.
I've switch back and forth multiple times with different framerates and resolution.
MJPEG was tested with Logitech c920 and Microdia Digital microscope
H264 was tested with Logitech c920
Enhanced if conditions to support 1 more codec.
Renamed files.
=> linux-v4l2: Support for H264 codec

UI/CMakeLists.txt, UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, UI/forms/OBSAdvAudio.ui, UI/window-basic-adv-audio.cpp, UI/window-basic-adv-audio.hpp
This converts the advanced audio window to use
a ui form, so it is easier to modify in the future.
This also fixes sizing issues with the control widgets,
as before the audio tracks would be clipped, because the
widgets in the window were too wide.
Before:
After:
Makes dialog easier to edit and makes it look better.
Opened dialog to make sure everything was working as expected.
- Tweak (non-breaking change to improve existing functionality) 
=> UI: Cleanup advanced audio window

deps/media-playback/media-playback/decode.c
av_hwframe_transfer_data doesn't seem to transfer metadata, so do it
manually.
Want to display video correctly.
HDR video displayed incorrectly before, correctly after.
=> deps/media-playback: Fix metadata for hw_accel

plugins/aja/aja-source.cpp
Add a property `Use Buffering` to AJA source.
Also set the default to unbuffering, which is a change of the behavior.
Buffering inside libobs is enabled by default. The latency of the buffering changes every startup, which is a problem to adjust delay of multi-camera setup or lip sync with other sources.
The `timestamp` for the video frame is taken from `os_gettime_ns()`, not taken from the timestamp of the received frames. I don't think buffering is not necessary for this source.
https://github.com/obsproject/obs-studio/blob/c5015d0e6cb180d138e1a9e2258afd903254b9ea/plugins/aja/aja-source.cpp#L381
Added a `blog` call in `obs_source_set_async_unbuffered` and checked the setting is sent to libobs. This PR does not contain the added `blog`. …
=> aja: Implement buffering property

UI/obs-app.cpp, UI/platform-osx.mm, UI/platform.hpp, docs/sphinx/reference-libobs-util-platform.rst, libobs/util/platform-cocoa.m, libobs/util/platform-nix.c, libobs/util/platform-windows.c, libobs/util/platform.h
Add function to get Rosetta translation status
Pruned from #5738.
As per @gxalpha's request
=> libobs/util: Add function to get Rosetta translation status

UI/forms/OBSBasic.ui, UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp
Reverts the redesign of the transitions dock (and a few related follow-up commits)
originally introduced in #2961 which moved adding transitions to the dropdown
menu and the remove function to the settings gear icon.
Most reverts applied cleanly, some had to be manually adjusted (like for RAII).
I left the commits separate to make it easier to follow what got changed, but feel
free to "Squash and Merge" should one commit be desired.
The original change had the intention of increasing discoverability, however it
achieved the opposite (see #3631 as well as the support channels on Discord). While
other things like sources and scenes have a standard +/- configuration for adding and
removing, for transitions you need to select the dropdown to add transitions.
Besides being inconsistent, this …
=> UI: Revert transitions dock redesign

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Cleans up the source right click menu mostly according to a mockup and requests from @Warchamp7.
Old menu (source has async video / no audio):
New menu (source has async video / no audio):
Mockup: 
New menu (no video / with audio):
Detailed overview:
- Removed "Resize output (source size)" menu
- Only shows "Interact" menu when source can be interacted with, instead of always showing the menu, but disabling it with most sources
- Grouped Scale Filtering, Blending Mode & Method, and Deinterlacing together
- Moved Projector menus down
- "Hide in mixer" has its own group. This is the only change that doesn't comply with the mockup (and the notes), since just up removing it would remove functionality and a better place for it has yet to be found. This can come at a later point.
List is very …
=> UI: Clean up source right-click menu

plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-outputs/flv-output.c, plugins/obs-outputs/ftl-stream.c, plugins/obs-outputs/rtmp-stream.c
`obs_encoder_get_extra_data` was called in many places without checking the return value. If the encoder was invalid, the input fields would be left as-is with uninitialized memory, resulting in a crash when they were used later.
This was found in obs-outputs where the send_thread can be in the process of (re)connecting but the encoder was shut down in the meantime, all other instances were fixed for consistency even if they weren't susceptible to race conditions.
Crashing is bad.
I was not able to reproduce the race condition, but tracing the code shows that this should correctly pass the error back up the stack instead of crashing.
=> Check return value of obs_encoder_get_extra_data

UI/context-bar-controls.cpp
When a module is not found, immediately return from the `Init()` function. This is same change as 41367bb2b but fixes window-capture and display-capture. See also #3485.
Also removes an unnecessary pair of braces.
If a module is not found in context bar, it crashed when resolving source type name.
The situation could happen in such cases below.
- The OBS Studio is built by a user who does not have enough dependencies to build the required module for the context bar such as `linux-capture` but the source is instantiated from imported configuration from other machine.
- User might remove the module.
Tested on Fedora 34. Log shows `xshm_input` is not found. Then choose the source for `xshm_input` and ensure the OBS won't crash.
```
Source ID 'xshm_input' not found
```
- Bug fix (non-breaking …
=> UI: Fix crash if missing module in context bar

plugins/mac-avcapture/av-capture.mm
Changes the default camera preset from 720p to [High](https://developer.apple.com/documentation/avfoundation/avcapturesessionpresethigh).
High is the maximum resolution that the camera provides.
Does not need v3 since v2 has not yet been deployed in production.
Users often don't change defaults and then are stuck on 720p
even if their webcam supports 1080p or more.
Created source on 27.2 and tested that it stays on 720 on the new build.
Created source on new build and confirmed it defaults to High, resulting in
1080p on my internal MacBook facecam.
=> mac-avcapture: Make "High" preset default

plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm, plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm, plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm
This change fixes a memory leak in the mac-virtualcam plugin that causes OBS to not release the CVPixelBuffers (and underlying IOSurfaces) it emits to the virtual camera consumers.
I have found that the plugin is leaking Mach ports associated with IOSurfaces, preventing them from being re-used. The previous approach using `NSMachPort` does not seem to properly release the Mach port allocated via `CVPixelBufferGetIOSurface` and `IOSurfaceLookupFromMachPort`. Instead, we must explicitly deallocate the port using `mach_port_deallocate`.
Pull request https://github.com/obsproject/obs-studio/pull/6573 (Avoid transcoding where possible) updated the mac-virtualcam plugin to share the virtual camera feed with other processes via IOSurfaces.
Although the changes work correctly, users have observed …
=> mac-virtualcam: Fix IOSurface memory leak

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
- Add service Mildom and Nonolive entry to plugins/rtmp-services/data/services.json
- Increment package version in plugins/rtmp-services/data/package.json
Mildom and Nonolive are the live streaming product of DOYU HONGKONG LIMITED, OBS Studio is widely used by our users, So we require to add our services to OBS service list.
Mildom Official website: https://www.mildom.com/
Nonolive Official website: https://www.nonolive.com/
We've test changes locally(replace the JSON files in OBS Studio install path), and it works fine.
rtmp-services module add two services.
=> rtmp-services: Add Mildom and Nonolive

plugins/linux-pipewire/CMakeLists.txt, plugins/linux-pipewire/linux-pipewire.c, plugins/linux-pipewire/pipewire-capture.c, plugins/linux-pipewire/pipewire.c, plugins/linux-pipewire/pipewire.h, plugins/linux-pipewire/portal.c, plugins/linux-pipewire/portal.h, plugins/linux-pipewire/screencast-portal.c, plugins/linux-pipewire/screencast-portal.h
A series of cleanups and code shuffling to prepare terrain for PipeWire-based cameras and audio.
The current linux-pipewire code mixes the screencast portal code, with PipeWire streaming code. This makes it harder to introduce new PipeWire-based sources, such as cameras, virtual camera output, and audio.
- Run this PR on a Linux / Wayland system
- Observe that both monitor and window captures still work exactly as they used to
=> Various cleanups to linux-pipewire

.github/workflows/steam.yml
Use official static 7zip linux binaries instead of removed PPA.
The PPA has been deleted so the Steam workflow started failing.
Has not been tested, but since this is just reverting the switch to the PPA I don't expect any issues.
=> CI: Use static 7zip build instead of PPA

UI/window-basic-main.cpp, libobs/obs-internal.h, libobs/obs-output.c
- Changes the default base exponent value to 1.5 from 2.0
- Applies a random skew of +-0.05 to the exponent to lessen the "water hammer" effect caused by predictable backoff techniques
- Fixes the logging associated with exponential backoff to log the true reconnect delay value
- Changes the default reconnect delay to 2 seconds from 10
- Changes the default max retries to 25 from 20
The default delay of 10 seconds is arguably quite excessive given that it already implements exponential backoff.
Depending on how a given stream is disconnected, it's likely that the RTMP server is already ready to accept the publisher again by the time the reconnect process even starts. If it's not ready, then that's why exponential backoff is there in the first place.
Total average reconnect time before …
=> UI: Improve exponential backoff reconnect on disconnect

UI/data/locale/en-US.ini, UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This adds the ability to reset to whole UI, instead of just
the docks.
The 'Reset UI' and 'Lock UI' in the dock view menu, are now
renamed to 'Reset Docks' and 'Lock Docks'.
Users were confused before because the 'Reset UI' action in the docks view menu would only reset the docks.
The 'Reset UI' has been moved now to the view menu, with the action in the docks view menu being renamed.
Items in the UI were hidden and then reset to made sure it worked properly.
=> UI: Add ability to reset entire UI

UI/window-basic-main.cpp
Makes OBS try to close the remux dialog before Clearing Scene data since
in case a remux might still be going on and the user does want to abort
closing OBS.
Fixes #4522
macOS 12 Beta 6, compiled and run
Pressing *No* when the dialog pops up will now correctly abort the shutdown process and keep OBS open (without asking a second time).
Pressing *Yes* will still shut down OBS and stop the remux.
=> UI: Try closing remux before initiating shutdown

UI/properties-view.cpp, docs/sphinx/reference-properties.rst, libobs/obs-properties.c, libobs/obs-properties.h
It adds a property which adds a text label to the properties view. This label can be a simple info, a warning or an error.
This new type of property is a sub-type of text property.
On UI side, Rich Text, clickable links and word wrap are enabled.
Depending on if the description, the string value and the long description are set, the property will be shown differently.
Forgot a "with" in a string value.
My screenshot tool does not let the cursor appear.
- A text info with only a description will only show the the info without the label in the first column.
- A text info with a description and a string value or a long description will fill the first column with the description and the second with the string value or the long description.
- If an empty description is set, the first column …
=> Add info (text label) property as text sub-type in properties API

UI/CMakeLists.txt, UI/auth-youtube.cpp, UI/auth-youtube.hpp, UI/data/locale/en-US.ini, UI/lineedit-autoresize.cpp, UI/lineedit-autoresize.hpp, UI/window-youtube-actions.cpp, UI/youtube-api-wrappers.cpp, UI/youtube-api-wrappers.hpp
Click [here](https://github.com/obsproject/obs-studio/actions/runs/2339957170) for CI test builds with YouTube enabled.
Adds a custom text box to the YouTube chat which allows for sending messages using the YouTube API.
- Due to how the chat polls, after sending a message it takes 2-3 seconds for the message to appear in the chat. This would only be fixable by implementing a completely custom chat which has already been decided against in the past for various reasons (which still apply).
- The YouTube API doesn't appear to give you any info on whether the live chat is actually enabled on a stream (until you try to send a message). This means that when it's disabled, the text input field is still visible and users can still try to send messages. In that case, an error message will appear …
=> UI: Add ability to send messages to YouTube chat

UI/auth-youtube.cpp
Replaces a call to QLayout::setMargins recently introduced with the
Qt 6 replacement, setContentsMargins.
Keep codebase compatible with Qt 6.
Now correctly compiles, YouTube chat looks exactly as it did before
=> UI: Fix YouTube Chat build failure with Qt 6

UI/forms/OBSBasicProperties.ui
I'll let the screenshots speak for themselves:
Before:
After: 
Yes.
macOS 13 Beta 2, Qt 5.
See screenshots.
=> UI: Make properties window default to 50/50 split

cmake/Modules/ObsDefaults_macOS.cmake
Sets a dynamic SWIG library path in the environment to allow relocatable swig installations on compilation hosts.
Swig hardcodes its library path at compilation time with Windows being the only platform on which it uses a path relative to its binary. This a deliberate choice by the Swig authors, as UNIX-style operating systems should either use Swig installed system wide (using default library paths) or compiled on the host system (for custom paths).
As we use pre-compiled dependencies via obs-deps, this results in self-built Swig versions that use the library path as present on the GitHub runner at compilation time and thus break on any other system.
This change detects if a obs-deps version with shipped Swig is used and forces it to use a path relative to the `CMAKE_PREFIX_PATH`.
A PR …
=> cmake: Fix hardcoded SWIG_LIB path on macOS

deps/obs-scripting/obs-scripting-lua.c, deps/obs-scripting/obs-scripting-python.c
Logs when a script gets loaded and unloaded
Requested for support, since scripts can mess up things real bad and currently there's no way to know if a script is active.
macOS 13 Beta 2
When starting OBS, both python and lua scripts get logged like this:
When refreshing, first "loaded" and then "unloaded" shows up.
When adding or removing, it shows as loaded or unloaded.
=> deps/obs-scripting: Log script load/unload

docs/sphinx/reference-encoders.rst
The order of the arguments as called is first the settings, then the type data:
https://github.com/obsproject/obs-studio/blob/2dd1a3fc6f3a3c5139290e09eebff60d7ee4f6e2/libobs/obs-encoder.c#L70-L71
https://github.com/obsproject/obs-studio/blob/2dd1a3fc6f3a3c5139290e09eebff60d7ee4f6e2/libobs/obs-encoder.h#L250
Noticed when referring to the docs and getting crashes.
Hasn't, besides seeing that it renders correctly on GitHub.
=> docs: Fix encoder .get_defaults2 arguments

deps/obs-scripting/CMakeLists.txt
Fixes swig runtime header generation failing on macOS with updated obs-deps.
Due to swig using a hardcoded swig library path in self-compiled variants, we need to pass our custom swig library path with every invocation of swig on macOS.
CMake's `add_custom_command` function does _not_ inherit the environment variables used during configuration, hence why it needs to be passed explicitly on invocation.
Usage of CMake's "-E env" command module should allow for cross-platform compatible invocation.
* Tested with full OBS-Studio build on macOS
* Tested with full OBS-Studio build on Windows
=> obs-scripting: Fix swig runtime header generation for macOS

plugins/obs-ffmpeg/obs-ffmpeg.c
obs-ffmpeg: Fix compatible NVENC with NVIDIA Tesla 
Testing environment:
HW: Dell R730 with NVIDIA Tesla P40
OS: Ubuntu 22.04 LTS
=> obs-ffmpeg: Add NVIDIA Tesla NVENC support

plugins/aja/aja-source.cpp
Increment the value read from the card via `CNTV2Card::ReadAudioLastIn` (AKA `currentAddress` in the code) by 1 to ensure capturing the correct range of 8ch of audio samples. The current code alters the `currentAddress` value by performing `currentAddress &= ~0x3`. This code was taken from the AJA demo app called `ntv2llburn` and was purported to "Force DWORD alignment". This effectively causes the start of the range of 8ch worth of samples to start ahead of where it should be in the card's audio ring.
After talking to several AJA engineers it was found that this computation is probably some legacy code that was left in the demo. The card's audio de-embedder always writes audio to the card's audio ring in 512 byte chunks, starting at 0 and e nding on the 511th byte. Adding 1 to the …
=> aja: Fix 8ch audio capture offset by a channel

UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp, deps/libcaption/CMakeLists.txt, libobs/CMakeLists.txt, libobs/graphics/graphics-ffmpeg.c, libobs/obs-scene.c, libobs/obs-video.c, plugins/aja/aja-common.cpp, plugins/image-source/image-source.c, plugins/obs-ffmpeg/CMakeLists.txt, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c, plugins/obs-filters/CMakeLists.txt, plugins/obs-x264/CMakeLists.txt
Fixes and/or suppresses compiler warnings in several modules. Main fixes are:
* Suppress warnings about non-exhaustive `switch` cases (fixed via compiler flags)
* Suppress warnings about unused variables (fixed via `OBS_UNUSED` macro)
* Fix warning about a function marked as no_return supposedly returning (fixed by applying the macro to all aliased function signatures as well)
Fixing warnings removes clutter in build output and allows maintainers to focus on actual (or new) warnings and errors.
* OBS built and tested locally on macOS
=> Fix compiler warnings in several modules

plugins/obs-outputs/librtmp/rtmp.c, plugins/obs-outputs/rtmp-stream.c
This commit fixes what is arguably a long-winded series of previous commits that have possibly caused just as many problems as they have fixed.
This provides a slight enhancement by removing the `RTMP_Init` call in `rtmp_stream_create()`, since it effectively just initializes TLS just for `try_connect` to deinitialize it before it is even used.
This also fixes the current `SO_RCVTIMEO` timeout functionality by making sure that `RTMP_Reset` is called last.
I'll spare the details, but basically, there's no reason that any of the RTMP object should ever be used across socket sessions. It's best just to zero out the RTMP context and initialize TLS each time we connect, than to do a bunch of things to only reset parts of it.
Ubuntu 20.04:
- RTMPS streaming - ok
- Standard RTMP streaming - ok
- …
=> obs-outputs: Rework RTMP context init/deinit

libobs-opengl/gl-egl-common.c, plugins/linux-capture/xcomposite-input.c
Fixes capture retry not working for xcomposite on EGL.
Fixes log spam when we are waiting for the user to remap a window (move to the right workspace, unminimize window, etc).
capture regressed from glx. Log spam regressed as well.
It works on my machine.
=> EGL fixups

UI/window-basic-main.cpp, UI/window-basic-main.hpp
If a plugin adds a dock and the program is run for the
first time, the reset ui warning would show up.
Found when making plugin that uses an extra dock.
Loaded plugin and made sure the dialog didn't show up.
=> UI: Fix reset ui warning showing on first start

UI/CMakeLists.txt, UI/multiview.cpp, UI/multiview.hpp, UI/window-projector.cpp, UI/window-projector.hpp
Moves the multi view layout and rendering out of the QT projector class and into a new class.
By decoupling this code we can work toward rendering the multi view and sending it to an output.
Tested that multiview works the same on macOS.
=> UI: Move multiview render into a new class

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, UI/qt-wrappers.cpp, UI/qt-wrappers.hpp, UI/window-basic-settings.cpp
Commit 1: Update hotkeys to use new truncate label function
Commit 2: Truncate push-to-mute / push-to-talk source name labels
Wanted to use new function introduced with https://github.com/obsproject/obs-studio/commit/0d0b65e8c82d29e4b7068153c86b1745ac7adcfb
Also noticed push-to-* hotkey labels weren't truncated.
Gave a source a really long name and made sure it rendered correctly in the settings dialog.
=> UI: Settings dialog truncate label cleanup/fixes

plugins/mac-syphon/syphon.m
`absolutePathForAppBundleWithIdentifier` and `openFile` have both been deprecated since macOS 11.0. 
This implements the correct modern APIs when OBS is compiled for macOS 11.0 or more recent and falls back to the legacy APIs when either compiled against or run on older macOS versions.
Ensure compatibility with future versions of macOS.
* Still needs to be tested with a proper Syphon setup
=> mac-syphon: Fix usage of methods deprecated since macOS 11.0

.github/workflows/main.yml
Ubuntu 22.04 images are now available on GitHub Actions. Add 22.04 and drop 18.04, as we are dropping 18.04 for the next release.
As we intend to drop support for Ubuntu 18.04 for OBS Studio 28, we should reflect that change on CI.
I ran CI on my fork with these changes. I have not done a local build test or tested a resulting application on Ubuntu 22.04, but I have no reason to believe there would be any serious issues.
=> CI: Update Ubuntu versions

UI/data/themes/Yami.qss
This adds a transparent border to lineEdits in their normal state, so that the :hover and :focus styling does not cause the text to shift.
Also adds some special styling for the QListWidget lineEdits (Scenes list, Sources list) to remove their shifting as well as more clearly show they're in edit mode, as the text highlight color matches the selected item color.
Text shifting doesn't look nice
I used some text boxes
=> UI: Fix text shifting on lineEdits in Yami

deps/obs-scripting/obspython/CMakeLists.txt
Fixes issues introduced by https://github.com/swig/swig/pull/2238. As obs-scripting is not compatible with the SWIGPYTHON_BUILTIN, obspython needs to disable this feature.
Fix crash issues introduced by possible swig/obs-deps update.
Tested locally with updated obs-deps and Python test script.
=> obs-scripting: Fix crashes introduced by Swig update to 4.1.0

UI/window-basic-settings.cpp
bbeafeabdd1c00affa73657a0ac992dd9295fc15 change how the combobox is filled.
And `UpdateColorFormatSpaceWarning` did not get the required change to use the combobox data rather than the text.
Fix this issue where the warning should not be shown:
Change color format and see if warnings are shown only when needed.
=> UI: Fix color format warning

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss
The menu icon was set only in the Yami theme.
New theme Yami broke existing themes.
Ran program to make sure the icons showed up as expected.
=> UI: Fix menu icons not showing up

libobs/util/bmem.c, libobs/util/bmem.h
Deprecates `base_set_allocator` and signals removal of support for `bmalloc(0)`.
As libobs has alignment requirements, allowing an app to change our memory allocator from our own aligned implementation with `base_set_allocator` doesn't really make a lot of sense. Presumably nothing ever used this function anyway, and having all allocations go through an indirect function call prevents more aggressive optimizations such as inlining directly to `malloc` at the call site. Also note that `base_set_allocator` was never documented.
I believe `bmalloc(0)` is also a bad thing to support as `malloc(0)` behavior is implementation defined - it either returns NULL or returns a pointer that can never be written or read. We handle it specially in libobs and pretend it was `bmalloc(1)` but I don't …
=> Memory allocator cleanups

libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
Change the default value of `get_default_id` from `NULL` to `bzalloc(1)` in order to be consistent with other place mentioned by https://github.com/obsproject/obs-studio/issues/6460#issuecomment-1183958912
Fixes #6460 
Reproduce this situation, and NO crash happen.
=> libobs: Fix pulseaudio crash

deps/media-playback/media-playback/media.c
When AVFormatContext->startime is set to AV_NO_PTS
mp_media_reset try to seek to INT64_MIN (and seek failed)
use 0 instead to seek to the start of the file.
Fix loop with aac file (Issue : https://github.com/obsproject/obs-studio/issues/6715)
Check that basic MP4 file still loop with media source after this patch
Check that after this patch, AAC file can loop
(test file can be found here (it's an ffmpeg unit test file) : https://www.swisstransfer.com/d/62ec0358-3f17-4417-b8e2-ebf8110aeb89)
=> deps/media-playback: Fix invalid seek at reset

UI/forms/OBSBasic.ui
The transitions dock doesn't have a proper container, like
the other docks.
Idea from @Warchamp7 
Ran program to make sure nothing bad happened.
=> UI: Add frame around transitions dock

plugins/aja/aja-output.cpp, plugins/aja/aja-source.cpp, plugins/aja/main.cpp
Add aja-source version 2 to differentiate buffering settings, which is implemented in a255b0f74.
- Version 1: buffering is enabled by default
- Version 2: buffering is disabled by default
To register two versions, remove to return obs_source_info and register the source inside aja-source.cpp. Also revise aja-output.cpp to register aja-output to keep consistency of function type.
Requested by @paulh-aja at https://github.com/obsproject/obs-studio/pull/6621#issuecomment-1180152631.
- Before this modification,
- added aja-source.
- With this modification,
- checked the aja-source has enabled buffer.
- added another aja-source and checked it's buffer is disabled.
=> aja: Increment aja-source version for buffering setting

UI/window-basic-main.cpp
Make a better error message for user,
in case recording path is invalid by checking OutputPathValid before LowDiskSpace
Fix issue : https://github.com/obsproject/obs-studio/issues/6731
Mac os Intel 11.6
Set a recording folder.
Try to start record, and start replay.
Rename this folder (to create an invalid record folder path),
Check that the error message when trying to start record or replay buffer is ok
=> UI: Check output path when starting replay buffer

UI/CMakeLists.txt, UI/frontend-plugins/aja-output-ui/CMakeLists.txt, cmake/Modules/CompilerConfig.cmake, plugins/aja/CMakeLists.txt, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-filters/CMakeLists.txt, plugins/obs-outputs/CMakeLists.txt, plugins/text-freetype2/CMakeLists.txt
Address the remaining warnings, and enable /WX on both MSVC compiler & linker to prevent more from being added.
I hate warnings.
- Verified the warnings were treated as errors when not fixed.
- Verified the warnings are gone after fixing.
- Verified Debug and RelWithDebInfo compiled on my machine.
=> Treat warnings as errors on MSVC

cmake/Modules/ObsHelpers_Linux.cmake, libobs/pkgconfig/libobs.pc.in
Existing code didn't check for possible "empty" linked libraries (e.g. Threads::Threads when compiler has built-in pthreads support).
Also adds support for compile options defined on linked dependencies.
Fix pkgconfig usage on Linux.
pkgconfig files successfully generated on Linux machine without invalid library names.
=> cmake: Fix pkgconfig generation on Linux

UI/data/themes/Yami.qss
The Yami theme never added the media control icons to
the qss file.
Noticed media control icons weren't used in the Yami theme.
Used media controls to make sure icons worked properly.
=> UI: Add media control icons to Yami

UI/window-basic-main.hpp
Fix this warning by ~~turning~~ moving `undo_s` after `ui` in the class definition. ~~into a pointer and initialized it inside `OBSBasic` constructor~~.
```
obs-studio/UI/window-basic-main.cpp: In constructor ‘OBSBasic::OBSBasic(QWidget*)’:
OBS/obs-studio/UI/window-basic-main.cpp:231:41: warning: member ‘OBSBasic::ui’ is used uninitialized [-Wuninitialized]
231 |         : OBSMainWindow(parent), undo_s(ui), ui(new Ui::OBSBasic)
|                                         ^~
```
Just remembered that this warning was there and wanted to get rid of it.
Tried to use Undo/Redo feature and no issue.
=> UI: Fix undo stack uninitialized ui warning

UI/obs-app.cpp, UI/obs-app.hpp
With Qt 6, high dpi scaling is always enabled and the AA_DisableHighDpiScaling becomes no-op. As such, we can remove the command line argument.
Less warnings in Qt 6.
By no means all (there are quite a few), but you gotta start somewhere.
Compiled and run on both Qt 5 and Qt 6.
=> UI: Remove disable_high_dpi_scaling option on Qt 6

cmake/Modules/ObsHelpers.cmake, cmake/Modules/ObsHelpers_Linux.cmake
Fix this warning:
```
CMake Warning (dev) at cmake/Modules/ObsHelpers.cmake:43 (install):
Target obs-frontend-api has PUBLIC_HEADER files but no PUBLIC_HEADER
DESTINATION.
Call Stack (most recent call first):
cmake/Modules/ObsHelpers_Linux.cmake:10 (_setup_binary_target)
UI/obs-frontend-api/CMakeLists.txt:39 (setup_binary_target)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
And add EXCLUDE_FROM_ALL to Linux install_headers, because even without it we still need to run `cmake --install . --component obs_libraries`
Fix a warning, and tweak something.
Try to build a `-git` package (with my own PKGBUILD) which use `cmake --install . --component obs_libraries`, header are there.
And Cmake no longer throw the warning.
- Code cleanup (non-breaking change which makes …
=> Fix CMake Warning and tweak Linux install_headers

plugins/mac-syphon/syphon.m
Ignore a deprecation warning that's effectively 10.13-only code, since syphon inject doesn't work on anything newer.
Less warnings.
Still compiles, warning gone.
=> mac-syphon: Ignore 10.13-only deprecation warning

UI/frontend-plugins/frontend-tools/scripts.cpp, cmake/Modules/FindPythonWindows.cmake, cmake/Modules/ObsDefaults_Linux.cmake, deps/obs-scripting/CMakeLists.txt, deps/obs-scripting/obs-scripting-python-import.c, deps/obs-scripting/obs-scripting-python-import.h, deps/obs-scripting/obs-scripting-python.c, deps/obs-scripting/obspython/CMakeLists.txt
Changes the Python module of obs-scripting to use the Python 3 stable ABI and also allows OBS to load several different recent Python 3 versions (any possible version between 3.6 and 3.10 will be loaded, if available).
Also changes the macOS UI to just require the base path a `Python.framework` is placed in (instead of requiring users to dive into the Framework to find the library path).
**Note:** This PR implements the changes introduced by https://github.com/obsproject/obs-studio/pull/6696 to pull the swig binaries compiled on CI with stable Abu support.
In theory these changes should allow users to run Python scripts in OBS with a wider range of available Python versions installed on the host system, independent from the version used to compile OBS.
Caveats: While the obspython module …
=> obs-scripting: Switch Python support to use the Py3 stable ABI

deps/libff/libff/ff-util.c, deps/media-playback/media-playback/decode.c, deps/media-playback/media-playback/decode.h, libobs/graphics/graphics-ffmpeg.c, plugins/linux-v4l2/v4l2-decoder.h, plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.h, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c, plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.h, plugins/obs-ffmpeg/obs-ffmpeg.c, plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/ffmpeg-decode.h
Avoid breaking building OBS with a newer version of FFmpeg with #6759.
No additional warning if built with FFmpeg 4.4.1.
Avoid breaking building OBS with a newer version of FFmpeg with #6759 (and maybe #6723).
Builds fine on my ArchLinux.
**Needs testing**, I don't consider myself has a good tester.
Following tests are made with a Flatpak build (FFmpeg 4.4.1) and a ArchLinux build (FFmpeg 5.0.1):
- Custom Output (FFmpeg) UI (libff changes) does not seem to have issue on both builds.
- Media Source with local MP4 file does not seem to have issue on both builds.
- Drawing Overflow on the Preview (graphics-ffmpeg.c changes) does not seem to have issue on both builds.
- V4L2 input with MJPEG does not seem to have issue on both builds.
- NVENC and VAAPI are shown in the settings on both …
=> Fix discarded-qualifiers warnings with FFmpeg 5

UI/media-slider.cpp, UI/menu-button.cpp, UI/obs-app.cpp, UI/qt-wrappers.cpp, UI/scene-tree.cpp, UI/source-tree.cpp, UI/window-basic-filters.cpp, UI/window-basic-interaction.cpp, UI/window-basic-main.cpp, UI/window-basic-preview.cpp, UI/window-projector.cpp
Fixes deprecations for Qt.
Less deprecations.
First commit:
- Undo/Redo hotkeys still work
- Moving items in the preview with arrow keys still works (with shift as well)
Second commit:
- Context Bar Media Slider (MediaSlider)
- Quick Transitions Button (MenuButton)
- Drag and Drop in Sources Dock and Scenes Dock (SourceTree and SceneTree)
- Interact Menu on Browser Source, with pointerpointer.com and webgl aquarium (OBSBasicInteraction)
- In preview, moving the mouse over items correctly highlights the item where the mouse is. When dragging a selection, that selection is in the correct place
- In multiview, clicking a scene correctly selects it for the preview. With "Transition to scene when double-clicked" enabled, double clicking a scene selects and transitions to it.
Third commit:
- …
=> UI: Qt 6 deprecations

deps/obs-scripting/obs-scripting.c, plugins/linux-v4l2/v4l2-udev.c
This sets some thread names for the scripting backend's defer thread and
the v4l2 udev thread.
It makes it easier to know I dont have to look at a thread if it's name is not "obs" when debugging.
=> v4l2,scripting: Add more thread names

plugins/obs-outputs/librtmp/rtmp.h
When trying to update to mbedTLS 3.2.1, I ran into failures with RTMPS output. After consulting an mbedTLS implementation example, I determined that we were not setting up the SSL/TLS context config in the correct order, causing the connection to fail. Performing the setup in the recommended order fixes that.
Want RTMPS to work with mbedTLS 3.1.0+.
I tested an RTMPS stream to YouTube before and after this change. Before it would fail to connect. After, the stream worked fine. Confirmed that this works with both mbedTLS 2.24.0 and 3.2.1 on Windows.
=> obs-outputs: Fix TLS_client init for mbedTLS 3.1.0+

UI/window-basic-main.cpp
Remove two functions `save_audio_source` and `load_audio_source`.
These functions are defined in C++ source code in `UI` but never called from any code. Also not defined in any header file.
I found `double` type is passed to `obs_source_set_audio_mixers`, where it requires `uint32_t` type, each bit of which defines enable/disable of sending the source to the output. Even though these functions are not in use, I don't want to see such a type conversion.
Built OBS Studio on Fedora 35 and confirmed it works.
Build OBS Studio on CI and confirmed no link errors.
=> UI: Remove unused functions for audio mixers

UI/frontend-plugins/frontend-tools/scripts.cpp
Obvious fix guarding against calling the std::string constructor with a NULL pointer.
Fix OBS crashing on macOS without preconfigured Python path.
Tested on macOS with clean config and config without available Python configuration.
=> UI: Fix crash on macOS if no python path is set in configuration

UI/obs-app.cpp
Found the issue on Linux, the Plasma default theme Breeze also provide a Qt style plugin.
This plugin add a frame to QDockWidget.
Those frames are not stylable with QSS because those are drawn with QPainter.
- https://github.com/KDE/breeze/blob/4222e8e83ae870ffb1ccc3c02775681322f62b88/kstyle/breezestyle.cpp#L1555
- https://github.com/KDE/breeze/blob/4222e8e83ae870ffb1ccc3c02775681322f62b88/kstyle/breezehelper.cpp#L457
Flatpak install is always affected because the KDE Runtime provide Breeze, and Linux systems with Breeze installed are also affected for non-Flatpak install
So to avoid this the base style is enforce to the Qt default style on Linux: Fusion.
Screenshot made with #2778 
Without the PR:
With the PR:
I want Yami to be nice on Linux and Qt doesn't want me to be happy.
- Run …
=> UI: Enforce Fusion Qt style on Linux

CMakeLists.txt
Enable HEVC code by default.
Widespread hardware encode/decode support.
Verified HEVC was enabled by default in fresh CMake build directory. Was able to make HEVC recording with NVENC.
=> cmake: Enable ENABLE_HEVC by default

plugins/mac-syphon/syphon.m
Fixes broken license button on macOS 11+ (introduced via deprecation fix recently) and also remove all injection functionality for macOS 10.15+ (which is blocked by macOS anyway).
Fix broken functionality and also remove errors in log occurring by normal use of the source.
Tested on macOS 12.4.
=> mac-syphon: Fix issues on modern macOS versions

UI/obs-app.cpp, UI/platform-osx.mm, UI/platform.hpp
Ensures that Cocoa knows that we intend to use multiple threads, per https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/CreatingThreads/CreatingThreads.html#//apple_ref/doc/uid/10000057i-CH15-SW21.
This change had been introduced in https://github.com/obsproject/obs-studio/pull/5680 to ensure that Cocoa frameworks are properly multithreaded (per Apple's documentation, see above).
The original PR was merged accidentally, then reverted, with some beneficial changes merged in a later PR. This PR takes the proposed change and adds it to the application initialisation, to ensure stability and multi-threaded performance interplay between core OBS functionality (which uses POSIX threads) and CoreFramework functions which use NSThreads. This should benefit …
=> UI: Add initialization to ensure compat between pthread and NSThread

UI/data/themes/Yami.qss
Icon added to Yami theme.
Icon is missing if launching with Yami theme.
Icon appears when launching with Yami theme.
=> UI: Add audioProcessOutputIcon to Yami

plugins/obs-filters/chroma-key-filter.c, plugins/obs-filters/color-grade-filter.c, plugins/obs-filters/color-key-filter.c, plugins/obs-filters/luma-key-filter.c, plugins/obs-filters/mask-filter.c
Not sure how to implement controls for HDR, so skip unless SDR for now.
Don't want to apply SDR color processing on HDR video.
Verify scenarios:
=> obs-filters: Add HDR bypass for various filters

UI/CMakeLists.txt, UI/obs-app.cpp, UI/platform-osx.mm, UI/platform.hpp
Adds functions to check and/or request specific macOS permissions (audio device access, video device access, accessibility access, and screen capture access).
By default only audio capture, video capture, and accessibility are requested on launch - the first two have straight-forward "Yes/No" prompts, the latter requires people to enable OBS in the settings application (but is required for hotkey functionality, independent
of scene setups).
Reduce friction to gain necessary permissions on macOS, especially for fixed hotkey functionality.
Yes.
=> UI: Add functions to check for and request macOS permissions

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Before the scene items would be centered at the same spot
when centering them, now they are moved relatively to each
other.
Before:
https://user-images.githubusercontent.com/19962531/139073933-2be27287-04b2-4b65-a220-b11e72f53f27.mp4
After:
https://user-images.githubusercontent.com/19962531/139073975-0b132e82-f585-45dd-a595-ed9d38f0d5b5.mp4
Easier to align multiple scene items.
Selected multiple scene items and centered them vertically, horizontally and to scene.
=> UI: Relatively center multiple scene items

UI/data/themes/Yami.qss
Fixes an issue with Yami where the rgba function was used but only with three parameters
Qt complained at runtime:
`2022-07-25 23:51:18.556063+0200 OBS[56903:664716] QCssParser::parseColorValue: Specified color with alpha value but no alpha given: 'rgba 25,27,38'`
Yami still seems to work and no runtime errors (in that regard)
=> UI/themes: Correctly specify rgb instead of rgba

.cmake-format.json, UI/CMakeLists.txt, UI/frontend-plugins/aja-output-ui/CMakeLists.txt, UI/frontend-plugins/decklink-captions/CMakeLists.txt, UI/frontend-plugins/decklink-output-ui/CMakeLists.txt, UI/frontend-plugins/frontend-tools/CMakeLists.txt, cmake/Modules/CopyMSVCBins.cmake, cmake/Modules/ObsHelpers.cmake
Depends on:
- https://github.com/obsproject/obs-vst/pull/109
- https://github.com/obsproject/obs-browser/pull/372
This refactor allow to use automatically the available Qt lib (5 or 6). If both are present, 5 is the default.
Also remove usage of versioned Qt libs name usually with GuiPrivate, the macro add the unversioned target.
If QT_VERSION is not defined, it gets define with the AUTO value. And definition is moved to the helper file.
find_qt now:
- Check quietly for Qt5 and Qt6
- If QT_VERSION is set to AUTO, it checks firstly if Qt5 was found and it use it. If not it do the same for Qt6
- If QT_VERSION is set to 5 or 6, it checks if the choice was found and use it. And if not, it falls back to the other if found.
- If neither Qt5 or Qt6 are found, a fatal error is emitted.
- The …
=> Refactor find_qt CMake macro to select Qt version automatically if not specified

plugins/mac-capture/mac-screen-capture.m, plugins/mac-capture/plugin-main.c
Fixes availability of screen capture source on macOS 12.5 and also increases code efficiency when source is initialised and source type is changed.
Also fixes broken desktop capture because of a bug introduced in macOS 12.5.
While the `availability` checks will correctly detect macOS 12.5, the `__MAC_OS_X_VERSION_MAX_ALLOWED` macro is dependent on the platform SDK. The most current platform SDK is 12.3, hence why this version needs to be checked for.
Also reduces the amount of calls to the update callback (and reduces amount of calls to check for available capture content).
Also moves some code to only update data for currently selected capture type.
Tested on macOS 12.5.
- Code cleanup (non-breaking change which makes code smaller or …
=> mac-capture: Fix availability on macOS 12.5 and increase code efficiency

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
With https://github.com/obsproject/obs-studio/pull/5148, it was
brought up that the loading of the missing files was not thread
safe, as the missing files were being loaded late in the loading
process. This PR tries to fix that problem, while still simplifying
the original missing files code.
@norihiro brought up in the PR that the code was possibly not thread safe.
Deleted files and made sure the missing files dialog still worked.
=> UI: Fix bugs with missing files refactor

deps/obs-scripting/obslua/obslua.i, deps/obs-scripting/obspython/obspython.i, libobs/util/base.c
Fixes a `Function declared 'noreturn' should not return` warning in `bcrash()`.
Compiler: Apple clang version 14.0.0 (clang-1400.0.28.1)
Compiler didn't know that `crash_handler()` doesn't return, so it assumed it did, in which case the entire function would return.
Compiled (macOS 13).
One less warning (186->185).
=> libobs: Fix crash handler noreturn compiler warning

UI/window-basic-preview.cpp, UI/window-basic-preview.hpp
Adds the following changes to the preview:
- Double clicking a source will open it's properties.
- Double clicking a group will open up that group for editing in the preview.
- Optional rotation handle can be enabled in settings.
- Handles and lines will now scale depending on the DPI OBS is running at.
Double clicking a source to open properties saves needing to find the corresponding source in the sources list, and can be quicker to find the source you mean to change properties for.
Editing groups are currently very finicky at best, since there's no way to click into them in the preview.
Rotation handles, while unnecessary for most setups can be useful when needing to change rotations often, and not wanting to use the transform dialog, so is added as an optional handle easily enabled in …
=> UI: Add various preview improvements

UI/properties-view.cpp
When finding current item for a combobox on properties view, use `QVariant` type to hold current values instead of converting all types into string.
A combobox created with `OBS_COMBO_FORMAT_FLOAT` cannot show the current item. When a modified callback for another item on the properties view returns true, the combobox is initialized again and the selection goes to the top item even though another item is selected.
When adding items into the combobox, `userData` is generated in the code below.
https://github.com/obsproject/obs-studio/blob/e3f416f3fc72db49d1ba71b8423454d053a9d6bf/UI/properties-view.cpp#L505-L523
| OBS's type | `userData` generation function |
| ---------- | --------- |
| `OBS_COMBO_FORMAT_INT`    | `QVariant::fromValue<long long>(long long)` |
| `OBS_COMBO_FORMAT_FLOAT`  | …
=> UI: Search combo property item with QVariant type

UI/platform-osx.mm, libobs/obs-cocoa.m
Apple have used the "macOS" branding instead of the "Mac OS X" branding for a long time. 
The `sysctl` header used by first attempt of Rosetta detection is unused and to be removed.
https://github.com/obsproject/obs-studio/pull/5738#pullrequestreview-1037130964
These 2 commits are cherry-picked from #5738, which itself have these 2 commits.
Change of string should not cause a problem, same goes for remove unused header file.
=> macOS branding change and code cleanup

plugins/obs-ffmpeg/obs-ffmpeg-source.c
simply add judgement to check whether the media has video when update the media source settings
to ensures that don't show the last video preloaded frame and clean the source output when the source don't have video
Fixes #6818 
win10, ubuntu20
reproduce following steps:
1. add a media source
2. choose a video file and check Loop, press ok to apply
3. click `Pause Media`, and click the media control bar to seek other pos, and then click `Play Media`
4. change the media source file path with a audio file(without video and thumb, `has_video == false`), press ok
5. *work correctly* after fixed. ( vs *render wrong video frame*)
=> obs-ffmpeg: Don't show preloaded video when the media source without video

UI/forms/OBSBasicSettings.ui
UI: Deduplicate UI element names
Prevent some warnings from AutoUIC.
Want to avoid warnings. Even if UIC will automatically rename these and these don't prevent compiling, we should just fix them.
Compiled locally. AutoUIC warnings were gone. OBS built and ran fine.
=> UI: Deduplicate UI element names

libobs/obs-module.c
Adds the path of the failed plugin to the log error message, like for the message one statement earlier.
Compiler complained `More '%' conversions than data arguments`
Compiled.
Compiler stopped complaining.
=> libobs: Include plugin path in log error message

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adds WpStream to the list of RTMP services
WpStream is a live video streaming plugin for WordPress 
Streamline broadcasting for WpStream users by choosing our service from a list instead of typing/pasting the full RTMP address.
We tested this by replacing services.json on a few different computers (different OS) and also compiled on Windows and Mac with expected results. 
=> rtmp-services: Add WpStream service

plugins/win-capture/graphics-hook/dxgi-capture.cpp, plugins/win-capture/graphics-hook/graphics-hook.h, plugins/win-capture/graphics-hook/vulkan-capture.c
Skip DXGI interception when called as a result of a Vulkan "Present" call.
Some Vulkan apps for Windows use a DXGI backend, which is called by the Vk "Present" API call. That makes OBS double-hooked during the same call, first by the Vulkan hook, which then call its native implementation, which then calls the DXGI hook in return.
That makes the Vulkan call to capture_should_init true, then the D3D11 call to capture_should_init false, causing the d3d11_capture method to call d3d11_shmem_capture (as data.using_shtex still having its default "false" value), which in turn uses an unititialized mutex as the d3d11_init method has not been called, and leads to a crash.
This was tested on Windows 10 20H2, on a RTX 2070 Super with driver version 516.40, with the project at the last tagged revision …
=> graphics-hook: Avoid conflict between Vulkan and DXGI Present

plugins/win-capture/graphics-hook/d3d12-capture.cpp, plugins/win-capture/graphics-hook/dxgi-capture.cpp
Previous approach could mark Present exit too early.
Better queue heuristics can lead to more reliable capture.
Verified D3D12HDR sample still captures.
=> graphics-hook: Track DXGI status with counter

plugins/image-source/obs-slideshow.c
correctly variable next_hotkey instead of prev_hotkey
this variable should be `ss->next_hotkey`
https://github.com/obsproject/obs-studio/blob/8ef134be7955d3436282c85ff7e806bab2e6f28b/plugins/image-source/obs-slideshow.c#L657-L664
correctly the variable which assigned to `NextSlide` hotkey
Hasn't, is just a variable name change.
=> image-source: Correctly assign to variable next_hotkey instead of prev_hotkey

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/data/themes/Yami.qss, UI/obs-app.cpp, UI/obs-app.hpp
This enhances the existing theme loading system with Theme Meta, which allows individual themes to provide additional information to OBS.
The primarily goal is for a theme to define a "parent", allowing to extend existing themes with additional attributes, including extending/replacing an existing theme's palette.
Warchamp expressed he would like the ability to provide "palatte swaps" of a single theme - such as dark/light variants, without having to clone the entire QSS file.
While I've updated existing themes to include metadata, I'm leaving creation of palette swaps to Warchamp.
A future version of this will allow for additional QSS, but that requires other changes, so I'm submitting this separately first.
Create a new theme file `YamiChild.qss` with the following contents and load it. …
=> UI: Add support for theme meta, parent theme palette

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, docs/sphinx/reference-frontend-api.rst, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.h
Adds a function (`obs_frontend_recording_split_file()`) to the Frontend API that makes file splitting split the file when called, without waiting for the limit (size of time).
When called, the limits are reset. For example, if the limit is 15 minutes and the function is called after 6 minutes, the second split will occur after another 15 minutes (at the 21 minutes mark), so there's one file of 6 minutes and another file of 15 minutes.
This function will still require "Automatic File Splitting" to be enabled in the settings.
Asked for in Discord ideas channel.
Will allow for UI integration for splitting files manually (with button and/or hotkey),
however preliminary discussion has shown that this could be a bit more controversial
in terms of how it will be implemented, so that will follow …
=> obs-frontend-api: Add function for manual file splitting

plugins/mac-capture/mac-screen-capture.m
When looking for content, we exclude the desktop windows (mainly wallpaper) to keep the list in window capture smaller.
However, due to a bug with SCK on macOS 12 we have to use this same list to populate the display.
This means that we need to exclude them when the user has Window Capture selected, but include them for Display Capture so that they appears on screen there.
This PR assumes that the only reason that they are excluded is the window capture list length. @PatTheMav will still need to confirm this. Should there be other reasons for the exclusion this PR might not be a good idea.
Fixes the desktop wallpaper missing on Display Capture on macOS 12
macOS 13
Changed the guard to macOS 14 so that I used the same method to capture the display as macOS 12 would. Without this change, …
=> mac-capture: Don't exclude desktop windows in SCK window capture

CI/linux/02_build_obs.sh, cmake/Modules/FindLibrist.cmake, cmake/Modules/FindLibsrt.cmake, plugins/obs-ffmpeg/CMakeLists.txt, plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.h, plugins/obs-ffmpeg/obs-ffmpeg-rist.h, plugins/obs-ffmpeg/obs-ffmpeg-srt.h, plugins/obs-ffmpeg/obs-ffmpeg-url.h
This PR is a stand in replacement of the obs-ffmpeg-mpegts output
which currently relies on a pipe to obs-ffmpeg-mux binary.
This improves srt/rist handling.
Additionally this fixes several bugs related to auto-reconnect : 
- auto-reconnect is partially broken with srt & rist; the UI will display a successful reconnect even though it is not the case
because in obs-ffmpeg-mux.c the obs_output_can_begin_data_capture function is not called in the thread doing the reconnect. Fixes: https://github.com/obsproject/obs-studio/issues/6749 
- when non existing urls are used, if auto-reconnect is enabled, obs is locked up.  Fixes: https://github.com/obsproject/obs-studio/issues/5791
Currently srt & rist protocols are supported in obs through their implementations
in FFmpeg/avformat.
It is much …
=> obs-ffmpeg: Support native SRT & RIST output

CI/include/build_support_windows.ps1, CI/windows/02_build_obs.ps1, cmake/Modules/ObsHelpers.cmake
Restores the configuration output of CMake on Windows and adds the selected Qt version.
Allows better insight into how the Windows build is configured on CI and also enables quicker check for the Qt version selected for a build.
=> CI: Restore output of cmake configuration on Windows with Qt version

CI/include/build_support_macos.sh, CI/macos/03_package_obs.sh
This PR replaces the third party tool `xcnotary` with Apple's `xcrun notarytool`.
The command `xcnotary precheck` implements these check points. However there is no equivalent steps provided by notarytool so that the checks are omitted. Though the checks are omitted, at least some of them are checked on the notarization server so that it should not be a critical issue.
- DeveloperIdCheck
- HardenedRuntimeCheck
- NoGetTaskAllowCheck
- SecureTimestampCheck
`xcnotary` is discontinued since Apple now provides `xcrun notarytool`. See their README.md for details.
https://github.com/akeru-inc/xcnotary
Run the flow with my own credential and confirm the notarization succeeded.
https://github.com/norihiro/obs-studio/actions/runs/2761096817
- Code cleanup (non-breaking change which makes code …
=> CI: Use xcrun notarytool instead of xcnotary

UI/window-basic-main.cpp
When studio mode is enabled and OBS is first started, the program
scene label would be empty.
Fixes bug I've found
Opened OBS with studio mode enabled and made sure the program label was set properly.
=> UI: Fix studio mode label not updating

plugins/obs-transitions/data/fade_transition.effect
Simplified fade effect shader code.
Maintainability.
Tested both nonlinear and linear paths still faded correctly.
=> obs-transitions: Reduce code duplication

UI/qt-display.cpp
A QPlatformSurfaceEvent constant is used in a switch that only accept
QEvent type.
Meaning that `QPlatformSurfaceEvent::SurfaceAboutToBeDestroyed` (1) is casted to `QEvent::Timer` (1).
timerEvent() is missing the override keyword.
While I was working on #6759, I decided to try to build with Clang on Linux to check and found warnings related to what this PR is actually fixing.
With Weston on my GNOME (X11) on my NVIDIA machine, no hang while closing properties and filter windows.
~~Need the Flatpak artifacts to test it on my Wayland machine easily.~~
No issue on my Wayland machine with the Flatpak artifact.
Needs surely same testing as #6487.
=> UI: Fix close display before native surfaces

plugins/obs-filters/gpu-delay.c
Add support for delaying HDR frames.
No reason we shouldn't be able to support delaying HDR frames.
=> obs-filters: Add HDR support to Render Delay

plugins/obs-filters/sharpness-filter.c
Not sure how to implement controls for HDR, so skip unless SDR for now.
Don't want to apply SDR color processing on HDR video.
Checked sharpen settings work on SDR input, but passes HDR input through.
=> obs-filters: Add HDR bypass for sharpen

plugins/obs-filters/crop-filter.c, plugins/obs-filters/data/color.effect, plugins/obs-filters/data/crop_filter.effect, plugins/obs-filters/scale-filter.c
Add support for Crop/Pad of HDR frames.
No reason we shouldn't be able to support crop/pad of HDR frames.
=> obs-filters: Add HDR support to Crop/Pad

UI/screenshot-obj.hpp, UI/window-basic-main-screenshot.cpp
Use JXR for HDR video on Windows. Other operating systems will tonemap
HDR to SDR, and save to PNG. Continue to take PNG screenshots for SDR.
We will probably support EXR for Mac/Linux someday.
Want to be able to take HDR screenshots.
Verified JXR and PNG outputs look correct on Windows.
Verified PNG output on Mac for SDR and HDR.
=> UI: JXR screenshots on Windows

plugins/aja/aja-common.cpp, plugins/aja/aja-common.hpp, plugins/aja/aja-output.cpp
This PR causes the AJA Output plugin UI to only show video formats in the list if their underlying frame rate matches the current OBS canvas frame rate. The setting is placed behind an ifdef so that we can eventually add and test an algorithm to support incongruous frame rates.
The current AJA Output plugin can handle small frame rate discrepancies but larger differences would require adding an algorithm to drop or dupe frames when needed.
Additionally, the DeckLink plugin has the same behavior, so this change also adds some UI consistency between similar features.
Tested by selecting all OBS frame rates, and ensuring that the AJA output video format list either shows an empty list when a rate is selected for which there is no available AJA format, or we show the AJA formats which match …
=> aja: Only allow output formats matching OBS framerate

CI/macos/01_install_dependencies.sh
Fixes the Sparkle cache location for the local macOS CI build, by changing it from `"${DEPS_BUILD_DIR}/obs-deps/Frameworks/Sparkle.framework` to `${DEPS_BUILD_DIR}/obs-deps/lib/Sparkle.framework`.
I've been building OBS Studio a lot from source recently using `./CI/build-macOS.sh --bundle`, and whilst the first build works successfully, the second build fails with the following error:
```
[OBS-Studio] Set up dependency Sparkle v1.26.0
+ Download...
+ Sparkle-1.26.0.tar.xz exists and passed hash check
+ Unpack...
cp: cannot overwrite directory /Users/carrot/git/obs-studio/../obs-build-dependencies/obs-deps/lib/Sparkle.framework/PrivateHeaders with non-directory /Users/carrot/git/obs-studio/../obs-build-dependencies/sparkle/Sparkle.framework/PrivateHeaders
cp: cannot overwrite directory …
```
=> CI: Fix Sparkle cache location for local macOS CI build

CI/linux/03_package_obs.sh
In [`.github/workflows/main.yml`](https://github.com/obsproject/obs-studio/blob/8af6b79044c2d4176a915884c4c76b9a836828ab/.github/workflows/main.yml), for the linux_build job, the variable BUILD_FOR_DISTRIBUTION is set to the string "true" or "false" on CI. Later, in `CI/linux/03_package_obs.sh`, we perform a boolean check on this variable. However, "false" will evaluate as true, because it is a non-null string. This was causing CI Linux packages to always build as if BUILD_FOR_DISTRIBUTION was enabled, which caused the git commit hash to be omitted from package filenames.
Since we know the expected values, let's just test directly if the variable equals "true" to get the expected behavior.
https://github.com/obsproject/obs-studio/blob/8af6b79044c2d4176a915884c4c76b9a836828ab/.github/workfl …
=> CI: Fix Linux package filename version

deps/media-playback/media-playback/media.c, plugins/win-dshow/ffmpeg-decode.c
Figure out colorspace from TRC and primaries if necessary. AMF in
particular doesn't seem to provide full metadata.
More correct playback of files with missing metadata.
Debugger inspection of AMF-generated video file playback. Uses 2020 matrix instead of 709 now.
=> media-playback: win-dshow: Compute HDR colorspace

plugins/mac-capture/mac-screen-capture.m
Adds an option to SCK Application Capture to make the background transparent.
Only available on macOS 13, because on 12.5 the desktop icons (like drives, files and folders) show. Should this get fixed with a macOS 12 update (like 12.6) we'll make it available there as well.
Users might want transparency instead of just a black background.
macOS 13.
Tested that it doesn't work on 12 by changing the guards to check for macOS 14.
=> mac-capture: Add transparent background option to SCK App Capture

plugins/obs-ffmpeg/CMakeLists.txt
When compiling with the new flag these are required, if we dont fail
here we instead get a more cryptic failure that the targets are
unassigned later in the file. This should make it easier to find the
flag to turn off or packages being searched for.
Compiling obs-ffmpeg failed for an odd reason, this makes it a less odd reason.
Compiled obs-ffmpeg.
=> plugins/obs-ffmpeg: Mark rist/srt required when flag enabled

plugins/obs-transitions/data/stinger_matte_transition.effect, plugins/obs-transitions/transition-stinger.c
Allow stinger transitions to work with HDR.
HDR track matte might work, but would take a very carefully crafted video. SDR track matte should work in all situations.
More HDR support.
=> obs-transitions: Add HDR support to stinger

libobs/data/format_conversion.effect, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c
Update shaders to export 10-bit 4:2:0 SDR video with left chroma instead of top-left.
Update video metadata to indicate top-left chroma for 4:2:0 HDR video.
VLC now indicates correct chroma location for Rec. 2100.
Verified high-precision sRGB video still looks correct.
Verified SDR/HDR videos generated by NVENC has left/top-left locations set in VLC.
=> libobs: obs-ffmpeg: Fix some chroma locations

cmake/Modules/ObsHelpers.cmake
Fixes OBSHelpers overwriting the prefix set up by UseSWIG for scripting libraries.
SWIG uses the prefix target property to prefix generated Python libraries with an underscore (so that obspython.py is loaded first, which acts as a shim for the actual _obspython.pyd library on Windows).
Usually the prefix is set to an empty string on Windows (to avoid the automatic "lib" prefix used by CMake), but this also removed the necessary underscore prefix required for the Python library.
Tested with obslua and obspython on Windows 11.
=> cmake: Remove prefix suppression for scripting plugins.

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-preview.cpp
Removes calls to `devicePixelRatioF` from functions run on the graphics thread and use a property of passed object instead.
Calling `devicePixelRatioF` from any thread but the main UI thread triggers thread-safety warnings at runtime on macOS, because Qt uses NSView calls to determine the value.
NSView calls are only allowed to be made from the main thread on macOS, so instead the value is stored as a property of the OBSQTDisplay at initialization, to be retrieved from the preview object later.
Static functions that do not have access to the preview object have the pixel ratio passed in their call signature.
Tested on macOS, tests on Windows pending.
=> UI: Fix Qt UI call from graphics thread

libobs/obs-avc.c, libobs/obs-avc.h, libobs/obs-hevc.c, libobs/obs-hevc.h, libobs/obs-nal.h, plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.h
The spec for nal_ref_idc doesn't indicate that it should be used for
priority like x264 seems to be using it for. NVENC seems to pass
different values, so let's not rely on it.
The new scheme might be naive, but we can iterate on it, and apply
evenly to all H.264 encoders.
Also implement priority for HEVC over HLS.
Want to round out codec packet priority functionality.
Verified streams to Twitch (RTMP H.264), and YouTube (HLS H.264, HLS HEVC) appeared normal.
=> libobs: obs-ffmpeg: Update codec priority handling

plugins/win-wasapi/win-wasapi.cpp
Log only on first initialize failure.
Don't want log spam.
Verified log only on first connect attempt.
=> win-wasapi: Don't log if reconnect fails

UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
Callbacks had the wrong signature.
Want warning to be visible.
Warning works again.
=> UI: Restore color format/space warning

plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
The encoded_video_codecs field doesn't seem to be used though.
Also update HDR luminance to match pattern.
Demonstrate good ENABLE_HEVC usage, and output desired metadata.
Both muxers work on HEVC even without string, so there's that.
Debugger inspection for HDR luminance.
=> obs-ffmpeg: Make muxers respect ENABLE_HEVC 

UI/auth-youtube.cpp, UI/auth-youtube.hpp, UI/obs-proxy-style.cpp, UI/properties-view.cpp
Remove old ifdefs for compatibility with Qt versions prior to 5.10.
Ubuntu 18.04 is dead (to us), long live not having to support an ancient Qt version.
Still compiles with Qt 5.15.
- Code cleanup (non-breaking change which makes code smaller or more readable) -->
=> UI: Remove compatibility for QT < 5.10

plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c, plugins/obs-ffmpeg/obs-ffmpeg-srt.h
Replace [ftime](https://man7.org/linux/man-pages/man3/ftime.3.html) by [clock_gettime](https://man7.org/linux/man-pages/man2/clock_gettime.2.html) on *nix platforms.
Newer glibc version deprecated it and on macOS in `timeb.h` ftime is qualified as a "Legacy Interface".
Fix an incompatible-pointer-types warning.
- ftime is deprecated on newer version of glibc.
- incompatible-pointer-types warning looks bad.
Not used to test SRT and mpegts output, feedbacks about how to test are welcome.
=> obs-ffmpeg: Replace ftime on *nix platforms and fix incompatible-pointer-types warning

UI/forms/OBSBasicSettings.ui, UI/window-basic-settings.cpp
#6769 introduced a segfault with `ENABLE_PULSEAUDIO` turned off on Linux because the parent UI element gets removed.
This fix the segfault by removing neighborhood elements rather than the parent.
Note: the spacer was moved to avoid empty spaces in the group box.
Matt asked me to fix it, and I willingly did it.
Going to audio settings with `-DENABLE_PULSEAUDIO=OFF`, no crash with the PR.
=> UI: Fix crash if there is no monitoring available

deps/media-playback/media-playback/decode.c
Need to call mp_decode_clear_packets before destroying orig_pkt in case
packet_pending is true.
Don't want to crash.
Verified mp_decode_free doesn't crash for both packet_pending is true and false cases.
=> media-playback: Fix crash on free

libobs/obs-avc.c, libobs/obs-avc.h, libobs/obs-hevc.c, libobs/obs-hevc.h, plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
Parsing priority while serializing/discarding packet data is too gross.
Don't like gross code. Should also be a bit faster.
Debugger inspection of AVC/HEVC over HLS, and AVC over RTMP.
=> libobs: obs-ffmpeg: Use new priority parsing for HLS

.github/workflows/main.yml, CI/freebsd/03_package_obs.sh, CI/linux/03_package_obs.sh, CI/macos/03_package_obs.sh, CI/windows/03_package_obs.ps1
This makes the build names with each OS consistent with each other.
Makes it easier to work with them in different workflows.
Needs SEEKING_TESTERS tag to confirm.
=> CI: Change build file names

plugins/obs-ffmpeg/obs-amf-test/obs-amf-test.cpp, plugins/obs-ffmpeg/texture-amf-opts.hpp, plugins/obs-ffmpeg/texture-amf.cpp
- Avoid loading the AMF DLL before running the test process.
- Add timeout for the AMF test process in case it freezes.
- Fix typo causing min_qp_p / max_qp_p not to function.
- Use `get_ buf` function to ensure mutex is properly locked.
- Throw in `get_buf` if amf_format is invalid to fix possible uninitialized variable warning.
Make loading of the new AMD AMF encoder safer. Fix some small bugs.
Not at all as I don't have AMF.
=> AMD AMF Encoder Improvements

.github/workflows/main.yml, CI/linux/03_package_obs.sh, CI/macos/03_package_obs.sh, CI/windows/03_package_obs.ps1
On CI, do not fetch tags in packaging scripts. For some reason, the checkout action seems to locally update any new git tags on the runner:
t [tag update]   (commit-hash) -> tag-name
This causes future calls to fetch git tags to fail on CI with:
! [rejected]   tag-name -> tag-name  (would clobber existing tag)
To avoid this, we can simply not fetch tags a second time on CI.
Additionally, fix the Windows Installer job.
We want both CI and locally run scripts to work.
See lines 573-580: https://github.com/obsproject/obs-studio/runs/7618273262?check_suite_focus=true#step:2:578
See lines 43-46: https://github.com/obsproject/obs-studio/runs/7618273262?check_suite_focus=true#step:14:44
Tested on my fork's CI.
https://github.com/RytoEX/obs-studio/actions/runs/2778324498
- Bug fix (non-breaking …
=> CI: Fix packaging scripts

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json, plugins/rtmp-services/rtmp-common.c
Make optional `supported video codecs` and `supported audio codecs` by adding a fallback to H264 in `rtmp-services`.
`supported audio codecs` is not used for now so no fallback to AAC.
Remove field in the JSON that have only H264 or only AAC.
Opus ones are kept but are not used at all.
Also fixes incompatible-ponter-types warnings.
Some services don't have those fields which cause issue and those should be optional.
Service without those field are now considered compatible only with H264.
=> rtmps-services: Add fallback to H264 and some tweaks and fixes

UI/window-basic-settings.cpp
Fixes an issue where when you select manual file splitting, it would set time and size to 0, but not store it in the config and restore it in the settings when reopening them.
Manual splitting wouldn't be stored properly.
Next time, a bug report that's not written passive-aggressively would be appreciated, since that would mean that I could look at the report without getting mad at wrong/imprecise claims and/or accusations.
Manual file splitting with the hotkey still works.
When reopening the settings, it get's correctly reselected in the dropdown.
=> UI: Properly store manual file splitting type

plugins/aja/aja-output.cpp, plugins/aja/aja-output.hpp
This PR augments the existing audio delay algorithm in the output plugin to dynamically adjust both the video and audio delays, rather than just the audio delay, in order to maintain sync with the card's current output rate. The PR also increases the number of card frame buffers to a maximum of 8, increased from the current 2 frames, and tries to maintain a buffer level of 4 frames of video and audio at the current output rate.
_NOTE: I am submitting this PR on behalf of my co-worker, David S., who wrote both the existing audio delay algorithm and the new video delay algorithm code in this PR. If there are questions that I cannot answer, I will relay them to David and ask him to comment here, as I am not sure if he gets Github notifications._
- Added a video delay algorithm to the current …
=> aja: Fix frame duplication in output plugin

.github/workflows/main.yml
Manually install Xcode 14 beta 4 to compile OBS 28.0 with all new macOS features available.
GitHub's runner images do not include Xcode 14 yet. But we need it for macOS 13 specific features that are only in the Xcode 14 SDK.
Build: https://github.com/derrod/obs-studio/actions/runs/2785485502
=> CI: Install Xcode 14 beta for tagged builds

.github/workflows/steam.yml
Our new DMGs no longer have a subfolder that contains the `.app` apparently (at least when extracted this way). So this adjusts the paths.
Stop CI from failing and me from crying.
On my fork: https://github.com/derrod/obs-studio/runs/7643611723?check_suite_focus=true
=> CI: Fix Steam workflow for APFS DMGs

.github/workflows/flatpak.yml
Fixes the glob for the relase tag.
No Flathub release = big sad.
Verified it now matches `refs/tags/28.0.0-beta1` and `refs/tags/28.0.0-beta` in a local bash shell.
=> CI: Fix Flathub workflow tag validation

plugins/mac-capture/mac-screen-capture.m
Fixes a bug where the "Show hidden windows / applications" checkbox would only be
visible when opening the dialog, but not when it updates (for example when someone
switches from another method to Application Capture.
During the PR period for SCK we changed this checkbox to be visible for Application
Capture (since it has an effect there), but apparently this was forgotten to also be
changed when updating the dialog.
macOS 13
Checkbox now shows up when switching to Application Capture.
=> mac-capture: Show "hidden" checkbox for app capture on update as well

UI/lineedit-autoresize.cpp
Not sure why they were hardcoded in the first place. Different themes have different margins, the size should respect these.
Noticed that in some themes, the chat box would have a scrollbar. Which is bad, it shouldn't have that.
I don't like introducing bugs and then not fixing them.
macOS 13
Neither Yami, Dark, nor system theme have a scrollbar, and the box isn't visibly larger than it needs to be (meaning its size is exactly right).
=> UI: Don't hardcode margins in lineedit-autoresize

UI/window-basic-main.cpp
Calls the unregister function on the hotkey when clearing out hotkeys,
like for every other hotkey. Position in code is because it's in the same
order they were registered in (which I find nicer).
I am stupid.
Fixes #6914
Switching profiles no longer adds more hotkeys to the list.
Hotkey still works.
=> UI: Unregister file splitting hotkey when clearing hotkeys

UI/forms/OBSBasicSettings.ui
Increase maximum limits of time and file size to trigger splitting file.
New upper limits are 1024 TiB for split by size, 525600 minutes (365 days) for split by time. These upper limits should be large enough for any users.
Suggested on Discord.
https://discord.com/channels/348973006581923840/1004146447991709816/1004332982762475520
1. Added these change to obs-ffmpeg plugin (not included in this PR).
```patch
diff --git a/plugins/obs-ffmpeg/obs-ffmpeg-mux.c b/plugins/obs-ffmpeg/obs-ffmpeg-mux.c
index bf8e15fea..d08bdfd1c 100644
--- a/plugins/obs-ffmpeg/obs-ffmpeg-mux.c
+++ b/plugins/obs-ffmpeg/obs-ffmpeg-mux.c
@@ -403,6 +403,8 @@ static bool ffmpeg_mux_start(void *data)
stream->max_size = obs_data_get_int(settings, "max_size_mb") *
(1024 * 1024);
stream->split_file = …
```
=> UI: Increase maximum limit of automatic file splitting

UI/data/themes/Yami.qss
Typo in the Yami.qss file, "QTestEdit" instead of "QTextEdit".
Fix the typo.
Tested in W10.
- [x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x ] My code is not on the master branch.
- [x ] The code has been tested.
- [x ] All commit messages are properly formatted and commits squashed where appropriate.
=> Fix typo in Yami theme

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-opengl/gl-cocoa.m, libobs-opengl/gl-nix.c, libobs-opengl/gl-windows.c, libobs/graphics/device-exports.h, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h, libobs/obs-display.c
Some users stream projectors, so don't let them tear. Use the waitable
object to check the flip queue, and only flip if there's space.
Fixes #6936
Want to both have tear-free flip, and avoid stalling the graphics thread.
Used temporary instrumentation to both verify flip/no-flip repeating pattern for 120 Hz video on 60 Hz monitor, and that Present calls normally last 50-60 µs in the new setup.
=> libobs: Prevent D3D11 projectors from tearing

plugins/obs-ffmpeg/jim-nvenc.c
1. Correctly assign argument psycho_aq to false when retrying again without Psycho Visual Tuning.
2. Reinit encode session before retrying init encoder to fix crash
3. Code cleanup
1. notice that the argument `psycho_aq` was assigned unexpectedly when debugging
2. fixes #6911 
3. code cleanup mentioned by @jpark37 
the diff between 28 and 27.2.4(doesnt crash in this version mentioned by issue) https://github.com/obsproject/obs-studio/commit/699e89d8596e8f96c3d7d4448998ca73d2efac87
move the retrying code segments, and then in this way pass the `nvenc_destroy(enc)` and `init_session(enc)` procedure.
https://github.com/obsproject/obs-studio/blob/1444ead8123a3947ea12f1f515afd5741ee5936e/plugins/obs-ffmpeg/jim-nvenc.c#L689-L696
https://github.com/obsproject/obs-studio/blob/1444ead8123a3947ea12f …
=> obs-ffmpeg: Fix crash when retrying init encoder for NVENC

plugins/obs-ffmpeg/texture-amf.cpp
Replace TRANSCONDING with TRANSCODING for both H.264 and HEVC, becuase it is likely that the typo compatibility will be removed in a future AMF header update. This should also minimize confusion and improve search.
See: https://github.com/obsproject/obs-studio/blob/a1e8075fba09f3b56ed43ead64cc3e340dd7a059/plugins/obs-ffmpeg/external/AMF/include/components/VideoEncoderVCE.h#L50-L51
Currently uses an old typo. While currently valid, this could change when AMF headers are updated, so might as well correct it now.
Compiled on windows, recorded using the encoder (both h264 and HEVC), and inspect the outputs.
- Code cleanup (non-breaking change which makes code smaller or more readable) -->
=> obs-ffmpeg: fix USAGE typo

plugins/obs-filters/nvidia-greenscreen-filter.c
This resets the RTX greenscreen filter if the FX returns a CUDA error.
In case of a CUDA error 1099, the error can keep repeating locking up
the filter which is inoperant. So if such an error is detected we reset
the FX.
Bug fix.
After changing some properties of a webcam source, a lockup of the filter may occur with
a CUDA error 1099 which keeps repeating.
If that occurs, we fix it by resetting NVIDIA FX.
Tested on win 10.
Bug is fixed.
=> obs-filters: Reset RTX greenscreen on cuda error

libobs/obs-display.c
Call `GS_DEBUG_MARKER_END` outside the conditional block.
Order of `GS_DEBUG_MARKER_END` and `gs_present` is swapped, I think this is not a significant difference.
The conditional branch added by obsproject/obs-studio/6942 resulted `GS_DEBUG_MARKER_END` is not called when the branch condition is failed.
OS: Fedora 35.
Started OBS and checked displays show contents.
=> libobs: Fix missing pair of GS_DEBUG_MARKER

cmake/Modules/ObsDefaults_Linux.cmake
Fixes RPATH setting on Linux to use the correct variable notation.
The `$ORIGIN` variable for RPATHs on Linux has been erroneously using CMake's variable notation, which will obviously not work for Linux' library loader.
This PR fixes the issue by using the proper notation.
Tested on Ubuntu 22.
=> cmake: Fix plugin RPATH entry on Linux

deps/obs-scripting/CMakeLists.txt, deps/obs-scripting/obspython/CMakeLists.txt
Fixes #6946 
Avoid SWIG Python ABI flag on non-macOS POSIX rather than just Linux.
Work on my Arch Linux.
Need a sanity check for the macOS build.
=> obs-scripting: Fix SWIG flags for non-macOS POSIX

plugins/obs-filters/data/rtx_greenscreen.effect, plugins/obs-filters/nvidia-greenscreen-filter.c
Fix non-async sources, make sure math is linear-correct, preserve
incoming alpha, and allow the filter to work in previews.
Improve color correctness.
Verified main preview and filter preview look reasonable.
=> obs-filters: Fix NVIDIA greenscreen issues

cmake/Modules/CompilerConfig.cmake
Fixes CMake mistakenly assuming POSIX threading support in MSVC compilers.
Workaround for CMake issue https://gitlab.kitware.com/cmake/cmake/-/issues/23829.
Needs to be tested by affected reporters.
=> cmake: Fix broken pthread detection on Windows with CMake 3.24

cmake/bundle/macOS/Info.plist.in
Fix OBS.app appearing as an "iOS" app in macOS' system information overview of programmes available on the local machine.
MacOS' system information checks the CFBundleSupportedPlatforms value in the app's property list file for the type. This was correctly set for plugin bundles, but not binary bundles so far.
OBS built locally and checked in system information.
=> cmake: Fix M1-based OBS.app appearing as an "iOS" app

UI/installer/mp-installer.nsi
This updates the Windows Vista check to Windows 8.1 and lower.
This also improves the wording of the 32bit error.
Submitting this as a PR to get feedback on wording, and to determine if more 32bit/64bit code should be removed from the installer script.
With Qt 6, Windows 8.1 and below are no longer supported.
Additionally, 32bit is no longer supported.
* Launch the installer on Windows 8.1.
* Click "Next" to go past the first screen
* See error message
=> UI/installer: Require Windows 10 64bit minimum

deps/w32-pthreads/cmake/w32-pthreadsConfig.cmake.in, libobs/cmake/libobsConfig.cmake.in
Moves dependency imports for libobs above the target definition in the exported CMake package definition file.
CMake 3.24 implemented changes that break dependency discovery of the exported libraries build by OBS.
Specifically, without this fix, building obs-plugintemplate with CMake 3.24.0 will break.
This bug is _present_ on all other OSes as well, but because macOS and Linux supply POSIX threads as a static library, it is only resolved at project generation (much later step) and is not required by `libobsTargets.cmake` during creation of the `libobs` target.
On Windows `libobs` is linked against the shared library `w32-pthreads` and thus needs to be resolved at link-time and is added to the `IMPORTED_LINK_DEPENDENT_LIBRARIES` target property automatically. As such, the dependency needs …
=> cmake: Fix cmake package export templates for CMake 3.24

cmake/Modules/ObsDefaults_macOS.cmake, cmake/Modules/ObsHelpers.cmake, cmake/Modules/ObsHelpers_Linux.cmake, cmake/Modules/ObsHelpers_macOS.cmake, cmake/external/ObsPluginHelpers.cmake
~Fixed issues on Linux:~
* ~libobs and obs-frontend-api headers are not installed by default~
* ~RPATH for frontend-tools was malformed~
Improved behaviour on macOS:
* When a valid team ID is provided and the Xcode generator is used, automatic code-signing is enabled for all targets in the project
* Different deployment targets are set in Xcode for arm64 and Intel x86 when universal builds are configured
Other improvements:
* Support for legacy obs-browser submodule removed, because it is not necessary anymore
* Update plugin helper CMake script shipped in repository with more recent variant adapted from obs-plugintemplate
~The Linux fixes enable easier creation of distributable packages for maintainers and ensure that frontend-tools can find the scripting plugin if available.~
*Linux …
=> cmake: Improve code signing behavior on macOS

plugins/obs-filters/data/color.effect, plugins/obs-filters/data/rtx_greenscreen.effect, plugins/obs-filters/nvidia-greenscreen-filter.c
Add HDR support to AI greenscreen.
More HDR support.
Checked SDR image/camera, and HDR image/video.
Admittedly, I didn't check every color space combination, but the others should be rare, and follow the same pattern as other filters. We can fix bugs if they come up.
=> obs-filters: Support HDR AI greenscreen

libobs/obs-display.c
Don't mark up display draws if there aren't going to be any.
Don't need markers for empty draws.
Verified markers are still getting through to RenderDoc.
=> libobs: Remove display GPU markers without draws

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/forms/OBSBasicVCamConfig.ui, UI/record-button.cpp, UI/record-button.hpp, UI/window-basic-main-outputs.cpp, UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-vcam-config.cpp, UI/window-basic-vcam-config.hpp, libobs/obs-encoder.c, libobs/obs-internal.h, libobs/obs-source-deinterlace.c, libobs/obs-video-gpu-encode.c, libobs/obs-video.c, libobs/obs-view.c, libobs/obs.c, libobs/obs.h
Add the ability to render multiple "video mixes" where a "video mix" is ultimately a `render_texture` created by compositing scenes and sources that can be fed into one or more video encoders/outputs. 
This implementation splits `obs_core_video` keeping global resources in place and moving per-mix resources to a new `obs_core_video_mix` struct. It then updates the main graphics thread to render each channel of the `main_view` onto a separate `render_texture` / `obs_core_video_mix` rather than rendering them one on top of another on the same `render_texture` (I don't believe this old behavior was actual used since scenes and transitions achieve the same effect with a single `main_view` channel). GPU resource allocation has been deferred until the first render tick when a channel is …
=> libobs: Add support for multiple video mixes

plugins/obs-filters/nvidia-greenscreen-filter.c
Didn't notice two params were the same. Remove extra param.
Cleanup.
Verified filter still works.
=> obs-filters: Remove param from AI greenscreen

UI/data/locale/en-US.ini, UI/forms/OBSBasicVCamConfig.ui, UI/window-basic-vcam-config.cpp, UI/window-basic-vcam-config.hpp
The user could want to configure the virtual camera without starting it.
Also remove unneeded headers and `using namespace`.
Forcing the user to start the virtual camera to save settings is bad UI/UX.
The dialog no longer start the VCam and the "ISO VCam" still works.
=> UI: Don't force the user to start virtual camera after configuring it

.gitignore
We don't want this folder to be searched, as it's just a temp folder.
See `.github/workflows/main.yml:444` and `CI/windows/03_package_obs.ps1:37`
It's annoying to have it show up as untracked files in git.
Tested with git CLI and the fork client. The folder and its contents no longer show up.
=> .gitignore: Add "install_temp" folder

plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Adds the P010 enum case to the list of video formats that do not need to get converted to
NV12 as they are supported directly. This avoids an unnecessary performance penalty.
Importantly, this does NOT add any kind of HDR support to the virtualcam. If one of the
Rec. 2100 color spaces is selected, the image looked washed out before and still does. However,
now it's smooth instead of what looked like ~3fps (on my somewhat powerful Mac).
I actually noticed this when running across a crash when stopping the virtualcam, where when
one of the color formats that need to be converted (meaning I444, P010, I010; but not RBG which
seems to be a bit random in that regard) was combined with one of the color spaces Rec. 601,
Rec. 2100 PQ, Rec. 2100 HLG, it would crash.
This PR *does not fix the cause …
=> mac-virtualcam: Avoid conversion of P010

plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Converting the color space was likely accidental as it isn't explicitly
set. Unfortunately, not setting it means that it gets set to the
default, which is Rec. 709 and thus a conversion takes place when having
any other space. This conversion leads to a massive performance penalty
that isn't necessary.
When looking at the crash mentioned in #7034, I noticed a pattern where it would crash only
when converting the color format *and* having a non-default color space set. There, I stumbled
across the fact that the color space indeed isn't set and thus VIDEO_CS_DEFAULT is used which
when converting means Rec. 709. This is not good as it brings a performance penalty (which is
especially massive if you're using HDR), and we're fine using whatever color space (as seen with
any color format that …
=> mac-virtualcam: Don't convert color space when converting color format

libobs/obs-source.c, plugins/obs-filters/chroma-key-filter.c, plugins/obs-filters/color-correction-filter.c, plugins/obs-filters/color-grade-filter.c, plugins/obs-filters/color-key-filter.c, plugins/obs-filters/crop-filter.c, plugins/obs-filters/gpu-delay.c, plugins/obs-filters/luma-key-filter.c, plugins/obs-filters/mask-filter.c, plugins/obs-filters/nvidia-greenscreen-filter.c, plugins/obs-filters/scale-filter.c, plugins/obs-filters/scroll-filter.c, plugins/obs-filters/sharpness-filter.c
Filters need to chain against target to ask the next filter what its color space is, not parent.
Fix color space chaining exposed broken by HDR Tonemap, which can tonemap from HDR to SDR.
Checked each modified filter that it wasn't propagating correctly before, and is propagating correctly after.
=> libobs,obs-filters: Fix filter color space passthrough

UI/window-basic-main.cpp
Fix a crash introduced by the virtual camera UI changes. As part of that work the replay buffer button was refactored to be a reusable split button. This introduced an additional level of indirection which led to an incorrect null check when pausing or unpausing recording.
Fixes a crash when pausing or unpausing recording when the replay buffer is disabled (`replayBufferButton` is null).
Verified the bug before fixing, and lack of bug after the fix.
=> UI: Fix crash when pausing/unpausing recording

libobs/obs-internal.h, libobs/obs-video.c, libobs/obs-view.c, libobs/obs.c
Fixes a bug where enabling the new virtual camera when GPU encoding had already started (for streaming or recording) would cause the GPU thread to exit early. This early exit would result in the output getting stuck in the stopping state later.
Fixes bug reported in v28 beta 2
Repro steps:
- Start recording or streaming with a GPU encoder
- Start he virtual camera (this silently stops the GPU encoder thread)
- Stop the virtual camera (optional)
- Stop the recording or stream -> causes the UI to get stuck in a "Stopping..." state
Re-tested after the fix and was no longer able to reproduce.
The source of the bug was a DARRAY of video mixes containing structs rather than struct pointers. The GPU encoder thread holds a pointer to one of these structs which is invalidated when the DARRAY is …
=> libobs: Fix gpu thread termination when additional video mixes are added

UI/window-basic-main-outputs.cpp
Call `OBSBasicVCamConfig::StopVideo()` if `obs_output_start()` failed while starting a virtual camera output.
When failed to start virtual camera on Linux, memory leaks are observed.
1. Remove module `v4l2loopback` before starting OBS.
```
sudo rmmod v4l2loopback
```
2. Start OBS.
3. Start Virtual Camera.
4. Authentication dialog will appear to install the module `v4l2loopback`. Cancel it.
5. Exit OBS.
6. Check log file.
=> UI: Fix memory leak when virtual camera failed to start

.cirrus.yml
- Clone submodules too (for obs-websocket)
- Disable ALSA and AJA
- Add new deps (srt, librist, and libpci packages)
- Bump OS to most recent release, FreeBSD 13.1
- 
Restore FreeBSD CI build to green
Cirrus-CI run: https://cirrus-ci.com/build/5105257410723840
=> CI: Update FreeBSD Cirrus-CI configuration

.github/workflows/main.yml
Set Xcode 14 Beta as the active version on CI.
GitHub updated the runner image to include the 14 beta, so we no longer need to manually install it, saving us about 30 minutes of build time.
CI ran successfully.
=> CI: Switch to included Xcode 14 Beta

UI/data/themes/Dark.qss, UI/data/themes/System.qss
Steals a Yami fix and applies it to Dark and System.
Not added to Rachni / Acri since they will be changed to be palette swaps of Yami
Fixes #7050
Fixes #6300
This does make the themes a bit more ugly on macOS but that's an okay tradeoff, especially as no one should be using these themes anymore anyways.
macOS 13
Dock resizing now works properly on these themes.
=> UI/themes: Add macOS separator fix to Dark and System

.cirrus.yml
Update FreeBSD .cirrus.yml to stop setting UNIX_STRUCTURE.
UNIX_STRUCTURE was deprecated in df94b0207563.
Cirrus-CI run: https://cirrus-ci.com/task/4900659664257024
=> CI: remove UNIX_STRUCTURE from FreeBSD Cirrus-CI config

plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/texture-amf.cpp
Don't want to silently generate lossy video.
Don't want invalid videos out there. Leaks are bad.
Verified AMF H.264 can no longer record 8-bit HDR, and the error message looks as expected.
Verified AMF H.264 can no longer record 10-bit anything, and the error message looks as expected.
Verified AMF HEVC can no longer record 8-bit HDR, and the error message looks as expected.
Lots of debugger breakpoints to verify that the encoder destructors are called as expected in error situations for all code paths.
=> obs-ffmpeg: Prevent invalid AMF combinations, and fix leaks

plugins/obs-filters/hdr-tonemap-filter.c
That's the lower limit of max_display_mastering_luminance in the spec.
Range sanity
Verified both controls respect the new minimum values.
=> obs-filters: Don't allow HDR max below 5 nits

plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/obs-ffmpeg-av1.c
Don't want to silently generate lossy video.
Don't want invalid videos out there.
Verified 8-bit HDR fails with dialog for AOM and SVT.
Verified 8-bit SDR, 10-bit SDR, and 10-bit HDR videos still record successfully for AOM and SVT.
=> obs-ffmpeg: Block 8-bit HDR for AV1 encoders

.cirrus.yml
FreeBSD provides an ALSA compatibility library.  Install it, and leave ALSA support enabled as default.
Desire to test the FreeBSD build with as much functionality enabled as possible.
FreeBSD CI via Cirrus-CI is green with this change: https://cirrus-ci.com/task/5783415617224704
=> CI: Build ALSA support on FreeBSD

libobs/obs-nix.c
Previously FreeBSD had an optional port that installed /etc/os-release
so it was already available on many FreeBSD systems, but os-release is
now provided by the base system and will be universally available.
Improved diagnostic/error reporting, and consistency with Linux.
Running locally, I see "Distribution" in the log:
```
17:01:02.771: Using EGL/X11
17:01:02.771: CPU Name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
17:01:02.771: CPU Speed: 2000.00MHz
17:01:02.774: Physical Cores: 4, Logical Cores: 8
17:01:02.777: Physical Memory: 15678MB Total, 7362MB Free
17:01:02.777: Kernel Version: FreeBSD 14.0-CURRENT
17:01:02.777: Distribution: FreeBSD 13.0
17:01:02.777: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.14
17:01:02.778: Qt Version: 5.15.2 (runtime), 5.15.2 …
```
=> libobs: Read /etc/os-release on FreeBSD

plugins/linux-v4l2/v4l2-udev.c
udev_event_thread calls poll with two fds: the udev fd, and an eventfd
used for shutdown.  On FreeBSD we were hanging on shutdown in
udev_monitor_receive_device after receiving the eventfd event.
Now, if the udev fd reports no events skip the
udev_monitor_receive_device call.
At shutdown the loop will exit via os_event_try().
Avoid shutdown hang.
Tested locally on my FreeBSD laptop
=> Address shutdown hang on FreeBSD

plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Don't want to silently generate lossy video.
Don't want invalid videos out there.
Verified 8-bit HDR fails with dialog on H.264 & HEVC.
Verified 10-bit fails with dialog on H.264.
Verified I010 fails with dialog on HEVC.
Verified 8-bit SDR, 10-bit SDR, and 10-bit HDR videos still record successfully.
=> obs-ffmpeg: Prevent invalid NVENC combinations

libobs/obs-avc.c
H.264 spec only mentions zero/non-zero, but RFC 6184 uses 0/1/2/3 values
for prioritization. Go back to reading packet field for priority.
Want better packet loss behavior.
Logged type/keyframe/priority values, and they looked reasonable.
Regular Twitch stream worked okay.
=> libobs: Use nal_ref_idc for H.264 priority

UI/properties-view.hpp
I experienced a random crash under a debugger with heap validation active when changing items in the settings window. Further investigation showed that we're calling `obs_data_release` on an `OBSData` class member inside `WidgetInfo`, which I believe is incorrect behavior since `OBSData` will automatically call `obs_data_release` on destruction. This caused a double `obs_data_release` call when destroying `WidgetInfo`, which in the unlikely event of the `WidgetInfo` having an `update_timer` assigned AND the freed heap memory having `ref = 1`, would trigger a double-free crash.
Crashing bad.
Confirmed fixed the crashing for me. Additional eyes on this to make sure this is correct use of `OBSData` would be nice.
=> UI: Fix use-after-free in properties view

plugins/obs-ffmpeg/texture-amf.cpp
Adds b-frame value to the log file. After moving this option to the UI there would be no other way to know what b-frame value the user has set.
When checking for b-frame support, also set bf=0 so the log will reflect the actual value.
It is important for support purposes to know the b-frame value, as well as useful for users to know the when checking logs.
Tested on Windows 11, built, recorded with both h264 and HEVC. Recordings are fine, and log output is what is expected.
=> obs-ffmpeg: Add b-frame logging for the AMD encoder

plugins/obs-qsv11/QSV_Encoder_Internal.cpp, plugins/obs-qsv11/obs-qsv11.c
Do not restrict QSV resolution if CPU ID lookup returns "Unknown".
This should be removed and replaced with a proper check once the encoder implementation gets reworked for OneAPI-VPL and AV1 support.
Users with Intel dGPU (Arc) and AMD CPU would find themselves restricted to 1200p for no reason.
Hasn't.
=> obs-qsv11: Do not apply limits if CPU generation is unknown

UI/window-basic-main.cpp
macOS OBS plugins in following locations/formats will no longer get loaded with this PR:
- The plugin is a `.plugin` bundle, but located in the global application support directory (`/Library/Application Support/obs-studio/plugins`)
- OBS and the plugin have the arm64 architecture and the plugin has the `/bin` and `/data` folder structure (which effectively means it's an `.so` plugin)
This means that plugins are now only loaded if:
- They are a `.plugin` bundle in the user application support directory
- They are an x86_64 `.so` plugin
Important note: None of what got removed got released in a stable OBS release yet.
This does not break any setups just upgrading from 27.2 to 28.
Modern plugins on macOS are `.plugin` bundles.
They live in the user application support directory, so that …
=> UI: Enforce macOS plugin bundle on M1; don’t load plugin bundles globally

plugins/linux-v4l2/v4l2-udev.c
Fixes:		91f986ec9969 ("linux-v4l2: Check udev fd events")
Parentheses are needed due to operator precedence (although the previous
code happened to work because POLLIN has the value 1).
Fix bug in my previous change 91f986ec9969
OBS still exits successfully on FreeBSD here.
=> linux-v4l2: Correct udev fd poll event test

UI/window-basic-settings.cpp
This PR makes sure that the theme doesn't get set again if it's already set, since that'd be a waste and can cause small hiccups sometimes.
Noticed originally that theme switching is very bad on macOS. In the process, I noticed that the theme gets applied each time something in the combobox gets selected, even if it already was selected before.
macOS 13
Selecting the already selected theme no longer calls SetTheme
=> UI: Don't set theme if it didn't change

UI/obs-app.cpp
Setting a QStyle resets the color palette. This is unhelpful when a few
lines before that we set a new palette. In theory the setStyle call
could just be moved up, but we don't need to since we always set the
same style so there's no reason to call it multiple times.
Massive thanks to @Fenrirthviti for digging into the documentation.
Colors broke when theme switching (especially on macOS and Linux)
macOS 13
Switching themes now no longer appears to break colors.
Tested that the styleHint in OBSIgnoreWheelProxyStyle still gets respected after
switching themes (by setting it to 1 for the test(default on Mac is 0) and testing wheel
scrolling before and after, and it worked in both situations).
=> UI: Only set QStyle on app start

libobs-d3d11/d3d11-subsystem.cpp
D3D debug layer would INFO spam about RTV0 unbind for FLIP chains.
INFO spam potentially gets into the way of real issues.
INFO spam exists before; gone after. Was still able to preview & record a video.
=> libobs-d3d11: Unbind framebuffer before Present

plugins/obs-x264/obs-x264.c
We don't allow HDR for x264, so remove dead code.
Avoid confusion.
x264 SDR still works; HDR still errors out intentionally.
=> obs-x264: Remove unused HDR code

UI/window-basic-main.cpp, UI/window-basic-vcam-config.cpp, UI/window-basic-vcam-config.hpp, libobs/obs-view.c
Fix a memory leak on shutdown if the virtual camera is still active. Also fixes an untracked memory leak (C++ new/delete) of the `vCamConfig` by making it statically allocated.
- Reproduced leak on shutdown, implemented fix and tested that leak was gone.
- Added `new`/`delete` overrides to `VCamConfig` so that leak was tracked, fixed and then tested again that leak was gone before removing the overrides.
=> UI: Free virtual cam memory on shutdown

UI/window-basic-main.cpp, UI/window-basic-vcam-config.cpp, UI/window-basic-vcam-config.hpp
The `modules` object is more meant for plugins using the frontend API.
So this PR made the virtual camera configuration saved outside of the modules object in the Scene Collection.
This need to be merge before 28 is released, or it will become a breaking change.
This should be saved outside of the `modules` object.
My virtual camera config is kept between sessions and scene collections changes.
=> UI: Save virtual camera config outside of the modules object

UI/window-basic-preview.cpp
in obs28
1. Don't show sub-item SpacingHelper on locked group
Add judgment whether the sub-item's parent group locked or not
2. Correctly draw sub-item SpacingHelper on group
Recalculate the position of the sub-item source sides
1. Don't show sub-item SpacingHelper on locked group when sub-item of group source clicked in source list
before:
after:
2. Correctly draw sub-item SpacingHelper on group
before:
after:(with *pos moved*)
before:
after:(with *x and y scaled*, *pos moved*, *angle rotated* )
observe those changes
=> UI: Fix sub-item's SpacingHelper render on group

UI/obs-app.cpp
Qt translation strings use the full English string as an identifier, rather than a standardised key. Meanwhile, .ini files aren't designed
for keys with spaces, so a translation string for "Restore Defaults" won't match unless the ini line is
`"Restore Defaults"="Defaults"`
which is inconsistent, unpleasant and harder to read.
This fixes the "Restore Defaults" button in Filters and Properties to actually be translated using the right key.
In https://github.com/obsproject/obs-studio/commit/dbb063eae6a4b111ef6dabef5aeab5514d4a7b73#diff-fa7b36911cb29093d60306caac7b90c5e9d2d489b8f0ad563c4061be8d18e483R581 I changed the "Defaults" button from a Reset button with a modified label to use the built-in Qt button "Restore Defaults", not realising that the translation key wasn't being applied. …
=> UI: Remove spaces from translation keys

libobs/obs-internal.h, libobs/obs-source.c
~~1. Add function to limit texture filling size to avoid memcpy overflow in memcpy~~
Correctly set the async texture size,
based on the frame to be rendered on this loop,
rather than the newest frame from encoder when async delay filter on.
1. Fixes #6188
2. And fixes crash when preload frame remain but the source texture changed
(by media file changed or other situation, found in debugging other issues)
When using Video Delay filter, after the source media changed(especially when the media dimension size get bigger),
the frame pop from the delay filter with the old size, but the texture is changed by the newest frame.
https://github.com/obsproject/obs-studio/blob/bad54448ceb65b015a3b2c812a40920f6f78d8b1/libobs/obs-source.c#L2377-L2381
When occurs the mismatch between frame and texture, …
=> libobs: Fix the crash when Async Delay Filter on

plugins/win-dshow/CMakeLists.txt, plugins/win-dshow/virtualcam-module/CMakeLists.txt
Elgato has provided a submodule to support their devices, so use it. Also add support for HD60 S+.
Easier integration of bug fixes, and new device support.
=> win-dshow: Incorporate Elgato submodule

libobs/obs.c
Fixes a race condition where the video thread would exit because it sees no active mixes, causing OBS to freeze on startup. Introduced in https://github.com/obsproject/obs-studio/pull/6577.
Bug fix.
@tytan652 tested on Discord and confirmed it fixed the freezing he experienced.
=> libobs: Initialize main_view video mix before video thread

cmake/Modules/ObsHelpers_macOS.cmake
Fixes broken export of `libobs` Framework target on macOS.
For exported targets `INCLUDES DESTINATION` behaves in a specific way when running `install`: It sets the `INTERFACE_INCLUDE_DIRECTORY` for the target (relative to the `INSTALL_PREFIX` when a relative path is given).
This is not implicitly done by CMake, which resulted in the exported libobs Framework to miss the variable and as such targets linking to libobs were not able to find the necessary headers anymore.
Issue was introduced via https://github.com/obsproject/obs-studio/commit/8e3f19722e8818b57150e6f618df6ad2b55426aa.
Configured and exported `libobs` for use with obs-websocket's "4.9-compat-new" branch and successfully compiled obs-websocket with the updated `libobs` Framework. …
=> cmake: Fix missing interface include directory on Framework export

.github/workflows/flatpak.yml, .github/workflows/main.yml, CI/flatpak/com.obsproject.Studio.json
- Update the container image for the Flatpak CI, it just make flatpak-builder avoid installing the required runtime and SDK each time.
- Avoid cleaning libobs, FFmpeg and PipeWire pkgconfig files since plugin could need them to build.
- Revert #6561 because #6934 remove this requirement
Clean and fix.
~~CI is required to test this.~~
The CI Flatpak contains the pkgconfig, cmake and headers files as expected.
=> Various tweak/fix related to Flatpak

plugins/mac-capture/mac-screen-capture.m
Mac likes P3, but OBS only supports sRGB for SDR.
Fixes #7139
Aliasing P3 as sRGB is worse than clipping out of range colors, which shouldn't happen too often given that most SDR content fits in sRGB.
Recursive display capture colors were measured to be stable by Digital Color Meter with changes, and unstable without.
=> mac-capture: Clip gamut to sRGB

UI/obs-app.cpp
Adds the `typeName` when registering the meta type. As outlined in the Qt documentation, this should be done when registering typedefs: https://doc.qt.io/qt-6/qmetatype.html#qRegisterMetaType
The current implementation seemed to work in Qt 5, but no longer does.
@norihiro noticed that `obs_queue_task(OBS_TASK_UI, ...)` wasn't working anymore on his
machine and throws `QMetaMethod::invoke: Unable to handle unregistered datatype 'VoidFunc'`.
While I can't confirm the original issue on my system, @norihiro confirmed that this
fixes the issue (Fedora 35).
Also ran a quick code search to confirm that all other `qRegisterMetaType` calls include the typeName, this appears to be the only one missing it.
=> UI: Properly register VoidFunc in Meta Object System

UI/data/themes/Acri.qss, UI/data/themes/Grey.qss, UI/data/themes/Light.qss, UI/data/themes/Rachni.qss, UI/data/themes/Yami.qss
The disabled sliders would be the same color as the window background.
Before:
After:
Fix Yami bugs
Locked volume controls to make sure the disabled slider was colored properly
=> UI: Fix disabled sliders with Yami

plugins/mac-capture/mac-screen-capture.m
Render code seems unnecessarily custom. Use normal patterns.
Less is more.
Screen capture still works.
=> mac-capture: Use cleaner render patterns

UI/CMakeLists.txt, UI/crash-report.cpp, UI/crash-report.hpp, UI/forms/OBSLogViewer.ui, UI/frontend-plugins/aja-output-ui/CMakeLists.txt, UI/frontend-plugins/decklink-output-ui/CMakeLists.txt, UI/frontend-plugins/frontend-tools/CMakeLists.txt, UI/frontend-plugins/frontend-tools/scripts.cpp, UI/log-viewer.cpp, UI/plain-text-edit.cpp, UI/plain-text-edit.hpp, UI/properties-view.cpp
Since the Yami QSS changes the default font for widgets, we need
to force the system fixed font for plain text edits.
Fix Yami bugs
Opened log viewer to make sure it was the right font
=> UI: Force fixed font in plain text edits

libobs-opengl/gl-cocoa.m
Use sRGB instead of native display color space for correctness.
Projector colors should match main preview colors.
Verified windowed and multiview projectors were incorrect before change, and correct after with Digital Color Meter.
=> libobs-opengl: Fix Mac projector color space

UI/window-basic-main.cpp
The toggleControlLayoutAction (change between horizontal and vertical display mode) deletes and re-recreates the volume controls, meaning we were writing to freed memory. This is a kind of hacky fix but it's the only action we need to be concerned with for now.
This was introduced in v27 by https://github.com/obsproject/obs-studio/pull/4123.
Crash / memory corruption is bad.
Tested with debug heap, no crash / heap corruption reported after toggling 10+ times.
=> Fix crash when toggling volume control mode

UI/window-projector.cpp
Removes the `allProjectors` list from `window-projector.cpp`. It was reported that projectors were not being removed from this list on destruction, which resulted in a memory leak. However the list doesn't appear to be used at all, so we may as well get rid of it entirely unless it has some purpose I am missing? Also simplifies the multiview projector cleanup code.
Fix memory leak. Code simplification.
Ran OBS, verified projectors still behaved as expected.
=> Remove allProjectors list from window-projector.cpp

plugins/obs-ffmpeg/texture-amf.cpp
Move multiplication to when its passed to the encoder, so that bitrate
is kept in kbps. Changed for both for H264 and HEVC. Other encoders (x264 and NVENC) already display kbps in the log,
so it makes sense to mimic this with AMF. It's difficult to tell the exact bitrate with bps.
```
01:10:56.878: 	rate_control: VBR
01:10:56.878: 	bitrate:      25000
```
It's difficult to tell the exact bitrate with bps. Helps support volunteers and users who are used to seeing kbps in other encoders. I believe it's important to have units (kbps) as it reduces confusion, especially with AMF which has been displaying bps since its inception.
Tested on Win11, both texture-amf and fallback-amf, using H.264 and HEVC. Records fine, log output is as expected for all 4 variations.
- Tweak (non-breaking change …
=> obs-ffmpeg: Change AMF bitrate logging to kbps

libobs/CMakeLists.txt, libobs/util/threading.h
Using a relative path for the pthread.h header by w32-pthreads breaks compilation of plugins which include threading.h from libobs (as w32-pthreads will exist at a different location relative to the libobs header).
As w32-pthreads (and its include directory) is added to the libobs target by CMake, the pthread.h header will be found even when using system header notation.
Fixes https://github.com/obsproject/obs-studio/issues/7155
Fixes an oversight in libobs' threading.h header that was designed to be used within the obi-studio source tree, but is not compatible when used by plugins built out-of-tree (as desired and expected by the updated obs-plugintmmplate).
Built obs-studio on Windows 11 with updated header.
=> libobs: Use system header notation for pthread.h include

plugins/mac-capture/mac-screen-capture.m
Param is uint32_t, not bool.
Want code to be correct, and not misleading.
Verified screen capture still works on Mac.
=> mac-capture: Replace false with 0

libobs/obs-display.c, libobs/obs-internal.h
Allow fast clears in cases where we know it's safe.
Performance. Refinement of #7175
=> libobs: Avoid display clear workaround if possible

UI/scene-tree.cpp, UI/scene-tree.hpp
Adds a workaround for [QTBUG-105870](https://bugreports.qt.io/browse/QTBUG-105870).
This makes the user unable to deselect the current scene in the scene tree.
Does not fix same happening on the settings page but that isn't very important, it can
wait until the issue is fixed (or else wise clarified) on the QT side.
It's possible to very easily lose any indicator of which scene you're on, which can be an issue.
Fixes #7196
macOS 13
Clicked on the empty area, scene no longer gets unselected.
=> UI: Add workaround for scenes being unselected

libobs/obs-display.c
Apparently this isn't just a laptop issue.
Flicker is bad for sensitive people.
No regression in the single NVIDIA GPU case...
=> libobs: Extend NVIDIA anti-flicker to desktops

plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
Add overlooked metadata.
Want to provide reliable metadata for decoding.
Debugger inspection using SRT looks good. Didn't verify metadata appears on the other side, but we can work that out some other day.
=> obs-ffmpeg: Add AVContentLightMetadata to MPEG-TS

UI/source-tree.cpp
Attempting to resize the Sources dock to be smaller than when initially loaded would result in the contents of the list to never shrink.
Switching to another scene & back would temporary fix the sizing.
Fixes an issue introduced in adba393ca85fba19ed1bf6cd825ab8188beb2d16
Original bug video:
https://user-images.githubusercontent.com/941350/187218158-369e1485-616b-49ba-8a6f-93daa158d7d1.mp4
Users should be able to resize docks without running into bugs.
Bug reported by _m in Discord beta-testing.
Resize the Sources dock.
=> UI: Fix position of Sources dock actions on horizontal resize

UI/scene-tree.cpp
This PR is a collection of three commits to fix three distinct issues with the Scene Grid Mode:
1. Dropped items do not appear on the grid location where they were dropped
2. Scrollbar disappears when resizing or dragging while scrolled to the bottom and reappears when resizing or dragging after scrolling back up
3. While scrolled down, grid items repositioning while dragging do not reflect the grabbed object correctly
Fixes #5005.
https://user-images.githubusercontent.com/624931/187057609-cd0e071d-505d-4adf-9a94-6d82fbcccb3b.mp4
https://user-images.githubusercontent.com/624931/187057688-73ff8af5-672b-4163-b38e-ef0df938e93b.mp4
https://user-images.githubusercontent.com/624931/187057751-f0a7acbe-525a-4a01-915a-0171e1e7ea4e.mp4
https://user-images.githubusercontent.com/624931/187057766-6d967 …
=> UI: Fix Grid Mode operations

plugins/obs-ffmpeg/jim-nvenc.c
Forgot to switch enableEncodeAsync to 0.
Want NVENC HEVC to work.
HEVC works again. H.264 tested to still work.
=> obs-ffmpeg: Fix NVENC HEVC regression

UI/data/themes/Dark.qss, UI/data/themes/System.qss
Fix source context bar changing height on non-Yami based themes depending on the type of source selected. Not sure why this regressed, but with 28 coming up we need a fix regardless. Approved off-thread by @Warchamp7.
~~Also normalizes the theme files to use spaces instead of tabs.~~
Video of issue:
https://user-images.githubusercontent.com/876345/186013516-9a8e639e-f523-445c-86f6-9aec54214c73.mp4
The changing height of the bar made the user think they'd accidentally changed something when clicking as the preview window shrunk in response.
Tested Dark and System, verified no more jumping height. **Should ideally be tested on macOS and Linux if we have the time**.
=> Non-Yami Theme Source Context Bar Height Fixes

plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
With HEVC and H264 settings being near-identical, it was impossible to figure out which codec was being used by context alone. This applies to both ffmpeg output and jim-nvenc.
Fixes #6976.
Avoid confusion for user support.
Ran OBS, checked logs.
=> obs-ffmpeg: Log codec when creating NVENC encoders

UI/win-update/updater/hash.cpp, UI/win-update/updater/updater.cpp
Adds a new `removed_files` array to the manifest which allows to specify files to be deleted.
Originally this was supposed to go further [based on this discussion](https://github.com/obsproject/obs-studio/discussions/3885), but most of that seemed kinda overkill for what we actually need.
I wasn't able to build the updater originally, simply using the zlib package shipped with obs-deps fixed that, but ideally someone should document how it's actually supposed to work.
With the upgrade to Qt6, running the updater would otherwise leave a lot of orphaned `Qt5*.dll` files in the installation directory.
Built updater, ran it with modified manifest that removed the entry for `decklink-ouput.dll` and added the path to `removed_files` like so:
```json
...
"packages": [
{
"removed_files": [ …
```
=> Allow updater to delete files specified as removed in manifest

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/window-basic-main-outputs.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.h
This PR hide `Reset timestamps at the beginning of each split file` from the automatic split file when the format is other than MPEG-TS (`ts`).
When setting other than MPEG-TS, the setting will be overwritten to reset the timestamp.
Also invert the checkbox by changing the text.
- Old text: `Reset timestamps at the beginning of each split file`
- Revised text: `Preserve timestamps at the beginning of each split file`
The property marked by an orange box won't show unless user select MPEG-TS.
The option was originally provided for ease of debugging and also for some containers that support timestamp not starting from zero. However, some users could turn the option off even though the current container requires the timestamp starting from zero. In such case, user experiences the recording …
=> UI: Hide reset-timestamp property for file splitting

UI/data/themes/Dark.qss
Only the text source has not been corrected.
Before
https://user-images.githubusercontent.com/24505855/187587705-bb62711d-9d82-4b16-bef3-fff526c078f9.mp4
After
https://user-images.githubusercontent.com/24505855/187587717-528b7433-071c-4770-9a81-2ff90c4547f2.mp4
Bug reported in Discord beta-testing.
=> UI: Fix padding on context bar buttons in Dark

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
A problem was identified in the buffering thread added to `obs-ffmpeg-mux` in #5717. If FFmpeg seeked, wrote data and then seeked back to immediately overwrite it, the second seek would be skipped as our virtual offset was not being updated with the data offset caused by the first write. This caused MP4 corruption when seeking back in the file to write the moov atom.
Fixes https://github.com/obsproject/obs-studio/issues/7269
Fixes https://github.com/obsproject/obs-studio/issues/7144
Corrupting files by seeking incorrectly is bad 🙁
Reproduced the issue, confirmed fix worked.
=> obs-ffmpeg: Fix seek offset being calculated incorrectly

UI/win-update/updater/updater.cpp, UI/win-update/updater/updater.hpp
OBS Studio 28 no longer supports Windows 7, 8, or 8.1, and Qt 6 will fail to run on those versions. Users on those systems being offered the update will end up in a state where OBS will not run if they install the update. Let's prevent the updater executable from running on those versions to avoid that scenario.
Want to prevent broken installations.
Compiled locally, though I don't have a test Win7/8 installation to test the updater.
=> UI/updater: Only run updater on Windows 10+

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This reverts commit 829e906ac2b15d822173009cde5c90b5ec6c04c1.
Honestly this change annoyed me because it's a useful feature that got removed without replacement. And clearly I'm not the only one judging by some forum posts/comments about it (like https://obsproject.com/forum/threads/resize-output-missing-in-28-0-0.159123/ and on the PR/commit itself).
**Edit:**
To elaborate; one of the annoying design decisions in OBS is that canvas size is tied to profile, and not scene collection. Meaning that switching between profiles or scene collections can require you to change your canvas/output sizes. Sometimes this gets extra annoying because the scaled dropdown will default to something weird rather than what you select for the canvas. Being able to just right-click a fullscreen source and …
=> Revert "UI: Remove "Resize output (source size)" menu"

libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-capture.h, plugins/win-capture/data/locale/en-US.ini, plugins/win-capture/window-capture.c
We don't know if there's a way to get window color space, so we've been
using the monitor color space of the window. This toggle forces OBS to
ignore the monitor color space, and assume the window is SDR.
Good to treat SDR windows as SDR windows both for look, and filter compatibility.
=> libobs-winrt,win-capture: Allow forcing SDR

cmake/Modules/ObsHelpers_macOS.cmake
Ensure file permissions (e.g. executable bit) are copied when bundling OBS.
The Sparkle updater is broken due to missing executable bits in `Autoupdate.app` in 28.0 and 28.0.1, as reported for example in #7277
Ran update from CI build, ensured Autoupdate.app now runs (even though it refuses to install due CI build being a newer version).
=> cmake: Fix Sparkle framework permissions

plugins/win-capture/window-capture.c
Remove temporary code that never ended up being used.
Don't want dead code.
Window capture still works.
=> win-capture: Remove unused wildcard code

libobs/obs-video.c
Fast path for output texture shouldn't care what the effect is.
Simplify code.
Fast and slow paths are still taken as expected.
=> libobs: Remove unnecessary branch

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp, libobs/media-io/video-io.c, plugins/decklink/decklink-output.cpp
Fix up DeckLink video metadata, and use FFmpeg scaler to adjust for more conditions.
Don't want incorrect, untransformed data.
Don't have a test case that exercises this, but test case that doesn't is still working.
=> decklink,media-io: Use scaler for range and color space

plugins/win-capture/graphics-hook/d3d10-capture.cpp, plugins/win-capture/graphics-hook/d3d11-capture.cpp, plugins/win-capture/graphics-hook/d3d12-capture.cpp, plugins/win-capture/graphics-hook/dxgi-capture.cpp, plugins/win-capture/graphics-hook/dxgi-helpers.hpp
Log the DXGI_SWAP_CHAIN_DESC of the game for debugging.
Also add commit to remove some unused code.
More info can only make debugging easier.
Verified logging appears for D3D10, D3D11, and D3D12 applications.
=> graphics-hook: Print DXGI swap chain desc

UI/window-basic-main.cpp
OBS only populates the extraBrowserDocks list if `cef` is valid. By saving docks regardless of whether `cef` is valid, this can result in the user's custom docks being cleared unexpectedly.
This ensures the list is only saved if it was loaded in the first place. Consistent with
https://github.com/obsproject/obs-studio/blob/db766273b60a07a9a9b308b98f020e41a0658e56/UI/window-basic-main.cpp#L1954-L1968
Losing configuration is bad. Especially if it's unnecessary.
User reported that after updating, the browser component didn't load, and after running the Integrity Check, the browser component returned but custom browser docks did not. After digging, found the discrepancy in loading vs saving.
Closed and reopened OBS, verified docks were still saved.
- Bug fix (non-breaking change which fixes …
=> UI: Don't save/overwrite browser docks if CEF hasn't loaded

plugins/image-source/obs-slideshow.c
Update the media states of the image slide show when the source is de-/activated.
Add calls to `set_media_state` in `ss_activate` and `ss_deactivate`.
Currently the image slide show media state is not being updated properly in some circumstances:
For example it would continuously remain in `OBS_MEDIA_STATE_ENDED`, even if the slide show was restarted again due to the `behavior` being set to `BEHAVIOR_STOP_RESTART`, if the slide show reached its end at least once.
Similarly, the `OBS_MEDIA_STATE_PAUSED` state was never set in combination with `behavior` being set to `BEHAVIOR_PAUSE_UNPAUSE`.
This was discovered by @Zhaph in https://github.com/WarmUpTill/SceneSwitcher/issues/527 as checking the media state of the image slide show source did not function properly when using the advanced …
=> image-source: Update media states when source is de-/activated

UI/forms/OBSBasic.ui, UI/scene-tree.cpp
Due to QTBUG-106395, sources or scenes that are drag-and-dropped into the spacing between other sources and scenes would currently go to the bottom of the list, leaving users confused. Until that is fixed, we have to remove this spacing.
The call in scene-tree.cpp was redundant anyways, should this commit get reverted in the future it doesn't need to be re-added.
Fixes #7321
macOS 13
The spacing is gone in both the source tree and the scene tree, and sources can't be dropped anymore in a place where they would unintentionally go to the bottom.
=> UI: Remove spacing from scene and source tree

plugins/linux-capture/xcomposite-input.c
The void cookie will never return an error unless we use the explicitly checked version of this function.
Avoids getting annoying x11 errors later in the EGL calls.
Tested with some unnamable pixmaps and it works as intended.
=> linux-capture: Ensure name pixmap is checked

libobs/data/format_conversion.effect, libobs/obs-source.c
Sony cameras can create 8-bit HLG videos for some reason.
Fixes #7251
Make Sony camera users happy.
Verified I420 HLG renders now. Verified I420 SDR & PQ videos still play correctly.
=> libobs: Add support for reading I420 HLG

UI/hotkey-edit.cpp, UI/hotkey-edit.hpp
Re-enables full availability of hotkeys on macOS in OBS 28.
By default Qt will hand off key events to platform-native input methods on macOS because the OS or additional software can intercept key input and transform it (e.g. the international variations popping up when holding down the key for certain letters).
This functionality can lead to certain key combinations being ignored because they don't call the delegate methods implemented by Qt to handle the input after it's been interpreted by the Input Method.
Disabling Input Methods for hotkey input fields fixes this issue, as the native input methods are bypassed entirely and the key events are handled by the widget and its keyboard events directly.
Fixes https://github.com/obsproject/obs-studio/issues/7259.
* Tested on macOS 12.5
* …
=> UI: Fix hotkey settings screen not accepting all input on macOS

deps/obs-scripting/obspython/CMakeLists.txt
Ensures that the binary module for `obspython` uses the correct prefixed name.
The correct names for the `obspython` module require the Python loader module to be called `obspython.py` and the binary module to be called `_obspython.so` to ensure that the binary module is loaded by the Python wrapper.
Fixes https://github.com/obsproject/obs-studio/issues/7331.
* Tested on Ubuntu 22
=> deps: Fix broken prefix for obspython binary module on Linux

cmake/Modules/ObsHelpers.cmake
By default libraries and their CMake package files should be installed on Linux and FreeBSD and omitted on Windows. This explicitly adds FreeBSD.
Ensure that libraries, CMake packages, pkg-config, as well as header files are installed by default on FreeBSD as well as on Linux.
Fixes https://github.com/obsproject/obs-studio/issues/7289.
Tested on FreeBSD 13.
=> cmake: Fix CMake package files not being installed on FreeBSD

plugins/linux-v4l2/v4l2-output.c
Fix resource leak occurring on error path in Linux v4l2-output.
Resource leaks generally are to be avoided.
Manual code review.
=> Fix resource leak v4l2 output

cmake/Modules/ObsHelpers.cmake
The environment variable DESTDIR is commonly used to specify an install- time prefix for installation of build artifacts (e.g. for staging an installation in a temporary directory while keeping the overall prefixes intact).
This variable should be ignored by all targets but the install target, which requires us to set it to an empty string/path when we use `install` to set up our rundir.
Fixes https://github.com/obsproject/obs-studio/issues/7265.
Tested on Windows 11 and Ubuntu 22 (set a `DESTDIR` environment variable and observed only the `install` command installing files into the directory).
=> cmake: Fix rundir installation accepting DESTDIR environment variable

UI/window-projector.cpp
Fixes a crash that could occur after having a multiview opened and clicking a non-multiview projector.
https://obsproject.com/forum/threads/double-clicking-on-obs-projector-scene-causes-crash.159557/
Reproduced crash and verified it was fixed.
=> UI: Ignore left-click on non-multiview projectors

UI/source-tree.cpp
The Enter key is connected to the `Edit` function and is handled by Qt with the highest priority in its key event handler. Alas the boolean return value is not propagated to the shortcut handling system, so the key event will always be consumed and as such the user will be stuck in editing state.
To fix this, `Edit` needs to behave like a toggle, saving the current state of the input at a repeat press of Enter while in editing state.
Fixes https://github.com/obsproject/obs-studio/issues/7240
Tested on macOS, also tested that functionality is not impacted on Windows 11 and Ubuntu 22.
=> UI: Fix source name edit textbox not accepting input on enter

libobs-opengl/gl-cocoa.m
We are aware of OpenGL having been deprecated on macOS since Mac OS X 10.14, so silence the deprecation warnings the "official" way.
Remove unnecessary warnings from build output or Xcode project reports.
Tested with macOS 12.6.
=> libobs-opengl: Disable deprecation warnings on macOS

deps/w32-pthreads/CMakeLists.txt
When exporting w32-pthreads, the public header file `pthread.h` needs to be exported as well to expose the implemented functionality.
(`sched.h` is required by `pthread.h` and added as well.)
Fixes https://github.com/obsproject/obs-studio/issues/7155
Tested with a plugin template build on windows including `<util/threading.h>` from `libobs`.
=> w32-pthreads: Add pthread.h as public header

libobs/data/format_conversion.effect, libobs/obs-source.c
8-bit HDR shouldn't exist, but OBS looks broken, so just support it.
Uninitialized alpha looks broken.
- NV12/P010/YV12/YUY2 Rec. 709 all look like each other.
- NV12/P010/YV12/YUY2 Rec. 2100 PQ all look like each other.
- NV12/P010/YV12/YUY2 Rec. 2100 HLG all look like each other.
=> libobs: Add support for reading NV12/YUY2 PQ/HLG

.github/workflows/services-json.yml
Uses workaround described in https://github.com/actions/cache/blob/main/workarounds.md#update-a-cache to create a new cache every time.
Used to not work correctly.
Hasn't yet.
=> Fix service check cache

.github/workflows/main.yml
Set Xcode version to 14.1 beta.
GitHub thought it'd be funny to update their runner images and instead of being consistent and naming the Xcode 14.1 beta something like `Xcode_14.1_beta.app` it's just `Xcode_14.1.app`, and to top it off they then removed the 14.0 beta, yay!
CI completed successfully.
=> CI: Fix Xcode selection in new runner image

UI/window-basic-main-profiles.cpp
Ensures the volume controls decay rate is correctly updated on a profile switch, as there is no hook onto that UI event yet.
Without this change the decay rate would only be updated when an audio source is added or when the volume meter itself is changed (e.g. from horizontal to vertical layout).
Fixes https://github.com/obsproject/obs-studio/issues/7409
Tested on macOS 12.6 with 2 profiles and different decay rates (fast vs slow).
=> UI: Update volume controls decay rate on profile switch

plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm, plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm, plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Fixes an issue with empty IOSurface references on Intel-based Macs and also broken output when OBS is set to deliver full colour range output.
The plugin was missing necessary IOSurface locks to ensure that modifications to the underlying memory reference made by the OS do not occur when client code accesses the image data.
On machines without unified memory this can lead to IOSurfaces pointing to GPU memory even though the data has been moved to CPU memory by the OS (to avoid unnecessarily large copy operations) and a PixelBuffer created from the IOSurface won't contain data.
In addition to the issue above, FFmpeg's `swscale` seems to have issues with converting images with full colour ranges to limited colour ranges, resulting in mangled frame data inside OBS.
As macOS natively supports …
=> mac-virtualcam: Fix frame sharing and colourspace issues

plugins/obs-vst/headers/VSTPlugin.h, plugins/obs-vst/linux/VSTPlugin-linux.cpp, plugins/obs-vst/mac/VSTPlugin-osx.mm, plugins/obs-vst/obs-vst.cpp, plugins/obs-vst/win/VSTPlugin-win.cpp
Fixes crashes on M1 Macs introduced by the fact that most (if not all) VSTs available do not support the Apple Silicon (arm64) architecture.
VST bundles might be present on user systems, but symbols will not be loaded as most VSTs do not contain arm64 binaries. This can lead to non-null bundle pointers to invalid references, which crash the plugin once it tries to free the references.
This PR ensures that no valid bundle pointers exist if the bundle wasn't loaded.
Also hides the VST UI button in the properties if no valid VST is currently loaded.
Tested on macOS 12.6 with M1 Max.
=> obs-vst: Fix crashes and unusable property button on M1 Macs

plugins/coreaudio-encoder/encoder.cpp, plugins/mac-avcapture/av-capture.mm, plugins/mac-capture/mac-screen-capture.m, plugins/obs-transitions/transition-luma-wipe.c
Fixes property getter methods to work even with NULL sources passed into the method.
According to [OBS' documentation](https://obsproject.com/docs/reference-sources.html#c.obs_get_source_properties), the API call can also be used to fetch a _source type's_ properties, which means that no active source reference will be passed.
Some plugins haven't implemented their property getters with that in mind, which this PR fixes.
Fixes https://github.com/obsproject/obs-studio/issues/7020.
Requires additional testing.
=> plugins: Fix property getter methods crashing when NULL sources are passed

UI/window-basic-filters.cpp
Deleting a filter will trigger a visibility change, which will also trigger a focus change if the focus has not been on the list itself (e.g. after interacting with the property view).
When an async filter list is available in the view, it will be the first candidate to receive focus. If this list is empty, we hide the property view by default and set the view to a `nullptr`.
When the call for the visibility change returns, we need to check for this possibility, as another event might have hidden (and deleted) the view already.
Fixes https://github.com/obsproject/obs-studio/issues/7325
Tested with Colour Correction filter on macOS 12.6.
=> UI: Fix crash when removing filter after changing a value.

plugins/obs-filters/noise-suppress-filter.c, plugins/obs-filters/nvafx-load.h
This updates the model when swapping effects with NVIDIA Audio Effects. 
This fixes a bug where the model was not updated. :(
Bug fix.
Tested that the model is swapped correctly when changing the FX.
=> obs-filter: Update model for NVIDIA Audio FX

UI/window-basic-main.cpp, libobs/obs-video.c, libobs/obs.c
Don't need to unswizzle channels for DeckLink output in the future.
Want to set up more efficient DeckLink output.
Verified no regression to DeckLink NV12/RGB output, and x264/Intel NV12/RGB recordings.
=> libobs,UI: Swap red/blue render/output channels

plugins/obs-ffmpeg/texture-amf.cpp
The AMF docs specify that the maximum value for TARGET_BITRATE and PEAK_BITRATE is 100,000,000 bit/s. Trying to set values above this maximum value results in AMF choosing from its defaults instead of capping at the maximum value. Let's cap at 100,000 Kbps in the UI to prevent users from running in to this.
See: https://raw.githubusercontent.com/GPUOpen-LibrariesAndSDKs/AMF/v1.4.24/amf/doc/AMF_Video_Encode_API.pdf
Fixes #7423
Want less potential pitfalls.
Built and checked UI locally on Windows 11.
=> obs-ffmpeg: Cap AMF encoder at 100 Mbps

plugins/linux-capture/xcomposite-input.c
There were a couple mistakes here that caused the fallback checks other than window ID to fail to ever return valid results. This restores this functionality that was broken since the c++/c transition.
fixes #7404
Tested that capturing obs works, closing obs, openign and closing some windows and then starting obs again regains capture. Sometimes X11 will reuse window IDs so opening and closing some windows in the interim helps avoid this.
=> linux-capture: Fixup window name/class checking

libobs/media-io/video-io.c
Green tint appears when using converting full NV12 to limited NV12 with
swscale, so just avoid creating scaler by color range for now.
Fixes #7442
Green tint is worse than slightly off luminance.
Green tint no longer appears when outputting full range. Limited range still works.
=> libobs/media-io: Avoid scaler for range diff

libobs/media-io/video-io.c, libobs/media-io/video-scaler-ffmpeg.c
FFmpeg needs color range during context init to handle conversions. sws_setColorspaceDetails after the fact is too late.
Want accurate colors.
Verified full range colors were incorrect before and correct after in Discord preview.
=> libobs/media-io: Restore color range conversion

plugins/linux-pipewire/screencast-portal.c
This way the stream can be cleaned up. Otherwise, we closed them all when OBS closes which works but is not entirely correct.
On Plasma we show an element for each button and it would infinitely grow as we interact with OBS.
I've been testing this against our system and confirmed that Close is called as we replace the session_handle so the system can properly clean up the UI.
=> linux-pipewire: Close sessions as we are done with them

plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/texture-amf.cpp
SPS/PPS header insert
When recording in m3u8 format using AMD HW H.264, the second and subsequent TS files are broken.
Fixed second and subsequent TS files are broken.
Tested with start recording in OBS Studio
=> obs-ffmpeg: Fix m3u8 recording in AMF

UI/item-widget-helpers.cpp, UI/scene-tree.cpp
In the scene tree, we currently prevent deselecting items by automatically reselecting a new one to workaround a regression in Qt 6.2 that would let users unselect items even in SingleSelection QItemViews. When clearing however, we explicitly want to unselect the currently selected item, so we should avoid reselecting it in the SceneTree.
Fixes #7280
macOS 13
The unintended side effect of the original commit (the selected transition getting greyed out when switching scene collections) no longer happens, the transitions combobox is still enabled.
=> UI: Don't reselect SceneTree items if tree is clearing

deps/obs-scripting/obs-scripting.c
Fix compile when python is not found
I want to be able to compile without python
On windows 64 bits compiling without python
=> obs-scripting: Fix compile when python is not found

plugins/win-wasapi/win-wasapi.cpp
Unnecessary reconnect attempts may cause noticeable hitches.
Don't want hitches to occur, particularly when a scene collection may contain a ton of inactive application audio captures.
=> win-wasapi: Don't reconnect when inactive

UI/window-basic-main.cpp
When the Advanced Output configuration is set to use custom FFmpeg output, automatic remuxing is disabled. Unfortunately this check will also take place even if Simple Output is used (as the value is set in the configuration data, but is not "active").
This check ensures that the check for custom FFmpeg output is only applied when Advanced Output is enabled.
Fixes https://github.com/obsproject/obs-studio/issues/6903
Tested with different Simple and Advanced Output and custom FFmpeg enabled and disabled.
=> UI: Fix AutoRemux not working in Simple Output mode when custom FFmpeg output is configured

plugins/win-wasapi/win-wasapi.cpp
Fix hang when audio capture is active in the background and stopped by either closing OBS, or switching scene collections.
Don't want OBS to hang.
Verified both cases were broken before, and fixed after.
=> win-wasapi: Fix Stop hang

CI/linux/01_install_dependencies.sh
The CI build script is useful to build OBS Studio even outside the CI environment. However, the current script hard codes adding the 'amd64' architecture to dpkg, the Debian/Ubuntu package management database. This breaks the system when run on non-x86 machines. e.g., a linux-aarch64 VM running on an Apple silicon macbook. Fixing the system requires telling dpkg to remove 'amd64' again with 'sudo dpkg --remove-architecture amd64'
As the CI build always runs on an amd64 machine, adding amd64 is not necessary and can be safely removed.
Tested locally on an Ubuntu linux-aarch64 virtual machine. Also tested by pushing out to GitHub and passing all Linux build actions.
=> CI: fix build on non-x86 Linux platforms

deps/obs-scripting/obspython/obspython.i
Re-enables Python annotations which were automatically disabled by the upgrade to SWIG 4. swig/swig@2072ae19c
This was previously available in OBS 27.2.
Additionally enables autodoc to provide the same information to apps such as VS Code.
**Before:**
```py
def obs_property_set_long_description(p, long_description):
return _obspython.obs_property_set_long_description(p, long_description)
```
**After:**
```py
def obs_property_set_long_description(p: "obs_property_t *", long_description: "char const *") -> "void":
return _obspython.obs_property_set_long_description(p, long_description)
```
**Before (same with/without annotations):**
```py
def obs_property_set_long_description(p: "obs_property_t *", long_description: "char const *") -> "void":
return …
```
=> obs-scripting: Re-enable Python annotations; Enable Python autodoc

UI/forms/OBSBasicSettings.ui
Define tabstop based on the location of widgets.
Some tabstops are not defined or just defined at the end.
Checked the tabstop numbers on Qt Creator by eyes.
These two widgets are still not correctly defined the tabstops because these are created from C++ code.
- Hotkeys on Audio tab.
- `Twitch VOD Track` on Streaming section for Advanced Output.
=> UI: Fix tabstop on settings dialog

UI/data/themes/Acri.qss, UI/data/themes/Grey.qss, UI/data/themes/Light.qss, UI/data/themes/Rachni.qss, UI/data/themes/Yami.qss, UI/volume-control.cpp
With the Yami themes, the volume sliders wouldn't
be aligned in the center of the layout.
Before:
After:
Fix UI bugs
Looked at sliders to see if they looked good.
=> UI: Fix alignment of volume sliders

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adds two new FTL ingest locations for our existing FTL service.
Adds some Glimesh RTMP ingests in parallel of our existing infrastructure.
Confirmed the JSON files are both valid, and tested them locally in my OBS client to ensure they show up in the UI and work correctly.
- Service Change / Addition
=> rtmp-services: Update Glimesh to add RTMP ingests

libobs/data/format_conversion.effect, libobs/obs-source.c
Expect left for 4:2:0 SDR and 4:2:2, and top-left for 4:2:0 HDR.
MJPEG will be a half-pixel off, but we'll live with that for now.
Want symmetry with OBS output, and closer adherence to standards.
Verified color output and texture coordinates in RenderDoc:
=> libobs: Sample video at default chroma location

plugins/win-capture/game-capture.c
While the inject-helper tries to hook an application, the source is set to `active` until the `inject-helper` reports being unable to hook.
If the graphics thread updates the transformations of every source in that time frame, the game-capture source will report the width and height used from the last valid capture, leading to its selection box flickering in and out of view.
Ensuring that width and height are only reported when the source is not only made active but is also capturing content fixes the flickering issue.
**Note:** This is a naive fix, but possibly the easiest one for the reported issue.
Fixes https://github.com/obsproject/obs-studio/issues/7569
Tested on Windows 11 with an active game in windowed mode and another application that cannot be hooked by the `inject-helper`.
- …
=> win-capture: Fix reporting valid width and height if not capturing

UI/volume-control.cpp, UI/volume-control.hpp
Casting a floating point type to an integer type has undefined behaviour if the value does not fit into the destination type.
As the volume meter is initialized with floats values representing +inf (as makes sense for a dB meter), values should be explicitly clamped to integer boundaries.
Fixes https://github.com/obsproject/obs-studio/issues/3262
Tested on macOS 12 by stepping through each step of the paint function and checked that the initial values of `+inf` were correctly converted into the integer maximum values, with smaller values fitting into `int` converted accordingly.
=> UI: Clamp float values possibly representing infinity to integer size

UI/window-basic-settings-stream.cpp
The wrong preset is set for NVENC AV1 while resetting encoders.
NVENC AV1 is maybe not available for streaming for now, but it's still a bug.
Fix that.
Can't test.
=> UI: Fix NVENC AV1 preset while resetting encoders

plugins/linux-pulseaudio/pulse-input.c
Ask the PA server to kindly not migrate our streams to the default device unless the user chose the default device for input/output captures.
Fixes #3211
Tested with some default and non-default sources. Changing the default device in `pavucontrol` no longer causes non-default sources to be migrated to the new default device. Default sources continue to migrate as the default device changes.
=> linux-pulseaudio: Use DONT_MOVE for non-default devices

plugins/obs-vst/obs-vst.cpp
Fix visibility of VST window display button on first selection of VST.
A prior patch made the button to show/hide a VST check the current status of a loaded VST. This lead to situation where upon first selection a VST might be loaded but the button's visibility is not changed.
This change will reevaluate the status of a loaded VST upon selection in the drop-down menu and trigger button visibility accordingly.
Tested with multiple VSTs on macOS 12.
=> obs-vst: Toggle properties button visibility upon VST selection

plugins/vlc-video/vlc-video-source.c
When a user clears a missing file on VLC Video Source, properly remove the file instead of setting an empty string to the file list in the property.
Also try to avoid sending NULL pointer or an empty string from the property to further internal functions.
When a user clears a missing file on VLC Video Source, an empty string will be passed to `missing_file_callback`.
Then, the empty string will be set to the `files` list.
1. Create an instance of `VLC Video Source` and specify a local file.
2. Remove the file.
3. Restart OBS
4. On `Missing Files` dialog, clear the file.
5. Click `Apply` button.
Before this fix, OBS crashed immediately after clicking `Apply` button.
With this fix, OBS does not crash. I also confirmed no memory leaks.
=> vlc-video: Fix crash at removing files from missing-file dialog

UI/data/locale/en-US.ini, UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Moves the "Always On Top" option from the "File" menu into the "View" menu.
This also requires putting the "Multiview (Fullscreen)" and "Multiview (Windowed)" actions into UI files instead of generating them in code, so that we can put the "Always On Top" action below it (without having to add it from code as well). That's something that should have been done at some point anyways though.
The View menu is the correct place for options like these. The View menu was added after the Always On Top option, but the option was never moved to it.
macOS 13
See screenshot above.
Tested that the multiview actions (both windowed and fullscreen) still work.
Tested that toggling Always On Top still works.
=> UI: Move "Always On Top" into View menu

deps/obs-scripting/obs-scripting-python.c
When loading a new Python script, the GIL might be released while importing the module, allowing the tick to run and change and reset the `cur_python_script` state variable. Use the `busy_script` variable to save and restore the value if not null.
Fixes https://github.com/obsproject/obs-studio/issues/3209
Tested with scripts provided in the linked issue, confirmed the script name prefix is correctly used.
=> obs-scripting: Fix script state variable being reset by tick callback

plugins/mac-capture/mac-audio.c
Adds the sample rate of an audio input/output capture device to the log file.
Requested for support purposes.
Useful to easily see sample rate mismatches.
macOS 13 Beta 10
Initialized different devices, saw the sample rate being logged (see above).
=> mac-capture: Log CoreAudio device sample rate

deps/obs-scripting/obs-scripting-lua.c, deps/obs-scripting/obs-scripting-python.c, docs/sphinx/scripting.rst
Adds function call to enumerate over items contained in a source group.
Implements functionality requested in https://github.com/obsproject/obs-studio/issues/2788.
Tested with Python 3.10 and Lua.
=> obs-scripting: Add obs_sceneitem_group_enum_items function call

UI/forms/OBSBasicVCamConfig.ui, UI/window-basic-vcam-config.cpp
This re-enables the individual source selection option in the virtual camera config window. In order to address the previously identified sizing issue, it now creates a private scene to add the source to and applies a transform the fit the source to the canvas size. Essentially it transparently automates the steps under [Show a single source in the virtual camera](https://obsproject.com/kb/virtual-camera-guide) help article.
This feature was pulled right before OBS 28's release due to the sizing issue. This PR fixes that issue and re-enables the individual source selection option.
Testes primary with a webcam source by re-importing the vcam into OBS and then selecting different custom resolutions for the webcam. In all cases the webcam was resized and centered within the vcam's output. …
=> Re-enable Virtual Camera Source Selection with Scene Transform

UI/obs-app.cpp
The old preset "mq" was "Max Quality", which used the old HQ preset with two-pass enabled. The old preset "hq" was "Quality", which used the old HQ preset without two-pass. Of the two, "mq" would have been considered "slower" or "higher quality" than "hq", so let's swap these entries.
Note: There is perhaps some argument to be made that "mq" and "hq" should simply both map to P4/P5 with different multipass settings, but let's get the simple fix out of the way before getting stuck on other items.
Reference:
https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-preset-migration-guide/index.html
Want more accurate migrations.
Checked locally that recording encoder settings are migrated as follows on application start:
* hq -> p4
* mq -> p6 …
=> UI: Swap mq and hq NVENC Preset mappings

UI/window-basic-preview.cpp
Selection state can change by main thread while UI thread (which calls DrawSpacingHelpers) tries to evaluate the amount of selected items. Get amount of selected items by enumerating over the scene data instead (which stays within the graphics thread).
Fix possible crashes introduced by quick UI changes and resulting race conditions.
Tested on macOS 12.6 and step-debugging through the function to check if any calls leave the graphics thread boundary.
Spacing helpers are not displayed when multiple items are selected and moved in the preview.
=> UI: Fix possible crash due to UI property access from graphics thread

UI/window-basic-main-outputs.cpp
Fixes the title of the "Failed to start replay buffer" window for *Advanced* Output replay buffer which currently (wrongly) says "Failed to start recording".
Noticed this oddity when working on an unrelated PR.
Hasn't. These dialog titles don't get shown on Mac. However, I checked that the correct string already exists and honestly, I personally think the patch is probably simple enough.
=> UI: Use correct title for failed replay buffer start

.github/workflows/flatpak.yml, .github/workflows/main.yml, .github/workflows/steam.yml
GitHub Actions has deprecated set-output. Replace usages of set-output in stdout with the new syntax to save the output to the new environment variable.
See:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Don't want deprecation warnings hiding real issues.
It hasn't. This was written by following documentation. A CI run will be the test.
=> CI: Update GitHub Actions for set-output deprecation

plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm, plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm, plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Fixes crashes that could happen in applications that load the virtual camera multiple times consecutively or in parallel and improves performance on M1-based Macs.
Without invalidating the mach port used for sharing the IOSurface between OBS and the application displaying the virtual camera output, IOKit seems to run into the issue of receiving "shared" mach ports, possibly because of port exhaustion. IOKit requires a "new" port however and crashes upon that error otherwise.
Fixes https://github.com/obsproject/obs-studio/issues/7287
Additionally, because Apple Silicon-based Macs have a unified memory architecture, an IOSurface will always be available in memory accessible to the CPU and GPU (and an off-load of the IOSurface will not take place).
eGPUs are not supported on Apple …
=> mac-virtualcam: Fix crashes in apps loading virtual camera and performance fixes

CI/steam/scripts_macos/launch.sh
Apparently Steam running the OBS launch script makes it run inside Rosetta as well, so it ended up launching the x86 version even on arm64 systems.
Explicitly detect Rosetta translation and set arm64 in those cases. Still allow users to override this by specifying `--intel` as a launch parameter.
This wasn't caught until #7617 due to the script working fine when just run from a terminal (and our macOS user numbers on Steam being rather small).
Want to run native version where possible.
Modified script locally before launching through Steam to verify.
=> CI: Fix Steam launching x86 version under Rosetta

docs/sphinx/conf.py, docs/sphinx/requirements.txt
Fixes the extension definition of sphinx-napoleon for Python 3.10 per official docs:
> As of Sphinx 1.3, the napoleon extension will come packaged with Sphinx under sphinx.ext.napoleon. The sphinxcontrib.napoleon extension will continue to work with Sphinx <= 1.2.
Restore functionality of sphinx-build on Python 3.10+.
Tested on macOS 12.6 with Python 3.10.7
=> docs: Fix sphinx import error on Python 3.10+

plugins/linux-v4l2/v4l2-output.c
Fix #4808 by applying insights found at https://github.com/floe/backscrub/issues/133#issuecomment-1085598710
At the same time, apply more logging and improve error handling to said module such that any future challenging behaviour can be identified more easily.
* Build OBS from git, install as portable, on Fedora 36
* Start OBS, load scene collection
* Click "Start Virtual Camera" 
* Click "Stop Virtual Camera" 
--> works; now demonstrating that this fixes the reported problem, do
* Click "Start Virtual Camera" 
* Click "Stop Virtual Camera" 
... and this now works.
Video does work, too - tested with Firefox 103 and the Slack (https://slack.com/) web interface, device configuration -> OBS.
Fixes #4808
=> Fix virtual camera can only be started once on Linux

UI/obs-app.cpp, UI/obs-app.hpp, UI/window-basic-about.cpp
Adds new internal `steam` flag and hides donate link when running under Steam.
Playtest app failed Valve review due to donation link in-app, to make use of it and make #7560 useful just hide the link when launched from Steam.
Hasn't yet, I'm too tired and my PC is too slow to compile before my face will hit the keyboard
=> UI: Hide Donation CTA when launched from Steam

UI/obs-app.cpp
Do not include `--portable` option in help options if not enabled in current build.
Do not show option that is unavailable.
Compiled on macOS, option no longer shown.
=> UI: Hide --portable from help text if disallowed

UI/window-basic-main-outputs.cpp
The new NVENC preset is set with the `preset2` key in the encoder settings.
Currently, simple mode will its preset with the old `preset` key, resulting in the default (P6) always being used. 
The [switch statement](https://github.com/obsproject/obs-studio/blob/89eeeb9c653adc75e75cdd5be9fd507b7f42c1cf/plugins/obs-ffmpeg/jim-nvenc.c#L463-L495) to map old presets to new ones does get entered from what I can tell, but of course none of the strings match up.
It was reported on Discord that Simple Mode always uses P6, no matter which preset was selected.
~~Hasn't, as I don't have an NVIDIA card (or a Windows system to begin with).
I've asked people to test, this PR will stay draft until this fix is verified to actually work.~~
Verified on Discord by Sapiens that this fixes the issue
- Bug fix …
=> UI: Set preset2 instead preset for simple mode NVENC

UI/obs-frontend-api/obs-frontend-api.h, UI/window-basic-main-screenshot.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-frontend-api.rst
This adds a frontend event for when a screenshot is taken.
https://ideas.obsproject.com/posts/1928/add-event-for-screenshot-saved
Tested with script.
=> obs-frontend-api: Add screenshot event

UI/window-basic-settings-stream.cpp
Fix the wrong stream setting page being set.
Fix a bug.
Check settings if the right page is set.
=> UI: Fix stream setting page being wrong on Wayland

UI/window-basic-about.cpp
The `ui->donate` element wasn't being deleted, resulting in a placeholder element with the untranslated string "Donate" to be left over.
This shouldn't be there.
Compiled and ran with and without `--steam` flag.
=> UI: Fix placeholder element not being deleted

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adding Vindral rtmp endpoints to streaming services dropdown, wrapped with the following changes:
- Adding active Vindral rtmp endpoints to **services.json** file.
- Incrementing rtmp-services version in **package.json** file.
Updating the rtmp-services ingestion list to introduce Vindral as a service
Vindral Live CDN delivers next-generation live streaming at sub-second latency, synchronized playout, and 4K video quality at a global scale.
[https://www.vindral.com/](https://www.vindral.com/)
[https://docs.vindral.com/docs/vindral-cdn/](https://docs.vindral.com/docs/vindral-cdn/)
Took the updated JSON and had it validated at jsonlint.com.
Build testing not required.
=> rtmp-services: Add Vindral service

plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg.c
Fix Ubuntu 20.04 NVENC requiring old NVENC presets
Ubuntu 20.04 and 22.04 both have the same FFmpeg versions, but FFmpeg on 20.04 was built with version 9 of NVENC headers, whereas 22.04 was built with 11.
Unfortunately, that means we have to revert back to the old presets when Ubuntu 20.04 is detected. The way this detection is done is a bit hacky, but it's the only way to preserve startup performance. Otherwise we'd have to write yet another startup subprocess test program to detect whether the FFmpeg being used was built with older or newer NVENC, which is both slow to start up and annoying to write. So instead, just get the distro name/version strings and detect Ubuntu 20.04 that way.
Hasn't really been tested, could probably use a tester, even if it just means forcing the ubuntu …
=> obs-ffmpeg: Fix FFmpeg NVENC presets on Ubuntu 20.04

plugins/obs-ffmpeg/obs-ffmpeg.c
The current Ubuntu 20.04 check doesn't work since both name and version id are quoted, but quotes are not stripped, resulting in the `dstrcmp`s here failing:
https://github.com/obsproject/obs-studio/blob/dd26fe4f8a5fc603a405841bfb02069bf59ee5c8/plugins/obs-ffmpeg/obs-ffmpeg.c#L274-L275
`VERSION_CODENAME` on the other hand is not quoted, and also easier since it requires just a single string.
Fixes.
Hasn't.
=> obs-ffmpeg: Fix Ubuntu 20.04 detection

libobs/obs-nix-wayland.c, libobs/obs-nix-x11.c
Links up the xkb keysyms with the obs vk codes.
Fixes #7649
Someone asked for it
Tested with my keyboard which only has these 7 buttons as a function extension on wayland ~~Ill test X11 another day but it should be right.~~ and X11.
I couldnt find a PLAY_PAUSE keysym in xkb but my PLAY_PAUSE key maps to this AudioPlay so I think its right.
=> libobs: Add media key support for linux

libobs/obs-scene.c
Property was not being copied over.
Want blend method to work in studio mode.
Blend method works in studio mode now. Still works in non-studio mode.
=> libobs: Fix blend method in studio mode

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main-screenshot.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, docs/sphinx/reference-frontend-api.rst
Adds functions to the frontend api to get the last recording, screenshot and replay buffer saved.
Makes it easier for developers to find these files.
Tested with script.
=> obs-frontend-api: Add functions to get last saved files

libobs/obs-source.c
Fixes case where video capture is darkened when both luma wipe and scale filtering are set.
Fixes #7675.
Want reasonable colors.
Tested that case was dark before, and normal now.
=> libobs: Force SRGB conversion for tonemapped video

UI/obs-app.cpp, UI/window-basic-main-outputs.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp
Simple Output Mode NVENC Presets were not migrated, so the UI would display the `Encoder Preset` dropdown with nothing selected. The user could still start a recording, but this is confusing. Let's actually migrate Simple Output Mode NVENC Presets when needed.
Want migrations to work. Don't want bugs.
Tested locally in a new portable mode instance with a new profile and with imported 28.0.x profiles. Checked that preset values before and after matched intended migration mappings. Checked that already migrated presets did not trigger another migration or file save.
=> Fix Simple Output Mode NVENC Preset migrations

plugins/obs-ffmpeg/jim-nvenc.c
Erroring out of NVENC init early if the Max B-frames setting was higher than the encoder's capability causes an encoder failure on NVIDIA Pascal (10-series) and earlier GPUs due to an unfortunate interaction between Simple Output Mode, HEVC, and our default B-frames setting of 2. Since we already check the Max B-frames capability of the encoder, cap at that value instead of erroring out.
Fixes #7698.
Want Simple Output Mode to work. Want less bugs.
Compiled and tested locally on Windows 10 21H2 with a GTX 1060.
=> obs-ffmpeg: Cap NVENC Max B-frames according to GPU caps

.github/workflows/steam.yml, CI/steam/obs_playtest_build.vdf
Uploads pre-release builds to Steam Playtest as well as beta branch.
Want to potentially use playtests in the future to allow side-by-side installation and better/easier discoverability of betas on Steam: https://partner.steamgames.com/doc/features/playtest
Tested on my fork.
=> CI: Upload beta builds as Steam Playtest

UI/window-basic-main.cpp
Changes how we save the "always on top" setting when exiting. The current code no longer works as the shutdown code has changed at some point so that the OBS window is closed by the time we reach this code, so `IsAlwaysOnTop` returns `false`.
https://twitter.com/MiisterVal/status/1588911410129477632
Ran OBS, verified it saved  the setting.
=> Fix always on top not being saved on exit

docs/sphinx/reference-core.rst, docs/sphinx/reference-sources.rst, libobs/obs-source.c, libobs/obs.c
Adds a source signal that gets triggered when a source's settings are updated.
~~There is `update_properties`, but it acts in a very different way.
Confirmation that it's not *supposed* to do what the new signal does would be great.~~
Writing a feature / plugin (probably plugin for the time being) that requires constantly watching a source's settings.
macOS 13
Connected to the signal via `signal_handler_connect(obs_source_get_signal_handler(source), "update", source_update_signal, data)` and saw the signal being triggered each time the source was updated.
=> libobs: Add "source_update" signal

libobs/util/platform-windows.c
Fixes Windows release name to get correctly read for 20H2 ("2009") or later.
Fixes #7726
Per https://twitter.com/bytenerd/status/1395071115072966656 the old key is no longer updated as to not break compatibility with software that (incorrectly) parsed it as an integer. OBS doesn't do this and the string exists purely as a convenience to have a human-readable major version identifier in the log.
- Checked strings is now correct on Windows 20H2 and later
- Checked that the log analyser continues to correctly read the Windows version
=> libobs: Fix reading Windows release name

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
The `on_foo_bar` slot name in Qt is used by the `QMetaObject::connectSlotsByName` to automatically connect signals to slots (the call is in the generated `ui_OBSBasicWhatever.h` file). As explained in the [documentation](https://doc.qt.io/qt-6/qmetaobject.html#connectSlotsByName), using it precisely requires the name to be `on_[sender name]_[signal name]`. Anything else will not get connected, and shouldn't get connected manually, as it makes it *look* as if it's automatically connected even if it isn't.
To explain in detail, the first commit renames the slot to avoid potential confusion. When there is no automatic connection (and there isn't, as the action gets created dynamically and not by UIC), it shouldn't seem like there is.
In the second commit, there is an object that always …
=> UI: Fix improper usages of `on_foo_bar` slot name pattern

UI/obs-app.cpp, docs/sphinx/reference-libobs-util-platform.rst, libobs/obs-cocoa.m, libobs/obs-windows.c, libobs/util/platform-windows.c, libobs/util/windows/win-version.h
Adds a check that detects if OBS is running on Windows ARM64 emulation and logs the result.
https://github.com/obsproject/obs-studio/pull/5644
I messed up #5738, this is the new PR. 
Running X64 OBS Studio gives the following log:
<details>
```
23:10:09.304: CPU Name: Microsoft SQ1 @ 3.0 GHz
23:10:09.305: CPU Speed: 1670MHz
23:10:09.305: Physical Cores: 8, Logical Cores: 8
23:10:09.305: Physical Memory: 7718MB Total, 3202MB Free
23:10:09.305: Windows Version: 10.0 Build 22538 (release: 2009; revision: 1010; ARM 64-bit)
23:10:09.305: Windows ARM64: Running with X64 Emulation
23:10:09.306: Running as administrator: false
23:10:09.307: Aero is Enabled (Aero is always on for windows 8 and above)
23:10:09.307: Windows 10 Gaming Features:
23:10:09.307: 	Game Bar: On
23:10:09.307: 	Game DVR: On …
```
=> libobs: Add Windows X64 Emulation on ARM64 and move Rosetta Detection

libobs-opengl/gl-cocoa.m, libobs/data/color.effect, libobs/data/default_rect.effect, plugins/mac-capture/mac-screen-capture.m
Added support for retaining P3 colors when capturing Mac screens. Gets clipped for SDR recordings, but kept for HDR recordings.
Want to keep wide colors when possible.
Verified SDR looks the same, and AOM AV1 HDR recording retains P3 colors.
=> Retain P3 for Mac screen capture

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp
Displays more than 8 bpc if monitor is configured to be higher.
Want to support high-precision SDR.
Also verified by another user that Windows 10 21H1 does not regress.
=> libobs-d3d11: Support advanced SDR window preview

UI/window-basic-main.cpp
Sets the ownership of the `OBSContextBarProxyStyle` manually to fix a memory leak
Whereas `QApplication::setStyle` does [transfer ownership](https://doc.qt.io/qt-6/qapplication.html#setStyle), `QWidget::setStyle` [does not](https://doc.qt.io/qt-6/qwidget.html#setStyle). This leads to the style leaking unless the ownership is transferred beforehand.
Added a destructor to `OBSContextBarProxyStyle`. Saw it not getting triggered
before and get triggered now. 
=> UI: Fix QStyle memory leak

plugins/aja/aja-presets.cpp, plugins/aja/aja-props.cpp, plugins/aja/aja-source.cpp
- Adds missing signal routing preset for Kona HDMI UHD/4K YUV
- Fix calculation of card's framebuffer index in the capture thread, based upon the preset's framestore widget index, rather than the input channel index.
Capturing UHD/4K YUV on the KonaHDMI, both on input 1 and 2, was not working in OBS.
Verified that capturing UHD/4K YUV signals works on Kona HDMI, on both input 1 and 2.
NOTE: Only inputs 1 and 2 on Kona HDMI are capable of UHD/4K capture. Inputs 3 and 4 can only capture HD, and only when inputs 1 and 2 are also being used to capture HD signals.
=> aja: Fix KonaHDMI UHD/4K YUV capture

deps/media-playback/media-playback/media.c, libobs/media-io/audio-resampler-ffmpeg.c, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
Also changes obs-ffmpeg.
This allows compilation with FFmpeg master.
More precisely for:
-  swresample >= 4.5.100, 
- avutil >= 57.24.100,
- avcodec >= 59.24.100.
One commit adapts the changes done in 5b6cc73 to the obs-ffmpeg-mpegts output.
The second updates obs audio resampler by swapping a deprecated function to its new version 
which uses the new channel layout API.
The third deals with the deprecation of AVFrame and AVCodecContext channels member by switching to new API.
Enable later updates of FFmpeg library on which obs-studio relies for a variety of stuff.
test platform: win 10 pro 21H2 x64 & win 11 22h2, visual studio 2022 
- checked that audio is resampled correctly with both new & old api (both new and old FFmpeg dlls),
- checked that mono audio is upmixed correctly with both …
=> libobs: Fixes for the new FFmpeg channel API

.github/workflows/main.yml, CI/linux/03_package_obs.sh, cmake/Modules/ObsDefaults_Linux.cmake
Ensures that binaries inside Debian packages are not only stripped, but also associated debug symbols are contained in a separate debug symbol package.
Enable debugging on builds installed via Debian packages.
* Debug symbol generation tested on Ubuntu 22-arm64
* CI runs checked via PR
=> CI: Add Debian debug symbols to build and CI artifacts

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adds IRLToolkit RTMP ingests to services list
IRLToolkit has grown to a size where I feel that it would be beneficial to include it on the services list.
Via standard service testing procedure
=> rtmp-services: Add IRLToolkit

UI/forms/OBSBasic.ui
It makes the source properties button more distinguishable.
Suggestion from @Warchamp7
Looked at source toolbar to make sure it looked correct.
=> UI: Add separator in source toolbar

CI/windows/02_build_obs.ps1
The backtick double-quote pattern does not work in PowerShell 7.3.x. There are still some other possible PowerShell 7.3.x issues in the packaging steps, but let's fix this first to get regular builds working in PowerShell 7.3.x again.
Updates are coming to the Windows CI images. Don't want CI to immediately fail all builds.
Some devs are getting PowerShell 7.3. Want them to be able to build locally.
Tested locally on Windows 11 with PowerShell 7.3.
=> CI: Fix building in PowerShell 7.3.x

libobs/obs-source.c
SDR source projectors are no longer blown out on HDR displays.
Fixes #7790
Want correct colors.
Windowed and fullscreen SDR projectors for async video sources (media source, video capture) were too bright before, and normal after.
=> libobs: Fix SRGB to SCRGB async video rendering

UI/window-projector.cpp, UI/window-projector.hpp
The projectors would still hold on to a reference of a source, even if the source was deleted, so use weak sources
A source projector would still be opened, even when its source is deleted.
- Added source projector
- Deleted the source
- Made sure the projector was closed properly
=> UI: Fix projectors not closing when source is deleted

plugins/win-capture/cursor-capture.c, plugins/win-capture/cursor-capture.h
Currently all monochrome cursors are always rendered all-black, meaning they are invisible on dark backgrounds (see #6794).
This updates the blend mode from GS_BLEND_SRCALPHA to GS_BLEND_INVDSTCOLOR when drawing monochrome cursors, so they are visible on both light and dark backgrounds.
The following monochrome cursor rendering requirements are complete: 
Tested on Windows 10 x64 with all of the baked-in Windows cursors. All color cursors remain unchanged, monochrome cursors (such as the I-Beam and Crosshair) are now rendered inverted instead of black. This should have no impact on any other areas of the code.
Bug Fix
Maintainer Edit: Fixes #3129, fixes #6794
=> win-capture: Invert destination pixels when drawing monochrome cursors

UI/context-bar-controls.cpp, plugins/win-capture/duplicator-monitor-capture.c
The index is not reliable. The id persists better, so use that.
Also remove matching against the first monitor if the expected monitor
is not available. That feature seems like a good way to get doxxed by
accident.
Fixes #5329
Want display capture target to be stable.
Two monitors:
- Much toggling between DXGI/WGC capture modes.
- Much toggling between monitors.
- Unplug/replug both monitors on both capture types.
- Logging changes work as expected.
- Display toggling via context bar still works.
=> win-capture,UI: Look up display by id, not index

UI/window-basic-main.cpp
To avoid the user having lookahead enabled with no way to disable it, change the Simple Output Mode NVENC Preset from P6 to P5.
Follow up to 8806738a04a651b147aff68fbddfb688c8d179db.
Want a better default UX. See also 8806738a04a651b147aff68fbddfb688c8d179db.
Tested locally on Windows 10 to observe that default had changed.
=> UI: Change Simple Output NVENC default preset to P5

UI/window-basic-auto-config-test.cpp, UI/window-basic-auto-config.cpp, UI/window-basic-auto-config.hpp
Adds the M1/Pro/Max/Ultra/M2 Hardware encoder to AutoConfig on macOS 13 or newer.
We added this to simple mode with OBS 28, but not to AutoConfig.
This meant that when running AutoConfig, people would still only get recommended x264 even if the hardware encoder was available.
Ran AutoConfig, both for recording and streaming.
Optimizing for streaming, with "Prefer hardware encoder" checked the encoder got selected and applied correctly.
Optimizing for recording, the hardware encoder got selected and applied correctly.
When the encoder was set to unavailable, x264 got set.
=> UI: Add Apple Hardware Encoder to AutoConfig

plugins/mac-videotoolbox/encoder.c
Changes the default profile of the VT H.264 encoder to High.
HEVC stays at main.
[R1ch's stream analyzer](https://r-1.ch/analyzer/) got mad at me for using the main profile.
We really should be using High in Simple Mode, I consider current behavior to be a bug.
Tested that recordings using the simple Apple H.264 streaming encoder use the High profile now (whereas before it was Main) by throwing the file into MediaInfo.
Tested that x264 recordings using the stream encoder in simple mode use the High profile both before and after.
Checked manually (by looking at the code) that both NVENC and AMF already use High.
Tested that HEVC recordings using the simple Apple HEVC streaming encoder still use the Main profile (which is correct for HEVC). …
=> mac-videotoolbox: Default to High profile

plugins/decklink/decklink-device-instance.cpp, plugins/decklink/decklink-output.cpp
Remove conversion to UYVY.
Quality preservation, and code simplification.
Verified Output and Preview Output both still work, both without and without rescaling output via swscale.
Internal keyer and disabled keyer still work.
=> decklink: Always output BGRA

libobs/obs-encoder.c, libobs/obs-internal.h, libobs/obs-scene.c, libobs/obs-video.c, libobs/obs-view.c, libobs/obs.c, libobs/obs.h
- Add new variant of obs_view_add to customize view specific canvas/encoder output resolution
I recently got familiar with https://github.com/obsproject/obs-studio/pull/6577 (cc @chippydip ) that was exactly what my plugin needed at the time, for potentially doing multiple outputs with separate encoder instances at the time.
Later on, the requirements changed and I'd prefer to encode an output with a custom resolution. I'm also using a scene with a custom resolution set as view source.
The multiple video mixes PR already did most of the work for making this happen, but this PR is just a small addition to ensure `obs_video_info` is a part of `obs_core_video_mix` context and reduce the direct use of `obs->video.main_mix`.
- Tested on a Mac and PC (x264/nvenc variants, with and without …
=> libobs: Allow overriding video resolution per view

UI/platform-windows.cpp
Removes the Qt implementation of the taskbar overlay on Windows.
This was removed with Qt 6, which is why we now have a native integration for that. There's no reason for this native integration to not be used with Qt 5 (except that we're not using Qt 5 anymore anyways).
+0 -35
Millions of users used this "new" codepath with OBS 28 which I consider to be enough of a test.
That being said, this PR itself hasn't been tested, but I consider it to be very low risk (and even in the tiny chance that it does somehow break, it would only break Qt 5 which we're not using anymore on Windows anyways).
=> UI: Remove Qt taskbar overlay

UI/data/locale/en-US.ini, UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Grey.qss, UI/data/themes/Light.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/data/themes/Yami.qss, UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Makes it easier to access scene filters.
Make UI better
Clicked on button to open scene filters.
=> UI: Add filters button to scenes toolbar

cmake/Modules/FindLibva.cmake, plugins/obs-ffmpeg/CMakeLists.txt, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c, plugins/obs-ffmpeg/obs-ffmpeg.c, plugins/obs-ffmpeg/vaapi-utils.c, plugins/obs-ffmpeg/vaapi-utils.h
**Testers: would please add to your feedback the output of the `vainfo --all` command and if issues a log of OBS with `--verbose` for debug log.**
Fixes #3184
With this change `obs-ffmpeg` is directly linked to Libva.
Only DRI device with H264 encode endpoint will be shown.
If none of them have it, the encoder is not registered.
Also only compatible rate control are shown.
My Nvidia driver only have decoding implemented through VA-API driver. 
Before on 27.2.4:
The `VAAPI Codec` was removed on master with #6590.
After on master with this PR:
If the environment variable `LIBVA_DRIVER_NAME` is set, a warning will be logged. This variable is usually set by advanced user.
if set it could load the wrong driver on the DRI device.
If set to `nvidia` on my machine:
```
warning: LIBVA_DRIVER_NAME …
```
=> obs-ffmpeg: Use Libva to enable FFmpeg VA-API

docs/sphinx/reference-core.rst, libobs/obs-internal.h, libobs/obs.c, libobs/obs.h
Marks the `obs_set_master_volume` and `obs_get_master_volume` as deprecated
as they aren't used by OBS and don't actually do anything.
Removes the associated event (that never gets called, because the function doesn't get called).
Removes the associated variable. The struct is in `obs-internal.h` so this shouldn't break the ABI.
Reported in #3786. We shouldn't have dead functions.
Closes #3786.
macOS 13 RC 1
Code still compiles.
Check that nothing in OBS uses these functions. Checked with git grep that the `master_volume` isn't used anywhere (tbf, it would have been odd if it was used).
Checked that the functions aren't used in #4741 (that PR is per channel)
=> libobs: Deprecate obs_get/set_master_volume

plugins/obs-ffmpeg/obs-ffmpeg-av1.c
This makes the CQP rate control QP value be respected, which it is currently not. `global_quality` does not get respected by the encoders, and this is remedied by specifying via `priv_data`.
Fixes https://github.com/obsproject/obs-studio/issues/7784
Want CQP rate control to work properly.
Tested on Win 11 22H2.
Confirmed QP value gets respected by encoding and checking the files produced (one file qp 10 one qp 50).
Made sure other rate control methods still work for both encoders.
Also tested ffmpeg deps 59.37.100 from https://github.com/obsproject/obs-deps/pull/141
CQP mode still works for both encoders with this PR.
=> Fix svt-av1 and libaom-av1 CQP ratecontrol

plugins/obs-vst/VSTPlugin.cpp, plugins/obs-vst/headers/VSTPlugin.h, plugins/obs-vst/obs-vst.cpp
Minor code cleanups for obs-vst. Use libobs memory functions instead of malloc / free  and some misc. string handling improvements.
Improve plugin behavior and clean up some static analysis warnings.
It compiled. I don't have VSTs so no functional testing.
=> Misc obs-vst cleanups

.github/workflows/flatpak.yml, .github/workflows/main.yml, CI/flatpak/com.obsproject.Studio.json, plugins/obs-vst/obs-vst.cpp
Closes #7132
The 6.4 runtime rely on Freedesktop 22.08 which provide a more recent version of Mesa and PipeWire.
The switch to 22.08 also requires to migrate paths of VST 2 plugins.
We need to bump the runtime version to provide a more recent version of Mesa and other stuff (Qt 6.4, remove custom PipeWire module).
- I installed `org.freedesktop.LinuxAudio.Plugins.DISTRHO-Ports//21.08` and `org.freedesktop.LinuxAudio.Plugins.DISTRHO-Ports//22.08`.
- Add a VST filter (from 21.08) with OBS Flatpak from Flathub (so 28.1.2 with 6.3)
- Run OBS Flatpak with this change, the filter stilsl work because the VST path has successfully been updated (and now use the 22.08 one)
Note: for unknown reason I had to build the flatpak with "beta" or "stable" has branch to test it, "master" seems to not allow …
=> CI,obs-vst: Update Flatpak KDE Runtime to version 6.4

cmake/Modules/CompilerConfig.cmake
If there is no BOM, MSVC defaults to the user's code page which can result in errors if UTF-8 characters are present in the source files.
https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170
Trying to build OBS with a non-standard codepage would fail.
Hasn't.
=> cmake: Specify utf-8 for MSVC builds

libobs/CMakeLists.txt, plugins/rtmp-services/CMakeLists.txt
Suppress LNK4098 in libobs and rtmp-services to allow building against pre-built Jansson from obs-deps in Debug configuration.
Want to be able to build in Debug for now.
Built in Debug locally.
=> Suppress LNK4098

plugins/obs-ffmpeg/texture-amf.cpp
Check rate control, if cqp (0), dont use vbaq.
Fixes https://github.com/obsproject/obs-studio/issues/7827
Want CQP to work properly for HEVC AMF.
On win 11 22H2. Checked all rate controls using breakpoints, making sure only CQP disables VBAQ.
Recorded videos and made sure output was ok (fixed).
=> obs-ffmpeg: Disable VBAQ for HEVC CQP rate control

plugins/obs-qsv11/QSV_Encoder.cpp, plugins/obs-qsv11/QSV_Encoder.h, plugins/obs-qsv11/QSV_Encoder_Internal.cpp, plugins/obs-qsv11/QSV_Encoder_Internal.h, plugins/obs-qsv11/obs-qsv-test/obs-qsv-test.cpp, plugins/obs-qsv11/obs-qsv11-plugin-main.c, plugins/obs-qsv11/obs-qsv11.c
- Add Intel HEVC hardware encoder (QSV H.265).
~~- Add *Simple Output Mode* for Intel HEVC hardware encoder.~~
- We should have a way to use Intel HEVC hardware encoder in streaming and recording.
~~- We should have easy way (*Simple Output Mode*) to use Intel HEVC hardware encoder in streaming and recording.~~
MSVC debugger, VLC color/metadata checks
RenderDoc color check
MediaInfo metadata checks:
Compile/UI check:
Chrome checks:
=> obs-qsv11: Add HEVC support

UI/window-basic-main.cpp
Fixes a potential race where the update check runs before the automatic beta opt-in completes.
Some users reported seeing an update to 28.1.2 when launching the beta.
Hasn't. Couldn't reproduce the issue (potentially due to network latency of EU vs US?)
=> UI: Delay timed update check until branch migration

UI/forms/OBSBasicSettings.ui, UI/window-basic-settings.cpp
Removes the "Update Channel" label on macOS.
Update channels aren't implemented on macOS yet (until #7723, which doesn't look like it'll get merged for this update), and this looks weird:
Confirmed that the label is gone, see screenshot above.
=> UI: Hide "Update Channel" label on macOS

plugins/obs-ffmpeg/texture-amf.cpp
Checks if rate control is CQP, if not, enable VBAQ.
File size is substantially (potentially 50% increase) larger with VBAQ for close to zero gain at same QP. Some metrics even score the substantially smaller file higher.
AMD says VBAQ was not designed to work with CQP. See https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/362
Both files generated using CQP 10, with the only variable changing being VBAQ.
VMAF:
| - | VBAQ Off | VBAQ On|
| ------------- | ------------- | ------------- |
| Bitrate: | 16 322 | 27 029  |
| VMAF | 98.612322  | 98.447583 |
| SSIM | 0.999355  | 0.999594 |
| PSNR | 60.837514| 61.978996 |
On Win 11 22H2, using breakpoints to ensure it only affecting CQP.
Recorded files, using all rate controls and verified output looks as expected.
- Tweak (non-breaking change …
=> obs-ffmpeg: Disable VBAQ for H264 CQP rate control

plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/ffmpeg-decode.h, plugins/win-dshow/win-dshow.cpp
Verified MJPEG devices are no longer locked to Rec. 601.
Want to be able to have more accurate colors.
Verified matrix override works now on Logitech BRIO in MJPEG mode.
=> win-dshow: Ignore FFmpeg colorspace if overridden

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added an rtmp service for [Bitmovin](https://bitmovin.com/).
Add [Bitmovin](https://bitmovin.com/) live streaming to the common rtmp services.
Bitmovin is a leading provider of video software and cloud infrastructure for online media companies and enterprises globally.
I already created a [PR](https://github.com/obsproject/obs-studio/pull/6502) once, where I tried to implement the generic workflow of Bitmovin. Back then, Bitmovin did not offer a single ingest point with stream-key, so it was a bit more complicated to authenticate, create a stream, fetch the metadata and input to it. 
Bitmovin heard OBS' feedback, and introduced a simplified workflow, named Bitmovin Streams - featuring the common practice of a single ingest point with stream key. 
- JSON validation
- manual test
- Build …
=> rtmp-services: Add Bitmovin

plugins/obs-ffmpeg/obs-ffmpeg-srt.h
Fixes #7848
Currently OBS_OUTPUT_INVALID_STREAM is emitted when a wrong password is used. This commit expands the signal emission to case of timeouts.
Bugfix is good.
Tested that a wrong srt URL leads to emission of OBS_OUTPUT_INVALID_STREAM and that the stream is stopped with the 
corresponding error message.
=> obs-ffmpeg: Allow srt stream to disconnect after timeout

UI/win-update/updater/http.cpp, UI/win-update/updater/updater.cpp
Bumps updater version to 2.2.
It's been 2.1 since it's introduction, I think it's time to update it :P
Hasn't, but what could a simple 3 byte change break?
=> updater: Bump to version 2.2

libobs/obs.c
- libobs: Override fps ovi for aux views
Previous iteration at https://github.com/obsproject/obs-studio/pull/7797 had discussion that since the one graphics thread drives all outputs, aux views should inherit the FPS settings from the main view
- Tested on a custom plugin that aux view do get settings from the main mix when available
- Tested what happens when video output settings are changed in the UI and obs_reset_video() is triggered
=> libobs: Override fps ovi for aux views

plugins/image-source/obs-slideshow.c
When missing files are cleared, they are replaced by empty strings. This can be dangerous if not accounted for and using string manipulation on the empty string.
Fixes the crash outlined in #6129 by removing said string from the list instead of adding it to the properties.
After `git grep`ing for `obs_properties_add_editable_list`, I noticed that the VLC Source should also have this issue. This would've been the case, except I saw that it was fixed by ba77ca6 (probably without checking for the same issue in other circumstances). My fix was slightly different, but I decided to make it the same as ba77ca6 for consistency reasons (and also because that commit is probably a bit nicer).
Fixes https://github.com/obsproject/obs-studio/issues/6129
Crash / empty items no longer appear.
- Bug fix …
=> image-source: Remove cleared missing files from slideshow

plugins/obs-filters/nvidia-greenscreen-filter.c
Use the `source_update` signal instead of `update_properties` to find out when the parent's settings have changed.
Noticed when writing #7845 and looking for potential wrong uses of `update_properties`.
Currently it likely only works on `Video Capture Device` and `Decklink Input` sources, because those sources happen to call `obs_source_update_properties` which triggers the `update_properties` signal. This means that the original issue of #6870 should still appear on other sources, which this PR is looking to change.
Tested by pkv 
=> obs-filters: Use correct signal to reset greenscreen filter

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-formats.h, plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c, plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c
The chroma location doesn't just depend on pixel format, but we're just trying to pick something reasonable for now.
This was part of #7818, but I split these changes out in case we don't want to take the ProRes changes yet.
Want accurate metadata, so players are more likely to decode correctly.
Verified chroma location is still good in debugger for NV12 Rec. 709 and Rec. 2100 PQ. Tested P216 and P416 in #7818.
=> obs-ffmpeg: Improve chroma location decision

UI/media-controls.cpp
When a slideshow is created with no slides, the slide counter shows value of "1 / 0". Now it shows "- / -".
Before:
After:
Fixes bug I noticed.
Created slideshow with no slides and made sure the slide counter looked correct.
=> UI: Fix slide counter with no slides

UI/platform-windows.cpp, UI/platform.hpp
d27cda1 made `GetMonitorName` unused on newer Qt versions, so it only needs to be defined for older ones.
Potential code cleanup in the (far) future.
Checked via `git grep` that the only other instance of `GetMonitorName` is in `win-capture`, where the function is defined again (since it can't access UI code anyways).
=> UI: Guard GetMonitorName behind Qt < 6.4

deps/libcaption/src/utf8.c
The variable data may be null if file open failed.
Static code analysis found it.
1. Set invalid path.
2. Check that the funtion runs well
=> libcaption: Fix invalid data at utf8_load_text_file

cmake/Modules/FindGio.cmake
Find actual `libgio-2.0.so` instead of `libgobject-2.0.so`.
Without this change CMake detects `libgobject-2.0.so` instead of the actual `libgio-2.0.so`
```
-- Checking for modules 'gio-2.0;gio-unix-2.0'
--   Found gio-2.0, version 2.74.0
--   Found gio-unix-2.0, version 2.74.0
-- Found Gio: /usr/x86_64-pc-linux-gnu/lib/libgobject-2.0.so
```
and later on fails the build ([obs-studio-28.0.3.log](https://github.com/obsproject/obs-studio/files/9715172/obs-studio-28.0.3.log)) with:
```
[ 48%] Linking C executable obs-x264-test
cd /var/tmp/paludis/build/media-video-obs-studio-28.0.3/work/build/plugins/obs-x264 && /usr/x86_64-pc-linux-gnu/bin/cmake -E cmake_link_script CMakeFiles/obs-x264-test.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-cc -march=native -O2 -pipe -Wl,-O1 …
```
=> cmake: Fix FindGio.cmake to find libgio

plugins/obs-filters/expander-filter.c
This fixes a bug where the upward compressor would hard limit above the threshold.
Also this changes detection to RMS instead of peak for the upward compressor.
This sounds better than peak (tested on regular mike and a test tone).
Fixes a bug. Bugs are bad.
Tested on a sine test tone and on a regular mike.
=> obs-filter: Fix upward compressor

plugins/obs-ffmpeg/texture-amf.cpp
Added mappings for the new AMD AVC/HEVC rate control methods in AMF v1.4.29 to set the correct new values.
My last PR to enable the new RC methods for AVC/HEVC enabled the options in the UI. The OBS logs for the AMF texture encode show the encoder settings based on the UI settings and before actual encoder initialization which may or may not change more settings based on requested user config. With this change, I have confirmed the RC methods are correctly mapped and have appropriate values set at the AMF level inside the AMD driver.
Tested on Windows 10 with the new AMF texture based encoder integration. Confirmed the RC methods are correctly mapped and have appropriate values set at the AMF level inside the AMD driver.
- …
=> obs-ffmpeg: Add new rate control method mappings for AVC/HEVC

UI/forms/OBSBasicSettings.ui
Currently, Qt's User Interface Compiler (UIC) emits a warning about the tabstop assignment for horizontalLayout_sdrPaperWhite, which is a QLayout rather than a QWidget. Remove the tabstop assignment to fix the warning.
Want less warnings while building. Get rid of this warning:
```
Automatic MOC and UIC for target obs
AutoUic: C:\dev\obsproject\obs-studio\UI\forms\OBSBasicSettings.ui: Warning: Tab-stop assignment: 'horizontalLayout_sdrPaperWhite' is not a valid widget.
```
cc @norihiro since this was added in #7486.
On Windows 11, I built OBS before and after this change. Verified that the warning is gone and that OBS builds and runs.
=> UI: Fix Qt AutoUic warning

libobs/obs-properties.c
The change includes allocation of a new string to store the string passed to the Python function
Fixes #5712 
Tested using Python script from the issue description.
MacBook Air M1, MacOS 12.3
=> libobs: Duplicate URL string for OBS_BUTTON_URL

plugins/mac-videotoolbox/encoder.c
Mac encoders should add HDR metadata for HDR videos, so add it.
Unfortunately, it doesn't actually seem to get added to the video streams, but it won't be for a lack of trying on our side.
Want HDR metadata in Mac-encoded videos (someday).
Mac videos don't seem to have metadata added, but they still play back as HDR in VLC on Windows. Tried HEVC and ProRes.
=> mac-videotoolbox: Add HDR metadata

plugins/obs-qsv11/obs-qsv11.c
HDR mastering primaries are supposed to be GBR order, not RGB. FFmpeg does the same with their QSV implementation.
Want metadata to be correct.
Verified MediaInfo still parses HEVC as Display P3.
=> obs-qsv11: Put mastering primaries in GBR order

UI/obs-app.cpp
Some wayland compositors exclusively use xwayland such as gamescope. This allows us to fallback to the platform determined by Qt, which will detect these exotic compositors and handle them correctly when not overidden by this envvar.
Qt preserves this undesired behavior until 6.3. With ubuntu 22 on 6.2 this workaround needs to be preserved.
fixes #6386
OBS starts on weird platforms without manual override.
OBS runs when gamescope doesnt crash.
=> UI: Restrict GNOME wayland override

libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs/obs-internal.h, libobs/obs.c
This PR reverts commits related to Intel iGPU+dGPU adapter reordering that occurs in systems with both an Intel iGPU and Intel dGPU. See PR #3686 where this was originally introduced.
Reverts the following commits:
* https://github.com/obsproject/obs-studio/commit/02d20e9f36c21069f59269ea94bf393231217e34
* https://github.com/obsproject/obs-studio/commit/e62759a3fa3d20366f80ddaa70fa58ca4f61a358
* https://github.com/obsproject/obs-studio/commit/c83eaaa51c260c3844baaf1cb76de63e0f096cea
Fixes #7917.
PR #3686 originally introduced this change "to improve performance" (per commit c83eaaa51c260c3844baaf1cb76de63e0f096cea). With the release of the Intel Arc GPUs, users were confused as to why they could not run OBS on their Arc GPU if their system also had an Intel iGPU. After further discussion …
=> Revert adapter reordering on Intel iGPU+dGPU systems

plugins/obs-filters/noise-suppress-filter.c, plugins/obs-filters/nvidia-greenscreen-filter.c
This puts the version logging behind a condition of having found a lib.
A user reported in beta channel that his log reported an nvidia fx version 0.0.0.0.
This should not be logged because this means the nvidia sdk is not installed.
If no version of the sdk is returned, there's no log anymore.
=> obs-filters: Log NVIDIA Effects version only if lib is found

UI/window-basic-settings-stream.cpp
Use stream encoder when resetting encoder rather than the recording one.
While resetting, OBS will try to restore the actual stream encoder stored in the `lastAdvEnc` variable but it contains the record one which will restored the wrong encoder.
It actually use recording encoder which is wrong.
It could cause issue if the record and steam encoder differ and a reset happen.
"reset": Action that usually happen while the user change services and the actual encoder is no longer available because of compatibility (e.g. HEVC).
Everything work as expected.
=> UI: Use stream encoder when resetting encoders

UI/volume-control.cpp
Fixes #5447 where sliders would work in reverse.
Before:
https://user-images.githubusercontent.com/941350/207585709-357d860a-dffc-49a0-85a6-74aee99c0eed.mp4
Bugs are bad. Some are relatively easy to fix.
On Windows with Qt set to launch in RTL mode.
=> UI: Lock volume meter sliders to LTR to fix RTL slider direction

plugins/win-capture/duplicator-monitor-capture.c
If the target display wasn't found, the timer was not reset, causing the code to execute on every single tick, stalling the graphics thread and using excessive CPU.
With 29.0 resetting everyone's monitor capture, this would cause FPS drops / excessive CPU usage until users fixed their sources which isn't a great experience.
Ran in debugger.
=> win-capture: Always reset timeout when searching for target display

.github/workflows/services-json.yml
This commit blocks schema validation every day in repositories other than `obsproject`. Also enables `service_check` if the owner triggers it manually.
A truth table shows when the jobs will be run.
| `repository_owner` | `event_name`     | `schema` | `service_check` |
| --- | --- | --- | --- |
| `obsproject` | `push`, `pull_request` | Yes       | No        |
| `obsproject` | `schedule`             | Yes       | Yes       |
| `obsproject` | `workflow_dispatch`    | Yes       | Yes       |
| *other*      | `push`, `pull_request` | Yes       | No        |
| *other*      | `schedule`             | Yes &rarr; No | No        |
| *other*      | `workflow_dispatch`    | Yes       | No &rarr; Yes |
The schema validation (the job `schema`) is running every day on my repository, which is not …
=> CI: Revise repository conditions to validate JSON schema of services
