plugins/obs-ffmpeg/CMakeLists.txt

Just make the error if srt or librist are not found less cryptic.
Avoid more issue like #6947 because of the cryptic error.
Didn't test it but it should work.

obs-ffmpeg: Add better error if srt or librist are not found

---

CI/flatpak/com.obsproject.Studio.json

The ffmpeg.org domain has had periods of instability recently. If GitHub is down, our entire CI is down, so let's use the FFmpeg GitHub mirror.
Improve stability of CI.
It hasn't been tested.

flatpak: Use FFmpeg GitHub mirror

---

libobs-opengl/gl-x11-egl.c

Without this we get somewhat misleading errors from later in the
swapchain creation when this fails. This is currently happening for
users attempting to use multi-gpu with prime offloading on nvidia.
Makes the error more clear, in this case the user identified it was a bad config and not something later in X11 which the old error suggested. This is a new regression as of the beta release, so we should report the correct error before things get released.
It works on my machine and changing the create call to fail it reports the error correctly.

libobs-opengl: Check window creation for errors

---

libobs-d3d11/d3d11-subsystem.cpp

Legacy DISCARD does not support HDR, so prevent HDR preview.
Don't want blown-out image.
Modified code to force legacy path. Looks bad without fix, and good with fix. Dragged preview across SDR/HDR monitors.

libobs-d3d11: Force SDR for legacy swap chain

---

UI/properties-view.cpp
deps/w32-pthreads/ptw32_OLL_lock.c
libobs/graphics/graphics-ffmpeg.c
libobs/obs-audio-controls.c
plugins/decklink/decklink-device.cpp
plugins/decklink/decklink-device.hpp

Removes unnecessary UTF characters and replaces them with closest ASCII character(s).
- `°` in comments are replaced with `degree`.
- `’`, `“`, and `”` are replaced with `'`, `"`, and `"`, respectively.
- `–` is replaced with `-`.
Also removes BOMs in source codes.
These files are not modified to avoid changing existing behavior or another reason.
- UI/properties-view.cpp
- NBSP is not modified.
- libobs/util/profiler.c
- `µ` and `±`
- plugins/linux-v4l2/v4l2-decoder.c
- plugins/linux-v4l2/v4l2-decoder.h
- It's a name of the author.
- UI/forms/OBSBasicTransform.ui
- Only `°`, which should not be modified.
- cmake/bundle/windows/ALL_BUILD.vcxproj.user.in
- Has BOM but I don't know it is ok to remove the BOM.
Want to have ASCII source code as possible.
Eyeball checked modifications other …

Remove unnecessary unicode characters and BOMs

---

UI/data/themes/Acri.qss
UI/data/themes/Dark.qss
UI/data/themes/Rachni.qss
UI/data/themes/Yami.qss

Disable icons on QDialog buttons, QStyle like Fusion provide icons to those.
Before:
After:
They are ugly and not needed and only Fusion do that. Windows and macOS seems to not have icon for that.
Launch a dialog where those icon should show.

UI: Disable QDialog button icons on all non-system themes

---

plugins/win-capture/dc-capture.c

It is releasing incorrect HDC object
fix memory leak

win-capture: Fix memory leak in dc-capture.c

---

README.rst

Updates the url of the translation guide to the wiki, and updates the Crowdin badge to use the officially provided url.
The 'How To Contribute Translations for OBS' guide is now located in a place dedicated to guides and information about contributing.
In a fork.

README.rst: Update urls of translation guide and Crowdin badge

---

plugins/linux-v4l2/v4l2-udev.c

Currently we use signals based on os_event's but the udev code blocks in
a 1s select that cannot be signalled without an FD. This adds an extra
unbound socket which will never recieve events but which can be closed
to signal the select.
Whenever udev is enabled it seems like obs hangs on shutdown which isnt a good feeling.
Starting and stopping obs with a udev enabled build and a v4l2 capture in the source list.

linux-v4l2: Add socket to signal select on shutdown

---

UI/data/themes/System.qss

accessibility and general and filter and interact icons is missing.
Before
https://user-images.githubusercontent.com/24505855/184539924-8442e35f-829b-4964-9878-d7dec29cf3ae.mp4
After
https://user-images.githubusercontent.com/24505855/184539933-5078a42a-d3d9-4dff-8063-e6c4baf13596.mp4

UI: Add missing Icon in System theme

---

UI/data/themes/Acri.qss
UI/data/themes/Grey.qss
UI/data/themes/Light.qss
UI/data/themes/Rachni.qss

Apply #7022, #6982 and #7018 on #7058 variants.
Same as #7022, #6982 and #7018.

UI/themes: Add missing fixes on Yami variants

---

UI/obs-app.cpp
UI/obs-app.hpp

This fixes leaks when loading and switching themes.
Leaks are bad.
This leak was detected with Visual Leak Detector.
Run obs with VLD; check that the leak is gone after changing a theme.

UI: Fix theme leak

---

plugins/obs-qsv11/obs-qsv11.c

Fixes initialize/destroy pattern; also slightly more performant.
Noticed critical section has weird lifetime.
Recorded two videos. OBS didn't crash, and videos look fine in VLC.

obs-qsv11: Replace CRITICAL_SECTION with SRWLOCK

---

plugins/aja/README.md

Correct two typos I found while looking at building aja support on FreeBSD.
Fix typos.
N/A - no code change.

aja: Correct typos in README.md

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

The Switchboard Live server URLs have been updated in the application, so the URLs need to updated in OBS to match.
There were recent changes to the various ingestion servers that Switch
This was tested using the latest build of OBS on macOS 12.3.1. 
Testing consisted of going live with every server to ensure connectivity was stable. 

rtmp-services: Update Switchboard Live servers

---

UI/window-basic-main.cpp

I introduced a crash with #7123. So I fixed it, normally.
Fix my mess.
OBS no longer crash with vCam disabled

UI: Check for virtual camera enablement before loading config

---

plugins/obs-ffmpeg/obs-ffmpeg-output.c

A PR below tried to fix a memory leak but I added some more changes.
- https://github.com/obsproject/obs-studio/pull/7122
I've added these changes.
- Fixed another memory leak reported by https://github.com/obsproject/obs-studio/pull/7122#discussion_r949298583
- Initialize all local variables to avoid potential warnings related to the use of `goto` statement. And removes boolean flag `new_packet` since `packet!=NULL` indicates the same.
The memory leak was introduced by my change to avoid using deprecated function.
- https://github.com/obsproject/obs-studio/pull/5764
OS: Fedora 35 (I believe this affects all platform.)
1. Set Advanced output mode.
2. Set FFmpeg output mode.
3. Start recording, wait roughly 1 minutes and see how much memory is increasing, stop recording.
Also tested with …

obs-ffmpeg: Fix ffmpeg_output memory leak

---

cmake/Modules/VersionConfig.cmake

Set `RELEASE_CANDIDATE` and `BETA` versions via git tag so What's New properly works with pre-release versions built on CI (i.e. Flatpak and macOS).
We want this to work I guess.
Ran cmake with three different configurations:
- Commit without tag => works as previously, setting the `git-describe` output as version info
- Commit with `28.0.0-beta4` tag => Properly configured as beta
- Commit with `28.0.0-rc2` tag => Properly configured as RC

cmake: Set RELEASE_CANDIDATE/BETA based on git describe

---

libobs/obs-display.c

Laptops that render OBS displays on NVIDIA, and display through Intel
have been seen flickering, and we think the driver is not properly
handling swap chain buffers that have been cleared but not drawn to. To
work around this, we use a draw to simulate a render target clear. This
is not as efficient, so hopefully NVIDIA will fix this soon.
Don't want previews to flicker.
Preview no longer flickers.

libobs: Emulate clear with draw for displays

---

libobs/obs-windows.c

It seems that the older key still exists on Win 11 and 10 but is always
set to 0, so use the newer to start with and fall back to the old one if
necessary.
Also changes "10" to "10/11" just for correctness.
Didn't work.
Ran OBS, worked.

libobs: Fix Windows 10/11 Gamemode detection

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Update "Streamvi".
Add server for users in Moscow
Locally tested and is working properly

rtmp-services: Update Streamvi

---

plugins/obs-filters/hdr-tonemap-filter.c

JXR images work now.
Want images to work with filter.
Verified filter still works for GS_CS_709_EXTENDED/GS_CS_709_SCRGB, and doesn't work for GS_CS_SRGB.

obs-filters: Fix HDR tonemap filter for scRGB

---

plugins/obs-ffmpeg/jim-nvenc.c

Fix async API usage problems reported by NVIDIA.
Apparently future drivers aren't going to be as lenient.
Recorded a video with NVENC. Used temporarily logging to verify event waits were being called at expected times.

obs-ffmpeg: Fix NVENC async usage pattern

---

plugins/obs-ffmpeg/jim-nvenc.c

Fixes hang on stop presumably because header read failed from being too
early?
Our buffering scheme makes async mode moot anyway.
Don't want to recording to hang on stop.
H.264 recording no longer hangs on stop.

obs-ffmpeg: Don't use NVENC async mode

---

UI/data/themes/Acri.qss
UI/data/themes/Grey.qss
UI/data/themes/Light.qss
UI/data/themes/Rachni.qss
UI/data/themes/Yami.qss

https://user-images.githubusercontent.com/26628474/187518324-de52e958-fea8-4a4c-a1e0-d4340470b5b8.mp4
Fix UI bug.
Starting Virtual Camera and hover the mouse over the button.

UI: Fix "Stop Virtual Camera" button color

---

UI/data/themes/System.qss

Previous icons is missing.
Before
https://user-images.githubusercontent.com/24505855/187583611-54c37bf5-06fb-4f1e-a353-47d0598881ef.mp4
After
https://user-images.githubusercontent.com/24505855/187583629-35813840-2c7b-4d93-8c98-1e5dfe38a37a.mp4

UI: Fix Previous icon in System

---

plugins/image-source/obs-slideshow.c

Only supported on Windows.
Mirrors image source support.
Slideshow of SDR & HDR images transitioned fine with SDR and HDR canvas. Verified SDR slideshow did not regress on Mac.

image-source: Add JXR HDR support to slide show

---

plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c

Fixes https://github.com/obsproject/obs-studio/issues/7305.
Some copied data was not freed and also not all paths freed AVPackets.
Leaks are bad.
Tested the leak was gone when streaming at very high bitrate with srt or rist.

obs-ffmpeg: Fix memory leak with mpegts

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Adding Livepush rtmp endpoints to streaming services dropdown, wrapped with the following changes:
- Adding active Livepush rtmp endpoints to **services.json** file.
- Incrementing rtmp-services version in **package.json** file.
Updating the rtmp-services ingestion list to introduce Livepush as a streaming service with its available rtmp endpoints.
Livepush is a relatively new live/recorded media broadcasting platform, and exposes a list of rtmp server locations to choose from.
Took the updated JSON and had it validated at jsonlint.com.
Build testing not required.

rtmp-services: Add Livepush service

---

UI/data/themes/Light.qss

Preview/Program Labels and T-Bar in Studio mode are not visible in the Light theme.
Before
After
I want displayed correctly.

UI: Fix in Light theme

---

docs/sphinx/reference-core.rst
docs/sphinx/reference-libobs-callback.rst
docs/sphinx/reference-properties.rst
docs/sphinx/reference-scenes.rst

Adds hyperlinks to the scripting functions that replace the C functions.
Example screenshots:
When looking through the documentation, I don't memorize all the overriding scripting functions, so I want to know immediately that the scripting equivalent has a different function signature.
Built and viewed locally, and tested the hyperlinks.

docs: Add links to python functions

---

UI/data/themes/Acri.qss
UI/data/themes/Dark.qss
UI/data/themes/Grey.qss
UI/data/themes/Light.qss
UI/data/themes/Rachni.qss
UI/data/themes/Yami.qss

Remove unnecessary styles for `PauseCheckBox`.
I checked any other missing files when the PR #7432 was merged.
The style includes a file path `media-play.svg`, which is not found.
Tested on Fedora 35.
Checked VLC Source and Media Source, confirmed the play and pause buttons on the toolbar is shown.

UI: Remove unnecessary styles

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Update ingest list for Restream.io:
- add new Restream ingests: New York, Hong Kong
- remove ingests: Luxembourg, Paris, Milan, Falkenstein, Prague, Moscow, Tel Aviv, Miami
- update rtmp-services version
Restream ingests could be checked at https://api.restream.io/v2/server/all
Updating the list of working ingests to keep it actual.
In local OBS client to ensure it connects to the new servers and works correctly.

rtmp-services: Update ingest list for Restream.io

---

UI/obs-app.cpp
UI/record-button.cpp
UI/source-tree.cpp
UI/window-basic-main-transitions.cpp
UI/window-basic-main.cpp
UI/window-basic-preview.cpp
UI/window-basic-settings.cpp
libobs/obs-video.c
plugins/obs-filters/crop-filter.c
plugins/obs-filters/hdr-tonemap-filter.c
plugins/obs-filters/noise-suppress-filter.c

Various fixes for issues detected by clang-analyzer.
Code cleanup and bug fixing.
Most of this was removal of dead code. The `getenv` change was debug tested to make sure it behaved as before.

Clang static analysis cleanups

---

CI/check-services.py

Bring check-services script in line with #7603
`::set-output` has been deprecated by github in favor of a file.
Tested on my fork: https://github.com/derrod/obs-studio/actions/runs/3259180660

CI: Fix services check using deprecated GHA output

---

UI/window-basic-settings.cpp

Cancel after apply in settings will set the old theme.
Fix a bug where if you:
- Go to the settings.
- Change the theme.
- Click the apply button.
- Click the cancel button.
- The old theme is set theme rather than letting the newly set.
Fix a bug.
Redo the steps in the description, the theme stay the newly set.

UI: Fix theme if apply and cancel in settings

---

UI/data/themes/Acri.qss
UI/data/themes/Grey.qss
UI/data/themes/Light.qss
UI/data/themes/Rachni.qss
UI/data/themes/Yami.qss
UI/window-basic-stats.cpp
UI/window-basic-stats.hpp

Fix the font size of status in the stats widget.
Fix background color of the stats dialog and dock on all Yami based themes.
**Before**:
**After**:
Fix the theme.
Open stats dialog and dock and check status font size and background color.

UI: Fix stats widget apparence and font size

---

.github/workflows/flatpak.yml
.github/workflows/main.yml
.github/workflows/steam.yml
CI/check-services.py
CI/steam/scripts_macos/launch.sh
UI/data/themes/Acri.qss
UI/data/themes/Grey.qss
UI/data/themes/Light.qss
UI/data/themes/Rachni.qss
UI/data/themes/Yami.qss
UI/window-basic-main-outputs.cpp
UI/window-basic-settings.cpp
UI/window-basic-stats.cpp
UI/window-basic-stats.hpp
plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm

Cherry-pick commits for 28.1.0.
See PRs:
* #7599 
* #7603
* #7605
* #7581
* #7620
* #7606 
* #7613
Pull in approved bug fixes to the release/28.1 branch.
I have not tested this branch personally. This is simply cherry-picking PRs/commits that were already merged to master.

Cherry-pick commits for 28.1.0

---

UI/obs-app.cpp
plugins/obs-ffmpeg/jim-nvenc.c

Bring NVENC preset migrations more in line with NVIDIA guidelines.
See:
* https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-preset-migration-guide/
Want the preset migrations to follow NVIDIA guidelines as close as we can.
Tested most migrations locally. More testing welcome.

Adjust NVENC preset migrations

---

UI/obs-app.cpp
libobs/obs-source.c
plugins/obs-ffmpeg/jim-nvenc.c

Cherry-pick commits for 28.1.0.
See PRs:
* https://github.com/obsproject/obs-studio/pull/7692
* https://github.com/obsproject/obs-studio/pull/7693
Pull in approved bug fixes to the release/28.1 branch.
Testing done on the previously merged individual PRs. This is simply cherry-picking PRs/commits that were already merged to master.

Final 28.1 cherry picks

---

.github/workflows/services-json.yml

ubuntu-latest has been switched to 22.04. This CI requires 20.04 because of the dependence on Python 3.9.
Fix CI.

CI: Fix service validator

---

docs/sphinx/reference-core.rst
docs/sphinx/reference-encoders.rst
docs/sphinx/reference-frontend-api.rst
docs/sphinx/reference-libobs-callback.rst
docs/sphinx/reference-outputs.rst
docs/sphinx/reference-properties.rst
docs/sphinx/reference-scenes.rst
docs/sphinx/reference-services.rst
docs/sphinx/reference-settings.rst
docs/sphinx/reference-sources.rst

Adds links to release functions for "new/incremented reference". Extra info on signal handler.
Parameter description on `obs_property_list_add_*` functions, since their parameter `name` can be confusing and it is unclear which value is stored in obs_data_t.
Adds clarifications on calldata_ptr.
See commit message above.
Unclear to non-C programmers or beginners which ones need freeing.
I also got confused by obs_property_list_add_*.
Built locally and checked the sphinx features I haven't used before, like `:c:type:`.

docs: Add clarifications

---

plugins/mac-avcapture/av-capture.mm

- Add support for preferredCamera, as defined in by the [documentation](https://developer.apple.com/documentation/avfoundation/capture_setup/supporting_continuity_camera_in_your_macos_app) 
- Expose DeskCam if the attached device supports it
- Adds the ability to use DeskCam if the attached device supports it, with OBS
- Tested on macOS 13 + iOS 16.1 Betas, OBS 28.0.3
- Streamed DeskCam + App to Twitch w/ OBS 

mac-avcapture: Add deskcam support

---

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp

Mapping a GPU resource for CPU read immediately after GPU write creates
a large stall on the graphics thread. Use a small circular buffer, and
read the oldest frame instead.
Bubbles are bad.
Graphics thread time, preview off -> on, before: 1.5 ms -> 11 ms
Graphics thread time, preview off -> on, after: 1.5 ms -> 2 ms

decklink-output-ui: Pipeline GPU data for preview

---

docs/sphinx/reference-properties.rst

Add links to obs_data_* funcs for color, font, and editable list properties
Add links to obs_data_* funcs for color, font, and editable list properties
I am unsure of what color format the color property is stored in. From my testing in a python script, it is in ABGR format, but weirdly, the code in the built-in plugins use `vec4_from_rgba` and `vec4_from_rgba_srgb`. I also saw one use `rgb_to_bgr`. So I decided not to add info that I may be wrong (but I will gladly include it if someone clarifies).
How the data of the mentioned properties is stored is vague. For example, some may assume that the color property is stored as a string. You would have to actually view code in the repo in order to know how these properties are used. Adding some info here reduces that need.
Viewed in the …

docs: Add info on funcs to use for properties

---

plugins/mac-videotoolbox/encoder.c

Adds HDR support to the VT HEVC and ProRes encoders.
OBS on macOS currently can't do any HDR hardware encoding. The only way to properly encode HDR content is with the AOM AV1 software encoder, which isn't optimal.
With HEVC and ProRes, recorded 8-bit SDR (still works the same), 10-bit SDR (pointless), 8-bit HDR (looks like you'd expect it to) and 10-bit HDR all using PQ, by 1) looking at them and 2) throwing them into MediaInfo. Tested 10-bit HLG as well.
Streamed to YouTube in glorious HDR! (with HEVC, ProRes isn't a supported streaming protocol).
Also limited testing by yam on Discord.

mac-videotoolbox: Support P010 and HDR color spaces

---

plugins/obs-ffmpeg/obs-ffmpeg-srt.h

Fix a comparison in SRT code
Fix a bug/error

obs-ffmpeg: Fix SRT error type comparison

---

CI/flatpak/com.obsproject.Studio.json

Add Jansson as a Flatpak modules.
macOS use it's own build included in obs-deps, Windows will have the same (https://github.com/obsproject/obs-deps/pull/139).
So let's add Jansson as a module in the Flatpak too.
OBS CMake report that it will use the system Jansson.
- CI

flatpak: Add Jansson to modules

---

plugins/obs-ffmpeg/obs-ffmpeg-av1.c

In updated versions of FFmpeg (5.1.x) and SVT-AV1 (1.2.0/1.3.0), the rate contol mode selection mechanism has changed, causing CBR to throw an "Invalid Parameter" error and the encoder will fail to start. This appears to be caused by us specifying rc_max_rate, which will also fail on FFmpeg CLI. Adjust how we manage rate control methods, appropriately version-gated, to work with both our current dependency versions and the versions that we'd like to use.
Alternatively, if it's more appealing as a simpler temporary fix, we could just ifdef specifying `rc_max_rate`, and review all of these changes as a separate effort later.
Want to update to newer FFmpeg and SVT-AV1. Want to work seamlessly with current deps and newer deps.
Tested builds locally on Windows 11 against FFmpeg 5.1.2 + SVT-AVT …

obs-ffmpeg: Fix SVT-AV1 rate control mode selection

---

UI/platform-windows.cpp
UI/platform-x11.cpp
plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
plugins/obs-ffmpeg/obs-ffmpeg-rist.h
plugins/obs-ffmpeg/obs-ffmpeg-srt.h

Fixes a few logging-related issues I've noticed while playing with OBS.
I like logs that are easy to read and cohesive.
- OBS starts
- OBS streams
- OBS happy :)

UI, obs-ffmpeg: Various logging enhancements

---

UI/media-controls.cpp
UI/media-controls.hpp
plugins/image-source/obs-slideshow.c

This shows the current slide and total number of slides in the
slideshow toolbar.
Better feedback to users.
Created slideshow and made sure the slide count and current slide were updated.

UI, image-source: Add slide counter to slideshow toolbar

---

CI/flatpak/com.obsproject.Studio.json

* x264: Updated to the same commit as obs-deps
* srt: Updated to 1.5.1
* aom: Updated to 3.5.0
* svt-av1: Updated to 1.3.0
* ffmpeg: Updated to the same commit and patches as obs-deps
* luajit: Updated to the same commit as obs-deps
Update the Flatpak
Build and run the Flatpak locally.

flatpak: Update deps based on obs-deps 2022-11-21

---

UI/data/locale/en-US.ini
UI/window-basic-main-outputs.cpp
UI/window-basic-main-profiles.cpp
UI/window-basic-main.hpp
UI/window-basic-settings-stream.cpp
UI/window-basic-settings.cpp
plugins/obs-qsv11/CMakeLists.txt
plugins/obs-qsv11/QSV_Encoder.cpp
plugins/obs-qsv11/QSV_Encoder.h
plugins/obs-qsv11/QSV_Encoder_Internal.cpp
plugins/obs-qsv11/QSV_Encoder_Internal.h
plugins/obs-qsv11/common_directx11.cpp
plugins/obs-qsv11/obs-qsv-test/CMakeLists.txt
plugins/obs-qsv11/obs-qsv-test/obs-qsv-test.cpp
plugins/obs-qsv11/obs-qsv11-plugin-main.c
plugins/obs-qsv11/obs-qsv11.c

- Add Intel AV1 hardware encoder
- We should have a way to use Intel AV1 hardware encoder in streaming and recording.
- Integrated graphics (to ensure the original code path works)
- Intel CPU and Intel Arc GPU
- Non-Intel and Intel Arc GPU

obs-qsv11: Add AV1 changes

---

UI/window-basic-main.cpp

Avoid having `AutoBetaOptIn` (and `UpdateBranch`) added to the config file if the OS does not have update channel.
Avoid having unneeded config in the config file.

UI: Guard AutoBetaOptIn as Windows-only

---

docs/sphinx/reference-libobs-callback.rst

Notes that it does nothing if the combination of `signal`, `callback`, and `data` is already connected to the handler. Adds missing param `signal` description.
Typo fix
See above.
Had to check the source code to figure out whether I have to disconnect the signal before connecting it again.
Built and viewed docs

docs: Clarify signal_handler_connect()

---

plugins/mac-videotoolbox/encoder.c

HEVC is not AVC, so don't treat them the same.
Don't want to generate broken HEVC streams.
Debugger inspection for HEVC, AVC, and ProRes. Video outputs were loadable by QuickTime (mov), and VLC (mkv).

mac-videotoolbox: Don't parse HEVC as AVC

---

docs/sphinx/reference-properties.rst

Adds info about the expected return value of the callback
This info is only seen in plugin/script tutorials.
Built and viewed locally

docs: Add info on property modified callback

---

docs/sphinx/reference-frontend-api.rst
docs/sphinx/reference-libobs-util-platform.rst
docs/sphinx/reference-sources.rst

Checked https://github.com/obsproject/obs-studio/compare/28.1.2...29.0.0-beta1 to see which were added (although I didn't check each commit, just judged if they seem to be adding functions to the API, so I could have missed a few).
Also fixed this by changing the tabs to spaces
Sample of versionadded directive:
This makes it easier for developers to know which version supports the functions added. Otherwise plugin/script developers would just get support questions and spend time debugging each version to find out when it was added. This then allows them to put a minimum OBS version. I myself needed the `source_update` event.
Built and viewed locally.

docs: Add versionadded for 29.0.0 functions

---

docs/sphinx/reference-frontend-api.rst

Changes docs to say that `obs_frontend_get_streaming_service` does not increase the reference.
Current docs claim that `obs_frontend_get_streaming_service` increases the reference count. That's not actually the case.
https://github.com/obsproject/obs-studio/blob/ba27474027f6a116a83a190862224aad5fbaaf3e/UI/window-basic-main.cpp#L4284-L4292
CI build:
Also checked that other methods in that file do in fact increase the reference if they claim so.

docs: Fix reference count info of obs_frontend_get_streaming_service

---

docs/sphinx/reference-sources.rst

Just some of the missing source functions. I don't really know the rest of the source functions, or their use, so I left them alone.
Undocumented functions. I have also seen scripters ask how to control media sources. I myself did not know about `copy_single_filter`.
Built and viewed locally, checked source code and existing code for some of the functions I needed clarifications on.

docs: Add missing source functions

---

plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c

Fix chroma location to align with pattern and ensure it gets set on the context.
Doesn't seem to help, but if this works one day, OBS will be ready.
Chroma location wasn't propagating, but the video still played okay.

obs-ffmpeg: Set chroma location for VA-API

---

.github/workflows/flatpak.yml
.github/workflows/main.yml

Supersedes a part of #7384
Update Flatpak Actions to theirs v5 versions.
v5 add an option to avoid generating an artifact, Flatpak jobs in `main.yml` got changes to use this option to behave like other jobs. This removes the requirement of the "Seeking Testers" label to just test build the Flatpak.
The label is only needed to generate the bundle (artifact).
Update and improve the CI. Align all Flatpak Actions to the same version.
This PR is meant to test that.
- No bundle without the label. ([run](https://github.com/obsproject/obs-studio/actions/runs/3816815374))
- Bundle with the label. ([run](https://github.com/obsproject/obs-studio/actions/runs/3816888671))
- CI enhancements

Update Flatpak Actions to v5

---

docs/sphinx/scripting.rst

Added missing documentation for script_description function.
Added missing documentation for script_description function to the scripting documentation.
I discovered this function was not documented, so added it to improve the documentation for others.
N/A
- [x ] I have included updates to all appropriate documentation.

docs: Add script_description to scripting

---

UI/win-update/updater/updater.cpp

Only download files once.
Skips unnecessary downloads and removes potential race condition when two threads attempt to write a download with the same hash at once.
Tested locally with update from 27.2.4 to 29.0.0 (i.e. without delta patches).

updater: Deduplicate Update Downloads

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Update Mildom servers in /plugins/rtmp-services/data/services.json
Update service version in /plugins/rtmp-services/data/package.json
We change servers because of our change in stream media architecture
We test it locally, and it's ok
- [ x ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x ] My code is not on the master branch.
- [ x ] The code has been tested.
- [ x ] All commit messages are properly formatted and commits squashed where appropriate.
- [ x ] I have included updates to all appropriate documentation.

rtmp-services: update Mildom servers

---

plugins/obs-outputs/rtmp-stream.c

Improve logging of network interface used for RTMP transmission on Windows:
- Properly report > 1gbps speed by using `GetIfEntry2`
- Log RX / TX speeds separately
- Log interface error counters if non-zero
Saw a log that had "4294 mbps" and got annoyed.
Tested locally with debugger.

Improvements to Windows interface logging

---

UI/platform-windows.cpp
UI/source-tree.cpp
UI/window-basic-stats.cpp
libobs-d3d11/d3d11-subsystem.hpp
libobs-opengl/gl-shader.c
libobs-opengl/gl-windows.c
libobs/graphics/graphics-ffmpeg.c
libobs/obs-nix.c
libobs/obs-scene.c
libobs/obs-source-deinterlace.c
libobs/obs-source.c
libobs/obs.c
plugins/linux-capture/linux-capture.c
plugins/obs-ffmpeg/obs-ffmpeg-formats.h
plugins/obs-filters/crop-filter.c
plugins/obs-filters/gpu-delay.c
plugins/obs-filters/nvidia-greenscreen-filter.c
plugins/obs-filters/scale-filter.c
plugins/obs-filters/scroll-filter.c
plugins/obs-qsv11/common_directx9.cpp
plugins/win-capture/graphics-hook/d3d8-capture.cpp
plugins/win-capture/graphics-hook/d3d9-capture.cpp
plugins/win-capture/graphics-hook/dxgi-helpers.hpp

Replace one-case switches, remove workaround casts and refactor a little the Windows taskbar code to fix its switch.
Clean up switches and switch warnings that can be simply cleaned.
Builds without issue.

Switch clean up (remove one-case switch and switch warning workaround)

---

UI/window-basic-main-outputs.cpp
libobs/obs-encoder.c
libobs/obs.c

Various issues I noticed while going down a rabbit hole implementing some obs_view_t stuff. See commit descriptions for individual details.
I dislike when things do not work correctly.
- Start streaming and recording in different combinations
- Modify code to run tests on added error handling (encoder funcs, remaining view logging)

libobs, UI: Collection of encoder/output related fixes

---

UI/win-update/updater/updater.cpp

Breaks out the hashing of existing files into a separate step that runs with multiple threads.
On my system this results in about 4x faster hashing when the files are not cached (7800 ms -> 1900 ms) and still about 2x faster hashing when files are in the OS cache (980 ms -> 480 ms).
Faster hashing. Further speeding up the updating process.
Tested locally with changes applied on top of #8074.

updater: Hash files with multiple threads

---

plugins/win-capture/duplicator-monitor-capture.c

Seeing EnumDisplayDevices fail in the wild, so use GetMonitorInfo name when the persistent name is unavailable.
Fixes #8069
Getting reports that display capture is not listing all displays.
- User reports this fixes his missing displays.
- Display capture still works on my machine.
- Logging looks reasonable when forced by altering RAX in debugger.

win-capture: Support EnumDisplayDevices failure

---

cmake/Modules/FindLibva.cmake
plugins/obs-ffmpeg/CMakeLists.txt

Fixes #8062 
Make sure that obs-ffmpeg is linked against libva-drm.so. Just libva.so seems to cause issue on some distro.
~~Mostly copy-paste, avoid to overengineer like @PatTheMav asked me.~~
"Refactoring" without over-engineering.
CMake works.
obs-ffmpeg is linked to libva.so and libva-drm.so in my test build.

cmake,obs-ffmpeg: Refactor Libva finder 

---

UI/window-basic-settings-stream.cpp

Fixes #6995
Signals are blocked while encoder is enforced, those need to be unblocked before setting the new encoder.
Fix a bug
Reproduce steps from the issue and the property view is now the right one.

UI: Unblock encoder comboboxes signals before change

---

plugins/obs-vst/VSTPlugin.cpp

Added vendor name reporting when plugin asks.
Doesn't solve specific bug.
In general, it's a good practice to implement the API properly.
Some plugins use it for their own reasons.
Verified that when this call came, we returned the appropriate string.

obs-vst: Add reporting of vendor name

---

plugins/obs-filters/expander-filter.c

The gain should be positive for an upward compressor. Initially, the gain would be zeroe'd below -60 dB to ensure noise is not amplified by the upward compressor. This created a discontinuity at -60 dB since just above -60 dB, the audio is boosted by +20 dB (at default settings). This was fixed in commit 50db097 which decreased smoothly the gain so that it's 0 dB at -60 dB. However that commit forgot to limit the gain decrease which was negative below -60 dB. This is fixed by the current commit.
Additionally initialization allowed -inf gain. We hard limit to positive gains only as they should be for an upward compressor. 
Bug found in audio-support, confirmed by @RytoEX and @pkviet .
Fix found by @notr1ch and put in form by @pkviet 
Tested against a test tone.
Added a new upward …

obs-filters: Ensure gain is positive for upward compressor

---

UI/window-basic-settings.cpp

Add input validator to other resolution edit line also.
Fixes #7991
Cant input invalid character to combo edit line.
Close *Settings Dalog* then reopen, repeat the above steps, validator also work fine.

UI: Use input validator on advance resolution line edit

---

libobs-d3d11/d3d11-subsystem.cpp
plugins/win-capture/duplicator-monitor-capture.c

Add logging to debug issues with matching ids for display capture.
Difficult to troubleshoot without these ids.
Verified ids look reasonable in log with my two displays.

win-capture,libobs-d3d11: Log display ids

---

plugins/obs-filters/expander-filter.c

Re add modified callback in expander filter
fixes #8224 
intro in #8121 
reproduce following steps:
1. add expander filter
2. change preset combobox
3. work as expect

obs-filters: Fix preset properties refresh

---

plugins/obs-vst/obs-vst.cpp

Read plugins in symlink directories.
Fixes #8234 
https://doc.qt.io/qt-6/qdiriterator.html#IteratorFlag-enum
real directory `C:\Program Files\Vstplugins\` and symlink `C:\Program Files\Vstplugins\test1\` to `D:\test1\` ,work fine.
symlink `C:\Program Files\Vstplugins` to `D:\test2\` ,work fine.
symlink `C:\Program Files\Vstplugins` to `D:\test\` and symlink `C:\Program Files\Vstplugins\test3` to `D:\test3\` ,work fine.

obs-vst: Read plugins in symlink

---

plugins/mac-videotoolbox/encoder.c

Copying the encoder list takes a while which blocks the main thread. Doing the copying asynchronously removes instead of blocking the main thread improves startup performance by about 60ms (from ~60-70ms to less than 1ms including the post_load function).
Most importantly, it stops Xcode from throwing 18 runtime warnings at us.
Xcode complained *loudly* about us running the `VTCopyVideoEncoderList` function on the main thread.
macOS 13.1
Checked that all encoders are still there.
Checked with profiler that loading times for the module that previously were about 60-70ms are down to less than 1ms for both module_load and module_post_load.

mac-videotoolbox: Load encoders from system asynchronously

---

plugins/vlc-video/vlc-video-source.c

vlc-video: Support subtitle track up to 1000

---

UI/window-remux.cpp

Correct browse behavior in non-empty input edit line,
to keep single-file and multi-file (selected) behavior consistent
Found when debugged
before:
https://user-images.githubusercontent.com/30559085/218437695-31b663bb-35bf-421f-818e-06c7a8b86c4d.mp4
after:
https://user-images.githubusercontent.com/30559085/218437754-34fbde2a-7c1c-41b3-ba53-63542d376b42.mp4
Just run again
win10, latest branch

UI: Correct browse behavior in non-empty input edit line

---

UI/media-controls.cpp
UI/window-basic-main.cpp
UI/window-remux.cpp
libobs/obs-audio.c

Minor miscellaneous fixes and cleanups.
Ran OBS with UBSan and ASan and found a few minor issues that weren't really worth splitting into individual PRs.
Run with debug breakpoints to verify.

Misc. small bug fixes and code cleanups

---

UI/window-basic-main.cpp
UI/window-basic-main.hpp

Refactors how nudges are registered by using a lambda instead of separate slot functions.
Significantly cuts down on code.
About a year ago when reviewing #6326 Jim mentioned that this should probably get cleaned up.
I stumbled across this code again and remembered that.
macOS 13.2
Tested nudging in all directions, both with and without shift.

UI: Refactor / Clean up addNudge

---

UI/obs-app.cpp

Apparently XDG_CURRENT_DESKTOP returns `ubuntu:GNOME` on Ubuntu.
Ubuntu bypass our workaround which is needed for Ubuntu versions that we support that provides Qt version earlier than 6.3.
Needs to be tested.

UI: Force Wayland usage on Ubuntu GNOME

---

UI/update/shared-update.cpp

UI: Fix compile error when obs-browser disabled
When fetch OBS latest from https://github.com/obsproject/obs-studio/commit/559925ebaa4262fe383234097da47967646c9d4f,
compile error happened
```
14>F:\project\obs-studio\UI\update\shared-update.cpp(18,10): fatal  error C1083: Cannot open include file: “browser-panel.hpp”: No such file or directory
```
Re compile, work well

UI: Fix compile error when obs-browser disabled

---

plugins/mac-capture/mac-screen-capture.m

Fixes memory leaks, mostly around leaked `NSArray`s and `NSString`s.
The `unsigned` to `ScreenCaptureStreamType` change silences/fixes a false warning.
Leaks detected by running clang analyzer in Xcode.
Don't want memory to leak.
macOS 13.2
Tested all SCK modes with various different apps / windows.

mac-capture: Fix various SCK memory leaks

---

plugins/mac-videotoolbox/encoder.c

Refactors the VideoToolbox implementation and fixes existing memory leaks.
Existing code made use of macros which broke parsing in Xcode and complicated debugging as crucial code was executed within macros and not actual source code.
Use of mutable CoreFramework data structures (which were never mutated) is replaced by use of faster non-mutable variants.
When an allocator needs to be used, `kCFAllocatorDefault` is specified explicitly.
VideoToolbox session properties are also set in bulk instead of multiple consecutive calls.
Also simplifies detection of Apple Silicon hosts to make code more readable.
Tested with 8-bit as well as 10-bit encodings, H.264, HEVC and ProRes recordings.

mac-videotoolbox: Refactor implementation and fix memory leaks

---

UI/audio-encoders.cpp

Clean UI code from reference to the "mf_aac" encoder.
"mf_aac" is no more.

UI: Remove mf_aac references

---

libobs/audio-monitoring/pulse/pulseaudio-output.c

This makes multiple changes to resolve issues with monitoring. We have added a number of things over time to resolve various issues due to our misunderstanding of the pulse api and the explicitly wrong pulse api documentation.
First is removing the prior stream write tracking. Write tracking was incorrect as pulse sends you the total number of bytes it wants written at that time and not a incremental, but also this write tracking is unhelpful since we can just let begin_write signal when we should stop writing.
Second removing underflow tracking, this sort of worked to detect high latency sources like vlc which buffer ~1s of data before writing audio data. It worked because it would grow the buffer in PA until we could write enough data into it, but it didn't allow us to leverage that …

libobs: Fix pulseaudio monitoring, once and for all

---

UI/window-basic-settings.cpp

Makes duplicate detection a heck of a lot faster by using a hash table and no quadratic functions instead.
(Superseedes #8324)
Instead of putting lipstick on a pig via micro-optimisations why not just replace it with a racehorse?
Ran with `Massive.json`, hotkey duplicate detection is now instant rather than locking up the UI for a bit.

UI: Use unordered_map for hotkey duplicate detection

---

docs/sphinx/reference-core.rst
docs/sphinx/reference-libobs-graphics-effects.rst
docs/sphinx/reference-modules.rst
docs/sphinx/reference-outputs.rst
docs/sphinx/reference-properties.rst
docs/sphinx/reference-scenes.rst
docs/sphinx/reference-sources.rst
docs/sphinx/scripting.rst
libobs/obs-properties.h

Fixed 
to 
Fixed 
to 
Fixed
to 
Fixed
to
Also fixed a number of typos.
I see them when i look at the docs
Built and viewed locally.

docs: Fix layout and typos

---

.github/workflows/main.yml

This was needed to get the macOS 13 SDK when Xcode 14.0 was the default. It no longer is (at the time of writing the default is 14.2), so we can (and probably should) stop pinning to the older 14.1
This is no longer needed.
Could bite us later when we GitHub eventually removes it.
The PR is the test.

CI: Stop pinning Xcode to 14.1

---

libobs/util/bmem.c

Adds a warning for future dungeon divers about the intricacies of things you might not obviously find mentioned in the documentation for `memalign()`.
Save others from wasting 15 minutes.
If you can read this it'll work on your system.

libobs: Clarify `memalign()` todo item

---

plugins/rtmp-services/data/services.json

Update Mildom more_info_link in /plugins/rtmp-services/data/services.json
We change the more_info_link because of our new update in user manual
We test it locally, and it's ok
Documentation (a change to documentation pages)
- [ x ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x ] My code is not on the master branch.
- [ x ] The code has been tested.
- [ x ] All commit messages are properly formatted and commits squashed where appropriate.
- [ x ] I have included updates to all appropriate documentation.

rtmp-services: update Mildom more_info_link

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

The Switchboard Live Server URLs have been recently updated in the application, so the URLs need to be updated in OBS to match.
There were recent changes to the ingestion servers  at Switchboard Live
This was tested using the latest build of OBS on Windows.
Testing consisted of going live with every server to ensure connectivity  was stable.

rtmp-services: Update Switchboard Live Servers & Name

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Add Live Streamer Cafe as an RTMP service
Ease of use for our streamers to have built in support
Tested local build successfully
Tweak

rtmp-services: Add LiveStreamerCafe

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Change Stripchat Streaming Service
Change streaming service url for streaming quality improvements
Change streaming service url
Update rtmp-sevices version of services.json
My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
I have read the [contributing document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
My code is not on the master branch.
The code has been tested.
All commit messages are properly formatted and commits squashed where appropriate.

rtmp-services: Update Stripchat streaming service url

---

UI/win-update/updater/updater.cpp

When checking for running OBS instance ensure the executable of an OBS process is actually residing the the directory we want to update.
Based on an old WIP commit: https://github.com/notr1ch/obs-studio/commit/95909ee25c3bbab9f6adc2a5c3795b0c115dd185
Contains and closes #8141 if merged first.
Allow updating OBS even if some other `obs64.exe` is running (e.g. updating portable install while non-portable version is running).
Also selfishly, this means I won't have to use ShareX when recording my screen while working on updater updates :P
Verified portable install can be updated while existing OBS install is running

updater: Check if awaited instance matches current install 

---

plugins/obs-ffmpeg/texture-amf.cpp

Implement QVBR rate control for all AMF encoders. Also fixes an incorrect if check for rate control on line 1457. Switch UI from bitrate to CQ/QP value (no bitrate needed for QVBR).
When the new rate controls were added, nothing was done to acommodate this rate control, which requires a "quality value". This change makes the rate control usable. ref: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Rate%20Control%20Methods#quality-based-variable-bitrate-qvbr
The scale goes in the opposite direction of what one might expect. Low values produce low qualty (6 would be poor), high values are high quality (say 46). The scale goes from 1-51 (same as CQP)
Want rate controls avaliable to the users to work correctly.
Fixes https://github.com/obsproject/obs-studio/issues/8237
Log: …

obs-ffmpeg: Implement QVBR for AMF encoders

---

UI/data/themes/Dark.qss

Fixed an issue where some text colors in settings were black at the start of output in dark themes.
Steps to Reproduce
1. Start output
2. open settings
3. change theme to dark
4. View output or Advanced settings
| Before |  After |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/24505855/220625265-f9539b01-aef0-4c5a-bda9-e500c8056d97.png) | ![after](https://user-images.githubusercontent.com/24505855/220625329-fd06bd34-918f-4e79-94e6-b11aa6eb51a0.png) |
Before (Output Mode Advanced)
https://user-images.githubusercontent.com/24505855/220629103-7a9d87be-b991-46d6-9385-52cd41d3025e.mp4
After (Output Mode Advanced)
https://user-images.githubusercontent.com/24505855/220629280-95909f98-05 …

UI: Fix disabled text color in dark theme

---

plugins/obs-outputs/CMakeLists.txt

Fixes #8298 
Librtmp files should be added in any cases and not only when RTMPS is enabled.
Fix an issue.
Twitch bandwith test with an `ENABLE_RTMPS=OFF` build
- CMake Bug fix (non-breaking change which fixes an issue)

obs-outputs: Fix RTMP undefined symbols if built without Mbed TLS

---

plugins/win-capture/CMakeLists.txt

Suppress LNK4098 to allow building against pre-built Jansson for now.
See also:
* #7826
* #6774
Want to be able to build in Debug.
I have not built this locally, but this is identical to previous changes.

win-capture: Suppress LNK4098

---

UI/obs-app.cpp
UI/window-basic-main.cpp

This fixes the window leaking and may (in theory) improve performance.
*Someone* didn't know how to program when they made this.
Tested with an explicit destructor that now the window gets destroyed when closed.

UI: Create OBSPermissions on stack

---

CI/flatpak/com.obsproject.Studio.json

git.videolan.org repo seems to be inconsitent.
Split from #8479.
Ask @derrod.
- CI

flatpak: Use Github mirror for nv-codec-headers

---

CI/flatpak/com.obsproject.Studio.json

CMake defaults to a type commonly named "None". Setting the type to "Release" is usually required to have optimization flags applied.
Do some fixup.
Builds fine.

flatpak: Add missing CMAKE_BUILD_TYPE

---

UI/platform-osx.mm
plugins/aja/aja-common.cpp
plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c

Remove empty clauses that did nothing.
Criteria to remove is the condition of `if` statement does not call any non-constant functions and it clause is empty.
Suggested by @derrod.
- https://github.com/obsproject/obs-studio/pull/8457#discussion_r1133295859
- Checked CI.
- Checked diff.

Remove empty unnecessary clauses

---

plugins/obs-outputs/librtmp/rtmp.c

Explicitly closes the RTMP socket if `send()` returns an error.
Some `send()` errors such as a timeout with no data sent are not fatal, but librtmp will still shut down the connection on an error. During shutdown, librtmp attempts to send an `FCunpublish` message which would usually not make it to the service since the socket has been torn down due to the error. But depending on the type of `send()` error, the `FCunpublish` message could actually make it through to the remote side and cause it to think a clean shutdown occurred, disabling features like "disconnect protection".
Not tested but Seems Good™

Explicitly close RTMP socket on send error

---

UI/data/themes/Dark.qss
UI/data/themes/System.qss

Before:
After:
Limit the influence range of padding in `QListView` to fix the select list height.
Open a select list.

UI: Fix Dark and System themes select list height

---

libobs/obs-output.c

Since 65eb3c0815929866dde7d398bec7738d21e9b211 we tried to get as close a sync between audio and video tracks as we could before starting to send frames to the output.
But in be717dbb2c19aa0e91a164fa52e3d4467b64be9d when multi-track audio was considered for synchronization it continued to try and line ALL audio packets up with one video packet. While audio and video packets are similar size this will work out. But once video packets duration is smaller than 1/2 audio packet duration this may fail forever. In practice with AAC's 20-23ms frame duration we can often get tracks producing frames 5-10ms out of phase. For 60fps video this mostly fine as 16ms frame duration will cover the gap, but for framerates as low as 100 its possible to fail to synchronize. In practice this is ~50% for 6 …

libobs: Reduce synchronization limit for multiple audio tracks

---

CI/flatpak/com.obsproject.Studio.json
CI/linux/01_install_dependencies.sh
cmake/Modules/FindAsio.cmake
cmake/Modules/FindWebsocketpp.cmake

Related to:
- https://github.com/obsproject/obs-deps/pull/155
Dependency of:
- https://github.com/obsproject/obs-websocket/pull/1097
Adds nlohmann JSON, WebSocket++ and Asio as packages for Ubuntu and modules for Flatpak.
Adds finders for Asio and WebSocket++ (the one provided by WebSocket++ has a broken version check) for Linux, Windows and macOS.
Those libraries are not cleaned up in the Flatpak bundle to allow plugin to re-use the exact same versions of these libraries.
Reduce the number of submodules in obs-studio repo.
obs-studio CI on my fork (https://github.com/tytan652/obs-studio/pull/10) with obs-websocket modified to be aware of obs-deps and custom-made finders for Asio and WebSocket++.
- CI and CMake additions

Add obs-websocket headers-only libraries on Linux and add their finders

---

plugins/rtmp-services/rtmp-common.c

The condition is missing `!`.
Fixing an issue that I created.

rtmp-services: Fix supported audio codecs in rtmp_common

---

libobs/obs-video.c

Simplify code until someone needs straight alpha.
This code being removed was only added for DeckLink keying, but this transformation happens elsewhere now.

libobs: Keep output as premultiplied alpha

---

deps/obs-scripting/obs-scripting-python-import.c

Enable using Python 3.11 for scripts in OBS.
Fixes #7740
I haven't tested this yet. Some extremely limited testing was done on #7740. Additional testing welcome.

obs-scripting: Enable Python 3.11

---

UI/window-basic-auto-config-test.cpp
plugins/obs-filters/expander-filter.c
plugins/vlc-video/vlc-video-source.c

Fix translation key.
| Before |  After |
| ------------- | ------------- |
| ![b01](https://user-images.githubusercontent.com/24505855/227380706-17003900-8133-49be-89bc-19099e598472.png) | ![a01](https://user-images.githubusercontent.com/24505855/227380885-8c0d5ea9-631e-4dfb-b7c6-68c810cdd5cf.png) |
| ![b02](https://user-images.githubusercontent.com/24505855/227380754-f71c8a58-fb54-4a22-8752-505b26c8dfba.png) | ![a02](https://user-images.githubusercontent.com/24505855/227380915-5008d684-b445-4aa0-9998-4b1ff8b9a38b.png) |
| ![b03](https://user-images.githubusercontent.com/24505855/227380850-2e816d39-f585-47bf-b77d-c89eac47a33b.png) | ![a03](https://user-images.githubusercontent.com/24505855/227380958-15984228-2b37-4db8-b1 …

UI, plugins: Fix translation key

---

.github/workflows/main.yml
plugins/linux-pipewire/pipewire.c

Fix building with PipeWire on 22.04 and enable PipeWire on Ubuntu 22.04 CI.
Master is actually unable to be built on 22.04 with PipeWire enabled.
This PR CI will be the test.
Edit: 22.04 CI does have PipeWire enabled with this change
- CI

Fix building with PipeWire and enable PipeWire on Ubuntu 22.04 CI

---

plugins/obs-ffmpeg/data/locale/en-US.ini

Updates error messages when hardware encoders fail to be more actionable. Also some minor tone / grammar fixes.
Telling a user to "Check your driver is up to date" is too open to interpretation, many users will use Windows Update or Device Manager to check for updates which doesn't help. Instead, let's explicitly tell them what is most likely to fix the problem.
Simulated an error and verified the links show as expected.

Use more actionable error messages for hardware encoders

---

UI/data/locale/en-US.ini

Rename "Additive" to "Add" in the UI as the other blending modes are also verbs.
The effort to change that in the code base is more complex than I am experienced, and there isn't much gain from it. Developers will still understand the correlation between the 2 forms.
Got reported on Crowdin + consistency is great
/

UI: Rename blending mode "Additive" to "Add" in UI

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Add new Sydney ingest
Keeping things up to date
Tested using normal method

rtmp-services: Add IRLToolkit Sydney ingest

---

CI/flatpak/com.obsproject.Studio.json

Enable obs-libfdk since Freedesktop runtime provides it.
Enable an available feature and do some fixup.
Builds fine and obs-libfdk is correctly loaded.

flatpak: Enable obs-libfdk

---

.github/workflows/flatpak.yml
.github/workflows/main.yml

Bump flatpak-builder action to enable:
- https://github.com/flatpak/flatpak-github-actions/pull/120
- https://github.com/flatpak/flatpak-github-actions/pull/119
Makes Flatpak CIs only restores the cache if the cache key hit a cache from the master branch.
Prevents Flatpak CIs to saves cache on branches that are not master. So a newer cache is saved only on the master branch.
Saving non-master branch caches fills the cache quota, this PR prevents this to happen.
Note: Future PR that change the manifest will have the cache feature disabled.
PR on my fork and no cache on the PR branch was generated so far and the master branch cache is used.
- CI

CI: Only generate and use master branch Flatpak caches

---

CI/flatpak/com.obsproject.Studio.json

* x264: Updated to the same commit as obs-deps
* nv-codec-headers: Update to n12.0.16.0
* ~~mbedtls: Updated to 3.3.0~~
* ~~mbedtls: Add new required build-deps (jsonschema, jinja2)~~ obs-deps reverted Mbed TLS update
- Modules created with https://github.com/flatpak/flatpak-builder-tools/tree/master/pip
* aom: Updated to 3.6.0
* svt-av1: Updated to 1.4.1
* ffmpeg: Updated to 6.0
* luajit: Updated to the same commit as obs-deps
Prepare the update in advance, commit name will be updated later
Just built and ran the Flatpak.
- CI

flatpak: Update deps based on on obs-deps 2023-03-26

---

libobs/media-io/video-io.c

This code assumed that no one would be racing after we stopped the input thread, however the obs output thread also races and can free the inputs during disconnect before we finish closing the video mix.
Instead keep the locks around after stop and use them during close to avoid races.
Fixes crashes when stopping virtual webcam on linux.
Starting and stopping virtual webcam no longer crashes with double free.

libobs/media-io: Use inputs_mutex during close

---

.github/workflows/main.yml

`github.event.pull_request.labels` contains the labels at the time the pull_request event was triggered. Modifications made during the workflow (or after the PR was submitted and before a CI re-run) won't show up there. To reliably check the labels on CI re-runs, switch back to checking the API.
Caused by https://github.com/obsproject/obs-studio/commit/08af16edaf3ec3343c8e3e3e6f8098afb5f2afe4 (https://github.com/obsproject/obs-studio/pull/8026).
Context about `github.event.pull_request.labels` [here](https://github.com/orgs/community/discussions/39062).
Have not tested this, but this uses the same code we used to use. See the diff of https://github.com/obsproject/obs-studio/pull/8026.

CI: Fix GitHub labels check

---

.github/workflows/services-json.yml

Updates the PR creation action used in the services-json, removing deprecated `set-output` calls.
Noticed on the [most recent service checker run](https://github.com/obsproject/obs-studio/actions/runs/4559206421) (and subsequent tests [on my fork](https://github.com/gxalpha/obs-studio/actions/runs/4563503911)) that it complained about `set-output` when opening a PR. Want service checker to continue working.
Tested on my own fork that service checker, including PR creation, still works:
- [Workflow run that doesn't complain anymore](https://github.com/gxalpha/obs-studio/actions/runs/4563548383)
- Resulting PR: https://github.com/gxalpha/obs-studio/pull/14
Skimmed the changes in the `src` directory of the [third party action](https://github.com/peter-evans/create-pull-request/compare/f094b77 …

CI: Update service check PR job to remove set-output

---

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c

We were calling `avio_close` on a field that might have held an `AVIOContext`. This PR checks which type was allocated so we can call the appropriate cleanup function.
ffmpeg-mux sometimes silently crashed on error / exit.
Debugger attached to ffmpeg-mux.

obs-ffmpeg: Fix memory corruption during cleanup

---

plugins/mac-capture/audio-device-enum.c

The current method would enum though all devices looking for a matching
uid instead of directly asking for kAudioHardwarePropertyDeviceForUID.
Asking directly instead would also enable finding hidden devices that
can only be found directly via uid and not via enumerating (were we ever
to need to find such a device).
Found this in an old branch from an abandoned PR I did a while back where
it was needed to be able to find a hidden device.
While the PR never got merged and subsequently closed (since macOS added native audio capture), this cleanup is still worth being included.
Tested that CoreAudio input and output capture both still work and continue to find devices.
Also tested with hidden devices as part of that old abandoned PR.
- Code cleanup (non-breaking change which makes code …

mac-capture: Simplify coreaudio_get_device_id

---

UI/CMakeLists.txt
UI/cmake/ui-elements.cmake
UI/cmake/ui-windows.cmake
libobs/CMakeLists.txt

The `# cmake-format: sortable` lets cmake know that a list can be sorted. By default `autosort` only sorts `add_library` `add_executable` (per the [documentation](https://cmake-format.readthedocs.io/en/latest/format-features.html#sort-argument-lists)).
In the UI, adds the `sortable`  hint to large `target_sources` lists to have them be sorted alphabetically.
In libobs, just sort the lists. Unfortunately the hint doesn't differentiate between files and directories and mixes them, making it quite ugly. As such, I added the hint, undid some of the changes manually and removed it again. I don't think for libobs it's as bad not to have it as the lists aren't that volatile.
Wanted to add a new file and wondered where to put it, noticing that some lists were only close to being sorted.
macOS …

cmake: Sort large target_sources lists alphabetically

---

UI/window-basic-settings.cpp

Unfortunately FFmpeg's check is too unreliable, so just use a hardcoded list instead *sigh*.
Don't want people to be able to select invalid combnations (e.g. AV1 in MOV).
Checked that correct codecs are now marked as invalid.

Fix Codec Compatibilty Check

---

UI/window-basic-preview.cpp

The rotation handle and cursor would be drawn at the wrong spot if the source was flipped.
Fixes https://github.com/obsproject/obs-studio/issues/7744
Flipped and rotated sources

UI: Fix rotation handle when source is flipped

---

UI/window-basic-settings.cpp

Removes an unused variable.
Cleanup.
Hasn't.

UI: Remove unused uppercase format string

---

plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c

When using FFmpeg-based NVENC, with b-frames, and a non-1 framerate numerator (eg. `1001/60000` aka 59.94fps), the DTS values outputted by FFmpeg result in invalid DTS values.
Detect when using an unpatched FFmpeg build and correct the values accordingly.
Invalid DTS values were causing issues with recordings being played back correctly. Streaming was seemingly unaffected in most cases. A patch has also been submitted upstream, but given how long it's expected to find its way into peoples' machines, we can also fix it on our end without too much hassle.
Streamed at 59.94, 2 b-frames, on Ubuntu (FFmpeg NVENC), and logged PTS/DTS values
Without this PR:
```
debug: pts: 0 | dts: -2
debug: pts: 3000 | dts: 998
debug: pts: 1000 | dts: 1998
debug: pts: 2000 | dts: 2998
debug: pts: 6000 | dts: …
```

obs-ffmpeg: Compensate for invalid NVENC DTS when using b-frames

---

plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c

Makes it possible to reuqest a specific sample format when creating an FFmpeg audio encoder.
- Ensure variable bit-depth codecs (FLAC/ALAC) keep currently used sample format should FFmpeg change the default
- Allows us to feed floating point data directly into Opus to avoid an unnecessary conversion
- Allows easily adding additional flavours such as 24-bit FLAC or 16-bit ALAC if desired
Encoded some AAC/Opus/PCM/ALAC and observed that the formats selected are the ones intended.
- Tweak (non-breaking change to improve existing functionality) -->

obs-ffmpeg: Allow specifying audio sample format

---

.github/workflows/main.yml

Enable the main GitHub Actions workflow to run on merge queue (merge group) items. Let's try running merge queues with actual workflows.
Let's try out merge queues for some limited parallelism.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue
It hasn't, but this change looks correct.

CI: Enable main workflow to run on merge queue items

---

plugins/obs-ffmpeg/obs-ffmpeg-source.c

Fixes an issue where update/destroy of a media source during reconnect would block the parent thread until the next reconnect attempt. This would result in significant quantities of dropped frames, delayed OBS shutdown, or frozen UI during this period.
Fixes #7521
We should avoid blocking the graphics thread for meaningless tasks. Blocking the UI thread also is not very desirable.
- Create media source
- Specify invalid network-based playback URL (like `rtmp://stream.global.irl.run/ingest/invalidkey`)
- Click Ok
- Immediately open properties dialog of media source
- Click Ok
- UI will freeze until the reconnect delay is over, and the graphics thread will too
With this PR, it no longer happens.
With time measurement attached to `pthread_join()` call in `ffmpeg_source_update()` callback:
- …

obs-ffmpeg: Use event to cancel media source reconnect sleep (first dropped frames fix)

---

.github/workflows/main.yml

To test Sparkle 2 delta updates before release let's enable generation for beta branches for now.
Testing.
Huh?

CI: Enable Sparkle deltas for betas

---

plugins/mac-videotoolbox/encoder.c

Set a default keyframe interval when using Apple VT encoder in CRF mode. If not set, the encoder will not create *any* keyframes past the initial one, making the file nearly unusable in editors (including FCP) and video players as well as causing potential data loss issues with formats expecting to fragment on keyframes (in our case: fMOV, fMP4, HLS).
Fixes #8466
Sidenote: It seems that `kVTCompressionPropertyKey_MaxKeyFrameInterval` just straight up does nothing with the HEVC encoder on M1 even in other modes (haven't tested H.264). No matter what it's set no keyframes will be created.
This is bad and Apple should feel bad.
Made a recording with and without it to confirm keyframes are now inserted in 10 second intervals.

mac-videotoolbox: Enforce minimum keyframe interval in CRF mode

---

UI/cmake/macos/Info.plist.in

Changes the macOS `CFBundleName` to "OBS Studio", which it was before cmake 3.0. 
Before:
After (also in current release):
We switched from "OBS" to "OBS Studio" in 28.0, and it looks like it was accidentally set to "OBS" in the new-for-cmake-3 Info.plist.in.
macOS 13.3.1, see above.

cmake: Set CFBundleName to "OBS Studio"

---

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
plugins/decklink/decklink-output.cpp

Noticed OBS crashing after I removed DeckLink hardware that I enabled auto-start output against. Skip start if the device isn't initialized properly.
obs_get_output_properties leads to a callback with an empty settings object, so ignore it to avoid adding a dummy entry to the device list.
Crashes are bad, and the device list shouldn't have empty entries in them.
Crash is gone. Settings list doesn't have empty entry anymore. DeckLink output still works.

decklink: Fix crash and device list

---

.github/workflows/flatpak.yml
.github/workflows/main.yml

- Bumped the version of `flatpak/flatpak-github-actions/flat-manager` from `v5` to [`v6`](https://github.com/flatpak/flatpak-github-actions/releases/tag/v6)
- Bumped the version of `flatpak/flatpak-github-actions/flatpak-builder` from a specific commit to [`v6`](https://github.com/flatpak/flatpak-github-actions/releases/tag/v6) as requested below.
Improved Flatpak compatibility, caching & restore support, and more verbosity come with this version.
This PR hasn't been tested, but the action runs can be checked below or on the Actions tab.

CI: Bump Flatpak actions to v6

---

.github/workflows/main.yml

Update actions version to avoid the impending shut down of deprecated commands on May 31, 2023.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Want the 29.1 CI to be stable in case we need releases after May 31.
It has not been tested. The diff (excluding changes such as those to `package-lock.json` and `dist/index.js`) is only a few lines changing the versions of node and `@actions/core`. Getting this in now will help us ensure that it is tested before the full 29.1 release.
https://github.com/Apple-Actions/import-codesign-certs/compare/253ddeeac23f2bdad1646faac5c8c2832e800071...8f1f4d258d6deeb3f85395452e1d14c59ce2957e
- Tweak (non-breaking change to improve existing …

CI: Update apple-actions GitHub Actions

---

UI/window-basic-main.cpp

Makes the sorting of the Add Source menu case insensitive.
Before / After:
<p>
</p>
Was annoyed that the `macOS Screen Capture` source was at the bottom and not where it alphabetically should be.
macOS 13.3.1
See screenshots above.

UI: Sort Add Source menu case insensitively

---

docs/sphinx/scripting.rst

Adds a note about instance methods as callbacks in the timer_add function for scripting.
As determined [here](https://github.com/obsproject/obs-studio/issues/8290#issuecomment-1507773463), we consider only module methods to be supported.
Closes https://github.com/obsproject/obs-studio/issues/8290. Clearer documentation is good.
Had CI build docs:

docs: Add note about instance methods as callbacks in scripting

---

UI/window-basic-main.cpp

With additional audio/video codec options auto-remux will not work in all cases. For example using a PCM audio codec is not yet supported in MP4, and while we can use MOV in most cases, AV1 in MOV is not standardised, so AV1+PCM is a currently non-remuxable combination.
This PR addresses these limitations in the following ways:
- If PCM + HEVC/H.264, use MOV container instead
- If AV1 + PCM, skip auto-remux
Don't want failed auto-remux.
Recorded in MKV with PCM + AV1 and PCM + HEVC.

UI: Disable auto-remux for AV1+PCM, use MOV for PCM

---

deps/obs-scripting/obs-scripting-lua.c

Fix loading lua with special characters in the path
OBS fails to load lua scripts with special characters like Chinese characters in the path.
On windows 10 loading OBS scripts with Chinese characters in the path.

obs-scripting: Fix loading lua utf8 path

---

docs/sphinx/reference-encoders.rst
docs/sphinx/reference-sources.rst

Adds a note about the `data` parameter in source/encoder `.defaults[2]` possibly being null.
This comes up every once in a while (see #4832, #7020, #7416) and it's good to have it written down somewhere.
Had CI build docs.

docs: Clarify that data for source/encoder properties can be null

---

UI/xdg-data/com.obsproject.Studio.appdata.xml.in

The "or later" must be specified in the identifier or it will be seen as "only".
[SPDX identifier](https://spdx.org/licenses/) are used for those fields.
Avoid showing the wrong license.

UI: Fix the license in the AppStream metadata

---

docs/sphinx/reference-frontend-api.rst

Fixes a minor copy paste error in the documentation of `obs_frontend_get_scene_collections()`.
The same description as for `obs_frontend_get_profiles` was used, which states that the list of _profile_ names would be returned.
This has been corrected to state that the list of _scene collection_ names  is returned.
N/A
N/A

docs: Fix obs_frontend_get_scene_collections() description

---

docs/sphinx/reference-scenes.rst

Removes nonexistent functions from the docs.
These function were removed in 35704c4 (and never got into a release).
- #8767
Had CI build docs, functions are gone.

docs: Remove obs_sceneitem_group_from_scene/source

---

deps/media-playback/media-playback/cache.c
deps/media-playback/media-playback/cache.h
deps/media-playback/media-playback/media-playback.c
deps/media-playback/media-playback/media-playback.h

Add missing ISC license headers to media-playback.
Make sure that any changes in media-playback from other contributor in the future will be under ISC.
- Licensing

media-playback: Add missing license headers

---

plugins/rtmp-services/CMakeLists.txt
plugins/rtmp-services/cmake/legacy.cmake

Fix an oversight of 1f6cf34c2c4ab7dc4dc4d0ad2be1cec07d8b9e83
Which turns off by default service updates on any *nix
Avoid breakage

rtmp-services: Enable service updates by default

---

plugins/rtmp-services/rtmp-services-main.c

Fix compilation with GCC/Clang if `-Wunused-variable` is enabled which seems to be the case on AppleClang.
Got an error on macOS CI on my fork.
https://github.com/tytan652/obs-studio/actions/runs/4788284586/jobs/8514693316
```
[rtmp-services] Compiling rtmp-services-main.c
❌ /Users/runner/work/obs-studio/obs-studio/obs-studio/plugins/rtmp-services/rtmp-services-main.c:20:20: unused variable 'RTMP_SERVICES_LOG_STR' [-Werror,-Wunused-variable]
static const char *RTMP_SERVICES_LOG_STR = "[rtmp-services plugin] ";
^
❌ /Users/runner/work/obs-studio/obs-studio/obs-studio/plugins/rtmp-services/rtmp-services-main.c:21:20: unused variable 'RTMP_SERVICES_URL' [-Werror,-Wunused-variable]
static const char *RTMP_SERVICES_URL = (const char *)SERVICES_URL;
^
```
I think caching help to hide the issue. …

rtmp-services: Fix building with service updates disabled

---

UI/data/locale/en-US.ini
UI/window-basic-main.cpp

Change title bar "Portable Mode" to translation key
Reduce the display of only English in non English languages.
Local build

UI: Change "Portable Mode" to translation key

---

docs/sphinx/reference-services.rst

Add missing elements in Services API documentation.
Fix documentation.

docs: Add missing elements in Services API

---

UI/auth-restream.cpp
UI/auth-twitch.cpp

Fixes #8861
Avoid registering CEF OAuth integrations on Wayland
User that log in under X11 and open the profile under Wayland it cause crashes.
Not tested, need to sleep.

UI: Avoid registering CEF OAuth integrations on Wayland

---

.editorconfig
UI/data/themes/Acri.qss
UI/data/themes/Dark.qss
UI/data/themes/Grey.qss
UI/data/themes/Light.qss
UI/data/themes/Rachni.qss
UI/data/themes/System.qss
UI/data/themes/Yami.qss

1. Normalize theme qss files
2. Fix scene grid mode button color
https://github.com/obsproject/obs-studio/assets/26628474/9213be0c-c5f2-4daf-9139-f2b5ff2c313a
After https://github.com/obsproject/obs-studio/pull/7232#issuecomment-1232224014 , no one has remembered to normalize qss files.
Local build

UI: Normalize theme qss files and Fix scene grid mode button color

---

UI/forms/OBSBasicSettings.ui
UI/window-basic-settings.cpp

Since this widget is disabled every time it's shown and we're not enabling this anywhere, it can just be disabled in the UI form.
Noticed when working on another PR.
macOS 13.3.1
Made sure the tracks are still disabled.

UI: Clean up disabling simpleFlvTracks

---

plugins/obs-outputs/librtmp/rtmp.c

Updates keychain API calls in `librtmp` to use non-deprecated calls (`SecKeychainOpen` is been deprecated since Mac OSX 10.10).
Modernise code and avoid sudden breakage or unexpected results because of reliance on API functions explicitly marked as deprecated.
Tested on macOS 13 with an active RTMPS stream.

obs-outputs: Fix keychain API deprecation warnings on macOS

---

.gitignore

CMake lets you define a file called `CMakeUserPresets.json` which it treats like the `CMakePresets.json` file.
It's meant for local configuration that unlike common presets should not be added to the main repo, but only apply to one system. As presets defined by the user can also inherit common presets, this can be very useful.
[Documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#introduction):
> [...] CMakePresets.json is meant to specify project-wide build details, while CMakeUserPresets.json is meant for developers to specify their own local build details.
>
>CMakePresets.json may be checked into a version control system, and CMakeUserPresets.json should NOT be checked in. For example, if a project is using Git, CMakePresets.json may be tracked, and …

.gitignore: Add CMakeUserPresets.json

---

UI/data/locale/en-US.ini
UI/window-basic-about.cpp

Remove tabs for About error statements.
Before:
After:
And change error statements to translation key
There is a blank in the third line.
Local build

UI: Remove tabs for About error statements

---

plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm

These results aren't handled anywhere, and shouldn't really happen.
Static analysis yelled at me.
macOS 13.4
Static analysis no longer yells at me.

mac-virtualcam: Omit enqueue result codes

---

plugins/win-dshow/win-dshow.cpp

Set audio on dshow_input only active when there is audio
I don't want devices in the audio mixer that don't have audio.
My C910 webcam by default has no audio when added in OBS, but it shows in the audio mixer.
On windows 10 64bit with my C910

win-dshow: Set audio only active when there is audio

---

CONTRIBUTING.rst

Link to new location of Crowdin getting started page.
Closes https://github.com/obsproject/obs-studio/pull/8352
Don't direct users to a redirection + close an invalid PR.
/

CONTRIBUTING.rst: Update Crowdin guide url

---

plugins/linux-alsa/alsa-input.c
plugins/linux-alsa/data/locale/en-US.ini

Make "Custom" and "Default" translatable.
Localization is important. Noticed while taking screenshots for Crowdin.
Was able to change the strings using the language files.

linux-alsa: Make "Custom" and "Default" translatable

---

plugins/mac-capture/mac-display-capture.m

ee3c2d0 introduced a local copy of the CGDisplayStream.h header as the macOS 13.3 SDK erroneously declared functions as unavailable on older systems. This has been fixed in the macOS 14 SDK with the functions correctly being declared as available on 10.8, so we can use the system header again, and in the future remove the local copy once our minimum compile version is new enough.
Future code cleanup (removal of the local copy of the header), and want to use system headers if possible.
Works on my machine™
Compiled on macOS 14.0 Developer Beta 1 with Xcode 15 Beta 1.

mac-capture: Use system CGDisplayStream.h header on macOS 14 and newer

---

plugins/obs-ffmpeg/texture-amf.cpp

Currently OBS only queries `...CAP_MAX_THROUGHPUT` property which returns the max throughput VCN can support regardless of any other encoding/decoding sessions running in parallel. 
OBS needs to query another property named `...CAP_REQUESTED_THROUGHPUT` to get the total requested throughput and subtracts it from the max throughput to obtain the available throughput. This PR implements this additional consideration of the already requested throughput in the quality preset fallback logic.
This improves the quality preset level fallback logic to not only consider the maximum possible throughput of the VCN but to also consider the already requested throughput of the VCN.
Tested on Windows 10 with an AMD Radeon RX 7900 XTX.

obs-ffmpeg: Consider requested throughput in AMF preset fallback

---

plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Adds the game Honkai: Star Rail to the compatibility list for win-capture.
People being able to probably game capture the game.
Honkai: Star Rail runs by default with administrative privileges which requires OBS Studio to run with administrative privileges as well for game capture to work.
Selected the game in the game capture source and the warning message showed up like it should.

win-capture: Add Honkai: Star Rail to compatibility list

---

plugins/rtmp-services/data/schema/service-schema-v5.json

Removes an extra comma introduced in ed577a05a at the end of the json array which our validator isn't happy about:
https://github.com/gxalpha/obs-studio/actions/runs/5227596106/jobs/9439342571
Got an email from my GitHub Actions failing after syncing upstream changes with my fork.
GHA run, schema is now happy: https://github.com/gxalpha/obs-studio/actions/runs/5227621319/jobs/9439378300

rtmp-services: Remove extraneous comma in schema

---

docs/sphinx/reference-libobs-util-darray.rst

Clarify that da_erase_range does not include element at end_idx. New description is based on https://cplusplus.com/reference/vector/vector/erase/ but more concise.
Confused me.
Built and viewed locally. Viewed darray_erase_range to know whether end_idx element is excluded, and Jim confirmed it too.

docs: Clarify da_erase_range

---

UI/window-basic-settings-stream.cpp
libobs/obs-properties.c

Brings #9006 and #9025 to master.
Want to mitigate this issue while better solutions are WIP or under discussion.
Picked and compiled.

Backport to master

---

UI/window-basic-settings-stream.cpp

Move the WHIP entry to the bottom of the stream service list
Twitch used to be the default selection, this fixes that.
New profile with settings on macOS

UI: Move WHIP service to the bottom of the visible list

---

UI/context-bar-controls.cpp
UI/forms/OBSBasic.ui
UI/forms/OBSBasicFilters.ui
UI/properties-view.cpp
UI/window-basic-filters.cpp
UI/window-basic-filters.hpp
UI/window-basic-main.cpp
deps/obs-scripting/obs-scripting-lua.c
docs/sphinx/reference-libobs-util-darray.rst
libobs/obs-internal.h
libobs/obs-video.c
libobs/obs.c
libobs/util/darray.h
plugins/mac-capture/mac-screen-capture.m
plugins/obs-ffmpeg/texture-amf.cpp
plugins/text-freetype2/text-functionality.c
plugins/win-capture/compat-helpers.c
plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Cherry picks for 29.1.3:
- https://github.com/obsproject/obs-studio/pull/8977
- https://github.com/obsproject/obs-studio/pull/8979
- https://github.com/obsproject/obs-studio/pull/9009
- https://github.com/obsproject/obs-studio/pull/8991
- https://github.com/obsproject/obs-studio/pull/9034
- https://github.com/obsproject/obs-studio/pull/7319
- https://github.com/obsproject/obs-studio/pull/9042
- https://github.com/obsproject/obs-studio/pull/9041
- https://github.com/obsproject/obs-studio/pull/9052
- https://github.com/obsproject/obs-studio/pull/9045
- https://github.com/obsproject/obs-studio/pull/9058
- https://github.com/obsproject/obs-studio/pull/9046
- https://github.com/obsproject/obs-studio/pull/9047
- https://github.com/obsproject/obs-studio/pull/8093
- …

Cherry Picks for 29.1.3

---

docs/sphinx/reference-libobs-util-darray.rst

da_push_back and da_push_back_array return type should be size_t
Saw it
Built and viewed locally. 

docs: Fix da_push_back return type

---

plugins/obs-filters/async-delay-filter.c

This PR adds more `#ifdef DELAY_AUDIO` to avoid compiling audio delay code in async-delay-filter.c.
Delaying audio is unnecessary and the actual code delaying audio is not compiled because it's inside the `#ifdef DELAY_AUDIO` directive.
However, still the context structure has unused audio buffers, which consumes user's memory. The `destroy` callback has a code to release the audio buffer, which a code coverage shows never reached.
OS: Linux
1. Build using GCC with `-coverage` option.
1. Run obs and apply the filter to a media source.
2. Check code coverage showing 100%.

obs-filters: Don't compile audio delay code in async-delay-filter

---

UI/data/locale/en-US.ini

Capitalizes the menu action "Full-Height Docks".
Before/After:
<p>
</p>
All other menu actions are capitalized, this one should be too.
macOS 14 Dev Beta 1.
See screenshots above.

UI: Capitalize "Full-Height Docks"

---

UI/window-basic-main-transitions.cpp

When changing the member variable `source` in `QuickTransition`, also update `fadeToBlack`.
Changing the quick transition between `Fade to Black` and other types did not work.
1. Set studio mode.
2. Change `Fade to Black` to `Fade` and hit the button.
- Without this PR, it still works as `Fade to Black`.
- With this PR, it works as `Fade`.
3. Change `Fade` to `Fade to Black`.
- Without this PR, it still works as `Fade`.
- With this PR, it works as `Fade to Black`.

UI: Fix changing quick transition to/from fade to black

---

UI/window-basic-vcam-config.cpp

Use `QTStr("StudioMode.Preview")` instead of `QTStr("Preview")` for virtual camera configuration dialog, which is not listed in en-US.ini.
The string "Preview" was not translated and not listed in the Crowdin.
OS: Linux
Run obs with `LANG=ja_JP.UTF-8` and checked `Preview` is translated.
(I expect `Program (Default)` will be translated once the Crowdin data is committed to the master.)

UI: Reuse StudioMode.Preview translation for virtual camera config

---

UI/window-basic-main-transitions.cpp
UI/window-basic-main.cpp
UI/window-basic-settings.cpp
UI/window-basic-source-select.cpp
plugins/text-freetype2/text-freetype2.c

Even more things!
- https://github.com/obsproject/obs-studio/pull/9093
- https://github.com/obsproject/obs-studio/pull/9094
- https://github.com/obsproject/obs-studio/pull/9096
- https://github.com/obsproject/obs-studio/pull/9097
- https://github.com/obsproject/obs-studio/pull/9098
Bug fixes good.
N/A

More cherry picks for 29.1.x

---

deps/obs-scripting/obslua/obslua.i
deps/obs-scripting/obspython/obspython.i

Add config file functions to scripting
Allow to read and write config files from scripts
On windows 10 64bit with lua code: `obs.config_set_uint(obs.obs_frontend_get_profile_config(), "SimpleOutput", "VBitrate", 8000)`

obs-scripting: Add config file functions

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Updated Vindral service.
Added global server and stream key address
Validated json

rtmp-services: Update Vindral servers

---

docs/sphinx/reference-core.rst
docs/sphinx/reference-frontend-api.rst
docs/sphinx/reference-libobs-util-platform.rst
docs/sphinx/reference-outputs.rst
docs/sphinx/reference-services.rst
docs/sphinx/reference-sources.rst

Checked output of `git diff 29.0.2..29.1.0 -- docs/**`. Checked the actual functions they are referring to, seeing if they actually are added in 29.1, or were just undocumented before.
Having versionadded and versionchanged directives makes it easier for devs, especially plugin devs, in the future. 
Built and viewed locally, verified Esbonio doesn't show a warning or error.

docs: Add versionadded directives for 29.1

---

plugins/mac-capture/mac-screen-capture.m

Improve complicated Objective-C implementations in mac-screen-capture implementation.
mac-screen-capture implementation contains some unnecessary complicated Objective-C
implementation, which can be simpler.
Also has some randomness for the value for each boolean like type.
Add macOS Screen Capture to the Sources, grant Screen Capture permissions (and restart the application if necessary,) then open property pane. Change each list and option to make sure it works as expected.
Includes following Objective-C implementations improvements and cleanups.
- Use `for` instead of overuse of block based iteration code.
- Use `YES` and `NO` for `BOOL` type instead of wrong `TRUE`, `FALSE`, `true`, `false`.
- Use `length` …

mac-capture: Improve various Objective-C code

---

plugins/obs-qsv11/QSV_Encoder.cpp
plugins/obs-qsv11/QSV_Encoder.h
plugins/obs-qsv11/QSV_Encoder_Internal.cpp
plugins/obs-qsv11/QSV_Encoder_Internal.h
plugins/obs-qsv11/common_utils.h
plugins/obs-qsv11/common_utils_windows.cpp
plugins/obs-qsv11/obs-qsv11-plugin-main.c
plugins/obs-qsv11/obs-qsv11.c

Minor changes to remove the majority of the windows dependencies and windows specific references in common code.
Removing unused headers and dead code is always a win, using common obs locks/more accurate names for variables is also nice. This also restores the presumed purpose of the "common_utils" collection of folders to provide common utilities to the other QSV supported platform. Finally it makes the work of implementing a linux/VAAPI build easier to review later.
Prayers to the github build bot.

QSV Cleanups

---

docs/sphinx/reference-libobs-util-darray.rst

Add example for DARRAY as function parameter.
While I'm at it, I also fixed the DARRAY macro definition in the docs (which previously did not show up because of a wrong directive).
When I first started using DARRAY, it was very confusing, and there isn't any real documentation on how to use them other than code in the obs-studio repo.
Built and viewed locally. As for the code example, I tried that myself and it worked correctly, and the integers in the array were incremented.

docs: Add example for DARRAY as function parameter

---

docs/sphinx/reference-libobs-graphics-math.rst
docs/sphinx/reference-libobs-util-darray.rst

Wrong directive for macro, causing the macro to not appear in the docs.
Docs.
Viewed locally

docs: Fix macro definitions

---

libobs/CMakeLists.txt

Adds additional headers from `libobs/util` that plugins might want to use to the `public_headers` list.
These are the headers in `libobs/util` that with this PR are *not* exported:
```cmake
util/array-serializer.h
util/bitstream.h
util/cf-lexer.h
util/cf-parser.h
util/crc32.h
util/curl/curl-helper.h
util/file-serializer.h
util/lexer.h
util/pipe.h
util/serializer.h
util/task.h
util/utf8.h
util/uthash.h
util/util_uint128.h
```
If someone thinks some of them might be useful as well, I could add them.
Fixes obsproject/obs-plugintemplate#79
Fixes obsproject/obs-plugintemplate#80
(This relies on the next OBS release of course)
Hasn't. Should be simple enough in theory.

libobs: Export more libobs/util headers

---

docs/sphinx/reference-properties.rst

Adds obs_properties_add_button2 and the associated data pointer to the docs.
Also changes the argument name from `description` to `text` in the description as that's what it's called.
Fixes #9198
Had CI build docs, see above.

docs: Add obs_properties_add_button2

---

README.rst

Fixes the URL to the status badge.
Reported on Discord that it's currently broken.
Badge works.
See https://github.com/gxalpha/obs-studio/tree/readme-fix#readme

README.rst: Fix GitHub Actions status badge

---

README.rst

Fix status badge target link
N/A (Only change the correct link)

README.rst: Fix GitHub Actions status badge target link

---

UI/win-update/updater/updater.cpp

Updates the registry value for the OBS version displayed in the control panel (and possibly other places).
Fixes #2897
Updated OBS, checked that version got updated in control panel.

updater: Update installed version in registry

---

plugins/obs-qsv11/CMakeLists.txt
plugins/obs-qsv11/cmake/legacy.cmake

Fixes #9316
Add missing linking with Libva.
Fix a bug
I don't have a Intel (d)GPU compatible with QSV, so I can't seem to reach the missing symbol.
@fp-fxi feel free to test it and confirm if it works.

obs-qsv11: Link against Libva on Linux

---

plugins/obs-outputs/flv-mux.c

Updates `videocodecid` in FLV `onMetaData` object to use FourCC values for newer codecs introduced in E-RTMP/E-FLV rather than always being set to `7.0` (AVC/H.264).
References:
- https://github.com/veovera/enhanced-rtmp/blob/main/enhanced-rtmp.pdf ("Enhancing onMetaData" section)
- https://github.com/veovera/enhanced-rtmp/issues/8
Adhere to updated spec and avoid contradictory codec information in metadata and video header.
Has not been tested yet.

obs-outputs: Set videocodecid to HEVC/AV1 FourCC in E-RTMP

---

.github/actions/build-obs/action.yaml
.github/actions/qt-xml-validator/action.yaml
.github/actions/run-clang-format/action.yaml
.github/actions/run-cmake-format/action.yaml
.github/actions/run-swift-format/action.yaml
.github/actions/setup-macos-codesigning/action.yaml
.github/actions/sparkle-appcast/action.yaml
.github/actions/steam-upload/action.yaml
.github/scripts/.package.zsh
.github/scripts/utils.zsh/create_diskimage
.github/scripts/utils.zsh/read_codesign_pass
.github/workflows/build-project.yaml
.github/workflows/dispatch.yaml
.github/workflows/publish.yaml
.github/workflows/push.yaml

Fixes issues only detected when attempting release runs and other minor outstanding issues:
* A valid provisioning profile needs to be provided for builds with macOS' Camera Extension enabled. Parts for that were in place but became non-functioning when changes were made to workflows during the review process. This PR restores the functionality.
* Pushing a commit to a new branch can break the formatting and Qt XML checks because the GitHub "before" commit hash is non-existent (the current push constitutes the first commit). 
* Deployment of documentation to CloudFlare requires the `cf-pages-deploy` environment, which was missing from the workflow files.
* GitHub's CLI tool requires a valid branch checkout to automatically detect an associated pull-request, but GitHub Actions uses …

CI: Add fixes for tagged release runs and assorted minor issues

---

plugins/obs-qsv11/CMakeLists.txt

Set minimum required cmake version to 3.22 instead of 3.24.
Ubuntu 22.04 provides cmake-3.22 so that the build is failing when compiling on Ubuntu 22.04 without extra package.
The ubuntu-22.04 runner on GitHub Actions has a newer cmake as described on the document.
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools
So, CI is succeeding.
OS: Ubuntu 22.04 on docker
Installed necessary packages by `apt`.
Checked the build script `.github/scripts/build-linux` succeeded.

obs-qsv11: Downgrade minimum required CMake version

---

.github/workflows/build-project.yaml
.github/workflows/dispatch.yaml
.github/workflows/pr-pull.yaml
.github/workflows/publish.yaml
.github/workflows/push.yaml
.github/workflows/scheduled.yaml

Shortens the names of the PR workflow and build/formatting jobs
Long prefixes often make the important parts like OS get cut off, especially on mobile devices.
Works fine on this PR

CI: Shorten Pull Request workflow names

---

buildspec.json

* deps.ffmpeg: Add macOS dSYMs
* deps.ffmpeg: Update libpng to 1.6.40
* deps.ffmpeg: Update opus to 1.4
* deps.ffmpeg: Update SVT-AV1 to 1.6.0
* deps.ffmpeg: Update aom to 3.6.1
* deps.ffmpeg: Update mbedTLS to 3.4.0
* deps.ffmpeg: Update libsrt to 1.5.2
* deps.ffmpeg: Update AMF to 1.4.30
* deps.macos: Add macOS dSYMs
* deps.macos: Add Carla 2.6.0-alpha1
* deps.macos: Add Libqrcodegencpp
* deps.macos: Update LuaJIT to 2.1 8635cbabf3
* deps.macos: Update libpng to 1.6.40
* deps.macos: Update FreeType to 2.13.1
* deps.macos: Update Asio to 1.28.0
* deps.macos: Fix SWIG version number
* deps.macos: Update Sparkle to 2.4.2
* deps.macos: Update Syphon Framework to 5.0 cb3d8ec506
* deps.windows: Add Carla 2.6.0-alpha1
* deps.windows: Add VPL v2023.3.0
* deps.windows: Add …

CI: Update deps to 2023-08-02 release

---

UI/cmake/feature-youtube.cmake
UI/cmake/legacy.cmake
UI/data/locale/en-US.ini
UI/window-basic-auto-config.cpp
UI/window-basic-main.cpp
UI/window-basic-main.hpp
UI/window-basic-settings-stream.cpp
UI/window-basic-settings.cpp
UI/window-dock-youtube-app.cpp
UI/window-dock-youtube-app.hpp
UI/window-youtube-actions.cpp
UI/window-youtube-actions.hpp
UI/youtube-api-wrappers.cpp
UI/youtube-api-wrappers.hpp

Integration of YouTube Control Panel in the OBS (like YT chat).
This new YT dock panel makes integration with YT  more responsive and gives the creator more control over the broadcast session. It also allows the YT side to faster deliver own changes to creators (including new features and possible bugfixes).
Needs obs-browser plugin [PR410](https://github.com/obsproject/obs-browser/pull/410) code changes.
Tested manually.
* Windows 10 x64, Linux Ubuntu 22.04, macOS M1 Ventura, macOS x86_64 Catalina.

UI: Add YouTube Control Panel dock (based on CEF and studio.youtube.com)

---

build-aux/modules/10-mbedtls.json
build-aux/modules/20-aom.json
build-aux/modules/20-srt.json
build-aux/modules/20-svt-av1.json
build-aux/modules/40-luajit.json
build-aux/modules/90-asio.json

Update Flatpak modules with obs-deps 2023-08-02 as bases.
- Update mbedTLS to 3.4.0
- Update aom to 3.6.1
- Update libsrt to 1.5.2
- Update SVT-AV1 to 1.6.0
- Update LuaJIT to 8635cbabf3
- Update Asio to 1.28.0
Update deps.
Just build and ran it.

build-aux: Update Flatpak modules

---

plugins/win-capture/graphics-hook/vulkan-capture.c

Our solution for adding TRANSFER_SRC usage for imageless framebuffers was triggering validation errors when combined with image view usage overrides. Add TRANSFER_SRC onto usage overrides for swap chain image views to fix mismatches.
Fixes #9353
Vulkan hook stability.

graphics-hook: Handle VkImageViewUsageCreateInfo

---

UI/window-basic-main.cpp
UI/window-dock-youtube-app.cpp
UI/window-dock-youtube-app.hpp

Replace the two add dock call by the newest one, and rely on the dock's action toggle rather than a custom one.
I was just dumbfounded by those two add dock code lines.
Ran OBS with YouTubse service selected and the dock is still added as expected.

UI: Use new add dock path for YouTubeAppDock

---

libobs/obs-cocoa.m

Fixes held-down hotkeys (such as "push to talk") on macOS.
Fixes https://github.com/obsproject/obs-studio/issues/9023.
To avoid a mismatch between the state of pressed keys as held by the hotkey thread and keys pressed while the application is in focus, local key events need to be monitored as well (even though they are already handled by Cocoa's main event loop).
Tested on macOS 13.4 using "push to talk" functionality on a media source.

libobs: Add local event monitor for hotkey thread

---

UI/data/locale/en-US.ini
UI/window-basic-main.cpp

Make title bar "SAFE MODE" translatable.
Reduce the display of only English in non English languages.
Local build.

UI: Make title bar "SAFE MODE" translatable

---

UI/window-dock-youtube-app.cpp

Avoid showing YouTubeAppDock each time settings are updated
If a user has purposefully hidden the docks, they should not reappear. One time is enough.

UI: Avoid showing YouTubeAppDock each time settings are updated

---

buildspec.json

CI: Update deps to 2023-08-08 release
* deps.windows: Add VPL debug build
VPL, similar to AJA NTV2, requires a separate Debug library to build OBS Studio in Debug. Want OBS Studio to be able to build in Debug. See:
* https://github.com/obsproject/obs-deps/pull/205

CI: Update deps to 2023-08-08 release

---

.github/actions/qt-xml-validator/action.yaml
.github/actions/services-validator/action.yaml

CI: Pin third-party actions to specific commits
Recommended practice is to pin third-party actions to specific commits.
CI: Update peter-evans/create-pull-request GitHub Action
We're currently using peter-evans/create-pull-request v4.0.3 which is still using the deprecated set-output command. This was fixed in v4.1.4, so let's update to that version for now.
The latter Action is used for the services-validator when creating the PR to remove services/servers. The diff between v4.0.3 and v4.1.4 looks benign, but perhaps @derrod can take a look.
https://github.com/peter-evans/create-pull-request/compare/v4.0.3...v4.1.4
https://github.com/peter-evans/create-pull-request/compare/f094b77505fb89581e68a1163fbd2fffece39da1...ad43dccb4d726ca8514126628bec209b8354b6dd
Don't want warnings on CI. The …

CI: Update GitHub Actions to remove warnings

---

libobs/util/c99defs.h

Define PRAGMA_WARN_DEPRECATION for MSVC to enable using that define for cross-platform code, which allows us to write slightly less code when we need to suppress this warning.
For cross-platform code, instead of something like this:
```
#if defined(_WIN32)
#pragma warning(push)
#pragma warning(disable : 4996)
#elif defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif
...
#if defined(_WIN32)
#pragma warning(pop)
#elif defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
```
or this:
```
PRAGMA_WARN_PUSH
PRAGMA_WARN_DEPRECATION
#pragma warning(disable : 4996)
...
PRAGMA_WARN_POP
```
I just want to write this:
```
PRAGMA_WARN_PUSH
PRAGMA_WARN_DEPRECATION
...
PRAGMA_WARN_POP
```
References:
* …

libobs/util: Define PRAGMA_WARN_DEPRECATION for MSVC

---

.clang-format
.github/actions/run-clang-format/action.yaml
UI/properties-view.cpp
UI/win-update/updater/manifest.hpp
UI/win-update/updater/updater.cpp
UI/window-basic-main.cpp
UI/window-basic-settings.cpp
build-aux/.run-format.zsh
libobs/obs-module.h
libobs/obs-source.c
libobs/obs.hpp
libobs/util/profiler.hpp
plugins/aja/aja-card-manager.cpp
plugins/aja/aja-card-manager.hpp
plugins/aja/aja-common.cpp
plugins/aja/aja-common.hpp
plugins/aja/aja-presets.cpp
plugins/aja/aja-presets.hpp
plugins/aja/aja-routing.cpp
plugins/aja/aja-routing.hpp
plugins/coreaudio-encoder/encoder.cpp
plugins/mac-avcapture/av-capture.mm
plugins/mac-avcapture/left-right.hpp
plugins/mac-avcapture/scope-guard.hpp
plugins/obs-ffmpeg/obs-ffmpeg-url.h

Update to clang-format 16. I used clang-format 16.0.5 for the formatting because that's what VS 2022 17.7 ships.
This does not cover submodules (obs-browser, libdshowcapture, obs-websocket). Those can be done in tandem with this or separately.
Want to stop pinning to clang-format 13.
Ran the formatter. I didn't do build tests, but CI will.

CI: Update to clang-format 16

---

UI/window-basic-settings.cpp

Like in 4f8b17d61, "toggled" is the signal that listens for changes however they may have happened (including through things like accessibility software), whereas clicked only is emitted on mouse clicks. We should react to any kind of change, whatever prompted it.
I looked at 4f8b17d61 again when wanting to rebase #6700 on master (since it's kinda related), when I spotted the "clicked" on the line above and it dawned on me...
macOS 14
Toggling the checkbox with VoiceOver now activates the "Apply" button.
Before, it didn't.

UI: Use QCheckBox::toggled signal for checkbox changes

---

.github/workflows/dispatch.yaml
.github/workflows/push.yaml

Updates obs-crowdin-sync to the latest commit https://github.com/obsproject/obs-crowdin-sync/commit/30b5446e3b5eb19595aa68a81ddf896a857302cf which includes all changes from https://github.com/obsproject/obs-crowdin-sync/pull/13.
I'm also re-adding the `fetch-depth` option, as it was removed with the workflow overhaul.
Fix the translations pull not working because Crowdin changed stuff in their API and some QOL changes described in the PR.
By testing all scenarios I could come up with in a forked org on GitHub and a private Crowdin project + unit tests.

CI: Update obs-crowdin-sync to latest

---

docs/sphinx/reference-frontend-api.rst

Fix the deprecated version set for `obs_frontend_add_dock` since it is deprecated for the version after 29.1.x.
I forgot to update the `deprecated` mark in #7637 after 29.1 got released.
Build the doc locally and it looks correctly rendered

docs: Fix obs_frontend_add_dock deprecation version

---

plugins/obs-filters/noise-suppress-filter.c

This fixes a bug when swapping NVIDIA effects.
The update signal triggers a destruction of the previous effect, but the effect would still run, potentially causing a crash.
The mutex added in the NVIDIA processing function prevents that.
Fixes a bug.
Repro steps for the bug:
- swap frequently the nvidia effects (ex: from denoiser to dereverb, etc).
- use current release (29.1.2).
In Debug, it is triggered much faster.
Crash is gone.

obs-filters: Add a mutex when running NVIDIA Audio FX

---

UI/cmake/feature-macos-update.cmake
UI/cmake/feature-whatsnew.cmake
UI/cmake/feature-youtube.cmake

Adds the `#cmake-format: sortable` flag to some longer lists ("The list is formatted to be separated into multiple lines" is my threshold for "long" here).
Saw a conversation on a recent PR where it was suggested to sort the list in `feature-youtube.cmake`, adding this attribute can eliminate manual sorting in the future.
Went through other `feature-` files and looked for lists that are long enough to be worth sorting.
macOS 14, ran cmake-format. Lists are now sorted.

cmake: Mark source lists in feature files sortable

---

docs/sphinx/reference-libobs-util-dstr.rst

Saw it, and had to debug to figure out its behavior. Also had to search OBS repo to find out how to use it.
Built and viewed locally. Also ran the example code.

docs: Clarify strlist_split

---

build-aux/modules/40-plog.json
build-aux/modules/40-usrsctp.json
build-aux/modules/50-libdatachannel.json
build-aux/modules/50-libqrcodegencpp.json

Add missing build type to most of the Flatpak modules added for OBS 30.
Without them, the module is built without compiler optimization.
Align with other modules.
CI should build without issue.

build-aux: Add missing build type to Flatpak modules

---

plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c

This recent commit [1] broke srt & rist streaming because obs_output_video now returns a null ptr for encoded outputs. This fixes it by retrieving the pointer from the encoder.
[1] https://github.com/obsproject/obs-studio/commit/fb57eff212fbe5e777cf559288bc70bf67d9c428
Fix streaming with SRT / RIST.
SRT streaming works again.

obs-ffmpeg: Fix broken mpegts output

---

.github/workflows/build-project.yaml
.github/workflows/publish.yaml
build-aux/com.obsproject.Studio.json

Closes #9451 since it superseeds it
1.Update Gtihub Action to fix the build-bundle option and bump its dependencies.
2.Update KDE Runtime to 6.5.
1. Fix the build-bundle option which allow to avoid bundling for nothing and save time on workflow runs.
2. It can be done since docks are fixed with Qt 6.5
Also 2. Reduce the risk of people complaining about the EOL message when they install KDE 6.4 by installing OBS Studio through the CLI
1. I did many testing for the action while reworking aarch64 builds.
2. Not tested but since it should be fine since it's a minor bump and Windows and macOS are on 6.5
- CI

Update Flatpak actions and runtime

---

UI/cmake/feature-restream.cmake
UI/cmake/feature-twitch.cmake
UI/cmake/feature-youtube.cmake

The current regex pattern will successfully match if the cache variable contains the pattern anywhere inside the string. Let's restrict the regex pattern such that it requires the pattern to be precisely between the beginning and end of the string with no other characters in between those anchor points.
Was testing locally and ran into this when I tried to build without obs-browser but the "YouTube API connection" feature was still enabled. I tried to disable that by deliberately prefixing the `YOUTUBE_CLIENTID_HASH` cache variable with what I thought were characters sure to avoid matching the pattern ("removemelater_"). However, the pattern still matched, and the feature was still enabled. I noticed that the pattern did not use beginning and end of string anchors, so I added them, and …

UI: Restrict regex pattern for OAuth secrets

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Rebranding Utreon to Playeur
Rebranding Utreon to Playeur
Manually applied the json entry to my local installation.

rtmp-services: Rebranding Utreon to Playeur

---

UI/window-basic-stats.cpp

Standardize spelling, fix typo.
Don't like multiple spellings and typos.
N/A

UI: Standardize spelling of closable, fix typo

---

UI/auth-youtube.cpp

The native popup has the problem that it doesn't work for links, leaving us with an unclickable text where a link should be. Qt 6.6 has an option to disable the native dialog, so let's add this to make the link clickable again.
With the native messagebox, the link is unclickable:
This PR restores the previous behavior: 
macOS 14
Previous behavior is back, the link is now clickable.

UI: Don't show native popup for YouTube auth message box

---

.editorconfig
UI/forms/OBSBasicSettings.ui

It just fix the order of the IP settings to be more correct, select the family and then the IP not the reverse.
No logic is changed, I don't want to introduce more code hacking around RTMP outputs properties.
Before:
After:
The actual order is really bad UI/UX wise.
Just run OBS, and the settings were in the expected order.

UI: Fix IP settings order

---

buildspec.json

CI: Update deps to 2023-09-18 release
* deps.ffmpeg: Apply fixups for libdatachannel
* deps.macos: Update qrcodengen CMake project to fix CMake packages
* deps.windows: Update qrcodengen CMake project to fix CMake packages
* deps.windows: Add qrcodegencpp debug build
* deps.windows: Update FreeType to 2.13.1 to align with macOS version
Qrcodegencpp, similar to AJA NTV2 and VPL, requires a separate Debug library to build OBS Studio in Debug. Want OBS Studio to be able to build in Debug. See:
* https://github.com/obsproject/obs-deps/pull/210
* https://github.com/obsproject/obs-studio/pull/9601
I tested building the deps locally, and I pulled down #9601 locally and tested, and it seemed to build fine.

CI: Update deps to 2023-09-18 release

---

buildspec.json

CI: Update deps to 2023-09-28 release
* deps.ffmpeg: Fix libdatachannel packaging for macOS
* deps.qt: Update Qt6 to 6.5.3 for Windows
* deps.qt: Update Qt6 to 6.5.3 for macOS
Want to fix obs-webrtc failing to load on macOS.
Want to fix Qt regressions that were present in 6.5.2. Regressions in 6.5.2 with multi-display systems (context menus appearing on the wrong display) should be fixed in 6.5.3. Other 6.5.x regressions should also be fixed.
* https://bugreports.qt.io/browse/QTBUG-114199
* https://bugreports.qt.io/browse/QTBUG-115511
* https://bugreports.qt.io/browse/QTBUG-115699
* https://bugreports.qt.io/browse/QTBUG-116060
* https://bugreports.qt.io/browse/QTBUG-116155
* https://bugreports.qt.io/browse/QTBUG-116499
* https://bugreports.qt.io/browse/QTBUG-116549
See:
* …

CI: Update deps to 2023-09-28 release

---

libobs/graphics/effect-parser.c

Errors creating shader pass as errors for `gs_effect_create`
`gs_effect_create` can fail but the errors would still be empty. The errors are useful to have to display to a user and not have to look in the obs log file every time for the error.
On windows 11 with obs-shaderfilter loading an invalid shader.

libobs: Fix errors for gs_effect_create

---

buildspec.json

CI: Update deps to 2023-10-09 release
* deps.ffmpeg: Update libvpx to v1.31.1
Want to update libvpx to address a CVE.
I have not tested this, but the diff is minimal.

CI: Update deps to 2023-10-09 release

---

cmake/common/buildspec_common.cmake

Store and read dependency hashes to determine if a dependency needs to have its extracted copy replaced (e.g., a dependency that had its revision changed but not its version changed).
Want #9684 to replace deps without user/dev intervention.
Tested locally with @PatTheMav .

cmake: Use dependency hashes to track revisions

---

buildspec.json

CI: Update CEF builds
Update CEF builds to patch two CVEs:
* CVE-2023-4863
* CVE-2023-5217
Want to address CVEs.
I haven't tested this.

CI: Update CEF builds

---

build-aux/modules/99-cef.json

Alike to #9684 but for the Flatpak
Update CEF build to patch two CVEs:
* CVE-2023-4863
* CVE-2023-5217
Same as #9684
Ran OBS with a browser dock with no issue.

build-aux: Update Flatpak CEF build

---

UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp

Didn't realize OBS could output both program and preview views at the same time with multiple devices.
Also remove render callbacks earlier on stop to avoid use-after-free.
Fixes #9697
Crashes and lost functionality are bad.
Combination of 4K Extreme 12G and Mini Monitor 4K:

decklink-output-ui: Decouple DeckLink output state

---

buildspec.json

CI: Update deps to 2023-10-26 release
* deps.qt: Backport patch for CVE-2023-43114
* deps.qt: Backport patch for QTBUG-117779
* deps.qt: Backport patch for QTBUG-118117
Fix a crash on Windows when reading corrupt font data.
Fix a bug on Windows where child windows would move with the parent window and also resize to their minimum size.
Fix a bug on Windows that caused taskbar icon overlays to be reset by Qt if previously set via native Windows API calls.
Want less bugs in OBS.
On Windows 11, I built Qt locally with these patches and built OBS Studio against that version of Qt. I verified that QTBUG-117779 and QTBUG-118117 were no longer present.

CI: Update deps to 2023-10-26 release

---

plugins/obs-qsv11/obs-qsv11.c

Calling update_targetusage in update_params only updates the setting when an encoder session is initialized. Calling update_targetusage in rate_control_modified, like update_latency and update_enhancements, will update the setting when the Settings window is loaded. This will cause the updated setting to be reflected in the UI.
It's probably better for users if the UI reflects the updated setting.
Fixes #9574
Tested on Windows 11 by importing an OBS 29.1.3 profile into a local build with this change. Verified that the UI showed the newly migrated setting rather than the first entry (TU1).
As far as I could tell, the setting in recordEncoder.json will still continue to contain the old target usage string until the encoder settings are changed and saved. Logging shows the correct target …

obs-qsv11: Migrate target usage settings

---

docs/sphinx/reference-scenes.rst

Fixed the signature of obs_sceneitem_get_group in docs to match the [actual one](https://github.com/obsproject/obs-studio/blob/20ffdda89a4590dc0e44f6a2f703abda9b4a2d45/libobs/obs.h#L1959C29-L1959C29)

docs: Fix obs_sceneitem_get_group signature

---

plugins/obs-ffmpeg/vaapi-utils.c

Removes an unused variable that can trigger warning on recent version of GCC.
I quickly reviewed #9735 between 1:00 AM and 2:00 AM. I didn't see the unused variable.
Builds without the warning.

obs-ffmpeg: Remove unused variable in VA-API utils

---

libobs/obs-properties.c

If a plugin removes a property when processing 'modified' property callback, OBS WILL CRASH.
This commit moves callback processing to after iterating over properties, thus removing the chance to crash OBS.
Example of offending plugin: obs-source-record
Offending code: https://github.com/exeldro/obs-source-record/blob/76da992729ef6d6ed2f691235ca0e086127f2716/source-record.c#L1035-L1055
After applying the change OBS no longer crashes when loading the plugin settings.
I have changed `obs_properties_apply_settings_internal` to put all properties with callbacks in a temporary array.
After iterating through properties `obs_properties_apply_settings` calls every callback from the temporary array.
The official API of `obs_properties_apply_settings` remains unchanged.
Reference to the change that …

libobs: Fix crash when plugins delete properties in callback

---

buildspec.json

* deps.windows: Fix building against deps on Windows in Debug
Building OBS Studio (specifically obs-websocket) on Windows in Debug against qrcodegencpp would fail due to workflow and caching issues causing the previous release package to not contain all components.
No deps versions have changed. This is just a deps package fix.
Want Debug builds on Windows to work.
Built locally in Debug on Windows 11.

CI: Update deps to 2023-11-03 release

---

build-aux/com.obsproject.Studio.json

Since Qt 6.2, "org.kde.StatusNotifierItem-2-2" is no longer needed to make the tray feature work
`flatpak-builder-lint` output with exceptions on the manifest before:
```
{
"errors": [
"finish-args-broken-kde-tray-permission"
],
"warnings": [
"finish-args-contains-both-x11-and-wayland"
]
}
```
After:
```
{
"warnings": [
"finish-args-contains-both-x11-and-wayland"
]
}
```
Make the Flatpak pass incoming Flathub validation. Keeping this permission will trigger a `"finish-args-broken-kde-tray-permission"` error while validating.
Ran flatpak-builder-lint (and on CI) locally against the manifest and ran the Flatpak without the permission and the tray icon still works.
- Code cleanup (non-breaking change which makes code smaller or more …

build-aux: Remove StatusNotifierItem Flatpak permission

---

UI/window-basic-auto-config.cpp
UI/window-basic-main-outputs.cpp
UI/window-basic-main.cpp
UI/window-basic-preview.cpp
UI/window-basic-settings-stream.cpp
build-aux/com.obsproject.Studio.json
buildspec.json
deps/obs-scripting/obs-scripting-python.c
docs/sphinx/reference-scenes.rst
libobs/CMakeLists.txt
libobs/data/area.effect
libobs/data/bicubic_scale.effect
libobs/data/bilinear_lowres_scale.effect
libobs/data/default.effect
libobs/data/lanczos_scale.effect
libobs/obs-properties.c
plugins/obs-filters/data/blend_add_filter.effect
plugins/obs-filters/data/blend_mul_filter.effect
plugins/obs-filters/data/blend_sub_filter.effect
plugins/obs-filters/data/chroma_key_filter.effect
plugins/obs-filters/data/chroma_key_filter_v2.effect
plugins/obs-filters/data/color_correction_filter.effect
plugins/obs-filters/data/color_grade_filter.effect
plugins/obs-filters/data/color_key_filter.effect
plugins/obs-filters/data/color_key_filter_v2.effect
plugins/obs-filters/data/luma_key_filter.effect
plugins/obs-filters/data/luma_key_filter_v2.effect
plugins/obs-filters/data/mask_alpha_filter.effect
plugins/obs-filters/data/mask_color_filter.effect
plugins/win-capture/graphics-hook/vulkan-capture.c

Cherry pick commits for release/30.0.
* https://github.com/obsproject/obs-studio/pull/9773
* https://github.com/obsproject/obs-studio/pull/9785
* https://github.com/obsproject/obs-studio/pull/9775
* https://github.com/obsproject/obs-studio/pull/9780
* https://github.com/obsproject/obs-studio/pull/9801
* https://github.com/obsproject/obs-studio/pull/9019
* https://github.com/obsproject/obs-studio/pull/9798
* https://github.com/obsproject/obs-studio/pull/9818
* https://github.com/obsproject/obs-studio/pull/9819
* https://github.com/obsproject/obs-studio/pull/9795
* https://github.com/obsproject/obs-studio/pull/9716
* https://github.com/obsproject/obs-studio/pull/9809
Want to finalize cherry-picks for release/30.0.
Tested in original PRs. …

Cherry-picks for 30.0

---

.github/actions/flatpak-builder-lint/action.yaml
.github/workflows/build-project.yaml
.github/workflows/publish.yaml

We need to pass the build-log-url now, and validate our output with the flatpak-builder-lint tool. Let's do that.
Depends on:
- #9809 to pass validation
Supersedes #9776 and the differences are:
- Avoid the use of the org.flatpak.Builder Flatpak to use the linter since it does not seem to work inside a container in GHA. So this PR relies on cloning the linter repo and using Poetry to run it.
- Linter warnings and errors are reformatted as action annotations
- Validation steps are factorized as a custom action to avoid repetition
- Some customization were added to allow validating the Flatpak repository on pushes to avoid encountering an error only while on publish validation.
- "`--exceptions`" is added since we need one and have it for `"finish-args-flatpak-spawn-access"` 
- …

Flathub publishing updates

---

docs/sphinx/reference-settings.rst
libobs/obs-data.h

Expose the function `obs_data_set_autoselect_array` on obs-data.h.
Also add `obs_data_set_autoselect_array` and `obs_data_get_autoselect_array` to the document.
The function is implemented in obs-data.c as below but never exposed as an API.
https://github.com/obsproject/obs-studio/blob/e14b0e99bbe6102ffc04bb2bb1773437822458be/libobs/obs-data.c#L1250-L1254
Prepared an array `array` and set some items. Then, ran these code and checked the set/get APIs works fine.
```c
obs_data_set_autoselect_array(data, "array_as", array);
obs_data_array_t * array1 = obs_data_get_autoselect_array(data, "array_as");
assert_ptr_not_equal(array1, NULL);
obs_data_array_release(array1);
```
Visually checked there are `set` and `get`, `default` and `autoselect` APIs for all the basic variants (`string`, `int`, …

libobs: Expose obs_data_set_autoselect_array

---

.github/actions/flatpak-builder-lint/action.yaml
.github/workflows/build-project.yaml
.github/workflows/publish.yaml

Cherry pick commits for release/30.0.
- #9814
- Reason: Publish is ran from the tag workflow files
- The two last commits are not picked because those do not affect the publish workflow
For now avoid having the Flathub publish fail.
Tested in original PR(s).
- New CI feature (non-breaking change which adds functionality) -->

Cherry-picks for 30

---

plugins/mac-capture/mac-sck-video-capture.m

Adds handling for when a macOS Screen Capture Window Capture source is trying to acquire a capture for a window where there is no `SCWindow` that corresponds to that source's window ID. This most commonly happens when trying to reacquire a capture for a window that has since been closed. The `nil` case is now handled by returning from `init_screen_stream` early, in similar fashion as we do when finding a pre-Ventura system.
Additionally, the existing fallback for window ID 0 has been modified to use this same early return. While, to my knowledge, this id 0 code isn't reachable under normal conditions, we now avoid any scenario where we could acquire a capture for a window that the user has not specifically picked.
This resolves at least one prominent case where the macOS Sonoma capture …

mac-capture: Add handling for nil target window

---

docs/sphinx/reference-frontend-api.rst

Tested this in code, and it makes sense from the way `scenes.sources.array[i]` is accessed.

docs: fix missing accessor in example

---

libobs/obs.c

While filters are saved using obs_save_source other mutex are used. To prevent a deadlock, don't keep the filter mutex while iterating the filters. This fixes #9893
I don't like deadlocks. Always try to keep a mutex locked as short as possible.
On windows 64 tested saving the scene collection.

libobs: Don't keep filter mutex in obs_save_source

---

UI/properties-view.cpp

Added spacing to QHBoxLayout
Some elements are overlapping on MAC due to 
no spacing in QHBoxLayout.
https://github.com/obsproject/obs-studio/issues/7758
Tested on MAC only.
- [ x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x] My code is not on the master branch.
- [ x] The code has been tested.
- [ x] All commit messages are properly formatted and commits squashed where appropriate.
- [ x] I have included updates to all appropriate documentation.

UI:Properties view

---

libobs/obs-video.c

Reuses the render texture for mixes that match a previously renderer mix's view/colorspace/resolution.
In combination with #9937 this allows GPU scaling to be used for encoded auxiliary views.
Currently the encoder-only mixes created for GPU scaling (added in #9043) re-render the entire mix, which seems wasteful when we already have a perfectly good render texture!
Ideally "expensive" sources such as filters will only get rendered once per tick anyway, but some filters may not do this, e.g. `obs-composite-blur` didn't until https://github.com/FiniteSingularity/obs-composite-blur/pull/16, so this may save some GPU time for users with many filters as well.
Tested with GPU scaling enabled on recording output ([like so](https://github.com/derrod/obs-studio/commit/fadfb94749d20f7d80b6be3e1a7450 …

libobs: Reuse matching mix's render texture if possible

---

libobs/obs-encoder.c

Changes GPU encoder mix creation to use the mix originally specified as the encoder media rather than always using the main mix.
Bug fix.
Has been validated to still work with the main view, actually using aux views was not tested.

libobs: Fix GPU scaling always using the main mix

---

.github/scripts/.build.zsh
UI/obs-app.cpp
UI/win-update/updater/updater.cpp
cmake/macos/helpers.cmake
libobs-d3d11/d3d11-shader.cpp
libobs/obs-encoder.c
libobs/obs-scene.c
libobs/util/platform-cocoa.m
libobs/util/platform-nix.c
plugins/linux-pipewire/pipewire.c
plugins/mac-capture/mac-sck-video-capture.m
plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Cherry picks for the first 30.0 hotfix.
PRs included:
- https://github.com/obsproject/obs-studio/pull/9803
- https://github.com/obsproject/obs-studio/pull/9806
- https://github.com/obsproject/obs-studio/pull/9845
- https://github.com/obsproject/obs-studio/commit/3e6797ca5bfe445381d721e407163b70b8de6d1e
- https://github.com/obsproject/obs-studio/pull/9866
- https://github.com/obsproject/obs-studio/pull/9880
- https://github.com/obsproject/obs-studio/pull/9881
- https://github.com/obsproject/obs-studio/pull/9879
- https://github.com/obsproject/obs-studio/pull/9875
Bugs.
?

30.0 hotfix cherry picks

---

libobs/obs-scene.c

This small patch ensures media source to be removed when being removed with scene.
This PR is to fix [issue #6145 ](https://github.com/obsproject/obs-studio/issues/6145).
The effect is tested on my computer running Windows 10 21H2 and it solves the problem.
But i'm not sure if extra codes are needed to prevent affecting other functions.
Bug fix

libobs: Extra callback when removing scene

---

libobs/obs-audio.c

Render audio for all views
At the moment you can add views to obs via `obs_view_add` or `obs_view_add2`, but the audio for those views was not rendered.
Not rendered audio causes transitions not to finish and scenes to forever wait on audio to deactivate sources.
With the vertical plugin on windows

libobs: Render audio for all views

---

.github/scripts/.build.zsh
cmake/macos/helpers.cmake

This reverts commit 9f66c23825e41807c56f3a865d1c1462fa7ff73b.
This commit caused a crash in CEF on startup for many users. Let's just revert it asap for now and worry about the minor problem it was solving another time. Although according to https://github.com/obsproject/obs-studio/issues/9871#issuecomment-1815205387%3E that original issue may have been fixed in macOS anyways so I'm not worried about it.
Incidentally it also causes a problem I was having (but couldn't debug because of a lack of time) where the build folder needed cleaning before each rebuild or otherwise code signing was failing.
People report this crash on 30.0.1 and I don't like crashes.
In my setup, which was also effected by this crash (which I only noticed a few days ago), it no longer crashes.
- Bug fix …

Revert "cmake: Align Product Name and Bundle Name on macOS"

---

.github/workflows/publish.yaml

Fedora unfortunately provides unstable version of flatpak-builder, so we downgrade to the lowest version available for Fedora 39 which is functional for releases.
Fix the publish workflow for 30 hotfixes until a better solution is applied upstream (flatpak-github-action).
https://github.com/obsproject/obs-studio/actions/runs/7156924103/job/19487176553
https://github.com/tytan652/obs-studio/pull/19 proves that the downgrade works (dnf command output: https://github.com/tytan652/obs-studio/actions/runs/7159006283/job/19491780706?pr=19#step:4:31)

CI: Downgrade flatpak-builder to fix Flatpak publish

---

plugins/win-wasapi/win-wasapi.cpp

Makes `reroute_target` a weak source to avoid circular references preventing rerouting source from being destroyed.
Fixes issue reported in https://github.com/obsproject/obs-studio/pull/9524#issuecomment-1854338191
Locally.

win-wasapi: Make reroute target a weak reference

---

docs/sphinx/reference-properties.rst

Add undocumented property functions.
`obs_property_text_monospace` only having an effect on multiline
text properties were something I noticed by testing myself, so
correct me if I'm wrong.
Missing documentation for functions
Built and viewed locally. 

docs: Add property functions

---

docs/sphinx/reference-scenes.rst

Adds functions related to selected scene items and show/hide transitions of sceneitems.
I did see that obs.h says that the `...selected` and `...locked` functions are supposed
to be replaced, but `...locked` is documented.
I had not added docs for other related functions yet, since I have yet to
figure out what they do (like `obs_sceneitem_transition_load`, `obs_sceneitem_save`,
and `obs_sceneitem_force_update_transform`).
Missing documentation for some functions.
Built the docs and viewed the html file in the browser (with a webserver).

docs: Add missing sceneitem functions

---

plugins/win-capture/graphics-hook/d3d12-capture.cpp

Create ID3D11Resource dynamically to avoid reference inflation.
Fixes #9863
Don't want to prevent hooked applications from destroying the swap chain.
D3D12Fullscreen doesn't leak on exit after being hooked.
There's a small CPU hit and the churning a resource every frame is gross, but I guess that's better than interfering with applications.

graphics-hook: Fix DXGI ref leak for D3D12 capture

---

CONTRIBUTING.rst
build-aux/README.md

Add documentation about our formatting scripts and mention their existence in the CONTIRBUTING.rst.
The idea was in my head since a while and I finally took the time to do it.
Check the rendered files on my fork.

Add documentation about formatting

---

.github/actions/services-validator/action.yaml
.github/scripts/utils.py/check-services.py
.github/workflows/dispatch.yaml
.github/workflows/scheduled.yaml

Updates service check job to use geographically distributed servers provided by @tt2468 to increase accuracy of uptime checks.
Currently the check suffers from an increasing number of false-positives.
Ran on my fork: https://github.com/derrod/obs-studio/actions/runs/6992208282/job/19023560306

CI: Use distributed network for service uptime check

---

cmake/macos/compilerconfig.cmake

This PR fixes variable names in the error message.
When the Xcode version is too old, cmake shows an error below, whose version number information is missing.
```text
CMake Error at cmake/macos/compilerconfig.cmake:33 (message):
Your macOS SDK version () is too low.  The macOS SDK (Xcode ) is required
to build OBS.
Call Stack (most recent call first):
CMakeLists.txt:13 (include)
```
OS: macOS 14.2 (AArch64)
Xcode: 14.3.1
With this change, I confirmed the current version and required version is correctly displayed in the error message.
```text
CMake Error at cmake/macos/compilerconfig.cmake:33 (message):
Your macOS SDK version (13.3) is too low.  The macOS 14.2 SDK (Xcode 15.1)
is required to build OBS.
Call Stack (most recent call first):
CMakeLists.txt:13 (include)
```
- Bug fix …

cmake: Fix Xcode version error message

---

libobs/util/pipe-posix.c

Adds support for standard error output from subprocesses spawned on POSIX systems, specifically for `obs-ffmpeg-mux`.
Updates and supersedes https://github.com/obsproject/obs-studio/pull/3459.
`obs-ffmpeg-mux` provides error messages that are ignored by the main application right now because of lack of support for the standard error output stream. The original PR added the necessary code to handle all required input and output streams, including the standard error output.
Tested on macOS 14.2.1 with modified `obs-ffmpeg-mux` to fail early with an error message and checked that the return code as well as the error message was successfully displayed in the log.

libobs: Add  handling for obs-ffmpeg-mux standard error output on POSIX systems

---

buildspec.json
plugins/obs-ffmpeg/obs-nvenc.c

CI: Update deps to 2024-01-18 release
* deps.ffmpeg: Update zlib to 1.3
* deps.ffmpeg: Update SVT-AV1 to 1.8.0
* deps.ffmpeg: Update aom to 3.8.0
* deps.ffmpeg: Update libsrt to 1.5.3
* deps.ffmpeg: Update nv-codec-headers to 12.1.14.0
* deps.ffmpeg: Update AMF to 1.4.32
* deps.ffmpeg: Update FFmpeg to 6.1
* deps.macos: Update LuaJIT to 2.1 c525bcb902
* deps.macos: Update FreeType to 2.13.2
* deps.macos: Update Asio to 1.29.0
* deps.macos: Update nlohmann JSON to 3.11.3
* deps.macos: Update Sparkle to 2.5.2
* deps.macos: Update Syphon Framework to 5.0 39e31383ff
* deps.windows: Update FreeType to 2.13.2
* deps.windows: Update curl to 8.5.0
* deps.windows: Update LuaJIT to 2.1 c525bcb902
* deps.windows: Update Asio to 1.29.0
* deps.windows: Update nlohmann JSON to 3.11.3
* …

CI: Update deps to 2024-01-18 release

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Deleted a previously added service.
We do not support current connection addresses.
Users are confused by choosing StreamVi from the list.
This change does not affect the program code

rtmp-services: Remove StreamVi

---

plugins/obs-webrtc/whip-output.cpp

Log the libcurl-provided error message when libcurl fails.
Without the libcurl error message, it is very difficult to debug issues.
Against [Galene](https://galene.org)
Adds logging.

obs-webrtc: Improve error messages on HTTP failure

---

libobs-opengl/gl-egl-common.c
libobs-opengl/gl-subsystem.c
libobs/graphics/graphics-imports.c
libobs/graphics/graphics-internal.h
libobs/graphics/graphics.c
libobs/graphics/graphics.h
libobs/obs-encoder.h
libobs/obs-internal.h
libobs/obs-module.c
libobs/obs-video-gpu-encode.c
libobs/obs-video.c
libobs/obs.c

This enables the texture encoding path for opengl, my target is linux but I think we probably can/should support these on  mac/opengl so I did not restrict these to just windows+linux.
It is largely a rebase of some of commits in  #4974 that were specific just to enabling the texture_encode path on opengl.
It also adds a profiler root for the gpu encoder thread which is helpful when bringing up a new encoder.
I was looking into texture encoding on QSV and the existing work in #4974 worked well in my implementation so it seems worth pulling into its own PR.
Considering I am working with vaapi/mesa and  #4974 is nvenc, I think this should be a workable solution for all platforms. But it would be good to have more discussion on whether this is the best way to pass textures. 
At least one …

Linux texture encoding

---

build-aux/modules/50-libdatachannel.json
buildspec.json
plugins/obs-webrtc/whip-output.cpp

CI: Update deps to 2024-01-27 release
To avoid a compiler error, this commit also modifies obs-webrtc.
* deps.ffmpeg: Update libdatachannel to 0.20.1
* deps.macos: Remove Carla
* deps.macos: Add uthash to macOS deps
* deps.windows: Remove Carla
* deps.windows: Add uthash to Windows deps
Fixes #9800
Unblocks:
* #9307
* #9331
* #9567

CI: Update deps to 2024-01-27 release

---

UI/window-basic-settings.cpp

This fixes the screen reader audio issue in the hotfix settings window by setting an accessible name for each text box. This name is the name of the function to the left of the text box. The screen reader will still say "edit" as well but that is intentional so that users can know they are tabbed into a text box.
This fixes the screen reader audio issue mentioned in [#7768](https://github.com/obsproject/obs-studio/issues/7668).
Using Windows 10 and using Windows Screen Reader, tabbed into each hotkey edit text box and confirmed each one has the function name added to the audio output. This should not affect any other areas of code.

UI: Add accessible names to hotkey edit boxes

---

plugins/obs-webrtc/CMakeLists.txt
plugins/obs-webrtc/cmake/legacy.cmake

Since now we rely on a stable version, we can now set a minimum requirement for libdatachannel in CMake.
Error out, if an older version is used.
Replaced the number with 0.21 and CMake complained.

obs-webrtc: Require libdatachannel 0.20 or newer

---

.github/actions/flatpak-builder-lint/action.yaml
.github/actions/generate-docs/action.yaml
.github/actions/services-validator/action.yaml
.github/actions/steam-upload/action.yaml
.github/workflows/build-project.yaml
.github/workflows/check-format.yaml
.github/workflows/dispatch.yaml
.github/workflows/pr-pull.yaml
.github/workflows/publish.yaml
.github/workflows/push.yaml
.github/workflows/scheduled.yaml

GitHub Actions has deprecated Actions based on node16. The v4 actions are based on node20. Replace first-party v3 actions with their v4 counterparts.
See:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Want to resolve deprecation warnings on CI. Want to avoid CI failing when the node16 actions are disabled.
obs-plugintemplate, obs-deps, and obs-browser have both had successful CI runs. This repo's CI will also verify.

CI: Update first-party GitHub Actions from v3 to v4

---

.github/workflows/push.yaml

CI: Update upload-artifact from v3 to v4 for Sparkle appcast job
Implement the new merge sub-action from upload-artifact as a separate job that requires the Sparkle appcast creation job so that we still get a single combined artifact for the Sparkle appcast. This lets us update upload-artifact from v3 to v4.
GitHub Actions has deprecated Actions based on node16. The v4 actions are based on node20.
See:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Follow-up to fbbfbc68585b64c84e6bd4ab21389b07c6a68755 (#10161).
This can only be tested on tag, and I don't have my fork set up to do testing of the Sparkle processes. This looks correct to @derrod and I, but only a tag can tell if we got this right. …

CI: Update upload-artifact from v3 to v4 for Sparkle appcast job

---

build-aux/com.obsproject.Studio.json

The KDE Runtime 6.6 relies on the Freedesktop SDK 23.08 and so the branch of audio plugins should be updated too.
I forgot to do it while updating to 6.6.

build-aux: Update Flatpak audio plugins branch

---

plugins/mac-capture/mac-audio.c

Limit amount of audio buffers copied into libobs' audio pointer array to amount of channels supported by libobs.
OBS handles up to 8 channels of audio, which requires the CoreAudio input callback to omit/ignore any audio data from channels above that count and also report a maximum amount of 8 channels to match the speaker setup given to swresample by libobs.
This also means that for devices with more than 8 channels the only way to get that audio in OBS is to use the channel mapping feature and manually select those channels.
Tested on macOS 14.3.1 with BlackHole 16-ch (which provides the necessary channel count above 8) and also confirmed that audio sent on channels 15 and 16 of it are properly handled when using channel mapping.
Fixes …

mac-capture: Limit number of copied audio channels to libobs limits

---

UI/window-basic-main.cpp

Fixed Yes/No message box buttons not translated.
I refer to this commit.
https://github.com/obsproject/obs-studio/commit/522f5cdf3b733575c865ef43ad81f6f5fa5e92bc
| English |  Japanese |
| ------------- | ------------- |
| Are you sure you want to reset the UI? | UIをリセットしてもよろしいですか？ |
| Resetting the UI will hide additional docks. You will need to unhide these docks from the Docks menu if you want them to be visible.<br><br>Are you sure you want to reset the UI? | UIをリセットすると追加のドックは非表示になります。表示したい場合ドックメニューからこれらのドックを表示する必要があります。<br><br>UIをリセットしてもよろしいですか？ |
| Yes | はい |
| No | いいえ |
Before
After
I want to display translations.
Tested on my fork's CI.
Use Windows 11 22H3

UI: Fix problem with Yes/No message box buttons not translated

---

buildspec.json

CI: Update deps to 2024-02-20 release
* deps.ffmpeg: Force classic linker for AppleClang 15.0.0+
* CI: Update macOS jobs to use macOS 14 runners
* deps.ffmpeg: Enable runtime CPU detection for AOM to fix ARM64 crashes
* deps.ffmpeg: Update zlib to 1.3.1
* deps.ffmpeg: Update aom to 3.8.1
* deps.ffmpeg: Update mbedTLS to 3.4.1
* deps.qt: Update Qt6 to 6.6.2 for Windows
* deps.qt: Update Qt6 to 6.6.2 for macOS
* deps.qt: Restore native dialogs on macOS
Don't want crashes (e.g., AOM on macOS). Patch updates should be safe for us to adopt. Will look out for regressions during beta in case we need to revert.
Fixes #10226
I haven't tested OBS Studio yet with these. As this is a minimal deps update, this should be fine, but testing (particularly for AOM and code paths relying on …

CI: Update deps to 2024-02-20 release

---

.github/actions/flatpak-builder-lint/action.yaml
.github/workflows/build-project.yaml
.github/workflows/publish.yaml

TLDR: Replace use of appstream-glib tooling with flatpak-builder-lint + libappstream (unfortunately a fork)
Sorry, the not TLDR would end up in a rant.
But I can say that AppStream validation is also added to push/PR workflow to catch issues before release.
Make Flatpak release finally work…
CI on my fork and this PR

Update/fix Flatpak AppStream CI steps

---

buildspec.json

CI: Update deps to 2024-02-26 release
* deps.ffmpeg: Revert libsrt to 1.5.2 to avoid a crash
Fixes #10256
Tested on #10256. Tested locally on Windows 11 briefly.

CI: Update deps to 2024-02-26 release

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Add [SharePlay.tv](https://www.shareplay.tv) to rtmp services list.
Add support for "SharePlay.tv" in rtmp services.

rtmp-services: Add SharePlay.tv

---

UI/xdg-data/CMakeLists.txt
UI/xdg-data/com.obsproject.Studio.metainfo.xml.in
buildspec.json
deps/media-playback/media-playback/decode.c
libobs/media-io/media-remux.c
plugins/mac-capture/mac-audio.c
plugins/mac-capture/mac-sck-video-capture.m
plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
plugins/obs-ffmpeg/obs-ffmpeg-output.c
plugins/obs-qsv11/obs-qsv11-plugin-main.c
plugins/win-capture/get-graphics-offsets/cmake/32bit-build.cmake
plugins/win-capture/graphics-hook/cmake/32bit-build.cmake
plugins/win-capture/inject-helper/cmake/32bit-build.cmake
plugins/win-dshow/virtualcam-module/CMakeLists.txt
plugins/win-dshow/virtualcam-module/cmake/32bit-build.cmake

Cherry pick commits for release/30.1.
* https://github.com/obsproject/obs-studio/pull/10328
* https://github.com/obsproject/obs-studio/pull/10373
* https://github.com/obsproject/obs-studio/pull/10378
* https://github.com/obsproject/obs-studio/pull/10389
* https://github.com/obsproject/obs-studio/pull/10376
* https://github.com/obsproject/obs-studio/pull/10394
* https://github.com/obsproject/obs-studio/pull/10411
* https://github.com/obsproject/obs-studio/pull/10414
* https://github.com/obsproject/obs-studio/pull/10400
Want to finalize cherry-picks for release/30.1.
Tested in original PRs.

Cherry-pick commits for 30.1.1

---

docs/sphinx/reference-core.rst
docs/sphinx/reference-sources.rst

This adds documentation for the `obs_source_set_audio_active` and `obs_source_audio_active` functions and the `source_audio_activate`, `source_audio_deactivate`, `audio_activate` and `audio_deactivate` signals.
Those functions were undocumented.
documentation built and checked.

docs: Document the audio_active functions and signals

---

plugins/obs-text/gdiplus/obs-text.cpp

make alignment and vertical alignment work as expected
Made a new version to keep old gdi+ text sources the same.
Make the alignment options do what people expect it to do.
Fixes #3373
On windows 11 by creating the text sources you see in the screenshot above

obs-text: Fix alignment with extents

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Update "recommended" settings for "CHZZK" platform
Update "recommended" settings for "CHZZK" platform
Local Build & CI Buil

rtmp-services: Update "CHZZK" platform

---

UI/window-basic-main.cpp

This reverts commit 9488bb20b68ef2ca12a4f3eb040f56762c6f1447.
This is currently a frequent support issue as Windows Media Player, Movies & TV, and File Explorer all cannot seem to handle fMP4 files correctly. Windows Media Player and Movies & TV will play the files fine, but no duration is listed and the applications cannot seek the file. File Explorer will simply not list the file's length/duration (the field is shown as having no set value). This was somehow not caught during a year's worth of beta and RC builds. The world just wasn't ready for this. =(
For the record, we have reported these issues to Microsoft.
I haven't tested this, but as this is a revert it should be fine. We've used the previous code for a year prior.

Revert "UI: Change default format for release builds to fMP4/fMOV"

---

UI/window-basic-main.cpp
plugins/obs-ffmpeg/obs-nvenc.c

Cherry pick commits for release/30.1.
* https://github.com/obsproject/obs-studio/pull/10445
* https://github.com/obsproject/obs-studio/pull/10482
Want to fix a regression and finalize cherry-picks for release/30.1.
Tested in original PRs or in the original code.

Cherry-pick commits for 30.1.2

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

- Update RTMP services for Chaturbate
- Added more regions and update to new domain
- Tested locally

rtmp-services: Update Chaturbate

---

.github/actions/generate-docs/action.yaml

CI: Fix generate-docs action
Effectively revert 743117f08060d3d79f92740f46a60cbeed2e2699.
This action began failing recently. Updating the Dockerfile per the action's repo did not fix this. Unpinning Sphinx fixed it.
Sphinx was pinned to 5.1.1 on September 24, 2022 with commit 743117f08060d3d79f92740f46a60cbeed2e2699. The issue it linked to was subsequently fixed on October 3, 2022.
Tested on my fork.
https://github.com/RytoEX/obs-studio/actions/runs/8729371940/job/23951201269

CI: Fix generate-docs action

---

cmake/common/helpers_common.cmake

We no longer need this functionality in the new CMake paths. It is still available in the legacy CMake path.
Clean up the new CMake path a bit. We only kept this around temporarily to enable us to update obs-browser and obs-websocket.

cmake: Remove find_qt macro

---

libobs/obs-output.c

Calling `set_higher_ts` before offsets are known (i.e. all encoders produced usable output) pollutes `highest_video_ts` with timestamps that are out of range of actual timestamps (i.e. they're generally somewhere high above 0 until an offset for all streams is found, where they are then reset to 0 or slightly below 0 in the presence of b-frames)
`highest_video_ts` also needs to start below 0 for the same reason, i.e. even with timestamps being reset to close to 0, b-frames will cause initial dts to drop below 0, thus we need a value that should "always" be below any "real" timestamps observed
`highest_video_ts` tracking now only starts once all input streams are ready, and is computed based on all buffered packets at that point
video timestamps are based off of multitrack flv muxer ouputs …

libobs: Fix `highest_video_ts` tracking

---

.github/actions/compatibility-validator/action.yaml
.github/actions/services-validator/action.yaml

This is one of the few remaining actions in this repo that was still using node16. Updating will remove the associated warnings. Also, pin to the v0.5.0 commit.
Prevent eventual CI warnings.
https://github.com/yuzutech/annotations-action/compare/v0.4.0...v0.5.0
https://github.com/yuzutech/annotations-action/compare/3aa369f1f03cc794a39fe41608dfa004654974d0...0e061a6e3ac848299310b6429b60d67cafd4e7f8
Follow-up to:
* https://github.com/obsproject/obs-studio/pull/10175
It hasn't. If we wanted to test it, we'd probably have to test on a fork and intentionally mess up a file that would be annotated by this.

CI: Update yuzutech/annotations-action to v0.5.0

---

.github/workflows/push.yaml

CI: Fix Windows Signing action commit hash
The commit hash changed when I clicked the "Rebase and merge" button. Fix that.
It hasn't.

CI: Fix Windows Signing action commit hash

---

plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c

During high graphics thread pressure it can take a significant time to
acquire the graphics lock. This change releases the OpenGL texture after
rendering to avoid the 2nd lock after sending the frame to FFmpeg. This
improves 99%-tile/100%-tile and median encode in a near encoder overload
scenario, and modestly raises the ceiling before encoder overload in my
test scene.
Random dropped frames are no fun.
Master:
min=0 ms, median=4.29 ms, max=33.072 ms, 99th percentile=8.877 ms
min=0 ms, median=4.438 ms, max=77.157 ms, 99th percentile=9.853 ms
min=0 ms, median=4.527 ms, max=57.292 ms, 99th percentile=9.282 ms
This commit:
min=0.97 ms, median=3.009 ms, max=13.215 ms, 99th percentile=5.899 ms
min=1.181 ms, median=2.91 ms, max=9.854 ms, 99th percentile=5.56 ms
min=0.461 ms, median=3.013 ms, …

obs-ffmpeg: Release encode texture early

---

UI/window-basic-main.cpp
UI/window-basic-status-bar.cpp
UI/window-basic-status-bar.hpp

See commits and testing below.
Fix #10218.
Tested on Ubuntu 23.10 at 7ae66c72fd2395b49a44d460e5360994da0cfceb (top of tree at the time of writing).
https://github.com/obsproject/obs-studio/assets/31630318/c6e556c8-feca-4aeb-849a-25075877c16b
https://github.com/obsproject/obs-studio/assets/31630318/396efd61-d536-4cd1-b285-72361376b580

UI: Fix text stacking in paused indicator

---

plugins/linux-capture/data/locale/en-US.ini
plugins/linux-capture/xshm-input.c

Fix the naming
The source is wrongly named. Source: Warchamp7 
New wording is shown.

linux-capture: Rename Screen Capture as Display Capture

---

build-aux/com.obsproject.Studio.json

Disable a feature that might never be available in Flatpak since BlackMagic does not provide a stable link to download it as extra-data.
Since the Flatpak became part of the repo, nothing has changed on BlackMagic side.
DeckLink libraries are still not redistributable and without stable download link so even extra-data is not usable.
This makes enabling DeckLink feature in the Flatpak impossible without involving customization on the end-user side which is not how Flatpak is designed for.
It builds
- Flatpak cleanup

build-aux: Disable DeckLink in the Flatpak

---

buildspec.json

CI: Update deps to 2024-05-08 release
* deps.ffmpeg: Update libpng to 1.6.43
* deps.ffmpeg: Update opus to 1.5.2
* deps.ffmpeg: Update libvpx to v1.14.0
* deps.ffmpeg: Update SVT-AV1 to 2.0.0
* deps.ffmpeg: Update aom to 3.9.0
* deps.ffmpeg: Update libdatachannel to v0.21.0
* deps.ffmpeg: Update AMF to 1.4.33
* deps.ffmpeg: Update FFmpeg to 7.0
* deps.macos: Update LuaJIT to 2.1 5790d25397
* deps.macos: Update libpng to 1.6.43
* deps.macos: Update Asio to 1.30.2
* deps.macos: Replace ntv2 with libajantv2
* deps.macos: Update Sparkle to 2.6.2
* deps.windows: Update curl to 8.7.1
* deps.windows: Update LuaJIT to 2.1 5790d25397
* deps.windows: Update Asio to 1.30.2
* deps.windows: Update Zstandard to 1.5.6
* deps.windows: Update VPL to v2.10.2
* deps.windows: Replace ntv2 …

CI: Update deps to 2024-05-08 release

---

UI/data/themes/System.obt

In 7931f2acb8688326375775dcef9c289f64951ac4 (https://github.com/obsproject/obs-studio/pull/9990) the classes have been removed in favor of properties, but this styling change appears to have been reverted by accident, likely by the theming overhaul.
Don't want broken styling.
macOS 14.4.1
Before/After:
<p>
</p>

UI: Fix visibility and lock checkbox styling on system theme

---

UI/window-basic-main.cpp
UI/window-basic-main.hpp

The majority of this method got removed in a prior commit [1]. Let's inline the rest.
[1] 8dcfae9a390763645d354700f36caef6b8f482c7 (https://github.com/obsproject/obs-studio/pull/10602)
Noted on the PR that I would clean this up later (https://github.com/obsproject/obs-studio/pull/10602#discussion_r1591238475).
macOS 14.4.1
Ran and changed the theme, breakpointed the api call.

UI: Inline OBSBasic::ThemeChanged()

---

docs/sphinx/reference-sources.rst

Add return type of obs_source_set_audio_active obs_source_audio_active
Building docs yields a warning for these functions
Built and viewed locally

docs: Add return type of obs_source_audio_active

---

docs/sphinx/reference-core.rst
docs/sphinx/reference-encoders.rst
docs/sphinx/reference-frontend-api.rst
docs/sphinx/reference-libobs-util-deque.rst
docs/sphinx/reference-modules.rst
docs/sphinx/reference-properties.rst
docs/sphinx/reference-settings.rst
docs/sphinx/reference-sources.rst

Makes it easier to find out if a function is already in a certain release.
Built and viewed locally

docs: Add versionadded for 30.x functions

---

UI/multitrack-video-output.cpp

Remove redundant assignments
Detected by PVS-Studio.
Seems like an easy cleanup.
Tested on Windows 11.

UI: Remove redundant assignments

---

UI/multitrack-video-output.cpp

Fixes query parameters being incorrectly concatenated with the stream key if it already contains query paramters itself (e.g. `?bandwidthtest=true`).
This should work and it doesn't.
Verified final stream key is now correctly assembled.

UI: Fix multitrack stream key query parameter concatenation

---

.github/workflows/push.yaml

CI: Fix incorrect filenames in release creation
Follow-up to fb4d65875e27ed58ce545875b2591c46fc324d12 (#9787).
Want CI to work when creating releases.
It hasn't.

CI: Fix incorrect filenames in release creation

---

UI/data/themes/Yami.obt
UI/forms/OBSBasicSettings.ui
UI/window-basic-settings.cpp

Many of the tabs in Settings right now have margins or sizings that do not match, or have widget heirarchies that vary between them. This PR makes adjustments to many containers and widgets in Settings to make their margins and appearance more consistent.
Want settings to look better and cleaner.
Checked through all tabs of Settings, including nested stacked pages.

UI: Clean up Settings widget structure and styling

---

.github/workflows/publish.yaml

CI: Add updateChannel to check-tag in Publish workflow
This was missing even though we try to set it later.
Was trying to figure out an issue with the release notes creation in the windows-patches action and came across this. The windows-patches action defaults its `channel` input to "stable" if not set, and this was not set in our recent Publish runs.
https://github.com/obsproject/obs-studio/actions/runs/9486945548/job/26142437314#step:3:5
vs. 
https://github.com/obsproject/obs-studio/actions/runs/9491426245/job/26156825712#step:3:8
It hasn't.

CI: Add updateChannel to check-tag in Publish workflow

---

UI/forms/OBSBasicSettings.ui

UI: Set Multitrack Video maximum bitrate limit default to 0/Auto
There were some reports that the default value of 8000 was confusing because it implies that the automaticaly selected and used value is 8000 Kbps. Set it to 0 which should hopefully make it more obvious that OBS is not sending 0 Kbps.
Note that this also requires lowering the _minimum_ permissible value of the field from 500 to 0.
Want the UI to be less confusing.

UI: Set Multitrack Video maximum bitrate limit default to 0/Auto

---

libobs/CMakeLists.txt

Adds the `obs-config.h` header to the non-public header list to make it findable in IDEs.
It's already listed as a public header, but to make it appear in IDEs it needs to be in the "normal" header list as well.
(Do not confuse this with `obsconfig.h`. `obsconfig.h` is a file generated by `obsconfig.h.in`, but `obs-config.h` is a normal header file).
Noticed this file missing from the list when trying to check some things that were defined in there.
Would like it to show up in IDEs.
macOS 15.0 Beta 1, Xcode 16 Beta 1
Reran cmake, `obs-config.h` now shows up under headers.

cmake: Add obs-config.h to libobs headers

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Add [Dolby Millicast](https://dolby.io) to RTMP Services list.
Add support for "Dolby Millicast" in RTMP Services.

rtmp-services: Add Dolby Millicast

---

.github/actions/flatpak-builder-lint/action.yaml

`jq` does not return zero if the array does not exist but an empty output
Stop the action tab becoming more red
Here (I will temporarily push a commit to trigger errors/warnings )

CI: Fix flatpak-builder-lint action

---

libobs/graphics/libnsgif/libnsgif.c

libobs/graphics: Prevent heap overflow in libnsgif
See upstream commit:
https://source.netsurf-browser.org/libnsgif.git/commit/?id=a268d2c15252ac58c19f1b19771822c66bcf73b2
Built and ran on Windows 11. Loaded an animated GIF.

libobs/graphics: Prevent heap overflow in libnsgif

---

plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Adds the game Zenless Zone Zero to the compatibility list for win-capture.
People being able to probably game capture the game.
Zenless Zone Zero runs by default with administrative privileges which requires OBS Studio to run with administrative privileges as well for game capture to work.
Selected the game in the game capture source and the warning message showed up like it should.

win-capture: Add Zenless Zone Zero to compatibility list

---

plugins/obs-nvenc/nvenc-opts-parser.c

Improves logging for custom options by ensuring the format specifiers are correct and the type/bit length is logged as well.
Want logging to be more clear.
Changed a few options, ensured output remains correct.

obs-nvenc: Improve logging for custom options

---

libobs/obs-encoder.c

Adds a temporary reference to the stopping encoder to ensure it's not being destroyed by any releases during the stopping process.
Fixes a potential deadlock when closing OBS while the output is still active.
The UI releases its reference to the encoder before the output stops, leaving the GPU encode thread as the last thing to hold a reference. This then results in a deadlock when trying to stop the encoder:
- `end_data_capture_thread()`
+ `stop_video_encoders()`
+ `obs_encoder_stop()` -> locks `encoder->init_mutex`
+ `remove_connection()`
+ `stop_gpu_encode()`
+ `stop_gpu_encoding_thread()` -> waits on `pthread_join()` on the `gpu_encode_thread()`
- `gpu_encode_thread()`
+ `obs_encoder_release()` -> releases last reference
+ `obs_encoder_destroy()` -> attempts to lock …

libobs: Ensure encoder is not destroyed prematurely

---

UI/adv-audio-control.cpp
UI/adv-audio-control.hpp
UI/window-basic-adv-audio.cpp
UI/window-basic-adv-audio.hpp

Simplifies code by using a vector instead of individual signals.
Code cleanup
Made sure the advanced audio dialog still worked as expected.

UI: Use signal vector for advanced audio dialog

---

UI/win-update/updater/http.cpp
UI/win-update/updater/updater.cpp

The legacy type may not work on some setups, use new one on 8.1+  instead.
Updater does not go through my system proxy.
The legacy type seems do not check system proxy settings throughly.
I haven't test compile the changes,but should not break since it's a rather simple change.
Tweak

win-update: Use correct winhttp proxy type

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Unfortunately, as Match Group has decided discontinue the live streaming business, we have decided to terminate Hakuna Live as well, leading me to submit this PR.
See https://techcrunch.com/2024/07/31/match-group-ends-live-streaming-service-layoffs/

rtmp-services: Remove Hakuna Live RTMP service

---

plugins/obs-ffmpeg/obs-ffmpeg-url.h

Removes a declaration of a class `Logger`, which is never defined nor used.
The declaration was introduced at the commit e7d097cab8, which is the first commit of the file `plugins/obs-ffmpeg/obs-ffmpeg-url.h`. At that commit, the class was never defined nor used.
OS: Fedora 39
Confirmed the build was succeeded.

obs-ffmpeg: Remove unexisting class name declaration

---

plugins/win-dshow/CMakeLists.txt

The code prior to this change would never add virtualcam.c to the win-dshow target, which resulted in the virtualcam_output not being registered and thus Virtual Camera not working.
Want the Virtual Camera to work when correctly configured.

win-dshow: Fix CMake preventing Virtual Camera from working

---

shared/properties-view/CMakeLists.txt

As per https://github.com/obsproject/obs-studio/discussions/11170 we only support Qt 6.4.2 and higher, and have recently removed other 6.2 workarounds. As such, we can drop this cmake code.
Saw this, and it's not needed.
Hasn't. Don't think it's applicable.

shared/properties-view: Remove Qt 6.2 cmake code

---

.github/workflows/build-project.yaml
.github/workflows/publish.yaml

Update flatpak-builder and flat-manager actions.
This should remove some warnings on CI about deprecated GitHub Actions versions.
Note that the default cache key format will change from `flatpak-builder-${this._manifestHash}-${this.arch}` to `flatpak-builder-${this.arch}-${this._manifestHash}`. I think we manually specify cache keys, so I'm not sure this affects us, but we may consider adopting their new default pattern at some point.
https://github.com/flathub-infra/flatpak-github-actions/compare/23796715b3dfa4c86ddf50cf29c3cc8b3c82dca8...e5fa5a8fe51d76f770ad9d240e4ad5898b1c6a53
It hasn't.

CI: Update flatpak-builder and flat-manager actions

---

cmake/linux/helpers.cmake

As it was discussed, a strict ABI break is not done on Windows and macOS.
This PR aligns Linux to do the same as other platforms.
Freeze SOVERSION to 30, this number is to be incremented when a clean break is wanted.
Alignement about API/ABI break.
Build and only SOVERSION 30 shared libraries were built.
- Bug fix ? (non-breaking change which fixes an issue)

cmake: Avoid breaking ABI through major version bump on Linux

---

.github/workflows/scheduled.yaml

Fix broken condition that never caused the following upload action to be triggered.
Patch as per https://discord.com/channels/348973006581923840/697237531426685029/1281363574962524181. Utilizes the condition that all other workflows use currently.
Since https://github.com/obsproject/obs-studio/pull/10391 no more files got uploaded to Crowdin automatically.
Let's see.

CI: Fix condition for changed files in upload locales action

---

plugins/obs-qsv11/QSV_Encoder_Internal.h

Do more initialization.
We check that mids is a nullptr which may not be the case if this remains uninitialized. Earlier attempt to fix this assumed we faulted on the response itself being null but this wasnt the case.
fixes #11221
Consulted the wisdom of the ancients (godbolt).

obs-qsv11: Initialize allocator response

---

libobs/obs-output-delay.c

Removes the function definition of `obs_output_signal_delay`.
The function is not declared in any header file, and is never called or documented.
OS: Fedora 39
Checked build flow passed.
Also [searched it on GitHub](https://github.com/search?q=%22obs_output_signal_delay%22&type=code) and I didn't find any usage of the API.

libobs: Remove obs_output_signal_delay

---

docs/sphinx/reference-frontend-api.rst

Add obs_frontend_get_user_config to docs
Keep documentation updated with code
-

docs: Add obs_frontend_get_user_config

---

buildspec.json

CI: Update deps to 2024-09-12 release
* deps.qt: Revert Qt from 6.7.2 to 6.6.3 on macOS
* deps.qt: Revert Qt from 6.7.2 to 6.6.3 on Windows
Avoid two known QTBUGs on Windows 11:
* https://bugreports.qt.io/browse/QTBUG-128517
* https://bugreports.qt.io/browse/QTBUG-128518
* https://github.com/obsproject/obs-deps/pull/264
We were previously on Qt 6.6.3, so this version has already been tested.

CI: Update deps to 2024-09-12 release

---

libobs/obs-cocoa.m

Removes an unused method.
An equivalent method called `isInBundle()` exists in the UI which is still used.
Stumbled across this when doing something else.
macOS 15.
Still compiles.

libobs: Remove unused is_in_bundle() method

---

libobs/util/platform-nix.c

Closes #9968
Avoid creating the screensaver inhibitor thread when another method has been applied.
Make inhibition unavailable in a Flatpak if portal is not available.
1. If the Portal or the D-Bus method is in place, adding the xdg-screensaver thread is overkill. It should be just a fallback.
2. Flatpak only support the Portal method, so spamming xdg-screensaver will do nothing

libobs/util: Improve inhibit functions on Linux

---

UI/obs-app.cpp
UI/window-basic-interaction.cpp
UI/window-basic-main.cpp
UI/window-basic-settings.cpp

“Automatically check for updates on startup” is unchecked. (Settings > General)
“Enable Browser Source Hardware Acceleration” is unchecked. (Settings > Advanced)
The number of log files is low. (Usually 10, but now 2.)
The number of profiler_data files is low. (Usually 10, but now 1.)
*This occurs when there is no OBS config file. (when OBS is started for the first time)
I'm not sure if this change is correct, so please close if it's wrong.
I want to solve a problem.
I checked with the CI build.
I’m not sure if the code changes are correct.

UI: Fix settings mismatch

---

plugins/obs-nvenc/data/locale/en-US.ini

The translation string does not exist in en-US.ini.
In version 30.2.3, this string has been translated.
I want to display translations.
I tested by changing the local translation file. (ja-JP.ini)

obs-nvenc: Add missing locale text

---

plugins/obs-qsv11/CMakeLists.txt
plugins/obs-qsv11/obs-qsv-test/CMakeLists.txt

Since we no longer support Ubuntu 22.04, we can bump the minimum VPL version to 2.9 which is available in Ubuntu 24.04 packages.
Want the minimum VPL version to be clearly indicated.
Tested locally on Windows 11 with obs-deps (VPL 2.12).

obs-qsv11: Update minimum VPL version to 2.9

---

UI/data/themes/Yami_Rachni.ovt

The control button pressed color does not change in the Rachni theme.
This issue does not occur in version 30.1.2.
Use the code in `Rachni.qss` (version 30.1.2)
I'm not sure if this change is correct, so please close if it's wrong.
Before
https://github.com/user-attachments/assets/e8738c40-7a42-4e52-82af-6c54b02446f4
After
https://github.com/user-attachments/assets/c2101d0d-0442-4f87-94eb-bf8fb1c12f8a
A user reported this bug on X (formerly Twitter).
I want to solve the problem.
I changed the Yami_Rachni.ovt file.
I’m not sure if the code changes are correct.

UI/themes: Fix control button pressed color in rachni theme

---

UI/window-basic-main-profiles.cpp

Fix the problem with YouTube Live Control Panel not being created when switching profiles.
*This issue only occurs when using stream keys.
I'm not sure if this change is correct, so please close if it's wrong.
*This does not occur in version 30.2.3.
Reference source. https://github.com/obsproject/obs-studio/commit/eb89f7c3abc4956b3c0814e5125e02f05e9763e3 (lines 804-807)
Does not occur until master https://github.com/obsproject/obs-studio/commit/26d275223ae7b39baf08011992e836ee0b0678eb (confirmed by nightly builds).
Before (Using version 31.0 beta3)
https://github.com/user-attachments/assets/7a8f3d91-a10d-4e75-b697-c6520f44df3e
After
https://github.com/user-attachments/assets/38df64a1-cccb-4479-9d2a-5dd111445169
I would like to solve the problem.
My local build. (Set YOUTUBE_CLIENTID , …

UI: Create YouTube Dock when switching profile

---

plugins/obs-filters/noise-suppress-filter.c

Move nvafx migration to queued task
Fix deadlock in migration:
main thread locks `sources_mutex` in `obs_load_sources` followed by `source->filter_mutex` in `obs_source_filter_add`
while an audio thread locks `source->filter_mutex ` in `obs_source_output_audio` and `sources_mutex` in `obs_source_destroy`
In the new situation the migration does not lock both mutexes at the same time
On windows 11 by migrating noise suppression

obs-filters: Move nvafx migration to queued task

---

UI/window-basic-main-scene-collections.cpp

Adds code to actively remove pre-existing backups of scene collections when a new scene collection with the same name is created.
The new Scene Collection code uses the lazy creation behaviour of `OBSBasic::Load`, which itself uses `obs_data_create_from_json_file_safe`.
The internal implementation will create a new scene collection with the contents of an existing backup file with the same name however, thus users would end up with a nominally "new" scene collection that contains contents of an old backup.
This update will remove any existing backup file colliding with the name of the new, duplicated, or renamed, scene collection and remove it before activating it (and having `OBSBasic::Load` create a new one).
Tested by deleting a scene collection with an existing backup file, checking …

UI: Fix collision of existing backup files for new scene collections

---

plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Adds the game Marvel Rivals to the compatibility list for win-capture.
People being able to probably game capture the game.
Marvel Rivals runs by default with administrative privileges which requires OBS Studio to run with administrative privileges as well for game capture to work.
Selected the game in the game capture source and the warning message showed up like it should.

win-capture: Add Marvel Rivals to compatibility list

---

plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Add the game "The Bazaar" to the compatibility list. Known issue, confirmed the issue and the fix
Want to make it easier for users to be aware of and handle capturing the game.
Just dropped my modified JSON files into my install.

win-capture: Add The Bazaar to compatibility list

---

libobs/util/platform-nix-portal.c

Check for a property of the inhibit portal rather than just the portal D-Bus name that does not indicate if the specific portal is available.
The actual check is not enough accurate since #10751 only enables one method.
The inhibit portal is correctly detected with the new method.

libobs/util: Improve inhibit portal detection on Linux

---

.github/workflows/analyze-project.yaml

Per discussion on #11529, temporarily disable PVS-Studio for now.
Want nightly runs to stop failing. Want some breathing room to discuss whether to keep this job/workflow or not.
It hasn't.

CI: Disable PVS-Studio job

---

.github/workflows/publish.yaml

It is not needed to publish on a Flatpak repo and the push workflow already generates a bundle.
Github changed behavior about artifacts from overriding to rejecting same-name artifacts.

CI: Disable Flatpak bundling on publish

---

libobs/cmake/os-linux.cmake

We directly depend on libx11 for various operations in obs-nix-x11.c, not just xcb. So be sure to link it in too.
fixes #11667
It compiles.

libobs: Fix underlinking by adding libx11

---

libobs/obs-config.h

Update libobs version 31.0.1.
Update the version so we can release 31.0.1.
It hasn't.
- Version Bump

libobs: Update version to 31.0.1

---

.github/actions/setup-macos-codesigning/action.yaml

Fix a typo in setup-macos-codesigning action.
It bothers me.
It hasn't been tested, but this should be a straightforward change.

CI: Fix typo in setup-macos-codesigning action

---

frontend/cmake/feature-sparkle.cmake
frontend/cmake/os-macos.cmake
libobs/cmake/os-macos.cmake
plugins/mac-avcapture/legacy/CMakeLists.txt

COMPILE_OPTIONS was added and superseded COMPILE_FLAGS in CMake 3.11.
https://cmake.org/cmake/help/v3.30/prop_sf/COMPILE_FLAGS.html
https://cmake.org/cmake/help/v3.30/prop_sf/COMPILE_OPTIONS.html
Was browsing CMake documentation and saw the superseded note.
It hasn't. It seems that these changes are only for macOS paths, so I would appreciate confirmation from someone who devs regularly on macOS (@jcm93 , @gxalpha , or @PatTheMav ) that this works the same as before.

cmake: Replace COMPILE_FLAGS with COMPILE_OPTIONS

---

libobs/obs-video.c
plugins/win-capture/dc-capture.c
plugins/win-wasapi/enum-wasapi.hpp

Fixes a typo in the macro `WIN32_LEAN_AND_MEAN` (wrong version: `WIN32_MEAN_AND_LEAN`) to prevent unnecessary headers from being included by <windows.h>. This reduces compilation time and may prevent future bugs due to unexpected includes. I fixed all files in which the typo occured. The other occurences of the macro are fine.
The macro `WIN32_LEAN_AND_MEAN` prevents `<windows.h>` from including a whole bunch of headers that are not used by OBS. Due to the typo, the macro had no effect and the headers were included. This didn't cause any bugs, but it wasted (a small amount of) compilation time. More importantly, these hidden includes could theoretically cause trouble in the future if an unexpected conflict with one of the included headers occurs. The macro is used inconsistently in the …

libobs,win-capture,win-wasapi: Fix typo in macro WIN32_LEAN_AND_MEAN

---

plugins/mac-avcapture/plugin-main.m

Changes the mac-avcapture source destruction to occur synchronously on the source's serial dispatch queue, rather than on the current thread (typically a dedicated deferred destruction task thread). 
On unclean shutdown, we can end up in a state where a source is present in the scene collection's list of sources, but where that source is not present in any scenes.
On startup, this results in the source being created while iterating through the source list initialization routine, and then immediately queued for destruction when separate logic realizes that the source is not present in any scenes.
Ordinarily, this would proceed fine, but the mac-avcapture source uses a dedicated dispatch queue to perform the expensive parts of initialization asynchronously. This means that initialization …

mac-avcapture: Prevent race condition in source init/deinit

---

libobs/obs-config.h

Update libobs version 31.0.2.
Update the version so we can release 31.0.2.
It hasn't.
- Version Bump

libobs: Update version to 31.0.2

---

buildspec.json

CI: Update deps to 2025-03-06 release
Notable Changes:
* deps.ffmpeg: Update AMF to 1.4.36
* deps.windows: Update VPL to v2.14.0
* deps.ffmpeg: Update libpng to 1.6.47
* deps.ffmpeg: Update SVT-AV1 to 2.3.0
* deps.ffmpeg: Update AOM to 3.12.0
* deps.ffmpeg: Update nv-codec-headers to n13.0.19.0
* deps.ffmpeg: Update FFmpeg to 7.1
* deps.macos: Update LuaJIT to v2.1 a4f56a459
* deps.macos: Update libpng to 1.6.47
* deps.macos: Update Asio to 1.32.0
* deps.macos: Update Syphon to 5.0 b834acdb9
* deps.macos: Update VLC headers to 3.0.21
* deps.qt: Update Qt to 6.8.2 for macOS
* deps.qt: Update Qt to 6.8.2 for Windows
* deps.windows: Update curl to 8.12.1
* deps.windows: Update LuaJIT to v2.1 a4f56a459
* deps.windows: Update Asio to 1.32.0
* deps.windows: Update Zstandard to 1.5.7
* …

CI: Update deps to 2025-03-06 release

---

plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Adds FragPunk to compatibility list for win-capture
Game capture will not work otherwise
I guess it hasn't really, but seems fine.

win-capture: Add FragPunk to compatibility list

---

plugins/obs-qsv11/QSV_Encoder_Internal.cpp

Adding Battlemage for CBR fix.
Needs VPL 2.13 to build: https://github.com/obsproject/obs-deps/pull/274
Adding CBR fix for future Intel platform.
Tested on Intel Battlemage platform

obs-qsv11: Fix CBR Spike for Battlemage

---

buildspec.json

Use a rebuilt CEF of the same version (6533) that disables use_partition_alloc_as_malloc and enable_backup_ref_ptr_support to avoid memory-related crashes on macOS.
Fixes #11621
Tested by @jcm93 and @PatTheMav . More testing appreciated.

CI: Use rebuilt CEF to avoid memory allocation crashes on macOS

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Added RTMP service for [VRCDN](https://vrcdn.live).
Modified the `services.json` to add the geo-balanced, primary ingest endpoint for VRCDN and information on maximum bitrates and suggested keyframe Interval.
We did this due to confusion from our userbase on how to stream to our service, and to also simplify the application of the service limits.
- Tested on local OBS version on Windows 11 Pro 23H2.
- Started a stream and validated the connection.
- Validated that the stream propagated through the network.

rtmp-services: Add "VRCDN - Live"

---

UI/window-basic-main.cpp
buildspec.json
libobs/obs-output.c
plugins/mac-avcapture/plugin-main.m
plugins/nv-filters/nvidia-videofx-filter.c
plugins/obs-nvenc/nvenc-cuda.c
plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json
plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Cherry-picks:
* https://github.com/obsproject/obs-studio/pull/11806
* https://github.com/obsproject/obs-studio/pull/11947
* https://github.com/obsproject/obs-studio/pull/11948
* https://github.com/obsproject/obs-studio/pull/11925
* https://github.com/obsproject/obs-studio/pull/11926
* https://github.com/obsproject/obs-studio/pull/11924
* https://github.com/obsproject/obs-studio/pull/11952
* https://github.com/obsproject/obs-studio/pull/11977
* https://github.com/obsproject/obs-studio/pull/11972
* https://github.com/obsproject/obs-studio/pull/11949
* https://github.com/obsproject/obs-studio/pull/11835
* https://github.com/obsproject/obs-studio/pull/11591
* https://github.com/obsproject/obs-studio/pull/11897
* https://github.com/obsproject/obs-studio/pull/11988
Cherry pick changes to …

Cherry-picks for release/31.0 branch

---

libobs/obs-config.h

Update libobs version 31.0.3.
Update the version so we can release 31.0.3.
It hasn't.
- Version Bump

libobs: Update version to 31.0.3

---

.github/workflows/build-project.yaml
.github/workflows/publish.yaml

I discovered while investigating a separate caching issue that the read command was not assigning ref correctly. This is inconsequential since we do not use that value, but it led me to look up the documentation for the GitHub CLI extension used here, gh-actions-cache.
The GitHub CLI extension gh-actions-cache is deprecated as of October 2024. The recommendation is to use the offical gh cache command. That command produces slightly different output, so adjust the read command accordingly.
Want to remove outdated and deprecated gh CLI usage.
Tested on my fork to validate that the values are read correctly.
https://github.com/RytoEX/obs-studio/actions/runs/13999957456/job/39203983096#step:4:31
There is no noticeable time difference.
- Code cleanup (non-breaking change which makes code …

CI: Clean up Flatpak cache detection

---

.github/actions/windows-patches/action.yaml
.github/actions/windows-signing/action.yaml

Use latest bouf v.0.6.5, as the latest update has not been included yet.
Mainly to make the Windows Start Menu cleanup I contributed there used.

CI: Update bouf to v0.6.5

---

.github/workflows/build-project.yaml
.github/workflows/publish.yaml

Look motivation.
The fork has been merge with upstream.
https://github.com/flathub-infra/flatpak-github-actions/issues/17
CI will tell

CI: Use Flatpak action upstream

---

plugins/rtmp-services/data/package.json
plugins/rtmp-services/data/services.json

Add Enhanced Streaming support for Dolby Millicast
Add Enhanced Streaming support for Dolby Millicast

rtmp-services: Add Enhanced Streaming support for Dolby Millicast

---

docs/sphinx/reference-core.rst

Should be obs_set_video_levels
On pull request #6312, the function `obs_set_levels` was added but in the documentation it was
submitted as `obs_set_video_sdr_white_level`
To have correct documentation.

docs: Fix function name obs_set_video_sdr_white_level

---

CONTRIBUTING.rst

change mac0S to macOS
fix typo in our documentation

CONTRIBUTING.rst: Fix macOS typo

---

plugins/linux-v4l2/v4l2-input.c

This patch modifies the Linux v4l2-input plugin to improve the handling of H264 and MJPEG bulk mode streams. When encountering decoding errors, instead of terminating the capture thread, OBS will now skip the corrupted frame and continue capturing.
Receiving H264 or MJPEG video streams from UVC devices in bulk mode under Linux would frequently cause OBS to stop displaying video due to decoding errors. Skipping corrupted frames improves playback stability without needing to restart the capture.
Tested with multiple UVC devices outputting H264 and MJPEG over bulk mode under Ubuntu 22.04. Confirmed that when corrupted frames occur, OBS logs the error but continues playback without interruption. Regular (non-bulk) streams and other input formats remain unaffected.
- Bug fix (non-breaking …

linux-v4l2: Skip corrupted H264/MJPEG frames during capture

---

frontend/components/SourceTreeItem.cpp

Fix visibility and lock checkbox in System theme.
This does not occur in version 31.0.3.
Please close the PR if this change is wrong.
Before
After
I want to resolve this issue.
I’m not sure how many people are using the system theme, but I’ll fix it (even though I don’t use it myself).
I changed the System.obt file.
I’m not sure if the code changes are correct.
You can test by changing the Theme in user.ini to `Theme=com.obsproject.System`.

frontend: Fix visibility and lock checkbox in System theme

---

frontend/data/locale/en-US.ini
frontend/forms/OBSBasicSettings.ui

Translations were not added in this commit: https://github.com/obsproject/obs-studio/commit/c0c77071b5977aff65421c770658ae8e5d44fc89
I don't think 'Classic', 'Compact', 'Normal', and 'Comfortable' need translation, but I added them just in case.
Please close the PR if this change is wrong.
I want to display translations.
Tested on Windows 11 24H2 using a local build.

frontend: Add missing translations

---

frontend/data/themes/Yami_Rachni.ovt

The Density button pressed color does not change in the Rachni theme.
The issue was addressed by swapping `primary` and `primary_light`.
Please close the PR if this change is wrong.
Before ( border-width: 2px / The position is slightly off.)
After ( border-width: 1px )
Before (Density button)
After (Density button)
I want to resolve this issue.
I changed the Yami_Rachni.ovt file.
I’m not sure if the code changes are correct.

frontend: Fix button pressed color in Rachni theme

---

frontend/data/themes/Yami.obt

frontend: Fix spacing of group expand button

---

buildspec.json

CI: Update deps to 2025-05-23 release
* deps.ffmpeg: Update AMF to 1.4.36
* deps.ffmpeg: Revert nv-codec-headers to n12.2.72.0
* deps.ffmpeg: Update FFmpeg to 7.1.1
* deps.qt: Update Qt to 6.8.3 for macOS
* deps.qt: Update Qt to 6.8.3 for Windows
Wanted to downgrade the nv-codec headers to avoid a minimum driver version bump and we aren't using the features yet.
The other updates are patch updates and seemed safe in my limited testing.

CI: Update deps to 2025-05-23 release

---

libobs/obs-config.h

libobs: Update version to 31.1.0
Required update.
It hasn't.
- Version Bump

libobs: Update version to 31.1.0

---

frontend/widgets/OBSBasic_Browser.cpp

At a glance, the GenId function looks like it can only return a 16-character hexadecimal string with all characters being [0-9A-F]. However, it seems that it can rarely return a 16-character string that has one or two space characters at the beginning due to the value of id, from which the final string is derived, being too low (lower than 1152921504606846976 or 0x1000000000000000) and the printf format specifier having a width of 16. This results in a string of less than 16 characters that is padded with blank spaces. The end result is a cookie directory that has leading spaces in its name, which can cause various issues, such as breaking syncing on OneDrive.
If we set the format specifier to pad with zeroes instead of spaces, the resulting hexadecimal value is always 16 characters long …

frontend: Ensure cookie ID is always 16 hexadecimal characters

---

buildspec.json

Use CEF ubuntu-aarch64 build with the wrapper built.
The v3 build did not have the wrapper built. This fixes that.
Fixes #12134
I have not tested this.

CI: Fix CEF ubuntu-aarch64 build

---

shared/obs-hook-config/graphics-hook-ver.h

shared/obs-hook-config: Update graphics hook to 1.8.7
Please close this PR if the change is incorrect.
I recalled the following comment from [#11583](https://github.com/obsproject/obs-studio/pull/11583#issuecomment-2825536569)
> RytoEX:
> We will probably have to increment the graphics-hook version before the next release.
I checked the graphics-hook version and found it had not been updated.
I confirmed that the graphics-hook file version is updated in the local build.
- Version Bump

shared/obs-hook-config: Update graphics hook to 1.8.7

---

frontend/data/themes/Yami.obt
frontend/data/themes/Yami_Classic.ovt
frontend/settings/OBSBasicSettings_Appearance.cpp
frontend/widgets/OBSBasic_Preview.cpp

Various fixes for issues in 31.1 related to appearance and theme changes.
- Updated volume mixer font size in the Classic theme variant to respect font size setting better
- Updated context menu for the disabled preview to match the new projector menu format
- Fixed the settings window Apply button always getting enabled when font size or density were not default values
- Fixed the padding of the top menu bar items
Appearance problems bad
👁

frontend: Fix theme and appearance issues

---

frontend/forms/OBSPermissions.ui

horizontalLayout_5 was already used further up.
@PatTheMav found that `uic` complained about this.
macOS 15.5
`uic` no longer complains.

frontend/forms: Fix duplicate UI element name warning

---

.github/actions/windows-patches/action.yaml
.github/workflows/push.yaml

Explicitly label the Windows x64 artifacts and assets as such to disambiguate them from the Windows arm64 artifacts and assets.
Subsequently, make the windows-patches action able to take an architecture argument which defaults to x64. This will help enable later usage for Windows arm64.
Lastly, rearrange some of the Windows lines in push.yaml to have a consistent order.
Follow-up from:
* #12220
* #12226
It hasn't.

CI: Explicitly label Windows artifact and asset architecture

---

frontend/OBSApp_Themes.cpp
frontend/data/themes/Yami.obt

Enables the font size setting on macOS.
As with the hardcoded 12pt before, the values are scaled up by 1.2 times their displayed values to match the look on other operating systems.
Contains a fix that's required by the fact that `obsFontScale` is only used in a `calc` statement on Mac, and not in a direct alias.
Want to use this on macOS.
It would be weird if this was available everywhere except on macOS; and the current message "Some appearance options are not available for this style." is confusing as it's available for the style on other operating systems.
The font scale setting now is enabled and works.

frontend: Make Mac font size configurable 

---

.github/actions/steam-upload/action.yaml

After bf48a84d1ccdd564e2ea2b9cfc6722dc08b38092, the scheduled nightly runs began to fail because the filenames of the artifacts had changed. This would also have caused uploads on tag to fail. Explicitly specify the asset architecture here. Windows arm64 builds are still ignored for Steam Upload for now.
Want CI to work.
I tested the change locally in zsh.
- CI

CI: Fix Steam upload again

---

.github/actions/windows-patches/action.yaml
.github/actions/windows-signing/action.yaml

Make both `.github/actions/windows-patches/action.yaml` and `.github/actions/windows-patches/action.yaml` architecture aware so that they can work on distinct x64 or arm64 OBS builds.
Working towards better WoA support.
It hasn't.
- CI

CI: Add WoA support to windows-patches and windows-signing actions

---

.github/actions/windows-signing/action.yaml

CI: Update windows-signing to rclone 1.69.3
Update rclone version.
The windows-patches action has used this version and I have used it locally and it seems fine.
- CI

CI: Update windows-signing to rclone 1.69.3

---

.github/workflows/push.yaml

Update sign-windows commit
Want CI to use the updated sign-windows and windows-signing versions.
This does not require a merge commit since the commit hash it's targeting is already set in the repo.
It hasn't.
- CI

CI: Update sign-windows commit

---

frontend/components/SourceTreeItem.cpp

Fix the position of the group icons in the system theme 
I tried applying the changes warchamp7 made in PR #12157 here as well.
This issue does not occur in version 31.0.3.
Please close the PR if this change is wrong.
Before (31.0.3)
Before
After
I want to resolve this issue.
I'm not sure how many people actually use the System theme (I don’t myself), but I wanted to fix it anyway.
I'm not 100% sure if the code is correct.
You can test by changing the `Theme` in `user.ini` to `Theme=com.obsproject.System`.

frontend: Fix group icon position in System theme

---

buildspec.json
plugins/nv-filters/nvidia-videofx-filter.c
plugins/win-capture/duplicator-monitor-capture.c

When cherry-picking https://github.com/obsproject/obs-studio/commit/3b0d71500c722916051c77c753e6003f00b92ea7, I missed a trailing comma on one line in the buildspec file. The first commit fixes that.
I forgot that CI's verion of Visual Studio would have updated and that we'd need to fix build issues for that, so I've additionally cherry-picked:
* https://github.com/obsproject/obs-studio/pull/12095
Want release/31.0 to build.
Original commits tested in 31.1.0 and on master.

Fix broken build on release/31.0

---

plugins/win-capture/data/compatibility.json
plugins/win-capture/data/package.json

Adds the game Roblox to the compatibility list for win-capture.
People being able to capture the game which is not compatible with game capture or BitBlt Window capture.
Selected the game in the window capture and game capture source and the warning message showed up like it should.

win-capture: Add Roblox to compatibility list

---

.github/workflows/publish.yaml

Add GH_TOKEN to fix usage of GitHub CLI.
Fix CI failure:
https://github.com/obsproject/obs-studio/actions/runs/16129574795/job/45514190238
It hasn't. I checked another usage of `gh` in the same file and used the same solution.
- CI

CI: Add GH_TOKEN to fix usage of GitHub CLI

---

buildspec.json

Fixes RTMPS streaming not working in some cases.
Fixes SRT ingest failing in some cases.
* deps.ffmpeg: Update mbedTLS to 3.6.4
* deps.ffmpeg: Revert libsrt to v1.5.2 with patches
Fixes #12361
Fixes #12362

CI: Update deps to 2025-07-11 release

---

libobs/obs-config.h

libobs: Update version to 31.1.1
Required update.
It hasn't.
- Version Bump

libobs: Update version to 31.1.1

---

build-aux/modules/99-cef.json

Flatpak CEF was not updated in #12369
Align and re-enable hw accel on FLatpak.

build-aux: Use rebuilt CEF on Linux with backported API on Flatpak

---

frontend/data/themes/Yami.obt

Changes the QSS rule for `spacing` to be more specific and only target the widgets it affects. Also adds visual styling for progress bars since I was here anyway.
Fixes an alignment issue with the progress % on some systems.
Supersedes #12402
**Before**
Fixes #12378
Closes #12402
For whatever reason, setting the `spacing` value on QProgressBars causes it to assume it is being styled via QSS even though the setting does not affect it.
This retargets the spacing rule to only target widgets that actually support the setting instead of a wildcard.
Also added styling for progress bars to unify them across operating systems, as we style the rest of the app already too.
Remuxed multiple recordings
- Tweak (non-breaking change to improve …

frontend: Fix progress bar appearance

---

frontend/data/themes/Yami_Light.ovt
frontend/data/themes/Yami_Rachni.ovt

Fixed an issue where the scrollbar was invisible in the Light and Rachni themes.
The scrollbar are not visible in the source properties and settings window.
This issue does not occur in version 31.1.1.
This issue was caused by the following changes:
https://github.com/obsproject/obs-studio/commit/6a7de7ed4f75a41dc4a82e192dd740473a809e7c
Additional note about the Rachni changes:
`--scrollbar` was removed from Yami (the base theme) by the following changes:
https://github.com/obsproject/obs-studio/commit/a3884d1375255cd5b70f92fa82663ec5afee0e3d
Fixed by changing `--scrollbar` to `--scrollbar_handle`.
Additionally, as `--scrollbar` is still present in other themes (Acri and Classic), would it be better to update them to use `--scrollbar_handle` as well?
Feel free to close this PR if a better …

frontend: Fix invisible scrollbar issue in Light and Rachni themes

---

build-aux/.run-format.zsh

Adds the `test/` directory to the file list that clang-format formats.
Edited something locally in the `test` directory and noticed clang-format didn't fix the formatting when executing `./build-aux/run-clang-format`.
It used to be in there (e.g. it was affected by the change from 80 to 120 columns a while back), but probably got lost at some refactor. Note that all the code in the directory happens to still be formatted correctly and not need any changes.
macOS 15.5
Intentionally screwed up the formatting in `test-input.c` and ran `./build-aux/run-clang-format`, which now fixes the formatting.

build-aux: Add test directory to clang-format file list

---

plugins/mac-avcapture/OBSAVCapture.m

We require the macOS 15 SDK since 8f1bcc1 (#11893), so this check is unneeded.
Noticed this when looking at something else.
Hasn't. Should be needed.

mac-avcapture: Remove unneeded macOS SDK ifdef

---

plugins/obs-outputs/mp4-output.c

Reset the start timestamp used for file splitting and remove timestamp adjustments that are unnecessary for the MP4 muxer.
Fixes #11772
Based on reproduction steps in #11772.

obs-outputs: Reset splitting timestamps on mp4 output start

---

libobs/obs-config.h

libobs: Update version to 32.0.0
Required update.
It hasn't.
- Version Bump

libobs: Update version to 32.0.0

---

frontend/data/locale/en-US.ini

Removes an unused string.
String is unused, doesn't need translation.
Checked `git grep "ContextBar.ResetTransform"` to confirm the only other occurrences are in other localization files.

frontend/data: Remove unused context bar string

---

libobs/obs-config.h

libobs: Update version to 32.0.1
Required update.
It hasn't.
- Version Bump

libobs: Update version to 32.0.1
