obsproject/obs-studio

- plugins/rtmp-services/data/package.json
In preparation for v29, I adjusted the server-side to serve separate files for `/v3` and `/v4`. Unfortunately while `package.json` was correctly downloaded from `/v3` by OBS 28.x and lower, the `services.json` was fetched from the root URL and unintentionally "updated" everyone to an older version than v28 ships with, breaking things like YouTube - HLS.
This PR fixes the URL in `package.json` and bumps the version to force a re-download for affected users.  On the server-side, the URL is replaced for the `/v3` path during update.
Broken services are bad.
Checked file contents.
> rtmp-services: Specify RTMP_SERVICES_FORMAT_VERSION in package.json

- docs/sphinx/reference-core.rst
- docs/sphinx/reference-scenes.rst
Adds info on what the enum callbacks should return.
I was using obs_scene_enum_items but I had no idea whether I should return true or false, and the few occurrences of it in the repo only returned true, so I had to check the source code of the function for clarification.
Checked the source code of the functions to see if returning false will end enumeration.
As for the docs, I built it and viewed locally.
> docs: Clarify enum functions return value

- UI/obs-app.cpp
Qt is not smart enough to disable qt5 platform plugins when users blindly ask for them, which causes users to be unable to start OBS. Instead lets kindly disable broken platforms on their behalf.
Users prefer obs to not crash.
It doesnt do anything when I load obs normally. It doesnt fail to load when I set the platform theme.
> UI: Disable qt5ct when compiled with qt6

- plugins/linux-pipewire/pipewire.c
Fixes pipewire-screencast when using a software renderer
Whe using a software renderer there will be no formats available for using with dmabufs. We should only consider those formats wrt. to modifiers and as such move this check after adding general support for that format.
Fixes #7985 
Run obs with `LIBGL_ALWAYS_SOFTWARE=true`
> linux-pipewire: Check format availablity against DRM only for dmabufs

- UI/window-basic-stats.cpp
This PR stops updating the "time until disk full" calculation in the stats window if we don't have enough data. Otherwise the code processes Inf / NaN and generates meaningless numbers.
Seeing negative numbers for time until disk was full looks bad.
Tested with a paused recording.
> Prevent negative "disk full in" calculation when there's no output

- plugins/obs-filters/noise-suppress-filter.c
This fixes a bug reported by R1ch internally.
If someone uses NVIDIA noise suppression filter and later uninstalls the SDK, 
there can be a crash because the filter tries to load the models.
Crashes are bad. Fixes a crash.
Tested that there's no crash when the SDK is not found (removed the env var for the sdk path).
Tested that the filter works when the SDK is re-enabled or reinstalled.
> obs-filters: disable NVIDIA FX audio model loading if SDK is not installed

- plugins/obs-ffmpeg/obs-ffmpeg-output.c
Remove code forcing x264 and ffmpeg aac encoder. People in custom ffmpeg output should be able to use other video and audio encoders when streaming with RTMP, given its h264 or aac.
Fixes https://github.com/obsproject/obs-studio/issues/8043
Nice to be able to use fdk_aac, or harware encoders like nvenc, amf, qsv etc. in custom ffmpeg output.
I built OBS, and streamed to twitch using RTMP and custom ffmpeg output, and selected the h264_nvenc encoder. Using several monitoring tools I confirmed that the encoding was happening on nvenc, and confirmed usable output on the twitch player.
Windows 10 22H2.
> obs-ffmpeg: Remove forced x264 and aac on RTMP

- UI/forms/OBSYoutubeActions.ui
(Re-)Introduces spacing to the bottom row buttons in the YouTube dialog.
Before:
After:
The number `10` was chosen arbitrarily.
ffbcbaece8b85592e154da20a419d23cac2a0873 / #7267 (accidentally) removed the spacing between the buttons, leaving them very crammed. It seems like Qt implicitly added spacing with the setup from before the PR but no longer does.
macOS 13, built and run.
See Screenshots above.
> UI: Reintroduce spacing to YouTube dialog buttons

- libobs/util/text-lookup.c
The text-lookup library is supposed to handle the key case-insensitive but the function `text_node_bychar` compared the key case-sensitive. This PR fixes the bug by converting the key to upper-case before creating the data structure.
When converting to upper-case, uses `toupper` so that the behavior is consistent with `astrcmpi_n`, which is utilized when looking-up the text.
Also removes the code below because both `val1` and `val2` have already been converted to upper-case.
https://github.com/obsproject/obs-studio/blob/783bd5219758f4eb031d9bfba19d92dd120ea7d8/libobs/util/text-lookup.c#L162-L165
The definition of `astrcmpi_n` is as below.
https://github.com/obsproject/obs-studio/blob/783bd5219758f4eb031d9bfba19d92dd120ea7d8/libobs/util/dstr.c#L122-L142
I'm making another PR #8018 having …
> libobs/util: Fix text-lookup not always case-insensitive

- UI/win-update/updater/updater.cpp
When the updater is launched from a portable install, relaunch OBS with `--portable`
Fixes a thing that annoyed me when testing #8048
Ran updater from portable install, hit "Launch OBS" and confirmed it now runs in portable mode.
> updater: Maintain portable state when relaunching

- libobs-opengl/gl-cocoa.m
- libobs-opengl/gl-nix.c
Mac was already dropping a most of these when leaving contexts, this patch brings the same drops to linux and also drops vertex/index buffers that were noticed as leaking across contexts and resulting in invalid bindings by later draws. Especially with the new spacing labels.
Fixes opengl error spam when moving sources on linux.
Tested with all the default sources and some transitions, and i could not find anything rendering differently. I expect that no one tried to do something as dangerous as depend on gl state across calls to obs_enter_graphics(). Especially since mac was already dropping various state, so any such plugins would probably be broken on mac already.
> libobs-opengl: Drop gl pointers on device_leave_context

- libobs-winrt/winrt-capture.cpp
- libobs-winrt/winrt-capture.h
- plugins/win-capture/duplicator-monitor-capture.c
- plugins/win-capture/window-capture.c
Leverage existing window capture support for display capture.
(Also add another commit to fix visibility for window capture setting as a bonus.)
Users don't want to disable HDR in their Windows settings to capture SDR, and that's reasonable.
Checkbox appears when it should, and behaves as it should.
I didn't inspect color values this time since the same code path was tested for window capture, but they looked reasonable at a glance, i.e. not dim.
> libobs-winrt,win-capture: Add Force SDR for WGC display

- libobs/obs-source-transition.c
Fix stopping transitions that are not active
For transitions in the properties dialog (cloned private source) no audio render is done, so the transition never stopped, it kept waiting for the audio to finish. With these changes it will set the audio as done when video is done.
On windows 64 bit by checking if transition_stop function is called after the preview button is clicked in the properties dialog of a transition.
> libobs: Fix stopping transitions that are not active

- plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm
- plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm
Fixes https://github.com/obsproject/obs-studio/issues/8039.
The DAL plugin-based virtualcamera shares data between OBS and the plugin using an IOSurface. IOSurface locks are necessary to ensure race conditions between data generation (OBS side) and consumption (virtual camera side) and also that an IOSurface is not offloaded to GPU memory when it is indeed needed in CPU memory.
Also moves the invalidation of the NSMachPort for the frames to after the IOSurface data has been converted into a pixelbuffer and added to the frame queue of the virtual camera, as an early invalidation will cut off access to the pixel data shared with the DAL plugin.
Tested on Intel-based iMac (late 2015) and Mac Studio (2022).
> mac-virtualcam: Fix memory access issues for shared IOSurfaces

- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs-output.h
Refactors the obs-output to better separate the usage of MAX_AUDIO_MIXES (raw audio) and the audio encoders.
This is in preparation for adding multiple video encoders per output as well as generally clarifying usage and allowing potentially more encoders than audio mix tracks (6).
Also fixes some bugs around removing encoders from outputs while active
* Tested multi track consecutive and sparse tracks (ffmpeg muxer)
* Tested multi track consecutive and sparse tracks (ffmpeg adv recording)
> libobs: Refactor obs-output in preparation of multiple video encoders

- libobs/obs-scene.c
This moves the `custom_size` code above the return statement, to allow scenes to be set to a custom size if they are missing the `items` array (aka coming from a default configuration).
Previously, `custom_size` was checked at the end of the `scene_load` function. If the scene contained no "items" array, the `custom_scene` loading code would never be run.
Before: Custom size did not work without `items` defined
After: It works without `items` defined
> libobs: Fix loading of custom_size for empty scenes

- UI/source-tree.cpp
This disables opening of the properties dialog if a scene is double clicked in the source tree.
The scene properties dialog is empty, so it is unnecessary to open it.
Double clicked scene item that was scene.
> UI: Don't open properties dialog if item is scene

- UI/window-basic-main.cpp
This disables the source screenshot action in the context menu if the source has no video.
Better feedback to users.
Right clicked an audio source to make sure the action was disabled.
> UI: Disable screenshot action if item has no video

- docs/sphinx/reference-libobs-graphics-graphics.rst
- libobs/graphics/device-exports.h
- libobs/graphics/graphics-imports.c
- libobs/graphics/graphics-internal.h
- libobs/graphics/graphics.c
- libobs/graphics/graphics.h
Trying to build [wlrobs](https://hg.sr.ht/~scoopta/wlrobs) >= 1.1 I get the following error:
```
ld: error: undefined symbol: gs_texture_create_from_dmabuf
>>> referenced by dmabuf_source.c
>>>               libwlrobs.so.p/src_dmabuf_source.c.o:(ready)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
despite https://github.com/obsproject/obs-studio/blob/88ea0bbb56b0a020b60c908a706cbe2403a13fd8/libobs/graphics/graphics.h#L970-L976
wlroots (Wayland) support on FreeBSD and DragonFly. wlrobs-1.0 already works fine but wlrobs-1.1 needs this change.
wlroots + wlrobs are also supported on DragonFly, so expose DMABUF API there as well.
```
$ pkg install sway wlrobs glx-utils
$ sway
$ glxgears &
$ obs
<Sources>
<Add Source>
<Wayland output(dmabuf)>
<OK>
<Sources> …
```
> libobs/graphics: unbreak DMABUF on FreeBSD

- plugins/obs-filters/noise-suppress-filter.c
- plugins/obs-filters/nvafx-load.h
- plugins/obs-filters/nvidia-greenscreen-filter.c
- plugins/obs-filters/nvvfx-load.h
- Don't repeatedly query version at runtime in case a user installs the SDK while OBS is running
- Restore default DLL search directory
- Don't show outdated SDK message if the SDK is not found
- Protect minimum version macro with brackets
Don't want to show warning to users without the SDK installed. Cleaned up other things while working on the code.
Ran OBS on a GPU supporting NVIDIA effects SDK and verified in debugger.
> obs-filters: Improve NVIDIA effects SDK version checks

- libobs-opengl/gl-x11-egl.c
Previously we passed the wrong display and formats/modifiers could not be queried. This prevented pipewire sources from negotiating texture sharing on x11.
Maybe fast screencapture on X11 for compositors that support it, resolves the error in the logs when users attempted screencapture on x11.
Fixes totally busted dmabuf support if anyone was trying to use it on x11.
Ran on gnome and observed the error was resolved (though it didnt negotiate a dmabuf).
> libobs-opengl: Fixup dmabuf queries on X11

- UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp
On non X11 windowing systems OBS will crash when the automatic scene switcher is enabled and the current foreground window is changed due to invalid Window parameters being passed to various X11 functions:
```
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  29
Current serial number in output stream:  29
```
Add error handling to avoid passing invalid windows to various X11 functions and thus crashes of OBS.
OBS no longer crashes on Ubuntu 22 with the Wayland windowing system when the automatic scene switcher is enabled and the foreground window is changed.
The automatic scene switcher still works as expected on Ubuntu 22 with the X11 windowing system. …
> frontend-tools: Fix crash on non X11 windowing systems

- plugins/obs-ffmpeg/obs-ffmpeg-output.c
Prevents alpha from getting dropped with custom encoders.
Fixes #8133
People are relying on this.
Davinci Resolve shows alpha is working again.
> obs-ffmpeg: Tell FFmpeg that BGRA uses alpha

- UI/auth-restream.cpp
- UI/auth-twitch.cpp
- UI/auth-youtube.cpp
This is a workaround for #7348. It doesn't fix it, but at least gets OBS up and running again by not attempting to restore the integration docks when OBS is in a state that would cause the crash (not visible but maximised).
Want to keep users at least up and running, even with the minor inconvenience of having their docks fucked up.
Tested in debugger to ensure no crashes.
> UI: Work around Qt dock restore crash

- libobs-d3d11/d3d11-subsystem.cpp
- libobs/obs-source.c
Bug was seen when projecting SDR video capture on WCG displays.
Fixes #8032
Want projectors to output the right colors.
Checked projector looks good on WCG, and hasn't regressed on SDR/HDR displays. Log output also looks good in all three cases.
> libobs: Fix SDR async video on non-SDR targets

- UI/win-update/updater/updater.cpp
Just adds a few more status messages to be more clear what the updater is doing.
Updater would say "Installing v8something" until it finished. Since steps after installing updates can take a few seconds this just shows messages for what it's actually doing.
Ran updater, saw messages.
> updater: Add additional status messages

- UI/win-update/updater/updater.cpp
Pass AppData location to elevated process via command line parameter.
(This is classed as a bug fix as the previous method doesn't work [anymore] and this replaces it.)
When a separate administrator account is used for elevation the appdata path would be set to the wrong user's directory.
Previously this was attempted via an environment variable, but those are not retained for the elevated process.
Verified correct path is passed and read by the elevated process.
> updater: Pass AppData path to elevated process

- libobs-opengl/gl-x11-egl.c
- libobs/obs-nix-x11.c
The platform display retrieved in `OBSApp::OBSInit()` belongs to Qt, therefore libobs components should not destroy it. Because when it is destroyed, it may result in UAFs when Qt components try to use it. Not closing the platform display is the main change, but there are also two other small changes that close X displays that weren't previously closed. See the commit messages for more details.
Fixes a use-after-free issue that manifests itself when `gl_x11_egl_platform_create()` fails.
Tested locally on top of the master branch. Linux 6.1.7, with X11, NVIDIA.
-- 
@GeorgesStavracas @kkartaltepe
> libobs-opengl:  Do not close X11 platform display on error

- plugins/linux-pipewire/pipewire.c
This patch checks the buffer received from PipeWire for flags indicating that the buffer is corrupt.
Portals can set a buffer as corrupted via flags. This allows obs to skip those frames and avoid trying to import them.
Modified version of [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr) to alternate between those flags for a given time duration. With this patch your screencast will freeze until a new frame without a flag arrives. Mouse pointer should still be updated when it is not embedded. 
> linux-pipewire: check pipewire buffers for corruption

- plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp
Fixes a crash when the virtualcamera filter size changes when used inside OBS. This was due to the `in_obs` code path that changed the filter size, but the `new_filter_cx` / `new_filter_cy` were already read from the filter so the scaler used the wrong values.
Reported in v29 after the resolution change fixes in the Discord support channel.
Ran OBS at 1080p, started camera, stopped, dropped to 360p, started camera and observed no more crashes.
> virtualcam-module: Update filter size immediately when used in OBS

- UI/properties-view.cpp
Calls a [raise()](https://doc.qt.io/qt-6/qwidget.html#raise) on the properties window after a file or directory has been picked either in a file property or file list property.
This ensures that the properties dialog is still in front after a file/directory has been picked.
Currently on macOS, after picking a file the properties window disappears behind the main window due to a bug in Qt.
This is *bad*.
Upstream issue: [QTBUG-42661](https://bugreports.qt.io/browse/QTBUG-42661)
macOS 13
Picked files in the media source and the slideshow source.
Where without this patch the properties would disappear behind the main window, they no longer do.
> UI: Re-raise properties window after picking files on macOS

- cmake/Modules/CompilerConfig.cmake
- deps/media-playback/media-playback/decode.c
- deps/obs-scripting/obs-scripting-python.c
- deps/obs-scripting/obs-scripting.c
Contains a rework of #8113
Add an option `CALM_DEPRECATION` to enable `-Wno-error=deprecated-declarations` for Linux users that might use bleeding-edge dependencies compared to obs-deps.
Fix a few other warning/errors.
Improve #6759 and fix warnings/errors.
> Add CALM_DEPRECATION cmake option and fix some warnings

- UI/window-basic-main.cpp
Hides the following items if source is only audio:
- Transform menu
- Resize output (size of source)
- Scale filter menu
- Blending mode menus
- Projector menus
- Screenshots
- Interact
These are not needed if the source is only audio.
Right clicked audio source to make sure the items were hidden.
> UI: Hide menu items if source is only audio

- UI/win-update/updater/updater.cpp
Reverts 7396c211be75da3bce74cf8d2661a481a5c10fff and enables deduplication for delta patch files as well.
Fixes the same issue as 7396c211be75da3bce74cf8d2661a481a5c10fff but with the new deduplication feature.
Updated locally from 28.1.2 and 27.2.4 to 29.0.0.
> updater: Deduplicate Delta Patch Downloads

- UI/obs-app.cpp
- UI/obs-proxy-style.cpp
- UI/obs-proxy-style.hpp
- UI/platform-osx.mm
- UI/platform.hpp
Sets the `SH_ComboBox_UseNativePopup` to true on macOS. By doing this, Qt's combobox popups get replaced by native macOS ones. Before/After:
<p>
</p>
This flag currently only has an effect on macOS, but it's still probably safer to ifdef-guard it.
As recommended by Qt on QTBUG-106162, this fixes QComboBox popups not working with VoiceOver.
Together with Qt 6.5 (which fixes comboboxes not opening in the first place, see [QTBUG-106162](https://bugreports.qt.io/browse/QTBUG-106162)) this should make non-editable comboboxes work flawlessly.
Renamed `OBSIgnoreWheelProxyStyle` to `OBSProxyStyle` since it's no longer exclusive to ignoring wheel scrolling.
Want OBS to be more accessible. Making VoiceOver work properly is a long and difficult (maybe impossible) road, but every step counts.
macOS …
> UI: Use native combobox popup on macOS

- .github/workflows/docs.yml
Amends docs workflow to upload generated page to Cloudflare Pages when a tag is pushed or when manually triggered.
Automated deploy, no worries about security policy affecting other obsproject sites.
On my fork:
- Workflow run: https://github.com/derrod/obs-studio/actions/runs/4037558811
- Deployed site: https://a00126b6.obs-docs-test.pages.dev/
> CI: Publish docs to Cloudflare Pages

- UI/api-interface.cpp
- UI/obs-frontend-api/obs-frontend-api.cpp
- UI/obs-frontend-api/obs-frontend-api.h
- UI/obs-frontend-api/obs-frontend-internal.hpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-basic-transform.cpp
- UI/window-basic-transform.hpp
- docs/sphinx/reference-frontend-api.rst
Add `obs_frontend_open_sceneitem_edit_transform(obs_sceneitem_t *item)`
Allow scripts and plugins to open the edit transform dialog for a specific scene item
On windows 64 bit by calling the function from a plugin.
> UI: Add obs_frontend_open_sceneitem_edit_transform

- deps/obs-scripting/obs-scripting-python-import.c
- deps/obs-scripting/obs-scripting-python-import.h
Adds necessary Python 3 symbols for use with Swig 4.1.1.
Swig merged in partial support for Python's stable ABI, which require `PyType_Modified` to be available at compile time.
Required for https://github.com/obsproject/obs-deps/pull/154
* Tested on Windows 11 (Windows being the only OS that requires the symbols to be resolved at link time)
> obs-scripting: Add PyType_Modified import for Swig 4.1.1 compatibility

- UI/api-interface.cpp
- UI/obs-frontend-api/obs-frontend-api.cpp
- UI/obs-frontend-api/obs-frontend-api.h
- UI/obs-frontend-api/obs-frontend-internal.hpp
- docs/sphinx/reference-frontend-api.rst
Add `void obs_frontend_add_undo_redo_action(const char *name, const undo_redo_cb undo, const undo_redo_cb redo,	const char *undo_data, const char *redo_data, bool repeatable)`
Allow plugins to add undo and redo actions
On windows 64 bit calling it from a plugin
> UI: Add obs_frontend_add_undo_redo_action

- libobs-d3d11/CMakeLists.txt
- libobs-d3d11/d3d11-subsystem.cpp
Log display DPI.
Example (100% scaling):
```
23:08:35.567: 	  output 2:
23:08:35.567: 	    name=DELL U2715H
23:08:35.567: 	    pos={-2560, 0}
23:08:35.567: 	    size={2560, 1440}
23:08:35.567: 	    attached=true
23:08:35.567: 	    refresh=59
23:08:35.567: 	    bits_per_color=8
23:08:35.567: 	    space=RGB_FULL_G22_NONE_P709
23:08:35.567: 	    sdr_white_nits=80
23:08:35.567: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
23:08:35.567: 	    dpi=96 (100%)
```
Users do funny things.
Ran on my machine, seems to log correct info, but who knows.
> libobs-d3d11: Log display DPI and scale factor

- plugins/win-capture/graphics-hook/graphics-hook.c
It never works, and leaves a confusing message behind.
Trying not to confuse game programmers.
Tried Vulkan and D3D11 samples, and they no longer show the message. They both connect to OBS in similar amounts of time whether the samples are started before or after OBS. Surprisingly, the message was still showing without this change even if OBS was launched first and waiting for the specific sample.
> graphics-hook: Stop trying to connect early

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
If a scene or group is selected, disable the properties button in the source toolbar. This also does a refactor of the function to enable/disable the toolbar buttons.
Makes the source toolbar consistent with the source context bar.
Selected/unselected a nested scene in the sources list to make sure the toolbar updated correctly.
> UI: Disable properties button in source toolbar

- CI/windows/01_install_dependencies.ps1
Switches to curl for downloading dependencies rather than powershell itself.
Bypasses whatever issue is causing build failures when using `Invoke-WebRequest`. Also see issue on GitHub's repo for reference: https://github.com/actions/runner-images/issues/7007
Despair.
Many runs on my fork that all succeeded.
> CI: Switch to curl for dependency downloads

- CI/flatpak/com.obsproject.Studio.json
Fixes #7849
Fixes crashes with 0.3.48/49 daemons.
Because of the unstable nature of the JACK ABI, Freedesktop will not update PipeWire on their side immediately.
> flatpak: Override PipeWire to 0.3.65

- UI/properties-view.cpp
Ensure the properties widget is correctly sized when it is created/updated.
**Before:**
**After:**
Don't want properties widgets being cut off. This affects all widgets, but is most noticeable with labels.
Mostly noticed during work on #8080 as the warnings were cut off and only wrapped once the window was manually resized.
Opening and closing properties.
> UI: Fix properties widget being cut off until resize

- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
The aac spec has a list of default channel layouts that are implemented by all aac encoders / decoders.
Unfortunately 2.1 is not in that list. When I wrote the surround sound support into OBS, as a workaround I decided to encode 2.1 as AV_CH_LAYOUT_SURROUND = FL+FR+FC.
The LFE channel is encoded as a regular audio channel which uses more bits but this allows compatibility with all aac decoders. Recently we updated to the new channel layout API of FFmpeg, but the mapping of 2.1 to AV_CH_LAYOUT_SURROUND was forgotten in the FFmpeg native aac encoder. This is remedied here.
Fixes #8225 
Fix bug.
Both streaming to Twitch and recording work fine when encoding with 2.1 speaker layout.
> obs-ffmpeg: Fix encoding of 2.1 with FFmpeg aac encoder

- libobs/obs-scene.c
When `AUDIO_OUTPUT_FRAMES - pos` is not positive, skip the later audio process.
When a variable `pos` became larger than `AUDIO_OUTPUT_FRAMES`, `count` will get overflowed number. We should avoid such an underflow number going to later processing.
Since the pointer while processing audio is compared by the operator `<`, the underflow should be safely handled in the usual architectures. However, I don't think it's reliable for any architecture.
https://github.com/obsproject/obs-studio/blob/f81f580d26366dec262f0ef2144cf7a77ae86393/libobs/obs-scene.c#L1388-L1393
This issue was found while debugging #8002 but this is independent issue.
OS: Fedora 36
1. Create an empty scene collection.
2. Add `Audio Input Capture (Pulse)` to the scene.
3. Add `Media Source` with a audio file.
4. Start …
> libobs: Avoid position underflow when mixing audio sources

- UI/qt-wrappers.cpp
- UI/window-basic-main.cpp
In some cases, `QToolbar::widgetForAction` may return `nullptr`. This causes a crash on affected system.
To mitigate this, we check for `widgetForAction` result and skip operating on a NULL widget.
Not checking for the return value causes the program to crash in cases where `widgetForAction` returns nullptr
Crash reproduced locally, added fix, crash disappeared.
> UI: Add check for null widgetForAction result

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-basic-preview.cpp
- UI/window-basic-preview.hpp
- UI/window-basic-settings.cpp
Updates the overflow settings for the preview once on startup and when settings change isntead of querying every frame.
Before the config would be queried twice per source per frame to see if the overflow options were set.
Discovered while checking config queries for capitalisation issues while working on #8229.
Verified config is no longer queried each frame and options still work
> UI: Avoid excessive config reads when drawing preview

- UI/item-widget-helpers.cpp
- UI/scene-tree.cpp
- UI/scene-tree.hpp
Qt 6.2 introduced an issue where SingleSelection item views would deselect the current item if the user clicked on empty area in the widget.
This was very confusing in the scene tree as it was now possible to unselect the current scene. A workaround for this in OBS was added in 08e4ee6 (#7200) and expanded on in dc30cf0 (#7499), but being quite hacky it never was the perfect solution.
I since dug into Qt and fixed the issue upstream at [Qt Gerrit 459511](https://codereview.qt-project.org/c/qt/qtbase/+/459511). ~~That hasn't actually landed in Qt (yet), but first review by the maintainer suggests it's in relatively decent shape, so I'm preparing this PR now.~~ That patch has now landed.
It's being cherry-picked to 6.4 and 6.5, so it will be in 6.4.3 and newer meaning we can remove the …
> UI: Remove workaround for current scene being deselectable on Qt 6.4.3+

- libobs/obs-nix.c
Add `XDG_CURRENT_DESKTOP` and/or `XDG_SESSION_DESKTOP` to the log to identify the desktop environment.
Before:
```
info: Distribution: "Arch Linux" Unknown
info: Session Type: x11
```
After:
```
info: Distribution: "Arch Linux" Unknown
info: Desktop Environment: GNOME (gnome-xorg)
info: Session Type: x11
```
In a Flatpak environment, a  file `.flatpak-info` is created in the root. This file contains information that the application can retrieve to log them.
Its syntax allows it to be read with `config_t`.
```
➜  ~ flatpak run --command=sh --devel com.obsproject.Studio//stable
[📦 com.obsproject.Studio ~]$ cat /.flatpak-info 
[Application]
name=com.obsproject.Studio
runtime=runtime/org.kde.Sdk/x86_64/6.4
[Instance]
instance-id=562527906 …
```
> Improve Flatpak and Linux session logging

- plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp
- plugins/win-dshow/virtualcam-module/virtualcam-filter.hpp
Fix virtualcam output a default video format
Depends on: https://github.com/obsproject/libdshowcapture/pull/50
The virtual camera indicates it supports a resolution that is not the resolution of the output.
This makes apps like vdo.ninja use the wrong resolution, which results in stretched images.
On windows 64bit with a virtual camera and vdo.ninja
> win-dshow: Fix virtualcam output a default video format

- UI/source-tree.cpp
If an user exits the source tree edit mode, without changing the name, the scene item would become undraggable until the scene is refreshed.
Bug reported by @Warchamp7 
Entered the source tree edit mode and exited, without changing the name, and made sure the item was draggable.
> UI: Fix scene item edit drag & drop bug

- libobs-opengl/gl-egl-common.c
- libobs-opengl/gl-texture2d.c
Previously we would actually initialize a texture memory that would then also have to be deleted when we bound the EGLImage to the texture during dmabuf import.
Instead simply do not create the dummy texture memory. One odd thing is that we must still query the texture to ensure its initialized or binding the EGLImage will not work. So we leave the TEXTURE_MAX_LEVEL check.
This makes screencapture up to 100x faster on discrete intel cards and likely has some performance benefit for amd/integrated cards. Without this dmabufs are actually slower than shared memory for these intel cards.
Tested with screencapture and texture encoding (pending another PR) and both continue to work with this change. If someone on AMD wants to confirm a performance improvement that would be nice.
- Performance …
> libobs-opengl: Accelerate dmabuf import

- plugins/linux-pipewire/linux-pipewire.c
- plugins/linux-pipewire/pipewire.c
- plugins/linux-pipewire/pipewire.h
- plugins/linux-pipewire/screencast-portal.c
- plugins/linux-pipewire/screencast-portal.h
Various cleanups in preparation for making `linux-pipewire` handle cameras and audio. This pull request contains the "easy" half of https://github.com/obsproject/obs-studio/pull/6669 and should not be controversial.
What is done here is: 
* Clean up a leftover object when the plugin is unloaded
* Massage some functions to receive more parameters...
* ... which then allow cleaning up the internal struct
* Rename a struct to better represent its scope
* Shuffle code around
Prepare the `linux-pipewire` plugin to receive support for cameras and audio. This is also an effort to get https://github.com/obsproject/obs-studio/pull/6669 unstuck.
- Run OBS Studio on Linux + Wayland, and notice it continues to work
> Dimidium Totius (in preparation for PipeWire camera and audio, part 1)

- plugins/obs-ffmpeg/external/AMF/include/components/HQScaler.h
- plugins/obs-ffmpeg/external/AMF/include/components/SupportedCodecs.h
- plugins/obs-ffmpeg/external/AMF/include/components/VQEnhancer.h
- plugins/obs-ffmpeg/external/AMF/include/components/VideoDecoderUVD.h
- plugins/obs-ffmpeg/external/AMF/include/components/VideoEncoderAV1.h
- plugins/obs-ffmpeg/external/AMF/include/components/VideoEncoderHEVC.h
- plugins/obs-ffmpeg/external/AMF/include/components/VideoEncoderVCE.h
- plugins/obs-ffmpeg/external/AMF/include/core/Factory.h
- plugins/obs-ffmpeg/external/AMF/include/core/Platform.h
- plugins/obs-ffmpeg/external/AMF/include/core/Surface.h
- plugins/obs-ffmpeg/external/AMF/include/core/Variant.h
- plugins/obs-ffmpeg/external/AMF/include/core/VulkanAMF.h
Updated AMF SDK headers to v1.4.29.0.
Updating to AMF SDK v1.4.29.0 affects OBS in the following ways:
- Smart Access Video support for the AVC / HEVC / AV1 encoders
- New options for the AV1 encoder
Tested on Windows 10 with a GPU + APU setup.
> obs-ffmpeg: Update AMF SDK to v1.4.29

- plugins/linux-pipewire/pipewire.c
Receiving buffers flagged as corrupted, or empty, is a casualty of how things are implemented in various compositors, and it's not a critical situation to be afraid of. We can expect a few buffers to be flagged as corrupted here and there, and that's fine.
Demote these warnings to debug messages, as they're still useful for debugging.
We were spamming the log with messages that are actually fine.
Spamming log bad, clean log good
- Run OBS Studio in Wayland
- Notice that the stdout / stderr log is decent
> linux-pipewire: Demote error to debug message

- libobs-opengl/gl-cocoa.m
Fixes a crash occurring whenever a full screen projector was placed on an attached display, which is then disconnected while OBS runs.
When an external display is disconnected with a fullscreen projector attached to it, Qt will trigger a resize of the window twice, which makes the renderer queue 2 resize event blocks.
At the time when those blocks are run, Qt's window destructor will have reset all pointers, and the block directly accesses pointers within structures identified by pointers, which are invalid by that point.
This commit makes a block return early if the associated window has been destroyed already and also explicitly checks for valid pointers after.
Tested with an external display connected via HDMI on macOS Ventura.
> libobs-opengl: Fix projector crash with external macOS displays

- .github/workflows/docs.yml
- docs/sphinx/conf.py
- Disables beta/rc tags being published to live page
- Runs version update step for `workflow_dispatch` as well
- Sphinx output is now created without `.html` suffix in Links to avoid unnecessary redirects on CF's platform
Note: This would break browing the docs locally unless they're hosted on a webserver that is configured to support extension-less URLs.
Fixing good.
Tested on my fork: https://obs-docs-test.pages.dev/
> CI/docs: Some fixes for CF Pages publishing

- libobs/media-io/media-remux.c
Check codec tag compatibility for out stream.
Fixes #8029 
When the codec tag is not supported by out stream codec, the error happen.
introduced by https://github.com/obsproject/obs-studio/commit/bbb3dc00590a572cf49f97db3397221f0828f9ad
So add judgement to check compatibility.
https://github.com/FFmpeg/FFmpeg/blob/51efa68ec0b4f42b5b124b8987fb68f60a929c4f/libavformat/segment.c#L174-L180
Follow steps mentioned in issue to test, run well. (`ts, flv, m3u8 ...`)
~Not check hevc behavior.~
> libobs/media-io: Check codec tag compatibility for out stream

- UI/window-basic-filters.cpp
Use a different method to create a sorted list that avoids worst-case quadratic time behavior.
PVS Studio warned about poor use of `vector` since insertions were done in the middle which causes the rest of the data to be moved.
Ran OBS, verified menu was still sorted.
> UI: Improved implementation for sorting filters menu

- libobs-d3d11/d3d11-subsystem.cpp
- libobs-winrt/winrt-capture.cpp
- libobs-winrt/winrt-dispatch.cpp
- libobs/obs-windows.c
- plugins/win-capture/duplicator-monitor-capture.c
PRs #7749 and #7766 highlighted a bug in how we process wide character format strings. For whatever reason, these are locale-dependent and without us changing the process locale, the strings would either be truncated or empty when the `*sprintf` family of functions hit the wide character bytes. Unfortunately these PRs were closed without resolution, so I am trying to finish the changes required.
Fixes #7816
Missing information in log files is bad, and possibly empty monitor names is worse.
Breakpoint tested most changes, winrt errors were not easy to trigger but the code looks correct.
> Fix mixed WCS and UTF-8 format strings

- UI/source-tree.cpp
Check item whether selected before select
To prevent item from being selected again,
then mess up the qt internal list order.
When Click SourceTree Item, then the App will run like following steps:
and the last step is not as expected, it **mess up** the qt internal list order. (found after debugging qtcore `QItemSelectionModel::select`)
So Add a judgement to Check item whether selected before select.
Fixes #7685
reproduce steps mentioned in issues, and work fine.
Paste items order as expected.
Click item 0, then Press Shift and Click item n.
the order is `0->n` not `n, 0 -> n-1`
> UI: Check item whether selected before select

- plugins/linux-jack/jack-input.c
Prepends all devices created by the jack input client source with "OBS Studio: ".
This makes it more clear that the device belongs to OBS.
Fixes #7988
Since this changes the name of the clients this might impact existing setups that rely on the old device names without the prefix. 
- Created a Jack Input Client source
- Checked qpwgraph or any other patch bay for the prefix
- Exited obs and checked log to make sure there are no memory leaks
> linux-jack: Prepend devices with "OBS Studio: "

- plugins/obs-ffmpeg/jim-nvenc-helpers.c
- plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
- plugins/obs-ffmpeg/obs-ffmpeg.c
This copies the result of `nvEncGetLastErrorString` to the last encoder error instead of only writing it to the log file. This makes it user-visible, which should help users diagnose and solve the problem.
Also strips off leading colons from NVENC error strings as these can look odd given our format string. An example of such an error:
`::NV_ENC_TWO_PASS_FULL_RESOLUTION is only supported multipass encoding on this architecture.`
Additionally handles `NV_ENC_ERR_NO_ENCODE_DEVICE` with the unsupported device message and blacklists a GeForce MX350 variant.
While the full error message in the log file is useful, it's not really visible to users. Showing it in the encoder failure message box should help users solve the problem.
Not tested very well as I couldn't easily trigger error conditions …
> NVENC error handling improvements

- plugins/vlc-video/vlc-video-source.c
Current behavior leads to overflow in computing source width with Sample Aspect Ratio. Changing to `uint64_t` fixed this problem.
Resolve #7666.
Playing testing videos described in #7666.
Changed precision of computing `display_width` with SAR.
> vlc-video: Fix videos larger than 1080p being squished

- plugins/obs-ffmpeg/jim-nvenc.c
When bitrate is updated, a check against 'lookahead' setting is done. If 'lookahead' is enabled, the bitrate update is disabled. We indeed used to observe crashes with nvenc when frequent bitrate resettings were effected while lookahead option was enabled. But recent tests have shown that the issue is gone. As a result this commit allows 'lookahead' with bitrate live update.
The need for a fix was raised when a user reported that bitrate live update did not work with P6 or P7 presets for jim-nvenc.
These presets enable 'lookahead' option which before this commit would disable bitrate live update
(either dynamic bitrate or manual update through the Settings > Output menu).
Fixes https://github.com/obsproject/obs-studio/issues/8268
Tested by @notr1ch who had 15k bitrate changes on P7 preset …
> obs-ffmpeg: Relax 'lookahead' constraint when bitrate is updated

- UI/data/locale/en-US.ini
- UI/forms/OBSBasicSettings.ui
- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
Waits with loading hotkeys until the user clicks on the settings tab.
The user sees a message while the tab is still loading:
Enables the settings window to still open really quickly even with tons of hotkeys (like #6081).
Opened settings, it was quick!
> UI: Defer loading hotkeys until tab is switched

- UI/obs-app.cpp
- UI/window-basic-about.cpp
This removes the bitness strings from the title bar and about dialog.
These are now pointless because we are now only 64 bit.
Checked UI to see if the strings were removed.
> UI: Remove bitness strings

- UI/window-basic-transform.cpp
- UI/window-basic-transform.hpp
Removes the detour of going via an extra slot and connects the clicked signal of the reset button in the Edit Transform dialog to the main window directly.
Qt threw `QMetaObject::connectSlotsByName: No matching signal for on_resetButton_clicked` at us because the slot wasn't connected automatically. This made me sad.
I was going to just rename it (which would be a correct fix, the `on_foo_bar` names should only be used if the signal is (primarily) connected automatically), however I noticed that the slot function just called a slot of the main window. We can get rid of this complication by connecting directly.
Tested that "Reset" button in the Edit Transform menu still works.
> UI: Connect Reset button in Transform menu with main window directly

- UI/properties-view.cpp
One of OBSPropertiesView constructors does not set object at all.
And since no object are set, the button callback is never called.
I was trying to add and use a button in a OBSPropertiesView in the settings but the callback was nerver called.
The callback was called on my button, and button like in browser sources still works.
> UI: Fix OBSPropertiesView button callback with its const char* constructor

- UI/context-bar-controls.cpp
- UI/properties-view.cpp
- UI/window-basic-main.cpp
- UI/window-basic-settings-a11y.cpp
Currently, we use the Qt provided color dialog on all platforms except Windows.
This was because of the native dialog "closing other open QDialogs" and events not working properly.
The former is either not true anymore, or has never been true. What happens is that other open QDialogs get put behind the main window, making it look like they were closed. This can be worked around with a `raise()` call on the main window (like in #8116).
[QTBUG-34532](https://bugreports.qt.io/browse/QTBUG-34532) is about events not working when subclassed. We're not subclassing the QColorDialog so this isn't be relevant to what we're doing.
The Qt color picker on macOS has the problem that it can't pick screen colors from outside the color picker window, making it useless for picking screen colors.
macOS' …
> UI: Use native color dialog on macOS

- UI/window-basic-settings.cpp
These widgets are all children of updateSettingsGroupBox, meaning they get deleted when updateSettingsGroupBox gets deleted. This means that the first two calls are unnecessary and the third one segfaults as updateChannelLabel is gone already.
Just delete the parent widget instead.
Noticed by @fzwoch in https://github.com/obsproject/obs-studio/commit/12a27d8b99473d00d8939a78601c3ebcd6b2a2a9#r101210111.
Hasn't.
But should work according to my knowledge of Qt and also it can't get any worse than segfaulting.
> UI: Don't double-delete children of deleted widgets

- UI/window-basic-settings.cpp
This PR significantly improves search performance in the hotkey settings tab.
The original author had the right idea with disabling updates so the list would not be continuously updated/redrawn while the search loop is updating visibilities, but they set it on the wrong element. Disabling the layout instead improves things significantly with large scene collections.
Also includes some smaller optimisations to avoid some operations (`toLower()`/getting combinations) unless necessary which speeds up the loop a tiny bit.
Makes search usable with the example collection linked in #6081.
Searched some hotkeys, no longer was afraid of dying of old age while it updates
> UI: Massively improve hotkey search performance

- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.hpp
The `sliderMoved` signal doesn't trigger when clicking on the slider, only the `valueChanged` signal. According to QTBUG-72995 this is intentional, since the documentation states that `sliderDown` also needs to be true for the sliderMoved signal to be triggered. As for why `sliderDown` isn't true when clicking, or why that would even be necessary for a signal that should trigger when the slider is moved (and it very clearly moves) remains a mystery.
Also gets rid of the wrong usage of the `on_foo_bar` slot declaration, which should only be used for signals where the sender is part of a UI file and it gets connected automatically. While it of course is possible to connect it manually, this is against convention and can cause confusion. In this case it was particularly wrong since even if …
> UI: Use valueChanged() signal for T-Bar everywhere

- UI/data/locale/en-US.ini
- UI/window-basic-filters.cpp
- UI/window-basic-properties.cpp
Adds a confirmation dialog before resetting properties (filters or sources) to defaults:
Requested by @Warchamp7 
1. Clicked "Defaults"
2a. Clicked "No" => Nothing happened
2b. Clicked "Yes" => Properties reset
> UI: Add confirmation dialog for resetting properties

- UI/data/locale/en-US.ini
- UI/forms/OBSBasicSettings.ui
- UI/window-basic-settings.cpp
Disables the "Enable Replay Buffer" checkbox in Advanced output mode if the recording type is set to "Custom Output (FFmpeg)" and adds a label stating why it's disabled.
Closes #4948
Switched back and forth between normal and custom FFmpeg Output, checked that the checkbox is disabled and the text is visible, and that the checkbox is enabled and the text invisible otherwise.
> UI: Disable replay buffer checkbox when using custom FFmpeg

- libobs/obs-source.c
Fixes compiler errors due to non-exhaustive switch statement for video formats introduced by https://github.com/obsproject/obs-studio/pull/7818.
New video formats introduced for ProRes 4444 encoding have not been implemented in function calls used for video decoding, which makes the switch statements non-exhaustive.
This does not functionally change the status quo (decoding ProRes 4444 files could still be broken because libobs does not explicitly handle the colour format).
@jpark37 LMK if you feel like the formats should be properly implemented instead (if I'm not mistaken this does mainly affect ProRes 4444 + XQ playback, not recording).
Compiled on macOS with extended warnings enabled and checked ProRes 4444 recordings.
> libobs: Fix non-exhaustive switch statements introduced by ProRes 4444 support 

- UI/obs-app.cpp
- UI/window-basic-main.cpp
Consists of three small commits that all are related / kinda depend on each other. I'm all for atomic commits but don't think separate PR's are needed here. Feel free to disagree with me and let me know.
1. Nearly everything that involves portable mode is ifdef'ed, just not actually setting the variable. This would mean that if the `--portable` argument was passed on unsupported systems, the log would show portable mode as enabled even though it's effectively no-op. This can lead to confusion and shouldn't be the case.
2.  Portable mode is meant to be separated from the rest of the system, and as such it doesn't make sense to load globally installed plugins there. On Windows, there currently are only two major plugins that I'm aware of (StreamDeck and StreamFX) that install themselves …
> UI: Don't load global plugins in portable mode; Minor portable mode fixes

- plugins/linux-pipewire/pipewire.c
Import PipeWire buffers respecting previously applied transformations.
The wlroots Portal implementation won't transform buffers and as such a screencast is displayed wrongly if the output is rotated. This MR aims to prototype PipeWire buffer transformation informations to read the screencontent correctly from the rotated buffer.
No test available yet.
> PipeWire buffer transform

- UI/hotkey-edit.cpp
- UI/hotkey-edit.hpp
Avoid creating the icon when not necessary.
Shaves off a couple seconds when loading hotkeys for large scene collections.
Compared profiler results when loading hotkeys. It was slightly faster.
> UI: Defer creation of hotkey dupe icon until needed

- UI/obs-app.cpp
This feels like a dirty hack, and it probably is, but it doesn't seem to break anything (as far as I tested).
The function in Qt this effectively disables is annotated with `this is too expensive !!!` - they're right about that one!
Make hotkeys faster for large scene collections.
Checked with profiler. This function used to be the single slowest thing and now it's gone.
For my favourite stress test (`Massive.json`) this speeds up loading the hotkeys list by eleminating most of the time the UI would spend unresponsive *after* it has finished creating all the widgets (creating the widgets itself is still slow tho).
> UI: Set QT_NO_SUBTRACTOPAQUESIBLINGS env var 

- libobs-d3d11/d3d11-subsystem.cpp
DXGI_ADAPTER_DESC's DedicatedVideoMemory and SharedSystemMemory are
unsigned long long int, but we were logging them as unsigned int. For
GPUs with memory values higher than 4294967295, the logged value would
roll over. Use %PRIu64 (%llu on VS2022) instead of %u in the log call.
Want accurate log files.
Checked on my AMD system. GPU-Z shows the RX 6600M as having 8192MB of RAM.
Before:
```
Adapter 0: AMD Radeon RX 6600M
Dedicated VRAM: 4247564288
Shared VRAM:    3943546880
```
After:
```
Adapter 0: AMD Radeon RX 6600M
Dedicated VRAM: 8542531584
Shared VRAM:    8238514176
```
> libobs-d3d11: Log D3D11 adapter memory correctly

- UI/CMakeLists.txt
- UI/window-basic-main-outputs.cpp
- UI/window-basic-main-outputs.hpp
- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-basic-vcam-config.cpp
- UI/window-basic-vcam-config.hpp
- UI/window-basic-vcam.hpp
Prepare the dialog to be extended with new feature like #5383 by moving some code elsewhere.
Most of the "dialog" code does not belong there and was moved.
- Struct & enum moved to their own header.
- The config code moved to the main window code.
- The video mix code is moved to output handler.
Also a fix the issue where if a scene/source is renamed, it is not in the vcam config.
Avoid putting those change directly in #5383 and allow a separate review.
I tested:
- If the config was saved
- Starting the VCam with a source/scene/internal
- Changing the config while the VCam is active.
- Re-starting the VCam
> UI: Refactor Virtual Camera source selector dialog

- deps/media-playback/CMakeLists.txt
- deps/media-playback/media-playback/cache.c
- deps/media-playback/media-playback/cache.h
- deps/media-playback/media-playback/decode.c
- deps/media-playback/media-playback/media-playback.c
- deps/media-playback/media-playback/media-playback.h
- deps/media-playback/media-playback/media.c
- deps/media-playback/media-playback/media.h
- plugins/obs-ffmpeg/obs-ffmpeg-source.c
- plugins/obs-transitions/data/locale/en-US.ini
- plugins/obs-transitions/transition-stinger.c
Adds the ability to fully preload stinger videos to RAM before playback, greatly improving stinger playback performance.
Stingers -- and especially track matte stingers -- are subject to real time decoding, thus if there are not enough computing power available, decoding can lag, causing stingers to play back slowly or stutter, which just kind of ruins a nice broadcast. It's even worse when track matte stingers are in use, because they require twice the decoding power of normal videos.
To solve this, add an option to fully decode and preload video files into RAM to completely eliminate decoding from the equation, and ensure smooth playback of the stinger's video and greatly improving stinger playback performance (at the cost of RAM usage, of course).
Tested with various stinger transition …
> Add option to fully decode and preload stinger video files into RAM

- libobs/obs-scene.c
In obs-scene.c file, function scene_audio_render() has following code.
```
pos = (size_t)ns_to_audio_frames(sample_rate,
source_ts - timestamp);
count = AUDIO_OUTPUT_FRAMES - pos;
if (!apply_buf && !item->visible &&
!transition_active(item->hide_transition)) {
item = item->next;
continue;
}
obs_source_get_audio_mix(source, &child_audio);
for (size_t mix = 0; mix < MAX_AUDIO_MIXES; mix++) {
if ((mixers & (1 << mix)) == 0)
continue;
for (size_t ch = 0; ch < channels; ch++) {
float *out = audio_output->output[mix].data[ch];
float *in = child_audio.output[mix].data[ch];
if (apply_buf)
mix_audio_with_buf(out, in, buf, pos,
count);
else
mix_audio(out, in, pos, count);
}
}
```
what this snippet code basically do is to align source's audio_output_buf to the mininum timestamp, so here `pos` and …
> libobs: Fix bug with scene_audio_render() 

- plugins/obs-ffmpeg/obs-ffmpeg-source.c
This is an option that while very powerful also provides a footgun for users if they don't have enough memory. It will be helpful for support volunteers to be able to see if the option has been enabled.
Want to avoid a situation where people to come to support "OBS makes my computer super slow" (after some YouTuber tells their users to enable this setting everywhere in some best settings video) and the support people not being able to spot it.
macOS 13.2
Checked and unchecked the "Preload Video to RAM" setting for stingers and noticed how the log switches from "no" to "yes".
> obs-ffmpeg: Add full_decode to media source log

- UI/audio-encoders.cpp
Removes an unused variable triggering compiler errors in CMake 3.0 rework.
Commit 2a2d8fc1bb2943d798aab3747b262b158aa9add2 removed the only usage of the `output_channels` variable, but didn't remove it. This PR fixes the issue.
Tested on macOS 13 with Xcode and extended warnings enabled.
> UI: Remove unused variable in PopulateBitrateMap

- libobs/util/utf8.c
> libobs: Make wcs<->utf8 conversion consistent

- docs/sphinx/reference-core.rst
- docs/sphinx/reference-frontend-api.rst
- docs/sphinx/reference-scenes.rst
- docs/sphinx/reference-sources.rst
Added more info on some functions
It is not immediately clear how to get `obs_scene_t` objects from `obs_enum_scenes`, since it just `obs_source_t` just like `obs_enum_sources`. Developers may also find `obs_enum_scenes` to enumerate in an unexpected order, especially as plugins need to enumerate scenes to show them as options, in which case it has to be in order. Adding a link to the frontend function reduces a lot of development time. The same way, some developers would not expect `obs_scene_enum_items` to start at the bottom, I've seen a few plugins list scene items in a reversed order because this info is not in the docs. Also added the info that `obs_source_get_weak_source` and `obs_weak_source_get_source` returns an incremented reference, which was not clear, especially since we …
> docs: Add clarifications

- UI/forms/OBSBasicSettings.ui
Revise tab stop order of updater (`updateChannelBox` and `enableAutoUpdates`) and `hideOBSFromCapture`.
The tab stop order should be well aligned at least inside a layout.
- Checked on Linux, Fedora 36 with a modification to not remove the updater settings.
- Checked the tab stop on qtcreator by eyes.
Without this PR:
With this PR:
I didn't test with Windows.
> UI: Fix tabstops on settings dialog

- libobs/graphics/device-exports.h
- libobs/graphics/graphics-imports.c
Marks function symbols intended to be exported to _actually_ be exported even with visibility set to "hidden".
As clang and gcc use "default" visibility (as in "not hidden") when no visibility is specified, all functions are implicitly exported.
When changing default visibility to "hidden", the corresponding symbols are not exposed anymore and linking fails. This PR updates all functions signatures that were added in recent commits but not set to be EXPORTed.
Also makes required OpenGL imports for texture sharing on macOS mandatory.
Tested on macOS and Linux with clang and gcc.
> libobs: Fix device functions not marked as EXPORT

- UI/frontend-plugins/frontend-tools/captions-handler.hpp
- UI/window-basic-settings.cpp
- cmake/Modules/CompilerConfig.cmake
- libobs/util/windows/ComPtr.hpp
- plugins/obs-ffmpeg/jim-nvenc.c
- plugins/win-capture/graphics-hook-ver.h
- plugins/win-dshow/virtualcam-module/virtualcam-module.cpp
Enable compiling OBS with `/permissive- /Zc:__cplusplus /Zc:preprocessor /std:c17`.
This is the bare-minimum to get OBS (minus `enc-amf`) to compile and run with these options.
See: https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview
Draft because I'm not 100% happy/sure about some of these. 
Want to not use `/permissive-` anymore and use more consistent build options with *nix.
Build and ran OBS.
> Support MSVC standard conforming mode

- UI/win-update/updater/updater.cpp
Makes applying delta patches multi-threaded.
On its own this shaves off about 3 seconds when doing 28.1.2 => 29.0.0 on my system. Together with #8106 this speeds up the entire process quite a bit.
The speedup when patching multiple large files (e.g. CEF) as in my 27.2.4 => 29.0.0 test case I use for #8074 is a decent bit larger. 
Gotta go fast(er).
28.1.2 -> 29.0.0 with official update server.
> updater: Multi-threaded delta patching

- plugins/linux-pipewire/pipewire.c
Various legibility and quality related cleanups.
I dislike code that confuses me, and try to make it less confusing when I see it.
- Run OBS in Linux / Wayland
- Check that everything still works
> More PipeWire cleanups

- UI/win-update/updater/updater.cpp
Removes remaining support for updating a 32 bit OBS build from the updater.
(Ideally this should be merged after
* #8070
* #8114 
* #8115 
so I only have to solve conflicts (if any) in this PR and 
* #8074
)
Code cleanup before more updates.
OBS has not provided 32 bit releases since 28.0.
Updater still works.
> updater: Remove 32-bit Support

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Added a new service, Enchant.events, to the rtmp-services list. I belong to the development team of Enchant.
Help users to connect to Enchant easier.
Tried on a local build and confirmed working.
Incremented version on rtmp-services/data/package.json
Added service info to rtmp-services/data/services.json
> rtmp-services: Add Enchant.events to service list

- libobs/media-io/video-io.c
By adding the range data we can get successful handling of full range color via custom ffmpeg output. Previously, it would always default to 0 which would would yield partial/limited output.
Adds colorspace info. Currently the the output file is correctly tagged, but not undergone the actual conversion.
Big thank you to @RytoEX who helped me work out some of this libobs stuff, and to @mia-is-baka for their code submission.
Fixes https://github.com/obsproject/obs-studio/issues/7602
Fixes https://github.com/obsproject/obs-studio/issues/8199
Fixes https://github.com/obsproject/obs-studio/issues/5363
https://github.com/obsproject/obs-studio/pull/8202 was closed.
On Win10 22H2 I ran thru a battery of codecs and containers to test and observe said change, and compare with expected behavior from …
> libobs/media-io: Add color range and colorspace data to conversion

- libobs/obs-encoder.c
Adds an additional check to `obs_encoder_set_scaled_size` that disables scaling if the requested scale resolution matches the output resolution.
DRAFT: Is this the correct place to do this? Should the logic also / instead be in the UI to not request the scaling in the first place?
Users would often tick "Enable scaling" in Advanced Output mode and then leave the resolution the same as their main resolution. OBS would dutifully call `obs_encoder_set_scaled_size` with the same resolution as the output, causing an unnecessary pass through swscale and skipping hardware  encoders like jim-nvenc that don't handle rescaled output.
Ran OBS, tried to "rescale" 1080p to 1080p, scaling was disabled and jim-nvenc worked.
> Disable encoder scaling if scaled resolution matches output resolution

- plugins/obs-transitions/data/locale/en-US.ini
- plugins/obs-transitions/transition-stinger.c
Adds a long description for the "Preload Video to RAM" outlining RAM usage.
Uses the formula `(1920 * 1080 * 1.5 * 60 + 48000 * 4) * 5 = 934.080.000` (1920*10180 pixels, NV12, 60 FPS, 48kHz Audio, 5 seconds) for the "~1 GB" number.
I'm scared of users (and potentially bad tutorials).
This should point out that the option may not be suitable on some lower-end systems (when doing something besides OBS, like playing games).
macOS 13.2
See screenshot above (the position of the `(?)` is an existing bug at least on macOS that's not caused by this PR).
> obs-transitions: Add long description for full decode option

- UI/obs-app.cpp
Adds a mutex that is locked when writing to the log file and removes inline on the function.
fstream is not thread-safe and the act of writing the string and the newline are two separate operations which could execute concurrently in multiple threads, resulting in lines joining together followed by two newlines (example: https://obsproject.com/logs/H9kyOhPqQEOwEXeW)
Ran OBS, it worked.
> Add mutex for writing to the log file

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
When iterating over an array of structs we incorrectly check for a null pointer, but the actual sentinal value is the empty struct.
Crash fix when starting recording due to trying to copy the null string from the sentinel.
The crash when starting recording due to copying a null char * no longer occurs.
> obs-ffmpeg: Fix crash during ratecontrol check

- libobs/obs-source.c
Hold the async mutex when calling `set_async_texture_size`.
Calling `set_async_texture_size` without holding `async_mutex` is dangerous as `cur_async_frame` could be changed / freed by another thread. When running OBS under cuzz (race condition exploiter) I experienced a crash in this code.
Ran OBS and it didn't deadlock.
> Hold async mutex when calling set_async_texture_size

- UI/window-basic-preview.cpp
If the scene item was rotated greater than 45 degrees, and flipped vertically or horizontally, the spacing helpers would be drawn incorrectly. This fixes the issue by checking the scale before the rotation, instead of after.
Before:
After:
Fixes bug
Rotated and flipped scene item
> UI: Fix spacing helpers when rotated and flipped

- UI/properties-view.cpp
Makes the label have colors based on themes, instead of hard coding.
Looked through some TODOs in the code, and noticed some old code where the label colors were still hardcoded. This code was before themes were a thing.
Looked at properties to make sure labels looked correct
> UI: Don't hardcode properties label colors

- libobs/util/platform-windows.c
If the recording path is left empty in Settings, a leak can occur in window-basic-stats.cpp because a bmalloc is called for a size 1. This fixes the leak by checking against the path.
Leaks are bad.
The leak was found by having an empty path in Settings/output/recording.
OBS then logs 5 leaks.
Admittedly this path should not be empty.
But it's better to be on the safe side even for stuff which we think users won't do.
OBS does not log any leak after the fix.
> UI: Fix leak with empty path in stats

- UI/window-basic-main.cpp
If OBS is set to minimize to system tray on startup and studio mode is enabled, the preview would be disabled when showing OBS, if the preview in non studio mode was disabled.
Fixes bug I've found
Made sure preview was enabled in studio mode when click show from system tray, when set to minimized on start.
> UI: Fix preview disabled in studio mode

- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.hpp
The program scene would be incorrect if the tbar was released at its original position.
Fixes https://github.com/obsproject/obs-studio/issues/6586
Checked to see if scene was correct when releasing tbar and ran other studio mode function to make sure nothing broke.
> UI: Fix wrong program scene if tbar is aborted

- UI/window-basic-preview.cpp
- UI/window-basic-preview.hpp
Prevents the preview from zooming in or out too far.
Min zoom: 10%
Max zoom: 1000%
Fixes https://github.com/obsproject/obs-studio/issues/4115
Zoomed preview
> UI: Set min/max zoom levels for preview

- plugins/mac-syphon/syphon.m
Removes unused functions and explicitly casts higher-precision CoreFramework data types into lower precision obs-module types.
Ensures compatibility with CMake rework and extended warnings.
Compiled successfully on macOS 13.
> mac-syphon: Fix warnings in ObjC code for CMake rework

- UI/slider-ignorewheel.cpp
- UI/slider-ignorewheel.hpp
- UI/window-basic-main-transitions.cpp
Changes the T-Bar so that it can only be dragged and not clicked at all.
Follow-up to #7347.
Requested by @Warchamp7 in off-thread discussions about #7347.
*Edit: Maybe. That was what I remembered at least. On the PR itself he wasn't completely sure. So we'll see, maybe this PR will get closed in the end.*
macOS 13.2
Tested by clicking on the T-Bar and seeing that nothing happens, and by dragging it and seeing that it still functions when dragging.
> UI: Make T-Bar unclickable

- .github/workflows/main.yml
- CI/macos/appcast_convert.py
- CI/macos/appcast_download.py
Adds CI job to download previous builds, generate deltas, and create a new appcast when a notarised build is created.
Based on changes in #7723 (new URL, channels, combined arm/x86 feed).
Stop Jim from editing XML manually. Get Mac users some deltas.
Has not. I do not have the necessary credentials and haven't done a mock setup yet.
> CI: Create Sparkle appcast and deltas on tag

- libobs/util/config-file.c
Changes the config file implementation to save default values in case no user-provided value has been set.
Migrations make life diffcult when we change defaults. So just save values even if the users never changes them from default.
Locally in portable mode, checked that generated config had all keys with default values written.
> libobs: Write default values to config

- UI/CMakeLists.txt
- UI/frontend-plugins/aja-output-ui/CMakeLists.txt
- UI/frontend-plugins/decklink-captions/CMakeLists.txt
- UI/frontend-plugins/decklink-output-ui/CMakeLists.txt
- UI/frontend-plugins/frontend-tools/CMakeLists.txt
- cmake/Modules/CompilerConfig.cmake
- cmake/Modules/ObsHelpers_Windows.cmake
- plugins/obs-vst/CMakeLists.txt
Makes Windows builds *mostly* reproducible using undocumented (but working) MSVC compiler/linker options and dropping the Qt Resource Compiler version to 1 (since 2+ includes last-modified timestamps).
PDBs won't be identical due to lambdas having random identifiers but they are compatible, meaning that it would be possible to also create debug symbols for any build after the fact.
ToDo:
+ CMake bug: https://gitlab.kitware.com/cmake/cmake/-/issues/15865 (7 years old D:)
+ Possible workaround: https://github.com/boostorg/stacktrace/issues/55#issuecomment-984782636
+ Seems to be fixed by #8377 
We eventually want to have fully reproducible builds for OBS and its dependencies. For the reason why you may want that, see https://reproducible-builds.org/docs/buy-in/
Aside from the security …
> A first foray into reproducible builds

- UI/update/shared-update.cpp
Switched `QuickReadFile` to use binary mode when reading files as text mode converts `\r\n` to just `\n` which caused a premature `EOF` as the size determined by seeking to the end would no longer match the amount of data that is actually read into the buffer.
Also throws in a mutex for good measure since on Windows it can theoretically try to read the public key file from multiple threads at the same time.
Reading the public key could fail if the file was in CRLF format. 
Started OBS, no longer saw read failures.
> Fix failures in reading public key file

- UI/obs-app.cpp
Remove setting of a default locale in the UI.
With 75693a6682a81088c0a0b8416ef8b51d43ac8a09 deafults are now also treated as user-set values if provided. This causes an issue with automatic locale switching no longer working as the UI code assumes the user has set the default locale.
Launched OBS on my system (`en-GB`) and it correctly loaded "English (UK)" as the locale.
> UI: Do not set default locale

- plugins/mac-virtualcam/src/dal-plugin/CMSampleBufferUtils.mm
- plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
👋 First time contributing to the OBS project, please let me know if anything is unclear or needs improvement. Happy to improve this PR where necessary to get this merged.
The `fillFrame` method of the mac-virtualcam plugin is creating samples directly using the value from `mach_absolute_time()` as `hostTime`. This assumes this value is in nanoseconds, while it is in fact in mach tick units. On Intel macs mach tick units will be exactly 1 nanosecond resulting in valid values, but on Apple Silicon macs this is no longer the case.
This results in sample buffers with the placeholder image that have much lower presentation time stamps than the samples containing content produced by OBS. In previews/live streams this shows due to the last content sample being shown frozen until the whole buffer …
> mac-virtualcam: Fix incorrect PTS on Apple Silicon as well as PTS being rounded

- UI/CMakeLists.txt
- UI/obs-app.cpp
- UI/obs-app.hpp
- UI/win-dll-blocklist.c
This PR implements a way to block specific DLLs from loading into OBS by way of a `NtMapViewOfSection` hook. This is useful to block known problematic DLLs from injecting that end up causing OBS crashes or other undesirable behavior. DLLs are matched by path suffix, for example `\BadApplication\StupidHook.dll` to only block StupidHook from the BadApplication directory, or `\GenericHook.dll` to match all DLLs with that name.
Currently the list of DLLs is hard coded - this list has been built up over the years since OBS Classic, so while initially it looks quite large, the rate of change is expected to be low. As the blocking hook has to be installed as early as possible to be effective, using methods like loading JSON from an auto updated list is less feasible as the libobs API is not yet …
> Add DLL blocking functionality for Windows

- plugins/obs-vst/mac/VSTPlugin-osx.mm
Fixes leaks detected by clang-analyzer.
Ran clang-analyzer to double-check another PR I'm working on and got annoyed by these findings.
Compiles successfully and no more complaints about obs-vst.
Didn't run with broken VST's as I don't know how I would get them, but the changes are pretty straightforward. We're creating the objects, and we need to release them (see [The Create Rule](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029)).
> obs-vst: Fix memory leaks on macOS when VST's fail to load

- UI/window-remux.cpp
Raises the remux dialog after a file got selected on macOS to make sure it doesn't get hidden behind the main window. See QTBUG-42661.
Fixes https://github.com/obsproject/obs-studio/issues/7788
macOS 13.2.1
Window now pops up again instead of disappearing behind the main window. After selecting the directory to save the file in, the `raise()` call seems to not be necessary.
> UI: Re-raise remux dialog after selecting file on macOS

- UI/xdg-data/CMakeLists.txt
- UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Set the `flathub::manifest` key in the AppStream file.
Currently, the manifest URL on Flathub Beta points to the deprecated manifest hosted on Flathub. The flathub::manifest key is an undocumented attribute that will update the website to use the proper location.
- Tag and release OBS 
- Notice the CI workflow in the tags generate AppStream metadata with the commit hash
> UI: Set flathub::manifest to manifest used to build Flatpak

- deps/media-playback/media-playback/decode.c
Fixes version check to work correctly with major versions > 57 (current is 58.3).
Should fix #8441
Do I really need to explain this?
CI will tell me if I'm right.
> media-playback: Fix libavutil version check

- UI/installer/mp-installer.nsi
This fixes issue #7935
This adds quotes around the UninstallString in the registry.
Fixes #7935
We also made the same mistake in one of our programs.
A customer noted that on a Swedish installation the un-installation did not work until they added the quotes.
No test has been made by me for the change for OBS-Studio, but this is the exact same fix as for our program.
> UI/installer: Add Quotes around UninstallString

- UI/record-button.cpp
Passing the parent of a QLayout sets it directly as the top-level layout (as per the [QLayout docs](https://doc.qt.io/qt-6/qlayout.html#QLayout)). This is obviously not what is intended here. Luckily it doesn't even work since the main window of course already has a layout which would need to be explicitly removed before, but it makes Qt yell at us for trying.
```
QLayout: Attempting to add QLayout "" to OBSBasic "OBSBasic", which already has a layout
```
macOS 13.2.1
Button and everything still works.
Confirmed with a debugger and an explicate destructor that the layout still gets destroyed at the same time as before, which is with the dock (ownership was likely the original intent of passing the parent in the first place, and with QWidgets is correct thing to do, but not with QLayouts). …
> UI: Don't try to make OBSBasic parent of ControlsSplitButton

- UI/window-basic-main-scene-collections.cpp
- libobs/obs-data.c
- libobs/obs-data.h
When a scene collection is exported, sort sources by name and pretty-print the output.
This also adds new functions to `obs_data` to get/write JSON in a prettified format.
As of 0dc1e01b5bed35f1514ad32ed4beb5155ca53eb4 the JSON has been saved in minified/"compact" form meaning that it's just one long line.
Opening those files in editors can perform extremely poorly, and tracking changes between them is additionally made difficult due to the order of sources being unreliable.
Some users use git to store and version their scene collection, or work on them collaboratively (e.g. GDQ), and have complained about the instability of the exported collections resulting in large diffs.
Exported some collections, verified they're now pretty-printed and sorted by name.
- Tweak (non-breaking change to …
> UI: Sort and pretty-print exported collections

- UI/window-basic-filters.cpp
Expands the filter_compatible check to return false if the source isn't async and the filter is not an audio filter, filtering out e.g. the "Video Delay (Async)" filter from browser sources (which have audio but don't have async video).
Follow-up to https://github.com/obsproject/obs-studio/pull/5670.
Reported on Discord that browser sources had the "Video Delay (Async)" in the list, but adding them wouldn't do anything since browser sources have synchronous video.
macOS 13.2.1
Tested that in the async list:
- Browser Source (synchronous video, with audio) now only shows audio filters (3-Band EQ, ..., VST)
- Media Source (async video, with audio) still shows all async filters (3-Band EQ, ..., VST, Video Delay (Async))
- Audio Output Capture (only audio) still only shows audio filters …
> UI: Don't show video-only async filters for synchronous sources

- UI/window-basic-settings.cpp
Deletes the Update section of the settings on macOS when OBS is built without Sparkle.
When building without sparkle, there would be an "Update" section in which one would choose the channels, but the dropdown wasn't populated as OBS was build without the updater:
macOS 13.2.1
Built without Sparkle, section is gone.
> UI: Don't show Update section in settings when built without Sparkle

- UI/window-basic-main-scene-collections.cpp
- cmake/Modules/FindLibUUID.cmake
- docs/sphinx/reference-core.rst
- docs/sphinx/reference-libobs-util-platform.rst
- docs/sphinx/reference-sources.rst
- libobs/CMakeLists.txt
- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs-scene.c
- libobs/obs-service.c
- libobs/obs-source.c
- libobs/obs.c
- libobs/obs.h
- libobs/util/platform-nix.c
- libobs/util/platform-windows.c
- libobs/util/platform.h
- Adds libobs platform util for creating UUIDs
- Adds `uuid` to `obs_context_data`
+ Only saves/restores UUIDs for sources
- Adds `obs_get_source_by_uuid()` to retrieve a source by it's UUID
If #8229 gets merged this PR will be updated to use a separate hash table for GUID based lookups.
Developers of plugins and third-party integrations have asked for UUIDs for a long time so that, for example, name changes done via the UI do not result in a desynchronisation between their app's and OBS's state.
UUIDv4 is a standardised format that is supported and understood by various frameworks, databases, and standard libraries. They can be serialised/deserialised for storing without any extra work, and can be used in databases with better performance than a generic string type. Additionally, most …
> Add unique identifier (UUID) to sources

- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
Remove the AAC coder option passing to ffmpeg in `ffmpeg_aac`.
This reverts commit aa58b9cf5f3e030958d23b6d147439e09e49d485.
FFmpeg has reverted their default AAC encoder from fast to twoloop at the commit [660d1d8e3b](https://github.com/FFmpeg/FFmpeg/commit/660d1d8e3b).
They claimed that `twoloop` has much better rate control management, making it closer to CBR, and it sounds much better.
The `twoloop` as the default is included in n5.0 and later. And, obs-deps is now pointing to n5.1. Hence, just removing the option will choose `twoloop`.
OS: Fedora 36
Waveforms below show a comparison among `libfdk_aac`, current `ffmpeg_aac`, and this PR's `ffmpeg_aac` for 440 Hz sine wave.
I guess sine wave with loud volume is a corner case for FFmpeg fast coder so that the difference is significantly …
> Revert "obs-ffmpeg: Use FFmpeg's "fast" AAC encoder by default"

- UI/win-update/updater/CMakeLists.txt
Fixes linker error when trying to build OBS in debug with the updater enabled
*Somebody* forgot to add this again after already causing the same issue once this week.
Built in debug.
> updater: Fix building in Debug

- plugins/linux-pipewire/pipewire.c
If we receive an empty cursor bitmap - one without valid size - we should hide the cursor. Do so by clearing the texture.
This fixes visible cursors when recording various games with Wayland compositors.
Closes https://github.com/obsproject/obs-studio/issues/4895
Locally tested, asking other people to test as well.
> linux-pipewire: Clear cursor texture on empty bitmap

- plugins/win-capture/data/compatibility.json
- plugins/win-capture/data/locale/en-US.ini
Remove the redundant "-" in the CSGO launch option.
Remove Steam url language code. Users will be redirected to their own language page.
https://github.com/SteamDatabase/GameTracking-CSGO/blob/be343ab9d6a2cd4cfb1ff917eeaf0ffc22d9a6b3/csgo/bin/linux64/client_client_strings.txt#L3455
It is not the latest client version, but launch option has not changed.
> win-capture: Remove the redundant "-" in the CSGO launch option and Steam url language code

- UI/auth-restream.cpp
- UI/auth-restream.hpp
- UI/auth-twitch.cpp
- UI/auth-twitch.hpp
- UI/auth-youtube.cpp
- UI/auth-youtube.hpp
- UI/forms/OBSBasic.ui
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-extra-browsers.cpp
**Dependency of:**
- https://github.com/obsproject/obs-studio/pull/7637
- https://github.com/obsproject/obs-studio/pull/7638
Groundwork for other PRs and also avoid creating QActions by using the one included in the dock by modifying its connections making it usable even while the docks are locked.
Preparation for PRs that depends on this one.
- Test docks toggle with docks locked or not
- Connect to services integration
- Modify custom browser docks
> Refactor main docks toggle and integration and browser docks

- UI/obs-app.cpp
- plugins/obs-outputs/rtmp-stream.c
Removes two checks for Windows 7 I stumbled over during other work.
Windows 7.
N/A
> Remove Some Windows 7 leftovers

- UI/win-dll-blocklist.c
Blocks old versions of the Vtuber Maker `lib64_new2.dll` which don't have the Unity Capture deadlock fix implemented.
Freezing OBS is bad.
Simulated using the NVIDIA Broadcast filter as I don't wish to install Vtuber Maker. Seemed to work.
> Add old Vtuber Maker versions to DLL blocklist

- UI/window-basic-main-outputs.cpp
- plugins/obs-outputs/rtmp-stream.c
Fixes #7900
"New Socket Loop" and "Low Latency Mode" RTMP options are only available on Windows.
Those options should be ignored and forced-disabled on non-Windows builds.
Fix it.
Not tested, I may test it later.
> obs-outputs: Disable Windows-only options on non-Windows

- UI/properties-view.hpp
- UI/window-basic-filters.cpp
Calling `RefreshProperties` on a properties view only rebuilds the widgets from the currently held `obs_properties_t` object. This is useful for when a modified_callback changes visibility of items.
It does not re-fetch the `obs_properties_t` from the object again. Such re-fetching is however required when the `obs_properties_t` itself wasn't updated, for example after a simple `obs_source_update` call (which is what the defaults button does). `OBSPropertiesView::ReloadProperties` is the function that does this before itself calling `RefreshProperties` and as such is the correct function to call.
This brings the filters window correctly in line with the source properties window.
In fact, I don't believe there is a reason for anything except the properties view itself to ever simply call …
> UI: Properly update filter properties after resetting

- deps/file-updater/file-updater/file-updater.c
Changes the file updater to use `LOG_INFO` instead of `LOG_WARNING` in its `info` logging macro.
Noticed when looking at a log file posted on an unrelated issue that a successful file update would print a warning log line and went "huh?"
Tested by adding additional logging calls and confirming that `info` uses `info` severity and `warn` uses `warning` severity.
> deps/file-updater: Use LOG_INFO log priority for info logging

- UI/window-basic-settings.cpp
Fixes a crash that happens when saving the general settings but building without sparkle.
With the changes to the macOS updater (update channels PR and follow-up PRs) the "Enable Auto Updates" checkbox now no longer gets shown when building without sparkle and deleted instead.
That means we shouldn't perform `WidgetChanged` on it.
macOS 13.2.1
Saving general settings no longer crashes.
> UI: Fix macOS crash when saving general settings without Sparkle

- UI/api-interface.cpp
- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.cpp
- UI/window-basic-preview.cpp
- UI/window-basic-transform.cpp
- libobs/obs-scene.c
- Swap the order of `obs_source_release` and `obs_source_remove` in `OBSBasic::on_actionAddScene_triggered()`.
- Use `OBSSource` and `OBSScene` types instead of `obs_source_t` and `obs_scene_t`.
I'm enabling GCC's `-Wuse-after-free` option to detect use-after-free of `bfree` and `obs_*_release` in [this branch](https://github.com/norihiro/obs-studio/commits/bfree-warning). Though this change is not finalized, I realized some codes are dangerous in multi-thread.
For example, creating a group and another thread removes the creating group by finding from an updated scene-item list. Such a non-sense operation won't happen in real but I think the code would be better to be revised.
OS: Fedora 36
1. Run OBS Studio
2. Activate the majority of the modified code (exceptions are …
> UI,libobs: Fix possible use-after-free

- test/test-input/sync-pair-vid.c
Add `UNUSED_PARAMETER` to resolve errors.
A source `test-input` is not build in CI and the source is now causing compile errors.
OS: Fedora 36
Build with cmake option `-DBUILD_TESTS=ON`.
Built the source and checked `Sync Test Pair (Audio)` and `(Sync Test Pair (Video)` work.
> test: Fix unused-parameter warnings in test-input

- docs/sphinx/reference-libobs-util-platform.rst
- libobs/util/platform.c
- test/cmocka/CMakeLists.txt
- test/cmocka/test_os_path.c
This PR includes these changes.
- libobs/util: Simplify implementation of `os_get_path_extension`
In current implementation, it allocate memory, replace `\` with `/`, and calls two `strrchr`. This PR will just iterate two times without allocating the memory.
- docs: Clarify a dot is included in the extension
- test: Add a test for `os_get_path_extension`
Also considered other implementations below but the code in PR would be the best balance of readability and simplicity.
This code has just one interaction but I feel it is worse to read.
```c
const char *os_get_path_extension(const char *path)
{
const char *ext = NULL;
for (; *path; path++) {
switch (*path) {
case '.':
ext = path;
break;
case '/':
case '\\':
ext = NULL;
}
}
return ext;
}
```
This is similar to the original code in terms …
> libobs/util: simplify implementation of os_get_path_extension

- plugins/linux-v4l2/v4l2-input.c
Fixes very large log sizes and STDOUT spam when camera does not report framerate.
Code taken from https://github.com/Mikael-Lovqvist/obs-studio/commit/3cd5742be5168f625558c14c1b38fedf23116277
This adds a fallback framerate if the camera does not report one. It defaults to 10 frames per second, but can be manually changed later in the UI (included).
- Fixes https://github.com/obsproject/obs-studio/issues/4926
- Fixes https://github.com/obsproject/obs-studio/issues/8397
Tested on `Linux hostname 5.16.11-arch1-1 #1 SMP PREEMPT Thu, 24 Feb 2022 02:18:20 +0000 x86_64 GNU/Linux`. Built with `mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX="/usr" -DBUILD_BROWSER=OFF -DBUILD_VST=OFF -DDISABLE_VLC=ON .. && make -j$(nproc) && mkdir dist && make install DESTDIR=dist`. Tested by checking log …
> linux-v4l2: Fix fallback framerate for camera

- libobs/audio-monitoring/pulse/pulseaudio-enum-devices.c
- libobs/audio-monitoring/pulse/pulseaudio-output.c
- libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
- libobs/audio-monitoring/pulse/pulseaudio-wrapper.h
The Pulseaudio implementation of audio monitoring was actually listing audio sources. This change corrects that, so all possible outputs are available.
While the old code worked for some outputs, not all possible outputs were available. And the actual name displayed, "monitor of x" was wrong.
Closes #4226
Built and tested with an audio source and sink on Fedora Linux. The list of possible monitoring devices is now correct
> libobs: Fix Pulseaudio audio monitoring listing sources

- UI/forms/source-toolbar/media-controls.ui
- UI/media-controls.cpp
The play, pause and restart shortcuts were being called as global shortcuts, being triggered no matter what. This fixes this by calling the shortcut actions only when the media controls widget has focus.
Fixes https://github.com/obsproject/obs-studio/issues/7199
Made sure shortcuts only triggered when the media controls were clicked
> UI: Fix media controls shortcuts being global

- docs/sphinx/reference-core.rst
- libobs/obs-view.c
- libobs/obs.h
Add `bool obs_view_get_video_info(obs_view_t *view, struct obs_video_info *ovi)`
Gets the video settings currently in use for this view context, returns false if no video
Allow to get video info from a view, for example to get the size of a view
Useful for future code to create a projector or virtual camera from the view.
On windows 64 bit with test code in the vertical plugin
> libobs: Add obs_view_get_video_info

- plugins/win-capture/game-capture.c
Fix the mode check for game capture compatibility information.
If the user created a new source and never used the manual mode the first game capture compatibility entry would erroneously be shown.
Created new game capture source, no longer shows wrong info.
> win-capture: Fix compatibility info showing in any mode

- UI/window-basic-main.cpp
- Restore default advance record audio to AAC.
- Enforce stream audio to Opus if FTL, default are AAC so not enforcing them will cause an issue.
Fix it.
Test by using a profile without audio codec settings and a FTL service. Record was AAC and stream was opus.
> Fix audio codec settings change from RFC 45

- libobs/obs-display.c
- libobs/obs-internal.h
NVIDIA driver 527.37 fixes flickering when multiple GPUs are installed.
Gotta go fast.
Clear color is still visible on Windows and Mac.
Flicker verified gone in 528.49.
> libobs: Enable fast clear on Windows always

- UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
- docs/sphinx/reference-outputs.rst
- libobs/obs-output.c
- libobs/obs.h
- plugins/decklink/decklink-output.cpp
These commits move rescaling for DeckLink preview output from FFmpeg swscale on the CPU to the GPU where it is much cheaper.
Also convert from premultiplied alphs to straight alpha to match DeckLink's internal keyer behavior. (External keyer is untested.)
Decrease performance hit of using DeckLink. Trying to get DeckLink in good code shape before adding HDR support.
- 4K -> 1080p preview output is no longer a slideshow.
- 1080p -> 1080p has not regressed.
> decklink: Move preview output rescaling to GPU

- libobs-d3d11/d3d11-duplicator.cpp
- libobs-d3d11/d3d11-subsystem.cpp
- libobs-d3d11/d3d11-subsystem.hpp
- libobs/graphics/graphics-imports.c
- libobs/graphics/graphics-internal.h
- libobs/graphics/graphics.c
- libobs/graphics/graphics.h
- plugins/win-capture/duplicator-monitor-capture.c
- plugins/win-capture/window-capture.c
Same function as the checkbox in window capture for forcing SDR capture when HDR is enabled on a display in Windows settings.
Also plumb support for wide SDR although DXGI chooses narrow anyway?
Stacks on top of #7974.
FIxes #7970.
Users don't want to disable HDR in their Windows settings to capture SDR, and that's reasonable.
Checked display capture of SDR and HDR monitor with and without checkbox enabled.
Checked log output for display capture DXGI/WGC, force on/off, and window capture BitBlt/WGC, force on/off.
> libobs-d3d11,win-capture: Add Force SDR for DXGI duplicator

- plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Fixes FFmpeg mux for recording Opus in MP4.
(Commits adapted from #8289 with lossless specifics removed)
Recording Opus in MP4 should not fail with FFmpeg < 6.0 and be correctly tagged in files.
Tested in #8289
> obs-ffmpeg: Fix muxing non-AAC codecs / Opus in MP4

- UI/window-basic-settings-stream.cpp
Fix inconsistencies that might lead to issue or even a crash.
Note: The else branch should not have been taken in custom server scenarios.
Fix a crash reported on discord: https://discord.com/channels/348973006581923840/374636084883095554/1087384798894501939
Switch from a FTL service to custom (with empty server URL) and the encoder warning shown up. Without the fix it doesn't show.
> UI: Fix inconsistencies in FindProtocol 

- UI/data/themes/Acri.qss
- UI/data/themes/Grey.qss
- UI/data/themes/Light.qss
- UI/data/themes/Rachni.qss
- UI/data/themes/Yami.qss
Add space for right arrow in menu
When making custom menu I noticed that the right arrow was on top of the text.
It looks to me that it is caused by setting the padding for QMenu::item to 6px in the theme.
Now I override only the right padding for QMenu::item to 12px
Before:
After:
The dark and system theme don't set the padding and don't have the issue.
On windows 64 by having only 1 menu item that has a right arrow.
> UI: Add space for right arrow in menu

- UI/audio-encoders.cpp
- UI/window-basic-main-outputs.cpp
Removes unused variables in recently updated source code.
CMake 3.0 rework has stricter warning settings than master branch and will break on unused variables left in code.
Successfully compiled with CMake 3.0 rework active.
> UI: Remove unused variables to fix errors in the CMake 3.0 rework

- UI/window-basic-settings-stream.cpp
- plugins/rtmp-services/rtmp-common.c
I'm an idiot that forgot some migration code in `rtmp_custom` and code to save the protocol in settings.
Fix bugs that I introduced.
Without the fix service like Twitch don't return a protocol and so start streaming fail.
With it, streaming works and protocol is saved in the JSON in the settings.
> Make sure that protocol is set in non-custom services

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
- plugins/obs-ffmpeg/obs-ffmpeg.c
- plugins/obs-ffmpeg/vaapi-utils.c
- plugins/obs-ffmpeg/vaapi-utils.h
Add HEVC support to create HDR videos using FFmpeg VA-API on Linux.
EDIT (jpark37): I have reworked the changes to add NV12 back to support narrow SDR again. I've also consolidated the files, so no new files are added.
HDR streaming.
- HDR video was recorded using "FFmpeg HEVC VAAPI" encoder with AMD hardware device selected. Video parameters were tested using the `ffprobe` tool. The recorded video was played using `mpv`.
- HDR Video was streamed to YouTube using "FFmpeg HEVC VAAPI" encoder with AMD hardware device selected. Video parameters were tested using the `Stats for nerds` YouTube feature. The streamed video was viewed using `chrome web browser`.
AMD Ryzen 7 5700U with Radeon Graphics
EDIT (jpark37): I've tested recordings with these combinations on my Rocket Lake on Ubuntu 22.10. …
> obs-ffmpeg: Add HDR and HEVC to VA-API encoder

- plugins/win-capture/graphics-hook-ver.h
- plugins/win-capture/graphics-hook/vulkan-capture.c
- plugins/win-capture/graphics-hook/vulkan-capture.h
Applications that use this Vulkan extension would have image usage mismatches because we add VK_IMAGE_USAGE_TRANSFER_SRC_BIT to VkSwapchainCreateInfoKHR::imageUsage, so make the same modification to VkFramebufferAttachmentImageInfo::usage.
Vulkan hook stability.
> graphics-hook: Handle VK_KHR_imageless_framebuffer

- UI/window-basic-settings-stream.cpp
5a40934 refactored slots around services but a
on_service_currentIndexChanged() was not replaced by ServiceChanged().
The latter contains the code that was in the former before the refactor.
https://github.com/obsproject/obs-studio/commit/5a409347d5bf7dec50c41641660a131c265fb4ad
Fix an issue created by me
I have a profile with Twitch with server set to Paris.
- On master, settings will show Auto
- With the PR, settings will show Paris
> UI: Fix issue from stream settings Qt slots refactor

- UI/data/locale/en-US.ini
- UI/data/themes/Acri.qss
- UI/data/themes/Dark.qss
- UI/data/themes/Dark/unassigned.svg
- UI/data/themes/Grey.qss
- UI/data/themes/Light.qss
- UI/data/themes/Rachni.qss
- UI/data/themes/System.qss
- UI/data/themes/Yami.qss
- UI/mute-checkbox.hpp
- UI/volume-control.cpp
- UI/volume-control.hpp
Adds a new icon to the volume meter indicating that a source is unmuted, but inaudible due to not being assigned to any tracks:
When attempting to unmute a source in this state, the following message is shown:
Had no audio in a 4+ hour D&D session recording because the track assignment got lost (possibly fixed by #8495), probably a good idea to warn users about such cases.
Unassigned a soure, tried to start output.
> UI: Add unassigned indicator and warning to mixer

- UI/data/locale/en-US.ini
- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
- deps/libff/libff/ff-util.c
- deps/libff/libff/ff-util.h
Disable codecs that are incompatible based on the container drop down state. If an incompatible codec is selected when changing container, the encoder selection is reset to an invalid state and a warning is shown.
**Screenshot:**
Wanted to avoid having to add more warnings for Opus and #8289
Selected different contaiers, ensured codecs got disabled as necessary. Also tested with #8289 and made sure that works correctly.
> UI: Disable incompatible codecs in settings

- UI/obs-app.cpp
- UI/obs-app.hpp
Running Qt code in a signal handler is not safe. Per the Qt docs, we instead create a pair of sockets and a `QSocketNotifier` so that the signal handler can notify the main thread which can process the exit request without risk.
https://man7.org/linux/man-pages/man7/signal-safety.7.html
https://doc.qt.io/archives/qt-6.3/unix-signals.html
Make sure OBS handles Ctrl+C safely when run in a terminal.
Tested on Debian 11, other *nix variants likely need testing too assuming this even builds on non-Linux...
> Properly handle SIGINT on non-Windows platforms

- UI/window-basic-main-outputs.cpp
- UI/window-basic-main.cpp
- UI/window-basic-settings.cpp
RFC 51 (https://github.com/obsproject/rfcs/pull/51) has the objective of switching the default format to fragmented MP4/MOV for increased compatibility and to avoid of some of the issues with MKV.
Also changes the recording format config key to `RecFormat2` to ensure profiles remain backwards compatible given the new formats added.
Based on discussion a call to action in the changelog is probably not enough to get user feedback, so make it the default and see what happens.
Hasn't really.
> UI: Set fragmented MP4/MOV as default for pre-release versions

- UI/window-basic-main-outputs.cpp
Commit f1223ca566473bc90cf3643711db742b3d976c9c
(UI: Set fragmented MP4/MOV as default for beta/rc) changed RecFormat to RecFormat2.
This conflicts with the use of RecFormat introduced in d18b38e784a1e8ffef4ded32eece7bf6b7ef0589
(UI: Enable multiple audio tracks in Simple Output recording). This fixes the issue.
An unused var is also removed.
RecFormat no longer has a default. This causes a bug when one tries to load the setting.
This fixes it.
Tested that with a new profile recording works oob.
> UI: Switch RecFormat to RecFormat2

- docs/sphinx/reference-libobs-media-io.rst
- docs/sphinx/reference-outputs.rst
- docs/sphinx/reference-sources.rst
- libobs/data/format_conversion.effect
- libobs/media-io/video-frame.c
- libobs/media-io/video-io.h
- libobs/media-io/video-matrices.c
- libobs/obs-source.c
- plugins/decklink/decklink-device-instance.cpp
- plugins/decklink/decklink-source.cpp
Also add true 10-bit support for DeckLink, which required adding `VIDEO_FORMAT_V210` to `libobs`.
Said I would do it.
- PS5 10-bit YUV 4:2:2 HDR
- PS5 SDR
> decklink: Add HDR capture support

- libobs/data/format_conversion.effect
Fixed these errors reported by GLSL.
- Type cast `(uint)pos.x` is not accepted by GLSL. It should be `uint(pos.x)`.
- GLSL is strictly compare types so that an implicit arithmetic operation with `int` and `uint` are not allowed.
- It was passing `float4` type variable to `float2` argument.
OBS says error below and failed to initialize video.
```plain
error: Error compiling shader:
0:49(16): error: syntax error, unexpected ')', expecting '('
```
OS: Fedora 36
Hardware: AMD Radeon RX 6600 + Intel i7-7700.
- Only tested on Linux. It should be tested with HLSL on Windows.
> libobs: Fix VIDEO_FORMAT_V210 shader for GLSL

- libobs/media-io/video-frame.c
- libobs/obs-video.c
Adds explicit handling of recently introduced `VIDEO_FORMAT_V210` enum value to all switch statements in `libobs`. 
Format was added to enum but not handled in all switch statement handling the enum, which breaks warnings-as-errors about non-exhaustive switch statements.
Compiled successfully with stricter warnings enabled.
> libobs: Add missing VIDEO_FORMAT_V210 handling in switch statements

- .github/workflows/main.yml
Fixes macOS CI runs on master pushes.
Pushes to master will use faster Ninja builds on macOS, which cannot generate macOS app bundles anymore. Thus packaging will only work with PR pushes (and the "Seeking Testers" label set) or upon pushing a release tag to the master branch.
Tested with a push to master on my own fork.
> CI: Prevent build artifact creation for macOS without pushed tag

- plugins/obs-outputs/flv-mux.c
Fixes compiling without `ENABLE_HEVC`.
Somebody broke it.
Compiled without it.
> obs-outputs: Fix compilation without ENABLE_HEVC

- UI/obs-frontend-api/cmake/obs-frontend-apiConfig.cmake.in
Use `find_dependency(libobs REQUIRED)` instead of `find_dependency(OBS::libobs REQUIRED)`.
3rd party plugin that has the line below will fail to run cmake.
```cmake
find_package(obs-frontend-api REQUIRED)
```
The error message is as below.
```plain
CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
By not providing "FindOBS::libobs.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"OBS::libobs", but CMake did not find one.
Could not find a package configuration file provided by "OBS::libobs" with
any of the following names:
OBS::libobsConfig.cmake
obs::libobs-config.cmake
Add the installation prefix of "OBS::libobs" to CMAKE_PREFIX_PATH or set
"OBS::libobs_DIR" to a directory containing one of …
```
> cmake: Fix obs-frontend-apiConfig.cmake included from 3rd party plugin

- libobs/obs.c
This PR adds a error log when a libobs data file (such as `default.effect`) is not found.
When an install is broken and the data file is not found, the log says only the line below. It is hard to identify what is really wrong.
```
Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.
```
OS: Fedora 36
Built with `-DUNIX_STRUCTURE=1`, installed, and run obs.
> libobs: Log when libobs data file is not found

- cmake/common/helpers_common.cmake
Adds all variations of QDarwinPermissionPlugins to the ignorelist in cmake.
This already existed for QDarwinBluetoothPermissionPlugin but it looks like I didn't actually confirm that it generated correctly.
Want OBS to work with Qt 6.5
macOS 13.2.1
The project *generates* correctly now with both Qt 6.5.0-rc and dev branch.
There still appears to be an issue with the 3.0 cmake, because no Qt versions apart from obs-deps appear to work.
I installed 6.4.3 and 6.5.0-rc from the Qt online installer, as well as building the dev branch, and while generating the project worked with all of them, they also failed to run (can't find QtDBus).
*However* using obs-deps Qt 6.4.3 works (while 6.4.3 from the online installer doesn't), so presumably using 6.5.0 from obs-deps would also work (with this …
> cmake: Ignore all Qt darwin permission plugins

- UI/cmake/legacy.cmake
CMake 3.0 replaces some "boolean" macros by compile definitions but the UI legacy.cmake  is missing service integrations'.
Fix this issue quick.
Build locally with API keys, Connect button shows up on services with the PR.
> UI: Add missing compile definitions for service integrations

- UI/win-update/updater/updater.cpp
Adds a workaround so the updater works correctly with portable builds pre-#8566
I'm an idiot.
Ran locally.
> updater: Add workaround for broken CLI arguments

- UI/update/win-update.cpp
Fixes portable mode installs + beta branches not updating correctly due to the updater not getting the correct arguments.
This is wrong.
Has not.
> UI: Fix updater parameters missing a space

- plugins/win-capture/game-capture.c
Fixes compat info showing in hotkey mode.
:(
Hasn't but I'm fairly confident it'll work.
> win-capture: Fix compat info showing in hotkey mode

- CI/include/build_support_macos.sh
- CI/macos/02_build_obs.sh
- CI/macos/03_package_obs.sh
- UI/cmake/macos/exportOptions-extension.plist.in
- UI/cmake/macos/exportOptions.plist.in
- cmake/macos/helpers.cmake
- cmake/macos/resources/package.applescript.in
Fixes packaging on CI to use Xcode's archiving and extraction functionality, which also ensures that all binaries contained in an app bundle are code-signed and fulfil Apple's requirements for application distribution.
Xcode's automatic packaging will not check an entire application bundle for missing code signatures. This job is handled by the archiving and extraction functionalities, which we haven't used before.
This PR changes the build and packaging script to use Xcode's own functionality, which also ensures that the resulting application bundle fulfils notarisation requirements.
Moving forward this will need to be extended to also use proper provisioning profiles (see the Camera Extension PR), which also needs to tap into Xcode's built-in functionality.
`xcodebuild` and `hdiutil` …
> CI: Fix macOS packaging for notarisation and forward compatibility

- deps/file-updater/CMakeLists.txt
Changes lower version boundary for the file-updater interface library to 3.16, fixing build issues on Linux distributions that cannot update to more recent CMake versions.
Version 3.16 required for Linux compatibility.
Needs to be tested by Linux contributors.
> deps: Fix lower CMake version boundary for file-updater

- UI/window-basic-settings-stream.cpp
This makes AV1 encoders fallback to their H264 counterpart rather than just falling back to x264 while changing services.
AV1 streaming was still not a thing, now it is. It just a avoids falling back directly to x264 in some service change scenarios.
Better fallback, until we improve settings by avoiding hardcode.
I don't have AV1 HW encoders, sorry.
> UI: Improve AV1 fallbacks while changing services

- UI/properties-view.cpp
Makes sure size is only adjusted the first time `RefreshProeprties()` runs.
Fixes #8553
Calling this is only required the first time properties widgets are created as Qt doesn't display them correctly otherwise. On subsequent updates it's no longer required and will result in the scroll position being reset.
Built, tested.
> UI: Only adjust size of properties on first draw

- UI/window-remux.cpp
When the input file is an `.mp4` or `.mov` file remux it to `.remuxed.mp4` or `.remuxed.mov`.
MP4 -> MP4 and MOV -> MOV is now valid due to the addition of fragmented formats.
Remuxed some recordings.
> UI: Remux mp4/mov to mp4/mov with suffix

- UI/window-basic-main-outputs.cpp
- UI/window-basic-main-outputs.hpp
- UI/window-basic-main.cpp
Changes autoremux so it retains the same container type when using fmp4 or fmov. In order to separate the files it adds `remuxed` to the suffix.
Also fixes automremux recording as MKV when fMP4 is selected.
AutoRemux kinda doesn't work correctly right now when fmp4/fmov are used.
Recorded in fmp4, autoremux remuxed to regular MP4 without recording to MKV.
> UI: Auto-Remux fragmented containers to regular counterparts

- plugins/obs-ffmpeg/jim-nvenc.c
- plugins/obs-outputs/rtmp-av1.c
Enable filler data insertion for native NVENC encoders.
CBR should be constant.
Recorded HEVC CBR, now actually fills the requested bitrate envelope.
Not tested with AV1 as I do not have hardware for that.
> obs-ffmpeg/obs-outputs: Fix AV1/HEVC padding with enhanced RTMP and NVENC

- .github/workflows/flatpak.yml
- CI/flatpak/com.obsproject.Studio.json
Just some cleanup.
jack2 is already in the runtime, we were just using the headers and removing the built module (`cleanup: ["*"]`).
Just done it before I forget.
The manifest still build without the jack2 module.
> Flatpak: Remove jack2 from manifest and clean up workflow

- libobs/util/util_uint64.h
In util_uint64.h the intrinsic function _udiv128 is used. The implementation of _udiv128 is only available in Visual Studio 2019+.
This quick fix removes the dependency on VS 2019 without cutting any functionality.
In the file libobs/util/util_uint64.h the compiler-intrinsic function _udiv128 is used when compiling with MSVC.
The implementation of _udiv128 is only available in VisualStudio 2019 and above.
With the check _MSC_VER >= 1920 said function is only called when compiling with MSVC 2019 and above.
As documented [here](https://learn.microsoft.com/en-us/cpp/intrinsics/udiv128?view=msvc-170), _udiv128 is available starting in Visual Studio 2019.
When trying to compile a custom project with VisualStudio 2017 while including the obs headers,
the compilation fails because of the missing …
> libobs: Remove dependency on Visual Studio 2019+

- UI/win-dll-blocklist.c
Adds some additional DLLs to the blocklist based on reports in #8552:
- Bandicam: Freezes OBS preview when unhooking.
- VirtualMotionCapture: Old versions without Unity Capture fix.
- HolisticMotionCapture: All versions prior to today as there is no fixed version yet (also Unity Capture based).
Freezing OBS is bad.
Untested, but strong evidence was presented in the issue showing the problems.
> UI: Update Windows DLL blocklist

- UI/window-basic-settings-stream.cpp
AMD AV1 was missing in simple mode.
Fixes https://github.com/obsproject/obs-studio/issues/8584
Not tested as I have no compatible hardware.
> UI: Add AMD AV1 encoder to simple output mode

- plugins/win-dshow/win-dshow.cpp
Currently buffering is enabled by default for Elgato capture devices due to an ancient patch.  
This PR disables buffering for Elgato devices by default except for  "Elgato Game Capture HD"  and devices that are producing encoded video.
(Sorry, I had to recreate this PR as I was not able to retroactively change the commit text.)
The old patch was only necessary only for the old capture devices "Game Capture HD" and "Game Capture HD60" that were accessed through a virtual capture device named "Elgato Game Capture HD".  These old devices delivered audio much later than video. Therefore buffering needed to be enabled to force OBS to respect timestamps.
All newer devices perform better and with lower latency when buffering is disabled. This was confirmed by our (Elgato) suppport.
I connected …
> win-dshow: Change buffering for Elgato devices

- plugins/decklink/CMakeLists.txt
- plugins/decklink/cmake/legacy.cmake
- plugins/decklink/decklink-device-instance.cpp
- plugins/decklink/decklink-device-instance.hpp
- plugins/decklink/decklink-device.cpp
- plugins/decklink/decklink-device.hpp
- plugins/decklink/decklink-output.cpp
Three is recommended though, so use at least that many.
Also add commit to stop swscale from kicking in because of color space mismatch add chewing up CPU without actually fixing the colors.
Correctness.
1080p and 2160p tested.
> decklink: Query for preroll frame count

- plugins/linux-pipewire/pipewire.c
Pipewire desktop portal capture assumes premultiplied alpha, so make sure to use the right blend equation to make translucent pixels work properly.
This is still broken for emissive pixels (alpha < color) since OBS seems to unpremultiply at some point during blending, but it works properly for translucent pixels (emissive pixel support requires an end-to-end premultiplied pipeline).
There is actually partial support in PipeWire for specifying whether the video format is premultiplied or not, but it seems to be incomplete and nobody uses it. I opened an issue [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3126). In the future if this is properly implemented as a property, OBS could support both formats.
Makes transparent window capture with PipeWire/Wayland work properly. …
> linux-pipewire: Use premultiplied alpha

- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Abort replay buffer muxing on error.
Without this, we could continuously call `signal_failure` in `write_packet`, crashing OBS with a stack overflow with all the error callbacks.
Tested with a failed mux as reported on Discord.
> obs-ffmpeg: Handle mux errors when writing replay buffer

- UI/window-basic-main-outputs.cpp
Fixes replay buffer not starting when fragmented format is selected.
The whole format handling needs a rethink, using the internal ID as a file extension is a bit of a headache in multiple places, but this will fix it for now.
Do I really have to explain this?
Has not.
> UI: Fix replay buffer with fragmented formats

- UI/window-basic-settings.cpp
Guards the `ResetInvalidSelection` workaround behind Qt < 6.5.1, as the bug will be fixed on 6.5.1 and newer (currently in the merge queue to the 6.5 branch, already merged on the dev branch).
There's an argument to be made for the code to be scrapped entirely as we're back porting the fix to obs-deps (see obsproject/obs-deps#175), that would however mean that people not running obs-deps-qt would have the bug again. Admittedly that's not many people, but the code doesn't do any harm by itself either.
This workaround exists because of [QTBUG-56064](https://bugreports.qt.io/browse/QTBUG-56064).
I fixed the bug upstream, so the workaround can be removed on the fixed version (so that in the future we don't forget to remove it once we drop support for Qt < 6.5.1).
Tested by decreasing the …
> UI: Guard ResetInvalidSelection check behind Qt < 6.5.1

- .github/workflows/steam.yml
Fixes Steam workflow being unable to find Windows asset since "x64" is no longer part of the ZIP name.
Want automatic upload to succeed once we release beta2.
Has not been tested.
> CI: Fix Steam workflow not finding win asset

- UI/obs-app.cpp
- UI/window-basic-about.cpp
This reverts commit 64d4ae0106ff9c61978bdb7b55dc35679edb5a13.
@WizardCM 's comment on #8267 indicated that it would be preferable to remove the display of extra build information from the application window's title bar (platform and bitness) but that we should keep it in the log and the About dialog. Removing this string caused the log analyzer to throw false positives for the "32-bit OBS on 64-bit OS" warning (see https://github.com/obsproject/loganalyzer/issues/122 and https://github.com/obsproject/loganalyzer/pull/124). Per discussion with @Fenrirthviti , I've reverted the changes in #8267 accounting for the new `platform` bool in #8371. The string will still be absent from the application window's title bar. We can reconsider removing the strings from the log and About dialog for a …
> Revert "UI: Remove bitness strings"

- UI/data/locale/en-US.ini
- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
Adds a message preventing the user from saving the settings if they have a config where an encoder or container is set to "Select Encoder/Format".
I'm not 100% sold on the strings used here, feedback on those (especially by native english speakers) would be appreciated.
Currently, this UX workflow is possible:
https://user-images.githubusercontent.com/59806498/228105567-c4560301-3853-4918-8314-43adbe9330de.mov
The user can easily miss that the field they just set changed to "Select Encoder...", and then go on with their lives, saving the settings, starting a recording and get the generic error (or alternatively get the incompatible encoder that was selected before to start recording, usually resulting in another opaque error message).
This doesn't fix the fact that the warning at the …
> UI: Disallow closing settings without selected codec or format

- UI/qt-wrappers.cpp
UUIDs are more robust than names as they can't be changed.
More robust code.
Dragged / dropped scenes in scene tree.
> UI: Use UUIDs for QDataStream

- plugins/decklink/decklink-device-instance.cpp
- plugins/decklink/decklink-device-instance.hpp
Eliminates the stalls that have been seen when waiting for frame copies.
We shouldn't be copying at all ideally, but that would break the API.
Stalls are bad.
- This seems to fix the choppiness at 2160p59.94 although I'm not sure I 100% trust my eyes. At the very least, the mutex stalls are gone, and someone can improve from there.
- Used `__debugbreak()` to make sure 3 frames was a decent enough pool size. It did trip very occasionally, but I'd feel queasy about increasing to 4.
> decklink: Pass frames between threads using queues

- plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
- plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c
* HTML error messages were added for the first time in #8474
Qt's default QString renderer will use HTML when recognised, but will prioritise the plaintext renderer if newlines are used via `\r\n`.
This updates the error string generator to use HTML line breaks instead.
Before:
After:
Links should be clickable, not rendered as raw HTML.
* Set NVENC rescale resolution to `1920x10801` to trigger an invalid code path
* Start Recording
> obs-ffmpeg: Don't use standard newlines in HTML error messages

- UI/context-bar-controls.cpp
`main` is used later in the function after being `std::move`ed which is technically undefined behavior even though it's only a basic type (pointer) that `std::move` has no effect on. `scene_name` however is safe to move so let's do that instead.
Detected by PVS Studio.
Solve a warning and weird behavior.
Ran in debugger. I would appreciate comments by someone with more C++ experience about this behavior.
> UI: Don't std::move main in SetUndoProperties

- plugins/obs-ffmpeg/obs-ffmpeg-output.c
- plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c
In avcodec.h, the docs for AVCodecContext->framerate say:
```
encoding: May be used to signal the framerate of CFR content to an
encoder.
```
OBS is designed to always output Constant Frame Rate (CFR) content. Instead of letting this be implied, let's explicitly set the framerate per the docs.
Want more predictable behavior and less autodetection/inference code paths.
I tested setting this explicitly last year and didn't see any negative side effects then. I re-tested this briefly just now and it seemed fine. Additional testing would be welcome.
> obs-ffmpeg: Set framerate for AVCodecContext outputs

- UI/obs-app.cpp
- UI/obs-app.hpp
- UI/window-basic-main-outputs.cpp
- UI/window-basic-main-outputs.hpp
- UI/window-basic-main.cpp
- UI/window-basic-settings.cpp
Reworks how recording formats are handled to avoid some of the string manipulation required to properly work with fragmented formats by only translating from the internal name to the extension when the filename is generated.
This should make it less error prone and easier to extend with new formats should that ever be desireable.
**Note:** Superseedes and closes #8629 
The old stuff kinda sucked.
Recorded fragmented video, verified config migration works.
> UI: Rework recording format handling

- UI/cmake/os-windows.cmake
- deps/file-updater/CMakeLists.txt
- deps/json11/CMakeLists.txt
- deps/libff/CMakeLists.txt
- deps/media-playback/CMakeLists.txt
- deps/obs-scripting/CMakeLists.txt
- deps/opts-parser/CMakeLists.txt
- libobs/cmake/32bit-build.cmake
- libobs/cmake/os-windows.cmake
- plugins/mac-virtualcam/CMakeLists.txt
- plugins/obs-ffmpeg/CMakeLists.txt
- plugins/obs-outputs/cmake/ftl.cmake
Removes `EXCLUDE_FROM_ALL` for `INTERFACE` type libraries.
Emits an error on older CMake versions, seems to be ignored by more recent ones. As interface-type libraries are not built by themselves anyway (they are vehicles for header files and compile options), the `EXCLUDE_FROM_ALL` directive is practically superfluous.
Fixes https://github.com/obsproject/obs-studio/issues/8595.
Needs to be tested on Linux with CMake 3.16.
> cmake: Remove EXCLUDE_FROM_ALL directive from interface libraries

- UI/window-basic-settings.cpp
Uses the localized name instead of the internal extension to display that something is incompatible.
Before:
After:
I will say that I'm a tiny bit torn on the double brackets, but also didn't want to introduce another string for this.
(and yes, I realize my screenshots were from different comboboxes, but the result is the same for both)
Current warning doesn't look great.
macOS 13.3
See screenshots above.
> UI: Use name instead of internal extension for incompatible codec check

- plugins/obs-outputs/flv-mux.c
Fixes bug in Enhanced RTMP implementation, where HEVC streams with B-frames enabled are not adhering to the spec.
Credit to derrod 
Populates non-zero composition times in the FLV extended video tag header for HEVC streams.
See https://github.com/obsproject/obs-studio/pull/8522 for context.
The [Enhanced RTMP spec](https://github.com/veovera/enhanced-rtmp) provides an optimization where HEVC streams without B-frames do not need to send a composition time of 3 bytes (with value 0) for every frame.
This patch fixes a bug: Composition times are just not getting set at all, instead of only when the value of the composition time is 0.
We ran streams against YouTube, inspected the bitstream and confirmed that composition times are correctly set.
Bug fix (non-breaking change which fixes an …
> obs-outputs: Fix HEVC/RTMP composition time

- plugins/mac-videotoolbox/encoder.c
Fix possible unused variable if obs-studio is built with `ENABLE_HEVC` disabled.
The format is only checked for 10-bit capable formats, which in this case applies to HEVC only. When HEVC is disabled, then `format` is not checked and becomes an unused variable otherwise.
Compiled on macOS 13.3 with Xcode 14.3.
> mac-videotoolbox: Fix compile issue if HEVC is disabled

- UI/obs-app.cpp
- UI/window-basic-main-outputs.cpp
- UI/window-basic-main.cpp
Clean up a few unused variables and some `string -> char * -> string` conversions found by PVS Studio.
Got annoyed at these warnings.
Built OBS on Windows.
> UI: Remove unnecessary variables and type conversions

- UI/window-basic-main-outputs.cpp
As #8652 revealed some of the filename formatting functions were called but the results never used for replay buffer/file splitting so the extesnion would still be wrong. This fixes that.
Wake me up inside (can't wake up)
Confirmed replay buffer and splitting work as expected.
> UI: Fix splitting/replay buffer extension

- UI/window-basic-settings.cpp
Adds explicit `std::` prefixes to `move`, even when `using namespace std`.
Clang doesn't like unqualified `move` calls anymore.
> This follows some C++ committee discussions where some
people where concerns that this might be an usual anti pattern
particularly britle worth warning about - both because move
is a common name and because these functions accept any values.
We un-errored this warning in #8647, mostly because we have json11 which uses it, but I'd like to still fix the warning in our code at least.
macOS 13.3
Warning gone.
> UI: Fix "Unqualified call to 'std::move'" warnings

- UI/window-basic-settings.cpp
Fixes the compatibility check again, this time because of a silly mistake I should've caught because I made it before. `QT_TO_UTF8(x)` (which just expands to `x.toUtf8().constData()`) returns a pointer to memory that gets freed immediately at the end of the statement. This is valid in function calls but will cause issues in cases like this one.
Fun fact: This is a use-after-free and `rustc` would yell at you for this, but C++ compilers just go "nah seems goot mate".
Fix bugs.
Opened settings a few times and validated things work now.
> UI: Fix simple mode container check

- plugins/obs-ffmpeg/texture-amf.cpp
A number of people and their logs indicate that the AMD texture encoder will "crash" (drop to 0 kbps output) when reconfigured while running (e.g. #8548).
To prevent people's outputs from dropping disable this for now and rely on frame-dropping instead.
Do not want outputs to die.
Has not.
> obs-ffmpeg: Disable AMF texture encoder runtime reconfiguration

- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
The iteration was running on the enum rather than the actual array specified in the codec, so it would keep searching through FFmpeg's memory until it found `-1`, fun!
Fixes #8660
Fix bug.
Breakpointed to validate things now work correctly.
> obs-ffmpeg: Fix iteration over sample formats

- UI/volume-control.cpp
Fix callback not masking the new mixer state to check unassigned status.
Fix bugs.
Ran on macOS, tested it now works correctly.
> UI: Fix unassigned audio source check in callback

- UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp
- UI/frontend-plugins/frontend-tools/auto-scene-switcher.hpp
Fixes settings in the auto scene switcher window not being saved when the window is closed.
The `done` event does not emit a `closeEvent`, but saving is only implemented in that event handler. Changing this to `close` correctly triggers the default QWidget event and thus settings are saved.
Tested on macOS 13.
> frontend-plugins: Fix auto scene switcher not saving settings on close

- UI/window-basic-main.cpp
e832b42 (in 2019) made AddProjectorMenuMonitors a member function of OBSBasic, but the (now unused) declaration of the static function never got removed.
Stumbled across this (pretty unrelated) in my quest to get rid of `SIGNAL` and `SLOT` macros.
macOS 13.3
Still compiles, and can still open fullscreen projectors.
> UI: Removed unused static AddProjectorMenuMonitors declaration

- UI/properties-view.cpp
- UI/properties-view.hpp
Sets the size before restoring the scroll position, and also recalculates the scroll position based on the change in maximum value to the scroll bars.
Fixes #8659
Fixes odd behaviour.
Not easy to test, the main sources with this cursed behaviour are on Windows. But seems to work with mac avcapture sources.
> UI: Fix properties resizing (again)

- .github/workflows/steam.yml
Moves the Steam Upload workflow to macOS to deal with more modern DMG formats.
Also fixes deprecation warnings by updating the actions to setup steamcmd and generate TOTP codes.
Fixes run failures (probably).
My fork: https://github.com/derrod/obs-studio/actions/runs/4622028817
> CI: Migrate Steam uploader to macOS

- UI/window-basic-settings.cpp
Fix an invalid pointer caused by holding on to freed memory.
After #8661 I wanted to see if there were other places affected by this anti-pattern.
Compiled and ran OBS.
> UI: Fix incorrect use of QT_TO_UTF8 in SpeakerLayoutChanged

- libobs/obs.c
The obs_get_transition_by_uuid function would return a valid source even if it wasn't a transition.
Fixes bug I've found
Got transitions by uuid
> libobs: Fix transition lookup by uuid

- plugins/obs-outputs/rtmp-av1.c
The header packets are only used within the rtmp-output and do not need or use the ref counter as the data is manually free'd directly.
The presence of this ref counter causes a crash on *nix platforms due to our memory alignment hack attempting to free memory but reading the wrong offset due to the ref counter being there rather than the alignment offset.
Fix crash.
Streamed with libaom-av1 on macOS.
> obs-outputs: Fix AV1 header parser adding ref count to data

- UI/cmake/feature-sparkle.cmake
Sets `SPARKLE_UPDATE_INTERVAL` to 0 instead of not setting it if Sparkle is disabled.
Plist files don't like empty integers (`<integer></integer>`), and an empty integer gets generated in Info.plist if `SPARKLE_UPDATE_INTERVAL` isn't set. This is a regression of 50d1b5ccb.
This means that OBS doesn't compile without Sparkle anymore which makes me sad because I quite like being able to compile OBS.
macOS 13.3
OBS now compiles on my Mac.
> cmake: Fix build without Sparkle

- plugins/rtmp-services/CMakeLists.txt
- plugins/rtmp-services/cmake/legacy.cmake
- plugins/rtmp-services/rtmp-format-ver.h
- plugins/rtmp-services/rtmp-services-main.c
Replaces preprocessor defines with actual constant values.
Quoting from [Google Objective-C Style Guide](https://google.github.io/styleguide/objcguide.html):
> Avoid macros, especially where const variables, enums, XCode snippets, or C functions may be used instead.
> Macros make the code you see different from the code the compiler sees. Modern C renders traditional uses of macros for constants and utility functions unnecessary. Macros should only be used when there is no other solution available.
The use of macros and defines was a valid crutch in past decades when languages didn't have first-class support for the desired constructs. This has not been the case for a long time, and as such this old practise needs to be laid to rest.
Tested on macOS 13.
- Code cleanup (non-breaking change …
> rtmp-services: Replace preprocessor defines with actual constant values

- UI/update/mac-update.cpp
- UI/update/shared-update.cpp
Replaces preprocessor definitions with actual constant string values.
Removes code smell and adapts modern coding practices - as per SonarSource (https://rules.sonarsource.com/cpp/RSPEC-5028):
> A macro is a textual replacement, which means that it’s not respecting the type system, it’s not respecting scoping rules…​ There is no reason not to use a constant instead.
Also updates two stray occurrences of unqualified calls to `std::move`.
Compiled on macOS 13 and checked values with debugger.
> UI: Replace use of macros for macOS updater with character constants

- plugins/mac-avcapture/av-capture.mm
Fixes a possible typo in mac-avcapture - it's a single line assignment and should obviously be terminated by a semicolon.
Fixes a "questionable use of comma" compile error when using clang with default Xcode settings.
Tested on macOS 13 with Xcode 14.3 and default compile settings.
> mac-avcapture: Fix questionable use of comma

- cmake/Modules/CompilerConfig.cmake
- cmake/macos/compilerconfig.cmake
- cmake/macos/xcode.cmake
- libobs/obs-cocoa.m
Set default compiler options C standard to C17. For MSVC this was previously manually set via the compiler flags but we can probably use this on all platforms (I can't quite remember why it was necessary for MSVC).
Might fix issue reported here: https://github.com/obsproject/obs-studio/pull/8377#issuecomment-1499495578
Compiled on macOS with Xcode 14.3, this PR will be the test for Windows/Linux.
> cmake: Set C standard to C17

- buildspec.json
- cmake/macos/buildspec.cmake
- plugins/CMakeLists.txt
Fixes the following issues that arose when trying to compile `libobs` for plugin development:
* Add platform configuration for universal architecture (require for JSON parsing)
* Fix `OBS_VERSION_OVERRIDE` handling
* Fix detection of available prebuilt dependencies (dependencies will be set up for building plugins already and should be shared by the build tree for `libobs`
* Skip setup of Chromium Embedded Framework for universal builds (we do not provide a Universal binary variant of CEF)
* Skip plugin targets when `ENABLE_PLUGINS` is not enabled
These fixes are required for an incoming update to `obs-plugintemplate` to work correctly with the updated CMake build system.
Tested with obs-plugintemplate on macOS.
> cmake: Fix build system for macOS universal builds

- cmake/common/helpers_common.cmake
- libobs/CMakeLists.txt
Fixes header definitions for `libobs` Framework and adds missing headers to the export.
Ensure that plugins can still correctly link against `libobs`.
Tested with a plugin build on macOS.
> cmake: Fix Framework export of libobs with new build system

- UI/window-basic-settings.cpp
Previously Qt events were temporarily disabled while the codec disablement check ran to prevent `AdvOutRecCheckWarnings` being called several times in a row, however, this also resulted in `on_advOutRecEncoder_currentIndexChanged()` never being called (I didn't see this function previously as it does not use the `connect()` syntax but the `on_` syntax).
To avoid any more issues related to this simply accept that `AdvOutRecCheckWarnings()` may be called twice in quick succession, this should not have any negative effects aside from wasting CPU cycles. The call at the end of `AdvOutRecCheckCodecs()` will now only happen if neither encoder had been changed.
Fix properties still showing after encoder has been invalidated.
Mucked about with settings for a bit. …
> UI: Do not disable events when disabling codecs

- UI/win-dll-blocklist.c
Block another broken DLL.
Crashing reported by user, https://obsproject.com/forum/threads/obs-is-crashing-v29-0-2-and-27-2-4.165863/
Hasn't, but similar changes to block other DShow DLLs all seem to work.
> UI: Add Citrix ICAService to Windows DLL blocklist

- UI/window-projector.cpp
Skips calling `obs_source_get_signal_handler` and `obs_source_get_name` if not using a source / scene projector (i.e. multiview).
Calling libobs functions with a null pointer is bad behavior.
Ran OBS, opened projectors.
> Avoid calling libobs functions with null pointers in projectors

- UI/window-basic-settings.cpp
Fixes maximum of memory limit spinbox not being set in simple mode replay buffer.
Fixes #8704 
Verified spinbox now goes beyond 8192.
> UI: Fix simple mode replay buffer maximum not being set

- cmake/macos/buildspec.cmake
Fix version comparison in build spec parser to ensure outdated `obs-deps` are automatically detected and new variants downloaded automatically.
VERSION comparison requires semver-compliant version strings, but obs-deps versions are based on dates, which are not compliant. Fix version strings to semver variants before comparison.
Tested with new updated deps available for beta-4.
> cmake: Fix buildspec version parsing for dependencies

- .github/workflows/flatpak.yml
- .github/workflows/main.yml
Use Flatpak GitHub action v6.1.
Sadly, v6 had an issue where it pushed the build to the `master` branch regardless of the branch specified in the action config. This was fixed in v6.1, so let's use that, and publish further releases on the right branch.
- Publish another OBS beta release
- See that it pushed to the `beta` branch on Flathub Beta (stable releases are unaffected)
> CI: Bump Flatpak actions to v6.1

- libobs/util/c99defs.h
- libobs/util/darray.h
Extract the function `darray_push_back_new`, which is receiving `struct darray *` type in the macro `da_push_back_new`.
A GCC's extension is utilized so that `#ifdef __GNUC__` is added.
Also removes the macro `PRAGMA_WARN_STRINGOP_OVERFLOW`.
The macro `PRAGMA_WARN_STRINGOP_OVERFLOW` was introduced to suppress a warning `-Wstringop-overflow` caused by the macro `da_push_back_new` calling `darray_push_back_new`. This looks a false-positive warning.
Less suppression of warnings is better.
OS: Fedora 36
GCC: 12.2.1 20221121 (Red Hat 12.2.1-4)
This will also enables checking the type check of the returned pointer.
For C++, I compiled the code with a modification below and the compile passed.
```patch
diff --git a/UI/api-interface.cpp b/UI/api-interface.cpp
index 800788be7..cb3f72bf4 100644
--- …
```
> libobs: Remove newly introduced PRAGMA_WARN_STRINGOP_OVERFLOW macro

- plugins/obs-outputs/rtmp-stream.c
This logs that dynamic bitrate is disabled when a codec which does not support bitrate reconfiguration is used, such as aom, svt-av1 ...
User reported that dynamic bitrate did not work with aom + rtmp to YouTube.
See #8740 
Tested that it logs that dbr is disabled.
> obs-outputs: Log encoder incompatibility with dynamic bitrate

- UI/hotkey-edit.cpp
Changes the margins of the horizontal layout of the hotkey edit widget to have 2 pixels on the top and bottom each, rather than 4 on the top and 0 on the bottom.
Before/After (with horizontal helper lines added):
<p>
</p>
Closes https://github.com/obsproject/obs-studio/issues/8468
Saw https://github.com/obsproject/obs-studio/issues/8468 and couldn't unsee since. Thus, I had to fix it.
Also, smaller issue count == better.
macOS 13.3.1
See the screenshots above.
> UI: Make hotkey edit layout margins symmetrical

- plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInMain.mm
Fixes macOS virtualcam missing `PlugInMain` entry point for CoreMediaIO.
With the recent change to enforce C17 standard for compilers, default visibility was also enforced to be hidden. This also automatically hid the `PlugInMain` symbol required for DAL plugins. Adding the `__exported` decorator makes the symbol explicitly visible.
(It also seems as if the related Xcode setting is forced to be "off" by CMake's Xcode generator even though we enable it in our build. Only setting it via the generator-independent CMake flags seems to has the desired effect, which is why it didn't occur before that PR was merged).
Tested on macOS 13.
> mac-virtualcam: Fix DAL plugin entrypoint not being exported

- libobs/util/util_uint64.h
Use inline assembly for x86_64 speed/accuracy.
Sacrifice speed for accuracy on other processors.
Continue to use original implementation for ARM on Windows.
Make Linux behave like Windows. Make Mac behave closer to Windows.
Checked Windows (x64), Mac (ARM64), and WSL2 Ubuntu (x86_64). Modified code temporarily to verify previous failure case works now.
> libobs: Improve util_mul_div64 outside MSVC

- cmake/Modules/CompilerConfig.cmake
Sets C standard version to C11 for CMake versions that do not support higher values.
Fix building with older CMake versions (CMake 3.16 is still the default on Ubuntu 20.04).
Has not.
> cmake: Set C11 for CMake < 3.21

- plugins/obs-outputs/flv-mux.c
Per the spec, non-metadata packets still use the frame type. In OBS's use case this should either be 1 (key frame) or 2 (inter frame), but never 0 (reserved/undefined). The enum for inter frames existed but was not used here due to an oversight.
Send spec-conforming stream.
Tested HEVC streaming to YouTube, still worked as expected.
> obs-outputs: Fix enhanced RTMP frame type not being set

- plugins/obs-outputs/flv-mux.c
- plugins/obs-outputs/flv-mux.h
- plugins/obs-outputs/rtmp-stream.c
Prevent underflow of RTMP timestamp delta by not setting the DTS offset for packets without a valid DTS (SEQ start/end) to prevent librtmp from trying to calculate the delta in the first place.
Fixes an issue reported on Discord.
Verified in Wireshark capture that OBS now sends a zero timestamp rather than invalid delta.
> obs-outputs: Do not set DTS offset for Seq start/end packets

- UI/cmake/legacy.cmake
- UI/cmake/ui-qt.cmake
Adds `OBSBasicProperties.ui` and `OBSLogViewer.ui` to the cmake sources list.
Used Xcode to search for code that should be in the properties dialog for an unrelated PR, and wondered why I didn't get any results. This also made me check the other files which revealed that log viewer was also missing.
macOS 13.3.1
Files now show up in the "UI Files" category.
- DX Bug fix (non-breaking change which fixes an issue)
> cmake: Add properties and log viewer UI files to sources list

- libobs/obs-source.c
Fixes a possible crash when renaming a source during the source_create signal callback as it has not been added to the hash table yet.
Fix crash reported on Discord.
Has not been tested.
> libobs: Finalise source creation before firing signal

- plugins/rtmp-services/data/schema/service-schema-v5.json
- plugins/rtmp-services/data/services.json
- plugins/rtmp-services/rtmp-format-ver.h
Prevent newer version of OBS to use old version of `services.json` that are not updated for RFC 45 and Enhanced RTMP
Avoid breakage for Windows user that have a v4 `services.json` in their roaming directory that is not up to date because OBS was built with `ENABLE_SERVICE_UPDATES` off.
> rtmp-services: Bump format version to v5

- libobs/util/platform.c
In some cases (ffmpeg_mux), the extension and format values are a direct passthrough from arbitrary data. Instead of always postfixing a `.` at the end of a generated path if the extension is invalid, don't postfix the `.` at all.
Before: `my_formatted_string.`
After: `my_formatted_string`
I want to make ffmpeg_mux write data to a named pipe which does not have a file extension.
```c
const char *testformat = "test format pp";
const char *extension = NULL;
//const char *extension = "";
//const char *extension = "mp4";
char *filename = os_generate_formatted_filename(extension, false, testformat);
blog(LOG_INFO, "filename: \"%s\"", filename);
bfree(filename);
```
> libobs: Check for extension validity in os_generate_formatted_filename

- plugins/linux-pipewire/pipewire.c
Compositors did not agree on how to communicate invalid buffers until recently, so e0a4d8628d287217cebc3d05d2077e1f0709b450 resulted in regressions on KDE. This restores our old behavior which is too conservative but mostly works on old and new compositors (which contain similar workarounds to pass in invalid but non-zero sizes for dma-bufs).
Once all old compositors are out of use we can remove this workaround and then compositors can remove their random size workaround.
fixes #8630
We should carry a workaround while we support ubuntu who wont backport such compositor fixes.
I havent as I dont have an ubuntu install to test this on right now.
> linux-pipewire: Only consider chunks with size set

- libobs/obs-nix-x11.c
Fixes issue with mouse buttons 4 and 5 not working for push to talk when using linux
If I understand correctly, according to FindXCB.cmake, the definition for xinput should be XCB_XINPUT_FOUND which was causing the obs-nix-x11.c to not utilize xinput. This caused the function mouse_button_pressed to fallback onto code that does not include support for mouse buttons greater than 3. 
Fixes issue  #8517
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
info: CPU Speed: 3099.713MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 15883MB Total, 8226MB Free
info: Kernel Version: Linux 6.2.10-arch1-1
info: Distribution: "Arch Linux" Unknown
info: Desktop Environment: KDE
info: Session Type: tty
info: Window System: X11.0, Vendor: The X.Org Foundation, …
> libobs: Fix mouse button push to talk for linux

- libobs/data/color.effect
- plugins/obs-filters/data/color.effect
Adjust colors from BT.1886 to sRGB.
Want colors to be bad because of Reinhard, and not because we used the wrong transfer function.
- Compared screenshots and tonemapped image is now brighter than before.
- Verified HDR tonemap shader behavior matches common shader.
- Checked D3D11 and OpenGL backends on Windows.
> libobs,obs-filters: Align HDR to SDR disparity

- plugins/rtmp-services/rtmp-services-main.c
Effectively reverts 8b315186a724f3af59163196db79080ffd26dfcb, as the cmake referenced in the description has long since been completely rewritten and replaced.
v5 service schema isn't up on the webhost yet, and the warning was bothering me. I don't even need services anyway, and I found that I could not disable them.
The plugin no longer attempts to download the services file from the internet when I disable the service updates cmake variable.
> rtmp-services: Allow service updates to be disabled on *nix

- UI/audio-encoders.cpp
Audio bitrate maps needs to be populated while finding closest available bitrate
Not populating makes always fallback to 192
Fix a bug caused by my audio encoders change in RFC 45 PR.
- Open OBS and set in settings in advanced mode with an audio bitrate different from 192
- Save the settings and close OBS
- Open OBS and start recording/streaming, the encoder use 192 without the PR in the logs.
> UI: Fix advanced audio encoder bitrate always set to 192

- .github/workflows/clean-caches.yml
Adds a scheduled or manually runnable workflow that removes outdated caches.
- Removes PR with a date before the current one
- Removes duplicate Flatpak caches not on the master branch
- Removes outdated Flatpak caches on the master branch
Note that it requires Python 3.11+ since `datetime.fromisoformat()` was fixed in that version to properly understand nanosecond precision timestamps and the `Z` suffix as a UTC timezone alias.
Cache usage high.
Test run on my fork: https://github.com/derrod/obs-studio/actions/runs/4682838775/jobs/8297197955
> .github: Add workflow to clean caches

- deps/media-playback/media-playback/cache.c
Moves mutex initialization before any function calls.
`mp_cache_stop` / `mp_cache_free` both try to use the mutex so we need to make sure it's initialized before calling functions that may fail or OBS will crash. Reported on Discord: https://discord.com/channels/348973006581923840/1090367203385278514/1101725241434177536
Tested with a removed cached stinger, OBS no longer crashes.
> deps/media-playback: Initialize mutex earlier for cached media

- cmake/finders/FindFFmpeg.cmake
Fixes broken version detection in updated FFmpeg find module.
This is a non-critical fix as we do not use a version parameter in our `find_package` calls to find FFmpeg.
Once we do, project generation will break as FFmpeg uses non-semantic versioning in their headers.
This PR updated the find module to work with FFmpeg's versioning to properly set `FFmpeg_VERSION´ so a call like `find_package(FFmpeg 6)` will succeed.
Tested on Windows and macOS.
> cmake: Fix version detection for FFmpeg find module

- UI/window-basic-properties.cpp
Changes the properties view to explicitly focus the `Ok`  button on launch.
On some (operating?) systems, the `Restore Defaults` button is focused by default, so clicking Enter after opening the dialog would result in the "Are you sure [...]" window popping up instead of the dialog closing and continuing which I consider the more intuitive behaviour.
Similar to #8751, but using `focus()` instead of `setDefault()`.
Adresses https://github.com/obsproject/obs-studio/issues/8749 (which is closed as it didn't turn out to be a 29.1 regression, but the point of the issue is still valid).
On my Mac: Tested with a small change to this PR that using QDialogButtonBox::RestoreDefaults would make the "Defaults" button the focussed button when clicking enter. However currently the "OK" button already …
> UI: Explicitly focus Ok button in properties dialog

- deps/media-playback/media-playback/media.c
Moves the `mp_media_can_play_frame` check earlier in the `mp_media_next_audio` function.
It's possible that `frame_ready` is false when this function is called, which implies that the `mp_decode` `frame` field is not valid. However we dereference the `frame` (variable `f`) by counting the number of audio channels before calling `mp_media_can_play_frame` which checks the value of `frame_ready`.
One of several fixes for issues discovered in https://obsproject.com/forum/threads/obs-crashing-all-the-time-from-rtsp-sources.165637/
Untested, but should be correct.
> deps/media-playback: Check if frame can be played before using it

- UI/CMakeLists.txt
- UI/cmake/feature-macos-update.cmake
- UI/cmake/feature-sparkle.cmake
- UI/cmake/feature-whatsnew.cmake
Fixes building on macOS without browser being enabled.  
Also allows building Sparkle support without the browser.
Fixes good.
Compiled on my Mac without browser and with Sparkle.
> UI: Fix building macOS/Sparkle without Browser

- UI/win-dll-blocklist.c
This is actually a MainConcept redistributable and not related to Adobe. Unfortunately Elgato Game Capture HD software relies on this dependency when presenting the DirectShow device to OBS, so we unintentionally blocked it from loading.
Instead of outright blocking, we now block only versions older than the one shipped by Elgato, which has hopefully been patched to fix the random crashes.
Blocking legit capture devices isn't great.
Hasn't as I don't have the necessary hardware.
> UI: Relax mc_trans_video_imagescaler.dll DLL block

- cmake/Modules/CompilerConfig.cmake
Supersedes #8852
Fixes #8850
`-Wmaybe-uninitialized` has proven to be too unstable (GCC regressions, false positive) to be turn into an error.
GCC does not seem to keep this warning stable enough through versions, which is not a complaint it is just incompatible with `-Werror` purpose.
Build with GCC 13 in Release mode and no errors.
> cmake: Enforce -Wmaybe-uninitialized to never turn into an error

- UI/volume-control.cpp
- UI/volume-control.hpp
Disables unassigned indicator/warning for sources set to "Monitor only (mute output)".
Sources that are monitored are intentionally not mixed into any tracks, so they should not be shown as unassigned.
Reported on Discord: https://discord.com/channels/348973006581923840/768389015484760106/1103309430633803817
Toggled tracks and monitoring state for a source.
-
> UI: Do not show unassigned icon for monitored sources

- plugins/mac-capture/mac-screen-capture.m
Catch possible division-by-zero issue in audio handling code.
The possibility of `mChannelsPerFrame` being 0 is not properly covered by current code, which will result in a division-by-zero error.
Issue was discovered by Xcode's "Analyze" run.
Tested and re-analyzed on macOS 13 with Xcode 14.3.
> mac-capture: Fix possible division by zero error.

- .github/workflows/main.yml
Update cache keys used for saving and restoring `ccache` cache data.
Current caching steps do not use a coarse restore key to enable cache restoration from a possible master cache. This is a forward-port of a future CI workflow update that uses the same cache key logic.
Also fixes missing generator token for cache keys generated by master branch.
Tested on `obs-studio` fork with upgraded workflows.
> CI: Update ccache cache entries to enable restoration from master branch

- plugins/mac-syphon/syphon.m
Removes macOS 10.15-only code.
The minimum version of macOS for OBS is 11.0 now, so this can be removed
macOS 13, compiled and run.
Clicked on the Show License button which still works.
> mac-syphon: Remove macOS 10.15-only code

- libobs/data/format_conversion.effect
We are currently loading luma samples unnecessarily close to texel boundaries, and that's causing the wrong texels to be sampled depending on the GPU that's doing the rounding. We can adjust the math to use much safer coordinates.
Fixes #7742
Distorted sources are bad.
- Intel Mac looks good now
- RenderDoc shader debugger shows texel coordinates are what they were intended to be
> libobs: Fix luma sampling for packed 4:2:2 sources

- UI/data/locale/en-US.ini
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Faulty plugins or other bugs resulting in references to source outliving the intended lifetime can result in data corruption or loss as in #8843. Instead of corrupting data just crash as something has gone horribly wrong.
Crashing > Data corruption.
Manually incremented ref counter of some sources. Couldn't reproduce #8843 directly.
> UI: Exit if clearing scene data fails

- UI/auth-oauth.cpp
- UI/auth-oauth.hpp
Fixes possible crash when a panel's browser source is destroyed after its associated `NSView` has been removed by Cocoa.
Deleting the cefWidget in the panel's destructor can result in a crash on macOS because the underlying NSView might have been destroyed in memory between Qt closing the QDialog and the destructor call.
Moving the browser destruction into the accept and reject calls ensures that CEF can clean up its state _before_ Qt tears down the view hierarchy.
Fixes #8836.
Tested on macOS by several team members.
> UI: Fix crash on macOS when closing OAUTH browser panel

- test/cmocka/test_serializer.c
This PR adds `serializer_get_pos` and `array_output_serializer_free` in the unit-test code.
I'm looking at a code coverage report and realized `array_output_serializer_free` is never called.
OS: Fedora 36
Configured with `-DENABLE_UNIT_TESTS=ON` and built.
Checked `make test` passed
Also checked the unit-test can cover all lines in `libobs/util/array-serializer.c`.
> test: Cover all array_output_serializer functions

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
When ENABLE_HEVC is not set the 'bool hevc' function parameter is not being used in this function causing a warning and aborting compilation.
Fixes compilation with a specific feature set.
Not sure why it actually happened I had `ENABLE_HEVC=OFF`, but with that option compilation would error out due to unused variables.
Compiled with `ENABLE_HEVC=OFF` and `ENABLE_HEVC=ON`
> obs-ffmpeg: Fix compilation when ENABLE_HEVC is not set

- UI/window-projector.cpp
If "transition on double click" was enabled, OBS assumed all double clicks were going to multiview projectors, which isn't necessarily the case.
Fix [reported crash on the forum](https://obsproject.com/forum/threads/repeatable-crash-on-w11.166526/).
Crash was reproduced and new behavior verified.
> UI: Fix crash when double-clicking projector

- CI/linux/01_install_dependencies.sh
Qt6 libraries are installed if the package is available on the system.
Uses the inverted condition to install Qt5 libraries to avoid unnecessarily install both libraries.
Installing Qt5 library is unnecessary but it took ~17 seconds to download and install the packages.
This will also reduce ~100 MB usage of storage.
Checked CI ran without errors.
Compared the log file of with and without this commit.
The difference is only that `WrapVulkanHeaders` is not found while loading Qt6-Widgets, which should not affect the results.
> CI: Download Qt5 conditionally on Linux

- deps/obs-scripting/obs-scripting-lua.c
Sets the script's path as the name when loading the lua script from a buffer.
Someone complained on Discord that their script can no longer get its own filename, and I don't see a compelling reason not to set it.
Short snippet:
```lua
function filename() 
local str = debug.getinfo(2).source:sub(2) 
return str:match("^.*/(.*).lua$") or str 
end
print(filename())
```
> deps/obs-scripting: Set file/chunk name when loading lua scripts

- UI/window-basic-main-outputs.cpp
- UI/window-basic-main-outputs.hpp
- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.cpp
This fixes one of the leaks surfaced by #8846.
Mainly the current virtual cam has the following issues:
- The sceneitem is not released/removed when switching scene collections, retaining a reference to the source
- The private scene is not released, which doesn't itself break anything, but it's just wasting resources
- If `UpdateVirtualCamOutputSource()` gets called but the target source has not changed it is leaked as the reference acquired is only released in the branch where the scene item does not exist yet
+ This would happen e.g. with `SetTransition()` as it would not check if the output type is set to internal (also fixed in this PR)
- Fixed vcam update only being called when set to preview on loading, previously this only worked with scene/source output because `SetTransition()` …
> UI: Reset Virualcam when clearing scene data

- UI/window-basic-main.cpp
Process Qt Events one final time before the leak check runs to give UI code (e.g. volume meter) time to release their held references.
Unfortunately I do not know if this is *the* fix or just happens to work around a race condition. From my testing with additional logging related to the creation and release of references it did seem like the RAII wrapper was always the last one to release the affected sources, and that the `DeactivateAudioSource` function was the last to use the `OBSSource` (the affected sources were always audio sources).
My best guess is that the scheduled (`invokeMethod(...)`) calls from the signal handler for removing the sources from the mixer were not always processed by the time the loop exits, resulting in a race condition where sometimes sources were not fully …
> UI: Process Qt events once after destroy queue finishes

- libobs/obs-cocoa.m
- libobs/util/platform-cocoa.m
Updates Cocoa-specific functions to use Objective C functions instead of C functions to reduce code complexity and ease maintenance.
Also removes support for the older, deprecated, `MACH_TASK_BASIC_INFO` struct.
Cocoa has safe, Unicode-capable, and extensive string handling support - using that functionality brings our code closer to native platform functionality and also easier to maintain (as Apple takes care of maintaining `NSString` and other Cocoa types).
Ran OBS with changes and used step-debugging to check the steps taken by code.
> libobs: Update cocoa functionality for modern macOS

- UI/data/locale/en-US.ini
- UI/platform-osx.mm
Updates Cocoa-specific functions to use Objective C functions instead of C functions to reduce code complexity and ease maintenance.
This is a companion PR to https://github.com/obsproject/obs-studio/pull/8624.
With the CMake 3.0 merge, there is no support for building or running OBS outside of an app bundle on macOS, as such a valid value for `NSBundle mainBundle` can be assumed (and any other situation should not be handled/supported).
Using the `NSScreenSaverWindowLevel` constant to set the window level to stay on top is the "canonical" way to do this, as this also allows the OS to safely place its own windows on top of OBS.
Ellipses added to the permissions menu item - per Apple's Human Interface Guidelines:
> Append an ellipsis to a menu item’s label when people need to provide …
> UI: Update Cocoa functionality for modern macOS

- deps/obs-scripting/obs-scripting-lua-frontend.c
Replaces inline macro function to add frontend functions to the Lua script environment with a pure C-based implementation.
Instead of using a non-debuggable macro function, keep function references and desired function names in a static array that can then be iterated over to add desired functions.
This allows for proper debugging as well as makes the combination of function and function name more explicit.
Used obs test-script used internally to check for Lua functionality (which explicitly checks for availability and return types of frontend API functions).
> obs-scripting: Replace macro adding frontend functions with plain C code

- UI/obs-app.cpp
Installs a message handler for Qt that redirects Qt log messages to the OBS log, so that warnings thrown by Qt will be visible there.
Developers sometimes aren't aware of warnings they're causing, since from time to time new ones appear. This might make them (and fellow developers) more aware.
It also makes it much easier to debug them since you can just breakpoint the blog statement, instead of having to step through the code and to see where stuff is going wrong.
macOS 13.2.1, Qt dev branch.
Tested that the ever-present `QWidget::setTabOrder: 'first' and 'second' must be in the same window` that I haven't gotten around to fixing yet now appears as a warning in the OBS log.
I'm also thinking maybe the message should get prefixed, but I'm not sure which prefix would be fitting.
- Tweak …
> UI: Redirect Qt log messages to OBS log

- libobs/obs-output-delay.c
- libobs/obs-output.c
Adds sanity checks for cases where we shouldn't let certain set functions be performed, when the output doesn't support the associated features. This also does a mild amount of code cleanup, adding inline functions for checking the flags mentioned below.
Since OBS outputs can have any combination of flags for encoded, video, audio, and service, there are a number of cases where it would be a good idea to validate that we're not allowing output changes that risk undefined behavior given the supported flags.
Ubuntu 20.04
- Streaming
- Recording
- Virtual cam
> libobs: Add sanity checks to some obs_output_t functions

- libobs/CMakeLists.txt
Adds `obs.hpp` to list of public headers for `libobs`.
Required for C++-based plugins to correctly compile and link against `libobs`. 
Tested with plugintemplate if include of `obs.hpp` was correctly resolved.
> libobs: Adds obs.hpp to exported header files

- plugins/linux-pipewire/pipewire.c
This adds support for the R10G10B10A2 format to the pipewire-capture plugin.
Wlroots supports 10bit formats and thus the portal implementation does export buffers with this format.
Configure an output with `render_bit_depth 10` in sway and use xdpw from the master branch.
> linux-pipewire: Add support for GS_R10G10B10A2

- UI/window-missing-files.cpp
Re-raises the missing files dialog after a file has been selected to work around QTBUG-42661 which causes windows to disappear behind other windows (behind the main window in particular).
Don't want windows to disappear. Noticed this one disappearing when testing an unrelated reported issue.
macOS 13.3.1
Selecting a file in the missing files dialog no longer causes the window to hide behind other windows.
> UI: Re-raise missing files dialog on macOS after file is selected

- plugins/mac-videotoolbox/encoder.c
Fixes an accidental float to integer conversion which makes the values set for `kVTCompressionPropertyKey_MaxKeyFrameInterval` hilariously wrong. We're creating a number of type `kCFNumberSInt32Type` so we should give that an int instead of a float.
It turns out that a keyframe every 1123024896 frames isn't super useful.
Hopefully fixes reports of encoders on Intel Macs not working properly and streaming services reporting incorrect keyframe intervals.
macOS 13.3.1
Tested that when setting a 2 second keyframe interval and then retrieving the value via `VTSessionCopyProperty`, it's now `120` instead of `1123024896`.
Don't really have an Intel Mac anymore so can't test if it actually fixes the issue reported, but will ask people reporting the problem to test CI builds of this PR.
Edit: CI …
> mac-videotoolbox: Fix incorrect keyframe interval calculation

- libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
When the monitoring device is set to default, this bit of code was appending the no-longer-needed ".monitor' to the device name.
Fixes #8877
Tested by Penwywern on Discord.
> libobs: Fix PulseAudio monitoring when device is set to default

- UI/window-basic-preview.cpp
- UI/window-basic-transform.cpp
- libobs/obs-scene.c
Fixes a bug where if a source's dimensions go to 0 while you are scaling either by dragging the edges or modifying the scaling in the transform dialog, the transform would completely break, causing the source to become permanently invisible until the source's transform is reset somehow or another (Ctrl-F or Ctrl-R).
Also makes it so you cannot modify the scaling widgets in the transform dialog if the source's dimensions are 0.
Fixes #7962
Just fixes an annoying little bug that's been there for a while: permanently invisible sources are bad.
Tested it on a media source with looping off, causing its internal dimensions to be set to 0,0 when playback ends.
> Do not allow scaling when trying to scale 0-dimension source

- libobs-d3d11/d3d11-subsystem.cpp
- libobs/obs-windows.c
Adds logging of HAGS and only sets priority to `HIGH` instead of `REALTIME` if enabled.
Testing showed that HAGS related crashes do not occur when using a lower priority.
Not yet.
> libobs-d3d11: Do not use realtime GPU priority if HAGS enabled

- UI/data/locale/en-US.ini
- UI/window-basic-main-outputs.cpp
This PR fixes a typo in a translation key, adds two missing translations, and also removes obsolete translations in the translation files.
Some texts were not translated but showing the translation-keys.
The newly added translation was tested by dropping an empty folder into the remux dialog.
Concatinated all cpp files under `UI` (and preprocess some of the files).
then, used `sed` and `grep` below to list translation keys from the source code.
```
t=$(mktemp)
cat > $t
function str_arg
{
f="$1"
sed 's/\(\<'"$f"'([^()]*)\)/\1\n/g' < $t |
grep "\\<$f\\>" | sed \
-e 's/.*\<'"$f"'("\([^"]*\)")/\1\n/g' \
-e 's/.*\<'"$f"'("\([^"]*\)" "\([^"]*\)").*/\1\2/g' \
-e 's/.*\<'"$f"'([a-z]\+ ? "\([^"]*\)" : "\([^"]*\)").*/\1\n\2/g' |
}
{ str_arg QTStr; str_arg Str } | LC_ALL=C sort -u
```
Also processed …
> UI: Fix missing translations

- libobs/util/windows/window-helpers.c
- libobs/util/windows/window-helpers.h
Move header inclusion of `dstr.h` into `window-helpers.h` to fix breaking use of `struct dstr` before the type definition.
In its current form `struct dstr` is used in functions declarations in the header file before the actual type is included (as `dstr.h` is included after in `window-helpers.c`.
`clang-cl` is unable to compile this code because the function signature defined in the header will not match the implementation in the source code due to the implicit forward-declaration of `struct dstr` before the type is included in the actual header.
Tested with `clang-cl.exe` and `cl.exe` on Windows 11.
> libobs: Fix struct type usage before actual include

- docs/sphinx/reference-outputs.rst
- libobs/obs-output-delay.c
- libobs/obs-output.c
- libobs/obs.h
- plugins/aja/aja-output.cpp
- plugins/decklink/decklink-output.cpp
- plugins/linux-v4l2/v4l2-output.c
- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
- plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
- plugins/obs-outputs/flv-output.c
- plugins/obs-outputs/ftl-stream.c
- plugins/obs-outputs/null-output.c
- plugins/obs-outputs/rtmp-stream.c
- plugins/win-dshow/virtualcam.c
Depends #8873
This deprecates the following functions, replacing them with new versions:
- `obs_output_can_begin_data_capture()` - now `*capture2()`
- `obs_output_initialize_encoders()` - now `*encoders2()`
- `obs_output_begin_data_capture()` - now `*capture2()`
An implementation to allow audio/video to be optional is best done using the flag technique described below, with audio/video enablement specified by whether media (raw, `video_t/audio_t`) or encoder (`obs_encoder_t`) objects are specified.
Since every implementation I could find always specifies `flags` as 0, I was able to safely conclude that immediately removing the parameters' functionality is safe to do.
The flags parameter was reportedly initially designed to support audio-only or video-only operation of an output which had …
> libobs, plugins: Deprecate obs_output_t functions with flag parameters

- UI/properties-view.cpp
- docs/sphinx/reference-properties.rst
- libobs/obs-properties.c
- libobs/obs-properties.h
Adds `OBS_COMBO_FORMAT_BOOL` to combo formats, making it possible to have bool values in a properties list (dropdown).
Adds `OBS_COMBO_TYPE_RADIO`, which displays a properties list as radio buttons instead of as a combobox. For the API user, input and output behaves the same as `OBS_COMBO_TYPE_LIST`.
Hypothetical case of how this would look (this isn't the actual use case, which will follow in a second separated PR to make reviewing easier.):
<p float="left">
</p>
Technically, these changes are unrelated, but one modifies each other, making it simpler to have them combined (cause the radio type also needs bool support if that would be merged first, so I'd have to fix conflicts from my own PR).
Having radio buttons in properties would be beneficial for some use cases, and a year ago at …
> libobs,UI: Add bool list and radio button list to properties

- UI/context-bar-controls.cpp
- plugins/mac-capture/mac-display-capture.m
- plugins/mac-capture/mac-screen-capture.m
Changes current code for "Display Capture" and "Screen Capture" to store a display's `UUID` instead of its `CGDirectDisplayID` as the latter will be reset upon system restarts.
Display IDs are only (somewhat) guaranteed to stay stable within a given macOS boot session and will be reset/changed upon a reboot. While reboots/shutdowns on macOS are uncommon (a Mac should usually only be restarted upon an OS update), this can lead to user frustration.
Storing the display UUID (and deriving the _current_ Display ID from it) allows us to retain a more stable value in the settings.
The sources themselves use the Display ID at runtime (which makes interacting with macOS system APIs easier and more straight-forward) but when it comes to OBS' settings the code will convert to and from UUIDs. …
> mac-capture: Make display selection based on UUID instead of CGDirectDisplayID

- UI/properties-view.cpp
- docs/sphinx/reference-properties.rst
Deferring properties was only ever made for input sources. As other property dialogs do not have an "Ok" button that would cause an update to happen, if the deferred flag was set the callback would never be called.
Also clarifies the docs to reflect this.
Fixes #5139
Tested that whereas before, setting the flag on scripts and filters would prevent the update signal from being called basically ever, it now is a no-op and the signal is called in all cases.
Tested that with normal sources, the flag still defers saving until pressing Ok/Apply.
> UI: Only defer property updates for input and transition sources

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Add FFmpeg Options for VA-API.
Add option to set custom FFmpeg options for VA-API encoder, which is already available for other FFmpeg encoders.
Checked the options were applied correctly. ArchLinux.
> obs-ffmpeg: Add FFmpeg Options for VA-API

- plugins/obs-ffmpeg/obs-ffmpeg-source.c
Allows plugins to disable the logging of settings every time the ffmpeg source is updated, by passing "log_changes" as true in the settings.
Adds "log_changes" to the ffmpeg source settings. If false, it will not log changes every time the settings of the media source is updated. This does not affect logging of errors and warnings. I did not add this to the properties window because I assume it's used in support channels to check the settings of media sources, so it would be bad if users can set this directly.
I am writing a playlist plugin that uses media sources internally, just as the Image Slideshow source uses Image sources internally. However, Media source spams the log when the settings are updated, which is not ideal for this sort of plugin. Image Slideshow does not have this …
> obs-ffmpeg: Add option to disable settings logging

- UI/scene-tree.cpp
- UI/window-basic-main.cpp
This now saves the grid mode in the grid mode toggle action in the OBSBasic class.
Widgets should not save their own states, just in case they are used elsewhere.
Toggled grid mode
> UI: Move saving of scene tree grid mode

- plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
Fixes a string to say "administrator password" instead of "account password". A non-admin password wouldn't be enough here as we need admin permissions.
Noticed this when looking through crowdin and seeing wrong translations - or at least I thought the translations were wrong until I saw that the source sting was actually the problem.
I suspect that when I originally wrote this string it was probably 4 AM, can't explain this otherwise.
String change, so n/a.
> mac-virtualcam: Fix admin password locale string

- UI/obs-app.cpp
Don't call `close` after the main window gets deleted.
I tried another implementation deleting `snInt` when `main->close()` returns true as below.
Unfortunately, this does not work. If sending 2nd SIGINT to obs while ConfirmExit dialog is open, `close()` returns true so that `snInt` is deleted. Then, if the exit is canceled by a user, `SIGINT` cannot terminate obs again.
```cpp
if(main->close()) {
delete snInt;
snInt = nullptr;
}
```
When I ran a command below on GitHub Actions runner `ubuntu-22.04`, sometimes obs crashes with `SIGSEGV`.
```sh
xvfb-run timeout -s SIGINT --preserve-status -k 30 10 obs
```
When I added `blog` message in `ProcessSigInt`, sometimes `ProcessSigInt` is called multiple times in a short time such as within 80 ms. That results `main->close()` is called after the …
> UI: Fix crash when receiving multiple SIGINT

- UI/window-basic-settings-stream.cpp
Resets service selection to "Custom" if the previously selected service is not found in the dropdown.
Prevents the crash from #8949 for a hotfix, but doesn't address the underlying design issues.
Opened settings; No crash.
-
> UI: Reset service selection to custom if name not found

- UI/data/locale/en-US.ini
- UI/window-basic-main-outputs.cpp
- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
Disallows the user from exiting the audio settings without having selected an audio track.
Split into two commits so that the first commit (for simple mode) can be cherry-picked to the 29.1 branch, while the second commit can wait until the next version.
Fixes #8887
macOS 13.3.1
Unselected all audio tracks in both simple and advanced mode, and saw the popup appear, preventing me from exiting settings. Selected an audio track and exited successfully.
Selected FLV (and "Same as Stream" quality in simple mode) with none of the checkboxes checked beforehand and exited the settings successfully (since the checkboxes don't have an effect with FLV or with Same as stream quality in simple mode).
- Tweak (non-breaking change to improve existing …
> UI: Disallow exiting settings with no audio tracks selected

- UI/data/locale/en-US.ini
- UI/forms/OBSBasic.ui
beab803599e5b9e90e306b2da1f0484064ad9748 changed the string to add ellipses as recommend for menu items that require further action, however the same string was used as the window title (in fact, the key is `MacPermissions.Title`) so the ellipses would also appear in the window title:
That is not desired.
Don't want ellipses in window title.
macOS 13.4
Ellipses is still in menu item but no longer in dialog title.
> UI: Don't use ellipses in permissions window title

- plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
Adjusts the virtualcam strings regarding how the user should act when prompted to install or uninstall the DAL plugin.
It was brought up that there is no "administrator password" on macOS, just accounts with administrator rights.
After a bit of back and fourth it was decided to use the Apple terminology that's also used in the popup that follows, which is "the name and password of an administrator".
Strings change so N/A, but discussed with @PatTheMav.
> mac-virtualcam: Adjust admin privilege strings to use Apple terminology

- UI/window-basic-main.cpp
In the destructor `OBSBasic::~OBSBasic()`, wait until the thread `patronJsonThread` exit.
If a user exit obs while patronJsonThread is running, the thread crashed with the error below.
```
QThread: Destroyed while thread is still running
```
Not crashing is better.
OS: Fedora
1. Block connection to the host.
```
sudo iptables -I OUTPUT -d obsproject.com -j DROP
```
2. Start OBS
3. Open About dialog
4. Exit OBS by clicking `Exit` button on the main window.
After above steps, without this PR, obs crashes.
With this PR, obs won't crash and wait the thread.
5. Then, run this to unblock the connection to the host.
```
sudo iptables -D OUTPUT 1
```
After this, confirmed obs terminated without crash.
> UI: Fix crash on patronJsonThread

- plugins/obs-outputs/rtmp-stream.c
- plugins/obs-outputs/rtmp-stream.h
Cherry picks commit 48a0e7822a4a08c9a252a1d9015d43e023279cc5.
Fixed conflicts by using the old libobs functions instead of the new ones.
People want it cherry picked.
Hasn't.
> obs-outputs: Remove support for "RTMP Go Away" feature in 29.1

- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
The pixel buffer pool is used to create pixel buffers with both the CMIO extension and the DAL plugin. As such, it is created independent of which camera type is used, and should be released independent of it as well.
Saw the code and went "huh?".
macOS 13.4, with the `cmio_extension_supported()` method changed to always return false.
Confirmed in instruments that the memory leak does indeed happen without the fix and that it no longer happens without it.
> mac-virtualcam: Release pixel buffer pool for DAL as well

- UI/forms/OBSBasic.ui
- UI/window-basic-main.cpp
The scene and source rename/remove actions were missing shortcuts in the context menu.
Before:
After:
Noticed by @Warchamp7 
Opened scene/source context menus
> UI: Fix menu actions missing shortcuts

- plugins/text-freetype2/text-functionality.c
Test a pointer `src_glyph` is not NULL before the contents.
A buffer `texbuf` has a fixed size that won't expand. When a lot of multi-byte characters has arrived, it overflow and `src_glyph` becomes NULL.
OS: Linux
- Configure as below.
- Use a Japanese font (`IPAexMincho`, size 72).
- Read from file (`ja.txt`)
- Set `Word Wrap` on
- Prepare some Japanese text files (`ja-1.txt`, `ja-2.txt`, ...)
- On a shell, update `ja.txt` like below.
```
for i in ja-?.txt; do sleep 2; cat $i > ja.txt; done
```
- Check log shows a message below. (Without this PR, obs crashed right after this message.)
```
Out of space trying to render glyphs
```
> text-freetype2: Fix crash after reaching buffer size

- UI/cmake/legacy.cmake
- UI/cmake/os-windows.cmake
- UI/obs-app.cpp
- UI/window-basic-about.cpp
- libobs/CMakeLists.txt
- libobs/cmake/legacy.cmake
- libobs/cmake/os-windows.cmake
- libobs/obs-internal.h
- libobs/obsconfig.h.in
- libobs/obsversion.c.in
- libobs/obsversion.h
- plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
- plugins/obs-outputs/flv-mux.c
- plugins/obs-outputs/ftl-stream.c
- plugins/win-capture/CMakeLists.txt
Moves version and commit hash information out of `obsconfig.h` and into a slim static library to improve ccache hit rate for local compilations and CI runs, as well as reduce amount of necessary recompilations on new commits or reconfigured CMake runs.
Currently CMake generates the `obsconfig.h` header file each time the project is configured (either manually or automatically because a file in the dependency graph has changed).
In its current state this leads to several architectural issues:
* `obsconfig.h` is included by `obs.h` (which is in turn included by `obs-module.h`), so almost every module or piece of OBS is affected by a change of this file and leads to recompilations even though the underlying files haven't changed
* `obsconfig.h` includes version strings but also git commit …
> libobs: Fix ccache misses due to unstable obsconfig header

- docs/sphinx/reference-sources.rst
Clarifies the documentation on the `update_properties` signal of a source.
Over time, there's been a lot of confusion about this signal.
Quite a few of people (including myself) mistook it for a signal that's called when a source's settings are updated, which is wrong.
Had CI generate the docs:
> docs: Clarify source update_properties signal

- UI/data/locale/en-US.ini
- UI/forms/OBSBasicVCamConfig.ui
- UI/window-basic-main-outputs.cpp
- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-basic-vcam-config.cpp
- UI/window-basic-vcam-config.hpp
- UI/window-basic-vcam.hpp
Fixes #7780
Depends on #7169 so review the last commit.
This change allows the virtual camera to really output what is in the program view, some plugin interract with this view but their changes does not appear on the virtual camera.
This change requires to restart the virtual camera when changing the view is needed, so changing from/to the Program type will require a restart.
New type list:
Output selection when Program or Preview is selected:
Warning when changing from/to Program type:
The virtual camera shall show the program view and this is not case.
1. Install downstream keyer plugin
2. Add and enable a downstream keyer
3. Start virtual camera with program as type
4. Check output of virtual camera is the same as the main output of obs …
> UI: Use main video on the virtual camera if program

- UI/forms/OBSBasicFilters.ui
- UI/window-basic-filters.cpp
- UI/window-basic-filters.hpp
This fixes the shortcuts not showing up in the filters context menu for rename and remove. This also has a code cleanup for the rename action, as now it is created in the ui file.
Before:
After:
Helps users know what the shortcuts are.
Renamed/removed filters
> UI: Fix filter shortcuts not showing in context menu

- UI/window-basic-settings-stream.cpp
#8951 was intended to avoid a crash by resetting the service combobox to default if a service is not on the list. What we missed is that if a service is not shown by default, i.e. not has the `common` flag set, it would not be found and the selection reset.
This fixes the actual reason for the crash by adding a NULL check to `find_output`, which results in the behvaiour being as before where a stub service entry is created in the UI until the user selects a different one.
Note that the second commit (c5714e495d8c1c3a215c55b4b880e1ad393b1733) should probably be picked to master as well.
Users want to be able to stream to services that are not listed by default.
Tested with outdated service file originally used for testing #8951 and selected uncommon service to verify it works as intended. …
> Fix non-common services not being selectable

- UI/window-basic-settings-stream.cpp
- plugins/mac-videotoolbox/encoder.c
Currently, encoders are displayed in the UI in the order they are registered to libobs. In practice, this means in whatever order their modules are loaded and, if a module registeres multiple encoders, in which order it does that.
This leads to the order appearing to be basically random to the end user.
<p>
</p>
In the videotoolbox plugin, we had to implement custom sorting in the plugin before registering the encoders to libobs because they were discovered by macOS in an inconsistent order. This has always been a thorn in my eye, and I want to get rid of it. I don't think how things are displayed in the UI should depend on the order they were added to libobs in.
macOS 13.4
Made sure both audio and video encoders are all still there, and that they are now sorted.
Made a few test …
> UI: Sort encoders alphabetically

- plugins/obs-ffmpeg/texture-amf.cpp
For AMF, before a component can be reinitialized with the `ReInit` method, either `Flush` or `Drain` needs to be called on the same object to remove any frames which are still in the component for processing.
Calls to either `Flush` or `Drain` must be done before any calls to `ReInit` for AMF. This was missing in the current code and would cause encoding to break if the bitrate was changed for example while recording or streaming. This resolves issue #8548.
Tested on Windows 10 with an AMD Radeon RX 7900 XTX.
Bug fix for issue #8548
> obs-ffmpeg: Fix AMF encoder reconfiguration

- UI/data/locale/en-US.ini
- UI/window-basic-main.cpp
This change makes the mixer toolbar also show/hide when toggling the source toolbars in the view menu.
Make it consistent with the scene/source toolbars, so the user can maximize space if they so choose.
Toggled toolbars
> UI: Also toggle mixer toolbar in view menu

- UI/data/locale/en-US.ini
- UI/forms/OBSBasic.ui
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Before: widgets docked on the sides of the preview are of the height of the preview
After: the user can toggle the setting in the docks menu so the side widgets are of the height of the whole window
The feature is long requested. It was stated that the feature would require total rewrite of widget system.
https://ideas.obsproject.com/posts/488/allow-top-level-vertical-splits-for-docks
https://obsproject.com/forum/threads/chat-dock-size-customisation.151609/
https://obsproject.com/forum/threads/make-a-widget-full-vertical.150216/
It is actually possible with minimal changes and backward compatibility.
Tested on Windows 10 system.
This is a new feature that allows user to have docks of the height of the main OBS window.
> UI: allow side docks to be tall

- UI/api-interface.cpp
- UI/obs-frontend-api/obs-frontend-api.cpp
- UI/obs-frontend-api/obs-frontend-api.h
- UI/obs-frontend-api/obs-frontend-internal.hpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- docs/sphinx/reference-frontend-api.rst
**Depends on:**
- https://github.com/obsproject/obs-studio/pull/7636
**Dependency of:**
- https://github.com/obsproject/obs-studio/pull/7638
https://doc.qt.io/qt-6/qmainwindow.html#saveState
> You should make sure that this property is unique for each QToolBar and QDockWidget you add to the QMainWindow.
We should avoid letting plugins add docks with the same object name. So to implement that:
- `obs_frontend_add_dock()` is deprecated in favor of `obs_frontend_add_dock_by_id()` and `obs_frontend_add_custom_qdock()` which ask for an unique id (object name). The dock is not added if the id is already used and return false in this case. 
- Also the new method does not return a QAction since internally we use the one included in QDockWidget.
- `obs_frontend_add_dock()` implements a temporary …
> Avoid having two docks with the same object name

- UI/properties-view.cpp
Don't trigger a settings update when property list is empty
To avoid recursive call
Fixes #7299 
When property list is empty, the `idx` assigned to `combo->findData(value)` is always `-1`.
https://github.com/obsproject/obs-studio/blob/db766273b60a07a9a9b308b98f020e41a0658e56/UI/properties-view.cpp#L626-L628
This cause recursive call in `RefreshProperties`
`RefreshProperties` -> `AddProperty` -> `AddList` -> `ControlChanged` -> `RefreshProperties` ...
on win10, obs28
add `return;` procedure above `add_window` in this function
https://github.com/obsproject/obs-studio/blob/db766273b60a07a9a9b308b98f020e41a0658e56/libobs/util/windows/window-helpers.c#L422-L434
before fix:
sometimes the buttonBox cannot work well
after fix:
work fine
> UI: Don't trigger a settings update when property list is empty

- libobs/obs-windows.c
The debug symbol path is duplicated in windows. The following is the debug symbol paths set by the program.
```
{array=0x000001db458ddc60 "E:\obs\obs-studio\cmake-build-debug\rundir\Debug\bin\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit;E:\obs\obs-studio\cmake-build-debug\rundir\Debug\obs-plugins\64bit …
```
> libobs: Remove duplicate debug symbol paths in Windows

- plugins/win-capture/window-capture.c
Render nothing if window is iconic.
to fix #5034
tested on window10
> win-capture: Render nothing if window is iconic

- plugins/win-capture/compat-helpers.c
Fixes compatibility messages appearing when no window is selected in window capture properties.
First matching message appearing when no window is selected is weird.
Ran OBS and tested with an empty window capture source.
> win-capture: Skip compat helper matching if properties are null

- libobs/util/sse-intrin.h
MinGW comes with it's own intrinsics macros as regular MSVC does. On MinGW the inclusion of SIMDe would cause multiple definitions of the same macro names.
Since sse-intrin.h leaks into the public header space this will cause 3rd party plugins build with MinGW tool-chains emit redeclaration warnings when including obs-module.h.
Change an #ifdef to change behavior when compiling with MinGW tool-chains.
Another way would be to just switch out the original `_MSC_VER` check with `_WIN32`, but I'm not sure which approach is more desired.
I like to build my plugins from non-Windows platforms without having to use MSVC.
Compile a noop C app with including `obs-module.h`.
Compiling with a common available MinGW compiler.
```C
// x86_64-w64-mingw32-gcc -I ../obs-studio/libobs main.c
// …
```
> libobs/util: Do not include SIMDe for MinGW targets.

- UI/obs-app.cpp
This PR removes a function `move_to_xdg`, which moves configuration directory from the old `$HOME/.obs-studio` to current XDG's directory.
The configuration directory was `$HOME/.obs-studio` until version 0.10.1 and then moved to XDG's configuration path by ba02e065fe.
The function `move_to_xdg` left almost untouched for 8 years.
I don't think it's unnecessary for now to move the configuration at 0.10.1 or earlier to the latest but it's better to create the configuration from scratch.
OS: Fedora
Start obs and confirmed it opens the configuration as usual.
It's a breaking change for users who last used obs-studio version 0.10.1 …
> UI: Remove move_to_xdg

- libobs/obs-properties.c
Fixes the same issue as #9019 but in a minimal way that restores pre-29.1 behaviour.
As mentioned in https://github.com/obsproject/obs-studio/pull/9019#issuecomment-1575590865 this may still be problematic if the property whose callback is being executed is deleted during the callback. For that reason this is only targeting the `release/29.1` branch to leave discussion for an alternative approach open while mitigating possible crashes in 29.1.x.
Fix crash.
Hasn't been.
> libobs: Fix crash when properties are deleted in callback

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
[Livepeer](https://livepeer.org) is a decentralized video infrastructure protocol which is designed to power the new creator economy. [Livepeer Studio](https://livepeer.studio) is our flagship product to let users easily interact with the protocol and start a livestream.
We have many users currently streaming into Livepeer Studio using a custom RTMP setup. Similar to other RTMP providers who have added configs to OBS, we have [custom documentation](https://docs.livepeer.org/guides/developing/stream-via-obs#configuring-obs-for-low-latency)/support for users who are setting up OBS and trying to get low latency out of the box. We are hoping to add this so that we don't need to educate users on b-frames and keyframe intervals, and they can just select our preset and start streaming.
We have …
> rtmp-services: Add Livepeer Studio

- plugins/mac-capture/mac-screen-capture.m
Explicitly sets a clear background color for SCK sources, so that window corners as well as the background of Application Capture remain transparent.
macOS 14 changed the default from transparent to white, making window corners and Application Capture white.
We want this to stay transparent.
macOS 14, things are transparent again.
> mac-capture: Explicitly set clear background for SCK

- libobs/util/darray.h
After the array is allocated in `darray_ensure_capacity`, the pointer `item` is invalid.
This PR moves `darray_ensure_capacity` earlier than starting to modify the contents of the array.
I was checking code coverage, adding a test code, and found the bug.
The function `darray_insert_new` is called from only `obs_property_frame_rate_option_insert` and `obs_property_frame_rate_fps_range_insert`. Both of them are never used in the obs-studio repository and it's submodules.
OS: Fedora
Tested with a modified test code.
https://github.com/norihiro/obs-studio/blob/test-darray/test/cmocka/test_darray.c
> libobs/util: Fix use-after-free in darray_insert_new

- libobs/obs-internal.h
- libobs/obs-video.c
- libobs/obs.c
Don't keep the sources mutex in tick_sources
Allow other threads to use sources while the graphics thread does video_tick, update, activate and deactivate on sources
For example in a gdi+ text source the update and video_tick (when reading file from slow disk or network) can take long.
All this time the sources_mutex was locked, blocking other threads like obs websocket calls.
On windows 64 bit by trying to update a gdi+ text source via obs websocket multiple times a second.
> libobs: Don't keep the sources mutex in tick_sources

- deps/obs-scripting/obs-scripting-lua.c
Sets the correct `current_lua_script` prior to `script_unload()` call to allow using OBS API in that hook
Fixes #8997
Tested by repro steps on Windows 10 machine
> obs-scripting: Fix the pointer to current_lua_script when calling script_unload() in Lua script deinitialization

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Changes the name to ThemeChanged, as the function now does more than reset the volume sliders.
Better code readability
Changed themes to make sure nothing broke
> UI: Change name of ResetProxyStyleSliders function

- docs/sphinx/reference-outputs.rst
- libobs/obs-output-delay.c
- libobs/obs-output.c
- libobs/obs.h
- plugins/aja/aja-output.cpp
- plugins/decklink/decklink-output.cpp
- plugins/linux-v4l2/v4l2-output.c
- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
- plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
- plugins/obs-outputs/flv-output.c
- plugins/obs-outputs/ftl-stream.c
- plugins/obs-outputs/null-output.c
- plugins/obs-outputs/rtmp-stream.c
- plugins/win-dshow/virtualcam.c
Effectively reverting parts of d314d47, this commit removes the new functions that got added to remove the flags parameter. Instead, it just marks the parameter as unused and documents this. Having what is effectively an API break just to remove a parameter is a bit overkill. The other parts of d314d47 which cleaned up the usage of the flags parameter are untouched here.
People brought up that this effective API break is a bit extreme, and I agree.
If we want to merge this, we'll have to do so before the first beta of the next release, so opening this now to get the discussion going.
macOS 13.4
Tested that it still compiles, as well as making sure that recording and streaming still works.
> libobs,plugins: Remove new obs_output_*2 functions

- UI/properties-view.cpp
Fixes a memory leak where a combobox would be created even when radio buttons are used for a list, and then not be used.
Static analysis yelled at me.
macOS 13.4
Static analysis no longer yells at me. Comboboxes and radio buttons both still work. 
> UI: Don't create combobox for radio buttons in properties view

- UI/context-bar-controls.cpp
Don't update text source when nothing changed
When selecting different text sources the source toolbar would create undo records and update the source while nothing was changed.
On windows 64 bit by selecting different text sources
> UI: Don't update text source when nothing changed

- UI/window-basic-settings-stream.cpp
Don't show the WHIP stream menu item if the webrtc plugin is disabled
Currently if you don't have the webrtc plugin enabled you would crash in stream settings
Tested with and without the plugin enabled on macOS
> UI: Don't show WHIP in stream settings if the protocol isn't registered

- plugins/obs-webrtc/whip-output.cpp
The obs-webrtc PR was merged before 79822a58c, but the PR of 79822a58c was not rebased on latest master before being merged. As such, the usages of the obs_output_*2 functions was not removed by that PR.
I break it, I fix it.
macOS 14
Code compiles now.
> obs-webrtc: Use old obs_output functions

- plugins/linux-pipewire/pipewire.c
After a failed import we should signal buffer renegotiaten and then just skip processing this videobuffer.
Found by investigating #8925 
> linux-pipewire: Skip processing video buffer if import failed

- UI/window-basic-main.cpp
- UI/window-basic-settings.cpp
- deps/libff/libff/ff-util.c
- deps/libff/libff/ff-util.h
FFmpeg added support for PCM in MP4 in https://github.com/FFmpeg/FFmpeg/commit/d4ee177a36c59b19de474d3713304c7828263cb0 and bumped the minor version of libavformat in https://github.com/FFmpeg/FFmpeg/commit/dc2da568cfd281740102032582ca25bbf4449100 so we can now support this via some simple ifdefing.
Support AV1+PCM in containers other than MKV.
Has not been tested yet.
> Support PCM in MP4 with newer libavformat

- UI/win-update/updater/hash.cpp
- UI/win-update/updater/http.cpp
- UI/win-update/updater/patch.cpp
- UI/win-update/updater/updater.cpp
- UI/win-update/updater/updater.hpp
This is essentially the same as #8815 but without support for bundles as they do not provide enough of a benefit with our fast CDN, and we want to move to curl + HTTP/2 multiplexing soon.
**Changes:**
- New `B2Hash` typedef for blake 2 hashes (`std::array<std::byte, 20>`)
+ Also added `std::hash` specialisation to allow using it in maps or sets
- Stop using temporary files for downloads (uses RAM instead)
+ VC redistributables installation still uses a temp file, so the folder in `%TEMP%` will still be created/removed
- Moved some defines to global `constexpr` variables
- Moved some hardcoded values to global variables
- Removed a lot of utf8<->wide conversions that were unnecessary now that temporary files aren't used anymore
- Changed some for loops to use iterators instead of indices …
> updater: Refactor and cleanup

- UI/window-basic-main.cpp
Moves the preview lines around sources to be rendered above the preview safe area lines.
Suggestion from @Warchamp7 
Looked to see if everything was rendered correctly.
> UI: Render preview lines above safe areas

- libobs/obs-output.c
> Fix NULL pointer access introduced in #8093

- .gitmodules
- cmake/macos/helpers.cmake
- plugins/mac-syphon/CMakeLists.txt
- plugins/mac-syphon/SyphonOBSClient.h
- plugins/mac-syphon/SyphonOBSClient.m
- plugins/mac-syphon/syphon.m
Updates the syphon to use the Syphon.framework from obs-deps instead of the submodule, and removes the submodule.
The submodule was not updated in 9 years and additionally had custom patches. We want to get away from having submodule dependencies, and also from having custom patches for dependencies.
macOS 13.3
Tested with a custom obs-deps that includes `Syphon.framework` framework.
Ran their [sample server](https://github.com/Syphon/Simple) and had it correctly get picked up, announce creation and retirement; and received the correct frames.
> mac-syphon: Update syphon, use obs-deps framework, remove submodule

- plugins/obs-ffmpeg/texture-amf.cpp
There was a typo in the last change to the AMF quality preset fallback logic. This change fixes that typo.
This is needed to fix a typo in the earlier PR #9034.
Tested on Windows 10 with an AMD Radeon RX 7900 XTX.
> obs-ffmpeg: Fix logic in one of the AMF preset fallback checks

- plugins/mac-capture/mac-screen-capture.m
Adds a SCStreamDelegate logging when SCK sources stop with an error.
Having a delegate is needed for a future PR where we have to introduce some sort of UI feature that re-enables a stopped stream, as macOS 14 adds a UI for the user to stop SCK streams outside of OBS, or for when the computer goes to sleep (see https://github.com/obsproject/obs-studio/issues/8928).
I'm also low-key hoping (at least a tiny bit) that it could help us diagnose remaining freezing issues that still pop up very sporadically (assuming that they exit with error codes), and as such wouldn't mind this change making its way into a hotfix release (assuming other people think that's acceptable).
macOS 14
Put computer to sleep and (when waking it up again) saw the "Stream stopped with no capture source" message in the …
> mac-capture: Add SCStreamDelegate to stream to log capture errors

- plugins/mac-capture/window-utils.m
Fixes a new warning where the CFString `kCGWindowOwnerPID` is casted to an `NSNumber`.
This is wrong. Things most likely currently works because I think when using it it's implicitly casted to `NSString` but really it should never be casted to a number in the first place.
Warning popped up, don't like warnings.
macOS 14
Checked that in the dictionaries where `OWNER_PID` is used that the key is indeed a string.
Tested in a debugger that the comparisons still work the same as before.
> mac-capture: Fix wrong CFString to NSNumber cast

- plugins/mac-syphon/syphon.m
`OBSSyphonKVObserver` was once used to listen to announce/retire events (?) but that has been changed at some later point. Since then, this code is unused.
Noticed after the recent syphon changes (which, to be clear, did not remove the usage of OBSSyphonKVObserver, that was earlier).
macOS 14, still compiles
Did a `git grep` for `OBSSyphonKVObserver` without any results.
> mac-syphon: Remove unused OBSSyphonKVObserver

- libobs-d3d11/d3d11-subsystem.cpp
Adds more detailed logging for HAGS status, including whether or not it is supported, enabled by default, and if support in the driver is considered "experimental".
All the info for all the supporters.
Ran locally, could probably use tests from others.
Results:
```
04:14:54.763: Initializing D3D11...
04:14:54.763: Available Video Adapters: 
04:14:54.766: 	Adapter 0: NVIDIA GeForce RTX 4090
04:14:54.766: 	  Dedicated VRAM: 25329401856
04:14:54.766: 	  Shared VRAM:    34219354112
04:14:54.766: 	  PCI ID:         10de:2684
04:14:54.766: 	  HAGS Status:    Disabled (Default: No, Driver status: Supported)
04:14:54.766: 	  Driver Version: 31.0.15.3179
```
> libobs-d3d11: More detailed HAGS logging

- docs/sphinx/reference-frontend-api.rst
In the Docs the parameter name is wrong ("collection" vs "profile"). See how it looks:
https://docs.obsproject.com/reference-frontend-api#c.obs_frontend_set_current_scene_collection
Screenshot
Documentation should be clear from misinterpretations
It wasn't.
> docs: Fix param name

- plugins/text-freetype2/text-freetype2.c
Update vertex buffer when chat log mode property is toggled.
1. Create an instance of Text (FreeType2).
2. Set `Text input mode` to `From file` and specify a file containing more than 6 lines.
3. Toggle `Chat log mode` property.
Without this PR, the drawing does not change when toggling the property.
With this PR, the drawing will change so that only the last 6 lines are rendered.
> text-freetype2: Fix not updating chat log mode property

- UI/window-basic-main.cpp
Toggles the check state of the menu item to show/hide the source toolbar when the hotkey changed the show/hide state of the source toolbar.
Hotkeys can toggle the source toolbar. When the visibility of the source toolbar has changed, the check state of the menu item should be consistent.
1. Set the hotkeys for `Show Source Toolbar` and `Hide Source Toolbar` in the settings.
2. Toggle the source toolbar by the hotkey.
3. Check the menu item `View` -> `Source Toolbar`.
> UI: Fix checked state of source toolbar menu item

- UI/window-basic-settings.cpp
Set the changed state when changed something, but do not clear the changed state.
The member variable `channelIndex`, `sampleRateIndex`, and `llBufferingEnabled` hold the settings that was read from the configuration when the settings was opened.
When changing audio channels, sample rate, or audio buffering settings multiple times by hitting `Apply` button, the internal `changed` state got corrupted.
Tested with these two scenarios.
- Changed sample rate multiple times.
1. Open the settings dialog.
2. Change the sample rate to 44.1 kHz.
3. Hit `Apply` button.
4. Change the sample rate to 48 kHz.
- Expected `Apply` button is enabled but actually left disabled.
5. Hit `OK` button, restart OBS manually, and open the settings dialog.
- Expected the sample rate is 48 kHz but actually 44.1 kHz. …
> UI: Fix changed state of audio settings

- UI/window-basic-source-select.cpp
Translate the place holder for the new group name.
When creating a source, the default names are translated for other sources but not for the group only.
OS: Linux
1. Start obs with non-English locale.
2. Right-click the sources list.
3. Click `Add`.
4. Click `Group`.
5. Check the default name is translated.
> UI: Translate place holder name for new group

- UI/window-basic-source-select.cpp
Disables the "Ok" button in the Add Source dialog if the user wants to add an existing source but hasn't selected one yet.
Current behaviour will either do nothing or use the first item in the list, which is not desirable.
Before:
https://user-images.githubusercontent.com/59806498/233029647-ae4ceb22-e9a4-442c-b9ac-bde6b5ccbf34.mov
After:
https://user-images.githubusercontent.com/59806498/233029835-d654f3ce-f29d-470e-805d-582634d6a3fd.mov
People complained on Discord.
macOS 13.3.1
Tested both with normal sources and with scenes, when nothing is selected in the list the button is now disabled until something is selected.
> UI: Disable Ok button in Add Source dialog if no source is selected

- deps/media-playback/media-playback/media-playback.c
- deps/media-playback/media-playback/media-playback.h
- deps/media-playback/media-playback/media.c
- plugins/obs-ffmpeg/obs-ffmpeg-source.c
Some options do not require a media source restart. Saving source unchanged source settings should also not trigger a restart.
I tried to also make it so speed changes do not require a restart by manipulating the elapsed timestamp  for the source, but it sometimes causes the first few milliseconds after saving settings to be rough or slightly distorted. I am also unsure whether a/v frame buffers should be cleared on a speed change (and how to) so I made it so restarts are required for speed changes. Chiyo also mentioned that successive quick speed changes will cause maximum audio buffering (which I was able to reproduce once).
Nonlocal file playback is unaffected, and will cause the media source to restart because I am not aware of the possible consequences and because there's no restart …
> obs-ffmpeg: Prevent media source restart

- .github/workflows/main.yml
Removes 20.04 as per https://github.com/obsproject/obs-studio/discussions/9055.
Want #9061 and #9062 to build.
N/A
Code cleanup (non-breaking change which makes code smaller or more readable)
> CI: Remove Ubuntu 20.04 build

- UI/forms/OBSBasic.ui
In Qt Creator, the transition add/remove buttons had no icons, as the paths were incorrect.
Make sure the icons were correct
Opened Qt Creator to make sure the icons showed up
> UI: Fix icon paths of transition buttons

- libobs/obs-windows.c
Adds a `log_conflicting_software` function which can be used to check for and log possible 3rd party software interference, in this case, Lenovo Vantage.
I'm not sure if the best place for this is in libobs or OBS, discussion welcome.
Many users have Lenovo PCs and Lenovo Vantage / Legion Edge ("gamer" version) is pre-installed, causing issues with OBS that aren't immediately obvious. By logging this it is easier to handle support cases; ideally when we have a non-critical notification system it can also be raised there.
Not tested very well as I don't have such software installed.
> libobs: Detect and log presence of Lenovo Vantage on Windows

- plugins/obs-ffmpeg/obs-ffmpeg-source.c
Quick fix for https://github.com/obsproject/obs-studio/pull/7455, as I only realized the flaw in my logic a few hours after i pushed. The issue is that when looping is turned on but the source is inactive, `ffmpeg_source_start` will be called, causing the video to play in the background (but not actually shown).
Do note that the comment above the looping change check does not currently do what was intended, because media source sets the state to ENDED regardless of whether the user stopped it manually or reached the end. I plan to fix the media source state in a future PR.
My mistake, sorry!
- Played the file, then hid the scene item of the source. Then turned on the Loop option. The video and progress bar didn't play.
- Tested other options that would trigger a forced restart, like …
> obs-ffmpeg: Fix media source playing when inactive

- plugins/mac-capture/mac-screen-capture.m
This patch fixes "Show fullscreen and hidden windows/applications", "Show windows with empty names" options works immediately on properties pane as UI behaviors expected.
macOS Screen Capture properties pane has various check box but these are not working as expected until it's opend again. 
Add macOS Screen Capture to the Sources, grant Screen Capture permissions (and restart the application if necessary,) then open property pane.
Toggle these check mars and observe list of windows or applications are immediately updated.
`screen_capture_build_content_list` or similar calls uses updated `sc->show_hidden_windows` or similar flags, but these are not set before calling these functions. Changing order of calls to solve the problem.
> mac-capture: Fix  show hidden windows option which doesn't work immediately.

- plugins/rtmp-services/rtmp-custom.c
For mpegts output, used in rtmp-custom service, encoder settings
require:
- ADTS with fdk-aac.    
For all non-rtmp protocols, one also requires:
- video encoder header repetition;
This future proofs the code against protocol addition.
Additionally, I've added a check against NULL audio settings, which was
in my fork but that I forgot to add in the PR [1] to my utter shame.
🙈
[1] https://github.com/obsproject/obs-studio/pull/6163
Force audio encoder settings only for SRT and RIST.
Force header repetition for all non-RTMP protocols.
Checked that an srt stream with nvenc h264 / fdk-aac does not errors out meaning
the encoders settings were enforced.
> rtmp-services: Enforce encoder settings according to protocol

- libobs/obs-output.c
Amends 6ec0b2db11d5fde051d533609a974fb0fa81ff05 to have the `obs_output_get_height2` function actually return the height of the output instead of the width.
yam on Discord brought up that their recordings were square, and reported as 1920*1920.
I tested it and it turned out my recordings are square as well.
I don't like having square recordings when I configure them to not be square.
macOS 14.
Tested that all players now play back the recording in the correct resolution and aspect ratio.
> libobs: Fix obs_output_get_height2 returning width

- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs.h
- plugins/obs-ffmpeg/obs-nvenc.c
- plugins/obs-ffmpeg/texture-amf.cpp
- plugins/obs-qsv11/obs-qsv11.c
Allow GPU based scaling of output (textures) using on-demand created `obs_core_video_mix`es
Currently if multiple outputs require different output resolution there's only one resolution that gets converted (and downloaded) on the GPU, which caused people to stream at 720p and upscale 720p to 1080p for recording in the past (not sure if that still happens).
Additionally, this allows encoders that take texture inputs to also be rescaled.
Modified `window-basic-outputs.cpp` to enable GPU scaling for the streaming encoder, set streaming encoder to rescale to 720p with a base output resolution of 1080p and observed `obs-nvenc` (as opposed to `FFmpeg NVENC`) log messages; also checked the resulting output file for proper resolution
- …
> Add GPU based output scaling

- UI/adv-audio-control.cpp
- UI/context-bar-controls.cpp
- UI/source-tree.cpp
- UI/volume-control.cpp
- UI/window-basic-filters.cpp
- UI/window-basic-main-dropfiles.cpp
- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.cpp
- UI/window-basic-preview.cpp
- UI/window-basic-properties.cpp
- UI/window-basic-transform.cpp
- libobs/obs-scene.c
Migrates various undo/redo actions to using UUIDs instead of source names.
Names are temporary, UUIDs are eternal.[^1]
[^1]: UUIDs for private sources that are not saved/loaded via `obs_save_source()` and `obs_load_source_type()` only persist for the lifetime of the source in the current session.
Undid and redid stuff.
> UI: Migrate undo/redo to using UUIDs

- deps/obs-scripting/obs-scripting-python-frontend.c
Any frontend_save_callback added through a python script, when triggered,
doesn't recieve any calldata, and the triggering often causes errors in the log.
This is caused byPy_BuildValue being directly passed a C bool, which the function
doesn't accept, causing the building of the arguments passed to the callback to fail.
This fixes the callback by passing instead a Py_Bool object built from the C bool.
To reproduce the issue :
- add the script linked below to obs
- trigger a frontend save event (typically, changing settings and applying them)
- check the log for the arguments the callback recieved and errors
[Log showcasing the issue.](https://obsproject.com/logs/ESIvJQ8N2n4KR5e9)
tester script : [save_cb_tester.zip](https://github.com/obsproject/obs-studio/files/11585412/save_cb_tester.zi …
> obs-scripting: Fix python save callback Py_BuildValue

- .github/workflows/main.yml
- cmake/macos/defaults.cmake
- cmake/macos/resources/package.applescript
Splits up macOS builds on CI between a macOS 13-based runner for building the project and a macOS 12-based runner for generating disk images for distribution.
Since early 2023, Xcode 14.3 and later requires macOS 13 to run. This requires switching to macOS 13-based runners for support of macOS 14 and beyond.
Unfortunately macOS 13-based runners are still considered "beta" by GitHub themselves (though many issues are fixed purely by switching to a more recent macOS version). For obs-studio specifically, AppleScript support is required to create the disk images used for release, but this support is not available in those runners.
The common workaround to this issue is to generate application bundles on macOS 13 runners, upload them as artefacts, then download and package them on a macOS 12 …
> CI: Update main workflow to enable building with macOS 13 runners

- .github/workflows/main.yml
When using long options with `base64` on macOS, you must separate the option from the value with an equal sign.
CI is currently broken. Want CI to work.
Tested locally.
> CI: Fix call to base64 on macOS

- libobs/cmake/legacy.cmake
- plugins/obs-ffmpeg/obs-nvenc-test/cmake/legacy.cmake
- plugins/win-capture/cmake/legacy.cmake
- plugins/win-dshow/cmake/legacy.cmake
Adds necessary code to allow legacy code paths to configure without changes to existing configurations.
By default Windows builds use the legacy CMake code paths, which ideally work as-is with existing build directories. Switching to the new code paths should be opt-in (via preset selection), so at least for the time being existing configurations should continue to work after the code update.
Tested on Windows 11 with existing build configuration from _before_ the CMake 3.0 merge and reconfigured in place after updating to current master commit.
> cmake: Fix configuration errors with Windows legacy path

- UI/cmake/feature-restream.cmake
- UI/cmake/feature-twitch.cmake
- UI/cmake/feature-youtube.cmake
Unobfuscated secrets require the hash values to be set to 0, by default CMake will treat 0 as a falsy value. This commit adds support for _either_ 0 _or_ a valid hexadecimal hash.
Allow maintainers and forks to provide their own unobfuscated OAuth credentials.
Tested locally with variants of empty hash values, using `0`, and using actual hash values.
> cmake: Add support for unobfuscated OAuth secrets

- cmake/windows/compilerconfig.cmake
- cmake/windows/helpers.cmake
Compiler and linker flags for reproducible builds on Windows were omitted from the recent CMake rework in error. This commit adds those flags back.
Restores desired ability to create reproducible builds on Windows.
Will be tested by CI run on Windows.
> cmake: Add flags for reproducible builds on Windows

- UI/window-basic-main-transitions.cpp
This adds a log info message whenever the user changes the Program scene in studio mode.
This was requested for troubleshooting purposes.
[Link](https://discord.com/channels/348973006581923840/376042662580715521/1116925630697701377)
Tested on ubuntu 22.04 by being in studio mode and checking that all transition methods (clicking button, double clicking scene name, Tbar slide and quick transitions) correctly trigger the message. 
> UI: Log Program scene changes in studio mode

- libobs/graphics/effect-parser.c
- libobs/graphics/effect-parser.h
- libobs/graphics/effect.c
- libobs/graphics/effect.h
- libobs/obs-internal.h
- libobs/obs-module.c
- libobs/obs-scene.c
- libobs/util/cf-lexer.c
- libobs/util/cf-lexer.h
- libobs/util/darray.h
- libobs/util/profiler.c
- plugins/image-source/obs-slideshow.c
- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-mux.h
- plugins/vlc-video/vlc-video-source.c
Defines type of DARRAY macros and changes function parameter types using `struct darray *` to the newly defined types.
Also add parentheses in DARRAY macros so that any expression can be passed to the macro as if it is a usual function.
Inspired by #9048.
Currently, a pointer of `struct darray *` is passed to some functions because the unnamed union types cannot be identified as the same type even though the union definition is actually same.
However, using the type `struct darray *` looses the types of the element so that it requires type casts.
To avoid the type-casts, I'd like to suggest defining the DARRAY macro types at one place using `typedef` for each usage.
OS: Linux
Compiled with GCC and Clang. CI will also test the code can be built.
Image slideshow and VLC source are tested. …
> Define types of DARRAY macro to carry element types

- plugins/mac-capture/plugin-main.c
Marks the CoreAudio output capture source as deprecated when on macOS 13 or newer, hiding it away in the "Deprecated" folder of the Add Source menu along with the old screen capture sources.
With macOS Audio Capture merged, users now have a clear and obvious way to capture desktop audio, which does not require any virtual audio cables shenanigans or alternatively hiding a screen capture source.
To avoid confusion, I think it makes sense to hide the old capture source away in the deprecated category and only show the new capture method when supported (macOS 13+). *Technically* the new source doesn't cover 100% of the use cases of the old method (you can't split a programs audio stream into different sources, which in theory could be achieved with the old method and supported applications) …
> mac-capture: Mark CoreAudio output capture source as deprecated

- UI/update/shared-update.cpp
Fixes reading/writing files with non-ASCII characters in their path in the shared code of the update framework.
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Compiled and ran on my machine. Still needs to be tested on an affected system.
> UI: Fix utf-8 paths in shared updater components

- cmake/windows/helpers.cmake
Generated post build action batch scripts retained an empty token to the copy command with the used generator expression (as PDBs are only generated for Debug and RelWithDebInfo configurations).
Moving their copy step into its own command (and using the `true` CMake command, which is a no-op) ensures that builds in Release and MinSizeRel correctly finish this step.
Fix builds in Release and MinSizeRel configurations.
Tested on Windows 11 with all 4 configurations.
> cmake: Fix copy to rundir in Release and MinSizeRel configurations

- plugins/mac-capture/mac-sck-audio-capture.m
Removes a log line introduced in 239e9273d that looks like it was for debugging purposes. 
This log always prints an error message when an SCK audio capture source was successfully created, which doesn't make much sense.
macOS 14
Error log when adding a macOS Audio Capture source is gone.
> mac-capture: Remove unneeded debug log

- plugins/mac-capture/mac-sck-audio-capture.m
- plugins/mac-capture/mac-sck-video-capture.m
Changes a magic number error code to instead use a human readable constant.
And it turns out that this never worked in the first place, because the error code isn't `3808` but actually `-3808` (the former code just doesn't exist).
I'll be honest here, I'm not sure what the motivation behind excluding this particular error is, but whatever it was it didn't work until now (this was in the code ever since SCK was introduced to OBS).
Saw a magic number, don't like magic numbers.
Hasn't. I don't know how I would cause errors when stopping the stream.
> mac-capture: Use error code constant instead of magic number

- libobs/media-io/video-io.c
- libobs/media-io/video-io.h
- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs-video-gpu-encode.c
- libobs/obs.c
- libobs/obs.h
This allows setting `skip_frames` for encoders, which results in encoded frame rate being some fraction of the composition frame rate; e.g. using a base/composition frame rate of 60 FPS and setting `skip_frames = 1` on an encoder results in 30 FPS encoded stream being generated, `skip_frames = 2` would result in 20 FPS, `skip_frames = 3` gives 15 FPS etc.
Outputting at different frame rates is potentially beneficial to various use cases, such as e.g. high FPS (60 or even 120 FPS) recording while only streaming at lower FPS to fit within bandwidth constraints (while at the same time reducing encoding load from two separate encoders). Another use case discussed on discord was allowing a lower FPS display for remote control.
Compared to enabling arbitrary frame rates, this change is somewhat …
> Allow encoders to output at partial frame rates compared to main compositing frame rate

- plugins/mac-virtualcam/src/camera-extension/OBSCameraDeviceSource.swift
Adds explicit types to empty collection passed as pixel buffer IOSurface properties.
Swift 5.0 requires empty collections to carry explicit type definitions.
Tested on macOS 13.
> mac-virtualcam: Fix use of collection without explicit type

- cmake/common/compiler_common.cmake
- cmake/windows/compilerconfig.cmake
Fixes compilation when setting the C++ standard to 20+ by disabling `char8_t`.
Note that while #9183 introduces a deprecation warning in C++20 that gets treated as error, `char8_t` also causes failure in other cases where `std::filesystem` is used, such as `obs-app.cpp`.
We might want to start using C++20 at some point, and the less said about `char8_t` the better.
Compiled on Windows with `CMAKE_CXX_STANDARD` set to 20.
> cmake: Disable char8_t when using C++20

- libobs/audio-monitoring/osx/coreaudio-output.c
- libobs/obs-source.c
- libobs/obs.h
When playing VLC source on MacOS audio starts lagging after pause, stop or timeline seeking actions.
This is caused by VLC delaying the call to `buffer_audio()` callback. After each pause or stop the delay keeps adding up resulting in audio lag.
This change is adding an additional callback for "media_pause" and "media_stop" events to clean the `monitor->new_data` buffer and prevent audio data accumulation caused by VLC callback delay.
Fixes issue #7552
Tested on MacBook Air M1 with different files in multiple sources including VLC
> Add pause callbacks for coreaudio

- CMakeLists.txt
- test/test-input/cmake/legacy.cmake
Updates the CMake script for the test-input plugin to make it work with the updated CMake path.
Test plugin contains useful test sources and filters for debugging that should be available to build for developers.
The functionality can be enabled specifically by setting `ENABLE_TEST_INPUT` to `ON`.
Built the test input on macOS and checked the test sources and filter.
> test-input: Update CMakeLists for updated CMake path

- UI/win-update/updater/updater.cpp
#8952 refactored parts of the updater but forgot to set the `installed_ok` result in the non-patch path.
Don't want this to be broken.
Tested updater with and without deltas.
-
> updater: Fix updating without patch files

- UI/multiview.cpp
Fix the X coordinates for the labels on Scenes Only multiview.
The multiview labels are off from the center when set to `Scenes only (4 Scenes)`, `Scenes only (9 Scenes)`, `Scenes only (16 Scenes)`, `Scenes only (25 Scenes)`.
I tested all the settings of multiview.
An orange line shows the center for each scene.
|Setting | Without this PR | With this PR |
|---|---|---|
| Scenes only (25 Scenes) | ![multiview-25](https://github.com/obsproject/obs-studio/assets/780600/32401aff-b8ca-4320-a541-bb81015fd93f) | ![Screenshot 2023-06-18 00-24-07](https://github.com/obsproject/obs-studio/assets/780600/2ff0ea06-bb62-4395-b0c8-0423d0b4f77c) |
| Scenes only (16 Scenes) |![Screenshot 2023-06-18 00-32-59](https://github.com/obsproject/obs-studio/assets/780600/346bb3a1-0976-49bf-9a0e-f1e122aea91b) | …
> UI: Fix scenes only multiview label position

- UI/properties-view.cpp
Using `OBS_COMBO_TYPE_RADIO` but not adding any items app will crash
due to out-of-bound access.
In case the conditional list UI component setup for example, and there are no items
assigned to the list with `OBS_COMBO_TYPE_RADIO`, app will crash due to
out-of-bounds access without checking nubmer of items.
This patch cheks number of items before accessing first item of items array to prevent
out-of-bounds access.
Create list property with `OBS_COMBO_TYPE_RADIO`, for example, changing existing
`OBS_COMBO_TYPE_LIST` to `OBS_COMBO_TYPE_RADIO`
and see if application works in case application doesn't have any items in the list.
> UI: Fix crash radio list without items

- plugins/win-capture/CMakeLists.txt
- plugins/win-capture/cmake/legacy.cmake
Changes compatibility data updates in win-capture to be enabled by default.
This was meant to be enabled by default like service updates, but wasn't.
N/A
> win-capture: Enable compatability data updates by default

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Default ffmpeg initial buffer fullness (75%) is too low and results in significantly lower video quality on AMD cards.
Changing it to 100% fixes the quality and also matches what AMF encoder is doing.
Set HRD initial buffer fullness to 100% to fix video quality on AMD cards.
Encoded video quality on AMD cards is rather bad with default settings at low bitrates (6000kbps).
Tested on ArchLinux with mesa 23.1.3 and 7900XTX.
> obs-ffmpeg: Increase initial buffer fullness for VAAPI

- UI/window-basic-main-scene-collections.cpp
Instead of actually removing the file, simply rename it to the .bak version which OBS ignores in most cases.
That allows users to recover accidentally deleted collections more easily, while only taking up a few kilobytes of disk space at most.
Save users from themselves, at least a little. Suggested by @notr1ch on Discord.
Deleted collection, file was just renamed, and trivial to recover (just remove the `.bak`).
> UI: Soft-delete scene collections

- libobs/obs-scene.c
The sign of the sceneitem's scale was discarded when using the "stretch to bounds" bounding box type, causing sceneitem flip to have no effect when that type was selected.
This fixes it by copying the sign of the item's scale to the scale returned by `calculate_bounds_data`.
Fixes  #9208.
Ubuntu 22.04.
Set a sceneitem to "stretch to bounds"
Verified that flipping it worked correctly
> libobs: Fix flip not working with stretch to bounds

- UI/window-basic-auto-config.cpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-basic-settings-stream.cpp
This PR replaces `#if` with `#ifdef` for the lines of `#if YOUTUBE_ENABLED`, `#if RESTREAM_ENABLED`, `#if TWITCH_ENABLED`.
https://github.com/obsproject/obs-studio/pull/9031#discussion_r1261203925
`#if TWITCH_ENABLED` was implemented by a88b440. At that time, the macro was defined to `0` or `1` as below.
https://github.com/obsproject/obs-studio/blob/a88b440290372cc6699734c1df89027333436158/UI/ui-config.h.in#L19
Later commit 349372b removes the macros `TWITCH_ENABLED`, `RESTREAM_ENABLED`, and `YOUTUBE_ENABLED`.
OS: Linux (Fedora)
- Built with `YOUTUBE_CLIENTID`, `YOUTUBE_CLIENTID_HASH`, `YOUTUBE_SECRET`, `YOUTUBE_SECRET_HASH`. Checked the YouTube integration button appears on the settings.
- Built without `YOUTUBE_CLIENTID`, `YOUTUBE_CLIENTID_HASH`, `YOUTUBE_SECRET`, `YOUTUBE_SECRET_HASH`. …
> UI: Fix preprocessor directives for streaming platform integrations

- plugins/obs-webrtc/CMakeLists.txt
- plugins/obs-webrtc/cmake/legacy.cmake
Fix legacy CMake obs_status call
An additional stray comma resulted in an incorrectly formatted status message in the CMake log.
Fix CMake 3.0 module disabled path
The CMake 3.0 path used the old syntax for logging if the module was disabled. Update this to use `target_disable` to match the syntax in other CMake 3.0 paths.
Was doing local test builds and noticed the CMake logging was incorrect.
> Fix obs-webrtc CMake syntax

- plugins/obs-filters/cmake/legacy.cmake
Setting ENABLE_RNNOISE to OFF would result in SpeexDSP being logged as disabled. Correct the CMake logging.
Was doing local test builds and noticed that "SpeexDSP" was in the CMake logging twice. Want correct logging.
> obs-filters: Fix legacy CMake obs_status for RNNoise

- plugins/obs-qsv11/obs-qsv-test/CMakeLists.txt
Adds the `ENABLE_HEVC` preprocessor definition to the `obs-qsv11` test executable, as the define is usually inherited from `libobs`, but the test executable is standalone and thus the configuration option isn't propagated to the target otherwise.
Make `obs-qsv-test` check for HEVC encoding capabilities again.
Needs to be tested by another maintainer with access to Intel hardware.
> obs-qsv11: Fix missing ENABLE_HEVC definition for test executable

- UI/focus-list.cpp
- UI/hotkey-edit.cpp
- UI/hotkey-edit.hpp
- UI/log-viewer.cpp
- UI/obs-app.cpp
- UI/obs-app.hpp
- UI/qt-display.cpp
- UI/qt-display.hpp
- UI/scene-tree.cpp
- UI/slider-ignorewheel.cpp
- UI/source-tree.cpp
- UI/source-tree.hpp
- UI/window-basic-filters.cpp
- UI/window-basic-filters.hpp
- UI/window-basic-interaction.cpp
- UI/window-basic-interaction.hpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-basic-preview.cpp
- UI/window-basic-properties.cpp
- UI/window-basic-properties.hpp
- UI/window-basic-settings.cpp
This PR removes all code exclusive to Qt 5 (which at the same time is all code exclusive to Qt < 6.2, there was no code exclusive to 6.0 or 6.1 in obs-studio).
I plan to create a companion PR to obs-browser later today.
See the announcement:
- https://github.com/obsproject/obs-studio/discussions/9055
macOS 14 Beta
Tested that it still compiles. Explicitly double-checked that the slider-ignorescroll code still works.
CI is expected to fail on Ubuntu 20.04 for obvious reasons. I have not removed the run as part of this PR as I am not sure whether there's more to that than removing it from the strategy matrix.
> UI: Remove Qt 5 ifdef guards and code

- libobs/util/cf-lexer.h
- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
This PR removes outdated TODO comments.
- libobs/util/cf-lexer.h: Left to implement predefined macros
- plugins/obs-ffmpeg/obs-ffmpeg-mux.c: Allow codecs other than h264
Now we support other codecs such as HEVC and obs-ffmpeg-mux can handle other codecs.
Less number of TODO is better.
- Reviewed modification so that this PR does not change any behavior itself.
- Checked predefined macro `_OPENGL` defined in `ep_parse` can enable the preprocess result of `#ifdef _OPENGL`.
- Checked HEVC can be saved using VA-API on Linux.
> Remove outdated TODO comments

- deps/libff/libff/ff-util.c
- deps/media-playback/media-playback/decode.c
- deps/media-playback/media-playback/decode.h
- deps/media-playback/media-playback/media.c
- libobs/graphics/graphics-ffmpeg.c
- libobs/media-io/media-remux.c
- libobs/obs-ffmpeg-compat.h
- plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
- plugins/obs-ffmpeg/obs-ffmpeg-compat.h
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
- plugins/obs-ffmpeg/obs-ffmpeg.c
- plugins/win-dshow/ffmpeg-decode.c
In accordance with https://github.com/obsproject/obs-studio/discussions/9055 this drops support for libav* version prior to what ships with Ubuntu 22.04.
Remove some legacy baggage.
Compiled on Windows with recent obs-deps.
> Remove support for legacy FFmpeg versions

- libobs/obs-encoder.c
Reset frame_rate_divisor_counter to 0 on encoder shutdown.
After starting and stopping a GPU encoder session, obs_encoder_shutdown would set frame_rate_divisor_counter to 1. When the next GPU encoder session was started, in libobs/obs-video-gpu-encode.c, gpu_encode_thread would set skip to this value (1), and increment frame_rate_divisor_counter to 2. This causes the next check to fail, as frame_rate_divisor is 1 by default (2 == 1 is false), so frame_rate_divisor_counter retains its value. Since skip is non-zero, the next check, if(skip), passes, and skip to the next loop iteration.
This will continue forever, because frame_rate_divisor_counter will continue to increment, so it will never hold the same value as frame_rate_divisor. This means that send_off_encoder_packet is never called, …
> libobs: Fix back-to-back GPU encoder sessions breaking

- CI/linux/01_install_dependencies.sh
- CI/linux/02_build_obs.sh
- UI/window-basic-main-profiles.cpp
- UI/window-basic-settings-stream.cpp
- build-aux/com.obsproject.Studio.json
- cmake/Modules/FindVPL.cmake
- plugins/CMakeLists.txt
- plugins/obs-qsv11/CMakeLists.txt
- plugins/obs-qsv11/QSV_Encoder.h
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/QSV_Encoder_Internal.h
- plugins/obs-qsv11/bits/linux_defs.h
- plugins/obs-qsv11/cmake/legacy.cmake
- plugins/obs-qsv11/common_utils.cpp
- plugins/obs-qsv11/common_utils.h
- plugins/obs-qsv11/common_utils_linux.cpp
- plugins/obs-qsv11/common_utils_windows.cpp
- plugins/obs-qsv11/obs-qsv11-plugin-main.c
- plugins/obs-qsv11/obs-qsv11.c
This is built on top of #8014, so the first 3 commits are from there and enables the non-texture encoding path for linux.
ffmpeg's vaapi encoding implementation seems to not be making much progress in av1, so we can enable it through this. This also helps reduce confusion as the typical QSV UI on windows is now applicable on linux as well.
Tested on a750 and a i3-7100U, there are some parts of mfx/vpl that seem broken on va-api and have been marked windows only but the largely everything works as it does on windows.
> Add Linux QSV Implementation

- CI/linux/01_install_dependencies.sh
- build-aux/com.obsproject.Studio.json
- build-aux/modules/50-libqrcodegencpp.json
- cmake/Modules/FindLibqrcodegencpp.cmake
- cmake/finders/FindLibqrcodegencpp.cmake
Related to:
- https://github.com/obsproject/obs-deps/pull/182
- https://github.com/PatTheMav/cmake-finders/pull/2
obs-websockets PR requires:
- **Drop Ubuntu 20.04**, related CI will failed because of an API break from Libqrcodegen between 1.5.0 (20.04) and 1.7.0 (22.04) (header file name change) with obs-websocket PRs.
Dependency of:
- https://github.com/obsproject/obs-websocket/pull/1143
Add Libqrcodegencpp to Ubuntu script and Flatpak and its finder since not all distribution of the library comes with a CMake package.
**Please, review the finder on the cmake-finders repo PR.**
Reduce to zero the number of submodule in obs-websocket repo.
Generated a QR code with obs-websocket with obs-websocket build with the library and not the submodule on Linux.
Test binaries available on a PR on my …
> Add Libqrcodegencpp on Linux and add its finder

- plugins/linux-v4l2/v4l2-decoder.c
- plugins/win-dshow/ffmpeg-decode.c
Add pixel format mappings to support decoding grayscale MJPEG streams in the Windows DShow plugin as well as Linux V4L2 plugin. (Already working fine without any changes when tested on MacOS.)
I am the author of the [GB Interceptor](https://github.com/Staacks/gbinterceptor), a device that analyses the data on a Game Boy's memory bus to recreate the image seen on screen. It acts as a USB Video Class device, so a video stream of the Game Boy can be used for recording or streaming. Unfortunately, since it is only a USB 1.1 device with limited processing power, I can only squeeze the full 60fps of the Game Boy through the USB bus by encoding it as grayscale MJPEG, i.e. without chroma channels which would be filled with zeros for the grayscale Game Boy anyway.
While UVC 1.5 clearly requires …
> win-dshow, linux-v4l2: Add support for grayscale MJPEG decoding

- UI/window-basic-main.cpp
During initialization, if the window is supposed to be hidden, don't call `activateWindow()`. This is determined through `hideWindowOnStart`, which is the same variable that determines whether to call `show()`. This change prevents the window from stealing focus and becoming the active window.
Users may choose to launch OBS Studio based on the current active window. If launching OBS to the system tray changes the active window, this could result in undesired behaviour if the user is not expecting the active window to change. Additionally, I would argue that setting the window to active when not showing it is not correct, but that is probably subjective, and in any case, the first point applies.
[Forum post describing the issue](https://obsproject.com/forum/threads/obs-steals-focus-on-start …
> UI: Don't call activateWindow() when hidden

- plugins/mac-capture/mac-sck-audio-capture.m
Removes the internal display settings from SCK Audio Capture.
When capturing desktop audio via ScreenCaptureKit, this always includes the entire audio, independent of which display an application might be running on. As such we don't currently expose a setting to change the display, and don't need any code handling a display setting (as we can always simply use the primary display because it doesn't matter).
macOS 14 23A5286g
Checked that SCK Audio Capture still works.
> mac-capture: Remove internal display settings from SCK Audio Capture

- libobs/obs-encoder.c
- plugins/obs-ffmpeg/obs-nvenc.c
MaxBitrate gets correctly set during encoder init. https://github.com/obsproject/obs-studio/blob/578dc46a797db8860e90789741bae40441d18575/plugins/obs-ffmpeg/obs-nvenc.c#L672
Gets promptly overwritten by nvenc_update, which set max = (avg)bitrate.
I wish for the max bitrate value in the UI to be respect. There were at least 2 complaints.
Built on win10 22h2, it compiles. Using breakpoints in the debugger, I confirmed the contents of `maxBitRate` when running VBR and CBR. I checked the recordings pre and post this change, and confirmed the encoder now allows the bitrate to spike higher (I used 2500kbps bitrate, 10 000kbps max).
> Fix defer encoder updates and NVENC VBR maxBitRate

- UI/window-basic-main-outputs.cpp
When an output is started in simple mode, the fragmented movflags are always set if the format is set to fragmented. However in lossless mode, the format is implicitly set to AVI, and we shouldn't try to set the fragmentation movflags there.
Fixes https://github.com/obsproject/obs-studio/issues/9135
macOS 14 Beta 3
Tested that the log no longer complains about Invalid muxer settings when executing the steps in the linked issue.
Made sure flags are still correctly set in non-lossless mode when Fragmented MP4/MOV is selected.
> UI: Don't set fragmentation movflags in lossless mode

- libobs/audio-monitoring/win32/wasapi-enum-devices.c
- plugins/win-wasapi/enum-wasapi.cpp
```
PROPVARIANT name_var;
PropVariantInit(&name_var);
hr = store->lpVtbl->GetValue(store, &PKEY_Device_FriendlyName,
&name_var);
if (FAILED(hr)) {
goto fail;
}
PropVariantClear(&name_var);
```
Free `name_var` by PropVariantClear when its value has been given.
Avoid memory leak. 
Reference: https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-propvariantclear
https://learn.microsoft.com/en-us/windows/win32/coreaudio/device-properties
This commit has been tested on my computer, win10.
> libobs, win-wasapi: Fix PROPVARIANT variable has not be freed

- libobs-d3d11/d3d11-subsystem.cpp
If a device PCI ID can be represented in less than 4 characters, left-pad it with zeroes.
Saw a device PCI ID in a log that was less than four characters. Thought they should have consistent lengths.
Could have used `%04x`, but as far as I can tell, `%04x` and `%.4x` are equivalent for the `x` format specifier.
Could probably also left-pad the vendor PCI ID if we think we should ensure both are 4 characters.
Tested build locally on Windows 11. Tested format specifier syntax in Compiler Explorer with various values.
> libobs-d3d11: Left-pad device PCI ID to 4 characters with zeroes

- CMakeLists.txt
This whitespace character between two sentences in a cmake error message was accidentally removed in 349372b3b39e2346952732ab14122d23c7ec7a57
I found this issue while trying to build OBS to look at a separate issue and decided to fix it. This change is a simple fix to a missing space between two sentences in a cmake error message.
Error messages should be clear and easy to read, and this change was clearly introduced accidentally.
Running `cmake -LAH` in the root source directory triggers this error message and was used to verify the fix.
> cmake: Fix missing space between sentences

- plugins/linux-pipewire/pipewire.c
- plugins/linux-pipewire/pipewire.h
- plugins/linux-pipewire/portal.c
- plugins/linux-pipewire/portal.h
- plugins/linux-pipewire/screencast-portal.c
This is the second batch of commits from https://github.com/obsproject/obs-studio/pull/6669, rebased on top of `master` and adjusted to the most recent changes.
The biggest change that this round of preparations introduce is making the PipeWire code able to handle async sources. There are no actual async sources that use PipeWire, but this is such a big change that I reasoned it's better reviewed independently from the next - and even bigger - reworks.
There should be no functional changes to the screencapture code.
I don't want code reviewers crying in a corner when reviewing the PipeWire camera merge request, so let's go incremental and chop choppy and handle this massive amount of code in digestible chunks :slightly_smiling_face: 
- Run OBS Studio on Linux
- Add a PipeWire capture of …
> Preparations for Portals + PipeWire camera, part 2

- UI/obs-frontend-api/obs-frontend-api.cpp
- UI/source-tree.cpp
- UI/source-tree.hpp
- UI/window-basic-main.cpp
- UI/window-basic-stats.cpp
- docs/sphinx/reference-frontend-api.rst
Destroys the frontend API after the `OBS_FRONTEND_EVENT_EXIT` event has finished and fixes some internal use of the frontend API that violates this.
Many plugins (and even some parts of OBS itself) continue to call the frontend API after the `OBS_FRONTEND_EVENT_EXIT` event . This is very dangerous as OBS is in the process of shutting down so there are no guarantees that the functions they want to call will be valid or the data returned won't be in the middle of destruction, resulting in crashes.
Fixes #8370.
Ran OBS with default set of plugins, no errors logged or broken behavior noticed. Some 3rd party plugins may be relying on this previously dangerous behavior though so this needs testing well.
- Breaking change (fix or feature that …
> Destroy frontend API on shutdown

- plugins/mac-capture/mac-sck-audio-capture.m
- plugins/mac-capture/mac-sck-video-capture.m
Changes the type of data being set for `application` from `obj` to `string`
Noticed that an `obj` is being set here, which is wrong, as `application` is a string type.
It probably doesn't make a difference in the real world but we should be correct if possible.
macOS 14 Beta 3
Tested that both new and existing sources with Application Capture still work.
> mac-capture: Set correct default type for application data

- cmake/windows/helpers.cmake
Adds missing code to Windows CMake files to sort `libobs` sort files into respective subdirectories in MSVC's code navigator.
Code was implemented for macOS and Xcode, but missed for Windows.
Tested with MSVC 17 2022 on Windows 11.
> cmake: Fix missing libobs subdirectories in MSVC code navigator

- plugins/obs-ffmpeg/obs-ffmpeg-source.c
Previously would always end up with OBS_MEDIA_STATE_ENDED whether the
video reaches the end or the user stops the source (state is set to
STOPPED, but becomes ENDED right after). This fixes it so that if the
user stops the source, it will remain stopped.
Found this bug after https://github.com/obsproject/obs-studio/pull/9137 got merged. Even Advanced Scene Switcher users are affected by this weirdness. My interpretation of the two states is that ENDED is when the video naturally ends, and STOPPED when the user stops the video manually.
I put a breakpoint in update function to watch the state.
- If video ended, state is `OBS_MEDIA_STATE_ENDED`
- If video stopped, state is `OBS_MEDIA_STATE_STOPPED`
This also made the referenced PR do what was intended; to only restart the media if the state …
> obs-ffmpeg: Fix media source always STATE_ENDED

- plugins/obs-webrtc/CMakeLists.txt
- plugins/obs-webrtc/cmake/legacy.cmake
- plugins/obs-webrtc/whip-output.cpp
- plugins/obs-webrtc/whip-output.h
- plugins/obs-webrtc/whip-utils.h
The following changes were made to provide compatibility and increase usability behind NAT / Firewall. Specific modifications and additions are as follows:
- Creates a User-Agent string for application identification
- Implements a maximum fragment size for video packetization
- Uses a randomized u32 generation routine for SSRC and RTP timestamps to fit RFC-3550
- Adds additional life-cycle methods for clearer flow; Init, Setup...
My motivation is to remove hard-coded SSRC values and to set starting RTP timestamps to match RFC-3550.
All testing during development was performed on Windows 11 x64 against a modified private pre-release version of Red5 Pro Server. As of generation of this PR, I cannot build on this branch in current windows environment and I'm not sure why; its an error in …
> obs-webrtc: Add user-agent, timestamp, and ssrc generation

- UI/window-basic-stats.cpp
Changes a `QT_TO_UTF8(QTStr())` call to `Str`.
The construct here converts a translated c-string to a QString and then back to a c-string. That's not needed.
macOS 14
Tested that the `asprintf` call still works.
> UI: Avoid QT_TO_UTF8(QTStr()) double conversion

- plugins/obs-ffmpeg/obs-ffmpeg-srt.h
Rendezvous mode with SRT protocol is used to punch through firewalls. Although caller or listener mode are much more widespread, it is sometimes in use. The rendezvous mode was broken in obs because we would bind to the remote IP, instead of a local IP. This fixes the bug. Note that there is also a bug in libsrt preventing our code to work. But Version 1.5.2+ of libsrt fixes that.
Requires srt v1.5.2+ which fixes a rendezvous bug. Without the commit [1], the fix in this PR is not working.
SRT is updated in the companion PR in obs-deps [2].
[1] https://github.com/Haivision/srt/commit/1cffd2f2abad1782d1218f2c2b893f26bf4bbfce
[2] https://github.com/obsproject/obs-deps/pull/191
Fix a bug.
Tested during SRT Plugfest 2023 against Epiphan hardware and Haivision Makito X decoder in rendezvous …
> obs-ffmpeg: Fix rendezvous mode with SRT

- .github/actions/qt-xml-validator/action.yaml
Explicitly check only for changes `.ui` files in forms subdirectory and pass only changed files with that suffix to validator.
Fix validator being triggered by any changes to files in the `forms` subdirectory, which will inevitably lead to such files not passing validation.
> CI: Fix Qt XML validator attempting to validate non-XML files

- .github/workflows/scheduled.yaml
Change the workflow to fetch at most 2 runs of the scheduled workflow runs to compare the last run's commit hash with the current one.
Apparently the workflow run list will also yield the _current_ workflow run, so we have to fetch at least 2 runs to also get the prior one.
Needs to bested on master branch with a scheduled run.
> CI: Fix scheduled Steam builds

- build-aux/modules/50-libdatachannel.json
- cmake/Modules/CopyMSVCBins.cmake
This updates libdatachannel to commit supporting simulcast.
This syncs the lib to obs-deps concurrent PR updating libdatachannel for windows & macOS [1].
It also copies for old cmake datachannel.dll created in [1] as well as libdatachannel.dll which is
cross-compiled with mingw on linux.
[1] https://github.com/obsproject/obs-deps/pull/194/
Keep libdatachannel updated on flatpak and synced with obs-deps.
Copy old as well as new libdatachannel dll.
Flatpak untested. I don't have any linux box except WSL.
I tested though that with an old cmake build dir, the new dll is indeed copied.
> build-aux/cmake: Update libdatachannel for Flatpak & copy updated DLL

- .github/workflows/pr-pull.yaml
Removes label triggers from pull request workflow.
Having the main pull request workflow run for labeling events has the unintended side-effect of an automatically canceled run when a pull request is opened with labels attached to it.
As GitHub's user interface allows interactive restarts of CI jobs, maintainers can add the label and re-trigger builds directly.
> CI: Remove label triggers from pull request workflow

- .github/workflows/dispatch.yaml
- .github/workflows/scheduled.yaml
Switches service availability checks to macOS runners on GitHub Actions. Affects only scheduled and dispatched workflow runs, as other invocations only check schema validity.
Linux runners exhibit connectivity issues with some services that are not present with macOS runners. Switching to macOS thus reduces chances for false positives.
Requires testing on CI.
> CI: Switch service availability checks to macOS runners

- .github/actions/setup-macos-codesigning/action.yaml
Fix error when generating random password if no keychain password is set for macOS codesigning credentials
`sha1sum` is part of Homebrew's coreutils, but macOS ships with `shasum` by default, which supports many variants and defaults to SHA-1 by default.
Tested on local fork without a keychain password set in repository secrets.
> CI: Fix random password generation for macOS codesigning

- .github/workflows/build-project.yaml
- .github/workflows/publish.yaml
Fixes Flatpak build runs on master branch not generating a new cache entry after manifest changes.
Cache key needs to provided regardless of whether a cache hit occurs, the key is not automatically generated by the action.
Tested on local fork with direct pushes to master branch.
> CI: Fix broken Flatpak cache generation on CI

- .github/actions/steam-upload/action.yaml
Fix nightly runs of steam-upload action not being able to download generated build artefacts.
GitHub's CLI utility is not capable of downloading artifacts generated by the workflow job it is being run in itself. Thus the official repository action is needed.
Tested with scheduled runs on fork of `obs-studio`.
> CI: Fix broken download of nightly build artifacts for Steam uploads

- build-aux/.run-format.zsh
clang-format was not skipping libdshowcapture and got changes each time I ran the script.
clang-format and cmake-format were not formating the deps folder were most the cmake is made by us and clang-format config files were added to not format some deps that are not made by us.
Fix the script, I had enough reverting libdshowcapture changes.
Ran the script on my machine, no uneeded changes happened.
> Ignore libdshowcapture and add deps to the format script

- UI/window-basic-settings-stream.cpp
Removes the `lastService.clear()` in `LoadStream1Settings`.
Here is why I *think* this is safe:
`lastService` only gets set in `UpdateServerList`. There are 2 times where `UpdateServerList` is called:
- In `on_service_currentIndexChanged`: This means that after switching service once, and *then* click "Show more", the service is remembered.
- In `LoadStream1Settings`, where it is currently cleared immediately after.
`lastService` is only used in two places:
- In `LoadServices` to set the server in the list after creating the list, where it currently is mostly useless.
- In `ServiceChanged` to make sure that the code reloading service specific properties is not called multiple times - which on load it *also* fails to do, because the service gets reset immediately before.
I'll be honest, I …
> UI: Don't clear lastService immediately after setting it

- UI/window-basic-status-bar.cpp
Amends 1c8407183 to address the remaining points brought up on the Pull Request that were not changed before merging.
Removes the unused `main` pointer and changes the string concatenation into a single `asprintf` call.
Commented about this on the PR, but it was agreed to merge the PR first and fix this up later.
macOS 14.
Status bar FPS still show up the same way as before.
> UI: Fix remaining status bar nits

- .github/actions/steam-upload/action.yaml
Changes `steamcmd` invocation to pass absolute path to generated build file.
steamcmd seems to have a quirk where it cannot find a file in the current working directory on macOS, but requires the absolute path to the file instead - using the `:a` Zsh modifier yields the absolute path of a valid filename in the current directory scope.
Needs to be tested via CI run.
> CI: Fix steamcmd being unable to find generated build file

- .github/actions/services-validator/action.yaml
Enforce installation of Python 3.11 via Homebrew for scheduled service checks.
Once again GitHub Action runners have a minor Python 3 version preinstalled that we want to upgrade, which will fail because that versions does not seem to be Homebrew-based.
Enforcing an upgrade will fix the issue as Homebrew can overwrite the files.
> CI: Fix Python 3.11 installation on macOS 13 runners

- UI/CMakeLists.txt
- UI/cmake/legacy.cmake
- UI/data/locale/en-US.ini
- UI/forms/OBSBasic.ui
- UI/obs-app.cpp
- UI/obs-app.hpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- docs/sphinx/reference-modules.rst
- libobs/obs-internal.h
- libobs/obs-module.c
- libobs/obs.c
- libobs/obs.h
This PR adds several things:
- `obs_add_safe_module(name)` to allow specifying a list of safe modules, if the list is not empty, only the specified modules are allowed to load
- Automatic detection of unclean shutdowns (disabled in `Debug` builds)
- Prompt to ask user if they want to run OBS in safe or normal mode when an unclean shutdown has been detected
- `--safe-mode` flag to run OBS in safe mode
- `--only-bundled-plugins` flag to run OBS without third-party plugins
- `--disable-shutdown-check` flag to disable unclean shutdown detection
"Safe Mode" currently disables third-party plugins as well as `frontend-tools` and `obs-websocket` to prevent scripts from running or external applications from making changes to OBS's state.
**Screenshot:**
The automatic crash/improper shutdown …
> Add Safe Mode

- UI/obs-app.cpp
- libobs-d3d11/d3d11-shader.cpp
- libobs-d3d11/d3d11-subsystem.cpp
- libobs-d3d11/d3d11-subsystem.hpp
Implements a D3D shader cache. The shader script itself is hashed (using fnv1a for now as a quick hash) and if a file exists with a matching hash the compiled program is read from that instead of calling `D3DCompile` which is slow.
A lot of time on OBS startup on Windows is spent compiling the same static shaders.
Ran OBS a bit and it worked. More testing across different drivers / vendors would be nice. We had a similar implementation of a shader cache in OBS Classic that seemed to always break things, but I have no idea why. Microsoft recommend precompiling and shipping compiled shaders as D3D compiles to [DXIL](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst) which is then further consumed by the GPU driver and compiled to native GPU code. So the D3D compiled …
> libobs-d3d11: Implement shader cache

- build-aux/steam/scripts_windows/uninstall.bat
Cleanup shader cache directory created by #9249 when uninstalling OBS via Steam.
Cleanup files that are no longer needed.
Hasn't.
> build-aux: Add shader cache cleanup to steam uninstall script

- UI/win-update/updater/CMakeLists.txt
- UI/win-update/updater/cmake/legacy.cmake
- UI/win-update/updater/manifest.hpp
- UI/win-update/updater/updater.cpp
- UI/win-update/updater/updater.hpp
Migrate the updater from defunct Json11 to nlohmann JSON as we use in websockets/browser and potentially the UI as well in the future.
Includes #9291
json11 is unmaintained/abandoned and nlohmann allows us to have nicer struct based (de)serialisation.
Updated OBS.
> updater: Migrate to nlohmann JSON

- UI/obs-app.cpp
- libobs-d3d11/d3d11-subsystem.cpp
Moves creation of the shader cache folder from the UI to libobs-d3d11
Kinda maybe better practice?
Verified folder is still created before anything is written to it.
> libobs-d3d11,UI: Move shader cache folder creation

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
[VStream](https://vstream.com/) is a live streaming and video hosting platform for [VTubers](https://en.wikipedia.org/wiki/VTuber). 
As a livestreaming platform we would love it so that our creators could more easily start streaming to VStream using OBS. While we have [existing docs](https://vstream.com/help/streaming-with-obs) on how to stream to OBS, users who are coming from platforms like Twitch or Youtube are often confused by them and forget to set important settings like their keyframe interval. By adding VStream an support rtmp-service this would make life much easier for our users and us.
We've been in private-beta for the past 3 months and our beta users have been very successfully streaming using these settings and OBS. We'll be entering our open-beta stage [very soon …
> rtmp-services: Add "VStream" RTMP service

- plugins/win-capture/graphics-hook-ver.h
- plugins/win-capture/graphics-hook/vulkan-capture.c
The wrong linked list was used when removing framebuffer data. It generated memory leak, the linked list grew more and more involving performance degradation each time an application called the vkCmdBeginRenderPass.
Furthermore, few pointers referenced objects on the stack that were no more valid.
It solves a memory leak and performance problems.
> win-capture: Fix leaking framebuffers data

- UI/window-basic-preview.cpp
This fixes a couple issues related to the handling of sceneitem flipping by the preview, and in particular when within a bounding box.
The issues in question are the following : 
Penwy/obs-studio@a2487fc2021765ae0ad655abe378658de4165685 fixes the rotation handle's mouse interaction being incorrectly positioned when an item has been flipped.
Steps to reproduce :
1. Horizontally flip a sceneitem
2. Rotate it (90° for most observable result)
3. Try to grab the rotate handle
Penwy/obs-studio@70a9343861eabb2842148ac89f7ea72d61e7f955 and Penwy/obs-studio@41f78c129f7d79fe99f0ab84fe83c56ea670fa86 fix the rotation handle and the pixel guides being drawn at the wrong position on a flipped sceneitem in a bounding box.
Steps to reproduce :
1. Set a sceneitem's bounding box type to anything other than …
> UI: Fixes to preview drawing and interactions with flipped sceneitems

- libobs/obs-scene.c
This fixes flipping behaviour when positional alignement inside the bounding box is other than centered, so that the item gets flipped in-place within the bounding box, instead of being thrown out of the bounding box.
Currently, when a sceneitem set in a bounding box with an alignment other than "center" gets flipped, it is thrown out of the bounding box, which does not feel like the expected behaviour of a bounding box.
Ubuntu 22.04
Tested various combinations of positional alignement and bounding box types, checked that all correctly flipped the item in-place on x and y.
> libobs: Fix flip calculations in bounding box

- libobs/obs-encoder.c
During encoder shutdown `maybe_clear_encoder_core_video_mix` is called to clear created mixes that are no longer needed; at that time `obs_encoder_set_video` rejects changes to `media` since the encoder is still active, so we bypass those checks
This is an issue e.g. when a rtmp stream disconnects (and thus all encoders are cleared) and subsequently reconnects
The call to `set_encoder_active(encoder, false)` happens right after the call to `obs_encoder_shutdown` in this case, but I'm not entirely sure whether it's safer to reorder those calls rather than bypassing the check for `obs_encoder_set_video`
OBS crashes when GPU scaling is used through additional core video mixes and those encoders are recreated due to e.g. rtmp disconnects
Disconnect an rtmp stream while having an encoder …
> libobs: Fix GPU scaled video encoder media not being cleared

- UI/window-basic-auto-config-test.cpp
- UI/window-basic-main-profiles.cpp
Previously we left the QSV -> x264 in the fallback function to deal with the autoconfig wizard possibly selecting QSV outside of the UI. But this actually runs for both recording and streaming every time obs starts, reseting user's config if they selected QSV for recording.
Instead avoid QSV from being selected in the UI and by the auto-config wizard, and revert changes to the fallback function.
Reseting user's config does not make users happy.
Autoconfig wizard with "Prefer Hardware Encoding" still selects x264.
I can restart obs after selecting QSV in simple mode and it isnt reset.
> UI: Avoid auto config selecting QSV on linux

- docs/sphinx/reference-sources.rst
Edited `obs_filter_get_parent` and `obs_filter_get_target`
Was tricked into thinking it incremented ref count, causing me to double release.
Built and viewed locally, and my plugin that freed the filter from obs_filter_get_parent was fixed when i didn't release. Source code also shows that obs_filter_get_target is similar, so I changed its docs too. Exeldro also confirmed this.
> docs: Indicate that refcount is not incremented

- plugins/aja/aja-routing.cpp
This PR will replace another PR #9294.
Ignore return values from the functions `aja::lower` and `aja::replace`.
The functions `aja::lower` and `aja::replace` overwrite the 1st argument and just return the reference to the 1st argument. It is not necessary to use the return value.
- `aja::lower`: https://github.com/aja-video/ntv2/blob/3a1e91f740e36e43a1ec74ff446a097330e87220/ajalibraries/ajabase/common/common.cpp#L343-L347
- `aja::replace`: https://github.com/aja-video/ntv2/blob/3a1e91f740e36e43a1ec74ff446a097330e87220/ajalibraries/ajabase/common/common.cpp#L60-L70
According to the other PR #9294, GCC 13's warning `-Wdangling-reference` reported a warning on the line below.
https://github.com/obsproject/obs-studio/blob/edf2c8210ca45d4d25c96ac1b9afc122caadb529/plugins/aja/aja-routing.cpp#L28 …
> aja: Ignore return value from aja-common functions

- UI/cmake/feature-macos-update.cmake
- UI/cmake/feature-whatsnew.cmake
- UI/cmake/legacy.cmake
- UI/cmake/os-windows.cmake
- UI/obs-app.cpp
- UI/update/models/branches.hpp
- UI/update/models/whatsnew.hpp
- UI/update/win-update.cpp
- UI/win-update/updater/manifest.hpp
- UI/window-basic-main.cpp
This PR does three things:
- Migrate Windows update check to use nlohmann JSON for manifest deserialisation
- Migrate macOS/Windows update branch deserialisation to use nlohmann JSON
- Migrate WhatsNew deserialisation to use nlohmann JSON
json11 is dead/abandoned, and nlohmann allows us to more prettily deserialise things into a struct.
- Verified manifest is parsed correctly and version check works
- Verified branches are parsed correctly
- Tested WhatsNew on Windows with some mock data including the optional `os` filter.
> UI: Migrate WhatsNew, update branches, and Windows update check to nlohmann JSON

- build-aux/com.obsproject.Studio.json
- build-aux/modules/50-rnnoise.json
Replace in-tree RNNoise with a module with the same version as macOS obs-deps
Align with obs-deps and make Ubuntu the only reason that RNNoise in-tree exists.
Flatpak build (configure step does not have the message about using a bundled RNNoise) and the noise filter have the RNNoise option while running the Flatpak
> build-aux: Add RNNoise Flatpak module

- docs/sphinx/reference-sources.rst
- libobs/obs-source.c
- libobs/obs-source.h
If there is filter_remove, it is reasonable to expect that there is also filter_add. filter_add also enables filters to attach signal handlers on the parent, and disconnect them in filter_remove.
Add obs_source_info.filter_add, counterpart of filter_remove
I've had two plugins where I needed to reference the parent outside of the valid functions. One is my Source Defaults that creates a custom filter which uses the global "source_create" signal to copy settings of the parent source to the new source (same source type). Adding a `filter_video` that does nothing except get a reference to the parent does not seem optimal to me.
In the other, I wrote a custom filter that generates subtitles. I wanted to attach to the signal handler of the parent source, but the parent source is not available …
> libobs: Add obs_source_info.filter_add

- libobs-d3d11/d3d11-subsystem.cpp
- libobs-d3d11/d3d11-subsystem.hpp
- libobs/graphics/graphics-imports.c
- libobs/graphics/graphics-internal.h
- libobs/graphics/graphics.c
- libobs/graphics/graphics.h
- libobs/obs-display.c
On multi-adapter systems where at least one GPU is an NVIDIA GPU, using fast clear can cause the Properties window's preview pane to flicker rapidly if the NVIDIA driver is older than 527.37. This series of changes enables us to run a one-time check for if the graphics adapter can perform a fast clear, and if so, then always use that. The check is performed once and the result is stored for future use. If the adapter is determined to not be able to safely fast clear, continue to use the clear workaround.
Want fast clear when possible. Don't want to try fast clear when it's not safe.
Follow-up to:
* #7601
* #7214
* #7177
* #7175
I tested OBS Studio 28.0.0-rc1 (a version where fast clear was universally enabled) on my Intel+NVIDIA laptop (Windows 10) with NVIDIA driver versions 522-528 to …
> libobs: Enable fast clear on Windows with driver check

- docs/sphinx/reference-libobs-media-io.rst
- docs/sphinx/reference-outputs.rst
- docs/sphinx/reference-sources.rst
- libobs-opengl/gl-shaderparser.c
- libobs/data/format_conversion.effect
- libobs/media-io/video-frame.c
- libobs/media-io/video-io.h
- libobs/media-io/video-matrices.c
- libobs/obs-internal.h
- libobs/obs-source.c
- libobs/obs-video.c
- plugins/decklink/decklink-device-instance.cpp
Avoid chroma subsampling if a pure RGB signal is available.
Pure colors.
> decklink: Support 10-bit RGB capture

- UI/data/locale/en-US.ini
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Split toggle preview program hotkey into hotkey pair
To be sure it is enabled or disabled when the hotkey is pressed.
set the same and different keys for enable and disable
> UI: Split toggle preview program hotkey into hotkey pair

- plugins/linux-capture/xcomposite-input.c
- plugins/win-capture/game-capture.c
- plugins/win-capture/window-capture.c
- plugins/win-wasapi/win-wasapi.cpp
This adds signals and procedures to various sources that allow tracking whether said sources have hooked into a window and are capturing data from it.
The sources affected are :
- Xcomposite window capture
- Windows window capture
- Windows game capture
- Windows application audio capture
Each source recieves two signals : 
- "hooked", fired when a window has been successfully hooked, with calldata containing a pointer to the source as well as information about the window hooked (title, class, executable)
- "unhooked", fired when a window has unhooked, with calldata containing a pointer to the source
and one procedure :
- "get_hooked", which returns a boolean of the hooked state of the source, as well as information on the window hooked (title, class, executable)
Currently there is no way …
> API: Add signals and procs exposing the hook state of various sources

- UI/ffmpeg-utils.cpp
- UI/ffmpeg-utils.hpp
- UI/window-basic-settings.cpp
This PR addresses a few things with the newly introduced FFmpeg utilities:
- Fixes the equality operator overload to have null checks
- Fixes one initialisation of `FFmpegFormat` 
- Removes the alias in the name because it's misleading/useless
- Refactors getting the encoders for a given format to remove an unnecessary indirection and quadratic search
- Adds long name to items in encoder list
- Refactors getting the default encoder from a format
- Adds constructors to `FFmpegFormat`/`FFmpegCodec` for their libav counterparts
- Cleans up some leftovers from the original C code (e.g. `NULL` instead of `nullptr`)
Would prefer not to crash and cleaner code.
Opened settings, changed settings, closed settings, reopened settings.
- Code …
> UI: FFmpeg utils cleanup/fixes

- libobs/obs.c
Adds profiling to `obs_init_graphics()` and the shader compilation contained within.
Note: Typically we keep profiling to a function level, if we want to keep that pattern the default shader compilation could be moved to a separate function like so: https://github.com/derrod/obs-studio/commit/f17eeea15189d5cb2096c58197725449b57366a4
Wanted to evaluate user-provided logs to measure impact of shader compilation on macOS/Linux startup time to see if we'd want to also add a shader cache to the OpenGL graphics backend.
Without cache:
```
11:18:42.521:      ┣OBSBasic::ResetVideo: 896.154 ms
11:18:42.521:      ┃ ┗obs_init_graphics: 894.978 ms
11:18:42.521:      ┃   ┗obs_init_default_shaders: 808.217 ms
```
With cache:
```
11:18:46.936:      ┣OBSBasic::ResetVideo: 127.955 ms
11:18:46.936:      ┃ …
```
> libobs: Profile graphics initialisation and shader compilation

- .github/scripts/utils.zsh/create_diskimage
Fixes typo in Zsh script for macOS disk image creation.
By checking a non existing status variable the code to capture the common CI issue of temporary disk images not being detached on time was ineffective.
Tested on separate fork with forced error during detaching.
> CI: Fix detaching of temporary macOS disk images during image creation

- .github/scripts/utils.zsh/create_diskimage
As not only detaching but apparently all operations of hdiutil can be blocked by slow disk I/O on CI runners, this wraps all invocations of it in a helper function that attempts up to 5 retries with a backoff timer.
Allow more graceful recovery of blocking disk I/O on macOS CI runners.
Needs to be tested on CI runners that actually seem to have regular I/O issues.
> CI: Add wrapper function for macOS disk image operations

- .github/workflows/dispatch.yaml
- .github/workflows/scheduled.yaml
Adds the "write" permission to the contents scope for the service validator job in scheduled and dispatched workflows.
The action's documentation unfortunately does not spell out which API permissions are required for the token and neither GitHub's documentation spells this out directly, so this fix is based on an educated guess.
Current implementation seems to lack required permissions to push a new branch to the repository, which leads to the job failing when actual unrecoverable changes to services are detected.
Needs to be tested after merging unfortunately as it needs to be merged on the master branch and then run as part of a scheduled or dispatched workflow run.
> CI: Add write permissions to contents scope to service validator

- .github/scripts/utils.zsh/create_diskimage
Remove code that optimistically continues with disk image creation if mount point is gone after unsuccessful detach attempt.
The situation of the mount point being unmounted after an unsuccessful detach attempt leads to an unrecoverable situation. Instead of optimistically continuing, the script has to fail.
Was tested on CI before the extra branch was added.
> CI: Remove optimistic continuation of disk image creation for macOS

- UI/window-basic-main.cpp
https://github.com/obsproject/obs-studio/commit/c33fa8b introduced a call to `obs_source_get_output_flags` which would always be called when the selection changes, even if things get unselected. This would result in `get_output_flags` being called on a `NULL` source which libobs yells about. This PR also inverts the `audioOnly` bool to make it a bit more obvious what is actually being checked (which is whether the source has video).
This PR leaves an existing bug w/r/t multiple scene items which I'm planning on addressing as well, but it may involve a minor refactor and I don't want this PR to get too large.
Got annoyed at debug warnings each time I unselect the current scene item.
macOS 14
Tested that everything (including the bugs) works the same as before, with both video sources as …
> UI: Don't call obs_source_get_output_flags on a NULL source

- plugins/obs-outputs/librtmp/rtmp.c
Updates Keychain query on macOS to limit returned data to certificates that are valid (based on current datetime) and trusted only.
Refines implementation on macOS, as only valid and trusted certificates should have been used in the first place.
Tested on macOS 13.4.1. and successfully streamed via RTMPS and HLS.
> obs-outputs: Refine certificate selection on macOS

- UI/auth-youtube.cpp
- UI/window-basic-main.cpp
- UI/window-dock-youtube-app.cpp
Creates the dock at the right moment to never require its own dock state restoration.
YouTubeAppDock rather than being created before OBS Studio own dock state restore. Restore the dock state each time the dock are created so it can suddenly revert the actual dock state.
It also does not checks if the integration is enabled which doesn't use the same dock state config.
Run OBS with YouTube service selected in the config, no issue the dock is loaded.
> UI: Fix YouTubeAppDock restore dock state

- libobs/obs-cocoa.m
- libobs/util/sse-intrin.h
- plugins/linux-pipewire/pipewire.c
- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Fixes #9160
- Replace linux-pipewire variable-length arrays with dynamic arrays, those were not generating errors because of our in-tree simde that makes some warning ignored.
- Contain simde diagnostic pragmas
I was trying to use my system simde rather than the in-tree and discover how to reproduce #9160.
So I tried to fix the vla issue and the pragma contamination.
Pipewire captures seems to work fine.
> Contain simde diagnostic pragmas and replace variable-length arrays

- .github/workflows/dispatch.yaml
- .github/workflows/scheduled.yaml
Add write permission to the pull-request scope for the services-availability and services-validation jobs to allow them to create and update Pull Requests.
The Scheduled workflow [began failing recently](https://github.com/obsproject/obs-studio/actions/runs/5733238307) once it tried to create a pull request to remove defunct services. In #9367, we added `write` permissions to the `contents` scope to the services-availability and services-validation jobs to try to resolve this error:
``` 
Wed, 02 Aug 2023 00:31:02 GMT   Pushing pull request branch to 'origin/automated/clean-services'
Wed, 02 Aug 2023 00:31:02 GMT   /usr/local/bin/git push --force-with-lease origin HEAD:refs/heads/automated/clean-services
Wed, 02 Aug 2023 00:31:02 GMT   remote: Permission to obsproject/obs-studio.git denied …
```
> CI: Fix services validator being unable to create Pull Requests

- UI/forms/OBSBasicSettings.ui
Changes the warning box in the Simple Mode settings to be floating at the bottom of the visible page, instead of being at the bottom of the scroll area.
Before/After:
<p>
</p>
Warnings should be visible.
Prerequisite to #6700, this really does not require a huge refactor like the one proposed in #7709.
For reference, off-thread discussion a while back regarding #6700 yielded that this was the desired layout (see https://github.com/obsproject/obs-studio/pull/6700#issuecomment-1187632936):
macOS 14 Beta 3
Tested with and without warnings being shown, and they're now always visible on the bottom.
> UI: Make simple mode settings warnings float at bottom of page

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Adding MasterStream.iR to OBS-Studio's Ingest List
This pull request adds the website of MasterStream.iR, which is the biggest restreaming platform in Iran with more than 3 years of availability and a user base of over 6,000 users, to OBS-Studio's ingest list. By adding this website to the ingest list, OBS-Studio users will be able to easily and conveniently use MasterStream.iR as a source for their live streams and content.
- JSON validation: Ensured that the JSON files are well-formed and adhered to the required format for OBS-Studio's ingest list.
- Copy JSON files to `%APPDATA%\obs-studio\plugin_config\rtmp-services`: Manually copied the JSON files to the appropriate location where OBS-Studio reads ingest settings.
- Checked settings: Verified that MasterStream.iR appears in the …
> rtmp-services: Add MasterStream.iR to ingest list

- plugins/obs-qsv11/obs-qsv-test/obs-qsv-test.cpp
MFXEnumImplementations expects the adapter index to be within a range of valid Intel adapters produced by MFXLoad and the config filter. If a system has one non-Intel high performance GPU and one Intel iGPU, OBS and the test app will see the Intel iGPU as index 1 due to high performance hints, but MFXEnumImplementations will expect only one valid index, 0. In this scenario, passing a value of 1 to MFXEnumImplementations will cause it to abort and return MFX_ERR_NOT_FOUND (Provided index is out of possible range). This causes subsequent capabilities testing to fail.
To avoid this, let's track how many non-Intel adapters we see and subtract that number from adapterIdx to only pass valid index to MFXEnumImplementations.
Want QSV to be correctly detected on multi-GPU mixed vendor systems. …
> obs-qsv11: Fix adapter enumeration in test app

- plugins/obs-webrtc/whip-output.cpp
- plugins/obs-webrtc/whip-utils.h
Improves WHIP compliance around the handling of Location headers.
If the location header isn't present we don't allow the session to start. We also now support Absolute and Relative Location headers. 
This cherry-picks https://github.com/obsproject/obs-studio/pull/9306 and then adds additional checks
I want to make sure we are as compliant as possible. If we ship a release with compliance issues we will have to support it forever. 
Tested against 
* AWS IVS
* Broadcast Box
* Cloudflare
> obs-webrtc: Improve WHIP compliance

- .clang-format
- UI/frontend-plugins/frontend-tools/auto-scene-switcher-osx.mm
- UI/platform-osx.mm
- libobs/obs-cocoa.m
- plugins/mac-avcapture/av-capture.mm
- plugins/mac-syphon/SyphonOBSClient.m
- plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm
- plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugIn.mm
- plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm
- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Updates ObjC-specific `clang-format` rules to coincide with https://github.com/obsproject/obs-studio/pull/9401.
Update files to updated `clang-format` version.
Tested locally on macOS 13 with `clang-format` 16.0.5.
> Update .clang-format rules for ObjC files for version 16

- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Fixes a crash on start of virtualcam output on macOS introduced by a recent change to use `NSData` instead of variable-length arrays.
Array iterations need to be determined by _dividing_ the byte size of the returned data by the size of a single object (not multiplied).
The actual value of `used` is undocumented, so using the more obvious `size` parameter makes the code also safer to use.
Tested on macOS 13.4, actively running virtual camera output with the new camera extension.
> mac-virtualcam: Fix crash on macOS when starting virtualcam output

- UI/update/win-update.cpp
- UI/win-update/updater/updater.cpp
Updates the UI and updater to run relaunch OBS with the same arguments that were originally used to launch it.
Options should be kept after updating, and @Warchamp7 complained.
- Launched updater via OBS to confirm that arguments are passed-through
- Launched OBS from updater to confirm that arguments are retained
> UI/updater: Retain OBS launch arguments

- UI/window-basic-settings-a11y.cpp
Changes the `SetStyle` macro in a11y settings to a static inline function.
Macros can be hard to read and are usually not very friendly to use in a debugger. Using a static inline function instead [gives the same result](https://gcc.gnu.org/onlinedocs/gcc-3.1.1/gcc/Inline.html) when compiling with optimizations,  with the advantage of better syntax highlighting in IDEs and better debugger support.
Noticed this when working on https://github.com/obsproject/obs-studio/pull/9402. Like to fix (change? Not sure "fix" is the right word since it's not really a bug) small things like these when I see them.
macOS 14
Tested that colors in Accessibility settings are still correctly set, as before.
> UI: Use inline function instead of macro to set color

- plugins/linux-pipewire/pipewire.c
Replace dynamic arrays introduced in #9339 by allocations.
I'm not used to use alloc as variable-length arrays and so I used dynamic arrays in this previous PR.
With #9412 and this PR, I wanted to give a try.
I didn't get nay issue while using a window capture.
> linux-pipewire: Replace dynamic arrays with allocations

- plugins/obs-ffmpeg/obs-ffmpeg-output.c
This PR sets the `avg_frame_rate` field on the video `AVStream` in obs-ffmpeg-output.
This sets the frame rate on container files when recording using "Custom Output (FFmpeg)".
Setting the frame rate on container files will report the accurate frame rate to tools such as ffprobe, and on associated files such as MPEG-DASH manifests (see before/after patch tests below for examples).
This was tested by recording videos before applying this patch, applying the patch, recording videos using the same settings, and ensuring the videos playback the same as before the patch.
Additionally the frame rate is present or more precise on the container or associated files with the patch.
Tests with recordings using Advanced -> "Custom Output (FFmpeg)" at 60 FPS:
MPEG-DASH before patch (note the absence …
> obs-ffmpeg: Set avg_frame_rate for AVStream video output

- UI/window-basic-settings-a11y.cpp
- UI/window-basic-settings.cpp
The QGroupBox::clicked is specifically for mouse clicks. This means that it's not emitted if the "checked" property is modified through other means than the mouse, for example programatically or through accessibility software like VoiceOver.
However, we do want to catch such events, so the QGroupBox::toggle signal (which as per the Qt documentation is the notified signal for the "checked" property) is the appropriate one to use.
As for the first commit, loading needs to be set to true to avoid the signal from activating the button while the settings are loading in. This should have always been done but just wasn't detected as the correct signal wasn't used so it wasn't triggered until now (also because there are no other settings in Accessibility that would have revealed this bug). …
> UI: Use QGroupBox::toggled signal for group changes

- UI/window-basic-auto-config.cpp
Capping the precision for whole numbers results in scientific notation being used for any number that's larger than what can be displayed with the given precision. In case of 2, that would be anything larger than 99, resulting in 120 for example to be shown as 1.2e+02. Let's not cap the precision for whole numbers ourselves and just use the default value (which at the time of writing would be 6).
Fixes https://github.com/obsproject/obs-studio/issues/9216
macOS 14
Auto-config wizard now shows "120" instead of "1.2e+02" which is much more helpful. Also tested with 119.88, 60, 30, and 29.97 FPS.
> UI: Don't cap auto-config wizard FPS whole number precision at 2

- plugins/sndio/sndio-input.c
Fix building with `ENABLE_SNDIO=ON`
Fix building even if it's disabled by default
Quickly tested by adding a sndio source. I have no experience with SNDIO.
> sndio:  Remove variable-length array usage

- UI/importers/sl.cpp
This change fixes unwanted behavior with hotkeys when importing a scene collection from a recent version of Streamlabs Desktop. They have changed how empty hotkeys are stored in a users scene collection .json so this updates the importer to ignore empty hotkeys.
Users in the community discord server have reported that scene collections they have imported from Streamlabs Desktop have unwanted hotkeys for various actions within OBS, which this fixes.
Took a scene collection exported from Streamlabs Desktop and imported it to OBS, saw that it no longer had the erroneous hotkeys as it did prior to this change. Compared the two scene collections from before and after this change to ensure there were no unwanted consequences.
> UI: Ignore empty Streamlabs hotkeys

- UI/window-basic-settings.cpp
Somewhat addresses #9118 by making it at least possible to change the encoder if only one is available by setting the combobox to an invalid state. Users will be prevented from saving settings until they select a valid item.
Want to make this issue recoverable without config editing.
Validated that when CoreAudio is missing the combobox will now show the placeholder instead, then once selecting "FFmpeg AAC" and saving the config will be in a working state again.
> UI: Set advanced audio encoder to invalid if missing

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Firstly, removes the `UpdateTransformShortcuts()` method introduced in c33fa8b which was trying to re-implement the behavior of `UpdateEditMenu()`.
Secondly, updates `UpdateEditMenu()` to account for sources without video. Sources without video shouldn't be able to have their transform edited, copied, pasted, or changed in any other way (because they don't have one).
The Transform menu items are now enabled/disabled as per the following ("AV" in this context means both sources with audio *and* video as well as sources with only video, they behave the same. "Paste Transform if applicable" means "Paste Transform is enabled if a transform got copied before".):
- No item selected: 
- No Transform items enabled.
- Single item selected:
- Audio-only: No Transform items enabled
- AV, locked: …
> UI: Fix transform shortcuts with multiple items selected

- libobs/obs-internal.h
- libobs/obs-output.c
In this PR, `video` and `audio` in `struct obs_output_t` will be left NULL if the output is an encoded output type.
To avoid NULL pointer access, adds a guard for `obs_output_get_video_conversion` to return NULL if not a raw-video output.
Also removes `starting_frame_count` because it's never read.
I observed random crashes while auto-configuration wizard in these environment.
- Windows running on a GitHub Actions runner.
- Crash log: https://cdn.discordapp.com/attachments/697237531426685029/1137964909670441041/Crash_2023-08-06_13-28-47.txt
- Log: https://cdn.discordapp.com/attachments/697237531426685029/1137964910001782794/2023-08-06_13-28-27.txt
- Ubuntu 22.04 running on Docker.
I also observed random crashes when started recording after changing advanced settings such as autoRemux. …
> libobs: Fix holding possibly released pointer in obs_output_t

- UI/window-basic-preview.cpp
Replace direct lookup of currently selected scene item on the Qt selection model with data available through prior call to `obs_scene_enum_items`.
The use of GetCurrentSceneItem can lead to a race condition between the graphics thread (where this function will be run) and the main UI thread, as both access the scene list model and iterate through its members which can change during iteration (as there is no lock around its access).
Tested on macOS 13, confirmed that spacing helpers are only drawn on a single selected item.
> UI: Fix possible race condition in DrawSpacingHelpers

- UI/window-basic-main.cpp
This moves the inclusion of
`UI/update/models/whatsnew.hpp`
within
`#if !defined(_WIN32) && defined(WHATSNEW_ENABLED)`
to fix compiling without nlohmann JSON and `ENABLE_WHATSNEW=OFF`.
This enables compiling without nlohmann JSON, which is used only for browser, websocket, and the whatsnew features (as far as I am aware).
Texted by compiling without nlohmann JSON installed, and the browser, websocket, and whatsnew features disabled on Gentoo Linux.
> UI: Fix compiling without nlohmann JSON

- UI/window-basic-main.cpp
Removes the silent fallback to OpenGL on Windows.
The fallback can hide issues with D3D11 and OBS's OpenGL backend is not well supported/tested on Windows.
Ran with broken D3D11 state (i.e. current master), got an error instead of silent fallback.
> UI: Remove silent OpenGL fallback on Windows

- cmake/Modules/FindLibva.cmake
- plugins/obs-qsv11/CMakeLists.txt
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/cmake/legacy.cmake
- plugins/obs-qsv11/common_utils_linux.cpp
VPL does not have a consistent initialization process for the various
backends it dispatches to. So this resolves the new VPL dispatcher
failing to initialize the video session when it dispatches to
intel-mediaSDK backend. On the oneVPL-intel-gpu backend VA-API sessions
are correctly initialized so this wasnt noticed when tested on newer
hardware.
I also tried to sneak in a small fixup for the low power fallback inside `InitParams`.
we call Query internally and possibly fixup the low power state and expect the
next status check to be done after the 2nd Query call.
QSV Should work on 7th gen like it did before the shift to the vpl dispatcher.
Arc card and 7th gen chip both work again.
> obs-qsv11: Fix VPL initialization on intel-mediaSDK

- .github/actions/check-changes/action.yaml
- .github/actions/qt-xml-validator/action.yaml
- .github/actions/run-clang-format/action.yaml
- .github/actions/run-cmake-format/action.yaml
- .github/actions/run-swift-format/action.yaml
- .github/scripts/utils.zsh/create_diskimage
- .github/workflows/push.yaml
Fixes open issues with CI workflows:
* Concurrency rules are enforced even for non-tagged pushes to master branch
* Checks against invalid git references fail in specific scenarios leading to false positives
Also downgrades the compression used for generated macOS disk images.
The disk images created by the packaging script are based on APFS (which is the default as of 2023) and `lzma` compression. The latter is only supported on Mac OS X 10.15+, which leads to a cryptic error message about a corrupted disk image for users on those older systems.
Using `lzfse` is supported on Mac OS X 10.11+ (with APFS being supported on Mac OS X 10.13+) so those older versions will be able to open the disk image.
> [!NOTE] 
> Even though users can open the disk image and copy the application bundle to …
> CI: Fix open issues and macOS disk image creation

- .github/actions/check-changes/action.yaml
- .github/actions/qt-xml-validator/action.yaml
- .github/actions/run-clang-format/action.yaml
- .github/actions/run-cmake-format/action.yaml
- .github/actions/run-swift-format/action.yaml
- .github/workflows/dispatch.yaml
- .github/workflows/push.yaml
Updates steps checking for changes to use `git cat-file` as the "empty" git reference passed by GitHub Actions will be considered a valid "commit-ish" hash by `git rev-parse --verify` (but not by `cat-file`).
Also updates the dispatch workflow to not create redirects to older (now non-existing) documentation pages and removes superfluous provision of the commit hash and fixes the condition for a documentation upload to always(!) happen for a pushed tag.
Unbreak tagged pushes and checks in general.
Changes to `git cat-file` were tested locally, changes to dispatch workflow need to be tested on CI.
> CI: Update checks for changed files to detect empty GHA references

- plugins/obs-filters/nvafx-load.h
- plugins/obs-filters/nvvfx-load.h
We need to check for new versions of the NVIDIA Effects redistributables because mismatched versions of the AUDIO and VIDEO sdk can have different CUDA versions of the deps, which has caused crashes in obs.
It'd be way better that NVIDIA either ships a single installer with both audio and video effects or that they auto-install with the drivers.
But meanwhile, we provide a warning to users which requires us to keep in sync with what's released.
Try to pre-emptively mitigate the risks by warning the user the sdk needs to be updated.
There's a warning displayed if the audio or video sdk are not the latest.
> obs-filters: Update NVIDIA Effects SDK versions

- UI/qt-display.cpp
Set the instance of OBSQTDisplay as the parent of the instance of SurfaceEventFilter so that the instance of SurfaceEventFilter will be destroyed when the OBSQTDisplay is destroyed.
Even if the instance of `SurfaceEventFilter` is deleted before the dispatcher of the event-filter, though I couldn't find documented information, this should be safe because the installed event filters are stored in a QPointer wrapper as below.
https://github.com/qt/qtbase/blob/50bce440277d4383dcf3a055cb9b5d513735bcbc/src/corelib/kernel/qobject_p.h#L95
A memory leak was introduced by my PR #9435.
Actually, there are similar memory leaks as described in #7557.
OS: Fedora 37
Tested with a temporary modification below and checked there is no memory leaks.
```patch
diff --git a/UI/qt-display.cpp …
```
> UI: Fix memory leak in OBSQTDisplay

- UI/obs-app.cpp
Moves the restarting of OBS to the end of `main()`.
Fixes #9467 and an oversight where the executable path is copied to the new arguments list as well.
Verified safe mode no longer kicks in during regular restarts and that arguments are copied correctly (minus the first one).
> UI: Move restart to end of main()

- .cirrus.yml
FreeBSD 13.1 is EOL.
Bump FreeBSD version in Cirrus-CI to currently supported release.
FreeBSD 13.1 is now EOL, and packages may not be available.
Tested in Cirrus-CI. The FreeBSD build itself is failing, but this allows the image and packages to install.
> CI: Bump FreeBSD version to supported release: 13.2

- build-aux/com.obsproject.Studio.json
- build-aux/modules/50-intel-media-sdk.json
- build-aux/modules/50-onevpl-intel-gpu.json
- build-aux/modules/50-onevpl.json
Add the 3 Intel libraries required to enable QSV in the Flatpak:
- OneVPL (Dispatcher for the following)
- OneVPL GPU for recent QSV capable hardware
- MediaSDK for Broadwell to Raptor Lake (excluded)
Most of unneeded feature are disabled.
Enable QSV
Intel Core m3-7Y30 (Amber Lake Y), so Media SDK.
Made a RTMP stream with a QSV encoder and it worked.
> build-aux: Enable QSV encoders on Flatpak

- cmake/common/versionconfig.cmake
The cmake update broke parsing the beta/rc version from `git describe`, this PR restores it. It also removes the old `BETA` and `RELEASE_CANDIDATE` defines in favour of always using `OBS_VERSION_OVERRIDE` as the source of the version.
Beta 1 on Windows did not have the beta version set, resulting in the update check still assuming that it is 29.1.3.
Tested tags and `OBS_VERSION_OVERRIDE` with beta/rc version strings.
> cmake: Parse beta/rc version from override/git describe

- .github/actions/steam-upload/action.yaml
- .github/workflows/publish.yaml
Specify tag when running Steam action in a release workflow.
`gh release download` will otherwise use the latest non-pre-release, see https://github.com/obsproject/obs-studio/actions/runs/5912931275/job/16036816503 where it downloads 29.1.3 instead.
Hopefully fixe automated Steam uploads for pre-release versions.
Has not directly been tested, but on my fork I tested specifying the beta tag to download the correct release and that worked.
> CI: Specify tag for Steam action on release

- UI/window-basic-main-outputs.cpp
Adds log messages if user has the checkbox for ignoring service bitrate limits set. Additionally adds a higher severity message if the undocumented config flag for ignoring all service settings (including keyframe interval) is set.
With #9442 we might see some people having trouble with services such as Twitch that have hard limits on ingest bitrate.
Disabled limits, got yelled at.
> UI: Log if user is ignoring service limits

- UI/data/locale/en-US.ini
- UI/obs-app.cpp
This fixes the capitalization of "WebSocket".
The official capitalization is "WebSocket", not "websocket". It looks cleaner this way.
I am confident that this works as-is.
> UI: Fix capitalization of "WebSocket"

- .editorconfig
- .github/scripts/.Aptfile
- .github/scripts/.build.zsh
- .github/scripts/.package.zsh
Requires:
- #9304
Use Ubuntu CMake package.
If it worked CI should fail while configuring obs-qsv until #9304 is merged.
Github enforce an updated version of CMake, while we need to rely on what the distribution actually provides.
If it worked CI should fail while configuring obs-qsv until #9304 is merged.
The right CMake is indeed use since configure has failed on obs-qsv.
> CI: Enforce the use of Ubuntu's CMake

- UI/window-basic-main-dropfiles.cpp
Use the latest version of the source type when dropping files.
On Linux, when a text file is dropped, the oldest version source of `text_ft2_source` is created.
OS: Linux
1. Start OBS
1. Drop files including JPEG, MKV, and text file types.
1. Exit OBS
1. Check `versioned_id` in the scene collection file.
- The newly created text source has `text_ft2_source_v2`.
- Other 2 sources have `image_source` and `ffmpeg_source`.
Note that I haven't tested on Windows.
> UI: Fix the source type version when dropping files

- UI/volume-control.cpp
The mute and config buttons were not vertically centered in vertical mode.
Before:
After:
Make the volume controls look better.
Looked at volume controls
> UI: Center vertical volume control buttons

- UI/forms/StatusBarWidget.ui
- UI/window-basic-status-bar.cpp
- UI/window-basic-status-bar.hpp
The status bar message was not vertically aligned properly to other widgets in the status bar. We have to implement our own message system here, as the default status bar in Qt has hardcoded paddings.
Before:
After:
Fix status bar visual bug
Saved recording to make sure status bar message looked correct
> UI: Fix alignment of status bar message

- UI/window-basic-main-profiles.cpp
Fixes #9497
Since enc-amf was removed, this reference causes issue by flagging H264 AMF as unsupported forcing a fallback to x264.
Fix a bug
Can't
> UI: Replace remaining enc-amf reference

- .github/workflows/push.yaml
- .github/workflows/scheduled.yaml
Moves the upload of language files to the scheduled nightly workflow run to upload changes in bulk and removes concurrency limits on the push workflow.
Current concurrency limits on the push workflow seem to prohibit GitHub Actions from _starting_ new workflow runs if there is an active one (even when canceling current runs is disabled) which means that desired actions are not run.
Language file upload is moved to nightly runs nevertheless because it might make more sense for translators to get changes in bulk as they will probably not look into untranslated strings after every push anyway.
Needs to be tested on CI with a nightly run and consecutive pushes to the master branch.
> CI: Move language file upload to nightly runs and remove master push concurrency limits

- UI/window-basic-main-dropfiles.cpp
This reverts commit aeed4a3aa1b81f154f10d047aad4974a7c293dd0, PR #2317.
https://github.com/obsproject/obs-studio/pull/9490#pullrequestreview-1587053356
The source type `browser_source` is now available for all supported platforms so we don't need to fallback to `linuxbrowser-source`.
OS: Fedora 37
Dropped a URL into OBS and checked the browser source is created.
Note: I didn't check if there is a 3rd party package that does not have `browser_source` but has `linuxbrowser-source`.
> Revert "UI: Support DnD overlay in linuxbrowser"

- .github/scripts/utils.zsh/create_diskimage
Kills the `XProtectBehaviorService` between attempts to macOS create disk image for distribution.
Workaround has been suggested by maintainer of GitHub Actions macOS runners (https://github.com/actions/runner-images/issues/7522#issuecomment-1566746364) as a fix for the "Resource Busy" issue that we run into semi-regularly on those runners.
Needs to be tested by having a CI run running into this actual issue.
> CI: Add brute-force workaround for macOS disk image creation failure

- plugins/obs-x264/obs-x264.c
1. Remove unused getparam() function
2. Refactor log callback
1. Remove limitation of message length.
2. Improve performance by remove the local copy.
3. Map x264 log level to obs.
1. Remove dead code
2. Improve performance
OS: Windows 10
Test steps:
1. Enable software encoder x264
2. Set x264 options to "log=3" to see some debug message of x264
3. Run recording.
Here is part of log file:
```
11:51:20.743: [x264 encoder: 'advanced_video_recording'] preset: fast
11:51:20.743: [x264 encoder: 'advanced_video_recording'] profile: main
11:51:20.743: [x264 encoder: 'advanced_video_recording'] settings:
...
11:51:20.743: 
11:51:20.744: using SAR=1/1
11:51:20.744: 
11:51:20.744: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
11:51:20.744: 
11:51:20.747: profile Main, level …
```
> Cleanup obs-x264 plugin

- cmake/finders/FindCEF.cmake
On Windows, if CEF libraries were present in default paths, they would be picked up in this find_program call, and it could later cause a build failure in the CMake custom copy commands on install if the components we are trying to copy do not exist. I recently ran into this after installing Intel PresentMon, which included CEF components, and was picked up by this find_program call. Let's apply NO_DEFAULT_PATH here the same as the find_library calls in this finder.
Want OBS to build even when the dev has other software installed.
<https://cmake.org/cmake/help/v3.25/command/find_program.html>
Built OBS locally on Windows 11 with Intel PresentMon installed. Verified that the build failed before this PR, but succeeded after this PR. Manually inspected the paths picked up by CMake in both.
- …
> cmake: Restrict FindCEF path to omit default paths on Windows

- .github/workflows/scheduled.yaml
Fixes step in nightly language file upload that is based on Zsh but has to be based on Bash instead.
Fix nightly CI runs.
Tested shell script in local bash environment with manually set `GITHUB_SHA` environment variable.
> CI: Fix scheduled language file upload

- UI/auth-youtube.hpp
`YoutubeAuth::chat` is a raw pointer that is uninitialized. Most of the time it doesn't matter, since the object it points to is created at the application start. However, in case of Wayland (Linux), CEF is not initialized (because it's not supported) and the chat object will never get created.
This patch fixes crash on Wayland by initializing `chat` to `nullptr`.
It fixes 100% crash on Linux Wayland when choosing a YouTube stream in "Manage Broadcast" window. 
Compiled locally and tested.
> UI: Fix crash in YoutubeAuth

- UI/window-basic-auto-config.cpp
- UI/window-basic-settings-stream.cpp
1. Fix stream key tooltip in the settings page
https://github.com/obsproject/obs-studio/assets/26628474/3e5fa173-16de-4016-b75d-a971cb425afc
2. Add stream key tooltip in the auto-config wizard
Display the correct text, icons and tooltips in the settings page.
Local build
> UI: Fix stream key tooltip in the settings page and add in the auto-config wizard

- UI/window-basic-main.cpp
- UI/window-basic-settings.cpp
Increase the minimum required output resolution from 8x8 to 32x32.
Some hardware encoders fail in indecipherable ways if you try to at certain low resolutions such as 17x17 or 19x19, but works at 20x20. However, there is no good way to determine what the minimum working resolution is for every possible encoder without running extensive capabilities tests locally and storing the results. There isn't that much difference between 8x8 and 32x32, except that the latter will reduce or eliminate such odd failure cases, so let's increase the minimum required output resolution by just a little bit.
Fixes #8934.
@Warchamp7 agreed with this in concept off-thread.
Built and tested locally on Windows 11. This uses a pre-existing mechanism for the resolution limit. The mechanism itself does not prevent …
> UI: Increase minimum output resolution to 32x32

- cmake/Modules/FindLibva.cmake
- plugins/obs-qsv11/CMakeLists.txt
- plugins/obs-qsv11/QSV_Encoder.h
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/cmake/legacy.cmake
- plugins/obs-qsv11/common_directx11.cpp
- plugins/obs-qsv11/common_utils.h
- plugins/obs-qsv11/common_utils_linux.cpp
- plugins/obs-qsv11/common_utils_windows.cpp
Fixes the wayland/x11 dependencies
Hopefully fixes QSV failing to initialize on multi-gpu systems like laptops.
Includes minor fix-ups I'm trying to sneak into this review.
Largely this is just a lot of shuffling of code so i can pass the codec being used into `Initialize` and use it to make a better decision on the device to use based on initial device enumeration. And some tweaks to avoid leaking resources that are hard to track with the current plugin design, while hopefully not impacting windows. And removing the previous attempt that used x11/wayland as a source of defaults.
People prefer when OBS works.
Encoding still works on Arc 750 and 7100U systems.
> obs-qsv11: Fix Linux build/runtime issues and clean up Windows code

- libobs/util/pipe-windows.c
- plugins/obs-ffmpeg/obs-nvenc-helpers.c
- plugins/obs-ffmpeg/texture-amf.cpp
- plugins/obs-qsv11/common_utils_windows.cpp
- plugins/win-capture/load-graphics-offsets.c
A user is reporting (#9293) an encoder test program failing to run, however we don't have any code to log why `CreateProcess` would fail. This PR adds logging if `CreateProcessW` fails and also (in a separate commit) quotes the executable paths used in `obs-ffmpeg`, `win-capture` and `obs-qsv11` as they are open to misinterpretation if the path has spaces in it.
Try to debug process creation failures and fix a potential issue.
Fixes #9293
Tested graphics offsets, NVENC and QSV test programs locally. No AMF DLL so could not test that but I think this code is correct?
> Quote process paths and add some logging

- UI/obs-app.cpp
- plugins/linux-capture/xcomposite-input.c
- plugins/mac-avcapture/av-capture.mm
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-outputs/ftl-stream.c
- plugins/obs-outputs/rtmp-stream.c
- plugins/rtmp-services/rtmp-common.c
This PR removes unused static functions under UI and plugins.
There are some unused static functions such as `getparam()` found by #9498.
Used `lcov` on macOS and Linux (Fedora 37 and Ubuntsu 22.04) and searched white lines (not counted lines).
When removing, I also checked the function is never found by `git grep`.
Built on Fedora 37 and run it.
CI will also test the code can be built...
Note:
`session_set_prop_str` is also unused but I left the function because this is just one type of `session_set_prop_*` functions.
https://github.com/obsproject/obs-studio/blob/08f5a7bd4d62c3aae459b59a02eb927001d4fdbb/plugins/mac-videotoolbox/encoder.c#L271-L279
> plugins, UI: Remove unused static functions

- plugins/obs-ffmpeg/obs-ffmpeg-srt.h
- plugins/obs-ffmpeg/obs-ffmpeg-url.h
- Moves `#include <sys/timeb.h>` from `obs-ffmpeg-url.h` to `obs-ffmpeg-srt.h`, which is the actual file that uses `struct timeb`.
- Adds `#ifdef _WIN32` so that `timeb.h` is not included on *nix system.
The `struct timeb` is used on `obs-ffmpeg-srt.h` for only Windows.
The header file `sys/timeb.h` is deprecated on FreeBSD so we want to not include the header file.
CI has passed to build the code.
Not tested on FreeBSD.
> obs-ffmpeg: Do not include sys/timeb.h on non-Windows system

- UI/win-update/updater/hash.cpp
- UI/win-update/updater/helpers.hpp
- UI/win-update/updater/patch.cpp
- UI/win-update/updater/updater.cpp
- UI/win-update/updater/updater.hpp
Cleans up a number of complaints from clang-tidy and ReSharper C++.
Code cleanup, fixing some longstanding issues (e.g. returning ints in a function with return type `bool`), replacing hacks like `CreateFoldersForPath` with modern std functions, some C++17 stuff.
Also removing some unused stuff, better const correctness, avoiding unnecessary copies in custom `std::hash` extension.
Compiled and updated an OBS install successfully.
> updater: Static analysis cleanups

- .github/actions/build-obs/action.yaml
Removes custom Ccache configuration path for cache status output step in `build-obs` action.
CCache configuration path was configurable until the CI script cleanup (as scripts were still intended to be used locally then), which is not needed anymore.
By specifying a custom path, the stats output of `ccache` will use the default cache directory (vs the custom one used on CI) and thus no cache hits will be reported.
Needs to be tested by CI run for pull request.
> CI: Fix ccache status output for workflow jobs

- UI/window-basic-source-select.cpp
Fixes an issue when enumerating sources for the "add existing" option. This clearly is meant to ignore hidden sources, not abort the enumeration when it encounters one.
OBS itself doesn't use them (yet), but third-party plugins do. Also fixes an issue observed with #9524.
Verified sources are now listed properly.
> UI: Fix source enumeration in source select aborting prematurely

- plugins/mac-avcapture/av-capture.mm
These effects can remain enabled between devices (so enabling it on one device can mean it's later also enabled on another device), leading to cases of capture cards getting blurred.
Logging that the effects are enabled should make it easier to spot this in support.
Blurred capture cards come up sometimes in support.
Medium term I'd also like to put a warning about it somewhere in the UI (maybe via the properties of the source, or the notifications system once it exists), but that brings UI/UX discussion with it. This PR just adds a log line on device selection (so on OBS startup or when a user switches the device).
Would like to get this into OBS 30.0 if possible (therefore the small scope).
macOS 14
Enabled the effects on my camera and saw it being logged upon device selection. Disabled …
> mac-avcapture: Log if portrait or studio light effects are active

- deps/json11/CMakeLists.txt
- libobs/audio-monitoring/osx/coreaudio-output.c
- libobs/cmake/os-macos.cmake
- libobs/obs-cocoa.m
- libobs/util/platform-cocoa.m
- plugins/aja/CMakeLists.txt
- plugins/decklink/CMakeLists.txt
- plugins/obs-ffmpeg/CMakeLists.txt
- plugins/obs-outputs/cmake/ftl.cmake
- plugins/text-freetype2/find-font.c
- plugins/text-freetype2/text-freetype2.h
- plugins/vlc-video/CMakeLists.txt
Either suppresses or fixes a majority of warnings currently emitted by macOS builds.
After reviewing the warnings currently emitted by macOS builds, a majority of them falls into these categories:
* Integer truncation: `libobs` uses 64-bit integers internally which are (with a few exceptions) stored in 16-bit integers. Given that most values used by code should fit within that smaller type, the truncation is possible, but improbable and even if it occurs should not lead to runtime issues.
* Outdated or abandoned vendored dependencies: Maintainers are aware of the status of these dependencies, with plans to either remove or replace them in due time. The warnings have been acknowledged and can thus be silenced.
Given the widespread occurrence of the warnings, it was not feasible to silence …
> CI: Suppress and fix majority of macOS-specific warnings

- UI/youtube-api-wrappers.cpp
The OBS client side timeout for the YouTube API is too short. New changes proposed to the YouTube API will cause this to fail for creating a broadcast. Increase to a minimum of 60.
Increase the timeout for the API used to create a YouTube broadcast to a minimum of 60 seconds.
The server side timeout is significantly higher. New changes to the create process are causing OBS
to prematurely timeout.
Tested on Windows.
- Bug fix (non-breaking change which fixes an issue) -
> UI: Increase YouTube API timeout 

- plugins/mac-virtualcam/src/camera-extension/OBSCameraDeviceSource.swift
Changes pixel format used by camera extension device to use BGRA instead of the more obscure ARGB.
BGRA was used by default in Apple's example code and is also already supported by OBS.
Tested on macOS 13.5.1 and checked reported format via Video Input Source.
> mac-virtualcam: Switch pixel format of camera extension to BGRA

- UI/window-basic-settings.cpp
Fixes ifdef disabling the function that actually destroys the YouTube dock when switching away from a YouTube service.
For some reason this used `BROWSER_ENABLED` which isn't a thing.
Doesn't need to stick around when you switch to a different service.
Hasn't.
> UI: Fix ifdef for YouTube dock integration

- libobs/util/platform-cocoa.m
Updates `NSProcessInfo` code to interact with the class directly instead of indirect ObjC message calls.
With the lowest deployment target being macOS 11.0, there is no need to check for the availability of the selectors on the NSProcessInfo class anymore.
The API was added in Mac OSX 10.9, so we are safe:
```
- (id <NSObject>)beginActivityWithOptions:(NSActivityOptions)options reason:(NSString *)reason API_AVAILABLE(macos(10.9), ios(7.0), watchos(2.0), tvos(9.0));
```
Tested on macOS 13.5.1.
> libobs: Remove old macOS guards for NSProcessInfo

- UI/win-update/updater/updater.cpp
Removes all non-error logging messages from multithreaded code.
Error messages could be hidden by another thread printing an informative message.
The messages printed from multithreaded code are also not particularly useful as they do not reflect reality (multiple things are downloaded/updated at once) and do not really help users understand what's happening either.
Updated OBS locally.
> updater: Remove non-error logging from multithreaded code

- plugins/obs-qsv11/common_utils_linux.cpp
Users with newer amd chips might get the default set to the wrong gpu.
Fixes recording on multi-gpu systems.
It still picks the same devices in my one gpu systems as expected.
> obs-qsv11: Ensure default devices are Intel devices

- plugins/win-dshow/win-dshow.cpp
Add a source name to every error log in win-dshow.
Some but not all of the `blog` call in `win-dshow.cpp` had source name.
When a user has multiple win-dshow inputs, it's hard to identify the input outputting errors in a log file.
For example, [this log file](https://github.com/obsproject/obs-studio/files/12504627/2023-08-28.20-37-03.7z.txt) has 82 MB log file and the online log analyzer refused to receive it.
The log file is first commented on the PR 6351. (This PR is unrelated to 6351 so I itentionaly didn't link it.)
Not tested.
Compilation on CI has passed without warnings.
> win-dshow: Log source name at error

- UI/window-basic-settings.cpp
Fixes the settings window always having the "Apply" button enabled as though things have changed.
This was simply due to the state of the checkbox being changed before the "loading" flag was set.
Fix UI.
Opened settings, apply button no longer enabled.
> UI: Fix settings Apply button always being enabled

- UI/obs-proxy-style.cpp
- UI/obs-proxy-style.hpp
Fixes #9473 
Once https://codereview.qt-project.org/c/qt/qtbase/+/494209 has been upstreamed into Qt we can version-gate or remove this.
Tooltip styling should work.
Compiled and ran OBS with tooltips now working correctly (tested with CI build and Qt 6.7 'dev' snapshot).
> UI: Add workaround for Qt tooltip stylesheet bug

- plugins/image-source/obs-slideshow.c
Fixes a buffer overrun in the slideshow source's audio rendering functions.
Fix bug discovered when working on the original variant of #9524.
Hasn't (this source doesn't actually support audio, but has to implement `.audio_render` as it's a composite source).
> image-source: Fix slideshow audio rendering buffer overrun

- UI/window-basic-main.cpp
Like many IDEs, Xcode has this feature where it shows the declaration of the method currently being worked in. However it gets confused by scopes starting inside of preprocessor guards and ending outside them, resulting in the declaration of OBSBasic::ReceivedIntroJson always being shown in window-basic-main.cpp from that method downwards. We can work around that by starting and ending the if-scope outside of the ifdefs.
I reported this problem to Apple a while back (FB12306380) but don't expect a fix in the foreseeable future.
The problem isn't big but does get a bit annoying after a while, and this workaround is quite trivial.
macOS 14, Xcode 15 Beta 8
Xcode now shows the correct declarations through the entirety of the file. Still compiles.
- Code cleanup (non-breaking change which …
> UI: Untangle ifdef'd if-statement to un-confuse Xcode

- UI/window-basic-main-profiles.cpp
Supersedes and closes #9508.
- Destroys dock when switching profiles
- Recreates it when it is a YouTube service and the dock doesn't exist yet (i.e. OAuth is not used, but YT service selected)
- Also destroys dock when creating a new profile (the old PR doesn't do this)
Fix this, but properly.
Switched between profiles, created new profiels.
> UI: Create/Delete YouTube Dock when switching profiles

- libobs/obs-output.c
This PR tries to fix the issue described in #9536 by another way.
Let `obs_output_video` and `obs_output_audio` return the media (video and audio, respectively) from the encoder if the output type is encoded.
|   | 29.1 | master | #9536 | This PR |
|---|---|---|---|---|
| Auto-config wizard (addressed by #9409) | works fine | works fine | works fine | works fine |
| MPEG-TS (addressed by #9523) | works fine | works fine | works fine | works fine |
| #9550 obs-websocket `GetRecordStatus` duration is 0 | Correct | Always 0 | Correct | Correct |
| #9551 obs-websocket `GetRecordStatus` dangling pointer access | Use-after-free | Always 0 | Use-after-free | Correct |
| obs-ndi/obs-ndi#908 Start NDI output fail after restarting video  | Use-after-free | Use-after-free | Use-after-free | …
> libobs: Fix obs_output_video and obs_output_audio for encoded output

- UI/cmake/legacy.cmake
- UI/cmake/ui-elements.cmake
- UI/expand-checkbox.hpp
- UI/source-tree.cpp
`ExpandCheckBox` was introduced in 88b6c63, but the seemingly replaced by `SourceTreeSubItemCheckBox` during development. This means that it became completely unused.
Noticed this empty class. Saw that it was unused.
macOS 14, compiled successfully.
Git grep'd for `ExpandCheckBox` and `expand-checkbox` to confirm it isn't used for styling (like `SourceTreeSubItemCheckBox` is).
Ran OBS to confirm groups still work.
> UI: Remove unused ExpandCheckBox

- cmake/common/versionconfig.cmake
Fixes the regular expression used to detect beta and RC builds.
While CMake can do partial matching with regular expressions, replacements require the entire regular expression to match the entire string.
Commits branching off a tagged commit will contain the necessary beta suffix, but also have the modification suffix and commit distance added, which _can_ be available after the beta number and thus have to be ignored.
Tested with a branch off a tagged beta commit.
> cmake: Fix regular expression for beta and RC version detection

- .github/actions/steam-upload/action.yaml
Fixes Steam upload action for runs triggered by a release.
The GitHub CLI tool requires an explicit tag to be provided when attempting to fetch information of prerelease versions.
Needs be tested via the next release tag.
> CI: Fix Steam prerelease detection for releases

- UI/window-basic-stats.cpp
This PR adds cleanup of the stats frontend event handler to window close.
Previously this was called in the destructor, but that is too late as the frontend API is gone by that point. It was then moved to the event handler for `OBS_FRONTEND_EVENT_EXIT` in #8735 but that doesn't account for the window being closed, leaking event handlers and causing crashes. Adding it to the window close handler should now account for both manual window closes / shutdown of OBS and the `OBS_FRONTEND_EVENT_EXIT` handler handles the dock cleanup.
Fixes a crash introduced in #8735, [reported on Discord](https://discord.com/channels/348973006581923840/1141766543735275570/1150805117008891904).
Verified code paths of closing windows and exiting OBS both clean up the event handler for the standalone window and …
> Add cleanup of stats callback on window close

- UI/data/locale/en-US.ini
- UI/window-basic-main.cpp
Some errors include HTML links directing users to e.g. driver updates or further information. Using a raw newline instead of `<br>` causes Qt to skip parsing the HTML, resulting in an ugly mess of HTML displayed to the user instead of the intended links.
Hopefully avoid this:
I only verified that `<br>` works as a newline in an error dialog. Didn't test all error conditions.
> UI: Avoid using newlines in error messages

- plugins/obs-qsv11/obs-qsv11.c
Fixes problems with the astrcmpi logic, as well as a typo that said "vertfast" instead "veryfast".
Also makes the method a void because it always returns true and isn't checked anyways.
Was found while investigating https://github.com/obsproject/obs-studio/issues/9574.
Hasn't.
> obs-qsv11: Fix target usage migration string comparisons

- libobs/obs-source.c
This PR changes the behaviour of the async frame cache to only break out of the loop if `frame` is already set. This avoids a repeated failure of the frame cache to select a close frame resulting in more frames being dropped than necessary on the output for a period of several seconds until it recovers.  
This appears to happen when OBS and the input source's frame timestamps go in and out of sync, an inconsistent frame delivery from the source, e.g. 24-8-24-8 ms pattern instead of 16.6 ms ± 2 ms (while frame timestamps stay consistent 16.6 ± 0.1 ms) seems to also exacerbate this problem.
I'm not sure if this is the "right" fix, but it sure seems to work in my testing.
This will **not** improve frame skipping when buffering is disabled, but that is not avoidable unless we tie OBS's …
> libobs: Do not skip async frames unless one has been selected

- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
For some reason, using MFX_SCENARIO_GAME_STREAMING causes the keyframe quants to be higher than other frames, which is not desirable. In turn, this causes bitrate to be higher than the target bitrate for a sustained period of time after each keyframe.
Not setting the scenario removes this behavior and returns CBR to somewhat reasonable levels of consistency.
<details>
<summary>Initial approach no longer used</summary>
obs-qsv11: Adjust CBR parameters to reduce bitrate variance
For CBR, set MaxKbps to be the same as TargetKbps, and reduce the multiplier for BufferSizeInKB from 2 to 1. This should reduce the bitrate variance while using CBR.
obs-qsv11: Adjust CBR parameters to reduce initial bitrate spike
For CBR, reduce the InitialDelayInKB multiplier from 1 to 0.5. This should reduce the …
> obs-qsv11: Fix unusual CBR bitrate issues

- plugins/obs-webrtc/whip-output.cpp
- plugins/obs-webrtc/whip-output.h
- plugins/obs-webrtc/whip-utils.h
libdatachannel is now built with MSVC instead of MinGW so we are able to
use C++ API instead.
The C++ is preferred by upstream and what the project is written in. The
C API provides a subset of features and has a performance penalty.
I have used it locally on NixOS + macOS
> obs-webrtc: Move libdatachannel code to C++ from C

- libobs/util/platform-nix.c
Forces loading of obs-studio plugins to always hide all imported symbols to avoid symbol duplication issues (particularly noticeable with `asio`).
By default duplicate non-static symbols loaded by dynamic libraries are de-duplicated by the dynamic library loader. This can lead to issues with statically linked libraries inside obs plugins if the symbols share their signature: Whichever plugin is loaded first gets to "set" the symbol (which can become problematic especially for C++ template functions).
Using RTLD_LOCAL ensures that all symbols are hidden and can only be explicitly loaded using dlsym() which avoids this issue.
Unfortunately due to the way scripting works in obs-studio, Python still needs to be loaded with RTLD_GLOBAL, hence the branch in the fix.
> [!NOTE] 
> Following …
> libobs: Fix duplicate symbol resolution for obs plugins

- plugins/mac-capture/mac-display-capture.m
- plugins/mac-capture/mac-sck-video-capture.m
- plugins/mac-capture/window-utils.h
- plugins/mac-capture/window-utils.m
The current code assumes that a display UUID can be created with the stored ID, but that's not always the case, e.g. when the user doesn't have the display connected. As such, we need to null check this, and fall back to the invalid ID (0) when the ID cannot be migrated.
The current code also only migrates on source creation, which yields weird behaviour where if the user opens properties and then cancels it would still show the first display, but only for the session. This is why the code was factored out of the creation function and now is always used when an ID needs to be acquired from OBS Data settings, including when the source is updated.
The deprecated display capture still doesn't like when the display doesn't exist (it returns false/NULL on creation leading to the source …
> mac-capture: Don't crash when migrating unknown display IDs

- UI/window-basic-main.cpp
Qt has been porting uses of Q_FOREACH/foreach to C++11's ranged-for. Let's do the same.
References:
* https://bugreports.qt.io/browse/QTBUG-115796
* https://doc.qt.io/qt-6/foreach-keyword.html
* https://codereview.qt-project.org/q/Q_FOREACH
* https://en.cppreference.com/w/cpp/language/range-for
We target C++17. Q_FOREACH was previously suggested to be deprecated/replaced for Qt 6. While that did not happen, Qt's efforts to replace Q_FOREACH/foreach indicate that its days may be numbered.
Built and ran OBS on Windows 11. Invoked the Reset Stats hotkey a few times.
> UI: Use C++11 ranged-for instead of Q_FOREACH

- UI/volume-control.cpp
- UI/volume-control.hpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- UI/window-extra-browsers.cpp
UI: Use std::shared_ptr instead of QSharedPointer
Also use std::weak_ptr instead of QWeakPointer as needed.
Qt has been porting QSharedPointer and QWeakPointer to std::shared_ptr and std::weak_ptr respectively. QSharedPointer is apparently 2x slower than std::shared_ptr.
References:
* https://bugreports.qt.io/browse/QTBUG-109570
* https://codereview.qt-project.org/c/qt/qtbase/+/359678
* https://codereview.qt-project.org/c/qt/qtgrpc/+/447780
* https://codereview.qt-project.org/c/qt/qtbase/+/450134
* https://codereview.qt-project.org/c/qt/qttools/+/450776
* https://codereview.qt-project.org/c/qt/qttools/+/450777
* https://codereview.qt-project.org/q/QSharedPointer
Built and ran OBS on Windows 11. Created, opened, closed, and removed some Custom Browser Docks.
- Performance enhancement …
> UI: Use std::shared_ptr instead of QSharedPointer

- libobs/data/color.effect
- plugins/obs-filters/data/color.effect
Can happen when colors are wider than Rec. 2020.
Don't want black pixels where colors should be.
Both shader paths looked buggy before and look fine after. Also verified Windows OpenGL runs.
> libobs,obs-filters: Fix NAN when tonemapping

- plugins/obs-ffmpeg/texture-amf.cpp
Re-enable dynamic bitrate on texture-amf. This was left out of #8991 for some reason.
After reconfiguration was fixed the flag wasn't added back.
Fixes #9667
Fixes #8548
Hasn't.
> obs-ffmpeg: Readd OBS_ENCODER_CAP_DYN_BITRATE to AMF texture encoders

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Update OnlyFans streaming service urls 
We have changed the our main url for streaming. Added it as a new entity. The old one has been renamed as an alternative.
Not tested. Since it was not possible to build the project on macOS 12.5 (a lot of build errors)
> rtmp-services: Update OnlyFans streaming service

- plugins/linux-v4l2/v4l2-helpers.c
- plugins/linux-v4l2/v4l2-helpers.h
- plugins/linux-v4l2/v4l2-input.c
Expand packed values to 4 bytes, and wrap up static values with a macro.
These days you might capture card a 175Hz monitor with a framerate defined as 10000000/57143 that doesnt fit in a short, as reported by a user. And reporting a negative FPS in that case isnt very helpful.
My logitech webcam still works.
> linux-v4l2: Expand packed values to 4 bytes

- UI/window-dock-youtube-app.cpp
Explicitly initialises CEF when a YouTubeAppDock is created to fix a premature trigger of a `QEventLoop` before the main event loop has even been started.
This avoids all other browser docks' browser instances from being automatically created, their associated websites being loaded, and their video and audio output automatically playing even though no docks are hidden.
> [!IMPORTANT]
> Given that user-created browser docks do _not_ use `InitBrowserPanelSafeBlock` but instead initialise CEF directly on the main event loop, this should not lead to worse UX, but merely makes the YouTubeAppDock behave like normal browser docks.
> [!NOTE]
> When used before the primary event loop has been started, this function will lead to unknown side-effects. After that, the function does have the same …
> UI: Fix YouTubeAppDock causing hidden browser docks to automatically play audio on macOS

- libobs/obs-scene.c
Use the locally unique ID of a scene item for its hotkey(s) rather than the name, which will conflict when multiple sceneitems for the same source exist.
Also addresses the following issues:
- IDs and counter were not restored before creating hotkeys, which needs to be the case for ID-based hotkeys to work
- Moving items into and out of groups did not move their hotkeys to the group/scene so they would get lost
- Adds migration for old name-based hotkeys to new ID-based ones
Fixes #9639
Verified hotkeys are now saved and loaded correctly.
> libobs: Fix hotkeys with groups and duplicate sceneitems

- plugins/win-wasapi/win-wasapi.cpp
Changes process audio capture to use the OS-provided timestamp instead of calculating our own. In tests this seems to resolve audio issues reported by various users (also see: https://github.com/stream-labs/obs-studio/pull/543).
Additionally adds some logging and handling for flags that may be set by `IAudioClient::GetBuffer()`:
- `AUDCLNT_BUFFERFLAGS_TIMESTAMP_ERROR` is treated as failure, buffer is free'd and capture reset
- `AUDCLNT_BUFFERFLAGS_DATA_DISCONTINUITY` is logged to debug, but ignored as it probably won't cause issues with libobs's audio data processing
- `AUDCLNT_BUFFERFLAGS_SILENT` now replaces the buffer with all zeroes to avoid processing potentially stale or garbage data (also logged to debug as it can get very spammy)
Hopefully helps with #8064 (not closing that one …
> win-wasapi: Use provided timestamp for process capture and handle flags

- plugins/win-wasapi/data/locale/en-US.ini
Removes the "BETA" from the Application Audio Capture name.
With #9672 merged and hopefully finally fixing #8064 it's probably time to remove the "BETA" label.
We can wait with this until we receive more feedback during the final release candidate phase.
N/A
> win-wasapi: Remove 'BETA' from Application Audio Capture name

- UI/window-basic-main.cpp
Fixes an issue where if no filters had previously been copied and the user copies a filter from either the scene tree or the audio mixer, the "Paste Filters" action would not be available until the Edit menu reloads (e.g., by selecting another source in the source tree).
I'm looking to also do another change to check filter compatibility before enabling "Paste Filters" in general which will probably replace both these calls by `UpdateEditMenu` which gets called increasingly often which starts to annoy me a bit because of overhead but that's a future problem 😅. Maybe `UpdateEditMenu` should get split up into multiple parts or something. I'm also mostly writing this so that I remember in the future.
@RytoEX noticed this issue when looking at something related.
macOS 14.
Copying filters from …
> UI: Enable "Paste Filters" after copying from scenes or mixer

- .github/scripts/utils.zsh/setup_linux
Adds support for revisions in buildspec file for Linux CI builds.
Updating dependencies without increasing the version number requires a revision suffix to the file name (as hashes will change).
This support is already implemented in CMake for Windows and macOS but was missing support for Linux builds, which is added with this PR.
Tested on Ubuntu 23.04 with added revision to buildspec and without.
> CI: Add support for dependency revisions to Linux CI builds

- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Current code assumes that a newer version of the extension is always better. However that's not true - when the user installs an old version of OBS, we should also install the old version of the camera extension to have a version compatible with the installed OBS.
For normal users this method is only called when the versions in the Info.plist do not match. In system extensions developer mode it's called every time an installation is requested (meaning on every start), which is probably desired as well; and by never returning "ReplacementActionCancel" we can now always treat "ErrorRequestCanceled" as an error and not something that we requested to happen.
OSSystemExtensionErrorRequestCanceled is called when the activation delegate returns OSSystemExtensionReplacementActionCancel on request …
> mac-virtualcam: Always replace camera extension; Treat extension installation cancellation as error 

- plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Adds a switch to distinguish between the possible results that could occur. While we expect to received RequestCompleted for our camera extension (RequestWillCompleteAfterReboot is usually more of a network extension thing), we can't be sure that this always is what we receive unless we check it.
I may have overdone it a bit by adding the locale string but if we're adding this handling we may as well also tell the user about it.
@PatTheMav suggested this in #9638 
macOS 14.
Tested that the virtualcam still works as before because we always receive `OSSystemExtensionRequestCompleted`.
Tested the `OSSystemExtensionRequestWillCompleteAfterReboot` code path by flipping the switch cases, I'm not sure we can get actually get this case in reality (at least currently. who knows what happens in …
> mac-virtualcam: Check result of finished extension installation

- UI/data/themes/Acri.qss
- UI/data/themes/Dark.qss
- UI/data/themes/Grey.qss
- UI/data/themes/Light.qss
- UI/data/themes/Rachni.qss
- UI/data/themes/System.qss
- UI/data/themes/Yami.qss
- UI/obs-app.cpp
- UI/source-tree.cpp
- UI/window-basic-status-bar.cpp
Adds search paths for Qt `theme:` prefix upon initialising style for the first time so theme data can be referenced with relative paths anywhere within Qt (e.g. stylesheets, QUrl).
While exploring options for making the appearance of OBS more customisable without requiring users to write their own theme files I encountered the issue that all image files use relative paths.  
If we do not load QSS from a path but instead a runtime generated stylesheet this won't work, so instead use a search path with custom prefix that will work regardless of where the file is loaded from.
Loaded up themes, confirmed they still work.
> UI: Add theme data search paths

- .github/actions/steam-upload/action.yaml
Fixes the steam upload action once again.
- `gh release view --json` outputs keys in alphabetical order, regardless of the order of speciifed tags, so this never worked
- `gh release download --pattern` is case-sensitive
- `asset_names` was never used
- Custom asset URLs were assigned from outputs that don't exist rather than the inputs?
I hate it here.
Tested at least the dispatch: https://github.com/derrod/obs-studio/actions/runs/6466954279/job/17556017624
> CI: Fix Steam upload (again)

- UI/update/win-update.cpp
On Windows in VS2022 I was getting a compile error due to the usage of `strlen` in a `constexpr`.
`C:\Repos\github\obs-studio\UI\update\win-update.cpp(60,30): error C2131: expression did not evaluate to a constant`
I asked about this in the OBS developer Discord chat but it seems like the original author of this code was not experiencing a compile error.
It is unclear to me exactly why I am experiencing the compile error and the original author of the code is not. I checked to see if the string whose length was being checked (`OBS_COMMIT`) was defined in my build, which it is, although it was set to empty string by default. In my debugging I tried manually setting OBS_COMMIT to a non-empty string and still got the same compile error.
However, it seems like the right thing to do here is …
> UI: Fix compile error due to use of strlen in constexpr

- libobs/obs-output.c
As of fb57eff212fbe5e777cf559288bc70bf67d9c428 `output->video` will be `NULL` for encoded outputs, so check if the output has the video flag set instead to determine whether or not to print frame stats.
Fixes #9704
@Penwy confirmed that this change fixes it.
> libobs: Fix rendering stats not being logged on output stop

- plugins/linux-v4l2/v4l2-input.c
This copies the linear alpha settings UI and translation strings from `image-source` and applies the setting to the V4L2 `obs_source_frame`.
I am supplying non-premultiplied alpha to OBS, but OBS seems to be converting the frame to premulitplied alpha, and then render it as if it *wasn't* premulitplied, which gives a very wrong look. With this setting enabled, it looks correct.
I am not sure why this is called "linear" alpha in OBS - to my knowledge alpha is always *linear*.
By trying it with a v4l2loopback source, AR24 format, non-premultiplied alpha. I have also tested that changes to the checkbox are visible in the preview immediately.
- (could not find any)
The changes to the V4L2 source UI look like this:
> linux-v4l2: add support for linear alpha blending

- UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp
- UI/frontend-plugins/frontend-tools/auto-scene-switcher.hpp
Remove a variable `startAtLaunch` and function `on_startAtLaunch_toggled`.
`startAtLaunch` was there from the initial commit 39592ff5eb for the scene switcher. However, it was not used at that time and is still not used.
The automatic scene switcher is automatically started if it was enabled at previous time. I think the variable `startAtLaunch` is unnecessary.
OS: Fedora 37
Checked there are no files containing `startAtLaunch` by git-grep.
Checked major functionalities on Automatic Scene Switcher are working.
> frontend-tools: Remove unused startAtLaunch variable

- libobs-d3d11/d3d11-subsystem.cpp
Log VRAM in GiB.
Bytes are not super useful to humans.
Verified that it gets logged somewhat more readable.
> libobs-d3d11: Log VRAM in GiB

- deps/obs-scripting/obs-scripting-lua.c
Adds to the search path of native libraries for OBS to look for.
Currently when using Lua scripts and you include a module that is Lua code. OBS will properly resolve it by searching the script's location, however if the module is a native library OBS will only search its executable location as well as obs-scripting folder. This fixes the issue and allows OBS to resolve native libraries lying in Lua script's location. Fixes #9100
Tested on Windows 10, OBS 29.1.0, Lua 5.1
The script provided uses a native library for Windows 64-bit
[sample-script.zip](https://github.com/obsproject/obs-studio/files/11781606/sample-script.zip)
> obs-scripting: Search native libraries in Lua script's location

- UI/update/win-update.cpp
Adds a missing check as `config_get_string()` actually returns `NULL` if the key does not exist.
Other config or data functions return valid values even if not set, e.g. `config_get_int()` returns `0` or `obs_data_get_string()` returns `""`, and I missed that `config_get_string()` doesn't when changing this from a number to a string.
Fixes #9719
Verified OBS no longer crashes if `SkipUpdateVersion` config key does not exist.
> UI: Add missing NULL check for skipUpdateVer

- cmake/macos/compilerconfig.cmake
Adds a check to explicitly make sure that the macOS SDK being used is recent enough to build OBS. OBS code currently has ifdefs for older SDKs in some but not all places and relies on some frameworks existing that do not exist on older versions, this should clarify what we require.
This commit sets the minimum SDK to 13.0. This can be increased in the future if required.
I've put this code in `compilerconfig.cmake` because it feels to me like it makes the most sense, but am not really sure about that. Happy to change this if desired.
The ifdef situation is a bit unclear. We have 12.3 ifdefs in some places, but then not others, same with 13.0.
The [wiki](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Mac#prerequisites) specifies Xcode 14.2 (which has the macOS 13.1 …
> cmake: Explicitly fail if macOS SDK is too old

- libobs/audio-monitoring/osx/coreaudio-enum-devices.c
- plugins/mac-avcapture/av-capture.mm
- plugins/mac-capture/audio-device-enum.c
- plugins/mac-capture/mac-audio.c
Replaces enum values `kAudioObjectPropertyElementMaster` and `kCMIOObjectPropertyElementMaster` with their `Main` counterparts.
The `Master` versions are deprecated since macOS 12. This doesn't currently complain as our deployment target is 11, but it also doesn't hurt to use the new versions (which are the same values anyways) as we soft-require (and soon hard-require, see #9698) the macOS 13.1 SDK.
macOS 14
Compiled and run. The resulting code is the same as `Master` and `Main` have the same values in both the AudioObject and CMIO cases.
> libobs, mac-capture, mac-avcapture: Replace Master enums with Main

- plugins/obs-qsv11/obs-qsv11.c
QSV logging was missing many of its settings. Let's fix that.
Want more accurate logs.
> obs-qsv11: Log more QSV settings

- plugins/linux-pipewire/pipewire.c
These functions log that they should be used with the thread lock held, so lets hold the lock before calling them.
Maybe it fixes the errors we see related to obs_pw being invalid.
adding a bunch of pipewire sources and removing a bunch and restarting obs and nothing seems impacted.
- Bug fix (non-breaking change which fixes an issue) (maybe)
> linux-pipewire: Add locks to unsafe pipewire functions

- plugins/linux-pipewire/pipewire.c
We refactored this data to be part of the format properties instead of an out parameter. But forgot to start using this field instead.
Fixes comments here https://github.com/obsproject/obs-studio/issues/9733#issuecomment-1773900272
Both `RGBx` and `BGRx` render correctly on my machine now.
> linux-pipewire: Use the format properties for swap r/b

- plugins/linux-pipewire/linux-pipewire.c
After the cmake 3.0 rebuild glad was transitioned to a static library. This lead to the glad symbols being uninitialized and crashes when they are used in some cases.
fixes shm capture for compositors that dont support dmabuf.
Loading with software gl no longer crashes when calling glBindTexture.
> linux-pipewire: Load glad symbols on start

- libobs/CMakeLists.txt
Changes `libobs` export to include SIMDe headers by default.
Fixes https://github.com/obsproject/obs-plugintemplate/issues/95.
Checked import of `libobs` Framework with new settings and confirmed SIMDe headers were correctly copied over.
> libobs: Export SIMDe headers unconditionally for plugin development

- plugins/mac-virtualcam/src/camera-extension/OBSCameraDeviceSource.swift
Resolves the conversion to a Double in `OBSCameraDeviceSource`, such that the virtual camera device timer fires correctly every `1/60` seconds, instead of trying to fire every `0` seconds.
Resolves https://github.com/obsproject/obs-studio/issues/9760. CPU use was very high with the new virtual camera extension at idle and while active because of the amount of polling the device timer was doing.
Tested locally on my machine. Reduced camera extension process CPU use by roughly 10x.
> mac-virtualcam: Correct device timer firing rate

- UI/window-basic-main-outputs.cpp
This actually applies the presets to the AMF AV1 encoder when selected to record in simple mode.
Selecting AMF AV1 in simple mode recording doesn't trigger an update of the encoder settings, causing it to use the defaults of CBR 2500 kbps instead, which could easily be construed as unwishable.
Reproduction steps : 
- Select AMF AV1 in simple mode.
- Record
[Log showcassing the issue.](https://obsproject.com/logs/zfmQ7KirdCNPqLUB)
Recorded AMF AV1 in simple mode, verified that it used CQP 16 as intended.
[Log of test.](https://obsproject.com/logs/z106Gn4ztZVOI66j)
> UI: Fix AMF AV1 simple recording presets

- plugins/win-wasapi/win-wasapi.cpp
Log the source name when a WASAPI device is initialized.
This was brought up in the ideas section of the community discord and I agree that it will help when troubleshooting.
Checked the log: https://obsproject.com/logs/VfuT59quYb99nOos
> win-wasapi: Log source name on initialization

- plugins/mac-avcapture/av-capture.mm
- plugins/mac-capture/mac-sck-common.h
- plugins/mac-capture/mac-sck-common.m
- plugins/mac-capture/mac-sck-video-capture.m
- plugins/mac-capture/plugin-main.c
- plugins/mac-videotoolbox/encoder.c
8dd20dfd335dd07d2f1678c9cdf67894e09beab4 introduced an explicit check for the available macOS SDK, meaning that we can be sure that the macOS 13.1 SDK is available. As such, we do not require ifdef guards for the availability of functions that are older than 13.1.
Don't like dead code.
macOS 14, compiled and run.
Made a basic test with the effected sources/encoder to make sure I didn't majorly screw anything up.
Functionality should be the same as before.
> plugins: Remove old macOS version ifdefs

- UI/data/themes/Acri.qss
- UI/data/themes/Dark.qss
- UI/data/themes/Grey.qss
- UI/data/themes/Light.qss
- UI/data/themes/Rachni.qss
- UI/data/themes/System.qss
- UI/data/themes/Yami.qss
- UI/source-tree.cpp
- UI/source-tree.hpp
Replaces the empty `SourceTreeSubItemCheckBox` class which is only used for styling with a property.
IIRC @Warchamp7 wanted `themeID` to go the way of the dodo in favor of properties set to true, so I'm using this syntax. Needs confirmation though.
Having classes just for QSS styling seems a bit overkill to me when it's possible to achieve the same result without them.
macOS 14
Tested in all themes that the expand checkbox still shows the icons, but when the group is expanded and when it's not.
> UI: Replace SourceTreeSubItemCheckBox class with Qt property

- plugins/linux-pipewire/pipewire.c
We were passing the core pipewire pointer where renegotiation expected the stream pointer. Somehow this worked, probably because the two are very close.
fixes #9733
Very wrong and crashing.
Tested with hyprland and it fixes the issue.
> linux-pipwire: Pass obs_pw_stream to renegitation callback

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
- plugins/obs-ffmpeg/vaapi-utils.c
- plugins/obs-ffmpeg/vaapi-utils.h
The option is already there, but it wasn't available from UI.
Add B-Frames option for VA-API
The option was already there, but it was needed to edit configuration file to enable B-frames. This makes it available from UI.
Tested with mesa driver.
> obs-ffmpeg: Add B-Frames option for VA-API

- libobs/CMakeLists.txt
Adds more files to list of public header files to fix build errors for 3rd party plugins.
`libobs` does not provide a bespoke set of public headers for consumers of the library - instead the internal structure of the library is exposed unchanged via its internal headers to consumers.
This requires all headers that export symbols to be included as well as all headers included by those, and also all headers providing functionality via static inline functions.
As these are distributed over almost all headers of `libobs` (there are no bespoke "export headers" that only contain symbols and inline functions needed for consumers), this unfortunately also requires providing a majority of the header files.
This change probably "overcorrects" the issue, but given that 3rd party plugins currently …
> libobs: Add more files to list of public headers

- libobs/CMakeLists.txt
- libobs/cmake/legacy.cmake
- libobs/obs-av1.c
- libobs/obs-av1.h
One notable difference from the AVC/HEVC code is that it also inserts the METADATA and SEQUENCE_HEADER OBUs into new_packet, otherwise the resulting video file wouldn't play.
Add AV1 parsing functions
This is needed for Linux VAAPI (#8832) and NVENC (#8794) encoders. Split out from the VAAPI PR so NVENC can use it before VAAPI lands. 
I've been using it with VAAPI encoder and it works with both recording (mkv, mp4, ...) and streaming to YouTube.
> libobs: Add AV1 parsing functions

- UI/window-basic-preview.cpp
Clear stretchGroup if the group is meant to be ignored.
Group resize is not deferred until adjustments are completed by a mouseReleaseEvent in certain cases, resulting in unexpected movement of sources that are part of a group as they are resized or stretched beyond group bounds.
Related/Resolved Issue: https://github.com/obsproject/obs-studio/issues/9754
The bug can be described/reproduced as follow:
1. The user selects within a group in the sources dock
2. The user moves their mouse over the selected source such that the cursor would change.
- This results in a cursor update and a call to `GetStrechHandle()`
- as the source is part of a group, `stretchGroup` will be set to the group of the source
3. The user clicks on the canvas without touching a stretch/rotation handle
- A …
> UI: Fix transform of sources in groups

- libobs/data/area.effect
- libobs/data/bicubic_scale.effect
- libobs/data/bilinear_lowres_scale.effect
- libobs/data/default.effect
- libobs/data/lanczos_scale.effect
- plugins/obs-filters/data/blend_add_filter.effect
- plugins/obs-filters/data/blend_mul_filter.effect
- plugins/obs-filters/data/blend_sub_filter.effect
- plugins/obs-filters/data/chroma_key_filter.effect
- plugins/obs-filters/data/chroma_key_filter_v2.effect
- plugins/obs-filters/data/color_correction_filter.effect
- plugins/obs-filters/data/color_grade_filter.effect
- plugins/obs-filters/data/color_key_filter.effect
- plugins/obs-filters/data/color_key_filter_v2.effect
- plugins/obs-filters/data/luma_key_filter.effect
- plugins/obs-filters/data/luma_key_filter_v2.effect
- plugins/obs-filters/data/mask_alpha_filter.effect
- plugins/obs-filters/data/mask_color_filter.effect
This pattern uses fewer instructions and also avoids using max, which does not work on infinity.
Also remove unreferenced techniques from scale filters.
Clean up my past badness.
> libobs,obs-filters: Use common straight alpha math

- cmake/finders/FindCEF.cmake
This modify the CEF finder of CMake 3.0 framework, to restore a behavior that was supported with 2.0.
The Flatpak (and also my CEF AUR packages), do not generate/use a build folder to provide the wrapper.
I don't see a real reason to drop this behavior.
Makes Flatpak on CMake 3.0 with #9787 (with other fixes e.g. fix GIO finder, disabling AJA) build.
- If you have a shorter commit name idea, feel free to suggest it.
> cmake: Allow finding the CEF wrapper without a build folder on Linux

- deps/obs-scripting/obs-scripting-python.c
Restores delta patching functionality on macOS for users with correctly configured Python framework for scripting.
Python automatically creates bytecode caches which end up inside the application bundle of OBS Studio on macOS. These directories will lead to a hash mismatch when Sparkle attempts to apply a delta update (to ensure that the patch can be applied).
> [!NOTE]
>
> This issue will occur even without any active scripts - just having a valid Python framework configured will make the scripting library create a Python environment and import the `obspython` module.
Tested on macOS 14 by launching the application with Python 3.10 enabled and checked the contents of the app bundle. Also removed the automatically created cache directory on an unfixed bundle and confirmed that Sparkle …
> obs-scripting: Fix Sparkle delta updates by disabling bytecode caching

- plugins/mac-videotoolbox/encoder.c
0 seconds means "auto" according to the [documentation](https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_maxkeyframeinterval), but this appears
to be broken in many configurations (more than just CRF mode on Apple
Silicon). With some encoders it means that the encoder sets a keyframes
every 31st frame, other times it just doesn't set any keyframes at all
after the first one, only rarely does the "auto" interval actually
appear to work.
Lets just set the default to 2 seconds and be happy. In theory this is
the maximum keyframe interval and encoders are allowed to set more if
they so wish, but they never appear to do so.
Also removes the 0 second keyint override in CRF mode.
The 0 second default interval no longer happens per default, if
someone explicitly …
> mac-videotoolbox: Set default keyframe interval to 2 seconds, Remove CRF 0 second keyint override

- UI/window-basic-main-outputs.cpp
- UI/window-basic-main.cpp
This logs the output type and output source of the virtual camera both when starting it and when changing it while it is running.
Issues caused by an user mistakenly selecting the wrong output type/source are rather frequent, this would greatly streamline the troubleshooting process for those.
Ubuntu 22.04.
Started and changed the virtual camera output type, verified that the logging is correct.
No crash no memory leak.
> UI: Log Virtual Camera output type

- docs/sphinx/reference-core.rst
- libobs/obs.c
- libobs/obs.h
- plugins/win-wasapi/CMakeLists.txt
- plugins/win-wasapi/plugin-main.cpp
- plugins/win-wasapi/wasapi-notify.cpp
- plugins/win-wasapi/wasapi-notify.hpp
- plugins/win-wasapi/win-wasapi.cpp
Changes win-wasapi to reset audio monitoring when the default output device changes.
Fixes #4463
Closes #5398 
When the default Windows output changes, OBS should switch to the new one if it is configured to use default.
- Enable audio monitoring with default device
- Change default output device: OBS responds [ok]
- Change default input device: OBS does not respond [ok]
- Set audio monitoring to non-default device
- Change default input/output devices: OBS does not respond [ok]
> libobs, win-wasapi: Handle changes to the default audio monitoring device

- UI/window-basic-main-outputs.cpp
- UI/window-basic-main.cpp
cvam -> vcam
Want function names to be easily understood and not cause confusion. Noticed while evaluating commits for inclusion in the release/30.0 branch.
Built locally on Windows 11 to confirm the rename did not introduce build errors.
> UI: Fix typo in Virtual Camera logging functions

- plugins/win-capture/graphics-hook/vulkan-capture.c
This race condition is caused when one thread creates a swap chain, which calls OBS_CreateSwapchainKHR, at the same time another thread calls OBS_CreateImageView.
OBS_CreateSwapchainKHR allocates swap data, publishes this into the data->swaps linked list, then initializes it. Meanwhile, OBS_CreateImageView is iterating the swaps linked list, to see if the image matches any swap chain images. Due to the order in OBS_CreateSwapchainKHR, there's no guarantee this data is initialized so it often ends up running out of bounds on the swap_images array.
The fix is simply to defer the swap data publish to after init.
The issue is that we have one thread (our window thread) creating a swap chain, which calls OBS_CreateSwapchainKHR, at the same time another thread (the main thread) is calling …
> win-capture: Fix Vulkan race condition

- UI/window-basic-auto-config.cpp
- UI/window-basic-settings-stream.cpp
Before:
Make the text display correctly. And after clicking on "Use Stream Key (advanced)", the button is hidden.
Unable to test in local build.
> UI: Fix UseStreamKeyAdv not display stream key and not hide button

- cmake/windows/compilerconfig.cmake
- cmake/windows/helpers.cmake
Adds necessary compiler and linker flags to mimic MSVC's default settings which always generate PDBs regardless of optimisation and never use incremental linking.
CMake 3.25 changed the way PDB generation is handled by only enabling it for Debug and RelWithDebInfo builds, which prohibits generation of fully optimized builds with associated symbols (which is MSVC's default).
If configuring with CMake 3.25 or above, enable this globally for builds using MSVC and fall back to embedded debug information for anything else (which would probably be clang-cl).
The necessary linker flag `/DEBUG` also needs to be added manually to the "Release" configuration, as CMake removes it by default.
With these changes, users get the benefit of optimised builds while we retain the ability to symbolicate …
> cmake: Force PDB generation on Windows for MSVC builds in all configs

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
- Adds Dallas ingest
- Rotterdam PoP was moved to Amsterdam
- Use RTMPS for all servers
Always good to keep services up to date
Validated that the JSON files parse correctly.
> rtmp-services: Update IRLToolkit service

- deps/obs-scripting/obs-scripting-python-import.c
- deps/obs-scripting/obs-scripting-python-import.h
- deps/obs-scripting/obspython/CMakeLists.txt
Adds necessary forward definitions of Python symbols for Python 3.11, enabling Python 3.11 support for Windows and macOS.
Python 3.11 is the first version with official ARM64 support on Windows and is also the current stable version of Python.
Compiled and run OBS with Python 3.11 on Windows 11 and macOS 14.1, used a Python test script to check API functionality with all 17 tests passing.
Also confirmed that the loaded Python version in the frontend was reported as Python 3.11.
> obs-scripting: Add Python 3.11 support for Windows and macOS

- plugins/linux-pipewire/pipewire.c
We use a size_t that can be 64bit while EGL uses 32bit for the
underlying value on some platforms. Writes from our graphics function
can leave high bits uninitialized and cause iteration of the format list
to overlfow in those cases.
fixes #9844
This short write seems uncommon,  maybe this is just due to legacy nvidia drivers on the device in issue.
OBS still works on my machine.
> linux-pipewire: Ensure n_drm_formats is zero initialized

- libobs/obs-scene.c
This PR adds `obs_data_array_release` when a legacy scene item data structure is detected.
Before the commit 763dddbbaf, hotkeys to show and hide scene items are distinguished by source name instead of ID. When migrating from the legacy data structure, the pointer to the data was not released.
OS: Fedora 37
Steps to reproduce and test:
1. Prepare an old scene collection file.
Ensure there is a key starting from `libobs.hide_scene_item.` and followed by source names instead of numbers.
2. Run OBS.
3. Exit OBS.
4. Check there is no memory leaks.
> libobs: Fix memory leak when migrating from legacy scene item data

- plugins/obs-filters/cmake/speexdsp.cmake
Remove `/LTCG` linker flag for SpeexDSP implementation on Windows.
Flag was added in CMake 2.0 update and is incompatible with incremental linking enabled by default for Debug configuration (MSVC default) in recent compiler flag update.
The original error that necessitates adding LTCG is not present with current obs-deps anymore, so remove it and disable the hard-coded default library directive instead.
Built OBS Studio on Windows 11 with Debug configuration on current master.
> obs-filters: Remove LTCG linker flag for SpeexDSP builds on Windows

- UI/obs-app.cpp
Disables safe mode when `--multi` is used.
Fix #9859
Hasn't.
> UI: Disable safe mode when `--multi` is used

- libobs/util/platform-cocoa.m
- libobs/util/platform-nix.c
Implements macOS-specific API functions for libobs to report free disk space.
APFS has the concept of "purgeable disk space" which is used by the OS for caches, ephemeral data and volume snapshots, which will be made available to users if they write data to disk.
As such the disk space available to users can be larger than what is actually used on the volume. macOS makes a distinction between available volume data for different types of data, for OBS it makes sense to use "Opportunistic Usage" which is defined as "nonessential resources".
This aligns the amount of free disk space with what is reported in Finder, Disk Utility, and other native applications.
Fixes https://github.com/obsproject/obs-studio/issues/9810.
Tested on macOS 14.1.
> libobs: Use macOS specific APIs to report free disk space

- libobs-d3d11/CMakeLists.txt
- libobs-d3d11/d3d11-shader.cpp
- libobs-d3d11/d3d11-subsystem.cpp
- libobs-d3d11/d3d11-subsystem.hpp
OBS needs Windows 10 minimum these days, so the DLL will be there.
Less code is better.
Able to run OBS with empty shader cache, with and without DISASSEMBLE_SHADERS defined.
> libobs-d3d11: Use OS D3DCompiler_47.dll

- libobs/obs-scene.c
Removes the internal helper `remove_without_release()` and branches `obs_sceneitem_remove()` into public and internal versions.
The `obs_sceneitem_set_transition()` calls were missing from the `remove_without_release()` function, so this resolves that issue implicitly. Code cleanup mentioned above is done to hopefully avoid these mistakes again.
Ran OBS, added some scene items, removed them, removed the whole scene, things all worked as expected.
> libobs: Consolidate scene item remove code

- .github/scripts/.build.zsh
- cmake/macos/helpers.cmake
Changes the `PRODUCT_NAME` property to "OBS Studio" to ensure `CFBundleName` in the app bundle's `Info.plist` has the value used in OBS Studio 29.
The `CFBundleName` is used on macOS for the menu bar, Dock, LaunchPad, and task switcher. The changes to have Xcode manage the property list file automatically requires the `PRODUCT_NAME` to be set correctly for this.
Fixes https://github.com/obsproject/obs-studio/issues/9871.
Tested on macOS 14.1.
> cmake: Align Product Name and Bundle Name on macOS

- UI/frontend-plugins/frontend-tools/output-timer.cpp
This will fix the output timer bug from issue #6558. If you use the output timer too many times in a run of the program, issues start happening where on every other run of the output timer, the video will stop prematurely and generate a tiny video recording file. 
Every time the start button is pressed it makes a new connection to the QTimers, increasing the amount of connections and signals being sent to the QTimers by 1 each time the start button is clicked.
This fix moves the connections to the QTimers to the function that creates them, so that the connection is only established once.
Fixes #6558.
I used the output timer to record multiple 5 seconds videos consecutively with the issue not happening.
> frontend-tools: Fix multiple signal-slot connections on output timer

- libobs/media-io/video-frame.h
- libobs/util/array-serializer.h
- libobs/util/crc32.h
- libobs/util/file-serializer.h
This PR adds `extern "C" {}` to the header files under `libobs/util/` that contain extern functions.
I realized it causes a link error when I include a header file `util/crc32.h` and use the function from a C++ source code.
OS: Fedora 37
In a C++ source code for an external building plugin, included `util/crc32.h` and called `calc_crc32` from a function, and build it. Then, confirmed the linker shows no error.
CI will test this won't break existing code.
> libobs/util, libobs/media-io: Fix link error including header files from C++

- libobs/util/text-lookup.c
Removes an unused dstr from this struct.
Stumbled over it while working on some text-lookup related experiments.
Still compiled
> libobs/util: Remove unused struct member from text-lookup

- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
If an output has already stopped, but its StopRecording function was called again, then ffmpeg_mux_stop would be called and set stopping to true. On the next output start, OBS would output 1 frame, see that stopping is true, and then stop the output.
This was most easily observed using an Output Timer to record prior to 93f5b45be8c8b91199c52cf7a0ab59d8c3a08760.
Initialize stopping to false with the other state flags to ensure that the output has a clean starting state.
Discovered while reviewing #9813 and investigating #6558.
Prior to 93f5b45be8c8b91199c52cf7a0ab59d8c3a08760 (#9813), you could run into this by following these Steps To Reproduce:
1. Set an Output Timer for recording. Use something like 5-10 seconds (short enough to make repeatedly running easy, long enough to distinguish …
> obs-ffmpeg: Initialize stopping member variable to false

- deps/media-playback/media-playback/decode.c
- deps/media-playback/media-playback/media.c
- libobs/media-io/media-remux.c
- plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
Deprecated FFmpeg API usage (deprecated by FFmpeg 6.1) are updated to use the [newer API as detailed here.](https://github.com/FFmpeg/FFmpeg/blob/master/doc/APIchanges).
~~Note that one of the commits removes code that uses the deprecated API without replacement code. This is because the metadata being copied by the removed code is handled by the latter usage of `avcodec_parameters_copy()` which copies over the metadata that is now included in `AVCodecParameters` since FFmpeg 6.1.~~
The code that is no longer necessary since FFmpeg 6.1 is now in a `#if` block. See the previous comment for details.
On ArchLinux, the AUR package obs-studio-git fails to build due to usage of deprecated FFmpeg functions causing build fails (as the deprecation warnings are treated as errors). Currently, …
> Add support for FFmpeg 6.1

- plugins/obs-ffmpeg/CMakeLists.txt
- plugins/obs-ffmpeg/cmake/legacy.cmake
Adds missing header to cmake lists.
Missed this file in VS.
Re-ran CMake, file now listed in VS.
> obs-ffmpeg: Add missing header to CMakeLists

- plugins/mac-videotoolbox/encoder.c
Fixes caller of `create_encoder` handle `OSStatus` error codes instead of boolean and change function signature to reflect the types that are actually returned by the function.
When an encoder was not created in create_encoder, the appropriate OSStatus value is returned but the calling code expects a boolean return value.
The negative OSStatus code sent on error is thus interpreted as a truthy value and the error is not detected. Changing the call signature to correctly return an OSStatus (and change the caller to detect error situations) fixes this.
Tested on macOS 14.1.1.
> mac-videotoolbox: Fix handling of unsuccessful encoder creation
