UI/window-basic-settings.cpp
Trying to output to a container with multiple extensions currently results in the container having all file extensions  (e.g. mpegts results in the file extension being `.ts,m2t,m2ts,mts`).
This just fixes that by adding a missing `*`.
=> UI: Fix ffmpeg output file extension

UI/data/locale/en-US.ini, UI/window-basic-settings.cpp
While recording to mp4 in obs-studio is safer than in classic there still are situations where a file is not finalized such as
* Some crashes to desktop as well as situation where obs becomes unresponsive
* Crashes outside of obs (Bluescreens, Power outages, etc.)
* Recordings never stopping i.e. Button saying "Stopping Recording..." but it never finalizing (At least on once occurence forceful stopping as introduced in 5c5d0ba9e5055ea4fc961b06d03263ed10920a96 didn't work for me either)
* File system is full and file can no longer be written
Given the amount of users I've seen in the past weeks having issues with unfinalized recordings I think it is sensible to warn them about the possible dangers of recording to mp4 while also suggesting an alternative (mkv + remuxing).
The warning …
=> UI: Add warning for recording to mp4 format

.travis.yml
This PR will:
- Disable skip_join This isn't working with obs-dev on QuakeNet because external messages aren't allowed.
- Always notify on failure and only on builds/commits that fixed the build.
- Reformat the IRC message to something like this:
[Travis CI|passed] obs-studio/master (Gol-D-Ace - Commit title) https://travis-ci.org/jp9000/obs-studio/builds/buildid
This is most likely only temporary until our bot OBScommits can handle it.
=> Travis CI IRC Notifications fixing and reformatting

.travis.yml, CI/before-script-linux.sh, CI/before-script-osx.sh, CI/install-dependencies-osx.sh
Uses [ccache](https://ccache.samba.org/manual.html#_description) to speed up recompilation.
=> CI: Use ccache to speed up the build

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Update ingest list for Restream.io:
- add new Restream server: Asia (Seoul, South Korea)
- update rtmp-services version
Restream ingests could be checked at: https://restream.io/ingests
=> rtmp-services: Update ingest list for Restream.io

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Updated max 3.5 to 6. See https://help.twitch.tv/customer/portal/articles/1253460-broadcast-requirements#Broadcast%20Requirements
> Recommended bitrate range - 3-6 megabits per second
=> rtmp-services: Update maximum bitrate for Twitch

plugins/image-source/image-source.c
The code to process GIF animations contained a return statement that
will skip the modification check, if the image is not in an active
scene. Like that images in the preview scene of studio mode would never
update, when they get modified on disk.
Also reloading the image, if an animation file has been modified before
processing the old animation that will be replaced later anyway, seems
like a better way to do it.
=> image-source: Move file modification check before animation processing

UI/window-basic-main.cpp
Previously, minimizing obs-studio in any linux window manager without a system tray resulted in a segfault! This simple fix changes that.
also happens when switching workspaces in a tiling wm like xmonad
Bug introduced as of abe4bfd
=> UI: Fix segfault when no system tray exists

libobs/obs.c
Prevents double free of type data for sources.
=> libobs: Remove multiple calls to free_type_data

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Update maximum video bitrate for Picarto from 2000 to 3500 and maximum audio bitrate from 160 to 128.
See http://help.picarto.tv/knowledge_base/topics/how-to-configure-open-broadcaster-software:
> **2. Max bitrate should be set according to our streaming standards. But not more than 3500. Also it is very important that your bitrate is not higher than your own internet upload speed, otherwise you will suffer frame drops.**
> **3. Settings for Audio Encoding section:**
> 
> - Codec to: **AAC**
> - Format to: **48kHz**
> - Bitrate between **64 - 128** depending on your personal preference and internet bandwidth. (128 recommended)
> - Channel to: **stereo**
As always, feedback is appreciated.
=> rtmp-services: Update Picarto maximum bitrates

plugins/win-dshow/ffmpeg-decode.c
Update `packet_size` when reallocating.
=> win-dshow: Fix reallocation issue in ffmpeg-decode

UI/data/locale/en-US.ini, UI/forms/OBSRemux.ui
Currently "Dialog" is the window name. This changes it to "Remux Recordings."
=> UI: Add window name to remux dialog

libobs-opengl/gl-subsystem.c, libobs-opengl/gl-x11.c
This commit logs the OpenGL version on all operating systems and brings the OpenGL subsystem's initialization logging more in line with the D3D11 logging to make logs more uniform.
The warning for selecting OpenGL on Windows systems will still occur.  This is largely to make the logs more uniform across systems/settings.  Hopefully we'll see this less on Windows anyway with fdc9c47875b6f583865a5dd6200d089d53774145 and 67e5f6c54e6cc3e6896768e297e881ee7f2e2797.
Compiled and tested on Windows 10 64-bit.
=> libobs-opengl: Log OpenGL version on all systems

UI/window-basic-main.cpp
This commit removes some define statements that were used in the updater code before OBS Studio 18.0.0 (see [UI/window-basic-main.cpp from 17.0.2](https://github.com/jp9000/obs-studio/blob/17.0.2/UI/window-basic-main.cpp#L2056)).  They are no longer used, so they should be safe to remove.  Of course, I would understand if they were left in place to be used by something else later.
=> UI: Remove unused defines from old updater code

UI/forms/OBSBasic.ui
Added a shortcut to "Edit Transform", with Ctrl+E (lines 1191-1193).
Editing was very easy in OBS Classic, and I could not find the option
for stretching a source to bounds in OBS Studio, so the "Edit Transform"
dialogue should be more user-facing. Giving it a keyboard shortcut
denotes that it is important enough to have a shortcut, as opposed
to the myriad options with no shortcut
=> UI: Ctrl+E to Edit Transform

CONTRIBUTING.rst
When visiting https://www.kernel.org/doc/Documentation/CodingStyle, you see the message, "This file has moved to process/coding-style.rst".  I feel like linking to the old document just creates an extra step for users wanting to understand the coding style of this project.  This commit replaces the old URL with a version hosted on GitHub.
=> Update Linux kernel coding style URL in CONTRIBUTING

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
- Remove livecoding.tv (now using per-user ingest assignment)
- Remove Connectcast.tv (Shutting down)
- Remove Cashplay.tv (Shut down)
- Remove Restream.io LA ingest (removed)
- Rename Stre.am to Stream.live and update URL
=> rtmp-services: Update ingests

UI/window-basic-main-dropfiles.cpp
If user drags and drops text files on Mac & Linux, a segfault would happen because gdi would be selected instead of freetype.
=> UI: Fix drag & drop bug

UI/window-basic-settings.cpp
Fix a double free in the settings window that occurs on linux only.
The UI Element already gets deleted above as a child of the
advAudioGroupBox which is not present on linux.
Apart from making the code even more unreadable, this will likely
come back to haunt us if the advAudioGroup will ever be shown on linux.
=> UI: Fix settings dialog crashing on linux

libobs/util/platform-nix.c
Make sure the target file exists before attempting to create a backup.
This will allow for the function to work correctly if the target does
not yet exist.
=> libobs: Fix os_safe_replace not working linux

CI/install-dependencies-osx.sh
Possible fix for "curl: (56) SSLRead()" errors on Travis. Curl only retries until a connection is made but not if it is lost afterwards. Wget can handle that (see https://gist.github.com/flomotlik/6212725).
Other projects have had similar issues with OSX builds on Travis and this seems to be the suggested fix (https://github.com/travis-ci/travis-ci/issues/7636, https://github.com/travis-ci/travis-ci/issues/7628).
=> CI: OSX - Use wget instead of curl

plugins/decklink/audio-repack.c, plugins/decklink/decklink-device.cpp, plugins/decklink/decklink-device.hpp, plugins/decklink/linux/CMakeLists.txt, plugins/decklink/mac/CMakeLists.txt, plugins/decklink/win/CMakeLists.txt
Some minor changes/fixes:
* Add the ability to disable the plugin by passing `-DDISABLE_DECKLINK=1` to cmake
* Fix two compiler warnings
=> Decklink fixes

UI/window-basic-main-outputs.cpp
For OBS changelogs (includes 2.1.0/2.0.0 changes):
```
* The AMD Encoder has been completely rewritten from scratch for improved stability, performance and new features. All advanced configurations will break due to this change.
* Added HEVC, Two-Pass and Full-Range color support to the AMD Encoder.
* Improved timestamps generated by the AMD Encoder.
```
- Added: HEVC Encoder for Polaris, Vega, etc.
- Added: Pre-Pass Mode to AVC & HEVC Encoder.
- Added: Variance Based Adaptive Quantization (VBAQ) to AVC & HEVC Encoder.
- Changed: Improved speed by rewriting internal encoder code.
- Changed: Massively reduced encoding latency by removing threaded submission and querying.
- Changed: IDR Period now has a default of 0 ("Don't Overwrite").
- Changed: Improved multi-GPU support with Direct3D9 …
=> enc-amf: Version 2.1.3

CI/before-deploy-win.cmd
.gitignore is useless to users who download artifacts.
=> CI: exclude .gitignore from AppVeyor artifacts

UI/obs-app.cpp
This commit fixes creating **crash** log files in windows with Unicode path.
cf. #916
=> UI: Fix creation of crash log with non-english paths

plugins/obs-outputs/librtmp/rtmp.c
When building on FreeBSD before this patch, it would produce the error:
`plugins/obs-outputs/librtmp/rtmp.c:733:25: error: use of undeclared identifier 'ENODATA'`
This patch fixes that.  For more information, check this [FreeBSD mailing list conversation](https://lists.freebsd.org/pipermail/freebsd-hackers/2016-May/049494.html) and this [file from Ceph](https://github.com/ceph/ceph/blob/e8f03e205d27dc3f25b4446093b4c11ba7b9a135/src/include/compat.h#L27).
This patch builds successfully on FreeBSD 11.  As always, I would appreciate additional testing and feedback.  On this particular PR, review from @jp9000 or @notr1ch would be great since it touches librtmp.  If there's a better solution, feel free to edit this PR or close it and fix the issue in another commit.
=> librtmp: Fix build error with ENODATA on FreeBSD

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Microsoft renamed Beam.pro to Mixer for some reason, so here's the update for that.
=> rtmp-services: Rename Beam to Mixer

UI/obs-app.cpp, libobs/graphics/effect-parser.c, libobs/graphics/shader-parser.c, libobs/util/cf-lexer.c, plugins/obs-outputs/librtmp/cencode.c
Since GCC 7 added new warnings, fall through in switch statements are flagged during compiling time.
Assuming all existing cases are intended, this PR adds a hint to the compiler so no warnings are displayed.
More info about this warning can be found here: https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/
=> Suppress -Wimplicit-fallthrough in GCC 7

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main-transitions.cpp
This Pull Request aims to add several features to the Frontend API:
- Functions: enable, disable and get Studio Mode status + get and set the current preview scene
- Events: on Studio Mode enable and disable + when the currently previewed scene in Studio Mode changes.
Please let me know of any issue with code style or API design.
=> UI: Add functions and events for Studio Mode into the Frontend API

plugins/obs-text/gdiplus/obs-text.cpp, plugins/text-freetype2/text-freetype2.c, plugins/text-freetype2/text-freetype2.h, plugins/text-freetype2/text-functionality.c
Delayed reading the text file till the update after the timestamp changes, this should fix a minor issue where if the file updates twice in one second, only the first change it displayed.
Fix was also appied to text-freetype2.
=> obs-text: Fix file reader occasionally not updating

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
This PR removes the enforced maximum audio bitrate limit for Picarto.  It seems that they now recommend leaving the audio bitrate at OBS' default (160), but they permit higher bitrates with no maximum limit specified.
See http://help.picarto.tv/knowledge_base/topics/how-to-configure-open-broadcaster-software:
> You don't have to change the audio bitrate for art live streams. If you are streaming music an increased audio bitrate might bring better quality to your live stream audio. It all depends on your own internet connection.
As always, feedback is appreciated.
=> rtmp-services: Update Picarto maximum audio bitrate

UI/forms/OBSBasic.ui
This commit fixes two regressions introduced by the modular UI (commit
25bb8a444fb3a7ca6c19a429f2d89e83a6ddb823):
- the Delete key no longer working in the scene list
- the Delete key no longer working in the source list
This commit also enables the Delete key on sources that were selected by clicking on them in the preview, which addresses [Mantis Bug 576](https://obsproject.com/mantis/view.php?id=576).
Originally, I had added code for enabling the Delete key on sources selected in the preview by adapting it from the code for adding the "nudge" hotkeys.  After going over the generated UI code, I figured I could attach the "actionRemoveSource" action to the preview widget instead of handwriting additional code for it.  I'm all ears for any feedback on better ways to do this.
All of this …
=> UI: Fix Delete key not working on scenes/sources

UI/window-basic-auto-config.cpp, UI/window-basic-auto-config.hpp
This PR updates instances of "Beam" or "beam.pro" to "Mixer" in the autoconfig wizard.  This should remove the last holdovers of the former "Beam" and "beam.pro" names.
I've successfully compiled this on Windows 10 Pro 64-bit, and the compiled OBS did run.  However, I did not try the autoconfig stream test for Mixer as I do not have an account on Mixer.  For that, I apologize.
As always, feedback and testing are welcome.
=> UI: Update service names in autoconfig wizard

UI/forms/OBSBasicSettings.ui
This fixes the issues presented in:
https://obsproject.com/mantis/view.php?id=885
https://obsproject.com/mantis/view.php?id=354
Minimum size is changed to 700x512. I arrived at this number from testing
the minimum sizes that I felt the settings UI was still perfectly usable
and readable. Any smaller, and things became difficult to see and adjust.
Min before: https://pub.rachni.com/img/obs64_2017-07-27_19-43-38.png
Min after: https://pub.rachni.com/img/obs64_2017-07-27_21-57-15.png
It should be noted that while the min height was significantly reduced, the min width was increased to avoid clipping of UI elements.
=> UI: Fix settings window minimum width/height

plugins/obs-outputs/ftl-stream.c
The ftl output gets very spammy (3-6 lines every 5 seconds), this PR changes the loglevel of those messages to debug so they do not clutter up the logs of users.
In case these messages are needed they can be re-enabled using the `--verbose` flag.
=> git obs-outputs: Change loglevel of ftl status thread to debug

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
That said "Columbia", and not "Colombia".
https://en.wikipedia.org/wiki/Medell%C3%ADn
Many people in USA are confusing with this name, but well, here is the fix :)
=> rtmp-services: Fix misspelled country name

libobs/obs-nix.c, libobs/util/platform-nix.c
This PR's goal is to make the system info logging (CPU name, CPU speed, CPU core counts, and memory) more like Windows and Mac.
Rename "Processor" to "CPU Name" and place it before the number of cores. Log free RAM for *nix. Log CPU Speed on Linux and FreeBSD. Unify processor logging on Linux and FreeBSD. Get logical and physical CPU cores on Linux and FreeBSD, even for multi-core CPUs. Use the new os_get_logical_cores and os_get_physical_cores function from commits 6fc74d6 and e4a64f0 to get CPU core counts on *nix systems.
This has been compiled and tested on Ubuntu 16.04 and FreeBSD 11.  I haven't noticed any memory leaks or errors with this patch.  Additional review, feedback, and/or testing would be appreciated.
=> Make *nix system info logging more like Windows/Mac

libobs/obs-nix.c
This was found with ASan as a part of investigating my segfault, caused by other factors.
The calculation was off and caused read overflow. The correct range is `mincode...maxcode` (`...` means inclusive, which contains both min and max).
=> Fix XCB keyboard mapping size calculation

plugins/linux-capture/xcompcap-helper.cpp, plugins/linux-capture/xcompcap-main.cpp
Some window managers like i3 don't issue Expose events when switching
between workspaces, but send VisibilityNotify events. This causes the
stream to freeze even when the workspace is switched back.
Related issue: https://obsproject.com/mantis/view.php?id=863
=> Add fix to watch for VisibilityNotify events.

UI/window-basic-main.cpp
Add 'Advanced Audio Properties' option to context menu over empty area
of the Mixer's pane.
=> UI: Add missing option to context menu

UI/data/themes/Rachni.qss, UI/volume-control.cpp, UI/volume-control.hpp
With the addition of the peak volume indicator, themes may wish to change
these colors but there was no way to do so. This change updates the
VolumeControl widget to allow a stylesheet to adjust all possible colors
for the volume bar. In addtion, the Rachni theme is updated to demonstrate
this new capability.
=> UI: Allow volume peak to be customized via .qss

UI/window-basic-main.cpp
The parent window adjusted according to child object polices and hint 
sizes. Thus, it is possible to disable all docking panes to restore 
true parent geometry first. The docking geometry and settings will be 
restored later in OBSBasic::OBSInit().
Fixes issue when any Docks panes were disabled - the application still
restores full size interface on startup.
=> UI: Fix parent window geometry loading

deps/file-updater/file-updater/file-updater.c
If there is no network connection, OBS crashes after 5 minutes idling
with following crash:
*** longjmp causes uninitialized stack frame ***: obs terminated
======= Backtrace: =========
/lib64/libc.so.6(+0x6f1e3)[0x7f8f95f901e3]
/lib64/libc.so.6(__fortify_fail+0x37)[0x7f8f96018ba7]
/lib64/libc.so.6(+0xf7add)[0x7f8f96018add]
/lib64/libc.so.6(__longjmp_chk+0x29)[0x7f8f96018a39]
/usr/lib64/libcurl.so.4(+0xa5d5)[0x7f8f979b75d5]
/lib64/libpthread.so.0(+0x10e30)[0x7f8f962cae30]
/lib64/libc.so.6(__poll+0x2d)[0x7f8f95fff46d]
/usr/lib64/libglib-2.0.so.0(+0x4a64c)[0x7f8f91b5564c]
/usr/lib64/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f8f91b5575c]
/usr/lib64/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f8f9706c1ff] …
=> file-updater: fix crash due to network timeout

UI/window-basic-main.cpp
This commit prevents users from being able to use the "Paste (Duplicate)" context menu option after copying a source that has the OBS_SOURCE_DO_NOT_DUPLICATE flag set. Though OBS would correctly paste the source as a reference, it seems that this behavior was confusing some users. This fixes [Mantis Bug 1034](https://obsproject.com/mantis/view.php?id=1034).
I decided to disable/enable the option instead of hiding/showing it because I thought that changing the context menu too often might also be confusing for users.  This was also the easiest change to make (just slightly fewer lines of code).  However, I'm not completely against the hide/show idea, and I'm definitely open to hearing feedback or rationale for hiding/showing the context menu item as needed.  Tagging @Fenrirthviti since he …
=> UI: Disallow pasting duplicates of sources with DO_NOT_DUPLICATE

libobs/util/platform-windows.c
This is a follow-up to 47aa56b (PR #620).  Windows 10 revision detection broke in Build 15036 (Creators Update) after Revision 296.  For all revisions of Windows 10 Build 15036 after Revision 296 up to Revision 608, OBS will log Revision 296 (Windows Version: 10.0 Build 15063 (revision: 296; 64-bit)).  This aims to further fix revision detection on Windows 10 by forcefully checking the registry for the Windows 10 revision.  To try to ensure we're logging the correct revision, I also compare it against the revision from `kernel32.dll` and logs whichever is higher.
I drafted a few different possible solutions to this and gave rationale in a gist [here](https://gist.github.com/RytoEX/1faa1e0e468e3565ea37df3ca5b5d571).  It may be sufficient to just always log the revision from the registry. …
=> libobs/util: Fix Windows 10 revision detection

libobs/CMakeLists.txt, libobs/obs-windows.c, libobs/util/platform-windows.c, libobs/util/windows/win-registry.h
This PR aims to add logging for the Windows 10 Gaming Features that can negatively affect OBS performance.  This is to make it easier for support providers to diagnose possible issues with OBS users on Windows 10.  Tagging @Fenrirthviti since this patch is of interest to him.
This PR consists of two commits.  The first adds a wrapper function to libobs/util for Windows to make it easier to query the Windows Registry.  The file `libobs/util/windows/win-registry.h` is based on `libobs/util/windows/win-version.h`.  The second adds logging for Windows 10 Gaming features that may negatively impact the performance of game capture, recording, or streaming.  The logging code attempts to log the status of the following features:
* Game Bar
* Game DVR
* Game DVR Background Recording
* Game Mode
The …
=> Log Windows 10 Gaming Features (Game Mode)

CI/before-script-osx.sh
Since OSX 10.10 is now the officially supported minimum OS version on Mac, update the CI script.  This is may not be necessary, strictly speaking.  As far as I know, the build scripts have still been producing Mac builds, though I don't know if those builds actually run.  Testing the build artifacts before and after this PR/commit might be informative.
Tagging @DDRBoxman and @Gol-D-Ace since they've done a lot of the work with CI.
=> CI: Update Travis script to target OSX 10.10+

plugins/linux-alsa/alsa-input.c
The "Custom" device entry was added inside the loop that runs for each device; this causes "Custom" to be added once for each device detected, or not at all if no device was detected. Moving this outside the loop (as would appear to have been the original intent, judging by the indentation) fixes this by adding the entry only after all devices have been processed.
This pull request fixes the above problem.
Steps to reproduce:
1. Using a Linux computer which has more than one ALSA audio device detected by OBS (ie. more than one `front:` PCM listed by `arecord -L`), add the "Audio Capture Device (ALSA)" source to a scene. (Alternatively, on a computer with no `front:` PCMs at all.)
2. Right click the new source, choose "Properties", and show the "Device" dropdown.
Expected results:
* OBS …
=> linux-alsa: Display the "Custom" entry once only

UI/forms/OBSBasic.ui, UI/window-basic-main.cpp
This commit addresses [Mantis Bug 993](https://obsproject.com/mantis/view.php?id=993). If no source was selected, the "Copy" context menu item was enabled, but selecting it would do nothing. This commit disables that menu item when no sources are selected.
This PR is a follow-up to PR #860 and its commits.  I've compiled and tested this PR on Windows 10 Pro 64-bit.  As always, feedback and reviews are welcome.
=> UI: Disable source copy if no sources are selected

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This PR addresses [Mantis Issue 955](https://obsproject.com/mantis/view.php?id=955).
I'm admittedly not familiar with the naming conventions for the recording/streaming start/stop/stopping functions in `UI/window-basic-main.cpp`, so I'm not sure if "ReplayBufferSave" is the most appropriate name.  I was unsure if I needed to add more functions in `UI/window-basic-main.cpp` and `UI/window-basic-main-outputs.cpp` similar to the other recording/streaming start/stop functions.
I was also unsure about the need for a function attached to OBSBasic, since saving the replay buffer doesn't seem to interact with the UI at all.  I mostly added it for the future consideration of the third item in [Mantis Issue 761](https://obsproject.com/mantis/view.php?id=761).  I suppose it could be useful if there …
=> UI: Add Frontend API function to save replay buffer

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
[Eventials](https://www.eventials.com/) is a platform to broadcast webinars and events.
Eventials is a Brazilian company and was founded in 2010.
=> rtmp-services: Add Eventials streaming platform

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Hey! Here's another ingress we're adding. We also changed the naming scheme to include more information. Let us know if it checks out on your side.
We're also interested if there's a special decision process for when a service gets the common flag - not that we think we're entitled to having it, someone in the office just wanted to know how well we'd need to do :)
If you want to check that this request comes from a Picarto staff member you can send a mail to schittler@picarto.tv
Thank you!
=> rtmp-services: Add us-west1 Picarto ingress

UI/window-projector.cpp
X11BypassWindowManagerHint  Bypass the window
manager completely. This results in a borderless window
that is not managed at all (i.e., no keyboard input unless
you call QWidget::activateWindow() manually).
This allows the Esc key to close the projector on X11
=> UI: Allow keyboard events on X11 fullscreen projector

libobs/obs-source.c
This fixes that in studio mode disabled filters are applied to sources in
the live scene.
=> libobs: Copy enabled state when duplicating filters

libobs/obs-encoder.c
This should fix "Output fails" when Rescale Output height set to 0.
=> libobs: Fix height return value condition

.travis.yml
Travis changed the default OS X build environment from Xcode7.3 to
Xcode8.3 and it seems to have broken the packaging step somehow.
Fixes the issue by reverting to Xcode7.3.
=> CI: OSX - Use Xcode7.3

CI/before-deploy-osx.sh, CI/install/osx/build_app.py
The Travis CI Xcode 8.3 image uses macOS 10.12, where some changes were made to the `productsign` utility, and Apple's documentation didn't clearly reflect this. This commit should fix Mac builds on Travis for Xcode 8.3 and clean up the job log.
This PR will require reverting ca835ddfd2c021bc72985d06b62a58c5437ff57b / 64911222e9604c1604b7ef0fc374dfbd8fabd1e4 before applying this..  The only way to tell if this patch fixes the Mac CI deploy step would be to apply the new syntax and either simulate the CI build locally or to actually make the Travis CI build run through the deploy steps (which only seem to happen on a commit to the master branch).
The changes to CI/before-deploy-osx.sh should hopefully fix the package signing step.  The changes to CI/install/osx/build_app.py are to handle a …
=> CI: Fix Mac builds on Travis CI's Xcode 8.3 image

CI/before-deploy-osx.sh, CI/install/osx/build_app.py
The Travis CI Xcode 8.3 image uses macOS 10.12, where some OS and Xcode components were changed. This commit should hopefully fix macOS deployments on Travis for Xcode 8.3.
Take two!  I'd found a few references to `security set-key-partition-list` being required for keychain/codesigning operations in macOS 10.12+.  Hopefully this fixes the issues.  If it doesn't, I have _maybe_ one or two other leads, but I really hope this gets it, or at least gets us some output from `productsign`.  If there are security concerns from listing the keychain, feel free to remove this line from `before-deploy-osx.sh`:
`security list-keychains -s build.keychain`
My revised opinion on the log spam from the "Packaging .app" step in `build_app.py` is that the call to `otool` is producing error output on stderr, …
=> CI: Fix macOS builds on Travis CI's Xcode 8.3 image

plugins/rtmp-services/data/services.json
This commit adds Mobcrush RTMP ingest to services.json.
=> rtmp-services: Add Mobcrush to services list

plugins/rtmp-services/data/services.json
* Coderwall.com seem to have shut down the livestreaming part, the domain also no longer resolves
* Livestream.com calls the service "Livestream" without the capital "S"
=> rtmp-services: Remove Coderwall / Fix Livestream service name

.travis.yml, CI/install/osx/build_app.py
Trying to clear up the log spam that started in the Xcode 8.3 image before getting this into master.
Revert a bit more of the `build_app.py` logging changes that I'd previously made and temporarily add a build for Xcode 9.1 to see if the logging works as expected there or not.
Hopefully not chasing a unicorn here.  If we need to just change the logging altogether to avoid the log spam, that's probably an option.
=> CI: Debug Python output

CI/install-dependencies-linux.sh
This reverts commit de32d89fc6ac1cc85346732f722fe74ac1cb1eca.
Fixes an issue where Linux CI builds fail because FFmpeg fails to
compile. Using FFmpeg git master in CI builds was obviously not the
smartest idea because changes in FFmpeg can break things unexpectedly.
Sorry about that.
The reason for the original commit was that OBS failed to compile
with FFmpeg 2.4. That has been fixed since.
=> Revert "CI: Linux - Install FFmpeg from source"

UI/frontend-plugins/frontend-tools/CMakeLists.txt, deps/glad/CMakeLists.txt
Some CMake checks were recently switched from UNIX to LINUX to get them to not apply to macOS/OSX. Since LINUX doesn't seem to be defined, switch these checks to UNIX AND NOT APPLE.
@juvester and I looked into this a bit, and we cannot find evidence of LINUX actually being supported.  Nonetheless, it still seems to build and run on Ubuntu without failing, but neither of us know why.  All the same, @juvester, @DDRBoxman, and I concur that these checks should probably be using `UNIX AND NOT APPLE`.
=> cmake: Correct CMake checks for LINUX

UI/data/themes/Rachni.qss
The tab bars in the Rachni theme had an issue related to an attempted
property of qproperty-drawBase: 0 in the .qss file. This, in theory,
should have worked and removed the base of the tab bar, but there is a
bug that prevents this from consistently applying, as detailed here:
https://bugreports.qt.io/browse/QTBUG-2982
This fix removes that property, and adjusts the styling of the tabs
themselves for a more consistent experience. Tabs should no longer be
cut off or displayed improperly.
In addition, this also corrects an issue with the scene/source rename
QLineEdit field displaying improperly.
=> UI: Fix minor Rachni theme bugs

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Not sure if Salt Lake City should count as US Central, unfortunately Twitch remains inconsisten with their ingest naming and did not include the region with this one.
=> rtmp-services: Add Twitch Salt Lake City ingest

libobs/media-io/video-io.c
Fixes the Rescale Output range and colorspace conversion issue.
When range and colorspace properties were missing and thus undefined:
get_ffmpeg_coeffs returns SWS_CS_ITU601
get_ffmpeg_range_type returns 0 (which is VIDEO_RANGE_PARTIAL).
Should solve mantis: https://obsproject.com/mantis/view.php?id=947
More info: https://obsproject.com/forum/threads/x264-rescale-output-over-saturating-colors.69730/
=> libobs: Fix incomplete struct in scaler call

plugins/obs-ffmpeg/obs-ffmpeg-output.c
Fixes ticket 1070.
See also
https://obsproject.com/forum/threads/ffmpeg-recording.77378/#post-330473
(related bugs).
The ffmpeg constant AVFMT_RAWPICTURE was deprecated in october 2015
and marked for removal at avformat major bump to version 58
(ffmpeg commit 34ed5c2 , oct 12, 2015).
The bump occured with commit 69b5ce6 (oct21, 2017).
The constant was subsequently removed (commit 693a11b, oct 26 2017).
It was removed from obs-studio with commit d670d7b (from me).
But the code block which was executed with this constant was not
removed, causing issues with ffmpeg output.
The commit fixes the issue for old ffmpeg builds as well as new ones.
The constant is reintegrated for avformat major version < 58 and removed
for version >= 58 (along with its accompanying code).
Thanks to J Lowe for help …
=> obs-ffmpeg: Fix ffmpeg output recording in x264

UI/window-basic-properties.cpp
When clicking the close button with unsaved changes in a source properties
dialog closeEvent and reject are called, which both call ConfirmQuit.
This fixes it by setting the acceptClicked flag correctly in ConfirmQuit
https://obsproject.com/mantis/view.php?id=1051
=> ui: Fix unsaved changes dialog showing twice

libobs/obs-source.c
The 'bool private' variable was receiving either OBS_SCENE_DUP_PRIVATE_COPY or
OBS_SCENE_DUP_COPY hence always being true.
=> libobs: Fix for int-in-bool-context-warning

UI/data/themes/Dark.qss, UI/data/themes/Default.qss, UI/data/themes/Rachni.qss, UI/volume-control.cpp, UI/volume-control.hpp, libobs/obs-audio-controls.c, libobs/obs-audio-controls.h
The following features have been added to the audio-meters:
* Stereo PPM-level meter, with 20 dB/1.7s decay rate.
* Stereo VU-level meter, with 300 ms integration time.
* Stereo Peak-hold meter, with 20 second sustain.
* Input level peak level color-dot.
* Minor-ticks for each dB.
* Major-ticks for every 5 dB.
* Meter is divided in sections at -20 dB and -9 dB.
The ballistic parameters chosen here where taken from:
* https://en.wikipedia.org/wiki/Peak_programme_meter (SMPTE RP.0155)
* https://en.wikipedia.org/wiki/VU_meter
In the rework I have removed any ballistic calculations from
libobs/obs-audio-controls.c making the calculations here a lot more
simple doing only MAX and RMS calculations for only the samples in
the current update. The actual ballistics are now done by just
the …
=> UI: Rework volume-meters, adding more information

libobs/audio-monitoring/pulse/pulseaudio-output.c, libobs/audio-monitoring/pulse/pulseaudio-wrapper.c, libobs/audio-monitoring/pulse/pulseaudio-wrapper.h
Listen for underflows on playback stream and adjust the tlength accordindly
This fixes Mantis Issue [0001076](https://obsproject.com/mantis/view.php?id=1076)
=> libobs: Fix pulseaudio monitor playback stuttering

libobs/audio-monitoring/pulse/pulseaudio-output.c, plugins/linux-pulseaudio/pulse-input.c
This pull request changes the fallback sample format for pulse-audio
to from PA_SAMPLE_S16LE to PA_SAMPLE_FLOAT32LE.
The pulseaudio plugin can handle the following sample format:
* PA_SAMPlE_U8
* PA_SAMPLE_S16LE
* PA_SAMPLE_S32LE
* PA_SAMPLE_FLOAT32LE
When an audio device advertises itself as another format, the pulseaudio-plugin
will ask pulse audio to convert to the fallback sample format.
The fallback PA_SAMPLE_S16LE is not ideal when your audio interface advertises
as PA_SAMPLE_S24LE since the conversion will lose precision.
With PA_SAMPLE_FLOAT32LE there is no precision loss and it is also equals OBS's
internal format.
=> linux-pulseaudio: Default sample format float32le

appveyor.yml
This is not necessary with the updated pre-built windows dependencies.
This reverts commit 516e9daa1ccf3f68fe456c1210d1622cee04c511.
Previous PR got merged a bit too fast ;)
=> Revert "CI: Add Python path for AppVeyor"

UI/volume-control.cpp, UI/volume-control.hpp
Added the "-60" ticker to the left most side of the meter. This also do some minor code clean-up to better fit the contributing style and clear all gcc warnings
=> UI: Add the -60 volume control marker

UI/data/themes/Dark.qss
Fixes the docked widgets tab bars from looking like poop.
Old: 
New:
=> UI: Fix tab bars for docked widgets in Dark theme

cmake/Modules/FindSwigDeps.cmake
Fixes a case of `DepsPath` not finding swig when it properly finds ffmpeg. This happens if you strictly follow the install instructions and set `DepsPath` to `win64\include`.
=> CMake: Fix FindSwigDeps search path

libobs/obs-module.c
Refines warning message to make it clear for the end-user.
Module may fail to load by different reasons.
=> libobs: Fix log message

libobs/audio-monitoring/pulse/pulseaudio-output.c, libobs/media-io/audio-io.h, plugins/linux-pulseaudio/pulse-input.c
When using more than two channels, the channel map of pulse-audio is incorrect.
Add an API for getting a speaker map based on OBS speaker layout. Then use the
speaker map when connecting to a pulse-audio device, for both source and
monitor output.
=> linux-pulseaudio: Surround speaker map

CI/install-dependencies-linux.sh, cmake/Modules/FindPythonDeps.cmake
Fixes an issue where Python libraries aren't found on Ubuntu 14.04 because CMake 2.8 only searches up to Python 3.3.
Also edits CI by enabling scripting in Linux builds.
=> cmake: Search for Python 3.4

UI/forms/OBSBasic.ui, UI/window-basic-main.cpp
This fixes a problem introduced in #1050 where the Copy option would
be grayed out when rightclicking a source above the currently selected
source. This also retains the functionality of not having the Copy option
enabled when no source is selected.
=> UI: Fix grayed out Copy option in sources context menu

cmake/Modules/FindLuajit.cmake
Out of the box, cmake doesn't include lualib.h in compiling, which causes obs-scripting-lua.c to throw a C99 warning for implicit use of luaopen_ffi().
=> cmake: Fix LuaJIT search

UI/window-basic-preview.cpp
Audio Input or Output, for instance, don't have the OBS_SOURCE_VIDEO
output flag so there is no need to draw the compositing helper bounding
boxes.
=> UI: Don't draw bounding boxes for sources without video flag

UI/forms/OBSBasic.ui
This change enables the ability to use nested docks, with the dependency of Qt5.10 or later being used to build OBS. 
Similar to the Lock UI option we could add a toggle to the menu. Not sure if this is necessary, maybe you guys have some ideas.
Example screenshots of nesting OBS:
http://img.jack0r.com/Share/obs64_2018-01-29_01-03-34.png
http://img.jack0r.com/Share/obs64_2018-01-29_00-10-24.png
=> UI: Allow nested docks

deps/obs-scripting/obs-scripting-lua.c
Tick function was smashing stack every time it was called due to arg number mismatch.
=> deps/obs-scripting: Fix tick function arg number

cmake/Modules/CopyMSVCBins.cmake
These don't appear to be necessary and prevent qt binaries from
being found on some systems (notably: mine).
=> cmake: Remove extraneous checks

UI/window-basic-main.cpp, UI/window-basic-main.hpp
SystemTray and viewMenu->Multiview available displays list was only updated on OBS init.
With this changes every possible QAction to create a fullscreen projector will show a fresh list
of available displays. The other 5 or 6 options to show the display list were already updated per action.
=> Refresh projector display list

.gitmodules
Small hotfix for the currently included version in OBS Studio. Primarily fixes outstanding issues that have been reported and can be fixed and adds the out-of-process AMF capability testing that @jp9000's fork has (with far less code modifications however).
> # 2.3.2 - Changes to the Blacklist, Out-of-Process AMF Capability testing and more
> The Blacklist introduced with 2.3.0 unfortunately had the side effect that all Windows 8 users were no longer able to use the plugin and had to downgrade. With this version, the blacklist is instead now a warning written into the log file. This is all thanks to @jp9000's work on moving the initial AMF Capability test into a different process, stopping broken drivers from crashing OBS Studio.
> 
> Not only that, but a bunch of previously unidentified …
=> enc-amf: Version 2.3.2

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
This is from aparat.com and it is to ask you to add our website to your default list.
**Aparat** is an Iranian online video sharing platform. According to Alexa's statistics, it is number one in Iran (after Google) and 130th globally. According to the latest official statistics, we have 10.5 million successful video streams, 21 million pageviews daily and 29 million of monthly unique users equal to 67.4% of all the Iranian internet users (for more information please visit this page on our website)
=> rtmp-services: Update ingest list for Aparat.com

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
we need "x264opts": "scenecut=0" otherwise we have big problems
=> rtmp-services: Update recommended parameters for Nood.tv

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-projector.cpp, UI/window-projector.hpp
This expands the original work to save fullscreen projectors by changing a bit how it works in the background. Instead of creating an array of saved projectors by type, now it stores it all on a single array accounting for its type and monitor id.
Users with saved fullscreen projectors, just on the first load after this change, will have to reopen the projectors so obs generates the new save data on the new format on exit.
I haven't squashed the refactor commit because i don't know if i should. This way we can squash later if needed.
=> Save Windowed Projectors on exit

plugins/obs-outputs/flv-mux.c
Fixes the size of the ECMA array storing onMetadata in flv.
(from 14 to 20).
Fixes ticket 1204.
=> obs-outputs/flv: Fix ECMA array size

UI/window-basic-main-profiles.cpp
When profile gets changed, will result in the audio monitoring device being reinitialized with that profiles selected device.
Fixes [https://obsproject.com/mantis/view.php?id=1216](https://obsproject.com/mantis/view.php?id=1216)
=> UI: Change monitoring device on profile change

libobs/obs-source.c
libobs: Fix crash when no destination for pasting filter
Solves https://obsproject.com/mantis/view.php?id=1220
=> libobs: Fix pasting filters crash when missing sources

UI/window-basic-main.cpp
UI: Disable paste filters unless a source is selected
Fixes the paste filters right click option to behave like copy.
See: https://obsproject.com/mantis/view.php?id=1220 
and https://github.com/obsproject/obs-studio/pull/1261
=> UI: Disable paste filters unless a source is selected

plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
After you call av_frame_alloc(), ffmpeg expects you to fill in certain
fields on the frame, depending on whether it's an audio or video frame.
obs-ffmpeg did this in the two places where it allocates video frames,
but not where it allocates audio frames.  On my system, using trunk
ffmpeg and the Opus codec, this causes OBS to crash while calling
avcodec_send_frame, ultimately because av_frame_copy fails due to
'dst->format < 0' (as 'format' stays at the default of -1), causing a
null pointer to be added to a buffer queue, which later gets
dereferenced.
Oddly, the fields in question can just be copied directly from
corresponding fields in the AVCodecContext, but I don't see any ffmpeg
API to automatically copy all relevant fields, and all the examples I've
seen do it by hand.  So this …
=> obs-ffmpeg: fill in more fields on audio frames

UI/obs-app.cpp, libobs/obs-windows.c, libobs/obs.c, libobs/obs.h
This separates the crash handler from libobs startup. The problem with starting the crash handler at all times is anything using libobs and its own signal handler immediately turns into a conflict. To avoid this, the separation given here allows us to opt-out of the crash handler. 
In particular, the recent PR for CMocka unit-tests has this issue since it catches segmentation faults and similar via a well-featured signal handler. We can now opt-out of the crash handler and let CMocka do that for us, at least while running the tests.
The Streamlabs OBS UI also has a conflict with this since they use Electron which uses Crashpad. Crashpad catches signals via an external process but it still seems to conflict. As a result, the Streamlabs OBS fork required explicitly removing the crash …
=> Separate crash handler from libobs startup

plugins/win-capture/load-graphics-offsets.c, plugins/win-capture/plugin-main.c
This is version 2 of avoiding a race condition in win-capture. Since unload of modules is called *after* global obs context is shutdown, functions that rely on obs context cannot be called during unload. We can't asynchronously call obs functions without making sure we're not shutdown. This version works around that by making sure no obs functions are called within a thread we don't know the end time of.
=> win-capture: Avoid obs functions in init_hooks

libobs/obs-internal.h, libobs/obs.h
Streamlabs uses this since they opted out of using obs_save_source and there's no other way to tell a source to save before caching its settings. The only plugin that currently uses the save feature is obs-vst. No plugin, to my knowledge, uses the load functionality. I don't see any possible side effect of exposing the functionality as well.
=> libobs: Expose source save/load signal

UI/window-basic-main-dropfiles.cpp
Patches a memory leak when a poorly matched type value is not handled by the case switch.
=> UI: Fix memory leak when drag/dropping

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp
@jp9000 I took the freedom to cherry-pick this commit from `jimtree` to a dedicated branch.
Description from original commit:
> OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED is supposed to be called
whenever the user changes the current preview scene -- it was almost
never being triggered.
=> UI: Fix OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/forms/OBSBasic.ui, UI/frontend-plugins/frontend-tools/CMakeLists.txt, UI/horizontal-scroll-area.cpp, UI/horizontal-scroll-area.hpp, UI/obs-app.cpp, UI/volume-control.cpp, UI/volume-control.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
Add toggle to change horizontal and vertical Mixer.
=> Add Vertical Mixer Toggle

libobs/media-io/media-remux.c
Currently, when a user remuxes a file, any audio tracks with custom names will have their names reset to default (e.g., Track 1, Track 2, Track 3, Track 4).  This PR enables the remux operation to copy metadata for audio and video tracks (called streams in FFmpeg), which preserves custom audio track names.  Since users are often instructed to remux files for various reasons, this PR will help users preserve track names they had set.
At first, I'd only enabled copying metadata for audio streams to preserve user-specified track names.  However, since video streams can also have similar metadata, and OBS users may try to use the remux feature on media files not directly generated by OBS, I thought we could copy all track metadata on remux.
This PR has been successfully built on the CI …
=> libobs: Copy metadata for tracks/streams when remuxing

plugins/obs-filters/color-correction-filter.c, plugins/obs-filters/compressor-filter.c, plugins/obs-filters/noise-gate-filter.c, plugins/obs-filters/scroll-filter.c, plugins/obs-filters/sharpness-filter.c
We're expecting a variable with double precision. Since we don't read
the value of these doubles with a particular precision, it can often
lead to unpredictable results where the value set isn't the one
intended due to the loss of precision from float->double conversion.
=> obs-filters: Use double-precision where viable

libobs-opengl/gl-shaderparser.c, libobs/graphics/effect-parser.c, libobs/graphics/effect-parser.h, libobs/graphics/shader-parser.c, libobs/graphics/shader-parser.h
This adds support for the "in", "out" and "inout" keywords in function signatures in both effect-parser.c and shader-parser.c. This attempts to address [Mantis issue 001239](https://obsproject.com/mantis/view.php?id=1239).
=> libobs: Handle 'in', 'out', and 'inout' keywords in shader parsers

plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
This commit fixes an issue where videos created with OBS will appear as having 1000 FPS in some media players (and FFmpeg as of the current Windows nightly).  Credit to @OsirisNL for pointing out the fix and where to apply it.
I did question whether remuxed videos should also apply this setting.  I briefly investigated this, and it seems that for 60 FPS videos, remuxing calculates a new avg_frame_rate that is within 60±0.01.  I'm not sure if this is preferable to specifying the avg_frame_rate (if the data is available), and I figure that could be left to a separate PR for later if needed.
I've built and tested this on Windows 10 64-bit.  As always, feedback, reviews, or more testing are welcomed.
=> obs-ffmpeg: Set average framerate in video stream

plugins/obs-x264/obs-x264.c
Back in an older commit, the default YUV colorspace was changed to 601
in order to ensure correct playback in video players that ignore the
contents of the H264 header.
x264's "undef" is unfortunately not what players that don't ignore the
header expect for BT.601, resulting in incorrect colors when played
back. Setting it to "bt470bg", similar to what is specified in ffmpeg
outputs, remedies this issue.
=> obs-x264: Specify x264 color space for BT.601

UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-main.hpp
When the vertical volume meter was introduced it set in the OBSBasic.ui
mixer dock definition a min width/height that was valid for both
widgets. QStackedWidget hints the minimum size as the higher w/h
of its children so this workaround is necessary.
=> UI: Fix mixer dock widget minSize being too big

UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp, libobs/obs-hotkey.c, libobs/obs-hotkey.h, libobs/obs-scene.c
Hotkey description and/or name should be reset each time its registerer's name (or similiar data) is changed.
Fixes [Hotkey of show & hide source never update description after renaming source](https://obsproject.com/mantis/view.php?id=1225).
=> libobs, UI: reset hotkey description on target rename

UI/slider-absoluteset-style.hpp, UI/volume-control.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, plugins/obs-outputs/librtmp/rtmp.c
This PR fixes ~~5~~ 6 memory leaks, mostly in UI.    
I found two other leaks but didn't manage to fix;  I leave the info here for further reference.    
(i) UI: volume-control.cpp: line 213 in VolControl()    
slider->setStyle(new SliderAbsoluteSetStyle(slider->style()));     
There seems to be an ownership issue with slider because delete slider->style() does not work.    
See this : https://stackoverflow.com/questions/37786568/qstyle-ownership?rq=1     
However being too ignorant about QT, I could not make anything out of this stackoverflow discussion.    
edit: fixed in craftwar commit (included in this PR)
(ii) UI: window-basic-main.cpp: OBSBasic( ...) line 184 installEventFilter(CreateShortcutFilter());
The CreateShortcutFilter function returns a new OBSEventFilter .    
Elsewhere …
=> Fix several mem leaks

UI/properties-view.cpp
Originally wanted to do a separate color swatch, but was stymied by the single widget reference in WidgetInfo. Using QPalette values achieves basic white/black text for contrast, though it is still possible to select a color with poor contrast.
=> Use selected color in color property label

libobs/audio-monitoring/osx/coreaudio-enum-devices.c, libobs/audio-monitoring/osx/coreaudio-output.c
The main bug fix is to show output devices in the Advanced Audio
Settings configuration, where currently on macOS it shows erroneously
input devices.
Second and third bugfixes are minor: after retrieving audio device UID
we then check for errors and return if we were not able to retrieve
the data. However cf_uid may already be allocated (since
AudioObjectGetPropertyData is OSX Api it may allocate then return
error. Checking for it being non-null and freeing if it is doesn't
hurt.
Last fix is the lowercase file not found error on coreaudio-output.c
file. Default MacOSX partitioning is case-insensitive, thus
by most developers. However, the actual dir name is AudioToolbox.
In other words, this bug is only exposed for developers compiling
on HFS case-sensitive based-storage.
Main bug fix …
=> libobs: Fix Monitoring devices showing input devices

libobs/obs-source.c, libobs/obs.h
For a plugin I'm working on I need to copy frames. Now I have a full copy of the internal function copy_frame_data in my code but it would be nice to have an exported function to use in my plugin.
The plugin I'm working on is an in memory replay buffer. The frames of one source are buffered and can be shown in a replay source.
https://obsproject.com/forum/resources/replay-source.686/
=> libobs: add obs_source_frame_copy

libobs/util/cf-lexer.c
libobs: prevent crash from unbounded copy and bfree
Restricts the range of the copy to count number of characters.
=> libobs: prevent crash from unbounded copy and bfree

UI/source-tree.cpp
Currently if you making a new group it named "Group 1" by default
instead of just "Group". This fixes it. The second group will be
named "Group 2".
In accordance with 133fa04
=> UI: If group's name exist, start it from 2

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added support for Castr.io to OBS:
- added castr.io ingests details/recommended confs to service list.
- incremented rtmp-services version.
[Castr.io RTMP Ingests](https://castr.io/ingests.json) gets updated periodically.
=> rtmp-services: Adding Castr.io ingests to service list

UI/window-basic-main-transitions.cpp
This event is fired during Add/Delete operations but was missing on
renaming a transition.
=> UI: Add missing OBS_FRONTEND_EVENT_TRANSITION_LIST_CHANGED

CI/before-deploy-osx.sh, CI/install/osx/build_app.py
This updates the default base_url used to make Sparkle Update Feed URLs (`SUFeedURL`).  The current default hasn't worked in some time, so it doesn't make sense to have it remain the default.
@DDRBoxman Can you sanity check this please?  There are other aspects for Feed URLs that probably should be looked at (non-stable `SUFeedUrl`, `OBSFeedsURL`), but I wanted to keep this simple for now.
=> CI: Update Sparkle default base_url

UI/window-basic-main.cpp
This fixes a crash in case the user selected the option to save
projectors on exit and had multiple monitors at that time. Later on,
when obs is started again if the monitor list is lower now the open
projector code will return null when trying to create the saved
projector.
Just check if the returned projector pointer is valid before trying
to restore the saved geometry.
=> UI: Fix start up crash with saved projectors

CI/install-dependencies-osx.sh, UI/frontend-plugins/frontend-tools/captions.cpp, appveyor.yml
This PR contains three commits, which can probably be squashed down to two (or one) if needed.  The first commit is for compatibility/compliance with Qt 5.11 includes.  QAction was previously implicitly included, but this is no longer done as of Qt 5.11.  The second and third commits switch AppVeyor Windows and Travis macOS builds to Qt 5.11.1, respectively.  Brew does not let us specify a patch release of Qt, so we can only specify Qt 5.11 in general.  Travis Linux builds on Ubuntu 14.04 don't have easy access to Qt 5.11.
Updating to Qt 5.11 does come with a few caveats.  First, Qt 5.11 dropped support for Microsoft Visual Studio 2013.  OBS Studio will probably not compile on VS2013 after this update.  Second, I'm also pretty sure that Qt 5.11 fully dropped support for OS X (macOS) …
=> CI: Update to Qt 5.11.1

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Piczel.TV is a streaming and art gallery website - https://piczel.tv
=> rtmp-services: Add Piczel.TV server

libobs-d3d11/d3d11-subsystem.cpp
Initialize variable (that will be used to change the resource) to zero.
An attempt to resolve the rare crashes: https://obsproject.com/mantis/view.php?id=996
=> libobs-d3d11: Initialize variable to zero

libobs/obs-win-crash-handler.c
This PR adds the bitness (32-bit/64-bit) marker for libobs to the Windows crash logs.  This is mostly a convenience for people who read logs, since you can also determine if OBS is 32-bit vs. 64-bit from other information in the log.  There should be no need to add this on macOS
I had also considered using an extra config entry in `libobs/obsconfig.h.in` like so:
```
#define OBS_BITNESS "@_lib_suffix@"
```
If there's a better way to do this, I'm all ears.  I've tested this on Windows 10 64-bit with both 32-bit and 64-bit builds by forcing an application crash.  As always, feedback and reviews are welcome.
=> libobs: Log libobs bitness in crash logs

UI/data/themes/Dark.qss
In the Dark theme, disabled UI elements had text that was too close in color to enabled UI elements. This commit switches them to use the "light" palette color instead of the "lighter" palette color.
This issue seems to have been introduced in https://github.com/obsproject/obs-studio/commit/e1ab9a0fc4ce3d442f12bdcc1c7a2cf5e1f52ae4.  I've tested this on Windows 10 64-bit.  As always, feedback and reviews are welcome.
Before:
After:
=> UI: Fix disabled items in Dark theme being too light

UI/window-basic-settings.cpp
This defect was found with Cppcheck. The code checking string pointer was originally located after the first `strcmp()` call so should the string pointer be null it would be passed as is into `strcmp()` call and yied undefined behavior. This places the check in front of `strcmp()` call.
=> UI: Check pointer before the first dereference

UI/win-update/updater/updater.cpp
This was found with Cppcheck. The assignment operator function is declared to return non-void but has return statement omitted. This yields undefined behavior.
=> UI: Add missing return statement

plugins/win-mf/mf-common.cpp
This was found with Cppcheck. `va_start()` is not paired with `va_end()` which yields undefined behavior.
=> win-mf: Add missing va_end() call

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/forms/ColorSelect.ui, UI/source-tree.cpp, UI/source-tree.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This PR adds color coding to scene items in the source tree widget, along with providing preset colors through QSS to make it customizable per theme.
=> UI: Add Color Coding to Source Tree Widget

UI/forms/OBSBasicFilters.ui, UI/window-basic-filters.cpp, UI/window-basic-filters.hpp, UI/window-basic-properties.cpp
Hides the preview window for audio sources in the properties menu and
contextually in the filters menu to save on gui space.
=> UI: Hide preview for sources and filters where possible

plugins/obs-filters/compressor-filter.c
obs_audio_data* sent to compressor_filter_audio had audio->frames == 0.
The analyze_envelope was trying to access an array at index -1 in result
of that. Just return if no samples are provided.
backtrace:
```Thread 13 "threaded-ml" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa0c09700 (LWP 23257)]
0x00007fffa3f46cf4 in analyze_envelope (cd=0x5555564c80e0, samples=0x55555ace2ab8, num_samples=0) at 
/home/linus/Projects/c/obs-studio/plugins/obs-filters/compressor-filter.c:338
338		cd->envelope = cd->envelope_buf[num_samples - 1];
(gdb) bt full
#0  0x00007fffa3f46cf4 in analyze_envelope (cd=0x5555564c80e0, samples=0x55555ace2ab8, num_samples=0) at 
/home/linus/Projects/c/obs-studio/plugins/obs-filters/compressor-filter.c:338
attack_gain = 0.99622786
release_gain = …
```
=> obs-filters: Fix segfault in Compressor Filter

libobs-opengl/gl-x11.c
Expands X error handler with more details and prevent a segfault on invalied returned window geometry
=> Improve X error handling

.travis.yml, CI/before-script-osx.sh, CI/install-dependencies-osx.sh, CI/util/build-package-deps-osx.sh
This PR does four things in three commits:
1. Update Travis CI builds for macOS to use the Xcode 9.4 image (macOS 10.13 w/ Xcode 9.4).
2. Update the Travis CI scripts to actually target macOS 10.11 as the minimum supported macOS version.
3. Update the build script that downloads the packages the macOS dependencies to target updated URLs for those dependencies.
4. Update the build script that downloads and packages the macOS dependencies to the latest stable versions of those dependencies.
The first change should be fairly safe to do.  Travis CI is [making the Xcode 9.4 image their default macOS build image on July 31, 2018](https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce).
The second change should also be fairly safe to do.  The OBS website has stated that current releases …
=> Update macOS CI build image, target, and deps

UI/window-basic-main.hpp
QNetworkReply was added here in commit 5ba8b09c9c0ee3bd4cca7860e5892ee60d1f6cf6. Qt5Network was replaced in commits 13bed1a448e3726819778e5759bdf456556b6bf9 and 39d1cda4e9b276f1b0770027e211aec0d9ecb927, but this one line referring to QNetworkReply remained. Let's finally remove it.
This isn't a significant change.  Just removing a single unnecessary line.
Compiled and tested on Windows 10 64-bit.  As always, feedback and reviews are welcome.
=> UI: Remove QNetworkReply from window-basic-main.hpp

UI/obs-app.cpp
This was found with Cppcheck. `va_copy()` is not paired with `va_end()` which yields undefined behavior.
=> UI: Add missing va_end() call

plugins/win-capture/cursor-capture.c
Re-fetch texture when cursor's either width or height changed.
When the cursor icon changed and the new one has the same width or height,
it may not recreate the texture and thus cause memory access violation.
=> win-capture: Avoid tex size mismatch for cursor

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss
This PR has two commits (feel free to squash, I kept them separate because they're for two different theme files).
The first is updates to the Rachni theme to fix a few issues with the new SourceTree widget, and some minor tweaks to colors. This also includes some white-space fixes that were introduced in 8b6d437
The second is an update to the link color used with the dark theme, as the default blue was essentially unreadable.
=> UI: Theme fixes

plugins/win-capture/game-capture.c
When changing size of a game-capture scene item in preview window, 
if the capture target window closed, it may crash.
In stop_capture function, it first release the global_hook_info member,
and then set the active member to false.
But while in game_capture_width/height function, it first checks the
active member to decide if get the value of cx from global_hook_info.
It will causes the game_capture_width function to read cx member from
a global_hook_info structure with nullptr value, thus crashes the obs.
game_capture_width/height function will be called in UI thread while
resizing scene item while the stop_capture called in a different thread
(graphic thread), so stop_capture may be executing concurrently.
I see that game_capture::cx/cy will be updated when the target resized,
so I …
=> win-capture: Avoid segfault when retrieve size

UI/obs-app.cpp
This commit explicitly puts "32-bit" in the title bar and OBS log for 32-bit versions of OBS. It also changes "64bit" to "64-bit" to match the string used for Windows version info.
This is mostly a convenience for people providing support so they don't have to remember that "(windows)" in the OBS version string means that the OBS build is 32-bit.
=> UI: Make OBS bitness more specific in title bar and log

plugins/obs-qsv11/QSV_Encoder_Internal.cpp
This was found with Cppcheck. One of member variables of "raw pointer" type is left uninitialized in the class constructor.
=> obs-qsv11: Initialize member variable

CMakeLists.txt
This policy was introduced in CMake version 3.11.
The FindOpenGL module provides an OpenGL::GL target and an
OPENGL_LIBRARIES variable for projects to use for legacy GL interfaces.
When both a legacy GL library (e.g. libGL.so) and GLVND libraries for
OpenGL and GLX (e.g. libOpenGL.so and libGLX.so) are available, the
module must choose between them. It documents an OpenGL_GL_PREFERENCE
variable that can be used to specify an explicit preference. When no
such preference is set, the module must choose a default preference.
The default behavior is to default to legacy (OLD) and is deprecated.
https://cmake.org/cmake/help/v3.11/policy/CMP0072.html
https://github.com/NVIDIA/libglvnd
=> cmake: Prevent policy CMP0072 warning

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Livestreaming now available on DTube
See announcement: https://steemit.com/dtube/@heimindanger/dtube-0-8-the-grand-upgrade-is-finally-here-dtv-dtalk-vip-system-etc
=> rtmp-services: Add DTube

CI/install-dependencies-osx.sh
Pull Request #1420 changed the URL for the macOS deps package. When it did that, it also changed the URL from HTTPS to HTTP. Since this asset is available over HTTPS, we should use that.
The certificate when using HTTPS is valid, and CI successfully compiled with this change.
=> CI: Use HTTPS for downloading macOS deps package

UI/data/locale/en-US.ini, UI/window-basic-settings.cpp
The ability to use multiple separate QSV encoders was added in Pull Request #1341 (commit 3a08e858a68aeecaf6499973b55988db5a903ae5). This error message was left in place, so let's remove it now.
I've compiled and tested this on Windows 10 64-bit.  As always, feedback or reviews are appreciated.
=> UI: Remove warning when using separate QSV encoders

libobs/obs-module.c
Correct "regsiter" to "register" in a couple function names. These functions are currently unused. Let's correct these names before they start getting used.
=> libobs: Fix typo in function names

UI/window-basic-main.cpp
This is a weird one. On KDE just clicking in the options or right
clicking the empty space areas of the mixer dock would trigger a layout
change.
This fixes mantis #1256
=> UI: Fix mixer context menu toggling layout on kde

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Periscope's recommended ingest settings were recently updated:
> Input Key Settings (make sure to input these accurately)
>
>    - Video bitrate & codec: 2500 kbps (recommended), 4000 kbps (max), H.264
>    - Audio bitrate & codec: 128 kbps AAC-LC 
>    - Framerate: 30 fps 
>    - Resolution: 1280 x 720
>    - Keyframe interval: Every 3 seconds (OBS) or keyframe every 90 frames (Wirecast)
Source: https://help.pscp.tv/customer/en/portal/articles/2600293-what-is-periscope-producer
=> rtmp-services: update Periscope settings

UI/window-projector.cpp
This was triggered by openning a fullscreen projector and trying to alt
tab. The projector was still on top but the first click on a KDE system
was returning a NULL activeWindow.
=> UI: Fix a rare multiview crash when clicked

UI/window-projector.cpp
This fixes mantis issue # [1279](https://obsproject.com/mantis/view.php?id=1279)
=> UI: Use AlwaysOnTop option for windowed projectors

libobs-opengl/gl-helpers.c, libobs-opengl/gl-helpers.h, libobs-opengl/gl-stagesurf.c, libobs-opengl/gl-subsystem.c, libobs-opengl/gl-subsystem.h, libobs-opengl/gl-texture2d.c, libobs-opengl/gl-texturecube.c
The previous model stored a new FBO per texture width/height/format on
a array in the device struct. This allocated memory was only released
on gs_device_destroy (obs exit).
The new approach stores a FBO on gs_texture and the its info is
destroyed once the texture is deleted.
=> libobs-opengl: Store FBOs per texture instead of per device

UI/source-tree.cpp, UI/source-tree.hpp, UI/window-basic-main.cpp
This creates a hidden QAction in sceneDocks and sourceDocks so we can
assign a shortcut to perform the renaming action.
This finishes the work on PR #1212 as groupping was added to SourceTree
=> UI: Add rename scene/source shortcut

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
* Hitbox/Smashcast NBG/VIE servers are offline
* Dailymotion seems to have removed public live streaming
* Watchpeoplecode removed their live streaming functionality
* All gameplank servers are unavailable
* Afreeca KR en-ko server is unavailable
* Afreeca TW servers are unavailable
* Afreeca JP servers are unavailable
=> rtmp-services: Remove offline/unavailable servers/services

plugins/win-capture/game-capture.c
Occasionally users accidentally select the following applications built
into Windows 10 using game capture, which cannot be captured.
This PR simply hides them from the game capture list.
The latter takes up 6 entries in the dropdown.
LockApp.exe - the lock screen which doesn't run in user space
WindowsInternal.ComposableShell.Experiences.TextInput.InputApp
=> UI: Blacklist LockApp and Text Input from Game Capture

plugins/win-ivcam/seg_library/SegServerImpl.cpp, plugins/win-ivcam/seg_library/SegServerImpl.h
This was found with Cppcheck. Copy constructor and assignment operator do nothing and are declared private and are not actually used anywhere. It's clearer and more reliable to just prohibit them.
=> win-ivcam: Remove and prohibit useless member functions

CMakeLists.txt, libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
There isn't any on Windows (maybe MSVC just doesn't allow/support it) but on Linux there were only 1 case of VLA and we should avoid it if possible.
Links:
lkml [here](https://lore.kernel.org/lkml/CA+55aFzCG-zNmZwX4A2FQpadafLfEzK6CC=qPXydAacU1RqZWA@mail.gmail.com/T/#u)
linux git [changes](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=02361bc77888)
linux securiy summit [pages 6, 7 and 8](https://outflux.net/slides/2018/lss/danger.pdf)
=> Add compiler checks to avoid VLA

UI/forms/OBSBasic.ui, UI/window-basic-main.cpp, UI/window-basic-stats.cpp, UI/window-basic-stats.hpp
Adds a new dock out of the stats widget.
=> UI: Make stats dockable

plugins/image-source/image-source.c
Add psd (photoshop) to file filter and more generally enable display of all files (\*.\*).
=> image-source: Add psd and *.* to file filter.

plugins/win-capture/game-capture.c
Distinguish in the log that this is for shared-mem/mutli-adapter not anti-cheat.
Mostly so I don't have to open OBS and check to remember which one this means.
=> [win-capture] Modify log for sharedmem

UI/obs-app.cpp, libobs/obs.c, libobs/obs.h
This paves the way for plugins to have access to the argc/argv used when
spawning OBS. Notably, this will allow a patch to obs-browser that passes
through command line arguments on macOS to CEF.
=> libobs/UI: Allow Access To argc/argv

deps/obs-scripting/CMakeLists.txt
obs-scripting CMakeList.txt expects SWIG, Python3 or Luajit to enable
scripting so in case of not finding just return and don't abort
the configuration
Fix this [error](https://gist.github.com/admshao/bbcb1e12b04ec3a0ec9b51fc03da9434)
=> cmake: Fix an error when SWIG isn't found

UI/data/locale/en-US.ini, UI/window-basic-settings.cpp
This commit adds a search bar to the top of the hotkeys settings menu,
with it set to look for matches anywhere in the string label for that
hotkey.
It currently has issues when clearing a search, since setVisible(true)
or show() on a widget will recompute the styles, making it a slow
operation. There doesn't seem to be a way around this without
implementing pagination or some other means of displaying the data
first.
=> UI: Add Search to Hotkeys settings menu

docs/sphinx/reference-libobs-graphics-effects.rst, libobs-d3d11/d3d11-shader.cpp, libobs/graphics/effect-parser.c, libobs/graphics/effect-parser.h, libobs/graphics/effect.c, libobs/graphics/effect.h, libobs/graphics/graphics.h
Note: Dependent on #1319
Gives the ability to retrieve param annotations. Blocks wrapped in <>
following a parameter.
For example:
```c
float slider < float max_value = 10.0; float min_value = 0.0; >;
```
These blocks are not for shading purposes but to help describe the shader's gui
as in the example above.
Adds graphics api functions for retrieving annotations and their default values:
```c
gs_eparam_t *gs_param_get_annotation_by_idx(const gs_eparam_t *param,
size_t annotation);
gs_eparam_t *gs_param_get_annotation_by_name(const gs_eparam_t *param,
const char *name);
void *gs_effect_get_val(gs_eparam_t *param);
void *gs_effect_get_default_val(gs_eparam_t *param);
```
Example usage:
[shader-filter](https://github.com/andersama/obs-studio/tree/shader-filter-eval)
=> libobs: Add HLSL annotation parsing

libobs/graphics/image-file.h
Wraps image-file.h in extern "C" like rest of libobs api.
Prevents unresolved external errors when using in c++.
=> libobs: Export image-file to c

UI/data/themes/Dark.qss
Newer themes like Acri and Rachni have consistent sizing and padding on buttons and inputs. This brings the default Dark theme in line with them.
Changes in this PR:
* Added Spacing between Hotkey buttons 
* Aligned height of inputs with hotkey buttons
* aligned left inner edge of text inputs and rounding with other inputs (like dropdowns)
* ~~Aligned dock headings with dock contents~~ Removed per Jim's request
* Coloured the Mixer with the same background as Scenes/Sources
* Added a hover color for dropdown menus similar to buttons
* Removed gradient behind the scrollbar
Hotkey inputs & buttons:
Input alignment:
Mixer background:
Dropdown hover:
Scrollbar:
=> UI: Dark theme padding and alignment fixes

plugins/obs-qsv11/QSV_Encoder.cpp, plugins/obs-qsv11/QSV_Encoder.h, plugins/obs-qsv11/QSV_Encoder_Internal.cpp, plugins/obs-qsv11/obs-qsv11.c
- Allow user to change # of B frames. New Default -> 1
- Allow user to enable Content Adaptive Quantization (MBBRC) if CPU is Skylake or newer.
- Allow user to choose LA_CBR as a rate control.
- LA depth: New Default -> 15, only when LA rate control is used.
=> obs-qsv: Expose additional QSV encoder settings through GUI

docs/sphinx/reference-scenes.rst
The current docs don't mention obs_sceneitem_get_id, which makes obs_scene_find_sceneitem_by_id confusing for people reading the docs unless they look at the source code.
=> docs/sphinx: Add missing obs_sceneitem_get_id info

UI/frontend-plugins/frontend-tools/captions-mssapi-stream.cpp
This was found with Cppcheck. Code uses `sizeof()` applied to a pointer which yields `sizeof(void*)`. Actual length of string should be used instead.
=> UI: Fix array length computation

libobs/util/threading-posix.c
The pthread_setname_np manpage states:
The thread name is a meaningful C language string, whose length is restricted to 16 characters, including the terminating null byte ('\0').
Have not verified whether this is also the case for other POSIX based systems, so am making this change for Linux only.
=> libobs: Truncate thread names on Linux

plugins/linux-capture/xcompcap-main.cpp
Previously toggled swapRedBlue every update regardless of settings being set, which resulted in
moving or resizing of windows causing undesired color-swapping behavior. Also now use more direct
method of comparing visualIDs without type-casting and base the glxpixmap attributes on texture
format being used rather than the bit-depth of the window.
=> linux-capture: Fix repeated color-swapping and improve robustness further

.gitmodules
This PR corrects the submodule address to point to the obsproject copy instead of my fork of it. Additionally it updates the plugin to Version 2.5.0, changelog follows (important changes in bold):
* **Updated AMF to 1.4.9.0.**
* Updated english locale text for Pre-Pass to include encoding cost.
* Fixed various erroneous usages of short codes for printf in log text.
* Added support for Git commit detection to CMake.
* Added support for clang-format.
* Added support for CppCheck to CMake. (Thanks to Streamlabs for this one)
=> enc-amf: Update to 2.5.0 and update repository address

UI/data/locale/en-US.ini
The text for resizing the output based on source is inaccurate
because base and canvas are the same thing.
=> UI: Change resize output text

.gitmodules
See #1498 for patch notes, this simply restores compatibility with cmake 3.7 and earlier.
=> enc-amf: Update to 2.5.0.1 and update repository address

libobs/obs-windows.c
Correctly initialize the data array. Calling `memset(data, 0, 1024)` only initializes the first 1024 bytes of the array. Since `sizeof(wchar_t)` is 2 bytes, then `sizeof(data)` is 2048 bytes long.
Also, `RegQueryValueExW` expects a byte pointer and was only getting half the bytes of the buffer since `size` was also being initialized to 1024.
=> libobs: memset() the correct buff size

plugins/decklink/decklink-device-instance.hpp
This was found with Cppcheck. One of member variables of "raw pointer" type is left uninitialized in the class constructor.
=> decklink: Initialize member variable

UI/data/themes/Dark.qss
Fixes an issue when it's hard to perform drag-by-mouse move of the
scrollbar while handle is at corner and has minimum size.
Info: the handle minimum size styled as 20px, while add/sub-line is
14px, thus only 6px left for mouse drag when handle resides at corner.
While handle styled to cover whole bar, including subcontrol elements,
it is better to remove invisible subcontrols completely.
=> UI: Remove scrollbar line controls for Dark theme

README.rst
This PR adds CI status badges to the README file for the master branch builds on Travis and AppVeyor.  These badges shows the current build status (success or failure) on the CI services of the master branch.
=> Add status badges to README

plugins/obs-libfdk/obs-libfdk.c
fdk-aac v2.0.0 (aacenc 4.0.0) changes the AACENC_InfoStruct:
the encoderDelay parameter is replaced by two, nDelay and
nDelayCore. This patch checks the lib version and adjusts the parameter
accordingly.
=> obs-libfdk: Compatibility fix for new API

libobs/obs-output.c
Track 1 offset is reset but not the offset for other tracks.
This caused sync issues in between tracks (with track 1 and others).
(bug found by EposVox)
=> libobs: Fix audio offset not reset for all tracks

plugins/win-mf/mf-h264-encoder.cpp
This was found with Cppcheck. A member variable of built-in type is left uninitialized in the class constructor.
=> win-mf: Initialize member variable

plugins/decklink/decklink-device.hpp
Another attempt to compile in VS 2013, without additional obs plugins, warns me that type _int32_t_ was unknown.
=> decklink: Add declaration file for integer types

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
For cleaning purposes I wrote a script that attempts to connect to all servers within the services file.
Should the connection be rejected or not possible for any other reason during several runs of the script over a period of time, these servers (or services in case this applies to all listed servers) will be considered "dead" and shall be removed.
In the case of the services removed in this PR they are either dead (DTube) or instruct users to use other server urls that will be given out on demand in their web interface (StageTen, etc.). The server urls listed within OBS do no longer function.
=> rtmp-services: Remove dead servers/services

UI/forms/OBSBasicSettings.ui
Commit 2fedcab9872 changed the default index for widget "advOutTabs"
in OBSBasicSettings.ui; revert to index 0 (stream tab).
=> UI: Revert default tab in Settings > Output: Advanced tab to Stream tab

libobs/util/circlebuf.h
The only time circlebuf_pop_back is used in obs self is with data set to NULL so this change should not break anything.
=> libobs: Fix circlebuf_pop_back returning front

libobs/graphics/effect-parser.c
Checks that the token is not null while looping. Logs errors when pixel
or vertex shader are missing.
=> libobs: Fix crash when pixel or vertex shader are missing

libobs/util/utf8.c
I think this is typo, "insize" should be "i_insize".
Or line 48 will read over 3 bytes.
`ret = MultiByteToWideChar(CP_UTF8, 0, in, i_insize, out, (int)outsize);`
=> libobs: Fix utf-8 bom is not properly skipped

UI/display-helpers.hpp, UI/window-basic-preview.cpp
OBS scales the preview window incorrectly if the scaling is not set to an integer value. For example, I set QT_SCALE_FACTOR to 1.2, the controls and fonts are scaled as intended but the preview is not because devicePixelRatio() returns an integer (1 in this case). As a result, part of the main window is not invalidated and not redrawn.
This could've happened after refactoring or something. `QWindow::devicePixelRatio()` actually returns double but in these cases the function called is `QPaintDevice::devicePixelRatio()` (inherited from QMainWindow) which returns int. Looks like a bad design decision on the Qt side tbh.
=> UI: Support fractional scaling

CMakeLists.txt, deps/media-playback/CMakeLists.txt, libobs/CMakeLists.txt
As currently used and configured, x86 intrinsics (defined in  `xmmintrin` and `emmintrin` etc) prevent building on PowerPC64 LE systems. Defining the flag `NO_WARN_X86_INTRINSICS` permits the GCC 8+ provided compatibility shims to supply suitable implementations for _MMX_/_(SSE/2)_ as used in OBS. This is in preparation for a direct port to AltiVec/native vector acceleration.
Specifically this is to enable livestreaming on Raptor Computing Systems Talos 2 workstation systems (fully open source firmware/software fully documented OpenPOWER PPC64 systems) - https://www.raptorcs.com/content/base/products.html
=> Build on PPC64LE using x86 Intrinsic Compat Shims

libobs/obs-windows.c
It seems the registry key for Game Mode was changed in a recent Windows 10 update, this fixes the Game Mode detection in the log.
=> libobs: Fix Windows Game Mode detection on newer Windows 10 versions

libobs/obs.c, libobs/obs.h
obs_set_cmdline_args copies the arguments passed to it. This means that
the array passed will never require it to be modified.
=> libobs: Allow const argument in obs_set_cmdline_args

UI/window-basic-main-scene-collections.cpp
If someone were to make changes to a scene collection and go to export, the resulting export would not contain their changes, since the export just copies off of disk. This change makes sure that the scene collection is up to date first, before performing the export.
=> UI: Save scene collection before export

AUTHORS
This was generated using this script
`git shortlog -ns jp9000/master | awk '{$1=""; print}' | sed -e 's/^.//'`
And manually editing the AUTHORS file later.
Should we also add email address?
This should ideally be re-run and updated prior to the release
=> Authors: Update Contributors list

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-stats.cpp, UI/window-basic-stats.hpp
Fixes leaks with:
- projector menus (in source, main preview, scenes),
- background color menu
- deinterlace menu,
- scene transition override,
- filter shortcuts (in Main and stats).
There are more leaks with filter shortcuts (see https://github.com/obsproject/obs-studio/pull/1366 ) but I didn't fix them out of laziness ...
=> UI: Fix a series of mem leaks

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Twitch Oslo ingest is still omitted as it currently still points to
the Stockholm domain.
=> rtmp-services: Update Twitch and Smashcast ingests

UI/window-basic-auto-config-test.cpp
Uses the "Auto" server automatically for Restream rather than doing a region-based test on multiple servers.
=> UI: Add support for Restream "Auto" server in auto-config

UI/window-projector.cpp
Scenes have a transparent background by default. In the multiview, this is handled correctly for individual scenes and the preview output, but not for the program output. This PR aims to fix this behaviour.
Current behaviour:
Expected behaviour:
=> UI: add a default black background to the PGM output of the multiview

libobs/util/platform-nix.c
This was found with Cppcheck. When reading into `unsigned long` the proper type specifier if `%lu`, not `%ld`
=> libobs: Fix scanf type specifiers

plugins/win-capture/duplicator-monitor-capture.c, plugins/win-capture/monitor-capture.c
Operating systems don't report monitors from 0, so OBS shouldn't either. This avoids user confusion when display capture doesn't work, or when the user uses "Identify" systems which overlay monitor indexes.
This does not change monitor count internally.
Let me know if I've missed any display capture plugins, I modified the two I could find. Tested on Windows 10.
=> win-capture: Start user-facing monitor count at 1

plugins/obs-filters/expander-filter.c
This was found in build logs. The change is a very low impact cleanup.
=> obs-filters: Fix unused parameter warnings

plugins/obs-ffmpeg/obs-ffmpeg-output.c
Fixes rare crash with custom output where audio encoder may be disabled.
Credits to @SuslikV for discovering this.
=> obs-ffmpeg: Fix crash when audio not configured

plugins/obs-ffmpeg/jim-nvenc.c
Right now selecting "CQP" in OBS will set Nvenc to what Nvidia calls "Target Quality" mode. This means VBR with a constant quality target instead of actual constant QP.
There also appears to be an issue wit `maxBitrate` set to 0 that limits bitrate to 128 Mbps in Target Quality mode. When properly setting CQP mode this does not happen.
This commit changes jim-nvenc so that the mode is properly set to `constQP` with the parameters set in identical fashion to what nvenc in ffmpeg would do. The result works as expected. I also removed setting `maxBitRate` and `averageBitRate` as these parameters don't do anything in CQP mode and combined lossless/cqp into a single if-clause.
=> obs-ffmpeg: Fix constant QP mode in new NVENC

UI/data/locale/en-US.ini
Release 22.0.2: - Removed the "Beta" warning from the Auto-Configuration tool
The texts that the Auto-Configuration tool is in beta remained.
=> UI: Remove unused "Beta" texts

UI/window-remux.cpp
If a file that is added to the Remux dialog has a `.` in it's filename, it's target path / target filename is being cut from that point onwards (say `example.video.mkv` => `example.mkv`)
This happens due to the usage of `QFileInfo::baseName()` instead of `QFileInfo::completeBaseName()`.
This is already correctly used in [`UI/window-basic-main.cpp`](https://github.com/obsproject/obs-studio/blob/01c78bffc5f19a270905d08cb0252a76b45ebef7/UI/window-basic-main.cpp#L5184).
This PR fixes up `UI/window-remux.cpp` to also use `completeBaseName()`.
=> UI: Fix wrong filename building for Remux dialog

UI/frontend-plugins/frontend-tools/scripts.cpp
Reloading any script will have a memory leak. Properties are received from a get function call, but not destroyed. This change makes sure they get destroyed.
=> frontend-tools: Fix memory leak when reloading scripts

UI/forms/OBSBasicSettings.ui
When Settings fields have been added or moved, their tabbing order hasn't been updated to match. I've gone through and ensured the tab order makes sense throughout the entire flow.
Note that dynamic pages like Hotkeys don't control tabbing via this section of code.
=> UI: Update tab stop order in Settings

plugins/win-dshow/win-dshow.cpp
MatcherClosestFrameRateSelector updates best_match as a side effect of
visiting every VideoInfo instance, but CapsMatch uses std::any_of,
which will stop iterating prematurely on first match. This means that
the highest FPS is not selected.
This change switches to a for loop that doesn't exit early.
=> win-dshow: Fix "Highest FPS" algorithm

UI/window-basic-main.cpp
Fixes an issue when Start Replay Button stays at checked state if stop
signal generated (hotkey event for example) instead of mouse click.
Mantis: https://obsproject.com/mantis/view.php?id=1343
=> UI: Reset replay buffer button on "stop" signal

libobs/obs.c
Previously only sources would receive a load signal, but sources and filters would receive a save signal. This meant that filters that had a save signal to store something on disk would never receive a load signal to load it from disk.
With this both sources and filters will now receive save and load signals, allowing both to work the same way.
=> libobs: Tell filters that we want to load

libobs/media-io/audio-resampler-ffmpeg.c
Fixes Mantis issue 960.
A mono source is currently upmixed by swresampler in the following way:
- for stereo output, FL=FR=input/sqrt(2)
- for other speaker layouts of the outputs, FC=input, other channels
are zeroed.
In the case of stereo output, this leads to a 3dB level decrease which
users have issue with [1].
The obvious fix of adding a 3dB gain is reported to be adding distortions
on some setups [2].
Instead this commits changes the resampler options for mono input.
Note that the "Downmix to Mono" does not fix this upmix problem, since
it just makes all output channels identical by summing all input channels
and normalizing (by dividing by the number of output channels). This last
normalization step results in a level reduction for a mono input.
[1] …
=> libobs/media-io: Fix mono upmix

.travis.yml
The IRC bot's webhook functionality hasn't worked in some time since
switching host machines. The Discord bot can handle build result changes
itself and having all results will useful for some future expansions
(e.g. tracking latest mac nightly build).
(Also removes commented-out IRC section.)
=> CI: Always send travis webhook and remove IRC sections

.travis.yml
Trusty is reaching EOL in April 2019.
=> CI: Build on Ubuntu Xenial for Travis CI

plugins/obs-ffmpeg/data/locale/en-US.ini, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
(Variation on #1650 with it being a property, enabled by default).
According to nvidia documentation using b-frames as reference results in a slight quality improvement with no/negligible performance impact and is recommended to be enabled when using multiple b-frames.
Because of nvidia's recommendations I made this enabled by default but kept it configurable in case it causes issues.
=> obs-ffmpeg: Add option to use b-frames as reference

CMakeLists.txt, UI/obs.rc.in
This defines the main OBS Windows executable with a resource file, including a version number accessible externally and a File
description which appears in Windows Task Manager.
This is the first version, just looking to get feedback on what each of the fields should be populated with.
Originally I was going to put the cmakelist code within UI, but felt it could actually be used by other aspects (like libobs version?) so it's better if it's at the core.
Fields are defined here https://docs.microsoft.com/en-us/windows/desktop/menurc/stringfileinfo-block
=> UI: Automatically generate Windows file description

cmake/Modules/FindLibVLC.cmake
1. Changed `pkg-config` module name to `libvlc`
2.~~On UNIX, reference symlink `libvlc.so`, rather than
`libvlc.so.5`, which can change with `libvlc` version~~
Tested with VLC 3 installed via `libvlc-dev`, and also with VLC 4 with source install.
=> cmake: Fix pkg-config handling of libvlc

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-settings.cpp
Originally added for completeness but wasn't actually implemented
correctly. Can be added back later if desired.
=> UI: Remove Area downscale filter option

libobs/obs-properties.c
This function incorrectly checked for an Integer type instead of a Float type, causing it to do nothing.
=> libobs: Fix obs_property_float_set_limits

.gitignore, UI/obs.rc
Second time's the charm 😉 
This file gets automatically generated from obs.rc.in by CMake and
could get accidentally committed.
The info still gets generated correctly with this change.
=> UI: Remove and ignore obs.rc

libobs/media-io/video-io.c
This causes warnings in build logs. This earlier change https://github.com/obsproject/obs-studio/commit/36ffa65b68b0a0e625d3aed717323e7794b73b0e altered the types of variables but didn't change the output specifiers. The current code yields undefined behavior.
=> libobs: Fix output type specifiers

plugins/image-source/obs-slideshow.c
With the dynamic loading of images being reverted, the fix for
this separate issue was also reverted.
=> image-source: Re-add fix of repeating images

plugins/obs-filters/data/sharpness.effect
Not sure why, but there's a dead uniform and interpolant in the
sharpness effect. This change removes them.
=> libobs: Remove dead code in sharpness effect

libobs/data/area.effect
Remove const qualifiers because they are syntax errors for GLSL when
used like in C.
=> libobs: Fix Area scale filter for GLSL

plugins/obs-filters/data/color_key_filter.effect
SampleYUVToRGB() is no longer used after the previous DrawMatrix purge.
=> obs-filters: Remove unused function in shader

libobs-opengl/gl-windows.c, libobs/graphics/shader-parser.c, libobs/obs.c
max_anisotropy is initialized to zero, but the minimum value is 1.
=> libobs: Fix invalid max_anisotropy value

UI/obs-app.cpp
This fixes a seg fault that would happen when launching OBS from the
terminal and then hitting ctrl-c.
=> UI: Fix crash when using ctrl-c in Linux terminal

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, libobs/obs-hotkey.c, libobs/obs-hotkey.h, libobs/obs-nix.c
This also modifies libobs.
This only happened on Linux.
Fixes https://obsproject.com/mantis/view.php?id=1018
=> UI: Fix issue where space/esc hotkeys would be blank

UI/auth-restream.cpp
While the default sizes for these widgets is fine, the minimum is too large - it makes them feel unwieldy. This updates the minimum size of the chat dock to the same as Twitch Chat, and the stream info to the same as Twitch Stats dock.
=> UI: Allow smaller Restream docks

libobs/data/area.effect, libobs/obs-scene.c
I just noticed that scene items with Area scaling were invisible in the Preview pane of Studio Mode when using OpenGL. It appears there's a projection flip that is applied in some situations, and when it is, it breaks the shader math. This PR fixes the math for GLSL (with a tiny redundancy penalty to HLSL), and cleans up some unnecessary code along the way.
=> libobs: Fix and simplify Area scale filter

UI/auth-oauth.cpp
Previously enabling and disabling bandwidth testing in a certain order
lead to the parameter being included in the stream key that is saved to
disk, making it impossible to disable the bandwidth test later on.
By doing this properly and using string concatenation instead of
modifying (appending to) the key_ value this will no longer happen.
=> UI: Fix bandwidth test flag being saved to stream key

UI/data/themes/Rachni.qss
Negative values in padding may lead to unpredictable behavior
(example: https://github.com/obsproject/obs-studio/pull/1610#issuecomment-455804938)
This patch emulates similar shift of the text that was main goal by the theme creator, so it doesn't changes appearance of the theme itself.
=> UI: Fix incorrect padding usage in Rachni theme

UI/window-basic-stats.cpp, UI/window-basic-stats.hpp
When the stats dock is hidden, the QTimer is still updating it, causing
unnecessary CPU usage.
=> UI: Don't update stats dock if hidden

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp
All UI elements are accessible through the obs frontend api via
obs_frontend_api_get_main_window, except for the tray icon and its
elements. This commit adds an obs_frontend_api_get_system_tray function
which returns the pointer to the QSystemTrayIcon cast to void*.
=> obs-frontend-api: Access system tray icon from API

UI/window-basic-about.cpp
This fixes an issue where the wrong version would
be shown in the about dialog when it is a rc release.
=> UI: Show correct version in about dialog

UI/obs-app.cpp
Without this, we strcmp a null pointer if no theme is set in the
configuration file.
=> UI: Add null check for rename of default theme

deps/media-playback/media-playback/closest-format.h, deps/media-playback/media-playback/media.c, libobs/data/area.effect, libobs/data/bicubic_scale.effect, libobs/data/bilinear_lowres_scale.effect, libobs/data/default.effect, libobs/data/deinterlace_base.effect, libobs/data/deinterlace_blend.effect, libobs/data/deinterlace_blend_2x.effect, libobs/data/deinterlace_discard.effect, libobs/data/deinterlace_discard_2x.effect, libobs/data/deinterlace_linear.effect, libobs/data/deinterlace_linear_2x.effect, libobs/data/deinterlace_yadif.effect, libobs/data/deinterlace_yadif_2x.effect, libobs/data/format_conversion.effect, libobs/data/lanczos_scale.effect, libobs/data/repeat.effect, libobs/obs-internal.h, libobs/obs-source-deinterlace.c, libobs/obs-source.c
These changes move YUV -> RGB from later shaders into the earlier format conversion shaders. I444 was not covered, and format conversion had to be implemented. This paves the way for changes like #1713 to simplify and speed up by good amounts. See commit descriptions for details.
I have tested all code diffs at least once in some fashion, so I feel decent about this change.
=> Simplify YUV conversion, and direct YUV444P support

UI/window-projector.cpp
I considered making this an option, but I decided against it because
I felt it wasn't necessary and would make the settings more complex.
Opinions are welcome.
=> UI: Don't hide cursor over multiview

libobs-d3d11/d3d11-subsystem.hpp, libobs/graphics/graphics.c, libobs/obs-scene.c, libobs/obs-source-transition.c, libobs/obs-source.c, libobs/obs-video.c, plugins/obs-filters/gpu-delay.c
Currently SrcBlendAlpha and DestBlendAlpha are both ONE, and can
combine together to form two. This is not a noticeable problem for
UNORM targets because the channels are clamped, but it will likely
become a problem if FLOAT targets are more widely used.
This change switches DestBlendAlpha to ZERO, which is a much more
standard setup. INV_SRC_ALPHA is also an option, but I'm not sure what
the original change was trying to make work.
=> libobs: libobs-d3d11: Fix blend alpha overflow

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Input buffer by default is set to 2MB - for some sources, for example streaming
RTSP input over UDP, this is not enough and causes significant playback issues
that are not present while playing back the same source under ffplay/mpv.
It looks like someone actually started working on this feature as there are
translated strings, properties and everything ready - only the control was
missing from the UI. This commit adds that control.
Currently, the range is set to 1-16MB, step 1MB. This is somewhat arbitrary,
so suggestions to tweak this range with more real-world use cases are welcome.
=> obs-ffmpeg: Bind network buffer size in the UI

plugins/win-capture/graphics-hook/graphics-hook.c
… get two mutexes,eventually may cause deadlock
if obsstudio shutdown abnormal,tex_mutexes may not be released(ReleaseMutex),at that time if use WaitForSingleObject to get mutexe WaitForSingleObject will return WAIT_ABANDONED and get lock,but try_lock_shmem_tex will not return,it will continue wait next mutexe。eventually the return WAIT_ABANDONED will not release infinite。this commit will fix this bug。
=> win-capture/graphics-hook: Fix try_lock_shmem_tex mutex  deadlock bug

CI/install-dependencies-linux-ubuntu16.sh, CI/install-dependencies-linux.sh, plugins/linux-capture/CMakeLists.txt, plugins/linux-capture/xhelpers.c, plugins/linux-capture/xhelpers.h, plugins/linux-capture/xshm-input.c
I just reworked my monitor setup and the xinerama support in linux-capture's xshm plugin was not able to capture the monitor I needed it to.  So this adds xcb-randr as a dependency and then uses it to determine the location of the screens which the rest of the xshm plugin will happily use.
I haven't done a lot of testing here yet, but everything does seem to be working fine so far.
=> linux-capture: Add randr support

libobs/obs-internal.h, libobs/obs-output.c, libobs/obs.h
Adds `display_duration` declaring the minimum duration a caption text is not going to be overwritten by a new one.
To keep the functions backwards-compatible `obs_output_output_caption_text2` was added while
`obs_output_output_caption_text1` continues having a 2 second default.
Tested this with a newer version of my obs-websockets PR and it worked quite well when sending the results from Google's speech to text in real time to Twitch.
=> libobs: Add minimum display duration to caption data

libobs/obs-properties.c, libobs/obs-properties.h
At the moment it is not possible to properly create a dynamic workflow for sources and encoders which have a dynamic number of properties that change depending on other values. As these values most of the time can be changed by the user, fake names have to be used, which makes the code extremely complicated.
With this OBS Studio supports removing properties again in the modified_properties callback, however only if true is returned. Returning false and using the function is currently undefined behavior.
=> libobs: Add function to remove properties

libobs/obs-nix.c
Fixes https://obsproject.com/mantis/view.php?id=1257
=> libobs: Add support for F25-F35 hotkeys on Linux

UI/CMakeLists.txt, UI/comboBox-ignorewheel.cpp, UI/comboBox-ignorewheel.hpp, UI/double-slider.cpp, UI/double-slider.hpp, UI/frontend-plugins/decklink-output-ui/CMakeLists.txt, UI/frontend-plugins/frontend-tools/CMakeLists.txt, UI/properties-view.cpp, UI/slider-ignorewheel.cpp, UI/slider-ignorewheel.hpp, UI/spinBox-ignorewheel.cpp, UI/spinBox-ignorewheel.hpp
0001214: Scroll wheel events modifies keyboard focus
Uses eventFilter to disable scrollwheel for comboBox, Slider, and Spin box when adding sources.
=> Ui scroll wheel events

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/qt-display.cpp, UI/qt-display.hpp, UI/window-projector.cpp
1. Fixes an issue when custom theme has no info about the preview
background color, the preview's display background may be rendered
with random color.
2. Adds Projector display background color customization instead of
hardcoded black. Now if source larger than the display's height or
width, the remaining space for the Fullscreen Projector filled with
the preview's display background color from the theme.
The Projector's background, if it defer from the Display's background
color may be specified via:
```
OBSProjector {
qproperty-displayBackgroundColor: ... ;
}
```
record that is placed after the `OBSQTDisplay` section in the theme
file (qss).
3. The usage of the `* [themeID="..."]` in themes was not versatile - 
this is selector _for any child object that has `themeID` property_.
In …
=> UI: Correct custom property implementation

UI/properties-view.cpp, UI/properties-view.hpp, libobs/obs-properties.c, libobs/obs-properties.h
The current OBS Studio properties UI does not have any visual indicators for things that belong together. This results in very cluttered UIs if you have a lot of options, something that does not necessarily have to be, but is currently a limitation of the way OBS Studio works.
This PR adds Property Groups which can be used to visually group properties together with additional context information, and optionally even allowing an entire group of properties to be disabled at the same time. They work using the same API as before and require a child property list, but do not allow recursion and correctly check for duplicated property names.
There are two types of groups:
- Normal: A normal group with just a name and content.
- Checkable: A checkable group with a checkbox, name and content.
In …
=> libobs/UI: Add Property Grouping

UI/slider-ignorewheel.cpp, UI/slider-ignorewheel.hpp, UI/volume-control.cpp, UI/volume-control.hpp
Disable volume slider change with mouse hover.
Allow volume slider change after mouse click.
Allow click on volumeMeter to enable scrollWheel.
Remove focus when mouse leaves widget.
=> UI: Volume scrollEvents

UI/qt-wrappers.cpp, UI/qt-wrappers.hpp, UI/window-basic-filters.cpp, UI/window-basic-main-outputs.cpp, UI/window-basic-main-profiles.cpp, UI/window-basic-main-scene-collections.cpp, UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-source-select.cpp, libobs/util/pipe-posix.c, libobs/util/pipe-windows.c, libobs/util/pipe.h, plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-mux.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
These commits add a handle to the Win32 pipe structures to allow the ffmpeg-mux process to write to stderr and have OBS capture the output. This error data is stored in the ffmpeg data structure and eventually passed back to the UI if a critical error occurs, providing additional details to the infamous "An unspecified error occurred while recording" dialog. It also catches errors from internal use of ffmpeg-output where the ffmpeg-mux process isn't involved.
The UI was updated to support additional severity levels of QMessageBox implementations, so errors actually show an error box instead of an information box.
=> Improve ffmpeg output error handling

UI/window-basic-preview.cpp, libobs/obs-scene.c, libobs/obs-scene.h, libobs/obs.h
The line drawing functions previously assumed the upper-left 3x3 for
box_transform only held scale. The matrix can also hold rotation, so
pass in scale separately.
Fixes https://obsproject.com/mantis/view.php?id=1442
=> libobs: UI: Fix rotated line scale

plugins/win-wasapi/win-wasapi.cpp
BUG: OBS audio input capture gets frozen if USB sound card is disconnected and then reconnected. This also might happen accidentally on sound card power cycle.
After this PR user does not have to restart OBS or re-add audio source after said event.
Note: if audio input device is set to Default, Windows might automatically fallback to available input device and this PR effect is unnoticeable. To test it properly please explicitly select your sound card as input and monitoring device.
=> win-wasapi: Fix audio capture after USB sound card unplugging

plugins/obs-outputs/librtmp/rtmp.h, plugins/obs-outputs/rtmp-stream.c
Fix about a thousand leaks (one per certificate) with mbedTLS for rtmp.
=> obs-outputs: Fix leak with certs for rtmp

libobs-opengl/gl-indexbuffer.c, libobs/graphics/graphics.c
GS_UNSIGNED_LONG is defined as sizeof(long) in some places, making it 8
outside of Windows instead of 4 as it should be.
Fixes https://obsproject.com/mantis/view.php?id=1444
=> libobs: Fix GS_UNSIGNED_LONG definition

UI/forms/OBSBasic.ui, UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp
=> UI: Fix preview/program label alignment

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Fixes https://obsproject.com/mantis/view.php?id=1443
=> UI: Fix unable to escape when renaming scene

libobs/util/platform-nix.c
It is fixed to return null (not to load from libobs.dylib) if function is not defined in libobs-***.so for macOS.
=> libobs: Load function simbol from specified file.

UI/properties-view.cpp
Do not allow the user to select the alpha component of a color.
While https://github.com/obsproject/obs-studio/commit/78d566916bfd9847e8777a031f590106de17aa36 is still in use why not to hide this useless stuff?
Also, people asking time to time:
https://obsproject.com/forum/threads/color-correction-filter.94484/
=> UI: Hide Alpha channel field from the color picker

plugins/win-dshow/ffmpeg-decode.c
Logitech C920 web camera will output YUVJ420P H.264 in 1080p which is not supported yet.
=> win-dshow: fix issue decoding some H.264 stream

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, UI/data/locale/en-US.ini, UI/volume-control.cpp, libobs/obs-audio-controls.c, libobs/obs-audio-controls.h
This changes the volume to dB, instead of percent, in the advanced audio properties. I've set the range from -120.0 dB to +12.0 dB with 0.1 dB increments. I believe users would understand dB more easily than percents.
=> UI: Use dB for volume in adv. audio properties

libobs-d3d11/d3d11-subsystem.hpp, libobs/data/area.effect, libobs/data/bicubic_scale.effect, libobs/data/bilinear_lowres_scale.effect, libobs/data/default.effect, libobs/data/lanczos_scale.effect, libobs/graphics/graphics.c, libobs/obs-scene.c, libobs/obs-source-transition.c, libobs/obs-video.c, libobs/obs.c, plugins/obs-transitions/data/fade_to_color_transition.effect, plugins/obs-transitions/data/fade_transition.effect, plugins/obs-transitions/data/luma_wipe_transition.effect, plugins/obs-transitions/data/premultiplied.inc, plugins/obs-transitions/data/slide_transition.effect, plugins/obs-transitions/data/swipe_transition.effect
There are cases where alpha is multiplied unnecessarily. This change
attempts to use premultiplied alpha blending where appllicable.
In addition, SrcBlendAlpha and DestBlendAlpha are both ONE, and can
combine together to form two. This is not a noticeable problem for
UNORM targets because the channels are clamped, but it will likely
become a problem if FLOAT targets are more widely used.
This change switches DestBlendAlpha to INVSRCALPHA, and starts the main
background as opaque black instead of transparent black. The blending
behavior of stacked transparents is preserved without overflowing the
alpha channel.
=> libobs: libobs-d3d11: Fix alpha blend

plugins/obs-outputs/librtmp/rtmp.c
Define MSG_NOSIGNAL even if CRYPTO is not defined.
=> obs-outputs: Fix undefined MSG_NOSIGNAL

libobs/obs-source.c
Clang doesn't like it if you convert T** to const T* const* without
casting even though it should be safe. Might be a C language thing.
=> libobs: Restore casts to fix Clang warnings

UI/window-basic-main.cpp, libobs/obs-display.c, libobs/obs.h
This fixes Xcode warning about detecting UI usage from another thread.
=> libobs: UI: Remove Qt usage from graphics thread

plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
In my setup, while VAAPI encoding works, the output bitrate varies wildly. Using examples from the FFmpeg wiki, I devised this patch that makes the bitrate more stable.
According to the FFmpeg wiki, the configuration created by the VAAPI plugin for FFmpeg is referred to as VBR. Setting maxrate makes it CBR. Reference: https://trac.ffmpeg.org/wiki/Hardware/VAAPI#Encode-only
=> Fix VAAPI CBR

UI/data/locale/en-US.ini, UI/properties-view.cpp, UI/properties-view.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-properties.cpp, UI/window-basic-properties.hpp, libobs/obs-source-transition.c, libobs/obs-source.c, libobs/obs.h
This PR adds a preview to the properties window for transitions. The preview will play back the transition at the global transition duration or the transitions fixed duration, between two private scenes with an A and B label, and different background colors.
=> libobs/UI: Add Transition Previews

UI/data/themes/Dark.qss
Selected but unfocused Source colour (improves visibility)
- Before:
- After:
Scenes font (most visible when using uppercase "i") - only problem with this change is that it slightly changes the height of the element so that aspect no longer matches Sources
- Before:
- After:
Padding when editing Source name (was slightly cut off)
- Before:
- After:
=> UI: Dark theme consistency for Scenes vs Sources

libobs/obs-source.c
A previous refactoring to make DrawMatrix unnecessary has left behind
unreachable YUV conversions. Even if this code was somehow reachable,
DrawMatrix for YUV -> RGB doesn't exist anymore, so they would render
incorrectly anyway.
=> libobs: Remove unreachable YUV decode paths

UI/window-basic-stats.cpp
The recording time left timer was being called an unnecessary time,
in the stats constructor, when it should have only been started
when the recording starts.
=> UI: Fix issue where rec time left would show negative time

libobs-d3d11/d3d11-subsystem.cpp
Fix bad logging for LogAdapterMonitors and LogD3DAdapters. Update
EnumD3DAdapters for consistency.
=> libobs-d3d11: Bad indices in log output

plugins/win-wasapi/win-wasapi.cpp
Remove KSAUDIO_SPEAKER_2POINT1 because it is included in the Windows
SDK. (I'm guessing it wasn't before.)
Redefine 4POINT1 as KSAUDIO_SPEAKER_SURROUND|SPEAKER_LOW_FREQUENCY
instead of KSAUDIO_SPEAKER_QUAD|SPEAKER_LOW_FREQUENCY. See definitions:
FFmpeg 4.1: FL+FR+FC+LFE+BC
WASAPI QUAD: FL+FR+BL+BR (looks wrong)
WASAPI SURROUND: FL+FR+FC+BC
WASAPI LOW_FREQUENCY: LFE
=> win-wasapi: Speaker enum fixes

CI/install-dependencies-osx.sh
`-v` test not supported in OS X system bash
=> CI: Fix travis test on OSX

CI/install-dependencies-osx.sh
`-DCMAKE_OSX_DEPLOYMENT_TARGET=10.11` fails to change target to 10.11
=> CI: Build CEF with OS X 10.11 target

UI/window-basic-properties.cpp
Previously, if the video size in OBS was too big, the labels would not
render on macOS/Linux due to the labels not fitting inside the texture
in the freetype plugin. This change makes it so that there is a maximum
size for the label, rather than being solely based on video size.
This change also makes the labels look centered on macOS/Linux, as
unlike the GDI plugin on Windows, the freetype plugin aligns the bottom
of the text with the bottom of the source.
=> UI: Fix transition A/B labels on macOS/Linux

UI/win-update/updater/CMakeLists.txt, UI/win-update/updater/updater.cpp, UI/win-update/updater/updater.manifest
This modernizes the OBS updater a bit by adding a DPI manifest so it doesn't look blurry on high DPI displays, adds a marquee progress bar during the existing file check so the program doesn't appear frozen and clarifies some action text.
=> UI/updater: Various updates

libobs/obs-source.c
This fixes the issue where limited-range RGB sources were being
composited with dirty render targets.
=> libobs: Disable blending when converting sources

libobs/data/bilinear_lowres_scale.effect
The issue with the current bilinear_lowres_scale effect is that it
samples adjacent texels, disregarding the texel-to-pixel ratio. If the
ratio is large, this can lead to aliasing. This change provides a fair
set of texture samples across the entire pixel.
The 8-sample pattern used here comes from Direct3D.
**Example**
Consider this image, a white square with 9 evenly spaced black squares.:
Downsampling from 24x24 to 3x3 leads to a completely black image because all samples are concentrated within the black squares:
With samples spread out to cover the entire pixel, we get a nice light-gray as expected:
=> libobs: Improve low-resolution bilinear sampling

libobs/obs-internal.h, libobs/obs-video.c, libobs/obs.c
Remove three instances of unnecessary double-buffering. They are not
needed to avoid stalls, and cause increased memory traffic when
measured on Intel HD 530, presumably because texture data will remain
in cache if sampled immediately after write.
(Note: GPU timings from Intel GPA are volatile.)
NV12, 3 Draws:
RGBA -> UYVX: 628 us -> 543 us
UYVX -> Y: 522 us -> 507 us
UYVX -> UV: 315 us -> 187 us
Total, Duration: 1594 us -> 1153 us
Total, GTI Read Throughput: 25.2 MB -> 15.9 MB
=> libobs: Remove unnecessary frame pipelining

libobs/data/format_conversion.effect, libobs/media-io/video-frame.c, libobs/media-io/video-io.h, libobs/media-io/video-scaler-ffmpeg.c, libobs/obs-source.c, plugins/linux-v4l2/v4l2-helpers.h, plugins/obs-ffmpeg/obs-ffmpeg-formats.h
Someone mentioned this format preserves the most quality for a
particular capture card using V4L2.
=> libobs: linux-v412: obs-ffmpeg: Add packed BGR3 video support

libobs-d3d11/d3d11-subsystem.cpp
Simplify STL usage as requested by function comment.
=> libobs-d3d11: Clean up device_projection_pop

libobs/data/area.effect
Switch for loop to do/while because we know the condition is always
true for the first loop.
Replace int math with float math to play nicely with more GPUs.
Add variables imagesize/targetsize to avoid redundant reciprocals.
Intel GPA results: 1166 -> 836 us
=> libobs: Area-resampling shader optimizations

UI/source-tree.cpp, UI/source-tree.hpp, UI/visibility-item-widget.cpp, docs/sphinx/reference-scenes.rst, libobs/obs-scene.c
Similar to item_visible, this event fires whenever a scene item is
locked or unlocked. This allows the UI and libobs to remain in sync
regarding scene elements' statuses.
Implements https://obsproject.com/mantis/view.php?id=1463
=> libobs/UI: Implement an item_locked event

libobs-d3d11/d3d11-shader.cpp, libobs-d3d11/d3d11-shaderprocessor.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs-opengl/gl-shaderparser.c, libobs-opengl/gl-subsystem.c, libobs-opengl/gl-vertexbuffer.c, libobs/data/format_conversion.effect, libobs/obs-source.c, libobs/obs-video.c
The cache coherency of rasterization for full-screen passes is better
using an oversized triangle that is clipped rather than two triangles.
Traversal order of rasterization is GPU-specific, but will almost
certainly be better using an undivided primitive.
A smaller benefit is that quads along the diagonal are not evaluated
multiple times, but that's minor in comparison.
Add gs_draw_sprite_fullscreen and redo shaders to bypass vertex buffer,
and input layout. Add global shader bool "obs_glsl_compile" to make
API-specific decisions, i.e. handle upside-down UVs. gl_ortho is not
needed for format conversion because the vertex shader does not use
ViewProj anymore.
This can be applied to more situations, but start small first.
Testbed full screen passes, Intel HD Graphics 530:
RGBA -> UYVX: …
=> libobs: Full-screen triangle format conversions

libobs-opengl/gl-helpers.h, libobs-opengl/gl-subsystem.c, libobs-opengl/gl-subsystem.h, libobs-opengl/gl-vertexbuffer.c
Use an empty VAO for shaders that generate their own vertices.
=> libobs-opengl: Empty VAO

libobs-d3d11/d3d11-subsystem.cpp
Use raw pointer on both sides of ternary test result to remove
conversions.
=> libobs-d3d11: Unnecessary type conversions

libobs/obs-source.c
Fix ternary test to use BGRX render targets for YUV to RGB
conversions. The previous behavior may have been fine though since
the shaders fill the alpha channel with 1.0 anyway.
=> libobs: Fix format selection

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
* Add Twitch Oslo ingest
* Add Chicago server for restream
* Do not mark Smashcast as common anymore (<300 CCU, mostly pirate streams)
* Remove stream.me (defunct)
* Remove gameplank (defunct)
* Remove djlive.pl (defunct, in the process of being relaunched?)
* Remove "Asia Central" from switchboard (NXDOMAIN)
=> rtmp-services: Update and prune services

UI/data/themes/Dark.qss
This changes the group box title to be bold and adjusts position of title a few pixels.
This makes the group boxes easier to distinguish between each other and I believe it is
more aesthetically pleasing.
I tested this on Linux only but I should be just fine on Mac/Windows.
Visual change (changes look of UI)
=> UI: Make Dark theme group box title bold

UI/properties-view.cpp
Fixes the issue where checkable property groups did not correctly store their state, as the signal `toggled()` doesn't actually exist. The correct signal is called `toggled(bool)` and once this fix is applied, checkable property groups correctly store their state into the obs_data_t object.
It's required because things are broken right now. Original PR was not tested extensively, so this is my attempt at fixing up all the messes I've made with the additions.
Tested with obs-ffmpeg-encoder's libvpx-vp9 implementation which uses a checkable property group. It correctly kept its state even after closing the settings window.
=> UI: Fix toggled signal of property groups

libobs/obs-encoder.c, libobs/obs-encoder.h, libobs/obs-source.c, libobs/obs-source.h
Back in commit 93549ea17cb696b064ec0b967a667170e8d25595 I've introduced get_defaults2 and get_properties2 APIs in order to drastically reduce code duplication, but ended up not using it for a long time. Until I began to work on obs-ffmpeg-encoder, which actively used these new APIs, and ended up with really weird bugs.
One was that even though get_defaults2 was being called, all the values that were at the default values were giving back 0 instead of the actual default - which meant that the UI got the correct values, but something was broken somewhere else. After a short debugging session, I found the cause to be 'init_encoder', which I did not modify with the original commit - a mistake on my part which should have been caught had I properly tested the change.
Additionally there is no …
=> libobs: Call both get_defaults and get_defaults2

UI/window-basic-main.cpp
This changes the default format from flv to mkv in both Simple and Advanced output modes.
MKV maintains FLV's stability while providing multiple audio tracks out of the box and adds slightly better media player support (including Films & TV, the default app on Windows 10).
Launched a clean config of OBS and checked Settings -> Output. Switched to Advanced output mode and did the same there. Then attempted a recording. Played back successfully in Windows 10's default media player, Films & TV.
=> UI: Change default recording format to MKV

libobs/obs-audio.c, libobs/obs-source.c, plugins/win-dshow/win-dshow.cpp
This PR attempts to address buffering and audio loss problems with GV-USB2 in a robust way.
See https://obsproject.com/mantis/view.php?id=1269
=> Fix audio buffering for devices like GV-USB2

libobs-opengl/gl-helpers.h
glGetError() returns GL_INVALID_OPERATION during OBS shutdown when GL is
used on Windows. This change gives up after eight errors.
This could be avoided by stopping the graphics thread before window
destruction, but the shutdown code looks like it could be tricky to
reorder.
Infinite loop on shutdown prevents the process from terminating.
Using GL on Windows, OBS now breaks out of the loop and terminates. The log is consistent with code intent. Also tried OBS shutdown using D3D and there was no regression.
=> libobs-opengl: Fix glGetError() infinite loop

libobs/data/area.effect, libobs/obs-scene.c, libobs/obs-video.c, plugins/obs-filters/scale-filter.c
Add a separate shader for area upscaling to take advantage of bilinear
filtering. Iterating over texels is unnecessary in the upscale case
because a target pixel can only overlap 1 or 2 texels in X and Y
directions. When only overlapping one texel, adjust UVs to sample texel
center to avoid filtering.
Also add "base_dimension" uniform to avoid unnecessary division.
The Area scaling shader is slow, but it doesn't need to be in the more common upscaling direction.
Intel HD Graphics 530, 644x478 -> 1323x1080: ~836 us -> ~297 us
Tested upscale/downscale paths with breakpoint inspection and RenderDoc shader debug verification for both item scaling and scale filter, and both D3D/GL, but only on Windows. Measured draw performance using Intel GPA, taking the minimum of 5 runs with …
=> libobs: obs-filters: Area upscale shader

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, libobs/obs.c, libobs/obs.h
Use blend states to simulate the black background of
DrawBackdrop() for the following situations:
- Main preview window (Studio Mode off)
- Studio Mode: Program
This does not effect:
- Studio Mode: Preview (still uses DrawBackdrop)
- Fullscreen Projector (uses GPU clear to black)
- Windowed Projector (uses GPU clear to black)
It's a waste of GPU time to do two fullscreen passes to render final mix
previews.
Checked transparent and opaque scenes in previously mentioned preview scenarios and video output.
Intel GPA, SetStablePowerState, Intel HD Graphics 530, 1920x1080
Before:
DrawBackdrop: ~529 us
main texture: ~367 us (Cheaper than drawing a black quad?)
After:
[DrawBackdrop optimized away]
main texture: ~383 us
=> libobs: UI: Remove DrawBackdrop() to save fullscreen pass

UI/adv-audio-control.cpp, UI/volume-control.cpp
This displays the infinity symbol when volume is at 0 percent.
This symbol is easier to understand than inf and is language independent.
I ran the program and everything worked as expected.
-Visual change (improves look of UI)
=> UI: Display infinity symbol when volume is at 0 percent

UI/window-remux.hpp
window-remux.hpp: Add missing override declaration to 'dropEvent' and 'dragEnterEvent' methods (matching existing style).
'dropEvent' and 'dragEnterEvent' override methods in qwidget.h but are not marked 'override'
Compiled and launched on macOS 10.14. Compiler warnings regarding undeclared virtual methods ('dropEvent' and 'dragEnterEvent') no longer appear. No new warnings in UI during compilation. Zero memory leaks reported after program termination.
=> UI: Declare missing overrides

UI/window-basic-main.cpp
This simplifies checking if outputs are active in the resize output code.
At the time I wrote the code, I didn't know there was the obs_video_active() function.
I tested the resizing of outputs and everything works as expected.
=> UI: Simplify resize output code

UI/frontend-plugins/frontend-tools/data/locale/en-US.ini, UI/frontend-plugins/frontend-tools/forms/output-timer.ui, UI/frontend-plugins/frontend-tools/output-timer.cpp, UI/frontend-plugins/frontend-tools/output-timer.hpp
This adds an option to the output timer to pause the timer when the recording is paused.
I made this because I noticed when using the output timer, it would continue even if the recording is paused.
I've tested by making recordings with the output timer and pausing/unpausing to make sure that everything works as intended.
=> frontend-tools: Add option to pause output timer when rec is paused

libobs/CMakeLists.txt, libobs/libobs.pc.in
I've only tested this on a multilib Gentoo install, but it looks like it should be correct for others as well.  :]
=> cmake: Install 'libobs.pc' under the correct 'libdir'

libobs/data/bicubic_scale.effect, libobs/data/bilinear_lowres_scale.effect, libobs/data/default.effect, libobs/data/format_conversion.effect, libobs/data/lanczos_scale.effect, libobs/obs-video.c
RGB to YUV converison was previously baked into every scale shader, but
this work has been moved to the YUV packing shaders. The scale shaders
now write RGBA instead. In the case where base and output resolutions
are identical, the render texture is forwarded directly to the YUV pack
step, skipping an entire fullscreen pass.
Scale shaders shouldn't really need to know anything about YUV conversions, but the main reason is to reduce unnecessary GPU writes in the common case of unscaled output.
Intel GPA trace inspection:
Intel GPA, SetStablePowerState, Intel HD Graphics 530, NV12
1920x1080, expect win from skipping fullscreen pass
Before:
RGBA -> UYVX: ~321 us
UYVX -> Y: ~480 us
UYVX -> UV: ~127 us
After:
[forward render texture]
RGBA -> Y: ~487 us
RGBA -> UV: ~131 us
1920x1080 -> …
=> libobs: Rework RGB to YUV conversion

libobs-opengl/gl-shaderparser.c, libobs-opengl/gl-subsystem.h
Small menu of GL improvements: fix GS_R8G8 using the wrong GL values, and update the GLSL generator to support gl_FragCoord. Also remove some unused code.
- GS_R8G8 support will be necessary for an upcoming change to simplify YUV output shaders to store NV12 CbCr.
- gl_FragCoord allows usage of SV_Position-style PS inputs. It's a natural fit for fullscreen passes where gl_FragCoord.xy contains the texelFetch coordinates.
- Dead code leads to confusion.
- GS_R8G8 support has been exercised in a coming PR and now behaves as intended.
- gl_FragCoord support has been exercised in a coming PR and behaves as intended. All GLSL shaders generated on Windows application startup have been looked over, and interpolants look good. Tested various rescaling shaders and video recording on Mac.
- …
=> GL support improvements

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/window-basic-main.cpp, UI/window-basic-settings.cpp
OBS has an option to warn before stopping a stream, but it doesn't have
a similar warning for recording. This can result in a recording being
unintentionally stopped.
Add an option to warn when the "Stop Recording" button is pressed.
Note: While OBS also has an option to warn on stream start, this
patch purposefully does not add similar warn on recording start option.
This is because accidentally starting to record isn't risky in the same
way that accidentally starting to stream is.
=> UI: Add option to warn on stop recording

libobs/data/format_conversion.effect, libobs/media-io/video-frame.c, libobs/media-io/video-io.h, libobs/media-io/video-scaler-ffmpeg.c, libobs/obs-source.c, plugins/obs-ffmpeg/obs-ffmpeg-formats.h, plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/win-dshow.cpp
The former change supports the latter. Better CPU usage, and lower latency on my webcam.
=> Add planar 4:2:2 video support; Use FFmpeg MJPEG decoder instead of DirectShow

libobs-opengl/gl-shaderparser.c, libobs/data/bicubic_scale.effect, libobs/graphics/shader-parser.h, libobs/obs-scene.c
Use bilinear filtering to reduce 16 taps to 9 for the regular path. This
works because the middle weights are always between 0 and 1, allowing
texture coordinates to be placed strategically to sample correct ratios.
I'm not sure about the undistort path, so I've left that alone.
Also remove weight normalization. I'm not seeing that make even a small
difference.
Shader is unnecessarily slow, and enabled by default for the entire canvas.
Checked Windows-D3D/GL, upscale/downscale/1:1, undistort/regular. All image diffs with/without PR were nearly identical. Also checked undistort/regular upscale on Mac for extra verification.
Intel HD Graphics 530, D3D11
644x478 -> 1323x1080: 1790 us -> 1279 us
1920x1080 -> 1280x720: 1301 us -> 918 us
- Performance enhancement (non-breaking change which …
=> Optimize bicubic shader

libobs/obs-source.c
The video format is not updated if switching between cache-compatible
formats, e.g. YUY2 and YVYU, resulting in the wrong conversion technique
being used. This change ensures the format is always up-to-date.
Noticed the video format was not being updated with my format-testing plugin.
Correct technique is now used. Also checked format switching in win-dshow plugin still works.
=> libobs: Fix stale format in async frame cache

UI/data/themes/Rachni.qss
This fixes an issue where the pause button wouldn't change color, when checked, in the Rachni theme.
This makes the button consistent with other buttons.
Everything works as expected.
=> UI: Fix pause button checked color with Rachni theme

UI/frontend-plugins/frontend-tools/data/scripts/pause-scene.lua
This adds a script for when a specific scene is switched to, the recording will pause.
With the pause feature, this script will be a good companion when the next OBS version is released. Since it is a very simple script, it is a good guide on how to write other scripts.
It has been tested and everything works as expected.
=> obs-scripting: Add pause scene script

deps/obs-scripting/obs-scripting-lua-source.c
In the current OBS Studio stacking multiple Lua filters registered by the same script will freeze OBS Studio in place, with no way to fix it on the user side. Any progress made until that moment is lost if there was no scene collection save happening. If there was one happening during the freeze, the collection might end up corrupted and the backup is loaded instead.
This is due to the fact that the mutex we use does not allow a recursive lock, so when that eventually happens everything just freezes since we already hold a lock on the mutex and are trying to lock it again.
When a Lua script creates a filter, that filter can't be used more than once in the same filter stack, which is severely limiting, and actually counterproductive as OBS Studio simply freezes in place. 
Tested against …
=> obs-scripting: Use a recursive mutex for Lua scripting

libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-opengl/gl-subsystem.c, libobs-opengl/gl-subsystem.h, libobs/graphics/device-exports.h, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h
Exposes GPU timestamp functionality in D3D11 and OpenGL.
This change only wraps the functionality. I have rough code to exercise
the the query functionality, but that part is not really clean enough to
submit.
Tool timing can be missing/unreliable, so it's sometimes better to read them directly from the application itself.
I have separate changes to print out timestamps and it works on both APIs.
=> libobs: Add GPU timestamp query support

UI/properties-view.cpp
Reverts the size and decimal places change done in #1979 which shouldn't have been part of that PR.
PR #1979 broke support for various filters, sources and encoders and should not have been merged as it is.
Tested against all bundled plugins, stream effects, ffmpeg encoder, enc-aomedia1, enc-vfw, av-toolkit. All plugins returned to working correctly after this change.
=> UI: Fix Int/Float Sliders and Spinboxes by partially reverting PR #1979

libobs/data/format_conversion.effect, libobs/obs-internal.h, libobs/obs-video.c, libobs/obs.c
The shaders to pack YUV information into the same texture were rather
complicated and suffering precision issues. Breaking them up into
separate textures makes the shaders much simpler and avoids having to
compute large integer offsets. Unfortunately, the code to handle
multiple textures is not as pleasant, but at least the NV12 rendering
path is no longer separate.
In addition, write chroma samples to "standard" offsets. For I444,
there's no difference, but I420/NV12 formats now have chroma shifted to
the left as 4:2:0 is shown in the H.264 specification.
YUV shaders are not operating as quickly as they should, and we can out knock two precision-related bugs in the process.
Fixes https://obsproject.com/mantis/view.php?id=624
Fixes https://obsproject.com/mantis/view.php?id=1512
Also nice …
=> libobs: Separate textures for YUV output, fix chroma

UI/data/locale/en-US.ini, libobs/data/lanczos_scale.effect
Use bilinear filtering to reduce 36 taps to 25 for the regular path.
This works because the middle weights are always between 0 and 1,
allowing texture coordinates to be placed strategically to sample
correct ratios. I'm not sure about the undistort path, so I've left that
alone.
Also remove scaling added in #526, after which weight normalization is
unnecessary. If we want to use or invent an algorithm with alternate
downscaling properties, that's fine, but I don't think we should change
Lanczos scaling to mean something it's not. The scale implementation was
also seen not working when applied directly to scene items because of
assumptions made about the projection matrix.
Also fix the UI string. The Lanczos shader performs 36 samples (with 25 shader reads), not 32.
Align Lanczos shader …
=> libobs: Optimize lanczos shader, remove scaling

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/forms/OBSExtraBrowsers.ui, UI/qt-wrappers.cpp, UI/qt-wrappers.hpp, UI/source-tree.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-extra-browsers.cpp, UI/window-extra-browsers.hpp
Adds the ability to add custom browser docks to OBS from the View -> Docks menu.  Users can specify URLs to load as a part of OBS itself in additional dockable widgets.  They will then load up with the program when it starts up.
A lot of users have other browsers they commonly have open alongside OBS that they typically may have to open every single time they stream.  This simplifies the process by allowing them to have those open as a part of OBS on startup if the user so chooses.
=> Add ability to create custom browser docks

libobs/data/format_conversion.effect, libobs/obs-internal.h, libobs/obs-source-deinterlace.c, libobs/obs-source.c, libobs/obs-video.c
The shaders to unpack YUV information from the same texture were rather
complicated. Breaking them up into separate textures makes the shaders
much simpler, and we can remove the PRECISION_OFFSET hack.
Performance also gets a nice boost on Intel for planar textures.
Looking for more GPU headroom, and it's there. Also nice to remove shader hacks.
UYVY
YUY2
YVYU
I420
I422
I444
NV12
Y800 (limited/full)
RGB (limited/full)
BGR3 (limited/full)
Intel GPA, SetStablePowerState, Intel HD Graphics 530, 1920x1080
UYVY: 473 us -> 457 us
YUY2: 492 us -> 422 us
YVYU: 491 us -> 441 us
I420: 1637 us -> 505 us
I422: 1644 us -> 482 us
I444: 1653 us -> 504 us
NV12: 1656 us -> 369 us
Y800 (limited): 270 us -> 277 us
Y800 (full): 263 us -> 289 us
RGB (limited): 341 us -> 411 us
BGR3 (limited): 512 us -> 509 us …
=> libobs: Separate textures for YUV input

plugins/obs-transitions/transition-stinger.c
This fixes an issue where the transition point (frame) would show the ms suffix.
It was pointed out that the suffix was wrong for this item.
I opened the stinger transition properties and changed transition point type and everything worked as expected.
=> obs-transitions: Fix suffix with stinger transition

libobs/media-io/video-io.h
Insert VIDEO_FORMAT_I422 into switch cases: format_is_yuv and get_video_format_name. Rearrange video formats (in logical order) for consistency: 4:2:0, 4:2:2 (planar, packed), 4:4:4, uncompressed
Fix compiling warning: VIDEO_FORMAT_I422 not included in switch case...
Compilation warning no longer appears.
=> libobs: Add missing format to format_is_yuv & get_video_format_name

libobs-opengl/gl-helpers.h, libobs-opengl/gl-subsystem.h, libobs-opengl/gl-texture2d.c, libobs/graphics/graphics.h, plugins/linux-capture/xcompcap-main.cpp
This fixes https://obsproject.com/mantis/view.php?id=1488.
There are a few added changes in here. The previous implementation used GS_GL_DUMMY textures which were broken, and used mixed GS_BGRX GS_RGBA so I have added GS_RGBX to unify them.
This correctly deduces alpha in cases like GTK/Gnome shadows and Video games which were previous detected as having alpha when they did not.
Drivers tested: Nvidia/Nouveau (mesa)/llvmpipe (mesa)/Intel (mesa)/AMD (thanks kon)
DEs tested: Gnome 3/Unity/i3/KDE
This PR doesnt fix a number of pre-existing issues on master:
- Nvidia drivers (430) on gnome3 may fail to allocate pixmaps meaning capture doesnt work or works sporadically. This issue still occurs with this change
- Intel hardware is R/B swapped for all windows. This issue still occurs but the R/B …
=> linux-capture: Correct XCompCap glxFBConfigs alpha check

deps/media-playback/CMakeLists.txt
Add closest-format.h to CMake file list.
I use VS solution search frequently, and not having the header in the project results in lost search hits.
VS now lists the header file. Application still runs.
=> deps/media-playback: Add missing header to CMake

libobs-opengl/gl-subsystem.h, libobs-opengl/gl-texture2d.c, libobs/graphics/graphics.h, plugins/linux-capture/xcompcap-main.cpp
Revert the GS_RGBX changes which introduced an ABI breaking change and is unsupportable on D3D11 backends (In two steps to preserve a pure revert commit and a separate commit remove from linux-capture).
Fix a typo in DUMMY texture creation introduced in the same PR.
Tested on intel/nvidia/nouveau and it shows no regressions from the committed PR.
=> Revert GS_RGBX changes made as part of #1934

deps/media-playback/media-playback/closest-format.h, deps/media-playback/media-playback/media.c, libobs/data/format_conversion.effect, libobs/media-io/video-frame.c, libobs/media-io/video-io.h, libobs/media-io/video-scaler-ffmpeg.c, libobs/obs-internal.h, libobs/obs-source.c, plugins/obs-ffmpeg/obs-ffmpeg-formats.h
Enable OBS to convert YUV alpha formats to RGBA on the GPU to free up CPU.
The GPU is much faster at processing images than the CPU.
Breakpoint inspection to verify old path (swscale MMX) has been replaced by new code paths.
Tested dancer1.webm and soccer1.webm from Google blog on Windows and Mac using Media Source. Converted those yuva420p videos to yuva422p and yuva444p using FFmpeg. AYUV tested with custom plugin since FFmpeg does not support.
Performance was measured using a custom plugin source at 1080p.
I40A -> RGBA, 1080p, CPU
swscale (MMX), Intel i7-6700: 1910 us -> 0 us
GPU measurements used Intel GPA with SetStablePowerState.
I40A -> RGBA, 1080p, GPU
Intel HD Graphics 530: 0 us -> 677 us
NVIDIA RTX 2080 Ti: 0 us -> 43 us
- New feature (non-breaking change which adds …
=> Add support for YUV alpha formats

libobs-opengl/gl-helpers.h
Tweaked function to address some issues: compiler warnings, skipped
entries, and type safety.
Noticed some new compiler warnings, and saw the function wasn't quite operating as intended.
Breakpoint inspection before and after to see entries were being skipped before, and are not skipped now. Compiler output is clean.
=> libobs-opengl: Fix gl_error_to_str

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/window-extra-browsers.cpp
This makes the trash icon background transparent in the extra browser panels dialog. I also fixed an issue where the button would change size when a new panel was added.
It makes it look more consistent with the UI.
Ran program, everything looked like it should.
UI change (change look of UI)
=> UI: Fix look of extra panels trash icon

libobs/data/lanczos_scale.effect
When texel samples are not exactly on texel centers, weight calculations
will involve a divide by a number very close to zero, resulting in
precision issues. Restore normalization of weights to compensate.
Dark lines were seen using Lanczos with specific resolutions.
Tested 2560x1440 -> 1536x864 before and after. Dark lines are gone.
=> libobs: Fix dark lines using Lanczos

libobs/data/lanczos_scale.effect
Remove some divides that I meant to remove earlier.
Reciprocal operations are very expensive, and it's better to be explicit than trust the compiler when possible.
Tested Lanczos still works 2560x1440 -> 1536x864
=> libobs: Remove unnecessary divides from Lanczos

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, libobs/obs-video.c
Add Area scaling for downscale output. Previously only available for scene items and scale filter.
Now that Lanczos downscale blurring has been removed, the Area shader can attempt to fill the void. We may see user reports of people wanting a blurring downscale where Bilinear doesn't do the job.
Verified Area and Lanczos menu selections work.
Verified in RenderDoc that the correct shaders were being used.
=> libobs: UI: Add Area for downscale output

plugins/obs-text/gdiplus/obs-text.cpp
Text transform did only work on the first loading of the file. Updates on the file did not get the text transform.
=> obs-text: fix text transform on updated file

libobs-d3d11/d3d11-subsystem.cpp
NV12 GPU copies to staging textures for CPU read take a ridiculously
long time on my integrated Intel GPU. Using R8/R8G8 instead seems to be
a huge speed-up.
Intel GPU needs all the help it can get, and this appears to be a big win for NV12 output.
Verified x264 and NVENC with my NVIDIA card still works with Intel as primary. Also verified NVENC new still works with NVIDIA as primary.
Intel HD Graphics 530, D3D11 query timings, SetStablePowerState
NV12: ~3268 us (minimum of wild timings)
R8/R8G8: ~781 us (most frequently occurring timing)
=> libobs-d3d11: Disable NV12 usage for Intel

UI/data/locale/en-US.ini
Downscale will either fetch 2x2, 2x3, 3x2, or 3x3 texels.
Originally thought it would be 1x1, 1x2, 2x1, or 2x2 texels, but I'm pretty sure the new values are correct.
Verified menu text has been updated.
=> UI: Fix Area sample count text

deps/obs-scripting/obslua/CMakeLists.txt, deps/obs-scripting/obspython/CMakeLists.txt
This PR fixes some warnings that are produced when building with CMake 3.13 and above.
When building with CMake 3.13, I get the following warnings: 
```
-- Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.12", minimum required is "2")
CMake Deprecation Warning at /usr/share/cmake-3.13/Modules/UseSWIG.cmake:524 (message):
SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
deps/obs-scripting/obspython/CMakeLists.txt:33 (SWIG_ADD_MODULE)
CMake Warning (dev) at /usr/share/cmake-3.13/Modules/UseSWIG.cmake:564 (message):
Policy CMP0078 is not set.  Run "cmake --help-policy CMP0078" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Call Stack (most recent call first): …
```
=> cmake: Fix SWIG deprecation warnings

UI/window-basic-main.cpp, UI/window-basic-main.hpp
This stops the recording when disk space is low. It is currently
set to stop when disk space is below 500 MB.
=> UI: Stop recording when disk space is low

UI/auth-oauth.cpp, UI/qt-display.cpp, UI/win-update/win-update.cpp, libobs-d3d11/d3d11-duplicator.cpp, libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs/graphics/matrix4.c, libobs/obs-encoder.c, libobs/obs-windows.c, plugins/win-capture/get-graphics-offsets/dxgi-offsets.cpp, plugins/win-capture/inject-library.c, plugins/win-wasapi/enum-wasapi.cpp, plugins/win-wasapi/win-wasapi.cpp
This fixes warnings generated by clang-tidy and CppCheck which both check for by-value exceptions and const correctness. In all cases that I know of, catching by value is not necessary, and we also don't seem to modify the exception either, so we can use const& instead of directly accessing a copy of the exception.
Got annoyed by the extreme noise that comes from obs-studio when clang-tidy and CppCheck is run over it.
This has no effect on functionality, only portability.
=> Fix various clang-tidy and CppCheck warnings.

UI/CMakeLists.txt, UI/source-tree.cpp, UI/source-tree.hpp, UI/window-basic-preview.cpp, UI/window-basic-preview.hpp
This change adds the ability to box select by clicking and dragging from
an empty part of the preview.
Shift + Drag add any items in the box to the selection. Alt + Drag will
remove items in the box from the selection. Ctrl + Drag inverts the
selected state for items in the box.
Regular Click + Drag: ![Regular Drag](https://i.imgur.com/aJTV0AE.gif)
Shift + Drag: ![Shift Drag](https://i.imgur.com/Fsgrwxu.gif)
Alt + Drag: ![Alt Drag](https://i.imgur.com/XvDLLFj.gif)
Ctrl + Drag: ![Ctrl Drag](https://i.imgur.com/EVRFY55.gif)
=> UI: Add box select to preview

UI/data/themes/Acri.qss, UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp, UI/frontend-plugins/decklink-output-ui/forms/output.ui, UI/record-button.cpp, UI/volume-control.cpp, UI/window-basic-properties.cpp, UI/window-basic-settings.cpp, UI/window-basic-settings.hpp, deps/obs-scripting/obs-scripting-lua.c, libobs/obs-encoder.c, plugins/vlc-video/vlc-video-source.c
This fixes the warnings that show up when compiling OBS.
Seeing warning are quite annoying and can sometimes make you think you made a mistake in your own code.
I have been compiling this on Linux to see if the warnings are gone.
=> various: Fix compiler/theme warnings

libobs/obs-source.c
I merged ```obs_source_process_filter_end``` and ```obs_source_process_filter_tech_end``` functions because they have almost the same logic, but in the aspect of variable validation I will say that they should complement each other.
I also moved the ```texture``` variable validate from ```obs_source_process_filter_end``` to ```obs_source_process_filter_tech_end```.
I met a crash when remove filter and in visual studio it shows that crash happened in ```parent_flags = parent->info.output_flags;``` with ```parent == nullptr```. 
But it seems quite hard to reproduce: never happened again during the following test.
It doesn't crash during following code running. 
(Though this code not reproduced the crash before modify the code.) 
```
#include <obs.h>
#include …
```
=> libobs: Merge obs_source_process_filter_(tech_)?end functions

libobs-opengl/gl-helpers.h, libobs-opengl/gl-subsystem.c
Fix Clang warnings in libobs-opengl.
Noticed a bunch of warnings when compiling from Xcode.
Code builds clean in VS and Xcode. OpenGL path still draws to screen.
=> libobs-opengl: Fix Clang warnings

plugins/linux-capture/xcompcap-main.cpp
Correctly bind the texture before applying swizzles.
Previously xcompcap depended on the bind leak on GS_GL_DUMMYTEX. After resolving that leak the red/blue swap stopped working.
Tested on intel where red/blue swap is required.
=> linux-capture: Bind texture after GS_GL_DUMMYTEX changes

UI/window-basic-main.cpp
This sets the tooltip when the pause is toggled. The toggle code was simplified by removing duplicate code.
Updating the tooltip makes it easier for users to understand what the button is doing. The code was simplified because it would be easier to set the tooltip with less duplicate code. 
I ran the program and saw that the tooltips were correct when pausing/unpausing.
=> UI: A couple of pause changes

plugins/obs-ffmpeg/jim-nvenc.c
This sets some nvenc API parameters used when the encoder is reconfigured, as when the bitrate is changed (dynamic bitrate).
It has been reported that jim-nvenc with dynamic bitrate sometimes gets stalled mid-stream.
This does not occur with ffmpeg nvenc.
I've set additional parameters which I used with Timo when we implemented dynamic bitrate support in ffmpeg for nvenc.
This has been tested on windows 10 with a Turing GPU.
=> obs-ffmpeg: Set some parameters for dynamic bitrate in new nvenc

libobs/obs-output.c
Fixes a possible null pointer access in the `reset_raw_output` function of outputs.
In libobs, if the audio component of an output is set to `nullptr` (through `obs_output_set_media`), the program will crash when starting an output. The crash happens in a function called `reset_raw_output`, which belongs to `obs-output.c`.
The `reset_raw_output` internal function of `obs-output.c` calls `audio_output_get_info` with a pointer to an audio component (`audio_t`) as its only parameter, and returns a pointer to information about this component. If the parameter is null, `audio_output_get_info` returns null.
However, the code that comes after the call to `audio_output_get_info` doesn't check if the returned pointer is valid. If it's not, the program crashes.
This PR fixes this issue.
Tested on …
=> libobs: add pointer check in reset_raw_output

libobs-d3d11/d3d11-duplicator.cpp, libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-subsystem.cpp
Mostly exception catch parameter consistency. Also changed feature level to print in hexadecimal.
Saw this warning and decided to clean up things nearby:
warning C4227:  anachronism used: qualifiers on reference are ignored
Didn't check every catch statement, but verified one still worked as usual. Warning is gone. Feature level prints as expected.
=> Minor D3D11 cleanup

plugins/obs-qsv11/QSV_Encoder.cpp
Removed a leftover stack variable. The code that used it has been removed.
Tired of seeing the warning for it.
Just compiled and ran. Did not actually try to use QSV, but I would be surprised if it broke.
=> obs-qsv11: Remove leftover stack variable

libobs/data/area.effect
Area downscale setting currently only works with YUV outputs. This adds
the missing DrawAlphaDivide technique.
Noticed Area downscale was a black screen in RGB output video.
Verified new technique with RGB video output. Verified other two techniques still work as intended. Used Intel GPA to verify the proper shaders were chosen in all three cases.
=> libobs: Fix Area shaders missing for RGB output

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/hotkey-edit.cpp, UI/obs-app.cpp, UI/slider-ignorewheel.cpp, UI/slider-ignorewheel.hpp, UI/source-tree.cpp, UI/volume-control.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp
This commit fixes various issues with screen readers in the main OBS interface.
Checkboxes or buttons which toggle, when receiving an activate signal from the screen reader would visually update, but not perform any action. This is because they're listening only for clicks. They should all now be listening for toggles instead.
The screen reader would navigate through the UI in the order that elements are defined in the .ui XML, and not by their row positions. The XML has been reordered so that things should be defined in their row order.
Audio track selection now says Track 1, 2, etc, rather than just the number. Various checkboxes that just say "Enable" now have accessible text that says what the enable is for (since it says "checkbox", the fact it's an enable should hopefully be clear). …
=> UI: Various screen reader fixes

plugins/win-dshow/ffmpeg-decode.c, plugins/win-dshow/ffmpeg-decode.h, plugins/win-dshow/win-dshow.cpp
Full color range seems to be active when decoding video with FFMmpeg
even when partial is explicitly selected. This should keep the range
synchronized.
Annoying to select partial color range, and get full colors.
Forum post: https://obsproject.com/forum/threads/obs-studio-24-0-release-candidate-5.109625/page-4#post-418657
Was able to reproduce the original bug. Tested fix with breakpoint inspection using Default/Full/Partial settings for both on-the-fly changes and application startup.
=> win-dshow: Fix color range when using FFmpeg decode

UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-stats.cpp
When using custom FFmpeg output mode, the check would instead use the standard recording path which is no longer visible in the settings. This commit also simplifies the checks by moving the duplicated code to a new function.
I am creating a PR instead of directly commiting as I am not sure whether creating a new public function in the OBSBasic class is the best way to allow both the main window and stats window access to the output path.
This fixes cases where users couldn't record due to the wrong output path being checked.
I tested every recording output mode to verify the free disk space matched the selected file path.
=> UI: Fix path calculation for disk space check

libobs-d3d11/d3d11-subsystem.cpp
Disable NV12 format support for WARP. This is a speculative fix since I don't have an easy way to reproduce corruption on older Windows editions.
Lots of help requests about busted WARP output.
Breakpoint inspection, and log output. NV12 is disabled when WARP is enabled, and potentially enabled when WARP is disabled.
=> libobs-d3d11: Disable NV12 format support for WARP

UI/window-basic-main.cpp, UI/window-basic-main.hpp
This fixes an issue where the multiview wouldn't update when the scenes were reordered by drag and drop. 
https://obsproject.com/mantis/view.php?id=1562
I reordered the scenes by drag & drop and the multiview was now updating.
=> UI: Fix issue where multiview doesn't update

libobs-d3d11/d3d11-duplicator.cpp, plugins/win-capture/duplicator-monitor-capture.c
Make duplicator_capture_tick the sole creater, and reference adder of
IDXGIOutputDuplication objects. This prevents a situation where
duplicator_capture::showing cause be false while
duplicator_capture::duplicator was not null at startup on background
scenes, preventing IDXGIOutputDuplication from being recreated when
DXGI_ERROR_ACCESS_LOST.
Also added OCD change to use unordered_map since keys don't need to be sorted.
Access lost can be performed by triggering a UAC prompt, and if you do that on OBS without visiting the background scenes that capture the same display, the DX object won't be recreated.
Tested broken case is now not broken. Also tested other permutations of display capture scenes without issue.
=> Fix duplicator ref count

UI/window-basic-preview.cpp, libobs/obs.c
This fixes some compiler warnings.
Makes the compiling process less spammy.
Recompiled program, warnings didn't show up anymore. Everything still works.
=> UI, libobs: Fix compiler warnings

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add ChathostessModels to the RTMP Services list.
Add ChathostessModels to the RTMP Services list to be available for our models using OBS Studio.
Server works properly when tested directly on stream custom settings.
=>  rtmp-services: Add ChathostessModels

libobs-opengl/gl-shaderparser.c, libobs-opengl/gl-subsystem.c, libobs-opengl/gl-windows.c, libobs-opengl/gl-x11.c
There don't appear to be any GPUs that support 3.2, but not 3.3. GLSL
330 maps to HLSL Shader Model 4, so this will theoretically make shaders
programs less likely to diverge, particularly for behavior around NaNs.
I'm using HLSL SM4 behavior for NaNs, and I think this makes things less likely to regress for OpenGL.
Verified 3.3+/330+ versions printed in log output on Windows (4.6), Mac (4.1), and Ubuntu WSL (3.3). Still requesting 3.2 for Mac, only options are 3.2 and 4.1, with the expectation that we get at least 3.3 back.
Tested Lanczos NaN behavior is as expected, min() returns non-NaN term. Breakpoint-inspected anisotropic extension code paths when implemented (Mac), and not implemented (Ubuntu WSL).
Went through NVIDIA/AMD/Intel GPU lists on Wikipedia to verify there aren't any that …
=> libobs-opengl: Require OpenGL 3.3 instead of 3.2

UI/window-basic-main-transitions.cpp
When a transition is running and "Duplicate Scenes" is enabled in Studio Mode, the scenes are duplicated without their names and it makes it impossible to know the names of the source and destination scenes.
This PR fixes this behaviour by setting proper names (from their origins) on scenes duplicated by the "Duplicate Scenes" functionality of Studio Mode.
It started as a [bug report for obs-websocket](https://github.com/Palakis/obs-websocket/issues/259). I think fixing names on duplicated Studio Mode scenes could benefit other plugin developers as well, unless it is an issue or not the right fix for this situation.
Tested on macOS with obs-websocket 4.6.1 and the "Duplicate Scenes" option enabled, watching for the contents of the "from-scene" and "to-scene" properties on the …
=> UI: set names on scenes duplicated for Studio Mode

UI/obs-frontend-api/obs-frontend-api.h, UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp
This PR adds the `OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED` event to the Frontend API and ties it to value changes of the global "transition duration" control in the main UI.
The motivation behind this is to complement the transition duration getter and setter functions (`obs_frontend_get_transition_duration` and `obs_frontend_set_transition_duration`) provided by the Frontend API with an event that gives the possibility to keep track of changes on that value.
The context behind this is that I'd like to fix how obs-websocket keeps track of transition duration changes. Currently it's a ugly hack that:
- Fetches the pointer of the main window from the Frontend API (and casts it to a QMainWindow type)
- Calls `QWidget::findChild` to find a `QSpinBox` named `transitionDuration`
- Then …
=> Frontend API: provide a "transition duration changed" event

UI/qt-display.cpp, libobs-d3d11/d3d11-subsystem.cpp, libobs-opengl/gl-windows.c, libobs-opengl/gl-x11.c, libobs/graphics/graphics.c
Use FLIP_DISCARD on Windows 10 to skip a copy, and BGRA on D3D for supposed benefits. The swap chain format field is ignored on Mac and Linux.
FLIP_DISCARD info:
https://devblogs.microsoft.com/directx/dxgi-flip-model/
BGRA info:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/f56e4449-f3e1-491e-9f64-e65e989a518a/best-swap-buffer-format-rgba-or-bgra-
"I believe there are some flip optimizatoin benefits to using BGR rather than RGB."
Trying to save unnecessary GPU work.
Tested WIndows 10 D3D/GL, Mac, and Ubuntu (via WSL) still work. Test OBS runs on Windows 7 using Parallels.
Verified Windows 10 respects flip mode change using PresentMon tool.
DXGI_SWAP_EFFECT_DISCARD: "Composed: Copy with GPU GDI"
DXGI_SWAP_EFFECT_FLIP_DISCARD, main preview: "Composed: Flip" …
=> D3D swap chain enhancements

libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-subsystem.cpp, plugins/win-capture/graphics-hook/d3d12-capture.cpp, plugins/win-capture/graphics-hook/d3d9-capture.cpp, plugins/win-capture/graphics-hook/gl-capture.c
It appears OBS never successfully supported 9.3 because it wasn't compiling against a 9.x shader profile. Just use 10.0 as the baseline.
Make code intention clearer.
With debugger inspection/modifcation, verified 9.3 actually fails when loading shader bytecode, and 10.0 succeeds. Also verified straight path successfully uses 11.0 on my card.
GL and D3D9 game capture still work.
=> Use D3D_FEATURE_LEVEL_10_0 as baseline

CMakeLists.txt
This patch just removes the `-Werror=implicit-function-declaration` option from the `CMakeLists.txt` from `CMAKE_CXX_FLAGS` (GCC/CLANG).
Apparently this option is not valid when run in `C++` mode. This options has been silently ignored until now. Staring with GCC 9 the compiler will complain about this option when run in C++ mode:
```
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
[ 73%] Building CXX object UI/CMakeFiles/obs.dir/obs-app.cpp.o
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
[ 73%] Building CXX object UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-ouput-ui.dir/DecklinkOutputUI.cpp.o
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ …
```
=> cmake: no -Werror-implicit-function-declaration for C++

UI/frontend-plugins/frontend-tools/forms/output-timer.ui
output timer tab stop order
The default tab stop order is strange.
On windows x64
=> frontend-tools: output timer tab stop order

libobs-d3d11/d3d11-subsystem.cpp
Add GPU driver version to info log. DX version string is not the nicest, but no need for IHV library.
Handy to know what the GPU driver version is, so we can tell if users are out of date.
Driver strings were reported correctly when tested on AMD and Intel.
Adapter 0: Intel(R) HD Graphics 530
Dedicated VRAM: 134217728
Shared VRAM:    4221272064
Driver Version: 26.20.100.7212
output 0: pos={0, 0}, size={2560, 1440}, attached=true
Adapter 1: Radeon RX Vega
Dedicated VRAM: 4220833792
Shared VRAM:    4221272064
Driver Version: 26.20.13003.1007
output 0: pos={2560, 16}, size={3840, 2160}, attached=true
=> libobs-d3d11: Add GPU driver version to log

libobs-d3d11/d3d11-subsystem.cpp
Log display refresh rates, and monitor names.
Common issue for mismatched monitor refresh rates to cause problems.
Ran on my current PC.
Adapter 0: Intel(R) HD Graphics 530
Dedicated VRAM: 134217728
Shared VRAM:    4221272064
output 0: pos={0, 0}, size={2560, 1440}, attached=true, refresh=120, name=ROG PG279Q
Adapter 1: Radeon RX Vega
Dedicated VRAM: 4220833792
Shared VRAM:    4221272064
output 0: pos={2560, 0}, size={3840, 2160}, attached=true, refresh=60, name=DELL UP2718Q
=> Log display refresh rates, and monitor names on D3D11

plugins/linux-capture/xhelpers.c, plugins/linux-capture/xshm-input.c
Fixed a bug where randr was counting screen based upon number of crtcs even if they were not configured.
Fixes [this mantis issue](https://obsproject.com/mantis/view.php?id=1555) where multiple monitors were being given with 0 width and height.
I was able to reproduce the bug on my system. Tested fix by running through line-by-line where the misreporting of screen numbers was occurring.
=> linux-capture: Fix bug where multiple 0x0 windows would appear

libobs/obs-source.c, libobs/obs.h
export obs_group_from_source to allow it to be used
I need it to loop through the scene items of a group
Using it in a lua script
=> libobs: Export obs_group_from_source

UI/visibility-item-widget.cpp, UI/visibility-item-widget.hpp
This removes unnecessary code from the visibility item widget because the scene item list widget is its own class now.
This simplifies code.
The filters list widget still works as expected.
=> UI: Remove unused code from visibility item widget

UI/window-basic-filters.cpp
This adds the ability to rename the filters with F2 (Return on Mac).
https://ideas.obsproject.com/posts/532/f2-to-quickly-rename-filters
Renamed filters with the shortcut.
=> UI: Add ability to rename filters with F2 (Return on Mac)

CI/before-script-linux.sh, deps/libcaption/CMakeLists.txt
This is a small fix for compiling libcaption for compilation on Linux, `-wPIC` should only be set on linux if i have done the checking correct
This is to allow caption plugins like [OBS-Captions-Plugin](https://github.com/ratwithacompiler/OBS-captions-plugin/) to be installed on the linux version of OBS. This was blocked mainly by this compilation error 
```
/usr/bin/ld: ../deps/libcaption/libcaption.a(mpeg.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
```
compiled OBS 
**Enviroment info**:
uname output: `Linux IoansThinkpad 5.3.4-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 5 13:44:11 UTC 2019 x86_64 GNU/Linux`
Hardware: Lenovo ThinkPad T450 i5-5200U RAM 12gb 
=> cmake: Compile option to fix libcaption linking

CI/install-dependencies-linux.sh
Linux CI builds are currently failing due to an issue with a third-party PPA, this PR removes that PPA as it's no longer required.
This PPA fails during build, and we no longer support Trusty anyway
CI completes successfully with no errors.
=> CI: Remove dead PPA to fix Linux build failure

UI/window-projector.cpp
This fixes an issue where the preview projector stopped working when toggling studio mode.
https://obsproject.com/mantis/view.php?id=1401
I created a preview projector and switched in and out of studio mode, and everything works as it should.
=> UI: Fix issue with preview projector

plugins/obs-ffmpeg/obs-ffmpeg-output.c
Note: may need more testing with other encoders and usage scenarios.
Certain ffmpeg parameters such as "bufsize" or "maxrate" have to be applied to `context` rather than to `context->priv_data`. In order to make sure options are still passed to the encoder setting set `AV_OPT_SEARCH_CHILDREN`.
This PR fixes setting certain options for ffmpeg encoders such as "maxrate" or "bufsize" which were previously unavailable.
Tested on Windows with the latest ffmpeg deps and the NVENC and x264 encoders (based on a bug report about not being able to set maxrate/bufsize). Verified to now pass both parameters and encoder settings successfully.
=> obs-ffmpeg: Use av_opt_set on context instead of priv_data

libobs-d3d11/d3d11-subsystem.cpp, libobs-opengl/gl-subsystem.c, libobs/graphics/device-exports.h, libobs/graphics/graphics-imports.c, libobs/graphics/graphics-internal.h, libobs/graphics/graphics.c, libobs/graphics/graphics.h, libobs/obs-video.c
We really shouldn't be resetting duplicator state as part of gs_flush.
gs_begin_scene is not ideal because it is called twice per frame, and
only after duplicators have been ticked. Even though it makes no
user-facing difference, it makes more logical sense to reset at the top
of the frame than the bottom.
It's just too gross to have this as part of gs_flush. I'd like to get rid of redundant flush calls one day, which would mean we may not have one every frame to reset the duplicators.
gs_begin_frame may also come in handy for adding frame boundary profiling markers.
Breakpoint-inspected that duplicators only acquire one image per frame.
=> libobs: Add gs_begin_frame for duplicators

plugins/obs-outputs/rtmp-stream.c
I've found another compiler warning where it warned about comparisons between signed and unsigned integers. 
Cleaning up warnings.
Warning doesn't show up anymore.
=> rtmp-stream: Fix comparison between signed and unsigned ints

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-basic-stats.hpp
This adds a hotkey to reset stats.
https://ideas.obsproject.com/posts/374/stats-panel-reset-hotkey
Created hotkey and the stats were reset as expected.
=> UI: Add stats reset hotkey

UI/properties-view.cpp
Checkable property groups in OBS Studio currently don't call any callbacks, including the update callback. This fixes that issue.
I needed an update whenever a property group was checked or unchecked.
Tested against new changes in Stream Effects, which use checkable Property Groups.
=> UI: Fix checkable property groups

libobs-d3d11/d3d11-rebuild.cpp
Don't build input layout without VS inputs on device loss.
Building an input layout without VS inputs will result in a DX failure, and OBS exception (crash). Having VS without inputs is relatively new; the creation logic was fixed up, but not the rebuild logic.
Used debugger to force-call RebuildDevice(). Crashes without change. Doesn't crash with change.
=> libobs-d3d11: Fix null input layout rebuild

plugins/win-capture/window-helpers.c
These are additional internal windows processes that should not be listed in the Windows window capture dropdown. Ideally, this list should be updated to allow for external updates so that a new release is not necessary for this to be maintained.
These show up in the window capture list and were confusing/cluttering. Since they cannot be captured anyway, no reason to have them listed.
Compiled on windows 10 x64, after adding these to the blacklist they no longer show up in the window capture list. All other executable correctly enumerate. 
=> win-capture: Add additional exe to window capture blacklist

UI/forms/OBSBasicSettings.ui, UI/window-basic-settings.cpp, plugins/win-wasapi/enum-wasapi.hpp, plugins/win-wasapi/win-wasapi.cpp
This adds the device's sample rate to the log file when a WASAPI device is initialized. If the sample rate detection fails, a hyphen is shown instead.
As part of this change, I also noticed the display of the sample rate in Settings -> Audio was a little hard to read *and* slightly inaccurate, and fixed that too.
```
WASAPI: Device '5.1 Speakers (High Definition Audio Device)' [48000 Hz] initialized
WASAPI: Device 'CABLE-B Output (VB-Audio Cable B)' [48000 Hz] initialized
```
Often, if a user runs into audio de-sync issues or clicking sounds, it's caused by an inconsistency between a device's sample rate, and the sample rate configured in OBS. This will make troubleshooting such situations easier.
* Configured a Desktop Audio Device, Mic/Aux device, and Audio Input Capture Device, then …
=> Log Sample Rate for WASAPI devices

.gitignore
Ignores additions and changes to any configurations in VSCode.
Adds `.vscode/*`to the .gitignore file. 
Myself and other users don't want to see this in staging because they should never be committed. 
Files in .vscode/ no longer populate git staging.
=> git: Add VSCode working dir to .gitignore

UI/window-basic-main-outputs.cpp
There was a bug in simple mode where the unset value for recording audio bitrate was being used. This fixes simple recording so that bitrate (192kbps) is properly set. This is a replacement for #2143
Thanks @pkviet for the finding the actual problem.
Fixes a bug which caused audio bitrate to be set improperly to 128. This fix sets it to 192 as originally intended.
Applied the change, observed in both logs and resulting file the audio bitrate is properly set to 192
=> UI: Fix audio bitrate not being set in simple mode

UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp
There are instances where XFetchName will fail to get a window's name, even if it has a WM_NAME property set [[example](https://github.com/herbstluftwm/herbstluftwm/issues/64)]. Add a fallback to XGetWMName when this occurs.
When OBS enumerates windows for the automatic scene switcher on Linux, any windows that return an empty string when passed to GetWindowTitle are ignored [[1](https://github.com/obsproject/obs-studio/blob/master/UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp#L141)]. Since GetWindowTitle relies on XFetchName, some windows are skipped during the enumeration (e.g. Chrome).
I verified that Chrome as well as all the windows listed before the change were present in the dropdown menu for the automatic scene switcher. I also verified that automatic scene …
=> UI: Fall back to XGetWMName if XFetchName fails

plugins/win-capture/graphics-hook/gl-capture.c
*This PR has been edited/clarified by Jim*
When hooking a program that has both DirectX and OpenGL contexts in use, it is possible to cause a crash on shutdown due to capture_active() returning true when an OpenGL context is deleted.  Normally, when capturing an OpenGL program, this would not happen because the 'active' variable would not be set due to OpenGL capture not being initialized, but if DirectX is captured while an OpenGL context is available, and OpenGL could not load these required functions, then GL can crash due to trying to use unavailable functions.
This case is extremely rare and doesn't happen under normal circumstances; only if a program is using both DirectX and OpenGL within the same program simultaneously, and *only* if OpenGL could not load the required functions. …
=> win-capture: Fix rare crash when OpenGL programs exit with graphics-hook

plugins/rtmp-services/rtmp-common.c
Type checks "profile" before attempting to use service recommended settings.
This fixes ovewritting hidden "profile" setting in ffmpeg vaapi which is
a number and not a string. It also shouldnt be overwritten as it is
required to be constrainedbaseline on some AMD hardware for the encoder to work, so I didn't make it a string.
Tested by attempting vaapi encoding and confirming the profile is not overwritten. nvenc still overwrites profile as expected and disabling enforce service settings works as expected.
=> rtmp-services: Type check apply_encoder_settings

UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp
This fixes an issue where using a quick transition, it would change
the main transition as well.
I found it annoying when using a quick transition, then using the normal transition, it would use whatever the quick transition was.
I triggered a quick transition, then I transitioned normally, and everything worked as expected.
=> UI: Fix main transition being set to the quick one

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/window-basic-main-outputs.cpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
This makes the FLV track selection radio buttons instead of check boxes.
Since FLV can only have one track, it makes sense to use radio buttons. Before, if more than one track was selected, and FLV was used, a recording error would happen. This makes that error not even possible.
I recorded with FLV and other formats, and everything worked as expected.
=> UI: Use radio buttons for FLV track selection

UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp, UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.h, UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp, UI/frontend-plugins/decklink-output-ui/forms/output.ui
Adds a UI label to show the current state of the decklink output.
Previously users had to remember the state of the output, this should add some sanity to this
Tested on Windows starting and stopping decklink outputs
=> decklink-ui: Show the state of outputs in the decklink dialog

CMakeLists.txt, UI/platform-windows.cpp, deps/obs-scripting/CMakeLists.txt, deps/obs-scripting/obslua/CMakeLists.txt, deps/obs-scripting/obspython/CMakeLists.txt
Use C++17 for compilation, enforce CMake 3.10 as minimum, and set explicit policy to clean up SWIG warnings.
Prerequisites:
I would like to eventually implement features like Windows 10 ScreenCapture, which requires WinRT, which requires C++17 to use the projection headers. I would imagine more features will eventually require a more recent version of C++, so it's probably worth biting the bullet at some point.
CMake 3.10 is required for CXX_STANDARD VS support.
An alternative fix for SWIG warnings would be to use the new policy, but I don't know what SWIG does, and what the consequences would be.
Compiles and runs on Windows/Mac/Linux.
=> CMake 3.10, C++17, SWIG warnings

plugins/win-dshow/win-dshow.cpp
=> win-dshow: fix H264 to mjpeg issue

plugins/rtmp-services/CMakeLists.txt, plugins/rtmp-services/data/services.json, plugins/rtmp-services/rtmp-common.c, plugins/rtmp-services/younow.c, plugins/rtmp-services/younow.h
Dear OBS maintainers,
We would like to merge our YouNow integration into the master branch. We have introduced minimal changed to support server discovery from our end, very similar to the way it’s done by Twitch and Mixer.
Thank you,
Roman.
=> rtmp-services: Add YouNow service and implement ingest lookup

plugins/win-dshow/win-dshow.cpp
The biHeight field can be negative, leading to crashes on some cards
like VisionRGB-E1S. Adding flip support is fairly straightforward.
There also appears to be a hack to automatically flip for RGB formats,
but I wish to remove it because it seems to fight with this change. We
already have a separate vertical flip checkbox to deal with non
compliant behavior.
Fix crash on VisionRGB-E1S, and support negative heights robustly.
VisionRGB-E1S does not crash any more, and appears vertically correct.
=> win-dshow: Support bottom-up DIBs

UI/CMakeLists.txt, cmake/Modules/ObsHelpers.cmake, deps/obs-scripting/obs-scripting-python-import.c, deps/obs-scripting/obspython/CMakeLists.txt
Make python scripting work on MacOS with a user supplied python version, just like on Windows.
Python scripting is really useful and would be nice to have available on MacOS but currently requries some manual changes to get it to work.
Manually tested locally on my machine (10.14.6) against homebrew and macports pythons.
On a fresh 10.14.0 VM with only a Azure CI built OBS installed and homebrew python and macports pythons. 
All worked succesfully, with both python 3.6 and 3.7 depending on what the respective OBS was built with.
Minor issue is that changing the interpreter after one has been loaded does require an OBS restart to use the new one (but I think Windows behaves the same based on a quick try?).
=> obs-scripting: Fix Python on MacOS

UI/window-basic-interaction.cpp
Removes the '?' icon in the titlebar of Interact windows
Consistency with all other windows, as we don't currently use the help icon
Tested on Windows 10 with a browser source.
=> UI: Remove help icon from Interact titlebars

plugins/obs-text/gdiplus/obs-text.cpp
Pull request #2079 added localisation functions but without the needed include of the `locale` headers, breaking the build of obs-text under VS 2019
Fix for broken build
Adding the include fixes the build on Visual Studio 2019 (x64 Windows 10)
=> obs-text: add missing include to fix build

CI/before-deploy-osx.sh, CI/install/osx/packageApp.sh, deps/obs-scripting/obs-scripting-python.c
Fixes python in the new MacOS .app bundles. 
Moves `obspython.py` and `_obspython.so` to the binary directory like the Lua one and adds the bin directory as python import path so it can find and import `obspython`. The bin path needs to be looked up at runtime since app bundles don't set the current working dir so relative paths aren't an option. 
Keeps adding the normal SCRIPT_DIR path for running out of rundir.
Python doesn't work anymore on MacOS when run from the .app bundle since folder structure changed a bit and it can't find obspython.
Locally on 10.15 with macports python 3.7 against a locally build OBS and against the Azure CI built OBS.
In a 10.14.0 VM with homebrew and macports python 3.7 against OBS built via Azure CI.
=> obs-scripting: Fix Python in new MacOS .app bundles

UI/auth-twitch.cpp, UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/obs-app.cpp, UI/window-basic-main.cpp, UI/window-basic-settings-stream.cpp, UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
Adds dropdown menu in stream settings that offers the option to change which twitch chat extension will be used in the "Chat" dock.
(Only visible when authenticated with Twitch.)
BTTV and FFZ conflict in some cases, removing either will upset people so instead make it a choice for users: None, BTTV, FFZ, or both.
Windows 10, switched between services and options on offer, made sure that they all work.
=> UI: Add dropdown for Twitch chat extension

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This fixes an issue where if swap scenes was enabled in studio mode, double clicking to transition wouldn't swap the scenes.
https://obsproject.com/mantis/view.php?id=1554
In studio mode I enabled double click and swap mode and transitioned. Everything now works as expected.
=> UI: Fix swap scene issue with double click mode

plugins/mac-vth264/encoder.c
This PR is the mac-vth264 version of edfc2be in obs-qsv11.  There are no other changes.
On macOS, when streaming with the vth264 hardware encoder, network congestion can trigger OBS to drop frames and never stop dropping frames.  The [obs-qsv11 plugin had this issue](https://obsproject.com/forum/threads/15-4-16-5-quicksync-issue-kbps-dropped-to-0-without-crash.57417/) from OBS Studio 0.16.0 to 0.16.5, but it was fixed in edfc2be for 0.16.6.  It was not fixed for mac-vth264.  This PR ports the fix from obs-qsv11 to mac-vth264, allowing users to recover from dropping frames with the Apple hardware encoder.
This has been reported and discussed in the OBS Project forums:
* https://obsproject.com/forum/threads/apple-hardware-encoder-destroys-stream.82677/
* …
=> mac-vth264: Manually mark priority bits for frames

libobs-d3d11/d3d11-subsystem.cpp, plugins/obs-ffmpeg/obs-ffmpeg.c
This change replaces string / substring matching on the device name or description with static values from the PCI database, allowing more precise matching of devices and vendors.
This allows more granular targeting of devices that potentially share the same names but with different features. It also helps avoid possible false positives as in c18aab29.
I verified the blacklisted adapter list was being matched against the device IDs instead of strings. All devices IDs were verified against the PCI database after entry to avoid typos that might have caused matching on the wrong ID.
=> Use PCI database IDs instead of string matching for devices

UI/window-basic-main.cpp, UI/window-basic-main.hpp
When selecting multiple sources and copying them (through the context menu or Ctrl+C) and then pasting them (as references or duplicates) all of the selected sources that were copied are now pasted instead of just the first selected source. 
Implements the feature requested here:
https://obsproject.com/mantis/view.php?id=1560
- Windows 10 x64  
- Manually verified that the behavior for single source copy/pasting remained consistent between the release version of OBS and the proposed changes.
- Verified that pasting as references works as intended for multiple sources (i.e. they all function as references). 
=> UI: Add copy/paste of multiple selected sources

UI/window-basic-main.cpp
Simply fixes the incorrect status icon with recording. I tested out a couple of different iterations and they all appeared to be working.
Fixes issues from #2093 
Simply tested on my linux machine
=> UI: Fix wrong icon if recording stopped while paused

UI/data/locale/en-US.ini, UI/window-basic-main.cpp, UI/window-basic-main.hpp, UI/window-projector.cpp, UI/window-projector.hpp
This adds the ability for projectors to change between fullscreen and windowed mode. In windowed mode, when switching to fullscreen, the user can select which monitor to set it to. Also, when in fullscreen mode, the monitor can be changed to a different one. These options are accessed in the right-click menu of the projector. This also simplifies the saving and loading of projectors code.
This makes the projectors a more powerful tool.
I've created different types of projectors and switched between modes and monitors. 
- New feature (non-breaking change which adds functionality) -->
=> UI: Add ability to change projector type

plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
In ffmepg 4.2 setting qp overrides bitrate, this option isnt exposed
currently so users cannot disable it.
https://obsproject.com/mantis/view.php?id=1534
Tested on ubuntu 18.04 with ffmpeg 4.1, no regression when recording. Someone with an affected device on ffmpeg 4.2 has confirmed this resolves the issue.
Removal of some settings, users might have tried to use them via json but they probably wouldnt have worked.
=> obs-ffmpeg: Remove unexposed vaapi parameters

plugins/obs-outputs/CMakeLists.txt
Adds a status message during configuration about ftl-outputs being enabled.
Without this its hard to review downstream packagers' logs to know if they have configured the build correctly for what users expect in a default install.
cmake outputs a line as expected during configuration.
Build System
=> obs-outputs: Log FTL during configure

libobs/obs-windows.c, libobs/obs.c, plugins/win-wasapi/win-wasapi.cpp
Balance COM initialization calls, log failures, and have main thread request STA rather than MTA.
Current code misleads people into thinking MTA is used on the main thread when it is not because Qt initializes COM first.
Unbalanced initialization calls are not causing any known issues, but no need to take chances.
Breakpoint inspection for all code paths, and verified log output for all branches, including paths that require some fakery to exercise.
=> Clean up COM initialization

plugins/linux-capture/xcompcap-main.cpp, plugins/linux-capture/xcursor.c, plugins/linux-capture/xcursor.h
When cropping the left or top of a window capture, OBS would
misalign the drawn cursor, placing it as if the entire window were
being captured. Instead, offset the captured cursor by the same
number of pixels, thus placing the cursor back where it belongs.
Fixes a bug in window capture with the cursor visible and a left/top crop.
Tested on Linux. Needs Windows testing but not expected to have any impact (applies only to X11).
=> libobs: Fix cursor draw position bug when cropping a window capture.

UI/api-interface.cpp, UI/obs-frontend-api/obs-frontend-api.cpp, UI/obs-frontend-api/obs-frontend-api.h, UI/obs-frontend-api/obs-frontend-internal.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This will allow customized setups to spawn whichever projectors they need, whenever they need them. It's more flexible than simply saving and restoring the last-used projectors, allowing more complicated setups that are managed by an external script.
=> UI: Create an API to open projectors

azure-pipelines.yml
This change will result in build artifacts being kept for PRs that have the "Seeking Testers" label applied to them.
The purpose of the Seeking Testers label is to get testers of a particular feature. Limiting this to only people who are able to build OBS for themselves means we get fewer testers and opportunities to spot bugs early. By keeping the build artifacts of PRs with the label applied, a test build is created for us that can be easily shared.
This was tested using my accounts GitHub fork connected to Azure Pipelines.
- CI (a change to continuous integration scripts)
=> CI: Keep artifacts for PRs labelled "Seeking Testers"

deps/media-playback/CMakeLists.txt, libobs/CMakeLists.txt, libobs/graphics/quat.h, libobs/graphics/vec3.h, libobs/graphics/vec4.h, libobs/media-io/format-conversion.c, libobs/obs-audio-controls.c, libobs/util/aarch/check.h, libobs/util/aarch/hedley.h, libobs/util/aarch/mmx.h, libobs/util/aarch/simde-arch.h, libobs/util/aarch/simde-common.h, libobs/util/aarch/sse.h, libobs/util/aarch/sse2.h, libobs/util/sse-intrin.h, plugins/decklink/audio-repack.c, plugins/win-capture/game-capture.c
This pull request enables compiling on Aarch64, while retaining full previous compatibility.
I still need someone who can test against PowerPC.
To do this, I've added SIMDe as a dependency, which provides an audited universal SIMD abstraction layer.
This provides full performance for the native intrinsics, while allowing relatively fast translation for aarch64.
SIMDe also includes Hedley, an acceleration layer that can improve performance of existing code.
I've converted all currently used x86 intrinsics to use the SIMDe layer.
I've enabled automatic aarch64 detection in cmake.
**EDIT** 
SIMDe is no longer a dependency, I took a snapshot of the files actually used and put them in libobs/util/aarch.
I've written an abstraction layer to translate between the native intrinsics and SIMDe. …
=> Enable Aarch64 support via SIMDe.

libobs/graphics/quat.h, libobs/graphics/vec3.h, libobs/graphics/vec4.h, libobs/media-io/format-conversion.c, libobs/obs-audio-controls.c
sse-intrin.h is a required header now, but the implicit path breaks building addons once the headers are installed.
Fix this by making the path explicit.
Fixes compiling addons dependent on libobs.
Discovered when clean compiling obs-gstreamer
Tested building addons works correctly.
=> libobs: fix building modules once installed

libobs/util/platform-nix.c
sysctlbyname requires #include <sys/sysctl.h>.  Perhaps this previously
worked due to header pollution that has since been cleaned up in newer
FreeBSD.
I found this issue while working on adding FreeBSD CI support via Cirrus-CI, building on FreeBSD 12.1.
=> libobs: add missing FreeBSD #include to fix build

plugins/win-dshow/win-dshow.cpp
I think Logitech cameras are prone to spam errors about failing to decode app fields. Only print the first message for this benign error.
Plausible explanation: https://stackoverflow.com/questions/55439184
Log files are filling up quickly.
I remember seeing this previously, but I am mysteriously unable to reproduce. I have otherwise breakpoint inspected the new code paths with some instruction pointer fakery.
TODO: Find someone to verify this fix.
=> win-dshow: Suppress MJPEG error spam

UI/properties-view.cpp
Use desired functions instead of deprecated ones.
Clean up compiler warnings.
The selected and hidden properties were faked in debugger, and tested to save and propagate correctly.
=> UI: Fix Qt deprecation warnings

UI/window-remux.cpp
Rename QPalette::ColorRole::Background to Window.
Compiler warning when using Qt 5.13.2. ColorRole::Window exists on older Qt versions though.
Enum value is the same numerically. Verified remux dialog color is the same, and different when using another value like WindowText.
=> UI: Rename deprecated QPalette::ColorRole

UI/source-tree.cpp
This fixes an issue where the source icons were moved to the right when renaming a source.
Fixes a bug mentioned in Discord.
Renamed source and the issue didn't happen anymore.
=> UI: Fix source icons being shifted to the right

.cirrus.yml
Add a FreeBSD CI build confg, using [Cirrus-CI](https://cirrus-ci.org/).
Ensure FreeBSD continues to build (e.g. https://github.com/obsproject/obs-studio/commit/97c243fdf9b4450327a7ec2a50620a507bd22c39), complementing existing CI builds for other operating systems using Travis.
Note it was simple enough to install dependencies directly in .cirrus.yml, but if desired I'll change this to add a CI/install-depndencies-freebsd.sh akin to -linux.sh and move the `pkg install` step there.
Next step would be for obsproject to add the Cirrus-CI GitHub application and allow it to access the repository, as with Travis.
Tested by via Cirrus-CI in my fork: https://cirrus-ci.com/task/4868993894055936
=> CI: Add Cirrus-CI config for FreeBSD builds

plugins/decklink/decklink-output.cpp
Fix compiler warnings about long long -> int conversion.
Less build spam.
Compiler warnings have been fixed. Program did not crash.
=> Decklink: Explicit casts for truncation warnings

UI/window-basic-settings.cpp
Don't modify theme if already set. This includes reselecting the existing selection, and cancelling out of settings altogether. Takes a long time (7 seconds) in debug builds.
Speed up programming workflows.
Selected all four themes redundantly and not. Cancelled out of settings redundantly and not. Themes were applied and not as expected without delays.
=> UI: Don't modify theme if already set

UI/window-basic-settings.cpp
Reload the theme even if the user selects the currently selected theme from the settings dialog.
This is useful for people making changes to theme files.
Theme now reloads when selecting the currently selected theme.
(Not really "new" since this behavior existed in the last release.)
=> UI: Allow switch to existing theme to reload

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/forms/OBSBasic.ui, UI/scene-tree.cpp, UI/scene-tree.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This PR adds an option to the right click menu in the scenes widget to switch modes. When in regular list mode, it'll let you select grid mode, and in grid mode, it'll let you select list mode. Grid mode changes the scenes widget to have a grid of buttons for scenes rather than a list, much like XSplit.
To provide a familiar look and feel to people coming over from XSplit, and to show more scenes compactly in certain situations.
This has been tested on a Windows 10 PC using all 4 themes shipped with OBS.
=> UI: Add Grid Mode to Scenes Widget

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/ui-validation.cpp, UI/ui-validation.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
The first commit PR moves UI verification to another class to be reusable.
The second commit adds checks to "Start Streaming" user action prompting users to fill out streaming URL, service, and stream keys if they're missing. 
When we use the server error to respond to user's failing to start a
stream it is slow to return an error and unclear to the user what went
wrong. 
In the case of preset services (Youtube, Facebook, Twitch) we check there is a Stream Key before
attempting to start a stream.
In the case of "custom" we only verify there is a URL since for some
services that's all that is required or the user may use user/password
authentication.
In both cases the short explanation and Settings link button will guide users to solve the issue more smoothly. 
MacbookPro. MacOSX 10.14.6. …
=> UI: Streaming Settings Validation On Stream Start & User Help

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Facebook Live now recommends 6000kbps for most streamers and the auto
capping is clamping users to 4000kpbs. This fixes the new suggested
setting.
Gaming streamers are now recommended to stream at 6Mbps on FB Live so updating the recommendation. 
If the streamer doesn't find the way to turn off rate limit enforcement they'll still stream at 4mbps even with 6mbps entered into the form. This fixes that. 
Can now stream at 6mbps with enforcer on. 
=> rtmp-services: Increase FB max bitrate to 6Mbps

CI/before-deploy-osx.sh, CI/install/osx/Info.plist, CI/install/osx/packageApp.sh
This fixes up a few last issues that were preventing signing the application.
*  Switching to -R fixes the symlinks in the frameworks
*  The QtNetwork framework is copied over differently than the other frameworks so we had to remove some stuff from it that was making signing angry
*  Also the binary name in the PList is case sensitive so we fix that.
Trying to get a new version of OBS out with Catalina fixes.
Built, signed, notarized, awaiting deploy :)
=> CI: Fix framework symlinks when building osx app

libobs/obs-cocoa.m
An attempt to fix a hotkey crash on macos
=> libobs: Null check hotkey device on macos

plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Enable choosing CBR, CQP and VBR.
Add the ability to choose between CBR, CQP and VBR, with proper setup of the ffmpeg options to actually use the chosen rate control.
I believe CBR is the recommended mode for streaming, but is not so great for recording locally. I’d like the ability to record with a CQP setting instead of CBR.
FFmpeg version 4.2 introduced the usage of the rc_mode option for VAAPI. It also, when rc_mode is not set, changed to order in which it tests the options (rc_max_rate, bit_rate, qc) to determine which rate control mode to use.
To keep the behaviour compatible with previous versions of FFmpeg and obs, we set the options only when needed :
- CQP : "qp"
- CBR : "bit_rate", with "rc_max_rate" set to be the same as "bit_rate"
- VBR : "bit_rate", with "rc_max_rate" if set …
=> obs-ffmpeg: Enable VAAPI Rate Control

CI/install/osx/packageApp.sh
1. Recursively add write permission to entire QT Network framework in order to delete the Headers (as per #2236).
2. Replace deprecated `cp -r` with `cp -R`
QT files may not have write permission, resulting in these commands prompting for override permission to delete each file inside the Headers path:
```bash
rm -r ./OBS.app/Contents/Frameworks/QtNetwork.framework/Headers
rm -r ./OBS.app/Contents/Frameworks/QtNetwork.framework/QtNetwork.prl
rm -r ./OBS.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Headers/
```
=> CI: Fix error deleting QT network framework on OSX

UI/window-basic-auto-config.cpp, plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
I added one more service to "plugins/rtmp-services/data/services.json"
It's called YouStreamer (https://youstreamer.com/en.html), it provides re-streaming services.
Also 2 files has been changed: 
"UI/window-basic-settings-stream.cpp" and "UI/window-basic-auto-config.cpp".
In both cases there is a minor update. When you select youstreamer service - there will be a link button to redirect to the page with stream key. 
=> rtmp-services: Add YouStreamer

plugins/obs-qsv11/QSV_Encoder.h, plugins/obs-qsv11/obs-qsv11.c
I've added, and named all Target Usage options, TU6 most definitely should be exposed, as it's quality is far superior to the current "speed" option.
Used the terminology from [Intel's own publication](https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/cloud-computing-quicksync-video-ffmpeg-white-paper.pdf), left old settings there for compatibility reasons.
Currently untested.
=> obs-qsv: Add all target usage options

UI/obs-app.cpp, UI/window-basic-settings.cpp
This change makes it so OBS will still launch even if a theme is missing. This change also deprecates the "CurrentTheme" config key, and is replaced by "CurrentTheme2".
The code to make sure OBS fell back to the System theme in case of a missing theme had been accidentally removed. Changing the key prevents a new version of OBS setting a theme that doesn't exist in an older version, which would prevent that version from launching.
This has been tested by changing the old CurrentTheme key to a theme that didn't exist, and checking that OBS launched with the System theme after a dialog noting the missing theme. After changing the theme, I checked the CurrentTheme2 key is used instead.
=> UI: Ensure OBS launches when theme is missing

plugins/linux-v4l2/CMakeLists.txt, plugins/linux-v4l2/v4l2-controls.c, plugins/linux-v4l2/v4l2-controls.h, plugins/linux-v4l2/v4l2-input.c
Video4Linux exposes controls for capture devices.  This commit adds
those controls to the properties window for v4l2-input devices.
Few things to mention here.  This dynamically adds properties and as far as I can tell, this isn't something that's been done in OBS before, so it's kind of hacky.  Also, right now properties don't get cleared if you switch devices which leads to all sorts of issues.  I'm working on that, but it's going to be hacky too, requiring a hidden setting to the device or something.
This also means that I can't mark the strings for translation, as they're coming from the v4l driver.  There _might_ be a way to load in the v4l get text domain and do it that way, but I haven't investigated that yet.
=> linux-v4l2: add support for controls

UI/window-basic-main-outputs.cpp, plugins/obs-ffmpeg/CMakeLists.txt, plugins/obs-ffmpeg/ffmpeg-encoded-output.c, plugins/obs-ffmpeg/ffmpeg-encoded-output.h, plugins/obs-ffmpeg/obs-ffmpeg-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.h, plugins/obs-ffmpeg/obs-ffmpeg.c
This PR adds a new `ffmpeg-encoded-output` output to the `obs-ffmpeg` plugin.
**Motivation**:
OBS streaming workflow uses the stream settings page to configure streaming to an existing service such as Twitch or to a custom URL. The upstream code assumes streaming over the RTMP protocol. With this PR, non-RTMP protocols such as SRT, or any other FFmpeg-supported protocol, can be used.
**Details**:
1. The new output is based on rtmp-stream - ffmpeg is used to mux to MPEG TS and send.
1. The new output can be used to stream to SRT end points.
1. Container, video and audio codecs are hard coded to MPEG TS, H264 and AAC respectively.
**Building**:
1. build and install `libsrt`
1. Configure ffmpeg with `--enable-libsrt` and build + install
1. Build and install branch
**Running**:
1. Under …
=> obs-ffmpeg: UI and back-end for obs-encoded streaming over various protocols such as SRT

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, UI/data/locale/en-US.ini, UI/window-basic-adv-audio.cpp, UI/window-basic-adv-audio.hpp
This adds a right click option in the advanced audio properties to switch between dB and percent.
Several users have stated they would rather use percent than dB.
I opened the advanced audio properties and switched between volume types and everything works as expected.
=> UI: Add option to use percent instead of dB

deps/obs-scripting/obslua/obslua.i, deps/obs-scripting/obspython/obspython.i
Adds matrix3.h and matrix4.h to the scripting build so you can create matrix3 and matrix4 structs from Lua and Python.
Various functions available in the scripting API aren't usable currently since you can't create the matrix3 and matrix4 values needed for their arguments (without ugly hacks).
Tested with a Lua and Python script each to get all scene item canvas positions via their box transform which needs a matrix4, and also tried some basic matrix math. All results looked correct.
=> deps/obs-scripting: Expose matrix3 & 4 to scripting

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss, UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp, libobs/obs-internal.h, libobs/obs-source-transition.c, libobs/obs-source.c, libobs/obs.h
This adds the ability for users to manually transition between sources in studio mode.
https://ideas.obsproject.com/posts/338/manual-scence-transition-control
In studio mode I transitioned back and forth between sources.
=> Add t-bar to studio mode

UI/window-remux.cpp
Alter the Remux input path function to use QDir's Native Separators function. This means that the user will not see unix style on windows and vice versa.
Solves issue #2272
I have tested this on a Windows 10 machine. The remux process still functions as normal.
Bug fix
=> UI: Convert remux path separators to OS native style

UI/properties-view.cpp, libobs/obs-properties.c, libobs/obs-properties.h
Will be in coordination with a future PR to `obs-browser` to set the CSS input as monospace.
This PR also halves the length of tab character for easier readability and consistency with modern editors.
While the text property for OBS Browser's CSS doesn't support advanced code editor capabilities, and probably shouldn't, there can be a fair bit of custom CSS applied to third party webpages. This significantly improves the usability and readability of the Custom CSS field, and the same can be done for any other multi-line text property that contains code.
Apply this change to `obs-browser`:
https://github.com/WizardCM/obs-browser/commit/855ade440db17bd48fba8867918b9795adac822d
Then open the properties for a Browser source.
=> Add monospace font for multiline text property

UI/window-basic-main.cpp, UI/window-basic-main.hpp
When setting with an invalid output path, press the "start recording" button, UI will remind that output path is invalid (not low disk space).
This occurs to me when I change the output dir's name, and it reminds me that I need more space to start recording. I have tried deleting for 20G datas and it still reminds me that I need more space. So, I check the source code and fix it.
I've tested it in Windows 10 1809, Intel Core i7 4720HQ with NVIDIA GTX 950M, and it works as expect.
It affects method OBSBasic::StartRecording() in window-basic-main.cpp:5412 with a branch code.
Bug fix.
=> UI: Properly inform user if recording path is invalid

libobs-d3d11/d3d11-rebuild.cpp, libobs-d3d11/d3d11-subsystem.hpp, libobs-d3d11/d3d11-texture3d.cpp, libobs-opengl/gl-texture3d.c
Remove support for binding 3D textures as render targets.
Noticed the D3D path wasn't written correctly, and there's not really a sensible "default" for this, so it's probably better to remove support, and not bother.
SRV usage still works (Apply LUT) on Windows (D3D) and Mac (GL).
=> Remove volume render targets

.gitignore, UI/CMakeLists.txt, UI/obs.manifest
Provides a standard manifest file for Windows applications to specify application compatibility. Details [here](https://docs.microsoft.com/en-au/windows/win32/sysinfo/targeting-your-application-at-windows-8-1).
This change also removes `*.manifest` ignore from Git.
`VerifyVersionInfo()` in the Windows APIs reports the incorrect version on everything above Windows 8. This is due to how the Windows API (and its helper functions) report the version based on the provided manifest.
> If the application has no manifest, VerifyVersionInfo behaves as if the operation system version is Windows 8 (6.2).
If the application has a manifest that contains the GUID that corresponds to Windows 8.1, VerifyVersionInfo behaves as if the operation system version is Windows 8.1 (6.3).
If the application has a …
=> Supply Windows manifest file (incl. compatibility info)

plugins/obs-ffmpeg/ffmpeg-encoded-output.c, plugins/obs-ffmpeg/obs-ffmpeg-output.c
Clean up VC++ warnings from #1748.
Don't like warning spam.
Breakpoint inspection on Windows for all diffs to ensure behavior is the same.
=> obs-ffmpeg: Fix VC++ warnings

libobs-opengl/gl-subsystem.c, libobs-opengl/gl-texture3d.c
Forgot to add clean-up path for volume textures in OpenGL.
Leaks are bad.
2 leaks before change. 0 after.
=> libobs-opengl: Fix volume texture leak

deps/obs-scripting/obs-scripting-python-frontend.c
Adds `obs_frontend_add_event_callback` and `obs_frontend_remove_event_callback` support for python scripting.
Code has been mostly reused from the `obs_frontend_add_save_callback` and related functions, I trust Jim's code and it shouldn't behave much differently.
https://github.com/obsproject/obs-studio/blob/master/deps/obs-scripting/obs-scripting-python-frontend.c#L258
I implemented this because I needed it and it hadn't been implemented for reasons unknown.
> 14:57 <@​Jim> I wonder why it's not there
> did I just forget or was there another reason?  I can't remember
I couldn't find this on mantis/gh, but there was a thread covering it;
https://obsproject.com/forum/threads/python-scripting-missing-bindings-to-frontend-events-making-it-hard-to-trigger-on-stream-start-stop.82955/
I have …
=> obs-scripting: Add Python functions for frontend events

CMakeLists.txt, deps/media-playback/CMakeLists.txt, libobs/CMakeLists.txt
ppc64le was fixed before, but ppc64 (big-endian) was still failing.
=> CMake: Fix build on ppc64

UI/scene-tree.cpp, plugins/mac-vth264/encoder.c
Fixed a few leaks found by Instruments tool on Mac.
Leaks are bad.
Instruments no longer reports as many leaks. Some still remain on the VideoToolbox side, but I'm not sure those are our fault.
=> Leak fixes

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
- Mixer OSL removed (NXDOMAIN)
- Restream.io Prague added (FTL & RTMP)
- GameTips.tv removed (NXDOMAIN on all servers)
Twitch has made several updates as well, but since those are kinda messy (splitting single servers into multiple with inconsistent naming) and we fetch the Twitch server list from them anyway I skipped over that for now.
Gametips.tv *technically* still seems to exist, but all their servers we knew about are offline and  I can't find any information on their website indicating new ones, so remove them for now.
Update/Remove service information.
Servers have been added, servers have been removed.
Really?
- OBS Service Data Update
=> rtmp-services: Update/remove services

plugins/obs-outputs/librtmp/rtmp.c, plugins/obs-outputs/librtmp/rtmp_sys.h
mbedtls_md5_starts(), mbedtls_md5_update() and mbedtls_md5_finish()
have been marked deprecated since mbedtls version 2.7 and may go
away in the future.
These function have been superseded by versions with a return
value. They are suffixed with "_ret". We do not actually check
return values.
Also the header "mbedtls/net.h" has been superseded by
"mbedtls/net_sockets.h".
I wanted to get rid of some "deprecated" warnings during compiling. Also these deprecated functions _may_ (or may not) be removed in future releases of mbedtls.
I successfully compiled the changes on my Linux machine. The  mbedtls related deprecation warnings are gone.
- **I could not verify if compilation on other platforms still succeed**.
- **I could not verify whether RTMPS endpoints are still working correctly** (They …
=> obs-outputs: Fix mbedtls use of deprecated functions

docs/sphinx/reference-properties.rst
Minor fix of this definition not being complete
Want to have any one else avoid having to find the definition of this function back in source since it's incomplete. Simple fix, writing this PR is longer than the patch 
=> docs/sphinx: Fix obs_property_list_item_disable entry

UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/window-basic-settings.cpp
This displays aspect ratios in the video settings.
Makes it easier for users to determine aspect ratio.
Changed both base and scaled resolutions.
=> UI: Display aspect ratios in video settings

UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
If the user clicks 'no' on the stereo audio message or changes a audio setting and changes it back, the restart message is still shown. This fixes the issue by hiding the message again.
Less confusing for user.
Changed audio stuff in settings.
=> UI: Fix audio restart message not hiding

plugins/obs-outputs/librtmp/rtmp.c
mbedtls_x509_crt_parse_path returns a positive number if it partially
succeeds and a negative number on complete failure. This changes the
positive result to no longer error and prevent TLS connections (OBS
verifies all endpoints so having no CA chain prevents TLS).
People are unable to stream to facebook due to missing CA cert chains when their `/etc/ssl/certs` directory seems appropriate and openssl validates enpoints fine. Errors in this case are `MBEDTLS_ERR_SSL_CA_CHAIN_REQUIRED` (RTMP_Connect1, TLS_Connect failed: -0x7680)
Dropping the CA chain replicates user issues. Im going based on documentation that this is what is happening as my cert chain does not produce any such errors.
=> librtmp: Allow partial success for mbedtls

UI/data/locale/en-US.ini, UI/window-basic-main-dropfiles.cpp, UI/window-basic-main.hpp
Extending the ability to drag files into the OBS window to automatically add it to the scene, this adds the ability to do the same for web links (especially when dragged from a web browser).
Web links can be built into any web element, like a button or thumbnail. The web developer can also define the width, height, and source name for when the source is added. See the link below when testing. Dragged links default to canvas size.
Users should be able to efficiently build their overlays. With web overlays becoming more and more popular, this PR aims to improve the workflow of importing them.
Drag any one of these into OBS: https://wizardcm.github.io/OBS-Drag-Demo/
=> Support for URL/web link drag and drop 

plugins/win-dshow/win-dshow.cpp
Fix regression to RGB DIB orientation caused by #2072.
Re-read MSDN documentation, and saw misinterpretation.
YUY2 and XRGB are both upright on my capture card now.
=> win-dshow: Fix upside-down RGB DIBs

UI/forms/AutoConfigStreamPage.ui, UI/window-basic-auto-config.cpp, UI/window-basic-auto-config.hpp, UI/window-basic-settings-stream.cpp
Follow up to previous pull request https://github.com/obsproject/obs-studio/pull/2145
The wizard has a stream link URL as well. Adding the URL button in the
wizard to match. Additionally, fixing a few  errors in the UI layout
and spacing where items were not padded.
Before: 
After: 
Matches UI of previous changes and fixes a button layout issue. 
Yes. 
MacOS 10.14.6
MacBook Pro
=> UI: Upgrade stream key link to button in Wizard

plugins/image-source/color-source.c, plugins/image-source/image-source.c, plugins/obs-text/gdiplus/obs-text.cpp, plugins/text-freetype2/text-freetype2.c, plugins/text-freetype2/text-freetype2.h
Color Source: change default to size of canvas
Text: change default size to 256
This also adds fallbacks for when the user didn't change the defaults in a previous version.
Provides better defaults for these sources.
This is a combination of #2073, #2112 and #1921.
The previous issues of why those weren't merged are fixed with this.
I've tested the color source and text-freetype2 on Linux. The gdi text source needs testing on Windows.
=> obs-plugins: Change defaults of various plugins

UI/window-basic-main-dropfiles.cpp
Add support for checking multiple source types in Drag n Drop callback
to support overlays for linuxbrowser users. Once the "browsersource" is
available on the platform it will have priority.
It's trivial to support linuxbrowser-source in this case, so I think it's important for platform parity.
Worked on my machine. Im not sure if the original branch introduced a memory leak or I did, but I see ~1 leak per drag n drop.
=> UI: Support URL/web DnD in linuxbrowser

UI/window-basic-main-transitions.cpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
-If the user were in the middle of a transition and clicked
the cut transition, the transitions would become borked.
-This actually disables the transition widgets, so the
user doesn't click them. Before, the disabling of the
widgets didn't work as expected. The code for enabling/disabling
them was also simplified.
-This loading of studio mode was moved in OBSInit because
the loading of transitions needs to happen first. This fixes
a bug when enabling/disabling the t-bar when the program
is first loaded. The t-bar would be disabled even if a
cut or stinger transition was not used.
-When the user would click the quick transitions, the
t-bar would be enabled even when it was not supposed
to.
Just squashing bugs.
Transitioned between scenes in studio mode. …
=> UI: Fix studio mode transition bugs

plugins/image-source/color-source.c
The color source default height was set to the canvas width.
Bug fix.
Created color source.
=> image-source: Fix color source default size

libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
This fixes a crash where the default audio monitoring device would be returned as null. This happens when I build OBS in portable mode on Linux, where the pulse server for some reason can't be connected to. This has only happens to me on Ubuntu 19.10. Audio monitoring still doesn't work here, but at least it doesn't crash anymore.
Fix annoying crash.
Created audio monitoring with default device.
=> audio-monitoring: Fix Pulse Audio crash

docs/sphinx/reference-core.rst, docs/sphinx/reference-scenes.rst
Add obs_group_from_source and obs_enum_scenes to the documentation
It is missing from the documentation.
=> docs/sphinx: Add obs_group_from_source and obs_enum_scenes

libobs/obs-encoder.c, libobs/obs-properties.h, libobs/obs.c, libobs/obs.h, libobs/util/c99defs.h
Rename DEPRECATED to OBS_DEPRECATED to avoid collisions with other libraries that define DEPRECATED.
I use a library in my personal plugin that defines DEPRECATED differently.
Grep'd for all usages of DEPRECATED. Compiles without warning.
=> libobs: Rename DEPRECATED to OBS_DEPRECATED

UI/frontend-plugins/frontend-tools/output-timer.cpp, UI/window-basic-settings.cpp, UI/window-basic-stats.cpp, UI/window-basic-status-bar.cpp
Replace QString sprintf member function with non-member asprintf, and qVariantFromValue with QVariant::fromValue.
Clean up build output.
Tested one of the asprintf replacements to validate the pattern. qVariantFromValue itself is implemented as QVariant::fromValue, so that's unlikely to fail, but I verified the FFmpeg advanced settings still work.
=> UI: Fix Qt 5.14 deprecation warnings

libobs/media-io/video-io.h
Add VIDEO_CS_SRGB enum value in preparation for sYCC support. Can't PR all at once because of the AMF submodule.
WIP AMF changes: https://github.com/jpark37/obs-amd-encoder/commits/srgb-support
WIP sYCC changes: https://github.com/jpark37/obs-studio/commits/sycc-color-space
Most video applications handle 709 incorrectly and sYCC correctly. We also don't perform color transformation from sRGB to 709, so sRGB is a more accurate TRC to label our videos with.
See RFC for compatibility matrix: https://github.com/obsproject/rfcs/pull/7
OBS compiles and runs without crashing. At this point, it's just an unused enum value.
=> libobs: Add VIDEO_CS_SRGB enum value

UI/window-basic-main-transitions.cpp
Fixes transition overrides not working with the t-bar.
Fixes bug.
Set scene to have transition override and used t-bar to transition to the scene.
=> UI: Fix t-bar not working with transition override

libobs/media-io/video-io.h, libobs/media-io/video-scaler-ffmpeg.c, plugins/obs-x264/obs-x264.c
Fixes enum not handled in case switch.
Compiler warnings are annoying.
Compiled program.
=> libobs, obs-x264: Fix compiler warnings

UI/window-basic-settings.cpp
This fixes an issue where loading the aspect ratio would cause the settings to change, causing the Apply button to be enabled.
Bug mentioned on Discord by @jpark37
Opened settings.
=> UI: Fix aspect ratio triggering settings change

plugins/obs-transitions/transition-stinger.c
Populates the name of a stinger transition's media source to the name of the stinger itself.
Occasionally when audio buffering is added and it's caused by a stinger, the log will not specify which stinger it's from - it'll instead say (null). This ensures the name will be displayed in such a scenario, which will help the user track down the issue.
Added a stinger transition, and checked the log to ensure the media source is named.
```
[Media Source 'MyCustomStinger']: settings:
input:                   D:/User/Documents/OBS/Transition_Purple_wAudio.webm
```
=> Set stinger media source's name

UI/window-basic-settings.cpp
Fixes crash when entering very high numbers in the resolution line edits. I've now set the max lengths of the line edits to 9. Resolutions up to 9999x9999 can be entered.
https://github.com/obsproject/obs-studio/issues/2343
Entered resolutions.
=> UI: Fix crash when entering large resolutions

UI/window-basic-main-transitions.cpp
If a user is in a middle of a transition and exits studio mode, the transitions wouldn't be re-enabled.
Fixing bugs.
Exited studio mode while using transition.
=> UI: Fix transtions not enabled

UI/window-basic-settings.cpp
Fix crash in resolution line edit.
While https://github.com/obsproject/obs-studio/commit/818e3a364e5873e5e1cdb18dddf91733cf8dec83 prevents users from using large resolutions, a crash will still happen if 9999999999999999999 was put in as the resolution, for example.
Entered resolutions.
=> UI: Use input validator on resolution line edit

deps/media-playback/media-playback/media.c, deps/media-playback/media-playback/media.h
This adds functions to pause/seek media sources.
This is another piece of #1803, in which I'm separating into different PRs.
As part of #1803, the media sources could be paused and seeked.
=> media-playback: Add functions to pause/seek media source

plugins/obs-transitions/transition-stinger.c
This is a modification to the change made in https://github.com/obsproject/obs-studio/commit/e023060afad105e59a07ac56499836b23182ae30
Triggering a new transition too soon after a stinger would cause the wrong scene to be displayed. Jim suggested halving the padding which should mitigate this issue.
Attempted to transition after a stinger, ran into the issue significantly less often.
=> obs-transitions: Halve stinger padding to 250ms

UI/win-update/win-update.cpp
This PR makes the automatic update prompt on Windows appear regardless of whether any outputs are active or whether game capture is in use.
OBS will stop prompting to update if the user has configured NDI or Virtualcam, since these plugins start outputs automatically, and users may be left on old OBS versions without realizing. Game capture hooks are also possible on startup, but given that the capture DLLs are infrequently updated it doesn't make sense to skip updates on this either.
It hasn't! But since this is straightforward deletion of the code to check and prompt, I don't see any issues...
=> UI: Always prompt when updates are available

plugins/win-capture/duplicator-monitor-capture.c, plugins/win-capture/window-capture.c
This commit forces window and display capture to update immediately when their properties are changed instead of waiting for the next tick.
This was requested in https://github.com/obsproject/obs-studio/issues/2322 and makes the UI feel more responsive.
I changed the target window / display in the settings and verified it updated immediately.
=> win-capture: Faster display / window capture updates

UI/window-basic-main-transitions.cpp
Fixes bug where transitions remained disabled when the scenes were not swapped.
https://github.com/obsproject/obs-studio/issues/2368
Turned off swap mode and transitioned between scenes.
=> UI: Fix transitions being disabled

UI/adv-audio-control.cpp, UI/adv-audio-control.hpp, UI/window-basic-adv-audio.cpp, UI/window-basic-adv-audio.hpp, UI/window-basic-main.cpp
Shows source icons next to the name of each source. Also controlled by the toggle in View.
Consistent with the Sources list.
Open the AAP window. Toggle icons.
=> UI: Show source icons in Advanced Audio Properties

UI/platform-windows.cpp
Uses an absolute path to determine whether the current portable OBS config directory is in use.
Currently this uses a relative path, which means every portable instance is assumed to be using the same config directory.
Load two different portable installations of OBS at the same time. Previously a warning would appear when opening the second instance.
=> UI: Use absolute path for portable mode multi-instance check

libobs-opengl/gl-cocoa.m, libobs-opengl/gl-helpers.h, libobs-opengl/gl-subsystem.c, libobs-opengl/gl-subsystem.h, libobs-opengl/gl-windows.c, libobs-opengl/gl-x11.c
Attempt to fix threading issues that cause OBS to force-crash when compiled with latest Xcode. There are two places where the new SDK introduces a force-crash because operations are not happening on the main thread: when we modify the context view to switch swap chains, and when we resize a swap chain.
Instead of using just one context for all rendering, we can create additional contexts for each swap chain, set each view once on initialization, and switch contexts as needed by the renderer.
For resizing, we can schedule the update code to run on the main thread from the render thread. Ideally, we wouldn't have to round trip the logic from main thread to graphics thread and back, but I don't think we want to hack up the interface for this, especially since OpenGL will give way to Metal …
=> Fix OpenGL thread-safety on Mac to use latest Xcode

docs/sphinx/reference-sources.rst, libobs/obs-source.h
Add media controls and source icon to the documentation
It is add to OBS but not to the documentation.
Not
=> docs/sphinx: add media controls and source icon

libobs/graphics/half.h
Non-static inline functions don't work for some reason, so make them static.
Couldn't build on Mac.
Mac builds. LUTs still work.
=> libobs: Fix Mac linker error

UI/obs-app.cpp, UI/platform-osx.mm
This fixes some crashes in browser panels on Mac, but it's also harmless
if browser panels aren't enabled.
Some parts of Chromium apparently can't live without knowing whether they're being called from the Mac event loop. To satisfy them, this PR implements the `isHandlingSendEvent` method on NSApp. 
This fixes a crash led to a crash when you right click a browser panel.
Tested in combination with https://github.com/obsproject/obs-browser/pull/197, makes it crash less.
=> UI: Add Chromium-compatible NSApplication subclass

UI/platform.hpp
This broke the build, but I had no idea because the build break
detection was itself broken.
<insert gif of homer simpson disappearing into bush>
=> UI: Add missing function delcaration

azure-pipelines.yml, formatcode.sh
=> CI: Fail osx and linux on build failures. Fix decklink clang-format

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Adding new Castr.io ingest locations to RTMP service list:
- Adding new ingest locations; Miami, Singapore, Australia, India.
- Updating pathnames in existing castr.io ingests in RTMP service list.
- Incrementing rtmp-services version in `package.json`.
List of updated Castr.io ingest locations  
[developers.castr.io/apiv1/ingests/list](https://developers.castr.io/apiv1/ingests/list)
Updating the rtmp-services ingestion list to enable updated Castr.io ingests.
Castr.io has added support for a few more ingest locations and to reflect changes in rtmp pathnames for existing ingests locations.
Not required.
Updating OBS RTMP Services Data
- [ x] I have read the …
=> rtmp-services: updating castr.io rtmp ingests

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Callbacks when media starts/ends.
Originally a commit in #2380. The media controls UI won't be put in until after v25.
Tested in #2380
=> obs-ffmpeg: Use callbacks when starting/ending

UI/obs-app.cpp
Fixes #2194
This ensures the UI doesn't block the left mouse click event.
See #2194 for full details. Essentially, mouse events are blocked without determining if they're part of a hotkey.
1. Set "Hotkey Focus Behaviour" to "Disable hotkeys when main window is in focus"
2. Drag to resize a docked panel
=> UI: Allow resizing docks when hotkeys are disabled

libobs/obs-properties.c
Fixes the corrupted obs_properties structure that happens when the obs_properties_remove_by_name encounters the first or the last element.
Stream Effects 0.8.0 makes heavy use of the obs_properties_remove_by_name feature, which breaks when used on the first or last element in the obs_properties_t*. This means that OBS enters an invalid state, and any future attempts to read from the obs_properties_t* object lead to memory corruption, or even a crash.
Validated against new Stream Effects code. Stopped crashing.
=> libobs: Don't corrupt obs_properties in ..._remove_by_name

UI/CMakeLists.txt, UI/data/locale/en-US.ini, UI/forms/OBSBasicSettings.ui, UI/forms/OBSImporter.ui, UI/importers/classic.cpp, UI/importers/importers.cpp, UI/importers/importers.hpp, UI/importers/sl.cpp, UI/importers/studio.cpp, UI/importers/xsplit.cpp, UI/window-basic-main-scene-collections.cpp, UI/window-basic-main.hpp, UI/window-basic-settings.cpp, UI/window-importer.cpp, UI/window-importer.hpp
This PR replaces the previous Open File dialog for importing collections with a window for importing many collections at once based on the remux window, and translates sources between OSes. In addition, it adds support for importing from the following programs:
- OBS Classic
- XSplit Broadcaster
- Streamlabs' fork of OBS
Many people are looking to move to OBS Studio from different programs, or from other computers with many collections. Importing one-by-one can be slow, and being limited to Studio collections means anyone making the switch will need to remake their scenes.
This change makes importing much quicker for transferring between computers, and allows people to seamlessly switch to OBS from other software. It also translates OS specific sources when importing Studio collections, …
=> UI: Add advanced scene collection importer

UI/window-basic-main.cpp, UI/window-basic-main.hpp
This overrides the default context menu provided by Qt's docking system, and instead displays the View->Docks menu.
**Note**: Without the specific check for null/dock widgets, this would "add" the context menu anywhere in the main window where a context menu isn't defined (including within the Controls dock).
* The default context menu greys out any entries that have the close buttons hidden, while the Docks menu does not
* The default context menu is ordered differently than the Docks menu
* The docks menu provides Lock & Reset UI options, plus a link to add custom browser docks
* General consistency
* Right click on a docked panel's title area
* Right click on the separator/grip between docks
=> UI: Use OBS dock menu instead of Qt dock context menu

UI/data/locale/en-US.ini, UI/volume-control.cpp, UI/volume-control.hpp, UI/window-basic-main.cpp, UI/window-basic-main.hpp
This adds an option the the volume control config menu to lock the volume slider.
https://ideas.obsproject.com/posts/734/please-add-a-lock-to-the-volume-level
Locked/unlocked volume.
=> UI: Add ability to lock volume

UI/window-basic-main.cpp
Fixes locked sources being transformed.
https://github.com/obsproject/obs-studio/issues/2410
Locked sources then tried to transform them.
=> UI: Fix locked sources being transformed

plugins/decklink/decklink-output.cpp
When a user starts a Decklink output and there are none available (such as when the Decklink input is active), OBS would crash.
https://obsproject.com/mantis/view.php?id=1298
Created Blackmagic source and then tried to start output.
=> decklink: Fix crash when no outputs are available

UI/data/locale/en-US.ini, UI/obs-app.cpp, UI/obs-app.hpp, UI/window-basic-main.cpp, UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
When the user closes the settings and changes audio or locale, ask them if they want to restart OBS.
Users currently have to manually restart OBS.
Previous PR: #1701
Changed audio/language.
=> UI: Restart program when audio/locale changed

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added Whalebone.tv streaming services.
Whalebone is recommending artists to use OBS Studio. Adding it to the list would make
OBS easier to use for those artists.
Ran JSON Validator on all edited files.
Running clang-format on the files rewrites them completely so they are not formated
correctly. Didn't push these changes as that is out of scope for this pull request.
Added services to the list and bumped versioning on related files.
=> rtmp-services: Add Whalebone.tv

UI/frontend-plugins/frontend-tools/data/scripts/countdown.lua, UI/frontend-plugins/frontend-tools/data/scripts/url-text.py
Fixes issue where the scripts wouldn't show text sources in the dropdowns.
v25 updated the text source IDs.
Used script dialog.
=> obs-scripting: Update text source IDs

deps/media-playback/media-playback/media.c, deps/media-playback/media-playback/media.h
This fixes max buffering and sync issues when seeking or pausing media sources. Will need a code review and more testing because I'm new to timestamp stuff, but it seems to work quite well.
Fixes media source bugs when using media controls.
Tested with #2380, and was only tested on Linux.
=> deps/media-playback: Fix buffering/sync issues

plugins/mac-vth264/encoder.c
Reland of 30d29618, except actually tested this time.
The VideoToolbox encoder gives I-frames and P-frames a priority of 1, but the RTMP output code expects I-frames to have priority 3 and P-frames to have priority 2. This causes RTMP to never stop dropping frames.
30d29618 changed the priority of all frames that aren't I-frames, but that included B-frames as well as P-frames. B-frames are given a priority of 0 by VideoToolbox and changing that priority causes artifacts for reasons I don't understand. So ignore the B-frames by ignoring slice packets with priority 0.
1. Did a bunch of recording and streaming with the hardware VT codec, confirmed that the corruption issues introduced by the previous incarnation are fixed.
2. Used Network Link Conditioner to artificially introduce …
=> mac-vth264: Manually mark priority bits for VideoToolbox frames

UI/data/themes/Acri.qss, UI/window-extra-browsers.cpp
Fixes table headings (and grid) & the delete button in Custom Browser Docks
**After:**
Unreadable headings, near-invisible grid lines, and delete button that doesn't fill the cell
**Before:**
Open any one of the following:
* Custom Browser Docks
* Remux dialog
* Scene Collection import dialog
=> Acri theme fixes: Tables

UI/window-basic-main-profiles.cpp
QDir.mkpath seems broken with relative paths, which causes the import to silently fail because the parent directory is never created. This also adds a basic check to avoid accidentally overriding an existing profile.
https://obsproject.com/mantis/view.php?id=1548
* Launch OBS in portable mode
* Export a profile
* Rename the profile within OBS
* Import the profile you just exported
=> UI: Fix Import Profile in Portable Mode

UI/obs-app.cpp
The program would still launch if it failed to init or was cancelled.
Wasn't tested, but should work properly now.
=> UI: Return 0 when launch cancelled or failed

UI/window-basic-adv-audio.cpp
Use correct integer type to avoid compilation warning
Fixes a compilation warning
Ran a build. Got no warning.
=> UI: Fix compilation warning re signed/unsigned

libobs/obs-video.c
winrt-capture needs to clean up some objects on the render thread, and we need this one final pump to ensure wc_hide gets calls.
OBS can crash or leak on exit.
Breakpoint thread freeze/thaw inspection on Windows. Ran Linux build 10 times in a row without leaking.
=> libobs: Pump graphics loop one final time for cleanup

libobs-opengl/gl-cocoa.m
Make sure context is current while empty VAO is created on Mac. Draws that used the invalid empty VAO were failing.
Fix video capture failing to draw on Mac.
Video capture now succeeds on Mac.
=> libobs-opengl: Fix Mac VAO created without context

UI/data/themes/Acri.qss, UI/data/themes/Dark.qss, UI/data/themes/Rachni.qss, UI/data/themes/System.qss
Changes size of t-bar.
Before:
After:
Looks better.
Opened studio mode.
=> UI: Make t-bar smaller

libobs/util/pipe-posix.c
os_process_pipe_write now retries partial writes until it's written all the data, or it's unable to write anything at all.
Saving the replay buffer twice would previously result in a crash where the pipe write got stuck in an infinite loop of failures (resulting in a wedged UI). The issue began with a large packet that was only partially written, which was deemed a failure, resulting in the pipe being prematurely closed and all future operations failing.
Tested on Debian Linux by manually firing up the replay buffer and saving it twice.
=> libobs/util: Retry pipe writes to avoid spurious failures on short write.

plugins/decklink/decklink-output.cpp
Fixes crash when starting Decklink output and no device is selected.
Bug fixing.
Created Decklink output when device wasn't selected.
=> Decklink: Fix crash when no device selected

UI/forms/OBSBasic.ui
This removes dock margins for docks that have dark backgrounds. (scenes, sources and volume)
Before:
After:
I think it looks better.
Looked at UI.
- UI Change
=> UI: Remove dock margins

UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp, UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.h, UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp, UI/frontend-plugins/decklink-output-ui/decklink-ui-main.h, UI/frontend-plugins/decklink-output-ui/forms/output.ui
This combines the stop and start buttons into a single toggle button. Instead of the status labels, the buttons are set checked if active. This also simplifies some of the code.
Before:
After:
Simplifies the UI.
Started Decklink output.
- Code cleanup
- UI change
=> frontend-plugins: Refactor Decklink out UI

CI/install/osx/packageApp.sh
'PlugIns' is normal for MacOS and whatever is generating qt.conf
(macdeployqt?) is using 'PlugIns', so this both builds and generates
an app that works on case insensitive filesystems but fails to load
on case sensitive filesystems.
I haven't tested building the installer, only modifying the
qt.conf in the installed copy of OBS.app which fixes my copy
of OBS so it loads.
Fixes https://github.com/obsproject/obs-studio/issues/2302
Bugfix (https://github.com/obsproject/obs-studio/issues/2302)
=> CI: Fix case of PlugIns directory

plugins/win-capture/game-capture.c, plugins/win-capture/graphics-hook/graphics-hook.c
Before this change, after a game capture source would send a signal to
init or restart a graphics hook, it would respond to any and all hook
ready signals.
With multiple game capture sources in the same scene, a source could
receive the signal intended for another source, and show the wrong
texture.
This change adds the window handle to the name for shared data with the
hook, resulting in hooks for other sources being ignored.
=> win-capture: Fix hook collisions with multiple game captures

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Remove implicit float to int64_t conversion by avoiding float entirely.
Fixes VC++ warning.
No more warning. Calling code doesn't seem to exist yet, so didn't test functionality.
=> obs-ffmpeg: Fix type conversion warning

UI/source-tree.cpp
Instead of hard-coding an expected index, or assuming the index based on whether icons are enabled, this will dynamically read where the widget was previously.
Bug reported [here](https://obsproject.com/forum/threads/obs-studio-25-0-release-candidate.116067/post-437794).
Long story short - when icons are disabled, widget indexes are different.
Disable source icons. Rename a source. Re-enable source icons. Rename a source.
=> UI: Dynamically set widget index when renaming sources

plugins/obs-ffmpeg/ffmpeg-encoded-output.c
This fixes some configuration parameters which were incorrect (for audio).
It seems to fix streaming to Haivision Makito decoder (a box which can ingest mpegts through srt/udp/tcp).
Fixed errors in retrieving some audio parameters.
Bug fix.
Tested on windows against Haivision Makito server, wowza server, nimble server.
=> obs-ffmpeg: Fix some incorrect settings for srt output

UI/window-basic-main-transitions.cpp, UI/window-basic-main.hpp
- If the override transition is a cut or stinger, fallback to scene transition.
- If the scene transition is cut or stinger (with or without override), fallback to fade transition.
Users were confused why t-bar was disabled.
Transitioned between scenes with different types of transitions.
=> UI: Do not disable t-bar

UI/window-basic-main-transitions.cpp
Fixes transition override not working as expected.
Oversight in #2460
Used override transitions.
=> UI: Fix override transition not working

plugins/win-capture/graphics-hook/vulkan-capture.c
Fix crash in Vulkan game capture if VkApplicationInfo is NULL.
mpv passes NULL, and that's valid.
mpv works now.
=> win-capture: Handle NULL VkApplicationInfo

libobs/obs-source.c
Filters can be hidden without being shown, which can unbalance the ref
count and destroys them prematurely. We really only care about input
sources having a chance to clean up from the render thread from the hide
handler, Windows 10 window capture specifically.
Filters were disappearing on scene switches.
Filters stick around when scenes are being switched. WGC capture successfully cleaned up 5/5 times.
=> libobs: Only manipulate input source ref counts

plugins/win-capture/game-capture.c, plugins/win-capture/graphics-hook/graphics-hook.c
Use correct format string for uint32_t (unsigned int)
Reduce warning
After this fix, warning dispears
=> win-capture: Fix format string warning

plugins/linux-v4l2/v4l2-controls.c
Use LP64 macro to determine pointer size in linux-v4l2 plugin.
"unknown platform, this code won't work" buildtime error happens when
building for armhf. It should also effect powerpc.
Build & run test on armhf & amd64.
=> Fix build for armhf and powerpc

plugins/win-capture/graphics-hook-ver.h, plugins/win-capture/graphics-hook/vulkan-capture.h
Add support for VK_FORMAT_A8B8G8R8_UNORM_PACK32.
Some programs use VK_FORMAT_A8B8G8R8_UNORM_PACK32 for their swap chains.
Vetted that Vulkan applications still capture, but I'm not in a position to test this specific format.
=> win-capture: Support VK_FORMAT_A8B8G8R8_UNORM_PACK32

plugins/win-capture/graphics-hook/vulkan-capture.c
Restore Vulkan 1.1 version hack for AMD drivers.
Fix regression caused by null application info fix.
Vulkan works on AMD again after not working.
=> win-capture: Restore Vulkan 1.1 version hack

libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-capture.h, plugins/win-capture/window-capture.c
Starting with Windows 10 2004, we can disable WGC cursor capture, and
provide a user toggle. We swap out WGC support for our own though
because ours does not break hardware cursor support.
Being able to disable cursor capture is good. WGC cursor capture is also apparently detrimental to mouse cursor performance.
BitBlt and WGC cursor captures work according to user setting and window focus. Mouse cursor offset appears to be good for both sides of client area toggle.
Older Windows 10 works as expected on builds made with old and new Windows SDK.
=> libobs-winrt: win-capture: HDC cursor capture for WGC

deps/obs-scripting/obs-scripting-python-import.c, deps/obs-scripting/obs-scripting-python-import.h
Add PyDict_New and PyTuple_New to obs-scripting-python-import.[ch]; these functions are used by SWIG's generated code when I build OBS on macOS with SWIG 4.0.1.
obs-scripting-python-import is a wrapper used on Windows and macOS that dlopen()s Python instead of linking it directly.  It contains many pairs of definitions like
```c
PY_EXTERN void (*Import_PySys_SetArgv)(int, wchar_t **);
#define PySys_SetArgv Import_PySys_SetArgv
```
But it was missing two functions, causing OBS to fail to build.
It builds.  I haven't tested further, but it seems like a straightforward fix.
=> obs-scripting: Add missing symbols in -python-import.[ch]

UI/window-projector.cpp
Uses the correct translation key instead of the current one.
`MultiviewWindowed="Multiview (Windowed)"`
Currently the window title is rendered as the key, not the string. This means it is not translated for users.
Open a windowed multiview. Note the window title.
=> UI: Fix windowed multiview title

UI/window-basic-main.cpp, libobs-d3d11/d3d11-duplicator.cpp, libobs/graphics/graphics.h, plugins/win-capture/duplicator-monitor-capture.c, plugins/win-capture/monitor-capture.c
Replaces "Display X" in Fullscreen Projector lists on all platforms, and Display Capture on Windows, with the real display names. Falls back to Display X if a name is unavailable or blank.
Display Capture:
Projectors (Windows):
Projectors (Linux):
Projectors (macOS):
**Note;** If someone is able to get proper display names on macOS or Linux Screen Capture, feel free to PR to my branch, I'll happily combine the changes. I tried and failed.
Improves UX: "Display X" isn't very descriptive, especially as it doesn't always match the display indexes in the system's Display properties. This makes it easier to find the right display at a glance.
* Right click on a scene, source, preview or program and select "Fullscreen Projector"
* Add a Display Capture source on Windows 7 or above. The dropdown …
=> Show friendly monitor names on Display Capture on Windows & Projectors

plugins/win-capture/graphics-hook-ver.h, plugins/win-capture/graphics-hook/vulkan-capture.c
Handle vkCreateSwapchainKHR errors instead of ignoring them.
Hopefully fixes behavior for an application reported by AMD, fixes #2485.
OBS is still able to capture vkcube. Used breakpoint inspection to verify new code behaves as expected. Contrived failure leads to NULL dereference caused by sample code ignoring the return value.
=> win-capture: Handle vkCreateSwapchainKHR errors

test/win/test.cpp
Nothing fancy here: if one tries to build OBS Studio on Windows with `BUILD_TESTS` enabled, compile fails with a `no enough parameters` error on a call to `obs_display_create`.
Not having to edit `test/win/test.cpp` whenever I want to build The Tests™ on Windows.
Tested on Windows 10 1903 64-bit with `BUILD_TESTS` enabled in CMake. Compiles OK.
=> tests: fix Windows compile error

UI/window-basic-filters.cpp, UI/window-basic-filters.hpp
Fixes crash when pressing F2 to rename filter twice.
Fix crash reported on Discord.
Renamed filters.
=> UI: Fix filter rename crash

UI/window-basic-main.cpp
Uses and then converts wide char for fullscreen projector names on Windows.
If a display device doesn't report its model number, Windows localises "Generic PnP Monitor", which in Russian becomes a series of question marks.
Unfortunately, of the 5 displays I have access to, none display as "Generic PnP Monitor", so I cannot test this fix myself.
At the very least, I've tested this to ensure there's no regression for standard English characters.
=> UI: Support Unicode for Windows fullscreen projectors

plugins/win-capture/graphics-hook-ver.h, plugins/win-capture/graphics-hook/graphics-hook.c, plugins/win-capture/graphics-hook/vulkan-capture.c, plugins/win-capture/graphics-hook/vulkan-capture.h
Make sure HWND tracking is cleaned up when Vulkan surfaces are
destroyed. Also use unbounded linked list to fix games that leak
surfaces on Alt+Tab like Doom.
Also replace CRITICAL_SECTION with SRWLOCK, both for claimed speed
benefit, and to remove initialization code.
Fix games that leak surfaces and crash after 16 Alt-Tab presses in fullscreen.
Lots of debugger/breakpoint inspection
=> win-capture: Vulkan surface refactor

UI/window-basic-filters.cpp
When adding a duplicate filter, append an incrementing number after the default name.
Consistency. Both Scene & Source creation auto-increment their names this way.
Add a filter with a default name. Add the same filter a second time.
=> UI: Increment filter name automatically

libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-capture.h, plugins/win-capture/window-capture.c
Use proper check to fix false positive on 1809, and rework error spew to
remove output parameters from winrt_capture_init.
Clean up unnecessary error message for 1809, and remove general grossness of returning an allocated output parameter.
- 1809 successfully fails, and never calls winrt_capture_init to begin with.
- Verified new log lines output correctly by adding in temporary throws.
- WGC still works fine on Windows 10 20H1.
=> libobs-winrt: win-capture: Clean up error handling

UI/window-basic-settings.cpp, UI/window-basic-settings.hpp
Shows the newly introduced "Do you want to restart now?" dialog when browser hardware acceleration is toggled.
As we removed the full Intel blacklist for browser hardware acceleration, a few users have come in with a need to disable it.
Users currently have to manually restart OBS when this setting is changed.
Continues changes from #2408
* Toggle the setting
* Save and close the Settings window
* Be asked to restart
* Click Yes
=> UI: Restart when browser hardware acceleration changed

libobs-winrt/winrt-capture.cpp
Wrap winrt_capture_supported and winrt_capture_cursor_toggle_supported
with try/catch.
Crash PTSD.
Verified correct logging with dummy throws, and WGC still works against unmodified commit.
=> libobs-winrt: Catch more hresult exceptions

UI/importers/importers.hpp, libobs/obs-source.c, libobs/obs.hpp, libobs/util/util.hpp, libobs/util/windows/CoTaskMemPtr.hpp
Clean up warnings at HEAD on latest VS 2019.
I hate warnings.
Debugger inspection for memcpy and destructor calls. Couldn't really test the noexcept changes because I don't think anything calls them, but c'mon.
=> Warning pass 2020-03-19

UI/window-basic-settings.cpp
Fixes crash on linux and mac when updating settings introduced in 25.0.1
Bisected and runs on my machine.
=> UI: Fix crash on settings update

plugins/obs-qsv11/QSV_Encoder.h
PR #1937 (commit b9ad1ce) added QSV target usage options, but there was a comma missing between two of the array entries. This resulted in "faster" and "veryfast" becoming "fasterveryfast", which is not valid.
Code style changes were required by .clang-format.
Fixes #2527.  The encoder doesn't complain, and the log doesn't indicate which usage target was selected, but this should be fixed.
Compiled on Windows 10 1903 (Build 18362.720) 64-bit using VS2017 (15.9.21) with latest OBS deps.  Confirmed that the target usage entries are listed correctly and that recordings work with either selected.
=> obs-qsv11: Fix target usage values

plugins/obs-filters/color-grade-filter.c
Make LUT file selection filter match expected format. FIxes #2532.
LUT file selection filter doesn't work on Linux.
LUT file selection filter works on Linux now, and still on Windows.
=> obs-filters: Fix LUT file extension filter on Linux

UI/forms/OBSUpdate.ui
While `QTextEdit` can have links, they aren't clickable by default. This changes it to a `QTextBrowser` and forces the links to open externally (in a web browser).
As part of 25.0, the updater message had links to informative webpages, but were not clickable in the updater.
* Disabled `CheckDataSignature()` and set `WIN_MANIFEST_URL` to my own
* Clicked the links in the 25.0.1 update dialog.
=> UI: Make links in updater dialog clickable

plugins/linux-capture/xhelpers.c, plugins/linux-capture/xhelpers.h, plugins/linux-capture/xshm-input.c
RandR has two sets of screen geometry information:
1. CRTC. These are the physical scanout engines in the hardware
2. Monitors. These are the logical partitions of the screen.
By default, each CRTC gets mapped to a Monitor. However, some monitors
actually require two CRTCs to drive them due to limitations in the
scanout hardware. Users can also create 'virtual' monitors to support
VNC or other systems.
This patch makes the RandR code prefer the Monitor mechanism to the
older CRTC mechanism. If the server doesn't support a new enough RandR
version, the existing CRTC code is used instead.
The name of the monitor is also provided in place of the arbitrary
number to help users select the desired source.
This updates the RandR code in obs-studio to use current best practices for
identifying …
=> linux-capture: Use RandR monitors for screen information

plugins/linux-v4l2/v4l2-controls.c
v4l2_ioctl will clear the V4L2_CTRL_FLAG_NEXT_CTRL flag resulting in
infinite loops for any driver that reported readonly, disabled, or
volitile controls.
Users whos drivers report these controls will have OBS hang. Reported in support with a device which infinitely logs readonly controls.
Tested on c920 and it continues to work as expected. I dont have a device which reports these values.
Trivial reordering.
=> linux-v4l2: readonly controls cause infinite loop

plugins/linux-v4l2/v4l2-controls.c
Previous fix in #2547 altered id before they were handed off to
callbacks and v4l2 wont strip its own flags from ids resulting in
invalid ids in the ioctl.
Instead add cleanup section and jump all branches there before looping.
Previous code results in invalid states being set and device reset loops after the first opening of obs.
I opened obs multiple times and slide sliders till my device reset. It was able to recover from resets now.
=> linux-v4l2: Fixup invalid id

UI/importers/sl.cpp
This change gets rid of some fields that were assumed to exist in Streamlabs scene collections but don't, and explicitly sets the volume of imported scenes to 1.0.
Previously, the importer assumed scenes had fields that sources did for audio, namely volume, sync, mute and monitoring type. Streamlabs scenes do not have these fields. This resulted in mistakes in importing, such as imported scenes having a volume of 0.0. This prevented audio sources inside those scenes from being audible.
Imported a scene collection before and after the change, and verified that volume was correctly set to 1.0 after being saved in Studio.
=> UI: Fix silent scenes with imported SL scenes

plugins/obs-ffmpeg/obs-ffmpeg.c
Make NVENC available again to Windows 7 users in advanced output mode. Created as PR since this is a bit of a hacky solution to the problem.
Since the old encoder was flagged internal, users can't choose it any more. However NVENC new depends on Windows 8 or higher, so Windows 7 users have no NVENC options at all.
Reported at https://obsproject.com/forum/threads/obs-25-0-1-nvenc-on-rtx-card-and-advanced-output-mode.117322/
Breakpoint to stop the call to `jim_nvenc_load` and verifying old encoder appeared.
=> obs-ffmpeg: Expose old NVENC on Windows 7

libobs-winrt/winrt-capture.cpp
Stop WGC exceptions from turning into crashes.
WGC is still throwing exceptions that appear not to be hresult_error objects.
WGC still works. Log lines were testing by throwing std::bad_alloc.
=> libobs-winrt: Stronger exception handling

UI/window-importer.cpp, UI/window-remux.cpp
Signal only needs to be connected once, not every keystroke.
Also commit data only when text widget focus is lost to fix cursor
moving to the end of the string after every keystroke.
Fixes #2575.
Wacky text entry behavior.
Text entry behavior good for both remux and scene import dialogs. Text is still committed when clicking button immediately after text entry.
=> UI: Fix text handling for dialogs

plugins/obs-qsv11/QSV_Encoder_Internal.cpp
Broken by https://github.com/obsproject/obs-studio/commit/2f62831a96dec0c79134d8eed125b57c03692671 when the break statement was forgotten.
=> Fix QuickSync LA_ICQ encoder settings

plugins/decklink/decklink-output.cpp
Fixes https://github.com/obsproject/obs-studio/issues/2494
OBS crashes when decklink output is auto started and the device is
removed or changed to different model while OBS is not running.
- set decklink device and its mode
- tick auto start
- close OBS
- remove or change device
- open OBS
=> Decklink: Fix crash when no matching device

UI/forms/OBSBasicSettings.ui
On versions prior to 5.14, this field renders correctly. in 5.14, it stretches to fit the dialog.
Incorrect:
Correct (with this PR):
As we're now using Qt 5.14 on macOS and newer versions of Linux, this is worth fixing.
Open the Stream Settings page
=> UI: Don't stretch server field in Qt 5.14

formatcode.sh
Code formatting script was using `sysctl -n hw.physicalcpu` on macOS 
machines to get the CPU count. This command returns the physical CPUs. 
`nproc`, however, returns logical CPU count on Linux machines. It 
should be `sysctl -n hw.logicalcpu` to make it consistent with its 
Linux counterpart. But there also another way. 
`getconf _NPROCESSORS_ONLN` gives the number of logical CPUs on both Linux and 
macOS.
Script was getting the CPU count inconsistently across platforms. 
I've tested my modifications on separate macOS and Linux machines to see it gets the correct CPU count.
=> CI: Make processor count consistent

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
We made update ingest point url. The previous url will work as usual for some time.
Added new backup url and EU and US ingest point urls
We made update "recommended" settings and added b-frames ignore
The ability to select a geo point server manually, same with backup url.
Some streamers asked to replace dns.
B-frames create a webrtc issues.
All rtmp servers works properly, tested with Custom URL
=> rtmp-services: Update Bongacams servers and settings

UI/window-basic-main.cpp
Currently, if you don't have a source selected and press Ctrl+E, a completely broken Edit Transform dialog will appear - as no source is selected, it doesn't have a defined scene, and therefore if you try clicking on another source in the scene, the dialog doesn't update.
This change requires that an item be selected before the dialog will open.
Fixes #2468 
* With a source selected, press Ctrl+E. A window should appear. Close it manually.
* Deselect all sources, and press Ctrl+E. Nothing should happen. If a transform dialog is already open, it will close.
=> UI: Require selected source for Transform shortcut

UI/window-basic-main-transitions.cpp
When switching to Studio mode, a tiny window would appear for a split second, stealing focus. This is likely because the widget did not have a parent. This change ensures the window's parent is `OBSBasic`.
Unnecessary and annoying. Potentially also caused accessibility issues for screen readers.
Toggle Studio mode on/off a few times, watching the taskbar for an extra `obs64` window.
=> UI: Don't open Studio Mode's "Program" label in a window

UI/window-basic-main.cpp
Request from support-team.
Currently only sources in Scenes are logged with their filters.
This excludes global audio sources set in Settings > Audio.
This patch remedies this.
Log global audio sources and their filters.
Helps for support.
Tested on win 10 x64.
=> UI: Log global audio devices and their filters

UI/window-basic-main.cpp
Update an expression to match the style of other flags conditionals.
Building with Clang 10 on FreeBSD 13-CURRENT emitted a warning about logical not `!` applying only to the left hand side of a comparison.  
Verified that object code in window-basic-main.cpp.o is the same.
=> UI: fix warning compiling with Clang 10

libobs/util/platform-nix.c
FreeBSD and Dragonfly uses sysctl(3) for querying system information such as process stats. This change implements FreeBSD and Dragonfly support for os_get_executable_path_ptr().  
To implement proper FreeBSD supports.
Tested on FreeBSD by checking if issue mentioned in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245299 goes away. Not tested on Dragonfly.
=> libobs/util: Add FreeBSD and Dragonfly support in os_get_executable_path_ptr()

plugins/obs-outputs/librtmp/rtmp.c
Some unused variables were not marked unused when RTMPS was disabled.
Warnings are gone with and without rtmps.
Trivial
=> obs-outputs: Fix warnings WITH_RTMPS=OFF

plugins/rtmp-services/rtmp-custom.c
rtmp_custom service will cause memory leak if updated more than once.
fix memory leak.
Bug fix.
=> rtmp-services: Fix memory leak when updating rtmp-custom-service.

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
add a streaming service "niconico" (ニコニコ生放送 in Japanese) into "plugins/rtmp-services/data/services.json".
=> rtmp-services: Add niconico

deps/lzma/liblzma/check/crc32_x86.S, deps/lzma/liblzma/check/crc64_x86.S
FreeBSD uses the same .note.GNU-stack section as Linux to indicate that the
stack should not be executable.
With GNU and GNU-compatible toolchains binaries are tagged with a `GNU_STACK` program header with RW permissions to indicate that they should use a non-executable stack. Linkers emit this header when all input objects contain a .note.GNU-stack section with RW permissions. Add `__FreeBSD__` to the cases where we do this for Linux today.
Built and ran with this change on FreeBSD-CURRENT,
`FreeBSD nazar 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r359488: Tue Mar 31 13:13:49 EDT 2020     emaste@nazar:/usr/obj/usr/home/emaste/src/freebsd-svn/head/amd64.amd64/sys/GENERIC  amd64`
Small security cleanup?
=> deps: lzma: also use .note.GNU-stack on FreeBSD

libobs/obs-encoder.c, libobs/obs-internal.h, libobs/obs-output.c, libobs/obs.h, plugins/obs-ffmpeg/jim-nvenc-helpers.c, plugins/obs-ffmpeg/jim-nvenc.c, plugins/obs-ffmpeg/jim-nvenc.h, plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c, plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Similar to how outputs can store errors in their internal structure, this PR extends the same functionality to encoders. WIP for critique on the design and usefulness of this change as the cases where this is most useful (failed NVENC initialization) are hampered by the fact that jim-nvenc automatically falls back to ffmpeg nvenc which has far less useful error messages.
When an encoder fails, the only clues are in the log file. By storing the most recent error, this can be passed to the output, and eventually back to the UI, allowing a more useful user-facing error message than "Starting the output failed".
I injected faults into jim-nvenc and ffmpeg nvenc encoders and verified the errors appeared in the UI. Example screenshot of a failed NVENC recording output: …
=> Encoder error feedback

UI/window-projector.cpp
Calling showFullScreen after setGeometry puts the projector on the
expected monitor.
On FreeBSD an attempt to open a projector on secondary monitor put it on the primary display instead, reported in #2670. Fixes #2670
This is my first experience with Qt so I am not sure of the canonical way to do this, but I looked at a [stackoverflow question about multiple monitors with Qt](https://stackoverflow.com/questions/3203095/display-window-full-screen-on-secondary-monitor-using-qt), tried moving the showFullScreen after setGeometry, and found that the issue was fixed.
Tested on FreeBSD 13 with qt5-5.13.2_3, View->Multiview (Full Screen)->2nd monitor now appears on the second monitor.
This definitely needs to be tested across operating systems. …
=> UI: fix projector on other than primary display

plugins/linux-jack/jack-wrapper.c
Failed to initialize FFmpeg resampler when setup 4 channels in `Jack Input Client` source. And the volume meter in audio mixer would fallback to 1 channel.
To successfully initialize `Jack Input Client` after setting 4 channels in properties for ambisonics inputs.
Create `Jack Input Client` source and setup 4 channels
=> linux-jack: Fix conversion from channels to speaker layout

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Added wasd.tv to streaming services drop down.
=> rtmp-services: Add wasd.tv

CI/before-script-osx.sh, CI/install-dependencies-osx.sh
=> CI: Add freetype dep on osx

libobs/obs-cocoa.m
Changes the case in the plugins search path on macOS
OBS would crash on a case sensitive file system
See #2686 
Ran the artifact generated from CI inside a case sensitive DMG.
I also ran other versions of OBS in the DMG to prove that it crashed.
=> libobs: Fix plugin folder search path case on macOS

plugins/linux-v4l2/v4l2-controls.c
add_control_property() was previously static inline bool, but did not return a
value and failed to build on FreeBSD-CURRENT with Clang 10.0, with
`error: non-void function 'add_control_property' should return a value [-Wreturn-type]`
Fixes build on FreeBSD-CURRENT with Clang 10.0.
Build was successful.
=> linux-v4l2: Fix build with Clang 10.0

.cirrus.yml
Add qt5-xml package currently required to build on FreeBSD
FreeBSD CI build started failing some time ago with a cmake error that Qt5Xml was not found.
Successful Cirrus-CI run: https://cirrus-ci.com/build/4851080737587200
Note that the build fix from https://github.com/obsproject/obs-studio/pull/2667 is also required.
=> CI: Add qt5-xml package for FreeBSD build task

libobs/obs.c
Don't save removed sources
Sources can keep references due to various problems like bad plugins.
If that is the case and the source is removed the source should still not be saved.
This does not fix the root problem of #2724 and #2709, but prevents the bad results.
With the steps in #2724
=> libobs: Don't save removed sources

plugins/obs-ffmpeg/obs-ffmpeg-source.c
Media Source now closes file when inactive
This PR solves 
https://obsproject.com/mantis/view.php?id=1603
Testing on Windows 10.
Tested with several scenes and media sources. Tried to delete the source file in windows explorer while the media source is active and while it is not active anymore.
=> lib-ffmpeg: Fix media source not closing file when inactive

plugins/obs-qsv11/CMakeLists.txt, plugins/obs-qsv11/QSV_Encoder.cpp, plugins/obs-qsv11/QSV_Encoder.h, plugins/obs-qsv11/QSV_Encoder_Internal.cpp, plugins/obs-qsv11/QSV_Encoder_Internal.h, plugins/obs-qsv11/common_directx11.cpp, plugins/obs-qsv11/common_utils.h, plugins/obs-qsv11/obs-qsv11-plugin-main.c, plugins/obs-qsv11/obs-qsv11.c
Enables a pipeline for texture-based encoding with QSV. Utilizes OBS
NV12 output for encode to avoid offloading them from GPU, which will
increase performance. The option to select old QSV pipeline still
remains and will fallback if new pipeline fails.
=> obs-qsv: Enable QSV texture-based encoding

UI/window-basic-main.cpp
Set scenes as removed on clearing scene data
Helps prevent bugs on switching scene collections.
Was first in #2739, but made it separate pull request
On windows 64 combined with #2739, with the reproduction steps of #2724
=> UI: Remove all scenes in ClearSceneData

UI/window-basic-main.cpp
Label renders with default styling instead of using dynamic property
because it was already polished.
Honestly the use of dynamic properties for styling should be reevaluated if there is a safer alternative that will automatically handle styling changes. Likely this could occur elsewhere already or in the future.
Rendering correctly is nice.
Before(top) and after(bellow)
https://imgur.com/a/NAXFLdI
Validated against existing code using unpolish/polish tricks and qt's magic wiki https://wiki.qt.io/Dynamic_Properties_and_Stylesheets (unpolishing doesnt seem to be required for my case, but i can add it in).
Trivial
=> UI: Fix previewLabel styling

docs/sphinx/reference-properties.rst
Add property grouping (#1664) to documentation
It is missing 
=> docs/sphinx: Add Property Grouping

plugins/CMakeLists.txt
Build ALSA plugin for FreeBSD
The ALSA plugin sometimes works better than pulseaudio and JACK audio input depending on the setup.
Tested using FreeBSD.
System build files.
=> plugins: Build ALSA plugin for FreeBSD

UI/forms/OBSBasic.ui
-Remove 9px margins around central widget. This saves 18px of vertical
space. This will be helpful when the source context menu is added,
which is 24px tall.
-Adjusts margins in transitions dock. The top of the transitions dock
wasn't lined up with the top of the controls dock, which made it look
bad.
Before:
After:
Make UI look better.
Looked and saw it looked better.
- UI tweak
=> UI: Adjust a few margins

UI/forms/images/recording-active.svg, UI/forms/images/recording-inactive.svg, UI/forms/images/recording-pause-inactive.svg, UI/forms/images/recording-pause.svg, UI/forms/images/streaming-active.svg, UI/forms/images/streaming-inactive.svg, UI/forms/obs.qrc, UI/window-basic-main.cpp, UI/window-basic-status-bar.cpp, UI/window-basic-status-bar.hpp
Add status icons for recording and streaming in the statusbar at the bottom of the window.
This is how the status bar looks like now:
This PR implements [this](https://ideas.obsproject.com/posts/131/status-icons-for-recording-and-streaming) idea from the ideas page.
It makes the current recording/streaming status more visible.
This has been tested on Windows 10 with the available themes (Dark, Rachni, and Acri).
=> UI: Add status icons for recording and streaming

plugins/mac-capture/window-utils.h, plugins/mac-capture/window-utils.m
Use a window's id in init_window in the mac window capture plugin.
This is a one-line change that resolves https://github.com/obsproject/obs-studio/issues/2642.
By using a window's ID to identify it, we can find windows even if their name has been changed.
Note that a window's name is still used first, so if a window ID is changed or recycled (I don't know if this can happen) it will still have at least as good behavior as it used to have. In my experience, this change improves things considerably, and I no longer need to reselect all the windows in the window capture settings every time I reopen OBS, which saves me a bunch of time :).
Solves https://github.com/obsproject/obs-studio/issues/2642: the issue that OBS wouldn't be able to find a window if its name changed while OBS was closed. …
=> mac-capture: Use window id to identify windows on MacOS

UI/window-basic-main.cpp, UI/window-basic-main.hpp
Remove unneeded global variables.
There were a bunch of QMenus that didn't need to be global. Also removed global shortcut filter.
Everything ran as expected.
=> UI: Remove unnecessary global variables

CI/install-dependencies-osx.sh
Fixes the unlink step in the `install-dependencies-osx.sh` CI script for environments where Swig is not pre-installed.
Should fix the failing macOS CI runs on Azure Pipelines starting on 2020-04-23.
In the current form the script assumes that a prior (more recent) version of Swig is present on the system, unlinks it (so it's not "visible" to the system), and then installs an older "pinned" version. If no Swig is pre-installed on the system, `brew unlink` will finish with a non-zero return code and due to `set -e` at the top of the script the whole step will fail as well.
By checking if any Swig installation exists on the system before unlinking, this should not happen anymore.
Tested script steps on macOS Catalina 10.15.4 with Homebrew 2.2.13-134-gd5ffb96. …
=> CI: Fix Azure Pipelines macOS runs

plugins/obs-filters/color-grade-filter.c
While discussing the Flatpak RFC [1], it was spotted that the
LUT filter couldn't open the file selection dialog. It was
explained, then, that the proper formats were either composed
of "User Label (file extensions)", or "file extensions", and
the LUT filter was setting "(file extensions)" without the
actual user label.
While this works on a standard Qt file selection dialog, it
cannot be properly formatted as a set of D-Bus filters, thus
breaking the sandbox integration.
Add a simple user label to the LUT file filter.
[1] https://github.com/obsproject/rfcs/pull/21
Add the LUT filter to any image source when running OBS Studio either from Flatpak or a standard execution, and click the "Browse" button to select the LUT picture.
=> obs-filters: Add a user label to the LUT filter

plugins/CMakeLists.txt
Enable vlc-video plugin on FreeBSD, as a1ec0ecee3 for Linux.
Plugin works fine on FreeBSD so enable it. Although it seems the VLC plugin is somewhat deprecated in favour of the media plugin it's reported to have some features not yet supported there.
Built and sanity tested on FreeBSD-current, creating a playlist with a few entries.
=> vlc-video: Enable building the plugin on FreeBSD

plugins/rtmp-services/data/package.json, plugins/rtmp-services/data/services.json
Add ingest list for Nimo TV
Limit the maximum bitrate to improve service quality.
Tested on Windows 10 and Mac OS X 10.15.3.
=> rtmp-services: Add Nimo TV

plugins/obs-ffmpeg/obs-ffmpeg-output.c
The error message in the process_packet function was prefixed with "receive_audio" because it was previously from code in the encode_audio function which was called from the receive_audio function. This is just a string change to avoid being misled to believe that the error is always audio related.
Previously, the logged error might be:
> receive_audio: Error writing packet: Invalid argument
Now the logged error will be:
> process_packet: Error writing packet: Invalid argument
We should provide clearer error messages in the log.
I compiled OBS on Win10 1903 64-bit and caused an encoder failure to trigger this log line.
- Logging change (non-breaking change which does not change functionality)
=> obs-ffmpeg: Update error message in process_packet

libobs-opengl/gl-cocoa.m
Parent context lock keeps GL commands serialized.
Fixes race that causes crash when resizing multiview.
Fixes #2848
Spammed multiview resize, and OBS would normally crash much sooner, but it stayed alive.
=> libobs-opengl: Lock Mac parent context during present

libobs/obs-win-crash-handler.c
Follow-up to eadb96f.  Add Windows 10 release version (e.g., 1809, 1903, 1909) to the crash log.
Make crash logs contain the same Windows version string as the regular log.  This makes it easier to determine the Windows 10 version at a glance from just the crash log header.
I built OBS on Win10 64-bit and induced a crash in a browser source to trigger the crash handler.  That resulted in OBS outputting a crash log with the following header:
> Unhandled exception: 80000003
Date/Time: 2020-04-30, 01:34:03
Fault address: 7FFBB4681562 (c:\users\rytoex\documents\code\obsproject\obs-studio\build64\rundir\relwithdebinfo\obs-plugins\64bit\libcef.dll)
libobs version: 25.0.7-61-gb20e71cd-modified (64-bit)
Windows version: 10.0 build 18362 (release: 1903; revision: 778; 64-bit)
CPU: Intel(R) …
=> libobs: Add Windows 10 release version to crash log

deps/obs-scripting/obslua/obslua.i, deps/obs-scripting/obspython/obspython.i
Expose platform functions to scripts.
In my specific use case, I want to use the function os_gettime_ns() because Lua's current time function only has seconds precision.
Used functions in scripts.
=> obs-scripting: Expose platform functions to scripts

plugins/image-source/obs-slideshow.c, plugins/obs-ffmpeg/obs-ffmpeg-source.c, plugins/vlc-video/vlc-video-source.c
Make media hotkeys work with studio mode preview.
Better solution than #2805.
Used media hotkeys in studio mode.
=> obs-plugins: Check if sources are showing for media hotkeys

plugins/rtmp-services/data/services.json
Add XLoveCam.com stream service to OBS dropdown options.
www.xlovecam.com is a technical platform, on which users and Performers meet through live chat sessions. Over more than 100,000 registered Performers are using this platform. so add to OBS dropdown options will improve Performers user experience.
Just changed 2 files of services.json. do not effect to other.
Add a stream service.
=> rtmp-services: Add Xlovecam.com streaming service

plugins/vlc-video/vlc-video-plugin.c, plugins/vlc-video/vlc-video-plugin.h, plugins/vlc-video/vlc-video-source.c
This adds a procedure ``get_metadata`` to the VLC video source, which allows the retrieval of metadata about the currently playing media.
Right now there's no safe way of getting this information for a [plugin](https://github.com/univrsal/tuna) I'm working on, so this would provide a proper interface.
I have called the procedure on Arch Linux and Windows 10  and the metadata was delivered fine.
The only thing I noticed is that it will return the metadata of the last played song when the queue is emptied, but ``obs_source_media_get_state`` should be enough to determine whether the returned metadata is for a currently playing song.
I ran formatcode.sh on Linux, but had to manually fix the indentation of a comment so I hope the …
=> vlc-video: Add procedure to receive media metadata

deps/glad/src/glad_glx.c
Use 'extern' to turn the first definition of 'gladGetProcAddressPtr' into a declaration.
GCC-10 defaults to '-fno-common', which triggers issues with multiple definitions of global variables.
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85678
Without the changes, builds will fail like so:
```
FAILED: deps/glad/libobsglad.so.0 
: && /usr/bin/x86_64-pc-linux-gnu-gcc -fPIC -Wall -Wextra -Wvla -Wno-unused-function -Werror-implicit-function-declaration -Wno-missing-braces -Wno-missing-field-initializers -march=znver1 -O2 -fomit-frame-pointer -pipe -mindirect-branch=thunk -std=gnu99 -fno-strict-aliasing  -Wl,-O1 -Wl,--as-needed -shared -Wl,-soname,libobsglad.so.0 -o deps/glad/libobsglad.so.0 deps/glad/CMakeFiles/glad.dir/src/glad.c.o deps/glad/CMakeFiles/glad.dir/src/glad_glx.c.o …
```
=> deps/glad: Fix build with GCC-10

libobs/obs-scene.c, libobs/obs-source.c
Explicitly disables the ability to "Paste (Duplicate)" for a nested scene. Does not affect "Duplicate Scene" capabilities. Does not affect studio mode duplicate sources.
Improvement of #2737
Fixes #2736
On windows 64 bit trying to duplicate scenes
=> libobs: Don't allow duplicating scene sources

libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-capture.h, plugins/win-capture/window-capture.c
Make WGC window capture recover from GraphicsCaptureItem closure, which
can occur when following links in fullscreen Chrome for example.
Window capture was stuck in a state where the capture was severed, but it didn't know.
Following links in fullscreen Chrome now work, albeit with a black hiccup.
=> libobs-winrt: win-capture: Detect GraphicsCaptureItem closure

plugins/obs-ffmpeg/obs-ffmpeg-output.c
Fix an issue in the way AVFrames were handled in the FFmpeg
encoder plugin, which could lead to tearing in the encoded
video due to data races in the AVFrame and AVBuffer.
This is fixed by calling av_frame_make_writable which ensures
the frame and its associated buffer are writable. If its not,
it will copy the AVFrame, create a new AVBuffer for it and
decrease the refcount of the old AVFrame and AVBuffer.
This way OBS always ends up with a usable buffer to write into
which is not still used by the encoder while avoiding a copy
when unnecessary.
This issue was most noticeable with the ProRes encoder with a large output
bitrate as it caused severe tearing in the output.
Tested with a debug build on Windows 10, 64bit.
=> obs-ffmpeg: Fix AVFrame handling in FFmpeg output

plugins/mac-capture/mac-window-capture.m
Better practice for the tracked size to be nonzero.
This does NOT speed up window capture significantly.
Code inspection of Mac window capture found this minor issue.
Window capture on Mac still works.
=> mac-capture: Use resize instead of reserve

libobs/util/darray.h
Test desired capacity against original capacity instead of size.
Noticed a spot in code where the allocation was recreated unnecessarily.
Allocation was no longer being recreated.
=> libobs: Fix da_reserve early return logic

libobs/obs-windows.c
Remove entry from the top of the log. Always returns S_FALSE, and that's
unlikely to change.
Remove unhelpful log message.
Log no longer has success message in it.
=> libobs: Remove log entry for CoInitializeEx pass

libobs/graphics/math-extra.c
If the previously calculated torque value is too close to 1.0 (but not considered 1.0), it would be impossible for the TBar to finish its transition since it returned the old value, causing desync.
Makes TBar much more reliable
Fiddled with the TBar for a *very* long time.
=> libobs: Return target instead of current in calc_torquef

plugins/win-capture/window-capture.c
WGC will give up on a window that it fails to capture, but that
shouldn't stop it from attempting to capture new windows.
Fixes #2928.
WGC was failing to capture relaunched applications.
Relaunched calculator as outlined in the issue.
=> win-capture: Reset WGC fail flag for new window

UI/frontend-plugins/frontend-tools/forms/scripts.ui, UI/frontend-plugins/frontend-tools/scripts.cpp
Hide script tab bar when there are no Python settings.
Before:
After:
Makes the dialog visually look better.
Opened scripts dialog to see if tab were hidden as expected.
=> UI: Hide script tabs if no python settings

UI/volume-control.cpp
When dragging a dock in/around the Audio Mixer dock, the Volume Meter would assume the sudden change in size was caused by audio clipping, but only when no audio was being played. This seems to be specific to the horizontal meters.
Before this fix:
The clipping indicator should only be visible when the audio is **actually** clipping.
Undock Sources, and drag it in/around the mixer dock. Make sure no audio is playing. You may need to first play audio, then wait for the meters to settle, then drag Sources.
=> UI: Don't clip meters when resizing with no input

libobs-opengl/gl-shaderparser.c, plugins/obs-filters/color-grade-filter.c, plugins/obs-filters/data/color_grade_filter.effect
LUT improvements:
- Previously assumed zero to one domain instead of respecting values.
- Tetrahedral interpolation for 3D LUTs instead of trilinear.
We have separate shaders for 1D and 3D LUTs now because domain handling is per-channel for 1D LUTs, and all channels combined for 3D LUTs. We also need separate shaders for tetrahedral interpolation for 3D LUTs as requested by the CUBE spec. 1D LUTs are still linearly interpolated per channel.
Tetrahedral interpolation math source: https://www.nvidia.com/content/GTC/posters/2010/V01-Real-Time-Color-Space-Conversion-for-High-Resolution-Video.pdf
If anyone uses DOMAIN_MIN and DOMAIN_MAX in their CUBE file, they will have wrong colors.
If anyone expected tetrahedral interpolation, they were not getting it.
PNG, 1D, and 3D LUTs still work.
Tried …
=> Implement CUBE LUT domain properly, tetrahedral interpolation for 3D LUTs

UI/window-basic-auto-config-test.cpp
Use standard resolutions in the auto-config dialog.
- 2160p
- 1440p
- 1080p
- 720p
- 480p
- 360p
- 240p
Found it annoying when it would recommend 1151x647, for example.
Used auto-config wizard to setup resolutions.
- UI tweak
=> UI: Use standard resolutions with auto-config

plugins/win-capture/graphics-hook/vulkan-capture.c
Use allocation callbacks for layer-specific allocations, so applications can track memory allocations.
Be a good Vulkan citizen.
Breakpoint inspection of most paths. Neither vkcube nor Doom 2016 use allocation callbacks, so I hacked up vkcube. No issues with or without allocation callbacks as far as I can tell.
=> win-capture: Use VkAllocationCallbacks

plugins/win-capture/graphics-hook/CMakeLists.txt, plugins/win-capture/graphics-hook/vulkan-capture.c, plugins/win-capture/graphics-hook/vulkan-capture.h
Cleaner COM usage.
Check for VK_KHR_external_memory_win32 support.
Noticed minor things while making other changes. Reduce confusion, increase obviousness.
Debugger breakpoint inspection for all diffs.
=> Vulkan hook COM clean up, and extension check

plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
This change adds Profile and Extra options to FFmpeg VAAPI output.
With certain resolutions (such as 3440x1440), using an inappropriate level not only fails to produce output, it can trigger strange behavior on the kernel (witnessed with dmesg, using level 4.2, the highest supported before this patch).
FFmpeg allows specifying level -99 (defined by FF_LEVEL_UNKNOWN macro) which instructs it to decide the appropriate level automatically.
The level names were removed since they are not accurate representation of what the level means. This assumes that whoever decides to tune with it knows what they're doing.
Encoding profiles were also exposed to allow more flexibility (instead of being restricted to CONSTRAINED_BASELINE).
Fedora 31, Mesa 20.0.1, AMD Fury X.
Recorded desktop and HDMI …
=> Expose more levels and profiles for FFmpeg VAAPI

libobs-winrt/winrt-capture.cpp, plugins/win-capture/CMakeLists.txt, plugins/win-capture/window-helpers.c
Illegal CopySubresourceRegion parameters were sometimes computed when
minimizing and restoring WGC window captures, leading to device loss.
Add robust safeties to ensure that doesn't happen.
Also prevent cloaked window handles from being selected for minimized UWP apps like Calculator because they will fail to capture even after uncloaking. For some reason, there is still an alternate uncloaked handle that can be latched onto.
Fixes #2932.
Device loss is very bad.
Debugger breakpoint inspection. Minimized and restored window many times.
=> Fix WGC minimize handling

plugins/win-capture/graphics-hook/vulkan-capture.c, plugins/win-capture/graphics-hook/vulkan-capture.h
Don't allow unsupported Vulkan formats to fall back to B8G8R8A8.
Probably better to fail completely than do an illegal copy.
Also remove bad conversion for VK_FORMAT_A2R10G10B10_UNORM_PACK32.
Red and blue channels were reversed, and there's no DXGI equivalent.
Addresses #2796. We can do more later if justified.
AMD noticed we weren't handling VK_FORMAT_A2R10G10B10_UNORM_PACK32 correctly.
Hacked up vkcube to test VK_FORMAT_A2R10G10B10_UNORM_PACK32 (not working with appropriate logging), and VK_FORMAT_A2B10G10R10_UNORM_PACK32 (working).
=> win-capture: Fail on unsupported Vulkan formats

libobs-winrt/CMakeLists.txt, libobs-winrt/winrt-capture.cpp, libobs-winrt/winrt-capture.h, libobs-winrt/winrt-dispatch.cpp, libobs-winrt/winrt-dispatch.h, libobs/obs-video.c
Make sure render thread is set up with winrt apartment and dispatcher queue initialized.
MS discussion is here: https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/59
Recommended for WGC stability. We were seeing infrequent hangs on shutdown.
WGC still works. Also messed with downscale filter to force graphics thread recreates.
WIndows 7 also seems to work fine.
=> Set up dispatcher queue for WGC stability

libobs/graphics/graphics.c
Fix potential truncation warnings
I hate warnings.
Debugger breakpoint inspection, both paths. (Flip path contrived by flipping test; no existing code actually enters.)
Generated disassembly is a little bit tighter as well.
=> libobs: Fix potential truncation warnings

deps/media-playback/media-playback/media.c, plugins/obs-ffmpeg/obs-ffmpeg-source.c
When using an IP camera on a local network, we wanted to minimize delay. In order to achieve minimum delay, we allowed Media Source to set `BufferingMB` to 0, and when it is 0, also enable `AVFMT_FLAG_NOBUFFER` in the `AVFormatContext` flags.
We are using RTMP IP cameras as Media Sources and OBS introduces an unacceptable delay.
We are using this patch with IP cameras and Ubuntu 19 for video production.
=> media-playback: Unbuffered Media Source
