obsproject/obs-studio

- libobs/obs-view.c
Multiple mixes can share a view (as demonstrated with the GPU scaling feature), so we should reset the view for *all* mixes, not just the first one that uses it.
Fix bugs.
Hasn't.
> libobs: Fix obs_view_remove only resetting the first matching mix

- docs/sphinx/reference-core.rst
- libobs/obs-view.c
- libobs/obs.h
- Deprecates `obs_view_get_video_info()`
- Adds `obs_view_enum_video_info()`
Existing function will only return info for first mix using the view, but multiple mixes can use it. Note that these are not used internally at the moment, but for the sake of correctness this feels good to do.
N/A
> libobs: Add obs_view_enum_video_info and deprecate obs_view_get_video_info

- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs-video-gpu-encode.c
Change encoder pairing to sync video encoder to all audio encoders and vice-versa.
Also removes unused `wait_for_video` bool.
Fixes longstanding issue where first audio track in multi-track recordings is offset from the other audio tracks.
Fixes #4530
| **Before** | **After** |
| - | - |
| ![before](https://github.com/obsproject/obs-studio/assets/3123295/1d9f6109-0942-4748-b3ab-bc40ba878477) | ![after](https://github.com/obsproject/obs-studio/assets/3123295/41a3b631-ea2d-4111-9d8a-6abe8cdd2f47) |
Made some test recordings and confirmed no longer broken.
> libobs: Pair video encoder with all audio encoders

- plugins/obs-vst/win/EditorWidget-win.cpp
On Windows, the VST plugins' window sizes are rendered larger than the actual content on displays that have UI scale factor. The sizes are larger by the scale factor, for example, 100x100 content will have a 200x200 window on a 200% scaled screen, and 150x150 on a 150% scaled screen. This change adjust the window size to fit the content size. The screenshot is a loaded VST plugin with an extremely big window.
The problem described in the description above makes VST plugins difficult to use on HiDPI screen. This change makes the window as big as its content.
Issue #8092 talked about this problem. This change should fix it.
I tested the change with VST2 plugins from MeldaProduction's MFreeFXBundle, and Youlean Loudness Meter 2. The MeldaProduction plugins are HiDPI aware plugins that adjust …
> obs-vst: Fix incorrect VST window size on HiDPI display

- plugins/mac-capture/mac-sck-video-capture.m
Adds a check for an invalid <nil> display ID to bail out early and avoid non-deterministic deadlocks caused by ReplayKit failing internally.
In some scenarios ScreenCaptureKit will not call our completion handler when an internal ReplayKit error occurred. This seems to be more common when a <nil> display id is provided as the content filter for ScreenCaptureKit.
The issue was reported to Apple as FB13455947, but it is good practice for us to check for an invalid display ID before even attempting to start a capture stream.
Fixes https://github.com/obsproject/obs-studio/issues/9923
Tested on macOS 14.1.2.
> mac-capture: Fix ScreenCaptureKit deadlock when using invalid display ID

- UI/window-basic-main.cpp
This disables pasting transforms on an item that is locked.
Transformations shouldn't be modified if a scene item is locked.
Tried pasting with locked scene items to make sure it didn't work anymore.
> UI: Don't paste transform on locked item

- UI/window-basic-main.cpp
- UI/window-basic-transform.cpp
- UI/window-basic-transform.hpp
The transform window was still accessible if the scene item was locked.
You shouldn't be able to edit the transform of a locked item.
Locked/unlocked scene items to make sure the transform window was disabled.
> UI: Disable edit transform if item is locked

- plugins/image-source/obs-slideshow.c
While `ss_update` used the mutex, `ss_video_tick` did not, so concurrent access was not well protected. This could cause crashes if an update modified the files as the tick function was running concurrently.
Hopefully fixes random slideshow crashes such as #5260.
Was not able to reproduce the race condition to actually test this, but I think the change is good.
> image-source: Use mutex when accessing slideshow

- libobs/obs-output.c
Fix audio-only output did not receive `raw_audio` callback at all.
I want to make a plugin that outputs mixed audio track(s).
When defining `obs_output_info` as below, the callback `raw_audio` was never called.
```c
struct obs_output_info vban_output_info = {
.id = ID_PREFIX "output",
.flags = OBS_OUTPUT_AUDIO,
.get_name = vban_out_get_name,
.create = vban_out_create,
.destroy = vban_out_destroy,
.start = vban_out_start,
.stop = vban_out_stop,
.raw_audio = vban_out_raw_audio,
.update = vban_out_update,
.get_defaults = vban_out_get_defaults,
.get_properties = vban_out_get_properties,
};
```
As a workaround, audio arrives if adding `OBS_OUTPUT_VIDEO` to `flags` and defining `raw_video`. However, I don't think this workaround is not ideal as it causes raw-video to be sent from the GPU.
- …
> libobs: Fix audio-only output did not receive raw_audio

- libobs-d3d11/d3d11-subsystem.cpp
Can't hurt to know what Windows thinks the mastering primaries are.
Doubt this info would be used in a support situation, but it could. Plus it's fun to have the info there.
Example output:
```
22:04:00.652: 	    space=RGB_FULL_G2084_NONE_P2020
22:04:00.652: 	    primaries=[r=(0.679688, 0.312500), g=(0.281250, 0.666016), b=(0.154297, 0.066406), wp=(0.312500, 0.329102)]
22:04:00.652: 	    relative_gamut_area=[709=1.266340, P3=0.933509, 2020=0.669730]
22:04:00.652: 	    sdr_white_nits=100
```
> libobs-d3d11: Add display primaries to the log

- plugins/win-capture/graphics-hook/d3d11-capture.cpp
- plugins/win-capture/graphics-hook/dxgi-capture.cpp
Use ID3DDestructionNotifier to handle destruction rather than hook IUnknown::Release, which has an unreliable ref count although the ref count has not been a source of known bugs as far as I know.
Also delete some unused member variables.
Should note that this does nothing to fix the D3D12 leak.
Clean up my past changes.
Sample D3D11 application still terminates with no leaks.
> win-capture: Clean up code in game capture

- plugins/win-capture/CMakeLists.txt
- plugins/win-capture/audio-helpers.c
- plugins/win-capture/audio-helpers.h
- plugins/win-capture/cmake/legacy.cmake
- plugins/win-capture/data/locale/en-US.ini
- plugins/win-capture/game-capture.c
- plugins/win-capture/window-capture.c
- plugins/win-wasapi/win-wasapi.cpp
Based on discussions and ideas from others I've come up with five differrent ways of doing this, this PR represents my favoured one but this is still up for discussion:
1. (first attempt) Making window/game capture a composite source ([branch](https://github.com/derrod/obs-studio/commits/game-cap-linked-audio-legacy))
2. Rerouting audio in libobs ([branch](https://github.com/derrod/obs-studio/commits/libobs-reroute-audio))
3. **(this PR)** Procedure call in win-wasapi to reroute its audio to another source ([branch](https://github.com/derrod/obs-studio/commits/wasapi-reroute-proc))
4. Using a submix in win-capture ([branch](https://github.com/derrod/obs-studio/commits/win-capture-audio-mix))
5. Using audio callbacks to re-emit the wasapi source's audio …
> win-capture: Add audio capture option to window/game capture

- plugins/win-wasapi/win-wasapi.cpp
Initialize a pointer `reroute_target` with `nullptr`.
The pointer `reroute_target` was never initialized if the reroute was not set but read during processing audio.
https://github.com/obsproject/obs-studio/pull/9524#issuecomment-1852857321
Checked the nightly build (4b28631a9) crashed but this build (a7d7ccc18) did not crash.
> win-wasapi: Initialize a pointer reroute_target

- plugins/linux-pipewire/pipewire.c
- plugins/linux-pipewire/pipewire.h
- plugins/linux-pipewire/screencast-portal.c
Massage the function to connect PipeWire streams to receive construction info through a small struct embedded, instead of directly from the function arguments.
This is a tangential cleanup split out from https://github.com/obsproject/obs-studio/pull/9771 to help reviewers.
- Run OBS Studio on Linux / Wayland, add a screen or window capture
- Notice it continues to work normally
> Preparations for Camera portal, part 3

- UI/data/themes/Acri.qss
- UI/data/themes/Grey.qss
- UI/data/themes/Light.qss
- UI/data/themes/Yami.qss
In the Yami theme, when a ediableList (`QlistWidget`) inside a `QGroupBox`, the background color are same, not easy to distinguish.
So change the `QListWidget` background color to other (*the comboBox background color*).
after:
Yami
light:
grey:
acri:
fixes #8302 
the background-color of `QListWidget`(`QAbstractItemView`) same to `QGroupBox` and `PropertiesContainer`
Win10
Just rebuild and look at the background changes.
> UI: Fix editableList inherits background-color of the group

- UI/window-basic-preview.cpp
When rotating or flipping a scene item the resize cursor is not updated correctly. With this fix the cursor gets set according to the item rotation, the horizontal scale and the vertical scale. It handles all 90° and 45° rotations. All rotations in between are rounded up or down.
Before:
After:
fixes [#7247](https://github.com/obsproject/obs-studio/issues/7247)
I've tested it with nearly every rotation and transformation that is possible on windows with dev version.
What else should I test?
> UI: Fix the resize cursor with respecting the item transformation

- UI/qt-wrappers.hpp
- UI/source-tree.cpp
Since QSignalBlocker does the same thing, remove SignalBlocker.
Remove unnecessary code
Ran OBS to make sure nothing broke
> UI: Remove SignalBlocker

- libobs/util/platform-cocoa.m
Changes available disk space calculation on macOS to use more generic available disk space volume resource for non-local volumes.
While the NSURLVolumeAvailableCapacityForOpportunisticUsageKey resource correctly reports available disk space for local volumes (regardless of actual file system used), it does not report actual values for attached network drives.
The NSURLVolumeAvailableCapacityKey resource will still report available disk space as expected, so use this value for non-local volumes instead.
This change should have no drawbacks for users: On local volumes and those with support for purgeable disk space, the correct amount of available disk space is reported. For remote volumes, purgeable disk space is not supported in disk space calculations anyway (the feature is not exposed …
> libobs: Fix disk space reporting for attached network drives on macOS

- libobs/CMakeLists.txt
This file got removed in 5177a593af3a2b206887bf78d0d00ecfacb3cc36 (#9954) and as such should no longer be declared as a public header.
Failed to generate a plugin project based on the plugintemplate against current master because the libobs build failed due to this header not existing.
macOS, plugin now generates.
> libobs: Remove obs-ui from public headers

- .github/workflows/build-project.yaml
Updates Xcode selection for GitHub Actions builds to Xcode 15.1.
Ensure that OBS Studio builds on GitHub Actions have the same build environment available as local builds.
Requires test on actual CI infrastructure.
> CI: Update build workflow to use Xcode 15.1 on macOS

- cmake/macos/compilerconfig.cmake
Increases build system requirements for macOS builds to Xcode 15.1 and associated macOS 14.2 platform SDK.
Allows the project to use recent fixes and changes to macOS frameworks and also allows restoration of functionality available in older macOS versions that changed in 14.2 and beyond.
Ensures that https://github.com/obsproject/obs-studio/pull/10065 will not break on local builds.
Tested with macOS 14.2.1 and Xcode 15.1 on CI as well as locally.
> cmake: Update build requirements to Xcode 15.1 and macOS 14.2 SDK

- libobs/obs-scene.c
Fixes bounding box crop information not being duplicated when a scene item is duplicated (e.g. when duplicating scenes).
Fix bug.
Duplicated scene, no longer an issue.
> libobs: Fix crop to bounding box not being duplicated with item

- plugins/obs-outputs/rtmp-stream.c
Sends color metadata before the video header for RTMP streams. Only applicable to HDR RTMP streams. Ensures the server sees the correctly configured color metadata first, in cases where the decoder config in the video header has incorrect or missing color information. Mitigates a bug that users with outdated AMD drivers may encounter.
Sends color metadata before the video header for RTMP streams. Only applicable to HDR RTMP streams. 
We noticed in previous testing of HDR HEVC livestreaming over RTMP with AMD RX 7900 XTX, that the decoder config in the video header was missing color metadata. This has since been fixed with the latest drivers. This PR sends the correctly configured container-level HDR color metadata first before sending the video header, mitigating potentially incorrect …
> obs-outputs: Switch RTMP color metadata order

- plugins/obs-outputs/rtmp-stream.c
Removes flag guard to enable HDR streaming for HEVC over enhanced-RTMP. This functionality is currently only supported by YouTube. See github.com/veovera/enhanced-rtmp for the enhanced-RTMP spec.
HDR support for RTMP was previously added in https://github.com/obsproject/obs-studio/pull/8522, according to the enhanced-RTMP spec at [github.com/veovera/enhanced-rtmp](https://github.com/veovera/enhanced-rtmp). This change partially removes the flag guard, to enable streaming HDR with HEVC over RTMP.
Enables streaming HDR with HEVC over RTMP to YouTube.
Notes:
- Streaming HDR with HEVC to YouTube is already supported via HLS in OBS. This enables the capability via RTMP.
- Streaming HDR with AV1 over RTMP to YouTube is not officially supported at this time. 
Tested against YouTube with Nvidia …
> obs-outputs: Enable HDR for HEVC over RTMP

- deps/libcaption/src/utf8.c
Optimize the condition expression of `c[0] >= 0 && c[0] <= ' '` to avoid warnings on platforms where `char` is equivalent to  `unsigned char`.
I'm packaging OBS Studio for RISC-V architecture and it fails with an error message:
```
/build/obs-studio/src/obs-studio-29.1.1/deps/libcaption/src/utf8.c: In function ‘utf8_char_whitespace’:
/build/obs-studio/src/obs-studio-29.1.1/deps/libcaption/src/utf8.c:54:21: error: comparison is always true due to limited range of data type [-Werror=type-limits]
54 |     if (!c || (c[0] >= 0 && c[0] <= ' ') || c[0] == 0x7F) {
|                     ^~
cc1: all warnings being treated as errors
```
According to C reference:
> `char` - type for character representation. Equivalent to either `signed char` or `unsigned char` (which one is implementation-defined …
> libcaption: Optimize branch conditons

- libobs/obs-cocoa.m
Adds hardware model identifier strings (e.g. `MacBookPro18,2` to logs on macOS.
Providing support or debugging issues with OBS on Mac frequently involves querying the user about their hardware beyond just the CPU or GPU. This is because the same chip in a Mac can have different capabilities inside a different chassis, and the user may need different advice accordingly. An M1 chip inside a 13" MacBook Pro has a very different thermal envelope than inside a MacBook Air, for example.
There currently isn't any way to see a user's exact model of machine from logs for Apple Silicon machines. For Intel machines, determining a user's model year currently involves looking up either their CPU or GPU model and seeing which Macs used it, which is a relatively complex series of steps to figure out …
> libobs: Log Mac model identifier

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Saves the last used output resolution to the scene collections.
Useful for supporting changes for #9910 to avoid wrong migrations. Suggested by @Warchamp7 
Ensured it's now saved and there are no leaks.
> UI: Save last used output resolution to scene collection

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Add new Frankfurt, Germany ingest to the IRLToolkit service
For a complete list of ingest locations
JSON decoder doesn't error out
> rtmp-services: Add IRLToolkit Frankfurt ingest

- plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
- plugins/obs-ffmpeg/obs-ffmpeg.c
Removes fallbacks that were necessary for Ubuntu 20.04 and Windows 7, which are no longer supported.
Dead code cleanup.
N/A
> obs-ffmpeg: Remove Windows 7/Ubuntu 20.04 NVENC fallback

- plugins/vlc-video/vlc-video-source.c
This fixes the behaviour of the media_play_pause of the VLC Video Source, to bring it in line with the media source and the documentation.
`libvlc_media_list_player_pause_` acts as a pause toggle, unpausing the video if it is currently paused. As such, calling `media_play_pause(vlc_source, true)` would unpause the video if currently paused, effectively ignoring the value of the bool.
This fixes it by checking for the state before calling the libvlc functions.
There is a very slight technical breaking change here : `media_play_pause` is now a no-op when called on a source that is in a state other than playing or paused.
Previously, when calling `media_play_pause` on a video in a state other than playing or paused, the libvlc functions were called, but as far as I can see the only effect …
> vlc-video: Fix play_pause to respect boolean

- plugins/mac-virtualcam/src/camera-extension/OBSCameraDeviceSource.swift
The function that [consumes sample buffers](https://developer.apple.com/documentation/coremediaio/cmioextensionstream/3915931-consumesamplebuffer) in the virtual camera's sink stream appears to be non-blocking. Since the completion handler in OBS calls the parent function directly, this causes the completion handler to be called very frequently, predominantly with a `nil` `CMSampleBuffer`. This PR is one attempt at addressing the amount of calls, modifying the callback to call `consumeBuffer` in tandem with the virtual camera's framerate, via ~~`DispatchQueue`'s `asyncAfter` method~~ a second `DispatchSourceTimer`.
The background CPU usage from the excessive amount of calls to `consumeBuffer` adds up, with various Mac OBS users noting an increase in CPU use of the new virtual camera, and …
> mac-virtualcam: Reduce excessive polling for new sample buffers

- libobs/obs-scene.c
Swaps order to send `item_remove` signal *after* it has actually been removed from the list of scene items
The documentation states
> Called when a scene item has been removed from the scene.
However, as the signal is emitted *before* the removal actually takes place using any enumerations such as `obs_scene_enum_items` in the callback will still produce the "removed" item. This PR changes the order for this to be in line with the documentation.
Has been tested with my ROI WIP UI which suffered from an issue due to the callback triggering an immediate refresh of its internal list of scene items, which would still include the removed item.
> libobs: Send item_remove signal after detaching item

- plugins/mac-capture/mac-sck-video-capture.m
Explicitly enable capture of the menu bar and child windows for application capture on macOS.
macOS 14.2 changed internal defaults of SCK requiring the inclusion of the menu bar and child windows to be enabled explicitly.
This will have a slight negative impact on capture performance but is required to restore behaviour of prior macOS versions.
Tested on macOS 14.2.1.
> mac-capture: Update capture to include menu bar and child windows

- UI/window-basic-main.cpp
Some variables were not guarded for being unused when built with FFmpeg 6.1
Fix building UI with #9787
```
[build] …/obs-studio/UI/window-basic-main.cpp: In member function ‘void OBSBasic::AutoRemux(QString, bool)’:
[build] …/obs-studio/UI/window-basic-main.cpp:7586:14: error: unused variable ‘audio_is_pcm’ [-Werror=unused-variable]
[build]  7586 |         bool audio_is_pcm = strncmp(aCodecName, "pcm", 3) == 0;
[build]       |              ^~~~~~~~~~~~
```
```
[build] …/obs-studio/UI/window-basic-main.cpp: In member function ‘void OBSBasic::AutoRemux(QString, bool)’:
[build] …/obs-studio/UI/window-basic-main.cpp:7582:21: error: unused variable ‘aCodecName’ [-Werror=unused-variable]
[build]  7582 |         const char *aCodecName = obs_encoder_get_codec(audioEncoder);
[build]       | …
```
> UI: Fix unused-variable

- UI/window-basic-main-screenshot.cpp
Fixes an issue where filters that resize a source, like "Crop/Pad" or "Scaling/Aspect Ratio", change the texture but the new source size gets ignored, effectively either cropping the screenshot or giving it black borders.
Fixes #9956
macOS 14.2
Took a screenshot of a source that had a Crop/Pad filter applied and confirmed that the black border has gone away.
> UI: Use normal source width for screenshots

- plugins/obs-ffmpeg/obs-ffmpeg.c
- plugins/obs-ffmpeg/obs-nvenc-helpers.c
- plugins/obs-ffmpeg/obs-nvenc.c
- plugins/obs-ffmpeg/obs-nvenc.h
Changes fallback to use NVENC version reported by driver to determine which version should be used, rather than always using the old version for non-AV1 codecs.
- We might want to actually use a newer SDK features at some point (e.g. explicit split encoding in 12.1)
- The ROI feature #10039 breaks when using the compat version, this should fix that by not using it when unnecessary
NVENC still works on my 4090.
This has *not* been tested on a system that requires the compatibility workaround as my current GPU is not supported by driver versions that old (pre-Oct 2022), but I don't see why it would break.
> obs-ffmpeg: Only use NVENC compatibility hack if necessary

- UI/forms/OBSBasicSettings.ui
- UI/window-basic-main-outputs.cpp
- UI/window-basic-main.cpp
- UI/window-basic-settings-stream.cpp
- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.h
This adds support for multi-track audio for mpegts outputs (srt or rist).
Also modifies UI.
For mpegts compatible protocols, this changes radio buttons into checkboxes for the audio track selection in the Streaming output (only in Advanced output).
YouTube has added support for SRT ingest and allowed broadcast engineers to test it during the 2023 SRT Plugfest.
I was told during the zoom introduction that multi-track support is being worked on by YouTube (public discussion,
there was no NDA).
I had this code around for a while, so it seems it's the right time to add it to obs.
Maybe multi-track will be supported also by RTMP (who knows) and the  code would use the UI parts of this PR.
Tested against several services during 2023 SRT Plugfest.
Works as expected. One can play any track.
- New …
> obs-ffmpeg: Enable multi-track audio support for mpegts

- libobs/obs-scene.c
With https://github.com/obsproject/obs-studio/commit/aaf8d8b38fba518d6dbeef92fbf75b0738843d10 changing the order `item->parent` would be NULL thus resulting in a crash.
Fix my dumb mistake from apparently not testing this (properly).
OBS runs and doesn't crash :)
> libobs: Pass parent pointer into signal_item_remove

- plugins/obs-ffmpeg/obs-nvenc.c
Fixes issue with #10084 where the ternarys were all the wrong way around after updating them to the new variables 😅
Makes the compat hack actually work.
Tested on my 4090 to make sure the new version is actually used now.
> obs-ffmpeg: Fix NVENC compat hack ternary being inverted

- cmake/finders/FindMbedTLS.cmake
Remove `DEFAULTLIB` directive of MbedTLS for Debug builds on Windows.
Natively compiled MbedTLS for Windows will use the non-debug platform library, which will lead to a linker error when building OBS in debug configuration with MSVC.
Neutralizing the linker directive for Debug builds on Windows unbreaks the build configuration without the need to ship separate debug variants of MbedTLS.
Tested on Windows 11 with natively compiled MbedTLS static libraries.
> cmake: Update MbedTLS finder to support MSVC Debug configuration

- plugins/obs-ffmpeg/cmake/dependencies.cmake
Fix incorrect CMake `list` invocation. The current syntax had arguments in the incorrect order and also incorrectly used `_error_string` twice. Fix the syntax to join the `_error_messages` strings into `_error_string` so that the error messages are correctly displayed.
Want CMake errors to be clear when they occur.
https://cmake.org/cmake/help/v3.27/command/list.html#join
> `list(JOIN <list> <glue> <output variable>)`
>
> New in version 3.12.
> 
> Returns a string joining all list's elements using the glue string. To join multiple strings, which are not part of a list, use [`string(JOIN)`](https://cmake.org/cmake/help/v3.27/command/string.html#join).
Tested locally against a copy of deps where librist could not be found to ensure the error message appeared. …
> obs-ffmpeg: Fix incorrect CMake list syntax

- plugins/image-source/CMakeLists.txt
- plugins/image-source/cmake/legacy.cmake
- plugins/image-source/image-source.c
- plugins/image-source/obs-slideshow-mk2.c
Adds a new version of the slideshow that now supports as many files as you like without a memory limit. It can now decode asynchronously without stalling the OBS video feed.
You must set an explicit size for the slideshow, but this is mostly due to the fact that it can no longer read all the files to determine a maximum size. The default size is 1920x1080.
To achieve asynchronous decoding without affecting slides, some minor modifications to the image source had to be made, and a task thread had to be put in to decode any new files. There are now five slides buffered ahead of the current slide, and five slides buffered behind the current slide, which will help ensure that neither the OBS video feed nor the slideshow are impacted when loading very large or complex image files.
The …
> Rework slideshow (slideshow mk2)

- plugins/obs-outputs/librtmp/rtmp.c
According to https://rtmp.veriskope.com/docs/spec/#5313-extended-timestamp extended timestamps need to be present in Type 3 chunks (`RTMP_PACKET_SIZE_MINIMUM`) if the previous chunk also included an extended timestamp
Ran into this issue while playing around with sending large payloads in byte arrays (similar to Twitch VOD track) that exceeded the rtmp chunk size (thus librtmp split the payload over multiple packets, triggering this issue)
Add the following code to `rtmp-stream.c`:
```c
stream->start_dts_offset = get_ms_time(packet, packet->dts);
stream->start_dts_offset -= 0xffffff - 15000;
```
and send large INFO packets; the issue should be triggered within a few seconds
> librtmp: Add missing extended timestamp in Type 3 chunks

- plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
- plugins/obs-ffmpeg/obs-nvenc.c
This is functionally the same as x264's `scenecut=0` option
This allows for multiple NVENC encoders to stay GOP/keyframe aligned, which is interesting for applications using https://github.com/obsproject/obs-studio/pull/8093 targeting e.g. HLS or similar formats that require keyframes to be aligned
Tested via Twitch Enhanced Broadcasting
> obs-ffmpeg: Add `disable_scenecut` option for NVENC

- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.hpp
Saves transitions that failed creating the source properly in separate array if safe mode is enabled.
There may be a better way of doing this, hence a draft.
Fixes #9963 
Verified transitions are not removed from JSON anymore.
> UI: Save invalid transition source data in safe mode

- docs/sphinx/reference-encoders.rst
- libobs/obs-encoder.c
- libobs/obs-encoder.h
- libobs/obs-internal.h
- libobs/obs.h
- plugins/obs-ffmpeg/obs-nvenc.c
- plugins/obs-ffmpeg/texture-amf.cpp
- plugins/obs-qsv11/QSV_Encoder.cpp
- plugins/obs-qsv11/QSV_Encoder.h
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/QSV_Encoder_Internal.h
- plugins/obs-qsv11/obs-qsv11.c
- plugins/obs-x264/obs-x264.c
Adds support for specifying regions of interest (ROI) for video encoders.
ROI is a means of prioritising certain regions of the frame for encoding, i.e. retaining higher quality, or sacrificing quality, in areas of the encoded picture.
Possible use cases are:
1. Ensuring important elements remain legible even in bitrate-starved scenarios (e.g. face cam, UI text)
2. Increasing perceptual quality by assigning priority to center of attention (e.g. crosshair in FPS games)
3. Making [fun glitch art](https://pbs.twimg.com/media/GCGxFYGWQAAUo1M?format=jpg&name=large) 😛
**No ROI:**
https://github.com/obsproject/obs-studio/assets/3123295/eaf54245-d9b1-4d50-9715-4b0102c8c724
**ROI on "face cam":**
https://github.com/obsproject/obs-studio/assets/3123295/8f3ed4af-d520-4db9-8b6a-55c1a24c932e
This …
> libobs/plugins: Add region of interest (ROI) encoder feature

- build-aux/com.obsproject.Studio.json
With an Intel GPU, the QuickSync encoders fail to start in the Flatpak build:
```
info: [qsv encoder: 'advanced_video_recording'] debug info:
error: Failed to initialize MFX
Specified object not found. /run/build/obs/plugins/obs-qsv11/common_utils_linux.cpp 140
Specified object not found. /run/build/obs/plugins/obs-qsv11/QSV_Encoder_Internal.cpp 156
warning: [qsv encoder: 'msdk_impl'] Specified object/item/sync point not found. (MFX_ERR_NOT_FOUND)
warning: [qsv encoder: 'advanced_video_recording'] qsv failed to load
```
Tracing this back points to the `MFXCreateSession` call [in common_utils_linux.cpp](https://github.com/obsproject/obs-studio/blob/0e5007794836c31bebd46fb492776f38f84f0441/plugins/obs-qsv11/common_utils_linux.cpp#L137), implemented on `libvpl`'s side in …
> build-aux: Work around oneVPL search path for Flatpak QSV

- UI/data/locale/en-US.ini
- UI/forms/OBSBasicSettings.ui
- UI/window-basic-main-outputs.cpp
- UI/window-basic-main.cpp
- UI/window-basic-settings.cpp
Adds a combobox to set GPU scaling filter to the advanced output UI:
- Allows people to use texture encoders such as NVENC while using rescaling
- Higher qualty scaling
NVENC and x264.
> UI: Implement GPU scaling options

- plugins/obs-ffmpeg/texture-amf.cpp
If a user sets both `AdaptiveMiniGOP=true` and `EnablePreAnalysis=true` in the AMF/FFmpeg options field, AMF will adaptively insert B-pictures, and no longer uses the fixed B pattern. Since `MAX_CONSECUTIVE_BPICTURES` is hard-coded to 3, the max B-frame UI setting is not respected. Furthermore, for a fixed B-frames pattern, it is expected that increasing B-frames can cause a quality drop for certain content such as with high motion. AdaptiveMiniGOP is recommended when using B-frames to improve the quality in such cases. AdaptiveMiniGOP is dependent on PreAnalysis which means that trying to enable it without having PreAnalysis turned ON will have no negative effect (AdaptiveMiniGOP won't be enabled).
Additionally, if a UI element for enabling PreAnalysis such as a checkbox is added, it can …
> obs-ffmpeg: Fix issue with B-frames introducing motion blur

- buildspec.json
CI: Update deps to 2024-01-11 release
* deps.qt: Fix library naming for macOS debug builds
* deps.ffmpeg: Fix local universal architecture builds of aom for macOS
* deps: Update Windows build script with explicit package names
* deps.ffmpeg: Switch Windows builds to native build toolchain
The most important item here is "deps.ffmpeg: Switch Windows builds to native build toolchain", which switched from cross-compiling FFmpeg and various other dependencies on Linux for Windows to compiling those dependencies natively on Windows.
See:
* https://github.com/obsproject/obs-deps/pull/186
This PR is being made to provide a distinct point for easily bisecting deps changes. A separate PR with the actual updates to dependency versions will happen later.
As noted on the obs-deps PR, …
> CI: Update deps to 2024-01-11 release

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
- plugins/obs-ffmpeg/obs-ffmpeg.c
- plugins/obs-ffmpeg/vaapi-utils.c
- plugins/obs-ffmpeg/vaapi-utils.h
AV1 support for VA-API encoder.
Added FFmpeg VAAPI AV1 encoder.
~~Draft for now as av1_vaapi FFmpeg encoder is not yet upstreamed.~~
Tested with Mesa driver.
> obs-ffmpeg: Add AV1 support for VA-API

- plugins/obs-ffmpeg/obs-nvenc.c
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/QSV_Encoder_Internal.h
Use 2 tiles in NVENC AV1 for 4K+. When resolution is 4K or higher, use 2 uniform tile columns for NVENC AV1.
Use 2 tiles in QSV AV1 for 4K+. When resolution is 4K or higher, use 2 tile columns for QSV AV1.
Single-tile 4K videos are more difficult to decode. Using 1x2 or 2x1 tiles for 4K should make decoding easier.
This is an updated version of #8788. Defines and constexpr variables have been trimmed down. NVENC is now set to 1x2 (1 row, 2 columns) instead of 2x2.
See also [YouTube's tiling recommendations](https://support.google.com/youtube/answer/2853702):
>Minimum of 2 tile columns for AV1-encoded streams at resolutions of 3840x2160 and above
Previously tested in the original PR, but could use retesting given the adjustments. I did test the QSV change and verified with ffprobe that the …
> Adjust AV1 tiles at 4K+ (v2)

- UI/obs-app.cpp
- UI/obs-app.hpp
This effectively returns `FALSE` for `WM_QUERYENDSESSION` which will throw up the "This app is blocking shutdown" message until the OBS process exits. This allows any shutdown cleanup to run without windows killing the process.
More all-encompassing alternative to #9927
Fixes #9877 until we have a better idea for a long-term solution.
This is a port of #9928. While a more comprehensive solution would probably have us implement Qt's aboutToQuit signal, doing so would likely require a large refactor of our shutdown process. @PatTheMav and I have concluded that such a refactor is unlikely to materialize any time soon, and the alternative without this patch is a bad experience for users.
Tested in a VM and in 30.0.1 and 30.0.2.
> UI: Cancel session end request on commitDataRequest() signal

- libobs/obs-encoder.c
Fix GPU scaling using the main mix
Was missed in #9937
Want to have the correct view for the scaled video
On windows 64 by trying to gpu scale an encoder to same as main.
> libobs: Fix GPU scaling using the main mix

- libobs/obs-audio.c
Fixes audio issue reported in https://github.com/obsproject/obs-studio/pull/10091#issuecomment-1905992836 by only adding the root source for the main mix rather than every mix that uses the main view.
Since scaled mixes also use the main view their root audio nodes would be added multiple times, leading to constructive interference and an increase in volume.
Used media source with ffmpeg sine wave generator, then used `volumedetect` filter in FFmpeg to check recording volume.
No scaling (master):
```
[Parsed_volumedetect_0 @ 0000015d3afe2ac0] mean_volume: -21.1 dB
[Parsed_volumedetect_0 @ 0000015d3afe2ac0] max_volume: -17.4 dB
```
GPU scaling (master):
```
[Parsed_volumedetect_0 @ 0000024149d94180] mean_volume: -15.1 dB
[Parsed_volumedetect_0 @ 0000024149d94180] max_volume: -12.0 dB
``` …
> libobs: Fix audio doubling with multiple main view mixes

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Adding PandaTV to OBS-Studio's Ingest List.
[PandaTV](https://www.pandalive.co.kr) is a livestreaming platform with more than 6 million users. As one of the biggest livestreaming platform, we would like to our creators can start streaming more easily by using OBS. We provide how to stream to OBS on our website, but users frequently forget to set their streaming settings like keyframe interval which is very important issue.  By adding PandaTV rtmp-service, more users will be able to use OBS easier and happier.
- JSON validation: Ensured that the JSON files are well-formed and adhered to the required format for OBS-Studio's ingest list.
- Copy JSON files to %APPDATA%\obs-studio\plugin_config\rtmp-services: Manually copied the JSON files to the appropriate location where OBS-Studio reads …
> Add PandaTV live RTMP service

- libobs/util/c99defs.h
Instead of using the Microsoft-specific __pragma keyword, use the standard _Pragma directive, which is now supported in C11 and C++11 /std modes.
Use the C/C++ standard features over compiler or toolchain specific features where possible.
See:
* https://learn.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=msvc-170
Built locally on Windows 11 with VS 2022 17.8.5.
> libobs: Use std _Pragma

- UI/window-basic-main-outputs.cpp
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.h
1. Set audio tracks name to `settings` when setup FFmpeg output
2. Add `const char *audio_stream_names[MAX_AUDIO_MIXES]` member to `struct ffmpeg_cfg`.
3. Set *tracks name* from step1 `settings` to (`struct ffmpeg_cfg`) `config`.
4. Set *tracks name* in `config` to FFmpeg *stream metadata* `title` when valid(not null) via `av_dict_set`.
fixes #7658 
same as Standard Recording
set audio stream title via `av_dict_set` *title* in `ffmpeg-mux` via command-line
https://github.com/obsproject/obs-studio/blob/c648222332d1a7ce7ea55fd14fbe514a5f258f33/plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c#L538
Win10, latest OBS
via VLC
- audio mux 1,2,3,4
**SETTINGS** audio track names[1-4]:
mux, desk, mic, [empty]
before:
after:
- audio mux 1,4,5
**SETTINGS** audio track names[1-5]:
mux, desk, mic, track4, …
> UI, obs-ffmpeg: Set audio track titles for FFmpeg Output

- cmake/Modules/ObsHelpers.cmake
- cmake/Modules/ObsHelpers_Windows.cmake
- cmake/windows/helpers.cmake
Required by:
- https://github.com/obsproject/obs-browser/pull/431
- https://github.com/obsproject/obs-websocket/pull/1196
Needed to enable installing obs-websocket-api  and obs-browser-api headers
Build on Linux (still uses legacy path) with obs-browser-api PR and check if the header is installed, which is the case.
Ci for Windows and macOS, headers install needs to be checked locally
- Tested on Windows,  `--component Development` adds the header
> Enable exporting CMake interface target

- plugins/obs-webrtc/whip-output.cpp
- plugins/obs-webrtc/whip-output.h
- plugins/obs-webrtc/whip-service.cpp
This adds AV1 support to obs-webrtc
Users wish to use AV1
Tested against Broadcast Box
> obs-webrtc: Add AV1 Support

- cmake/Modules/FindMbedTLS.cmake
FindMbedTLS.cmake uses `check_symbol_exists` macro which requires `include(CheckSymbolExists)` before invocation (see https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html).
Without `include(CheckSymbolExists)` project fails to configure
CMake produces this error on some cases:
```
CMake Error at cmake/Modules/FindMbedTLS.cmake:97 (check_symbol_exists):
Unknown CMake command "check_symbol_exists".
```
> Add CheckSymbolExists module for FindMbedTLS.cmake

- libobs/obs-encoder.c
Prevents an encoder relying on GPU scaling from being assignment a video output that has different dimensions.
Users reported issues about invalid output when using automatically started video recording.
The underlying issue is a race condition in the UI, but this seems like a good thing to do anyways and will prevent this issue from happening until we can fix the UI.
Race condition:
- `OBSBasic::StartStreaming()`
+ Calls `AdvancedOutput::SetupStreaming()`
* Calls `AdvancedOutput::SetupOutputs()`
- Assigns `obs_get_video()` to streaming/recording encoders
+ Calls `AdvancedOutput::StartStreaming()` which starts streaming output
- The GPU scaled output is set up here during encoder init
+ Calls `OBSBasic::StartRecording()`
* Calls `AdvancedOutput::StartRecording()`
- Checks `Active()`, …
> libobs: Prevent encoder reconfiguration after initialization

- libobs/obs-video.c
As the comment mentions this only occurs during an encoder stall on the first frame. With opengl texture encoders we might have multiple planes and need to copy both of them.
On very low power devices this happens once in a while, and it consistently happens on a very terrible egpu configuration.
Fixes the first frame only containing the Luma plane on the egpu setup where I can trigger this consistently.
> libobs: Copy both converted textures on stall

- UI/window-basic-main.cpp
NULL check for `obs_get_encoder_codec(option)` before calling `strcmp(it, "opus")`. `strcmp()` causes segfault when NULL is passed.
I tried to use OBS for streaming to broadcast box with WebRTC, but OBS crashed while trying to load the configuration. This PR fixes it.
It seems this code is ran only when OBS is preparing to display window. I built with this change and I confirmed the change prevents OBS from crashing. I have confirmed it passes all tests.
> UI: Fix null pointer dereference

- .github/actions/services-validator/action.yaml
macOS and the GitHub runners have python3 preinstalled. We only needed to specify a version because aiohttp wasn't compatible with 3.12, but that's no longer the case.
Fixes job.
Ran on fork.
> CI: Do not install python on macOS

- .github/actions/qt-xml-validator/action.yaml
- .github/actions/services-validator/action.yaml
- .github/actions/steam-upload/action.yaml
CI: Update third-party GitHub Actions
This PR updates four third-party actions. These updates should be low-impact. The update with the biggest diff is peter-evans/create-pull-request, though the bulk of the changes are in docs, tests, and generated files. If we don't want to review this diff now, I can pull that update out and we can put it in a different PR later.
----
CI: Update korelstar/xmllint-problem-matcher GitHub Action
We're currently using korelstar/xmllint-problem-matcher v1.1.0 which is based on the deprecated node16. This was fixed in v1.2.0, so let's update to that version's commit.
https://github.com/korelstar/xmllint-problem-matcher/compare/22352420d1d3e8f18d311d76284c4f5f71982222..1bd292d642ddf3d369d02aaa8b262834d61198c0
----
CI: Update CyberAndrii/setup-steamcmd GitHub …
> CI: Update third-party GitHub Actions

- .github/actions/bouf/action.yaml
- .github/workflows/push.yaml
Updates the google cloud related actions in the bouf action to their latest version.
Get rid of the Node deprecation warning
Seemed to work on my fork.
> CI: Update Google Cloud GitHub Actions

- UI/cmake/macos/exportOptions-extension.plist.in
- UI/cmake/macos/exportOptions.plist.in
Attempts to fix code signing with a provisioning profile on GitHub Actions CI runs.
Automatic signing does not seem to work with Xcode 15 anymore, instead manual signing needs to be used for manually provided provisioning profiles.
Using `xcodebuild -export` with the updated exportOptions file successfully exported the application with Xcode 15.1 locally.
Conclusive test requires a tagged push after this has been merged.
> UI: Update exportOptions template for macOS release code signing

- deps/obs-scripting/obs-scripting-lua.c
Fix race condition where `script_tick` is called before `script` is set on the `struct obs_lua_script`
I don't like a crash in the lua scripts when switching scene collections
On windows 11, by testing if scripts still load correctly
> deps/obs-scripting: Fix lua tick crash

- libobs-opengl/gl-wayland-egl.c
- libobs-opengl/gl-x11-egl.c
This is functionally a no-op, but works around a driver bug that prevents use of eglQueryDisplayAttribEXT. This makes us more likely to not trigger the driver bug and that gs_enum_adapters works correctly.
This is just a fixup for the earlier `gs_enum_adapters` functionality.
Drivers will return illegal values which make us think we are running on software renderers after Qt loads. This should avoid the Qt issue at least until drivers get fixed.
Setup the safety mode popup to get qt to render before obs' graphics backend is loaded. Observe device enumeration returns invalid values before the fix and correct display devices after the fix.
> libobs-opengl: Specify display attributes

- plugins/obs-ffmpeg/texture-amf.cpp
This PR changes frame rate setting for AMF encoders.
Frame rate should be defined before AMF encoder initialization, because this information is used for setting vui_time_scale in SPS (Sequence Parameter Set) inside HEVC encoder. If frame rate isn't defined before encoder initialization, then AMF encoder writes default frame rate into VUI (30 fps).
Some applications like DaVinchi Resolve use information about frame rate from SPS.
AMF encoder writes frame rate into SPS during initialization (Init() function), so if frame rate wasn't defined before initialization,
then AMF wrote default frame rate (30fps) into vui_time_scale inside SPS.
As a result, Davinchi Resolve runs video in 2x speed if we have 60 FPS video.
This issue appeared after AMD driver update  to 23.11.1, because it contains a …
> obs-ffmpeg: Fix wrong framerate in VUI header

- libobs/util/platform-cocoa.m
New space availability keys seem to have very specific file system requirements not documented anywhere. Using the opportunistic free space key opportunistically (and falling back on the legacy value otherwise) should always yield a "good-enough" free disk space value.
Fixes inability to record videos to ExFAT and FAT32 volumes on macOS.
Tested on macOS 14.3 with APFS, HFS+, ExFAT, FAT32, and mounted network volumes.
> libobs: Fix free disk space calculation on macOS

- plugins/image-source/obs-slideshow-mk2.c
Check if the number of files is zero before trying to randomize.
Fixes https://github.com/obsproject/obs-studio/issues/10188
Windows only.
Build, add fresh image slideshow source (no files), click randomize. Does not crash.
Try to add a folder with 2000 files, let it run thru a couple of images.
Remove folder (back to 0 files), randomize still enabled, checking breakpoints for sane output.
Re-add folder with 2000 files.
Random function still works (the selection seems random'y).
> image-source: Fix crash when randomize with 0 files

- .github/workflows/build-project.yaml
- .github/workflows/check-format.yaml
- .github/workflows/dispatch.yaml
- .github/workflows/publish.yaml
- .github/workflows/push.yaml
- .github/workflows/scheduled.yaml
The macOS 14 runners are M1-based and more performant than the macOS 13 runners. They also seems less prone to random failure.
Since the access table has changed between macOS 13 and 14, try removing the hack to enable AppleScript. Also update to Xcode 15.2.
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
The difference is staggering. You can find example runs with and without caching on my fork:
https://github.com/RytoEX/obs-studio/actions/runs/7749758334
Here are some average build and package times (based on averages across 6-10 runs of each scenario):
| Runner   | Cached | Build Time | Package Time |
| -------- | ------ | …
> CI: Switch to macOS 14 runners and Xcode 15.2

- UI/window-basic-main-outputs.cpp
RTMP protocol was not being recognized due to a string sensitive comparison; this changes to a case insensitive comparison to fix the issue. Fixes a bug found in beta channel.
Fix a bug.
The bad detection of protocol was preventing Twitch VOD track from being enabled. 
Untested but the fix is obvious.
> UI: Fix RTMP check in Advanced output

- plugins/win-dshow/tiny-nv12-scale.c
NV12 to YUY2 scale will cause obs-virtualcam-module64.dll crash with error YUY2 line size
obs-virtualcam-module64.dll will cause my app crash because of this logic error
it's tested in my PC
OBS Video Color format select NV12 && Capture App Select YUY2
> win-dshow: Fix YUY2 line size error

- .github/actions/steam-upload/action.yaml
Fix Steam workflow failing because PDBs are now part of releases.
Do not want CI runs to fail anymore :(
Tested on my fork.
> CI: Fix Steam workflow getting confused by PDBs

- docs/sphinx/reference-encoders.rst
- docs/sphinx/reference-libobs-util-circlebuf.rst
- docs/sphinx/reference-libobs-util.rst
Fixes warnings that sphinx reported that comes from "recent" changes:
- Add deque to libobs/util table of content
- Fix title underline of obs_encoder_roi
Also fix a deprecation note for circlebuf that was set to a placeholder version (`3X.0`).
Fix docs warnings right after I found them.
`make html` and Sphinx didn't complain of the issues fixed by the changes and deque is shown in the libobs/util TOC.
> docs: Add deque to the table of content and fix ROI underline

- plugins/obs-qsv11/obs-qsv11.c
After adding proper adapter enumeration the linux code ends up entering the texture encoding paths, but these paths are not correctly implemented on linux yet.
fixes #10221
Replicated the issue and this resolves it for me.
> obs-qsv11: Disable texture encoder on linux

- plugins/win-dshow/virtualcam-module/CMakeLists.txt
Add the generated Windows resource file to the shared interface sources of the 64-bit and 32-bit virtual camera sources.
Ensures that the generated virtual camera DLLs contain correct metadata information.
Tested on Windows 11, checked the properties of the generated DLL files.
> win-dshow: Add generated Windows resource file to virtualcam sources

- UI/source-tree.cpp
- UI/source-tree.hpp
Fix source remove log scene
`User Removed source 'Color Source' (color_source_v3) from scene '(null)'`
to:
`User Removed source 'Color Source' (color_source_v3) from scene 'Scene 2'`
The log message indicated scene null
On windows 11 by removing a source from a scene.
> UI: Fix source remove log scene

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Previously we always assumed we could push more frames before an encoded packet would be available. Actually we can get EAGAIN when the frame queue is full and before any encoded packets have been completed.
This changes attempts to read packets more often as the worst that can happen is we get EAGAIN again (i guess).
Fixes a hang in ffmpeg vaapi encoder on intel.
The resulting recording looks correct after enabling bframes on intel's av1 drivers.
> obs-ffmpeg: Receive packets while frame queue is full

- .github/actions/flatpak-builder-lint/action.yaml
- .github/workflows/build-project.yaml
- .github/workflows/publish.yaml
It's a ultimately a temporary workaround while the whole situation with libappstream, Flatpak, and flatpak-builder isn't figured out. But it does seem to work.
The Flathub publishing workflow is broken due to an odd flatpak-builder / appstream impedance mismatch, and this works around that.
The publishing job goes beyond the build step: https://github.com/GeorgesStavracas/obs-studio/actions/runs/7888002165/job/21524497985 (CI fails because I don't have the OBS Studio publishing tokens in my repo, but that's not important)
> Use flathub-infra images & various other cleanups

- plugins/win-capture/audio-helpers.c
Fixes a memory leak.
Leaks bad.
Ran.
> win-capture: Fix leak in wasapi reroute proc call

- plugins/win-capture/game-capture.c
If game capture gets unhooked, set audio source window to `NULL` to avoid it still capturing stuff.
Fixes issue reported in 30.1 beta.
Untested.
> win-capture: Disable audio source when game capture unhooks

- plugins/mac-avcapture/OBSAVCapture.m
- plugins/mac-avcapture/plugin-main.m
- plugins/mac-avcapture/plugin-properties.m
Adds colour format selection to Capture Card source to unbreak situations where specific resolutions do not support the same colour format as the device format the source was created with.
Some devices do not support all color formats at all resolutions, but the capture card source automatically uses an available color format and compares it against the available format for a specific resolution.
Without being able to change this format, some resolutions do not work as CMIO will not be able to find a compatible format. Thus the color format needs to be manually selected for capture card sources as well.
Tested on macOS 14.3.1 with Elgato HD 60x which supports NV12 and YUY2 up to 1080p but only supports NV12 for 2560x1440 and 3840x2160.
> mac-avcapture: Add color format selection for capture card source

- plugins/mac-capture/mac-audio.c
Splits the memory cleanup for channel maps and channel names in macOS audio capture source.
The uninit function prematurely released the memory allocated for the channel map setting, which exists in the scope of source life cycle (compared to channel names which are valid during the life cycle of a configured device).
Splitting up the clean-up for both (memory for channel names is released when the device is uninitialised, memory for channel map setting is released when the source is removed) ensures that the memory is released but pointers don't become unexpectedly invalid.
Tested on macOS 14.3.1, disconnecting and reconnecting a device with active channel map setting, then checking for leaked memory on shutdown.
> mac-capture: Fix crash in device reconnect handler

- UI/volume-control.cpp
Since the audio mixer widget is marked as being opaque it is necessary to draw all of it's pixels in the drawing region. Pixels not being drawn will leave transparent pixels (on Wayland at least) causing undesired effects.
Previously, the background was not filled when only the meters were repainted. Since the meters don't paint the complete region (spacing, padding etc.) some pixels in the region ended up not being painted.
Addressing https://github.com/obsproject/obs-studio/issues/9824
Locally run on GNOME/Wayland which was affected by the bug. After applied fix, the audio mixer looks correctly.
Hopefully this does not regress other platforms..
> UI: Fill audio meter background each update (#9842)

- plugins/win-capture/data/locale/en-US.ini
Capture Audio (BETA) tooltip are long.
Add line break makes the tooltip easier to read.
Before
After
See the #beta-testing channel on Discord.
https://discord.com/channels/348973006581923840/1203061968366206996/1203103512674705501
I opened the translation file and changed the strings to confirm.
Use Windows 11 22H3 
> win-capture: Add line break for capture audio tooltip

- plugins/mac-avcapture/OBSAVCapture.h
- plugins/mac-avcapture/plugin-main.m
- plugins/mac-avcapture/plugin-properties.h
- plugins/mac-avcapture/plugin-properties.m
Fixes OBSAVCaptureInfo struct potentially containing uninitialised values and also fix problematic circular reference of OBSAVCapture instance.
Fixes several possible crash issues that might occur on Intel-based Macs and older macOS versions:
On modern macOS versions (13+) allocated memory is zero-allocated by default which makes NULL pointer checks work correctly after allocation.
On older macOS versions this is not the case, so the OBSAVCaptureInfo struct needs to be zero-allocated to ensure the guards in the tick and render functions bail out correctly.
On Intel-based Macs and/or older macOS versions passing a reference to the OBSAVCapture instance inside the OBSAVCapture struct can lead to a crash because of a possible circular reference that cannot be resolved at runtime.
Passing …
> mac-avcapture: Fix crash issues on Intel-based Macs and older macOS

- UI/window-basic-main.cpp
- UI/window-basic-preview.cpp
- UI/window-basic-source-select.cpp
- UI/window-basic-transform.cpp
- libobs/obs-scene.c
- libobs/obs.h
Fix ABI break in `obs_sceneitem_get_info` and `obs_sceneitem_set_info`
Fixes #10261
On windows 11 with Aitum Vertical 1.4.0
> libobs: Fix crop to bounds ABI break

- .github/workflows/build-project.yaml
- .github/workflows/publish.yaml
Switch to flathub-infra action, which contains a fix for a flatpak-builder appstream regression; and update screenshot mirrot URL to match what Flathub uses now.
This fixes CI, and allows for publishing to Flathub properly once again.
- Run CI, see that it passes
> Switch to flathub-infra action, update screenshot mirrot URL

- UI/window-remux.cpp
The beginInsertRows/endInsertRows calls seem to signal that the rowCount has changed, and that views should adjust accordingly. The isProcessing boolean changes the returned value of RemuxQueueModel::rowCount, which seems to cause the empty row in the table model to disappear permanently. I still don't know why it used to work this way and no longer does.
Fixes #9878
I haven't done any Qt bisects yet between 6.5.2 and 6.5.3 to figure out exactly what commit changed this behavior, but these are my current guesses:
* https://github.com/qt/qtbase/commit/25f92391a48b6acb41e44eab7bdcd0086f46d427
* https://github.com/qt/qtbase/commit/703b48a7c01223e9163ded1fddc9940bdc5028a6
I still don't know if this change is correct, and would appreciate reviews.
- Bug fix …
> UI: Fix Remux window only being usable once

- .github/workflows/scheduled.yaml
Fix warnings in scheduled nightly workflow runs when master branch has not been updated between runs.
When a prior scheduled nightly run is detected with the identical commit hash, then the entire language file check should be skipped.
This adds the missing condition to skip the check for changed files removing the unnecessary warning contained in the workflow results.
Needs to be checked on CI.
> CI: Fix scheduled language file check running on same commit hash

- .github/actions/compatibility-validator/action.yaml
- .github/actions/services-validator/action.yaml
Change validator actions to use a virtual environment to install PIP modules required for validator scripts.
Python 3.11 and later support a system-wide configuration setting that marks the system packages as "externally managed" (e.g. to force using apt packages instead of pip packages).
This breaks installation of the modules necessary to run the validators, so use a virtual environment instead.
> CI: Fix broken pip install to use ephemeral virtual environment

- UI/window-basic-settings-stream.cpp
- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
This does two things:
1. This removes the LoadOutputSettings() called in SaveStream1Settings. It caused a bug when trying to save Output settings when both Stream and Output settings have been changed but the changes have not been applied by hitting the 'Apply' button in Settings.
Credits: Rodney made the correct guess for the faulty line.
2. This fixes the display of audio multi-tracks which must alternate between radio buttons (single track protocols) to checkboxes
(mpegts). The LoadOutputSettings call was used to do that update but it was too broad. Instead we use (a) the signal when a service is changed to switch back from mpegts multi-track to single track; (b) the signal when a URL is input in the Server text field of Custom service; (c) when Stream settings are saved.
Fixes a bug …
> UI: Fix a bug with Output Settings not updating & Toggle audio multi-tracks correctly

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Adding "Vault - by CommanderRoot" to OBS-Studio's ingest list
My Vault is a backup service but also allows the forwarding / re-streaming to other services. Adding it as a direct option in OBS Studio makes it easier for my users to setup ingesting into my service. Since Twitch removed the restriction on simulcasting there has been an increased interest in streaming to multiple streaming services at the same time.
> rtmp-services: Add "Vault - by CommanderRoot" to ingest list

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
The Switchboard Live Server URLs have been recently updated in the application, so the URLs need to be updated in OBS to match.
There were recent changes to the ingestion servers at Switchboard Live. We also removed Legacy url.
- This was tested using the latest build of OBS on Windows.
- Testing consisted of going live with every server to ensure connectivity was stable.
- Tweak (non-breaking change to improve existing functionality). 
- Removed Alt names
> rtmp-services: Update Switchboard Live servers

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Add [CHZZK](https://studio.chzzk.naver.com) to rtmp services list.
A live streaming platform from [NAVER](https://www.navercorp.com/) in South Korea.
Add support for "CHZZK" in rtmp services.
> rtmp-services: Add "CHZZK" platform

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Adding Streamway to OBS-Studio's Ingest List
Streamway (https://streamway.in) is a re-streaming and CDN provider, that allows users to livestream on multiple social media platforms like YouTube, Facebook, LinkedIn, Twitch, Twitter and many more at same time, so broadcasters can get more views and maximise their autocancel.  Streamway also acts as a live CDN to allow Broadcasters to publish livestream directly on their custom Mobile app or websites. Streamway is wildly used in India with more than 3 years of availability.
By adding this website to the ingest list, OBS-Studio users will be able to easily and conveniently use Streamway as a source for their live streams and content.
> rtmp-services: Add Streamway to ingest list

- plugins/obs-webrtc/whip-output.cpp
PeerConnection::setRemoteDescription validates the input SDP, throwing an exception whenever it is invalid.
Currently, instead of handling the exception, we just crash.
Instead, add an exception handler which logs a short description of the issue as well as the error message from the exception.
I develop an open-source WebRTC app, and one of the most confusing parts during development was when OBS would crash when my (not production-ready) server would give an invalid SDP answer. Fix that in this PR.
Simply respond with any invalid SDP on the WHIP endpoint - e.g. the string "hello".
```
info: --------------------------------- …
```
> obs-webrtc: Avoid crashing on invalid answer

- plugins/mac-avcapture/plugin-properties.m
Add check for possible NULL value returned for colour primaries of a capture device' image format.
BGRA or other formats that do not use color primaries will not yield a valid color primary value. Initializing the CFComparisonResult to a default value and replacing it only if a non-NULL color primary value was retrieved avoids a possible crash.
Tested with OBS Virtual Camera which has a BGRA output format, which has no colour primary information attached to it.
> mac-avcapture: Fix possible crash if camera uses BGRA format

- UI/frontend-plugins/frontend-tools/output-timer.cpp
- UI/frontend-plugins/frontend-tools/output-timer.hpp
If the "Pause timer when recording is paused" option in the Output Timer settings was enabled, even if an Output Timer was not being used, a recording may stop when attempting to unpause it. This was due to the check in the UnpauseRecordingTimer function being too loose and only checking for if the recording timer was not active. Let's initialize the recordingTimeLeft variable to -1 and check that it's greater than 0 before attempting to restart a recording timer.
Fix a bug that appeared at least as early as OBS Studio 30.1.0-beta1. Do not want recordings stopping unexpectedly or prematurely.
When uninitialized, recordingTimeLeft could be something like -842150451. A negative value passed to QTimer's `start` function results in this:
```
13:12:39.929: QObject::startTimer: Timers cannot …
```
> frontend-tools: Fix output timer stopping recording on unpause

- UI/win-dll-blocklist.c
The Elgato Stream Deck plugin older than 5.5.2.0 invokes undefined behavior that results in application crashes. Let's block older versions to prevent the crashes.
Requested by @notr1ch . Want less crashes.
I've built this locally on Windows 11, but I have not tested this, nor am I sure how I would test it.
> UI: Block Elgato Stream Deck plugin before 5.5.2.0 to avoid crashes

- plugins/obs-webrtc/data/locale/en-US.ini
- plugins/obs-webrtc/whip-output.cpp
Adding to the previous commit, let's also use obs_output_set_last_error to provide localized error messages to the user if we run into these failure cases.
Suggested by @notr1ch .
Tested the build locally on Windows 11. Have not tested the actual error conditions.
> obs-webrtc: Add additional error messaging for WHIP output

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Updating list of ingest servers for Vaughn Live and Breakers. Also removed recommended settings. I'm not familar with github as I do not use any git stuff, so when I was told in PR #8174 to "force push," I have zero idea what that means or how to go about it. But I do know how to make a pull request. I apologize if this is done incorrectly, however. 
Old ingest servers were listed and new ones were missing. 
Json file in OBS 
- Tweak (non-breaking change to improve existing functionality) 
- [ x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x ] The code has been tested.
> rtmp-services: Update Vaughn Live and Breakers ingests

- .github/actions/sparkle-appcast/action.yaml
Instead of pushing the Sparkle update to all macOS users at once, use Sparkle's "phased group rollouts" ("phased rollout interval") feature to split the notifications up into 7 groups separated by 1 day intervals. This potentially allows us to catch critical issues before all macOS users get the update notification.
We had a critical issue with OBS Studio 30.0.1 that we had to hotfix that day with OBS Studio 30.0.2. At the time, we considered the possibility of if we could have a more gradual rollout of macOS updates. This is possible with Sparkle's phased group rollouts.
https://sparkle-project.org/documentation/publishing/#phased-group-rollouts
It's possible that we conclude that this isn't worth the added complexity, but I wanted to get the code changes done so that we didn't have to …
> CI: Use phased group rollouts for Sparkle stable channel updates

- .github/actions/run-clang-format/action.yaml
- .github/actions/run-cmake-format/action.yaml
- .github/actions/run-swift-format/action.yaml
- build-aux/.run-format.zsh
Changes CI formatting actions (and associated formatting script) to accept a list of files.
Before the CI checks for source code and CMake files would always check the entire source code even if just a single files has been changed.
With this update, the formatting script is enhanced to accept a list of files (which is generated as a condition to run the script in the first place) which ensures that a PR will only fail validation over files it changed itself.
Tested the script locally with no list of files provided and different number of specified file paths.
> CI: Limit format checks to changed files only

- plugins/win-capture/game-capture.c
Fixes linked audio capture source not re-capturing a window after the game capture source is unhooked.
When the change in #10259 was made I forgot to also update the hook counterpart.
Fixes #10319 
Closed and restarted a game.
> win-capture: Always reconfigure audio source when game capture hooks

- libobs/cmake/os-windows.cmake
Adds w32-pthreads to CMake project if target is not available already when `libobs` is being configured.
w32-pthreads is not correctly added to the generated CMake project if the UI subdirectory is not also included, which leads to builds configured without UI to fail.
Fixes #10347.
Tested on Windows 11 using `cmake --preset windows-x64 --fresh -DENABLE_UI=OFF`.
> libobs: Fix missing w32-pthreads dependency when building without UI

- UI/window-basic-main.cpp
Sets default output format to fragmented MP4 on Linux/Windows and fragmented MOV on macOS (for ProRes support).
Originally, this change was limited to pre-release builds to gather feedback (#8516), since no complaints have really shown up since last year it's probably time to make it the default in release builds to finalise the implementation of https://github.com/obsproject/rfcs/pull/51.
N/A
> UI: Change default format for release builds to fMP4/fMOV

- plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
The newer FFmpeg API requires us to set the mastering display and content light level metadata on the codec parameters rather than the stream, as those get overwritten/reset by `avcodec_parameters_from_context()` we need to move things around so they are added *after* the codec parameters are initialised.
This mainly affects NVENC HEVC/AV1 and the software AV1 encoders, as those do not seem to add this data to the bitstream on their own (AMF/QSV do).
Fixes issue introduced in #9935
Fixes #10363
Recorded some HDR video, confirmed everything is correct.
> obs-ffmpeg: Fix HDR metadata not being written when using FFmpeg 6.1+

- plugins/mac-capture/mac-sck-video-capture.m
Makes consistent the early return behavior when creating a macOS Screen Capture, such that if the user is creating a capture with an invalid/stale window or display, we abandon initialization properly in all three capture modes.
Per https://github.com/obsproject/obs-studio/issues/10377 as well as lingering reports about stale capture indicators, ScreenCaptureKit still does not behave well if we try to initialize streams with bad parameters, which can cause side effects for other applications relying on replayd. Additionally, the way we are currently early returning from a bad Display Capture, we seem to invalidate the source (making it unmodifiable) for the remainder of that OBS session, which is not desirable.
On 14.4, before these changes, my testing showed that:
1. If initializing a …
> mac-capture: Standardize early return behavior in init_screen_stream()

- plugins/win-capture/get-graphics-offsets/cmake/32bit-build.cmake
- plugins/win-capture/graphics-hook/cmake/32bit-build.cmake
- plugins/win-capture/inject-helper/cmake/32bit-build.cmake
- plugins/win-dshow/virtualcam-module/CMakeLists.txt
- plugins/win-dshow/virtualcam-module/cmake/32bit-build.cmake
Adds the missing explicit MSVC runtime selection to the the 32-bit `win-capture` target and also moves the same selection out of the shared virtual cam interface library to the actual architecture-specific targets.
The `MSVC_RUNTIME_LIBRARY` target property when set on an `INTERFACE` type library is not inherited by targets which consume the library, thus their property is set automatically set by CMake.
This affected the virtual camera target which uses an `INTERFACE` library for sources and settings shared between its 64-bit and 32-bit variants.
The PR sets the property directly on the "final" output targets to fix this.
Needs to be tested on an Intel-based Windows installation.
> cmake: Fix MSVC runtime selection for win-dshow and win-capture targets

- UI/window-basic-status-bar.cpp
This reserves the size of the congestion vector in the status bar, so it isn't resized every second.
Performance improvement, nothing noticeable but an improvement nonetheless
Testing by streaming and checking if the congestion indicator still worked as expected
> UI: Reserve size of congestion vector

- UI/window-basic-status-bar.cpp
- UI/window-basic-status-bar.hpp
The stream output signals are now put inside of a vector.
Less code
Disconnected and reconnected stream
> UI: Use signal vector for status bar

- deps/media-playback/media-playback/decode.c
Fixes #10369.
Since the update to FFmpeg 6.1, streams to a Media Source are broken if hardware decoding is enabled (both RTMP or SRT have been reported). The video is black although the audio is decoded fine. The manual copy of metadata introduced in commit [1] does not work any more for some unfathomable reasons.
As a fix we call instead the av_frame_copy_props function used in FFmpeg app in a similar context (hardware decoding) [2].
The metadata are copied without issues.
There is no need to guard the use of that function since it was introduced 9 years ago in avutil/frame.c.
[1] https://github.com/obsproject/obs-studio/commit/22fde5cdcd1c784cd60b8a8cd50af02e7e537182
[2] https://github.com/FFmpeg/FFmpeg/master/fftools/ffmpeg_dec.c
NB: on FFmpeg master as of today (3/15/24), the relevant …
> deps/media-playback: Fix hardware decoding of streams

- UI/platform-x11.cpp
Unlike filesystem addresses, which are paths, abstract addresses are blobs.
This means that the address wasn't "\0/com/obsproject 2413747 version", but rather "\0/com/obsproject 2402613 version\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"; this is reflected in both /proc/net/unix:
```
000000001bf56057: 00000002 00000000 00000000 0002 01 56719817 @/com/obsproject 2402613 version@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
000000003e897b41: 00000002 00000000 00000000 0002 01 56730132 @/com/obsproject 2413747 version
```
and ss -l:
extending the whole address column to the point of unusability.
This size calculation follows trivially from the manual, and …
> UI: Size the abstract-socket address properly

- libobs/media-io/media-remux.c
Set the channel layout when remuxing.
Fixes muxing PCM in MP4 failing.
Fixes #10384
Remuxed file that previously failed.
> libobs: Set channel layout for remux output

- plugins/mac-capture/mac-audio.c
Fixes reading on invalid memory location.
Without this change the call to `bstrdup_n` gives in the string length with zero termination character. However, `bstrdup_n` will handle zero termination by itself and will do a `memcpy` on the given `size + 1`.
This will lead to double-zero terminated strings which get allocated with one byte more than necessary (doh!).
But it will also read from invalid/wrong memory when `memcpy`-ing in case the original string capacity is exactly the size of the string (including zero termination).
E.g.
```C
bstrdup_n("Test", 4 + 1);
-> bmemdup(str, 5 + 1);
-> bmalloc(6);
memcpy(out, ptr, 6); // causing read of 6 of bytes while string buffer is only 5 ("Test\0")
```
Fixing a report from Apple's address sanitizer:
``` …
```
> mac-capture: Fix string length when duplicated

- deps/media-playback/media-playback/decode.c
When playing back videos with the media source and using hardware decoding, we do not properly handle video resolution changes. If the resolution grows, a compositing-like effect happens where video data is written to only a portion of the space. If the resolution shrinks, it writes out of memory bounds and undefined behavior occurs.
This happens because we rely on `av_hwframe_transfer_data()` to initialize the `d->sw_frame` buffer and width/height parameters, however that function only does the initialization if the destination buffer is unallocated, it does not check for *differences*. As such, this adds logic to detect resolution changes and free the current sw_frame buffer in order to trigger allocation of the correct buffer size.
This is somewhat related to #5010, but fixes this lack …
> deps/media-playback: Detect and handle video res changes when using hardware decoding

- plugins/obs-qsv11/obs-qsv11-plugin-main.c
On linux we enumerate all VA-API devices, which incorrectly enables QSV AV1/HEVC encoders when an AMD devices reports these capabilities.
AMD users shouldnt see QSV encoders.
Incorrectly displayed devices on pure amd machine are hidden. When adding an intel device the encoders are presented again.
This shouldnt affect windows as the enumeration skips non-intel devices.
> obs-qsv11: Check all encoders are Intel devices

- UI/properties-view.cpp
- UI/properties-view.hpp
- UI/window-basic-settings.cpp
Prevents double scrollbars in advanced output encoder properties by forcing the scroll area to always be full height.
See above.
> UI: Prevent double scrollbars for encoder properties

- .github/workflows/scheduled.yaml
Removes condition from changed file check for nightly language file upload to fix JSON parsing error.
The upload step in the job uses the output of two prior steps as its condition. One of the jobs itself is a conditional job, so if the primary condition is not met, the secondary output is not set and the fromJSON call will fail.
Making the check for changed files unconditional ensures that both outputs provide a value that can be used with fromJSON and no syntax error occurs.
Language uploads still only happen if the commit hash of the nightly run has actually changed and any language files are actually changed.
Requires nightly run to test.
> CI: Fix JSON runtime error for language file uploads

- plugins/obs-ffmpeg/obs-nvenc.c
This fixes NVENC for NVIDIA devices stuck on pre-531.61 drivers, such as Kepler devices which can only update to 474.82. We didn't intentionally break this, so we should fix it until we remove the compatibility hacks that we currently use.
For the record we _will_ be officially dropping Kepler at some point, which we will attempt to communicate in advance.
Fix an unintentional breakage.
Fixes #10431
I tested this on a GTX 1060 with driver 512.15 to simulate the scenario of being on an SDK 11.1 driver (on Windows, 471.41 or newer but older than 522.25; on Linux, 470.57.02 and newer but older than 520.56.06). Will seek additional testing on actual Kepler hardware.
> obs-ffmpeg: Fix NVENC API compatibility with old drivers/hardware

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Adding Hakuna Live's RTMP Ingest server address
Hakuna Live is one of the global live streaming service platforms.
To make it easier for streamers to access Hakuna Live, add this address.
I followed [service submission guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines) and confirmed streaming's working.
> rtmp-services: Add Hakuna Live RTMP service

- UI/window-basic-auto-config.cpp
The issue reported on GitHub involves the OBS Studio Auto-Configuration Wizard becoming non-functional when a custom server is selected without requiring a stream key, preventing further progress. To address this, I included the !custom constraint in the if condition within the UpdateCompleted() function, aiming to handle cases where a custom server is used without a stream key, thereby allowing the wizard to proceed as expected.
This change improves the user experience in OBS Studio, especially for those utilizing custom streaming services. It solves the problem outlined in this issue: [obsproject/obs-studio#10087](https://github.com/obsproject/obs-studio/issues/10087), where the setup wizard would inaccurately report readiness due to not considering custom services without a provided …
> UI: Fix Auto-Config Wizard for custom server with no stream key

- UI/window-basic-main.cpp
Tab key press event was triggering default Qt behavior and selecting next item in scene list before rename event could complete. This caused the incorrect scene to become the target of the rename method. Consumed the tab key event and observed that tab now completes the edit and leaves the current scene selected. This is in alignment with how tabbing away from a rename affects renaming of sources.
Fixes #10090
Built and ran locally on Windows 11 machine before code change, observed incorrect behavior tabbing from rename. Modified code, observed tabbing from rename completes edit as expected.
> UI: Fix scene rename on tab

- plugins/obs-outputs/rtmp-av1.c
Adds parsing of AV1 frame type to AV1 OBU parsing to set drop priority of keyframes correctly.
Somewhat janky but matches what we did in 722ca8447e3be1ad4cd10ba1e8c8dd41e341a20f and should be good enough™ for our use case.
Should fix #10383
Verified priority now gets set.
> obs-outputs: Fix AV1 packet priority in RTMP

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
The Custom FFmpeg Output allows the user to configure it to output to a URL instead of a file. In OBSBasic::StartRecording(), we unconditionally call LowDiskSpace() to check for low disk space because we assume that a "recording" will always be to disk. When os_get_free_disk_space() is called on a non-existent path, it returns 0, which causes OBS to emit a low disk space warning. Instead, only call DiskSpaceMessage() if not "recording" to a URL.
Fixes #10443
Tested locally on Windows 11. Would appreciate extra review/testing to make sure I didn't miss something or introduce a regression.
> UI: Check low disk space only if recording to a file

- UI/window-basic-main-outputs.cpp
- UI/window-basic-main.cpp
- UI/window-basic-vcam.hpp
- plugins/linux-v4l2/linux-v4l2.c
- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
- plugins/win-dshow/dshow-plugin.cpp
Move the whole virtual camera enablement logic in the UI by checking if a the right output id is registered.
Split from #5383, the refactor is not dependent the dual vcam feature.
PipeWire virtual camera is blocked until portals provides a solution.
I just thought that this portion of code can be reviewed separately without waiting that I finally finish my work on portals.
Lightly tested on Linux.
> UI,plugin: Refactor virtual camera enablement

- .github/scripts/.build.zsh
- cmake/Modules/FindFFnvcodec.cmake
- cmake/finders/FindFFnvcodec.cmake
- plugins/obs-ffmpeg/cmake/dependencies.cmake
- plugins/obs-ffmpeg/cmake/legacy.cmake
- plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
- plugins/obs-ffmpeg/obs-ffmpeg.c
- plugins/obs-ffmpeg/obs-nvenc-helpers.c
- plugins/obs-ffmpeg/obs-nvenc.c
- plugins/obs-ffmpeg/obs-nvenc.h
Replaces the FFmpeg fallback in the "new" NVENC encoder with a native non-texture encoder.
Also adds support for the non-texture encoder on Linux.
Superseedes/Closes #8794 
The FFmpeg fallback sucks I hate it.
Tested H.264 encoder on my 4090 with the latest driver on Windows and Linux. 
> obs-ffmpeg: Add native non-texture NVENC encoder

- .github/actions/check-changes/action.yaml
- .github/actions/run-clang-format/action.yaml
- .github/actions/run-cmake-format/action.yaml
- .github/actions/run-swift-format/action.yaml
Update code formatting actions to use the `check-changes` action as a trigger for whether or not format checks should actually run and updates that action to pass custom `diff-filter` arguments for `git diff`.
Using git's diff-filter when checking for changed files allows the actions to ignore any deleted files. Combined with explicitly passing glob expressions for source files to git directly allows the command to yield a list of changed files compatible with a given formatter directly.
By updating only the `check-changes` action, the code-formatting actions are able to use that actions as well, reducing code duplication.
Requires CI runs for testing.
> CI: Update formatting actions to use git diff filter before formatting 

- UI/forms/OBSPermissions.ui
The macOS Permissions dialog was using empty widgets to force other widgets into position. Instead, use horizontal spacers.
Noticed when reviewing #10419 that this dialog used blank widgets to help position other elements. Seemed odd. This change should supersede the specific `native="true"` changes to the empty widgets in this file so that that and the duplicate/identical item names are no longer an issue blocking that PR.
Note that I used Qt Creator 12 on Windows 11 to make these changes to the .ui file. Some of the changes made in #10419 do not appear to have been made by Qt Creator 12 when I saved this (notably, the orientation enum namespace), so this file will still need processed again.
Compiled and checked the dialog on macOS 13.6.6. The dialog looked the same before and after.
- …
> UI: Use spacers instead of widgets in macOS Permissions UI

- cmake/Modules/VersionConfig.cmake
- cmake/common/versionconfig.cmake
when git describe fails to get a git tag for the OBS Version, a non-fatal message is printed, and the generator is left to continue, usually ending up with a more cryptic error message down the line, such as in #7705.
Instead, dump the git output together with a short description of what actually happened, and exit fatally so the problematic line of code is clear. An added advantage is that the git output is printed in red instead of (say) white on colour-enabled terminals.
Gives developers a more clear error for debugging issues like #7705.
Tested with CMake 3.25 on Debian 12.
Examples:
```
$ cmake -S . -B YOUR_BUILD_DIRECTORY -G Ninja  -DCEF_ROOT_DIR="../obs-deps/cef_binary_5060_linux_x86_64"       -DENABLE_PIPEWIRE=OFF        -DENABLE_AJA=0         -DENABLE_WEBRTC=1 …
```
> cmake: Provide a clear error on version check fail

- plugins/linux-v4l2/v4l2-decoder.c
- plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
Fix errors introduced by building OBS Studio with FFmpeg 7.
FFmpeg 7 is out, and Arch Linux will not wait for us…
And since the errors looked easy to fix, so I made the PR.
Not tested, I'll maybe try to on my side (at least the v4l2 path)…
> Fix compiling with FFmpeg 7

- plugins/obs-qsv11/QSV_Encoder.cpp
- plugins/obs-qsv11/QSV_Encoder.h
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/QSV_Encoder_Internal.h
- plugins/obs-qsv11/common_utils.cpp
- plugins/obs-qsv11/common_utils.h
- plugins/obs-qsv11/common_utils_windows.cpp
- plugins/obs-qsv11/obs-qsv11.c
Fixing a bug where OBS is selected to run on a GPU that does not support AV1 encoding, while there is an Intel dGPU in the same system. Instead of throwing an error, due to the other GPU being unable to encode AV1, the system will fall back to the dGPU that can run AV1 encoding.
Fixing this issue: https://github.com/obsproject/obs-studio/issues/9982 
Tested on CLEVO laptop with Intel iGPU and dGPU while OBS is selected to run on the iGPU.
- [x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/C …
> obs-qsv11: Fix for QSV AV1 in multi-GPU system

- UI/forms/OBSBasicSettings.ui
- UI/window-basic-settings.cpp
Add a new QVBoxLayout to OBSBasicSettings.ui to show the warnings in the output advanced recording settings.
**Old layout for warnings in advanced recording settings:**
**New layout for warnings in advanced recording settings:**
This PR fixes isssue #9276
It also improves the UI so the warnings shown in the advanced Output Recording Settings are consistent with the ones shown in the simple Output tab.
**Simple Output settings (old and new):**
Tests are conducted by manually entering MPEG-4 (.mp4) in the recording format and resizing the settings window.
**Environment:**
- windows 11 Version 10.0.22631 Build 22631
> UI: Move warnings to bottom of settings window

- UI/window-basic-main.cpp
This logs all available audio and video encoders when launching
It can often be challenging for support volunteers to remember which encoders are available on which hardware, especially with AMD.
This would greatly simplify the flow of some support interactions.
Ran obs, checked that available encoders were correctly listed and no memory leak happened.
> UI: Log available encoders on load

- UI/window-basic-main.cpp
> [!TIP]
> This summary has been updated to match the most recent code change
Change size policy of "Start Virtual Camera" button to ensure the minimum width of "Controls" panel is greater than or equal to the minimum width of "Start Virtual Camera" button plus the gear (settings) icon. Text cutoff is thus eliminated.
Old minimum width of "Controls" panel:
New minimum width of "Controls" panel:
This PR fixes #10210.
Tests are conducted by manually resizing "Controls" panel.
Solution works for both LTR and RTL languages.
Environment:  
- macOS Ventura 13.6.4 (22G513)
Arch: x86_64
- Xcode 15.2
Build version 15C500b
> UI: Fix `Start Virtual Camera` Text Cut Off in Corresponding Button

- plugins/obs-ffmpeg/obs-ffmpeg-source.c
Removes the hardcoded format override for the media source
Fixes #9388
FFmpeg is already very effective at detecting the correct input format for socket-style protocols (SRT, RIST, TCP, UDP etc). By overriding the format of SRT and RIST manually to mpegts, the user is being prevented from using other container formats via these protocols.
In the rare case that libavformat is unable to detect the correct container format for an SRT or RIST stream, the user may manually specify that format in the existing format field.
With the FFmpeg options field which was recently added, probe options may be specified by the user to further tune format detection.
Wasn't able to test due to not updating my Ubuntu 20.04 machine to 22 yet, but the change is dead simple.
- Tweak (non-breaking change to …
> obs-ffmpeg: Remove media source mpegts format override for SRT and RIST

- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs-video-gpu-encode.c
- libobs/obs-video.c
- libobs/obs.c
- libobs/obs.h
This is meant to allow grouping encoders for e.g. eRTMP multitrack video (<=> Twitch Enhanced Broadcasting) such that IDR frames are aligned for seamless rendition switching when transmuxing the overall output stream into e.g. HLS or similar multi rendition formats
Without this change, encoders aren't guaranteed to start on the same frame even if started "at the same time" due to encoder startup not being synchronized with the video thread; e.g. in practice we've observed a one frame offset that sometimes happens between encoders, though the offset can be arbitrarily high potentially due to lack of synchronization
With this there's explicit synchronization, so all encoders start on the same frame (and get the "same stream" of frames fed to them)
This code has been deployed in the Twitch …
> libobs: Add keyframe aligned encoder groups

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Changes scene collection module data to be always retained, even if not in safe mode.
Many plugins store their data using the frontend API's "save"/"load" callback, which allows them to store their configuration data directly in the scene collection. This makes sense for a lot of plugins that interact with the scenes and source themselves, and thus have collection-dependant data.
One downside of this mechanism is that if a plugin isn't loaded the data will be lost on saving. In safe mode this already is handled by keeping a copy of the previous module data and restoring it, but in regular mode this was not the case.
Added plugin data, removed plugin, data still there.
> UI: Always retain collection data of unloaded modules

- UI/window-basic-properties.cpp
- Fixes #10333
- Supersedes #10446
`QDialog::closeEvent()` already calls the `reject()` function, the override of the former function was actually allowing a first confirmation dialog which once discarded gets re-openned by `QDialog::closeEvent()`.
Removing most of the closeEvent() override code is enough to fix the issue since reject() will be called showing the confirmation dialog.
Fix a bug
I happen to be able to reproduce the bug with some of my sources, once the fix applied none of them add double dialog.
And the properties dialog behaves as before but without the bug.
> UI: Fix double confirmation dialog while discarding source change

- plugins/obs-ffmpeg/texture-amf.cpp
The frame rate used to initialize an AMF encoder should be aligned with the derived frame rate in video_output_info instead of the global obs_video_info structure. With this change, IDRs can be aligned when multiple renditions are being encoded.
Using video_output_info members for the format, colorspace, and range parameters in addition to the frame rate provides a single source for this information and obs_video_info is no longer needed.
IDR frames across segments in multi-track encoding (or eRTMP) must be aligned to allow clean switching in the decoder from one rendition to another. This commit uses the correct frame rate from the video_output_info struct for each encoder, which could be different than the composition frame rate, which allows proper IDR alignment across segments.
The …
> obs-ffmpeg: Use video_output_info in amf_create_encoder()

- plugins/coreaudio-encoder/encoder.cpp
- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
- plugins/obs-libfdk/obs-libfdk.c
Not strictly necessary, and does not fix any bug. This just corrects a nitpick that technically audio encoder packets are start points, but that they aren't being labeled accordingly as keyframes.
It would be nice to portray accurate metadata in encoder packets, even if things work regardless of what is set. The documentation does not specify this flag as being relevant only to video, so it might as well be "implemented."
Started up OBS and tested some streams and observed no difference in behavior.
> plugins: Set keyframe flag on encoded audio packets

- plugins/mac-avcapture/OBSAVCapture.m
Add a null pointer check for the source pointer in the source info struct before using it to output an empty `NULL` frame for a possibly stopped capture device.
When a capture card or video capture source is contained in the scene collection's list of sources, but the source is not a part of any scene, it will be first created but then destroyed again in a deferred fashion (as it has no strong references to it anymore).
This will happen before the capture source has finished its own initialization, hence why the source pointer can be invalid at that point.
* Tested on macOS 14 with a bespoke scene collection to trigger the issue.
> mac-avcapture: Add pointer check for outputting NULL video frames

- plugins/linux-pipewire/camera-portal.c
- plugins/linux-pipewire/pipewire.c
Deletes some unused variables.
These break builds eventually, not sure why they don't right now.
It builds.
- Code cleanup (non-breaking change which makes code smaller or more readable) -->
> linux-pipewire: Remove unused variables

- plugins/obs-outputs/flv-mux.c
This is supposed to make the FLV output emit more compliant FLV files
To prepare eRTMP support there's an upcoming PR that adds "eRTMP" (eFLV?) support to the FLV file output; having eFLV support is generally useful so testing doesn't have to involve RTMP/an actual server, and various tools used at Twitch complained about malformed FLVs (both the off-by-one tag size and the broken header/metadata after FLV files have been finalized)
Verified functionality with https://github.com/kc5nra/ertmp-toolbox and various internal tools
> obs-outputs: Fix FLV muxer tag size logic and file info offset

- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
Reduce the size of the settings window if greater than the current display's available geometry.
Fixes #5168
This change should avoid this to happen again on 720p:
[![Example](https://cdn.discordapp.com/attachments/376042662580715521/1015514364515729418/unknown.png)]()
OK, Cancel and Apply are not accessible without having to resize the window.
- Set manually the main window size at something 720p-like.
- Open the settings window.
- The settings window is smaller in height than the main window.
> UI: Reduce settings dialog default height

- build-aux/com.obsproject.Studio.json
- plugins/obs-ffmpeg/obs-nvenc.c
- Fix unused variable in NVENC native to enable the next point
- Make Flatpak use CMake build framework 3.0
- Also change CMake build type to RelWithDebInfo which is the preferred build type in Freedesktop SDK environments, dependencies will not be touched in this PR.
Move things forward to deprecate CMake 2.0 and battletest CMake 3.0.
Local build
> Make Flatpak use CMake build framework 3.0

- UI/platform-x11.cpp
- libobs/obs-nix.c
Fixes Linux builds using the legacy `LINUX_PORTABLE` flag.
The updated Linux build system uses the same directory structure for both fixed and relocatable builds (so all files are in the same locations relative to the main binary, libraries, or modules).
The legacy portable build variant used a different directory structure, so the existing guards and checks would not work anymore.
Tested on Ubuntu 23.10:
* Built and ran OBS Studio with legacy build system and `LINUX_PORTABLE` disabled
* Used `LD_LIBRARY_PATH` to enable running from custom install location
* Built and ran OBS Studio with legacy build system and `LINUX_PORTABLE` enabled
* Built and ran OBS Studio with updated build system and `ENABLE_RELOCATABLE` disabled
* Used `LD_LIBRARY_PATH` to enable running from custom install …
> Fix relocatable Linux builds using legacy portable build flag

- UI/adv-audio-control.cpp
- UI/adv-audio-control.hpp
- UI/window-basic-adv-audio.cpp
- UI/window-basic-adv-audio.hpp
This changes the active/inactive status in the advanced audio properties dialog to be based on the audio_active status of the source instead of its active status.
With the addition of audio capture to game and window capture in 30.1, those sources would appear in the advanced audio properties regardless of whether said audio capture was enabled or not. This can quickly clutter the dialog with sources who aren't actually capturing any audio. This change will hide those by default, by marking them as inactive if the audio capture is not enabled, while still allowing them to be shown by ticking "Show inactive".
Tried every case of making sources active/inactive, verified that all was showing correctly.
> UI: Change advanced audio controls to use audio_active

- CMakeLists.txt
We now support the new, modern CMake path on all platforms. Encourage everyone to migrate by deprecating the legacy CMake path. The legacy CMake path will be removed in a future update.
Want to give notice that the legacy CMake is deprecated.
Tested locally on Windows 11 to check that the deprecation warning was clearly displayed in the CMake log output.
> cmake: Deprecate legacy CMake for all platforms

- plugins/obs-webrtc/whip-output.cpp
- plugins/obs-webrtc/whip-output.h
- plugins/obs-webrtc/whip-service.cpp
**Description**
This adds HEVC support to obs-webrtc
**Motivation and Context**
Users wish to use HEVC
**How Has This Been Tested?**
Tested against Dolby Millicast service and Safari tech preview
**Types of changes**
**Checklist:**
-   [x] My code is not on the master branch.
-   [x] The code has been tested.
-   [x] All commit messages are properly formatted and commits squashed where appropriate.
-   [x] I have included updates to all appropriate documentation.
> obs-webrtc: Add HEVC support

- UI/volume-control.cpp
These comments do not actually match the color values here:
* (0xff, 0xff, 0xff) is white
* (0xcc, 0xcc, 0xcc) is light gray
Instead of just fixing the comments, use the values from the System theme and also correct the comments.
I was testing something the other day involving removing most of our QSS and couldn't figure out why the volume meter text colors were white instead of black as the comments said. Eventually realized that the colors did not match the comments. Asked @Warchamp7 if we should fix the comment, the colors, or both. Arrived at this.
https://github.com/obsproject/obs-studio/blob/8a7ad1026212e103c3c8b2dc0a0afcc907f83f89/UI/data/themes/System.qss#L113-L115
0x32 = 50
- Code …
> UI: Use System theme volume meter colors for default values

- libobs/graphics/device-exports.h
nv12 and p010 device functions were not exported on all platforms.    
Windows was exporting from C files instead. After CMake 3.0 we started     
hiding symbols and resolution failed. 
This resulted in obs crashing since fallback encoders were not used.
Fixes texture encoders on opengl
Launched a texture encoder.
> libobs: Export NV12/P010 functions

- libobs/obs-internal.h
- libobs/obs-source.c
Remove `last_audio_ts` in `struct obs_source`.
The variable `last_audio_ts` was set but was never read.
OS: Fedora 38
Confirmed the build succeeded.
Also checked `git grep '\<last_audio_ts\>' libobs`.
> libobs: Remove unused variable in obs_source

- plugins/text-freetype2/text-functionality.c
We had these advances laying around but didnt use them here. Loading the glyphs from the fonts is extremely slow, so lets avoid that since we take the time to cache these already.
Makes this function ~4000x times faster. Everyone loves fast.
It didnt crash, but also this is used in the other width computation so it should be fine.
> text-freetype2: Use cached glyph advances

- UI/api-interface.cpp
Setting the dock floating before hiding it created a transparent window on X11.
On X11 (Fedora 38, XFCE4), an undrawn window was created at the top-left corner of the screen by this API if the dock added by this API is hidden at the beginning.
The window mostly held the background image like the screenshot below.
The `statsDock` has the order `setVisible(false)` then `setFloating(true)`, which causes no issue so far.
https://github.com/obsproject/obs-studio/blob/83383c13bc5657fb7ef071d6e250a66d66cdcc95/UI/window-basic-main.cpp#L9621-L9622
The implementation of `QDockWidget::setFloating` has a branch condition involving `isVisible()` so I suspected the order mattered.
https://github.com/qt/qtbase/blob/a78938e0f686263540e06d923f2949169f3219e4/src/widgets/widgets/qdockwidget.cpp#L1448-L1468 …
> UI: Set dock floating after hiding it

- libobs/obs-encoder.c
Fix grouped encoder disconnect/reconnect behavior; this was included in all public Enhanced Broadcasting builds (original commits was <https://github.com/amazon-contributing/upstreaming-to-obs-studio/commit/340c205ce28adad2de103fa99276b9182ce28c38>), but missed in <https://github.com/obsproject/obs-studio/pull/10349>
Follow-up to <https://github.com/obsproject/obs-studio/pull/10349>, fixes encoders never receiving frames again after e.g. the multitrack output disconnected and tries to reconnect
Twitch Enhanced Broadcasting beta
> libobs: Fix grouped encoders never starting again after disconnect

- libobs/util/pipe-posix.c
Set `FD_CLOEXEC` file descriptor flag for the pipes created by `os_process_pipe_create`
Since https://github.com/obsproject/obs-studio/pull/10070 obs-ffmpeg-mux can get in a state that it does not close.
`os_process_pipe_destroy` waits till the process ends. The obs-ffmpeg-mux process is terminated when an EOF appears on the
pipe. However, forked process hold the file descriptor of the write-end of the pipe, the EOF won't arrive to the obs-ffmpeg-mux process.
Prevent plugins needing code to close all file descriptors like https://github.com/norihiro/obs-command-source/commit/f4e9b26210d818e4a98c54043b91aa1ff55c06cf
On Mac with the source record plugin
> libobs/util: Prevent leaking pipe file descriptors to subprocesses

- plugins/obs-qsv11/QSV_Encoder.cpp
- plugins/obs-qsv11/QSV_Encoder.h
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/QSV_Encoder_Internal.h
- plugins/obs-qsv11/common_directx11.cpp
- plugins/obs-qsv11/common_utils.h
- plugins/obs-qsv11/common_utils_linux.cpp
- plugins/obs-qsv11/obs-qsv11.c
Implements texture encoding based on #8312 bringing performance equivalence with windows. ~~Still draft as there are a handful of TODOs and doing the right thing on multi-gpu machines might need more plumbing in libobs, but for single gpu systems this should be enough to test the texture encoding PR.~~ Multi-gpu support is in place.
Gotta go fast. Encoding 1440p@120fps at 1% cpu is fun.
Tested on a KBL machine and a DG2 machine with h264/h265/av1 encoders. Everything seems to be working fine.
> obs-qsv11: Implement texture encoder on linux

- libobs/CMakeLists.txt
- libobs/cmake/legacy.cmake
- libobs/util/pipe-posix.c
- libobs/util/pipe-windows.c
- libobs/util/pipe.c
- libobs/util/pipe.h
- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
- Adds new `os_process_args_t` and associated API to construct command line arguments
- Adds `os_process_pipe_create2()` to take advantage of new API
- Migrates `obs-ffmpeg-mux` to the new API
Want a saner API than passing stuff to `/bin/sh` and dying inside while concatenating strings.
Recorded with output that requires ffmpeg muxer.
> Rework command line argument stuff

- plugins/obs-webrtc/whip-output.cpp
Adds the `whip_output_audio` and `whip_output_video` output kinds, which selectively advertise only video or only audio support.
To use these types, it is effectively the same as with the AV version. Just create the output, assign your video or audio encoder, and you're good.
It's not uncommon in WebRTC systems to have video-only or audio-only streams. The WHIP protocol supports this, so this will allow plugins which do custom things with WHIP to access this functionality.
Code compiles on Ubuntu 22.04
I've been using this patch for many months in production privately, and I think it can benefit more than just myself.
> obs-webrtc: Add support for audio-only and video-only outputs

- .github/workflows/push.yaml
The softprops/action-gh-release action is one of the last few remaining actions in this repo that was still using node16. Updating should remove the associated warnings.
Want less CI warnings so the meaningful warnings stand out.
Follow-up to:
* https://github.com/obsproject/obs-studio/pull/10175
Tested on my fork with obs-plugintemplate and got CI to be green with no warnings about node16.
See:
* https://github.com/obsproject/obs-plugintemplate/pull/118
* https://github.com/obsproject/obs-deps/pull/244
> CI: Update softprops/action-gh-release to v2.0.4

- plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Fixes issue introduced in #10101 that would result in the output file path being empty.
Fix bug.
Recorded file.
> obs-ffmpeg: Fix output path logging

- libobs/obs-av1.c
- libobs/obs-av1.h
- libobs/obs-internal.h
- libobs/obs-output.c
Main components of this change
1 - We will now keep a per track list of caption data. When caption insertion is triggered we will add that to the list for each actively encoding video track. When doing interleaved sending we will pull the data from the caption data for the corresponding video. This ensures that captions get copied to all video tracks.
2 - Captions were always being inserted as AVC SEIs regardless of the codec being used for encoding. This would corrupt anything other than AVC. This type of caption insertion must be handled on a codec by codec basis, and if a codec isn't handled explicitly, no caption insertion will be attempted. This was tested by streaming to twitch with a popular caption plugin enabled, while having enhanced broadcasting configured with HEVC and AVC …
> libobs: Add support for multitrack, AV1, and HEVC captions

- libobs/media-io/video-frame.c
The outer `for` loop defines a variable `i` to indicate the index of the plane, which is as expected.
The inner `for` loop should use a different name variable. I renamed the variable to `y` to indicate the line index of the iteration.
The PR #10139 implemented to copy a video frame into a different line-size video frame. However, when the line-size was different, the frame was not correctly copied.
I was writing a unit test to cover the new branch introduced by the PR #10139 and realized the bug. Fortunately, the bug has not been released yet.
OS: Fedora 38
Tested with a code below.
```c
static void memset_rand(void *dst, size_t size)
{
long *buf = dst;
for (size_t i = 0; i < size; i += sizeof(long))
buf[i] = random();
}
static void video_frame_line_by_line_test(void **state)
{ …
```
> libobs/media-io: Fix copying different line-size video frame

- plugins/win-dshow/ffmpeg-decode.c
Use "new" (FFmpeg 5.1+) channel layout API as needed.
Want to be able to compile against FFmpeg 7.0.
Follow-up to:
* #7462
Built locally on Windows 11. I'm not clear on how to activate this code path, so further review would be appreciated.
> win-dshow: Fix compiling with FFmpeg 7.0

- cmake/common/helpers_common.cmake
- cmake/macos/helpers.cmake
- cmake/windows/helpers.cmake
Qt Gui virtualkeyboard plugin was removed in Qt 6.x.
Qt Network Bearer Management was removed in Qt 6.0.
Qt Multimedia mediaservice and audio plugins were removed in Qt 6.x.
We don't support building with Qt 5 anymore, so we can remove Qt5-isms.
https://doc.qt.io/qt-5/bearer-management.html
https://github.com/qt/qtmultimedia/commit/98148969b112f82d2b49e77950ea5f6d8b37b8b2
https://github.com/qt/qtmultimedia/commit/762eff8c15aa8cbb6962c2893ff792ab172783ee
https://github.com/qt/qtmultimedia/commit/b4d331d08b48698c15d7b52da469341bf8dcfbca
https://doc.qt.io/qt-5/qtvirtualkeyboard-deployment-guide.html
https://doc.qt.io/qt-6/qtvirtualkeyboard-deployment-guide.html
> cmake: Remove more Qt 5 code

- plugins/obs-outputs/flv-mux.c
- plugins/obs-outputs/flv-mux.h
- plugins/obs-outputs/flv-output.c
- plugins/obs-outputs/rtmp-stream.c
- plugins/obs-outputs/rtmp-stream.h
Add eRTMP multitrack video support for the rtmp output and "full" eFLV support for the FLV output (both additional video codecs and multitrack video)
This allows transmitting multiple video streams within the same RTMP connection; it's used for Twitch Enhanced Broadcasting to allow multiple renditions to be sent through a single RTMP connection, helping ensure that renditions remain aligned
It's being used in the Twitch Enhanced Broadcasting Beta
> obs-outputs: Add eRTMP/eFLV multitrack support

- docs/sphinx/reference-encoders.rst
- libobs/obs-encoder.c
- libobs/obs.h
Allows parent (original) video object of an encoder with an FPS divisor to be fetched.
When implementing a non-shared-texture encoder, I needed to be able to determine the original video_t object to use as a reference for a cross-encoder frame caching system. Since FPS division creates a new video_t object, multiple encoders cannot be associated with each other if one of them has a divisor set, as the video_t object will be different.
Ubuntu 22.04, runs
> libobs: Add `obs_encoder_parent_video()` method

- deps/obs-scripting/cmake/python.cmake
- deps/obs-scripting/obspython/CMakeLists.txt
Remove Python version upper limit on Linux
We don't rely on the stable ABI on Linux…
Quickly tested the url-text.py script.
> obs-scripting: Remove Python version upper limit on Linux

- plugins/obs-webrtc/whip-service.cpp
- plugins/obs-webrtc/whip-service.h
This fixes an issue where when the MAX_CODECS length was equal to the amount of supported codecs (3), it would leave the list without a null terminator and crash when iterating over the elements.
Addresses a bug where a non-null terminated list of strings was iterated over into invalid memory
Crashes on some machines depending on if the memory layout had a null accidentally after the list.
Tested on Mac and Windows, no longer crashes in release mode.
Bug fix
> obs-webrtc: Add null terminator to codec array

- UI/window-basic-main.cpp
Changes the default recording container to Fragmented MOV on macOS for release builds.
See also #10331 and #10482 for additional context.
In 22205d582c6b2c010e2f48d52067eecb77c8857f (#10482), the change to default to Fragmented MP4/MOV on all platforms was reverted due to compatibility issues with the default video player on Windows.
On macOS however, the default player (QuickTime Player) works fine with fragmented formats, and instead is unable to play MKV files (which have always been the default format for OBS). This change makes videos with the default settings playable on macOS with the default player.
macOS 14.4.1
Created a new profile without this change, witnessed the default container to be MKV.
Created a new profile with this change and saw that the default was Fragmented MOV.
- …
> UI: Set default recording format to Fragmented MOV on macOS

- UI/data/themes/Yami.obt
Restore MuteCheckBox indeterminate state icon in Yami
Release (before composable theme):
Master:
PR:
Found weird that the button was empty rather than yellowish.
Launched OBS with a source with audio set to to none of the track.
> UI: Restore MuteCheckBox indeterminate state icon in Yami

- libobs-winrt/CMakeLists.txt
- libobs-winrt/cmake/legacy.cmake
- libobs-winrt/winrt-capture.cpp
Remove the custom declarations of the external 
functions _CreateDirect3D11DeviceFromDXGIDevice_ and 
_CreateDirect3D11SurfaceFromDXGISurface_, as well as the 
_IDirect3DDxgiInterfaceAccess_ interface. 
Add WinSDK interop header:
_windows.graphics.directx.direct3d11.interop.h_
This cleanup simplifies our codebase and ensures we're 
utilizing the standard, up-to-date definitions provided by the 
Windows SDK.
Tested AMD Windows 11 with WinSDK 10.0.22621.0.  Header file exists
in WinSDK 10.0.20348.0 as well, with same code definitions.
> libobs-winrt: Remove interop code now provided by Windows SDK

- libobs/media-io/media-remux.c
- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
This fixes two bugs with surround sound (blame Rodney !).
(1)
Commit [1] added ALAC & PCM support.
But 7.1 ALAC encoding fails.
This fixes the issue by assigning the correct 7.1 layout supported by FFmpeg ALAC encoder (7.1(wide)).
[1] https://github.com/obsproject/obs-studio/commit/3ae98511d09f1ebaf5c9cc005a285efd1a26aeff
(2) This commit [2] uses the av_channel_layout_default & av_get_default_channel_layout which set 5.0
as layout for 5 audio channels; but obs sets 4.1 speaker layout for 5 channels.
The second commit of this PR fixes that.
[2] https://github.com/obsproject/obs-studio/commit/567e35ac693ca0e97e0e74d4f7649fea7501d3ad
Fix a bug.
I came upon this bug while reviewing Rodney's hybrid mp4 muxer.
https://github.com/obsproject/obs-studio/pull/10608
The bug is due to the fact that …
> libobs & obs-ffmpeg: Surround sound fixes

- UI/cmake/linux/com.obsproject.Studio.metainfo.xml.in
- UI/cmake/os-linux.cmake
#9787 kept the old version of the metainfo file in the CMake 3 path
CMake 2 path have a newer version of this file.
See the following commits for metainfo change details:
- 853ae5e
- 904fe87
- 0cc6068
Fix an issue
CI will tell
> UI: Improve and update app CMake 3 metainfo file

- build-aux/com.obsproject.Studio.json
- build-aux/modules/20-aom.json.disabled
- build-aux/modules/20-svt-av1.json
- build-aux/modules/30-ffmpeg.json
- build-aux/modules/40-luajit.json
- build-aux/modules/50-libdatachannel.json
- build-aux/modules/50-libvpl.json
- build-aux/modules/50-ntv2.json
- build-aux/modules/50-vpl-gpu-rt.json
- build-aux/modules/90-asio.json
Companion to #10654 for the Flatpak
- build-aux: Update Flatpak modules
* Update SVT-AV1 to 2.0.0
* Update aom to 3.9.0
* Freedesktop SDK already provides it, so the module is disabled
* Update FFmpeg 7.0
* Update LuaJIT 5790d25397
* Update libdatachannel to 0.21.0
* Update Asio to 1.30.2
- build-aux: Update Flatpak VPL modules
* Update libvpl to 2.11.0
* Adds a build option to no longer require ONEVPL_SEARCH_PATH to be set
* Update onevpl-intel-gpu to vpl-gpu-rt 24.2.2
- build-aux: Update Flatpak ntv2 module to libajantv2
Update deps.
Just build and ran it.
> build-aux: Update Flatpak dependencies

- UI/window-basic-main.cpp
Changes an action that's getting a source from the weak source to check if the source still exists to simply use `obs_weak_source_expired`.
Noticed this, and appears to be unnecessary.
macOS 14.4.1
Copied filters from a source.
Right clicked on the audio mixer to see that "Paste Filters" is available.
Deleted the source. Right clicked on the audio mixer again and "Paste Filters" is unavailable.
> UI: Use weak_source_expired instead of getting the source

- libobs/obs-avc.c
Adds extended information for high* profiles to `obs_parse_avc_header()`.
When testing #10608 I received a warning from a third party tool that the `AVCDecoderConfigurationRecord` produced by `obs_parse_avc_header()` was missing these things.
ISO/IEC 14496-15 Section 5.3.3.1.2 says this should be present for high/high10/high422/high444 profiles (high and high444 are supported by OBS).
Given that nobody cared for the past 10 years this is not critical, but still nice to be correct.
Recorded a video with #10608 and validated the data is now present.
> libobs: Fix obs_parse_avc_header missing high profile parameters

- plugins/obs-webrtc/whip-output.cpp
- Fixes ifdef guards for HEVC
- Fixes a capitalization of a few comments
- Only advertises relevant codecs in audio-only and video-only outputs
Clean things up and improve standards
OBS compiles
> obs-webrtc: Various WHIP patches

- UI/source-tree.cpp
- UI/source-tree.hpp
- UI/visibility-item-widget.cpp
- UI/visibility-item-widget.hpp
This changes the labels for the source tree/visibility item widgets to use OBSSourceLabel, as it handles the renaming of sources.
Less code
Renamed sources in the filters dialog and the source tree
> UI: Use OBSSourceLabel for item widget labels

- UI/window-basic-main.cpp
- UI/window-projector.cpp
- UI/window-projector.hpp
This moves the renaming of projectors from OBSBasic to OBSProjector.
Makes projector code more self contained
Renamed sources
> UI: Move projector rename signal

- UI/volume-control.cpp
- UI/volume-control.hpp
- UI/window-basic-main.cpp
Commit 1 - Use vector for volume signals
Commit 2 - Use OBSSourceLabel for volume controls
Cleaner code
Used volume controls and renamed sources
> UI: Volume signal cleanup

- UI/window-basic-preview.cpp
Gives names to the spacing helper label private text sources in the preview, to make the log a bit nicer.
If people think the `dstr` is overkill (I'm a bit torn on that) I'd also be happy to change it to a generic `Preview spacing label` instead.
When you click on a scene item for the first time in a program run, you get this log:
```
debug: private source '(null)' (text_ft2_source) created
debug: private source '(null)' (text_ft2_source) created
debug: private source '(null)' (text_ft2_source) created
debug: private source '(null)' (text_ft2_source) created
```
While this obviously isn't a huge issue I think it's nicer to have debug lines that actually say something, so with this PR you get this:
```
debug: private source 'Preview spacing label 0' (text_ft2_source) created
debug: private …
```
> UI: Give private spacing helper sources names

- UI/window-basic-preview.cpp
Currently, the spacing lines begin in the middle of the box and then are their width wide towards one direction. This means that the larger they are, the more off-center their middle is.
This commit changes them to start at half their width left/top of the center and end half the width to the right/bottom of the center, putting the middle in the center.
Before/After:
<p>
</p>
Before/After with the width increased 10x for bigger effect:
<p>
</p>
This bothered me for a long time.
macOS 14.4.1
See screenshots above.
Also checked for lines wiggling. It appears to be the same behavior as before.
> UI: Center preview spacing lines

- UI/data/themes/Yami.obt
- UI/data/themes/Yami_Classic.ovt
Changes the font size on macOS to be more appropriate
Depends on #10661, supersedes #10660
Closes #10660
10pt font is smaller on macOS than other operating systems. We increase it only on macOS
It has not
> UI: Adjust font size on macOS

- .github/workflows/build-project.yaml
- .github/workflows/push.yaml
CI: Add Ubuntu 24.04
Add a job matrix for the Ubuntu Build so that we can test builds on both Ubuntu 22.04 and 24.04.
Want to make sure that OBS builds on 24.04 (at least on GitHub Actions runners).
Known caveat is that the GitHub Action image does have some newer software than a normal install of Ubuntu 24.04 (usually, GitHub's CMake is newer).
This PR does not update _all_ CI jobs/actions to use Ubuntu 24.04, as that image is still in beta.
This PR changes the sources package to use the sources created in the Ubuntu 24.04 job just so we don't have to remember to fix that whenever we remove the 22.04 job. I checked sources packages between 22.04 and 24.04 and they were identical.
Tested with a few runs on my fork. May be helpful to manually clear the old cache variables before merging, …
> CI: Add Ubuntu 24.04

- .github/scripts/utils.zsh/setup_ubuntu
Add clear separation between the CEF setup and the apt/apt-get calls. This makes it easier to see how much time is being spent on each task.
Was comparing build times between the ubuntu-22.04 and ubuntu-24.04 runners, and it bothered me that the "CEF" step included the calls to apt-get.
It hasn't, but it's a single line logging addition.
> CI: Add additional log group to setup_ubuntu script

- .clang-format
- plugins/mac-capture/mac-sck-audio-capture.m
- plugins/mac-capture/mac-sck-common.h
- plugins/mac-capture/mac-sck-common.m
- plugins/mac-capture/mac-sck-video-capture.m
Replace pragmas silencing `-Wunguarded-availability-new` by availlability markers.
Note: When placing the marker before a function declaration, clang-format can add an empty new line between the marker and the declaration. So markers were put after when it comes to function declaration.
I tried to unvendor simde and discover that `mac-sdk-common.h` pragmas somehow contaminated other `mac-sck-*.mm` files because of our vendored simde.
Simply moving the pragmas like the following allows to fix the contamination:
```diff
diff --git a/plugins/mac-capture/mac-sck-common.h b/plugins/mac-capture/mac-sck-common.h
index 32ca8d246a8a5..e8b1911f6164d 100644
--- a/plugins/mac-capture/mac-sck-common.h
+++ b/plugins/mac-capture/mac-sck-common.h
@@ -1,9 +1,6 @@
#include <AvailabilityMacros.h>
#include …
```
> mac-capture: Replace pragmas with availability markers

- UI/window-basic-status-bar.cpp
- UI/window-basic-status-bar.hpp
The status bar doesn't currently own its references to outputs, which can be a problem if streaming outputs are released soon after stream stop. The Multitrack Video output does exactly that, so the status bar will sometimes try to access an invalid pointer for updating its stats. Keeping a weak reference around and upgrading it to collect stats, similar to how the stats window behaves.
Picked from #10633. Want to pull some commits out of that PR to make that PR smaller.
This has been tested in the Twitch Enhanced Broadcasting beta.
> UI: Keep weak stream output ref in status bar

- docs/sphinx/reference-libobs-util-serializers.rst
- libobs/util/array-serializer.c
- libobs/util/array-serializer.h
Adds support for the seeking functionality of the OBS serializer API to the array serializer.
Also adds a `reset` function that can be used to avoid reallocating memory when multiple things need to be serialized in one step.
Sometimes you need to be able to seek in memory to make things easier, e.g. to write a size field after the contents have been written.
Split out from #10608 for easier review and slimming down that PR as things get merged.
Tested as part of #10608.
> libobs/util: Add seeking support to array serializer

- docs/sphinx/reference-libobs-util-serializers.rst
- libobs/CMakeLists.txt
- libobs/util/buffered-file-serializer.c
- libobs/util/buffered-file-serializer.h
Adds a buffered file serializer, essentially porting the feature added in #5717 to the libobs utilities and serializer API.
See #5717 for the reasons of wanting a buffered writer.
As the existing one is only in the ffmpeg muxer binary, but I also needed it for the native MP4 muxer, I figured it'd be good to make it available via the generic OBS serializer API so it can be reused in other components if it makes sense to do so. For example, we may consider also using it in the native FLV output.
Split out from #10608 for easier review and slimming down that PR as things get merged.
Tested as part of #10608.
> libobs/util: Add buffered file serializer

- plugins/obs-outputs/rtmp-hevc.c
Sets `ps_array_completeness` when creating the HEVC Decoder Configuration Record to 1.
The `hvc1` tag is used in Enhanced FLV/RTMP and the native MP4 muxer (#10608) because Apple for some reason does not support the more permissive `hev1` tag, and one of the requirements laid out in the specification (ISO/IEC 14496-15) is that for `hvc1` the `array_completeness` value for parameter sets needs to be `1`.
FFmpeg also just sets this to 1 if the tag is `hvc1` without any additional checks for bitstream modification and I checked playback of these files on Windows and macOS with various players and browsers so it's probably fine.
As far as I can tell this really just means that all SPS/VPS/PPS need to be inside the `HEVCDecoderConfigurationRecord` present in the `moov` atom, which is what we …
> obs-outputs: Adjust HEVCDecoderConfigurationRecord for hvc1 tag

- libobs/obs-output.c
Only set audio offset if current DTS is positive.
DTS/PTS can be negative for "priming" samples produced by AAC/Opus encoders, currently this would result in the DTS/PTS being corrected to 0, which causes A/V desync by making the silent priming samples part of the actual presentation.
By leaving the negative DTS/PTS the FFmpeg muxer (and #10608) can correctly set the encoder delay and ensure synced playback.
Recorded a few videos of the Twitch sync test and validated that sync is now equivalent to PCM (there still seems to be one frame of delay somewhere in OBS).
(Note: #10690 was included here)
> libobs: Ensure audio offsets are positive

- plugins/coreaudio-encoder/encoder.cpp
- plugins/coreaudio-encoder/windows-imports.h
> [!Note]
> Requires #10689 to be fully functional as currently OBS will not treat negative audio timestamps correctly.
CoreAudio - and other AAC encoders - generally have an encoder delay that produces a number of silent "priming" samples. For CoreAudio AAC this is 2112 by default and this needs to be subtracted from the PTS/DTS to ensure that PTS 0 is the actual start of the input audio.
See Apple's documentation for a good explanation of AAC encoder delay and how to deal with it: https://web.archive.org/web/20170912012230/https://developer.apple.com/library/content/documentation/QuickTime/QTFF/QTFFAppenG/QTFFAppenG.html
Want audio to be in sync.
When using FFmpeg encoders libavcodec already handles this for us. This is also already done in the libfdk-aac module: …
> coreaudio-encoder: Fix pts/dts not including encoder delay

- libobs/obs-scene.c
- libobs/obs-scene.h
Only mix audio of each unique source in a scene once.
Fixes a common pitfall as the constructive interference due to multiple scene items using the same source is not visible anywhere.
Based on discussions this should not happen.
Pure sine wave media source and ffmpeg `volumedetect` to make sure recordings after this fix have the same volume as a recording with only one scene item.
> libobs: Mix audio of each source in a scene only once

- UI/forms/OBSBasicSettings.ui
UI: Give unnamed settings labels relevant names
Pulled from #10633. These changes should be non-controversial.
Did a quick test build/run on Windows 11.
> UI: Give unnamed settings labels relevant names

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Updated the Joystick.TV RTMP service with
* a new `more_info_link`. Previous URL still 301 redirects for backwards compatibility
* Added a new Ingest server for Europe
* Renamed the North American server from "RTMP" to "North America" to be more explicit in the location
* Added recommended "max fps" setting
* Updated `x264opts` with `scenecut=0`
We recently launched a new ingest server in the EU for all of our European Streamers. This gives them easier access to setup OBS using the new EU servers.
The recommended settings are updates to help stability when streamers use the "Simple" format.
Replaced `/home/jeremy/.var/app/com.obsproject.Studio/config/obs-studio/plugin_config/rtmp-services/services.json` with the updated file, and streamed in to the site.
RTMP service update. (update to …
> rtmp-services: Update Joystick.TV servers and recommended settings

- UI/window-basic-main.cpp
When clicking Grid Mode or List Mode from the context menu within the Scenes list, whether or not Grid Mode is enabled persists between OBS sessions. When clicking Grid or List from the View Menu, the setting does not persist between OBS sessions. This seems to be a regression from fc8c42852173ed17729f343f8423901cc97ee351 (#8908).
Previously, SceneTree's SetGridMode would set this config value. If the intent is to not have SetGridMode directly set the config value, then any function that calls SetGridMode other than the OBSBasic constructor must instead set the config value.
Was reported in Discord. The behavior is inconsistent and seems incorrect.
> UI: Fix Grid Mode not persisting from View Menu

- UI/multiview.cpp
- UI/multiview.hpp
Adjusts the size of multiview borders and the label styling to be less opaque to avoid covering actual scene content.
**Before**
**After**
Preview/Program indicator borders are important information, so increasing the border width greatly improves their readability in some multiview layouts and display sizes/resolutions.
The size and position of the label box is adjusted to be based off the label's height plus the border width to look more consistent and fix the text not being vertically centered.
The background and label text are made less opaque to ensure they don't completely block visual content.
-----
Many hardware multiviews either place the labels outside/around the content, or on top with no background. BlackMagic ATEM is only of the only examples that places a black background …
> UI: Adjust appearance of multiview borders and labels

- UI/obs-app-theming.cpp
- UI/obs-app.cpp
- UI/obs-proxy-style.hpp
As of 8dcfae9a390763645d354700f36caef6b8f482c7, indicating the base style to the proxy is completely functional.
It also bypasses QT_STYLE_OVERRIDE and -style, but since the system theme is no longer available on Linux this is a non-issue.
Rewrite of #6664 to use the conventional method to enforce a Qt style.
Since #10602, issues with the conventional method were fixed since there is one style for the whole app.
Also #9653 phased out the system theme on Linux and other themes only support Fusion as a base style on Linux.
So the side-effect of #6664 allowing the user to set their own Qt style is mostly unusable and potentially unwanted.
Enforced system theme in the config file, and try to ran OBS with Breeze enforced.
With the PR, Fusion was in use and not Breeze.
- Code cleanup …
> UI: Enforce completely Fusion Qt style on Linux

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Copy-Pasting filters on a scene or on a source via the audio mixer context menu would not add an undo/redo action. This commit factors the undo/redo logic out into a generic paste filters function that can be used for pasting filters everywhere.
Noticed at some point that pasting filters via the audio mixer context menu wouldn't add an undo/redo action.
Found the same behavior when pasting on scenes when looking at the code.
macOS 14.4.1
Pasting filters on scenes or on a source via the audio mixer now adds an undo/redo action.
Looked through the code to find out there are no more `obs_source_copy_filters` calls in the codebase.
> UI: Add undo/redo to Paste Filters on audio mixer and scenes

- UI/window-basic-main.cpp
- docs/sphinx/reference-core.rst
- libobs/obs-source.c
- libobs/obs.c
Currently, when adding a filter to a source and then right-clicking it
or using the menu bar edit menu, it's not possible to copy the source's
filters. This is because the edit menu does not update on filter
changes.
Listening to the new global filters add/remove signal and updating the
edit menu will enable the copy option if a filter get added or disable
the option if the last filter gets removed.
If we're against a new global OBS signal, there are two possible
alternatives. However, I consider both to be worse than this solution:
- We could connect and disconnect the existing source signal on each
selection/deselection. This feels like it's quite a lot of overhead, and a
big headache for (future) code maintainability.
- We could create a Qt signal for the filters window that then …
> UI,libobs: Update edit menu on source filter changes

- libobs/media-io/video-frame.c
Fixes buffer overrun in `video_frame_init()`
`offsets[]` has size `MAX_AV_PLANES - 1` but the loop would iterate over `MAX_AV_PLANES`, thus resulting in it writing to the memory past the last item.
It is worth noting that in reality this would've never overran, as `MAX_AV_PLANES` is `8`, but the highest amount of planes a video frame can have is 4 (YUV + Alpha).
Found by ~~@notr1ch~~ PVS Studio.
Hasn't.
> libobs: Fix buffer overrun in video_frame_init

- plugins/mac-avcapture/plugin-main.m
Adds a comma to the end of the definition to improve on an... *interesting* formatting choice by clang-format.
Noticed this when working on something else, it made my eyes hurt.
A comma at the end is established practice in the rest of the code base.
Ran clang-format to get this new formatting.
Shouldn't have
> mac-avcapture: Improve av_capture_sync_info formatting

- .github/actions/windows-patches/action.yaml
- .github/workflows/push.yaml
- .github/workflows/sign-windows.yaml
Adds [GitHub's new attestation feature](https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/) to Windows release workflows.
This ensures that the artifact used to generate delta updates has been generated on CI and has not been altered before the patch workflow runs.
Tested on my fork.
> CI: Generate/Verify Attestation for Windows builds

- UI/auth-twitch.hpp
- UI/window-basic-main.hpp
The class DeviceToolbarPropertiesThread appears to have been removed, and the friend class here is redundant code
The class is located in
but has been removed in https://github.com/obsproject/obs-studio/commit/50d3130b641d9914901cec63009438a0892dfc88.
Yes, on windows11-22H2.
Clean up code.
> UI: Removed unused friend classes

- UI/properties-view.cpp
- UI/window-basic-settings.cpp
- UI/window-basic-settings.hpp
- UI/window-basic-transform.cpp
- UI/window-youtube-actions.cpp
qt/qtbase@3512fb1ec5ff088772170540c4e91b1886fbea45 (also cherry-picked to https://github.com/qt/qtbase/commit/02ba4b14dc1c0cee802d8d840315833fda2449b4) deprecated the stateChanged signal of QCheckBoxes in favor of a new checkStateChanged signal. The signals are the same, except that now the enum type is passed explicitly (before the enum was passed as an argument but defined as an int).
The documentation states that it's deprecated for 6.9 but I got the warning now already (dev version appears to be 6.8 currently) and it's also picked to 6.7 and the alternative exists since 6.7 so I'm not 100% what the "real" deprecation version is but 6.7 makes sense.
Got a deprecation warning when compiling against Qt dev branch.
macOS 14.5 with Qt dev branch.
Tested all the code paths (settings, …
> UI: Fix Qt 6.7 checkbox signal deprecations

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
add a streaming service "sheeta" into "plugins/rtmp-services/data/services.json"
Our service "Sheeta" requires broadcasters to set the keyframe interval appropriately to achieve low-latency delivery.
"Sheeta" is a service described at the following link: https://www.sheeta-info.com/ .
It is a fan club management service that utilizes OBS for its broadcasting features.
We Dwango Inc.(KADOKAWA Group) provide this service. We have been operating "niconico Live", the most famous live streaming service in Japan, for 10+ years.
I did "Local testing" as described in [Service Submission Guidelines](https://obsproject.com/wiki/Service-Submission-Guidelines) .
> rtmp-services: Add sheeta

- docs/sphinx/reference-frontend-api.rst
Adds documentation for `obs_frontend_recording_add_chapter()`.
This was missing from #10608 
N/A
> docs: Document obs_frontend_recording_add_chapter()

- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Previously, we just checked for H264 regardless of which codec was selected. This mostly worked, but on Fedora they ship AV1 without H264 or HEVC. In that case users wont see AV1 as an option.
We really should have been checking the right codec, and users will want to use AV1 without special drivers.
I dont see any changes on my AMD machine. I'll test a fedora machine later.
> obs-ffmpeg: Check correct VA-API codec support

- plugins/obs-qsv11/common_utils_windows.cpp
Fixes Intel QSV not working on setups where the Intel GPU is not idx 0.
QSV started failing on my NVIDIA dGPU+Intel dGPU system with https://github.com/obsproject/obs-studio/commit/4c6e2a6722de4ed923cf29bc0bf65ddd8f45a2cf applied.
The IDX fed into `MFXCreateSession()` only counts Intel GPUs, so we need to adjust the index down if there are non-Intel GPUs earlier in the list.
This is already done in the QSV test app, but was missing here: https://github.com/obsproject/obs-studio/blob/master/plugins/obs-qsv11/obs-qsv-test/obs-qsv-test.cpp#L73-L86
Tested on system with RTX 4090 and Arc A750.
> obs-qsv11: Fix QSV failing on multi-vendor multi-GPU systems

- plugins/obs-outputs/cmake/legacy.cmake
Adds the new hybrid MP4 output added in #10608 to legacy cmake.
Fixes #10764 
Built with legacy cmake on Linux, confirmed OBS no longer crashes.
> obs-outputs: Add native mp4 output to legacy cmake

- UI/window-basic-status-bar.cpp
- UI/window-basic-status-bar.hpp
This changes the status bar record output from a strong reference to a weak one.
Make it consistent with the stream output.
Recorded and made sure status bar still worked as expected.
> UI: Make status bar record output a weak ref

- plugins/obs-webrtc/whip-output.cpp
Adjust RtcpNackResponder from bitrate
At higher bitrates the cache would be undersized. Because of the undersized cache we wouldn't have enough NACK history to fix the stream.
Against Broadcast Box with a packet loss percentage of 1%
> obs-webrtc: Adjust RtcpNackResponder from bitrate

- .github/actions/windows-analysis/Invoke-External.ps1
- .github/actions/windows-analysis/Logger.ps1
- .github/actions/windows-analysis/action.yaml
- .github/actions/windows-analysis/obs.pvsconfig
- .github/workflows/analyze-project.yaml
- .github/workflows/scheduled.yaml
- README.rst
Runs PVS-Studio on Windows builds during scheduled runs.
Static analysis is nice to have, SARIF integrates with GitHub so maintainers can easily manage and action on automatic analysis reports.
Settings this up for Linux and macOS is a bit more involved as we can't just run it on a project file as on Windows, and the command line/configuration files are different. There will be some duplication between the three platforms which may be annoying, so ideally we'd also try to cut non-Windows platforms down to platform-specific files. We'll deal with that at a later date.
Ran on my fork.
> CI: Add PVS-Studio Analysis for Windows

- UI/CMakeLists.txt
- cmake/linux/helpers.cmake
Fixes #10737
Supersedes #10739
SOVERSION is either the major number of a semver or an arbitrary number incremented at each API/ABI break.
CMake 3 does not apply RPATH like CMake 2 so it unraveled this issue.
We didn't released a CMake 3.0 Linux build, so no breaking change.
Build and installed the Flatpak locally and OBS finds `libobs-opengl.so.30`.
Non-Flatpak local build seems to work too.
> cmake,UI: Fix SOVERSION on Linux

- UI/cmake/legacy.cmake
- UI/cmake/os-linux.cmake
- UI/obs-app.cpp
- UI/ui-config.h.in
USE_XDG definition is missing in CMake 3 code in the UI subdirectory.
This override is still needed until Qt minimum version requirement is increased to at least 6.3.0.
We still support Qt 6.2 and Ubuntu 22.04.
The override should enforce the Wayland platform where Qt was enforcing the X11 on GNOME Wayland.
The enforce was removed in 6.3.
Not tested.
> UI: Fix Qt platform override in CMake 3

- .github/actions/windows-analysis/action.yaml
Adds the error code indicating the licence is expiring soon to the ignored ones.
Want to avoid failure if there isn't one.
This shouldn't be required as we set `--disableLicenseExpirationCheck` check but here we are.
Hasn't.
> CI: Ignore PVS-Studio's license close to expiry error code

- UI/window-basic-settings.cpp
We refer to VOD tracks as 1-6 but internally the array is 0-5 so there's an off-by-one error here. I don't really like this mix of 1-6 and 0-5 as it's prone to these kind of bugs, but refactoring this is probably best left for another time.
Crash.
Opened settings, no longer crashed.
> UI: Fix crash when entering settings

- libobs/cmake/legacy.cmake
Adds buffered file serializer to legacy CMake.
Fix #10764 ...again
Hasn't.
> libobs: Add buffered file serializer to legacy cmake

- plugins/obs-filters/obs-filters.c
Do not load nvvfx when started with opengl
I want to be able to test opengl on windows without crashes as nvidia greenscreen filter uses `NvCVImage_InitFromD3D11Texture`
On windows 11 by starting with directx and with opengl
> obs-filters: Do not load NVVFX on OpenGL

- plugins/obs-webrtc/whip-output.cpp
- plugins/obs-webrtc/whip-output.h
WHIP/WHEP allows ICE Servers to be specified via [Link Headers](https://www.ietf.org/archive/id/draft-ietf-wish-whip-13.html#name-stun-turn-server-configurat)
Some WebRTC deployments are behind a NAT. Companies/developers place their TURN server on the edge, and use that to access the TURN servers.
I have had 3 companies reach out to me about this, so implemented it.
Ran broadcast-box and only listened on `127.0.0.1` and confirmed that traffic could be routed through [pion/turn](https://github.com/pion/turn)
> obs-webrtc: Add Link Header support

- UI/window-basic-main.cpp
Disable Multitrack Video (Twitch Enhanced Broadcasting) by default.
Noticed in testing that this was on by default in all cases. This is a behavior change that would suddenly and without warning change streaming settings for any users configured to stream to Twitch, such as increasing the amount of bandwidth used.
Built and ran locally on Windows 11.
> UI: Disable Multitrack Video by default

- UI/models/multitrack-video.hpp
- UI/system-info-windows.cpp
Remove GPU LUID from system info for Multitrack Video
Noticed LUID was sent with the other GPU info. After further review, decided this is not needed.
Built and ran locally on Windows 11.
> UI: Remove GPU LUID from system info for Multitrack Video

- UI/multitrack-video-output.cpp
UI: Fix incompatible settings message when streaming Multitrack Video
When streaming with Multitrack Video (Enhanced Broadcasting) and incompatible settings, the warning message was missing parts of the string due to incorrect translation string keys.
Additionally, use Unicode arrows to direct users through UI elements.
The bulk of the diff is just clang-format rearranging lines.
Want warning/error messages to be readable.
> UI: Fix incompatible settings message when streaming Multitrack Video

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
This is a smaller version of https://github.com/obsproject/obs-studio/pull/10634
Add Amazon IVS service entry with global DNS names
Currently users of Amazon IVS customers have to use the custom service entry and enter both a URL and their stream key; with multitrack video they'd also have to enter a config URL (which is currently not exposed in the custom service UI)
With these changes users will generally only have to enter their stream key (and select "Global (RTMPS, recommended)" or "Global (RTMP)" depending on whichever the Amazon IVS customer wants their users to use)
Tested using various IVS channels created for testing purposes, some of which were allowlisted for multitrack video
> rtmp-services: Add Amazon IVS service

- UI/window-basic-settings-stream.cpp
Add Amazon IVS service entry with global DNS names
Currently users of Amazon IVS customers have to use the custom service entry and enter both a URL and their stream key; with multitrack video they'd also have to enter a config URL (which is currently not exposed in the custom service UI)
With these changes users will generally only have to enter their stream key (and select "Global (RTMPS, recommended)" or "Global (RTMP)" depending on whichever the Amazon IVS customer wants their users to use)
Additionally, this enables the "custom server" settings entry for Amazon IVS
Tested using various IVS channels created for testing purposes, some of which were allowlisted for multitrack video
> UI: Enable custom server entry for Amazon IVS

- UI/obs-app.cpp
- UI/qt-wrappers.cpp
- libobs/util/base.c
Changes the remaining log buffer allocations in the log handler to use a buffer of size 8192 instead of 4096. Also adds improved string handling in the form of using `strncpy` rather than `strcpy` in the `too_many_repeated_entries()` check.
OBS was crashing on startup when logging messages over 4096 characters in length with corruption of the `QPointer` object for the log viewer. It turns out that this was due to a buffer overrun in the log handling code.
https://github.com/obsproject/obs-studio/commit/43a1b309940b7bb7a92fdcd019bd011ef762621f changed the size of the log buffer in obs-app.cpp's `do_log`, but to change the size of the buffer properly we need to also modify the buffer size in the subsequent check for repeated entries, as well as the base log handler in `libobs`. Otherwise …
> UI: Address logging buffer size discrepancies

- UI/multitrack-video-output.cpp
Removes some dead code.
Not needed anymore, just adds noise.
N/A
- [x ] I have included updates to all appropriate documentation.
> UI: Remove dead code from multitrack output

- plugins/obs-webrtc/whip-output.cpp
- plugins/obs-webrtc/whip-utils.h
API not available in Ubuntu 22.04 which ships 7.81 this API was first available in 7.83
Fixes build on Ubuntu 22.04
Tested against WHIP server with TURN
Tested against Broadcast Box
Tested against Twitch
> obs-webrtc: Do not use curl_easy_nextheader

- UI/multitrack-video-output.cpp
- UI/window-basic-main-outputs.cpp
Adds config option `MultitrackVideoStreamDumpAsMP4` to use the native MP4 muxer instead of FLV for dumping multi-track video to disk.
The "multitrack recording dump" output is hidden by default and exists for debugging/testing purposes, but it uses multi-track FLV which is not yet supported by FFmpeg and other tools. So when it's not being used to debug the FLV muxer itself this will make it easier to get a file containing all synchronised streams in one that is actually usable with existing software.
Tested locally. Opened file in MPC-HC:
> UI: Add config option to use MP4 for debug recording

- UI/multitrack-video-output.cpp
Simplifies the check for whether or not an encoder is available.
Much more readable and avoids the creation of a pointless `std::vector`.
Locally.
> UI: Simplify multitrack encoder availability check

- .github/workflows/analyze-project.yaml
Disables PVS Studio analysis job on forks as they (probably) won't have the licence key for PVS set up.
Don't want run failures on people's forks.
Hasn't.
> CI: Restrict PVS-Studio analysis to obsproject repo

- .github/actions/windows-patches/action.yaml
Fixes the input variable name.
Release notes should only be the latest tag, not all of them, silly.
Hasn't.
> CI: Fix input variable name when getting Windows release notes

- UI/obs-app.cpp
Removes an unused string copy of the last log output.
Found while looking at #10799, though unrelated to the crash.
N/A
> UI: Remove unnecessary string copy from log filter

- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.cpp
- UI/window-basic-preview.cpp
Adds some null checks.
Passing null pointers into the API isn't good behavior and generates a debug warning.
Built and ran OBS.
> UI: Add null checks before doing some API calls

- UI/properties-view.cpp
QMacStyle appears to have an issue where it messes up the positions of some widgets. The previous workaround added extra spacing to force the icon further to the right. Forcing the widget rectangle to be used instead of the one made by the style also fixes this, arguably in a nicer way.
See also b760b24ff00e844c34be0d26222976ee99281472 which does this for checkboxes in the source tree.
I'm planning to take a deeper look into what QMacStyle is doing that messes this up at a later point.
Stumbled across this when trying to look into why the checkbox has some sort of spacing to the left.
I did not yet succeed with that investigation.
macOS 14.5.1
See that even without extra spacing, the icon is at the correct position (that matches other operating systems):
- Code cleanup (non-breaking …
> UI: Improve macOS properties tooltip spacing workaround

- UI/basic-controls.cpp
Fixes a typo that resulted in a wrong connection, where the controls dock slot would attempt to connect to the main window slot instead of signal, which of course doesn't work.
To the user, this would mean that the replay buffer button text wouldn't change to "Stopping" when pressing "Stop", instead staying on "Stop" while stopping and then going to "Start" directly.
30.2 regression.
Saw obsproject/loganalyzer#163 that excluded an `OBSBasic`, which looked suspicious. No log should contain `OBSBasic`.
Turns out that Qt logged a warning that a signal couldn't be found. Looking into that further , this makes sense since the signal that the slot was connected to wasn't a signal.
macOS 14.5
Firstly, made sure the bug indeed exists (see observation in Description).
Tested that with this patch, …
> UI: Connect replay buffer stopping to signal instead of slot

- cmake/linux/helpers.cmake
Soname files are required since 1d8c377240dbeb601c8cc3c22bdd1888f685dcb7
Relocatable OBS can't be ran from rundir without this change.
I had to remove my system install of OBS to make sure that no `libobs-opengl.so.30` were in library paths.
With the PR, OBS ran from the rundir. Doesn't without.
With the PR and OBS install on the system, OBS ran from the rundir loading the right file.
Without the PR it loads the system install file.
`LD_DEBUG=libs ./obs` partial output with PR:
```
info: OBS 30.2.0-beta1-5-ge69061ad8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
samples per sec: 48000
speakers:        2
max buffering:   960 milliseconds
buffering type:  dynamically increasing
56595:	find …
```
> cmake: Copy shared library soname file to rundir on Linux

- UI/absolute-slider.cpp
- UI/data/themes/Yami.obt
- UI/volume-control.cpp
These commits make a few adjustments or fixes to the audio mixer.
1. Group the buttons together in horizontal layout for better alignment
2. Cleans up some spacing and sizing of audio mixer widgets
3. Remove wheel events from the absolute-slider event filter. This is still appropriately handled by the slider-ignorewheel widget
4. macOS-specific fix. May be able to squash
5. Center widgets in vertical layout
Before:
After:
Before:
After:
Fix and clean up audio mixer changes.
Tried scrolling the audio mixer while hovering a volume meter or slider
- Tweak (non-breaking change to improve existing functionality) -->
> UI: Various audio mixer adjustments and clean up

- UI/obs-app.cpp
Adds a check on startup that ensures a compatible Visual C++ runtime is being used.
The user is given the option to automatically open our existing VC runtime download page (https://obsproject.com/visual-studio-2019-runtimes),
Due to backwards-incompatible changes in MSVC 14.40 OBS crashes on startup for some users that do not have up to date runtimes installed. See #10799.
We should also adjust the updater and installer to check for these older versions, but that will be a larger undertaking and also does not cover the use case of portable ZIPs (unlike this PR).
Tested on Windows VM with outdated vc runtime:
> UI: Check VC++ Runtime version on startup

- UI/obs-app-theming.cpp
Avoid allowing to override provided themes when a user adds a themes with the same id.
User themes with same id as provided themes should be ignored/skipped.
> UI: Avoid allowing to override provided themes

- plugins/obs-ffmpeg/obs-nvenc.c
Set last encoder error when a CUDA error occurs.
CUDA failures, e.g. due to the user setting an invalid device, are not currently set, so users just get generic error messages.
Set GPU index > 0 on a system with a single GPU:
> obs-ffmpeg: Set encoder error message for CUDA errors

- .github/actions/windows-signing/action.yaml
- .github/workflows/push.yaml
Updates bouf release to https://github.com/obsproject/bouf/releases/tag/v0.6.3-nsis-update
Note that this does not include any changes to bouf itself, just to the NSIS script and VC runtime checker/installer.
Don't want people to install OBS and not have it work.
Installer has been tested in the Windows Sandbox, CI has not been tested.
> CI: Update bouf release

- UI/multitrack-video-error.cpp
UI: Translate Multitrack Video error dialog buttons
The Yes and No standard buttons are not translated unless we manually set the translated text ourselves.
A user reported to us in OBS Studio 30.2.0-beta1 that these buttons were not translated. We already use this pattern elsewhere in the codebase.
https://github.com/obsproject/obs-studio/blob/0680b642e9cb85101971e8e03bbcd9b574cff6f7/UI/ui-validation.cpp#L47-L49
I've built this locally on Windows 11, but I could not seem to get this specific dialog to pop up.
> UI: Translate Multitrack Video error dialog buttons

- UI/multitrack-video-output.cpp
OBS crashes after canceling a stream attempt with the multitrack video output with incompatible settings
found by @notr1ch 
Repro steps:
1. Enable an incompatible setting in settings
2. Start stream, hit cancel on incompatible settings dialog
3. Disable incompatible setting in settings
4. Start stream -> crash
Followed repro steps and the crash no longer happens
> UI: Fix crash after canceling stream attempt with incompatible settings

- UI/win-update/updater/CMakeLists.txt
Trying to build in Debug fails due a default lib conflict:
> LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
Instead, we can set the updater to always use /MT instead of /MTd.
Want to be able to build OBS in Debug.
Tested locally on Windows 11 with VS2022 17.10.1.
> updater: Fix defaultlib conflict

- UI/obs-app-theming.cpp
Prevents a theme's dependency graph from containing itself or duplicates.
User reported out of memory crash on discord.
Verified regular OBS themes still load, unfortunately the user has not provided their broken one.
> UI: Prevent recursion in theme dependencies

- UI/obs-app-theming.cpp
Fixes `themeDir` string being too small for holding the config directory path.
c677bac875e6b3b6e4d3358aa8b38679ff4fcb1f changed the order here, but this also resulted in the string having whatever size was necessary for the install data path, rather than being large enough to fit a userdata path. To fix this, move the resize operaetion *after* the buit-in themes are searched, and also bump it to 1024 just to be sure.
This resulted in a crash due to a bug in os_get_path_internal() which will need to be fixed separately.
Booted up OBS without a crash.
> UI: Fix themeDir buffer being resized incorrectly

- UI/obs-app-theming.cpp
Always delete the `theme` pointer to avoid memory leaks.
While the `std::move` will (probably) result in the object's contained members being moved the copy constructed within the hash map, the original object should be deleted as it's no longer needed.
Verified with a debugger that everything works correctly and values get moved.
> UI: Use unique_ptr for theme objects

- UI/goliveapi-postdata.cpp
- UI/models/multitrack-video.hpp
- UI/multitrack-video-output.cpp
- UI/window-basic-auto-config.cpp
Updated GetClientConfiguration request to conform to new 2024-06-04 schema, with clearer separation of encoder `settings` and libobs encoder selection/configuration, some other movement of fields
The previous version of this schema mixed encoder settings and libobs encoder selection/configuration such as `"type": "jim_nvenc"` and `"bitrate": 6000` in the same json object, which is fine for encoders currently used in the Twitch Enhanced Broadcasting beta, but it's a potential compatibility hazard and also this separation makes it clearer which values should go to the encoder implementation vs libobs configuration
Twitch Enhanced Broadcasting beta, support for the new schema should be available for Twitch/Amazon IVS globally
> Update multitrack video schema to version 2024-06-04

- UI/data/themes/Yami_Classic.ovt
Commit b11d61c89f822502f8c543304a7c32081a44a2c7 (#8082) added padding-right to provide some minimal padding for this element. In the Composable Themes changes, this was seemingly accounted for in the Yami Base Theme (Yami.obt), but was missed in the Yami Classic Variant Theme (Yami_Classic.ovt).
Re-add the padding-right to restore the padding.
Want submenu indicators to have some padding.
Before:
After:
I'm not sure if there is a reason Yami.obt has two `QMenu::item` rules for padding, but I'll leave that mystery to others to solve.
https://github.com/obsproject/obs-studio/blob/77d31fa33fa25fc3b66f823776ddbd3c1b9b3c96/UI/data/themes/Yami.obt#L365-L371
https://github.com/obsproject/obs-studio/blob/77d31fa33fa25fc3b66f823776ddbd3c1b9b3c96/UI/data/themes/Yami_Classic.ovt#L112-L114
Tested …
> UI: Fix submenu arrow indicator position in menus

- UI/models/multitrack-video.hpp
- UI/multitrack-video-output.cpp
This currently depends on https://github.com/obsproject/obs-studio/pull/10845
Mark multitrack video config audio vod key as optional
VOD track is currently a Twitch specific feature (Amazon IVS doesn't support it, and probably no other services?), so marking the key as optional to simplify canonical config examples
Config overrides and Twitch internal API tests
> UI: Make audio_configurations.vod optional

- cmake/linux/defaults.cmake
- deps/obs-scripting/obs-scripting-lua.c
Try to fix the same issue as #10800 but more correctly, as the latter does not work on Linux system install.
This PR reverts #10800 and refactor how C paths are added to enable adding more than two paths.
Fix loading Lua script on Linux.
If you have a better approach (taking CMake 2 and 3 in mind), please feel free to supersede this PR.
Lua script loads with OBS install system-wide and relocatable.
> Fix loading Lua scripts on Linux through a refactor of how C path are added

- UI/window-basic-settings.cpp
Custom output doesn't currently allow specifying a config URL, so disable relevant settings for now
Enabling multitrack video when service is set to "Custom..." results in an error message, with nowhere to enter a custom URL
- Multitrack video groupbox is hidden when setting service to "Custom..."
- Enabled multitrack video with service set to Twitch, saved settings, switched to "Custom..." service and observed no "missing configuration url" error message when clicking "start stream"
> UI: Hide multitrack video options for custom output

- UI/win-update/updater/CMakeLists.txt
- deps/blake2/CMakeLists.txt
Adds a secondary blake2b target that is using the static MSVC runtime and uses that in the updater to allow for fully-static builds that do not have external runtime dependencies.
Want updater to run even if VC runtimes aren't installed/outdated.
Tested on Windows sandbox without installing any redistributables.
> Use static blake2b library for Windows updater

- UI/goliveapi-postdata.cpp
- UI/models/multitrack-video.hpp
- UI/multitrack-video-output.cpp
Two simple improvements:
1. Recent multitrack schema changes have modified the `obsConfigId` name to `clientConfigId`
2. To help inform GetClientCapabilities() API for eRTMP, add the `composition_gpu_index` to the postdata
Both of these are recent improvements resulting from the ongoing eRTMP/multitrack video implementation. They first is needed to align with the new schema. The second is needed to help in situation where multiple GPU's are present, for example an AMD-based system with an iGPU and dGPU.
Both have been and are currently being tested in the Enhanced Broadcasting closed beta.
> UI: Fixup configID name and add `composition_gpu_index`

- UI/auth-youtube.cpp
- UI/auth-youtube.hpp
- UI/lineedit-autoresize.cpp
Fixes mistakes I made in the past that the PVS-Studio analysis uncovered:
LineEditAutoResize didn't have its maxLength initialized in the constructor, leaving it to be a random value until set via setMaxLength. The one place where LineEditAutoResize was used immediately set this after calling the constructor, but if we use this anywhere else in the future it makes sense to have this initialized.
As it is meant to mostly behave like a QLineEdit, lets use the same default value of 32767.
Currently, the chat input elements (lineEdit, sendButton, and chatLayout) are initialized when the QCefWidget gets set. This is problematic behavior that only happened to work because we're a bit lucky: The chat is only enabled after a widget is set, and it's only set once. Without those conditions, the …
> UI: Initialize members in constructor

- UI/window-basic-main.cpp
This removes a redundant addAction call in the studio mode program context menu.
Discovered when looking around code
Opened program context menu to make sure the projector still worked as before
> UI: Remove redundant addAction call

- UI/data/themes/System.obt
- UI/data/themes/Yami.obt
- UI/data/themes/Yami_Classic.ovt
The Qt docs on icon-size say its Type is Length, which is further defined as, "A number followed by a measurement unit."
https://doc.qt.io/qt-6/stylesheet-reference.html#icon-size
https://doc.qt.io/qt-6/stylesheet-reference.html#length
This fixes the following logged Qt warning:
> QCssParser::sizeValue: Too many values provided
Want to use correct Qt syntax. Want less warnings in logs.
> UI: Fix icon-size values in theme files

- plugins/obs-outputs/null-output.c
Adds the multitrack flag to the null output to allow multiple audio or video tracks to be assigned to it
For various reasons, I need to artificially start up encoders (due to current limitations of grouped video encoders) even without a real output running, so this happens to be a useful tool to make that happen.
Code compiled
> obs-outputs: Add multitrack flag to null output

- deps/media-playback/media-playback/media.c
Checking the format of the AVCodecContext will result in using the format of the hardware-side frames, not the software-side frames. This uses the software frame parameters itself to initialize the swscale context.
When playing back a 4:4:4 file with NVDEC, the swscaler was being initialized with the AVCodecContext's hardware format instead of the host frame's format. This changes everything to use the host frame's parameters instead of the device frame's parameters.
Test file does not work without this, but works with this.
> deps/media-playback: Fix initialization of swscale with hw decode

- UI/multitrack-video-output.cpp
- UI/multitrack-video-output.hpp
- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs-video-gpu-encode.c
- libobs/obs-video.c
- libobs/obs.h
Modifies the encoder group API added previously to better follow the existing libobs API naming paradigms. This also produces much more readable code, and allows a few small additional benefits like removing encoders from an encoder group while it is active.
The API implemented in #10349 is not yet set in stone. The design of the methods is quite obscure, and the internal implementation is difficult to maintain. This code should fix that up by a lot.
Tested on Ubuntu 22.04 - had to hardcode the GPU info for testing, but stream started to a test channel with no issues with three tracks.
> libobs, UI: Encoder group fixups

- UI/window-basic-main.cpp
Changes default format to from fragmented to hybrid MP4 for Windows beta builds.
Should've been done earlier to get more people testing it, but alas.
Hasn't.
> UI: Set default container for beta builds to hybrid MP4

- UI/multitrack-video-output.cpp
The code was checking stream_key, but stream_key could be the user-supplied value (in_stream_key) or the server-supplied value (endpoint.authentication). The server-supplied value may lack the query parameters set in the user-supplied value. To ensure that user-specified query parameters (such as bandwidthtest) are passed along, parse the user-supplied key instead of the server-supplied key.
@derrod remarked:
> seems like bandwidth test mode is broken in beta3 with enhanced broadcast
We want Bandwidth Test Mode and other URL parameters to work with Multitrack Video (Enhanced Broadcasting).
Tested on Windows 10 with a GTX 1060.
> UI: Fix parsing of Multitrack Video stream key query parameters

- UI/multitrack-video-output.cpp
- UI/multitrack-video-output.hpp
- UI/window-basic-main-outputs.cpp
- UI/window-basic-main-outputs.hpp
Fixes using the configured audio track (for advanced mode) with the multitrack video output
The multitrack video output defaulted its (main) streaming audio track to track 0 (i.e. simple output settings), as opposed to taking advanced mode main audio track selection into account
Set up a scene with two audio sources, one set to output to all tracks, the other only to one track, and verified that switching advanced stream track setting was being honored
> UI: Use advanced mode audio track in multitrack video output

- .github/actions/windows-patches/action.yaml
- Updates bouf version to fix pandoc conversion using the wrong input format
- Updates creation of notes file to be in line with the Sparkle variant that does include the "subject" line as a header
Improve patch notes.
Hasn't.
> CI: Update Windows Patches Action

- UI/goliveapi-network.cpp
Allow usage of different multitrack config URLs between different stream attempts without restarting the program
This is an artifact from when development on multitrack video started, before services could supply their config URLs through services.json
This currently works when switching between Twitch and Amazon IVS due to some infrastructure being shared, but won't work if switching between Twitch/Amazon IVS and a completely different service
Switched between Twitch and Amazon IVS and verified that they use their own service URLs:
```
13:27:18.508: Go live URL: https://ingest.contribute.live-video.net/api/v3/GetClientConfiguration
[…]
13:27:38.260: Go live URL: https://ingest.twitch.tv/api/v3/GetClientConfiguration
```
> UI: Only cache multitrack config URL startup argument

- UI/goliveapi-postdata.cpp
- UI/models/multitrack-video.hpp
Communicate available codecs to configuration API for multitrack video output streams
The default value for this according to the current (still WIP) version of the Twitch/IVS integration guide is `['h264']`, so enabling HEVC or AV1 will require this at some point in the future
OBS built without HEVC support does not(?) support HEVC, even though e.g. hardware encoders may be capable of producing HEVC bitstreams; also, codecs may not be supported in case hardware encoders are disabled on startup or similar
Twitch Enhanced Broadcasting beta internal testing
> UI: Add supported codecs to GetClientConfiguration request

- UI/window-basic-settings.cpp
Disables multitrack video output settings for platforms other than windows
System info is not implemented for platforms other than windows, so the overall sentiment is/was to disable the multitrack video output for other platforms until system info is implemented (and ideally encoders for those other platforms are validated and/or encoder ladders/configs are available)
Verified that these settings are available on windows builds, but aren't available on MacOS builds
> UI: Disable multitrack video settings on non-win32 platforms

- .cirrus.yml
FreeBSD's package tool is pkg(8), and install is the command verb passed to it.
Fixes: fb4d65875e27 ("CI: Update Linux build scripts to use CMake presets")
Correct `pkg install` invocation in FreeBSD Cirrus-CI invocation.
FreeBSD CI failed, e.g. https://cirrus-ci.com/build/5788727706910720
Push to my fork and observe CI progress. 
The build currently fails but this change allows us to get further.
```
/tmp/cirrus-ci-build/plugins/linux-alsa/alsa-input.c:132:15: warning: implicit conversion loses integer precision: 'long long' to 'unsigned int' [-Wshorten-64-to-32]
data->rate = obs_data_get_int(settings, "rate");
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/cirrus-ci-build/plugins/linux-alsa/alsa-input.c:201:9: warning: implicit conversion loses integer precision: 'long long' to 'unsigned …
```
> CI: Fix FreeBSD package installation

- plugins/obs-ffmpeg/vaapi-utils.c
On some systems (eg. mine), VAAPI fails on vaInitialize. Valgrind was able to spot that the device was not being closed, and it appears to have been correct. This fixes a memory leak.
Using NVIDIA GPUs on Ubuntu 22.04 shouldn't cause memory leaks, even if small.
Tested on Ubuntu 22.04 that valgrind does not complain about this function when patched.
> obs-ffmpeg: Close VAAPI device on vaInitialize fail (memory leak fix)

- UI/window-basic-main-outputs.cpp
Fix a minor oversight from a recent commit. Audio track indexing in the UI is 1-based while underlying code uses 0-based indexing.
Tested with a local build against Twitch Enhanced Broadcasting.
> UI: Fix multitrack-video audio track index

- UI/cmake/os-freebsd.cmake
As with Linux we need to link Qt::DBus on FreeBSD now that there's a HighContrastEnabled implementation that makes use of it.
Fixes: 41ba8bdfdd02 ("UI: Add HighContrastEnabled implementation fo...")
Link Qt::DBus on FreeBSD
41ba8bdfdd02 added a HighContrastEnabled implementation which makes use of DBus, and updated UI/cmake/os-linux.cmake to link Qt:DBus. os-freebsd.cmake needs the same change.
Built-tested on my laptop.
> UI: Link Qt::DBus on FreeBSD

- plugins/obs-outputs/mp4-mux.c
- plugins/obs-outputs/mp4-output.c
- Fixes an oversight where zero-size chunks were being added to the `moov`, this is invalid, but no data loss occured
- Fixes DTS being used instead of PTS for file splitting, resulting in the first video packets not having a PTS of 0
Fixes #10903 
Made some recordings, verified things are now fine.
> Fix issues with file splitting in Hybrid MP4

- cmake/finders/FindFFmpeg.cmake
This adds `~` to the list of characters accepted as part of a correct version name for ffmpeg in `/cmake/finders/FindFFmpeg.cmake`.
Ffmpeg version `6.1-1build2~22.04` (from https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/ffmpeg6) failed to be found while setting up cmake, due to the `~` character in the version name. Tildes are frequent enough in linux version names that I feel their inclusion here is warranted.
Legacy cmake hasn't been changed as it correctly finds that ffmpeg version.
Verified that it was still correctly compiling, both with that ffmpeg and the distro one (which doesn't have a tilde), both in legacy and modern cmake.
> cmake: Fix FFmpeg version regex

- plugins/obs-outputs/mp4-mux.c
Skips writing a `trak` box for tracks that do not have any data (chunks) when writing the full moov.
This would crash if the encoder failed after starting, but before producing any packets, due to an assumption that there would be at least one chunk. Since there's no point in writing the box at all if there are no chunks (i.e. data) we can just skip the entire box.
Reported on the forums: https://obsproject.com/forum/threads/an-issue-where-an-error-occurs-with-certain-color-formats.176240/
Verified with setup outlined in the forum thread.
> obs-outputs: Skip trak box if track has no data

- plugins/obs-x264/obs-x264.c
Adds some more options to the x264 options blacklist.
Multipass encoding doesn't work in OBS so there's no point. Also a precaution to avoid potentially malicious configuration data delivered via the new multi-track auto-configuration API leading to arbitrary files being written on the users PC.
Hasn't.
> obs-x264: Ignore stats/qp file and multipass options

- UI/data/themes/Yami.obt
- UI/data/themes/Yami_Classic.ovt
- UI/forms/OBSBasicFilters.ui
Many of the changes to Yami had some unintended side effects to the Classic variant that were not properly accounted for before.
Trying to match the old Dark theme more closely
Before:
After:
Before:
After:
> UI: Adjust Yami (Classic) styling

- libobs/obs-encoder.c
Fixes a crash when the following steps occur:
- Encoder group created and then started with encoders, only the group owning encoder refs
- Encoder group destroy called: group has `destroy_on_stop` set without actual destroy
- Outputs holding encoders from stopping are stopped
- `remove_connection()` function destroys encoder group, releasing encoders and causing the currently processed encoder to be destroyed early
- parent scopes try to access destroyed encoder pointer and crash
This change moves some logic around to improve the release/destruct order of `obs_encoder_stop()` to fix the race above.
Note: Cases of encoder errors will not destruct the group if it has `destroy_on_stop` set, as the encoder is also not destroyed if it also is set to destroy on stop. This part of the code …
> libobs: Fix destroy_on_stop functionality of encoder groups

- libobs/media-io/video-frame.c
This was short by one line compared to copies executed in obs-source.c:copy_frame_data which resulted in copying garbage immediately after the frame and causing crashes typically.
Fixes crashes when media source loads files with odd resolutions.
Replication file no longer crashes obs or triggers asan.
> libobs: Fix plane heights for odd values

- plugins/obs-ffmpeg/obs-nvenc.c
Checks preferred format (if set) when configuring NVENC encoder.
This is used to prevent people from streaming in 444 (which isn't really supported) but wasn't checked in the native implementation as it didnt support 4:4:4 before.
Hasn't.
> obs-ffmpeg: Honor preferred format in native NVENC

- plugins/win-wasapi/win-wasapi.cpp
Removes some leftover debug logging messages that have outlived their usefulness.
These were originally added to help troubleshoot the application audio capture issues. Since it has been established that those are a Windows bug we can't detect or work around, we don't need these any longer.
They also keep annoying me because I run OBS with verbose logging for testing and especially the silent flag gets quite spammy.
N/A
> win-wasapi: Remove noisy and useless debug logging

- UI/forms/OBSBasicSettings.ui
This adds a defined fieldGrowthPolicy back to the Settings form.
Part of the cleanup in #10779 involved removing unnecessary properties as they were being set to their defaults.
Unfortunately, some of these defaults are not the same across operating systems. The default fieldGrowthPolicy on Windows is AllNonFixedFieldsGrow, so this removal was fine there. However on mac the default policy is FieldsStayAtSizeHint which causes the below issue:
Re-adding this property should fix this.
Built on Windows and observed everything is still fine. This will need to be checked on mac.
> UI: Add field growth policy to form layouts

- UI/cmake/legacy.cmake
https://github.com/obsproject/obs-studio/pull/10957 removed a few files from `CMakeLists.txt`, but did not remove them from `legacy.cmake` (see https://github.com/obsproject/obs-studio/pull/10957#issuecomment-2222635224)
Legacy CMake should still work
Untested
> UI: Fix `qt-helpers.{c,h}pp` not being removed from legacy.cmake

- libobs/obs.c
When `obs_reset_video` is called, it calls `obs_free_video` that sets the mix to NULL here: https://github.com/obsproject/obs-studio/blob/master/libobs/obs.c#L879
Don't like crashes when switching resolution
On windows by changing the resolution multiple times
> libobs: Fix crash when mix is NULL

- UI/data/themes/Yami.obt
- UI/source-tree.cpp
Fixes the spacing on source tree icons to be consistent and properly sized.
More consistent and proper spacing of all icons in source list entries. This had more averse effects on the Classic theme due to it inheriting from Yami now.
**Before**
**After**
**Before**
**After**
Tested on Windows
> UI: Fix source tree icon spacing

- UI/data/themes/Yami.obt
- UI/data/themes/Yami_Classic.ovt
Fixes background color of read-only line edit boxes.
**Before**
**After**
Fixes some poor contrast on Classic especially
Windows About dialog
> UI: Fix read-only QTextEdit background color

- UI/data/themes/Yami.obt
- UI/data/themes/Yami_Classic.ovt
Fixes some sizing of volume meters on Classic theme and the alignment of the kebab menu in horizontal layout.
Goal with the new audio meters was to make better use of space while doing our best to not use more space than before. 
Classic was using a bit more extra space than intended due to the larger slider width that Yami uses.
**Before**
**After**
Windows
> UI: Adjust sizing of Classic audio meter elements

- UI/window-basic-main.cpp
A variable `curScene` has a type `OBSSourceAutoRelease`.
It's pointer `&curScene` is passed to `obs_enum_scenes`.
Hence, the right type is `OBSSourceAutoRelease *`.
Though the first commit 496e599 fixed the bug, there was a complaint that the code is not easy to read. This PR additionally change them for a little better readability of the code.
- Use `static_cast` instead of `reintepret_cast` so that some type-checks will be performed at compile time.
- Instead of having a reference type of `OBSSourceAutoRelease`, put the parameter `source_ptr` with the cast to the left hand side of the assignment.
The code was introduced by #9944.
A crash was reported on the forum. https://obsproject.com/forum/attachments/crash-2024-07-18-09-59-21-txt.105470/
OS: Fedora 39
1. Created a new scene …
> UI: Fix cast of pointer type at invalid current scene setting on load

- plugins/obs-outputs/flv-output.c
- plugins/obs-outputs/rtmp-stream.c
- plugins/obs-outputs/rtmp-stream.h
Ensures that PTS/DTS for audio start at 0 if there by ensuring the DTS offset is based on the first packet that comes in, regardless of whether or not it's video (b-frame delay), or audio (priming sample delay).
Fixes #10998
This became necessary due to #10689 and #10690 which fix handling of audio priming samples with negative timestamps. Note that if users have a sufficiently large number of b-frames configured (1 is enough) this currently doesn't actually cause any issues.
Logged output packets and ensured the resulting FLV files are playable.
> obs-outputs: Set FLV DTS offset based on first audio or video packet

- libobs-opengl/gl-subsystem.c
These formats are used for texture encoding but the OpenGL texture encoding pipeline is not supported on Windows. This can also cause failure to initialize on Windows so it's better to disable the formats.
Some people who forced the OpenGL backend had failures.
Hopefully someone on windows can test this.
> libobs-opengl: Disable NV12/P010 on Windows

- plugins/aja/aja-common.cpp
- plugins/aja/aja-common.hpp
- plugins/aja/aja-output.cpp
- plugins/aja/aja-source.cpp
- plugins/aja/aja-vpid-data.cpp
- plugins/aja/aja-vpid-data.hpp
Allow selecting v210 pixel format in the AJA capture plugin.
Enable auto-detection of SDI v210 pixel format when capturing from an AJA SDI device.
This change adds the v210 format to the list of usable pixel formats in the AJA capture plugin. It also enables the auto-detection of the v210 format from the SDI signal. If the AJA device is configured for v210 format the appropriate OBS video format will be used in the format conversion pipeline (`VIDEO_FORMAT_V210`).
The recent addition of the v210 pixel format conversion shaders to OBS now allows the AJA capture plugin to enable v210 as an available pixel format.
NOTE: The v210 format is not yet available for use in the AJA Output plugin as the OBS FFMPEG format conversion pipeline does not support it. I tried forcing 10-bit YCbCr it in the …
> aja: Add v210 pixel format support to capture plugin

- UI/obs-app-theming.cpp
Use `std::optional` as a return value instead of a pointer, thus avoiding any manual memory management shenanigans.
Want to avoid errors like the one fixed by #10838 
This function could probably throw an exception to signal the error, but it currently doesn't and I don't want to make too many changes.
Verified themes still work.
> UI: Return std::optional from ParseThemeMeta

- UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp
The Linux implementation of the automatic scene switcher is X11-only and the design itself of the feature is incompatible with how Wayland works.
If a user happen to have the scene switcher active, OBS will crash while freeing the tool under Wayland.
The saved configuration should be kept since we no longer create the scene collection JSON from scratch, so there is normally no loss.
The scene switcher is no longer loaded on Wayland.
> frontend-tools: Avoid initializing the scene switcher on Wayland

- plugins/mac-virtualcam/src/camera-extension/CMakeLists.txt
macOS 15 shows this in the settings (or at least I think it's only from 15, haven't seen it earlier).
This is in System Settings -> Common [or whatever it's named in English] -> Login Objects and Extensions [or similar] -> Extensions.
Before/After (German, but the important part should be obvious):
<p>
</p>
Noticed this randomly when browsing through the login items settings.
If we don't set the display name macOS will fall back on the identifier which isn't great for users.
macOS 15, installed vcam and saw the new name in system settings.
> cmake: Set CFBundleDisplayName for camera extension

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Updating MasterStream.iR to OBS Studio's Ingest List
- JSON validation: Ensured that the JSON files were well-formed and adhered to the required format for OBS-Studio's ingest list.
- Copy JSON files to `%APPDATA%\obs-studio\plugin_config\rtmp-services`: Manually copy the JSON files to the appropriate location where OBS-Studio reads ingest settings.
- Checked settings: Verified that MasterStream.ir appears in the updated ingest list within OBS-Studio's settings.
- Connection testing: Attempted to connect to the servers provided by MasterStream.iR to ensure successful streaming functionality.
- According to [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines) 
- Updating feature (non-breaking change which adds functionality)
> rtmp-services: Update MasterStream.iR ingest

- plugins/obs-ffmpeg/obs-nvenc.c
- plugins/obs-ffmpeg/texture-amf.cpp
Aligns AV1 DTS and PTS, since AV1 doesn't use b-frame delay (similar to VP9/VP8). AV1 instead handles reordering of frames transparently by outputting frames that aren't displayed in the same encode call; e.g. with b-frames enabled the first time data is returned by these encoders there will generally be a keyframe in the output that can be displayed immediately, and the next time data is returned (with the next dts) will contain various frames that aren't displayed and one frame that is displayed
in the image below, frames with green underline are output in the same encode call:
consider also the ertmp (v1 and later) spec https://github.com/veovera/enhanced-rtmp/blob/6445c80106c418ebe6bb18602e1c86645b2c1778/docs/enhanced/enhanced-rtmp-v1.md where `PacketTypeCodedFrames` for AV1 does not …
> obs-ffmpeg: Disable NVENC/AMF DTS adjustment for AV1

- plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Updates the error message for an uninstalled/not-yet-approved camera system extension on macOS 15.
Apple moved where the user approves system extensions away from "Privacy & Security" to "General -> Login Items & Extensions". Don't want to provide outdated/incorrect directions. Beta users have already arrived confused in support about the old message.
Tested in an offline branch with a custom signing configuration to allow for the installation of system extensions, then relevant changes manually copied to this branch but not technically tested. Should be double checked.
> mac-virtualcam: Update NotInstalled error text for macOS 15

- UI/volume-control.cpp
This fixes a memory leak introduced in [1] where a new QColor is not balanced by a delete.
[1] UI: Update volume meter appearance
https://github.com/obsproject/obs-studio/commit/52ae5fc4bd518c67edd8ab94121ace05d9076892
The leak was found with VLD.
Leak is gone.
> UI: Fix leak with paint event of volume slider

- shared/media-playback/media-playback/decode.c
By not performing an unref on sw_frame before using it again, a memory "leak" was being created if the frame had side data. This removes a previously-added check that optionally unrefs sw_frame, and just does it every tick.
Noticed a memory leak the other day when playing back an HDR media file. It was quite extreme (ticking up by 1MB every few seconds).
Memory usage no longer goes up over time, other behaviors that I could test still work as expected.
> shared/media-playback: Unref sw_frame before reuse if using hardware decoding

- UI/window-basic-main.cpp
- plugins/obs-vst/VSTPlugin.cpp
- plugins/obs-vst/headers/EditorWidget.h
This PR removes legacy workaround for the `max` and `min` macros on the legacy Windows environment.
Now the SDK provides a switch `NOMINMAX` to avoid defining the macros so that we no longer require the workaround in the source code.
In another PR, someone follows the workaround as [discussed during the review](https://github.com/obsproject/obs-studio/pull/10997#discussion_r1688385006).
The existing code is an example of the coding style guideline for potential future contributors. The coding style should be consistent.
Confirmed the build flow shows no errors on Linux, macOS, and Windows.
Also checked the modification by eyes.
OS: Fedora 39
Tested the centering with selecting multiple scene items.
- (UI was …
> Remove min and max macro workaround

- UI/window-basic-main.cpp
- UI/window-dock.cpp
- docs/sphinx/reference-frontend-api.rst
Send a custom event to the OBSDock widget when the dock (from `obs_frontend_add_dock_by_id`) is closed, which allow plugin authors to potentially save resources while the dock is closed.
A QShowEvent is already sent to the widget when the dock is (re-)opened.
Motivation related to:
- https://github.com/obsproject/obs-browser/pull/431
Enabling a way closing browser from a plugin dock when the said dock is closed, since OBS Studio completely owns the access to the dock object.
So in a scenario like separating service integration, beside randomly guessing we can't know when close browsers to save resources.
Disabled the `closeBrowser()` call in BrowserDock `closeEvent()` impl and added the following to QCefWidgetInternal for testing purpose:
```cpp
bool QCefWidgetInternal::event(QEvent …
```
> UI,docs: Send a custom event to the dock widget when closing

- plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
Changes the error text associated with the macOS camera extension failing to find its system-level counterpart to provide a more helpful hint for resolving the issue.
This error seems to be the one most frequently encountered by Mac users launching the virtual camera and reasonably results in a lot of [user](https://github.com/obsproject/obs-studio/issues/10381) [confusion](https://github.com/obsproject/obs-studio/issues/9912).
On an update, OBS replaces its system extension even if nothing material has changed within it, in order to conform with signing requirements and keep versioning consistent.
For some users, macOS will fail to launch the process for the newly installed extension, despite installing it successfully and reporting that it is both `[activated  enabled]` in …
> mac-virtualcam: Improve 'not found' error message

- UI/window-basic-main.cpp
Ensure scene collection name and filename are set correctly before creating default scene.
Fixes #11037 
Locally based on reproduction steps outlines in #11037 
> UI: Ensure collection name is set before creating default scene

- plugins/obs-qsv11/common_utils_linux.cpp
During destruction of the QSV_Encoder_Internal the response may not be initialized and we can segfault. Add a check for this similar to the Windows implementation.
Crashing is no good.
Currently untested, just had a user report but I don't know what the situation is that this partial encoder start happens instead of failing earlier.
> obs-qsv11: Check for null response on free

- libobs/util/text-lookup.c
Feels weird to touch code that has been there for 11 years.. but I think there is actually a bug in here.
In case the string buffer that is to be parsed is just a single `#`, `lookup_gettoken()` reads across the text buffer's memory. After `lexer_getbasetoken()` is run `lex->offset` has been incremented to the next character already.
In case of a comment `#` token `lex->offset` gets incremented again and is assigned to `ch` which is then checked for a string termination or newline.
This essentially results in the first byte after `#` being skipped. This leads to a buffer violation if the the string to parse is being set to `#\0`:
Essentially we have
```C
char buffer[2];
buffer[0] = '#';
buffer[1] = '\0';
lex->offset = buffer;
```
```C
lexer_getbasetoken(); // lex->offset now points to …
```
> libobs/util: Fix potential memory error in text parser

- libobs/util/platform.c
Fixes a buffer overrun in `os_wcs_to_utf8()`
If the output buffer size is exactly the same as the length of the converted string, `out_len` would point to the first element past the end of the buffer, thus writing the terminating NULL character out of bounds.
To fix that, only pass in the size of the buffer minus terminating NULL into `wchar_to_utf8()`.
Locally.
> libobs: Fix buffer overrun in os_wcs_to_utf8()

- UI/window-basic-settings-a11y.cpp
- libobs-opengl/gl-shader.c
- libobs/callback/calldata.c
- libobs/graphics/half.h
- libobs/graphics/image-file.h
- libobs/obs-source-transition.c
- libobs/obs-source.c
- libobs/obs.c
- libobs/util/config-file.c
- plugins/linux-alsa/alsa-input.c
- plugins/linux-pipewire/camera-portal.c
- plugins/obs-ffmpeg/obs-ffmpeg-formats.h
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
- plugins/obs-filters/noise-suppress-filter.c
- plugins/obs-outputs/rtmp-stream.c
- plugins/obs-qsv11/common_utils_linux.cpp
- plugins/obs-qsv11/obs-qsv11.c
- plugins/obs-x264/obs-x264.c
- plugins/text-freetype2/text-freetype2.c
- plugins/text-freetype2/text-freetype2.h
- shared/obs-scripting/obs-scripting-lua.h
This PR removes unused functions that were not exported, ie. functions declared with `static` qualifier.
This PR also adds `inline` qualifier to `static` functions defined in header files.
This will affect 3rd party plugins but it should not make something wrong.
text-freetype2: Some functions were unnecessarily declared in a header file. They were moved to a proper location.
libobs/graphics/effect-parser.c: Exceptionally,
I didn't remove `ep_getparam`
as it is a variant of `ep_get*` functions so that it might be used in future.
libobs/obs-source.c: The removed function `set_eparami` was introduced at e7f754df97 but later removed by bdd8d6405.
Unused functions should not be left.
I want to enable `-Wunused-function` (but I gave up for now since qt automoc generates an unused function …
> Remove unused functions

- plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.h
- plugins/obs-ffmpeg/obs-ffmpeg-srt.h
Fixes #10504.
When starting an SRT stream in listener mode, if no connection is made by a client, the socket was not closed when exiting obs. This fixes the issue so that SRT is closed properly.
Bugs are bad.
Bug is fixed.
SRT in caller mode still works.
> obs-ffmpeg: Fix SRT listener bug

- libobs/obs-cocoa.m
Changes the macOS hotkey system event handler to always explicitly register the state of the modifier keys, regardless of the event type that was received.
It turns out that applications will not always receive a "flags changed" NSEvent from the system when a modifier key status is either pressed or let go of. These events seem particularly likely to be eaten by the system or other applications if the modifier is released, and that action results in the application losing focus (Command + Tab, for example), though it can also happen under some other circumstances. This means that OBS can often spuriously think that a modifier key is held when it is not, or, more rarely, that a modifier is not held when it is. This will in turn cause OBS's hotkey system to fail to properly register hotkey …
> libobs: Always explicitly check modifiers in macOS hotkey event handler

- UI/screenshot-obj.hpp
Makes sure header is only included once preventing code clashes.
Found when looking through code
Made sure OBS still compiled
> UI: Add pragma once to ScreenshotObj header

- UI/window-basic-main-profiles.cpp
- UI/window-basic-main-scene-collections.cpp
- UI/window-basic-main-screenshot.cpp
- UI/window-basic-main-transitions.cpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
This adds a function to OBSBasic to call on_event, so every time a event is called, the api variable doesn't have to be checked every time.
Code cleanup
Tested events with one of my plugins
> UI: Cleanup frontend event handling

- plugins/obs-outputs/mp4-output.c
Defers destruction of the `mp4_mux` object to the destroy queue.
Avoids a deadlock when the destruction attempts to free an encoder we're currently in the `send_packets` callback of.
Reported on Discord, deadlock figured out by R1CH.
Recorded and made sure stuff still works and there are no leaks.
> obs-outputs: Defer muxer destruction to task queue

- UI/platform-osx.mm
- UI/platform.hpp
- UI/window-basic-main.cpp
Removes the default device-based "Desktop Audio" source created on first run if the user is on macOS 13+.
Since adding macOS Screen Capture in macOS 13, the recommended way to capture audio on macOS is via that source (or alternately, the macOS Audio Capture source for strictly audio-only sources). The device-based audio source idiom is only relevant for older versions of macOS, or for some specialized workflows that require advanced audio routing via programs like Blackhole, VB-Cable, et. al.
The creation of this device-based source by default on new macOS 13+ systems very often leads to new user confusion. It doesn't provide any audio, and users often think that they need to configure it to get desktop audio, which can actually point them *away* from the newer, easier-to-use audio …
> UI: Don't create default desktop audio source on macOS 13+

- plugins/obs-nvenc/nvenc-opts-parser.c
`APPLY_INT_OPT` usage gated behind 12.2 are lacking of the format parameter.
Allow master with CMake 3.0 to build with obs-nvenc.
With the PR I can build master with nvcodec 12.2.
> obs-nvenc: Fix building with nvcodec 12.2

- shared/happy-eyeballs/happy-eyeballs.c
[b7f89de](https://github.com/obsproject/obs-studio/pull/11110/commits/b7f89dedf0e79b42e62a8c89f2da719ba55445af) reserves enough space in the candidates array to avoid reallocation during happy eyeballs execution. The code should ideally not rely on the darray being fixed in the first place, but a better refactor can come later.
[c699dce](https://github.com/obsproject/obs-studio/pull/11110/commits/c699dce3e9b5efbd32e23108f675c2b43bf1047c) fixes an issue on Windows where `RTMP_Connect` would block while calling `happy_eyeballs_destroy`, causing the entire RTMP connection to time out when there was a happy eyeballs candidate still in progress.
[241429c](https://github.com/obsproject/obs-studio/pull/11110/commits/241429c927a328449943fb39874b4343c2321c8b) adds a hint flag to `getaddrinfo` that …
> happy-eyeballs: Various bug fixes and improvements

- .github/actions/windows-signing/action.yaml
- .github/actions/windows-signing/config.toml
- .github/workflows/push.yaml
Remove step copying legacy game capture DLLs for dual-signing.
Per https://obsproject.com/kb/capture-hook-certificate-update we want to switch exclusively to the new cert starting with 31.0.
Hasn't.
> CI: Remove game capture dual-signing

- buildspec.json
* deps.ffmpeg: Enable Media Foundation
* deps.ffmpeg: Update nv-codec to 12.2.72.0
* deps.macos: Use correct CMake vars for libajantv2
* deps.macos: Add SIMD Everywhere to macOS deps
* deps.windows: Add SIMD Everywhere to Windows deps
* deps.windows: Update VPL to v2.12.0
Unblock:
* #10902
* #11060
* #10961
I have not done full tests with OBS Studio against these deps.
> CI: Update deps to 2024-08-08 release

- plugins/obs-ffmpeg/obs-ffmpeg.c
Somehow VAAPI was under NVENC, so disabled if no NVENC.
Fix use of VAAPI when NVENC is not enabled.
VAAPI was disabled if NVENC was disabled, and they are unrelated.
Tested on my NixOS 24.05.
> obs-ffmpeg: Fix VAAPI/NVENC ifdefs

- UI/obs-app-theming.cpp
Changes this so it will no longer upset asan.
The original was written with trying to avoid memory copies in mind, but it was dumb. Make it less dumb.
Compiles and works.
- Code cleanup (non-breaking change which makes code smaller or more readable) -->
> UI: Fixup ResolveVariable to be less jank

- plugins/obs-nvenc/nvenc-compat.c
- plugins/obs-nvenc/nvenc.c
- Remove non-functional legacy lossless mode
- Omit irrelevant settings (e.g. CQP in CBR mode)
- Set rate control string to "lossless" in lossless mode
Lossless mode issue discovered in testing, logging change suggested on Discord.
Recorded with different settings, made sure it works now.
> obs-nvenc: Improve settings logging / legacy compatibility

- UI/window-basic-settings.cpp
- libobs/obs-encoder.c
- plugins/obs-nvenc/nvenc-compat.c
- Adds a warning to the log if an encoder is deprecated
- Suffixes deprecated encoders in the settings combobox
- Removes hardcoded untranslated suffix from NVENC compat encoders
Want to make it more obvious that things might stop working or be removed.
Selected deprecated encoder, took screenshot.
> UI/libobs: Add warning/suffix if using a deprecated encoder

- libobs/util/windows/window-helpers.c
- plugins/win-capture/data/compatibility.json
- plugins/win-capture/window-capture.c
Besides UWP applications, which means WinUI 2 applications that cannot be captured by BitBlt, WinUI 3 applications also cannot be captured by BitBlt. This commit adds a check for WinUI 3 applications.
Just as we cannot use Bitblt to capture the screen of UWP (WinUI 2) applications, WinUI 3 applications also have this problem. However, we have not made any special judgment on WinUI 3 at present.
- Install WinUI 3 Gallery and WinUI 2 Gallery, which is, WinUI 3 applications and UWP (WinUI 2) applications.
- Use Window Capture to capture these two windows using Automatic. 
- Specify the capture method to BitBlt and check the hint.
> Both windows are captured by WGC correctly, and the hints are displayed correctly when selecting BitBlt.
Testing environment:
- i9-11900H
- RTX 3060 Laptop
- …
> libobs: Also determine WinUI 3 Window

- shared/properties-view/properties-view.cpp
List widgets are currently used as playlists in source properties, but only contain the file paths and no other identifying information.
This can lead to files being added multiple times, so when changes to list order occurs, plugins cannot uniquely identify which duplicate item was actually changed (because they're only identified by the path).
By adding a UUID to the user data role of a list item, an additional unique information is added that allows plugins to de-duplicate list items.
Initially wrote https://github.com/obsproject/obs-studio/pull/8051 and @PatTheMav suggested that the obs_data should be left unmodified and this is one of their suggestions. I merely added a way for this to be backwards-compatible with existing editable lists (by generating UUIDs for items without uuids …
> UI: Add UUID to file-based list widgets

- libobs/obs-encoder.c
Add NULL check to encoder deprecation warning
If an encoder ID no longer exists `ei` will be `NULL`.
Locally.
> libobs: Add NULL check to encoder deprecation warning

- plugins/obs-nvenc/nvenc-helpers.c
Fix nvenc availability check always returning true
This always returned true, probably due to an oversight during testing.
Locally.
> obs-nvenc: Fix nvenc availability check always returning true

- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs-video-gpu-encode.c
Switch from the old `destroy_on_stop` mechanism to proper reference counting for encoders.
Fixes the same deadlock as #11111 but more holistically rather than just working around it.
Encoders originally were implemented without reference counting in 6da26a3a1c31d211082c5477ea95d985f5281c94 which was later added in ba0b8eb0e1173c045ba91df4c077a8ffddd050c4 without removing the error-prone `destroy_on_stop` mechanism that would result in encoders potentially being destroyed before all references to them are released.
Streaming (multitrack) + recording, no more deadlocks. No leaks.
- Tweak (non-breaking change to improve existing functionality) -->
> libobs: Move encoders to being fully reference counted

- plugins/CMakeLists.txt
Removes the `WITH_MESSAGE` parameter from `add_obs_plugin(obs-qsv11)`.
https://github.com/obsproject/obs-studio/commit/7d578c5cfb334d41aaa81cd00c1f1df5fbe8688e added `WITH_MESSAGE`.
This annoyed me because on macOS the module is obviously unavailable whatever you do, and the `add_custom_target` call leaves this confusing empty top-level target in the generated project:
I don't see any value in `WITH_MESSAGE` here.
Reran cmake, target gone.
> cmake: Remove WITH_MESSAGE from obs-qsv11

- .github/scripts/.build.zsh
- .github/workflows/analyze-project.yaml
Adds clang-analyze output to the project for macOS builds.
Current code analysis is based on Windows with PVS Studio, which will miss potential issues discovered by clang and/or by macOS-specific sub-projects.
This PR uses Xcode's "Analyze" build mode to generate sarif files and uses Microsoft's `sarif-multitool` to merge the files into a single report.
Tested on separate fork and checked that security reports where successfully generated.
> CI: Add clang-analyze analytics for macOS builds

- plugins/obs-nvenc/nvenc-properties.c
Only show UHQ tune on supported GPUs.
The UHQ tune is only supported on Turing or later, on earlier GPUs this would simply fail, so hide it if unsupported.
Verified it still shows up on an Ada GPU, don't have any GPUs predating Turing on hand.
> obs-nvenc: Only show UHQ tune on supported GPUs

- UI/window-basic-main-outputs.cpp
- UI/window-basic-settings.cpp
Fixes simple mode with new NVENC.
New NVENC uses `preset` instead of `preset2`, this broke some assumptions the UI had made in simple mode.
Verified it works.
> UI: Only use preset2 in simple mode for legacy/FFmpeg NVENC

- docs/sphinx/reference-encoders.rst
- libobs/obs-encoder.c
- libobs/obs-encoder.h
- libobs/obs-module.c
Adds a new encoder cap which tells libobs that rather than scaling video frames in software, the encoder is capable of scaling them via its own (presumably more efficient) means.
An encoder may implement this cap by comparing the VOI of its assigned `video_t` and the results of `obs_encoder_get_width/height()`. If the width/height values differ, then the encoder is being asked by libobs to self-scale, and the resolution in VOI will be the raw frame size, with the `...get_width/height()` being the intended output resolution of the encoder.
It is important to note that GPU rescaling mode will take priority over self-scaling. If GPU rescaling is enabled, the encoder will never be asked to self-scale.
This is useful for discrete hardware encoders, where they might have fixed-function video …
> libobs: Add `OBS_ENCODER_CAP_SCALING` cap

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Added rtmp service for the [NFHS Network](https://www.nfhsnetwork.com/).
We modified the `package.json` and `services.json` files inside of the `rtmp-services` plugin to include the primary RTMP endpoint for the NFHS Network. The changes to the plugin also include our supported resolutions and maximum frame rate.
Our primary motivation for this was to simplify the process of getting our customers streaming to our service and prevent potential user errors when re-typing or pasting the RTMP URL.
- JSON Validation
- Built using cmake and compiled using XCode on a 2021 Macbook Pro (Apple M1 Pro) running MacOS Sonoma 14.4.1
- Performed a test stream to our service using the new NFHS Network service dropdown option
- Verified RTMP stream displayed on the service
- New feature (non-breaking …
> rtmp-services: Add NFHS Network

- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
Force UpdateEditMenu on UI Thread
UpdateEditMenu should always be called on the UI Thread
broken since #10725
Fixes #11116
On windows by removing and adding filters via not UI
> UI: Force UpdateEditMenu on UI Thread

- UI/platform-osx.mm
- UI/platform.hpp
- UI/window-basic-main.cpp
Inlines the macOS 13 check for the default device.
When I closed #11127 I noticed that there is potential to clean this up.
macOS 15
New OBS Settings folder, new device does not get created.
> UI: Inline macOS 13 check

- UI/volume-control.cpp
Use [`std::clamp`](https://en.cppreference.com/w/cpp/algorithm/clamp), which is introduced in C++17.
The commit eb3d9963a0 and df94b02075 added `set(CMAKE_CXX_STANDARD 17)`. Now we can use C++17.
I want to avoid reinventing the wheel.
Tested on Fedora 39.
CI will test for all the platforms.
> UI: Use std::clamp instead of macro

- plugins/mac-capture/mac-sck-audio-capture.m
- plugins/mac-capture/mac-sck-common.h
- plugins/mac-capture/mac-sck-video-capture.m
Removes the `disp_finished` event.
This event is only used within destroy_[audio]_screen_stream, and does
not appear to be necessary there. stopCaptureWithCompletionHandler holds
a reference to the SCStream object by itself (and the other objects
being held aren't used afterwards anyways), so there should be no harm
in releasing everything immediately without blocking.
Tested selecting, changing and removing all the capture types. Still works as before.
> mac-capture: Remove disp_finished event

- UI/data/themes/Yami.obt
Fix warning color
Want difference between warning and error, like in OBS 30.1
On windows 64
> UI: Fix warning color

- UI/data/locale/en-US.ini
- UI/forms/OBSBasic.ui
- UI/window-basic-main-scene-collections.cpp
- UI/window-basic-main.cpp
- UI/window-basic-main.hpp
- docs/sphinx/reference-scenes.rst
- libobs/obs-scene.c
- libobs/obs-scene.h
- libobs/obs.h
> [!IMPORTANT]
> Scenes are saved in a backwards-compatible way, stuff might not work correctly and mess up your collection.
> Make backups of your scene collections before playing around with this!
This change enables the canvas resolution to be changed while maintaining the relative positioning and sizing of items in a scene collection.
**Video demo (outdated):**
https://github.com/obsproject/obs-studio/assets/3123295/fe3ad89f-d7f7-4b44-b1b1-514a5ffbf693
Implementation notes:
- `(0.0, 0.0)` is the center of the canvas 
- Positions are stored as offsets relative to the center
- The height of the canvas has the range `[-1.0f, 1.0f]` while the width side is `[-x, x]` where `x = 1.0f * aspect ratio`
- Items without bounding boxes retain the canvas resolution used during their original …
> libobs: Change scene items to using relative coordinates

- libobs/CMakeLists.txt
- libobs/cmake/os-windows.cmake
A recent obs-deps change removed all non-essential x86 deps. This caused the x86 subproject(s) on Windows to fail to configure due to being unable to find x86 dependencies that do not exist.
Want to be able to build against new obs-deps.
Tested a build on Windows 11.
> libobs: Fix Windows x86 CMake when using reduced obs-deps package

- shared/properties-view/CMakeLists.txt
- shared/properties-view/properties-view.cpp
- shared/qt/icon-label/CMakeLists.txt
- shared/qt/icon-label/icon-label.hpp
Adds an IconLabel widget (originally made as part of the [scene collection manager](https://github.com/obsproject/obs-studio/pull/8446)) which displays icons in High DPI.
Then changes the icon rendering for the properties view "question mark" icon
from Qt label HTML to use the IconLabel widget.
Before/After (From the Media Source, rows in between removed for demonstration):
<p>
</p>
The icon looked ugly.
macOS 15
See the screenshots above.
> shared: Make properties view "help" icon High DPI

- buildspec.json
Update CEF from 103/5060 to 127/6533.
Many thanks to @reitowo , @WizardCM , @tytan652 , @pkviet , @PatTheMav , @kkartaltepe , @Lain-B , and everyone else who pitched in to answer questions, test, help, and build the packages so that we can update CEF.
Built on Windows 11 and ran through some tests with browser sources (FishGL, HTML5Test, CSS3Test, etc.) and browser panels (Twitch Authentication).
More testing is welcome.
> CI: Update CEF from 103/5060 to 127/6533

- build-aux/com.obsproject.Studio.json
- build-aux/modules/99-cef.json
Flatpak counterpart of #11213 
Reminder that https://github.com/obsproject/obs-browser/pull/450 (or an alternative) is required to avoid the shutdown crash with browser docks.
The CEF module is also modified to:
- Use the pre-built wrapper included in the tarball
- Preserve debug symbols inside its binaries
- The copy done later by OBS Studio build-system will be split from its debug symbols
Update CEF on the Flatpak and preserve CEF debug symbols which will be put in the `.Debug` Flatpak extension.
Build with CEF and debug symbols are generated and compressed.
> build-aux: Update Flatpak CEF from 103/5060 to 127/6533

- shared/qt/slider-ignorewheel/CMakeLists.txt
- shared/qt/slider-ignorewheel/slider-ignorewheel.hpp
- shared/qt/wrappers/qt-wrappers.cpp
Some libobs headers are included in the shared qt module although they are not used.
Let's remove them.
In the case of slider-ignorewheel, this completely removes the need for the linkage against libobs.
Noticed this while working on something else.
macOS 15.
Still compiles.
> shared/qt: Remove unused libobs includes/linkage

- cmake/macos/helpers.cmake
Excludes the `.DS_Store` file from being included in the resources directory of a target in `target_install_resources`.
Noticed that the `.DS_Store` files get added to the resources directory in Xcode, which it probably shouldn't.
Re-ran cmake. File(s) no longer get included.
> cmake: Exclude macOS .DS_Store from resources

- UI/auth-oauth.cpp
- UI/window-basic-main.cpp
Removes the remaining instances of the `SIGNAL()`/`SLOT()` macro and replaces them with the new Qt connection style.
These were previously left in as there used to be linker issues on Windows using the old cmake path (as `QCefWidget` is defined in `obs-browser`), meaning this didn't build.
Now the old cmake path doesn't exist there anymore, so we can replace this.
Tested on my forks' CI that this now compiles and links on all operating systems.
> UI: Replace remaining SIGNAL/SLOT macros

- UI/forms/OBSBasicSettings.ui
Fix this warning:
```
AutoUic: /run/build/obs/UI/forms/OBSBasicSettings.ui: Warning: The name 'label_10' (QLabel) is already in use, defaulting to 'label_101'.
```
Note: I took the closest available number.
Likely caused by two merged adding `"label_10"` to the same UI file.
Less warning is better…
No more CMake warning while building.
> UI: Fix Qt UIC warning in settings UI

- libobs/obs-scene.c
Fixes the initial position of a newly created scene item not being the top left corner when in relative mode.
In relative mode (0, 0) is the center of the screen, so in order to maintain previous behaviour we need to convert the value here.
Created a colour source, confirmed now in top left.
> libobs: Always set initial scene item pos to top-left corner

- plugins/win-capture/data/locale/en-US.ini
- plugins/win-capture/duplicator-monitor-capture.c
- plugins/win-capture/window-capture.c
Fixes an issue where window and display capture on Windows would capture the first window or display on first creation. This is actually due to a design flaw in the properties view, but we need to fix it in the sources themselves to display the appropriate text to the user anyway.
It's not good to capture something without explicitly selecting it.
Tested locally, seems fine.
> Fix display/window capture on Windows capturing on creation

- buildspec.json
CI: Update deps to 2024-09-05 release
* deps.windows: Disable x86 build slice for dependencies
* deps.qt: Disable x86 build slice for Qt6
* CI: Remove Windows x86 slices for Qt6 and FFmpeg builds
* deps.ffmpeg: Disable Windows x86 build slice for FFmpeg dependencies
* deps.ffmpeg: Update libvpx to v1.14.1
* deps.ffmpeg: Update SVT-AV1 to 2.2.1
* deps.ffmpeg: Update aom to 3.9.1
* deps.ffmpeg: Update AMF to 1.4.34
* deps.ffmpeg: Update FFmpeg to 7.0.2
* deps.macos: Update LuaJIT to 2.1 f725e44cda
* deps.macos: Update FreeType to 2.13.3
* deps.macos: Update Asio to 1.31.0
* deps.macos: Update qrcodegen-cmake to v1.8.0-cmake3
* deps.macos: Update Sparkle to 2.6.4
* deps.qt: Update Qt to 6.7.2 for macOS
* deps.qt: Update Qt to 6.7.2 for Windows
* deps.windows: Update FreeType …
> CI: Update deps to 2024-09-05 release

- plugins/win-capture/graphics-hook/dxgi-capture.cpp
Trivial fix to avoid a segfault in `update_mismatch_count` when attempting to call `data.free` after it has been set to `nullptr`.
One possibility is that `update_mismatch_count` is called 16 times in a row without a match, then `data.free` is called and it is set to `nullptr`. If `update_mismatch_count` is called another 16 times in a row without a match, then `data.free` will be null this time and it will segfault.
Another possibility is that `update_mismatch_count` is called after `SwapChainDestructed`. I say this because the client experiencing the crashes recently upgraded OBS from a much older version that did not crash and 395ab0fbf54ee2692d6fe60036088580247d868c seems to be the only change to `dxgi-capture.cpp` in that time.
In any case, all calls to `data.free` should be guarded. …
> win-capture: Fix segfault when calling data.free()

- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/QSV_Encoder_Internal.h
CBR improvement for new Intel platform, the peak bitrate is now down to 120% on average from 200% while keeping same bitrate and quality. 
This PR will not build until VPL version has been updated: https://github.com/obsproject/obs-deps/pull/254.
This change has been made to decrease the CBR spike on new Intel platforms.
new Intel platforms on various driver versions
- Performance enhancement (non-breaking change which improves efficiency) 
- [ x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x] My code is not on the master branch.
- [ x] The code has been tested.
- [ x] All commit messages are …
> obs-qsv11: Fix CBR Spike

- plugins/nv-filters/CMakeLists.txt
- plugins/obs-filters/CMakeLists.txt
- plugins/obs-filters/cmake/nvidia.cmake
If speex and rnnoise are disabled but nvafx is enabled, the noise reduction filter still needs to be built. This fixes the issue.
Enable building of nvafx even if speex & rnnoise are disabled.
This is useful for minimal test builds.
Bug discovered by @RytoEX ; fix found by @RytoEX 
obs builds even when  speex & rnnoise are disabled, while nvafx is enabled.
> obs-filters: Fix building of noise reduction

- UI/window-basic-auto-config.cpp
When using the Auto-Configuration Wizard with the Twitch service, testing for Enhanced Broadcasting would always run, even if deselected. Add a conditional check to only run the test if selected.
The AutoConfig wizard would force Twitch Enhanced Broadcasting to be enabled even if users did not want it. 
Fixes #11177
Tested locally with my Twitch account, with several iterations of enabling/disabling the "Test Enhanced Broadcasting" option in the wizard.
> UI: Fix multitrack video autoconfig option

- plugins/obs-nvenc/nvenc-helpers.c
At some point NVIDIA started using NV_ENC_ERR_INCOMPATIBLE_CLIENT_KEY instead of NV_ENC_ERR_OUT_OF_MEMORY to signal that the session limit has been exceeded.
Want to provide users with more meaningful error message.
Verified this error code occurs when session limit is hit, and that the error message with this PR is accurate.
> obs-nvenc: Support new error code for too many sessions

- plugins/obs-nvenc/nvenc.c
Adds a check to see if the value for the `device` setting is actually set.
When using the redirect from the legacy ID this would not be set and `0` would be treated as an override resulting in the non-texture fallback being enabled. By checking if the value is explicitly set we avoid that.
Locally with a quick test recording.
> obs-nvenc: Check if device index in settings object is actually set

- plugins/obs-nvenc/nvenc-helpers.c
Define `success` = `false` at the beginning of the function `static bool nvenc_check()`.
I found a warning below as [commented](https://github.com/obsproject/obs-studio/pull/11153#issuecomment-2343562257) in the PR 11153.
```
[ 46%] Building C object plugins/obs-nvenc/CMakeFiles/obs-nvenc.dir/nvenc-helpers.c.o
obs-studio/plugins/obs-nvenc/nvenc-helpers.c: In function ‘nvenc_check’:
obs-studio/plugins/obs-nvenc/nvenc-helpers.c:385:16: warning: ‘success’ may be used uninitialized [-Wmaybe-uninitialized]
385 |         return success;
|                ^~~~~~~
obs-studio/plugins/obs-nvenc/nvenc-helpers.c:347:14: note: ‘success’ was declared here
347 |         bool success = config_get_bool(config, "general", "nvenc_supported");
|              ^~~~~~~
```
OS: Fedora 39 (GCC 13.3.1)
I ran these …
> obs-nvenc: Fix reading uninitialized variable

- plugins/obs-webrtc/whip-output.cpp
Description
The following change was added to fix a bug which stopped `stun` being supported; it previously worked as expected. Specific single line modification and addition is as follows:
Token at the beginning of a string has an OR added to allow `<stun:` in addition to `<turn:`
How Has This Been Tested?
It returns functionality that existed previously and is simplistic string token matching
Types of changes
Bug fix, feature restoral
Checklist:
My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
I have read the [contributing document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
My code is not on the master branch.
The code has NOT been directly tested.
All commit messages are properly formatted and …
> obs-webrtc: Fix bug in whip-output.cpp to support stun or turn

- libobs-opengl/gl-subsystem.c
Disclaimer: This is graphics code, do not consider that I know what I am doing.
- ~~Enable gs_shared_texture_available on all platforms, only Linux was missing which mainly use DMA-BUF.~~
- ~~obs-browser relies on it to enable hardware accel~~
- Relax OpenGL texture format copy check
- It allows to copy `_UNORM` to their non-`_UNORM` counterpart since CEF sends texture with SRGB.
Enable https://github.com/tytan652/obs-browser/tree/linux_hwaccel_2 to work without doing weird stuff like https://github.com/tytan652/obs-browser/commit/1ca22d27067df11c448aaa9b08ded40710dc80c6 or other in https://github.com/tytan652/obs-browser/tree/linux_hwaccel
Just built and ran OBS with this PR and my second hwaccel browser branch and their is no more SRGB gamma issues.
- Tweak (non-breaking change to …
> GS/GL Shenannigans (Prep for obs-browser hwaccel on Linux ?)

- libobs/obs-cocoa.m
Cleans up the source code by sorting functions by topic and also removes macros for hotkey implementation, removing the need to disable compiler warnings.
Key codes and descriptions are now contained in arrays which either use the OBS key code or the macOS key code as lookup keys with all necessary context information directly associated with the key.
The implementation also uses the zero-initialization rule for arrays of structs in such a way that the struct's "is_valid" boolean is "false" by default so that only values explicitly initialized with a key are ever "valid".
Make code more readable and easier to maintain by removing use of macros and also sorting functions into logical units (source code `MARK`s also make it easier to navigate through code in Xcode).
Tested on macOS 14.
- …
> libobs: Update macOS platform implementation

- plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Resolves a small issue related to custom OBS virtual camera builds.
When starting virtual camera output on macOS, a UUID string comparison is used to locate the CMIO extension associated with OBS. This UUID string, as stored in the app bundle, can be either lowercase or uppercase depending on the parameters originally provided to CMake. The variant returned from CMIO internals is always uppercase. ~~Since OBS is using a string comparison to compare the UUIDs, this PR changes the comparison to be case insensitive.~~ This PR changes the comparison to use `CFUUID`s created from the strings and `CFEqual` to check equality, rendering any questions of case sensitivity moot.
When debugging the Mac virtual camera with a separate code signing identity from OBS, it is necessary to generate new …
> mac-virtualcam: Compare camera UUIDs using CFUUID

- CMakePresets.json
- cmake/common/ccache.cmake
Disables Ccache by default for local builds and enables it by default for CI builds instead.
For all the benefits Ccache brings, it can also introduce unexpected issues, particularly when lazier source file matching is used (e.g. for Xcode builds due to the use of modules and other ObjC features).
Using Ccache by default also breaks the use of address sanitizer (asan) and other runtime analytics features that can be enabled via Xcode schemas (as the compiler cannot be identified if a `COMPILER_LAUNCHER` shell script is used).
Thus disabling Ccache by default makes these (primarily local) workflows easier, but is still available for developers who have to opt-in explicitly (features that introduce possible unknown side-effects should be opt-in to begin with).
Existing projects are not …
> cmake: Disable CCache for local builds and enable by default for CI

- docs/sphinx/reference-encoders.rst
- libobs/obs-encoder.c
- libobs/obs.h
- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
Add obs_encoder_get_mixer_index
Have a way to find out what audio track is used for an audio encoder
On windows 11 by logging the audio track .
> libobs: Add obs_encoder_get_mixer_index

- plugins/obs-qsv11/QSV_Encoder.h
- plugins/obs-qsv11/QSV_Encoder_Internal.cpp
- plugins/obs-qsv11/QSV_Encoder_Internal.h
- plugins/obs-qsv11/obs-qsv-test/obs-qsv-test.cpp
This change adds AV1 SCC for new Intel platforms to improve quality. 
When tested, target usage target usage 4 had an average of a 20% quality gain (up to 40%) and target usage 6 had an average of a 25% quality gain (up to 40%).
This change added quality improvements for future Intel platforms. 
new Intel platforms on various driver versions
- [x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x ] My code is not on the master branch.
- [x ] The code has been tested.
- [x ] All commit messages are properly formatted and commits …
> obs-qsv11: Add AV1 Screen Content Coding

- build-aux/com.obsproject.Studio.json
Fixes a warning when compiling/building the obs flatpak
fallback-x11 only enables x11 if the application doesn't use wayland, and instead falls back to x11. If the app uses wayland then the x11 socket is never made available I am assuming.
removes a warning
Testing is unnecessary because it just uses the same behavior but removes a build time warning
Bug fix
> build-aux: Use fallback-x11 instead of x11

- UI/cmake/feature-whatsnew.cmake
- UI/cmake/os-windows.cmake
- cmake/finders/FindMbedTLS.cmake
- plugins/obs-outputs/CMakeLists.txt
Update MbedTLS find module and usage in CMake files to prepare codebase for later update to CMake version 3.6.0 and beyond.
MbedTLS changed a lot of internals with their LTS version 3.6.0, which are incompatible with the find module currently shipped with OBS Studio.
The solution requires several changes to be applied at once:
* Rename the generated target name to MbedTLS::mbedtls to match the name used by MbedTLS' own CMake package
* Update find module to use the updated target name(s)
* Set CMAKE_FIND_PACKAGE_PREFER_CONFIG to TRUE before trying to find MbedTLS to ensure that CMake package files are used with priority (Those are shipped only with MbedTLS 3.6.0 in obs-deps).
* A deprecation warning is emitted if the find module is used with MbedTLS 3.6.0 available
Tested on macOS with …
> cmake: Update use of MbedTLS to support versions 3.6.0 and beyond

- CMakePresets.json
Before 6c590805e88755f70ad62ffbb217ad8ace09563b, builds on Windows would automatically select a Windows SDK using CMake's rules:
https://cmake.org/cmake/help/v3.25/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION.html https://cmake.org/cmake/help/v3.30/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION.html https://cmake.org/cmake/help/v3.30/policy/CMP0149.html
This meant that CI Windows builds would end up using SDK 10.0.20348.0 because that matched the runner's OS version exactly. Locally, if a Windows SDK version that exactly matched the host system version was not installed, CMake would select the latest Windows SDK available. This caused some observed differences in build success between CI and local builds if a newer SDK was used locally.
The Windows runners have the 10.0.22621.0 …
> CI: Use Windows 11 SDK 10.0.22621.0

- UI/api-interface.cpp
Fixes method names for certain scene collection and frontend methods exposed via the frontend API that had been renamed during review phase of #11055.
Restores functionality of the corresponding frontend API methods.
> [!NOTE]
>
> Plugins which invoke public slot functions on the UI thread directly instead of using the frontend API will face the same issue. Luckily this should not result in crashes or other issues at runtime as Qt will just ignore the call and at worst post a log message about a non-existing method being invoked.
Tested with a simple plugin that invokes the corresponding frontend API functions.
> UI: Fix outdated scene collection and profile method names

- libobs/obs-scene.c
Makes sure that a scene item that gets removed is in the "not selected" state, no matter whether it was selected before. This causes the "item_deselect" signal to be sent if the item is selected while being removed.
I think that semantically it makes sense that a selected item has the `item_deselect` signal sent if it is being removed, as it is selected before and not selected after (because it doesn't exist anymore); I'd consider current behavior to be a bug (or at least not work as one might expect).
While making a plugin, I noticed that if you listen to the select/deselect signals, an item that gets removed via the UI will not have the deselect signal when being removed.
This can lead to weird states if you count selections/deselections to track how many items are selected (and you …
> libobs: Deselect scene item before removing

- .github/actions/check-changes/action.yaml
- .github/actions/flatpak-builder-lint/action.yaml
- .github/actions/generate-docs/action.yaml
- .github/actions/qt-xml-validator/action.yaml
- .github/actions/sparkle-appcast/action.yaml
- .github/actions/sparkle-appcast/appcast_adjust.xslt
- .github/actions/sparkle-appcast/appcast_legacy.xslt
- .github/scripts/.build.zsh
- .github/scripts/.package.zsh
- .github/scripts/utils.zsh/check_ubuntu
- .github/scripts/utils.zsh/setup_ubuntu
- .github/workflows/build-project.yaml
- .github/workflows/push.yaml
- .github/workflows/scheduled.yaml
- buildspec.json
Updates the following aspects of the current build scripts and GitHub Actions workflows and actions:
* Build scripts on Linux require Ubuntu 24.04 and x86_64 - any preliminary/experimental support for aarch64 was removed
* Qt6 is used by Ubuntu builds by defaults, associated build spec settings are thus superfluous and have been removed
* Build scripts on macOS and Linux require Zsh 5.9
* macOS builds use Xcode 15.4 by default
* Experimental support for CCache on Windows was removed
* `qt-xml-validator` now uses the `check-changes` action to check for and get a list of changed UI files
* Several complex shell script snippets have been documented in-line
* XSLT stylesheets used by `sparkle-appcast` action have been updated with doc comments to explain how they work (XSLT and XPATH are …
> CI: Minor update of build scripts and GitHub Actions workflows and actions

- UI/obs-app.cpp
- UI/window-basic-settings.cpp
Aligns the config type of several OS-specific settings across their implementations in the OBSApp class.
Ensure selection of renderer on Windows and VSync settings on macOS are correctly retained and restored from settings.
Tested on macOS 15.
> UI: Fix config class mismatch in OBSApp class

- .github/actions/setup-macos-codesigning/action.yaml
The `provisioning` and `notarization` steps that set the `haveProvisioningProfile` and `haveNotarizationUser` outputs respectively only run if `haveCodesignIdent` has evaluated to true in the prior `codesign` step.
This means that if `haveCodesignIdent` is false, the other two outputs are left unset, evaluating their `value` expressions (and as such the output of the action) to empty instead of false. To mitigate that, we can just add a `|| 'false'` to set the value to false in case it isn't set.
Strictly speaking it's unnecessary for `haveCodesignIdent` as that always runs but to me it makes sense just to set it to all.
I found this issue in the [equivalent action](https://github.com/obsproject/obs-plugintemplate/blob/e3688b7491c52ef6e37ac59daa93e7cf4d9e2b28/.github/actions/setup-macos-co …
> CI: Set default values for have* outputs in macos-codesigning action

- UI/volume-control.cpp
~~This commit partially reverts 60a45d3aa3 to avoid a runtime assertion failure on Windows that checks the low value of std::clamp is not greater than the high value.~~
Based on the comment, another fix was implemented; `displayPeak[channelNr]` is always clipped at 0.
To clarify the necessity to consider the priority, I didn't revert to use the `CLAMP` macro but use an if-else-if statement.
I modified to use `std::clamp` in the PR #11167.
However, @exeldro [reported it caused a runtime error](https://github.com/obsproject/obs-studio/pull/11167#issuecomment-2314419470) on Windows.
I confirmed the low value (`currentPeak[channelNr]`) gets greater than the high value (`0.f`) by applying a gain filter with a large gain.
OS Fedora 39
Applied a gain filter to a audio source with a sine wave. …
> UI: Fix low value of std::clamp gets greater than high value

- cmake/finders/FindLuajit.cmake
- cmake/macos/defaults.cmake
Adds the default installation location of Homebrew packages to list of ignored paths for CMake to resolve dependencies on macOS.
macOS builds should only use dependencies built via the obs-deps build scripts. Default variants of the same dependencies are not compatible with our app packaging requirements and thus will create issues when creating the app bundle.
This is specifically an issue when MbedTLS is installed via Homebrew which ships a CMake package config by default and is picked up by our code ever since we switched to prefer CMake packages.
Tested on macOS 15 with MbedTLS installed via Homebrew and observed that CMake will only pick up MbedTLS provided by obs-deps.
> cmake: Disable discovery of Homebrew libraries for dependencies

- UI/cmake/os-linux.cmake
- UI/obs-app.cpp
- cmake/linux/defaults.cmake
Fixes broken support for portable mode on Linux and Windows.
Windows and Linux allow the storage of configuration files relative to the binary location, which is enabled by default on Windows and has to be explicitly enabled on Linux.
This was originally conflated with the `LINUX_PORTABLE` build setting which also allowed the application itself to be run from non-default locations on a Linux system.
This change reintroduces the functionality behind the `ENABLE_PORTABLE_CONFIG` build setting on Linux.
It also adds necessary code to make this setting compatible with the recently introduced relocatable settings code changes:
When portable mode is enabled, user configuration, scene collections, and profiles are stored in the config directory created for portable mode.
Tested on Windows 11 …
> UI: Fix missing support for portable configuration files

- libobs/obs-scene.c
Fixes crop values for new nested scene sources being incorrect due to `last_width`/`last_height` being 0 when first created, which causes a divide-by-zero error and invalid cropping values to be calculated. 
Reported on Discord.
Created new sceneitem, no longer broken.
> libobs: Fix crop values for new nested scene sources being incorrect

- libobs/obs-scene.c
Disables logging of transform matrices by default.
Want less noisy debug builds unless required.
N/A
> libobs: Disable transform debug logging by default

- libobs/util/source-profiler.c
fix source profiling inactive sources
When filters are disabled the tick takes time, but the cpu and gpu render do not, so I would like to see that in `profiler_result_t`.
Before it would show the last status before it was disabled, now the cpu and gpu go to 0 in 5 seconds
With https://github.com/exeldro/obs-source-profiler by enabling and disabling a filter.
> libobs: Fix source profiling inactive sources

- libobs/media-io/audio-io.c
The variable `input.conversion.allow_clipping` was left uninitialized. This could result in randomly sending unclamped audio to the output handlers that did not request the conversion.
To avoid the same initialized variables again when adding a new variable to the structure, I initialized `audio` at the declaration so that all other variables are initialized to zero.
The member variable `allow_clipping` was introduced by the commit dcee4fc61a54 in #8289.
In the function `audio_output_connect`, which allows the parameter `conversion` to be null to indicate no conversion is requested,
the variable `allow_clipping` was not initialized when the conversion was not requested.
I'm writing a plugin that calls `audio_output_connect` through `obs_add_raw_audio_callback` like …
> libobs: Fix sending unclamped audio to output handler

- UI/volume-control.cpp
Removed the condition `if (int(magnitude) != 0)`, which is not there in `VolumeMeter::paintVMeter`.
When the clipping happens on an audio source, the error color (red by default) is not displayed on the horizontal volume meter.
There are two rendering functions `VolumeMeter::paintHMeter` and `VolumeMeter::paintVMeter`. These functions should be identical except for the coordinate calculation.
OS: Fedora 39
1. Prepare an audio source that outputs continuous tone.
2. Apply a gain filter
3. Decrease and increase the gain and check the volume meter.
| master | this PR |
| ---- | ---- |
| https://github.com/user-attachments/assets/9b674f5c-ee40-4d4c-88cd-3250c7623adc | https://github.com/user-attachments/assets/1766d7c6-ce97-4d2c-8c7d-10df4f58a1e0 |
- Bug fix (non-breaking change which fixes …
> UI: Fix error color at clipping is not displayed on horizontal meter

- UI/window-basic-main.cpp
Fixes possible crash when a new scene collection is created with a name that consists "unsafe" characters.
Scene collection names that are not considered "safe" by OBS Studio get a changed JSON file name with incompatible characters replaced.
The refactored scene collection implementation uses the `Load` function to either activate an existing scene collection or create a new one if it does not exist.
The `Load` function however overwrote the scene collection name set in the profile with its own variant based off the "safe" file name, which created a mismatch with the code that created the collection data model.
As the `Load` function is only called by `ActivateSceneCollection` (which itself already sets the name and filename for the collection), removal of this superfluous code in the …
> UI: Fix crash when creating scene collections with "unsafe" names

- UI/window-basic-source-select.cpp
- docs/sphinx/reference-scenes.rst
- libobs/obs.h
`obs_scene_sceneitem_from_source` is problematic because there can be multiple items of the same source in a scene, which the function doesn't account for. In such a case, it would return the first item it finds, which often might not be what a developer expects. 
It was originally added for the undo/redo-operation of "Add New Source" where the UI guarantees that the item is unique, but for a general case it's not suitable.
In the one UI use, instead of first creating the scene item and then finding it again , we can just remember the scene item in AddNew after we create it, similar to the source itself.
The existence of the method was discussed on Discord, and I think it shouldn't exist.
macOS 15
Added and undo/redo'd (redid?) new sources without problems.
- Tweak (non-breaking change to …
> libobs,UI: Replace and deprecate obs_scene_sceneitem_from_source

- UI/window-basic-main.cpp
The InfoIncrement key in the application config everywhere else. This mismatch caused the "What's New" menu entry to stop functioning.
The recent settings refactor broke this by mismatching the configs.
Found while investigating #11321.
Used the "Help" -> "What's New" menu.
Doesn't work without this PR, does with it.
Made sure that in the code base now the app config is used everywhere for this.
> UI: Fix What's New increment settings mismatch

- libobs/obs-output.c
Prevents the reconnect thread from being started up again after the output has been put into the "stopping" state and reconnects have been requested to stop. Also sets the reconnect state to `false` to prevent `obs_output_active()` from returning `true` which would prevent the multitrack output's stop handler from continuing.
Should fix the crash reported on the EB Discord related to the output teardown not actually running due to the output still being in a reconnected state: https://discord.com/channels/1171528364000018442/1282992330604941365
This is a race condition that requires the right timing to trigger. It would also leave the `reconnect_thread` in a non-detached state while never being joined.
Technically it should also be possible to remove [this …
> libobs: Do not attempt to reconnect if stop event is set

- UI/multitrack-video-output.cpp
Sets the preferred format for multitrack encoders.
Twitch doesn't handle 444 or HDR content properly, and currently stream encoders are already always forced to NV12 (if not HDR): https://github.com/obsproject/obs-studio/blob/4dd3cf675834bbbd786a638f4427766021dd976d/UI/window-basic-main-outputs.cpp#L1873-L1883
This has been an issue for people that record 444 locally but still stream to Twitch (or other websites for that matter).
See TEB Discord thread: https://discord.com/channels/1171528364000018442/1286889511225393182
Streamed to Twitch, confirmed output is now 420.
> UI: Set NV12 as preferred format for multitrack video encoders

- libobs/obs-cocoa.m
Per the [documentation of `CFStringGetCString`](https://developer.apple.com/documentation/corefoundation/1542721-cfstringgetcstring?language=objc), the buffer provided must be large enough not just for the string itself, but also for a NUL terminator. This space for the `NUL` terminator is currently ignored, and we just get lucky that CFStringGetMaximumSizeForEncoding often dramatically overestimates the space required. However, it is possible to actually hit the maximum with the string itself (for example by using strings that contain exclusively Chinese characters such as "我"), in which case the conversion fails. Adding the extra byte for the `NUL` terminator fixes this.
Investigated a [clang-analyzer warning](https://github.com/obsproject/obs-studio/security/code-scanning/663) on a …
> libobs: Assure large enough buffer in dstr_from_cfstring

- shared/bpm/bpm-internal.h
- shared/bpm/bpm.c
While testing BPM in the Twitch Enhanced Broadcasting beta build an issue was uncovered where OBS Studio will crash due to an uninitialized mutex in the new BPM code. This crash only happens if: 
- The stream delay feature is enabled
- The user starts streaming and stops the stream before it ever started streaming
With the official OBS Studio, the stream delay feature is not compatible with enhanced broadcasting and will be disabled if the streamer attempts to use stream delay, so there is currently no chance of running into this issue. However, once stream delay compatibility with enhanced broadcasting is upstreamed, the crash will occur in the case specified above, so best to eliminate it ahead of time.
The fix is very simple. Simply ensure the mutex is initialized once from either …
> shared/bpm: Fixed crash when using Stream Delay

- UI/auth-youtube.cpp
- UI/auth-youtube.hpp
- UI/window-dock-youtube-app.cpp
- UI/window-dock-youtube-app.hpp
Unlock the full feature set of the YouTube Chat dock in OBS by removing custom scripting/CSS logic. Enable the signed-in experience for live streaming content creators while also sharing login credentials with the YouTube Control panel dock.
This will allow OBS users to utilize features _already_ supported in the YouTube Chat plugin, such as
* creating polls
* managing Q&A sessions
* a rich emoji set in the input panel
* emoji fountains
* moderation tools
and many more. These features are available to users who are logged-in to YouTube Chat and/or the YouTube Control panel.
Built OBS locally on Linux workstation, verified existing functionality for YouTube Chat continues to work in signed-out state. Signing-in to YouTube hides the native Qt input panel in favour of the YouTube native …
> UI: Enable first-party YouTube Chat features in OBS

- cmake/linux/helpers.cmake
We missed a spot when freezing the SOVERSION to 30 after we flipped to 31 causing builds to break.
Also use a variable which maybe makes it slightly easier to avoid in the future.
Believe it or not, sometimes we do want to build on linux.
Replicated CI issue and Works on my machine (tm).
> cmake: Use fixed SOVERSION everywhere

- libobs/util/dstr.h
- plugins/linux-capture/xcomposite-input.c
This fixes a null pointer dereference that can happen with `strcmp()` if the window class/name of a window being captured is null (which *can* happen and is *meant* to be handled, even if rare).
Trying not to blow a blood vessel over yet another null pointer dereference in the code for this capture method. There are waay too many pointers being manipulated in this file.
> linux-capture: Fix xcomposite null pointer derefence

- plugins/linux-pipewire/pipewire.c
Avoid trying to allocate 0 byte if 0 happens to be the number of format.
#11181
Added a Screen Capture source, no visible issue.
> linux-pipewire: Avoid trying to allocate 0 byte

- libobs/util/bmem.c
As outlined in c5965c8605ec8e20ae8a21caf723da94aec62049 (#6721), `bmalloc(0)` is pretty much always a mistake, possibly hiding other bugs. It's been two years since that commit introduced a warning announcing that this will crash in a future version of OBS, let's make that happen.
cc @notr1ch 
People are breaking stuff (see other PRs), let's break everything at once.
This gives plugin developers who might (unknowingly) do this the opportunity to fix it.
*If* there are places where we're doing it in OBS itself, this is a great (and certainly loud) way to find out.
macOS 15
Launched OBS and played around, did not observe crashes.
Manually added a `malloc(0)` call, had OBS crash as expected.
> libobs/util: Crash on bmalloc(0)

- plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
The things that happen to get this deadlock:
- the io thread reads `shutdown_requested` as false
- the main thread sets `shutdown_requested` to true
- the main thread gets the `data_mutex`
- the main thread signals `new_data_available_event`
- the main thread releases the `data_mutex`
- the main thread waits for the io thread to exit
- the io thread gets the `data_mutex`
- the io thread resets `new_data_available_event` because `chunk_used < 65536 && !shutting_down`
- the io thread releases the `data_mutex`
- the io thread waits for `new_data_available_event`
with the changes the `new_data_available_event` cannot be send from the main thread between the reading of `shutdown_requested` the getting of the  `data_mutex` in the io thread
Got a memory dump Fenrir from a muxer that was stuck. …
> obs-ffmpeg: Fix deadlock on shutting down muxer

- UI/window-basic-main-profiles.cpp
Fixes implicit conversion from `std::string` to `std::filesystem::path`, which is incorrect on Windows due to lack of UTF-8 to UTF-16 conversion.
Fixes #11363
Created a profile with one of the names provided by the reporter.
> UI: Explicitly convert profile config path via u8path

- shared/opts-parser/opts-parser.c
In `obs_parse_options`, ensure `input_option_count` is not zero so that `bmalloc` is not called with 0.
When `input_option_count` is zero, goto `failure` so that the behavior of `obs_parse_options(" ")` is same as `obs_parse_options("")`.
When passing just a space to `obs_parse_options`, the number of input options becomes 0. In this case, `bmalloc` was called with size 0, and OBS crashed.
After the PR #11181, `bmalloc` will crash when the given size is 0.
I found this bug while I was looking at each `bmalloc` usage by `git grep` such as
```sh
git grep '\<b[mz]alloc\>.* \* '
```
by assuming the multiplication-operator is there if a variable is passed to `bmalloc`.
1. Configure to use x264 encoder and put ` ` (just a space) to the setting `x264opts`.
(I think it could be a possible …
> shared/opts-parser: Fix crash when no options were given to the parser

- .github/actions/windows-patches/action.yaml
Fixes patch download failing due to a change in how rclone parses command line variables. Anything containing a comma (`,`) now needs to be quoted.
This appeared to be a regression but according to https://github.com/rclone/rclone/issues/8063#issuecomment-2344718575 this is a deliberate (breaking) change. Unfortunately not documented (e.g. in the changelog).
Ran rclone 1.68 locally with new format.
> CI: Fix rclone env var formatting in Windows Patches action

- UI/data/themes/Yami_Light.ovt
Fixes a few QSS selectors in Yami Light.
Amends cb026964b00c366943a3c16dfb1511eafc24c035 ([#11226](https://github.com/obsproject/obs-studio/pull/11226)).
Found when investigating an issue raised in the beta-testing on Discord.
Before/After:
<p>
</p>
`git grep`'ed for `=true]` to make sure this type selector wasn't used anywhere else.
> UI/themes: Fix selectors in Yami Light

- UI/obs-app.cpp
- UI/obs-app.hpp
- UI/window-basic-main-profiles.cpp
- UI/window-basic-main-scene-collections.cpp
- UI/window-basic-main.cpp
Fixes several issues introduced by the updated profile and scene collection management:
* After deleting a scene collection or profile, the last remaining item is automatically activated instead of the first item (regression)
* After deleting a scene collection, its associated backup copy is also deleted (regression)
* Launching OBS with a `--profile` or `--collection` command line argument crashes the app (bug)
First two bugs were oversights during development of the update, last one has an architectural reason: As profile and scene collections are now managed by `OBSBasic` (and not by code directly interfacing with the file system), an instance of the class needs to exist to do so.
The command line arguments were handled at an early point on `OBSApp`'s initialisation, at which point …
> UI: Fix crash and UX issues with updated profile and scene collection management

- libobs/CMakeLists.txt
Add source profiler to public headers
Want to use it in a plugin
-
> libobs: Add source profiler to public headers

- UI/data/themes/System.obt
- UI/data/themes/Yami.obt
- UI/data/themes/Yami_Acri.ovt
- UI/data/themes/Yami_Classic.ovt
- UI/data/themes/Yami_Light.ovt
- UI/data/themes/Yami_Rachni.ovt
cb026964b00c366943a3c16dfb1511eafc24c035 changed most instances of MuteCheckBox as a selector for the button that mutes/unmutes a source in the mixer to indicator-mute, but left a few instances of the old selector, especially in variant themes while the base theme got changed. This lead to competing selections where apparently indicator-mute won which meant that the variant themes wouldn't override the base. Changing all instances of MuteCheckBox to to indicator-mute fixes this and hopefully prevents future uses of MuteCheckBox as a selector anywhere.
Noticed when working on https://github.com/obsproject/obs-studio/pull/11376.
Before/After for light theme:
<p>
</p>
Also checked that in e.g. Rachni, the color when the button is being pressed is now dim-rachni-red instead of Yami-gray.
- …
> UI/themes: Consistently select indicator-mute instead of MuteCheckBox

- UI/cmake/feature-macos-update.cmake
- UI/cmake/feature-whatsnew.cmake
- UI/cmake/os-windows.cmake
- UI/win-update/updater/CMakeLists.txt
We know this is the minimum version that we require, so we can just fail during configure if somehow an older version is found.
See:
* https://github.com/obsproject/obs-browser/pull/452
Although we no longer support Ubuntu 22.04 for building or running OBS Studio, we can make the dependency requirement here more obvious at configure time.
Either "UI: " or "cmake: " seemed like acceptable commit prefixes, but I went with UI for now.
Tested locally on Windows.
> UI: Set minimum version for nlohmann_json to 3.11

- UI/window-basic-main.cpp
Change the way a new profile is initialised during OBS initialization to a void mistakenly resetting services that have not been added to program state yet.
SetupNewProfile is used to create new profiles when OBS is already running, which requires resetting program state for the new profile.
This function cannot be used to create a new profile as a fallback for either a non-existing profile or for a fresh installation of OBS Studio because by the point this is called from `OBSBasic::OBSInit`, the runtime modules are not loaded yet and as such no services exist.
Activating the new profile without a profile reset fixes this issue as the reset will be done explicitly by `OBSBasic::OBSInit` later.
Tested by launching OBS Studio without an existing settings directory on macOS 15.
- Bug fix …
> UI: Fix initialization bug when launching without existing profile

- plugins/obs-outputs/flv-mux.c
Add casts in flv-mux.c to fix build with latest Clang. Obtained from https://github.com/freebsd/freebsd-ports/commit/f0e9df3448bd5a567b9447dc711d0a5f0341a327.
Clang 19 has become more strict about mixing different enum types, which resulted in an error building multimedia/obs-studio on FreeBSD:
/wrkdirs/usr/ports/multimedia/obs-studio/work/obs-studio-30.2.3/plugins/obs-outputs/flv-mux.c:659:37: error: bitwise operation between different enumeration types ('enum multitrack_type_t' and 'enum packet_type_t') [-Werror,-Wenum-enum-conversion]
Build tested on FreeBSD
> obs-outputs: Add cast to fix build with Clang 19

- libobs/obs-scene.c
- Adds missing relative<->absolute conversions when calculating transform when ungrouping items
- Fixes scale reference for items in groups being wrong, resulting in them being larger than expected
Fixes #11366
In hindsight, perhaps I should've kept the matrices in relative scale as well and then pushed an opposite transformation matrix before rendering. That is some cleanup I can perhaps do for 31.1.
Used collection provided in #11366 for debugging.
> libobs: Fix scaling and positioning issues with groups in relative mode

- .cirrus.yml
Switch to FreeBSD 14.1 as the most recent production version.
FreeBSD 13.2 is now past EOL.
Local Cirrus-CI run here: https://cirrus-ci.com/build/4952213842296832
> CI: Bump FreeBSD image to 14.1

- CONTRIBUTING.rst
Reflect apparent change to use 120 column lines in the Coding Guidelines in CONTRIBUTING.rst
Commit a1fbf1015f40 updated .clang-format and existing code for 120 columns, so change Coding Guidelines to match.
(I recently had a change to submit, and manually wrapped it at 80 columns. I was surprised to find clang-format unwrapping it to put it on one line.)
n/a
> CONTRIBUTING.rst: Update Coding Guidelines for 120 column limit

- UI/forms/OBSBasic.ui
- UI/forms/OBSBasicFilters.ui
- UI/frontend-plugins/frontend-tools/forms/auto-scene-switcher.ui
- UI/frontend-plugins/frontend-tools/forms/scripts.ui
- shared/properties-view/properties-view.cpp
#11226 updated widgets to use the special `class` custom property on widgets for their QSS styling. These instances of the `toolButton` property were missed.
This also removes the toolButton styling from the Scripts and Advanced Scene Switcher window in a separate commit as they are more appropriate without it.
Fix up missed issues for consistency.
👁
> UI: Update toolButton styling property to use class

- UI/cmake/os-linux.cmake
- UI/obs-app.cpp
- libobs/cmake/os-linux.cmake
- libobs/util/platform-nix.c
We should use XDG config paths on FreeBSD. This could be done by adding `USE_XDG` in the os-freebsd.cmake files, but this would leave the `#else` case in `#ifdef USE_XDG` unused. It is also currently broken. Thus, just remove the `#else` case and `USE_XDG` references.
Also reintroduce `move_to_xdg` from ba02e065fe91 to migrate FreeBSD installs to XDG paths on upgrade.
OBS currently fails to start if built without `USE_XDG`.
We should be following XDG config paths on FreeBSD anyway.
OBS starts correctly on FreeBSD with these patches applied. I ran `rm -rf ~/.obs-studio/ ~/.config/obs-studio/`, started again, and confirmed that default config is created under ~/.config/obs-studio. Removed the directories again, created config under ~/.obs-studio, started again, and confirmed that the config …
> Use XDG config paths on FreeBSD

- UI/window-basic-main-profiles.cpp
- UI/window-basic-main-scene-collections.cpp
Replicates the sorting of profiles and scene collection menu items provided by the Windows file system APIs with the new system.
The old method to update the profile menu iterated over the directory entries of the profile directory in the order provided by the operating system.
The system calls used for this explicitly state that the order of items is "undefined" but seems to have followed a case-insensitive alphabetical order on Windows, an order which users have come to expect.
The new code uses a std::map to store discovered profiles and scene collections, which is ordered by key and with std::string used for keys this means a lexicographical sorting of keys which is case-sensitive.
To restore the old behavior, profiles and scene collections need to be added to their respective menus …
> UI: Update order of profiles and scene collections in their menus

- plugins/obs-nvenc/nvenc.c
Forces the number of b-frames to 4 if it is below 4.
Users running into non-descriptive errors when trying to use UHQ tune without setting the correct number of b-frames.
Hasn't.
> obs-nvenc: Force at least 4 b-frames when using UHQ tune

- build-aux/com.obsproject.Studio.json
This cause issues in Flatpak IDE like GNOME Builder.
I cause this issue, I fix it.
Anyway, all original CEF files (including debug files) are cleaned up at the end.
Avoid issues is better than gaining time.
Run the Flatpak in GNOME Builder and then re-run it.
- Without PR: Ninja will complain about missing CEF target
- With PR: GNOME Builder will ran OBS Studio
> build-aux: Remove CEF stripping workaround

- .cirrus.yml
Install www/libdatachannel and leave ENABLE_WEBRTC at the default of ON.
I'm not sure why the Cirrus-CI job previously set `-DENABLE_WEBRTC:BOOL=OFF` on FreeBSD; installing the `libdatachannel` package is all that's needed to leave this at the default of ON.
Build-tested via Cirrus-CI job: https://cirrus-ci.com/task/5539831604838400
> CI: Enable WebRTC on FreeBSD

- UI/auth-twitch.cpp
Log Twitch API message if 403 is encountered.
An increasing number of users report 403 issues from Twitch, since we have a specific handler they do not get shown the actual API error, which may not be particularly helpful.
In order to aid support and debugging log the actual error we get to be able to
1) Provide more information to Twitch to figure out why those users are getting errors
2) Figure out if we can forward Twitch error messages directly again (Twitch has stated they want to improve the messages to be clearer)
Manually set status to `403` and verified JSON response gets logged.
> UI: Log Twitch 403 error bodies

- cmake/linux/helpers.cmake
This fixes how the AUTHORS file is installed.
Magic function variable should die… `self` and `this` were enough…
About window on Linux should work now.
> cmake: Fix target_add_resource ARGN support on Linux

- UI/cmake/ui-windows.cmake
- UI/window-basic-main.cpp
- UI/window-whats-new.cpp
- UI/window-whats-new.hpp
CEF crashes on shutdown if any browser window remains open during the shutdown flow. 
This particular crash flow is reproducible 100% of the time on Linux with What's New and our modern CEF version.
The previous implementation of the What's New dialog correctly deleted all the Qt widgets, but the CEF internal event flow would only call the "preparing to close" function, and never the "window safely closed" function. All attempts to fix this with minimal changes went nowhere.
Moving the existing What's New code (practically unchanged) to a custom QDialog solves the problem entirely, and is more consistent with other uses (namely OAuth).
I don't believe this issue is new to Chromium 127 (therefore OBS 32.0), the crash just occurs late enough in the shutdown chain that user data (eg. scene …
> UI: Split out Whats New dialog to fix shutdown crash on Linux

- UI/cmake/os-freebsd.cmake
Copy the desktop file and icon routine from `os-linux.cmake` so that FreeBSD gets these installed too.
FreeBSD can generally run the same desktop environments that use these files as Linux. Without these files, icons and application launchers do not populate in these desktops. These files were previously installed prior to the CMake refactor here.
Built as usual on FreeBSD-CURRENT.
> cmake: Install desktop files and icons on FreeBSD

- plugins/linux-pipewire/camera-portal.c
- plugins/linux-pipewire/pipewire.c
Fixes memory leaks in the linux-pipewire plugin.
1. `pw_node_info`s copied [here](https://github.com/obsproject/obs-studio/blob/edd7a387a4f278e004a5a40b1dc72916cc061421/plugins/linux-pipewire/camera-portal.c#L847) were never freed
2. `pw_registry` proxy created [here](https://github.com/obsproject/obs-studio/blob/edd7a387a4f278e004a5a40b1dc72916cc061421/plugins/linux-pipewire/pipewire.c#L1028) was never freed
Memory leaks are bad.
Tried camera capture, unplugged and plugged in a camera several times, tried screen capturing, destroyed the sources. Everything works.
LeakSanitizer does not report the leaks anymore.
> linux-pipewire: Fix memory leaks

- UI/window-basic-main.cpp
Restore dispatch of frontend events that have not been dispatched due to prior refactor.
The frontend API events "OBS_FRONTEND_EVENT_SCENE_CHANGED" and "OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED" are not dispatched if disableSaving has a value `> 0`. Prior code decremented disableSaving to `0` globally (regardless of whether saving was necessary, which is only the case if a new collection is created as a fallback for a missing scene collection).
Thus the updated code exhibits different event dispatch behavior then old code which some plugins might have relied on. To avoid introducing new behavior, explicitly create the environment to allow the dispatch to take place and remove/refactor the events in a later version.
Checked frontend dispatch taking place with existing scene collection, …
> UI: Restore frontend API events being dispatched during initialization

- UI/win-dll-blocklist.c
Per https://www.hanselman.com/blog/webcam-randomly-pausing-in-obs-discord-and-websites-lsvcam-and-tiktok-studio, TikTok's Virtual Camera DLL is apparently buggy and causing issues when it loads into OBS.
There should be little reason why this virtual camera is needed in OBS, especially if it's broken in its current state. Should a fixed version be released, we can relax the timestamp check if there are use cases that need this.
Installed a random version of TT Live Studio in a VM and verified this DLL was installed, though at a different place than mentioned in the blog.
> UI: Add TikTok Live Studio Virtual Camera to DLL blocklist

- UI/importers/studio.cpp
Fixes a crash when importing scenes from Windows by translating window and game capture sources to `xcomposite` or `pipewire` depending on the display server used.
This change prevents `xcomposite` from being assigned on non-X11 systems, which causes the crash due to the module not being loaded.
Fixes #5323
Tested under Ubuntu 24.10 with KDE Plasma 6.1.5 under both Wayland and X11
> UI/importers: Translate capture sources depending on display server

- plugins/obs-outputs/librtmp/rtmp.c
Use the same `mbedtls_x509_crt_parse_path` call on FreeBSD as on Linux.
Older FreeBSD versions did not include a cert bundle in the base system and required installation of the security/ca_root_nss port or package.  All currently supported FreeBSD releases include a root certificate bundle in the base system, in the same path as Linux.
Ad-hoc end-to-end tested by streaming to Facebook. Without the change, failed with "The RTMP server sent an invalid SSL certificate."  With the change, successfully streamed a test pattern.
> librtmp: Use /etc/ssl/certs/ path on FreeBSD

- UI/window-basic-main.cpp
This corrects a regression of "File -> Show Profile Folder" opening the parent Profiles directory introduced in OBS 31. Now it opens the currently active profile's directory, as before.
Alternative solutions include (but are not limited to):
* A UX discussion about whether this should actually open the parent Profiles directory going forward, with alternate naming (eg. Show Profiles Folder)
* A UX discussion of moving this menu item into the Profiles menu instead, or removing it entirely
Users expect existing behaviour to remain the same unless a change is explicitly documented.
Reported in #beta-testing on Discord.
I have verified going back as far as 17.0.2 that this menu item would open the currently active profile's directory.
Tested my changes on Windows 10.
- Bug fix (non-breaking …
> UI: Open active profile directory via File menu

- plugins/win-capture/graphics-hook/d3d10-capture.cpp
- plugins/win-capture/graphics-hook/d3d11-capture.cpp
- plugins/win-capture/graphics-hook/d3d12-capture.cpp
- plugins/win-capture/graphics-hook/d3d9-capture.cpp
- shared/obs-hook-config/graphics-hook-ver.h
Multiple APIs may be setup to capture without being initialized in graphics-hook when multiple threads are sending present calls. This just prevents those invalid captures from completing.
Adds a check for `data.handle` being null, as that currently is one indicator that the data struct has not been initialized.
In the NVIDIA 555.85 driver, an extra API queue was added when using `VK_PRESENT_MODE_FIFO_KHR` or `VK_PRESENT_MODE_FIFO_RELAXED_KHR` present modes. Two separate threads present to each of the queues. The application presents to the Vulkan queue, and the driver presents to the DirectX 12 queue (DXGI). The user-mode driver copies the contents of the vulkan framebuffer into in the the DirectX 12 queue. After that the DX12 queue is the one that is rendered to the window.
Fixes …
> graphics-hook: Fix null pointer dereference

- plugins/obs-qsv11/obs-qsv11.c
The old MSDK 1.6 code paths were for older devices which we no longer support. Typically, version 1.0 is reported when QSV fails to initialize. The lowest version that should be supported is 1.35, so we should not need code that covers versions 1.0 to 1.6.
Don't want dead code.
Tested locally on Windows 11 with an Arc A770M.
> obs-qsv11: Remove old MSDK 1.6 code

- plugins/obs-qsv11/CMakeLists.txt
- plugins/obs-qsv11/common_utils_windows.cpp
This PR does two things:
1. Remove old DX9 code
2. Remove checks for DX11
The DX9_D3D ifdefs were left over from a previous cleanup. We currently only use DX11_D3D surfaces on Windows, so we can remove the ifdefs and references.
Since we currently only support DX11_D3D surfaces on Windows, we can remove the checks for the DX11_D3D and the flag itself.
There are currently two commits here just to be explicit about the changes in each, but they can be squashed.
Don't want unused or redundant checks.
Tested locally on Windows 11 on an Arc A770M.
> obs-qsv11: Remove old DX9 code and DX11 checks

- plugins/mac-capture/mac-audio.c
When getting CoreAudio properties for an audio device source on macOS, make sure the source is active and initialized before trying to read channel information.
If we had an audio device source on macOS, and that device was subsequently disconnected from the machine, OBS would uninitialize the source, freeing the data associated with the audio channels. libobs however would still see the channel layout information, and when trying to get the source properties, would read from the previously freed channel data.
Fixes https://github.com/obsproject/obs-studio/issues/11432, https://obsproject.com/forum/threads/crash-on-macos.181702/
Some other issues still abound in this code, and it is somewhat due for improvement, but for now, important to fix what is actually crashing.
Tested locally on …
> mac-capture: Don't read channels for disconnected audio device

- cmake/linux/cpackconfig.cmake
The regex was incorrectly excluding any file with build in the name. The intent was to exclude any build directories, so we should be able to restrict this.
Fixes #11443.
It hasn't.
> cmake: Fix build directory exclusion

- plugins/win-capture/graphics-hook/d3d10-capture.cpp
- plugins/win-capture/graphics-hook/d3d11-capture.cpp
- plugins/win-capture/graphics-hook/d3d12-capture.cpp
- shared/obs-hook-config/graphics-hook-ver.h
Add a check to avoid a NULL dereference on backbuffer capture in the D3D10, D3D11, and D3D12 capture modules in case d3d10_data, d3d11_data, or d3d12_data has not yet been successfully configured. This is similar to NULL checks in other places in these modules, such as the d3d10_free, d3d11_free, and d3d12_free functions. This change is intended to fix a specific issue with D3D12 capture we are seeing the wild, but for completeness we added NULL checks to the D3D10 and D3D11 capture modules.
We were seeing an intermittent crash in graphics-hook when using OBS Studio to capture the Midnight Murder Club demo (https://store.steampowered.com/app/2698870/Midnight_Murder_Club/) on some laptops with multiple GPUs. We tracked it down to a NULL dereference when capturing the backbuffer in the …
> win-capture: Avoid NULL deref when capture not initialized

- UI/multitrack-video-output.cpp
- UI/multitrack-video-output.hpp
- UI/window-basic-main-outputs.cpp
Allow multitrack video to work with Amazon IVS `Auto (RTMPS)` and `Auto (RTMP)` server entries selected
Amazon IVS uses two `auto` entries:
- `auto-rtmp` for rtmp URLs
- `auto-rtmps` for rtmps URLs
since channels by default only allow RTMPS, not RTMP (RTMP is a separate toggle when creating/modifying the channel).
With multitrack video, the effective server for "auto" entries is selected by the GetClientConfiguration call, where the response both RTMPS and RTMP entries generally; which of these should be used depends on whether RTMPS or RTMP is selected, hence the preference of using RTMP or RTMPS needs to be visible to the multitrack video output.
Streamed up to an Amazon IVS channel with "Auto (RTMP)" and "Auto (RTMPS)" selected, and checked the log for the correct protocol
- Bug fix …
> UI: Fix handling of Amazon IVS auto URLs when using multitrack video output

- UI/window-basic-auto-config.cpp
Fixes the auto config wizard saving the signed stream key when testing with multitrack video enabled.
Since we don't use the MT config anyway for the bandwidth test there's no reason to save or use the key returned by the API.
Reported on TEB Discord by a Linux user (OAuth wasn't available in initial Flatpak builds).
Locally.
> UI: Fix autoconfig saving signed stream key

- UI/window-basic-main-outputs.cpp
When an error occurs that prevents multitrack outputs from starting the user is given an option to continue with the regular stream output, clicking "Yes" on that prompt will crash. This PR fixes that by ensuring the necessary fields are captured by copy rahter than reference, as the nested lambdas would result in captured references not working/being invalid.
Reported on TEB Discord: https://discord.com/channels/1171528364000018442/1249911465192849409/1304077629413916744
Tested fallback by disabling NVENC.
> UI: Fix falling back to non-multitrack output after error

- UI/frontend-plugins/frontend-tools/scripts.cpp
86ce0e965253f5470ccd0fb3e093ecfe136135d7 set properties modified callbacks to be called on load/reload of the script.
However it passed them an empty data settings object instead of the actual data settings of the script.
This changes to instead correctly pass the data settings object of the script to those callbacks.
The callbacks are made to expect the script's data settings object, they should recieve it in any instance where they are called.
[This script](https://github.com/user-attachments/files/17686591/modified_cb.zip) allows checking the whole state of the data settings object passed to a modified callback.
Using this (on ubuntu 24.04, python 12), checked the correct data settings object was passed, and no crash or memory leak was observed. …
> frontend-tools: Correctly pass settings to modified cb on reload

- UI/window-basic-main.cpp
Fix macOS-specific paths added to list of module paths when custom environment variables are provided to OBS Studio at launch.
When custom module and module data paths are provided via environment variables, the module paths generated by current code will not be compatible with the plugin bundle structure used on macOS.
Using environment variables is a simple way to test plugins, as this allows OBS to discover them from alternative user-provided locations.
Tested on macOS with plugins put into a custom location and provided the same directory as `OBS_PLUGINS_PATH` and `OBS_PLUGINS_DATA_PATH` via Xcode launch options.
> UI: Fix broken module paths provided via environment on macOS

- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
Fixes #11504
Since FFmpeg 7.1 a check was added to disallow pre-initializing encoder with a negative bitrate.
https://github.com/FFmpeg/FFmpeg/commit/74385dd496bdcda9a6e029fabf4946f2234a0d13
In the future we will support FFmpeg 7.1.
Try to ran Replay buffer with FLAC and PCM with OBS Studio built with FFmpeg 7.1, without the PR the audio encoder will not start.
> obs-ffmpeg: Avoid setting negative bitrate for lossless audio codec

- UI/forms/images/unassigned.svg
- UI/forms/obs.qrc
The unassigned icon is missing in the System theme.
This issue occurs in version 31.0-beta1 or later, but does not occur in version 30.2.3.
this issue was caused by this change. (maybe.) https://github.com/obsproject/obs-studio/commit/cb026964b00c366943a3c16dfb1511eafc24c035
I'm not sure if this change is correct, so please feel free to close it if it's not.
Before
https://github.com/user-attachments/assets/f4e5c261-d8c6-4490-a575-9816bf55b05b
After
https://github.com/user-attachments/assets/b7200cc4-2465-4e82-a09a-90ed42019715
I’m not sure how many people are using the system theme, but I’ll fix it (even though I don’t use it myself).
I checked with the local build.
I am not sure if the code change is correct, but the icon is now displaying.
- …
> UI: Fix missing unassigned icon in System theme

- cmake/linux/cpackconfig.cmake
Upon further review, the build directory is never set to build_$arch. Currently, our CMake Presets on Ubuntu only use build_ubuntu. However, we can attempt to be flexible here and simply exclude the build directory configured in CMake.
Want this to really be fixed. Follow-up to #11501.
Discovered after tagging 31.0.0-rc1 that the build directory was not excluded from the source package. Dug a bit deeper and realized that the build directory on CI is always `build_ubuntu` and never `build_$arch`/`/build_${CMAKE_SYSTEM_PROCESSOR}`.
We could also simply say "we only support our provided presets" and hardcode this to "build_ubuntu" as we do in `CMakePresets.json`, but this _should_ use that same value.
Tested locally on WSL.
> cmake: Fix build directory exclusion for real

- libobs/obs-scene.c
Adds the erroneously removed scale calculation back to `apply_group_transform()`.
Fixes #11488
Using reproduction steps in https://github.com/obsproject/obs-studio/issues/11488#issuecomment-2487083369
> libobs: Fix scale calculation when applying new group transform

- docs/sphinx/reference-scenes.rst
- libobs/obs-scene.c
- libobs/obs.h
Removes APIs and their documentation introduced in #9910.
Based on discussions we had in private the implementation details of how this works are a bit too messy right now and thus the API a bit too counter-intuitive to make sense to be exposed to users.
We will revise it later, but for now just remove it to avoid having it in a stable release which would then require us to maintain the current behaviour for a while before we can remove it.
Compiles.
> libobs: Remove relative scene item APIs

- plugins/obs-filters/noise-suppress-filter.c
This fixes a bug where the NVIDIA NVAFX filters are migrated but not kept in their original order, with respect to other filters.
Fixes a bug.
The bug was noticed by @Penwy whom I thank for the info.
Tested on windows 11 pro 24H2, with an RTX 4090 GPU.
The filter order is kept during migration of NVIDIA audio FX.
> obs-filters: Maintain order of migrated NVAFX filters

- libobs-opengl/gl-egl-common.c
Fixes #11617
If `query_dmabuf_modifiers` will return 0 modifiers, it will try to allocate 0 byte. (Same for `query_dmabuf_formats`)
Fix it.
Not tested, but https://github.com/KhronosGroup/EGL-Registry/blob/main/extensions/EXT/EGL_EXT_image_dma_buf_import_modifiers.txt does document that "<max_modifiers>" can be zero. (Same for "<max_formats>")
> libobs-opengl: Avoid trying to allocate 0 byte on Linux

- libobs/obs-cocoa.m
Fixed a deadlock in macOS input method change handler.
In the existing code for handling macOS input method changes, if keyboard layout information is correctly obtained, it will result in the mutex of hotkeys never being released.
This will cause a deadlock on hotkeys and freeze OBS when exit. See #11650.
Tested on macOS Sequoia 15.2, seems fixed the issue.
> libobs: Fix deadlock on macOS input method change

- UI/window-basic-main-scene-collections.cpp
- UI/window-basic-main.hpp
Fixes resetting scene collection base resolution to work again.
This was broken in #11055
Locally.
> UI: Fix remigrating scene collections from absolute to relative

- UI/obs-app.cpp
This changes the `BASE_FOLDER` to be `..` instead of `../..` on linux.
On linux, the binaries are directly in the `bin` folder, so one level above the base folder. As such setting `BASE_FOLDER` to `../..` caused the config folder to be created one level below where it should be.
Launched OBS, checked that the config folder was created correctly.
> UI: Fix Linux base folder location

- plugins/obs-nvenc/nvenc.c
Fix string
Fix string
Fix string
> obs-nvenc: Fix translation string for 4:4:4 unsupported error

- plugins/obs-nvenc/data/locale/en-US.ini
- plugins/obs-nvenc/nvenc-internal.h
- plugins/obs-nvenc/nvenc-opts-parser.c
- plugins/obs-nvenc/nvenc.c
Makes invalid user options a hard failure.
Users are being silly.
Put in some invalid options, observed failure.
> obs-nvenc: Abort encoder init if custom options are invalid

- plugins/image-source/obs-slideshow-mk2.c
Don't stop slideshow in random mode.
Fixes #11449
Hasn't.
> image-source: Fix slideshow stopping on last file in random mode

- UI/cmake/macos/Info.plist.in
Cherry-pick of 79f5ba0e1d4d228de1ba613c927d45122e70711a (#11652)
I like cherries.
Tasted good.
> cmake: Turn off camera reaction by default on macOS 14.4 and later (31.0 cherry-pick)

- frontend/widgets/OBSBasic_SceneCollections.cpp
Prevents API clients against creating scene collections without a name, while also handling the possible case of a malformed scene collection gracefully.
OBS Studio itself does not allow users to create scene collections without a name, but the checks were not added to the internal API as well. Thus API clients were able to limbo right underneath that requirement.
This PR adds two changes:
1. Adds a check against providing an empty name for a new scene collection.
2. Adds a fallback to use the scene collection's filename stem as a collection name _if_ a malformed collection is present in the file system.
This should prevent new malformed scene collections to be created by API clients but also protect users against having their OBS Studio instance crash over such malformed collections.
> …
> frontend: Fix crashes caused by scene collections with empty internal name

- .github/workflows/analyze-project.yaml
- .github/workflows/build-project.yaml
- .github/workflows/check-format.yaml
- .github/workflows/dispatch.yaml
- .github/workflows/push.yaml
- .github/workflows/scheduled.yaml
- cmake/macos/compilerconfig.cmake
Updates macOS-based jobs to use macOS 15 runners and switch to Xcode 16.1 as development environment.
Using any feature introduced in macOS 15 requires compiling OBS Studio with Xcode 16+, which is only available on macOS 15 runners. Otherwise new features of the content sharing picker or audio sinks cannot be compiled on CI.
Requires test runs on CI itself.
> CI: Update macOS workflows to macOS 15 runners with Xcode 16.1

- libobs/util/threading-posix.c
Fix the carry condition of `tv_nsec` in the static function `add_ms_to_ts`, which add specified time in millisecond to an absolute time in `struct timespec`.
The static function `add_ms_to_ts` calculate the absolute time that will passed to `pthread_cond_timedwait` in the function `os_event_timedwait`.
When `tv_nsec` is 1000000000, some implementation of `pthread_cond_timedwait`, such as glibc on Linux, immediately return with an error code `EINVAL`.
OS: Fedora 39
Tested with a modification as below to accelerate the failure condition.
```patch
static inline void add_ms_to_ts(struct timespec *ts, unsigned long milliseconds)
{
ts->tv_sec += milliseconds / 1000;
ts->tv_nsec += (milliseconds % 1000) * 1000000;
+
+        if (ts->tv_nsec > 999000000) {
+                blog(LOG_INFO, "setting …
```
> libobs/util: Fix tv_nsec becoming 1000000000 in os_event_timedwait

- plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
- plugins/obs-ffmpeg/obs-ffmpeg-output.c
Closes #11484
Fix errors introduced by building OBS Studio with FFmpeg 7.1.
FFmpeg 7.1 is out, and Arch Linux will not wait for us…
And since the errors looked easy to fix, so I made the PR.
Not completely tested, I just tried lossless encoder with #11510…
> obs-ffmpeg: Fix deprecation with FFmpeg 7.1

- plugins/obs-outputs/mp4-output.c
Changes the MP4 muxer to attempt to use the path generation logic if a path is not explicitly specified. This allows MP4 muxer outputs to be configured with file splitting, without requiring both the `path` and `directory`+`format` fields to be specified.
Currently, the UI generates the initial recording path, then lets the output do it upon file splits. While this is great, it's not very friendly to usage of the output outside of the UI (saving effort on the side of developers of custom plugins).
Used a script to create a custom `mp4_output` output in OBS, and configured it with just `directory`, `format`, and `extension` fields, no `path` field. Output started correctly as expected, generating a path for the recording.
> obs-outputs: Attempt to generate path if one is not specified

- frontend/components/MediaControls.cpp
- frontend/forms/source-toolbar/media-controls.ui
This moves the dynamic properties for the media control buttons from the cpp file to the ui file.
Nicer code
Opened OBS and made sure media buttons still looked correct
> frontend: Move media control dynamic properties to ui file

- .gitignore
Since the frontend refactor, the UI directory no longer exists. Let's remove its exception in the .gitignore file.
There's no need for it to stay.
Created a file in the (recreated) UI directory without the PR, it gets found by git.
Created a file with the PR, it gets ignored.
> .gitignore: Remove UI exclusion

- plugins/obs-outputs/mp4-output.c
Adds `buffer_size`/`chunk_size` options to configure the buffered file writers buffer size.
In some cases, e.g. high bitrate with high latency storage (NAS, SMR HDD) the default buffer size can be insufficient, and increasing it is relatively painless but not something we probably want to do by default.
Compiles and still works.
> obs-outputs: Make MP4 output buffer/chunk size configurable

- docs/sphinx/reference-libobs-media-io.rst
- libobs/media-io/video-io.c
- libobs/media-io/video-io.h
- libobs/obs.c
Ensures `raw_active` counter is only incremented/decremented if a callback was actually added/removed.
Fixes #11329
There is a race condition here where the encoder stopping due to failure will call `remove_connection()` from `full_stop()` and the output itself stopping will also call it from `end_data_capture_thread()`. This can  result in the `raw_active` counter being decremented twice to `-1`, so that the next time an output is started the counter will be incremented to `0` (instead of `1`), which is treated as inactive.
Locally.
> libobs: Fix race when disconnecting raw video callbacks

- libobs/data/color.effect
- plugins/nv-filters/data/color.effect
- plugins/obs-filters/data/color.effect
- plugins/obs-transitions/data/fade_to_color_transition.effect
- plugins/obs-transitions/data/fade_transition.effect
- plugins/obs-transitions/data/stinger_matte_transition.effect
MAD is faster than ADD then MUL. Also fix stray comment about pow behavior to be accurate.
Speed increase is probably nothing to write home about, but I was working on another project in a similar area and figured I might as well address this.
> libobs: plugins: Use MAD for sRGB functions

- frontend/utility/GoLiveAPI_PostData.cpp
- frontend/utility/models/multitrack-video.hpp
- libobs/obs.c
- libobs/obs.h
Instead of transparently resampling audio to match [`GetClientConfiguration`'s request](https://github.com/obsproject/obs-studio/pull/10855) send information about local audio settings to `GetClientConfiguration`
[Currently this is only checked in OBS Studio](https://github.com/obsproject/obs-studio/pull/10874) after a configuration has already been received, which doesn't allow for potentially different configurations in case e.g. iOS support is not necessary for this particular stream
The Twitch iOS app (and/or HLS playback on iOS in general?) requires audio to be stereo or mono; with this change the requested number of channels from the go live config is being honored, so users can still set up their recordings to contain audio in whichever speaker layout they desire, while the format …
> frontend: Add audio properties to GetClientConfiguration request

- frontend/utility/MultitrackVideoOutput.cpp
- frontend/utility/models/multitrack-video.hpp
- libobs/obs-encoder.c
- libobs/obs-internal.h
- libobs/obs.h
- plugins/obs-ffmpeg/texture-amf.cpp
- plugins/obs-nvenc/nvenc-cuda.c
- plugins/obs-nvenc/nvenc-d3d11.c
- plugins/obs-nvenc/nvenc-opengl.c
- plugins/obs-nvenc/nvenc.c
- plugins/obs-qsv11/obs-qsv11.c
Extends GPU scaling to also handle colourspace or format conversions to enable shared-texture encoding with heterogenous output formats.
#11336 falls back to shared memory encoders, which are less efficient, this aims to fix that by extending the conversion capabilities.
In theory this would also allow recording HDR locally and streaming SDR, among other use cases that people might have.
Will need some additional discussion related to function naming and implemenation of the new texture availability check.
Streamed to Twitch while recording 444 locally as well as streaming SDR while recording HDR locally.
This is part of the closed beta Twitch Enhanced Broadcasting build and seems to work fine so far.
- Performance …
> Support GPU format/colorspace conversion

- plugins/obs-webrtc/whip-output.cpp
Adds packet pacing to WebRTC output.
Pacing reduces the amount of packet loss for users. Spreading bursty content over a larger window.
This isn't a problem that I have personally. I also haven't set up network simulations that exhibit the behavior either.
WHIP output users have reported they have a better experience with this. I will have them report their results in the thread.
> obs-webrtc: Enable PacingHandler

- frontend/utility/AdvancedOutput.cpp
- frontend/utility/SimpleOutput.cpp
Log the maximum recommended audio and video bitrate when the user ticks the "Ignore streaming service setting recommendations" box.
Remake of https://github.com/obsproject/obs-studio/pull/10917 because I broke something when rebasing and the commit new commit is not showing.
Mentioned by @Warchamp7 that we should warn when a user is going above the recommended bitrate in the loganalyzer, this logging is a requirement to make that happen.
Tested Twitch and Youtube in both simple and advanced output mode, both showed the correct values.
Tested with "Custom" to confirm it is showing "None" for audio and video bitrate maximums when those values are returning 0.
https://obsproject.com/logs/ZuadI85OgoP0Yjjj
> frontend: Log streaming service recommended maximums

- plugins/nv-filters/nv_sdk_versions.h
- plugins/nv-filters/nvidia-videofx-filter.c
- plugins/nv-filters/nvvfx-load.h
This PR does two things:
- updates the checks against the new redistributables of NVIDIA AUDIO & VIDEO effects to:
- 0.7.6. for Video Effects;
- 1.6.1.2 for Audio Effects.
- cleans up the code related with cuda RT functions, which is not used anymore.
Allow nv-filters to work with newer SDK.
Fixes #11813
The video & audio effects load fine on windows 11 PRO 24H2.
> nv-filters: Update for new SDK

- cmake/finders/FindFFmpeg.cmake
This adds a ``+`` in the regexp which is used to detect the version of FFmpeg on the system.
Compiling was failing on my system (Ubuntu 24.04) with cmake complaining about FFmpeg's version. My system version is ``6.1.1-3ubuntu5+esm2``, which was detected as an empty string because the regexp does not match.
Fixes #11827
I successfully compiled OBS.
- [N/A] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [N/A] I have included updates to all appropriate documentation.
> cmake: Fix regexp to detect installed FFmpeg version

- cmake/macos/helpers.cmake
- frontend/data/locale/en-US.ini
- frontend/dialogs/OBSPermissions.cpp
- frontend/dialogs/OBSPermissions.hpp
- frontend/forms/OBSPermissions.ui
- frontend/obs-main.cpp
- frontend/utility/platform-osx.mm
- frontend/utility/platform.hpp
- frontend/widgets/OBSBasic_MainControls.cpp
- libobs/obs-cocoa.m
Using CGEventTapCreate instead of addGlobalMonitorForEventsMatchingMask to listen to global hotkeys has the advantage of tighter control over what permissions we need. Since we only listen to and do not modify the event, it is enough to have "Input Monitoring" instead of the full "Accessibility" (which would allow modifying the event after catching it).
It also might fix the issues we have with hotkeys randomly breaking down after a while. I suspect that addGlobalMonitor could just be a wrapper around CGEventTap and not handle timeouts.
This is why I'd like people who currently have issues with hotkeys randomly dying after a while testing this Pull Request. That can be a bit tricky, as the binaries will not be signed. You will probably first have to remove OBS from the permissions list …
> libobs: Rewrite macOS Hotkeys to use CGEventTap

- frontend/widgets/OBSBasic_OutputHandler.cpp
Round resolution up to closest multiple of 4 for width, and 2 for height
Fixes #11201 
Prevents odd numbered resolutions, and conforms to https://github.com/obsproject/obs-studio/commit/21ec81ebcc43e465160fcc880e4088c64d407a23
Win 10 22H2. Created a color source with `1111x1133` resolution, and rescaled. Observed resolution being set to `1112x1134`.
> frontend: Resize Output to Source Size using rounded up values

- cmake/windows/compilerconfig.cmake
- deps/libdshowcapture/CMakeLists.txt
- frontend/updater/CMakeLists.txt
- frontend/utility/MultitrackVideoOutput.hpp
- libobs-d3d11/d3d11-subsystem.cpp
- libobs-winrt/winrt-capture.cpp
- plugins/decklink/CMakeLists.txt
- plugins/obs-vst/headers/EditorWidget.h
- plugins/win-dshow/cmake/libdshowcapture.cmake
This PR makes a few changes.
1. Explicitly use std::min
2. Explicitly use std::max
3. Set `NOMINMAX` as a default compile definition on Windows to prevent defining min/max macros
Want to just use STL std::min/std::max and avoid shenanigans with min/max macros.
See also:
* https://github.com/obsproject/obs-studio/pull/10997
Also needs:
* https://github.com/elgatosf/capture-device-support/pull/6
Can remove the `/wd4005` additions later when other changes land in the Elgato submodule to properly guard NOMINMAX.
Built locally on Windows 11. Still needs built with VS for/on WoA to make sure it works.
> cmake: Use NOMINMAX on Windows

- plugins/obs-nvenc/nvenc-properties.c
AV1 has a max CQ of `63`. Before it was set to `51` for all codecs but this is only the max for H264 and HEVC.
Show correct settings for the encoder
Set target quality to new maximum and started a local recording. Verified that bitrate and visual quality are lower compared to old max value.
> obs-nvenc: Correct max target quality for AV1

- frontend/settings/OBSBasicSettings.cpp
- frontend/utility/system-info-macos.mm
Adds TEB support for macOS on Apple Silicon.
Want to support all users, including macOS/Linux (Linux tbd).
The small number of SKUs makes Apple Silicon easy, and since Intel Macs are losing support it seems fine to only support ARM.
**Note:** GetClientConfiguration API changes have not yet rolled out into production.
Locally with Twitch staging environment.
> frontend: Add support for TEB/Multitrack Video to macOS (arm64 only)

- shared/bpm/bpm.c
`update_metrics()` in `bpm.c` is checking for null pointer arguments, and there was a very minor chance of de-referencing a null-pointer in the logged message. Correct the logic to prevent this from happening.
Tested with a local build with live streams to Twitch with Enhanced Broadcasting.
> bpm: Fix potential null-pointer dereference

- libobs/data/default.effect
DeckLink hardware seems to want the values in video range.
The scopes on my fancy display were showing bad values were being sent over the wire.
Values being between 64 and 940 for bmdFormat10BitRGBXLE don't seem to be in the DeckLink SDK PDF, but they are in code comments of Mac/Linux DeckLinkAPIModes.h and Windows DeckLinkAPIModes.idl.
Scopes on my display show proper values are being sent over the wire.
> libobs: Use limited range for R10l output

- plugins/obs-nvenc/nvenc.c
Log the final `lookaheadDepth` value after all calculations, instead of an intermediate value. (For Nvenc.)
Without this change, a value gets logged based on an internal variable `rc_lookahead` that's not necessarily equal to the actual, final value that gets used for the encode. (e.g. It can get [bounded to a lower value](https://github.com/obsproject/obs-studio/blob/6f115df3afa6baa1cd12c5e7809a96ef6c4445e3/plugins/obs-nvenc/nvenc.c#L314-L318) afterward without updating this internal variable.)
Would like to show users the actual value of `lookaheadDepth` that's being used for their encode session, or at least show what's actually _set_ on the encode session. (It's a bit unclear which values the driver actually respects / meaningfully responds to.)
Thanks to @Penwy for pointing out this …
> obs-nvenc: Fix lookahead depth value logging

- frontend/utility/AutoUpdateThread.cpp
Fixes the comparison for the manifest commit hash.
The intention here was to allow updates for builds that don't have distinct version numbers, e.g. on feature test branches. We never used this upstream but at Twitch we used it for our beta builds and I found the problem there.
Twitch closed beta OBS builds.
> frontend: Fix manifest commit hash comparison

- deps/w32-pthreads/context.h
- frontend/dialogs/OBSBasicFilters.cpp
- frontend/dialogs/OBSBasicInteraction.cpp
- frontend/dialogs/OBSBasicProperties.cpp
- libobs/obs-win-crash-handler.c
- plugins/obs-filters/compressor-filter.c
- plugins/obs-filters/expander-filter.c
- plugins/obs-filters/limiter-filter.c
- plugins/obs-outputs/utils.h
Introduces Windows on ARM support to the OBS-studio application. This includes modifications that are guarded with ARM-specific macros to ensure compatibility without affecting the existing codebase.
This pull request introduces several code refactoring changes to enhance WOA support and resolve conflicts in the OBS-Studio application. The key changes include:
- **w32-pthreads:** Added additional definitions of ARM macros `_M_ARM` and `_M_ARM64`.
- **libobs:** updated `obs-win-crash-handler.c` to handle instruction pointers and stack traces, improving crash reporting on ARM64 systems .
- **obs-filters:** Renaming `S_THRESHOLD` to `S_FILTER_THRESHOLD` to avoid a conflict with existing macro with a numeric value.
- **obs-outputs:** Replaced `__tzcnt_u32()` with `_CountTrailingZeros()` for …
> Add support for compiling for Windows on ARM

- cmake/linux/helpers.cmake
- cmake/windows/helpers.cmake
> [!IMPORTANT]  
> The updater will need to be informed that this file is deleted.
While attempting to test a fix for https://github.com/obsproject/obs-browser/issues/468 I was unable to build obs-browser with Chromium 133 (CEF 6943) because our CMake was attempting to copy a file that no longer existed. After some digging, I found the below commit, which states
> Shipping both snapshot_blob.bin and v8_context_snapshot.bin is unnecessary, and v8_context_snapshot.bin is available on all supported platforms. Chrome stopped shipping snapshot_blob.bin in https://crrev.com/b550792f0f (~M66).
https://bitbucket.org/chromiumembedded/cef/commits/719f423e7030540f9b334d12e2ef9f82fc759a36
While CEF continues to ship & read this up to and including in CEF 6834, it hasn't actually been used since …
> cmake: Don't copy legacy, unused Chromium file

- build-aux/modules/99-cef.json
- buildspec.json
obs-browser: Update version to 2.24.5
082a0a2 - Don't emit a normal call to a function for closing panels
663dc38 - Disable modern game controller API on Windows
4023fad - Log fatal CEF crashes to file
52c1527 - Print browser source renderer crashes to OBS log
af0651b - Log error if CefInitialize fails
8223215 - Revert "Enable Qt message loop on Linux"
16ff0fa - Update version to 2.24.5
Additionally, update buildspec.json and build-aux/modules/99-cef.json to use the new CEF builds. This is being done because the changes in obs-browser specifically are meant to work with a CEF build compiled with use_gtk=false.
Fixes #11485
Fixes https://github.com/obsproject/obs-browser/issues/468
Tested on https://github.com/obsproject/obs-browser/pull/472 and off-thread by others.
- Bug fix …
> obs-browser: Update version to 2.24.5

- plugins/win-dshow/win-dshow.cpp
If a frame has a width or height of zero, this value will make it into libobs/media-io/video-frame.c:video_frame_init and cause linesizes or heights to be zero, which will result in a bmalloc(0) call and OBS will crash.
Instead of letting the call stack get that far, check the frame width and height here at the source, log an error, and return early if the frame width or height are zero.
Alternative to:
* #11803
Fixes #11729
Fixes #11860
Tested locally by forcing `videoConfig.cx` or `videoConfig.cy_abs` above this change to be zero and verifying that the error is logged and OBS does not crash.
> win-dshow: Fix possible crash if frame width or height is zero

- build-aux/modules/99-cef.json
- buildspec.json
- cmake/finders/FindFFmpeg.cmake
- plugins/mac-avcapture/plugin-main.m
- plugins/nv-filters/nv_sdk_versions.h
- plugins/nv-filters/nvidia-videofx-filter.c
- plugins/nv-filters/nvvfx-load.h
- plugins/obs-nvenc/nvenc-properties.c
- plugins/obs-nvenc/nvenc.c
- plugins/win-dshow/win-dshow.cpp
- shared/obs-scripting/obs-scripting-python-import.c
- shared/obs-scripting/obs-scripting-python.c
Cherry-picks:
* https://github.com/obsproject/obs-studio/pull/11590
* https://github.com/obsproject/obs-studio/pull/11814
* https://github.com/obsproject/obs-studio/pull/11554
* https://github.com/obsproject/obs-studio/pull/11520
* https://github.com/obsproject/obs-studio/pull/11816
* https://github.com/obsproject/obs-studio/pull/11909
* https://github.com/obsproject/obs-studio/pull/11910
* https://github.com/obsproject/obs-studio/pull/11895
Want to ship crash fixes and bug fixes.
Tested on the PRs.
> Cherry-picks to release/31.0

- plugins/obs-ffmpeg/texture-amf.cpp
- Adds AMD AV1 B-frame support on supported GPUs
- Defaults to 2 B-frames and is enabled when supported
- Depends on AMF SDK header file updates in https://github.com/obsproject/obs-deps/pull/268
- Depends on OBS deps package update in https://github.com/obsproject/obs-studio/pull/11931
- Enable support for upcoming AV1 B-frame feature
- Tested on local AMD systems with and without AV1 B-frame support
> obs-ffmpeg: Add AMD AV1 B-frame support

- plugins/obs-ffmpeg/texture-amf.cpp
This PR fixes the case where OBS does not refresh the throughput caps with the user's setting so stale throughput values are used to check preset compatibility as well as the case where `..._CAP_MAX_THROUGHPUT` does not work as expected -> returns 0 -> and fails to fall back to the lowest preset.
This is a bug fix.
- Tested on multiple Windows machines
> obs-ffmpeg: Fix throughput checks for older AMD driver

- cmake/windows/helpers.cmake
Qt has some Release DLLs that end with the letter d:
* qdirect2d.dll
* qcertonlybackend.dll
* qopensslbackend.dll
* qschannelbackend.dll
As a result, they get caught by our simple check for if a DLL is a Debug DLL which just checks if the DLL ends with the letter d.
Extend that check to exclude these specific DLLs from being marked as Debug DLLs.
Noticed these files weren't being copied.
Tested locally some time last year.
> cmake: Fix some Qt DLLs not being copied due to filename patterns

- docs/sphinx/reference-outputs.rst
- frontend/utility/MultitrackVideoOutput.cpp
- libobs/obs-internal.h
- libobs/obs-output.c
- libobs/obs.h
Adds a callback for making reconnection decision.
Also reverts #11304
#11304 was necessary for #11452, but negatively impacted regular users as some servers would not accept a reconnection attempt after the default retry time (2 seconds), which resulted in some users seeing a warning message instead of automatic reconnection.
To restore the old behaviour, we instead add a new callback that makes it a decision by the output's creator on whether or not they want to allow a reconnect attempt.
In addition to a simple yes/no decision this also allows reconfiguring the output in the callback, allowing for a futrue rework of #11452 that does not rely on the somewhat ugly UI changes to hijack the regular disconnect logic and instead updates the output in-place before returning.
Verified regular …
> libobs/frontend: Add callback for reconnection decision

- libobs/obs-output.c
Ensures `reconnecting` is false if reconnection attempts are aborted.
Fixes an issue where an output remains "active" after a failed reconnection attempt due to `reconnecting` never being reset to `false`.
Tested with Twitch and two OBS instances:
- Instance A streaming with the regular stream key
- Instance B starting a few seconds later with `?priority=2` appended to the stream key
This will lead to instance B taking over the stream and instance A being disconnected by the streaming platform. Without this change OBS will perpetually be stuck in a semi-active state where the output cannot be restarted as `obs_output_active()` remains `true`.
> libobs: Reset reconnecting state when can_reconnect is false

- plugins/obs-nvenc/nvenc-cuda.c
Fix incorrect CUDA array size allocation.
The obs-nvenc module was using a double-sized CUDA array as a shared texture with the P010 format.
The original code snippet:
```cpp
desc.Format = CU_AD_FORMAT_UNSIGNED_INT16;
desc.Height += enc->cy / 2;
desc.NumChannels = 2; // number of bytes per element
```
According to the [cuArray3DCreate](https://developer.download.nvidia.cn/compute/DevZone/docs/html/C/doc/html/group__CUDA__MEM_gc2322c70b38c2984536c90ed118bb1d7.html) documentation,
the previous descriptor requested **4 bytes** per element, which was incorrect.
The changes were tested on Ubuntu 24.10 with an RTX 3060 Ti GPU.
To force obs-nvenc to use shared textures as if it were running on a different GPU,
in the `hevc_nvenc_create` function within nvenc.c, `nvenc_create_base` was called …
> obs-nvenc: Fix incorrect CUDA array size allocation

- plugins/nv-filters/nvidia-videofx-filter.c
This is a split of https://github.com/obsproject/obs-studio/pull/11899 which now only carries new features and improvements.
The current PR focuses on bug fixes.
Fixes bug #11383 
Fixes also a bug with a third-party plugin which requires Background Removal to set bulk foreground to alpha = 1. [1]
This fixes also several unreported bugs:
- when resetting Background Removal, the temporal state variable has to be recreated and not just reset.
- the cuda stream used for the operations of mapping, transfer and unmapping of resources must be the same; there was an error with Blur effect.
- the reset signal is removed because it recreates the effect and can cause bugs (crashes); we now leave the SDK deal on its own with parent source updates.
- the SDK reports an error on initial load; we …
> nv-filters: Various bugfixes

- plugins/mac-avcapture/plugin-main.m
When creating the `obs_source_frame` for a Video Capture Device source, use `bzalloc` instead of `bmalloc` to ensure the memory inside the struct is fully cleared before use.
macOS users have been noticing that, occasionally, Video Capture Device sources are flipped upside down inexplicably. It turns out that this was due to uncleared memory inside the `obs_source_frame` struct having the `flip` property evaluating to a truth-ish value.
While `malloc` on macOS seems like it should possibly [zero on allocations by itself](https://github.com/apple-oss-distributions/libmalloc/blob/bdc20d994577999401fb11f1db855e05707ae599/src/malloc.c#L1625) (since we target 11.0; though I'm not sure exactly what the program_sdk value represents in our case), one way or another we were getting uncleared …
> mac-avcapture: Clear memory when creating frame struct

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
This Pull Request updates the list of RTMP servers for Castr.io in the `services.json` file used by OBS Studio. The new server configurations are now included to support streaming functionality for users of Castr.io. The servers have been updated to reflect the latest changes from Castr.io.
This update is required to ensure that OBS users who stream to Castr.io have the correct server configurations available in the RTMP services list. The previous list may not have included the latest server configurations, which could cause issues for users.
I have tested this update by adding the new RTMP server configurations to the `services.json` file and verifying that they appear correctly in the OBS Studio stream settings. I also ensured that users can successfully stream to Castr.io using the …
> rtmp-services: Update Castr.io ingests

- frontend/widgets/OBSBasic.cpp
Change emission of frontend events for scene collection and scene changes during startup only for existing scenes.
To emit frontend events early during OBS' initialisation, the `disableSaving` state variable needs to be "falsy" (as events will not be emitted otherwise).
The code path taken for generating a new fallback scene collection has `disableSaving` decremented to "enable" saving (and thus frontend events) already, so it's just the code paths for existing collections that need this workaround.
Emitting the "scene changed" and "preview scene changed" events when a fallback scene collection has been created has side-effects when OBS Studio is set to studio mode and can lead to potential crashes, as the studio mode is still in an invalid state at this point.
Tested by launching OBS …
> frontend: Only emit frontend events for existing scene collection

- frontend/forms/OBSBasicControls.ui
- frontend/widgets/OBSBasic.cpp
- frontend/widgets/OBSBasicControls.cpp
- frontend/widgets/OBSBasicControls.hpp
Remove the Exit button from the Controls dock
I don't know a single other application that has an exit button in the main UI.
The Controls dock is something I'd like to fully replace one day but in the meantime this helps remove some clutter from it.
Compiled
> frontend: Remove Exit button

- cmake/macos/compilerconfig.cmake
Adjust the macOS CMake initialization logic to use `xcrun` to derive our SDK version information, rather than relying on the presence of `${CMAKE_OSX_SYSROOT}`.
CMake 4.0.0 (currently in the release candidate phase) breaks OBS configuration/generation on macOS. This is because CMake 4.0.0 no longer defines `CMAKE_OSX_SYSROOT` by default for macOS builds, which we currently rely on to make sure the user has an SDK supported by OBS.
This CMake change was apparently made because specifying `CMAKE_OSX_SYSROOT` seems to translate under the hood to passing `-isysroot` to the compiler, which apparently had some undesired impacts in some situations (further context [here](https://gitlab.kitware.com/cmake/cmake/-/commit/7b195312919cbf69497af2514b91b55bd9a6da71) and …
> cmake: Adjust macOS SDK detection

- plugins/linux-pipewire/pipewire.c
- plugins/linux-pipewire/screencast-portal.c
Tonemap textures from non-linear sRGB to linear sRGB when in 10-bit or higher color format and update texture format accordingly
Fix white-tint when using a pipewire capture in a 10-bit or 16-bit color format regardless of monitor source bitdepth
Before/After in NV12, P010 and P416 color formats on both 10-bit and 8-bit monitors. Confirmed to work both in Preview (no white tint observed) and custom FFmpeg render (10-bit gradient is captured)
> linux-pipewire: Fix 10- and 16-bit captures

- frontend/data/themes/Yami.obt
- frontend/forms/OBSBasic.ui
Not all list widgets were using this consistently, and these should be set in the themes instead.
Makes things consistent
Looked at each list widget to make sure there was no extra spacing besides margins set in themes.
> frontend: Make list spacing consistent

- docs/sphinx/reference-core.rst
- libobs/obs.h
`obs_get_transition_by_name` is very problematic because transitions are always private and their names aren't unique. This means that the method iterates over all private sources and then takes the first that both is a transition and matches the name we're looking for. However, this could be from anywhere - it could be a frontend transition, but also a source transition, quick transition, or even one from third-party plugins. This is always never what is intended.
As such, this method (which should never have been added in the first place) needs to go. In its place, `obs_frontend_get_transitions` returns a list of all frontend transitions (which is usually what people are looking for), and alternatively `obs_get_source_by_uuid` also provides access to private sources.
While we're at it, …
> libobs: Deprecate obs_get_transition_by_[name|uuid]

- frontend/cmake/os-linux.cmake
- frontend/settings/OBSBasicSettings.cpp
- frontend/utility/MultitrackVideoOutput.cpp
- frontend/utility/system-info-posix.cpp
- libobs-opengl/gl-subsystem.c
- libobs/graphics/device-exports.h
- libobs/graphics/graphics-imports.c
- libobs/graphics/graphics-internal.h
- libobs/graphics/graphics.c
- libobs/graphics/graphics.h
- libobs/util/platform-nix.c
- plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
TEB (Twitch Enhanced Broadcasting) requires the client to gather information about the host, such as which GPU(s) are available, memory sizes, OS version, etc..., and send that information to a server which then responds with a configuration set for the client to use with multitrack encoding. TEB originally supported Windows, and this PR adds support for Linux-based operating systems.
TEB on Linux supports NVIDIA and AMD GPUs, and Intel GPUs as of 2024.12.17. Intel GPUs with Linux seem to work at least with a flatpak build. For NVIDIA GPUs, NVENC is used and the configurations from the server are currently identical between Windows and Linux. For AMD GPUs, AMF is used on Windows and VAAPI is used on Linux; AMF on Linux is not currently supported for TEB. AMF on Linux might be supported in …
> Add Enhanced Broadcasting support for Linux

- docs/sphinx/reference-canvases.rst
- docs/sphinx/reference-core.rst
- docs/sphinx/reference-sources.rst
- libobs/CMakeLists.txt
- libobs/obs-audio.c
- libobs/obs-canvas.c
- libobs/obs-internal.h
- libobs/obs-scene.c
- libobs/obs-source.c
- libobs/obs-source.h
- libobs/obs-view.c
- libobs/obs.c
- libobs/obs.h
- libobs/obs.hpp
Adds canvases to libobs.
In this first iteration a canvas is a reference-counted object that contains scene sources (Scenes and Groups) and has an associated view and video mix.
Unlike views, canvases can be shared and ensure their video mixes persist across video resets. They can also be saved and loaded like sources, and solve various issues of using views (audio mixing, activation, scene rendering, etc.).
The end goal of this work is to superseede #10635 with something that is more generic and safer, and should make features that rely on rendering individual sources separately (e.g. ISO recording or virtual cam) easier to implement.
In the long term we want to deprecate views and refactor more things to be canvas-aware, to provide greater flexibility in the libobs world for multiple …
> Canvases - Part One (libobs)

- deps/json11/json11.cpp
Fixes a compile error in `json11` introduced in GCC 15.
The compiler already suggests this solution:
```
/builddir/build/BUILD/obs-studio-31.0.3-build/obs-studio/deps/json11/json11.cpp:25:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
24 | #include <cmath>
+++ |+#include <cstdint>
25 | #include <cstdlib>
```
* Fixes #11989 
Ran across a compile error, don't like those.
Compiled with GCC 15 on Fedora 42.
> deps/json11: Fix compile error on GCC 15+

- frontend/data/locale/en-US.ini
- frontend/data/themes/Yami.obt
- frontend/data/themes/Yami_Light.ovt
- frontend/forms/OBSImporter.ui
- frontend/importer/ImporterModel.cpp
- frontend/importer/OBSImporter.cpp
A few minor adjustments to the Scene Collection importer:
- Separate Browse and Import buttons physically in the bottom bar
- Adjust text on these buttons to be more clear
- Disable Import button when no collections are checked
- Adjust window title
- Update QTableView checkboxes to use theme icons
Hated how the old buttons were labeled "Import" and "Add" and the leftmost one was the one that actually added/imported the selected collections
Interacted with dialog, imported a collection.
> frontend: Adjust scene collection importer

- frontend/components/SourceTreeDelegate.cpp
- frontend/data/themes/Yami.obt
Minor adjustment to the SourceTreeItem sizeHint calculation and styling rule cleanup.
This also fixes the items in the Sources list being different sizes than the Scene list, which is a bug.
Before:
After:
There are a few confusing SourceTree specific style rules to account for the fact it uses a QListView with custom widgets instead of a QListWidget. This PR tidies that up a little bit and also removes some unnecessary rules targeting the SceneTree widget.
Compiled and checked visual changes.
> frontend: Adjust styling for Sources list

- frontend/dialogs/NameDialog.cpp
Sets the focused widget to the QLineEdit in NameDialog widgets.
Want the text entry field to be focused when these dialogs are created.
I think this was already the case in past versions, unsure when the regression happened and if it was our fault or Qts.
Opened Profile and Scene Collection New/Rename/Duplicate dialogs
> frontend: Focus text entry in NameDialog

- plugins/obs-ffmpeg/CMakeLists.txt
- plugins/obs-ffmpeg/data/locale/en-US.ini
- plugins/obs-ffmpeg/obs-ffmpeg-openh264.c
- plugins/obs-ffmpeg/obs-ffmpeg.c
This is split out of #8529 to provide only the commit that adds the wiring for the codec.
This also provides a framework for adding support for other H.264 software codecs provided through FFmpeg.
A number of distributions use [OpenH264 distributed by Cisco](http://www.openh264.org/) to provide a fully licensed H.264 implementation (in particular, both [Fedora Linux](https://fedoraproject.org/wiki/OpenH264) and [openSUSE Linux](https://en.opensuse.org/OpenH264) do). However, OBS Studio cannot currently use it.
This change allows OBS Studio to use OpenH264 through FFmpeg if it's available.
* Tested recording a screencast using OpenH264 + AAC with both Simple and Advanced settings modes (with #8529)
* Tested streaming a screencast using OpenH264 + AAC with both Simple and Advanced settings …
> Add OpenH264 support to obs-ffmpeg

- frontend/components/SourceTreeItem.cpp
This removes a hack that added additional spacing as scrollbars would go over content due to a Qt bug. This bug appears to be fixed, as the described behavior is no longer observed. As such, the additional spacing is no longer needed (and only looks out of place).
Effectively reverts 4e97b1bb30fa79215f7162f36066336732b59f28.
Before/After:
<p>
</p>
Noticed the out-of-place looking spacing, which seemed wrong. Doesn't look like it's still needed.
macOS 15.3
Everything I tried (adding, removing, resizing) seems fine, the scrollbar never went over the icons. Unfortunately it appears the Qt bug was never documented anywhere by us.
> frontend: Remove additional spacing hack in SourceTreeItem

- frontend/data/themes/Yami.obt
- frontend/forms/OBSBasic.ui
This is needed due to [QTBUG-106395](https://bugreports.qt.io/browse/QTBUG-106395). With spacing, drag-and-drop would cause items to go to the bottom of the list if they are dropped in the spacing.
Effectively reverts most of 5fa4ea44d0b364bf9be18816c2d9b35b96bab939 (https://github.com/obsproject/obs-studio/pull/11557). See also #7321 and 860b309db86ac4e096df1d72b9cf8f99d60e8c56 (#7341) which was the first time where the spacing got removed.
The comments in the `.ui` file don't exactly survive a Qt Creator save but neither does a lot of the rest of that file (tested in Qt Creator 16.0.0), so perhaps they'll stay for a while at least. Also they'll be in the git log, so if someone tries to re-add the spacing again in the future maybe they'll see them.
Don't want a regression like #7321 …
> frontend: Re-set list spacing of source and scene tree to 0

- .clang-format
- .github/actions/run-clang-format/action.yaml
- build-aux/.run-format.zsh
- frontend/settings/OBSHotkeyWidget.cpp
- frontend/utility/BasicOutputHandler.hpp
- frontend/utility/RemuxWorker.hpp
- libobs/util/threading-windows.c
- plugins/coreaudio-encoder/encoder.cpp
- plugins/mac-capture/mac-display-capture.m
- plugins/nv-filters/nvidia-videofx-filter.c
- plugins/nv-filters/nvvfx-load.h
- plugins/obs-webrtc/whip-output.cpp
- shared/obs-scripting/obs-scripting-python.c
- shared/obs-scripting/obs-scripting.c
Updates source code formatting script and CI actions to use `clang-format` v19.1.1.
Enables the `SkipMacroDefinitionBody` for `clang-format` to avoid reformatting of multi-line macro definitions.
Also includes updated formatting of all source code files with the updated version.
Microsoft Visual Studio started shipping version 19.1.1 of `clang-format`, thus any developer using that IDE will see their source code files automatically formatted using that version.
To minimise friction for these developers, updating to the same version on CI (and thus updating the project to that version) will reduce the potential for CI build failures.
Homebrew's current `clang-format` version is v20.1.0, so macOS is still "ahead" of Visual Studio, so a custom Formula is provided to easily install v19.1.1 on …
> CI: Update clang-format scripts and actions to version 19.1.1

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
Description
Added HEVC (h265) to the list of supported video codecs in services.json for Bilibili RTMP streaming.
Motivation and Context
Bilibili now supports HEVC encoding for RTMP streaming, but OBS’s services.json previously only listed h264. This change ensures that OBS correctly reflects HEVC as a supported codec for Bilibili.
How Has This Been Tested?
Tested on OBS version 31.0.2, using HEVC encoding to stream to the Bilibili RTMP server, and confirmed the video plays correctly.
Types of Changes
Checklist:
> rtmp-services: Add HEVC (h265) to the list of supported video codecs for Bilibili RTMP streaming

- plugins/rtmp-services/data/package.json
- plugins/rtmp-services/data/services.json
This is a recreated pull request due to the issue with PR #11901 (maintainers could not rebase because my previous fork was from stream-labs/obs-studio). I have reforked from obsproject/obs-studio and reapplied the changes.
The distinction between free and premium members in the server selection list has been removed. The Niconico service entry has been consolidated into a single entry, as the latest settings no longer require a separation based on membership type.
This PR updates the ingest URL for Niconico Live Streaming in the `rtmp-services` configuration file. The previous ingest URL is no longer valid, and the service now requires an updated URL.
Additionally, this PR adds `more_info_link` and a link to a page that explains how to obtain the stream key (`stream_key_link`) to the …
> rtmp-services: Update ingest URL for Niconico Live Streaming(ニコニコ生放送)

- plugins/obs-qsv11/obs-qsv11.c
Remove a function that, due to other, previous code removals, doesn't do anything anymore.
This `profile_modified` callback function exists simply to toggle visibility of a "CQM" encoder option in the settings UI; however, said option has been removed from the plugin years ago. There is no option to toggle anymore, so this code effectively does nothing now. This PR removes the non-functioning function.
Cleaning up a "fancy no-op with extra steps" function I saw when stepping through this plugin in the Visual Studio debugger.
(It used to do something, but the stuff it did has been removed from the codebase some time ago.)
History of this code: This callback function and the "CQM" setting it _used to_ toggle were added in https://github.com/obsproject/obs-studio/pull/2077. Then the …
> obs-qsv11: Remove non-functional CQM-related code

- frontend/widgets/OBSBasicPreview.cpp
If the crop values combined are larger than the width or height of the source, an integer overflow will occur.
This fix converts the width/height values to int, and then clamps any negative values to 0.
Fixes obsproject/obs-studio#11917
This was one of the root causes behind the freeze reported in https://github.com/obsproject/obs-studio/issues/11917. Due to the integer overflow, it would essentially make the for loop in `DrawStripedLine()` in `OBSBasicPreview.cpp` repeat nearly endlessly, which caused certain mutexes to stall (especially the scene video/audio mutexes). Because of that near-infinite loop, both the main and audio threads would stall until that near-indefinitely-stalled loop completed.
Tested according to the reproduction steps in …
> frontend/widgets: Fix integer overflow

- docs/sphinx/graphics.rst
- docs/sphinx/reference-libobs-graphics-graphics.rst
- frontend/data/striped_line.effect
- frontend/widgets/OBSBasicPreview.cpp
- frontend/widgets/OBSBasicPreview.hpp
- libobs/graphics/graphics-internal.h
- libobs/graphics/graphics.c
- libobs/graphics/graphics.h
- libobs/graphics/matrix4.c
Minorly improves performance by reusing vertex buffers for sprite drawing, for the preview primitives, and also improves performance by optimizing a few commonly-used matrix transformation functions and reducing the amount of math needed every time a matrix translate/rotate/scale occurs.
Due to obsproject/obs-studio#11917,  I realized that the preview was recreating vertex buffers for every draw call, which is very unnecessary. I just decided to improve the code for all of it because once I saw it I couldn't help but feel the need to fix this unnecessarily perf hit, and in turn that led me down other minor perf-related rabbit holes which I decided to fix up as I noticed them.
This affects all drawing so if there was something wrong it would probably affect everything if there were an …
> Improve preview primitive performance

- plugins/win-capture/graphics-hook/vulkan-capture.c
Vulkan Direct Display uses extensions:
VK_KHR_display/VK_EXT_direct_mode_display
This workflow allows creating swapchains that arn't active on the desktop, so they don't have HWNDs.
Avoid trying to create swap_data when a HWND can't be found.
Fixes #11581
VK_KHR_display/VK_EXT_direct_mode_display extensions created swapchains without HWND handles.
Avoid trying to work with HWND when they can't be found.
The old behavior causes crashes when applications using Direct Display.
The only thing I tested was that the crash doesn't occur. If avoiding filling the `swap_data` has
greater ramifications, then I'll need feedback from devs more familiar with OBS.
> graphics-hook: Fix crash with Vulkan DirectDisplay

- shared/media-playback/media-playback/media.c
If a frame has a width or height of zero, this value will make it into libobs/media-io/video-frame.c:video_frame_init and cause linesizes or heights to be zero, which will result in a bmalloc(0) call and OBS will crash.
Instead of letting the call stack get that far, check the frame width and height here at the source, log an error, and return early if the frame width or height are zero.
https://obsproject.com/logs/3ApOqPpoBR2XcHqO
[2025-03-30 23-01-46-1.txt](https://github.com/user-attachments/files/19556395/2025-03-30.23-01-46-1.txt)
See also:
* https://github.com/obsproject/obs-studio/pull/11861
Tested locally by forcing width or height to zero to see if OBS crashes or not.
I have not been able to spontaneously reproduce this crash otherwise.
- Bug fix (non-breaking change which fixes …
> media-playback: Fix possible crash if frame width or height is zero

- plugins/linux-v4l2/v4l2-output.c
Skip the 'non-compliant' usage of STREAMON ioctl for V4L2 compliant _v4l2loopback_ module
When starting the virtual camera:
-   Check the OUTPUT capability is reported for the device.
-   If has OUTPUT: use compliant calls only (do not use STREAMON/OFF workaround).
-   If no OUTPUT capability: _attempt_ to reset using the STREAMON/OFF workaround for _loopback_ 0.12.5-0.12.7, then continue to use workaround each time opened.
Fixes #11891
_v4l2loopback_ was recently updated to have stronger compliance with V4L2 UAPI; thus, the invocation of STREAMON by _OBS_ when no streaming I/O buffers have been negotiated (e.g. via REQBUFS) results in an error.
This is also a revision of the fix for #4808 - where it was identified that the STREAMON call would trigger the reset of the OUTPUT capability …
> linux-v4l2: Fix virtual camera start failure

- plugins/mac-capture/mac-sck-audio-capture.m
macOS Audio Capture was using the incorrect capture type enum member to check the capture method on initialization. Because the default was zero, and because the incorrect enum would typically be zero-initialized anyway, this went unnoticed. The correct member enum is being used everywhere else in macOS Audio Capture.
AppleClang in Xcode 16.3 flags this as a non-matching enum type in the comparison, breaking the build. For some reason earlier AppleClang in earlier SDKs did not flag this as a warning.
Fixes #12034.
Verified the build now works locally with Xcode 16.3 and that macOS Audio Capture still works as intended.
> mac-capture: Fix incorrect enum comparison

- plugins/obs-ffmpeg/texture-amf.cpp
The default "level" setting was being used for each codec (AVC, HEVC, AV1) supported by AMF. For example, all HEVC encoders were using level 6.2 and this caused some playback devices to reject decoding the bitstream because the device reported a maximum decode level lower than 6.2. 
This PR adds functionality to determine the best match for the codec level instead of relying on the defaults, for AMF encoders.
The default behaviour of setting the codec level to the maximum resulted in several Android-based devices failing to decode HEVC streams in the TEB (Twitch Enhanced Broadcasting) beta program, which is currently testing HEVC compatibility. Adjusting the level appropriately instantly fixed the decode failures.
Also, most APIs (such as NVENC and VAAPI) have an "Auto" option for setting …
> obs-ffmpeg: Set the codec level for AMF encoders

- build-aux/modules/30-ffmpeg.json
- build-aux/modules/patches/ffmpeg/0001-lavc-vaapi_encode-Query-surface-alignment.patch
- build-aux/modules/patches/ffmpeg/0002-lavc-vaapi_encode_h265-Use-surface-alignment.patch
The HEVC VCN encoder in AMD GPUs will output the incorrect vertical resolution in some cases, most importantly 1920x1080 will result in 1920x1088. A workaround for this issue is available in AMF on Windows, however on Linux with VAAPI and Mesa, a different solution is required. 
This PR adds 2 upstream FFmpeg commits that have already been merged in FFmpeg `master` to address the incorrect AMF vertical resolution problem, for the flatpak build.
Please refer to [1], [2], and [3] for context. The patches are taken from [2].
AMD VCN uses a different surface alignment compared to other GPUs for encoding, which required an upstream fix in Mesa, libva, FFmpeg, and the VCN firmware. 
This commit adds the FFmpeg patches to the flatpak build of OBS which is currently using FFmpeg version n7.1, …
> build-aux: Fix incorrect HEVC vertical resolution on AMD VCN

- libobs/util/platform-nix.c
In `has_qt5_dependency`, revert the log handler to the default just after the fork.
This change assumes that `base_set_log_handler` and `def_log_handler` do not use any locks.
The frontend has set a log handler which locks a mutex in `LogString`.
If `os_dlopen` fails in the child process, it calls `blog` and attempts to lock the mutex that another thread may have already locked before `fork()`.
Though I never encountered the deadlock, it's better to fix it.
OS: Fedora 40
Added a plugin binary file which causes an error during `os_dlopen`.
Ran OBS and checked the log file contains only one error message of the plugin.
> libobs/util: Prevent locking mutex in child process when checking Qt5

- frontend/OBSApp.cpp
Enables OBS Studio to fall back on default paths for settings, profiles, and scene collections when configured paths do not exist.
When a unique path is set up as the location for user settings, profiles, or scene collections, migrating the files from one computer to another will lead to confusing error messages as the original paths might not exist on the new machine.
The default directories for configuration files are already created by this point, so using those paths as a fallback should enable OBS Studio to also create the corresponding fallback settings files.
While this might lead to a confusing "in-between" state as OBS Studio will just carry on launching, creating fallbacks for everything, this is in line with current behaviour in the rest of the application.
Tested locally with …
> frontend: Use default location for user settings as fallback

- deps/blake2/CMakeLists.txt
Add missing `FOLDER` property for Windows-exclusive `blake2_static` target and group it with the global `blake2` target.
The blake2_static target has no specific FOLDER property set and thus would appear ungrouped in Visual Studio's Solution Explorer.
With this change both the default blake2 target as well as blake2_static appear in their own "blake2" subdirectory.
Tested on Windows 11 with Visual Studio 17.13.6.
> cmake: Group blake2 targets under same directory for IDEs

- frontend/data/locale/en-US.ini
- frontend/widgets/OBSBasicStats.cpp
This PR adds a dedicated translation for the remaining time of the disk space in the stats window.
I want to remove `, ` from the remaining time when the locale is Japanese.
| | English | Japanese |
| --- | --- | --- |
| master | ![screenshot-master-en_US](https://github.com/user-attachments/assets/1102632a-107f-4bd1-ade7-a39c5ef7d073) | ![screenshot-master-ja_JP](https://github.com/user-attachments/assets/56859f4b-db3a-44dd-bf2d-5850c28608e4) |
| this PR | ![screenshot-mod-en_US](https://github.com/user-attachments/assets/4e5c7416-c109-4278-aad2-da1a1cae71e4) | ![screenshot-mod-ja_JP](https://github.com/user-attachments/assets/80f96738-9ed8-4200-a262-465c675d3c09) |
In my workspace, added a line below to `ja-JP.ini` and tested.
```ini
Basic.Stats.DiskFullIn.Text="%1 時間 %2 分"
```
- …
> frontend: Add dedicated translation of remaining time

- libobs/obs-scene.c
When trying to set non-zero `position` on a scene item with `obs_sceneitem_set_order_position`, an edge case kicks in, causing a crash due to `scene->first_item` being `NULL` after `detach_sceneitem(item)` is executed.
`libobs` standard behaviour is to silently fix invalid input. This change respects this behaviour by silently fixing the edge case described above.
Manual testing.
> libobs: Fix setting non-0 order on only scene item

- libobs/callback/decl.c
In the API `parse_decl_string`, it jumps to `fail` label if an error occurs. However, the `success` is calculated depending on `cfp.error_list`, which could be empty.
This PR ensures the API will return failure if `goto fail` is called.
I found a code below crashed at `proc_handler_call`.
```c
#include <stdio.h>
#include <obs.h>
int main()
{
proc_handler_t *ph = proc_handler_create();
proc_handler_add(ph, "", NULL, NULL);
proc_handler_call(ph, "f", NULL);
return 0;
}
```
OS: Fedora 40
Tested above code.
Without this PR, `proc_handler_add` returns success and `proc_handler_call` crashed.
With this PR, `proc_handler_add` returns failure and `proc_handler_call` does not crash.
> libobs/callback: Catch fail cases with missing error data

- plugins/win-capture/game-capture.c
Updates the stop_capture call to set capturing to false before sending the unhooked signal.
If the get_hooked procedure is called during the unhooked signal the source would still report that it's hooked because gc->capturing hasn't been updated yet. This is mainly an issue when enumerating all capture sources to see if any are still capturing after an unhooked signal.
Tested on windows 10 x64 and it now works as expected. It's a very isolated change so easy to test.
> win-capture: Update hooked state before unhooked signal

- libobs/obs-nix.c
This uses an absolute path when evaluating `OBS_INSTALL_PREFIX "/" OBS_PLUGIN_DESTINATION` when adding it as a module path.
This fixes a bug where, if `OBS_INSTALL_PREFIX "/" OBS_PLUGIN_DESTINATION` contains any non-absolute components, the strcmp with `abs_module_bin_path` to returns false, even if both are the same path, causing both paths to be added, and modules to be loaded twice.
A trailing slash in the `CMAKE_INSTALL_PREFIX` and launching in portable mode is enough to cause this to happen.
Compiled and ran portable with a `CMAKE_INSTALL_PREFIX` with a trailing slash, verified it did not load plugins twice.
> libobs: Use absolute path for install prefix module load

- plugins/linux-v4l2/v4l2-output.c
This is the updated PR for https://github.com/obsproject/obs-studio/pull/5069
It provides FreeBSD support for tve Virtual Camera feature
> linux-v4l2: Add support for virtual camera on non-Linux environments

- frontend/utility/AdvancedOutput.cpp
- frontend/utility/MultitrackVideoOutput.cpp
- frontend/utility/MultitrackVideoOutput.hpp
- frontend/utility/SimpleOutput.cpp
- plugins/obs-outputs/rtmp-stream.c
This PR depends on https://github.com/obsproject/obs-studio/pull/12003 being merged first, to avoid merge conflicts. 
Remove network optimizations (aka New Socket Loop) from the incompatible settings list for multitrack video as it works properly now. Network optimizations are controlled in Settings -> Advanced and have 2 elements:
This PR enables both options (network optimizations and TCP pacing) to be used with multitrack video.
Network optimizations were incompatible with Enhanced Broadcasting during early development, along with some other standard OBS features, which led to the creation of a `MultitrackVideoOutput::HandleIncompatibleSettings()` function to notify users and block the stream attempt. The features have been tested within the TEB beta and have been working reliably for …
> frontend: Allow network optimizations with multitrack video

- frontend/OBSApp.cpp
- frontend/dialogs/OBSAbout.cpp
- frontend/widgets/OBSBasic.cpp
- libobs/CMakeLists.txt
- libobs/cmake/libobsConfig.cmake.in
- libobs/cmake/linux/libobs.pc.in
- libobs/obs-config.h
- plugins/obs-outputs/flv-mux.c
Removes `HAVE_OBSCONFIG_H` ifdef-checks and marks the definition for removal in 32.0 (as removing it could be considered a breaking change, in case there are any third-party plugins checking for it).
With the removal of all legacy code paths, `obsconfig.h` always exists and the `HAVE_OBSCONFIG_H` compile definition always gets set. As such, it's no longer necessary to check for it.
Tested with CI that all builds still compile.
Tested with `git grep` that the definition line in cmake is now the only instance remaining of `HAVE_OBSCONFIG_H`.
> UI,libobs,obs-outputs: Remove HAVE_OBSCONFIG_H ifdefs

- libobs/obs.c
Marks `obs_add_data_path` and `obs_remove_data_path` as deprecated.
Change was suggested by @Lain-B  in https://github.com/obsproject/obs-studio/pull/8179.
Successfully compiled without deprecation warnings on macOS 14.1.2.
> libobs: Mark data path modification functions as deprecated

- frontend/docks/BrowserDock.cpp
- frontend/docks/BrowserDock.hpp
This is needed as the BrowserDock is a QObject.
Without this, #11784 fails to compile
Compiled and ran OBS
> frontend: Use Q_OBJECT macro for BrowserDock

- frontend/OBSStudioAPI.cpp
- frontend/OBSStudioAPI.hpp
- frontend/api/obs-frontend-api.cpp
- frontend/api/obs-frontend-api.h
- frontend/api/obs-frontend-internal.hpp
- frontend/cmake/ui-utility.cmake
- frontend/cmake/ui-widgets.cmake
- frontend/utility/OBSCanvas.cpp
- frontend/utility/OBSCanvas.hpp
- frontend/widgets/OBSBasic.cpp
- frontend/widgets/OBSBasic.hpp
- frontend/widgets/OBSBasic_Canvases.cpp
- frontend/widgets/OBSBasic_SceneCollections.cpp
Adds saving and loading for frontend-owned canvases as well as a frontend API to create/remove/enumerate them.
In order to persist additional canvases and their scenes/sources in a way that is reasonably straightforward for API users we want the frontend to own/manage additional canvases that it may interface with.
In the future I'd also like to make transitions and the main canvas part of this abstraction.
This was tested with this fork of the vertical canvas plugin that makes use of the new APIs: https://github.com/dsaedtler/obs-vertical-canvas
> Canvases - Part Deux (Loading/Saving + Frontend API)

- plugins/nv-filters/nvidia-videofx-filter.c
- plugins/win-capture/duplicator-monitor-capture.c
Following errors occur with msvc 2022 preview and win-sdk 10.0.26100.
> nvidia-videofx-filter.c(133,9): error C2220: the following warning is treated as an error nvidia-videofx-filter.c(133,9): warning C5287: operands are different enum types 'nvvfx_fx_id' and 'nvvfx_filter_id'; use an explicit cast to silence this warning
> duplicator-monitor-capture.c(766,35): error C2220: the following warning is treated as an error duplicator-monitor-capture.c(766,35): warning C5287: operands are different enum types 'window_capture_method' and 'display_capture_method'; use an explicit cast to silence this warning
Warnings are reasonable, so change mismatched enum type.
I couldn't build without this change.
<details>
<summary>
Partial build log before this change due to 64k PR body limit.
</summary> …
> plugins: Fix warnings with Visual Studio 2022 17.14

- libobs/obs-nix.c
#12042 broke running relocatable OBS when relocated and with the original prefix not existing
Fix running OBS from the CMake rundir.
I can run OBS from the rundir on my machine.
@Penwy confirmed off-thread that it does **not** restore the issue that #12042 tried to fix
> libobs: Fix module load in relocatable scenario

- frontend/components/DelButton.hpp
- frontend/components/EditWidget.hpp
- frontend/utility/OBSProxyStyle.cpp
- frontend/utility/OBSProxyStyle.hpp
- frontend/utility/SettingsEventFilter.hpp
- frontend/utility/SurfaceEventFilter.hpp
- frontend/widgets/ColorSelect.cpp
- frontend/widgets/ColorSelect.hpp
Went through and found all QObject subclasses that didn't have a Q_OBJECT macro.
https://github.com/obsproject/obs-studio/pull/11784 still doesn't compile
It compiled
> frontend: Make sure all QObject subclasses have Q_OBJECT macro

- libobs/obs-scene.c
Improve this so others don't have to go through the same annoyances I did in figuring out what is happening here.
We have 120 lines now, no need for being clever.
Locally, nothing seems to change.
> libobs: Improve readability of scene duplication type

- libobs/util/pipe-posix.c
This fixes a regression on Linux, introduced in commit 9bc3082.
According to the POSIX specification for the exec family of commands,  "The first argument is the filename or pathname of the executable to  be executed". This was done correctly before, but the above commit  removed "sh" from the arguments, breaking the pipe function on Linux.
In OBS 31.0.3 on GNU/Linux, the os_process_pipe_create function fails silently, as the /bin/sh shipped with most Linux distros "eats" the first argument and so no program is launched.
Compiled and used for a day in production. Given that this is essentially a revert of one line back to 30.1.0, you could say it has been tested quite extensively.
OS: Arch Linux    
Used plugins: websocket, NDI, obs-ssp (my fork, this is where I discovered the issue)
- …
> libobs/util: Fix os_process_pipe_create on Linux

- plugins/obs-ffmpeg/data/locale/en-US.ini
- plugins/obs-ffmpeg/texture-amf.cpp
Introducing new default AMD encoder settings for improved perceptual quality for AVC/HEVC/AV1. These new default settings have been tuned to target stable recording on RX 5700 XT and up on the recent driver.
|                      |                     AVC                      |                     AVC                      |                     HEVC                     |                     HEVC                     |                     AV1                      |                     AV1                      |
| -------------------- | :------------------------------------------: | :------------------------------------------: | :------------------------------------------: | :------------------------------------------: | :------------------------------------------: | …
> obs-ffmpeg: New default settings for AMD encoders

- plugins/obs-ffmpeg/data/locale/en-US.ini
- plugins/obs-ffmpeg/texture-amf.cpp
Revert: obs-ffmpeg: New default settings for AMD encoders
Reverts #9352.
The commits in the PR were not cleanly structured. The second commit made a bunch of changes that were fixups for the first commit and should have landed there.
It hasn't. This is a revert.
> Revert: obs-ffmpeg: New default settings for AMD encoders

- plugins/win-capture/duplicator-monitor-capture.c
If no displays are available, numPath or numMode can be 0, which will result in a `bmalloc(0)` call and OBS will crash.
Fixes #12109 .
I have tested this by artificially setting `numPath` and `numMode` to `0`. I haven't tested this on a system with no displays.
> win-capture: Fix crash if no display is available

- frontend/OBSStudioAPI.cpp
- frontend/components/OBSAdvAudioCtrl.cpp
- frontend/components/SourceTree.cpp
- frontend/components/SourceTreeItem.cpp
- frontend/components/SourceTreeModel.cpp
- frontend/components/UIValidation.cpp
- frontend/components/VisibilityItemWidget.cpp
- frontend/dialogs/OBSBasicAdvAudio.cpp
- frontend/dialogs/OBSBasicFilters.cpp
- frontend/dialogs/OBSBasicSourceSelect.cpp
- frontend/dialogs/OBSBasicTransform.cpp
- frontend/utility/QuickTransition.cpp
- frontend/utility/ScreenshotObj.cpp
- frontend/widgets/OBSBasicPreview.cpp
- frontend/widgets/OBSBasicStats.cpp
- frontend/widgets/OBSBasicStatusBar.cpp
- frontend/widgets/OBSBasic_Preview.cpp
- frontend/widgets/OBSBasic_SceneItems.cpp
- frontend/widgets/OBSBasic_Scenes.cpp
- frontend/widgets/OBSBasic_VolControl.cpp
- frontend/widgets/OBSProjector.cpp
- frontend/wizards/AutoConfigTestPage.cpp
Using static_cast is preferred here, as it is safer to use than reinterpret_cast.
I've been reading about different types of casts, and I keep reading that you should never use reinterpret_cast unless you absolutely have to, as there is no guarantee that the casting will work unlike with static_cast.
Compiled and ran OBS to made sure nothing broke.
> frontend: Use static_cast when casting from void pointers

- shared/media-playback/media-playback/media.c
[Newly added frame width/height check](https://github.com/obsproject/obs-studio/pull/12024) crash if the frame is not given.
We can move the width/height check after other precondition checks.
I tested the master branch on my machine, and encountered the following.
My local windows 11.
> media-playback: Fix possible crash on startup

- libobs/obs-canvas.c
- libobs/obs-internal.h
- libobs/obs-source.c
Adds a function and signal for renaming sources held by a canvas (mainly scenes).
This also fixes two crashes (one at runtime, one during shutdown) that can occur when/after renaming a scene within a canvas, as previously it would use the wrong hash table (global sources) rather than the local canvas one.
Crash when renaming singular scene reported on TEB Discord, additionally discovered the second one during debugging.
Locally.
> libobs: Add obs_canvas_rename_source()

- libobs/obs-scene.c
Fall back to main canvas dimensions when attempting to get canvas size in scene sources.
Issue reported on TEB Discord.
In the case of "Studio Mode" with "Duplicate Sources" groups would not have a canvas reference, which caused them to fail to render as they could not determine the size of the canvas they exist on. Scenes themselves were fine since they would use a differnet code path that already has a fallback.
Note that the private source situation isn't great, as private sources will always use the main canvas as a size reference, since they technically don't belong to any canvas. I could not come up with a good solution for integrating canvases and private sources right now, but this change will at least prevent regressions by falling back to the old behaviour.  
I think perhaps …
> libobs: Fall back to main canvas dimensions if canvas invalid

- frontend/widgets/OBSBasic_Profiles.cpp
Ensures that path string passed into `libobs` APIs use UTF-8 encoding.
The use of the UTF-8 specific API calls in `std::filesystem` is consistent throughout the code, this instance has fallen through the cracks during review.
The directory name string passed into libobs functions needs to be converted into a 8-bit based encoding (e.g., UTF-8) to avoid mangling of characters and encoding issues particularly on Windows systems which use UTF-16 for file names.
Fixes #12101
Requires testing by affected users.
> frontend: Fix character encoding issue during profile import

- libobs/util/platform-nix.c
FreeBSD already implemented os_get_free_size.  Move the new Linux implementation into the existing not-__FreeBSD__ block.
Fixes: 935613816fd8 ("libobs/util: Update `os_get_free_size()`")
Avoid duplicate fn definition on FreeBSD
Build fix
Build-tested on FreeBSD locally (with additional changes, to come).
> libobs/util: Fix build on FreeBSD

- frontend/utility/MultitrackVideoOutput.cpp
- frontend/utility/MultitrackVideoOutput.hpp
Adds a counter to allow up to 5 reconnect failures with the "invalid key" status code before actually giving up.
Rather than fully resetting the output, we should try a few more times to wait out any server-side timeouts. If the stream key is still unavailable after 5 attempts (~50 seconds) this will fall back to re-running the full API flow to obtain a new stream key, and possibly different configuration.
Locally. Ideally could use a 48 hour test still.
> frontend: Allow 5 multitrack reconnect attempts before re-running GCC

- libobs/graphics/graphics.c
A few recently introduced graphics API functions needed for Enhanced Broadcasting support on Linux were marked as `GRAPHICS_IMPORT_OPTIONAL`. Add the proper checks in the wrapper to ensure they are safe on platforms that do not implement the underlying function.
Prevent possible crashes on platforms that do not implement the APIs marked as optional. 
Tested with local builds on Windows and Linux. 
> libobs: Add checks to some graphics API functions

- plugins/decklink/OBSVideoFrame.cpp
Update value for bmdDeckLinkFrameMetadataHDRMinDisplayMasteringLuminance from 0.00001 to 0.0001 to match the documented minimum in the DeckLink SDK Manual.
Correctness
I don't have the hardware to test this
> decklink: Fix incorrect HDR min mastering luminance value

- libobs/obs-canvas.c
- libobs/obs.h
Add obs_canvas_get_signal_handler
The canvas has signals, but no way to get the signal handler
By getting signals from the canvas
> libobs: Add obs_canvas_get_signal_handler

- frontend/cmake/os-freebsd.cmake
Add libpci to the build on FreeBSD.
As of e1d2cf705dd9 ("frontend: Support enhanced broadcasting on Linux") the FreeBSD build fails w/o libpci.
Build tested on FreeBSD.
- [x I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
> frontend: Fix build on FreeBSD

- frontend/OBSApp.cpp
- frontend/widgets/OBSQTDisplay.cpp
Using QNativeInterface allows us to move away from QPlatformNativeInterface and once all supported platforms are using Qt 6.5+.
~~Note that we still use private headers for the surface, private here stands for "unstable".~~
As of Qt 6.9 (https://github.com/qt/qtwayland/commit/32f9b4d0fc0bb749c63266ce36f8e4239b351f97), `QWidget::winId()` will provide the surface pointer as stable API.
@RytoEX had a branch a while ago and I decided to rebase it and push it as PR.
This [blog post](https://blog.david-redondo.de/qt/kde/2022/12/09/wayland-native-interface.html) about QNativeInterface.
The former method with `QPlatformNativeInterface` is an unstable API and mainly relies on function that returns `void *`, where QNativeInterface use real types.
Ran on my machine with Qt ~~6.8~~ 6.9, no issue …
> frontend: Replace completely QPlatformNativeInterface in Qt 6.9+

- libobs-opengl/gl-egl-common.c
Promote eglCreateImage failure in gl_egl_create_texture_from_pixmap() to LOG_ERROR 
Small improvement in diagnostics for an issue that is not yet understood, in case others encounter this. A similar case in gl_egl_create_dmabuf_image() uses LOG_ERROR.
Observe this error log while tracking down the underlying failure on FreeBSD.
> libobs-opengl: Promote eglCreateImage failure to LOG_ERROR

- plugins/obs-outputs/flv-mux.c
Fixes the CTS (composition timestamp/offset) calculation in OBS's native FLV muxer.
Currently the offset calculation will round down both the DTS and CTS, resulting in an off-by-one error when in the assembled PTS (DTS+CTS) timestamp.
To illustrate the problem:
```python
def get_ms_time(ts: int, den: int):
return ts * 1000 // den
timebase_den = 60 # 60 FPS: 1/60
dts = pts = 120
cts = pts - dts # == 0
dts_ms = get_ms_time(dts, timebase_den) # 2000
cts_ms = get_ms_time(cts, timebase_den) # 0
pts_ms = dts_ms + cts_ms
print(pts_ms) # prints "2000"
pts = 120
dts = pts - 1 # 1 frame of delay
cts = pts - dts # == 1
dts_ms = get_ms_time(dts, timebase_den) # 1983 (we lost 0.3̅)
cts_ms = get_ms_time(cts, timebase_den) # 16 (we lost 0.6̅)
pts_ms = dts_ms + cts_ms
print(pts_ms) # prints "1999"
``` …
> obs-outputs: Correct FLV CTS calculation

- libobs/util/windows/window-helpers.c
Adds `SDL_app` to list of generic window class names to avoid accidental matches.
Similar to the original PR that introduced this (#3121) is't to avoid accidental fallback to an app using the same underlying technology but may not be something you want to capture accidentally.
In this case a streamer was capturing a "game" that uses SDL, then next stream OBS automatically window-captured his Steam DMs because Steam also uses the generic `SDL_app` window class, leaking some private info.
Tested locally using Windows capture in WGC mode with Umineko Project and Steam.
> win-capture: Add SDL_app to list of generic classes

- CMakePresets.json
- buildspec.json
- plugins/CMakeLists.txt
This enables obs-browser and provides a compatible CEF build for Windows on ARM.
Ideally, first-party OBS builds have all standard functionality, including the browser.
Launched OBS on a Windows on ARM VM via UTM on an Apple Mac Mini M1 and ensured both `obs64.exe and `obs-browser-page.exe` indicated Arm64 architecture in Task Manager. Created both browser sources and browser docks.
> CI: Add CEF and enable obs-browser for Windows on ARM

- frontend/data/themes/Yami.obt
Fixes the padding of the top QMenuBar entries on Windows 11 (I hope)
Something in Qt changed that seems to affect the default padding of QMenuBar entries on Win11 (Likely meant to match how Windows 11 itself shows menu bars). This explicitly sets the padding on the menu items to fix it. (I hope)
It has not been as all my systems are on Windows 10 someone please help thanx
> frontend: Explicitly set titlebar item padding

- frontend/forms/OBSBasic.ui
Swaps the new preview zoom out and zoom in buttons to have zoom out on the left and zoom in on the right
This was the intended order, but I think I swapped them while testing the PR that added them and forgot to switch them back.
👁
> frontend: Swap preview zoom buttons

- libobs/util/pipe-posix.c
Pass `environ` to `posix_spawn` so that the child process can see the same environment variables.
To develop the code of OBS Studio, I configured obs-studio with `-D CMAKE_INSTALL_PREFIX=/home/user/.local` and am running with `env LD_LIBRARY_PATH=/home/user/.local/lib64: obs`.
However, now `obs-ffmpeg-mux` depends `libobs.so.30` and the shared object cannot be found with my configuration.
Before 71d963a7, we used `popen` so that the environment variables were implicitely passed to the child process.
Another motivation is that the code is shared with macOS and the man page of `posix_spawn` does not say it is ok to pass `NULL` as `envp`. Though it's silently ignored, I think it's better to fix it.
- [Mac OS X Man Pages / `posix_spawn`](https://developer.apple.com/library/archive/documentatio …
> libobs/util: Fix coprocess not having environment variables

- frontend/OBSApp.cpp
- frontend/settings/OBSBasicSettings.cpp
Depends on:
- https://github.com/obsproject/obs-studio/pull/11219
- https://github.com/obsproject/obs-browser/pull/453
- https://github.com/obsproject/obs-studio/pull/12149
Enable browser hw accel toggle under Linux
Add toggle for hwaccel support under Linux
Set the checkbox to true and the feature was enabled, and then set to false and it got disabled.
> frontend: Enable browser hw accel toggle under Linux

- frontend/forms/AutoConfigStreamPage.ui
Fix issue where multitrack video info text gets cut off
Please close this PR if the change is incorrect.
* Issue does not occur in 31.0.3  
* Issue occurs in 31.1.0 beta1 (before fix)  
* Fixed in this PR (after)
I want to resolve this issue.
Tested on Windows 11 24H2 using a local build.
**Steps to Reproduce**
1. Menu bar → Tools → Auto-Configuration Wizard
2. Click Next without changing any options
3. Click Next again without changing video settings
4. click "Use Stream Key"
> frontend/forms: Fix text cut off in multitrack video info

- frontend/data/themes/Yami.obt
Add padding variables for tabs to allow the new density option.
Tabs do not resize when using the new appearance options:
https://github.com/user-attachments/assets/9e9ed97b-86fb-45e4-a86b-89143e0c01d8
Adding padding variables it works:
https://github.com/user-attachments/assets/145878ef-4ceb-457b-a8f5-53a01de32438
Tabs to be integrated into the interface size
👁️
> frontend: Fix tab padding for the new appearance options

- frontend/widgets/OBSBasic_Scenes.cpp
Add missing operator declarations for `SignalContainer` type to fix warnings emitted by its use as a `QVariant`.
Metatype declarations should occur as soon as possible after the underlying type has been declared and can be placed in shared header files, as the macro will expand to a struct with a static getter method that attempts to return the associated meta type ID within Qt's meta type registry if it has been registered already or create a new meta type based on the type and the "stringified" identifer of the type.
To be used as a QVariant, stream operators also need to be provided as the meta type will otherwise be considered "incomplete".
Tested on macOS 15 by changing scene order via drag and drop which would have otherwise triggered the issue. …
> frontend: Fix metatype declaration for scenes and OBSBasic

- plugins/obs-ffmpeg/texture-amf.cpp
- This is a small PR that adds CQP correct support for B-frame AV1 encoding for AMD
- This PR depends on the API becoming available in the following obs-deps update: https://github.com/obsproject/obs-deps/pull/286
- `AMF_VIDEO_ENCODER_AV1_Q_INDEX_INTER_B` needs to be set for CQP rate control method to work correctly for AV1 B-frames. This property was published with the full AMF v1.4.36 release on March-6, 2025.
Fixes #12241
- Tested on Navi31, verified QIndex map with stream analyzer
> obs-ffmpeg: Add B-frame CQP support for AMD AV1 encoder

- .github/workflows/publish.yaml
CI: Update steam-upload runner to macos-15
This is the only job still using a macos-14 runner. The macos-15 runner is now GA and we've used it everywhere else.
It hasn't, but we use macos-15 everywhere else just fine.
- CI
> CI: Update steam-upload runner to macos-15

- frontend/OBSStudioAPI.cpp
- frontend/widgets/OBSBasic_Docks.cpp
When no role is set, the default is QAction::TextHeuristicRole. This means that the text of the item gets fuzzy-matched in Qt against a set of possible strings that could indicate that the menu should be in the application menu on macOS.
For us this meant however that on some languages, the translation of "WebSocket Server Settings" would begin with "Config", and as such the related QAction replaces our "Settings" action for the PreferencesRole, and clicking "Preferences..." in the application menu would open the websocket settings. It should probably be considered a bug in Qt that implicit matches via TextHeuristicRole can overwrite ones that are explicitly set (like our PreferencesRole). However we explicitly set our roles ourselves anyways and there is no scenario where a  plugin …
> frontend: Set Frontend-API QActions role to NoRole

- .github/workflows/build-project.yaml
- .github/workflows/publish.yaml
- UI/api-interface.cpp
- UI/window-basic-main-browser.cpp
- UI/window-basic-main.cpp
- UI/window-basic-preview.cpp
- build-aux/modules/40-luajit.json
- buildspec.json
- deps/json11/json11.cpp
- libobs/callback/decl.c
- libobs/obs-config.h
- libobs/obs-scene.c
- libobs/util/pipe-posix.c
- libobs/util/threading-posix.c
- plugins/linux-v4l2/v4l2-output.c
- plugins/mac-capture/mac-sck-audio-capture.m
- shared/media-playback/media-playback/media.c
Picks:
* https://github.com/obsproject/obs-studio/pull/11495
* https://github.com/obsproject/obs-studio/pull/11963
* https://github.com/obsproject/obs-studio/pull/12016
* https://github.com/obsproject/obs-studio/pull/12056
* https://github.com/obsproject/obs-studio/pull/12065
* https://github.com/obsproject/obs-studio/pull/11922
* https://github.com/obsproject/obs-studio/pull/12024
* https://github.com/obsproject/obs-studio/pull/11906
* https://github.com/obsproject/obs-studio/pull/12035
* https://github.com/obsproject/obs-studio/pull/11985
* https://github.com/obsproject/obs-studio/pull/12021
* https://github.com/obsproject/obs-studio/pull/12049
* https://github.com/obsproject/obs-studio/pull/12094
* https://github.com/obsproject/obs-studio/pull/12187
* …
> Cherry picks

- frontend/data/themes/Yami.obt
Adds a minimum height for QList items.
> [!NOTE]
> This PR is only really intended for 31.1 and would be reverted in a later release. If it's preferred/easier it should only be merged into the release branch as a pre-emptive hotfix and never included in master.
A Fix in #11555 means that our SourceTreeItemDelegates now return a proper sizeHint and the source list is styled with that in consideration.
Unfortunately a large number of plugins have copied our delegate code, and now do not display properly due to returning a height of 0
This PR adds a minimum height as a temporary solution so that those lists remain useable while intentionally using a value that does not look correct, to make it clear to plugin authors a proper fix is still needed on their end.
👁 …
> frontend: Enforce minimum height for QList items

- buildspec.json
CEF 127 lacks CEF_OSR_EXTRA_INFO, which can cause resizing a hardware-acclerated browser source to crash its GPU renderer process. Use a rebuilt CEF 127 with CEF_OSR_EXTRA_INFO backported from CEF 133+.
Also, update obs-browser to be able to use CEF_OSR_EXTRA_INFO. See:
* https://github.com/obsproject/obs-browser/pull/491
Want to make sure browser hardware acceleration works on Linux.
Tested on https://github.com/obsproject/obs-browser/pull/491.
> CI: Fix Linux browser hardware acceleration

- plugins/linux-v4l2/v4l2-decoder.c
When capturing video from UVC devices using H.264 at higher resolutions (e.g. 2560x1440 or higher), video capture frequently stops unexpectedly. This patch makes a minor adjustment to the decoder logic in `v4l2_decode_frame()` to continue capturing instead of stopping on `AVERROR(EAGAIN)`.
Currently, the `v4l2_decode_frame()` function treats all negative return values from `avcodec_receive_frame()` as fatal errors. However, `AVERROR(EAGAIN)` is a common return code that simply indicates that more data is needed before a frame can be decoded. Treating this as an error causes the video capture to stop unnecessarily, especially with high-resolution formats like H.264.
This change allows the decoder to continue feeding data to the codec even after receiving `AVERROR(EAGAIN)`, ensuring a more …
> linux-v4l2: Avoid stopping capture on AVERROR(EAGAIN)

- frontend/data/themes/Yami.obt
Fixes sizing of scrollbars in the Settings window.
Fixes #12384 
Changes to the layout margins and spacing in the settings window caused scrollbars to get scrunched up a bit. This fixes that so they appear as they did before.
👀
> frontend: Fix settings scrollbar size

- plugins/linux-pipewire/CMakeLists.txt
- plugins/linux-pipewire/pipewire.c
PipeWire format renegotiation runs in parallel with video rendering.
When the stream format is renegotiated, PipeWire removes the existing buffers and closes the syncobj file descriptors. At the same time, the video rendering thread may try to import the (already closed) syncobj acquire fd, and hang on waiting for the fence to become available.
This is not a problem for the dmabuf fd because it's imported into a texture right away, which doesn't disappear when PipeWire closes the fd.
The first commit adds duping to the syncobj fds so that they too remain open as long as the rendering thread may access them.
The second commit fixes a separate issue with explicit sync.
Since video rendering happens on a separate thread from PipeWire buffer ingestion, it may happen that two buffers are …
> linux-pipewire: Dup syncobj fds to prevent use-after-free hang & ensure release point is always signaled

- .github/workflows/analyze-project.yaml
Ensures that merged SARIF report files generated via `clang-analyze` use a single `run` object only.
GitHub introduced a policy change on 2024-05-06 which deprecated support for SARIF files that contain multiple runs for the same tool.
Tested on local fork via workflow dispatch.
> CI: Fix failures of analyze workflow runs due to GitHub policy change

- plugins/linux-pipewire/pipewire.c
- plugins/linux-pipewire/screencast-portal.c
Fixes #12412
This reverts commit 4dfd0b31e4988601ffab045a495ba319e45e8c16.
Also adds a FIXME comment.
#11207 generated issues on SDR users.
And the PR itself tries to handle color space the wrong way, the portal implementation should provide a node with PipeWire colorimetry info in its formats for OBS Studio to handle textures correctly.
> Revert "linux-pipewire: Fix 10- and 16-bit captures"

- libobs/obs.c
This fixes a change in #11605 that breaks Decklink video outputs. get_mix_for_video() returns NULL for those outputs, causing start_raw_video() to return before connecting the output.
Fixes #12366.
Decklink outputs do not output video. 
Verified that decklink video output works again by starting a decklink output.
Verified that the problem that #11605 fixes was still fixed by following the reproduction steps in #11329.
> libobs: Start video output even if there is no mix to fix DeckLink outputs

- shared/media-playback/media-playback/media.c
Move channels value assignment below mp_media_can_play_frame check.
Channels value was being assigned before mp_media_can_play_frame check occurred resulting in a null pointer de-reference exception. This fixes media source crashing issue - fixes #11851.  
Tested by following recreation steps using attached file and observing OBS crash. Made code change and re-ran test following same recreation steps. No crash was observed after fix.
OS Version: Windows 11
Channels variable was not used in function before mp_media_can_play_frame check, moving to after the check should not affect any other areas of code.
> media-playback: Fix null pointer dereference

- plugins/obs-outputs/mp4-mux.c
Fixes an issue where the version of the `tkhd` and `mvhd` boxes was not correctly set when using 64-bit durations/timestamps.
The larger fields are used when the duration exceeds `UINT32_MAX`, which in practice would happen around 1193 hours of continuous recording (OBS uses a millisecond timescale for the presentation).
Still works normally, overflow condition not specifically tested.
> obs-outputs: Fix tkhd/mvhd box version with 64-bit timestamps

- plugins/obs-transitions/transition-stinger.c
Fix stinger showing count for update during transition
When a transition is updated while a transition is running the `obs_source_remove_active_child` was called on an other source than `obs_source_add_active_child`
the `show_refs` counter gets to -1, because `obs_source_deactivate` does only check if it is above 0 for the source it is called on, not for the tree items in `hide_tree`
On windows 11 in combination with move transition having matched items doing a stinger transition
> obs-transitions: Fix stinger showing count for update during transition

- plugins/obs-outputs/mp4-output.c
Makes chapter markers frame-accurate[^1] by using packet timing callback introduced for BPM.
[^1]: Frame-reordering (b-frames) probably result in there still being some inaccuracy, but the amount is going to be much lower compared to before as other - larger - sources of delay (lookahead/audio buffering) are accounted for.
When there is a significant delay between a frame being rendered and submitted to the output, e.g. due to lookahead or audio buffering, the chapter markers would previously be too early in the file as there was no way to determine the packet's original rendering time. This change fixes that.
Recorded a video at 30 fps with `rc-lookahead=30`, confirmed chapter markers are now inserted with a 1-second delay at the correct frame.
- Tweak (non-breaking change to improve …
> obs-outputs: Use packet time callback for frame-accurate chapter markers

- libobs/obs-display.c
- plugins/mac-avcapture/plugin-main.m
- plugins/mac-capture/mac-display-capture.m
- plugins/mac-capture/mac-sck-video-capture.m
- plugins/mac-syphon/syphon.m
- plugins/obs-filters/data/sharpness.effect
This PR contains changes required to the existing codebase for the Metal renderer to function properly:
* It disables the clear workaround enabled unconditionally on macOS and instead uses the _linear gamma_ variant of the clear color to match the way `glClear` is apparently implemented in the Metal-based OpenGL driver for Apple Silicon Macs (which also matches how a clear has to be simulated in Metal proper)
* It adds a conditional branch to any plugin that uses the `OBS_EFFECT_DEFAULT_RECT` (required for OpenGL on macOS) to use it _explicitly_ only when OpenGL is selected as the current renderer
* Changes a ternary expression in the `sharpness` shader to explicitly convert a vector of booleans into a scalar boolean value, as the Metal Shader Language does not allow implicit type changes …
> libobs-metal: Add preparations for Metal renderer to current codebase

- libobs-opengl/gl-cocoa.m
Adds more error checking to macOS-specific code, particularly for swap chain size updates and also cleans up parts of the code:
* Swapchain-related code has been updated to use more expressive variable names following common ObjC coding practices
* Most data used by the async block handling a projector size update now operates on copies of the data instead of relying on nested data inside a heap object
* More detailed error reporting has been added to the async block for projector size updates
* Existing constants for FourCCs used by `IOSurface`s are used instead of encoding them manually
These changes attempt to either fix or at the very least provide more detailed error messages for issues related to projectors crashing OBS when windows are moved across screens or resized, but also for …
> libobs-opengl: Improve error handling of swap chain code for macOS and clean up platform-specific code

- libobs/util/bmem.c
- libobs/util/platform-nix.c
- libobs/util/platform-windows.c
- libobs/util/platform.h
Per discussion with @notr1ch , add an `os_oom()` copy of `os_breakpoint()` to make crash stacks clearer and to make troubleshooting easier.
When OBS crashes during `bmalloc()` or `brealloc()` calls using `os_breakpoint()` in Release/RelWithDebInfo builds, we do not get the logged line that is supposed to differentiate the crash types:
* bmalloc: Allocating 0 bytes is broken behavior, please fix your code!
* Out of memory while trying to allocate %lu bytes
* brealloc: Allocating 0 bytes is broken behavior, please fix your code!
* Out of memory while trying to allocate %lu bytes
@notr1ch suggested just duplicating `os_breakpoint()` into "nicer" variants, such as `os_oom()`.
Manually tested a call to `bmalloc(0)` and manually forced the null pointer check in `bmalloc()` to fail.
- Tweak …
> libobs: Add os_oom() to clarify out of memory crashes

- libobs/obs-hevc.c
- plugins/obs-ffmpeg/texture-amf.cpp
- plugins/obs-nvenc/nvenc-internal.h
- plugins/obs-nvenc/nvenc.c
Improves the HEVC packet drop priority determination by differentiating between reference (typically P) and non-reference (typically B) frames.
Also fixes AMF P-frame priority to bring it in line with other encoders and adds priority assignment to NVENC.
Currently all non-I frames are assigned the "high" priority, meaning that the frame dropping code will have to start dropping both reference and non-reference pictures as soon as congestion is hit. This can lead to decoding errors due to missing reference pictures.
With this change non-reference pictures are assigned a lower priority so they can be dropped before reference pictures to avoid decoding errors.
Streamed locally with drop testing enabled and dropped some frames.
Also compared output of the new code with the encoder-based …
> Fix HEVC packet priority issues

- libobs/obs-audio.c
- libobs/obs-internal.h
- libobs/obs-scene.c
- libobs/obs-scene.h
- libobs/obs-source-transition.c
- libobs/obs-source.c
This is split from the original PR https://github.com/obsproject/obs-studio/pull/12175 to  facilitate the reviewing.
PR #12175 fixed two audio bugs but the fixes are conceptually different.
The current bug consists in an increased audio level when a source is duplicated in a scene or through a nested scene.
The bug implies that the same audio samples will be mixed several times resulting in a coherent addition. For duplicate sources
this implies a doubling of the audio amplitude or a constant +6 dBFS level increase.
The bug was mostly fixed in commits 8a38e33 [1] and 72924ac [2]. But it was fixed at the scene level and this left an edge case where a nested scene has a Show/Hide transition. It implies an increase of +6 dBFS for any duplicated source.
An example of valid use case is a Media …
> libobs: Fix audio duplication bug

- frontend/OBSStudioAPI.cpp
- frontend/widgets/OBSBasic.cpp
- frontend/widgets/OBSBasic.hpp
- frontend/widgets/OBSBasic_SceneCollections.cpp
- frontend/widgets/OBSBasic_StudioMode.cpp
- frontend/widgets/OBSBasic_Transitions.cpp
Began to split transitions and transition duration storage from the UI.
Also makes the frontend code rely more on transitions UUID even if those are not preserved between sessions for now.
While this PR remove any kind of reliance on *index* of a transition, it does **not** overhaul things to rely only on UUID so there is still reliance on the transition name as an identifier. Same for retaining which transition was inserted last.
After multiple tries, I finally managed to separated the transitions data from this combobox, now it needs reviews and testings…
The awaited sequel of #7278, but it's the prequel of the expected sequel.
Please tests
> frontend: Transitions (dock) separation part 1

- frontend/oauth/RestreamAuth.cpp
- frontend/oauth/TwitchAuth.cpp
- frontend/oauth/YoutubeAuth.cpp
This reverts commit 3dcf68f8ed500a23154f502a85caa109afd04d81.
The bug that this was meant to work around was most likely QTBUG-102718, which was fixed in Qt 6.2.5, 6.3.1, and 6.4.0. The minimum version of Qt we currently support is Qt 6.4.2 because it is what is available on Ubuntu 24.04. Thus, we should not need this workaround now.
This should restore service dock restoration if the main window is "not visible but maximized". See:
* https://github.com/obsproject/obs-studio/pull/8135
* https://github.com/obsproject/obs-studio/issues/7348
https://bugreports.qt.io/browse/QTBUG-102718
Want to get rid of code targeting Qt versions older than Qt 6.4.2.
It hasn't yet. Testing appreciated.
> Revert "UI: Work around Qt dock restore crash"

- frontend/dialogs/LogUploadDialog.cpp
Removes an unneeded `.arg` call on the log upload text.
The string doesn't have (or need) any arguments, the text put into the `.arg` call is in the button.
Wanted to upload a log and got a warning in the console:
```
warning: QString::arg: Argument missing: "Please read the <a href='https://obsproject.com/privacy-policy'>Privacy Policy</a> and its section regarding file uploads before uploading any files.", "Upload"
```
Uploaded a log. Dialog still looks correct:
> frontend: Remove unneeded argument from log upload privacy notice

- frontend/plugin-manager/PluginManager.cpp
Issue found testing 32.0.0 Beta 1.  Current code isn't catching a parse error exception if an invalid config file is loaded by the plugin manager. This change wraps the plugin manager config json parse call with a try/catch, and handles invalid config files by creating a new config file, and logs an error that the existing config file is invalid.
Plugin manager initialization code has been modified to wrap the `nlohmann::json` parse function with a `try/catch` to catch any parsing errors that might occur if the plugin manager config file is corrupted or empty. If an invalid config file is found, a new default config file is created and used, and an error is logged to the OBS log.
Currently, if the plugin manager config file is corrupted or empty, OBS will crash on load. This change fixes …
> frontend: Fix plugin manager config loading crash

- plugins/mac-avcapture/plugin-main.m
- plugins/mac-capture/mac-display-capture.m
- plugins/mac-capture/mac-sck-video-capture.m
- plugins/mac-syphon/syphon.m
Ensures that calls to `gs_get_device_type` take place after the current thread has acquired the graphics context.
PR #12487 added explicit checks for the current renderer type in preparation for the Metal renderer. It was assumed that checking for a static value provided by a preprocessor `define` do not require the graphics context, the getter function does indeed require it.
Thus the checks (originally part of the Metal renderer PR) have been re-added as part of this PR.
Tested with OpenGL renderer on macOS. Affected source types like screen capture, video device capture, and display capture render as expected.
> plugins: Ensure that graphics device type checks use graphics context

- frontend/plugin-manager/PluginManager.cpp
- libobs/obs-encoder.h
- libobs/obs-module.c
- libobs/obs-module.h
- libobs/obs-output.h
- libobs/obs-service.h
- libobs/obs-source.h
Removes the `module` pointer from the `obs_*_info` structs, as it's unused (and was not even implemented for anything except `obs_source_info`). Generally `obs_*_info` are only* set by the caller of `obs_register_*`, not internally, so having the module there wouldn't make much sense (which is probably why another route was chosen, and this was just forgotten).
(* with the exception of `unversioned_id` for `obs_source_info`)
Sets the module for outputs that are registered, this seemed to have been forgotten.
Changes `obs_source_get_module` calls in the frontend to the calls that were probably intended originally.
cc @FiniteSingularity 
I was looking at the [32.0 public API changes](https://github.com/obsproject/obs-studio/compare/31.1.2...gxalpha:obs-studio:32.0-api-change-review) and got …
> libobs,frontend: Plugin manager API cleanup, minor fixes

- plugins/nv-filters/nvidia-audiofx-filter.c
I forgot to guard NvAFX_UninitializeLogger() called in Destroy function.
This fixes a crash for people using an old sdk which does not have the function.
Fixing a crash is good.
Such a crash was reported in Support and by @notr1ch 
Untested but the fix is obvious.
> nv-filters: Guard function introduced in sdk >= 1.6.0

- cmake/linux/helpers.cmake
Never had time to make it for 32 (and I don't plan to push for it during the beta), so plan for 33.
This PR removes any tweak made to soversion to avoid ABI break on Linux before enforcing that major version do a break.
We need to break on ABI break even if dlopen on Linux would find missing symbols and properly fail.
Untested, I need CI builds.
> Remove Linux soversion workarounds

- libobs/CMakeLists.txt
- libobs/obs-module.c
- libobs/util/platform-nix.c
- libobs/util/platform-windows.c
Remove the Qt 5 module checks.
The Qt 5 module checks were added in OBS Studio 28 about three years ago to help smooth the transition from Qt 5 to Qt 6. These checks have served their purpose, and we had previously decided to remove them for OBS Studio 32, particularly because they slow down initialization.
Alternatively, we could split this to only handle the removal in `platform-nix` and deal with `platform-windows` separately, and/or we could do manual reverts instead of `git reverts`.
It compiled on my fork's CI:
https://github.com/RytoEX/obs-studio/actions/runs/17448529710
I haven't done any runtime tests.
> Remove Qt 5 module checks

- frontend/utility/BasicOutputHandler.cpp
This ensures that there is a set config URL before attempting to start a multitrack stream.
Fixes #11079
Checked multitrack still worked, and that the bug wasn't present.
> frontend: Don't attempt multitrack without config url

- libobs/util/platform-windows.c
Make `os_oom()` specifically raise an out of memory exception instead of just calling `_debugbreak()`.
The previous attempt to clarify an out of memory exception/crash resulted in the compiler optimizing os_breakpoint() and os_oom() into the same result, which meant that crash stacks in the wild were still not specific enough to be helpful. Forcefully differentiating the functions in Release configuration by having os_breakpoint() only call __debugbreak() and having os_oom() call RaiseException() should give us clearer crash stacks.
Amends 94a736f1795c21afd0baa10c0692543b70c17dc5.
Want clearer crash stacks to differentiate memory allocation failures.
Tested locally. The crash stack still seems to optimize out in a different way, where the crash stack omits the bmalloc/brealloc calls and …
> libobs: Raise out of memory exception manually when out of memory

- frontend/widgets/OBSBasic.cpp
- plugins/obs-ffmpeg/obs-ffmpeg-av1.c
- plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
- plugins/obs-ffmpeg/texture-amf.cpp
- plugins/obs-qsv11/obs-qsv11.c
- plugins/obs-x264/obs-x264.c
Increases the default bitrate to 10000kbps (10mbps). For encoders that have a different `bitrate` / `max_bitrate`, use 8000 / 10000.
The default of 2500 kbps was chosen 10 years ago and times have changed. Logs and forums posts show that a lot of users who use OBS for recording don't touch the default settings and end up with a 2.5 mbps recording which looks terrible.
With service bitrate enforcement, this will be automatically capped to the maximum bitrate for streaming services, so the only time this should result in a problem is if the user's upload speed is the limiting factor, hopefully rarer these days with increasing internet speeds.
Ran OBS.
> frontend, plugins: Set default bitrate to 6000 kbps

- .github/scripts/utils.zsh/setup_ccache
- cmake/macos/resources/ccache-launcher-c.in
- cmake/macos/resources/ccache-launcher-cxx.in
Removes the enforced use of a second preprocessor call by Ccache on macOS entirely and guards it behind a version check in the build script used by macOS and Linux.
Ccache 4.12 [removed support](https://ccache.dev/releasenotes.html#_removed_features) do enable or disable the use of a second preprocessor call entirely, mainly to remove the ability to _disable_ it.
The project always enabled it explicitly, which is not necessary now, but as the flag/configuration parameter is entirely removed, Ccache will report the use of an unknown configuration parameter and break project configuration on CI.
Needs to be tested via CI runs.
> CI: Fix configuration issue with Ccache version 4.12 and above

- .github/workflows/build-project.yaml
- .github/workflows/publish.yaml
Upstream made some changes in the images which require an update
https://github.com/flatpak/flatpak-github-actions/pull/231.
Was asked to make the update by Flathub folks.
CI
> CI: Update Flatpak action

- frontend/components/SourceTreeItem.cpp
Fix Run-Time Check Failure `#2` - Stack around the variable `snapEnabled` was corrupted.
SPI_GETSNAPTODEFBUTTON should use BOOL, not bool. see https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfow
I have test use my complute.
> frontend: Fix runtime check failure issue with SPI_GETSNAPTODEFBUTTON
